QElectroTech: QetGraphicsHandlerItem Class Reference
QetGraphicsHandlerItem Class Reference
The QetGraphicsHandlerItem class This graphics item represents a point, destined to be used as an handler, for modifie the geometrie of a another graphics item (like shapes). The graphics item to be modified, must call "installSceneEventFilter" of this item with itself for argument,. The ghraphics item to be modified, need to reimplement "sceneEventFilter" for create the modification behavior.
#include <qetgraphicshandleritem.h>
Public Types
enum { Type = UserType + 1200 }
Public Member Functions
QetGraphicsHandlerItem (qreal size=10)
QetGraphicsHandlerItem::QetGraphicsHandlerItem.
QRectF boundingRect () const override
QetGraphicsHandlerItem::boundingRect.
int type () const override
void setColor (QColor color)
QetGraphicsHandlerItem::setColor.
Static Public Member Functions
static QVector< QetGraphicsHandlerItem * > handlerForPoint (const QVector< QPointF > &points, int size=10)
QetGraphicsHandlerItem::handlerForPoint.
Protected Member Functions
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
QetGraphicsHandlerItem::paint.
Private Attributes
QRectF m_handler_rect
QRectF m_br
qreal m_size
QColor m_color
QPen m_pen
Detailed Description
The QetGraphicsHandlerItem class This graphics item represents a point, destined to be used as an handler, for modifie the geometrie of a another graphics item (like shapes). The graphics item to be modified, must call "installSceneEventFilter" of this item with itself for argument,. The ghraphics item to be modified, need to reimplement "sceneEventFilter" for create the modification behavior.
Definition at line 36 of file qetgraphicshandleritem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 42 of file qetgraphicshandleritem.h.
Constructor & Destructor Documentation
QetGraphicsHandlerItem()
QetGraphicsHandlerItem::QetGraphicsHandlerItem (qreal size = 10)
QetGraphicsHandlerItem::QetGraphicsHandlerItem.
Parameters
size : the size of the handler
Definition at line 27 of file qetgraphicshandleritem.cpp.
References m_br, m_handler_rect, and m_size.
Referenced by handlerForPoint().
Member Function Documentation
boundingRect()
QRectF QetGraphicsHandlerItem::boundingRect () const override
QetGraphicsHandlerItem::boundingRect.
Returns
Definition at line 40 of file qetgraphicshandleritem.cpp.
References m_br.
handlerForPoint()
QVector< QetGraphicsHandlerItem * > QetGraphicsHandlerItem::handlerForPoint (const QVector< QPointF > & points, int size = 10) static
QetGraphicsHandlerItem::handlerForPoint.
Parameters
points
size
Returns
A list of handler with pos at point
Definition at line 87 of file qetgraphicshandleritem.cpp.
References QetGraphicsHandlerItem().
Referenced by PartEllipse::addHandler(), PartArc::addHandler(), PartRectangle::addHandler(), ElementPrimitiveDecorator::addHandler(), PartPolygon::addHandler(), PartLine::addHandler(), QetShapeItem::addHandler(), and Conductor::addHandler().
paint()
void QetGraphicsHandlerItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override protected
QetGraphicsHandlerItem::paint.
Parameters
painter
option
widget
Definition at line 60 of file qetgraphicshandleritem.cpp.
References m_color, and m_handler_rect.
setColor()
void QetGraphicsHandlerItem::setColor (QColor color)
QetGraphicsHandlerItem::setColor.
Parameters
color : set the color of the handler
Definition at line 48 of file qetgraphicshandleritem.cpp.
References m_color.
Referenced by Conductor::handlerMousePressEvent(), and QetGraphicsTableItem::setUpHandler().
type()
int QetGraphicsHandlerItem::type () const inline override
Definition at line 43 of file qetgraphicshandleritem.h.
References Type.
Member Data Documentation
m_br
QRectF QetGraphicsHandlerItem::m_br private
Definition at line 54 of file qetgraphicshandleritem.h.
Referenced by boundingRect(), and QetGraphicsHandlerItem().
m_color
QColor QetGraphicsHandlerItem::m_color private
Definition at line 56 of file qetgraphicshandleritem.h.
Referenced by paint(), and setColor().
m_handler_rect
QRectF QetGraphicsHandlerItem::m_handler_rect private
Definition at line 53 of file qetgraphicshandleritem.h.
Referenced by paint(), and QetGraphicsHandlerItem().
m_pen
QPen QetGraphicsHandlerItem::m_pen private
Definition at line 57 of file qetgraphicshandleritem.h.
m_size
qreal QetGraphicsHandlerItem::m_size private
Definition at line 55 of file qetgraphicshandleritem.h.
Referenced by QetGraphicsHandlerItem().
The documentation for this class was generated from the following files:
qetgraphicshandleritem.h
qetgraphicshandleritem.cpp