QElectroTech: NumerotationContextCommands Class Reference
NumerotationContextCommands Class Reference
The NumerotationContextCommands class this class provide methods to handle content of NumerotationContext.
#include <numerotationcontextcommands.h>
Public Member Functions
NumerotationContextCommands (const NumerotationContext &, Diagram *=nullptr)
Constructor.
~NumerotationContextCommands ()
Destructor.
NumerotationContext next ()
NumerotationContextCommands::next.
NumerotationContext previous ()
NumerotationContextCommands::previous.
QString toRepresentedString ()
NumerotationContextCommands::toFinalString.
Private Member Functions
void setNumStrategy (const QString &)
NumerotationContextCommands::setNumStrategy apply the good strategy relative to str.
Private Attributes
Diagram * diagram_
NumerotationContext context_
NumStrategy * strategy_
Detailed Description
The NumerotationContextCommands class this class provide methods to handle content of NumerotationContext.
Definition at line 30 of file numerotationcontextcommands.h.
Constructor & Destructor Documentation
NumerotationContextCommands()
NumerotationContextCommands::NumerotationContextCommands (const NumerotationContext & nc, Diagram * d = nullptr)
Constructor.
Definition at line 24 of file numerotationcontextcommands.cpp.
~NumerotationContextCommands()
NumerotationContextCommands::~NumerotationContextCommands ()
Destructor.
Definition at line 33 of file numerotationcontextcommands.cpp.
References strategy_.
Member Function Documentation
next()
NumerotationContext NumerotationContextCommands::next ()
NumerotationContextCommands::next.
Returns
the next numerotation context
Definition at line 41 of file numerotationcontextcommands.cpp.
References context_, NumerotationContext::itemAt(), setNumStrategy(), NumerotationContext::size(), and strategy_.
Referenced by QETProject::autoFolioNumberingSelectedFolios(), ConductorAutoNumerotation::newProperties(), ConductorAutoNumerotation::numerateNewConductor(), SelectAutonumW::on_m_next_pb_clicked(), Element::setUpFormula(), and QETProject::updateDiagramsFolioData().
previous()
NumerotationContext NumerotationContextCommands::previous ()
NumerotationContextCommands::previous.
Returns
the previous numerotation context
Definition at line 56 of file numerotationcontextcommands.cpp.
References context_, NumerotationContext::itemAt(), setNumStrategy(), NumerotationContext::size(), and strategy_.
Referenced by SelectAutonumW::on_m_previous_pb_clicked().
setNumStrategy()
void NumerotationContextCommands::setNumStrategy (const QString & str) private
NumerotationContextCommands::setNumStrategy apply the good strategy relative to str.
Definition at line 89 of file numerotationcontextcommands.cpp.
References diagram_, and strategy_.
Referenced by next(), previous(), and toRepresentedString().
toRepresentedString()
QString NumerotationContextCommands::toRepresentedString ()
NumerotationContextCommands::toFinalString.
Returns
the string represented by the numerotation context
Definition at line 71 of file numerotationcontextcommands.cpp.
References context_, diagram_, NumerotationContext::itemAt(), setNumStrategy(), NumerotationContext::size(), and strategy_.
Referenced by QETProject::autoFolioNumberingSelectedFolios(), and QETProject::updateDiagramsFolioData().
Member Data Documentation
context_
NumerotationContext NumerotationContextCommands::context_ private
Definition at line 43 of file numerotationcontextcommands.h.
Referenced by next(), previous(), and toRepresentedString().
diagram_
Diagram* NumerotationContextCommands::diagram_ private
Definition at line 42 of file numerotationcontextcommands.h.
Referenced by setNumStrategy(), and toRepresentedString().
strategy_
NumStrategy* NumerotationContextCommands::strategy_ private
Definition at line 44 of file numerotationcontextcommands.h.
Referenced by next(), previous(), setNumStrategy(), toRepresentedString(), and ~NumerotationContextCommands().
The documentation for this class was generated from the following files:
numerotationcontextcommands.h
numerotationcontextcommands.cpp