QElectroTech: PrintConfigPage Class Reference
PrintConfigPage Class Reference
The PrintConfigPage class This configuration page enables users to set default printing options.
#include <configpages.h>
Public Member Functions
PrintConfigPage (QWidget *=nullptr)
~PrintConfigPage () override
Destructeur.
void applyConf () override
PrintConfigPage::applyConf Apply the config of this page.
QString title () const override
QIcon icon () const override
Public Member Functions inherited from ConfigPage
ConfigPage (QWidget *parent)
~ConfigPage () override
Destructor.
Public Attributes
ExportPropertiesWidget * epw
Private Member Functions
PrintConfigPage (const PrintConfigPage &)
Detailed Description
The PrintConfigPage class This configuration page enables users to set default printing options.
Definition at line 103 of file configpages.h.
Constructor & Destructor Documentation
PrintConfigPage() [1/2]
PrintConfigPage::PrintConfigPage (QWidget * parent = nullptr)
Constructeur
Parameters
parent QWidget parent
Definition at line 289 of file configpages.cpp.
References ExportProperties::defaultPrintProperties(), epw, and title().
~PrintConfigPage()
PrintConfigPage::~PrintConfigPage () override
Destructeur.
Definition at line 311 of file configpages.cpp.
PrintConfigPage() [2/2]
PrintConfigPage::PrintConfigPage (const PrintConfigPage &) private
Member Function Documentation
applyConf()
void PrintConfigPage::applyConf () override virtual
PrintConfigPage::applyConf Apply the config of this page.
Implements ConfigPage.
Definition at line 318 of file configpages.cpp.
References epw.
icon()
QIcon PrintConfigPage::icon () const override virtual
Returns
l'icone de cette page
Implements ConfigPage.
Definition at line 332 of file configpages.cpp.
References QET::Icons::Printer.
title()
QString PrintConfigPage::title () const override virtual
Returns
le titre de cette page
Implements ConfigPage.
Definition at line 337 of file configpages.cpp.
References QET::Icons::tr.
Referenced by PrintConfigPage().
Member Data Documentation
epw
ExportPropertiesWidget* PrintConfigPage::epw
Definition at line 120 of file configpages.h.
Referenced by applyConf(), and PrintConfigPage().
The documentation for this class was generated from the following files:
configpages.h
configpages.cpp