QElectroTech: LinkReportPotentialSelector Class Reference
LinkReportPotentialSelector Class Reference
The LinkReportPotentialSelector class Use for get the conductor propertie when two potentials is linked with a folio report.
Public Member Functions
LinkReportPotentialSelector (Element *report)
~LinkReportPotentialSelector () override
bool isValid () const override
Public Member Functions inherited from AbstractPotentialSelector
AbstractPotentialSelector ()
virtual ~AbstractPotentialSelector ()
Private Attributes
bool m_is_valid
Additional Inherited Members
Public Attributes inherited from AbstractPotentialSelector
autonum::sequentialNumbers m_seq_num_1
autonum::sequentialNumbers m_seq_num_2
int m_conductor_number_1
int m_conductor_number_2
QList< ConductorProperties > m_properties_list_1
QList< ConductorProperties > m_properties_list_2
QList< Conductor * > m_conductors_list_1
QList< Conductor * > m_conductors_list_2
Detailed Description
The LinkReportPotentialSelector class Use for get the conductor propertie when two potentials is linked with a folio report.
Definition at line 141 of file potentialselectordialog.cpp.
Constructor & Destructor Documentation
LinkReportPotentialSelector()
LinkReportPotentialSelector::LinkReportPotentialSelector (Element * report) inline
Definition at line 144 of file potentialselectordialog.cpp.
References Element::AllReport, Element::conductors(), Element::isFree(), Element::linkedElements(), Element::linkToElement(), Element::linkType(), AbstractPotentialSelector::m_conductor_number_1, AbstractPotentialSelector::m_conductor_number_2, AbstractPotentialSelector::m_conductors_list_1, AbstractPotentialSelector::m_conductors_list_2, m_is_valid, AbstractPotentialSelector::m_properties_list_1, AbstractPotentialSelector::m_properties_list_2, AbstractPotentialSelector::m_seq_num_1, AbstractPotentialSelector::m_seq_num_2, Conductor::properties, and Element::unlinkAllElements().
~LinkReportPotentialSelector()
LinkReportPotentialSelector::~LinkReportPotentialSelector () inline override
Definition at line 176 of file potentialselectordialog.cpp.
Member Function Documentation
isValid()
bool LinkReportPotentialSelector::isValid () const inline override virtual
Implements AbstractPotentialSelector.
Definition at line 178 of file potentialselectordialog.cpp.
References m_is_valid.
Member Data Documentation
m_is_valid
bool LinkReportPotentialSelector::m_is_valid private
Definition at line 181 of file potentialselectordialog.cpp.
Referenced by isValid(), and LinkReportPotentialSelector().
The documentation for this class was generated from the following file:
potentialselectordialog.cpp