QElectroTech: ReplaceFolioDialog Class Reference
ReplaceFolioDialog Class Reference
#include <replacefoliowidget.h>
Public Member Functions
ReplaceFolioDialog (QWidget *parent=nullptr)
~ReplaceFolioDialog ()
TitleBlockProperties titleBlockProperties () const
ReplaceFolioDialog::titleBlockProperties.
void setTitleBlockProperties (const TitleBlockProperties &properties)
ReplaceFolioDialog::setTitleBlockProperties.
Private Attributes
ReplaceFolioWidget * m_widget = nullptr
QDialogButtonBox * m_button_box = nullptr
Detailed Description
Definition at line 60 of file replacefoliowidget.h.
Constructor & Destructor Documentation
ReplaceFolioDialog()
ReplaceFolioDialog::ReplaceFolioDialog (QWidget * parent = nullptr)
Definition at line 117 of file replacefoliowidget.cpp.
References QET::Icons::Cancel, m_button_box, and m_widget.
~ReplaceFolioDialog()
ReplaceFolioDialog::~ReplaceFolioDialog ()
Definition at line 136 of file replacefoliowidget.cpp.
Member Function Documentation
setTitleBlockProperties()
void ReplaceFolioDialog::setTitleBlockProperties (const TitleBlockProperties & properties)
ReplaceFolioDialog::setTitleBlockProperties.
Parameters
properties : set the title block properties edited by this dialog
Definition at line 151 of file replacefoliowidget.cpp.
References m_widget, and ReplaceFolioWidget::setTitleBlockProperties().
Referenced by SearchAndReplaceWidget::on_m_folio_pb_clicked().
titleBlockProperties()
TitleBlockProperties ReplaceFolioDialog::titleBlockProperties () const
ReplaceFolioDialog::titleBlockProperties.
Returns
The title block properties edited by this dialog
Definition at line 143 of file replacefoliowidget.cpp.
References m_widget, and ReplaceFolioWidget::titleBlockProperties().
Referenced by SearchAndReplaceWidget::on_m_folio_pb_clicked().
Member Data Documentation
m_button_box
QDialogButtonBox* ReplaceFolioDialog::m_button_box = nullptr private
Definition at line 73 of file replacefoliowidget.h.
Referenced by ReplaceFolioDialog().
m_widget
ReplaceFolioWidget* ReplaceFolioDialog::m_widget = nullptr private
Definition at line 72 of file replacefoliowidget.h.
Referenced by ReplaceFolioDialog(), setTitleBlockProperties(), and titleBlockProperties().
The documentation for this class was generated from the following files:
replacefoliowidget.h
replacefoliowidget.cpp