QElectroTech: PartTerminal Class Reference
PartTerminal Class Reference
#include <partterminal.h>
Public Types
enum { Type = UserType + 1106 }
Public Types inherited from CustomElementGraphicPart
enum LineStyle { NormalStyle, DashedStyle, DottedStyle, DashdottedStyle }
enum LineWeight {
NoneWeight, ThinWeight, NormalWeight, UltraWeight,
BigWeight
}
enum Filling {
NoneFilling, BlackFilling, WhiteFilling, GreenFilling,
RedFilling, BlueFilling, GrayFilling, BrunFilling,
YellowFilling, CyanFilling, MagentaFilling, LightgrayFilling,
OrangeFilling, PurpleFilling, HTMLPinkPinkFilling, HTMLPinkLightPinkFilling,
HTMLPinkHotPinkFilling, HTMLPinkDeepPinkFilling, HTMLPinkPaleVioletRedFilling, HTMLPinkMediumVioletRedFilling,
HTMLRedLightSalmonFilling, HTMLRedSalmonFilling, HTMLRedDarkSalmonFilling, HTMLRedLightCoralFilling,
HTMLRedIndianRedFilling, HTMLRedCrimsonFilling, HTMLRedFirebrickFilling, HTMLRedDarkRedFilling,
HTMLRedRedFilling, HTMLOrangeOrangeRedFilling, HTMLOrangeTomatoFilling, HTMLOrangeCoralFilling,
HTMLOrangeDarkOrangeFilling, HTMLOrangeOrangeFilling, HTMLYellowYellowFilling, HTMLYellowLightYellowFilling,
HTMLYellowLemonChiffonFilling, HTMLYellowLightGoldenrodYellowFilling, HTMLYellowPapayaWhipFilling, HTMLYellowMoccasinFilling,
HTMLYellowPeachPuffFilling, HTMLYellowPaleGoldenrodFilling, HTMLYellowKhakiFilling, HTMLYellowDarkKhakiFilling,
HTMLYellowGoldFilling, HTMLBrownCornsilkFilling, HTMLBrownBlanchedAlmondFilling, HTMLBrownBisqueFilling,
HTMLBrownNavajoWhiteFilling, HTMLBrownWheatFilling, HTMLBrownBurlywoodFilling, HTMLBrownTanFilling,
HTMLBrownRosyBrownFilling, HTMLBrownSandyBrownFilling, HTMLBrownGoldenrodFilling, HTMLBrownDarkGoldenrodFilling,
HTMLBrownPeruFilling, HTMLBrownChocolateFilling, HTMLBrownSaddleBrownFilling, HTMLBrownSiennaFilling,
HTMLBrownBrownFilling, HTMLBrownMaroonFilling, HTMLGreenDarkOliveGreenFilling, HTMLGreenOliveFilling,
HTMLGreenOliveDrabFilling, HTMLGreenYellowGreenFilling, HTMLGreenLimeGreenFilling, HTMLGreenLimeFilling,
HTMLGreenLawnGreenFilling, HTMLGreenChartreuseFilling, HTMLGreenGreenYellowFilling, HTMLGreenSpringGreenFilling,
HTMLGreenMediumSpringGreenFilling, HTMLGreenLightGreenFilling, HTMLGreenPaleGreenFilling, HTMLGreenDarkSeaGreenFilling,
HTMLGreenMediumAquamarineFilling, HTMLGreenMediumSeaGreenFilling, HTMLGreenSeaGreenFilling, HTMLGreenForestGreenFilling,
HTMLGreenGreenFilling, HTMLGreenDarkGreenFilling, HTMLCyanAquaFilling, HTMLCyanCyanFilling,
HTMLCyanLightCyanFilling, HTMLCyanPaleTurquoiseFilling, HTMLCyanAquamarineFilling, HTMLCyanTurquoiseFilling,
HTMLCyanMediumTurquoiseFilling, HTMLCyanDarkTurquoiseFilling, HTMLCyanLightSeaGreenFilling, HTMLCyanCadetBlueFilling,
HTMLCyanDarkCyanFilling, HTMLCyanTealFilling, HTMLBlueLightSteelBlueFilling, HTMLBluePowderBlueFilling,
HTMLBlueLightBlueFilling, HTMLBlueSkyBlueFilling, HTMLBlueLightSkyBlueFilling, HTMLBlueDeepSkyBlueFilling,
HTMLBlueDodgerBlueFilling, HTMLBlueCornflowerBlueFilling, HTMLBlueSteelBlueFilling, HTMLBlueRoyalBlueFilling,
HTMLBlueBlueFilling, HTMLBlueMediumBlueFilling, HTMLBlueDarkBlueFilling, HTMLBlueNavyFilling,
HTMLBlueMidnightBlueFilling, HTMLPurpleLavenderFilling, HTMLPurpleThistleFilling, HTMLPurplePlumFilling,
HTMLPurpleVioletFilling, HTMLPurpleOrchidFilling, HTMLPurpleFuchsiaFilling, HTMLPurpleMagentaFilling,
HTMLPurpleMediumOrchidFilling, HTMLPurpleMediumPurpleFilling, HTMLPurpleBlueVioletFilling, HTMLPurpleDarkVioletFilling,
HTMLPurpleDarkOrchidFilling, HTMLPurpleDarkMagentaFilling, HTMLPurplePurpleFilling, HTMLPurpleIndigoFilling,
HTMLPurpleDarkSlateBlueFilling, HTMLPurpleSlateBlueFilling, HTMLPurpleMediumSlateBlueFilling, HTMLWhiteWhiteFilling,
HTMLWhiteSnowFilling, HTMLWhiteHoneydewFilling, HTMLWhiteMintCreamFilling, HTMLWhiteAzureFilling,
HTMLWhiteAliceBlueFilling, HTMLWhiteGhostWhiteFilling, HTMLWhiteWhiteSmokeFilling, HTMLWhiteSeashellFilling,
HTMLWhiteBeigeFilling, HTMLWhiteOldLaceFilling, HTMLWhiteFloralWhiteFilling, HTMLWhiteIvoryFilling,
HTMLWhiteAntiqueWhiteFilling, HTMLWhiteLinenFilling, HTMLWhiteLavenderBlushFilling, HTMLWhiteMistyRoseFilling,
HTMLGrayGainsboroFilling, HTMLGrayLightGrayFilling, HTMLGraySilverFilling, HTMLGrayDarkGrayFilling,
HTMLGrayGrayFilling, HTMLGrayDimGrayFilling, HTMLGrayLightSlateGrayFilling, HTMLGraySlateGrayFilling,
HTMLGrayDarkSlateGrayFilling, HTMLGrayBlackFilling, HorFilling, VerFilling,
BdiagFilling, FdiagFilling
}
enum Color {
BlackColor, WhiteColor, GreenColor, RedColor,
BlueColor, GrayColor, BrunColor, YellowColor,
CyanColor, MagentaColor, LightgrayColor, OrangeColor,
PurpleColor, HTMLPinkPinkColor, HTMLPinkLightPinkColor, HTMLPinkHotPinkColor,
HTMLPinkDeepPinkColor, HTMLPinkPaleVioletRedColor, HTMLPinkMediumVioletRedColor, HTMLRedLightSalmonColor,
HTMLRedSalmonColor, HTMLRedDarkSalmonColor, HTMLRedLightCoralColor, HTMLRedIndianRedColor,
HTMLRedCrimsonColor, HTMLRedFirebrickColor, HTMLRedDarkRedColor, HTMLRedRedColor,
HTMLOrangeOrangeRedColor, HTMLOrangeTomatoColor, HTMLOrangeCoralColor, HTMLOrangeDarkOrangeColor,
HTMLOrangeOrangeColor, HTMLYellowYellowColor, HTMLYellowLightYellowColor, HTMLYellowLemonChiffonColor,
HTMLYellowLightGoldenrodYellowColor, HTMLYellowPapayaWhipColor, HTMLYellowMoccasinColor, HTMLYellowPeachPuffColor,
HTMLYellowPaleGoldenrodColor, HTMLYellowKhakiColor, HTMLYellowDarkKhakiColor, HTMLYellowGoldColor,
HTMLBrownCornsilkColor, HTMLBrownBlanchedAlmondColor, HTMLBrownBisqueColor, HTMLBrownNavajoWhiteColor,
HTMLBrownWheatColor, HTMLBrownBurlywoodColor, HTMLBrownTanColor, HTMLBrownRosyBrownColor,
HTMLBrownSandyBrownColor, HTMLBrownGoldenrodColor, HTMLBrownDarkGoldenrodColor, HTMLBrownPeruColor,
HTMLBrownChocolateColor, HTMLBrownSaddleBrownColor, HTMLBrownSiennaColor, HTMLBrownBrownColor,
HTMLBrownMaroonColor, HTMLGreenDarkOliveGreenColor, HTMLGreenOliveColor, HTMLGreenOliveDrabColor,
HTMLGreenYellowGreenColor, HTMLGreenLimeGreenColor, HTMLGreenLimeColor, HTMLGreenLawnGreenColor,
HTMLGreenChartreuseColor, HTMLGreenGreenYellowColor, HTMLGreenSpringGreenColor, HTMLGreenMediumSpringGreenColor,
HTMLGreenLightGreenColor, HTMLGreenPaleGreenColor, HTMLGreenDarkSeaGreenColor, HTMLGreenMediumAquamarineColor,
HTMLGreenMediumSeaGreenColor, HTMLGreenSeaGreenColor, HTMLGreenForestGreenColor, HTMLGreenGreenColor,
HTMLGreenDarkGreenColor, HTMLCyanAquaColor, HTMLCyanCyanColor, HTMLCyanLightCyanColor,
HTMLCyanPaleTurquoiseColor, HTMLCyanAquamarineColor, HTMLCyanTurquoiseColor, HTMLCyanMediumTurquoiseColor,
HTMLCyanDarkTurquoiseColor, HTMLCyanLightSeaGreenColor, HTMLCyanCadetBlueColor, HTMLCyanDarkCyanColor,
HTMLCyanTealColor, HTMLBlueLightSteelBlueColor, HTMLBluePowderBlueColor, HTMLBlueLightBlueColor,
HTMLBlueSkyBlueColor, HTMLBlueLightSkyBlueColor, HTMLBlueDeepSkyBlueColor, HTMLBlueDodgerBlueColor,
HTMLBlueCornflowerBlueColor, HTMLBlueSteelBlueColor, HTMLBlueRoyalBlueColor, HTMLBlueBlueColor,
HTMLBlueMediumBlueColor, HTMLBlueDarkBlueColor, HTMLBlueNavyColor, HTMLBlueMidnightBlueColor,
HTMLPurpleLavenderColor, HTMLPurpleThistleColor, HTMLPurplePlumColor, HTMLPurpleVioletColor,
HTMLPurpleOrchidColor, HTMLPurpleFuchsiaColor, HTMLPurpleMagentaColor, HTMLPurpleMediumOrchidColor,
HTMLPurpleMediumPurpleColor, HTMLPurpleBlueVioletColor, HTMLPurpleDarkVioletColor, HTMLPurpleDarkOrchidColor,
HTMLPurpleDarkMagentaColor, HTMLPurplePurpleColor, HTMLPurpleIndigoColor, HTMLPurpleDarkSlateBlueColor,
HTMLPurpleSlateBlueColor, HTMLPurpleMediumSlateBlueColor, HTMLWhiteWhiteColor, HTMLWhiteSnowColor,
HTMLWhiteHoneydewColor, HTMLWhiteMintCreamColor, HTMLWhiteAzureColor, HTMLWhiteAliceBlueColor,
HTMLWhiteGhostWhiteColor, HTMLWhiteWhiteSmokeColor, HTMLWhiteSeashellColor, HTMLWhiteBeigeColor,
HTMLWhiteOldLaceColor, HTMLWhiteFloralWhiteColor, HTMLWhiteIvoryColor, HTMLWhiteAntiqueWhiteColor,
HTMLWhiteLinenColor, HTMLWhiteLavenderBlushColor, HTMLWhiteMistyRoseColor, HTMLGrayGainsboroColor,
HTMLGrayLightGrayColor, HTMLGraySilverColor, HTMLGrayDarkGrayColor, HTMLGrayGrayColor,
HTMLGrayDimGrayColor, HTMLGrayLightSlateGrayColor, HTMLGraySlateGrayColor, HTMLGrayDarkSlateGrayColor,
HTMLGrayBlackColor, NoneColor
}
Signals
void orientationChanged ()
void nameChanged ()
Public Member Functions
PartTerminal (QETElementEditor *editor, QGraphicsItem *parent=nullptr)
PartTerminal::PartTerminal.
~PartTerminal () override
Destructeur.
int type () const override
QString name () const override
QString xmlName () const override
void fromXml (const QDomElement &) override
const QDomElement toXml (QDomDocument &) const override
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *) override
QPainterPath shape () const override
PartTerminal::shape.
QPainterPath shadowShape () const override
QRectF boundingRect () const override
PartTerminal::boundingRect.
bool isUseless () const override
QRectF sceneGeometricRect () const override
void startUserTransformation (const QRectF &) override
void handleUserTransformation (const QRectF &, const QRectF &) override
Qet::Orientation orientation () const
void setOrientation (Qet::Orientation ori)
void setName (QString &name)
PartTerminal::setName.
void setNewUuid ()
Public Member Functions inherited from CustomElementGraphicPart
CustomElementGraphicPart (QETElementEditor *editor, QGraphicsItem *parent=nullptr)
CustomElementGraphicPart::CustomElementGraphicPart Default constructor. By default, item is selectable, send geometry change (Qt > 4.6), accept mouse left button and accept hover event.
~CustomElementGraphicPart () override
CustomElementGraphicPart::~CustomElementGraphicPart Destructor.
LineStyle lineStyle () const
void setLineStyle (const LineStyle ls)
CustomElementGraphicPart::setLineStyle Set line style to ls.
LineWeight lineWeight () const
void setLineWeight (const LineWeight lw)
CustomElementGraphicPart::setLineWeight Set line weight to lw.
qreal penWeight () const
CustomElementGraphicPart::penWeight.
Filling filling () const
void setFilling (const Filling f)
CustomElementGraphicPart::setFilling Set filling to f.
Color color () const
void setColor (const Color c)
CustomElementGraphicPart::setColor Set color to c.
bool antialiased () const
void setAntialiased (const bool b)
CustomElementGraphicPart::setAntialiased Set antialias to b.
void setProperty (const char *name, const QVariant &value) override
QVariant property (const char *name) const override
virtual void setHandlerColor (QPointF, const QColor &)
virtual void resetAllHandlerColor ()
Public Member Functions inherited from CustomElementPart
CustomElementPart (QETElementEditor *editor)
CustomElementPart Constructor.
virtual ~CustomElementPart ()
~CustomElementPart Destructor
virtual QETElementEditor * elementEditor () const
virtual void updateCurrentPartEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QGraphicsItem * toItem ()
virtual QET::ScalingMethod preferredScalingMethod () const
Properties
Qet::Orientation orientation
QString name
Properties inherited from CustomElementGraphicPart
LineStyle line_style
LineWeight line_weight
Filling filling
Color color
bool antialias
Private Member Functions
PartTerminal (const PartTerminal &)
void updateSecondPoint ()
Private Attributes
TerminalData * d
QPointF saved_position_
Additional Inherited Members
Static Public Member Functions inherited from CustomElementGraphicPart
static void drawCross (const QPointF &center, QPainter *painter)
CustomElementGraphicPart::drawCross Draw a cross at pos center.
Protected Member Functions inherited from CustomElementGraphicPart
void stylesToXml (QDomElement &) const
CustomElementGraphicPart::stylesToXml Write the curent style to xml element. The style are stored like this: name-of-style:value;name-of-style:value Each style separate by ; and name-style/value are separate by :
void stylesFromXml (const QDomElement &)
CustomElementGraphicPart::stylesFromXml Read the style used by this, from a xml element.
void resetStyles ()
CustomElementGraphicPart::resetStyles Reset the curent style to default, same style of default constructor.
void applyStylesToQPainter (QPainter &) const
CustomElementGraphicPart::applyStylesToQPainter Apply the current style to the QPainter.
void drawShadowShape (QPainter *painter)
CustomElementGraphicPart::drawShadowShape Draw a transparent blue shadow arround the shape of this item. The QPainterPathStroker used to draw shadows have a width of SHADOWS_HEIGHT Be carefull if penWeight of this item is to 0 the outline of strock is bigger of 0.5.
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
CustomElementGraphicPart::itemChange Reimplemented from QGraphicsObject. If the item position change call updateCurrentPartEditor() the change is always send to QGraphicsObject.
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
CustomElementGraphicPart::hoverEnterEvent Reimplemented from QGraphicsObject. Set m_hovered to true.
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
CustomElementGraphicPart::hoverLeaveEvent Reimplemented from QGraphicsObject. Set m_hovered to false.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions inherited from CustomElementPart
QList< QPointF > mapPoints (const QRectF &, const QRectF &, const QList< QPointF > &)
Protected Attributes inherited from CustomElementGraphicPart
bool m_hovered
Detailed Description
This class represents a terminal which may be used to compose the drawing of an electrical element within the element editor.
Definition at line 30 of file partterminal.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 48 of file partterminal.h.
Constructor & Destructor Documentation
PartTerminal() [1/2]
PartTerminal::PartTerminal (QETElementEditor * editor, QGraphicsItem * parent = nullptr)
PartTerminal::PartTerminal.
Parameters
editor : L'editeur d'element concerne
parent : Le QGraphicsItem parent de cette borne
Definition at line 28 of file partterminal.cpp.
References d, Qet::North, and updateSecondPoint().
~PartTerminal()
PartTerminal::~PartTerminal () override
Destructeur.
Definition at line 39 of file partterminal.cpp.
PartTerminal() [2/2]
PartTerminal::PartTerminal (const PartTerminal &) private
Member Function Documentation
boundingRect()
QRectF PartTerminal::boundingRect () const override
PartTerminal::boundingRect.
Returns
the bounding rect of this item
Definition at line 114 of file partterminal.cpp.
References QET::Icons::br, d, and SHADOWS_HEIGHT.
fromXml()
void PartTerminal::fromXml (const QDomElement & xml_elmt) override virtual
Importe les proprietes d'une borne depuis un element XML
Parameters
xml_elmt Element XML a lire
Implements CustomElementPart.
Definition at line 46 of file partterminal.cpp.
References d, and updateSecondPoint().
handleUserTransformation()
void PartTerminal::handleUserTransformation (const QRectF & initial_selection_rect, const QRectF & new_selection_rect) override virtual
Handle the user-induced transformation from initial_selection_rect to new_selection_rect
Implements CustomElementPart.
Definition at line 194 of file partterminal.cpp.
References CustomElementPart::mapPoints(), and saved_position_.
isUseless()
bool PartTerminal::isUseless () const override virtual
Returns
true si cette partie n'est pas pertinente et ne merite pas d'etre conservee / enregistree. Une borne est toujours pertinente ; cette fonction renvoie donc toujours false
Implements CustomElementPart.
Definition at line 168 of file partterminal.cpp.
name()
QString PartTerminal::name () const inline override virtual
Returns
the name of the primitive
Implements CustomElementPart.
Definition at line 54 of file partterminal.h.
References d.
nameChanged
void PartTerminal::nameChanged () signal
Referenced by setName().
orientation()
Qet::Orientation PartTerminal::orientation () const inline
Definition at line 68 of file partterminal.h.
References d.
orientationChanged
void PartTerminal::orientationChanged () signal
Referenced by setOrientation(), TerminalEditor::setPart(), and TerminalEditor::setParts().
paint()
void PartTerminal::paint (QPainter * p, const QStyleOptionGraphicsItem * options, QWidget * widget) override
Dessine la borne
Parameters
p QPainter a utiliser pour rendre le dessin
options Options pour affiner le rendu
widget Widget sur lequel le rendu est effectue
Definition at line 67 of file partterminal.cpp.
References d, CustomElementGraphicPart::drawShadowShape(), CustomElementGraphicPart::m_hovered, and Terminal::neutralColor.
sceneGeometricRect()
QRectF PartTerminal::sceneGeometricRect () const override virtual
Returns
the minimum, margin-less rectangle this part can fit into, in scene coordinates. It is different from boundingRect() because it is not supposed to imply any margin, and it is different from shape because it is a regular rectangle, not a complex shape.
Implements CustomElementPart.
Definition at line 178 of file partterminal.cpp.
setName()
void PartTerminal::setName (QString & name)
PartTerminal::setName.
Parameters
name
Definition at line 138 of file partterminal.cpp.
References d, name, and nameChanged().
setNewUuid()
void PartTerminal::setNewUuid ()
Definition at line 144 of file partterminal.cpp.
References d.
Referenced by PastePartsCommand::PastePartsCommand().
setOrientation()
void PartTerminal::setOrientation (Qet::Orientation ori)
Definit l'orientation de la borne
Parameters
ori la nouvelle orientation de la borne
Definition at line 127 of file partterminal.cpp.
References d, orientationChanged(), and updateSecondPoint().
shadowShape()
QPainterPath PartTerminal::shadowShape () const inline override virtual
Implements CustomElementGraphicPart.
Definition at line 61 of file partterminal.h.
References shape().
shape()
QPainterPath PartTerminal::shape () const override
PartTerminal::shape.
Returns
the shape of this item
Definition at line 100 of file partterminal.cpp.
References d.
Referenced by shadowShape().
startUserTransformation()
void PartTerminal::startUserTransformation (const QRectF & initial_selection_rect) override virtual
Start the user-induced transformation, provided this primitive is contained within the initial_selection_rect bounding rectangle.
Implements CustomElementPart.
Definition at line 186 of file partterminal.cpp.
References saved_position_.
toXml()
const QDomElement PartTerminal::toXml (QDomDocument & xml_document) const override virtual
Exporte la borne en XML
Parameters
xml_document Document XML a utiliser pour creer l'element XML
Returns
un element XML decrivant la borne
Implements CustomElementPart.
Definition at line 57 of file partterminal.cpp.
References d.
type()
int PartTerminal::type () const inline override
Enable the use of qgraphicsitem_cast to safely cast a QGraphicsItem into a PartTerminal.
Returns
the QGraphicsItem type
Definition at line 53 of file partterminal.h.
References Type.
updateSecondPoint()
void PartTerminal::updateSecondPoint () private
Met a jour la position du second point en fonction de la position et de l'orientation de la borne.
Definition at line 152 of file partterminal.cpp.
References d, Qet::East, Qet::North, Qet::South, and Qet::West.
Referenced by fromXml(), PartTerminal(), and setOrientation().
xmlName()
QString PartTerminal::xmlName () const inline override virtual
Returns
the name that will be used as XML tag when exporting the primitive
Implements CustomElementPart.
Definition at line 55 of file partterminal.h.
Member Data Documentation
d
TerminalData* PartTerminal::d private
Definition at line 76 of file partterminal.h.
Referenced by boundingRect(), fromXml(), name(), orientation(), paint(), PartTerminal(), setName(), setNewUuid(), setOrientation(), shape(), toXml(), and updateSecondPoint().
saved_position_
QPointF PartTerminal::saved_position_ private
Definition at line 79 of file partterminal.h.
Referenced by handleUserTransformation(), and startUserTransformation().
Property Documentation
name
QString PartTerminal::name read write
Definition at line 1 of file partterminal.h.
Referenced by setName().
orientation
Qet::Orientation PartTerminal::orientation read write
Definition at line 1 of file partterminal.h.
Referenced by ESEventAddTerminal::keyPressEvent().
The documentation for this class was generated from the following files:
partterminal.h
partterminal.cpp