QElectroTech: CompositeTextEditDialog Class Reference
CompositeTextEditDialog Class Reference
The CompositeTextEditDialog class CompositeTextEditDialog display a dialog use to write the complex text of a dynamic element text item. This dialog provide a QComboBox to quickly add an information of the element in the composite text.
#include <compositetexteditdialog.h>
Public Member Functions
CompositeTextEditDialog (DynamicElementTextItem *text, QWidget *parent=nullptr)
CompositeTextEditDialog (QString text, QWidget *parent=nullptr)
~CompositeTextEditDialog () override
QString plainText () const
CompositeTextEditDialog::plainText.
Protected Member Functions
void focusInEvent (QFocusEvent *event) override
CompositeTextEditDialog::focusInEvent Reimplemented from QWidget::focusInEvent.
Private Slots
void on_m_info_cb_activated (const QString &arg1)
Private Member Functions
void setUpComboBox ()
CompositeTextEditDialog::setUpComboBox Add the available element information in the combo box.
QString infoToVar (const QString &info) const
Private Attributes
Ui::CompositeTextEditDialog * ui
QString m_default_text
DynamicElementTextItem * m_text = nullptr
Detailed Description
The CompositeTextEditDialog class CompositeTextEditDialog display a dialog use to write the complex text of a dynamic element text item. This dialog provide a QComboBox to quickly add an information of the element in the composite text.
Definition at line 19 of file compositetexteditdialog.h.
Constructor & Destructor Documentation
CompositeTextEditDialog() [1/2]
CompositeTextEditDialog::CompositeTextEditDialog (DynamicElementTextItem * text, QWidget * parent = nullptr) explicit
Definition at line 10 of file compositetexteditdialog.cpp.
References DynamicElementTextItem::compositeText, m_default_text, m_text, setUpComboBox(), QET::Icons::tr, and ui.
CompositeTextEditDialog() [2/2]
CompositeTextEditDialog::CompositeTextEditDialog (QString text, QWidget * parent = nullptr) explicit
Definition at line 22 of file compositetexteditdialog.cpp.
References m_default_text, setUpComboBox(), QET::Icons::tr, and ui.
~CompositeTextEditDialog()
CompositeTextEditDialog::~CompositeTextEditDialog () override
Definition at line 33 of file compositetexteditdialog.cpp.
References ui.
Member Function Documentation
focusInEvent()
void CompositeTextEditDialog::focusInEvent (QFocusEvent * event) override protected
CompositeTextEditDialog::focusInEvent Reimplemented from QWidget::focusInEvent.
Parameters
event
Definition at line 85 of file compositetexteditdialog.cpp.
References ui.
infoToVar()
QString CompositeTextEditDialog::infoToVar (const QString & info) const private
on_m_info_cb_activated
void CompositeTextEditDialog::on_m_info_cb_activated (const QString & arg1) private slot
Definition at line 74 of file compositetexteditdialog.cpp.
References ui.
plainText()
QString CompositeTextEditDialog::plainText () const
CompositeTextEditDialog::plainText.
Returns
The edited text
Definition at line 41 of file compositetexteditdialog.cpp.
References ui.
Referenced by DynamicTextFieldEditor::on_m_composite_text_pb_clicked(), and DynamicTextItemDelegate::setModelData().
setUpComboBox()
void CompositeTextEditDialog::setUpComboBox () private
CompositeTextEditDialog::setUpComboBox Add the available element information in the combo box.
Definition at line 49 of file compositetexteditdialog.cpp.
References Element::AllReport, QETApp::elementInfoKeys(), QETApp::elementInfoToVar(), QETApp::elementTranslatedInfoKey(), Element::linkType(), m_text, DynamicElementTextItem::parentElement(), and ui.
Referenced by CompositeTextEditDialog().
Member Data Documentation
m_default_text
QString CompositeTextEditDialog::m_default_text private
Definition at line 42 of file compositetexteditdialog.h.
Referenced by CompositeTextEditDialog().
m_text
DynamicElementTextItem* CompositeTextEditDialog::m_text = nullptr private
Definition at line 43 of file compositetexteditdialog.h.
Referenced by CompositeTextEditDialog(), and setUpComboBox().
ui
Ui::CompositeTextEditDialog* CompositeTextEditDialog::ui private
Definition at line 41 of file compositetexteditdialog.h.
Referenced by CompositeTextEditDialog(), focusInEvent(), on_m_info_cb_activated(), plainText(), setUpComboBox(), and ~CompositeTextEditDialog().
The documentation for this class was generated from the following files:
compositetexteditdialog.h
compositetexteditdialog.cpp