QElectroTech: DeleteQGraphicsItemCommand Class Reference
DeleteQGraphicsItemCommand Class Reference
#include <deleteqgraphicsitemcommand.h>
Public Member Functions
DeleteQGraphicsItemCommand (Diagram *diagram, const DiagramContent &content, QUndoCommand *parent=nullptr)
DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand.
~DeleteQGraphicsItemCommand () override
void undo () override
DeleteQGraphicsItemCommand::undo Undo this command.
void redo () override
DeleteQGraphicsItemCommand::redo Redo the delete command.
Private Member Functions
DeleteQGraphicsItemCommand (const DeleteQGraphicsItemCommand &)
void setPotentialsOfRemovedElements ()
DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements This function creates new conductors (if needed) for conserve the electrical potentials present at the terminals of each removed elements.
Terminal * terminalInSamePotential (Terminal *terminal, Conductor *conductor_to_exclude)
DeleteQGraphicsItemCommand::terminalInSamePotential Return a terminal at the same potential of terminal, by traveling through the conductors connected to terminal only if the owner element of the terminal is not delete by this undo command. Return nullptr if a terminal can't be found.
Private Attributes
DiagramContent m_removed_contents
Diagram * m_diagram
QHash< Element *, QList< Element * > > m_link_hash
QHash< DynamicElementTextItem *, Element * > m_elmt_text_hash
keep linked element for each removed element linked to other element.
QHash< DynamicElementTextItem *, ElementTextItemGroup * > m_grp_texts_hash
Keep the parent element of each deleted dynamic element text item.
QList< QPair< Terminal *, Terminal * > > m_connected_terminals
Keep the parent group of each deleted element text item.
QHash< QetGraphicsTableItem *, QPointer< QGraphicsScene > > m_table_scene_hash
bool m_remove_linked_table = false
Detailed Description
Definition at line 30 of file deleteqgraphicsitemcommand.h.
Constructor & Destructor Documentation
DeleteQGraphicsItemCommand() [1/2]
DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand (Diagram * diagram, const DiagramContent & content, QUndoCommand * parent = nullptr)
DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand.
Parameters
diagram : deigram where this undo work
content : content to remove
parent : parent undo
Definition at line 37 of file deleteqgraphicsitemcommand.cpp.
References DiagramContent::All, DiagramContent::items(), m_diagram, DiagramContent::m_element_texts, DiagramContent::m_elements, m_elmt_text_hash, m_grp_texts_hash, m_removed_contents, m_table_scene_hash, DiagramContent::m_tables, DiagramContent::m_texts_groups, QGIManager::manage(), ElementTextItemGroup::parentElement(), DynamicElementTextItem::parentElement(), DynamicElementTextItem::parentGroup(), Diagram::qgiManager(), DiagramContent::sentence(), setPotentialsOfRemovedElements(), and QET::Icons::tr.
~DeleteQGraphicsItemCommand()
DeleteQGraphicsItemCommand::~DeleteQGraphicsItemCommand () override
Definition at line 112 of file deleteqgraphicsitemcommand.cpp.
References DiagramContent::All, DiagramContent::items(), m_diagram, m_removed_contents, Diagram::qgiManager(), and QGIManager::release().
DeleteQGraphicsItemCommand() [2/2]
DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand (const DeleteQGraphicsItemCommand &) private
Member Function Documentation
redo()
void DeleteQGraphicsItemCommand::redo () override
DeleteQGraphicsItemCommand::redo Redo the delete command.
Definition at line 282 of file deleteqgraphicsitemcommand.cpp.
References DiagramContent::AnyConductor, DiagramContent::conductors(), DiagramContent::items(), Element::linkedElements(), m_diagram, DiagramContent::m_element_texts, DiagramContent::m_elements, m_link_hash, m_removed_contents, m_table_scene_hash, ElementTextItemGroup::parentElement(), DynamicElementTextItem::parentElement(), DynamicElementTextItem::parentGroup(), Element::removeDynamicTextItem(), Diagram::removeItem(), and Element::removeTextFromGroup().
setPotentialsOfRemovedElements()
void DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements () private
DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements This function creates new conductors (if needed) for conserve the electrical potentials present at the terminals of each removed elements.
Definition at line 121 of file deleteqgraphicsitemcommand.cpp.
References QET::Icons::Conductor, Terminal::conductors(), Conductor::diagram(), DiagramContent::Elements, DiagramContent::items(), m_connected_terminals, DiagramContent::m_elements, m_removed_contents, Terminal::parentElement(), Conductor::setProperties(), terminalInSamePotential(), and Element::terminals().
Referenced by DeleteQGraphicsItemCommand().
terminalInSamePotential()
Terminal * DeleteQGraphicsItemCommand::terminalInSamePotential (Terminal * terminal, Conductor * conductor_to_exclude) private
DeleteQGraphicsItemCommand::terminalInSamePotential Return a terminal at the same potential of terminal, by traveling through the conductors connected to terminal only if the owner element of the terminal is not delete by this undo command. Return nullptr if a terminal can't be found.
Parameters
terminal - terminal from search
conductor_to_exclude - a conductor to exlcude from search.
Returns
Definition at line 214 of file deleteqgraphicsitemcommand.cpp.
References Terminal::conductors(), DiagramContent::Elements, DiagramContent::items(), m_removed_contents, and Terminal::parentElement().
Referenced by setPotentialsOfRemovedElements().
undo()
void DeleteQGraphicsItemCommand::undo () override
DeleteQGraphicsItemCommand::undo Undo this command.
Definition at line 244 of file deleteqgraphicsitemcommand.cpp.
References Element::addDynamicTextItem(), Diagram::addItem(), Element::addTextToGroup(), DiagramContent::items(), m_diagram, DiagramContent::m_element_texts, DiagramContent::m_elements, m_elmt_text_hash, m_grp_texts_hash, m_link_hash, m_removed_contents, m_table_scene_hash, and Diagram::showMe().
Member Data Documentation
m_connected_terminals
QList<QPair<Terminal *, Terminal *> > DeleteQGraphicsItemCommand::m_connected_terminals private
Keep the parent group of each deleted element text item.
Definition at line 53 of file deleteqgraphicsitemcommand.h.
Referenced by setPotentialsOfRemovedElements().
m_diagram
Diagram* DeleteQGraphicsItemCommand::m_diagram private
Definition at line 49 of file deleteqgraphicsitemcommand.h.
Referenced by DeleteQGraphicsItemCommand(), redo(), undo(), and ~DeleteQGraphicsItemCommand().
m_elmt_text_hash
QHash<DynamicElementTextItem *, Element *> DeleteQGraphicsItemCommand::m_elmt_text_hash private
keep linked element for each removed element linked to other element.
Definition at line 51 of file deleteqgraphicsitemcommand.h.
Referenced by DeleteQGraphicsItemCommand(), and undo().
m_grp_texts_hash
QHash<DynamicElementTextItem *, ElementTextItemGroup *> DeleteQGraphicsItemCommand::m_grp_texts_hash private
Keep the parent element of each deleted dynamic element text item.
Definition at line 52 of file deleteqgraphicsitemcommand.h.
Referenced by DeleteQGraphicsItemCommand(), and undo().
m_link_hash
QHash<Element *, QList<Element *> > DeleteQGraphicsItemCommand::m_link_hash private
Definition at line 50 of file deleteqgraphicsitemcommand.h.
Referenced by redo(), and undo().
m_remove_linked_table
bool DeleteQGraphicsItemCommand::m_remove_linked_table = false private
Definition at line 55 of file deleteqgraphicsitemcommand.h.
m_removed_contents
DiagramContent DeleteQGraphicsItemCommand::m_removed_contents private
Definition at line 48 of file deleteqgraphicsitemcommand.h.
Referenced by DeleteQGraphicsItemCommand(), redo(), setPotentialsOfRemovedElements(), terminalInSamePotential(), undo(), and ~DeleteQGraphicsItemCommand().
m_table_scene_hash
QHash<QetGraphicsTableItem *, QPointer<QGraphicsScene> > DeleteQGraphicsItemCommand::m_table_scene_hash private
Definition at line 54 of file deleteqgraphicsitemcommand.h.
Referenced by DeleteQGraphicsItemCommand(), redo(), and undo().
The documentation for this class was generated from the following files:
deleteqgraphicsitemcommand.h
deleteqgraphicsitemcommand.cpp