QElectroTech: ElementInfoWidget Class Reference
ElementInfoWidget Class Reference
The ElementInfoWidget class this class is a widget to edit an element informations.
#include <elementinfowidget.h>
Public Member Functions
ElementInfoWidget (Element *elmt, QWidget *parent=nullptr)
ElementInfoWidget::ElementInfoWidget Constructor.
~ElementInfoWidget () override
ElementInfoWidget::~ElementInfoWidget Destructor.
void setElement (Element *element) override
ElementInfoWidget::setElement Set element to be the edited element.
void apply () override
ElementInfoWidget::apply Apply the new information with a new undo command (got with method associatedUndo) pushed to the stack of element project.
QUndoCommand * associatedUndo () const override
ElementInfoWidget::associatedUndo If the edited info is different of the actual element info, return a QUndoCommand with the change. If no change return nullptr;.
QString title () const override
PropertiesEditorWidget::title.
bool setLiveEdit (bool live_edit) override
ElementInfoWidget::setLiveEdit.
void updateUi () override
ElementInfoWidget::updateUi fill information fetch in m_element_info to the corresponding line edit.
DiagramContext currentInfo () const
ElementInfoWidget::currentInfo.
Public Member Functions inherited from AbstractElementPropertiesEditorWidget
AbstractElementPropertiesEditorWidget (QWidget *parent=nullptr)
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual void reset ()
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Protected Member Functions
bool event (QEvent *event) override
ElementInfoWidget::event Reimplemented from QWidget::event Only give focus to the first line edit at first activation. After send the event to QWidget.
void enableLiveEdit () override
ElementInfoWidget::enableLiveEdit Enable the live edit mode.
void disableLiveEdit () override
ElementInfoWidget::disableLiveEdit disable the live edit mode.
Private Slots
void firstActivated ()
ElementInfoWidget::firstActivated Slot activated when this widget is show. Set the focus to the first line edit provided by this widget.
void elementInfoChange ()
ElementInfoWidget::elementInfoChange This slot is called when m_element::elementInformation change.
Private Member Functions
void buildInterface ()
ElementInfoWidget::buildInterface Build the widget.
ElementInfoPartWidget * infoPartWidgetForKey (const QString &key) const
ElementInfoWidget::infoPartWidgetForKey.
Private Attributes
Ui::ElementInfoWidget * ui
QList< ElementInfoPartWidget * > m_eipw_list
bool m_first_activation
Additional Inherited Members
Protected Attributes inherited from AbstractElementPropertiesEditorWidget
QPointer< Element > m_element
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
The ElementInfoWidget class this class is a widget to edit an element informations.
Definition at line 38 of file elementinfowidget.h.
Constructor & Destructor Documentation
ElementInfoWidget()
ElementInfoWidget::ElementInfoWidget (Element * elmt, QWidget * parent = nullptr) explicit
ElementInfoWidget::ElementInfoWidget Constructor.
Parameters
elmt element to edit information
parent parent widget
Definition at line 32 of file elementinfowidget.cpp.
References buildInterface(), setElement(), and ui.
~ElementInfoWidget()
ElementInfoWidget::~ElementInfoWidget () override
ElementInfoWidget::~ElementInfoWidget Destructor.
Definition at line 46 of file elementinfowidget.cpp.
References m_eipw_list, and ui.
Member Function Documentation
apply()
void ElementInfoWidget::apply () override virtual
ElementInfoWidget::apply Apply the new information with a new undo command (got with method associatedUndo) pushed to the stack of element project.
Reimplemented from PropertiesEditorWidget.
Definition at line 91 of file elementinfowidget.cpp.
References associatedUndo(), and AbstractElementPropertiesEditorWidget::m_element.
Referenced by disableLiveEdit(), and enableLiveEdit().
associatedUndo()
QUndoCommand * ElementInfoWidget::associatedUndo () const override virtual
ElementInfoWidget::associatedUndo If the edited info is different of the actual element info, return a QUndoCommand with the change. If no change return nullptr;.
Returns
Reimplemented from PropertiesEditorWidget.
Definition at line 104 of file elementinfowidget.cpp.
References currentInfo(), and AbstractElementPropertiesEditorWidget::m_element.
Referenced by apply().
buildInterface()
void ElementInfoWidget::buildInterface () private
ElementInfoWidget::buildInterface Build the widget.
Definition at line 178 of file elementinfowidget.cpp.
References QETApp::elementInfoKeys(), QETApp::elementTranslatedInfoKey(), m_eipw_list, and ui.
Referenced by ElementInfoWidget().
currentInfo()
DiagramContext ElementInfoWidget::currentInfo () const
ElementInfoWidget::currentInfo.
Returns
the info currently edited
Definition at line 231 of file elementinfowidget.cpp.
References DiagramContext::addValue(), m_eipw_list, and DiagramContext::remove().
Referenced by associatedUndo(), and elementInfoChange().
disableLiveEdit()
void ElementInfoWidget::disableLiveEdit () override protected virtual
ElementInfoWidget::disableLiveEdit disable the live edit mode.
Reimplemented from PropertiesEditorWidget.
Definition at line 168 of file elementinfowidget.cpp.
References apply(), m_eipw_list, and ElementInfoPartWidget::textChanged().
Referenced by setLiveEdit(), and updateUi().
elementInfoChange
void ElementInfoWidget::elementInfoChange () private slot
ElementInfoWidget::elementInfoChange This slot is called when m_element::elementInformation change.
Definition at line 265 of file elementinfowidget.cpp.
References currentInfo(), AbstractElementPropertiesEditorWidget::m_element, and updateUi().
Referenced by setElement().
enableLiveEdit()
void ElementInfoWidget::enableLiveEdit () override protected virtual
ElementInfoWidget::enableLiveEdit Enable the live edit mode.
Reimplemented from PropertiesEditorWidget.
Definition at line 158 of file elementinfowidget.cpp.
References apply(), m_eipw_list, and ElementInfoPartWidget::textChanged().
Referenced by setLiveEdit(), and updateUi().
event()
bool ElementInfoWidget::event (QEvent * event) override protected
ElementInfoWidget::event Reimplemented from QWidget::event Only give focus to the first line edit at first activation. After send the event to QWidget.
Parameters
event
Returns
Definition at line 141 of file elementinfowidget.cpp.
References firstActivated(), and m_first_activation.
firstActivated
void ElementInfoWidget::firstActivated () private slot
ElementInfoWidget::firstActivated Slot activated when this widget is show. Set the focus to the first line edit provided by this widget.
Definition at line 257 of file elementinfowidget.cpp.
References m_eipw_list.
Referenced by event().
infoPartWidgetForKey()
ElementInfoPartWidget * ElementInfoWidget::infoPartWidgetForKey (const QString & key) const private
ElementInfoWidget::infoPartWidgetForKey.
Parameters
key
Returns
the ElementInfoPartWidget with key key, if not found return nullptr;
Definition at line 195 of file elementinfowidget.cpp.
References ElementInfoPartWidget::key(), and m_eipw_list.
Referenced by setElement().
setElement()
void ElementInfoWidget::setElement (Element * element) override virtual
ElementInfoWidget::setElement Set element to be the edited element.
Parameters
element
Implements AbstractElementPropertiesEditorWidget.
Definition at line 57 of file elementinfowidget.cpp.
References elementInfoChange(), Element::elementInfoChange(), infoPartWidgetForKey(), AbstractElementPropertiesEditorWidget::m_element, ElementInfoPartWidget::setDisabled(), ElementInfoPartWidget::setEnabled(), ElementInfoPartWidget::text(), ElementInfoPartWidget::textChanged(), and updateUi().
Referenced by ElementInfoWidget().
setLiveEdit()
bool ElementInfoWidget::setLiveEdit (bool live_edit) override virtual
ElementInfoWidget::setLiveEdit.
Parameters
live_edit true : enable the live edit mode, false disable
Returns
always true;
Reimplemented from PropertiesEditorWidget.
Definition at line 120 of file elementinfowidget.cpp.
References disableLiveEdit(), enableLiveEdit(), and PropertiesEditorWidget::m_live_edit.
title()
QString ElementInfoWidget::title () const inline override virtual
PropertiesEditorWidget::title.
Returns
the title of this editor
Reimplemented from PropertiesEditorWidget.
Definition at line 50 of file elementinfowidget.h.
References QET::Icons::tr.
updateUi()
void ElementInfoWidget::updateUi () override virtual
ElementInfoWidget::updateUi fill information fetch in m_element_info to the corresponding line edit.
Reimplemented from PropertiesEditorWidget.
Definition at line 211 of file elementinfowidget.cpp.
References disableLiveEdit(), enableLiveEdit(), m_eipw_list, AbstractElementPropertiesEditorWidget::m_element, and PropertiesEditorWidget::m_live_edit.
Referenced by elementInfoChange(), and setElement().
Member Data Documentation
m_eipw_list
QList<ElementInfoPartWidget *> ElementInfoWidget::m_eipw_list private
Definition at line 72 of file elementinfowidget.h.
Referenced by buildInterface(), currentInfo(), disableLiveEdit(), enableLiveEdit(), firstActivated(), infoPartWidgetForKey(), updateUi(), and ~ElementInfoWidget().
m_first_activation
bool ElementInfoWidget::m_first_activation private
Definition at line 73 of file elementinfowidget.h.
Referenced by event().
ui
Ui::ElementInfoWidget* ElementInfoWidget::ui private
Definition at line 71 of file elementinfowidget.h.
Referenced by buildInterface(), ElementInfoWidget(), and ~ElementInfoWidget().
The documentation for this class was generated from the following files:
elementinfowidget.h
elementinfowidget.cpp