QElectroTech: ElementsCollectionModel Class Reference
ElementsCollectionModel Class Reference
#include <elementscollectionmodel.h>
Signals
void loadingProgressValueChanged (int)
void loadingProgressRangeChanged (int, int)
void loadingFinished ()
Public Member Functions
ElementsCollectionModel (QObject *parent=Q_NULLPTR)
ElementsCollectionModel::ElementsCollectionModel Constructor.
QVariant data (const QModelIndex &index, int role) const override
ElementsCollectionModel::data Reimplemented from QStandardItemModel.
QMimeData * mimeData (const QModelIndexList &indexes) const override
ElementsCollectionModel::mimeData Reimplemented from QStandardItemModel.
QStringList mimeTypes () const override
ElementsCollectionModel::mimeTypes Reimplemented from QStandardItemModel.
bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const override
ElementsCollectionModel::canDropMimeData Reimplemented from QStandardItemModel.
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
ElementsCollectionModel::dropMimeData Reimplemented from QStandardItemModel.
void loadCollections (bool common_collection, bool custom_collection, QList< QETProject * > projects)
ElementsCollectionModel::loadCollections Load the several collections in this model. Prefer use this method instead of addCommonCollection, addCustomCollection and addProject, because it use multithreading to speed up the loading. This method emit loadingProgressRangeChanged(int, int) for know the minimu and maximum progress value This method emit loadingProgressValueChanged(int) for know the current progress value This method emit loadingFinished for know when loading finished.
void addCommonCollection (bool set_data=true)
ElementsCollectionModel::addCommonCollection Add the common elements collection to this model.
void addCustomCollection (bool set_data=true)
ElementsCollectionModel::addCustomCollection Add the custom elements collection to this model.
void addLocation (const ElementsLocation &location)
ElementsCollectionModel::addLocation Add the element or directory to this model. If the location is already managed by this model, do nothing.
void addProject (QETProject *project, bool set_data=true)
ElementsCollectionModel::addProject Add project to this model.
void removeProject (QETProject *project)
ElementsCollectionModel::removeProject Remove project from this model.
QList< QETProject * > project () const
ElementsCollectionModel::project.
void highlightUnusedElement ()
ElementsCollectionModel::highlightUnusedElement Highlight every unused element of managed project.
QList< ElementCollectionItem * > items () const
ElementsCollectionModel::items.
QList< ElementCollectionItem * > projectItems (QETProject *project) const
ElementsCollectionModel::projectItems.
void hideElement ()
ElementsCollectionModel::hideElement Hide element in this model, only directory is managed.
bool isHideElement ()
QModelIndex indexFromLocation (const ElementsLocation &location)
ElementsCollectionModel::indexFromLocation Return the index who represent location. Index can be non valid.
Private Member Functions
void elementIntegratedToCollection (const QString &path)
ElementsCollectionModel::elementIntegratedToCollection When an element is added to embedded collection of a project, this method create and display the new element.
void itemRemovedFromCollection (const QString &path)
ElementsCollectionModel::itemRemovedFromCollection This method must be called by a signal, to get a sender.
void updateItem (const QString &path)
ElementsCollectionModel::updateItem Update the item at path.
Private Attributes
QList< QETProject * > m_project_list
QHash< QETProject *, XmlProjectElementCollectionItem * > m_project_hash
bool m_hide_element = false
QFuture< void > m_future
QList< ElementCollectionItem * > m_items_list_to_setUp
Detailed Description
Definition at line 31 of file elementscollectionmodel.h.
Constructor & Destructor Documentation
ElementsCollectionModel()
ElementsCollectionModel::ElementsCollectionModel (QObject * parent = Q_NULLPTR)
ElementsCollectionModel::ElementsCollectionModel Constructor.
Parameters
parent
Definition at line 35 of file elementscollectionmodel.cpp.
Member Function Documentation
addCommonCollection()
void ElementsCollectionModel::addCommonCollection (bool set_data = true)
ElementsCollectionModel::addCommonCollection Add the common elements collection to this model.
Parameters
set_data
Definition at line 297 of file elementscollectionmodel.cpp.
References QETApp::commonElementsDirN(), m_hide_element, FileElementCollectionItem::setRootPath(), and FileElementCollectionItem::setUpData().
Referenced by loadCollections().
addCustomCollection()
void ElementsCollectionModel::addCustomCollection (bool set_data = true)
ElementsCollectionModel::addCustomCollection Add the custom elements collection to this model.
Parameters
set_data
Definition at line 316 of file elementscollectionmodel.cpp.
References QETApp::customElementsDirN(), m_hide_element, FileElementCollectionItem::setRootPath(), and FileElementCollectionItem::setUpData().
Referenced by NewElementWizard::buildStep1(), and loadCollections().
addLocation()
void ElementsCollectionModel::addLocation (const ElementsLocation & location)
ElementsCollectionModel::addLocation Add the element or directory to this model. If the location is already managed by this model, do nothing.
Parameters
location
Definition at line 336 of file elementscollectionmodel.cpp.
References ElementCollectionItem::addChildAtPath(), ElementsLocation::collectionPath(), indexFromLocation(), FileElementCollectionItem::isCustomCollection(), ElementsLocation::isCustomCollection(), ElementsLocation::isProject(), ElementCollectionItem::lastItemForPath(), m_project_hash, project(), ElementsLocation::project(), FileElementCollectionItem::Type, and ElementCollectionItem::type().
Referenced by ElementsCollectionWidget::locationWasSaved(), and ElementsCollectionWidget::newDirectory().
addProject()
void ElementsCollectionModel::addProject (QETProject * project, bool set_data = true)
ElementsCollectionModel::addProject Add project to this model.
Parameters
project : project to add.
set_data : if true, setUpData is called for every ElementCollectionItem of project
Definition at line 391 of file elementscollectionmodel.cpp.
References XmlElementCollection::directoryRemoved(), XmlElementCollection::elementAdded(), XmlElementCollection::elementChanged(), elementIntegratedToCollection(), XmlElementCollection::elementRemoved(), itemRemovedFromCollection(), m_project_hash, m_project_list, project(), XmlProjectElementCollectionItem::setProject(), XmlProjectElementCollectionItem::setUpData(), and updateItem().
Referenced by loadCollections().
canDropMimeData()
bool ElementsCollectionModel::canDropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) const override
ElementsCollectionModel::canDropMimeData Reimplemented from QStandardItemModel.
Parameters
data
action
row
column
parent
Returns
Definition at line 112 of file elementscollectionmodel.cpp.
References ElementCollectionItem::collectionPath(), ElementsLocation::collectionPath(), data(), and FileElementCollectionItem::Type.
data()
QVariant ElementsCollectionModel::data (const QModelIndex & index, int role) const override
ElementsCollectionModel::data Reimplemented from QStandardItemModel.
Parameters
index
role
Returns
Definition at line 47 of file elementscollectionmodel.cpp.
References XmlProjectElementCollectionItem::setUpIcon(), FileElementCollectionItem::Type, and XmlProjectElementCollectionItem::Type.
Referenced by canDropMimeData(), and dropMimeData().
dropMimeData()
bool ElementsCollectionModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) override
ElementsCollectionModel::dropMimeData Reimplemented from QStandardItemModel.
Parameters
data
action
row
column
parent
Returns
Definition at line 163 of file elementscollectionmodel.cpp.
References FileElementCollectionItem::addChildAtPath(), XmlProjectElementCollectionItem::collectionPath(), FileElementCollectionItem::collectionPath(), ElementsLocation::collectionPath(), ElementCollectionHandler::copy(), data(), ElementsLocation::exist(), ElementsLocation::fileName(), FileElementCollectionItem::fileSystemPath(), FileElementCollectionItem::isCommonCollection(), XmlProjectElementCollectionItem::isElement(), FileElementCollectionItem::isElement(), FileElementCollectionItem::Type, FileElementCollectionItem::type(), XmlProjectElementCollectionItem::Type, and XmlProjectElementCollectionItem::type().
elementIntegratedToCollection()
void ElementsCollectionModel::elementIntegratedToCollection (const QString & path) private
ElementsCollectionModel::elementIntegratedToCollection When an element is added to embedded collection of a project, this method create and display the new element.
Parameters
path : -The path of the new element in the embedded collection of a project
Definition at line 583 of file elementscollectionmodel.cpp.
References ElementCollectionItem::addChildAtPath(), QETProject::embeddedElementCollection(), ElementCollectionItem::lastItemForPath(), m_project_hash, m_project_list, and project().
Referenced by addProject(), and removeProject().
hideElement()
void ElementsCollectionModel::hideElement ()
ElementsCollectionModel::hideElement Hide element in this model, only directory is managed.
Definition at line 526 of file elementscollectionmodel.cpp.
References ElementCollectionItem::isElement(), items(), and m_hide_element.
Referenced by NewElementWizard::buildStep1().
highlightUnusedElement()
void ElementsCollectionModel::highlightUnusedElement ()
ElementsCollectionModel::highlightUnusedElement Highlight every unused element of managed project.
See also
QETProject::unusedElements()
Definition at line 465 of file elementscollectionmodel.cpp.
References indexFromLocation(), m_project_list, and project().
Referenced by ElementsCollectionWidget::highlightUnusedElement(), and ElementsCollectionWidget::loadingFinished().
indexFromLocation()
QModelIndex ElementsCollectionModel::indexFromLocation (const ElementsLocation & location)
ElementsCollectionModel::indexFromLocation Return the index who represent location. Index can be non valid.
Parameters
location
Returns
Definition at line 543 of file elementscollectionmodel.cpp.
References ElementsLocation::collectionPath(), ElementsLocation::isCommonCollection(), ElementsLocation::isCustomCollection(), ElementCollectionItem::itemAtPath(), FileElementCollectionItem::Type, ElementCollectionItem::type(), and XmlProjectElementCollectionItem::Type.
Referenced by addLocation(), highlightUnusedElement(), itemRemovedFromCollection(), ElementsCollectionWidget::locationWasSaved(), NewElementWizard::preselectedLocation(), and ElementsCollectionWidget::setCurrentLocation().
isHideElement()
bool ElementsCollectionModel::isHideElement () inline
Definition at line 59 of file elementscollectionmodel.h.
References m_hide_element.
itemRemovedFromCollection()
void ElementsCollectionModel::itemRemovedFromCollection (const QString & path) private
ElementsCollectionModel::itemRemovedFromCollection This method must be called by a signal, to get a sender.
Parameters
path
Definition at line 618 of file elementscollectionmodel.cpp.
References QETProject::embeddedElementCollection(), indexFromLocation(), m_project_list, and project().
Referenced by addProject(), and removeProject().
items()
QList< ElementCollectionItem * > ElementsCollectionModel::items () const
ElementsCollectionModel::items.
Returns
every ElementCollectionItem owned by this model
Definition at line 490 of file elementscollectionmodel.cpp.
References ElementCollectionItem::items().
Referenced by hideElement(), and loadCollections().
loadCollections()
void ElementsCollectionModel::loadCollections (bool common_collection, bool custom_collection, QList< QETProject * > projects)
ElementsCollectionModel::loadCollections Load the several collections in this model. Prefer use this method instead of addCommonCollection, addCustomCollection and addProject, because it use multithreading to speed up the loading. This method emit loadingProgressRangeChanged(int, int) for know the minimu and maximum progress value This method emit loadingProgressValueChanged(int) for know the current progress value This method emit loadingFinished for know when loading finished.
Parameters
common_collection : true for load the common collection
custom_collection : true for load the custom collection
projects : list of projects to load
Definition at line 259 of file elementscollectionmodel.cpp.
References addCommonCollection(), addCustomCollection(), addProject(), items(), loadingFinished(), loadingProgressRangeChanged(), loadingProgressValueChanged(), m_future, m_items_list_to_setUp, project(), projectItems(), and setUpData().
Referenced by ElementsCollectionWidget::addProject(), ElementsCollectionWidget::reload(), and ElementDialog::setUpWidget().
loadingFinished
void ElementsCollectionModel::loadingFinished () signal
Referenced by loadCollections(), and ElementsCollectionWidget::reload().
loadingProgressRangeChanged
void ElementsCollectionModel::loadingProgressRangeChanged (int , int) signal
Referenced by loadCollections(), and ElementsCollectionWidget::reload().
loadingProgressValueChanged
void ElementsCollectionModel::loadingProgressValueChanged (int) signal
Referenced by loadCollections(), and ElementsCollectionWidget::reload().
mimeData()
QMimeData * ElementsCollectionModel::mimeData (const QModelIndexList & indexes) const override
ElementsCollectionModel::mimeData Reimplemented from QStandardItemModel.
Parameters
indexes
Returns
Definition at line 67 of file elementscollectionmodel.cpp.
References ElementCollectionItem::collectionPath(), and ElementCollectionItem::isElement().
mimeTypes()
QStringList ElementsCollectionModel::mimeTypes () const override
ElementsCollectionModel::mimeTypes Reimplemented from QStandardItemModel.
Returns
Definition at line 94 of file elementscollectionmodel.cpp.
project()
QList< QETProject * > ElementsCollectionModel::project () const
ElementsCollectionModel::project.
Returns
every project added to this model
Definition at line 455 of file elementscollectionmodel.cpp.
References m_project_list.
Referenced by addLocation(), addProject(), elementIntegratedToCollection(), highlightUnusedElement(), itemRemovedFromCollection(), loadCollections(), projectItems(), ElementsCollectionWidget::reload(), removeProject(), and updateItem().
projectItems()
QList< ElementCollectionItem * > ElementsCollectionModel::projectItems (QETProject * project) const
ElementsCollectionModel::projectItems.
Parameters
project
Returns
return all items for project. the list can be empty
Definition at line 508 of file elementscollectionmodel.cpp.
References ElementCollectionItem::items(), m_project_hash, m_project_list, and project().
Referenced by loadCollections().
removeProject()
void ElementsCollectionModel::removeProject (QETProject * project)
ElementsCollectionModel::removeProject Remove project from this model.
Parameters
project
Definition at line 424 of file elementscollectionmodel.cpp.
References XmlElementCollection::directoryRemoved(), XmlElementCollection::elementAdded(), XmlElementCollection::elementChanged(), elementIntegratedToCollection(), XmlElementCollection::elementRemoved(), itemRemovedFromCollection(), m_project_hash, m_project_list, project(), and updateItem().
Referenced by ElementsCollectionWidget::removeProject().
updateItem()
void ElementsCollectionModel::updateItem (const QString & path) private
ElementsCollectionModel::updateItem Update the item at path.
Parameters
path
Definition at line 647 of file elementscollectionmodel.cpp.
References ElementCollectionItem::clearData(), QETProject::embeddedElementCollection(), m_project_hash, m_project_list, project(), and ElementCollectionItem::setUpData().
Referenced by addProject(), and removeProject().
Member Data Documentation
m_future
QFuture<void> ElementsCollectionModel::m_future private
Definition at line 76 of file elementscollectionmodel.h.
Referenced by loadCollections().
m_hide_element
bool ElementsCollectionModel::m_hide_element = false private
Definition at line 75 of file elementscollectionmodel.h.
Referenced by addCommonCollection(), addCustomCollection(), hideElement(), and isHideElement().
m_items_list_to_setUp
QList<ElementCollectionItem *> ElementsCollectionModel::m_items_list_to_setUp private
Definition at line 77 of file elementscollectionmodel.h.
Referenced by loadCollections().
m_project_hash
QHash<QETProject *, XmlProjectElementCollectionItem *> ElementsCollectionModel::m_project_hash private
Definition at line 74 of file elementscollectionmodel.h.
Referenced by addLocation(), addProject(), elementIntegratedToCollection(), projectItems(), removeProject(), and updateItem().
m_project_list
QList<QETProject *> ElementsCollectionModel::m_project_list private
Definition at line 73 of file elementscollectionmodel.h.
Referenced by addProject(), elementIntegratedToCollection(), highlightUnusedElement(), itemRemovedFromCollection(), project(), projectItems(), removeProject(), and updateItem().
The documentation for this class was generated from the following files:
elementscollectionmodel.h
elementscollectionmodel.cpp