QElectroTech: TitleBlockTemplateRenderer Class Reference
TitleBlockTemplateRenderer Class Reference
The TitleBlockTemplateRenderer class.
#include <titleblocktemplaterenderer.h>
Public Member Functions
TitleBlockTemplateRenderer (QObject *=nullptr)
TitleBlockTemplateRenderer::TitleBlockTemplateRenderer Constructor.
~TitleBlockTemplateRenderer () override
TitleBlockTemplateRenderer::~TitleBlockTemplateRenderer Destructor.
const TitleBlockTemplate * titleBlockTemplate () const
TitleBlockTemplateRenderer::titleBlockTemplate.
void setTitleBlockTemplate (const TitleBlockTemplate *)
TitleBlockTemplateRenderer::setTitleBlockTemplate.
void setContext (const DiagramContext &context)
TitleBlockTemplateRenderer::setContext.
DiagramContext context () const
TitleBlockTemplateRenderer::context.
int height () const
TitleBlockTemplateRenderer::height.
void render (QPainter *, int)
TitleBlockTemplateRenderer::render Render the titleblock.
void renderDxf (QRectF &, int, QString &, int)
TitleBlockTemplateRenderer::renderDxf.
void invalidateRenderedTemplate ()
TitleBlockTemplateRenderer::invalidateRenderedTemplate Invalidates the previous rendering of the template by resetting the internal QPicture.
void setUseCache (bool)
TitleBlockTemplateRenderer::setUseCache.
bool useCache () const
TitleBlockTemplateRenderer::useCache.
Private Member Functions
void renderToQPicture (int)
TitleBlockTemplateRenderer::renderToQPicture Renders the titleblock to the internal QPicture.
Private Attributes
const TitleBlockTemplate * m_titleblock_template
bool m_use_cache
QPicture m_rendered_template
DiagramContext m_context
int m_last_known_titleblock_width
Detailed Description
The TitleBlockTemplateRenderer class.
Definition at line 27 of file titleblocktemplaterenderer.h.
Constructor & Destructor Documentation
TitleBlockTemplateRenderer()
TitleBlockTemplateRenderer::TitleBlockTemplateRenderer (QObject * parent = nullptr)
TitleBlockTemplateRenderer::TitleBlockTemplateRenderer Constructor.
Parameters
parent : Parent QObject of this renderer
Definition at line 9 of file titleblocktemplaterenderer.cpp.
~TitleBlockTemplateRenderer()
TitleBlockTemplateRenderer::~TitleBlockTemplateRenderer () override
TitleBlockTemplateRenderer::~TitleBlockTemplateRenderer Destructor.
Definition at line 21 of file titleblocktemplaterenderer.cpp.
Member Function Documentation
context()
DiagramContext TitleBlockTemplateRenderer::context () const
TitleBlockTemplateRenderer::context.
Returns
the current diagram context use when render the titleblock
Definition at line 57 of file titleblocktemplaterenderer.cpp.
References m_context.
Referenced by setContext(), BorderTitleBlock::setNextFolioNum(), BorderTitleBlock::setPreviousFolioNum(), and BorderTitleBlock::titleblockInformation().
height()
int TitleBlockTemplateRenderer::height () const
TitleBlockTemplateRenderer::height.
Returns
the height of the rendered template, or -1 if no template has been set for this renderer.
See also
TitleBlockTemplate::height()
Definition at line 68 of file titleblocktemplaterenderer.cpp.
References m_titleblock_template.
invalidateRenderedTemplate()
void TitleBlockTemplateRenderer::invalidateRenderedTemplate ()
TitleBlockTemplateRenderer::invalidateRenderedTemplate Invalidates the previous rendering of the template by resetting the internal QPicture.
Definition at line 140 of file titleblocktemplaterenderer.cpp.
References m_rendered_template.
Referenced by setContext(), and setTitleBlockTemplate().
render()
void TitleBlockTemplateRenderer::render (QPainter * provided_painter, int titleblock_width)
TitleBlockTemplateRenderer::render Render the titleblock.
Parameters
provided_painter : QPainter to use to render the titleblock.
titleblock_width : The total width of the titleblock to render
Definition at line 79 of file titleblocktemplaterenderer.cpp.
References m_context, m_last_known_titleblock_width, m_rendered_template, m_titleblock_template, m_use_cache, and renderToQPicture().
Referenced by renderToQPicture().
renderDxf()
void TitleBlockTemplateRenderer::renderDxf (QRectF & title_block_rect, int titleblock_width, QString & file_path, int color)
TitleBlockTemplateRenderer::renderDxf.
Parameters
title_block_rect
titleblock_width
file_path
color
Definition at line 107 of file titleblocktemplaterenderer.cpp.
References m_context, and m_titleblock_template.
renderToQPicture()
void TitleBlockTemplateRenderer::renderToQPicture (int titleblock_width) private
TitleBlockTemplateRenderer::renderToQPicture Renders the titleblock to the internal QPicture.
Parameters
titleblock_width : Width of the titleblock to render
Definition at line 123 of file titleblocktemplaterenderer.cpp.
References m_context, m_last_known_titleblock_width, m_rendered_template, m_titleblock_template, and render().
Referenced by render().
setContext()
void TitleBlockTemplateRenderer::setContext (const DiagramContext & context)
TitleBlockTemplateRenderer::setContext.
Parameters
context : Context to use when rendering the titleblock
Definition at line 48 of file titleblocktemplaterenderer.cpp.
References context(), invalidateRenderedTemplate(), and m_context.
Referenced by BorderTitleBlock::setNextFolioNum(), and BorderTitleBlock::setPreviousFolioNum().
setTitleBlockTemplate()
void TitleBlockTemplateRenderer::setTitleBlockTemplate (const TitleBlockTemplate * titleblock_template)
TitleBlockTemplateRenderer::setTitleBlockTemplate.
Parameters
titleblock_template : TitleBlock template to render.
Definition at line 36 of file titleblocktemplaterenderer.cpp.
References invalidateRenderedTemplate(), and m_titleblock_template.
setUseCache()
void TitleBlockTemplateRenderer::setUseCache (bool use_cache)
TitleBlockTemplateRenderer::setUseCache.
Parameters
use_cache : true for this renderer to use its QPicture-based cache, false otherwise.
Definition at line 149 of file titleblocktemplaterenderer.cpp.
References m_use_cache.
titleBlockTemplate()
const TitleBlockTemplate * TitleBlockTemplateRenderer::titleBlockTemplate () const
TitleBlockTemplateRenderer::titleBlockTemplate.
Returns
the titleblock template used for the rendering
Definition at line 28 of file titleblocktemplaterenderer.cpp.
References m_titleblock_template.
useCache()
bool TitleBlockTemplateRenderer::useCache () const
TitleBlockTemplateRenderer::useCache.
Returns
true if this renderer uses its QPicture-based cache, false otherwise.
Definition at line 158 of file titleblocktemplaterenderer.cpp.
References m_use_cache.
Member Data Documentation
m_context
DiagramContext TitleBlockTemplateRenderer::m_context private
Definition at line 55 of file titleblocktemplaterenderer.h.
Referenced by context(), render(), renderDxf(), renderToQPicture(), and setContext().
m_last_known_titleblock_width
int TitleBlockTemplateRenderer::m_last_known_titleblock_width private
Definition at line 56 of file titleblocktemplaterenderer.h.
Referenced by render(), and renderToQPicture().
m_rendered_template
QPicture TitleBlockTemplateRenderer::m_rendered_template private
Definition at line 54 of file titleblocktemplaterenderer.h.
Referenced by invalidateRenderedTemplate(), render(), and renderToQPicture().
m_titleblock_template
const TitleBlockTemplate* TitleBlockTemplateRenderer::m_titleblock_template private
Definition at line 52 of file titleblocktemplaterenderer.h.
Referenced by height(), render(), renderDxf(), renderToQPicture(), setTitleBlockTemplate(), and titleBlockTemplate().
m_use_cache
bool TitleBlockTemplateRenderer::m_use_cache private
Definition at line 53 of file titleblocktemplaterenderer.h.
Referenced by render(), setUseCache(), and useCache().
The documentation for this class was generated from the following files:
titleblocktemplaterenderer.h
titleblocktemplaterenderer.cpp