QElectroTech: QetGraphicsTableItem Class Reference
QetGraphicsTableItem Class Reference
The QetGraphicsTableItem class This item display a table destined to represent the content of a QAbstractItemModel The table have a few parameters to edit her visual aspect. Margins, to edit the margin between the cell and the text. Text font. Text alignment in the cell These three parameters are not settable directly with the table but trough the model to be displayed by the table. The table search these parameters only in the index(0,0) for all the table. By consequence, set data in other index than 0,0 is useless also these parameter can't be set individually for each cell. The margins is stored in the model in index Qt::UserRole+1 and for value a QString. See QETUtils::marginsFromString and QETUtils::marginsToString.
#include <qetgraphicstableitem.h>
Public Types
enum { Type = UserType + 1300 }
Public Member Functions
QetGraphicsTableItem (QGraphicsItem *parent=nullptr)
QetGraphicsTableItem::QetGraphicsTableItem Default constructor.
virtual ~QetGraphicsTableItem () override
int type () const override
void setModel (QAbstractItemModel *model=nullptr)
QetGraphicsTableItem::setModel Set the model presented by this item. Since QetGraphicsTableItem don't take ownership of model, if item already have a model, it's your responsibility to delete it.
QAbstractItemModel * model () const
QetGraphicsTableItem::model.
virtual QRectF boundingRect () const override
QetGraphicsTableItem::boundingRect Reimplemented from QGraphicsObject.
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
QetGraphicsTableItem::paint Draw the table.
QetGraphicsHeaderItem * headerItem () const
void setSize (const QSize &size)
QetGraphicsTableItem::setSize Set the current size of the table to size.
QSize size () const
QetGraphicsTableItem::size.
QSize minimumSize () const
QetGraphicsTableItem::minimumSize.
void setDisplayNRow (const int &number)
QetGraphicsTableItem::setDisplayNRow Limit the number of row to display.
int displayNRow () const
QetGraphicsTableItem::displayNRow.
void setPreviousTable (QetGraphicsTableItem *table=nullptr)
QetGraphicsTableItem::setPreviousTable Set the previous table to table. If this table already have a previous table, the previous table will be replaced. Set new table to nullptr to remove an existing previous table. The table uses the model of the new previous table. Since the table does not take ownership of the model, it is your responsibility to manage the old model. Linked tables (table with next and/or previous table) share the same model, a table always take the model of the previous table. When remove a previous table (set to nullptr) from a table, the model is also removed, you need to set a new model.
void setNextTable (QetGraphicsTableItem *table=nullptr)
QetGraphicsTableItem::setNextTable Set the next table to table nullptr will remove an existing next table.
void setTableName (const QString &name)
QString tableName () const
int displayNRowOffset () const
QetGraphicsTableItem::displayNRowOffset.
QetGraphicsTableItem * previousTable () const
QetGraphicsTableItem * nextTable () const
void setToMinimumHeight ()
QetGraphicsTableItem::setToMinimumHeight Set the height to the the minimum. The width stay unchanged.
void initLink ()
QUuid uuid () const
int minimumRowHeigth () const
QetGraphicsTableItem::minimumRowHeigth.
QDomElement toXml (QDomDocument &dom_document) const
QetGraphicsTableItem::toXml Save the table to xml.
void fromXml (const QDomElement &dom_element)
QetGraphicsTableItem::fromXml Restore the table from xml. Make this item is already in a diagram to.
Public Member Functions inherited from QetGraphicsItem
QetGraphicsItem (QGraphicsItem *parent=nullptr)
QetGraphicsItem::QetGraphicsItem Default constructor.
~QetGraphicsItem () override=0
Diagram * diagram () const
QetGraphicsItem::diagram return the diagram of this item.
virtual void setPos (const QPointF &p)
QetGraphicsItem::setPos set the position of the item to p.
virtual void setPos (qreal x, qreal y)
QetGraphicsItem::setPos set the position of the item.
virtual bool isMovable () const
virtual void setMovable (bool movable)
virtual void editProperty ()
virtual QString name () const
QET::GraphicsItemState state () const
QetGraphicsItem::state.
Static Public Member Functions
static void adjustTableToFolio (QetGraphicsTableItem *table, QMargins margins=QMargins(20, 20, 20, 0))
QetGraphicsTableItem::adjustTableToFolio Adjust the table to fit at best the folio.
static void checkInsufficientRowsCount (QetGraphicsTableItem *first_table)
QetGraphicsTableItem::checkInsufficientRowsCount Check if the number of rows of table + linked table is enough to display all content of the model, if not open a dialog to advise user what to do.
static QString xmlTagName ()
Protected Member Functions
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
QetGraphicsTableItem::hoverEnterEvent Reimplemented from QetGraphicsItem.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QetGraphicsTableItem::hoverLeaveEvent Reimplemented from QetGraphicsItem.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
QetGraphicsTableItem::sceneEventFilter Reimplemented from QetGraphicsItem.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
QetGraphicsTableItem::itemChange.
Protected Member Functions inherited from QetGraphicsItem
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mousePressEvent handle the mouse click.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseDoubleClickEvent handle the mouse double click.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseMoveEvent handle mouse movement.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseReleaseEvent handle mouse release click.
Properties
QSize size
int displayNRow
Private Member Functions
void modelReseted ()
void setUpColumnAndRowMinimumSize ()
QetGraphicsTableItem::setUpColumnAndRowMinimumSize Calcule the minimum row height and the minimum column width for each columns this function doesn't change the geometry of the table.
void setUpBoundingRect ()
QetGraphicsTableItem::setUpBoundingRect.
void adjustHandlerPos ()
QetGraphicsTableItem::adjustHandlerPos Adjust the pos of the handler item.
void setUpHandler ()
QetGraphicsTableItem::setUpHandler.
void handlerMousePressEvent (QGraphicsSceneMouseEvent *event)
void handlerMouseMoveEvent (QGraphicsSceneMouseEvent *event)
void handlerMouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void adjustColumnsWidth ()
QetGraphicsTableItem::adjustColumnsWidth Adjust the size of each column according to the current table width by setting the sectionSize of the header item.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerSectionResized ()
QetGraphicsTableItem::headerSectionResized Connected to the header signal QetGraphicsTableItem sectionResized.
void adjustSize ()
QetGraphicsTableItem::adjustSize If needed, this function resize the current height and width of table and/or the size of columns. according to there minimum.
void previousTableDisplayRowChanged ()
Private Attributes
QAbstractItemModel * m_model = nullptr
QVector< int > m_minimum_column_width
int m_minimum_row_height
int m_number_of_displayed_row = 0
QSize m_current_size
QSize m_old_size
QSize m_pending_size
int m_br_margin = 10
QRectF m_bounding_rect
QetGraphicsHandlerItem m_handler_item
QetGraphicsHeaderItem * m_header_item = nullptr
QetGraphicsTableItem * m_previous_table = nullptr
QetGraphicsTableItem * m_next_table = nullptr
QString m_name
QUuid m_uuid = QUuid::createUuid()
QUuid m_pending_previous_table_uuid
Additional Inherited Members
Protected Attributes inherited from QetGraphicsItem
bool is_movable_
bool m_first_move
bool snap_to_grid_
QPointF m_mouse_to_origin_movement
QET::GraphicsItemState m_state = QET:: GIOK
Detailed Description
The QetGraphicsTableItem class This item display a table destined to represent the content of a QAbstractItemModel The table have a few parameters to edit her visual aspect. Margins, to edit the margin between the cell and the text. Text font. Text alignment in the cell These three parameters are not settable directly with the table but trough the model to be displayed by the table. The table search these parameters only in the index(0,0) for all the table. By consequence, set data in other index than 0,0 is useless also these parameter can't be set individually for each cell. The margins is stored in the model in index Qt::UserRole+1 and for value a QString. See QETUtils::marginsFromString and QETUtils::marginsToString.
Definition at line 42 of file qetgraphicstableitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 57 of file qetgraphicstableitem.h.
Constructor & Destructor Documentation
QetGraphicsTableItem()
QetGraphicsTableItem::QetGraphicsTableItem (QGraphicsItem * parent = nullptr)
QetGraphicsTableItem::QetGraphicsTableItem Default constructor.
Parameters
parent
Definition at line 124 of file qetgraphicstableitem.cpp.
References adjustHandlerPos(), headerSectionResized(), QetGraphicsHeaderItem::heightResized(), m_bounding_rect, m_br_margin, m_header_item, QetGraphicsHeaderItem::rect(), QetGraphicsHeaderItem::sectionResized(), setModel(), and setUpHandler().
~QetGraphicsTableItem()
QetGraphicsTableItem::~QetGraphicsTableItem () override virtual
Definition at line 148 of file qetgraphicstableitem.cpp.
Member Function Documentation
adjustColumnsWidth()
void QetGraphicsTableItem::adjustColumnsWidth () private
QetGraphicsTableItem::adjustColumnsWidth Adjust the size of each column according to the current table width by setting the sectionSize of the header item.
Definition at line 772 of file qetgraphicstableitem.cpp.
References headerSectionResized(), m_current_size, m_header_item, m_minimum_column_width, m_model, QetGraphicsHeaderItem::minimumSectionWidth(), minimumSize(), QetGraphicsHeaderItem::resizeSection(), QetGraphicsHeaderItem::sectionResized(), and QetGraphicsHeaderItem::sectionSize().
Referenced by adjustSize(), and setSize().
adjustHandlerPos()
void QetGraphicsTableItem::adjustHandlerPos () private
QetGraphicsTableItem::adjustHandlerPos Adjust the pos of the handler item.
Definition at line 716 of file qetgraphicstableitem.cpp.
References m_handler_item, and size.
Referenced by hoverEnterEvent(), and QetGraphicsTableItem().
adjustSize()
void QetGraphicsTableItem::adjustSize () private
QetGraphicsTableItem::adjustSize If needed, this function resize the current height and width of table and/or the size of columns. according to there minimum.
Definition at line 848 of file qetgraphicstableitem.cpp.
References adjustColumnsWidth(), m_current_size, m_model, minimumSize(), setSize(), and setUpBoundingRect().
Referenced by dataChanged(), and setModel().
adjustTableToFolio()
void QetGraphicsTableItem::adjustTableToFolio (QetGraphicsTableItem * table, QMargins margins = QMargins(20,20,20,0)) static
QetGraphicsTableItem::adjustTableToFolio Adjust the table to fit at best the folio.
Parameters
table : table to adjust
margins : margins between table and folio.
Definition at line 42 of file qetgraphicstableitem.cpp.
References Diagram::border_and_titleblock, QetGraphicsItem::diagram(), headerItem(), BorderTitleBlock::insideBorderRect(), minimumRowHeigth(), QetGraphicsHeaderItem::rect(), setDisplayNRow(), QetGraphicsItem::setPos(), setSize(), and size.
Referenced by QetGraphicsTableFactory::create(), and GraphicsTablePropertiesEditor::on_m_auto_geometry_pb_clicked().
boundingRect()
QRectF QetGraphicsTableItem::boundingRect () const override virtual
QetGraphicsTableItem::boundingRect Reimplemented from QGraphicsObject.
Returns
Definition at line 196 of file qetgraphicstableitem.cpp.
References m_bounding_rect.
checkInsufficientRowsCount()
void QetGraphicsTableItem::checkInsufficientRowsCount (QetGraphicsTableItem * table) static
QetGraphicsTableItem::checkInsufficientRowsCount Check if the number of rows of table + linked table is enough to display all content of the model, if not open a dialog to advise user what to do.
Parameters
table
Definition at line 72 of file qetgraphicstableitem.cpp.
References QetGraphicsItem::diagram(), displayNRow, QET::QetMessageBox::information(), model(), previousTable(), and QET::Icons::tr.
Referenced by modelReseted().
dataChanged()
void QetGraphicsTableItem::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight, const QVector< int > & roles) private
Definition at line 817 of file qetgraphicstableitem.cpp.
References adjustSize(), and setUpColumnAndRowMinimumSize().
Referenced by modelReseted(), and setModel().
displayNRow()
int QetGraphicsTableItem::displayNRow () const
QetGraphicsTableItem::displayNRow.
Returns
the number of row displayed. A value of 0 or less mean there is no limit
Definition at line 370 of file qetgraphicstableitem.cpp.
References m_number_of_displayed_row.
displayNRowOffset()
int QetGraphicsTableItem::displayNRowOffset () const
QetGraphicsTableItem::displayNRowOffset.
Returns
the offset (aka the last displayed row) of displayed row. If this item have a previous table, the previous offset is added.
Definition at line 454 of file qetgraphicstableitem.cpp.
References displayNRowOffset(), m_number_of_displayed_row, and m_previous_table.
Referenced by displayNRowOffset(), minimumSize(), and paint().
fromXml()
void QetGraphicsTableItem::fromXml (const QDomElement & dom_element)
QetGraphicsTableItem::fromXml Restore the table from xml. Make this item is already in a diagram to.
Parameters
dom_element
Definition at line 550 of file qetgraphicstableitem.cpp.
References QetGraphicsItem::diagram(), QETXML::directChild(), QetGraphicsHeaderItem::fromXml(), m_header_item, m_name, m_number_of_displayed_row, m_pending_previous_table_uuid, m_pending_size, m_uuid, no_model_height, no_model_width, setModel(), QetGraphicsItem::setPos(), QetGraphicsHeaderItem::xmlTagName(), ProjectDBModel::xmlTagName(), and xmlTagName().
handlerMouseMoveEvent()
void QetGraphicsTableItem::handlerMouseMoveEvent (QGraphicsSceneMouseEvent * event) private
Definition at line 739 of file qetgraphicstableitem.cpp.
References m_handler_item, minimumSize(), setSize(), size, and Diagram::snapToGrid().
Referenced by sceneEventFilter().
handlerMousePressEvent()
void QetGraphicsTableItem::handlerMousePressEvent (QGraphicsSceneMouseEvent * event) private
Definition at line 729 of file qetgraphicstableitem.cpp.
References QetGraphicsItem::diagram(), headerSectionResized(), m_header_item, m_old_size, QetGraphicsHeaderItem::sectionResized(), and size.
Referenced by sceneEventFilter().
handlerMouseReleaseEvent()
void QetGraphicsTableItem::handlerMouseReleaseEvent (QGraphicsSceneMouseEvent * event) private
Definition at line 754 of file qetgraphicstableitem.cpp.
References QetGraphicsItem::diagram(), headerSectionResized(), m_header_item, m_old_size, QetGraphicsHeaderItem::sectionResized(), size, QET::Icons::tr, and Diagram::undoStack().
Referenced by sceneEventFilter().
headerItem()
QetGraphicsHeaderItem* QetGraphicsTableItem::headerItem () const inline
Definition at line 65 of file qetgraphicstableitem.h.
References m_header_item.
Referenced by adjustTableToFolio().
headerSectionResized()
void QetGraphicsTableItem::headerSectionResized () private
QetGraphicsTableItem::headerSectionResized Connected to the header signal QetGraphicsTableItem sectionResized.
Definition at line 832 of file qetgraphicstableitem.cpp.
References m_current_size, m_header_item, QetGraphicsHeaderItem::rect(), setUpBoundingRect(), and size.
Referenced by adjustColumnsWidth(), handlerMousePressEvent(), handlerMouseReleaseEvent(), and QetGraphicsTableItem().
hoverEnterEvent()
void QetGraphicsTableItem::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
QetGraphicsTableItem::hoverEnterEvent Reimplemented from QetGraphicsItem.
Parameters
event
Definition at line 587 of file qetgraphicstableitem.cpp.
References adjustHandlerPos(), m_handler_item, and m_model.
hoverLeaveEvent()
void QetGraphicsTableItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
QetGraphicsTableItem::hoverLeaveEvent Reimplemented from QetGraphicsItem.
Parameters
event
Definition at line 603 of file qetgraphicstableitem.cpp.
References m_handler_item, and m_model.
initLink()
void QetGraphicsTableItem::initLink ()
Definition at line 483 of file qetgraphicstableitem.cpp.
References QetGraphicsItem::diagram(), m_pending_previous_table_uuid, m_pending_size, setPreviousTable(), setSize(), and ElementProvider::tableFromUuid().
itemChange()
QVariant QetGraphicsTableItem::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
QetGraphicsTableItem::itemChange.
Parameters
change
value
Returns
Definition at line 648 of file qetgraphicstableitem.cpp.
References m_handler_item.
minimumRowHeigth()
int QetGraphicsTableItem::minimumRowHeigth () const
QetGraphicsTableItem::minimumRowHeigth.
Returns
the minimum height of a row
Definition at line 500 of file qetgraphicstableitem.cpp.
References m_minimum_row_height.
Referenced by adjustTableToFolio().
minimumSize()
QSize QetGraphicsTableItem::minimumSize () const
QetGraphicsTableItem::minimumSize.
Returns
the minimum size the table can be The returned size take care of the table's minimum width, but also the header item's minimum width
Definition at line 329 of file qetgraphicstableitem.cpp.
References displayNRowOffset(), m_minimum_column_width, m_minimum_row_height, m_model, m_number_of_displayed_row, m_previous_table, no_model_height, and no_model_width.
Referenced by adjustColumnsWidth(), adjustSize(), handlerMouseMoveEvent(), and setSize().
model()
QAbstractItemModel * QetGraphicsTableItem::model () const
QetGraphicsTableItem::model.
Returns
The model that this item is presenting
Definition at line 187 of file qetgraphicstableitem.cpp.
References m_model.
Referenced by checkInsufficientRowsCount(), setModel(), GraphicsTablePropertiesEditor::setTable(), and setUpColumnAndRowMinimumSize().
modelReseted()
void QetGraphicsTableItem::modelReseted () private
Definition at line 660 of file qetgraphicstableitem.cpp.
References checkInsufficientRowsCount(), dataChanged(), m_model, previousTable(), and setToMinimumHeight().
Referenced by setModel().
nextTable()
QetGraphicsTableItem * QetGraphicsTableItem::nextTable () const
Definition at line 467 of file qetgraphicstableitem.cpp.
References m_next_table.
paint()
void QetGraphicsTableItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override virtual
QetGraphicsTableItem::paint Draw the table.
Parameters
painter
option
widget
Definition at line 207 of file qetgraphicstableitem.cpp.
References displayNRowOffset(), m_current_size, m_header_item, m_model, m_number_of_displayed_row, m_previous_table, QETUtils::marginsFromString(), QetGraphicsHeaderItem::rect(), QetGraphicsHeaderItem::sectionSize(), and size.
previousTable()
QetGraphicsTableItem * QetGraphicsTableItem::previousTable () const
Definition at line 463 of file qetgraphicstableitem.cpp.
References m_previous_table.
Referenced by checkInsufficientRowsCount(), and modelReseted().
previousTableDisplayRowChanged()
void QetGraphicsTableItem::previousTableDisplayRowChanged () private
Definition at line 876 of file qetgraphicstableitem.cpp.
References m_next_table, previousTableDisplayRowChanged(), and setToMinimumHeight().
Referenced by previousTableDisplayRowChanged(), and setDisplayNRow().
sceneEventFilter()
bool QetGraphicsTableItem::sceneEventFilter (QGraphicsItem * watched, QEvent * event) override protected virtual
QetGraphicsTableItem::sceneEventFilter Reimplemented from QetGraphicsItem.
Parameters
watched
event
Returns
Definition at line 618 of file qetgraphicstableitem.cpp.
References handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), and m_handler_item.
setDisplayNRow()
void QetGraphicsTableItem::setDisplayNRow (const int & number)
QetGraphicsTableItem::setDisplayNRow Limit the number of row to display.
Parameters
number : set to 0 or less to disabled the limit of row to display
Definition at line 358 of file qetgraphicstableitem.cpp.
References m_next_table, m_number_of_displayed_row, previousTableDisplayRowChanged(), and setToMinimumHeight().
Referenced by adjustTableToFolio().
setModel()
void QetGraphicsTableItem::setModel (QAbstractItemModel * model = nullptr)
QetGraphicsTableItem::setModel Set the model presented by this item. Since QetGraphicsTableItem don't take ownership of model, if item already have a model, it's your responsibility to delete it.
Parameters
model
Definition at line 158 of file qetgraphicstableitem.cpp.
References adjustSize(), dataChanged(), m_header_item, m_model, m_next_table, model(), modelReseted(), QetGraphicsHeaderItem::rect(), QetGraphicsHeaderItem::setModel(), setModel(), and setUpColumnAndRowMinimumSize().
Referenced by fromXml(), QetGraphicsTableItem(), setModel(), and setPreviousTable().
setNextTable()
void QetGraphicsTableItem::setNextTable (QetGraphicsTableItem * table = nullptr)
QetGraphicsTableItem::setNextTable Set the next table to table nullptr will remove an existing next table.
Parameters
table
Definition at line 420 of file qetgraphicstableitem.cpp.
References m_next_table, and setPreviousTable().
Referenced by setPreviousTable().
setPreviousTable()
void QetGraphicsTableItem::setPreviousTable (QetGraphicsTableItem * table = nullptr)
QetGraphicsTableItem::setPreviousTable Set the previous table to table. If this table already have a previous table, the previous table will be replaced. Set new table to nullptr to remove an existing previous table. The table uses the model of the new previous table. Since the table does not take ownership of the model, it is your responsibility to manage the old model. Linked tables (table with next and/or previous table) share the same model, a table always take the model of the previous table. When remove a previous table (set to nullptr) from a table, the model is also removed, you need to set a new model.
Parameters
table
Definition at line 389 of file qetgraphicstableitem.cpp.
References m_model, m_previous_table, setModel(), and setNextTable().
Referenced by initLink(), and setNextTable().
setSize()
void QetGraphicsTableItem::setSize (const QSize & size)
QetGraphicsTableItem::setSize Set the current size of the table to size.
Parameters
size
Definition at line 295 of file qetgraphicstableitem.cpp.
References adjustColumnsWidth(), m_current_size, minimumSize(), setUpBoundingRect(), and size.
Referenced by adjustSize(), adjustTableToFolio(), handlerMouseMoveEvent(), initLink(), and setToMinimumHeight().
setTableName()
void QetGraphicsTableItem::setTableName (const QString & name)
Definition at line 441 of file qetgraphicstableitem.cpp.
References m_name, and QetGraphicsItem::name().
setToMinimumHeight()
void QetGraphicsTableItem::setToMinimumHeight ()
QetGraphicsTableItem::setToMinimumHeight Set the height to the the minimum. The width stay unchanged.
Definition at line 476 of file qetgraphicstableitem.cpp.
References setSize(), and size.
Referenced by modelReseted(), previousTableDisplayRowChanged(), and setDisplayNRow().
setUpBoundingRect()
void QetGraphicsTableItem::setUpBoundingRect () private
QetGraphicsTableItem::setUpBoundingRect.
Definition at line 705 of file qetgraphicstableitem.cpp.
References m_bounding_rect, m_br_margin, m_current_size, m_header_item, and QetGraphicsHeaderItem::rect().
Referenced by adjustSize(), headerSectionResized(), and setSize().
setUpColumnAndRowMinimumSize()
void QetGraphicsTableItem::setUpColumnAndRowMinimumSize () private
QetGraphicsTableItem::setUpColumnAndRowMinimumSize Calcule the minimum row height and the minimum column width for each columns this function doesn't change the geometry of the table.
Definition at line 674 of file qetgraphicstableitem.cpp.
References m_header_item, m_minimum_column_width, m_minimum_row_height, m_model, QETUtils::marginsFromString(), QetGraphicsHeaderItem::minimumSectionWidth(), model(), and no_model_height.
Referenced by dataChanged(), and setModel().
setUpHandler()
void QetGraphicsTableItem::setUpHandler () private
QetGraphicsTableItem::setUpHandler.
Definition at line 723 of file qetgraphicstableitem.cpp.
References m_handler_item, and QetGraphicsHandlerItem::setColor().
Referenced by QetGraphicsTableItem().
size()
QSize QetGraphicsTableItem::size () const
QetGraphicsTableItem::size.
Returns
The current size of the table
Definition at line 318 of file qetgraphicstableitem.cpp.
References m_current_size, m_header_item, and QetGraphicsHeaderItem::rect().
tableName()
QString QetGraphicsTableItem::tableName () const
Definition at line 445 of file qetgraphicstableitem.cpp.
References m_name.
toXml()
QDomElement QetGraphicsTableItem::toXml (QDomDocument & dom_document) const
QetGraphicsTableItem::toXml Save the table to xml.
Parameters
dom_document : parent document
Returns
the dom_element that describe the table
Definition at line 510 of file qetgraphicstableitem.cpp.
References m_current_size, m_header_item, m_model, m_name, m_number_of_displayed_row, m_previous_table, m_uuid, QetGraphicsHeaderItem::toXml(), and xmlTagName().
type()
int QetGraphicsTableItem::type () const inline override
Definition at line 58 of file qetgraphicstableitem.h.
References Type.
uuid()
QUuid QetGraphicsTableItem::uuid () const inline
Definition at line 80 of file qetgraphicstableitem.h.
References m_uuid.
xmlTagName()
static QString QetGraphicsTableItem::xmlTagName () inline static
Definition at line 85 of file qetgraphicstableitem.h.
Referenced by fromXml(), Diagram::fromXml(), and toXml().
Member Data Documentation
m_bounding_rect
QRectF QetGraphicsTableItem::m_bounding_rect private
Definition at line 119 of file qetgraphicstableitem.h.
Referenced by boundingRect(), QetGraphicsTableItem(), and setUpBoundingRect().
m_br_margin
int QetGraphicsTableItem::m_br_margin = 10 private
Definition at line 118 of file qetgraphicstableitem.h.
Referenced by QetGraphicsTableItem(), and setUpBoundingRect().
m_current_size
QSize QetGraphicsTableItem::m_current_size private
Definition at line 114 of file qetgraphicstableitem.h.
Referenced by adjustColumnsWidth(), adjustSize(), headerSectionResized(), paint(), setSize(), setUpBoundingRect(), size(), and toXml().
m_handler_item
QetGraphicsHandlerItem QetGraphicsTableItem::m_handler_item private
Definition at line 121 of file qetgraphicstableitem.h.
Referenced by adjustHandlerPos(), handlerMouseMoveEvent(), hoverEnterEvent(), hoverLeaveEvent(), itemChange(), sceneEventFilter(), and setUpHandler().
m_header_item
QetGraphicsHeaderItem* QetGraphicsTableItem::m_header_item = nullptr private
Definition at line 122 of file qetgraphicstableitem.h.
Referenced by adjustColumnsWidth(), fromXml(), handlerMousePressEvent(), handlerMouseReleaseEvent(), headerItem(), headerSectionResized(), paint(), QetGraphicsTableItem(), setModel(), setUpBoundingRect(), setUpColumnAndRowMinimumSize(), size(), and toXml().
m_minimum_column_width
QVector<int> QetGraphicsTableItem::m_minimum_column_width private
Definition at line 111 of file qetgraphicstableitem.h.
Referenced by adjustColumnsWidth(), minimumSize(), and setUpColumnAndRowMinimumSize().
m_minimum_row_height
int QetGraphicsTableItem::m_minimum_row_height private
Definition at line 112 of file qetgraphicstableitem.h.
Referenced by minimumRowHeigth(), minimumSize(), and setUpColumnAndRowMinimumSize().
m_model
QAbstractItemModel* QetGraphicsTableItem::m_model = nullptr private
Definition at line 109 of file qetgraphicstableitem.h.
Referenced by adjustColumnsWidth(), adjustSize(), hoverEnterEvent(), hoverLeaveEvent(), minimumSize(), model(), modelReseted(), paint(), setModel(), setPreviousTable(), setUpColumnAndRowMinimumSize(), and toXml().
m_name
QString QetGraphicsTableItem::m_name private
Definition at line 127 of file qetgraphicstableitem.h.
Referenced by fromXml(), setTableName(), tableName(), and toXml().
m_next_table
QetGraphicsTableItem * QetGraphicsTableItem::m_next_table = nullptr private
Definition at line 125 of file qetgraphicstableitem.h.
Referenced by nextTable(), previousTableDisplayRowChanged(), setDisplayNRow(), setModel(), and setNextTable().
m_number_of_displayed_row
int QetGraphicsTableItem::m_number_of_displayed_row = 0 private
Definition at line 113 of file qetgraphicstableitem.h.
Referenced by displayNRow(), displayNRowOffset(), fromXml(), minimumSize(), paint(), setDisplayNRow(), and toXml().
m_old_size
QSize QetGraphicsTableItem::m_old_size private
Definition at line 115 of file qetgraphicstableitem.h.
Referenced by handlerMousePressEvent(), and handlerMouseReleaseEvent().
m_pending_previous_table_uuid
QUuid QetGraphicsTableItem::m_pending_previous_table_uuid private
Definition at line 129 of file qetgraphicstableitem.h.
Referenced by fromXml(), and initLink().
m_pending_size
QSize QetGraphicsTableItem::m_pending_size private
Definition at line 116 of file qetgraphicstableitem.h.
Referenced by fromXml(), and initLink().
m_previous_table
QetGraphicsTableItem* QetGraphicsTableItem::m_previous_table = nullptr private
Definition at line 124 of file qetgraphicstableitem.h.
Referenced by displayNRowOffset(), minimumSize(), paint(), previousTable(), setPreviousTable(), and toXml().
m_uuid
QUuid QetGraphicsTableItem::m_uuid = QUuid::createUuid() private
Definition at line 128 of file qetgraphicstableitem.h.
Referenced by fromXml(), toXml(), and uuid().
Property Documentation
displayNRow
int QetGraphicsTableItem::displayNRow read write
Definition at line 1 of file qetgraphicstableitem.h.
Referenced by checkInsufficientRowsCount().
size
QSize QetGraphicsTableItem::size read write
Definition at line 1 of file qetgraphicstableitem.h.
Referenced by adjustHandlerPos(), adjustTableToFolio(), handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), headerSectionResized(), paint(), setSize(), and setToMinimumHeight().
The documentation for this class was generated from the following files:
qetgraphicstableitem.h
qetgraphicstableitem.cpp