QElectroTech: ElementQueryWidget Class Reference
ElementQueryWidget Class Reference
The ElementQueryWidget class A widget use to edit a sql query for get element information This widget only work to get information from ProjectDataBase.
#include <elementquerywidget.h>
Public Member Functions
ElementQueryWidget (QWidget *parent=nullptr)
ElementQueryWidget::ElementQueryWidget.
~ElementQueryWidget ()
ElementQueryWidget::~ElementQueryWidget.
void setQuery (const QString &query)
ElementQueryWidget::setQuery.
QString queryStr () const
ElementQueryWidget::queryStr.
void setGroupBy (QString text, bool set=true)
ElementQueryWidget::setGroupBy Add the query instruction GROUP BY.
void setCount (QString text, bool set=true)
ElementQueryWidget::setCount Add the query instruction COUNT. Unlike setGroupBy, you have to write the entire sentance. ex : text = "COUNT(*) AS designation_qty". the query will contain what you write.
Static Public Member Functions
static QString modelIdentifier ()
Private Slots
void on_m_up_pb_clicked ()
ElementQueryWidget::on_m_up_pb_clicked.
void on_m_add_pb_clicked ()
ElementQueryWidget::on_m_add_pb_clicked.
void on_m_remove_pb_clicked ()
ElementQueryWidget::on_m_remove_pb_clicked.
void on_m_down_pb_clicked ()
ElementQueryWidget::on_m_down_pb_clicked.
void on_m_edit_sql_query_cb_clicked ()
ElementQueryWidget::on_m_edit_sql_query_cb_clicked.
void on_m_filter_le_textEdited (const QString &arg1)
ElementQueryWidget::on_m_filter_le_textEdited.
void on_m_filter_type_cb_activated (int index)
ElementQueryWidget::on_m_filter_type_cb_activated.
void on_m_load_pb_clicked ()
ElementQueryWidget::on_m_load_pb_clicked Load a query from nomenclature.json file.
void on_m_save_current_conf_pb_clicked ()
ElementQueryWidget::on_m_save_current_conf_pb_clicked Save the actual query to nomenclature.json file.
void on_m_save_name_le_textChanged (const QString &arg1)
void on_m_choosen_list_currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous)
void on_m_var_list_itemDoubleClicked (QListWidgetItem *item)
void on_m_choosen_list_itemDoubleClicked (QListWidgetItem *item)
void updateQueryLine ()
ElementQueryWidget::updateQueryLine.
QStringList selectedKeys () const
ElementQueryWidget::selectedKeys.
void setUpItems ()
ElementQueryWidget::setUpItems.
QPair< int, QString > FilterFor (const QString &key) const
ElementQueryWidget::FilterFor.
void fillSavedQuery ()
ElementQueryWidget::fillSavedQuery Fill the combobox of saved queries.
void reset ()
ElementQueryWidget::reset Clear this widget aka set to initial state.
Private Attributes
Ui::ElementQueryWidget * ui
QHash< QString, QString > m_export_info
QButtonGroup m_button_group
QList< QListWidgetItem * > m_items_list
QString m_custom_query
QString m_group_by
QString m_count
QHash< QString, QPair< int, QString > > m_filter
Detailed Description
The ElementQueryWidget class A widget use to edit a sql query for get element information This widget only work to get information from ProjectDataBase.
Definition at line 35 of file elementquerywidget.h.
Constructor & Destructor Documentation
ElementQueryWidget()
ElementQueryWidget::ElementQueryWidget (QWidget * parent = nullptr) explicit
ElementQueryWidget::ElementQueryWidget.
Parameters
parent
Definition at line 28 of file elementquerywidget.cpp.
References m_button_group, m_export_info, QET::Icons::tr, ui, and updateQueryLine().
~ElementQueryWidget()
ElementQueryWidget::~ElementQueryWidget ()
ElementQueryWidget::~ElementQueryWidget.
Definition at line 101 of file elementquerywidget.cpp.
References ui.
Member Function Documentation
fillSavedQuery
void ElementQueryWidget::fillSavedQuery () private slot
ElementQueryWidget::fillSavedQuery Fill the combobox of saved queries.
Definition at line 475 of file elementquerywidget.cpp.
References QETApp::configDir(), QET::Icons::it, and ui.
FilterFor
QPair< int, QString > ElementQueryWidget::FilterFor (const QString & key) const private slot
ElementQueryWidget::FilterFor.
Parameters
key
Returns
the filter associated to key
Definition at line 467 of file elementquerywidget.cpp.
References m_filter.
Referenced by on_m_choosen_list_currentItemChanged(), and queryStr().
modelIdentifier()
static QString ElementQueryWidget::modelIdentifier () inline static
Definition at line 48 of file elementquerywidget.h.
on_m_add_pb_clicked
void ElementQueryWidget::on_m_add_pb_clicked () private slot
ElementQueryWidget::on_m_add_pb_clicked.
Definition at line 509 of file elementquerywidget.cpp.
References ui, and updateQueryLine().
Referenced by on_m_var_list_itemDoubleClicked().
on_m_choosen_list_currentItemChanged
void ElementQueryWidget::on_m_choosen_list_currentItemChanged (QListWidgetItem * current, QListWidgetItem * previous) private slot
Definition at line 667 of file elementquerywidget.cpp.
References FilterFor(), and ui.
on_m_choosen_list_itemDoubleClicked
void ElementQueryWidget::on_m_choosen_list_itemDoubleClicked (QListWidgetItem * item) private slot
Definition at line 686 of file elementquerywidget.cpp.
References on_m_remove_pb_clicked().
on_m_down_pb_clicked
void ElementQueryWidget::on_m_down_pb_clicked () private slot
ElementQueryWidget::on_m_down_pb_clicked.
Definition at line 533 of file elementquerywidget.cpp.
References ui, and updateQueryLine().
on_m_edit_sql_query_cb_clicked
void ElementQueryWidget::on_m_edit_sql_query_cb_clicked () private slot
ElementQueryWidget::on_m_edit_sql_query_cb_clicked.
Definition at line 550 of file elementquerywidget.cpp.
References m_custom_query, ui, and updateQueryLine().
on_m_filter_le_textEdited
void ElementQueryWidget::on_m_filter_le_textEdited (const QString & arg1) private slot
ElementQueryWidget::on_m_filter_le_textEdited.
Parameters
arg1
Definition at line 571 of file elementquerywidget.cpp.
References m_filter, ui, and updateQueryLine().
on_m_filter_type_cb_activated
void ElementQueryWidget::on_m_filter_type_cb_activated (int index) private slot
ElementQueryWidget::on_m_filter_type_cb_activated.
Parameters
index
Definition at line 588 of file elementquerywidget.cpp.
References m_filter, ui, and updateQueryLine().
on_m_load_pb_clicked
void ElementQueryWidget::on_m_load_pb_clicked () private slot
ElementQueryWidget::on_m_load_pb_clicked Load a query from nomenclature.json file.
Definition at line 606 of file elementquerywidget.cpp.
References QETApp::configDir(), setQuery(), and ui.
on_m_remove_pb_clicked
void ElementQueryWidget::on_m_remove_pb_clicked () private slot
ElementQueryWidget::on_m_remove_pb_clicked.
Definition at line 521 of file elementquerywidget.cpp.
References ui, and updateQueryLine().
Referenced by on_m_choosen_list_itemDoubleClicked().
on_m_save_current_conf_pb_clicked
void ElementQueryWidget::on_m_save_current_conf_pb_clicked () private slot
ElementQueryWidget::on_m_save_current_conf_pb_clicked Save the actual query to nomenclature.json file.
Definition at line 636 of file elementquerywidget.cpp.
References QETApp::configDir(), queryStr(), and ui.
on_m_save_name_le_textChanged
void ElementQueryWidget::on_m_save_name_le_textChanged (const QString & arg1) private slot
Definition at line 663 of file elementquerywidget.cpp.
References ui.
on_m_up_pb_clicked
void ElementQueryWidget::on_m_up_pb_clicked () private slot
ElementQueryWidget::on_m_up_pb_clicked.
Definition at line 492 of file elementquerywidget.cpp.
References ui, and updateQueryLine().
on_m_var_list_itemDoubleClicked
void ElementQueryWidget::on_m_var_list_itemDoubleClicked (QListWidgetItem * item) private slot
Definition at line 681 of file elementquerywidget.cpp.
References on_m_add_pb_clicked().
queryStr()
QString ElementQueryWidget::queryStr () const
ElementQueryWidget::queryStr.
Returns
The current query
Definition at line 277 of file elementquerywidget.cpp.
References FilterFor(), m_count, m_group_by, selectedKeys(), and ui.
Referenced by BOMExportDialog::getBom(), ProjectDBModelPropertiesWidget::on_m_edit_query_pb_clicked(), on_m_save_current_conf_pb_clicked(), and updateQueryLine().
reset
void ElementQueryWidget::reset () private slot
ElementQueryWidget::reset Clear this widget aka set to initial state.
Definition at line 695 of file elementquerywidget.cpp.
References m_filter, and ui.
Referenced by setQuery().
selectedKeys
QStringList ElementQueryWidget::selectedKeys () const private slot
ElementQueryWidget::selectedKeys.
Returns
the current keys of selected infos to be exported
Definition at line 424 of file elementquerywidget.cpp.
References ui.
Referenced by queryStr().
setCount()
void ElementQueryWidget::setCount (QString text, bool set = true)
ElementQueryWidget::setCount Add the query instruction COUNT. Unlike setGroupBy, you have to write the entire sentance. ex : text = "COUNT(*) AS designation_qty". the query will contain what you write.
Parameters
text : the count instruction
set : true by default -> count will be used. false -> count will be not used.
Definition at line 403 of file elementquerywidget.cpp.
References m_count, and updateQueryLine().
Referenced by BOMExportDialog::on_m_format_as_bom_clicked().
setGroupBy()
void ElementQueryWidget::setGroupBy (QString text, bool set = true)
ElementQueryWidget::setGroupBy Add the query instruction GROUP BY.
Parameters
text : the text of the GROUP BY instruction: ex : if text = designation, the query will contain "GROUP BY designation"
set : true by default -> GROUP BY will be used. false -> GROUP BY will be not used
Definition at line 382 of file elementquerywidget.cpp.
References m_group_by, and updateQueryLine().
Referenced by BOMExportDialog::on_m_format_as_bom_clicked().
setQuery()
void ElementQueryWidget::setQuery (const QString & query)
ElementQueryWidget::setQuery.
Parameters
query Set the current query to query. If it's possible, rebuild the state of the widget from the query
Definition at line 111 of file elementquerywidget.cpp.
References m_button_group, m_filter, m_items_list, reset(), and ui.
Referenced by ProjectDBModelPropertiesWidget::on_m_edit_query_pb_clicked(), and on_m_load_pb_clicked().
setUpItems
void ElementQueryWidget::setUpItems () private slot
ElementQueryWidget::setUpItems.
Definition at line 441 of file elementquerywidget.cpp.
References QETApp::elementInfoKeys(), QETApp::elementTranslatedInfoKey(), m_export_info, m_items_list, and ui.
updateQueryLine
void ElementQueryWidget::updateQueryLine () private slot
ElementQueryWidget::updateQueryLine.
Definition at line 416 of file elementquerywidget.cpp.
References queryStr(), and ui.
Referenced by ElementQueryWidget(), on_m_add_pb_clicked(), on_m_down_pb_clicked(), on_m_edit_sql_query_cb_clicked(), on_m_filter_le_textEdited(), on_m_filter_type_cb_activated(), on_m_remove_pb_clicked(), on_m_up_pb_clicked(), setCount(), and setGroupBy().
Member Data Documentation
m_button_group
QButtonGroup ElementQueryWidget::m_button_group private
Definition at line 77 of file elementquerywidget.h.
Referenced by ElementQueryWidget(), and setQuery().
m_count
QString ElementQueryWidget::m_count private
Definition at line 81 of file elementquerywidget.h.
Referenced by queryStr(), and setCount().
m_custom_query
QString ElementQueryWidget::m_custom_query private
Definition at line 79 of file elementquerywidget.h.
Referenced by on_m_edit_sql_query_cb_clicked().
m_export_info
QHash<QString, QString> ElementQueryWidget::m_export_info private
Definition at line 76 of file elementquerywidget.h.
Referenced by ElementQueryWidget(), and setUpItems().
m_filter
QHash<QString, QPair<int, QString> > ElementQueryWidget::m_filter private
Definition at line 82 of file elementquerywidget.h.
Referenced by FilterFor(), on_m_filter_le_textEdited(), on_m_filter_type_cb_activated(), reset(), and setQuery().
m_group_by
QString ElementQueryWidget::m_group_by private
Definition at line 80 of file elementquerywidget.h.
Referenced by queryStr(), and setGroupBy().
m_items_list
QList<QListWidgetItem *> ElementQueryWidget::m_items_list private
Definition at line 78 of file elementquerywidget.h.
Referenced by setQuery(), and setUpItems().
ui
Ui::ElementQueryWidget* ElementQueryWidget::ui private
Definition at line 75 of file elementquerywidget.h.
Referenced by ElementQueryWidget(), fillSavedQuery(), on_m_add_pb_clicked(), on_m_choosen_list_currentItemChanged(), on_m_down_pb_clicked(), on_m_edit_sql_query_cb_clicked(), on_m_filter_le_textEdited(), on_m_filter_type_cb_activated(), on_m_load_pb_clicked(), on_m_remove_pb_clicked(), on_m_save_current_conf_pb_clicked(), on_m_save_name_le_textChanged(), on_m_up_pb_clicked(), queryStr(), reset(), selectedKeys(), setQuery(), setUpItems(), updateQueryLine(), and ~ElementQueryWidget().
The documentation for this class was generated from the following files:
elementquerywidget.h
elementquerywidget.cpp