QElectroTech: RotateSelectionCommand Class Reference
RotateSelectionCommand Class Reference
The RotateSelectionCommand class Rotate the selected items in the given diagram.
#include <rotateselectioncommand.h>
Public Member Functions
RotateSelectionCommand (Diagram *diagram, qreal angle=90, QUndoCommand *parent=nullptr)
void undo () override
RotateSelectionCommand::undo.
void redo () override
RotateSelectionCommand::redo.
bool isValid ()
RotateSelectionCommand::isValid.
Private Attributes
Diagram * m_diagram =nullptr
QList< QPointer< ConductorTextItem > > m_cond_text
QHash< ConductorTextItem *, bool > m_rotate_by_user
QList< QPropertyUndoCommand * > m_undo
Detailed Description
The RotateSelectionCommand class Rotate the selected items in the given diagram.
Definition at line 32 of file rotateselectioncommand.h.
Constructor & Destructor Documentation
RotateSelectionCommand()
RotateSelectionCommand::RotateSelectionCommand (Diagram * diagram, qreal angle = 90, QUndoCommand * parent = nullptr)
Definition at line 32 of file rotateselectioncommand.cpp.
References Diagram::isReadOnly(), m_diagram, m_undo, QET::Icons::tr, IndependentTextItem::Type, DiagramImageItem::Type, ConductorTextItem::Type, DynamicElementTextItem::Type, Element::Type, and undo().
Member Function Documentation
isValid()
bool RotateSelectionCommand::isValid ()
RotateSelectionCommand::isValid.
Returns
true if this command rotate a least one item.
Definition at line 117 of file rotateselectioncommand.cpp.
Referenced by QETDiagramEditor::selectionGroupTriggered().
redo()
void RotateSelectionCommand::redo () override
RotateSelectionCommand::redo.
Definition at line 101 of file rotateselectioncommand.cpp.
References m_cond_text, m_diagram, m_rotate_by_user, and Diagram::showMe().
undo()
void RotateSelectionCommand::undo () override
RotateSelectionCommand::undo.
Definition at line 85 of file rotateselectioncommand.cpp.
References m_cond_text, m_diagram, m_rotate_by_user, and Diagram::showMe().
Referenced by RotateSelectionCommand().
Member Data Documentation
m_cond_text
QList<QPointer<ConductorTextItem> > RotateSelectionCommand::m_cond_text private
Definition at line 44 of file rotateselectioncommand.h.
Referenced by redo(), and undo().
m_diagram
Diagram* RotateSelectionCommand::m_diagram =nullptr private
Definition at line 42 of file rotateselectioncommand.h.
Referenced by redo(), RotateSelectionCommand(), and undo().
m_rotate_by_user
QHash<ConductorTextItem *, bool> RotateSelectionCommand::m_rotate_by_user private
Definition at line 45 of file rotateselectioncommand.h.
Referenced by redo(), and undo().
m_undo
QList<QPropertyUndoCommand*> RotateSelectionCommand::m_undo private
Definition at line 46 of file rotateselectioncommand.h.
Referenced by RotateSelectionCommand().
The documentation for this class was generated from the following files:
rotateselectioncommand.h
rotateselectioncommand.cpp