QElectroTech: projectDataBase Class Reference
projectDataBase Class Reference
The projectDataBase class This class wrap a sqlite data base where you can find several thing about the content of a project.
#include <projectdatabase.h>
Signals
void dataBaseUpdated ()
Public Member Functions
projectDataBase (QETProject *project, QObject *parent=nullptr)
projectDataBase::projectDataBase Default constructor
virtual ~projectDataBase () override
projectDataBase::~projectDataBase Destructor
void updateDB ()
projectDataBase::updateDB Up to date the content of the data base. Emit the signal dataBaseUpdated
QETProject * project () const
projectDataBase::project
QSqlQuery newQuery (const QString &query=QString())
projectDataBase::newQuery
void addElement (Element *element)
projectDataBase::addElement
void removeElement (Element *element)
projectDataBase::removeElement
void elementInfoChanged (Element *element)
projectDataBase::elementInfoChanged
void addDiagram (Diagram *diagram)
void removeDiagram (Diagram *diagram)
Static Public Member Functions
static void exportDb (projectDataBase *db, QWidget *parent=nullptr, const QString &caption=QString(), const QString &dir=QString())
projectDataBase::exportDb
Private Member Functions
projectDataBase (QETProject *project, const QString &connection_name, const QString &path, QObject *parent=nullptr)
bool createDataBase (const QString &connection_name=QString(), const QString &name=QString())
projectDataBase::createDataBase Create the data base
void createElementNomenclatureView ()
projectDataBase::createElementNomenclatureView
void createSummaryView ()
projectDataBase::createSummaryView
void populateDiagramTable ()
void populateElementTable ()
projectDataBase::populateElementTable Populate the element table
void populateElementInfoTable ()
projectDataBase::populateElementsTable Populate the elements table
void populateDiagramInfoTable ()
void prepareQuery ()
Static Private Member Functions
static QHash< QString, QString > elementInfoToString (Element *elmt)
projectDataBase::elementInfoToString
Private Attributes
QPointer< QETProject > m_project
QSqlDatabase m_data_base
QSqlQuery m_insert_elements_query
QSqlQuery m_insert_element_info_query
QSqlQuery m_remove_element_query
QSqlQuery m_update_element_query
QSqlQuery m_insert_diagram_query
QSqlQuery m_remove_diagram_query
QSqlQuery m_insert_diagram_info_query
Detailed Description
The projectDataBase class This class wrap a sqlite data base where you can find several thing about the content of a project.
Note
this class is still in developement.
Definition at line 38 of file projectdatabase.h.
Constructor & Destructor Documentation
projectDataBase() [1/2]
projectDataBase::projectDataBase (QETProject * project, QObject * parent = nullptr)
projectDataBase::projectDataBase Default constructor
Parameters
project : project from the database work
parent : parent QObject
Definition at line 34 of file projectdatabase.cpp.
References createDataBase().
projectDataBase() [2/2]
projectDataBase::projectDataBase (QETProject * project, const QString & connection_name, const QString & path, QObject * parent = nullptr) private
Definition at line 41 of file projectdatabase.cpp.
References createDataBase().
~projectDataBase()
projectDataBase::~projectDataBase () override virtual
projectDataBase::~projectDataBase Destructor
Definition at line 52 of file projectdatabase.cpp.
References m_data_base.
Member Function Documentation
addDiagram()
void projectDataBase::addDiagram (Diagram * diagram)
Definition at line 150 of file projectdatabase.cpp.
References Diagram::border_and_titleblock, dataBaseUpdated(), QETApp::diagramInfoKeys(), m_insert_diagram_info_query, m_insert_diagram_query, m_project, BorderTitleBlock::titleblockInformation(), and Diagram::uuid().
Referenced by QETProject::addDiagram().
addElement()
void projectDataBase::addElement (Element * element)
projectDataBase::addElement
Parameters
element
Definition at line 91 of file projectdatabase.cpp.
References Diagram::convertPosition(), dataBaseUpdated(), QetGraphicsItem::diagram(), elementInfoToString(), Element::kindInformations(), Element::linkTypeToString(), m_insert_element_info_query, m_insert_elements_query, DiagramPosition::toString(), Element::uuid(), and Diagram::uuid().
Referenced by Diagram::addItem().
createDataBase()
bool projectDataBase::createDataBase (const QString & connection_name = QString(), const QString & name = QString()) private
projectDataBase::createDataBase Create the data base
Returns
: true if the data base was successfully created.
Definition at line 194 of file projectdatabase.cpp.
References createElementNomenclatureView(), createSummaryView(), QETApp::diagramInfoKeys(), QETApp::elementInfoKeys(), m_data_base, m_project, prepareQuery(), and updateDB().
Referenced by projectDataBase().
createElementNomenclatureView()
void projectDataBase::createElementNomenclatureView () private
projectDataBase::createElementNomenclatureView
Definition at line 291 of file projectdatabase.cpp.
References m_data_base.
Referenced by createDataBase().
createSummaryView()
void projectDataBase::createSummaryView () private
projectDataBase::createSummaryView
Definition at line 328 of file projectdatabase.cpp.
References m_data_base.
Referenced by createDataBase().
dataBaseUpdated
void projectDataBase::dataBaseUpdated () signal
Referenced by addDiagram(), addElement(), elementInfoChanged(), ProjectDBModel::ProjectDBModel(), removeDiagram(), removeElement(), ProjectDBModel::setQuery(), and updateDB().
elementInfoChanged()
void projectDataBase::elementInfoChanged (Element * element)
projectDataBase::elementInfoChanged
Parameters
element
Definition at line 136 of file projectdatabase.cpp.
References dataBaseUpdated(), QETApp::elementInfoKeys(), elementInfoToString(), m_update_element_query, and Element::uuid().
Referenced by ChangeElementInformationCommand::updateProjectDB().
elementInfoToString()
QHash< QString, QString > projectDataBase::elementInfoToString (Element * elmt) static private
projectDataBase::elementInfoToString
Parameters
elmt
Returns
the element information in hash as key for the info name and value as the information value.
Definition at line 514 of file projectdatabase.cpp.
References Element::actualLabel(), QETApp::elementInfoKeys(), and Element::elementInformations().
Referenced by addElement(), elementInfoChanged(), and populateElementInfoTable().
exportDb()
void projectDataBase::exportDb (projectDataBase * db, QWidget * parent = nullptr, const QString & caption = QString(), const QString & dir = QString()) static
projectDataBase::exportDb
Parameters
db
parent
caption
dir
Definition at line 537 of file projectdatabase.cpp.
References QETProject::filePath(), project(), QET::Icons::tr, and QETProject::uuid().
Referenced by QETDiagramEditor::setUpActions().
newQuery()
QSqlQuery projectDataBase::newQuery (const QString & query = QString())
projectDataBase::newQuery
Returns
a QSqlquery with query as query and the internal database of this class as database to use.
Definition at line 83 of file projectdatabase.cpp.
References m_data_base.
Referenced by BOMExportDialog::getBom().
populateDiagramInfoTable()
void projectDataBase::populateDiagramInfoTable () private
Definition at line 424 of file projectdatabase.cpp.
References QETApp::diagramInfoKeys(), m_data_base, m_insert_diagram_info_query, and m_project.
Referenced by updateDB().
populateDiagramTable()
void projectDataBase::populateDiagramTable () private
Definition at line 348 of file projectdatabase.cpp.
References m_data_base, m_insert_diagram_query, and m_project.
Referenced by updateDB().
populateElementInfoTable()
void projectDataBase::populateElementInfoTable () private
projectDataBase::populateElementsTable Populate the elements table
Definition at line 395 of file projectdatabase.cpp.
References elementInfoToString(), ElementProvider::find(), m_data_base, m_insert_element_info_query, m_project, Element::Master, Element::Simple, and Element::Terminale.
Referenced by updateDB().
populateElementTable()
void projectDataBase::populateElementTable () private
projectDataBase::populateElementTable Populate the element table
Definition at line 367 of file projectdatabase.cpp.
References ElementProvider::find(), m_data_base, m_insert_elements_query, m_project, Element::Master, Element::Simple, and Element::Terminale.
Referenced by updateDB().
prepareQuery()
void projectDataBase::prepareQuery () private
Definition at line 451 of file projectdatabase.cpp.
References QETApp::diagramInfoKeys(), QETApp::elementInfoKeys(), m_data_base, m_insert_diagram_info_query, m_insert_diagram_query, m_insert_element_info_query, m_insert_elements_query, m_remove_diagram_query, m_remove_element_query, and m_update_element_query.
Referenced by createDataBase().
project()
QETProject * projectDataBase::project () const
projectDataBase::project
Returns
the project of this database
Definition at line 74 of file projectdatabase.cpp.
References m_project.
Referenced by exportDb().
removeDiagram()
void projectDataBase::removeDiagram (Diagram * diagram)
Definition at line 179 of file projectdatabase.cpp.
References dataBaseUpdated(), m_remove_diagram_query, and Diagram::uuid().
Referenced by QETProject::removeDiagram().
removeElement()
void projectDataBase::removeElement (Element * element)
projectDataBase::removeElement
Parameters
element
Definition at line 122 of file projectdatabase.cpp.
References dataBaseUpdated(), m_remove_element_query, and Element::uuid().
Referenced by Diagram::removeItem().
updateDB()
void projectDataBase::updateDB ()
projectDataBase::updateDB Up to date the content of the data base. Emit the signal dataBaseUpdated
Definition at line 61 of file projectdatabase.cpp.
References dataBaseUpdated(), populateDiagramInfoTable(), populateDiagramTable(), populateElementInfoTable(), and populateElementTable().
Referenced by createDataBase(), BOMExportDialog::getBom(), ProjectDBModelPropertiesWidget::on_m_refresh_pb_clicked(), QETProject::readDiagramsXml(), and QETProject::readProjectXml().
Member Data Documentation
m_data_base
QSqlDatabase projectDataBase::m_data_base private
Definition at line 79 of file projectdatabase.h.
Referenced by createDataBase(), createElementNomenclatureView(), createSummaryView(), newQuery(), populateDiagramInfoTable(), populateDiagramTable(), populateElementInfoTable(), populateElementTable(), prepareQuery(), and ~projectDataBase().
m_insert_diagram_info_query
QSqlQuery projectDataBase::m_insert_diagram_info_query private
Definition at line 86 of file projectdatabase.h.
Referenced by addDiagram(), populateDiagramInfoTable(), and prepareQuery().
m_insert_diagram_query
QSqlQuery projectDataBase::m_insert_diagram_query private
Definition at line 84 of file projectdatabase.h.
Referenced by addDiagram(), populateDiagramTable(), and prepareQuery().
m_insert_element_info_query
QSqlQuery projectDataBase::m_insert_element_info_query private
Definition at line 81 of file projectdatabase.h.
Referenced by addElement(), populateElementInfoTable(), and prepareQuery().
m_insert_elements_query
QSqlQuery projectDataBase::m_insert_elements_query private
Definition at line 80 of file projectdatabase.h.
Referenced by addElement(), populateElementTable(), and prepareQuery().
m_project
QPointer<QETProject> projectDataBase::m_project private
Definition at line 78 of file projectdatabase.h.
Referenced by addDiagram(), createDataBase(), populateDiagramInfoTable(), populateDiagramTable(), populateElementInfoTable(), populateElementTable(), and project().
m_remove_diagram_query
QSqlQuery projectDataBase::m_remove_diagram_query private
Definition at line 85 of file projectdatabase.h.
Referenced by prepareQuery(), and removeDiagram().
m_remove_element_query
QSqlQuery projectDataBase::m_remove_element_query private
Definition at line 82 of file projectdatabase.h.
Referenced by prepareQuery(), and removeElement().
m_update_element_query
QSqlQuery projectDataBase::m_update_element_query private
Definition at line 83 of file projectdatabase.h.
Referenced by elementInfoChanged(), and prepareQuery().
The documentation for this class was generated from the following files:
projectdatabase.h
projectdatabase.cpp