QElectroTech: NewElementWizard Class Reference
NewElementWizard Class Reference
#include <newelementwizard.h>
Public Member Functions
NewElementWizard (QWidget *=nullptr, Qt::WindowFlags=Qt::Widget)
~NewElementWizard () override
void preselectedLocation (const ElementsLocation &location)
NewElementWizard::preselectedLocation Select item in the tree view represented by location,.
Private Types
enum WizardState { Category, Filename, Names }
Private Member Functions
NewElementWizard (const NewElementWizard &)
QWizardPage * buildStep1 ()
NewElementWizard::buildStep1.
QWizardPage * buildStep2 ()
NewElementWizard::buildStep2.
QWizardPage * buildStep3 ()
NewElementWizard::buildStep3.
bool validStep1 ()
NewElementWizard::validStep1 Valid the setp 1.
bool validStep2 ()
NewElementWizard::validStep2 Valid the step 2.
bool validateCurrentPage () override
NewElementWizard::validateCurrentPage.
void createNewElement ()
NewElementWizard::createNewElement Lauch an element editor for create the new element.
Private Attributes
QFileNameEdit * m_qle_filename
NameListWidget * m_names_list
QString m_chosen_file
QTreeView * m_tree_view = nullptr
ElementsLocation m_chosen_location
ElementsCollectionModel * m_model = nullptr
Detailed Description
This class provides a wizard dialog enabling users to to specify the basic parameters of the electrical elements they intend to draw.
These parameters include:
the category the element should be saved to
the filename the element should be saved to
localized names
Definition at line 38 of file newelementwizard.h.
Member Enumeration Documentation
WizardState
enum NewElementWizard::WizardState private
Enumerator
Category
Filename
Names
Definition at line 54 of file newelementwizard.h.
Constructor & Destructor Documentation
NewElementWizard() [1/2]
NewElementWizard::NewElementWizard (QWidget * parent = nullptr, Qt::WindowFlags f = Qt::Widget)
Constructeur
Parameters
parent QWidget parent de ce dialogue
f flags pour le dialogue
Definition at line 31 of file newelementwizard.cpp.
References buildStep1(), buildStep2(), buildStep3(), and QET::Icons::tr.
~NewElementWizard()
NewElementWizard::~NewElementWizard () override
Destructeur
Definition at line 54 of file newelementwizard.cpp.
NewElementWizard() [2/2]
NewElementWizard::NewElementWizard (const NewElementWizard &) private
Member Function Documentation
buildStep1()
QWizardPage * NewElementWizard::buildStep1 () private
NewElementWizard::buildStep1.
Returns
Definition at line 75 of file newelementwizard.cpp.
References ElementsCollectionModel::addCustomCollection(), Category, ElementsCollectionModel::hideElement(), m_model, m_tree_view, and QET::Icons::tr.
Referenced by NewElementWizard().
buildStep2()
QWizardPage * NewElementWizard::buildStep2 () private
NewElementWizard::buildStep2.
Returns
Definition at line 102 of file newelementwizard.cpp.
References Filename, m_qle_filename, and QET::Icons::tr.
Referenced by NewElementWizard().
buildStep3()
QWizardPage * NewElementWizard::buildStep3 () private
NewElementWizard::buildStep3.
Returns
Definition at line 126 of file newelementwizard.cpp.
References NamesList::addName(), m_names_list, Names, and QET::Icons::tr.
Referenced by NewElementWizard().
createNewElement()
void NewElementWizard::createNewElement () private
NewElementWizard::createNewElement Lauch an element editor for create the new element.
Definition at line 236 of file newelementwizard.cpp.
References ElementsLocation::addToPath(), m_chosen_file, m_chosen_location, and m_names_list.
Referenced by validateCurrentPage().
preselectedLocation()
void NewElementWizard::preselectedLocation (const ElementsLocation & location)
NewElementWizard::preselectedLocation Select item in the tree view represented by location,.
Parameters
location
Definition at line 62 of file newelementwizard.cpp.
References ElementsCollectionModel::indexFromLocation(), m_model, and m_tree_view.
Referenced by ElementsCollectionWidget::newElement().
validateCurrentPage()
bool NewElementWizard::validateCurrentPage () override private
NewElementWizard::validateCurrentPage.
Returns
true if the current step is valid
Definition at line 147 of file newelementwizard.cpp.
References Category, createNewElement(), Filename, NameListWidget::isEmpty(), m_names_list, Names, validStep1(), and validStep2().
validStep1()
bool NewElementWizard::validStep1 () private
NewElementWizard::validStep1 Valid the setp 1.
Returns
trie if the step is valid.
Definition at line 173 of file newelementwizard.cpp.
References ElementCollectionItem::collectionPath(), QET::QetMessageBox::critical(), ElementsLocation::exist(), ElementCollectionItem::isDir(), m_chosen_location, m_model, m_tree_view, and QET::Icons::tr.
Referenced by validateCurrentPage().
validStep2()
bool NewElementWizard::validStep2 () private
NewElementWizard::validStep2 Valid the step 2.
Returns
true if step is valid
Definition at line 205 of file newelementwizard.cpp.
References ElementsLocation::addToPath(), QET::QetMessageBox::critical(), ElementsLocation::exist(), m_chosen_file, m_chosen_location, m_qle_filename, and QET::Icons::tr.
Referenced by validateCurrentPage().
Member Data Documentation
m_chosen_file
QString NewElementWizard::m_chosen_file private
Definition at line 57 of file newelementwizard.h.
Referenced by createNewElement(), and validStep2().
m_chosen_location
ElementsLocation NewElementWizard::m_chosen_location private
Definition at line 59 of file newelementwizard.h.
Referenced by createNewElement(), validStep1(), and validStep2().
m_model
ElementsCollectionModel* NewElementWizard::m_model = nullptr private
Definition at line 60 of file newelementwizard.h.
Referenced by buildStep1(), preselectedLocation(), and validStep1().
m_names_list
NameListWidget* NewElementWizard::m_names_list private
Definition at line 56 of file newelementwizard.h.
Referenced by buildStep3(), createNewElement(), and validateCurrentPage().
m_qle_filename
QFileNameEdit* NewElementWizard::m_qle_filename private
Definition at line 55 of file newelementwizard.h.
Referenced by buildStep2(), and validStep2().
m_tree_view
QTreeView* NewElementWizard::m_tree_view = nullptr private
Definition at line 58 of file newelementwizard.h.
Referenced by buildStep1(), preselectedLocation(), and validStep1().
The documentation for this class was generated from the following files:
newelementwizard.h
newelementwizard.cpp