QElectroTech: DiagramPropertiesDialog Class Reference
DiagramPropertiesDialog Class Reference
The DiagramPropertiesDialog class This dialog open a windows for edit properties of a diagram.
#include <diagrampropertiesdialog.h>
Public Slots
void editAutonum ()
DiagramPropertiesDialog::editAutonum Open conductor autonum editor.
void editAutoFolioNum ()
DiagramPropertiesDialog::editAutonum Open folio autonum editor.
Public Member Functions
DiagramPropertiesDialog (Diagram *diagram, QWidget *parent=nullptr)
DiagramPropertiesDialog::DiagramPropertiesDialog Deafult constructor.
Static Public Member Functions
static void diagramPropertiesDialog (Diagram *diagram, QWidget *parent=nullptr)
DiagramPropertiesDialog::diagramPropertiesDialog Static method to get a DiagramPropertiesDialog.
Private Attributes
Diagram * m_diagram
ConductorPropertiesWidget * m_cpw
Detailed Description
The DiagramPropertiesDialog class This dialog open a windows for edit properties of a diagram.
Definition at line 30 of file diagrampropertiesdialog.h.
Constructor & Destructor Documentation
DiagramPropertiesDialog()
DiagramPropertiesDialog::DiagramPropertiesDialog (Diagram * diagram, QWidget * parent = nullptr)
DiagramPropertiesDialog::DiagramPropertiesDialog Deafult constructor.
Parameters
diagram : diagram to edit properties
parent : parent widget
TODO implement an undo command to allow the user to undo/redo this action
Definition at line 33 of file diagrampropertiesdialog.cpp.
References ConductorPropertiesWidget::autonumComboBox(), QET::Icons::Cancel, QETProject::conductorAutoNum(), QETProject::conductorAutoNumChanged(), Diagram::conductorsAutonumName(), editAutoFolioNum(), editAutonum(), ConductorPropertiesWidget::editAutonumPushButton(), m_cpw, Diagram::project(), Diagram::setConductorsAutonumName(), and QET::Icons::tr.
Member Function Documentation
diagramPropertiesDialog()
void DiagramPropertiesDialog::diagramPropertiesDialog (Diagram * diagram, QWidget * parent = nullptr) static
DiagramPropertiesDialog::diagramPropertiesDialog Static method to get a DiagramPropertiesDialog.
Parameters
diagram : diagram to edit properties
parent : parent widget
Definition at line 129 of file diagrampropertiesdialog.cpp.
Referenced by DiagramView::editDiagramProperties().
editAutoFolioNum
void DiagramPropertiesDialog::editAutoFolioNum () slot
DiagramPropertiesDialog::editAutonum Open folio autonum editor.
Definition at line 150 of file diagrampropertiesdialog.cpp.
References ProjectPropertiesDialog::Autonum, ProjectPropertiesDialog::changeToFolio(), ProjectPropertiesDialog::exec(), m_diagram, Diagram::project(), and ProjectPropertiesDialog::setCurrentPage().
Referenced by DiagramPropertiesDialog().
editAutonum
void DiagramPropertiesDialog::editAutonum () slot
DiagramPropertiesDialog::editAutonum Open conductor autonum editor.
Definition at line 137 of file diagrampropertiesdialog.cpp.
References ProjectPropertiesDialog::Autonum, ConductorPropertiesWidget::autonumComboBox(), QETProject::conductorAutoNum(), ProjectPropertiesDialog::exec(), m_cpw, m_diagram, Diagram::project(), and ProjectPropertiesDialog::setCurrentPage().
Referenced by DiagramPropertiesDialog().
Member Data Documentation
m_cpw
ConductorPropertiesWidget* DiagramPropertiesDialog::m_cpw private
Definition at line 44 of file diagrampropertiesdialog.h.
Referenced by DiagramPropertiesDialog(), and editAutonum().
m_diagram
Diagram* DiagramPropertiesDialog::m_diagram private
Definition at line 43 of file diagrampropertiesdialog.h.
Referenced by editAutoFolioNum(), and editAutonum().
The documentation for this class was generated from the following files:
diagrampropertiesdialog.h
diagrampropertiesdialog.cpp