QElectroTech: ElementInfoPartWidget Class Reference
ElementInfoPartWidget Class Reference
The ElementInfoPartWidget class.
#include <elementinfopartwidget.h>
Signals
void textEdited (const QString &text)
void textChanged (const QString &text)
Public Member Functions
ElementInfoPartWidget (QString key, const QString &translated_key, QWidget *parent=nullptr)
ElementInfoPartWidget::ElementInfoPartWidget Constructor.
~ElementInfoPartWidget () override
ElementInfoPartWidget::~ElementInfoPartWidget destructor.
QString key () const
QString text () const
ElementInfoPartWidget::text.
void setText (const QString &)
ElementInfoPartWidget::setText Set text to line edit.
void setPlaceHolderText (const QString &text)
ElementInfoPartWidget::setPlaceHolderText.
void setFocusTolineEdit ()
ElementInfoPartWidget::setFocusTolineEdit Set the focus to the line edit.
void setEnabled (bool e)
ElementInfoPartWidget::setEnabled enable the line edit.
void setDisabled (bool d)
ElementInfoPartWidget::setDisabled disable the line edit.
void setEraseTextVisible (bool visible)
ElementInfoPartWidget::setEraseTextVisible.
void setEraseTextChecked (bool check)
ElementInfoPartWidget::setEraseTextChecked.
Qt::CheckState EraseTextCheckState () const
ElementInfoPartWidget::EraseTextCheckState.
Private Slots
void on_m_erase_text_clicked ()
Private Attributes
Ui::ElementInfoPartWidget * ui
QString key_
bool m_show_erase = false
Detailed Description
The ElementInfoPartWidget class.
Definition at line 31 of file elementinfopartwidget.h.
Constructor & Destructor Documentation
ElementInfoPartWidget()
ElementInfoPartWidget::ElementInfoPartWidget (QString key, const QString & translated_key, QWidget * parent = nullptr) explicit
ElementInfoPartWidget::ElementInfoPartWidget Constructor.
Parameters
key the string key what represent this info part
translated_key the string key translated
parent parent widget
Definition at line 33 of file elementinfopartwidget.cpp.
References textChanged(), textEdited(), and ui.
~ElementInfoPartWidget()
ElementInfoPartWidget::~ElementInfoPartWidget () override
ElementInfoPartWidget::~ElementInfoPartWidget destructor.
Definition at line 54 of file elementinfopartwidget.cpp.
References ui.
Member Function Documentation
EraseTextCheckState()
Qt::CheckState ElementInfoPartWidget::EraseTextCheckState () const
ElementInfoPartWidget::EraseTextCheckState.
Returns
Definition at line 143 of file elementinfopartwidget.cpp.
References ui.
key()
QString ElementInfoPartWidget::key () const inline
Definition at line 42 of file elementinfopartwidget.h.
References key_.
Referenced by ElementInfoWidget::infoPartWidgetForKey().
on_m_erase_text_clicked
void ElementInfoPartWidget::on_m_erase_text_clicked () private slot
Definition at line 148 of file elementinfopartwidget.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
setDisabled()
void ElementInfoPartWidget::setDisabled (bool d)
ElementInfoPartWidget::setDisabled disable the line edit.
Parameters
d
Definition at line 115 of file elementinfopartwidget.cpp.
References ui.
Referenced by ElementInfoWidget::setElement().
setEnabled()
void ElementInfoPartWidget::setEnabled (bool e)
ElementInfoPartWidget::setEnabled enable the line edit.
Parameters
e
Definition at line 105 of file elementinfopartwidget.cpp.
References ui.
Referenced by ElementInfoWidget::setElement().
setEraseTextChecked()
void ElementInfoPartWidget::setEraseTextChecked (bool check)
ElementInfoPartWidget::setEraseTextChecked.
Parameters
check
Definition at line 134 of file elementinfopartwidget.cpp.
References ui.
setEraseTextVisible()
void ElementInfoPartWidget::setEraseTextVisible (bool visible)
ElementInfoPartWidget::setEraseTextVisible.
Parameters
visible
Definition at line 124 of file elementinfopartwidget.cpp.
References m_show_erase, and ui.
Referenced by ReplaceElementDialog::buildWidget().
setFocusTolineEdit()
void ElementInfoPartWidget::setFocusTolineEdit ()
ElementInfoPartWidget::setFocusTolineEdit Set the focus to the line edit.
Definition at line 95 of file elementinfopartwidget.cpp.
References ui.
setPlaceHolderText()
void ElementInfoPartWidget::setPlaceHolderText (const QString & text)
ElementInfoPartWidget::setPlaceHolderText.
Parameters
text
Definition at line 86 of file elementinfopartwidget.cpp.
References text(), and ui.
Referenced by ReplaceElementDialog::buildWidget().
setText()
void ElementInfoPartWidget::setText (const QString & txt)
ElementInfoPartWidget::setText Set text to line edit.
Parameters
txt
Definition at line 73 of file elementinfopartwidget.cpp.
References m_show_erase, SearchAndReplaceWorker::setupLineEdit(), and ui.
text()
QString ElementInfoPartWidget::text () const
ElementInfoPartWidget::text.
Returns
the text in the line edit
Definition at line 63 of file elementinfopartwidget.cpp.
References ui.
Referenced by ElementInfoWidget::setElement(), and setPlaceHolderText().
textChanged
void ElementInfoPartWidget::textChanged (const QString & text) signal
Referenced by ElementInfoWidget::disableLiveEdit(), ElementInfoPartWidget(), ElementInfoWidget::enableLiveEdit(), and ElementInfoWidget::setElement().
textEdited
void ElementInfoPartWidget::textEdited (const QString & text) signal
Referenced by ElementInfoPartWidget().
Member Data Documentation
key_
QString ElementInfoPartWidget::key_ private
Definition at line 63 of file elementinfopartwidget.h.
Referenced by key().
m_show_erase
bool ElementInfoPartWidget::m_show_erase = false private
Definition at line 64 of file elementinfopartwidget.h.
Referenced by setEraseTextVisible(), and setText().
ui
Ui::ElementInfoPartWidget* ElementInfoPartWidget::ui private
Definition at line 62 of file elementinfopartwidget.h.
Referenced by ElementInfoPartWidget(), EraseTextCheckState(), on_m_erase_text_clicked(), setDisabled(), setEnabled(), setEraseTextChecked(), setEraseTextVisible(), setFocusTolineEdit(), setPlaceHolderText(), setText(), text(), and ~ElementInfoPartWidget().
The documentation for this class was generated from the following files:
elementinfopartwidget.h
elementinfopartwidget.cpp