QElectroTech: QETDiagramEditor Class Reference
QETDiagramEditor Class Reference
#include <qetdiagrameditor.h>
Public Slots
void save ()
QETDiagramEditor::save Ask the current active project to save.
void saveAs ()
QETDiagramEditor::saveAs Ask the current active project to save as.
bool newProject ()
QETDiagramEditor::newProject Create a new project with an empty diagram.
bool openProject ()
bool openRecentFile (const QString &)
bool closeProject (ProjectView *)
bool closeProject (QETProject *)
void zoomGroupTriggered (QAction *action)
void selectGroupTriggered (QAction *action)
QETDiagramEditor::selectGroupTriggered This slot is called when selection need to change.
void addItemGroupTriggered (QAction *action)
QETDiagramEditor::addItemGroupTriggered This slot is called when an item must be added to the curent diagram, this slot use the DVEventInterface to add item.
void selectionGroupTriggered (QAction *action)
QETDiagramEditor::selectionGroupTriggered This slot is called when an action should be made on the current selection.
void rowColumnGroupTriggered (QAction *action)
void slot_updateActions ()
QETDiagramEditor::slot_updateActions Manage actions.
void slot_updateUndoStack ()
QETDiagramEditor::slot_updateUndoStack Update the undo stack view.
void slot_updateModeActions ()
QETDiagramEditor::slot_updateModeActions Manage action who need an opened diagram or project to be updated.
void slot_updateComplexActions ()
QETDiagramEditor::slot_updateComplexActions Manage the actions who need some conditions to be enable or not. This method does nothing if there is no project opened.
void slot_updatePasteAction ()
QETDiagramEditor::slot_updatePasteAction Gere les actions ayant besoin du presse-papier.
void slot_updateWindowsMenu ()
void slot_updateAutoNumDock ()
QETDiagramEditor::slot_updateAutoNumDock Update Auto Num Dock Widget when changing Project.
void generateTerminalBlock ()
QETDiagramEditor::generateTerminalBlock.
void setWindowedMode ()
void setTabbedMode ()
void readSettings ()
QETDiagramEditor::readSettings Read the settings.
void writeSettings ()
QETDiagramEditor::writeSettings Write the settings.
void activateDiagram (Diagram *)
void activateProject (QETProject *)
void activateProject (ProjectView *)
void activateWidget (QWidget *)
void projectWasClosed (ProjectView *)
void editProjectProperties (ProjectView *)
void editProjectProperties (QETProject *)
void editDiagramProperties (DiagramView *)
void editDiagramProperties (Diagram *)
void addDiagramToProject (QETProject *)
QETDiagramEditor::addDiagramToProject Add a diagram to project.
void removeDiagram (Diagram *)
void removeDiagramFromProject ()
void moveDiagramUp (Diagram *)
void moveDiagramDown (Diagram *)
void moveDiagramUpTop (Diagram *)
void moveDiagramUpx10 (Diagram *)
void moveDiagramDownx10 (Diagram *)
void reloadOldElementPanel ()
void diagramWasAdded (DiagramView *)
QETDiagramEditor::diagramWasAdded Manage the adding of diagram view in a project.
void findElementInPanel (const ElementsLocation &)
QETDiagramEditor::findElementInPanel Find the item for location in the element panel.
void editElementInEditor (const ElementsLocation &)
void editSelectedElementInEditor ()
void showError (const QETResult &)
void showError (const QString &)
void subWindowActivated (QMdiSubWindow *subWindows)
QETDiagramEditor::subWindowActivated Slot used to update menu and undo stack when subwindows of MDIarea was activated.
Public Slots inherited from QETMainWindow
void toggleFullScreen ()
void updateFullScreenAction ()
void checkToolbarsmenu ()
Public Member Functions
QETDiagramEditor (const QStringList &=QStringList(), QWidget *=nullptr)
QETDiagramEditor::QETDiagramEditor Constructor.
~QETDiagramEditor () override
void closeEvent (QCloseEvent *) override
QList< ProjectView * > openedProjects () const
void addProjectView (ProjectView *)
QETDiagramEditor::addProjectView Add a new project view to workspace and build the connection between the projectview / project and this QETDiagramEditor.
bool openAndAddProject (const QString &, bool=true)
QList< QString > editedFiles () const
ProjectView * viewForFile (const QString &) const
ProjectView * currentProjectView () const
QETProject * currentProject () const
QETDiagramEditor::currentProject.
bool drawGrid () const
QETDiagramEditor::drawGrid.
void openBackupFiles (QList< KAutoSaveFile * > backup_files)
QETDiagramEditor::openBackupFiles.
Public Member Functions inherited from QETMainWindow
QETMainWindow (QWidget *=nullptr, Qt::WindowFlags=Qt::Widget)
~QETMainWindow () override
Public Attributes
QAction * m_edit_diagram_properties
Show a dialog to edit diagram properties.
QAction * m_conductor_reset
Reset paths of selected conductors.
QAction * m_cut
Cut selection to clipboard.
QAction * m_copy
Copy selection to clipboard.
QActionGroup m_row_column_actions_group
QActionGroup m_selection_actions_group
Action related to add/remove rows/column in diagram.
QActionGroup * m_depth_action_group = nullptr
Action related to edit a selected item.
Protected Member Functions
bool event (QEvent *) override
QETDiagramEditor::event Reimplemented to : -Load elements collection when WindowActivate.
Protected Member Functions inherited from QETMainWindow
void initCommonActions ()
void initCommonMenus ()
void insertMenu (QMenu *, QMenu *, bool=true)
QAction * actionForMenu (QMenu *)
bool event (QEvent *) override
void dragEnterEvent (QDragEnterEvent *e) override
void dropEvent (QDropEvent *e) override
virtual void firstActivation (QEvent *)
Private Slots
void selectionChanged ()
QETDiagramEditor::selectionChanged This slot is called when a diagram selection was changed.
Private Member Functions
QETDiagramEditor (const QETDiagramEditor &)
void setUpElementsPanel ()
QETDiagramEditor::setUpElementsPanel Setup the element panel and element panel widget.
void setUpElementsCollectionWidget ()
QETDiagramEditor::setUpElementsCollectionWidget Set up the dock widget of element collection.
void setUpUndoStack ()
QETDiagramEditor::setUpUndoStack Setup the undostack and undo stack widget.
void setUpSelectionPropertiesEditor ()
QETDiagramEditor::setUpSelectionPropertiesEditor Setup the dock for edit the current selection.
void setUpAutonumberingWidget ()
QETDiagramEditor::setUpAutonumberingWidget Setup the dock for AutoNumbering Selection.
void setUpActions ()
QETDiagramEditor::setUpActions Set up all Qaction.
void setUpToolBar ()
QETDiagramEditor::setUpToolBar.
void setUpMenu ()
QETDiagramEditor::setUpMenu.
bool addProject (QETProject *, bool=true)
DiagramView * currentDiagramView () const
Element * currentElement () const
ProjectView * findProject (DiagramView *) const
ProjectView * findProject (Diagram *) const
ProjectView * findProject (QETProject *) const
ProjectView * findProject (const QString &) const
QMdiSubWindow * subWindowForWidget (QWidget *) const
Private Attributes
QActionGroup * grp_visu_sel
Action group for visualisation vs edition mode.
QActionGroup * m_group_view_mode
Action group for project.
QActionGroup m_add_item_actions_group
QActionGroup m_zoom_actions_group
Action related to adding (add text image shape...)
QActionGroup m_select_actions_group
Action related to zoom for diagram.
QActionGroup m_file_actions_group
Action related to global selections.
QAction * m_tabbed_view_mode
Actions related to file (open, close, save...)
QAction * m_windowed_view_mode
Display projects as windows.
QAction * m_mode_selection
Set edition mode.
QAction * m_mode_visualise
Set visualisation mode.
QAction * m_export_diagram
Export diagrams of the current project as imagess.
QAction * m_print
Print diagrams of the current project.
QAction * m_quit_editor
Quit the diagram editor.
QAction * undo
Cancel the latest action.
QAction * redo
Redo the latest cancelled operation.
QAction * m_paste
Paste clipboard content on the current diagram.
QAction * m_auto_conductor
Enable/Disable the use of auto conductor.
QAction * conductor_default
Show a dialog to edit default conductor properties.
QAction * m_grey_background
Switch the background color in white or grey.
QAction * m_draw_grid
Switch the background grid display or not.
QAction * m_project_edit_properties
Edit the properties of the current project.
QAction * m_project_add_diagram
Add a diagram to the current project.
QAction * m_remove_diagram_from_project
Delete a diagram from the current project.
QAction * m_clean_project
Clean the content of the curent project by removing useless items.
QAction * m_project_folio_list
Sommaire des schemas.
QAction * m_csv_export
generate nomenclature
QAction * m_add_nomenclature
Add nomenclature graphics item;.
QAction * m_add_summary
Add summary graphics item.
QAction * m_project_terminalBloc
generate terminal block
QAction * m_project_export_conductor_num
Export the wire num to csv.
QAction * m_export_project_db
QAction * m_tile_window
Export to file the internal database of the current project.
QAction * m_cascade_window
Show MDI subwindows as cascade.
QAction * m_previous_window
Switch to the previous document.
QAction * m_next_window
Switch to the next document.
QAction * m_edit_selection
To edit selected item.
QList< QAction * > m_zoom_action_toolBar
QAction * m_delete_selection
Only zoom action must displayed in the toolbar.
QAction * m_rotate_selection
Rotate selected elements and text items by 90 degrees.
QAction * m_rotate_texts
Direct selected text items to a specific angle.
QAction * m_find_element
Find the selected element in the panel.
QAction * m_group_selected_texts = nullptr
QAction * m_close_file
Close current project file.
QAction * m_save_file
Save current project.
QAction * m_save_file_as
Save current project as a specific file.
QAction * m_find = nullptr
QMdiArea m_workspace
QSignalMapper windowMapper
QDir open_dialog_dir
QDockWidget * qdw_pa
Directory to use for file dialogs such as File > save.
QDockWidget * m_qdw_elmt_collection
Dock for the elements panel.
QDockWidget * qdw_undo
ElementsCollectionWidget * m_element_collection_widget
Dock for the undo list.
DiagramPropertiesEditorDockWidget * m_selection_properties_editor
ElementsPanelWidget * pa
Elements panel.
QMenu * windows_menu
QToolBar * main_tool_bar = nullptr
QToolBar * view_tool_bar = nullptr
QToolBar * diagram_tool_bar = nullptr
QToolBar * m_add_item_tool_bar = nullptr
QToolBar * m_depth_tool_bar = nullptr
QUndoGroup undo_group
AutoNumberingDockWidget * m_autonumbering_dock
int activeSubWindowIndex
bool m_first_show = true
SearchAndReplaceWidget m_search_and_replace_widget
Additional Inherited Members
Protected Attributes inherited from QETMainWindow
QAction * configure_action_
Launch the QElectroTech configuration dialog.
QAction * fullscreen_action_
Toggle full screen.
QAction * whatsthis_action_
Toggle "What's this" mode.
QAction * about_qet_
Launch the "About QElectroTech" dialog.
QAction * manual_online_
Launch browser on QElectroTech online manual.
QAction * youtube_
Launch browser on QElectroTech Youtube channel.
QAction * upgrade_
Launch browser on QElectroTech Windows Nightly builds.
QAction * upgrade_M
Launch browser on QElectroTech MAC_OS_X builds.
QAction * donate_
Launch browser to donate link.
QAction * about_qt_
launch the "About Qt" dialog
QMenu * settings_menu_
Settings menu.
QMenu * help_menu_
Help menu.
QMenu * display_toolbars_
Show/hide toolbars/docks.
QHash< QMenu *, QAction * > menu_actions_
Store actions retrieved when inserting menus.
bool first_activation_
Used to detect whether the window is activated for the first time.
Detailed Description
This class represents the main window of the QElectroTech diagram editor and, ipso facto, the most important part of the QElectroTech user interface.
Definition at line 50 of file qetdiagrameditor.h.
Constructor & Destructor Documentation
QETDiagramEditor() [1/2]
QETDiagramEditor::QETDiagramEditor (const QStringList & files = QStringList(), QWidget * parent = nullptr)
QETDiagramEditor::QETDiagramEditor Constructor.
Parameters
files : list of files to open
parent : parent widget
Definition at line 52 of file qetdiagrameditor.cpp.
References activateWidget(), activeSubWindowIndex, QWidgetAnimation::lastSize, m_search_and_replace_widget, m_workspace, openAndAddProject(), qdw_pa, qdw_undo, QET::Icons::QETLogo, readSettings(), SearchAndReplaceWidget::setEditor(), setUpActions(), setUpAutonumberingWidget(), setUpElementsCollectionWidget(), setUpElementsPanel(), setUpMenu(), setUpSelectionPropertiesEditor(), setUpToolBar(), setUpUndoStack(), slot_updateActions(), slot_updatePasteAction(), subWindowActivated(), QET::Icons::tr, QET::Vertical, and windowMapper.
~QETDiagramEditor()
QETDiagramEditor::~QETDiagramEditor () override
Destructeur
Definition at line 131 of file qetdiagrameditor.cpp.
QETDiagramEditor() [2/2]
QETDiagramEditor::QETDiagramEditor (const QETDiagramEditor &) private
Member Function Documentation
activateDiagram
void QETDiagramEditor::activateDiagram (Diagram * diagram) slot
Active le schema passe en parametre
Parameters
diagram Schema a activer
Definition at line 1938 of file qetdiagrameditor.cpp.
References activateWidget(), and findProject().
Referenced by setUpElementsPanel().
activateProject [1/2]
void QETDiagramEditor::activateProject (ProjectView * project_view) slot
Active le projet passe en parametre
Parameters
project_view Projet a activer
Definition at line 1961 of file qetdiagrameditor.cpp.
References activateWidget().
activateProject [2/2]
void QETDiagramEditor::activateProject (QETProject * project) slot
Active le projet passe en parametre
Parameters
project Projet a activer
Definition at line 1953 of file qetdiagrameditor.cpp.
References findProject().
Referenced by addDiagramToProject(), closeProject(), editDiagramProperties(), editProjectProperties(), setUpActions(), and setUpElementsPanel().
activateWidget
void QETDiagramEditor::activateWidget (QWidget * widget) slot
Parameters
widget Widget a activer
Definition at line 1264 of file qetdiagrameditor.cpp.
References m_workspace, and subWindowForWidget().
Referenced by activateDiagram(), activateProject(), openAndAddProject(), and QETDiagramEditor().
addDiagramToProject
void QETDiagramEditor::addDiagramToProject (QETProject * project) slot
QETDiagramEditor::addDiagramToProject Add a diagram to project.
Parameters
project
Definition at line 2012 of file qetdiagrameditor.cpp.
References activateProject(), and findProject().
Referenced by setUpElementsPanel().
addItemGroupTriggered
void QETDiagramEditor::addItemGroupTriggered (QAction * action) slot
QETDiagramEditor::addItemGroupTriggered This slot is called when an item must be added to the curent diagram, this slot use the DVEventInterface to add item.
Parameters
action : Action that describe the item to add.
Definition at line 1316 of file qetdiagrameditor.cpp.
References currentDiagramView(), DiagramView::diagram(), QetShapeItem::Ellipse, DiagramEventAddImage::isNull(), QetShapeItem::Line, QetShapeItem::Polygon, QetShapeItem::Rectangle, Diagram::setEventInterface(), and QET::Icons::tr.
Referenced by setUpActions().
addProject()
bool QETDiagramEditor::addProject (QETProject * project, bool update_panel = true) private
Ajoute un projetmoveDiagramUp(
Parameters
project projet a ajouter
update_panel Whether the elements panel should be warned this project has been added. Defaults to true.
Definition at line 1089 of file qetdiagrameditor.cpp.
References ElementsCollectionWidget::addProject(), addProjectView(), currentDiagramView(), m_autonumbering_dock, m_element_collection_widget, pa, QETApp::registerProject(), AutoNumberingDockWidget::setProject(), and undo_group.
Referenced by newProject(), openAndAddProject(), and openBackupFiles().
addProjectView()
void QETDiagramEditor::addProjectView (ProjectView * project_view)
QETDiagramEditor::addProjectView Add a new project view to workspace and build the connection between the projectview / project and this QETDiagramEditor.
Parameters
project_view : project view to add
Definition at line 1689 of file qetdiagrameditor.cpp.
References diagramWasAdded(), editElementInEditor(), ProjectView::editElementRequired(), findElementInPanel(), ProjectView::findElementRequired(), m_workspace, projectWasClosed(), showError(), and slot_updateActions().
Referenced by addProject().
closeEvent()
void QETDiagramEditor::closeEvent (QCloseEvent * qce) override
Permet de quitter l'application lors de la fermeture de la fenetre principale
Parameters
qce Le QCloseEvent correspondant a l'evenement de fermeture
Definition at line 807 of file qetdiagrameditor.cpp.
References closeProject(), openedProjects(), and writeSettings().
closeProject [1/2]
bool QETDiagramEditor::closeProject (ProjectView * project_view) slot
Ferme un projet
Parameters
project_view Projet a fermer
Returns
true si la fermeture du projet a reussi, false sinon Note : cette methode renvoie true si project est nul
Definition at line 951 of file qetdiagrameditor.cpp.
References activateProject(), and subWindowForWidget().
Referenced by closeEvent(), closeProject(), setUpActions(), and setUpElementsPanel().
closeProject [2/2]
bool QETDiagramEditor::closeProject (QETProject * project) slot
Ferme un projet
Parameters
project projet a fermer
Returns
true si la fermeture du fichier a reussi, false sinon Note : cette methode renvoie true si project est nul
Definition at line 967 of file qetdiagrameditor.cpp.
References closeProject(), and findProject().
currentDiagramView()
DiagramView * QETDiagramEditor::currentDiagramView () const private
Returns
Le schema actuellement edite (= l'onglet ouvert dans le projet courant) ou 0 s'il n'y en a pas
Definition at line 1162 of file qetdiagrameditor.cpp.
References currentProjectView().
Referenced by addItemGroupTriggered(), addProject(), currentElement(), rowColumnGroupTriggered(), selectGroupTriggered(), selectionChanged(), selectionGroupTriggered(), setUpActions(), slot_updateActions(), slot_updateAutoNumDock(), slot_updateComplexActions(), slot_updateModeActions(), slot_updatePasteAction(), and zoomGroupTriggered().
currentElement()
Element * QETDiagramEditor::currentElement () const private
Returns
the selected element in the current diagram view, or 0 if: no diagram is being viewed in this editor. no element is selected more than one element is selected
Definition at line 1175 of file qetdiagrameditor.cpp.
References currentDiagramView(), DiagramView::diagram(), and DiagramContent::m_elements.
Referenced by editSelectedElementInEditor(), and selectionGroupTriggered().
currentProject()
QETProject * QETDiagramEditor::currentProject () const
QETDiagramEditor::currentProject.
Returns
the current edited project. This function can return nullptr.
Definition at line 1147 of file qetdiagrameditor.cpp.
References currentProjectView(), and ProjectView::project().
Referenced by SearchAndReplaceWidget::fillItemsList(), and setUpActions().
currentProjectView()
ProjectView * QETDiagramEditor::currentProjectView () const
Returns
Le projet actuellement edite (= qui a le focus dans l'interface MDI) ou 0 s'il n'y en a pas
Definition at line 1129 of file qetdiagrameditor.cpp.
References m_workspace.
Referenced by currentDiagramView(), currentProject(), generateTerminalBlock(), DiagramView::keyPressEvent(), removeDiagramFromProject(), save(), saveAs(), setUpActions(), slot_updateActions(), slot_updateAutoNumDock(), slot_updateModeActions(), slot_updateUndoStack(), and slot_updateWindowsMenu().
diagramWasAdded
void QETDiagramEditor::diagramWasAdded (DiagramView * dv) slot
QETDiagramEditor::diagramWasAdded Manage the adding of diagram view in a project.
Parameters
dv : added diagram view
Definition at line 2163 of file qetdiagrameditor.cpp.
References DiagramView::diagram(), selectionChanged(), and slot_updateModeActions().
Referenced by addProjectView().
drawGrid()
bool QETDiagramEditor::drawGrid () const
QETDiagramEditor::drawGrid.
Returns
true if the grid of folio must be displayed
Definition at line 1783 of file qetdiagrameditor.cpp.
References m_draw_grid.
editDiagramProperties [1/2]
void QETDiagramEditor::editDiagramProperties (Diagram * diagram) slot
Edite les proprietes du schema diagram
Parameters
diagram schema dont il faut editer les proprietes
Definition at line 1873 of file qetdiagrameditor.cpp.
References activateProject(), editDiagramProperties(), and findProject().
editDiagramProperties [2/2]
void QETDiagramEditor::editDiagramProperties (DiagramView * diagram_view) slot
Edite les proprietes du schema diagram
Parameters
diagram_view schema dont il faut editer les proprietes
Definition at line 1862 of file qetdiagrameditor.cpp.
References activateProject(), and findProject().
Referenced by editDiagramProperties(), and setUpElementsPanel().
editedFiles()
QList< QString > QETDiagramEditor::editedFiles () const
Returns
la liste des fichiers edites par cet editeur de schemas
Definition at line 1745 of file qetdiagrameditor.cpp.
References openedProjects().
editElementInEditor
void QETDiagramEditor::editElementInEditor (const ElementsLocation & location) slot
Lance l'editeur d'element pour l'element filename
Parameters
location Emplacement de l'element a editer
Definition at line 2190 of file qetdiagrameditor.cpp.
References QETApp::instance().
Referenced by addProjectView(), and editSelectedElementInEditor().
editProjectProperties [1/2]
void QETDiagramEditor::editProjectProperties (ProjectView * project_view) slot
Edite les proprietes du projet project_view.
Parameters
project_view Vue sur le projet dont il faut editer les proprietes
Definition at line 1993 of file qetdiagrameditor.cpp.
References activateProject().
Referenced by editProjectProperties(), setUpActions(), and setUpElementsPanel().
editProjectProperties [2/2]
void QETDiagramEditor::editProjectProperties (QETProject * project) slot
Edite les proprietes du projet project.
Parameters
project Projet dont il faut editer les proprietes
Definition at line 2003 of file qetdiagrameditor.cpp.
References editProjectProperties(), and findProject().
editSelectedElementInEditor
void QETDiagramEditor::editSelectedElementInEditor () slot
Launch an element editor to edit the selected element in the current diagram view.
Definition at line 2199 of file qetdiagrameditor.cpp.
References currentElement(), and editElementInEditor().
event()
bool QETDiagramEditor::event (QEvent * e) override protected
QETDiagramEditor::event Reimplemented to : -Load elements collection when WindowActivate.
Parameters
e
Returns
Definition at line 839 of file qetdiagrameditor.cpp.
References QETMainWindow::event(), m_element_collection_widget, and m_first_show.
findElementInPanel
void QETDiagramEditor::findElementInPanel (const ElementsLocation & location) slot
QETDiagramEditor::findElementInPanel Find the item for location in the element panel.
Parameters
location
Definition at line 2181 of file qetdiagrameditor.cpp.
References m_element_collection_widget, and ElementsCollectionWidget::setCurrentLocation().
Referenced by addProjectView(), and selectionGroupTriggered().
findProject() [1/4]
ProjectView * QETDiagramEditor::findProject (const QString & filepath) const private
Parameters
filepath Chemin de fichier d'un projet
Returns
le ProjectView correspondant au chemin passe en parametre, ou 0 si celui-ci n'a pas ete trouve
Definition at line 1236 of file qetdiagrameditor.cpp.
References openedProjects().
findProject() [2/4]
ProjectView * QETDiagramEditor::findProject (Diagram * diagram) const private
Cette methode permet de retrouver le projet contenant un schema donne.
Parameters
diagram Schema dont il faut retrouver
Returns
la vue sur le projet contenant ce schema ou 0 s'il n'y en a pas
Definition at line 1207 of file qetdiagrameditor.cpp.
References openedProjects().
findProject() [3/4]
ProjectView * QETDiagramEditor::findProject (DiagramView * diagram_view) const private
Cette methode permet de retrouver le projet contenant un schema donne.
Parameters
diagram_view Schema dont il faut retrouver
Returns
la vue sur le projet contenant ce schema ou 0 s'il n'y en a pas
Definition at line 1193 of file qetdiagrameditor.cpp.
References openedProjects().
Referenced by activateDiagram(), activateProject(), addDiagramToProject(), closeProject(), editDiagramProperties(), editProjectProperties(), moveDiagramDown(), moveDiagramDownx10(), moveDiagramUp(), moveDiagramUpTop(), moveDiagramUpx10(), and removeDiagram().
findProject() [4/4]
ProjectView * QETDiagramEditor::findProject (QETProject * project) const private
Parameters
project Projet dont il faut trouver la vue
Returns
la vue du projet passe en parametre
Definition at line 1222 of file qetdiagrameditor.cpp.
References openedProjects().
generateTerminalBlock
void QETDiagramEditor::generateTerminalBlock () slot
QETDiagramEditor::generateTerminalBlock.
Definition at line 2251 of file qetdiagrameditor.cpp.
References currentProjectView(), QETProject::filePath(), openedProjects(), ProjectView::project(), QET::Icons::tr, and QET::QetMessageBox::warning().
Referenced by setUpActions().
moveDiagramDown
void QETDiagramEditor::moveDiagramDown (Diagram * diagram) slot
Change l'ordre des schemas d'un projet, en decalant le schema vers le bas / la droite
Parameters
diagram Schema a decaler vers le bas / la droite
Definition at line 2070 of file qetdiagrameditor.cpp.
References findProject().
Referenced by setUpElementsPanel().
moveDiagramDownx10
void QETDiagramEditor::moveDiagramDownx10 (Diagram * diagram) slot
Change l'ordre des schemas d'un projet, en decalant le schema vers le bas / la droite x10
Parameters
diagram Schema a decaler vers le bas / la droite x10
Definition at line 2128 of file qetdiagrameditor.cpp.
References findProject().
Referenced by setUpElementsPanel().
moveDiagramUp
void QETDiagramEditor::moveDiagramUp (Diagram * diagram) slot
Change l'ordre des schemas d'un projet, en decalant le schema vers le haut / la gauche
Parameters
diagram Schema a decaler vers le haut / la gauche
Definition at line 2051 of file qetdiagrameditor.cpp.
References findProject().
Referenced by setUpElementsPanel().
moveDiagramUpTop
void QETDiagramEditor::moveDiagramUpTop (Diagram * diagram) slot
Change l'ordre des schemas d'un projet, en decalant le schema vers le haut / la gauche en position 0
Parameters
diagram Schema a decaler vers le haut / la gauche en position 0
Definition at line 2089 of file qetdiagrameditor.cpp.
References findProject().
Referenced by setUpElementsPanel().
moveDiagramUpx10
void QETDiagramEditor::moveDiagramUpx10 (Diagram * diagram) slot
Change l'ordre des schemas d'un projet, en decalant le schema vers le haut / la gauche x10
Parameters
diagram Schema a decaler vers le haut / la gauche x10
Definition at line 2109 of file qetdiagrameditor.cpp.
References findProject().
Referenced by setUpElementsPanel().
newProject
bool QETDiagramEditor::newProject () slot
QETDiagramEditor::newProject Create a new project with an empty diagram.
Returns
Definition at line 900 of file qetdiagrameditor.cpp.
References addProject().
Referenced by setUpActions().
openAndAddProject()
bool QETDiagramEditor::openAndAddProject (const QString & filepath, bool interactive = true)
Ouvre un projet depuis un fichier et l'ajoute a cet editeur
Parameters
filepath Chemin du projet a ouvrir
interactive true pour afficher des messages a l'utilisateur, false sinon
Returns
true si l'ouverture a reussi, false sinon
Definition at line 980 of file qetdiagrameditor.cpp.
References activateWidget(), addProject(), QET::QetMessageBox::critical(), QETApp::diagramEditorForFile(), DialogWaiting::dropInstance(), QETProject::FileOpenDiscard, DialogWaiting::instance(), QETProject::Ok, QETApp::projectsRecentFiles(), QET::Icons::tr, viewForFile(), and QET::QetMessageBox::warning().
Referenced by openProject(), openRecentFile(), and QETDiagramEditor().
openBackupFiles()
void QETDiagramEditor::openBackupFiles (QList< KAutoSaveFile * > backup_files)
QETDiagramEditor::openBackupFiles.
Parameters
backup_files
Definition at line 1791 of file qetdiagrameditor.cpp.
References addProject(), DialogWaiting::dropInstance(), QETProject::FileOpenDiscard, DialogWaiting::instance(), QETProject::Ok, QETProject::state(), QET::Icons::tr, and QET::QetMessageBox::warning().
Referenced by QETApp::checkBackupFiles().
openedProjects()
QList< ProjectView * > QETDiagramEditor::openedProjects () const
Returns
la liste des projets ouverts dans cette fenetre
Definition at line 1114 of file qetdiagrameditor.cpp.
References m_workspace.
Referenced by closeEvent(), editedFiles(), findProject(), generateTerminalBlock(), setUpActions(), slot_updateWindowsMenu(), and viewForFile().
openProject
bool QETDiagramEditor::openProject () slot
Cette fonction demande un nom de fichier a ouvrir a l'utilisateur
Returns
true si l'ouverture a reussi, false sinon
Definition at line 928 of file qetdiagrameditor.cpp.
References open_dialog_dir, openAndAddProject(), and QET::Icons::tr.
Referenced by setUpActions().
openRecentFile
bool QETDiagramEditor::openRecentFile (const QString & filepath) slot
Slot utilise pour ouvrir un fichier recent. Transfere filepath au slot openAndAddDiagram seulement si cet editeur est actif
Parameters
filepath Fichier a ouvrir
See also
openAndAddDiagram
Definition at line 917 of file qetdiagrameditor.cpp.
References openAndAddProject().
Referenced by setUpMenu().
projectWasClosed
void QETDiagramEditor::projectWasClosed (ProjectView * project_view) slot
Definition at line 1970 of file qetdiagrameditor.cpp.
References m_element_collection_widget, m_selection_properties_editor, pa, ElementsCollectionWidget::removeProject(), DiagramPropertiesEditorDockWidget::setDiagram(), undo_group, and QETApp::unregisterProject().
Referenced by addProjectView().
readSettings
void QETDiagramEditor::readSettings () slot
QETDiagramEditor::readSettings Read the settings.
Definition at line 1902 of file qetdiagrameditor.cpp.
References setTabbedMode(), and setWindowedMode().
Referenced by QETDiagramEditor().
reloadOldElementPanel
void QETDiagramEditor::reloadOldElementPanel () slot
Definition at line 2142 of file qetdiagrameditor.cpp.
References pa, and ElementsPanelWidget::reloadAndFilter().
removeDiagram
void QETDiagramEditor::removeDiagram (Diagram * diagram) slot
Supprime un schema de son projet
Parameters
diagram Schema a supprimer
Definition at line 2029 of file qetdiagrameditor.cpp.
References findProject().
Referenced by removeDiagramFromProject(), and setUpElementsPanel().
removeDiagramFromProject
void QETDiagramEditor::removeDiagramFromProject () slot
Supprime le schema courant du projet courant
Definition at line 2149 of file qetdiagrameditor.cpp.
References currentProjectView(), and removeDiagram().
Referenced by setUpActions().
rowColumnGroupTriggered
void QETDiagramEditor::rowColumnGroupTriggered (QAction * action) slot
Definition at line 1403 of file qetdiagrameditor.cpp.
References Diagram::border_and_titleblock, BorderProperties::columns_count, currentDiagramView(), DiagramView::diagram(), BorderTitleBlock::exportBorder(), Diagram::isReadOnly(), BorderProperties::rows_count, and Diagram::undoStack().
Referenced by setUpActions().
save
void QETDiagramEditor::save () slot
QETDiagramEditor::save Ask the current active project to save.
Definition at line 853 of file qetdiagrameditor.cpp.
References currentProjectView(), ElementsCollectionWidget::highlightUnusedElement(), QETResult::isOk(), m_element_collection_widget, QETApp::projectsRecentFiles(), showError(), and QET::Icons::tr.
Referenced by setUpActions().
saveAs
void QETDiagramEditor::saveAs () slot
QETDiagramEditor::saveAs Ask the current active project to save as.
Definition at line 877 of file qetdiagrameditor.cpp.
References currentProjectView(), ElementsCollectionWidget::highlightUnusedElement(), QETResult::isOk(), m_element_collection_widget, QETApp::projectsRecentFiles(), showError(), and QET::Icons::tr.
Referenced by setUpActions().
selectGroupTriggered
void QETDiagramEditor::selectGroupTriggered (QAction * action) slot
QETDiagramEditor::selectGroupTriggered This slot is called when selection need to change.
Parameters
action : Action that describes what to do.
Definition at line 1295 of file qetdiagrameditor.cpp.
References currentDiagramView(), DiagramView::selectAll(), DiagramView::selectInvert(), and DiagramView::selectNothing().
Referenced by setUpActions().
selectionChanged
void QETDiagramEditor::selectionChanged () private slot
QETDiagramEditor::selectionChanged This slot is called when a diagram selection was changed.
Definition at line 2238 of file qetdiagrameditor.cpp.
References currentDiagramView(), DiagramView::diagram(), m_selection_properties_editor, DiagramPropertiesEditorDockWidget::setDiagram(), and slot_updateComplexActions().
Referenced by diagramWasAdded().
selectionGroupTriggered
void QETDiagramEditor::selectionGroupTriggered (QAction * action) slot
QETDiagramEditor::selectionGroupTriggered This slot is called when an action should be made on the current selection.
Parameters
action : Action that describe the action to do.
Definition at line 1366 of file qetdiagrameditor.cpp.
References DiagramView::adjustSceneRect(), currentDiagramView(), currentElement(), DiagramView::diagram(), DiagramView::editSelection(), findElementInPanel(), RotateSelectionCommand::isValid(), DiagramContent::m_element_texts, QET::Icons::tr, and Diagram::undoStack().
Referenced by setUpActions().
setTabbedMode
void QETDiagramEditor::setTabbedMode () slot
Affiche les projets dans des onglets.
Definition at line 1892 of file qetdiagrameditor.cpp.
References m_tabbed_view_mode, m_workspace, and slot_updateWindowsMenu().
Referenced by readSettings(), and setUpActions().
setUpActions()
void QETDiagramEditor::setUpActions () private
QETDiagramEditor::setUpActions Set up all Qaction.
Definition at line 233 of file qetdiagrameditor.cpp.
References activateProject(), QET::Icons::adding_image, addItemGroupTriggered(), QET::Icons::ApplicationExit, QET::Icons::Autoconnect, Diagram::background_color, Diagram::changeZValue(), closeProject(), QET::Icons::ConductorSettings, QetGraphicsTableFactory::createAndAddNomenclature(), QetGraphicsTableFactory::createAndAddSummary(), currentDiagramView(), currentProject(), currentProjectView(), QET::depthActionGroup(), DiagramView::diagram(), QET::Icons::DiagramAdd, QET::Icons::DiagramBg, QET::Icons::DiagramDelete, QETProject::diagrams(), QET::Icons::DialogInformation, QET::Icons::DocumentExport, QET::Icons::DocumentOpen, QET::Icons::DocumentPrint, QET::Icons::DocumentSave, QET::Icons::DocumentSaveAs, QET::Icons::DocumentSpreadsheet, QET::Icons::EditClear, QET::Icons::EditCopy, QET::Icons::EditCut, QET::Icons::EditDelete, QET::Icons::EditPaste, editProjectProperties(), QET::Icons::EditRedo, QET::Icons::EditSelectAll, QET::Icons::EditSelectInvert, QET::Icons::EditSelectNone, QET::Icons::EditTableDeleteColumn, QET::Icons::EditTableDeleteRow, QET::Icons::EditTableInsertColumnRight, QET::Icons::EditTableInsertRowUnder, QET::Icons::EditUndo, QET::Icons::ElementEdit, BOMExportDialog::exec(), projectDataBase::exportDb(), generateTerminalBlock(), QET::Icons::Grid, grp_visu_sel, m_add_item_actions_group, m_add_nomenclature, m_add_summary, m_auto_conductor, m_cascade_window, m_clean_project, m_close_file, m_conductor_reset, m_copy, m_csv_export, m_cut, m_delete_selection, m_depth_action_group, m_draw_grid, m_edit_diagram_properties, m_edit_selection, m_export_diagram, m_export_project_db, m_file_actions_group, m_find, m_find_element, m_grey_background, m_group_selected_texts, m_group_view_mode, m_mode_selection, m_mode_visualise, m_next_window, m_paste, m_previous_window, m_print, m_project_add_diagram, m_project_edit_properties, m_project_export_conductor_num, m_project_terminalBloc, m_quit_editor, m_remove_diagram_from_project, m_rotate_selection, m_rotate_texts, m_row_column_actions_group, m_save_file, m_save_file_as, m_search_and_replace_widget, m_select_actions_group, m_selection_actions_group, m_tabbed_view_mode, m_tile_window, m_windowed_view_mode, m_workspace, m_zoom_action_toolBar, m_zoom_actions_group, newProject(), QET::Icons::ObjectRotateRight, openedProjects(), openProject(), QET::Icons::PartEllipse, QET::Icons::PartLine, QET::Icons::PartPolygon, QET::Icons::PartRectangle, QET::Icons::PartSelect, QET::Icons::PartTextField, ProjectView::project(), QET::Icons::ProjectClose, QET::Icons::ProjectNew, QET::Icons::ProjectProperties, redo, removeDiagramFromProject(), rowColumnGroupTriggered(), save(), saveAs(), selectGroupTriggered(), selectionGroupTriggered(), setTabbedMode(), setWindowedMode(), QET::Icons::TableOfContent, QET::Icons::TerminalStrip, QET::Icons::textGroup, ConductorNumExport::toCsv(), QET::Icons::tr, QET::Icons::TransformRotate, undo, undo_group, QET::Icons::ViewMove, QET::Icons::ZoomDraw, QET::Icons::ZoomFitBest, zoomGroupTriggered(), QET::Icons::ZoomIn, QET::Icons::ZoomOriginal, and QET::Icons::ZoomOut.
Referenced by QETDiagramEditor().
setUpAutonumberingWidget()
void QETDiagramEditor::setUpAutonumberingWidget () private
QETDiagramEditor::setUpAutonumberingWidget Setup the dock for AutoNumbering Selection.
Definition at line 221 of file qetdiagrameditor.cpp.
References m_autonumbering_dock.
Referenced by QETDiagramEditor().
setUpElementsCollectionWidget()
void QETDiagramEditor::setUpElementsCollectionWidget () private
QETDiagramEditor::setUpElementsCollectionWidget Set up the dock widget of element collection.
Definition at line 169 of file qetdiagrameditor.cpp.
References ElementsCollectionWidget::expandFirstItems(), m_element_collection_widget, m_qdw_elmt_collection, and QET::Icons::tr.
Referenced by QETDiagramEditor().
setUpElementsPanel()
void QETDiagramEditor::setUpElementsPanel () private
QETDiagramEditor::setUpElementsPanel Setup the element panel and element panel widget.
Definition at line 138 of file qetdiagrameditor.cpp.
References activateDiagram(), activateProject(), addDiagramToProject(), closeProject(), editDiagramProperties(), editProjectProperties(), moveDiagramDown(), moveDiagramDownx10(), moveDiagramUp(), moveDiagramUpTop(), moveDiagramUpx10(), pa, qdw_pa, removeDiagram(), and QET::Icons::tr.
Referenced by QETDiagramEditor().
setUpMenu()
void QETDiagramEditor::setUpMenu () private
QETDiagramEditor::setUpMenu.
Definition at line 714 of file qetdiagrameditor.cpp.
References QET::Icons::ConfigureToolbars, diagram_tool_bar, QET::Icons::DocumentOpenRecent, QETMainWindow::help_menu_, QETMainWindow::insertMenu(), m_add_nomenclature, m_add_summary, m_clean_project, m_conductor_reset, m_copy, m_csv_export, m_cut, m_depth_action_group, m_draw_grid, m_edit_diagram_properties, m_export_diagram, m_export_project_db, m_file_actions_group, m_find, m_grey_background, m_mode_selection, m_mode_visualise, m_paste, m_print, m_project_add_diagram, m_project_edit_properties, m_project_export_conductor_num, m_project_terminalBloc, m_quit_editor, m_remove_diagram_from_project, m_row_column_actions_group, m_select_actions_group, m_selection_actions_group, m_tabbed_view_mode, m_windowed_view_mode, m_zoom_actions_group, main_tool_bar, openRecentFile(), QETApp::projectsRecentFiles(), qdw_pa, qdw_undo, redo, QETMainWindow::settings_menu_, slot_updateWindowsMenu(), QET::Icons::tr, undo, view_tool_bar, and windows_menu.
Referenced by QETDiagramEditor().
setUpSelectionPropertiesEditor()
void QETDiagramEditor::setUpSelectionPropertiesEditor () private
QETDiagramEditor::setUpSelectionPropertiesEditor Setup the dock for edit the current selection.
Definition at line 210 of file qetdiagrameditor.cpp.
References m_selection_properties_editor.
Referenced by QETDiagramEditor().
setUpToolBar()
void QETDiagramEditor::setUpToolBar () private
QETDiagramEditor::setUpToolBar.
Definition at line 659 of file qetdiagrameditor.cpp.
References diagram_tool_bar, m_add_item_actions_group, m_add_item_tool_bar, m_auto_conductor, m_conductor_reset, m_copy, m_cut, m_delete_selection, m_depth_action_group, m_depth_tool_bar, m_draw_grid, m_edit_diagram_properties, m_file_actions_group, m_grey_background, m_mode_selection, m_mode_visualise, m_paste, m_print, m_rotate_selection, m_zoom_action_toolBar, main_tool_bar, redo, QET::Icons::tr, undo, and view_tool_bar.
Referenced by QETDiagramEditor().
setUpUndoStack()
void QETDiagramEditor::setUpUndoStack () private
QETDiagramEditor::setUpUndoStack Setup the undostack and undo stack widget.
Definition at line 187 of file qetdiagrameditor.cpp.
References qdw_undo, QET::Icons::tr, and undo_group.
Referenced by QETDiagramEditor().
setWindowedMode
void QETDiagramEditor::setWindowedMode () slot
Affiche les projets dans des fenetres.
Definition at line 1883 of file qetdiagrameditor.cpp.
References m_windowed_view_mode, m_workspace, and slot_updateWindowsMenu().
Referenced by readSettings(), and setUpActions().
showError [1/2]
void QETDiagramEditor::showError (const QETResult & result) slot
Show the error message contained in result.
Definition at line 2208 of file qetdiagrameditor.cpp.
References QETResult::errorMessage(), and QETResult::isOk().
Referenced by addProjectView(), save(), and saveAs().
showError [2/2]
void QETDiagramEditor::showError (const QString & error) slot
Show the error message.
Definition at line 2216 of file qetdiagrameditor.cpp.
References QET::QetMessageBox::critical(), and QET::Icons::tr.
slot_updateActions
void QETDiagramEditor::slot_updateActions () slot
QETDiagramEditor::slot_updateActions Manage actions.
Definition at line 1430 of file qetdiagrameditor.cpp.
References currentDiagramView(), currentProjectView(), m_add_item_actions_group, m_add_nomenclature, m_add_summary, m_clean_project, m_close_file, m_csv_export, m_edit_diagram_properties, m_export_diagram, m_grey_background, m_print, m_project_add_diagram, m_project_edit_properties, m_project_export_conductor_num, m_remove_diagram_from_project, m_rotate_texts, m_row_column_actions_group, m_save_file, m_save_file_as, m_select_actions_group, m_zoom_actions_group, slot_updateAutoNumDock(), slot_updateComplexActions(), slot_updateModeActions(), slot_updatePasteAction(), and slot_updateUndoStack().
Referenced by addProjectView(), QETDiagramEditor(), and subWindowActivated().
slot_updateAutoNumDock
void QETDiagramEditor::slot_updateAutoNumDock () slot
QETDiagramEditor::slot_updateAutoNumDock Update Auto Num Dock Widget when changing Project.
Definition at line 1473 of file qetdiagrameditor.cpp.
References activeSubWindowIndex, currentDiagramView(), currentProjectView(), m_autonumbering_dock, m_workspace, and AutoNumberingDockWidget::setProject().
Referenced by slot_updateActions().
slot_updateComplexActions
void QETDiagramEditor::slot_updateComplexActions () slot
QETDiagramEditor::slot_updateComplexActions Manage the actions who need some conditions to be enable or not. This method does nothing if there is no project opened.
Definition at line 1497 of file qetdiagrameditor.cpp.
References Diagram::canRotateSelection(), QET::Icons::ConductorEdit, DiagramContent::count(), currentDiagramView(), DiagramView::diagram(), QET::Icons::EditText, QET::Icons::ElementEdit, DiagramContent::Elements, DiagramContent::hasCopiableItems(), DiagramContent::hasDeletableItems(), DiagramContent::Images, Diagram::isReadOnly(), DiagramContent::items(), m_conductor_reset, m_copy, m_cut, m_delete_selection, m_depth_action_group, m_edit_selection, DiagramContent::m_element_texts, m_find_element, m_group_selected_texts, m_rotate_selection, m_rotate_texts, QET::Icons::resize_image, QET::Icons::ro, Diagram::selectedConductors(), DiagramContent::SelectedOnly, DiagramContent::selectedTexts(), DiagramContent::selectedTextsGroup(), DiagramContent::Shapes, QET::Icons::tr, ConductorTextItem::Type, and DynamicElementTextItem::Type.
Referenced by selectionChanged(), and slot_updateActions().
slot_updateModeActions
void QETDiagramEditor::slot_updateModeActions () slot
QETDiagramEditor::slot_updateModeActions Manage action who need an opened diagram or project to be updated.
Definition at line 1638 of file qetdiagrameditor.cpp.
References currentDiagramView(), currentProjectView(), grp_visu_sel, m_auto_conductor, m_mode_selection, and m_mode_visualise.
Referenced by diagramWasAdded(), and slot_updateActions().
slot_updatePasteAction
void QETDiagramEditor::slot_updatePasteAction () slot
QETDiagramEditor::slot_updatePasteAction Gere les actions ayant besoin du presse-papier.
Definition at line 1675 of file qetdiagrameditor.cpp.
References Diagram::clipboardMayContainDiagram(), currentDiagramView(), and m_paste.
Referenced by QETDiagramEditor(), and slot_updateActions().
slot_updateUndoStack
void QETDiagramEditor::slot_updateUndoStack () slot
QETDiagramEditor::slot_updateUndoStack Update the undo stack view.
Definition at line 1486 of file qetdiagrameditor.cpp.
References currentProjectView(), and undo_group.
Referenced by slot_updateActions().
slot_updateWindowsMenu
void QETDiagramEditor::slot_updateWindowsMenu () slot
met a jour le menu "Fenetres"
Definition at line 1818 of file qetdiagrameditor.cpp.
References currentProjectView(), m_cascade_window, m_close_file, m_next_window, m_previous_window, m_tile_window, m_workspace, openedProjects(), QET::Icons::tr, windowMapper, and windows_menu.
Referenced by setTabbedMode(), setUpMenu(), setWindowedMode(), and subWindowActivated().
subWindowActivated
void QETDiagramEditor::subWindowActivated (QMdiSubWindow * subWindows) slot
QETDiagramEditor::subWindowActivated Slot used to update menu and undo stack when subwindows of MDIarea was activated.
Parameters
subWindows
Definition at line 2226 of file qetdiagrameditor.cpp.
References slot_updateActions(), and slot_updateWindowsMenu().
Referenced by QETDiagramEditor().
subWindowForWidget()
QMdiSubWindow * QETDiagramEditor::subWindowForWidget (QWidget * widget) const private
Parameters
widget Widget a rechercher dans la zone MDI
Returns
La sous-fenetre accueillant le widget passe en parametre, ou 0 si celui-ci n'a pas ete trouve.
Definition at line 1252 of file qetdiagrameditor.cpp.
References m_workspace.
Referenced by activateWidget(), and closeProject().
viewForFile()
ProjectView * QETDiagramEditor::viewForFile (const QString & filepath) const
Parameters
filepath Un chemin de fichier Note : si filepath est une chaine vide, cette methode retourne 0.
Returns
le ProjectView editant le fichier filepath, ou 0 si ce fichier n'est pas edite par cet editeur de schemas.
Definition at line 1762 of file qetdiagrameditor.cpp.
References openedProjects().
Referenced by openAndAddProject().
writeSettings
void QETDiagramEditor::writeSettings () slot
QETDiagramEditor::writeSettings Write the settings.
Definition at line 1927 of file qetdiagrameditor.cpp.
Referenced by closeEvent().
zoomGroupTriggered
void QETDiagramEditor::zoomGroupTriggered (QAction * action) slot
Definition at line 1271 of file qetdiagrameditor.cpp.
References currentDiagramView(), DiagramView::zoom(), DiagramView::zoomContent(), DiagramView::zoomFit(), and DiagramView::zoomReset().
Referenced by setUpActions().
Member Data Documentation
activeSubWindowIndex
int QETDiagramEditor::activeSubWindowIndex private
Definition at line 230 of file qetdiagrameditor.h.
Referenced by QETDiagramEditor(), and slot_updateAutoNumDock().
conductor_default
QAction* QETDiagramEditor::conductor_default private
Show a dialog to edit default conductor properties.
Definition at line 179 of file qetdiagrameditor.h.
diagram_tool_bar
QToolBar * QETDiagramEditor::diagram_tool_bar = nullptr private
Definition at line 224 of file qetdiagrameditor.h.
Referenced by setUpMenu(), and setUpToolBar().
grp_visu_sel
QActionGroup* QETDiagramEditor::grp_visu_sel private
Action group for visualisation vs edition mode.
Definition at line 161 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateModeActions().
m_add_item_actions_group
QActionGroup QETDiagramEditor::m_add_item_actions_group private
Definition at line 163 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpToolBar(), and slot_updateActions().
m_add_item_tool_bar
QToolBar * QETDiagramEditor::m_add_item_tool_bar = nullptr private
Definition at line 225 of file qetdiagrameditor.h.
Referenced by setUpToolBar().
m_add_nomenclature
QAction* QETDiagramEditor::m_add_nomenclature private
Add nomenclature graphics item;.
Definition at line 188 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_add_summary
QAction* QETDiagramEditor::m_add_summary private
Add summary graphics item.
Definition at line 189 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_auto_conductor
QAction* QETDiagramEditor::m_auto_conductor private
Enable/Disable the use of auto conductor.
Definition at line 178 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpToolBar(), and slot_updateModeActions().
m_autonumbering_dock
AutoNumberingDockWidget* QETDiagramEditor::m_autonumbering_dock private
Definition at line 229 of file qetdiagrameditor.h.
Referenced by addProject(), setUpAutonumberingWidget(), and slot_updateAutoNumDock().
m_cascade_window
QAction* QETDiagramEditor::m_cascade_window private
Show MDI subwindows as cascade.
Definition at line 194 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateWindowsMenu().
m_clean_project
QAction* QETDiagramEditor::m_clean_project private
Clean the content of the curent project by removing useless items.
Definition at line 185 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_close_file
QAction* QETDiagramEditor::m_close_file private
Close current project file.
Definition at line 204 of file qetdiagrameditor.h.
Referenced by setUpActions(), slot_updateActions(), and slot_updateWindowsMenu().
m_conductor_reset
QAction* QETDiagramEditor::m_conductor_reset
Reset paths of selected conductors.
Definition at line 152 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateComplexActions().
m_copy
QAction* QETDiagramEditor::m_copy
Copy selection to clipboard.
Definition at line 154 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateComplexActions().
m_csv_export
QAction* QETDiagramEditor::m_csv_export private
generate nomenclature
Definition at line 187 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_cut
QAction* QETDiagramEditor::m_cut
Cut selection to clipboard.
Definition at line 153 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateComplexActions().
m_delete_selection
QAction* QETDiagramEditor::m_delete_selection private
Only zoom action must displayed in the toolbar.
Delete selection
Definition at line 199 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpToolBar(), and slot_updateComplexActions().
m_depth_action_group
QActionGroup* QETDiagramEditor::m_depth_action_group = nullptr
Action related to edit a selected item.
Definition at line 158 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateComplexActions().
m_depth_tool_bar
QToolBar * QETDiagramEditor::m_depth_tool_bar = nullptr private
Definition at line 226 of file qetdiagrameditor.h.
Referenced by setUpToolBar().
m_draw_grid
QAction* QETDiagramEditor::m_draw_grid private
Switch the background grid display or not.
Definition at line 181 of file qetdiagrameditor.h.
Referenced by drawGrid(), setUpActions(), setUpMenu(), and setUpToolBar().
m_edit_diagram_properties
QAction* QETDiagramEditor::m_edit_diagram_properties
Show a dialog to edit diagram properties.
Definition at line 151 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateActions().
m_edit_selection
QAction* QETDiagramEditor::m_edit_selection private
To edit selected item.
Definition at line 197 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateComplexActions().
m_element_collection_widget
ElementsCollectionWidget* QETDiagramEditor::m_element_collection_widget private
Dock for the undo list.
Definition at line 215 of file qetdiagrameditor.h.
Referenced by addProject(), event(), findElementInPanel(), projectWasClosed(), save(), saveAs(), and setUpElementsCollectionWidget().
m_export_diagram
QAction* QETDiagramEditor::m_export_diagram private
Export diagrams of the current project as imagess.
Definition at line 172 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_export_project_db
QAction* QETDiagramEditor::m_export_project_db private
Definition at line 192 of file qetdiagrameditor.h.
Referenced by setUpActions(), and setUpMenu().
m_file_actions_group
QActionGroup QETDiagramEditor::m_file_actions_group private
Action related to global selections.
Definition at line 166 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and setUpToolBar().
m_find
QAction* QETDiagramEditor::m_find = nullptr private
Definition at line 207 of file qetdiagrameditor.h.
Referenced by setUpActions(), and setUpMenu().
m_find_element
QAction* QETDiagramEditor::m_find_element private
Find the selected element in the panel.
Definition at line 202 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateComplexActions().
m_first_show
bool QETDiagramEditor::m_first_show = true private
Definition at line 231 of file qetdiagrameditor.h.
Referenced by event().
m_grey_background
QAction* QETDiagramEditor::m_grey_background private
Switch the background color in white or grey.
Definition at line 180 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateActions().
m_group_selected_texts
QAction* QETDiagramEditor::m_group_selected_texts = nullptr private
Definition at line 203 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateComplexActions().
m_group_view_mode
QActionGroup* QETDiagramEditor::m_group_view_mode private
Action group for project.
Definition at line 162 of file qetdiagrameditor.h.
Referenced by setUpActions().
m_mode_selection
QAction* QETDiagramEditor::m_mode_selection private
Set edition mode.
Definition at line 170 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateModeActions().
m_mode_visualise
QAction* QETDiagramEditor::m_mode_visualise private
Set visualisation mode.
Definition at line 171 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateModeActions().
m_next_window
QAction* QETDiagramEditor::m_next_window private
Switch to the next document.
Definition at line 196 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateWindowsMenu().
m_paste
QAction* QETDiagramEditor::m_paste private
Paste clipboard content on the current diagram.
Definition at line 177 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updatePasteAction().
m_previous_window
QAction* QETDiagramEditor::m_previous_window private
Switch to the previous document.
Definition at line 195 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateWindowsMenu().
m_print
QAction* QETDiagramEditor::m_print private
Print diagrams of the current project.
Definition at line 173 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), setUpToolBar(), and slot_updateActions().
m_project_add_diagram
QAction* QETDiagramEditor::m_project_add_diagram private
Add a diagram to the current project.
Definition at line 183 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_project_edit_properties
QAction* QETDiagramEditor::m_project_edit_properties private
Edit the properties of the current project.
Definition at line 182 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_project_export_conductor_num
QAction* QETDiagramEditor::m_project_export_conductor_num private
Export the wire num to csv.
Definition at line 191 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_project_folio_list
QAction* QETDiagramEditor::m_project_folio_list private
Sommaire des schemas.
Definition at line 186 of file qetdiagrameditor.h.
m_project_terminalBloc
QAction* QETDiagramEditor::m_project_terminalBloc private
generate terminal block
Definition at line 190 of file qetdiagrameditor.h.
Referenced by setUpActions(), and setUpMenu().
m_qdw_elmt_collection
QDockWidget* QETDiagramEditor::m_qdw_elmt_collection private
Dock for the elements panel.
Definition at line 213 of file qetdiagrameditor.h.
Referenced by setUpElementsCollectionWidget().
m_quit_editor
QAction* QETDiagramEditor::m_quit_editor private
Quit the diagram editor.
Definition at line 174 of file qetdiagrameditor.h.
Referenced by setUpActions(), and setUpMenu().
m_remove_diagram_from_project
QAction* QETDiagramEditor::m_remove_diagram_from_project private
Delete a diagram from the current project.
Definition at line 184 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_rotate_selection
QAction* QETDiagramEditor::m_rotate_selection private
Rotate selected elements and text items by 90 degrees.
Definition at line 200 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpToolBar(), and slot_updateComplexActions().
m_rotate_texts
QAction* QETDiagramEditor::m_rotate_texts private
Direct selected text items to a specific angle.
Definition at line 201 of file qetdiagrameditor.h.
Referenced by setUpActions(), slot_updateActions(), and slot_updateComplexActions().
m_row_column_actions_group
QActionGroup QETDiagramEditor::m_row_column_actions_group
Definition at line 156 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_save_file
QAction* QETDiagramEditor::m_save_file private
Save current project.
Definition at line 205 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateActions().
m_save_file_as
QAction* QETDiagramEditor::m_save_file_as private
Save current project as a specific file.
Definition at line 206 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateActions().
m_search_and_replace_widget
SearchAndReplaceWidget QETDiagramEditor::m_search_and_replace_widget private
Definition at line 232 of file qetdiagrameditor.h.
Referenced by QETDiagramEditor(), and setUpActions().
m_select_actions_group
QActionGroup QETDiagramEditor::m_select_actions_group private
Action related to zoom for diagram.
Definition at line 165 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
m_selection_actions_group
QActionGroup QETDiagramEditor::m_selection_actions_group
Action related to add/remove rows/column in diagram.
Definition at line 157 of file qetdiagrameditor.h.
Referenced by setUpActions(), and setUpMenu().
m_selection_properties_editor
DiagramPropertiesEditorDockWidget* QETDiagramEditor::m_selection_properties_editor private
Definition at line 217 of file qetdiagrameditor.h.
Referenced by projectWasClosed(), selectionChanged(), and setUpSelectionPropertiesEditor().
m_tabbed_view_mode
QAction* QETDiagramEditor::m_tabbed_view_mode private
Actions related to file (open, close, save...)
Display projects as tabs
Definition at line 168 of file qetdiagrameditor.h.
Referenced by setTabbedMode(), setUpActions(), and setUpMenu().
m_tile_window
QAction* QETDiagramEditor::m_tile_window private
Export to file the internal database of the current project.
Show MDI subwindows as tile
Definition at line 193 of file qetdiagrameditor.h.
Referenced by setUpActions(), and slot_updateWindowsMenu().
m_windowed_view_mode
QAction* QETDiagramEditor::m_windowed_view_mode private
Display projects as windows.
Definition at line 169 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and setWindowedMode().
m_workspace
QMdiArea QETDiagramEditor::m_workspace private
Definition at line 209 of file qetdiagrameditor.h.
Referenced by activateWidget(), addProjectView(), currentProjectView(), openedProjects(), QETDiagramEditor(), setTabbedMode(), setUpActions(), setWindowedMode(), slot_updateAutoNumDock(), slot_updateWindowsMenu(), and subWindowForWidget().
m_zoom_action_toolBar
QList<QAction *> QETDiagramEditor::m_zoom_action_toolBar private
Definition at line 198 of file qetdiagrameditor.h.
Referenced by setUpActions(), and setUpToolBar().
m_zoom_actions_group
QActionGroup QETDiagramEditor::m_zoom_actions_group private
Action related to adding (add text image shape...)
Definition at line 164 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and slot_updateActions().
main_tool_bar
QToolBar* QETDiagramEditor::main_tool_bar = nullptr private
Definition at line 222 of file qetdiagrameditor.h.
Referenced by setUpMenu(), and setUpToolBar().
open_dialog_dir
QDir QETDiagramEditor::open_dialog_dir private
Definition at line 211 of file qetdiagrameditor.h.
Referenced by openProject().
pa
ElementsPanelWidget* QETDiagramEditor::pa private
Elements panel.
Definition at line 219 of file qetdiagrameditor.h.
Referenced by addProject(), projectWasClosed(), reloadOldElementPanel(), and setUpElementsPanel().
qdw_pa
QDockWidget* QETDiagramEditor::qdw_pa private
Directory to use for file dialogs such as File > save.
Definition at line 212 of file qetdiagrameditor.h.
Referenced by QETDiagramEditor(), setUpElementsPanel(), and setUpMenu().
qdw_undo
QDockWidget* QETDiagramEditor::qdw_undo private
Definition at line 214 of file qetdiagrameditor.h.
Referenced by QETDiagramEditor(), setUpMenu(), and setUpUndoStack().
redo
QAction* QETDiagramEditor::redo private
Redo the latest cancelled operation.
Definition at line 176 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and setUpToolBar().
undo
QAction* QETDiagramEditor::undo private
Cancel the latest action.
Definition at line 175 of file qetdiagrameditor.h.
Referenced by setUpActions(), setUpMenu(), and setUpToolBar().
undo_group
QUndoGroup QETDiagramEditor::undo_group private
Definition at line 228 of file qetdiagrameditor.h.
Referenced by addProject(), projectWasClosed(), setUpActions(), setUpUndoStack(), and slot_updateUndoStack().
view_tool_bar
QToolBar * QETDiagramEditor::view_tool_bar = nullptr private
Definition at line 223 of file qetdiagrameditor.h.
Referenced by setUpMenu(), and setUpToolBar().
windowMapper
QSignalMapper QETDiagramEditor::windowMapper private
Definition at line 210 of file qetdiagrameditor.h.
Referenced by QETDiagramEditor(), and slot_updateWindowsMenu().
windows_menu
QMenu* QETDiagramEditor::windows_menu private
Definition at line 220 of file qetdiagrameditor.h.
Referenced by setUpMenu(), and slot_updateWindowsMenu().
The documentation for this class was generated from the following files:
qetdiagrameditor.h
qetdiagrameditor.cpp