QElectroTech: QetShapeItem Class Reference
QetShapeItem Class Reference
The QetShapeItem class this class is used to draw a basic shape (line, rectangle, ellipse) into a diagram, that can be saved to .qet file.
#include <qetshapeitem.h>
Public Types
enum ShapeType { Line =1, Rectangle =2, Ellipse =4, Polygon =8 }
enum { Type = UserType + 1008 }
Signals
void penChanged ()
void brushChanged ()
void closeChanged ()
void XRadiusChanged ()
void YRadiusChanged ()
Public Member Functions
QetShapeItem (QPointF, QPointF=QPointF(0, 0), ShapeType=Line, QGraphicsItem *parent=nullptr)
QetShapeItem::QetShapeItem Constructor of shape item. point 1 and 2 must be in scene coordinate.
~QetShapeItem () override
int type () const override
QPen pen () const
METHODS.
void setPen (const QPen &pen)
QetShapeItem::setPen Set the pen to use for draw the shape.
QBrush brush () const
void setBrush (const QBrush &brush)
QetShapeItem::setBrush Set the brush to use for the fill the shape.
ShapeType shapeType () const
virtual bool fromXml (const QDomElement &)
QetShapeItem::fromXml Build this item from the xml description.
virtual QDomElement toXml (QDomDocument &document) const
QetShapeItem::toXml Save this item to xml element.
virtual bool toDXF (const QString &filepath, const QPen &pen)
QetShapeItem::toDXF Draw this element to the dxf document.
void editProperty () override
QetShapeItem::editProperty Edit the property of this item.
QString name () const override
QetShapeItem::name.
void setP2 (const QPointF &P2)
QetShapeItem::setP2 Set the second point of this item. If this item is a polyline, the last point of the polyline is replaced by P2.
QLineF line () const
bool setLine (const QLineF &line)
QetShapeItem::setLine Set item geometry to line (only available for line shape)
QRectF rect () const
bool setRect (const QRectF &rect)
QetShapeItem::setRect Set this item geometry to rect (only available if shape is a rectangle or an ellipse)
QPolygonF polygon () const
bool setPolygon (const QPolygonF &polygon)
QetShapeItem::setPolygon Set this item geometry to polygon (only available if shape is a polyline)
bool isClosed () const
void setClosed (bool close)
QetShapeItem::setClosed Close this item, have effect only if this item is a polygon.
qreal XRadius () const
void setXRadius (qreal X)
qreal YRadius () const
void setYRadius (qreal Y)
int pointsCount () const
QetShapeItem::pointCount.
void setNextPoint (QPointF P)
QetShapeItem::setNextPoint Add a new point to the curent polygon.
void removePoints (int number=1)
QetShapeItem::removePoints Number of point to remove on the polygon If number is superior to number of polygon points-2, all points of polygon will be removed except the first two (minimum point for the polygon);.
QRectF boundingRect () const override
QetShapeItem::boundingRect.
QPainterPath shape () const override
QetShapeItem::shape.
Public Member Functions inherited from QetGraphicsItem
QetGraphicsItem (QGraphicsItem *parent=nullptr)
QetGraphicsItem::QetGraphicsItem Default constructor.
~QetGraphicsItem () override=0
Diagram * diagram () const
QetGraphicsItem::diagram return the diagram of this item.
virtual void setPos (const QPointF &p)
QetGraphicsItem::setPos set the position of the item to p.
virtual void setPos (qreal x, qreal y)
QetGraphicsItem::setPos set the position of the item.
virtual bool isMovable () const
virtual void setMovable (bool movable)
QET::GraphicsItemState state () const
QetGraphicsItem::state.
Protected Member Functions
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
QetShapeItem::paint Paint this item.
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
QetShapeItem::hoverEnterEvent Handle hover enter event.
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QetShapeItem::hoverLeaveEvent Handle hover leave event.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
QetShapeItem::itemChange.
bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
QetShapeItem::sceneEventFilter.
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) override
QetShapeItem::contextMenuEvent.
Protected Member Functions inherited from QetGraphicsItem
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mousePressEvent handle the mouse click.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseDoubleClickEvent handle the mouse double click.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseMoveEvent handle mouse movement.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseReleaseEvent handle mouse release click.
Properties
QPen pen
QBrush brush
QRectF rect
QLineF line
QPolygonF polygon
bool close
qreal xRadius
qreal yRadius
Private Member Functions
void switchResizeMode ()
QetShapeItem::switchResizeMode.
void addHandler ()
void adjusteHandlerPos ()
QetShapeItem::adjusteHandlerPos Adjust the position of the handler item.
void insertPoint ()
void removePoint ()
void handlerMousePressEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
QetShapeItem::handlerMousePressEvent.
void handlerMouseMoveEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
QetShapeItem::handlerMouseMoveEvent.
void handlerMouseReleaseEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
QetShapeItem::handlerMouseReleaseEvent.
Private Attributes
ShapeType m_shapeType
ATTRIBUTES.
QPen m_pen
QBrush m_brush
QPointF m_P1
QPointF m_P2
QPointF m_old_P1
QPointF m_old_P2
QPointF m_context_menu_pos
QPolygonF m_polygon
QPolygonF m_old_polygon
bool m_hovered
int m_vector_index
bool m_closed = false
bool m_modifie_radius_equaly = false
int m_resize_mode = 1
QVector< QetGraphicsHandlerItem * > m_handler_vector
QAction * m_insert_point
QAction * m_remove_point
qreal m_xRadius = 0
qreal m_yRadius = 0
qreal m_old_xRadius
qreal m_old_yRadius
Additional Inherited Members
Protected Attributes inherited from QetGraphicsItem
bool is_movable_
bool m_first_move
bool snap_to_grid_
QPointF m_mouse_to_origin_movement
QET::GraphicsItemState m_state = QET:: GIOK
Detailed Description
The QetShapeItem class this class is used to draw a basic shape (line, rectangle, ellipse) into a diagram, that can be saved to .qet file.
Definition at line 35 of file qetshapeitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 63 of file qetshapeitem.h.
ShapeType
enum QetShapeItem::ShapeType
Enumerator
Line
Rectangle
Ellipse
Polygon
Definition at line 57 of file qetshapeitem.h.
Constructor & Destructor Documentation
QetShapeItem()
QetShapeItem::QetShapeItem (QPointF p1, QPointF p2 = QPointF(0,0), ShapeType type = Line, QGraphicsItem * parent = nullptr)
QetShapeItem::QetShapeItem Constructor of shape item. point 1 and 2 must be in scene coordinate.
Parameters
p1 first point
p2 second point
type type of item (line, rectangle, ellipse)
parent parent item
Definition at line 38 of file qetshapeitem.cpp.
References QET::Icons::Add, insertPoint(), m_handler_vector, m_insert_point, m_P1, m_P2, m_pen, m_polygon, m_remove_point, Polygon, QET::Icons::Remove, removePoint(), QET::Icons::tr, and type().
~QetShapeItem()
QetShapeItem::~QetShapeItem () override
Definition at line 65 of file qetshapeitem.cpp.
References m_handler_vector.
Member Function Documentation
addHandler()
void QetShapeItem::addHandler () private
Definition at line 561 of file qetshapeitem.cpp.
References Ellipse, QetGraphicsHandlerItem::handlerForPoint(), Line, m_handler_vector, m_P1, m_P2, m_polygon, m_resize_mode, m_shapeType, m_xRadius, m_yRadius, QetGraphicsHandlerUtility::pointForRadiusRect(), QetGraphicsHandlerUtility::pointsForRect(), Polygon, and Rectangle.
Referenced by adjusteHandlerPos(), itemChange(), and switchResizeMode().
adjusteHandlerPos()
void QetShapeItem::adjusteHandlerPos () private
QetShapeItem::adjusteHandlerPos Adjust the position of the handler item.
Definition at line 606 of file qetshapeitem.cpp.
References addHandler(), Ellipse, Line, m_handler_vector, m_P1, m_P2, m_polygon, m_resize_mode, m_shapeType, m_xRadius, m_yRadius, QetGraphicsHandlerUtility::pointForRadiusRect(), QetGraphicsHandlerUtility::pointsForRect(), Polygon, and Rectangle.
Referenced by handlerMouseMoveEvent(), itemChange(), setLine(), setPolygon(), setRect(), setXRadius(), and setYRadius().
boundingRect()
QRectF QetShapeItem::boundingRect () const override
QetShapeItem::boundingRect.
Returns
the bounding rect of this item
Definition at line 249 of file qetshapeitem.cpp.
References shape().
Referenced by removePoints().
brush()
QBrush QetShapeItem::brush () const inline
Definition at line 75 of file qetshapeitem.h.
References m_brush.
brushChanged
void QetShapeItem::brushChanged () signal
Referenced by setBrush(), and ShapeGraphicsItemPropertiesWidget::setItem().
closeChanged
void QetShapeItem::closeChanged () signal
Referenced by setClosed(), ShapeGraphicsItemPropertiesWidget::setItem(), and ShapeGraphicsItemPropertiesWidget::setUpEditConnection().
contextMenuEvent()
void QetShapeItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) override protected
QetShapeItem::contextMenuEvent.
Parameters
event
Definition at line 452 of file qetshapeitem.cpp.
References DiagramView::contextMenuActions(), QetGraphicsItem::diagram(), m_context_menu_pos, m_handler_vector, m_insert_point, m_remove_point, m_shapeType, and Polygon.
editProperty()
void QetShapeItem::editProperty () override virtual
QetShapeItem::editProperty Edit the property of this item.
Reimplemented from QetGraphicsItem.
Definition at line 1004 of file qetshapeitem.cpp.
References QetGraphicsItem::diagram().
fromXml()
bool QetShapeItem::fromXml (const QDomElement & e) virtual
QetShapeItem::fromXml Build this item from the xml description.
Parameters
e element where is stored this item
Returns
true if load success
Definition at line 849 of file qetshapeitem.cpp.
References QETXML::brushFromXml(), QET::Icons::de, Ellipse, QET::findInDomElement(), QetGraphicsItem::is_movable_, Line, m_brush, m_closed, m_P1, m_P2, m_pen, m_polygon, m_shapeType, QETXML::penFromXml(), Polygon, Rectangle, setXRadius(), setYRadius(), and type().
handlerMouseMoveEvent()
void QetShapeItem::handlerMouseMoveEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
QetShapeItem::handlerMouseMoveEvent.
Parameters
qghi
event
Definition at line 726 of file qetshapeitem.cpp.
References adjusteHandlerPos(), Ellipse, Line, m_modifie_radius_equaly, m_P1, m_P2, m_polygon, m_resize_mode, m_shapeType, m_vector_index, QetGraphicsHandlerUtility::mirrorRectForPosAtIndex(), Polygon, QetGraphicsHandlerUtility::radiusForPosAtIndex(), Rectangle, QetGraphicsHandlerUtility::rectForPosAtIndex(), setRect(), setXRadius(), setYRadius(), and Diagram::snapToGrid().
Referenced by sceneEventFilter().
handlerMousePressEvent()
void QetShapeItem::handlerMousePressEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
QetShapeItem::handlerMousePressEvent.
Parameters
qghi
event
Definition at line 706 of file qetshapeitem.cpp.
References m_modifie_radius_equaly, m_old_P1, m_old_P2, m_old_polygon, m_old_xRadius, m_old_yRadius, m_P1, m_P2, m_polygon, m_xRadius, and m_yRadius.
Referenced by sceneEventFilter().
handlerMouseReleaseEvent()
void QetShapeItem::handlerMouseReleaseEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
QetShapeItem::handlerMouseReleaseEvent.
Parameters
qghi
event
Definition at line 790 of file qetshapeitem.cpp.
References QetGraphicsItem::diagram(), Ellipse, Line, m_modifie_radius_equaly, m_old_P1, m_old_P2, m_old_polygon, m_old_xRadius, m_old_yRadius, m_P1, m_P2, m_polygon, m_resize_mode, m_shapeType, m_xRadius, m_yRadius, name(), Polygon, Rectangle, QPropertyUndoCommand::setAnimated(), QET::Icons::tr, Diagram::undoStack(), and XRadius().
Referenced by sceneEventFilter().
hoverEnterEvent()
void QetShapeItem::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
QetShapeItem::hoverEnterEvent Handle hover enter event.
Parameters
event
Definition at line 341 of file qetshapeitem.cpp.
References m_hovered.
hoverLeaveEvent()
void QetShapeItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
QetShapeItem::hoverLeaveEvent Handle hover leave event.
Parameters
event
Definition at line 352 of file qetshapeitem.cpp.
References m_hovered.
insertPoint()
void QetShapeItem::insertPoint () private
Definition at line 652 of file qetshapeitem.cpp.
References QetGraphicsItem::diagram(), m_closed, m_context_menu_pos, m_polygon, m_shapeType, polygon, Polygon, QetGraphicsHandlerUtility::polygonForInsertPoint(), Diagram::snapToGrid(), QET::Icons::tr, and Diagram::undoStack().
Referenced by QetShapeItem().
isClosed()
bool QetShapeItem::isClosed () const inline
Definition at line 93 of file qetshapeitem.h.
References m_closed.
Referenced by ShapeGraphicsItemPropertiesWidget::associatedUndo(), and ShapeGraphicsItemPropertiesWidget::updateUi().
itemChange()
QVariant QetShapeItem::itemChange (GraphicsItemChange change, const QVariant & value) override protected
QetShapeItem::itemChange.
Parameters
change
value
Returns
Definition at line 375 of file qetshapeitem.cpp.
References addHandler(), adjusteHandlerPos(), m_handler_vector, and m_resize_mode.
line()
QLineF QetShapeItem::line () const inline
Definition at line 87 of file qetshapeitem.h.
References m_P1, and m_P2.
mousePressEvent()
void QetShapeItem::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 358 of file qetshapeitem.cpp.
References QetGraphicsItem::mousePressEvent(), and switchResizeMode().
name()
QString QetShapeItem::name () const override virtual
QetShapeItem::name.
Returns
the name of the curent shape.
Reimplemented from QetGraphicsItem.
Definition at line 1016 of file qetshapeitem.cpp.
References Ellipse, Line, m_shapeType, Polygon, Rectangle, and QET::Icons::tr.
Referenced by handlerMouseReleaseEvent().
paint()
void QetShapeItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override protected
QetShapeItem::paint Paint this item.
Parameters
painter
option
widget
Definition at line 298 of file qetshapeitem.cpp.
References Ellipse, Line, m_brush, m_closed, m_hovered, m_P1, m_P2, m_pen, m_polygon, m_shapeType, m_xRadius, m_yRadius, Polygon, Rectangle, setBrush(), setPen(), and shape().
pen()
QPen QetShapeItem::pen () const inline
METHODS.
Definition at line 73 of file qetshapeitem.h.
References m_pen.
penChanged
void QetShapeItem::penChanged () signal
Referenced by ShapeGraphicsItemPropertiesWidget::setItem(), setPen(), and ShapeGraphicsItemPropertiesWidget::setUpEditConnection().
pointsCount()
int QetShapeItem::pointsCount () const
QetShapeItem::pointCount.
Returns
the number of point in the polygon
Definition at line 206 of file qetshapeitem.cpp.
References m_polygon.
Referenced by DiagramEventAddShape::mouseReleaseEvent(), and removePoints().
polygon()
QPolygonF QetShapeItem::polygon () const inline
Definition at line 91 of file qetshapeitem.h.
References m_polygon.
rect()
QRectF QetShapeItem::rect () const inline
Definition at line 89 of file qetshapeitem.h.
References m_P1, and m_P2.
removePoint()
void QetShapeItem::removePoint () private
Definition at line 668 of file qetshapeitem.cpp.
References QetGraphicsItem::diagram(), m_context_menu_pos, m_handler_vector, m_shapeType, polygon, Polygon, QET::Icons::tr, and Diagram::undoStack().
Referenced by QetShapeItem().
removePoints()
void QetShapeItem::removePoints (int number = 1)
QetShapeItem::removePoints Number of point to remove on the polygon If number is superior to number of polygon points-2, all points of polygon will be removed except the first two (minimum point for the polygon);.
Definition at line 228 of file qetshapeitem.cpp.
References boundingRect(), m_polygon, and pointsCount().
Referenced by DiagramEventAddShape::mouseDoubleClickEvent(), and DiagramEventAddShape::mouseReleaseEvent().
sceneEventFilter()
bool QetShapeItem::sceneEventFilter (QGraphicsItem * watched, QEvent * event) override protected
QetShapeItem::sceneEventFilter.
Parameters
watched
event
Returns
Definition at line 414 of file qetshapeitem.cpp.
References handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), m_handler_vector, m_vector_index, and QetGraphicsHandlerItem::Type.
setBrush()
void QetShapeItem::setBrush (const QBrush & brush)
QetShapeItem::setBrush Set the brush to use for the fill the shape.
Parameters
brush
Definition at line 89 of file qetshapeitem.cpp.
References brush, brushChanged(), and m_brush.
Referenced by paint().
setClosed()
void QetShapeItem::setClosed (bool close)
QetShapeItem::setClosed Close this item, have effect only if this item is a polygon.
Parameters
close
Definition at line 176 of file qetshapeitem.cpp.
References close, closeChanged(), m_closed, m_shapeType, and Polygon.
Referenced by DiagramEventAddShape::mouseDoubleClickEvent().
setLine()
bool QetShapeItem::setLine (const QLineF & line)
QetShapeItem::setLine Set item geometry to line (only available for line shape)
Parameters
line
Returns
: true when shape is a Line, else false
Definition at line 124 of file qetshapeitem.cpp.
References adjusteHandlerPos(), line, Line, m_P1, m_P2, and m_shapeType.
setNextPoint()
void QetShapeItem::setNextPoint (QPointF P)
QetShapeItem::setNextPoint Add a new point to the curent polygon.
Parameters
P the new point.
Definition at line 215 of file qetshapeitem.cpp.
References m_polygon, and Diagram::snapToGrid().
Referenced by DiagramEventAddShape::mousePressEvent().
setP2()
void QetShapeItem::setP2 (const QPointF & P2)
QetShapeItem::setP2 Set the second point of this item. If this item is a polyline, the last point of the polyline is replaced by P2.
Parameters
P2
Definition at line 104 of file qetshapeitem.cpp.
References m_P2, m_polygon, m_shapeType, and Polygon.
Referenced by DiagramEventAddShape::mouseMoveEvent(), DiagramEventAddShape::mousePressEvent(), and DiagramEventAddShape::mouseReleaseEvent().
setPen()
void QetShapeItem::setPen (const QPen & pen)
QetShapeItem::setPen Set the pen to use for draw the shape.
Parameters
pen
Definition at line 76 of file qetshapeitem.cpp.
References m_pen, pen, and penChanged().
Referenced by paint().
setPolygon()
bool QetShapeItem::setPolygon (const QPolygonF & polygon)
QetShapeItem::setPolygon Set this item geometry to polygon (only available if shape is a polyline)
Parameters
polygon : new polygon
Returns
true if item is polygon, else false
Definition at line 160 of file qetshapeitem.cpp.
References adjusteHandlerPos(), m_polygon, m_shapeType, polygon, and Polygon.
setRect()
bool QetShapeItem::setRect (const QRectF & rect)
QetShapeItem::setRect Set this item geometry to rect (only available if shape is a rectangle or an ellipse)
Parameters
rect : new rect
Returns
: true when shape is rectangle or ellipse, else false
Definition at line 140 of file qetshapeitem.cpp.
References adjusteHandlerPos(), Ellipse, m_P1, m_P2, m_shapeType, rect, and Rectangle.
Referenced by handlerMouseMoveEvent(), and DiagramEventAddShape::mousePressEvent().
setXRadius()
void QetShapeItem::setXRadius (qreal X)
Definition at line 186 of file qetshapeitem.cpp.
References adjusteHandlerPos(), m_xRadius, and XRadiusChanged().
Referenced by fromXml(), and handlerMouseMoveEvent().
setYRadius()
void QetShapeItem::setYRadius (qreal Y)
Definition at line 194 of file qetshapeitem.cpp.
References adjusteHandlerPos(), m_yRadius, and YRadiusChanged().
Referenced by fromXml(), and handlerMouseMoveEvent().
shape()
QPainterPath QetShapeItem::shape () const override
QetShapeItem::shape.
Returns
the shape of this item
Definition at line 257 of file qetshapeitem.cpp.
References Ellipse, Line, m_closed, m_hovered, m_P1, m_P2, m_pen, m_polygon, m_shapeType, m_xRadius, m_yRadius, Polygon, and Rectangle.
Referenced by boundingRect(), and paint().
shapeType()
ShapeType QetShapeItem::shapeType () const inline
Definition at line 77 of file qetshapeitem.h.
References m_shapeType.
Referenced by DiagramEventAddShape::mousePressEvent(), ShapeGraphicsItemPropertiesWidget::setItem(), and ShapeGraphicsItemPropertiesWidget::updateUi().
switchResizeMode()
void QetShapeItem::switchResizeMode () private
QetShapeItem::switchResizeMode.
Definition at line 510 of file qetshapeitem.cpp.
References addHandler(), Ellipse, m_handler_vector, m_resize_mode, m_shapeType, and Rectangle.
Referenced by mousePressEvent().
toDXF()
bool QetShapeItem::toDXF (const QString & filepath, const QPen & pen) virtual
QetShapeItem::toDXF Draw this element to the dxf document.
Parameters
filepath file path of the the dxf document
pen
Returns
true if draw success
Definition at line 967 of file qetshapeitem.cpp.
References Createdxf::drawEllipse(), Createdxf::drawLine(), Createdxf::drawRectangle(), Ellipse, Createdxf::getcolorCode(), Line, m_P1, m_P2, m_shapeType, pen, and Rectangle.
Referenced by ExportDialog::generateDxf().
toXml()
QDomElement QetShapeItem::toXml (QDomDocument & document) const virtual
QetShapeItem::toXml Save this item to xml element.
Parameters
document parent document xml
Returns
element xml where is write this item
Definition at line 906 of file qetshapeitem.cpp.
References QETXML::brushToXml(), QetGraphicsItem::is_movable_, m_brush, m_closed, m_P1, m_P2, m_pen, m_polygon, m_shapeType, m_xRadius, m_yRadius, QETXML::penToXml(), Polygon, rect, and Rectangle.
type()
int QetShapeItem::type () const inline override
Definition at line 70 of file qetshapeitem.h.
References Type.
Referenced by fromXml(), and QetShapeItem().
XRadius()
qreal QetShapeItem::XRadius () const inline
Definition at line 95 of file qetshapeitem.h.
References m_xRadius.
Referenced by handlerMouseReleaseEvent().
XRadiusChanged
void QetShapeItem::XRadiusChanged () signal
Referenced by setXRadius().
YRadius()
qreal QetShapeItem::YRadius () const inline
Definition at line 97 of file qetshapeitem.h.
References m_yRadius.
YRadiusChanged
void QetShapeItem::YRadiusChanged () signal
Referenced by setYRadius().
Member Data Documentation
m_brush
QBrush QetShapeItem::m_brush private
Definition at line 132 of file qetshapeitem.h.
Referenced by brush(), fromXml(), paint(), setBrush(), and toXml().
m_closed
bool QetShapeItem::m_closed = false private
Definition at line 141 of file qetshapeitem.h.
Referenced by fromXml(), insertPoint(), isClosed(), paint(), setClosed(), shape(), and toXml().
m_context_menu_pos
QPointF QetShapeItem::m_context_menu_pos private
Definition at line 137 of file qetshapeitem.h.
Referenced by contextMenuEvent(), insertPoint(), and removePoint().
m_handler_vector
QVector<QetGraphicsHandlerItem *> QetShapeItem::m_handler_vector private
Definition at line 144 of file qetshapeitem.h.
Referenced by addHandler(), adjusteHandlerPos(), contextMenuEvent(), itemChange(), QetShapeItem(), removePoint(), sceneEventFilter(), switchResizeMode(), and ~QetShapeItem().
m_hovered
bool QetShapeItem::m_hovered private
Definition at line 139 of file qetshapeitem.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), paint(), and shape().
m_insert_point
QAction* QetShapeItem::m_insert_point private
Definition at line 145 of file qetshapeitem.h.
Referenced by contextMenuEvent(), and QetShapeItem().
m_modifie_radius_equaly
bool QetShapeItem::m_modifie_radius_equaly = false private
Definition at line 142 of file qetshapeitem.h.
Referenced by handlerMouseMoveEvent(), handlerMousePressEvent(), and handlerMouseReleaseEvent().
m_old_P1
QPointF QetShapeItem::m_old_P1 private
Definition at line 135 of file qetshapeitem.h.
Referenced by handlerMousePressEvent(), and handlerMouseReleaseEvent().
m_old_P2
QPointF QetShapeItem::m_old_P2 private
Definition at line 136 of file qetshapeitem.h.
Referenced by handlerMousePressEvent(), and handlerMouseReleaseEvent().
m_old_polygon
QPolygonF QetShapeItem::m_old_polygon private
Definition at line 138 of file qetshapeitem.h.
Referenced by handlerMousePressEvent(), and handlerMouseReleaseEvent().
m_old_xRadius
qreal QetShapeItem::m_old_xRadius private
Definition at line 149 of file qetshapeitem.h.
Referenced by handlerMousePressEvent(), and handlerMouseReleaseEvent().
m_old_yRadius
qreal QetShapeItem::m_old_yRadius private
Definition at line 150 of file qetshapeitem.h.
Referenced by handlerMousePressEvent(), and handlerMouseReleaseEvent().
m_P1
QPointF QetShapeItem::m_P1 private
Definition at line 133 of file qetshapeitem.h.
Referenced by addHandler(), adjusteHandlerPos(), fromXml(), handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), line(), paint(), QetShapeItem(), rect(), setLine(), setRect(), shape(), toDXF(), and toXml().
m_P2
QPointF QetShapeItem::m_P2 private
Definition at line 134 of file qetshapeitem.h.
Referenced by addHandler(), adjusteHandlerPos(), fromXml(), handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), line(), paint(), QetShapeItem(), rect(), setLine(), setP2(), setRect(), shape(), toDXF(), and toXml().
m_pen
QPen QetShapeItem::m_pen private
Definition at line 131 of file qetshapeitem.h.
Referenced by fromXml(), paint(), pen(), QetShapeItem(), setPen(), shape(), and toXml().
m_polygon
QPolygonF QetShapeItem::m_polygon private
Definition at line 138 of file qetshapeitem.h.
Referenced by addHandler(), adjusteHandlerPos(), fromXml(), handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), insertPoint(), paint(), pointsCount(), polygon(), QetShapeItem(), removePoints(), setNextPoint(), setP2(), setPolygon(), shape(), and toXml().
m_remove_point
QAction * QetShapeItem::m_remove_point private
Definition at line 146 of file qetshapeitem.h.
Referenced by contextMenuEvent(), and QetShapeItem().
m_resize_mode
int QetShapeItem::m_resize_mode = 1 private
Definition at line 143 of file qetshapeitem.h.
Referenced by addHandler(), adjusteHandlerPos(), handlerMouseMoveEvent(), handlerMouseReleaseEvent(), itemChange(), and switchResizeMode().
m_shapeType
ShapeType QetShapeItem::m_shapeType private
ATTRIBUTES.
Definition at line 130 of file qetshapeitem.h.
Referenced by addHandler(), adjusteHandlerPos(), contextMenuEvent(), fromXml(), handlerMouseMoveEvent(), handlerMouseReleaseEvent(), insertPoint(), name(), paint(), removePoint(), setClosed(), setLine(), setP2(), setPolygon(), setRect(), shape(), shapeType(), switchResizeMode(), toDXF(), and toXml().
m_vector_index
int QetShapeItem::m_vector_index private
Definition at line 140 of file qetshapeitem.h.
Referenced by handlerMouseMoveEvent(), and sceneEventFilter().
m_xRadius
qreal QetShapeItem::m_xRadius = 0 private
Definition at line 147 of file qetshapeitem.h.
Referenced by addHandler(), adjusteHandlerPos(), handlerMousePressEvent(), handlerMouseReleaseEvent(), paint(), setXRadius(), shape(), toXml(), and XRadius().
m_yRadius
qreal QetShapeItem::m_yRadius = 0 private
Definition at line 148 of file qetshapeitem.h.
Referenced by addHandler(), adjusteHandlerPos(), handlerMousePressEvent(), handlerMouseReleaseEvent(), paint(), setYRadius(), shape(), toXml(), and YRadius().
Property Documentation
brush
QBrush QetShapeItem::brush read write
Definition at line 1 of file qetshapeitem.h.
Referenced by ShapeGraphicsItemPropertiesWidget::associatedUndo(), setBrush(), and ShapeGraphicsItemPropertiesWidget::updateUi().
close
bool QetShapeItem::close read write
Definition at line 1 of file qetshapeitem.h.
Referenced by setClosed().
line
QLineF QetShapeItem::line read write
Definition at line 1 of file qetshapeitem.h.
Referenced by setLine().
pen
QPen QetShapeItem::pen read write
Definition at line 1 of file qetshapeitem.h.
Referenced by ShapeGraphicsItemPropertiesWidget::associatedUndo(), ExportDialog::generateDxf(), setPen(), toDXF(), and ShapeGraphicsItemPropertiesWidget::updateUi().
polygon
QPolygonF QetShapeItem::polygon read write
Definition at line 1 of file qetshapeitem.h.
Referenced by insertPoint(), DiagramEventAddShape::mouseDoubleClickEvent(), removePoint(), and setPolygon().
rect
QRectF QetShapeItem::rect read write
Definition at line 1 of file qetshapeitem.h.
Referenced by DiagramEventAddShape::mousePressEvent(), setRect(), and toXml().
xRadius
qreal QetShapeItem::xRadius read write
Definition at line 1 of file qetshapeitem.h.
yRadius
qreal QetShapeItem::yRadius read write
Definition at line 1 of file qetshapeitem.h.
The documentation for this class was generated from the following files:
qetshapeitem.h
qetshapeitem.cpp