QElectroTech: ExportElementTextPattern Class Reference
ExportElementTextPattern Class Reference
#include <elementtextpattern.h>
Public Member Functions
ExportElementTextPattern (Element *elmt)
ExportElementTextPattern::ExportElementTextPattern Constructor.
Private Member Functions
QString getName (bool &ok) const
ExportElementTextConf::getName Open a dialog to let user set the name of the conf and return it.
QWidget * parentWidget () const
QDomDocument xmlConf () const
Private Attributes
Element * m_element = nullptr
QString m_name
Detailed Description
Definition at line 27 of file elementtextpattern.h.
Constructor & Destructor Documentation
ExportElementTextPattern()
ExportElementTextPattern::ExportElementTextPattern (Element * elmt)
ExportElementTextPattern::ExportElementTextPattern Constructor.
Parameters
elmt
Definition at line 42 of file elementtextpattern.cpp.
References QETApp::configDir(), getName(), m_name, parentWidget(), QET::QetMessageBox::question(), QET::Icons::tr, QET::writeXmlFile(), and xmlConf().
Member Function Documentation
getName()
QString ExportElementTextPattern::getName (bool & ok) const private
ExportElementTextConf::getName Open a dialog to let user set the name of the conf and return it.
Returns
Definition at line 81 of file elementtextpattern.cpp.
References parentWidget(), and QET::Icons::tr.
Referenced by ExportElementTextPattern().
parentWidget()
QWidget * ExportElementTextPattern::parentWidget () const private
Definition at line 95 of file elementtextpattern.cpp.
References m_element.
Referenced by ExportElementTextPattern(), and getName().
xmlConf()
QDomDocument ExportElementTextPattern::xmlConf () const private
Definition at line 104 of file elementtextpattern.cpp.
References m_element, m_name, and Element::toXml().
Referenced by ExportElementTextPattern().
Member Data Documentation
m_element
Element* ExportElementTextPattern::m_element = nullptr private
Definition at line 38 of file elementtextpattern.h.
Referenced by parentWidget(), and xmlConf().
m_name
QString ExportElementTextPattern::m_name private
Definition at line 39 of file elementtextpattern.h.
Referenced by ExportElementTextPattern(), and xmlConf().
The documentation for this class was generated from the following files:
elementtextpattern.h
elementtextpattern.cpp