QElectroTech: ConfigDialog Class Reference
ConfigDialog Class Reference
#include <configdialog.h>
Public Slots
void applyConf ()
void addPage (ConfigPage *)
void setCurrentPage (const int index)
ConfigDialog::setCurrentPage Set the current index to index.
Public Member Functions
ConfigDialog (QWidget *=nullptr)
~ConfigDialog () override
Destructeur.
Public Attributes
QList< ConfigPage * > pages
Private Member Functions
ConfigDialog (const ConfigDialog &)
void buildPagesList ()
void addPageToList (ConfigPage *)
Private Attributes
QListWidget * pages_list
QStackedWidget * pages_widget
QDialogButtonBox * buttons
Detailed Description
This class represents the configuration dialog for QElectroTech. It displays "configuration pages", each page having to provide an icon and a title.
Definition at line 31 of file configdialog.h.
Constructor & Destructor Documentation
ConfigDialog() [1/2]
ConfigDialog::ConfigDialog (QWidget * parent = nullptr)
Constructeur
Parameters
parent QWidget parent
Definition at line 29 of file configdialog.cpp.
References applyConf(), buttons, QET::Icons::Cancel, Machine_info::i_max_screen_height(), Machine_info::i_max_screen_width(), pages_list, and pages_widget.
~ConfigDialog()
ConfigDialog::~ConfigDialog () override
Destructeur.
Definition at line 95 of file configdialog.cpp.
ConfigDialog() [2/2]
ConfigDialog::ConfigDialog (const ConfigDialog &) private
Member Function Documentation
addPage
void ConfigDialog::addPage (ConfigPage * page) slot
Ajoute une page au dialogue de configuration
Definition at line 132 of file configdialog.cpp.
References addPageToList(), pages, and pages_widget.
Referenced by QETApp::configureQET().
addPageToList()
void ConfigDialog::addPageToList (ConfigPage * page) private
Add the page ConfigPage to this configuration dialog.
Definition at line 111 of file configdialog.cpp.
References pages_list.
Referenced by addPage(), and buildPagesList().
applyConf
void ConfigDialog::applyConf () slot
Applique la configuration de toutes les pages
Definition at line 122 of file configdialog.cpp.
References pages.
Referenced by ConfigDialog().
buildPagesList()
void ConfigDialog::buildPagesList () private
Construit la liste des pages sur la gauche
Definition at line 101 of file configdialog.cpp.
References addPageToList(), pages, and pages_list.
setCurrentPage
void ConfigDialog::setCurrentPage (const int index) slot
ConfigDialog::setCurrentPage Set the current index to index.
Parameters
index
Definition at line 144 of file configdialog.cpp.
References pages_list.
Member Data Documentation
buttons
QDialogButtonBox* ConfigDialog::buttons private
Definition at line 58 of file configdialog.h.
Referenced by ConfigDialog().
pages
QList<ConfigPage *> ConfigDialog::pages
Definition at line 41 of file configdialog.h.
Referenced by addPage(), applyConf(), buildPagesList(), and ProjectPropertiesDialog::changeToFolio().
pages_list
QListWidget* ConfigDialog::pages_list private
Definition at line 56 of file configdialog.h.
Referenced by addPageToList(), buildPagesList(), ConfigDialog(), and setCurrentPage().
pages_widget
QStackedWidget* ConfigDialog::pages_widget private
Definition at line 57 of file configdialog.h.
Referenced by addPage(), and ConfigDialog().
The documentation for this class was generated from the following files:
configdialog.h
configdialog.cpp