QElectroTech: ReplaceElementDialog Class Reference
ReplaceElementDialog Class Reference
#include <replaceelementdialog.h>
Public Member Functions
ReplaceElementDialog (DiagramContext context, QWidget *parent=nullptr)
~ReplaceElementDialog ()
void setContext (DiagramContext context)
ReplaceElementDialog::setContext Set the current diagram context to be edited.
DiagramContext context () const
ReplaceElementDialog::context.
Private Member Functions
void buildWidget ()
Private Attributes
Ui::ReplaceElementDialog * ui
QList< ElementInfoPartWidget * > m_eipw_list
DiagramContext m_context
Detailed Description
Definition at line 30 of file replaceelementdialog.h.
Constructor & Destructor Documentation
ReplaceElementDialog()
ReplaceElementDialog::ReplaceElementDialog (DiagramContext context, QWidget * parent = nullptr) explicit
Definition at line 27 of file replaceelementdialog.cpp.
References buildWidget(), context(), setContext(), and ui.
~ReplaceElementDialog()
ReplaceElementDialog::~ReplaceElementDialog ()
Definition at line 36 of file replaceelementdialog.cpp.
References ui.
Member Function Documentation
buildWidget()
void ReplaceElementDialog::buildWidget () private
Definition at line 69 of file replaceelementdialog.cpp.
References QETApp::elementInfoKeys(), QETApp::elementTranslatedInfoKey(), m_eipw_list, ElementInfoPartWidget::setEraseTextVisible(), ElementInfoPartWidget::setPlaceHolderText(), QET::Icons::tr, and ui.
Referenced by ReplaceElementDialog().
context()
DiagramContext ReplaceElementDialog::context () const
ReplaceElementDialog::context.
Returns
The edited diagram context
Definition at line 59 of file replaceelementdialog.cpp.
References DiagramContext::addValue(), and m_eipw_list.
Referenced by SearchAndReplaceWidget::on_m_element_pb_clicked(), ReplaceElementDialog(), and setContext().
setContext()
void ReplaceElementDialog::setContext (DiagramContext context)
ReplaceElementDialog::setContext Set the current diagram context to be edited.
Parameters
context
Definition at line 46 of file replaceelementdialog.cpp.
References context(), m_context, and m_eipw_list.
Referenced by ReplaceElementDialog().
Member Data Documentation
m_context
DiagramContext ReplaceElementDialog::m_context private
Definition at line 47 of file replaceelementdialog.h.
Referenced by setContext().
m_eipw_list
QList<ElementInfoPartWidget *> ReplaceElementDialog::m_eipw_list private
Definition at line 46 of file replaceelementdialog.h.
Referenced by buildWidget(), context(), and setContext().
ui
Ui::ReplaceElementDialog* ReplaceElementDialog::ui private
Definition at line 45 of file replaceelementdialog.h.
Referenced by buildWidget(), ReplaceElementDialog(), and ~ReplaceElementDialog().
The documentation for this class was generated from the following files:
replaceelementdialog.h
replaceelementdialog.cpp