QElectroTech: IndiTextPropertiesWidget Class Reference
IndiTextPropertiesWidget Class Reference
The IndiTextPropertiesWidget class This widget is used to edit the properties of one or several independent text item.
#include <inditextpropertieswidget.h>
Public Member Functions
IndiTextPropertiesWidget (IndependentTextItem *text=nullptr, QWidget *parent=nullptr)
IndiTextPropertiesWidget::IndiTextPropertiesWidget.
IndiTextPropertiesWidget (QList< IndependentTextItem * > text_list, QWidget *parent=nullptr)
IndiTextPropertiesWidget::IndiTextPropertiesWidget.
~IndiTextPropertiesWidget () override
IndiTextPropertiesWidget::~IndiTextPropertiesWidget.
void setText (IndependentTextItem *text)
IndiTextPropertiesWidget::setText.
void setText (QList< IndependentTextItem * > text_list)
void apply () override
IndiTextPropertiesWidget::apply Apply the current edition through a QUndoCommand pushed to the undo stack of text's diagram.
bool setLiveEdit (bool live_edit) override
IndiTextPropertiesWidget::setLiveEdit.
QUndoCommand * associatedUndo () const override
IndiTextPropertiesWidget::associatedUndo.
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual void reset ()
virtual QString title () const
PropertiesEditorWidget::title.
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Private Slots
void on_m_advanced_editor_pb_clicked ()
IndiTextPropertiesWidget::on_m_advanced_editor_pb_clicked.
void on_m_break_html_pb_clicked ()
void on_m_font_pb_clicked ()
Private Member Functions
void setUpEditConnection ()
IndiTextPropertiesWidget::setUpEditConnection Disconnect the previous connection, and reconnect the connection between the editors widgets and void IndiTextPropertiesWidget::apply function.
void updateUi () override
IndiTextPropertiesWidget::updateUi.
Private Attributes
Ui::IndiTextPropertiesWidget * ui
QPointer< IndependentTextItem > m_text
QList< QPointer< IndependentTextItem > > m_text_list
QList< QMetaObject::Connection > m_connect_list
QList< QMetaObject::Connection > m_edit_connection
QFont m_selected_font
bool m_font_is_selected = false
Additional Inherited Members
Protected Member Functions inherited from PropertiesEditorWidget
virtual void enableLiveEdit ()
virtual void disableLiveEdit ()
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
The IndiTextPropertiesWidget class This widget is used to edit the properties of one or several independent text item.
Definition at line 33 of file inditextpropertieswidget.h.
Constructor & Destructor Documentation
IndiTextPropertiesWidget() [1/2]
IndiTextPropertiesWidget::IndiTextPropertiesWidget (IndependentTextItem * text = nullptr, QWidget * parent = nullptr)
IndiTextPropertiesWidget::IndiTextPropertiesWidget.
Parameters
text : the text to edit
parent : the parent widget of this widget
Definition at line 32 of file inditextpropertieswidget.cpp.
References setText(), and ui.
IndiTextPropertiesWidget() [2/2]
IndiTextPropertiesWidget::IndiTextPropertiesWidget (QList< IndependentTextItem * > text_list, QWidget * parent = nullptr)
IndiTextPropertiesWidget::IndiTextPropertiesWidget.
Parameters
text_list : a list of texts to edit
parent : the parent widget of this widget
Definition at line 47 of file inditextpropertieswidget.cpp.
References setText(), and ui.
~IndiTextPropertiesWidget()
IndiTextPropertiesWidget::~IndiTextPropertiesWidget () override
IndiTextPropertiesWidget::~IndiTextPropertiesWidget.
Definition at line 60 of file inditextpropertieswidget.cpp.
References ui.
Member Function Documentation
apply()
void IndiTextPropertiesWidget::apply () override virtual
IndiTextPropertiesWidget::apply Apply the current edition through a QUndoCommand pushed to the undo stack of text's diagram.
Reimplemented from PropertiesEditorWidget.
Definition at line 118 of file inditextpropertieswidget.cpp.
References associatedUndo(), m_text, m_text_list, and Diagram::undoStack().
Referenced by on_m_font_pb_clicked(), and setUpEditConnection().
associatedUndo()
QUndoCommand * IndiTextPropertiesWidget::associatedUndo () const override virtual
IndiTextPropertiesWidget::associatedUndo.
Returns
Reimplemented from PropertiesEditorWidget.
Definition at line 170 of file inditextpropertieswidget.cpp.
References m_font_is_selected, PropertiesEditorWidget::m_live_edit, m_selected_font, m_text, m_text_list, QPropertyUndoCommand::setAnimated(), QET::Icons::tr, and ui.
Referenced by apply().
on_m_advanced_editor_pb_clicked
void IndiTextPropertiesWidget::on_m_advanced_editor_pb_clicked () private slot
IndiTextPropertiesWidget::on_m_advanced_editor_pb_clicked.
Definition at line 424 of file inditextpropertieswidget.cpp.
References m_text.
on_m_break_html_pb_clicked
void IndiTextPropertiesWidget::on_m_break_html_pb_clicked () private slot
Definition at line 430 of file inditextpropertieswidget.cpp.
References m_text, m_text_list, and updateUi().
on_m_font_pb_clicked
void IndiTextPropertiesWidget::on_m_font_pb_clicked () private slot
Definition at line 442 of file inditextpropertieswidget.cpp.
References apply(), m_font_is_selected, m_selected_font, m_text, m_text_list, QET::Icons::tr, and ui.
setLiveEdit()
bool IndiTextPropertiesWidget::setLiveEdit (bool live_edit) override virtual
IndiTextPropertiesWidget::setLiveEdit.
Parameters
live_edit
Returns
Reimplemented from PropertiesEditorWidget.
Definition at line 147 of file inditextpropertieswidget.cpp.
References m_edit_connection, PropertiesEditorWidget::m_live_edit, and setUpEditConnection().
setText() [1/2]
void IndiTextPropertiesWidget::setText (IndependentTextItem * text)
IndiTextPropertiesWidget::setText.
Parameters
text : set text as edited text
Definition at line 68 of file inditextpropertieswidget.cpp.
References DiagramTextItem::fontChanged(), m_connect_list, m_text, DiagramTextItem::textEdited(), and updateUi().
Referenced by IndiTextPropertiesWidget(), and setText().
setText() [2/2]
void IndiTextPropertiesWidget::setText (QList< IndependentTextItem * > text_list)
Definition at line 87 of file inditextpropertieswidget.cpp.
References m_connect_list, m_text, m_text_list, setText(), and updateUi().
setUpEditConnection()
void IndiTextPropertiesWidget::setUpEditConnection () private
IndiTextPropertiesWidget::setUpEditConnection Disconnect the previous connection, and reconnect the connection between the editors widgets and void IndiTextPropertiesWidget::apply function.
Definition at line 322 of file inditextpropertieswidget.cpp.
References apply(), m_edit_connection, m_text_list, and ui.
Referenced by setLiveEdit(), and updateUi().
updateUi()
void IndiTextPropertiesWidget::updateUi () override private virtual
IndiTextPropertiesWidget::updateUi.
Reimplemented from PropertiesEditorWidget.
Definition at line 346 of file inditextpropertieswidget.cpp.
References m_edit_connection, m_text, m_text_list, setUpEditConnection(), QET::Icons::tr, and ui.
Referenced by on_m_break_html_pb_clicked(), and setText().
Member Data Documentation
m_connect_list
QList<QMetaObject::Connection> IndiTextPropertiesWidget::m_connect_list private
Definition at line 61 of file inditextpropertieswidget.h.
Referenced by setText().
m_edit_connection
QList<QMetaObject::Connection> IndiTextPropertiesWidget::m_edit_connection private
Definition at line 62 of file inditextpropertieswidget.h.
Referenced by setLiveEdit(), setUpEditConnection(), and updateUi().
m_font_is_selected
bool IndiTextPropertiesWidget::m_font_is_selected = false private
Definition at line 64 of file inditextpropertieswidget.h.
Referenced by associatedUndo(), and on_m_font_pb_clicked().
m_selected_font
QFont IndiTextPropertiesWidget::m_selected_font private
Definition at line 63 of file inditextpropertieswidget.h.
Referenced by associatedUndo(), and on_m_font_pb_clicked().
m_text
QPointer<IndependentTextItem> IndiTextPropertiesWidget::m_text private
Definition at line 59 of file inditextpropertieswidget.h.
Referenced by apply(), associatedUndo(), on_m_advanced_editor_pb_clicked(), on_m_break_html_pb_clicked(), on_m_font_pb_clicked(), setText(), and updateUi().
m_text_list
QList<QPointer<IndependentTextItem> > IndiTextPropertiesWidget::m_text_list private
Definition at line 60 of file inditextpropertieswidget.h.
Referenced by apply(), associatedUndo(), on_m_break_html_pb_clicked(), on_m_font_pb_clicked(), setText(), setUpEditConnection(), and updateUi().
ui
Ui::IndiTextPropertiesWidget* IndiTextPropertiesWidget::ui private
Definition at line 58 of file inditextpropertieswidget.h.
Referenced by associatedUndo(), IndiTextPropertiesWidget(), on_m_font_pb_clicked(), setUpEditConnection(), updateUi(), and ~IndiTextPropertiesWidget().
The documentation for this class was generated from the following files:
inditextpropertieswidget.h
inditextpropertieswidget.cpp