QElectroTech: DiagramPrintDialog Class Reference
DiagramPrintDialog Class Reference
The DiagramPrintDialog class This class implements both the dialog allowing users to configure the printing of a project file and the printing itself.
#include <diagramprintdialog.h>
Public Member Functions
DiagramPrintDialog (QETProject *, QWidget *=nullptr)
~DiagramPrintDialog () override
void setFileName (const QString &)
QString fileName () const
void setDocName (const QString &)
QString docName () const
QRect diagramRect (Diagram *, const ExportProperties &) const
DiagramPrintDialog::diagramRect.
int pagesCount (Diagram *, const ExportProperties &, bool=false) const
int horizontalPagesCount (Diagram *, const ExportProperties &, bool=false) const
int verticalPagesCount (Diagram *, const ExportProperties &, bool=false) const
void exec ()
Private Slots
void print (const QList< Diagram * > &, bool, const ExportProperties &)
void printDiagram (Diagram *, bool, const ExportProperties &, QPainter *, QPrinter *=nullptr)
void updatePrintTypeDialog ()
void acceptPrintTypeDialog ()
void browseFilePrintTypeDialog ()
Private Member Functions
DiagramPrintDialog (const DiagramPrintDialog &)
void buildPrintTypeDialog ()
void buildDialog ()
void saveReloadDiagramParameters (Diagram *, const ExportProperties &, bool)
void savePageSetupForCurrentPrinter ()
void loadPageSetupForCurrentPrinter ()
QString settingsSectionName (const QPrinter *)
Private Attributes
QETProject * project_
QPrinter * printer_
QString doc_name_
QString file_name_
QDialog * dialog_
QLabel * printtype_label_
QGridLayout * glayout0_
QVBoxLayout * vlayout0_
QHBoxLayout * hlayout0_
QLabel * printer_icon_
QLabel * pdf_icon_
QButtonGroup * printtype_choice_
QRadioButton * printer_choice_
QRadioButton * pdf_choice_
QLineEdit * filepath_field_
QPushButton * browse_button_
QDialogButtonBox * buttons_
QColor backup_diagram_background_color
Detailed Description
The DiagramPrintDialog class This class implements both the dialog allowing users to configure the printing of a project file and the printing itself.
Definition at line 33 of file diagramprintdialog.h.
Constructor & Destructor Documentation
DiagramPrintDialog() [1/2]
DiagramPrintDialog::DiagramPrintDialog (QETProject * project, QWidget * parent = nullptr)
Constructeur
Parameters
project Schema a imprimer
parent Widget parent du dialogue
Definition at line 34 of file diagramprintdialog.cpp.
References Diagram::background_color, backup_diagram_background_color, and printer_.
~DiagramPrintDialog()
DiagramPrintDialog::~DiagramPrintDialog () override
Destructeur
Definition at line 51 of file diagramprintdialog.cpp.
References Diagram::background_color, backup_diagram_background_color, dialog_, and printer_.
DiagramPrintDialog() [2/2]
DiagramPrintDialog::DiagramPrintDialog (const DiagramPrintDialog &) private
Member Function Documentation
acceptPrintTypeDialog
void DiagramPrintDialog::acceptPrintTypeDialog () private slot
Verifie l'etat du dialogue permettant le choix du type d'impression lorsque l'utilisateur le valide.
Definition at line 304 of file diagramprintdialog.cpp.
References dialog_, filepath_field_, QET::QetMessageBox::information(), printer_choice_, and QET::Icons::tr.
Referenced by buildPrintTypeDialog().
browseFilePrintTypeDialog
void DiagramPrintDialog::browseFilePrintTypeDialog () private slot
Permet a l'utilisateur de choisir un fichier
Definition at line 325 of file diagramprintdialog.cpp.
References filepath_field_, pdf_choice_, printer_choice_, and QET::Icons::tr.
Referenced by buildPrintTypeDialog().
buildDialog()
void DiagramPrintDialog::buildDialog () private
buildPrintTypeDialog()
void DiagramPrintDialog::buildPrintTypeDialog () private
Construit un dialogue non standard pour demander a l'utilisateur quelle type d'impression il souhaite effectuer : PDF, PS ou imprimante physique
Definition at line 215 of file diagramprintdialog.cpp.
References acceptPrintTypeDialog(), browse_button_, browseFilePrintTypeDialog(), buttons_, QET::Icons::Cancel, dialog_, file_name_, filepath_field_, glayout0_, hlayout0_, QET::Icons::PDF, pdf_choice_, pdf_icon_, QET::Icons::Printer, printer_choice_, printer_icon_, printtype_choice_, printtype_label_, QET::Icons::tr, updatePrintTypeDialog(), and vlayout0_.
Referenced by exec().
diagramRect()
QRect DiagramPrintDialog::diagramRect (Diagram * diagram, const ExportProperties & options) const
DiagramPrintDialog::diagramRect.
Parameters
diagram : Diagram to be printed
options :
Returns
the rectangle to be printed
Definition at line 91 of file diagramprintdialog.cpp.
References ExportProperties::draw_titleblock.
Referenced by horizontalPagesCount(), printDiagram(), and verticalPagesCount().
docName()
QString DiagramPrintDialog::docName () const
Returns
le nom du document
Definition at line 81 of file diagramprintdialog.cpp.
References doc_name_.
exec()
void DiagramPrintDialog::exec ()
Execute le dialogue d'impression
Definition at line 110 of file diagramprintdialog.cpp.
References buildPrintTypeDialog(), QETPrintPreviewDialog::diagramsChooser(), dialog_, QET::displayedVersion, doc_name_, QETPrintPreviewDialog::exportProperties(), filepath_field_, QETPrintPreviewDialog::fitDiagramsToPages(), loadPageSetupForCurrentPrinter(), print(), printer_, printer_choice_, project_, savePageSetupForCurrentPrinter(), setDocName(), and QET::Icons::tr.
Referenced by ProjectView::printProject().
fileName()
QString DiagramPrintDialog::fileName () const
Returns
le nom du PDF
Definition at line 67 of file diagramprintdialog.cpp.
References file_name_.
horizontalPagesCount()
int DiagramPrintDialog::horizontalPagesCount (Diagram * diagram, const ExportProperties & options, bool fullpage = false) const
Parameters
diagram Schema a imprimer
options Rendering options
fullpage true pour utiliser toute la feuille dans le calcul
Returns
La largeur du "poster" en nombre de pages pour imprimer le schema avec l'orientation et le format papier utilise dans l'imprimante en cours.
Definition at line 186 of file diagramprintdialog.cpp.
References diagramRect(), and printer_.
Referenced by pagesCount(), and printDiagram().
loadPageSetupForCurrentPrinter()
void DiagramPrintDialog::loadPageSetupForCurrentPrinter () private
Load parameters previously set in the "page setup" dialog for the current printer, if any.
Definition at line 579 of file diagramprintdialog.cpp.
References QET::Custom, printer_, and settingsSectionName().
Referenced by exec().
pagesCount()
int DiagramPrintDialog::pagesCount (Diagram * diagram, const ExportProperties & options, bool fullpage = false) const
Parameters
diagram Schema a imprimer
options Rendering options
fullpage true pour utiliser toute la feuille dans le calcul
Returns
Le nombre de pages necessaires pour imprimer le schema avec l'orientation et le format papier utilise dans l'imprimante en cours.
Definition at line 175 of file diagramprintdialog.cpp.
References horizontalPagesCount(), and verticalPagesCount().
print
void DiagramPrintDialog::print (const QList< Diagram * > & diagrams, bool fit_page, const ExportProperties & options) private slot
Effectue l'impression elle-meme
Parameters
diagrams Schemas a imprimer
fit_page Booleen indiquant s'il faut adapter les schemas aux pages ou non
options Options de rendu
Definition at line 356 of file diagramprintdialog.cpp.
References printDiagram(), and printer_.
Referenced by exec().
printDiagram
void DiagramPrintDialog::printDiagram (Diagram * diagram, bool fit_page, const ExportProperties & options, QPainter * qp, QPrinter * printer = nullptr) private slot
Imprime un schema
Parameters
diagram Schema a imprimer
fit_page True pour adapter les schemas aux pages, false sinon
options Options de rendu a appliquer pour l'impression
qp QPainter a utiliser (deja initialise sur printer)
printer Imprimante a utiliser
Definition at line 405 of file diagramprintdialog.cpp.
References diagramRect(), horizontalPagesCount(), saveReloadDiagramParameters(), and verticalPagesCount().
Referenced by print().
savePageSetupForCurrentPrinter()
void DiagramPrintDialog::savePageSetupForCurrentPrinter () private
Save parameters set in the "page setup" dialog into the QElectroTech configuration. Key/values pairs are associated to the printer for which they have been set.
Definition at line 543 of file diagramprintdialog.cpp.
References QET::Custom, printer_, and settingsSectionName().
Referenced by exec().
saveReloadDiagramParameters()
void DiagramPrintDialog::saveReloadDiagramParameters (Diagram * diagram, const ExportProperties & options, bool save) private
Sauve ou restaure les parametres du schema
Parameters
diagram Schema dont on sauve ou restaure les parametres
options Parametres a appliquer
save true pour memoriser les parametres du schema et appliquer ceux definis dans options, false pour restaurer les parametres
Definition at line 526 of file diagramprintdialog.cpp.
Referenced by printDiagram().
setDocName()
void DiagramPrintDialog::setDocName (const QString & name)
Definit le nom du document
Definition at line 74 of file diagramprintdialog.cpp.
References doc_name_.
Referenced by exec(), and ProjectView::printProject().
setFileName()
void DiagramPrintDialog::setFileName (const QString & name)
Definit le nom du PDF si l'utilisateur choisit une sortie vers un PDF
Definition at line 60 of file diagramprintdialog.cpp.
References file_name_.
Referenced by ProjectView::printProject().
settingsSectionName()
QString DiagramPrintDialog::settingsSectionName (const QPrinter * printer) private
Returns
a section name for use with QSettings in order to store parameters related to printer.
Definition at line 629 of file diagramprintdialog.cpp.
Referenced by loadPageSetupForCurrentPrinter(), and savePageSetupForCurrentPrinter().
updatePrintTypeDialog
void DiagramPrintDialog::updatePrintTypeDialog () private slot
Assure la coherence du dialogue permettant le choix du type d'impression
Definition at line 276 of file diagramprintdialog.cpp.
References browse_button_, filepath_field_, pdf_choice_, and printer_choice_.
Referenced by buildPrintTypeDialog().
verticalPagesCount()
int DiagramPrintDialog::verticalPagesCount (Diagram * diagram, const ExportProperties & options, bool fullpage = false) const
Parameters
diagram Schema a imprimer
options Rendering options
fullpage true pour utiliser toute la feuille dans le calcul
Returns
La largeur du "poster" en nombre de pages pour imprimer le schema avec l'orientation et le format papier utilise dans l'imprimante en cours.
Definition at line 202 of file diagramprintdialog.cpp.
References diagramRect(), and printer_.
Referenced by pagesCount(), and printDiagram().
Member Data Documentation
backup_diagram_background_color
QColor DiagramPrintDialog::backup_diagram_background_color private
Definition at line 104 of file diagramprintdialog.h.
Referenced by DiagramPrintDialog(), and ~DiagramPrintDialog().
browse_button_
QPushButton* DiagramPrintDialog::browse_button_ private
Definition at line 102 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog(), and updatePrintTypeDialog().
buttons_
QDialogButtonBox* DiagramPrintDialog::buttons_ private
Definition at line 103 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog().
dialog_
QDialog* DiagramPrintDialog::dialog_ private
Definition at line 91 of file diagramprintdialog.h.
Referenced by acceptPrintTypeDialog(), buildPrintTypeDialog(), exec(), and ~DiagramPrintDialog().
doc_name_
QString DiagramPrintDialog::doc_name_ private
Definition at line 88 of file diagramprintdialog.h.
Referenced by docName(), exec(), and setDocName().
file_name_
QString DiagramPrintDialog::file_name_ private
Definition at line 89 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog(), fileName(), and setFileName().
filepath_field_
QLineEdit* DiagramPrintDialog::filepath_field_ private
Definition at line 101 of file diagramprintdialog.h.
Referenced by acceptPrintTypeDialog(), browseFilePrintTypeDialog(), buildPrintTypeDialog(), exec(), and updatePrintTypeDialog().
glayout0_
QGridLayout* DiagramPrintDialog::glayout0_ private
Definition at line 93 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog().
hlayout0_
QHBoxLayout* DiagramPrintDialog::hlayout0_ private
Definition at line 95 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog().
pdf_choice_
QRadioButton* DiagramPrintDialog::pdf_choice_ private
Definition at line 100 of file diagramprintdialog.h.
Referenced by browseFilePrintTypeDialog(), buildPrintTypeDialog(), and updatePrintTypeDialog().
pdf_icon_
QLabel* DiagramPrintDialog::pdf_icon_ private
Definition at line 97 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog().
printer_
QPrinter* DiagramPrintDialog::printer_ private
Definition at line 87 of file diagramprintdialog.h.
Referenced by DiagramPrintDialog(), exec(), horizontalPagesCount(), loadPageSetupForCurrentPrinter(), print(), savePageSetupForCurrentPrinter(), verticalPagesCount(), and ~DiagramPrintDialog().
printer_choice_
QRadioButton* DiagramPrintDialog::printer_choice_ private
Definition at line 99 of file diagramprintdialog.h.
Referenced by acceptPrintTypeDialog(), browseFilePrintTypeDialog(), buildPrintTypeDialog(), exec(), and updatePrintTypeDialog().
printer_icon_
QLabel* DiagramPrintDialog::printer_icon_ private
Definition at line 96 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog().
printtype_choice_
QButtonGroup* DiagramPrintDialog::printtype_choice_ private
Definition at line 98 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog().
printtype_label_
QLabel* DiagramPrintDialog::printtype_label_ private
Definition at line 92 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog().
project_
QETProject* DiagramPrintDialog::project_ private
Definition at line 86 of file diagramprintdialog.h.
Referenced by exec().
vlayout0_
QVBoxLayout* DiagramPrintDialog::vlayout0_ private
Definition at line 94 of file diagramprintdialog.h.
Referenced by buildPrintTypeDialog().
The documentation for this class was generated from the following files:
diagramprintdialog.h
diagramprintdialog.cpp