QElectroTech: ProjectDBModel Class Reference
ProjectDBModel Class Reference
The ProjectDBModel class This model is intended to be use with the class projectDataBase and is designed to be displayed by the class QetGraphicsTableItem (but can be use by other view class since it inherit from QAbstractTableModel). This class should be sufficient to display the content of the project data base from a query set by the method void ProjectDBModel::setQuery(const QString &query). The indentifier method is used by widget editor to retrieve the good widget for edit the query. By defaut identifer return the string 'unknow'. You should use setIdentfier method to set your custom identifier. At the time this sentence is written, there is two identifier : nomenclature summary.
#include <projectdbmodel.h>
Public Member Functions
ProjectDBModel (QETProject *project, QObject *parent=nullptr)
ProjectDBModel::ProjectDBModel.
ProjectDBModel (const ProjectDBModel &other_model)
ProjectDBModel::ProjectDBModel.
int rowCount (const QModelIndex &parent=QModelIndex()) const override
ProjectDBModel::rowCount Reimplemented for QAbstractTableModel.
int columnCount (const QModelIndex &parent=QModelIndex()) const override
ProjectDBModel::columnCount Reimplemented for QAbstractTableModel.
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole) override
ProjectDBModel::setHeaderData Reimplemented from QAbstractTableModel. Only horizontal orientation is accepted.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
ProjectDBModel::headerData Reimplemented from QAbstractTableModel.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
ProjectDBModel::setData Only store the data for the index 0.0.
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
ProjectDBModel::data Reimplemented for QAbstractTableModel.
void setQuery (const QString &setQuery)
ProjectDBModel::setQuery Query the internall bd with query.
QString queryString () const
ProjectDBModel::queryString.
QETProject * project () const
QDomElement toXml (QDomDocument &document) const
ProjectDBModel::toXml Save the model to xml,since model can have unlimited data we only save few data (only these used by qelectrotech). The query, all header data. and some data of index::(0,0). All other data are not saved.
void fromXml (const QDomElement &element)
ProjectDBModel::fromXml Restore the model from xml.
void setIdentifier (const QString &identifier)
ProjectDBModel::setIdentifier Set the identifier of this model to identifier.
QString identifier () const
Static Public Member Functions
static QString xmlTagName ()
Private Member Functions
void dataBaseUpdated ()
ProjectDBModel::dataBaseUpdated slot called when the project database is updated.
void setHeaderString ()
void fillValue ()
Private Attributes
QPointer< QETProject > m_project
QString m_query
QVector< QStringList > m_record
QHash< int, QHash< int, QVariant > > m_header_data
QHash< int, QVariant > m_index_0_0_data
QString m_identifier = "unknow"
Detailed Description
The ProjectDBModel class This model is intended to be use with the class projectDataBase and is designed to be displayed by the class QetGraphicsTableItem (but can be use by other view class since it inherit from QAbstractTableModel). This class should be sufficient to display the content of the project data base from a query set by the method void ProjectDBModel::setQuery(const QString &query). The indentifier method is used by widget editor to retrieve the good widget for edit the query. By defaut identifer return the string 'unknow'. You should use setIdentfier method to set your custom identifier. At the time this sentence is written, there is two identifier : nomenclature summary.
Definition at line 43 of file projectdbmodel.h.
Constructor & Destructor Documentation
ProjectDBModel() [1/2]
ProjectDBModel::ProjectDBModel (QETProject * project, QObject * parent = nullptr) explicit
ProjectDBModel::ProjectDBModel.
Parameters
project :project of this nomenclature
parent : parent QObject
Definition at line 32 of file projectdbmodel.cpp.
References projectDataBase::dataBaseUpdated(), dataBaseUpdated(), and m_project.
ProjectDBModel() [2/2]
ProjectDBModel::ProjectDBModel (const ProjectDBModel & other_model) explicit
ProjectDBModel::ProjectDBModel.
Parameters
other_model
Definition at line 43 of file projectdbmodel.cpp.
References projectDataBase::dataBaseUpdated(), dataBaseUpdated(), m_index_0_0_data, m_project, queryString(), and setQuery().
Member Function Documentation
columnCount()
int ProjectDBModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
ProjectDBModel::columnCount Reimplemented for QAbstractTableModel.
Parameters
parent
Returns
Definition at line 73 of file projectdbmodel.cpp.
References m_record.
data()
QVariant ProjectDBModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
ProjectDBModel::data Reimplemented for QAbstractTableModel.
Parameters
index
role
Returns
Definition at line 157 of file projectdbmodel.cpp.
References m_index_0_0_data, and m_record.
dataBaseUpdated()
void ProjectDBModel::dataBaseUpdated () private
ProjectDBModel::dataBaseUpdated slot called when the project database is updated.
Definition at line 311 of file projectdbmodel.cpp.
References fillValue(), and m_record.
Referenced by ProjectDBModel(), and setQuery().
fillValue()
void ProjectDBModel::fillValue () private
Definition at line 361 of file projectdbmodel.cpp.
References m_project, m_query, and m_record.
Referenced by dataBaseUpdated(), and setQuery().
fromXml()
void ProjectDBModel::fromXml (const QDomElement & element)
ProjectDBModel::fromXml Restore the model from xml.
Parameters
element
Definition at line 278 of file projectdbmodel.cpp.
References m_index_0_0_data, QETXML::modelHeaderDataFromXml(), setIdentifier(), setQuery(), and xmlTagName().
headerData()
QVariant ProjectDBModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
ProjectDBModel::headerData Reimplemented from QAbstractTableModel.
Parameters
section
orientation
role
Returns
Definition at line 115 of file projectdbmodel.cpp.
References m_header_data, and QET::Vertical.
identifier()
QString ProjectDBModel::identifier () const inline
Definition at line 72 of file projectdbmodel.h.
References m_identifier.
Referenced by ProjectDBModelPropertiesWidget::on_m_edit_query_pb_clicked(), and setIdentifier().
project()
QETProject * ProjectDBModel::project () const
Definition at line 222 of file projectdbmodel.cpp.
References m_project.
Referenced by ProjectDBModelPropertiesWidget::on_m_refresh_pb_clicked().
queryString()
QString ProjectDBModel::queryString () const
ProjectDBModel::queryString.
Returns
the current query used by this model
Definition at line 218 of file projectdbmodel.cpp.
References m_query.
Referenced by ProjectDBModelPropertiesWidget::on_m_edit_query_pb_clicked(), and ProjectDBModel().
rowCount()
int ProjectDBModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
ProjectDBModel::rowCount Reimplemented for QAbstractTableModel.
Parameters
parent
Returns
Definition at line 59 of file projectdbmodel.cpp.
References m_record.
setData()
bool ProjectDBModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
ProjectDBModel::setData Only store the data for the index 0.0.
Parameters
index
value
role
Returns
Definition at line 140 of file projectdbmodel.cpp.
References m_index_0_0_data.
setHeaderData()
bool ProjectDBModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) override
ProjectDBModel::setHeaderData Reimplemented from QAbstractTableModel. Only horizontal orientation is accepted.
Parameters
section
orientation
value
role
Returns
Definition at line 95 of file projectdbmodel.cpp.
References m_header_data, and QET::Vertical.
Referenced by setHeaderString().
setHeaderString()
void ProjectDBModel::setHeaderString () private
Definition at line 334 of file projectdbmodel.cpp.
References QETApp::diagramTranslatedInfoKey(), QETApp::elementTranslatedInfoKey(), QET::Horizontal, m_project, m_query, setHeaderData(), and QET::Icons::tr.
Referenced by setQuery().
setIdentifier()
void ProjectDBModel::setIdentifier (const QString & identifier)
ProjectDBModel::setIdentifier Set the identifier of this model to identifier.
Parameters
identifier
Definition at line 303 of file projectdbmodel.cpp.
References identifier(), and m_identifier.
Referenced by fromXml().
setQuery()
void ProjectDBModel::setQuery (const QString & query)
ProjectDBModel::setQuery Query the internall bd with query.
Parameters
query
Definition at line 181 of file projectdbmodel.cpp.
References projectDataBase::dataBaseUpdated(), dataBaseUpdated(), fillValue(), m_project, m_query, and setHeaderString().
Referenced by fromXml(), ProjectDBModelPropertiesWidget::on_m_edit_query_pb_clicked(), and ProjectDBModel().
toXml()
QDomElement ProjectDBModel::toXml (QDomDocument & document) const
ProjectDBModel::toXml Save the model to xml,since model can have unlimited data we only save few data (only these used by qelectrotech). The query, all header data. and some data of index::(0,0). All other data are not saved.
Parameters
document
Returns
Definition at line 233 of file projectdbmodel.cpp.
References m_header_data, m_identifier, m_index_0_0_data, m_query, QETXML::modelHeaderDataToXml(), and xmlTagName().
xmlTagName()
static QString ProjectDBModel::xmlTagName () inline static
Definition at line 73 of file projectdbmodel.h.
Referenced by fromXml(), QetGraphicsTableItem::fromXml(), and toXml().
Member Data Documentation
m_header_data
QHash<int, QHash<int, QVariant> > ProjectDBModel::m_header_data private
Definition at line 85 of file projectdbmodel.h.
Referenced by headerData(), setHeaderData(), and toXml().
m_identifier
QString ProjectDBModel::m_identifier = "unknow" private
Definition at line 87 of file projectdbmodel.h.
Referenced by identifier(), setIdentifier(), and toXml().
m_index_0_0_data
QHash<int, QVariant> ProjectDBModel::m_index_0_0_data private
Definition at line 86 of file projectdbmodel.h.
Referenced by data(), fromXml(), ProjectDBModel(), setData(), and toXml().
m_project
QPointer<QETProject> ProjectDBModel::m_project private
Definition at line 81 of file projectdbmodel.h.
Referenced by fillValue(), project(), ProjectDBModel(), setHeaderString(), and setQuery().
m_query
QString ProjectDBModel::m_query private
Definition at line 82 of file projectdbmodel.h.
Referenced by fillValue(), queryString(), setHeaderString(), setQuery(), and toXml().
m_record
QVector<QStringList> ProjectDBModel::m_record private
Definition at line 83 of file projectdbmodel.h.
Referenced by columnCount(), data(), dataBaseUpdated(), fillValue(), and rowCount().
The documentation for this class was generated from the following files:
projectdbmodel.h
projectdbmodel.cpp