QElectroTech: TitleBlockTemplatesCollection Class Reference
TitleBlockTemplatesCollection Class Reference abstract
#include <templatescollection.h>
Signals
void changed (TitleBlockTemplatesCollection *, const QString &=QString())
void aboutToRemove (TitleBlockTemplatesCollection *, const QString &)
Public Member Functions
TitleBlockTemplatesCollection (QObject *parent)
~TitleBlockTemplatesCollection () override
virtual QStringList templates ()=0
virtual TitleBlockTemplate * getTemplate (const QString &)=0
virtual QDomElement getTemplateXmlDescription (const QString &)=0
virtual bool setTemplateXmlDescription (const QString &, const QDomElement &)=0
virtual void removeTemplate (const QString &)=0
virtual TitleBlockTemplateLocation location (const QString &=QString())=0
virtual bool hasFilePath ()=0
virtual QString filePath ()=0
virtual bool isReadOnly (const QString &=QString()) const =0
virtual QString title () const
virtual void setTitle (const QString &)
TitleBlockTemplatesCollection::setTitle.
virtual QString protocol () const
virtual void setProtocol (const QString &)
virtual QET::QetCollection collection () const
TitleBlockTemplatesCollection::collection.
virtual void setCollection (QET::QetCollection)
TitleBlockTemplatesCollection::setCollection Set the storage of this collection.
virtual QETProject * parentProject ()
virtual QList< TitleBlockTemplateLocation > templatesLocations ()
Protected Attributes
QString title_
Human-readable title for this collection.
QString protocol_
Protocol used to designate this collection.
QET::QetCollection m_collection
QHash< QString, TitleBlockTemplate * > titleblock_templates_
Already parsed embedded titleblock templates.
Private Member Functions
TitleBlockTemplatesCollection (const TitleBlockTemplatesCollection &)
Detailed Description
This abstract class represents a generic collection of title block templates. Unlike elements collections, title block templates collections do not provide a tree structure. Instead, they provide a simple, flat list of available templates.
Definition at line 34 of file templatescollection.h.
Constructor & Destructor Documentation
TitleBlockTemplatesCollection() [1/2]
TitleBlockTemplatesCollection::TitleBlockTemplatesCollection (QObject * parent)
Constructor
Parameters
parent Parent QObject
Definition at line 27 of file templatescollection.cpp.
~TitleBlockTemplatesCollection()
TitleBlockTemplatesCollection::~TitleBlockTemplatesCollection () override
Destructor
Definition at line 36 of file templatescollection.cpp.
TitleBlockTemplatesCollection() [2/2]
TitleBlockTemplatesCollection::TitleBlockTemplatesCollection (const TitleBlockTemplatesCollection &) private
Member Function Documentation
aboutToRemove
void TitleBlockTemplatesCollection::aboutToRemove (TitleBlockTemplatesCollection * , const QString &) signal
Referenced by QETProject::init(), TitleBlockTemplatesProjectCollection::removeTemplate(), and TitleBlockTemplatesFilesCollection::removeTemplate().
changed
void TitleBlockTemplatesCollection::changed (TitleBlockTemplatesCollection * , const QString & = QString()) signal
Referenced by TitleBlockTemplatesFilesCollection::fileSystemChanged(), GenericPanel::fillTemplatesCollectionItem(), QETProject::init(), TitleBlockTemplatesProjectCollection::removeTemplate(), TitleBlockTemplatesFilesCollection::removeTemplate(), TitleBlockTemplatesProjectCollection::setTemplateXmlDescription(), and TitleBlockTemplatesFilesCollection::setTemplateXmlDescription().
collection()
QET::QetCollection TitleBlockTemplatesCollection::collection () const virtual
TitleBlockTemplatesCollection::collection.
Returns
the collection where is stored this collection.
Definition at line 74 of file templatescollection.cpp.
References m_collection.
filePath()
virtual QString TitleBlockTemplatesCollection::filePath () pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
getTemplate()
virtual TitleBlockTemplate* TitleBlockTemplatesCollection::getTemplate (const QString &) pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
getTemplateXmlDescription()
virtual QDomElement TitleBlockTemplatesCollection::getTemplateXmlDescription (const QString &) pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
hasFilePath()
virtual bool TitleBlockTemplatesCollection::hasFilePath () pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
isReadOnly()
virtual bool TitleBlockTemplatesCollection::isReadOnly (const QString & = QString()) const pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
location()
virtual TitleBlockTemplateLocation TitleBlockTemplatesCollection::location (const QString & = QString()) pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
Referenced by TitleBlockPropertiesWidget::currentTitleBlockLocation(), templatesLocations(), and GenericPanel::updateTemplatesCollectionItem().
parentProject()
QETProject * TitleBlockTemplatesCollection::parentProject () virtual
Returns
the project this collection is affiliated to, or 0 if this collection is not related to any project.
Reimplemented in TitleBlockTemplatesProjectCollection.
Definition at line 91 of file templatescollection.cpp.
protocol()
QString TitleBlockTemplatesCollection::protocol () const virtual
Returns
the protocol used by this collection ; examples: commontbt, customtbt, embedtbt, ...
Reimplemented in TitleBlockTemplatesProjectCollection.
Definition at line 58 of file templatescollection.cpp.
References protocol_.
Referenced by TitleBlockTemplatesProjectCollection::protocol(), and setProtocol().
removeTemplate()
virtual void TitleBlockTemplatesCollection::removeTemplate (const QString &) pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
setCollection()
void TitleBlockTemplatesCollection::setCollection (QET::QetCollection c) virtual
TitleBlockTemplatesCollection::setCollection Set the storage of this collection.
Parameters
c
Definition at line 83 of file templatescollection.cpp.
References m_collection.
setProtocol()
void TitleBlockTemplatesCollection::setProtocol (const QString & protocol) virtual
Define the protocol for this collection
Parameters
protocol New protocol for this collection
Definition at line 66 of file templatescollection.cpp.
References protocol(), and protocol_.
setTemplateXmlDescription()
virtual bool TitleBlockTemplatesCollection::setTemplateXmlDescription (const QString & , const QDomElement &) pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
setTitle()
void TitleBlockTemplatesCollection::setTitle (const QString & title) virtual
TitleBlockTemplatesCollection::setTitle.
Parameters
title : New title for this collection
Definition at line 50 of file templatescollection.cpp.
References title(), and title_.
templates()
virtual QStringList TitleBlockTemplatesCollection::templates () pure virtual
Implemented in TitleBlockTemplatesFilesCollection, and TitleBlockTemplatesProjectCollection.
Referenced by templatesLocations().
templatesLocations()
QList< TitleBlockTemplateLocation > TitleBlockTemplatesCollection::templatesLocations () virtual
Returns
the templates contained within this collection, as a list of location objects.
See also
templates()
Definition at line 100 of file templatescollection.cpp.
References location(), and templates().
title()
QString TitleBlockTemplatesCollection::title () const virtual
Returns
the title of this collection
Reimplemented in TitleBlockTemplatesProjectCollection.
Definition at line 42 of file templatescollection.cpp.
References title_.
Referenced by setTitle().
Member Data Documentation
m_collection
QET::QetCollection TitleBlockTemplatesCollection::m_collection protected
Definition at line 74 of file templatescollection.h.
Referenced by collection(), setCollection(), and TitleBlockTemplatesProjectCollection::TitleBlockTemplatesProjectCollection().
protocol_
QString TitleBlockTemplatesCollection::protocol_ protected
Protocol used to designate this collection.
Definition at line 73 of file templatescollection.h.
Referenced by protocol(), and setProtocol().
title_
QString TitleBlockTemplatesCollection::title_ protected
Human-readable title for this collection.
Definition at line 71 of file templatescollection.h.
Referenced by setTitle(), title(), and TitleBlockTemplatesProjectCollection::title().
titleblock_templates_
QHash<QString, TitleBlockTemplate *> TitleBlockTemplatesCollection::titleblock_templates_ protected
Already parsed embedded titleblock templates.
Definition at line 76 of file templatescollection.h.
Referenced by TitleBlockTemplatesProjectCollection::getTemplate(), TitleBlockTemplatesProjectCollection::removeTemplate(), and TitleBlockTemplatesProjectCollection::setTemplateXmlDescription().
The documentation for this class was generated from the following files:
templatescollection.h
templatescollection.cpp