QElectroTech: TitleBlockTemplateLocationChooser Class Reference
TitleBlockTemplateLocationChooser Class Reference
#include <templatelocationchooser.h>
Public Member Functions
TitleBlockTemplateLocationChooser (const TitleBlockTemplateLocation &, QWidget *=nullptr)
TitleBlockTemplateLocationChooser::TitleBlockTemplateLocationChooser Constructor.
~TitleBlockTemplateLocationChooser () override
virtual TitleBlockTemplateLocation location () const
virtual TitleBlockTemplatesCollection * collection () const
virtual QString name () const
virtual void setLocation (const TitleBlockTemplateLocation &)
Protected Slots
virtual void updateCollections ()
virtual void updateTemplates ()
Protected Member Functions
void init ()
virtual int indexForCollection (TitleBlockTemplatesCollection *) const
TitleBlockTemplateLocationChooser::indexForCollection.
Protected Attributes
QFormLayout * form_layout_
QComboBox * collections_
QHash< int, TitleBlockTemplatesCollection * > collections_index_
Collections index within the combo box.
QComboBox * templates_
Existing templates combo box.
Private Member Functions
TitleBlockTemplateLocationChooser (const TitleBlockTemplateLocationChooser &)
Detailed Description
This class is a widget that allows the user to choose a target title block template.
Definition at line 28 of file templatelocationchooser.h.
Constructor & Destructor Documentation
TitleBlockTemplateLocationChooser() [1/2]
TitleBlockTemplateLocationChooser::TitleBlockTemplateLocationChooser (const TitleBlockTemplateLocation & location, QWidget * parent = nullptr)
TitleBlockTemplateLocationChooser::TitleBlockTemplateLocationChooser Constructor.
Parameters
location : Initial location displayed by the widget
parent : Parent QWidget
Definition at line 29 of file templatelocationchooser.cpp.
References init(), location(), and setLocation().
~TitleBlockTemplateLocationChooser()
TitleBlockTemplateLocationChooser::~TitleBlockTemplateLocationChooser () override
Destructor
Definition at line 42 of file templatelocationchooser.cpp.
TitleBlockTemplateLocationChooser() [2/2]
TitleBlockTemplateLocationChooser::TitleBlockTemplateLocationChooser (const TitleBlockTemplateLocationChooser &) private
Member Function Documentation
collection()
TitleBlockTemplatesCollection * TitleBlockTemplateLocationChooser::collection () const virtual
Returns
the currently selected collection
Definition at line 55 of file templatelocationchooser.cpp.
References collections_, and collections_index_.
Referenced by location(), updateCollections(), TitleBlockTemplateLocationSaver::updateTemplates(), and updateTemplates().
indexForCollection()
int TitleBlockTemplateLocationChooser::indexForCollection (TitleBlockTemplatesCollection * coll) const protected virtual
TitleBlockTemplateLocationChooser::indexForCollection.
Parameters
coll : A Title block templates collection which we want to know the index within the combo box of this dialog.
Returns
-1 if the collection is unknown to this dialog, or the index of coll
Definition at line 113 of file templatelocationchooser.cpp.
References collections_index_.
Referenced by TitleBlockTemplateLocationSaver::setLocation(), and setLocation().
init()
void TitleBlockTemplateLocationChooser::init () protected
Initialize this widget.
Parameters
location Initial location displayed by the widget
Definition at line 90 of file templatelocationchooser.cpp.
References collections_, form_layout_, templates_, QET::Icons::tr, updateCollections(), and updateTemplates().
Referenced by TitleBlockTemplateLocationChooser().
location()
TitleBlockTemplateLocation TitleBlockTemplateLocationChooser::location () const virtual
Returns
the current location
Definition at line 48 of file templatelocationchooser.cpp.
References collection(), and name().
Referenced by TitleBlockTemplateLocationSaver::setLocation(), setLocation(), TitleBlockTemplateLocationChooser(), and TitleBlockTemplateLocationSaver::TitleBlockTemplateLocationSaver().
name()
QString TitleBlockTemplateLocationChooser::name () const virtual
Returns
the currently selected/entered name
Reimplemented in TitleBlockTemplateLocationSaver.
Definition at line 62 of file templatelocationchooser.cpp.
References templates_.
Referenced by location().
setLocation()
void TitleBlockTemplateLocationChooser::setLocation (const TitleBlockTemplateLocation & location) virtual
Set the location displayed by this widget
Parameters
location to be displayed by this widget
Reimplemented in TitleBlockTemplateLocationSaver.
Definition at line 71 of file templatelocationchooser.cpp.
References collections_, indexForCollection(), location(), TitleBlockTemplateLocation::name(), TitleBlockTemplateLocation::parentCollection(), and templates_.
Referenced by TitleBlockTemplateLocationChooser().
updateCollections
void TitleBlockTemplateLocationChooser::updateCollections () protected virtual slot
Update the collections list
Definition at line 123 of file templatelocationchooser.cpp.
References QETApp::availableTitleBlockTemplatesCollections(), collection(), collections_, collections_index_, and updateTemplates().
Referenced by init().
updateTemplates
void TitleBlockTemplateLocationChooser::updateTemplates () protected virtual slot
Update the templates list according to the selected collection.
Definition at line 141 of file templatelocationchooser.cpp.
References collection(), and templates_.
Referenced by init(), updateCollections(), and TitleBlockTemplateLocationSaver::updateTemplates().
Member Data Documentation
collections_
QComboBox* TitleBlockTemplateLocationChooser::collections_ protected
Collections combo box
Definition at line 58 of file templatelocationchooser.h.
Referenced by collection(), init(), TitleBlockTemplateLocationSaver::setLocation(), setLocation(), and updateCollections().
collections_index_
QHash<int, TitleBlockTemplatesCollection *> TitleBlockTemplateLocationChooser::collections_index_ protected
Collections index within the combo box.
Definition at line 60 of file templatelocationchooser.h.
Referenced by collection(), indexForCollection(), and updateCollections().
form_layout_
QFormLayout* TitleBlockTemplateLocationChooser::form_layout_ protected
Definition at line 57 of file templatelocationchooser.h.
Referenced by TitleBlockTemplateLocationSaver::init(), and init().
templates_
QComboBox* TitleBlockTemplateLocationChooser::templates_ protected
Existing templates combo box.
Definition at line 61 of file templatelocationchooser.h.
Referenced by TitleBlockTemplateLocationSaver::init(), init(), TitleBlockTemplateLocationSaver::name(), name(), TitleBlockTemplateLocationSaver::setLocation(), setLocation(), TitleBlockTemplateLocationSaver::updateNewName(), TitleBlockTemplateLocationSaver::updateTemplates(), and updateTemplates().
The documentation for this class was generated from the following files:
templatelocationchooser.h
templatelocationchooser.cpp