QElectroTech: QET::QetMessageBox Namespace Reference
QET::QetMessageBox Namespace Reference
Functions
QMessageBox::StandardButton critical (QWidget *, const QString &, const QString &, QMessageBox::StandardButtons=QMessageBox::Ok, QMessageBox::StandardButton=QMessageBox::NoButton)
QMessageBox::StandardButton information (QWidget *, const QString &, const QString &, QMessageBox::StandardButtons=QMessageBox::Ok, QMessageBox::StandardButton=QMessageBox::NoButton)
QMessageBox::StandardButton question (QWidget *, const QString &, const QString &, QMessageBox::StandardButtons=QMessageBox::Ok, QMessageBox::StandardButton=QMessageBox::NoButton)
QMessageBox::StandardButton warning (QWidget *, const QString &, const QString &, QMessageBox::StandardButtons=QMessageBox::Ok, QMessageBox::StandardButton=QMessageBox::NoButton)
Detailed Description
This namespace defines static methods behaving in a very similar way to some static methods from the QMessageBox Qt class. The behavior is expected to be the same under X11 and Windows. However, under MacOS, when a parent widget is provided, these methodes ensure the dialog box is "window modal" and has the Qt:Sheet flag, thus enabling a better MacOS integration.
Function Documentation
critical()
QMessageBox::StandardButton QET::QetMessageBox::critical (QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons = QMessageBox::Ok, QMessageBox::StandardButton defaultButton = QMessageBox::NoButton)
See also
Documentation Qt pour QMessageBox::critical
Definition at line 23 of file qetmessagebox.cpp.
Referenced by ElementsCategoryEditor::acceptCreation(), TitleBlockTemplateLogoManager::addLogo(), ElementDialog::checkAccept(), QETElementEditor::checkElement(), ProjectView::cleanProject(), IntegrationMoveTitleBlockTemplatesHandler::errorWithATemplate(), BOMExportDialog::exec(), ExportDialog::exportDiagram(), TitleBlockTemplateLogoManager::exportLogo(), QETElementEditor::fromFile(), QETElementEditor::fromLocation(), QETDiagramEditor::openAndAddProject(), DiagramEventAddImage::openDialog(), QETElementEditor::openElement(), QETElementEditor::pasteFromElement(), QETElementEditor::pasteFromFile(), QETDiagramEditor::showError(), QETElementEditor::slot_save(), QETElementEditor::slot_saveAs(), QETElementEditor::slot_saveAsFile(), ConductorNumExport::toCsv(), QETElementEditor::toLocation(), NewElementWizard::validStep1(), and NewElementWizard::validStep2().
information()
QMessageBox::StandardButton QET::QetMessageBox::information (QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons = QMessageBox::Ok, QMessageBox::StandardButton defaultButton = QMessageBox::NoButton)
See also
Documentation Qt pour QMessageBox::information
Definition at line 38 of file qetmessagebox.cpp.
Referenced by DiagramPrintDialog::acceptPrintTypeDialog(), QetGraphicsTableItem::checkInsufficientRowsCount(), ElementsCollectionWidget::dirProperties(), QETTitleBlockTemplateEditor::editTemplateInformation(), ImportElementTextPattern::ImportElementTextPattern(), AutoNumberingManagementW::on_buttonBox_clicked(), SelectAutonumW::on_buttonBox_clicked(), FolioAutonumberingW::on_buttonBox_clicked(), and NameListDialog::showHelpDialog().
question()
QMessageBox::StandardButton QET::QetMessageBox::question (QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons = QMessageBox::Ok, QMessageBox::StandardButton defaultButton = QMessageBox::NoButton)
See also
Documentation Qt pour QMessageBox::question
Definition at line 53 of file qetmessagebox.cpp.
Referenced by QETTitleBlockTemplateEditor::canClose(), QETElementEditor::canClose(), ElementDialog::checkAccept(), QETApp::checkBackupFiles(), ElementsCollectionWidget::deleteDirectory(), ElementsCollectionWidget::deleteElement(), TitleBlockTemplateDeleter::exec(), ExportElementTextPattern::ExportElementTextPattern(), ProjectView::removeDiagram(), QETElementEditor::slot_reload(), and ProjectView::tryClosingDiagrams().
warning()
QMessageBox::StandardButton QET::QetMessageBox::warning (QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons = QMessageBox::Ok, QMessageBox::StandardButton defaultButton = QMessageBox::NoButton)
See also
Documentation Qt pour QMessageBox::warning
Definition at line 68 of file qetmessagebox.cpp.
Referenced by QETElementEditor::checkElement(), ElementsCollectionWidget::deleteDirectory(), ElementsCollectionWidget::deleteElement(), ElementsCategoryEditor::ElementsCategoryEditor(), QETElementEditor::fromFile(), QETElementEditor::fromLocation(), QETDiagramEditor::generateTerminalBlock(), PolygonEditor::on_m_points_list_tree_itemChanged(), QETDiagramEditor::openAndAddProject(), QETDiagramEditor::openBackupFiles(), QETProject::readProjectXml(), TitleBlockTemplateLogoManager::renameLogo(), ExportDialog::slot_export(), and QETElementEditor::toFile().