QElectroTech: QETMainWindow Class Reference
QETMainWindow Class Reference
#include <qetmainwindow.h>
Public Slots
void toggleFullScreen ()
void updateFullScreenAction ()
void checkToolbarsmenu ()
Public Member Functions
QETMainWindow (QWidget *=nullptr, Qt::WindowFlags=Qt::Widget)
~QETMainWindow () override
Protected Member Functions
void initCommonActions ()
void initCommonMenus ()
void insertMenu (QMenu *, QMenu *, bool=true)
QAction * actionForMenu (QMenu *)
bool event (QEvent *) override
void dragEnterEvent (QDragEnterEvent *e) override
void dropEvent (QDropEvent *e) override
virtual void firstActivation (QEvent *)
Protected Attributes
QAction * configure_action_
Launch the QElectroTech configuration dialog.
QAction * fullscreen_action_
Toggle full screen.
QAction * whatsthis_action_
Toggle "What's this" mode.
QAction * about_qet_
Launch the "About QElectroTech" dialog.
QAction * manual_online_
Launch browser on QElectroTech online manual.
QAction * youtube_
Launch browser on QElectroTech Youtube channel.
QAction * upgrade_
Launch browser on QElectroTech Windows Nightly builds.
QAction * upgrade_M
Launch browser on QElectroTech MAC_OS_X builds.
QAction * donate_
Launch browser to donate link.
QAction * about_qt_
launch the "About Qt" dialog
QMenu * settings_menu_
Settings menu.
QMenu * help_menu_
Help menu.
QMenu * display_toolbars_
Show/hide toolbars/docks.
QHash< QMenu *, QAction * > menu_actions_
Store actions retrieved when inserting menus.
bool first_activation_
Used to detect whether the window is activated for the first time.
Detailed Description
This is the base class for the main top-level windows within QElectroTech.
Definition at line 26 of file qetmainwindow.h.
Constructor & Destructor Documentation
QETMainWindow()
QETMainWindow::QETMainWindow (QWidget * widget = nullptr, Qt::WindowFlags flags = Qt::Widget)
Constructor
Definition at line 34 of file qetmainwindow.cpp.
References initCommonActions(), and initCommonMenus().
~QETMainWindow()
QETMainWindow::~QETMainWindow () override
Destructor
Definition at line 48 of file qetmainwindow.cpp.
Member Function Documentation
actionForMenu()
QAction * QETMainWindow::actionForMenu (QMenu * menu) protected
Returns
the action returned when inserting menu
Definition at line 187 of file qetmainwindow.cpp.
References menu_actions_.
Referenced by insertMenu().
checkToolbarsmenu
void QETMainWindow::checkToolbarsmenu () slot
Check whether a sub menu dedicated to docks and toolbars can be inserted on top of the settings menu.
Definition at line 219 of file qetmainwindow.cpp.
References QET::Icons::ConfigureToolbars, display_toolbars_, fullscreen_action_, insertMenu(), settings_menu_, and QET::Icons::tr.
Referenced by initCommonMenus().
dragEnterEvent()
void QETMainWindow::dragEnterEvent (QDragEnterEvent * e) override protected
Accept or refuse drag'n drop events depending on the dropped mime type; especially, accepts only URLs to local files that we could open.
Parameters
e le QDragEnterEvent correspondant au drag'n drop tente
Definition at line 255 of file qetmainwindow.cpp.
References QETApp::handledFiles().
dropEvent()
void QETMainWindow::dropEvent (QDropEvent * e) override protected
Handle drops accepted on main windows; more specifically, open dropped files as long as they are handled by QElectrotech.
Parameters
e the QDropEvent describing the current drag'n drop
Definition at line 268 of file qetmainwindow.cpp.
References QETApp::handledFiles(), and QETApp::instance().
event()
bool QETMainWindow::event (QEvent * e) override protected
Handle the e event.
Definition at line 233 of file qetmainwindow.cpp.
References first_activation_, firstActivation(), and updateFullScreenAction().
Referenced by QETDiagramEditor::event(), QETTitleBlockTemplateEditor::firstActivation(), and QETElementEditor::firstActivation().
firstActivation()
void QETMainWindow::firstActivation (QEvent *) protected virtual
Base implementation of firstActivation (does nothing).
Reimplemented in QETElementEditor, and QETTitleBlockTemplateEditor.
Definition at line 246 of file qetmainwindow.cpp.
Referenced by event().
initCommonActions()
void QETMainWindow::initCommonActions () protected
Initialize common actions.
Definition at line 54 of file qetmainwindow.cpp.
References QET::Icons::Configure, configure_action_, QETApp::configureQET(), QETApp::diagramEditors(), QETApp::instance(), and QET::Icons::tr.
Referenced by QETMainWindow().
initCommonMenus()
void QETMainWindow::initCommonMenus () protected
Initialize common menus.
Definition at line 134 of file qetmainwindow.cpp.
References about_qet_, about_qt_, checkToolbarsmenu(), configure_action_, donate_, fullscreen_action_, help_menu_, insertMenu(), manual_online_, settings_menu_, QET::Icons::tr, upgrade_, upgrade_M, whatsthis_action_, and youtube_.
Referenced by QETMainWindow().
insertMenu()
void QETMainWindow::insertMenu (QMenu * before, QMenu * menu, bool customize = true) protected
Add menu before before. Unless customize is false, this method also enables some common settings on the inserted menu.
Definition at line 172 of file qetmainwindow.cpp.
References actionForMenu(), and menu_actions_.
Referenced by checkToolbarsmenu(), initCommonMenus(), QETTitleBlockTemplateEditor::initMenus(), QETDiagramEditor::setUpMenu(), and QETElementEditor::setupMenus().
toggleFullScreen
void QETMainWindow::toggleFullScreen () slot
Toggle the window from/to full screen.
Definition at line 194 of file qetmainwindow.cpp.
updateFullScreenAction
void QETMainWindow::updateFullScreenAction () slot
Update the look of the full screen action according to the current state of the window.
Definition at line 202 of file qetmainwindow.cpp.
References fullscreen_action_, QET::Icons::FullScreenEnter, QET::Icons::FullScreenExit, and QET::Icons::tr.
Referenced by event().
Member Data Documentation
about_qet_
QAction* QETMainWindow::about_qet_ protected
Launch the "About QElectroTech" dialog.
Definition at line 58 of file qetmainwindow.h.
Referenced by initCommonMenus().
about_qt_
QAction* QETMainWindow::about_qt_ protected
launch the "About Qt" dialog
Definition at line 64 of file qetmainwindow.h.
Referenced by initCommonMenus().
configure_action_
QAction* QETMainWindow::configure_action_ protected
Launch the QElectroTech configuration dialog.
Definition at line 55 of file qetmainwindow.h.
Referenced by initCommonActions(), and initCommonMenus().
display_toolbars_
QMenu* QETMainWindow::display_toolbars_ protected
Show/hide toolbars/docks.
Definition at line 67 of file qetmainwindow.h.
Referenced by checkToolbarsmenu().
donate_
QAction* QETMainWindow::donate_ protected
Launch browser to donate link.
Definition at line 63 of file qetmainwindow.h.
Referenced by initCommonMenus().
first_activation_
bool QETMainWindow::first_activation_ protected
Used to detect whether the window is activated for the first time.
Definition at line 69 of file qetmainwindow.h.
Referenced by event().
fullscreen_action_
QAction* QETMainWindow::fullscreen_action_ protected
Toggle full screen.
Definition at line 56 of file qetmainwindow.h.
Referenced by checkToolbarsmenu(), initCommonMenus(), and updateFullScreenAction().
help_menu_
QMenu* QETMainWindow::help_menu_ protected
Help menu.
Definition at line 66 of file qetmainwindow.h.
Referenced by initCommonMenus(), and QETDiagramEditor::setUpMenu().
manual_online_
QAction* QETMainWindow::manual_online_ protected
Launch browser on QElectroTech online manual.
Definition at line 59 of file qetmainwindow.h.
Referenced by initCommonMenus().
menu_actions_
QHash<QMenu *, QAction *> QETMainWindow::menu_actions_ protected
Store actions retrieved when inserting menus.
Definition at line 68 of file qetmainwindow.h.
Referenced by actionForMenu(), and insertMenu().
settings_menu_
QMenu* QETMainWindow::settings_menu_ protected
Settings menu.
Definition at line 65 of file qetmainwindow.h.
Referenced by checkToolbarsmenu(), initCommonMenus(), QETTitleBlockTemplateEditor::initMenus(), QETDiagramEditor::setUpMenu(), and QETElementEditor::setupMenus().
upgrade_
QAction* QETMainWindow::upgrade_ protected
Launch browser on QElectroTech Windows Nightly builds.
Definition at line 61 of file qetmainwindow.h.
Referenced by initCommonMenus().
upgrade_M
QAction* QETMainWindow::upgrade_M protected
Launch browser on QElectroTech MAC_OS_X builds.
Definition at line 62 of file qetmainwindow.h.
Referenced by initCommonMenus().
whatsthis_action_
QAction* QETMainWindow::whatsthis_action_ protected
Toggle "What's this" mode.
Definition at line 57 of file qetmainwindow.h.
Referenced by initCommonMenus().
youtube_
QAction* QETMainWindow::youtube_ protected
Launch browser on QElectroTech Youtube channel.
Definition at line 60 of file qetmainwindow.h.
Referenced by initCommonMenus().
The documentation for this class was generated from the following files:
qetmainwindow.h
qetmainwindow.cpp