QElectroTech: BOMExportDialog Class Reference
BOMExportDialog Class Reference
The BOMExportDialog class.
#include <bomexportdialog.h>
Public Member Functions
BOMExportDialog (QETProject *project, QWidget *parent=nullptr)
BOMExportDialog::BOMExportDialog.
~BOMExportDialog () override
BOMExportDialog::~BOMExportDialog.
virtual int exec () override
BOMExportDialog::exec.
QString getBom ()
Private Slots
void on_m_format_as_bom_clicked (bool checked)
BOMExportDialog::on_m_format_as_bom_clicked.
Private Attributes
Ui::BOMExportDialog * ui
ElementQueryWidget * m_query_widget = nullptr
QETProject * m_project = nullptr
Detailed Description
The BOMExportDialog class.
Definition at line 33 of file bomexportdialog.h.
Constructor & Destructor Documentation
BOMExportDialog()
BOMExportDialog::BOMExportDialog (QETProject * project, QWidget * parent = nullptr) explicit
BOMExportDialog::BOMExportDialog.
Parameters
project
parent
Definition at line 34 of file bomexportdialog.cpp.
References m_query_widget, on_m_format_as_bom_clicked(), and ui.
~BOMExportDialog()
BOMExportDialog::~BOMExportDialog () override
BOMExportDialog::~BOMExportDialog.
Definition at line 50 of file bomexportdialog.cpp.
References ui.
Member Function Documentation
exec()
int BOMExportDialog::exec () override virtual
BOMExportDialog::exec.
Returns
Definition at line 59 of file bomexportdialog.cpp.
References QET::QetMessageBox::critical(), getBom(), m_project, and QET::Icons::tr.
Referenced by QETDiagramEditor::setUpActions().
getBom()
QString BOMExportDialog::getBom ()
Definition at line 95 of file bomexportdialog.cpp.
References QETProject::dataBase(), QETApp::diagramTranslatedInfoKey(), QETApp::elementTranslatedInfoKey(), m_project, m_query_widget, projectDataBase::newQuery(), ElementQueryWidget::queryStr(), QET::Icons::tr, ui, and projectDataBase::updateDB().
Referenced by exec().
on_m_format_as_bom_clicked
void BOMExportDialog::on_m_format_as_bom_clicked (bool checked) private slot
BOMExportDialog::on_m_format_as_bom_clicked.
Parameters
checked
Definition at line 165 of file bomexportdialog.cpp.
References m_query_widget, ElementQueryWidget::setCount(), and ElementQueryWidget::setGroupBy().
Referenced by BOMExportDialog().
Member Data Documentation
m_project
QETProject* BOMExportDialog::m_project = nullptr private
Definition at line 50 of file bomexportdialog.h.
Referenced by exec(), and getBom().
m_query_widget
ElementQueryWidget* BOMExportDialog::m_query_widget = nullptr private
Definition at line 49 of file bomexportdialog.h.
Referenced by BOMExportDialog(), getBom(), and on_m_format_as_bom_clicked().
ui
Ui::BOMExportDialog* BOMExportDialog::ui private
Definition at line 48 of file bomexportdialog.h.
Referenced by BOMExportDialog(), getBom(), and ~BOMExportDialog().
The documentation for this class was generated from the following files:
bomexportdialog.h
bomexportdialog.cpp