QElectroTech: replaceAdvancedDialog Class Reference
replaceAdvancedDialog Class Reference
#include <replaceadvanceddialog.h>
Public Member Functions
replaceAdvancedDialog (advancedReplaceStruct advanced, QWidget *parent=nullptr)
replaceAdvancedDialog::replaceAdvancedDialog
~replaceAdvancedDialog ()
void setAdvancedStruct (advancedReplaceStruct advanced)
replaceAdvancedDialog::setAdvancedStruct Set the edited advanced struct
advancedReplaceStruct advancedStruct () const
replaceAdvancedDialog::advancedStruct
Private Slots
void on_m_who_cb_currentIndexChanged (int index)
replaceAdvancedDialog::on_m_who_cb_currentIndexChanged
Private Member Functions
void fillWhatComboBox (int index)
Private Attributes
Ui::replaceAdvancedDialog * ui
Detailed Description
Definition at line 29 of file replaceadvanceddialog.h.
Constructor & Destructor Documentation
replaceAdvancedDialog()
replaceAdvancedDialog::replaceAdvancedDialog (advancedReplaceStruct advanced, QWidget * parent = nullptr) explicit
replaceAdvancedDialog::replaceAdvancedDialog
Parameters
advanced
parent
Definition at line 29 of file replaceadvanceddialog.cpp.
References fillWhatComboBox(), setAdvancedStruct(), and ui.
~replaceAdvancedDialog()
replaceAdvancedDialog::~replaceAdvancedDialog ()
Definition at line 44 of file replaceadvanceddialog.cpp.
References ui.
Member Function Documentation
advancedStruct()
advancedReplaceStruct replaceAdvancedDialog::advancedStruct () const
replaceAdvancedDialog::advancedStruct
Returns
the edited advanced struct
Definition at line 79 of file replaceadvanceddialog.cpp.
References advancedReplaceStruct::replace, advancedReplaceStruct::search, ui, advancedReplaceStruct::what, and advancedReplaceStruct::who.
Referenced by SearchAndReplaceWidget::on_m_advanced_replace_pb_clicked().
fillWhatComboBox()
void replaceAdvancedDialog::fillWhatComboBox (int index) private
Definition at line 90 of file replaceadvanceddialog.cpp.
References QETApp::conductorInfoKeys(), QETApp::conductorTranslatedInfoKey(), QETApp::diagramInfoKeys(), QETApp::diagramTranslatedInfoKey(), QETApp::elementInfoKeys(), QETApp::elementTranslatedInfoKey(), and ui.
Referenced by on_m_who_cb_currentIndexChanged(), and replaceAdvancedDialog().
on_m_who_cb_currentIndexChanged
void replaceAdvancedDialog::on_m_who_cb_currentIndexChanged (int index) private slot
replaceAdvancedDialog::on_m_who_cb_currentIndexChanged
Parameters
index
Definition at line 116 of file replaceadvanceddialog.cpp.
References fillWhatComboBox().
setAdvancedStruct()
void replaceAdvancedDialog::setAdvancedStruct (advancedReplaceStruct advanced)
replaceAdvancedDialog::setAdvancedStruct Set the edited advanced struct
Parameters
advanced
Definition at line 54 of file replaceadvanceddialog.cpp.
References advancedReplaceStruct::replace, advancedReplaceStruct::search, ui, advancedReplaceStruct::what, and advancedReplaceStruct::who.
Referenced by replaceAdvancedDialog().
Member Data Documentation
ui
Ui::replaceAdvancedDialog* replaceAdvancedDialog::ui private
Definition at line 47 of file replaceadvanceddialog.h.
Referenced by advancedStruct(), fillWhatComboBox(), replaceAdvancedDialog(), setAdvancedStruct(), and ~replaceAdvancedDialog().
The documentation for this class was generated from the following files:
replaceadvanceddialog.h
replaceadvanceddialog.cpp