QElectroTech: DiagramEventAddShape Class Reference
DiagramEventAddShape Class Reference
The DiagramEventAddShape class This event manage the creation of a shape.
#include <diagrameventaddshape.h>
Public Member Functions
DiagramEventAddShape (Diagram *diagram, QetShapeItem::ShapeType shape_type)
DiagramEventAddShape::DiagramEventAddShape Default constructor.
~DiagramEventAddShape () override
DiagramEventAddShape::~DiagramEventAddShape.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddShape::mousePressEvent Action when mouse is pressed.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddShape::mouseMoveEvent Action when mouse move.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddShape::mouseReleaseEvent Action when mouse button is released.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddShape::mouseDoubleClickEvent Action when mouse button is double clicked.
void init () override
Public Member Functions inherited from DiagramEventInterface
DiagramEventInterface (Diagram *diagram)
~DiagramEventInterface () override=0
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
DiagramEventInterface::keyPressEvent By default, press escape key abort the curent action.
virtual void keyReleaseEvent (QKeyEvent *event)
virtual bool isRunning () const
Protected Attributes
QetShapeItem::ShapeType m_shape_type
QetShapeItem * m_shape_item
QGraphicsLineItem * m_help_horiz
QGraphicsLineItem * m_help_verti
Protected Attributes inherited from DiagramEventInterface
Diagram * m_diagram
bool m_running
bool m_abort
Private Member Functions
void updateHelpCross (const QPointF &p)
DiagramEventAddShape::updateHelpCross Create and update the position of the cross to help user for draw new shape.
Additional Inherited Members
Signals inherited from DiagramEventInterface
void finish ()
Detailed Description
The DiagramEventAddShape class This event manage the creation of a shape.
Definition at line 28 of file diagrameventaddshape.h.
Constructor & Destructor Documentation
DiagramEventAddShape()
DiagramEventAddShape::DiagramEventAddShape (Diagram * diagram, QetShapeItem::ShapeType shape_type)
DiagramEventAddShape::DiagramEventAddShape Default constructor.
Parameters
diagram : the diagram where this event must operate
shape_type : the type of shape to draw
Definition at line 28 of file diagrameventaddshape.cpp.
References init(), and DiagramEventInterface::m_running.
~DiagramEventAddShape()
DiagramEventAddShape::~DiagramEventAddShape () override
DiagramEventAddShape::~DiagramEventAddShape.
Definition at line 42 of file diagrameventaddshape.cpp.
References DiagramEventInterface::m_abort, DiagramEventInterface::m_diagram, m_help_horiz, m_help_verti, DiagramEventInterface::m_running, m_shape_item, and Diagram::removeItem().
Member Function Documentation
init()
void DiagramEventAddShape::init () override virtual
Reimplemented from DiagramEventInterface.
Definition at line 200 of file diagrameventaddshape.cpp.
References DiagramEventInterface::m_diagram.
Referenced by DiagramEventAddShape().
mouseDoubleClickEvent()
void DiagramEventAddShape::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddShape::mouseDoubleClickEvent Action when mouse button is double clicked.
Parameters
event : event of mouse double click
Reimplemented from DiagramEventInterface.
Definition at line 177 of file diagrameventaddshape.cpp.
References DiagramEventInterface::m_diagram, m_shape_item, m_shape_type, QetShapeItem::polygon, QetShapeItem::Polygon, QetShapeItem::removePoints(), QetShapeItem::setClosed(), and Diagram::undoStack().
mouseMoveEvent()
void DiagramEventAddShape::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddShape::mouseMoveEvent Action when mouse move.
Parameters
event : event of mouse move
Reimplemented from DiagramEventInterface.
Definition at line 114 of file diagrameventaddshape.cpp.
References m_shape_item, QetShapeItem::setP2(), Diagram::snapToGrid(), and updateHelpCross().
mousePressEvent()
void DiagramEventAddShape::mousePressEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddShape::mousePressEvent Action when mouse is pressed.
Parameters
event : event of mouse press
Reimplemented from DiagramEventInterface.
Definition at line 61 of file diagrameventaddshape.cpp.
References Diagram::addItem(), QetShapeItem::Ellipse, Diagram::isReadOnly(), DiagramEventInterface::m_diagram, m_shape_item, m_shape_type, QetShapeItem::Polygon, QetShapeItem::rect, QetShapeItem::Rectangle, QetShapeItem::setNextPoint(), QetShapeItem::setP2(), QetShapeItem::setRect(), QetShapeItem::shapeType(), Diagram::snapToGrid(), and Diagram::undoStack().
mouseReleaseEvent()
void DiagramEventAddShape::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddShape::mouseReleaseEvent Action when mouse button is released.
Parameters
event : event of mouse release
Reimplemented from DiagramEventInterface.
Definition at line 135 of file diagrameventaddshape.cpp.
References DiagramEventInterface::finish(), DiagramEventInterface::m_diagram, DiagramEventInterface::m_running, m_shape_item, m_shape_type, QetShapeItem::pointsCount(), QetShapeItem::Polygon, Diagram::removeItem(), QetShapeItem::removePoints(), QetShapeItem::setP2(), and Diagram::snapToGrid().
updateHelpCross()
void DiagramEventAddShape::updateHelpCross (const QPointF & p) private
DiagramEventAddShape::updateHelpCross Create and update the position of the cross to help user for draw new shape.
Parameters
p : the center of the cross
Definition at line 211 of file diagrameventaddshape.cpp.
References Diagram::addItem(), Diagram::background_color, Diagram::border_and_titleblock, BorderTitleBlock::insideBorderRect(), DiagramEventInterface::m_diagram, m_help_horiz, m_help_verti, and Diagram::snapToGrid().
Referenced by mouseMoveEvent().
Member Data Documentation
m_help_horiz
QGraphicsLineItem* DiagramEventAddShape::m_help_horiz protected
Definition at line 48 of file diagrameventaddshape.h.
Referenced by updateHelpCross(), and ~DiagramEventAddShape().
m_help_verti
QGraphicsLineItem * DiagramEventAddShape::m_help_verti protected
Definition at line 48 of file diagrameventaddshape.h.
Referenced by updateHelpCross(), and ~DiagramEventAddShape().
m_shape_item
QetShapeItem* DiagramEventAddShape::m_shape_item protected
Definition at line 47 of file diagrameventaddshape.h.
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and ~DiagramEventAddShape().
m_shape_type
QetShapeItem::ShapeType DiagramEventAddShape::m_shape_type protected
Definition at line 46 of file diagrameventaddshape.h.
Referenced by mouseDoubleClickEvent(), mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
diagrameventaddshape.h
diagrameventaddshape.cpp