QElectroTech: AboutQETDialog Class Reference
AboutQETDialog Class Reference
The AboutQETDialog class.
#include <aboutqetdialog.h>
Public Member Functions
AboutQETDialog (QWidget *parent=nullptr)
AboutQETDialog::AboutQETDialog.
~AboutQETDialog ()
AboutQETDialog::~AboutQETDialog.
Private Member Functions
void setAbout ()
AboutQETDialog::setAbout.
void setAuthors ()
AboutQETDialog::setAuthors.
void setTranslators ()
AboutQETDialog::setTranslators.
void setContributors ()
AboutQETDialog::setContributors.
void setVersion ()
AboutQETDialog::setVersion.
void setLibraries ()
AboutQETDialog::setLibraries.
void setLicence ()
AboutQETDialog::setLicence.
void addAuthor (QLabel *label, const QString &name, const QString &email, const QString &work)
AboutQETDialog::addAuthor Adds a person to the list of authors.
void addLibrary (QLabel *label, const QString &name, const QString &link)
AboutQETDialog::addLibrary.
Private Attributes
Ui::AboutQETDialog * ui
Detailed Description
The AboutQETDialog class.
Definition at line 32 of file aboutqetdialog.h.
Constructor & Destructor Documentation
AboutQETDialog()
AboutQETDialog::AboutQETDialog (QWidget * parent = nullptr) explicit
AboutQETDialog::AboutQETDialog.
Parameters
parent
Definition at line 28 of file aboutqetdialog.cpp.
References setAbout(), setAuthors(), setContributors(), setLibraries(), setLicence(), setTranslators(), setVersion(), and ui.
~AboutQETDialog()
AboutQETDialog::~AboutQETDialog ()
AboutQETDialog::~AboutQETDialog.
Definition at line 45 of file aboutqetdialog.cpp.
References ui.
Member Function Documentation
addAuthor()
void AboutQETDialog::addAuthor (QLabel * label, const QString & name, const QString & email, const QString & work) private
AboutQETDialog::addAuthor Adds a person to the list of authors.
Parameters
label : QLabel which will add the person
name : Name of person
email : E-mail address of the person
work : Function / work done by the person
Definition at line 176 of file aboutqetdialog.cpp.
Referenced by setAuthors(), setContributors(), and setTranslators().
addLibrary()
void AboutQETDialog::addLibrary (QLabel * label, const QString & name, const QString & link) private
AboutQETDialog::addLibrary.
Parameters
label
name
link
Definition at line 193 of file aboutqetdialog.cpp.
Referenced by setLibraries().
setAbout()
void AboutQETDialog::setAbout () private
AboutQETDialog::setAbout.
Definition at line 53 of file aboutqetdialog.cpp.
References QET::Icons::tr, and ui.
Referenced by AboutQETDialog().
setAuthors()
void AboutQETDialog::setAuthors () private
AboutQETDialog::setAuthors.
Definition at line 70 of file aboutqetdialog.cpp.
References addAuthor(), QET::Icons::tr, and ui.
Referenced by AboutQETDialog().
setContributors()
void AboutQETDialog::setContributors () private
AboutQETDialog::setContributors.
Definition at line 115 of file aboutqetdialog.cpp.
References addAuthor(), QET::Icons::tr, and ui.
Referenced by AboutQETDialog().
setLibraries()
void AboutQETDialog::setLibraries () private
AboutQETDialog::setLibraries.
Definition at line 153 of file aboutqetdialog.cpp.
References addLibrary(), and ui.
Referenced by AboutQETDialog().
setLicence()
void AboutQETDialog::setLicence () private
AboutQETDialog::setLicence.
Definition at line 163 of file aboutqetdialog.cpp.
References QET::license(), and ui.
Referenced by AboutQETDialog().
setTranslators()
void AboutQETDialog::setTranslators () private
AboutQETDialog::setTranslators.
Definition at line 84 of file aboutqetdialog.cpp.
References addAuthor(), QET::Icons::tr, and ui.
Referenced by AboutQETDialog().
setVersion()
void AboutQETDialog::setVersion () private
AboutQETDialog::setVersion.
Definition at line 141 of file aboutqetdialog.cpp.
References Machine_info::compilation_info(), QET::displayedVersion, and ui.
Referenced by AboutQETDialog().
Member Data Documentation
ui
Ui::AboutQETDialog* AboutQETDialog::ui private
Definition at line 57 of file aboutqetdialog.h.
Referenced by AboutQETDialog(), setAbout(), setAuthors(), setContributors(), setLibraries(), setLicence(), setTranslators(), setVersion(), and ~AboutQETDialog().
The documentation for this class was generated from the following files:
aboutqetdialog.h
aboutqetdialog.cpp