QElectroTech: DialogWaiting Class Reference
DialogWaiting Class Reference
#include <dialogwaiting.h>
Public Member Functions
DialogWaiting (QWidget *parent=nullptr)
DialogWaiting::DialogWaiting.
~DialogWaiting () override
DialogWaiting::~DialogWaiting.
void setProgressBar (int val)
DialogWaiting::setProgressBar.
void setProgressBarRange (int min, int max)
DialogWaiting::setProgressBarRange.
void setProgressReset ()
DialogWaiting::setProgressReset, clear progressBar and reset.
void setTitle (const QString &val)
DialogWaiting::setTitle of action.
void setDetail (const QString &val)
DialogWaiting::setDetail of action.
int progressBarValue () const
DialogWaiting::progressBarValue.
Static Public Member Functions
static DialogWaiting * instance (QWidget *parent=nullptr)
static bool hasInstance ()
static void dropInstance ()
Private Attributes
Ui::DialogWaiting * ui
Static Private Attributes
static DialogWaiting * m_static_dialog = nullptr
Detailed Description
Definition at line 29 of file dialogwaiting.h.
Constructor & Destructor Documentation
DialogWaiting()
DialogWaiting::DialogWaiting (QWidget * parent = nullptr) explicit
DialogWaiting::DialogWaiting.
Parameters
parent
Definition at line 29 of file dialogwaiting.cpp.
References setDetail(), setTitle(), and ui.
Referenced by instance().
~DialogWaiting()
DialogWaiting::~DialogWaiting () override
DialogWaiting::~DialogWaiting.
Definition at line 41 of file dialogwaiting.cpp.
References ui.
Member Function Documentation
dropInstance()
static void DialogWaiting::dropInstance () inline static
Definition at line 54 of file dialogwaiting.h.
References m_static_dialog.
Referenced by QETDiagramEditor::openAndAddProject(), and QETDiagramEditor::openBackupFiles().
hasInstance()
static bool DialogWaiting::hasInstance () inline static
Definition at line 46 of file dialogwaiting.h.
References m_static_dialog.
Referenced by ProjectView::loadDiagrams(), and QETProject::readDiagramsXml().
instance()
static DialogWaiting* DialogWaiting::instance (QWidget * parent = nullptr) inline static
Definition at line 33 of file dialogwaiting.h.
References DialogWaiting(), and m_static_dialog.
Referenced by ProjectView::loadDiagrams(), QETDiagramEditor::openAndAddProject(), QETDiagramEditor::openBackupFiles(), and QETProject::readDiagramsXml().
progressBarValue()
int DialogWaiting::progressBarValue () const
DialogWaiting::progressBarValue.
Returns
The current vcalue of the progress bar
Definition at line 91 of file dialogwaiting.cpp.
References ui.
Referenced by ProjectView::loadDiagrams(), and QETProject::readDiagramsXml().
setDetail()
void DialogWaiting::setDetail (const QString & val)
DialogWaiting::setDetail of action.
Parameters
val is the string of detail action
Definition at line 83 of file dialogwaiting.cpp.
References ui.
Referenced by DialogWaiting(), ProjectView::loadDiagrams(), and QETProject::readDiagramsXml().
setProgressBar()
void DialogWaiting::setProgressBar (int val)
DialogWaiting::setProgressBar.
Parameters
val is the progressBar value
Definition at line 49 of file dialogwaiting.cpp.
References ui.
Referenced by ProjectView::loadDiagrams(), and QETProject::readDiagramsXml().
setProgressBarRange()
void DialogWaiting::setProgressBarRange (int min, int max)
DialogWaiting::setProgressBarRange.
Parameters
min is the minimum of progressBar
max is the maximun of progressBar
Definition at line 66 of file dialogwaiting.cpp.
References QET::Icons::tr, and ui.
Referenced by QETProject::readDiagramsXml().
setProgressReset()
void DialogWaiting::setProgressReset ()
DialogWaiting::setProgressReset, clear progressBar and reset.
Definition at line 57 of file dialogwaiting.cpp.
References ui.
setTitle()
void DialogWaiting::setTitle (const QString & val)
DialogWaiting::setTitle of action.
Parameters
val is the string of action
Definition at line 75 of file dialogwaiting.cpp.
References ui.
Referenced by DialogWaiting(), ProjectView::loadDiagrams(), and QETProject::readDiagramsXml().
Member Data Documentation
m_static_dialog
DialogWaiting * DialogWaiting::m_static_dialog = nullptr static private
Definition at line 66 of file dialogwaiting.h.
Referenced by dropInstance(), hasInstance(), and instance().
ui
Ui::DialogWaiting* DialogWaiting::ui private
Definition at line 81 of file dialogwaiting.h.
Referenced by DialogWaiting(), progressBarValue(), setDetail(), setProgressBar(), setProgressBarRange(), setProgressReset(), setTitle(), and ~DialogWaiting().
The documentation for this class was generated from the following files:
dialogwaiting.h
dialogwaiting.cpp