QElectroTech: ElementXmlRetroCompatibility Class Reference
ElementXmlRetroCompatibility Class Reference
Static Private Member Functions
static void loadSequential (const QDomElement &dom_element, const QString &seq, QStringList *list)
static void loadSequential (const QDomElement &dom_element, Element *element)
Friends
class Element
Detailed Description
Definition at line 37 of file element.cpp.
Member Function Documentation
loadSequential() [1/2]
static void ElementXmlRetroCompatibility::loadSequential (const QDomElement & dom_element, const QString & seq, QStringList * list) inline static private
Definition at line 41 of file element.cpp.
Referenced by Element::fromXml(), and loadSequential().
loadSequential() [2/2]
static void ElementXmlRetroCompatibility::loadSequential (const QDomElement & dom_element, Element * element) inline static private
Definition at line 56 of file element.cpp.
References autonum::sequentialNumbers::hundred, autonum::sequentialNumbers::hundred_folio, loadSequential(), Element::rSequenceStruct(), autonum::sequentialNumbers::ten, autonum::sequentialNumbers::ten_folio, autonum::sequentialNumbers::unit, and autonum::sequentialNumbers::unit_folio.
Friends And Related Function Documentation
Element
friend class Element friend
Definition at line 39 of file element.cpp.
The documentation for this class was generated from the following file:
element.cpp