QElectroTech: QETApp Class Reference
QETApp Class Reference
The QETApp class This class represents the QElectroTech application.
#include <qetapp.h>
Public Slots
void systray (QSystemTrayIcon::ActivationReason)
QETApp::systray Manages QSystemTrayIcon related events.
void reduceEveryEditor ()
QETApp::reduceEveryEditor Minimizes all application windows in the systray.
void restoreEveryEditor ()
QETApp::restoreEveryEditor Restores all application windows in the systray.
void reduceDiagramEditors ()
QETApp::reduceDiagramEditors Minimize all schema editors in the systray.
void restoreDiagramEditors ()
QETApp::restoreDiagramEditors Restore all schema editors in the systray.
void reduceElementEditors ()
QETApp::reduceElementEditors Minimize all element editors in systray.
void restoreElementEditors ()
QETApp::restoreElementEditors Restore all element editors in the systray.
void reduceTitleBlockTemplateEditors ()
QETApp::reduceTitleBlockTemplateEditors Reduce all known template editors.
void restoreTitleBlockTemplateEditors ()
QETApp::restoreTitleBlockTemplateEditors Restore all known template editors.
void newDiagramEditor ()
QETApp::newDiagramEditor launches a new schema editor.
void newElementEditor ()
QETApp::newElementEditor launches a new element editor.
bool closeEveryEditor ()
QETApp::closeEveryEditor Close all editors.
void setMainWindowVisible (QMainWindow *, bool)
QETApp::setMainWindowVisible Show or hide a window (schema editors / element editors)
void invertMainWindowVisibility (QWidget *)
QETApp::invertMainWindowVisibility Display a window (schema editors / element editors) if this is hidden or hides it if it is displayed.
void useSystemPalette (bool)
QETApp::useSystemPalette Change the application palette.
void quitQET ()
QETApp::quitQET Request the closing of all windows; if the user accepts them, the application quits.
void checkRemainingWindows ()
QETApp::checkRemainingWindows Check if there are any windows (hidden or not) and exit if there are no more.
void openFiles (const QETArguments &)
QETApp::openFiles Open files passed as arguments.
void openProjectFiles (const QStringList &)
QETApp::openProjectFiles Opens a list of files. Files are opened in the first visible schematic editor. Otherwise, the first existing schema editor becomes visible and is uses. If there is no schematic editor open, a new one is created and uses.
void openElementFiles (const QStringList &)
QETApp::openElementFiles Open the elements files passed in parameter. If an element is already open, the window which edits it is activated.
void openElementLocations (const QList< ElementsLocation > &)
QETApp::openElementLocations Open the elements whose location is passed in parameter. If an element is already open, the window which is edited is active.
void openTitleBlockTemplate (const TitleBlockTemplateLocation &, bool=false)
QETApp::openTitleBlockTemplate Launch a new title block template editor to edit the given template.
void openTitleBlockTemplate (const QString &)
QETApp::openTitleBlockTemplate Launch a new title block template editor to edit the given template.
void openTitleBlockTemplateFiles (const QStringList &)
QETApp::openTitleBlockTemplateFiles Open provided title block template files. If a title block template is already opened, the adequate window is activated.
void configureQET ()
QETApp::configureQET Allows the user to configure QET by launching an appropriate dialog.
void aboutQET ()
QETApp::aboutQET Open the dialog about qet.
void receiveMessage (int instanceId, QByteArray message)
QETApp::receiveMessage openFiles from message.
Public Member Functions
QETApp ()
QETApp::QETApp.
~QETApp () override
QETApp::~QETApp.
void setLanguage (const QString &)
QETApp::setLanguage Change the language used by the application.
void switchLayout (Qt::LayoutDirection)
Static Public Member Functions
static QETApp * instance ()
QETApp::instance.
static QString langFromSetting ()
QETApp::langFromSetting.
static void printHelp ()
QETApp::printHelp Display help and usage on standard output.
static void printVersion ()
QETApp::printVersion Print version to standard output.
static void printLicense ()
QETApp::printLicense Display license on standard output.
static ElementsCollectionCache * collectionCache ()
QETApp::collectionCache.
static QStringList elementInfoKeys ()
QETApp::elementInfoKeys.
static QString elementTranslatedInfoKey (const QString &)
ElementsProperties::translatedInfo Return the translated information key given by info If info don't match, return an empty string.
static QString elementInfoToVar (const QString &info)
QETApp::elementInfoToVar.
static QStringList conductorInfoKeys ()
QETApp::conductorInfoKeys.
static QString conductorTranslatedInfoKey (const QString &key)
QETApp::conductorTranslatedInfoKey.
static QStringList diagramInfoKeys ()
QETApp::diagramInfoKeys.
static QString diagramTranslatedInfoKey (const QString &key)
QETApp::diagramTranslatedInfoKey.
static TitleBlockTemplatesFilesCollection * commonTitleBlockTemplatesCollection ()
QETApp::commonTitleBlockTemplatesCollection.
static TitleBlockTemplatesFilesCollection * customTitleBlockTemplatesCollection ()
QETApp::customTitleBlockTemplatesCollection.
static QList< TitleBlockTemplatesCollection * > availableTitleBlockTemplatesCollections ()
QETApp::availableTitleBlockTemplatesCollections.
static TitleBlockTemplatesCollection * titleBlockTemplatesCollection (const QString &)
QETApp::titleBlockTemplatesCollection.
static QString commonElementsDir ()
QETApp::commonElementsDir.
static QString customElementsDir ()
QETApp::customElementsDir.
static QString commonElementsDirN ()
QETApp::commonElementsDirN like QString QETApp::commonElementsDir but without "/" at the end.
static QString customElementsDirN ()
QETApp::customElementsDirN like QString QETApp::customElementsDir but without "/" at the end.
static void resetUserElementsDir ()
QETApp::resetUserElementsDir Reset the path of the user common and custom elements dir. Use this function when the user path (common and/or custom) change.
static QString commonTitleBlockTemplatesDir ()
QETApp::commonTitleBlockTemplatesDir.
static QString customTitleBlockTemplatesDir ()
QETApp::customTitleBlockTemplatesDir.
static bool registerProject (QETProject *)
QETApp::registerProject.
static bool unregisterProject (QETProject *)
QETApp::unregisterProject Cancel the recording of the project project.
static QMap< uint, QETProject * > registeredProjects ()
QETApp::registeredProjects.
static QETProject * project (const uint &)
QETApp::project.
static int projectId (const QETProject *)
QETApp::projectId.
static QString configDir ()
QETApp::configDir Return the QET configuration folder, i.e. the path to the folder in which QET will read configuration and customization information specific to the current user. This file is generally C:\Documents And Settings\user\Application Data\ qet on Windows and ~/.qet under UNIX-like systems.
static QString languagesPath ()
QETApp::languagesPath.
static QString realPath (const QString &)
QETApp::realPath Allows you to know the absolute path of the * .elmt file corresponding to a symbolic path (of the type custom: // tools_pervers / sado_maso / contact_bizarre)
static QString symbolicPath (const QString &)
QETApp::symbolicPath Build the symbolic path (of the type custom: // tools_pervers / sado_maso / contact_bizarre) corresponding to a file.
static QStringList handledFileExtensions ()
QETApp::handledFileExtensions.
static QStringList handledFiles (const QList< QUrl > &)
QETApp::handledFiles.
static RecentFiles * projectsRecentFiles ()
QETApp::projectsRecentFiles.
static RecentFiles * elementsRecentFiles ()
QETApp::elementsRecentFiles.
static void overrideLangDir (const QString &)
QETApp::overrideLangDir Redefines the path of the folder containing the language files.
static QFont diagramTextsFont (qreal=-1.0)
QETApp::diagramTextsFont The font to use By default the font is "sans Serif" and size 9.
static QFont diagramTextsItemFont (qreal=-1.0)
QETApp::diagramTextsItemFont the font for to use in independent text item.
static QFont dynamicTextsItemFont (qreal=-1.0)
QETApp::dynamicTextsFont the default font of dynamic element text item.
static QFont indiTextsItemFont (qreal=-1.0)
QETApp::indiTextsItemFont The default font to use for independent text item.
static QETDiagramEditor * diagramEditorForFile (const QString &)
QETApp::diagramEditorForFile.
static QETDiagramEditor * diagramEditorAncestorOf (const QWidget *child)
QETApp::diagramEditorAncestorOf.
static QList< QETDiagramEditor * > diagramEditors ()
QETApp::diagramEditors.
static QList< QETElementEditor * > elementEditors ()
QETApp::elementEditors.
static QList< QETElementEditor * > elementEditors (QETProject *)
QETApp::elementEditors.
static QList< QETTitleBlockTemplateEditor * > titleBlockTemplateEditors ()
QETApp::titleBlockTemplateEditors.
static QList< QETTitleBlockTemplateEditor * > titleBlockTemplateEditors (QETProject *)
QETApp::titleBlockTemplateEditors.
static QTextOrientationSpinBoxWidget * createTextOrientationSpinBoxWidget ()
QETApp::createTextOrientationSpinBoxWidget Instantiates a QTextOrientationSpinBoxWidget and configures:
static TitleBlockTemplate * defaultTitleBlockTemplate ()
QETApp::defaultTitleBlockTemplate.
Static Public Attributes
static QString lang_dir = QString()
lang_dir Directory containing localization files.
Private Member Functions
QETApp (const QETApp &)
template<class T >
QList< T * > detectWindows () const
template<class T >
void setMainWindowsVisible (bool)
QList< QWidget * > floatingToolbarsAndDocksForMainWindow (QMainWindow *) const
QETApp::floatingToolbarsAndDocksForMainWindow.
void parseArguments ()
QETApp::parseArguments Parse the following arguments:
void initSplashScreen ()
QETApp::initSplashScreen Initializes the splash screen if and only if the execution is interactive. Otherwise, the splash_screen_ attribute is 0.
void setSplashScreenStep (const QString &=QString())
QETApp::setSplashScreenStep Changes the text of the splash screen and takes events into account. If the application is running non-interactively, this method does nothing.
void initLanguage ()
QETApp::initLanguage Determine and apply the language to use for the application.
void initStyle ()
QETApp::initStyle Setup the gui style.
void initConfiguration ()
QETApp::initConfiguration Reads and takes into account the configuration of the application. This method will create, if necessary:
void initSystemTray ()
QETApp::initSystemTray Build the icon in the systray and its menu.
void buildSystemTrayMenu ()
QETApp::buildSystemTrayMenu builds the icon menu in the systray.
void checkBackupFiles ()
QETApp::checkBackupFiles Check for backup files. If backup was found, open a dialog and ask user what to do.
void fetchWindowStats (const QList< QETDiagramEditor * > &, const QList< QETElementEditor * > &, const QList< QETTitleBlockTemplateEditor * > &)
QETApp::fetchWindowStats Updates the booleans concerning the state of the windows.
template<class T >
void addWindowsListToMenu (QMenu *, const QList< T * > &)
Static Private Member Functions
static int projectIdFromString (const QString &)
QETApp::projectIdFromString.
static QETProject * projectFromString (const QString &)
QETApp::projectFromString.
Private Attributes
QTranslator qtTranslator
QTranslator qetTranslator
QSystemTrayIcon * m_qsti
QSplashScreen * m_splash_screen
QMenu * menu_systray
QAction * quitter_qet
QAction * reduce_appli
QAction * restore_appli
QAction * reduce_diagrams
QAction * restore_diagrams
QAction * reduce_elements
QAction * restore_elements
QAction * reduce_templates
QAction * restore_templates
QAction * new_diagram
QAction * new_element
QHash< QMainWindow *, QByteArray > window_geometries
QHash< QMainWindow *, QByteArray > window_states
bool every_editor_reduced
bool every_diagram_reduced
bool every_diagram_visible
bool every_element_reduced
bool every_element_visible
bool every_template_reduced
bool every_template_visible
QSignalMapper signal_map
QETArguments qet_arguments_
Comand-line arguments parser.
bool non_interactive_execution_
non_interactive_execution_ Whether the application will end without any user interaction
QPalette initial_palette_
System color palette.
Static Private Attributes
static QETApp * m_qetapp = nullptr
static TitleBlockTemplatesFilesCollection * m_common_tbt_collection
static TitleBlockTemplatesFilesCollection * m_custom_tbt_collection
static ElementsCollectionCache * collections_cache_ = nullptr
static QMap< uint, QETProject * > registered_projects_ = QMap<uint, QETProject *>()
static uint next_project_id = 0
static RecentFiles * m_projects_recent_files = nullptr
static RecentFiles * m_elements_recent_files = nullptr
static TitleBlockTemplate * default_titleblock_template_ = nullptr
static QString m_user_common_elements_dir = QString()
static QString m_user_custom_elements_dir = QString()
static QString m_user_custom_tbt_dir = QString()
Detailed Description
The QETApp class This class represents the QElectroTech application.
Definition at line 54 of file qetapp.h.
Constructor & Destructor Documentation
QETApp() [1/2]
QETApp::QETApp ()
QETApp::QETApp.
Definition at line 73 of file qetapp.cpp.
References buildSystemTrayMenu(), checkBackupFiles(), checkRemainingWindows(), collections_cache_, configDir(), QETArguments::files(), initConfiguration(), QET::Icons::initIcons(), initLanguage(), initSplashScreen(), initStyle(), initSystemTray(), invertMainWindowVisibility(), langFromSetting(), m_qetapp, m_splash_screen, non_interactive_execution_, openFiles(), parseArguments(), qet_arguments_, ElementsCollectionCache::setLocale(), setSplashScreenStep(), signal_map, and QET::Icons::tr.
~QETApp()
QETApp::~QETApp () override
QETApp::~QETApp.
Definition at line 128 of file qetapp.cpp.
References ElementFactory::dropInstance(), ElementPictureFactory::dropInstance(), m_common_tbt_collection, m_custom_tbt_collection, m_elements_recent_files, m_projects_recent_files, m_qsti, m_splash_screen, and RecentFiles::save().
QETApp() [2/2]
QETApp::QETApp (const QETApp &) private
Member Function Documentation
aboutQET
void QETApp::aboutQET () slot
QETApp::aboutQET Open the dialog about qet.
Definition at line 1775 of file qetapp.cpp.
addWindowsListToMenu()
template<class T > void QETApp::addWindowsListToMenu (QMenu * menu, const QList< T * > & windows) private
Add a list of windows to menu. This template function assumes it will be given a QList of pointers to objects inheriting the QMainWindow class. T the class inheriting QMainWindow
Parameters
menu the menu windows will be added to
windows A list of top-level windows.
Definition at line 2055 of file qetapp.cpp.
References signal_map.
availableTitleBlockTemplatesCollections()
QList< TitleBlockTemplatesCollection * > QETApp::availableTitleBlockTemplatesCollections () static
QETApp::availableTitleBlockTemplatesCollections.
Returns
the list of all available title block tempaltes collections, beginning with the common and custom ones, plus the projects-embedded ones.
Definition at line 560 of file qetapp.cpp.
References commonTitleBlockTemplatesCollection(), customTitleBlockTemplatesCollection(), and registered_projects_.
Referenced by TitleBlockTemplateLocationChooser::updateCollections().
buildSystemTrayMenu()
void QETApp::buildSystemTrayMenu () private
QETApp::buildSystemTrayMenu builds the icon menu in the systray.
Definition at line 2104 of file qetapp.cpp.
References diagramEditors(), elementEditors(), every_diagram_reduced, every_diagram_visible, every_editor_reduced, every_element_reduced, every_element_visible, every_template_reduced, every_template_visible, fetchWindowStats(), menu_systray, new_diagram, new_element, quitter_qet, reduce_appli, reduce_diagrams, reduce_elements, reduce_templates, restore_appli, restore_diagrams, restore_elements, restore_templates, titleBlockTemplateEditors(), and QET::Icons::tr.
Referenced by QETApp(), and systray().
checkBackupFiles()
void QETApp::checkBackupFiles () private
QETApp::checkBackupFiles Check for backup files. If backup was found, open a dialog and ask user what to do.
Definition at line 2160 of file qetapp.cpp.
References QET::Icons::Cancel, diagramEditors(), QETProject::filePath(), QETDiagramEditor::openBackupFiles(), project(), QET::QetMessageBox::question(), registeredProjects(), and QET::Icons::tr.
Referenced by QETApp().
checkRemainingWindows
void QETApp::checkRemainingWindows () slot
QETApp::checkRemainingWindows Check if there are any windows (hidden or not) and exit if there are no more.
Definition at line 1489 of file qetapp.cpp.
References diagramEditors(), and elementEditors().
Referenced by QETApp().
closeEveryEditor
bool QETApp::closeEveryEditor () slot
QETApp::closeEveryEditor Close all editors.
Returns
true if the user has accepted all closures, false otherwise
Definition at line 1087 of file qetapp.cpp.
References diagramEditors(), elementEditors(), project(), registered_projects_, and restoreEveryEditor().
Referenced by quitQET().
collectionCache()
ElementsCollectionCache * QETApp::collectionCache () static
QETApp::collectionCache.
Returns
the collection cache provided by the application itself.
Definition at line 358 of file qetapp.cpp.
References collections_cache_.
Referenced by ElementsLocation::icon().
commonElementsDir()
QString QETApp::commonElementsDir () static
QETApp::commonElementsDir.
Returns
the dir path of the common elements collection.
Definition at line 598 of file qetapp.cpp.
References m_user_common_elements_dir, and QUOTE.
Referenced by commonElementsDirN(), autonum::elementPrefixForLocation(), realPath(), and symbolicPath().
commonElementsDirN()
QString QETApp::commonElementsDirN () static
QETApp::commonElementsDirN like QString QETApp::commonElementsDir but without "/" at the end.
Returns
QString path
Definition at line 693 of file qetapp.cpp.
References commonElementsDir().
Referenced by ElementsCollectionModel::addCommonCollection(), FileElementCollectionItem::collectionPath(), FileElementCollectionItem::isCollectionRoot(), FileElementCollectionItem::isCommonCollection(), ElementsLocation::isCommonCollection(), ElementsLocation::isWritable(), FileElementCollectionItem::localName(), ElementsLocation::setPath(), and FileElementCollectionItem::setUpIcon().
commonTitleBlockTemplatesCollection()
TitleBlockTemplatesFilesCollection * QETApp::commonTitleBlockTemplatesCollection () static
QETApp::commonTitleBlockTemplatesCollection.
Returns
the common title block templates collection, i.e. the one provided by QElecrotTech
Definition at line 521 of file qetapp.cpp.
References QET::Common, commonTitleBlockTemplatesDir(), m_common_tbt_collection, QETAPP_COMMON_TBT_PROTOCOL, and QET::Icons::tr.
Referenced by availableTitleBlockTemplatesCollections(), NewDiagramPage::NewDiagramPage(), ElementsPanel::reload(), and QETProject::setDefaultTitleBlockProperties().
commonTitleBlockTemplatesDir()
QString QETApp::commonTitleBlockTemplatesDir () static
QETApp::commonTitleBlockTemplatesDir.
Returns
the path of the directory containing the common title block templates collection.
Definition at line 729 of file qetapp.cpp.
References QUOTE.
Referenced by commonTitleBlockTemplatesCollection(), and realPath().
conductorInfoKeys()
QStringList QETApp::conductorInfoKeys () static
QETApp::conductorInfoKeys.
Returns
the conductor information keys
Definition at line 446 of file qetapp.cpp.
Referenced by replaceAdvancedDialog::fillWhatComboBox().
conductorTranslatedInfoKey()
QString QETApp::conductorTranslatedInfoKey (const QString & key) static
QETApp::conductorTranslatedInfoKey.
Parameters
key
Returns
the translated information key given by key If key don't match, return an empty string
Definition at line 465 of file qetapp.cpp.
References QET::Icons::tr.
Referenced by replaceAdvancedDialog::fillWhatComboBox().
configDir()
QString QETApp::configDir () static
QETApp::configDir Return the QET configuration folder, i.e. the path to the folder in which QET will read configuration and customization information specific to the current user. This file is generally C:\Documents And Settings\user\Application Data\ qet on Windows and ~/.qet under UNIX-like systems.
Returns
The path of the QElectroTech configuration folder
Definition at line 805 of file qetapp.cpp.
Referenced by ImportElementTextPattern::apply(), customElementsDir(), customTitleBlockTemplatesDir(), delete_old_log_files(), ExportElementTextPattern::ExportElementTextPattern(), SummaryQueryWidget::fillSavedQuery(), AddTableDialog::fillSavedQuery(), ElementQueryWidget::fillSavedQuery(), ImportElementTextPattern::ImportElementTextPattern(), initConfiguration(), SummaryQueryWidget::loadConfig(), AddTableDialog::loadConfig(), myMessageOutput(), ElementQueryWidget::on_m_load_pb_clicked(), ElementQueryWidget::on_m_save_current_conf_pb_clicked(), QETApp(), SummaryQueryWidget::saveConfig(), AddTableDialog::saveConfig(), and useSystemPalette().
configureQET
void QETApp::configureQET () slot
QETApp::configureQET Allows the user to configure QET by launching an appropriate dialog.
See also
ConfigDialog
Definition at line 1744 of file qetapp.cpp.
References ConfigDialog::addPage(), and QET::Icons::tr.
Referenced by QETMainWindow::initCommonActions().
createTextOrientationSpinBoxWidget()
QTextOrientationSpinBoxWidget * QETApp::createTextOrientationSpinBoxWidget () static
QETApp::createTextOrientationSpinBoxWidget Instantiates a QTextOrientationSpinBoxWidget and configures:
his font
his strings
Note
that the deletion of the widget thus allocated is the responsibility of the caller.
Returns
See also
QTextOrientationSpinBoxWidget
Definition at line 1272 of file qetapp.cpp.
References diagramTextsFont(), and QET::Icons::tr.
Referenced by ConductorPropertiesWidget::initWidget(), and RotateTextsCommand::openDialog().
customElementsDir()
QString QETApp::customElementsDir () static
QETApp::customElementsDir.
Returns
the dir path of user elements collection ened by a "/" separator
Definition at line 657 of file qetapp.cpp.
References configDir(), and m_user_custom_elements_dir.
Referenced by customElementsDirN(), autonum::elementPrefixForLocation(), QETElementEditor::getOpenElementFileName(), initConfiguration(), realPath(), QETElementEditor::slot_openFile(), QETElementEditor::slot_saveAsFile(), and symbolicPath().
customElementsDirN()
QString QETApp::customElementsDirN () static
QETApp::customElementsDirN like QString QETApp::customElementsDir but without "/" at the end.
Returns
QString path
Definition at line 705 of file qetapp.cpp.
References customElementsDir().
Referenced by ElementsCollectionModel::addCustomCollection(), FileElementCollectionItem::isCollectionRoot(), FileElementCollectionItem::isCustomCollection(), ElementsLocation::isCustomCollection(), FileElementCollectionItem::localName(), and ElementsLocation::setPath().
customTitleBlockTemplatesCollection()
TitleBlockTemplatesFilesCollection * QETApp::customTitleBlockTemplatesCollection () static
QETApp::customTitleBlockTemplatesCollection.
Returns
the custom title block templates collection, i.e. the one managed by the end user
Definition at line 541 of file qetapp.cpp.
References QET::Custom, customTitleBlockTemplatesDir(), m_custom_tbt_collection, QETAPP_CUSTOM_TBT_PROTOCOL, and QET::Icons::tr.
Referenced by availableTitleBlockTemplatesCollections(), NewDiagramPage::NewDiagramPage(), ElementsPanel::reload(), and QETProject::setDefaultTitleBlockProperties().
customTitleBlockTemplatesDir()
QString QETApp::customTitleBlockTemplatesDir () static
QETApp::customTitleBlockTemplatesDir.
Returns
the path of the directory containing the custom title block templates collection.
Definition at line 758 of file qetapp.cpp.
References configDir(), and m_user_custom_tbt_dir.
Referenced by customTitleBlockTemplatesCollection(), initConfiguration(), QETTitleBlockTemplateEditor::openFromFile(), realPath(), and QETTitleBlockTemplateEditor::saveAsFile().
defaultTitleBlockTemplate()
TitleBlockTemplate * QETApp::defaultTitleBlockTemplate () static
QETApp::defaultTitleBlockTemplate.
Returns
the default titleblock template for diagrams
Definition at line 1294 of file qetapp.cpp.
References default_titleblock_template_, instance(), and QET::TitleBlockTemplate.
Referenced by BorderTitleBlock::BorderTitleBlock(), QETTitleBlockTemplateEditor::edit(), and BorderTitleBlock::titleBlockTemplateRemoved().
detectWindows()
template<class T > QList< T * > QETApp::detectWindows private
Parameters
T a class inheriting QMainWindow
Returns
the list of windows of type T
Definition at line 1360 of file qetapp.cpp.
diagramEditorAncestorOf()
QETDiagramEditor * QETApp::diagramEditorAncestorOf (const QWidget * child) static
QETApp::diagramEditorAncestorOf.
Parameters
child
Returns
the parent QETDiagramEditor (or grandparent and so on to any level) of the given child. If not return nullptr;
Definition at line 961 of file qetapp.cpp.
References diagramEditors().
Referenced by ElementsCollectionWidget::leaveEvent(), and ElementsCollectionWidget::setUpConnection().
diagramEditorForFile()
QETDiagramEditor * QETApp::diagramEditorForFile (const QString & filepath) static
QETApp::diagramEditorForFile.
Parameters
filepath : A file path
Note
if filepath is an empty string, this method returns 0.
Returns
the QETDiagramEditor editing the filepath file, or 0 if this file is not edited by the application.
Definition at line 940 of file qetapp.cpp.
References diagramEditors(), and instance().
Referenced by QETDiagramEditor::openAndAddProject().
diagramEditors()
QList< QETDiagramEditor * > QETApp::diagramEditors () static
QETApp::diagramEditors.
Returns
schema editors
Definition at line 1214 of file qetapp.cpp.
References instance().
Referenced by buildSystemTrayMenu(), checkBackupFiles(), checkRemainingWindows(), closeEveryEditor(), diagramEditorAncestorOf(), diagramEditorForFile(), QETMainWindow::initCommonActions(), openProjectFiles(), and systray().
diagramInfoKeys()
QStringList QETApp::diagramInfoKeys () static
QETApp::diagramInfoKeys.
Returns
the diagram default default information keys
Definition at line 480 of file qetapp.cpp.
Referenced by projectDataBase::addDiagram(), projectDataBase::createDataBase(), replaceAdvancedDialog::fillWhatComboBox(), projectDataBase::populateDiagramInfoTable(), projectDataBase::prepareQuery(), and SummaryQueryWidget::setUpItems().
diagramTextsFont()
QFont QETApp::diagramTextsFont (qreal size = -1.0) static
QETApp::diagramTextsFont The font to use By default the font is "sans Serif" and size 9.
Parameters
size : the size of font
Returns
the font to use
Definition at line 1111 of file qetapp.cpp.
Referenced by CrossRefItem::AddExtraInfo(), createTextOrientationSpinBoxWidget(), BorderTitleBlock::draw(), TitleBlockTemplate::fontForCell(), PartDynamicTextField::fromTextFieldXml(), ElementPictureFactory::parseText(), PartText::PartText(), CrossRefItem::updateLabel(), DynamicElementTextItem::updateXref(), and ElementTextItemGroup::updateXref().
diagramTextsItemFont()
QFont QETApp::diagramTextsItemFont (qreal size = -1.0) static
QETApp::diagramTextsItemFont the font for to use in independent text item.
Parameters
size of font
Returns
Definition at line 1137 of file qetapp.cpp.
Referenced by DiagramTextItem::build(), dynamicTextsItemFont(), and indiTextsItemFont().
diagramTranslatedInfoKey()
QString QETApp::diagramTranslatedInfoKey (const QString & key) static
QETApp::diagramTranslatedInfoKey.
Parameters
key
Returns
the translated information key given by key If key don't match, return an empty string
Definition at line 502 of file qetapp.cpp.
References QET::Icons::tr.
Referenced by replaceAdvancedDialog::fillWhatComboBox(), BOMExportDialog::getBom(), ProjectDBModel::setHeaderString(), and SummaryQueryWidget::setUpItems().
dynamicTextsItemFont()
QFont QETApp::dynamicTextsItemFont (qreal size = -1.0) static
QETApp::dynamicTextsFont the default font of dynamic element text item.
Parameters
size
Returns
dynamic text font with PointSizeF(size)
Definition at line 1169 of file qetapp.cpp.
References diagramTextsItemFont().
Referenced by DynamicElementTextItem::DynamicElementTextItem(), PartDynamicTextField::fromXml(), DynamicElementTextItem::paint(), and PartDynamicTextField::PartDynamicTextField().
elementEditors() [1/2]
QList< QETElementEditor * > QETApp::elementEditors () static
QETApp::elementEditors.
Returns
element editors
Definition at line 1223 of file qetapp.cpp.
References instance().
Referenced by buildSystemTrayMenu(), checkRemainingWindows(), closeEveryEditor(), ElementsCollectionWidget::editElement(), elementEditors(), openElementFiles(), openElementLocations(), systray(), and ProjectView::tryClosingElementEditors().
elementEditors() [2/2]
QList< QETElementEditor * > QETApp::elementEditors (QETProject * project) static
QETApp::elementEditors.
Parameters
project : a project
Returns
element editors editing an element belonging to the QETProject project
Definition at line 1313 of file qetapp.cpp.
References elementEditors(), ElementsLocation::isNull(), ElementsLocation::project(), and project().
elementInfoKeys()
QStringList QETApp::elementInfoKeys () static
QETApp::elementInfoKeys.
Returns
all available key for describe an element
Definition at line 366 of file qetapp.cpp.
Referenced by DynamicTextItemDelegate::availableInfo(), ElementInfoWidget::buildInterface(), ReplaceElementDialog::buildWidget(), projectDataBase::createDataBase(), projectDataBase::elementInfoChanged(), projectDataBase::elementInfoToString(), elementInfoToVar(), DynamicTextFieldEditor::fillInfoComboBox(), replaceAdvancedDialog::fillWhatComboBox(), projectDataBase::prepareQuery(), SearchAndReplaceWorker::replaceElement(), SearchAndReplaceWidget::searchTerms(), CompositeTextEditDialog::setUpComboBox(), and ElementQueryWidget::setUpItems().
elementInfoToVar()
QString QETApp::elementInfoToVar (const QString & info) static
QETApp::elementInfoToVar.
Parameters
info
Returns
var in form %{my-var} corresponding to the info, if there is not available var for the given info the returned var is %{void}
See also
QETApp::elementInfoKeys for list
Definition at line 435 of file qetapp.cpp.
References elementInfoKeys().
Referenced by CompositeTextEditDialog::setUpComboBox().
elementsRecentFiles()
RecentFiles * QETApp::elementsRecentFiles () static
QETApp::elementsRecentFiles.
Returns
The list of recent files for the elements
Definition at line 1395 of file qetapp.cpp.
References m_elements_recent_files.
Referenced by QETElementEditor::fromFile(), QETElementEditor::setupMenus(), and QETElementEditor::slot_saveAsFile().
elementTranslatedInfoKey()
QString QETApp::elementTranslatedInfoKey (const QString & info) static
ElementsProperties::translatedInfo Return the translated information key given by info If info don't match, return an empty string.
Parameters
info the key to be translated
Returns
Definition at line 400 of file qetapp.cpp.
References QET::Icons::tr.
Referenced by ElementInfoWidget::buildInterface(), ReplaceElementDialog::buildWidget(), DynamicTextItemDelegate::createEditor(), DynamicTextFieldEditor::fillInfoComboBox(), replaceAdvancedDialog::fillWhatComboBox(), BOMExportDialog::getBom(), DynamicElementTextModel::itemsForText(), ElementPropertiesEditorWidget::populateTree(), ProjectDBModel::setHeaderString(), CompositeTextEditDialog::setUpComboBox(), ElementQueryWidget::setUpItems(), and DynamicElementTextModel::updateDataFromText().
fetchWindowStats()
void QETApp::fetchWindowStats (const QList< QETDiagramEditor * > & diagrams, const QList< QETElementEditor * > & elements, const QList< QETTitleBlockTemplateEditor * > & tbtemplates) private
QETApp::fetchWindowStats Updates the booleans concerning the state of the windows.
Parameters
diagrams : QList<QETDiagramEditor *>
elements : QList<QETElementEditor *>
tbtemplates : QList<QETTitleBlockTemplateEditor *>
Definition at line 2246 of file qetapp.cpp.
References every_diagram_reduced, every_diagram_visible, every_editor_reduced, every_element_reduced, every_element_visible, every_template_reduced, and every_template_visible.
Referenced by buildSystemTrayMenu(), and systray().
floatingToolbarsAndDocksForMainWindow()
QList< QWidget * > QETApp::floatingToolbarsAndDocksForMainWindow (QMainWindow * window) const private
QETApp::floatingToolbarsAndDocksForMainWindow.
Parameters
window : window where you have to find the toolbars and floating dock
Returns
the window's toolbars and floating dock
Definition at line 1793 of file qetapp.cpp.
Referenced by setMainWindowVisible().
handledFileExtensions()
QStringList QETApp::handledFileExtensions () static
QETApp::handledFileExtensions.
Returns
the list of file extensions QElectroTech is able to open and supposed to handle. Note they are provided with no leading point.
Definition at line 899 of file qetapp.cpp.
References TITLEBLOCKS_FILE_EXTENSION.
Referenced by handledFiles().
handledFiles()
QStringList QETApp::handledFiles (const QList< QUrl > & urls) static
QETApp::handledFiles.
Parameters
urls : URLs list
Returns
the list of filepaths QElectroTech is able to open.
Definition at line 914 of file qetapp.cpp.
References handledFileExtensions().
Referenced by QETMainWindow::dragEnterEvent(), and QETMainWindow::dropEvent().
indiTextsItemFont()
QFont QETApp::indiTextsItemFont (qreal size = -1.0) static
QETApp::indiTextsItemFont The default font to use for independent text item.
Parameters
size
Returns
independent text font with PointSizeF(size)
Definition at line 1193 of file qetapp.cpp.
References diagramTextsItemFont().
Referenced by IndependentTextItem::IndependentTextItem().
initConfiguration()
void QETApp::initConfiguration () private
QETApp::initConfiguration Reads and takes into account the configuration of the application. This method will create, if necessary:
the configuration folder
the folder of the personal collection
the directory for custom title blocks
Definition at line 1950 of file qetapp.cpp.
References configDir(), customElementsDir(), customTitleBlockTemplatesDir(), QET::Icons::Element, m_elements_recent_files, m_projects_recent_files, and QET::Icons::ProjectFile.
Referenced by QETApp().
initLanguage()
void QETApp::initLanguage () private
QETApp::initLanguage Determine and apply the language to use for the application.
Definition at line 1920 of file qetapp.cpp.
References langFromSetting(), and setLanguage().
Referenced by QETApp().
initSplashScreen()
void QETApp::initSplashScreen () private
QETApp::initSplashScreen Initializes the splash screen if and only if the execution is interactive. Otherwise, the splash_screen_ attribute is 0.
Definition at line 1888 of file qetapp.cpp.
References m_splash_screen, non_interactive_execution_, setSplashScreenStep(), and QET::Icons::tr.
Referenced by QETApp().
initStyle()
void QETApp::initStyle () private
QETApp::initStyle Setup the gui style.
Definition at line 1928 of file qetapp.cpp.
References initial_palette_, and useSystemPalette().
Referenced by QETApp().
initSystemTray()
void QETApp::initSystemTray () private
QETApp::initSystemTray Build the icon in the systray and its menu.
Definition at line 1985 of file qetapp.cpp.
References QET::Icons::ApplicationExit, QET::Icons::Hide, m_qsti, menu_systray, new_diagram, new_element, newDiagramEditor(), newElementEditor(), QET::Icons::QETLogo, quitQET(), quitter_qet, reduce_appli, reduce_diagrams, reduce_elements, reduce_templates, reduceDiagramEditors(), reduceElementEditors(), reduceEveryEditor(), reduceTitleBlockTemplateEditors(), QET::Icons::Restore, restore_appli, restore_diagrams, restore_elements, restore_templates, restoreDiagramEditors(), restoreElementEditors(), restoreEveryEditor(), restoreTitleBlockTemplateEditors(), setSplashScreenStep(), systray(), QET::Icons::tr, and QET::Icons::WindowNew.
Referenced by QETApp().
instance()
QETApp * QETApp::instance () static
QETApp::instance.
Returns
the instance of the QETApp
Definition at line 153 of file qetapp.cpp.
References m_qetapp.
Referenced by ElementsPanelWidget::addTitleBlockTemplate(), GeneralConfigurationPage::applyConf(), defaultTitleBlockTemplate(), diagramEditorForFile(), diagramEditors(), QETMainWindow::dropEvent(), TitleBlockPropertiesWidget::duplicateCurrentTitleBlockTemplate(), TitleBlockPropertiesWidget::editCurrentTitleBlockTemplate(), ElementsCollectionWidget::editElement(), QETDiagramEditor::editElementInEditor(), ElementsPanelWidget::editTitleBlockTemplate(), elementEditors(), ElementsPanelWidget::ElementsPanelWidget(), QETMainWindow::initCommonActions(), main(), ElementsCollectionWidget::newElement(), QETTitleBlockTemplateEditor::open(), QETElementEditor::openElement(), QETTitleBlockTemplateEditor::openFromFile(), QETElementEditor::slot_open(), and titleBlockTemplateEditors().
invertMainWindowVisibility
void QETApp::invertMainWindowVisibility (QWidget * window) slot
QETApp::invertMainWindowVisibility Display a window (schema editors / element editors) if this is hidden or hides it if it is displayed.
Parameters
window : window to show / hide
Definition at line 1437 of file qetapp.cpp.
References setMainWindowVisible().
Referenced by QETApp().
langFromSetting()
QString QETApp::langFromSetting () static
QETApp::langFromSetting.
Returns
the langage found in setting file if nothing was found return the system local.
Definition at line 205 of file qetapp.cpp.
Referenced by initLanguage(), NamesList::name(), and QETApp().
languagesPath()
QString QETApp::languagesPath () static
QETApp::languagesPath.
Returns
The path of the folder containing the language files
Definition at line 1047 of file qetapp.cpp.
References lang_dir, and QUOTE.
Referenced by setLanguage().
newDiagramEditor
void QETApp::newDiagramEditor () slot
QETApp::newDiagramEditor launches a new schema editor.
Definition at line 341 of file qetapp.cpp.
Referenced by initSystemTray().
newElementEditor
void QETApp::newElementEditor () slot
QETApp::newElementEditor launches a new element editor.
Definition at line 350 of file qetapp.cpp.
Referenced by initSystemTray().
openElementFiles
void QETApp::openElementFiles (const QStringList & files_list) slot
QETApp::openElementFiles Open the elements files passed in parameter. If an element is already open, the window which edits it is activated.
Parameters
files_list : Files to open
Definition at line 1586 of file qetapp.cpp.
References elementEditors().
Referenced by openFiles().
openElementLocations
void QETApp::openElementLocations (const QList< ElementsLocation > & locations_list) slot
QETApp::openElementLocations Open the elements whose location is passed in parameter. If an element is already open, the window which is edited is active.
Parameters
locations_list : Locations to open
Definition at line 1637 of file qetapp.cpp.
References elementEditors().
Referenced by ElementsCollectionWidget::editElement().
openFiles
void QETApp::openFiles (const QETArguments & args) slot
QETApp::openFiles Open files passed as arguments.
Parameters
args : Object containing arguments; the files
See also
openProjectFiles openElementFiles
Definition at line 1519 of file qetapp.cpp.
References QETArguments::elementFiles(), openElementFiles(), openProjectFiles(), openTitleBlockTemplateFiles(), QETArguments::projectFiles(), and QETArguments::titleBlockTemplateFiles().
Referenced by QETApp(), and receiveMessage().
openProjectFiles
void QETApp::openProjectFiles (const QStringList & files_list) slot
QETApp::openProjectFiles Opens a list of files. Files are opened in the first visible schematic editor. Otherwise, the first existing schema editor becomes visible and is uses. If there is no schematic editor open, a new one is created and uses.
Parameters
files_list : Files to open
Definition at line 1540 of file qetapp.cpp.
References QET::Icons::de, and diagramEditors().
Referenced by openFiles().
openTitleBlockTemplate [1/2]
void QETApp::openTitleBlockTemplate (const QString & filepath) slot
QETApp::openTitleBlockTemplate Launch a new title block template editor to edit the given template.
Parameters
filepath Path of the .titleblock file to be opened
Definition at line 1690 of file qetapp.cpp.
openTitleBlockTemplate [2/2]
void QETApp::openTitleBlockTemplate (const TitleBlockTemplateLocation & location, bool duplicate = false) slot
QETApp::openTitleBlockTemplate Launch a new title block template editor to edit the given template.
Parameters
location location of the title block template to be edited
duplicate if true, the template is opened for duplication, which means the user will be prompter for a new template name.
See also
QETTitleBlockTemplateEditor::setOpenForDuplication()
Definition at line 1677 of file qetapp.cpp.
Referenced by TitleBlockPropertiesWidget::duplicateCurrentTitleBlockTemplate(), TitleBlockPropertiesWidget::editCurrentTitleBlockTemplate(), and openTitleBlockTemplateFiles().
openTitleBlockTemplateFiles
void QETApp::openTitleBlockTemplateFiles (const QStringList & files_list) slot
QETApp::openTitleBlockTemplateFiles Open provided title block template files. If a title block template is already opened, the adequate window is activated.
Parameters
files_list Files to be opened
Definition at line 1703 of file qetapp.cpp.
References openTitleBlockTemplate(), and titleBlockTemplateEditors().
Referenced by openFiles().
overrideLangDir()
void QETApp::overrideLangDir (const QString & new_ld) static
QETApp::overrideLangDir Redefines the path of the folder containing the language files.
Parameters
new_ld : New path of the folder containing the language files
Definition at line 1034 of file qetapp.cpp.
References lang_dir.
Referenced by parseArguments().
parseArguments()
void QETApp::parseArguments () private
QETApp::parseArguments Parse the following arguments:
–common-elements-dir=
–config-dir
–help
–version
-v
–license
The other arguments are normally file paths. If they exist, they are just stored in the arguments_files_ attribute. Otherwise, they are stored in the arguments_options_ attribute.
Definition at line 1833 of file qetapp.cpp.
References QETArguments::langDir(), QETArguments::langDirSpecified(), non_interactive_execution_, overrideLangDir(), printHelp(), QETArguments::printHelpRequested(), printLicense(), QETArguments::printLicenseRequested(), printVersion(), QETArguments::printVersionRequested(), and qet_arguments_.
Referenced by QETApp().
printHelp()
void QETApp::printHelp () static
QETApp::printHelp Display help and usage on standard output.
Definition at line 2306 of file qetapp.cpp.
References QET::Icons::tr.
Referenced by parseArguments().
printLicense()
void QETApp::printLicense () static
QETApp::printLicense Display license on standard output.
Definition at line 2344 of file qetapp.cpp.
References QET::license().
Referenced by parseArguments().
printVersion()
void QETApp::printVersion () static
QETApp::printVersion Print version to standard output.
Definition at line 2335 of file qetapp.cpp.
References QET::displayedVersion.
Referenced by parseArguments().
project()
QETProject * QETApp::project (const uint & id) static
QETApp::project.
Parameters
id : Id of the desired project
Returns
the project corresponds to the id passed in parameter
Definition at line 2416 of file qetapp.cpp.
References registered_projects_.
Referenced by checkBackupFiles(), closeEveryEditor(), elementEditors(), Diagram::fromXml(), projectFromString(), projectId(), registerProject(), ElementsLocation::setPath(), titleBlockTemplateEditors(), titleBlockTemplatesCollection(), and unregisterProject().
projectFromString()
QETProject * QETApp::projectFromString (const QString & url) static private
QETApp::projectFromString.
Parameters
url The location of a collection item (title block template, element, category, ...).
Returns
the project mentionned in the URL, or 0 if none could be found.
Definition at line 2093 of file qetapp.cpp.
References project(), and projectIdFromString().
Referenced by titleBlockTemplatesCollection().
projectId()
int QETApp::projectId (const QETProject * project) static
QETApp::projectId.
Parameters
project : Project whose id we want to retrieve
Returns
the project id as a parameter if it is saved, -1 otherwise
Definition at line 2433 of file qetapp.cpp.
References project(), and registered_projects_.
Referenced by ElementsLocation::projectCollectionPath(), TitleBlockTemplatesProjectCollection::protocol(), registerProject(), TitleBlockTemplatesProjectCollection::title(), ElementsLocation::toString(), Diagram::toXml(), and unregisterProject().
projectIdFromString()
int QETApp::projectIdFromString (const QString & url) static private
QETApp::projectIdFromString.
Parameters
url The location of a collection item (title block template, element, category, ...).
Returns
the id of the project mentionned in the URL, or -1 if none could be found.
Definition at line 2074 of file qetapp.cpp.
Referenced by projectFromString().
projectsRecentFiles()
RecentFiles * QETApp::projectsRecentFiles () static
QETApp::projectsRecentFiles.
Returns
The list of recent files for projects
Definition at line 1386 of file qetapp.cpp.
References m_projects_recent_files.
Referenced by QETDiagramEditor::openAndAddProject(), QETDiagramEditor::save(), QETDiagramEditor::saveAs(), and QETDiagramEditor::setUpMenu().
quitQET
void QETApp::quitQET () slot
QETApp::quitQET Request the closing of all windows; if the user accepts them, the application quits.
Definition at line 1475 of file qetapp.cpp.
References closeEveryEditor().
Referenced by initSystemTray().
realPath()
QString QETApp::realPath (const QString & sym_path) static
QETApp::realPath Allows you to know the absolute path of the * .elmt file corresponding to a symbolic path (of the type custom: // tools_pervers / sado_maso / contact_bizarre)
Parameters
sym_path Character string representing the absolute path of the file
Returns
An empty string in case of error or the absolute path of the * .elmt file.
Definition at line 842 of file qetapp.cpp.
References commonElementsDir(), commonTitleBlockTemplatesDir(), customElementsDir(), customTitleBlockTemplatesDir(), QETAPP_COMMON_TBT_PROTOCOL, and QETAPP_CUSTOM_TBT_PROTOCOL.
Referenced by QETTitleBlockTemplateEditor::isEditing(), and QETElementEditor::isEditing().
receiveMessage
void QETApp::receiveMessage (int instanceId, QByteArray message) slot
QETApp::receiveMessage openFiles from message.
Parameters
instanceId Q_UNUSED
message
Definition at line 1342 of file qetapp.cpp.
References openFiles(), and QET::splitWithSpaces().
Referenced by main().
reduceDiagramEditors
void QETApp::reduceDiagramEditors () slot
QETApp::reduceDiagramEditors Minimize all schema editors in the systray.
Definition at line 288 of file qetapp.cpp.
Referenced by initSystemTray(), and reduceEveryEditor().
reduceElementEditors
void QETApp::reduceElementEditors () slot
QETApp::reduceElementEditors Minimize all element editors in systray.
Definition at line 307 of file qetapp.cpp.
Referenced by initSystemTray(), and reduceEveryEditor().
reduceEveryEditor
void QETApp::reduceEveryEditor () slot
QETApp::reduceEveryEditor Minimizes all application windows in the systray.
Definition at line 264 of file qetapp.cpp.
References every_editor_reduced, reduceDiagramEditors(), reduceElementEditors(), and reduceTitleBlockTemplateEditors().
Referenced by initSystemTray(), and systray().
reduceTitleBlockTemplateEditors
void QETApp::reduceTitleBlockTemplateEditors () slot
QETApp::reduceTitleBlockTemplateEditors Reduce all known template editors.
Definition at line 324 of file qetapp.cpp.
Referenced by initSystemTray(), and reduceEveryEditor().
registeredProjects()
QMap< uint, QETProject * > QETApp::registeredProjects () static
QETApp::registeredProjects.
Returns
the list of projects with their associated ids
Definition at line 2353 of file qetapp.cpp.
References registered_projects_.
Referenced by checkBackupFiles(), and ElementDialog::setUpWidget().
registerProject()
bool QETApp::registerProject (QETProject * project) static
QETApp::registerProject.
Parameters
project : Project to register with the application
Returns
true if the project could be saved, false otherwise Failure to save a project usually means that it is already saved.
Definition at line 2368 of file qetapp.cpp.
References next_project_id, project(), projectId(), and registered_projects_.
Referenced by QETDiagramEditor::addProject().
resetUserElementsDir()
void QETApp::resetUserElementsDir () static
QETApp::resetUserElementsDir Reset the path of the user common and custom elements dir. Use this function when the user path (common and/or custom) change.
Definition at line 717 of file qetapp.cpp.
References m_user_common_elements_dir, m_user_custom_elements_dir, and m_user_custom_tbt_dir.
Referenced by GeneralConfigurationPage::applyConf().
restoreDiagramEditors
void QETApp::restoreDiagramEditors () slot
QETApp::restoreDiagramEditors Restore all schema editors in the systray.
Definition at line 297 of file qetapp.cpp.
Referenced by initSystemTray(), and restoreEveryEditor().
restoreElementEditors
void QETApp::restoreElementEditors () slot
QETApp::restoreElementEditors Restore all element editors in the systray.
Definition at line 316 of file qetapp.cpp.
Referenced by initSystemTray(), and restoreEveryEditor().
restoreEveryEditor
void QETApp::restoreEveryEditor () slot
QETApp::restoreEveryEditor Restores all application windows in the systray.
Definition at line 276 of file qetapp.cpp.
References every_editor_reduced, restoreDiagramEditors(), restoreElementEditors(), and restoreTitleBlockTemplateEditors().
Referenced by closeEveryEditor(), initSystemTray(), and systray().
restoreTitleBlockTemplateEditors
void QETApp::restoreTitleBlockTemplateEditors () slot
QETApp::restoreTitleBlockTemplateEditors Restore all known template editors.
Definition at line 332 of file qetapp.cpp.
Referenced by initSystemTray(), and restoreEveryEditor().
setLanguage()
void QETApp::setLanguage (const QString & desired_language)
QETApp::setLanguage Change the language used by the application.
Parameters
desired_language : wanted language
Definition at line 166 of file qetapp.cpp.
References languagesPath(), qetTranslator, qtTranslator, switchLayout(), and QET::Icons::tr.
Referenced by initLanguage().
setMainWindowsVisible()
template<class T > void QETApp::setMainWindowsVisible (bool visible) private
T a class inheriting QMainWindow
Parameters
visible whether detected main windows should be visible
Definition at line 1375 of file qetapp.cpp.
References setMainWindowVisible().
setMainWindowVisible
void QETApp::setMainWindowVisible (QMainWindow * window, bool visible) slot
QETApp::setMainWindowVisible Show or hide a window (schema editors / element editors)
Parameters
window : window to show / hide
visible : true to display the window, false otherwise
Definition at line 1409 of file qetapp.cpp.
References floatingToolbarsAndDocksForMainWindow(), window_geometries, and window_states.
Referenced by invertMainWindowVisibility(), and setMainWindowsVisible().
setSplashScreenStep()
void QETApp::setSplashScreenStep (const QString & message = QString()) private
QETApp::setSplashScreenStep Changes the text of the splash screen and takes events into account. If the application is running non-interactively, this method does nothing.
Parameters
message : the text of the splash screen
Definition at line 1906 of file qetapp.cpp.
References m_splash_screen.
Referenced by initSplashScreen(), initSystemTray(), and QETApp().
switchLayout()
void QETApp::switchLayout (Qt::LayoutDirection direction)
Switches the application to the provided layout.
Definition at line 217 of file qetapp.cpp.
Referenced by setLanguage().
symbolicPath()
QString QETApp::symbolicPath (const QString & real_path) static
QETApp::symbolicPath Build the symbolic path (of the type custom: // tools_pervers / sado_maso / contact_bizarre) corresponding to a file.
Parameters
real_path : Character string representing the symbolic path of the file
Returns
An empty string in case of error or the path symbolic designating the element.
Definition at line 874 of file qetapp.cpp.
References commonElementsDir(), and customElementsDir().
systray
void QETApp::systray (QSystemTrayIcon::ActivationReason reason) slot
QETApp::systray Manages QSystemTrayIcon related events.
Parameters
reason : reason an integer representing the event on the systray
Definition at line 229 of file qetapp.cpp.
References buildSystemTrayMenu(), diagramEditors(), elementEditors(), every_editor_reduced, fetchWindowStats(), m_qsti, reduceEveryEditor(), restoreEveryEditor(), and titleBlockTemplateEditors().
Referenced by initSystemTray().
titleBlockTemplateEditors() [1/2]
QList< QETTitleBlockTemplateEditor * > QETApp::titleBlockTemplateEditors () static
QETApp::titleBlockTemplateEditors.
Returns
the title block template editors
Definition at line 1231 of file qetapp.cpp.
References instance().
Referenced by buildSystemTrayMenu(), openTitleBlockTemplateFiles(), systray(), titleBlockTemplateEditors(), and ProjectView::tryClosingElementEditors().
titleBlockTemplateEditors() [2/2]
QList< QETTitleBlockTemplateEditor * > QETApp::titleBlockTemplateEditors (QETProject * project) static
QETApp::titleBlockTemplateEditors.
Parameters
project Opened project object.
Returns
the list of title block template editors which are currently editing a template embedded within project.
Definition at line 1241 of file qetapp.cpp.
References project(), and titleBlockTemplateEditors().
titleBlockTemplatesCollection()
TitleBlockTemplatesCollection * QETApp::titleBlockTemplatesCollection (const QString & protocol) static
QETApp::titleBlockTemplatesCollection.
Parameters
protocol Protocol string
Returns
the templates collection matching the provided protocol, or 0 if none could be found
Definition at line 579 of file qetapp.cpp.
References m_common_tbt_collection, m_custom_tbt_collection, project(), projectFromString(), QETAPP_COMMON_TBT_PROTOCOL, and QETAPP_CUSTOM_TBT_PROTOCOL.
Referenced by TitleBlockTemplateLocation::fromString().
unregisterProject()
bool QETApp::unregisterProject (QETProject * project) static
QETApp::unregisterProject Cancel the recording of the project project.
Parameters
project : Project to be unregistered
Returns
true if the cancellation was successful, false otherwise The failure of this method usually means that the project was not saved.
Definition at line 2395 of file qetapp.cpp.
References project(), projectId(), and registered_projects_.
Referenced by QETDiagramEditor::projectWasClosed().
useSystemPalette
void QETApp::useSystemPalette (bool use) slot
QETApp::useSystemPalette Change the application palette.
Parameters
use : true to use the system colors, false to use those of the current theme
Definition at line 1451 of file qetapp.cpp.
References configDir(), and initial_palette_.
Referenced by GeneralConfigurationPage::applyConf(), and initStyle().
Member Data Documentation
collections_cache_
ElementsCollectionCache * QETApp::collections_cache_ = nullptr static private
Definition at line 214 of file qetapp.h.
Referenced by collectionCache(), and QETApp().
default_titleblock_template_
TitleBlockTemplate * QETApp::default_titleblock_template_ = nullptr static private
Definition at line 219 of file qetapp.h.
Referenced by defaultTitleBlockTemplate().
every_diagram_reduced
bool QETApp::every_diagram_reduced private
Definition at line 196 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and fetchWindowStats().
every_diagram_visible
bool QETApp::every_diagram_visible private
Definition at line 197 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and fetchWindowStats().
every_editor_reduced
bool QETApp::every_editor_reduced private
Definition at line 195 of file qetapp.h.
Referenced by buildSystemTrayMenu(), fetchWindowStats(), reduceEveryEditor(), restoreEveryEditor(), and systray().
every_element_reduced
bool QETApp::every_element_reduced private
Definition at line 198 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and fetchWindowStats().
every_element_visible
bool QETApp::every_element_visible private
Definition at line 199 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and fetchWindowStats().
every_template_reduced
bool QETApp::every_template_reduced private
Definition at line 200 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and fetchWindowStats().
every_template_visible
bool QETApp::every_template_visible private
Definition at line 201 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and fetchWindowStats().
initial_palette_
QPalette QETApp::initial_palette_ private
System color palette.
Definition at line 210 of file qetapp.h.
Referenced by initStyle(), and useSystemPalette().
lang_dir
QString QETApp::lang_dir = QString() static
lang_dir Directory containing localization files.
Definition at line 153 of file qetapp.h.
Referenced by languagesPath(), and overrideLangDir().
m_common_tbt_collection
TitleBlockTemplatesFilesCollection * QETApp::m_common_tbt_collection static private
Definition at line 212 of file qetapp.h.
Referenced by commonTitleBlockTemplatesCollection(), titleBlockTemplatesCollection(), and ~QETApp().
m_custom_tbt_collection
TitleBlockTemplatesFilesCollection * QETApp::m_custom_tbt_collection static private
Definition at line 213 of file qetapp.h.
Referenced by customTitleBlockTemplatesCollection(), titleBlockTemplatesCollection(), and ~QETApp().
m_elements_recent_files
RecentFiles * QETApp::m_elements_recent_files = nullptr static private
Definition at line 218 of file qetapp.h.
Referenced by elementsRecentFiles(), initConfiguration(), and ~QETApp().
m_projects_recent_files
RecentFiles * QETApp::m_projects_recent_files = nullptr static private
Definition at line 217 of file qetapp.h.
Referenced by initConfiguration(), projectsRecentFiles(), and ~QETApp().
m_qetapp
QETApp * QETApp::m_qetapp = nullptr static private
Definition at line 176 of file qetapp.h.
Referenced by instance(), and QETApp().
m_qsti
QSystemTrayIcon* QETApp::m_qsti private
Definition at line 179 of file qetapp.h.
Referenced by initSystemTray(), systray(), and ~QETApp().
m_splash_screen
QSplashScreen* QETApp::m_splash_screen private
Definition at line 180 of file qetapp.h.
Referenced by initSplashScreen(), QETApp(), setSplashScreenStep(), and ~QETApp().
m_user_common_elements_dir
QString QETApp::m_user_common_elements_dir = QString() static private
Definition at line 220 of file qetapp.h.
Referenced by commonElementsDir(), and resetUserElementsDir().
m_user_custom_elements_dir
QString QETApp::m_user_custom_elements_dir = QString() static private
Definition at line 221 of file qetapp.h.
Referenced by customElementsDir(), and resetUserElementsDir().
m_user_custom_tbt_dir
QString QETApp::m_user_custom_tbt_dir = QString() static private
Definition at line 222 of file qetapp.h.
Referenced by customTitleBlockTemplatesDir(), and resetUserElementsDir().
menu_systray
QMenu* QETApp::menu_systray private
Definition at line 181 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
new_diagram
QAction* QETApp::new_diagram private
Definition at line 191 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
new_element
QAction* QETApp::new_element private
Definition at line 192 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
next_project_id
uint QETApp::next_project_id = 0 static private
Definition at line 216 of file qetapp.h.
Referenced by registerProject().
non_interactive_execution_
bool QETApp::non_interactive_execution_ private
non_interactive_execution_ Whether the application will end without any user interaction
Definition at line 209 of file qetapp.h.
Referenced by initSplashScreen(), parseArguments(), and QETApp().
qet_arguments_
QETArguments QETApp::qet_arguments_ private
Comand-line arguments parser.
Definition at line 203 of file qetapp.h.
Referenced by parseArguments(), and QETApp().
qetTranslator
QTranslator QETApp::qetTranslator private
Definition at line 178 of file qetapp.h.
Referenced by setLanguage().
qtTranslator
QTranslator QETApp::qtTranslator private
Definition at line 177 of file qetapp.h.
Referenced by setLanguage().
quitter_qet
QAction* QETApp::quitter_qet private
Definition at line 182 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
reduce_appli
QAction* QETApp::reduce_appli private
Definition at line 183 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
reduce_diagrams
QAction* QETApp::reduce_diagrams private
Definition at line 185 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
reduce_elements
QAction* QETApp::reduce_elements private
Definition at line 187 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
reduce_templates
QAction* QETApp::reduce_templates private
Definition at line 189 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
registered_projects_
QMap< uint, QETProject * > QETApp::registered_projects_ = QMap<uint, QETProject *>() static private
Definition at line 215 of file qetapp.h.
Referenced by availableTitleBlockTemplatesCollections(), closeEveryEditor(), project(), projectId(), registeredProjects(), registerProject(), and unregisterProject().
restore_appli
QAction* QETApp::restore_appli private
Definition at line 184 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
restore_diagrams
QAction* QETApp::restore_diagrams private
Definition at line 186 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
restore_elements
QAction* QETApp::restore_elements private
Definition at line 188 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
restore_templates
QAction* QETApp::restore_templates private
Definition at line 190 of file qetapp.h.
Referenced by buildSystemTrayMenu(), and initSystemTray().
signal_map
QSignalMapper QETApp::signal_map private
Definition at line 202 of file qetapp.h.
Referenced by addWindowsListToMenu(), and QETApp().
window_geometries
QHash<QMainWindow *, QByteArray> QETApp::window_geometries private
Definition at line 193 of file qetapp.h.
Referenced by setMainWindowVisible().
window_states
QHash<QMainWindow *, QByteArray> QETApp::window_states private
Definition at line 194 of file qetapp.h.
Referenced by setMainWindowVisible().
The documentation for this class was generated from the following files:
qetapp.h
qetapp.cpp