QElectroTech: ConductorPropertiesWidget Class Reference
ConductorPropertiesWidget Class Reference
#include <conductorpropertieswidget.h>
Public Slots
void updatePreview (bool b=true)
ConductorPropertiesWidget::updatePreview Update the preview for single lien.
Public Member Functions
ConductorPropertiesWidget (QWidget *parent=nullptr)
ConductorPropertiesWidget::ConductorPropertiesWidget Constructor.
ConductorPropertiesWidget (const ConductorProperties &properties, QWidget *parent=nullptr)
ConductorPropertiesWidget::ConductorPropertiesWidget Constructor with properties.
~ConductorPropertiesWidget () override
ConductorPropertiesWidget::~ConductorPropertiesWidget destructor.
void setProperties (const ConductorProperties &properties)
ConductorPropertiesWidget::setProperties Set the properties.
ConductorProperties properties () const
ConductorPropertiesWidget::properties.
void setReadOnly (const bool &ro)
ConductorPropertiesWidget::setReadOnly.
void addAutonumWidget (QWidget *widget)
ConductorPropertiesWidget::addAutonumWidget.
void setHiddenOneTextPerFolio (const bool &hide)
ConductorPropertiesWidget::setHiddenOneTextPerFolio.
void setDisabledShowText (const bool &disable=true)
ConductorPropertiesWidget::setDisabledShowText.
void setHiddenAvailableAutonum (const bool &hide)
ConductorPropertiesWidget::setHiddenAvailableAutonum Hide the label, combo box and push button of available autonum.
QComboBox * autonumComboBox () const
QPushButton * editAutonumPushButton () const
Protected Member Functions
bool event (QEvent *event) override
ConductorPropertiesWidget::event.
Private Slots
void on_m_earth_cb_toggled (bool checked)
ConductorPropertiesWidget::on_m_earth_cb_toggled Update the widget when toggled.
void on_m_neutral_cb_toggled (bool checked)
ConductorPropertiesWidget::on_m_neutral_cb_toggled Update the widget when toggled.
void on_m_update_preview_pb_clicked ()
ConductorPropertiesWidget::on_m_update_preview_pb_clicked Update the preview of single line. m_update_preview_pb is a no used button and hidden, his role is only to centralize signal from various widget to edit single ligne properties, for update the preview.
Private Member Functions
void initWidget ()
ConductorPropertiesWidget::initWidget.
void setConductorType (ConductorProperties::ConductorType type)
ConductorPropertiesWidget::setConductorType Update this widget to the new conductor type.
Private Attributes
Ui::ConductorPropertiesWidget * ui
ConductorProperties m_properties
QTextOrientationSpinBoxWidget * m_verti_select
QTextOrientationSpinBoxWidget * m_horiz_select
Detailed Description
Definition at line 31 of file conductorpropertieswidget.h.
Constructor & Destructor Documentation
ConductorPropertiesWidget() [1/2]
ConductorPropertiesWidget::ConductorPropertiesWidget (QWidget * parent = nullptr) explicit
ConductorPropertiesWidget::ConductorPropertiesWidget Constructor.
Parameters
parent : paretn widget
Definition at line 29 of file conductorpropertieswidget.cpp.
References initWidget(), and ui.
ConductorPropertiesWidget() [2/2]
ConductorPropertiesWidget::ConductorPropertiesWidget (const ConductorProperties & properties, QWidget * parent = nullptr) explicit
ConductorPropertiesWidget::ConductorPropertiesWidget Constructor with properties.
Parameters
properties : properties to edit
parent : parent widget
Definition at line 46 of file conductorpropertieswidget.cpp.
References initWidget(), properties(), setProperties(), and ui.
~ConductorPropertiesWidget()
ConductorPropertiesWidget::~ConductorPropertiesWidget () override
ConductorPropertiesWidget::~ConductorPropertiesWidget destructor.
Definition at line 61 of file conductorpropertieswidget.cpp.
References ui.
Member Function Documentation
addAutonumWidget()
void ConductorPropertiesWidget::addAutonumWidget (QWidget * widget)
ConductorPropertiesWidget::addAutonumWidget.
Parameters
widget
Definition at line 177 of file conductorpropertieswidget.cpp.
References ui.
autonumComboBox()
QComboBox * ConductorPropertiesWidget::autonumComboBox () const
Definition at line 209 of file conductorpropertieswidget.cpp.
References ui.
Referenced by DiagramPropertiesDialog::DiagramPropertiesDialog(), and DiagramPropertiesDialog::editAutonum().
editAutonumPushButton()
QPushButton * ConductorPropertiesWidget::editAutonumPushButton () const
Definition at line 214 of file conductorpropertieswidget.cpp.
References ui.
Referenced by DiagramPropertiesDialog::DiagramPropertiesDialog().
event()
bool ConductorPropertiesWidget::event (QEvent * event) override protected
ConductorPropertiesWidget::event.
Parameters
event
Returns
Definition at line 156 of file conductorpropertieswidget.cpp.
References ui.
initWidget()
void ConductorPropertiesWidget::initWidget () private
ConductorPropertiesWidget::initWidget.
Definition at line 222 of file conductorpropertieswidget.cpp.
References QETApp::createTextOrientationSpinBoxWidget(), m_horiz_select, m_verti_select, QET::Icons::tr, and ui.
Referenced by ConductorPropertiesWidget().
on_m_earth_cb_toggled
void ConductorPropertiesWidget::on_m_earth_cb_toggled (bool checked) private slot
ConductorPropertiesWidget::on_m_earth_cb_toggled Update the widget when toggled.
Parameters
checked
Definition at line 287 of file conductorpropertieswidget.cpp.
References ui.
on_m_neutral_cb_toggled
void ConductorPropertiesWidget::on_m_neutral_cb_toggled (bool checked) private slot
ConductorPropertiesWidget::on_m_neutral_cb_toggled Update the widget when toggled.
Parameters
checked
Definition at line 298 of file conductorpropertieswidget.cpp.
References ui.
on_m_update_preview_pb_clicked
void ConductorPropertiesWidget::on_m_update_preview_pb_clicked () private slot
ConductorPropertiesWidget::on_m_update_preview_pb_clicked Update the preview of single line. m_update_preview_pb is a no used button and hidden, his role is only to centralize signal from various widget to edit single ligne properties, for update the preview.
Definition at line 311 of file conductorpropertieswidget.cpp.
References updatePreview().
properties()
ConductorProperties ConductorPropertiesWidget::properties () const
ConductorPropertiesWidget::properties.
Returns
the edited properties
Definition at line 116 of file conductorpropertieswidget.cpp.
References ConductorProperties::color, ConductorProperties::cond_size, SingleLineProperties::hasGround, SingleLineProperties::hasNeutral, ConductorProperties::horiz_rotate_text, SingleLineProperties::is_pen, ConductorProperties::m_bicolor, ConductorProperties::m_color_2, ConductorProperties::m_dash_size, ConductorProperties::m_formula, ConductorProperties::m_function, m_horiz_select, ConductorProperties::m_horizontal_alignment, ConductorProperties::m_one_text_per_folio, ConductorProperties::m_show_text, ConductorProperties::m_tension_protocol, m_verti_select, ConductorProperties::m_vertical_alignment, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, ConductorProperties::Multi, SingleLineProperties::setPhasesCount(), ConductorProperties::Single, ConductorProperties::singleLineProperties, ConductorProperties::style, ConductorProperties::text, ConductorProperties::text_color, ConductorProperties::text_size, ConductorProperties::type, ui, and ConductorProperties::verti_rotate_text.
Referenced by ConductorPropertiesWidget(), setProperties(), and updatePreview().
setConductorType()
void ConductorPropertiesWidget::setConductorType (ConductorProperties::ConductorType type) private
ConductorPropertiesWidget::setConductorType Update this widget to the new conductor type.
Parameters
type
Definition at line 246 of file conductorpropertieswidget.cpp.
References ConductorProperties::Multi, ConductorProperties::Single, and ui.
Referenced by setProperties().
setDisabledShowText()
void ConductorPropertiesWidget::setDisabledShowText (const bool & disable = true)
ConductorPropertiesWidget::setDisabledShowText.
Parameters
disable
Definition at line 193 of file conductorpropertieswidget.cpp.
References ui.
Referenced by ConductorPropertiesDialog::ConductorPropertiesDialog().
setHiddenAvailableAutonum()
void ConductorPropertiesWidget::setHiddenAvailableAutonum (const bool & hide)
ConductorPropertiesWidget::setHiddenAvailableAutonum Hide the label, combo box and push button of available autonum.
Parameters
hide
Definition at line 202 of file conductorpropertieswidget.cpp.
References ui.
Referenced by ConductorPropertiesDialog::ConductorPropertiesDialog(), and NewDiagramPage::NewDiagramPage().
setHiddenOneTextPerFolio()
void ConductorPropertiesWidget::setHiddenOneTextPerFolio (const bool & hide)
ConductorPropertiesWidget::setHiddenOneTextPerFolio.
Parameters
hide
Definition at line 185 of file conductorpropertieswidget.cpp.
References ui.
setProperties()
void ConductorPropertiesWidget::setProperties (const ConductorProperties & properties)
ConductorPropertiesWidget::setProperties Set the properties.
Parameters
properties
Definition at line 71 of file conductorpropertieswidget.cpp.
References ConductorProperties::color, ConductorProperties::cond_size, SingleLineProperties::hasGround, SingleLineProperties::hasNeutral, ConductorProperties::horiz_rotate_text, SingleLineProperties::isPen(), ConductorProperties::m_bicolor, ConductorProperties::m_color_2, ConductorProperties::m_dash_size, ConductorProperties::m_formula, ConductorProperties::m_function, m_horiz_select, ConductorProperties::m_horizontal_alignment, ConductorProperties::m_one_text_per_folio, m_properties, ConductorProperties::m_show_text, ConductorProperties::m_tension_protocol, m_verti_select, ConductorProperties::m_vertical_alignment, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, SingleLineProperties::phasesCount(), properties(), setConductorType(), ConductorProperties::singleLineProperties, ConductorProperties::style, ConductorProperties::text, ConductorProperties::text_color, ConductorProperties::text_size, ConductorProperties::type, ui, updatePreview(), and ConductorProperties::verti_rotate_text.
Referenced by ConductorPropertiesWidget().
setReadOnly()
void ConductorPropertiesWidget::setReadOnly (const bool & ro)
ConductorPropertiesWidget::setReadOnly.
Parameters
ro if true this widget is disabled
Definition at line 169 of file conductorpropertieswidget.cpp.
References QET::Icons::ro.
updatePreview
void ConductorPropertiesWidget::updatePreview (bool b = true) slot
ConductorPropertiesWidget::updatePreview Update the preview for single lien.
Parameters
b true: update from the value displayed by this widget false: update from the properties given at the constructor of this widget
Definition at line 266 of file conductorpropertieswidget.cpp.
References SingleLineProperties::draw(), QET::Horizontal, m_properties, properties(), ConductorProperties::singleLineProperties, and ui.
Referenced by on_m_update_preview_pb_clicked(), and setProperties().
Member Data Documentation
m_horiz_select
QTextOrientationSpinBoxWidget * ConductorPropertiesWidget::m_horiz_select private
Definition at line 73 of file conductorpropertieswidget.h.
Referenced by initWidget(), properties(), and setProperties().
m_properties
ConductorProperties ConductorPropertiesWidget::m_properties private
Definition at line 72 of file conductorpropertieswidget.h.
Referenced by setProperties(), and updatePreview().
m_verti_select
QTextOrientationSpinBoxWidget* ConductorPropertiesWidget::m_verti_select private
Definition at line 73 of file conductorpropertieswidget.h.
Referenced by initWidget(), properties(), and setProperties().
ui
Ui::ConductorPropertiesWidget* ConductorPropertiesWidget::ui private
Definition at line 71 of file conductorpropertieswidget.h.
Referenced by addAutonumWidget(), autonumComboBox(), ConductorPropertiesWidget(), editAutonumPushButton(), event(), initWidget(), on_m_earth_cb_toggled(), on_m_neutral_cb_toggled(), properties(), setConductorType(), setDisabledShowText(), setHiddenAvailableAutonum(), setHiddenOneTextPerFolio(), setProperties(), updatePreview(), and ~ConductorPropertiesWidget().
The documentation for this class was generated from the following files:
conductorpropertieswidget.h
conductorpropertieswidget.cpp