QElectroTech: DiagramsChooser Class Reference
DiagramsChooser Class Reference
#include <diagramschooser.h>
Public Slots
void updateList ()
Signals
void selectionChanged ()
Public Member Functions
DiagramsChooser (QETProject *, QWidget *=nullptr)
~DiagramsChooser () override
QETProject * project () const
QList< Diagram * > selectedDiagrams () const
QList< Diagram * > nonSelectedDiagrams () const
bool diagramIsSelected (Diagram *const) const
void setSelectedDiagrams (const QList< Diagram * > &, bool=true, bool=true)
void setSelectedAllDiagrams (bool=true)
Private Member Functions
DiagramsChooser (const DiagramsChooser &)
void buildLayout ()
Private Attributes
QETProject * project_
QWidget * widget0_
QVBoxLayout * vlayout0_
QHash< Diagram *, QCheckBox * > diagrams_
Detailed Description
This class provides a widget which allows users to select 0 to n diagrams among those of a particular project.
Definition at line 27 of file diagramschooser.h.
Constructor & Destructor Documentation
DiagramsChooser() [1/2]
DiagramsChooser::DiagramsChooser (QETProject * project, QWidget * parent = nullptr)
Constructeur
Parameters
project Projet dont il faut afficher les schemas
parent QWidget parent de ce widget
Definition at line 27 of file diagramschooser.cpp.
References updateList(), and widget0_.
~DiagramsChooser()
DiagramsChooser::~DiagramsChooser () override
Destructeur
Definition at line 50 of file diagramschooser.cpp.
DiagramsChooser() [2/2]
DiagramsChooser::DiagramsChooser (const DiagramsChooser &) private
Member Function Documentation
buildLayout()
void DiagramsChooser::buildLayout () private
Met en place la disposition du widget
Definition at line 179 of file diagramschooser.cpp.
References vlayout0_, and widget0_.
Referenced by updateList().
diagramIsSelected()
bool DiagramsChooser::diagramIsSelected (Diagram * const diagram) const
Parameters
diagram Un schema cense etre present dans ce widget
Definition at line 90 of file diagramschooser.cpp.
References diagrams_.
nonSelectedDiagrams()
QList< Diagram * > DiagramsChooser::nonSelectedDiagrams () const
Returns
la liste des schemas qui ne sont pas selectionnes
Definition at line 77 of file diagramschooser.cpp.
References diagrams_.
project()
QETProject * DiagramsChooser::project () const
Returns
le projet dont ce widget affiche les schemas
Definition at line 56 of file diagramschooser.cpp.
References project_.
selectedDiagrams()
QList< Diagram * > DiagramsChooser::selectedDiagrams () const
Returns
la liste des schemas selectionnes
Definition at line 63 of file diagramschooser.cpp.
References diagrams_, and project_.
Referenced by updateList().
selectionChanged
void DiagramsChooser::selectionChanged () signal
Referenced by setSelectedAllDiagrams(), setSelectedDiagrams(), and updateList().
setSelectedAllDiagrams()
void DiagramsChooser::setSelectedAllDiagrams (bool select = true)
Selectionne ou deselectionne tous les schemas
Parameters
select true pour selectionne les schemas de la liste, false pour les deselectionner
Definition at line 137 of file diagramschooser.cpp.
References diagrams_, and selectionChanged().
setSelectedDiagrams()
void DiagramsChooser::setSelectedDiagrams (const QList< Diagram * > & diagrams_list, bool select = true, bool reset = true)
Selectionne les schemas contenus dans la liste diagrams_list
Parameters
diagrams_list Liste de schemas a selectionner
select true pour selectionne les schemas de la liste, false pour les deselectionner
reset true pour deselectionner tous les schemas avant de selectionner ceux de la liste
Definition at line 104 of file diagramschooser.cpp.
References diagrams_, and selectionChanged().
updateList
void DiagramsChooser::updateList () slot
Met a jour la liste des schemas du projet
Definition at line 149 of file diagramschooser.cpp.
References buildLayout(), diagrams_, project_, selectedDiagrams(), selectionChanged(), QET::Icons::tr, and vlayout0_.
Referenced by DiagramsChooser().
Member Data Documentation
diagrams_
QHash<Diagram *, QCheckBox *> DiagramsChooser::diagrams_ private
Definition at line 60 of file diagramschooser.h.
Referenced by diagramIsSelected(), nonSelectedDiagrams(), selectedDiagrams(), setSelectedAllDiagrams(), setSelectedDiagrams(), and updateList().
project_
QETProject* DiagramsChooser::project_ private
Definition at line 57 of file diagramschooser.h.
Referenced by project(), selectedDiagrams(), and updateList().
vlayout0_
QVBoxLayout* DiagramsChooser::vlayout0_ private
Definition at line 59 of file diagramschooser.h.
Referenced by buildLayout(), and updateList().
widget0_
QWidget* DiagramsChooser::widget0_ private
Definition at line 58 of file diagramschooser.h.
Referenced by buildLayout(), and DiagramsChooser().
The documentation for this class was generated from the following files:
diagramschooser.h
diagramschooser.cpp