QElectroTech: ImportElementDialog Class Reference
ImportElementDialog Class Reference
#include <importelementdialog.h>
Public Member Functions
ImportElementDialog (QWidget *parent=nullptr)
~ImportElementDialog () override
QET::Action action () const
Private Member Functions
void setUpWidget ()
void setUpConnection ()
Private Attributes
Ui::ImportElementDialog * ui
Detailed Description
Definition at line 28 of file importelementdialog.h.
Constructor & Destructor Documentation
ImportElementDialog()
ImportElementDialog::ImportElementDialog (QWidget * parent = nullptr) explicit
Definition at line 22 of file importelementdialog.cpp.
References setUpWidget(), and ui.
~ImportElementDialog()
ImportElementDialog::~ImportElementDialog () override
Definition at line 30 of file importelementdialog.cpp.
References ui.
Member Function Documentation
action()
QET::Action ImportElementDialog::action () const
Definition at line 35 of file importelementdialog.cpp.
References QET::Abort, QET::Erase, QET::Ignore, QET::Rename, and ui.
Referenced by QETProject::importElement().
setUpConnection()
void ImportElementDialog::setUpConnection () private
setUpWidget()
void ImportElementDialog::setUpWidget () private
Definition at line 43 of file importelementdialog.cpp.
References ui.
Referenced by ImportElementDialog().
Member Data Documentation
ui
Ui::ImportElementDialog* ImportElementDialog::ui private
Definition at line 43 of file importelementdialog.h.
Referenced by action(), ImportElementDialog(), setUpWidget(), and ~ImportElementDialog().
The documentation for this class was generated from the following files:
importelementdialog.h
importelementdialog.cpp