QElectroTech: TextEditor Class Reference
TextEditor Class Reference
#include <texteditor.h>
Public Member Functions
TextEditor (QETElementEditor *editor, PartText *text=nullptr, QWidget *parent=nullptr)
TextEditor::TextEditor Default constructor.
~TextEditor () override
TextEditor::~TextEditor.
void updateForm () override
TextEditor::updateForm Update the gui.
bool setPart (CustomElementPart *part) override
TextEditor::setPart Set the current text to edit. Set part to nullptr to clear the current text.
bool setParts (QList< CustomElementPart * >) override
CustomElementPart * currentPart () const override
TextEditor::currentPart.
QList< CustomElementPart * > currentParts () const override
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
Private Slots
void on_m_font_pb_clicked ()
TextEditor::on_m_font_pb_clicked.
void on_m_color_pb_changed (const QColor &newColor)
TextEditor::on_m_color_pb_changed.
Private Member Functions
void setUpEditConnection ()
TextEditor::setUpEditConnection Setup the connection between the widgets of this editor and the undo command use to apply the change to the edited text.
void setUpChangeConnection (QPointer< PartText > part)
void disconnectChangeConnection ()
void disconnectEditConnection ()
Private Attributes
Ui::TextEditor * ui
QPointer< PartText > m_text
QList< PartText * > m_parts
QList< QMetaObject::Connection > m_edit_connection
QList< QMetaObject::Connection > m_change_connection
Detailed Description
Definition at line 32 of file texteditor.h.
Constructor & Destructor Documentation
TextEditor()
TextEditor::TextEditor (QETElementEditor * editor, PartText * text = nullptr, QWidget * parent = nullptr) explicit
TextEditor::TextEditor Default constructor.
Parameters
editor : the element editor who use this editor
text : the text to edit
parent : the parent widget
Definition at line 31 of file texteditor.cpp.
References setPart(), setUpEditConnection(), ui, and updateForm().
~TextEditor()
TextEditor::~TextEditor () override
TextEditor::~TextEditor.
Definition at line 45 of file texteditor.cpp.
References ui.
Member Function Documentation
currentPart()
CustomElementPart * TextEditor::currentPart () const override virtual
TextEditor::currentPart.
Returns
The current part
Implements ElementItemEditor.
Definition at line 153 of file texteditor.cpp.
References m_text.
currentParts()
QList< CustomElementPart * > TextEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 157 of file texteditor.cpp.
References m_parts.
disconnectChangeConnection()
void TextEditor::disconnectChangeConnection () private
Definition at line 82 of file texteditor.cpp.
References m_change_connection.
Referenced by setPart(), and setParts().
disconnectEditConnection()
void TextEditor::disconnectEditConnection () private
Definition at line 89 of file texteditor.cpp.
References m_edit_connection.
Referenced by setUpEditConnection(), and updateForm().
on_m_color_pb_changed
void TextEditor::on_m_color_pb_changed (const QColor & newColor) private slot
TextEditor::on_m_color_pb_changed.
Parameters
newColor
Definition at line 265 of file texteditor.cpp.
References m_parts, QET::Icons::tr, and ElementItemEditor::undoStack().
on_m_font_pb_clicked
void TextEditor::on_m_font_pb_clicked () private slot
TextEditor::on_m_font_pb_clicked.
Definition at line 239 of file texteditor.cpp.
References m_parts, m_text, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
setPart()
bool TextEditor::setPart (CustomElementPart * part) override virtual
TextEditor::setPart Set the current text to edit. Set part to nullptr to clear the current text.
Parameters
part : part to edit
Returns
if part is a partext or nullptr, else return false
Implements ElementItemEditor.
Definition at line 103 of file texteditor.cpp.
References disconnectChangeConnection(), m_text, setUpChangeConnection(), and updateForm().
Referenced by TextEditor().
setParts()
bool TextEditor::setParts (QList< CustomElementPart * > parts) override virtual
Reimplemented from ElementItemEditor.
Definition at line 122 of file texteditor.cpp.
References disconnectChangeConnection(), m_parts, m_text, setUpChangeConnection(), and updateForm().
setUpChangeConnection()
void TextEditor::setUpChangeConnection (QPointer< PartText > part) private
Definition at line 72 of file texteditor.cpp.
References PartText::colorChanged(), PartText::fontChanged(), m_change_connection, PartText::plainTextChanged(), and updateForm().
Referenced by setPart(), and setParts().
setUpEditConnection()
void TextEditor::setUpEditConnection () private
TextEditor::setUpEditConnection Setup the connection between the widgets of this editor and the undo command use to apply the change to the edited text.
Definition at line 170 of file texteditor.cpp.
References disconnectEditConnection(), m_edit_connection, m_parts, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
Referenced by TextEditor(), and updateForm().
updateForm()
void TextEditor::updateForm () override virtual
TextEditor::updateForm Update the gui.
Implements ElementItemEditor.
Definition at line 53 of file texteditor.cpp.
References disconnectEditConnection(), m_text, setUpEditConnection(), and ui.
Referenced by setPart(), setParts(), setUpChangeConnection(), and TextEditor().
Member Data Documentation
m_change_connection
QList<QMetaObject::Connection> TextEditor::m_change_connection private
Definition at line 60 of file texteditor.h.
Referenced by disconnectChangeConnection(), and setUpChangeConnection().
m_edit_connection
QList<QMetaObject::Connection> TextEditor::m_edit_connection private
Definition at line 59 of file texteditor.h.
Referenced by disconnectEditConnection(), and setUpEditConnection().
m_parts
QList<PartText*> TextEditor::m_parts private
Definition at line 58 of file texteditor.h.
Referenced by currentParts(), on_m_color_pb_changed(), on_m_font_pb_clicked(), setParts(), and setUpEditConnection().
m_text
QPointer<PartText> TextEditor::m_text private
Definition at line 57 of file texteditor.h.
Referenced by currentPart(), on_m_font_pb_clicked(), setPart(), setParts(), and updateForm().
ui
Ui::TextEditor* TextEditor::ui private
Definition at line 55 of file texteditor.h.
Referenced by on_m_font_pb_clicked(), setUpEditConnection(), TextEditor(), updateForm(), and ~TextEditor().
The documentation for this class was generated from the following files:
texteditor.h
texteditor.cpp