QElectroTech: Element Class Reference
Element Class Reference
#include <element.h>
Public Types
enum kind {
Simple = 1, NextReport = 2, PreviousReport = 4, AllReport = 6,
Master = 8, Slave = 16, Terminale = 32
}
The kind enum Used to know the kind of this element (master, slave, report ect...)
enum { Type = UserType + 1000 }
Signals
void linkedElementChanged ()
void elementInfoChange (DiagramContext old_info, DiagramContext new_info)
void textAdded (DynamicElementTextItem *deti)
void textRemoved (DynamicElementTextItem *deti)
void textsGroupAdded (ElementTextItemGroup *group)
void textsGroupAboutToBeRemoved (ElementTextItemGroup *group)
void textAddedToGroup (DynamicElementTextItem *text, ElementTextItemGroup *group)
void textRemovedFromGroup (DynamicElementTextItem *text, ElementTextItemGroup *group)
Public Member Functions
Element (const ElementsLocation &location, QGraphicsItem *=nullptr, int *state=nullptr, Element::kind link_type=Element::Simple)
Element::Element.
~Element () override
Element::~Element.
int type () const override
QList< Terminal * > terminals () const
Element::terminals.
QList< Conductor * > conductors () const
Element::conductors.
QList< QPair< Terminal *, Terminal * > > AlignedFreeTerminals () const
Element::AlignedFreeTerminals.
DiagramContext elementInformations () const
virtual void setElementInformations (DiagramContext dc)
Element::setElementInformations Set new information for this element. If new information is different of current infotmation emit elementInfoChange.
DiagramContext kindInformations () const
autonum::sequentialNumbers sequenceStruct () const
autonum::sequentialNumbers & rSequenceStruct ()
void setUpFormula (bool code_letter=true)
Element::setUpFormula Set up the formula used to create the label of this element.
void setPrefix (QString)
Element::setPrefix set Element Prefix.
QString getPrefix () const
Element::getPrefix get Element Prefix.
void freezeLabel (bool freeze)
Element::freezeLabel Freeze this element label.
bool isFreezeLabel () const
void freezeNewAddedElement ()
Element::freezeNewAddedElement Freeze this label if needed.
QString actualLabel ()
Element::actualLabel Always return the current label to be displayed. This function is usefull when label is based on formula, because label can change at any time.
QString name () const override
Element::name.
ElementsLocation location () const
virtual void setHighlighted (bool)
void displayHelpLine (bool b=true)
Element::displayHelpLine Display the help line of each terminal if b is true.
QSize size () const
QPixmap pixmap ()
Element::pixmap.
QPoint setHotspot (QPoint)
QPoint hotspot () const
void editProperty () override
virtual bool fromXml (QDomElement &, QHash< int, Terminal * > &, bool=false)
Element::fromXml Import the parameters of this element from a xml document. When call this function ensure this element is already in a scene, because the dynamic text item and element text item group (in the xml file) are created in this function and need a diagram for create their Xref, when this element is linked to another. If not the Xref can be not displayed, until the next call of update Xref of the group or text item.
virtual QDomElement toXml (QDomDocument &, QHash< Terminal *, int > &) const
Element::toXml Allows to export the element in XML.
QUuid uuid () const
Element::uuid.
int orientation () const
void addDynamicTextItem (DynamicElementTextItem *deti=nullptr)
Element::addDynamiqueTextItem Add deti as a dynamic text item of this element, deti is reparented to this If deti is null, a new DynamicElementTextItem is created and added to this element.
void removeDynamicTextItem (DynamicElementTextItem *deti)
Element::removeDynamicTextItem Remove deti, no matter if is a child of this element or a child of a group of this element. Set he parent item of deti to 0, deti is not deleted.
QList< DynamicElementTextItem * > dynamicTextItems () const
Element::dynamicTextItems.
ElementTextItemGroup * addTextGroup (const QString &name)
Element::addTextGroup Create and add an element text item group to this element. If this element already have a group with the same name, then name will renamed to name1 or name2 etc....
void addTextGroup (ElementTextItemGroup *group)
Element::addTextGroup.
void removeTextGroup (ElementTextItemGroup *group)
Element::removeTextGroup Remove the text group group from this element, and set the parent of group to 0. group is not deleted. All texts owned by the group will be reparented to this element.
ElementTextItemGroup * textGroup (const QString &name) const
Element::textGroup.
QList< ElementTextItemGroup * > textGroups () const
Element::textGroups.
bool addTextToGroup (DynamicElementTextItem *text, ElementTextItemGroup *group)
Element::addTextToGroup Add the text text to the group group; If group isn't owned by this element return false. The text must be a text of this element.
bool removeTextFromGroup (DynamicElementTextItem *text, ElementTextItemGroup *group)
Element::removeTextFromGroup Remove the text text from the group group, en reparent text to this element.
bool isFree () const
virtual void linkToElement (Element *)
virtual void unlinkAllElements ()
virtual void unlinkElement (Element *)
virtual void initLink (QETProject *)
Element::initLink Initialise the link between this element and other elements. This method can be call once because init the link according to uuid store in a private list, after link, the list is clear, so call another time do nothing.
QList< Element * > linkedElements ()
Element::linkedElements.
virtual kind linkType () const
QString linkTypeToString () const
void newUuid ()
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *) override
Element::paint.
QRectF boundingRect () const override
Public Member Functions inherited from QetGraphicsItem
QetGraphicsItem (QGraphicsItem *parent=nullptr)
QetGraphicsItem::QetGraphicsItem Default constructor.
~QetGraphicsItem () override=0
Diagram * diagram () const
QetGraphicsItem::diagram return the diagram of this item.
virtual void setPos (const QPointF &p)
QetGraphicsItem::setPos set the position of the item to p.
virtual void setPos (qreal x, qreal y)
QetGraphicsItem::setPos set the position of the item.
virtual bool isMovable () const
virtual void setMovable (bool movable)
QET::GraphicsItemState state () const
QetGraphicsItem::state.
Static Public Member Functions
static bool valideXml (QDomElement &)
Protected Member Functions
void drawAxes (QPainter *, const QStyleOptionGraphicsItem *)
void setSize (int, int)
Element::setSize Define the size of the element. The size must be a multiple of 10. If not, the dimensions indicated will be arrrondies to higher tens.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
Element::mouseMoveEvent.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Element::mouseReleaseEvent.
void hoverEnterEvent (QGraphicsSceneHoverEvent *) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *) override
Protected Member Functions inherited from QetGraphicsItem
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mousePressEvent handle the mouse click.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseDoubleClickEvent handle the mouse double click.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseMoveEvent handle mouse movement.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseReleaseEvent handle mouse release click.
Protected Attributes
QHash< DynamicElementTextItem *, QPointF > m_converted_text_from_xml_description
QList< Element * > connected_elements
QList< QUuid > tmp_uuids_link
QUuid m_uuid
kind m_link_type = Element::Simple
DiagramContext m_element_informations
DiagramContext m_kind_informations
autonum::sequentialNumbers m_autoNum_seq
bool m_freeze_label = false
QString m_F_str
ElementsLocation m_location
NamesList m_names
QList< Terminal * > m_terminals
const QPicture m_picture
const QPicture m_low_zoom_picture
Protected Attributes inherited from QetGraphicsItem
bool is_movable_
bool m_first_move
bool snap_to_grid_
QPointF m_mouse_to_origin_movement
QET::GraphicsItemState m_state = QET:: GIOK
Private Member Functions
Element (const Element &)
void drawSelection (QPainter *, const QStyleOptionGraphicsItem *)
void drawHighlight (QPainter *, const QStyleOptionGraphicsItem *)
bool buildFromXml (const QDomElement &, int *=nullptr)
Element::buildFromXml Build this element from an xml description.
bool parseElement (const QDomElement &dom)
Element::parseElement Parse the element of the xml description of this element.
bool parseInput (const QDomElement &dom_element)
Element::parseInput Parse the input (old text field) the parsed input are converted to dynamic text field, this function is only here to keep compatibility with old text.
DynamicElementTextItem * parseDynamicText (const QDomElement &dom_element)
Element::parseDynamicText Create the dynamic text field describ in dom_element.
Terminal * parseTerminal (const QDomElement &dom_element)
Element::parseTerminal Parse partTerminal from xml structure.
Private Attributes
bool m_must_highlight = false
QSize dimensions
QPoint hotspot_coord
bool m_mouse_over = false
QString m_prefix
QList< DynamicElementTextItem * > m_dynamic_text_list
QList< ElementTextItemGroup * > m_texts_group
Friends
class DiagramEventAddElement
Detailed Description
This is the base class for electrical elements.
Definition at line 40 of file element.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enable the use of qgraphicsitem_cast to safely cast a QGraphicsItem into an Element.
Returns
the QGraphicsItem type
Enumerator
Type
Definition at line 74 of file element.h.
kind
enum Element::kind
The kind enum Used to know the kind of this element (master, slave, report ect...)
Enumerator
Simple
NextReport
PreviousReport
AllReport
Master
Slave
Terminale
Definition at line 51 of file element.h.
Constructor & Destructor Documentation
Element() [1/2]
Element::Element (const ElementsLocation & location, QGraphicsItem * parent = nullptr, int * state = nullptr, Element::kind link_type = Element::Simple)
Element::Element.
Parameters
location : location of this element
parent : parent graphics item
state : state of the instanciation
link_type
Definition at line 79 of file element.cpp.
References buildFromXml(), autonum::elementPrefixForLocation(), ElementsLocation::exist(), ElementsLocation::isElement(), location(), m_uuid, setPrefix(), QetGraphicsItem::state(), and ElementsLocation::xml().
~Element()
Element::~Element () override
Element::~Element.
Definition at line 126 of file element.cpp.
References m_dynamic_text_list, and m_terminals.
Element() [2/2]
Element::Element (const Element &) private
Member Function Documentation
actualLabel()
QString Element::actualLabel ()
Element::actualLabel Always return the current label to be displayed. This function is usefull when label is based on formula, because label can change at any time.
Returns
Definition at line 1738 of file element.cpp.
References QetGraphicsItem::diagram(), autonum::AssignVariables::formulaToLabel(), m_autoNum_seq, m_element_informations, and DiagramContext::value().
Referenced by DynamicElementTextItem::elementInfoChanged(), projectDataBase::elementInfoToString(), setElementInformations(), setUpFormula(), and DynamicElementTextItem::updateLabel().
addDynamicTextItem()
void Element::addDynamicTextItem (DynamicElementTextItem * deti = nullptr)
Element::addDynamiqueTextItem Add deti as a dynamic text item of this element, deti is reparented to this If deti is null, a new DynamicElementTextItem is created and added to this element.
Parameters
deti
Definition at line 1264 of file element.cpp.
References m_dynamic_text_list, and textAdded().
Referenced by fromXml(), parseDynamicText(), AddElementTextCommand::redo(), removeTextFromGroup(), and DeleteQGraphicsItemCommand::undo().
addTextGroup() [1/2]
ElementTextItemGroup * Element::addTextGroup (const QString & name)
Element::addTextGroup Create and add an element text item group to this element. If this element already have a group with the same name, then name will renamed to name1 or name2 etc....
Parameters
name : the name of the group
Returns
the created group.
Definition at line 1328 of file element.cpp.
References m_texts_group, name(), textGroup(), and textsGroupAdded().
Referenced by fromXml().
addTextGroup() [2/2]
void Element::addTextGroup (ElementTextItemGroup * group)
Element::addTextGroup.
Parameters
group add group to the group of this element. the group must not be owned by an element.
Definition at line 1360 of file element.cpp.
References m_texts_group, ElementTextItemGroup::parentElement(), and textsGroupAdded().
addTextToGroup()
bool Element::addTextToGroup (DynamicElementTextItem * text, ElementTextItemGroup * group)
Element::addTextToGroup Add the text text to the group group; If group isn't owned by this element return false. The text must be a text of this element.
Returns
: true if the text was succesfully added to the group.
Definition at line 1432 of file element.cpp.
References ElementTextItemGroup::addToGroup(), m_dynamic_text_list, m_texts_group, textAddedToGroup(), and textRemoved().
Referenced by ElementTextItemGroup::fromXml(), fromXml(), and DeleteQGraphicsItemCommand::undo().
AlignedFreeTerminals()
QList< QPair< Terminal *, Terminal * > > Element::AlignedFreeTerminals () const
Element::AlignedFreeTerminals.
Returns
a list of terminal (owned by this element) aligned to other terminal (from other element) The first Terminal of QPair is a Terminal owned by this element, this terminal haven't got any conductor docked. The second Terminal of QPair is a Terminal owned by an other element, which is aligned with the first Terminal. The second Terminal can have or not docked conductors.
Definition at line 1480 of file element.cpp.
References Terminal::conductors(), and terminals().
Referenced by ElementsMover::endMovement().
boundingRect()
QRectF Element::boundingRect () const override
Returns
Le rectangle delimitant le contour de l'element
Definition at line 222 of file element.cpp.
References dimensions, and hotspot_coord.
Referenced by centerToBottomDiagram(), drawHighlight(), and drawSelection().
buildFromXml()
bool Element::buildFromXml (const QDomElement & xml_def_elmt, int * state = nullptr) private
Element::buildFromXml Build this element from an xml description.
Parameters
xml_def_elmt
state Optional pointer which define the status of build 0 - evreything all right 4 - xml isn't a "definition" 5 - attribute of the definition isn't present or valid 6 - the definition is empty 7 - parsing of a xml node who describe a graphical part failed. 8 - No part of the drawing could be loaded
Returns
Definition at line 376 of file element.cpp.
References QET::attributeIsAnInteger(), NamesList::fromXml(), DiagramContext::fromXml(), ElementPictureFactory::getPictures(), QET::GIBuildingFromXml, QET::GIOK, ElementPictureFactory::instance(), m_element_informations, m_kind_informations, m_location, m_low_zoom_picture, m_names, m_picture, QetGraphicsItem::m_state, name(), parseElement(), setHotspot(), setSize(), QetGraphicsItem::state(), QET::Icons::tr, and QET::version.
Referenced by Element().
conductors()
QList< Conductor * > Element::conductors () const
Element::conductors.
Returns
The list of conductors docked to this element the list is sorted according to the position of the terminal where the conductor is docked from top to bottom, and left to right.
Definition at line 146 of file element.cpp.
References m_terminals.
Referenced by ConductorCreator::existingPotential(), LinkReportPotentialSelector::LinkReportPotentialSelector(), PotentialSelectorDialog::on_buttonBox_accepted(), and LinkElementCommand::redo().
displayHelpLine()
void Element::displayHelpLine (bool b = true)
Element::displayHelpLine Display the help line of each terminal if b is true.
Parameters
b
Definition at line 188 of file element.cpp.
References Terminal::drawHelpLine(), and terminals().
drawAxes()
void Element::drawAxes (QPainter * painter, const QStyleOptionGraphicsItem * options) protected
Dessine un petit repere (axes x et y) relatif a l'element
Parameters
painter Le QPainter a utiliser pour dessiner les axes
options Les options de style a prendre en compte
Definition at line 291 of file element.cpp.
drawHighlight()
void Element::drawHighlight (QPainter * painter, const QStyleOptionGraphicsItem * options) private
Dessine le cadre de selection de l'element de maniere systematiquement non antialiasee.
Parameters
painter Le QPainter a utiliser pour dessiner les bornes.
options Les options de style a prendre en compte
Definition at line 337 of file element.cpp.
References boundingRect().
Referenced by paint().
drawSelection()
void Element::drawSelection (QPainter * painter, const QStyleOptionGraphicsItem * options) private
Dessine le cadre de selection de l'element de maniere systematiquement non antialiasee.
Parameters
painter Le QPainter a utiliser pour dessiner les bornes.
options Les options de style a prendre en compte
Definition at line 311 of file element.cpp.
References boundingRect().
Referenced by paint().
dynamicTextItems()
QList< DynamicElementTextItem * > Element::dynamicTextItems () const
Element::dynamicTextItems.
Returns
all dynamic text items of this element directly child of this element. Texts in text-groups belonging to this element are not returned by this function.
See also
ElementTextItemGroup::texts
Definition at line 1316 of file element.cpp.
References m_dynamic_text_list.
Referenced by ImportElementTextPattern::apply(), SearchAndReplaceWidget::searchTerms(), and AddElementTextCommand::~AddElementTextCommand().
editProperty()
void Element::editProperty () override virtual
Reimplemented from QetGraphicsItem.
Definition at line 157 of file element.cpp.
References QetGraphicsItem::diagram(), and ElementPropertiesWidget::findEditClicked().
elementInfoChange
void Element::elementInfoChange (DiagramContext old_info, DiagramContext new_info) signal
Referenced by DynamicElementTextItem::masterChanged(), ElementInfoWidget::setElement(), setElementInformations(), DynamicElementTextItem::setTextFrom(), setUpFormula(), DynamicElementTextItem::updateXref(), and ElementTextItemGroup::updateXref().
elementInformations()
DiagramContext Element::elementInformations () const inline
Definition at line 97 of file element.h.
References m_element_informations.
Referenced by SearchAndReplaceWidget::addElement(), CrossRefItem::AddExtraInfo(), DynamicTextItemDelegate::availableInfo(), DynamicElementTextItem::elementInfoChanged(), projectDataBase::elementInfoToString(), DynamicElementTextModel::itemDataChanged(), DynamicElementTextModel::itemsForText(), SearchAndReplaceWorker::replaceAdvanced(), SearchAndReplaceWidget::searchTerms(), DynamicElementTextItem::setCompositeText(), DynamicTextItemDelegate::setModelData(), DynamicElementTextItem::setupFormulaConnection(), and DynamicElementTextItem::updateLabel().
freezeLabel()
void Element::freezeLabel (bool freeze)
Element::freezeLabel Freeze this element label.
Definition at line 1715 of file element.cpp.
References m_freeze_label.
Referenced by Diagram::freezeElements(), freezeNewAddedElement(), and Diagram::unfreezeElements().
freezeNewAddedElement()
void Element::freezeNewAddedElement ()
Element::freezeNewAddedElement Freeze this label if needed.
Definition at line 1724 of file element.cpp.
References QetGraphicsItem::diagram(), and freezeLabel().
Referenced by DiagramEventAddElement::addElement().
fromXml()
bool Element::fromXml (QDomElement & e, QHash< int, Terminal * > & table_id_adr, bool handle_inputs_rotation = false) virtual
Element::fromXml Import the parameters of this element from a xml document. When call this function ensure this element is already in a scene, because the dynamic text item and element text item group (in the xml file) are created in this function and need a diagram for create their Xref, when this element is linked to another. If not the Xref can be not displayed, until the next call of update Xref of the group or text item.
Parameters
e : the dom element where the parameter is stored
table_id_adr : Reference to the mapping table between IDs of the XML file and the addresses in memory. If the import succeeds, it must be add the right couples (id, address).
handle_inputs_rotation : apply the rotation of this element to his child text
Returns
Definition at line 684 of file element.cpp.
References addDynamicTextItem(), addTextGroup(), addTextToGroup(), DiagramContext::addValue(), QetGraphicsItem::diagram(), DynamicElementTextItem::ElementInfo, QET::findInDomElement(), DiagramTextItem::font, autonum::sequentialNumbers::fromXml(), DiagramContext::fromXml(), ElementTextItemGroup::fromXml(), DynamicElementTextItem::fromXml(), QET::GILoadingFromXml, QET::GIOK, DiagramContext::keyMustShow(), XRefProperties::Label, ElementXmlRetroCompatibility::loadSequential(), location(), m_autoNum_seq, m_converted_text_from_xml_description, m_dynamic_text_list, m_element_informations, m_freeze_label, m_kind_informations, m_link_type, m_prefix, QetGraphicsItem::m_state, m_uuid, Master, NextReport, PreviousReport, ElementTextItemGroup::setAlignment(), setElementInformations(), DiagramTextItem::setFont(), DynamicElementTextItem::setFrame(), ElementTextItemGroup::setHoldToBottomPage(), DynamicElementTextItem::setInfoName(), ElementTextItemGroup::setPos(), ElementTextItemGroup::setRotation(), DynamicElementTextItem::setTextFrom(), DynamicElementTextItem::setTextWidth(), ElementTextItemGroup::setVerticalAdjustment(), tmp_uuids_link, QET::Icons::tr, Terminal::valideXml(), DiagramContext::value(), ElementTextItemGroup::xmlTaggName(), and DynamicElementTextItem::xmlTagName().
Referenced by Diagram::fromXml().
getPrefix()
QString Element::getPrefix () const
Element::getPrefix get Element Prefix.
Definition at line 1699 of file element.cpp.
References m_prefix.
Referenced by autonum::AssignVariables::AssignVariables().
hotspot()
QPoint Element::hotspot () const
Returns
Le hotspot courant de l'element
Definition at line 272 of file element.cpp.
References hotspot_coord.
Referenced by ElementsTreeView::startElementDrag().
hoverEnterEvent()
void Element::hoverEnterEvent (QGraphicsSceneHoverEvent * e) override protected
When mouse over element change m_mouse_over to true (used in paint() function) Also highlight linked elements
Parameters
e QGraphicsSceneHoverEvent
Definition at line 1619 of file element.cpp.
References linkedElements(), m_mouse_over, name(), and setHighlighted().
hoverLeaveEvent()
void Element::hoverLeaveEvent (QGraphicsSceneHoverEvent * e) override protected
When mouse over element leave the position change m_mouse_over to false(used in paint() function) Also un-highlight linked elements
Parameters
e QGraphicsSceneHoverEvent
Definition at line 1636 of file element.cpp.
References linkedElements(), m_mouse_over, and setHighlighted().
initLink()
void Element::initLink (QETProject * prj) virtual
Element::initLink Initialise the link between this element and other elements. This method can be call once because init the link according to uuid store in a private list, after link, the list is clear, so call another time do nothing.
Parameters
prj : ownership project of this element and other element to be linked
Reimplemented in MasterElement, SimpleElement, and TerminalElement.
Definition at line 1508 of file element.cpp.
References ElementProvider::fromUuids(), linkToElement(), and tmp_uuids_link.
Referenced by TerminalElement::initLink(), SimpleElement::initLink(), and MasterElement::initLink().
isFree()
bool Element::isFree () const inline
Definition at line 230 of file element.h.
References connected_elements.
Referenced by CrossRefItem::fillCrossRef(), ElementProvider::freeElement(), NewConductorPotentialSelector::getPotential(), LinkElementCommand::isLinkable(), LinkReportPotentialSelector::LinkReportPotentialSelector(), SlaveElement::linkToElement(), ReportElement::linkToElement(), PotentialSelectorDialog::on_buttonBox_accepted(), CrossRefItem::setUpCrossBoundingRect(), toXml(), SlaveElement::unlinkAllElements(), ReportElement::unlinkAllElements(), and MasterElement::unlinkAllElements().
isFreezeLabel()
bool Element::isFreezeLabel () const inline
Definition at line 114 of file element.h.
References m_freeze_label.
Referenced by DynamicElementTextItem::setupFormulaConnection().
kindInformations()
DiagramContext Element::kindInformations () const inline
Definition at line 100 of file element.h.
References m_kind_informations.
Referenced by MasterElement::aboutDeleteXref(), projectDataBase::addElement(), ElementTextItemGroup::autoPos(), CrossRefItem::drawAsContacts(), CrossRefItem::elementPositionText(), CrossRefItem::init(), MasterElement::linkToElement(), CrossRefItem::NCElements(), CrossRefItem::NOElements(), CrossRefItem::updateProperties(), ElementTextItemGroup::updateXref(), and MasterElement::xrefPropertiesChanged().
linkedElementChanged
void Element::linkedElementChanged () signal
Referenced by ElementTextItemGroup::ElementTextItemGroup(), DynamicElementTextItem::itemChange(), SlaveElement::linkToElement(), ReportElement::linkToElement(), MasterElement::linkToElement(), LinkSingleElementWidget::setElement(), MasterPropertiesWidget::setElement(), ElementTextItemGroup::setHoldToBottomPage(), CrossRefItem::setUpConnection(), SlaveElement::unlinkAllElements(), ReportElement::unlinkAllElements(), MasterElement::unlinkAllElements(), SlaveElement::unlinkElement(), and MasterElement::unlinkElement().
linkedElements()
QList< Element * > Element::linkedElements () inline
Element::linkedElements.
Returns
the list of linked elements, the list is sorted by position
Definition at line 258 of file element.h.
References comparPos(), connected_elements, and sort().
Referenced by CrossRefItem::drawAsContacts(), DynamicElementTextItem::elementUseForInfo(), ConductorCreator::existingPotential(), NewConductorPotentialSelector::getPotential(), hoverEnterEvent(), hoverLeaveEvent(), LinkElementCommand::isLinkable(), CrossRefItem::linkedChanged(), LinkElementCommand::LinkElementCommand(), LinkReportPotentialSelector::LinkReportPotentialSelector(), LinkElementCommand::makeLink(), ElementTextItemGroup::mouseDoubleClickEvent(), CrossRefItem::NCElements(), CrossRefItem::NOElements(), DeleteQGraphicsItemCommand::redo(), CrossRefItem::updateLabel(), and ElementTextItemGroup::updateXref().
linkToElement()
virtual void Element::linkToElement (Element *) inline virtual
Reimplemented in MasterElement, SlaveElement, and ReportElement.
Definition at line 154 of file element.h.
Referenced by initLink(), LinkReportPotentialSelector::LinkReportPotentialSelector(), ReportElement::linkToElement(), MasterElement::linkToElement(), and LinkElementCommand::makeLink().
linkType()
virtual kind Element::linkType () const inline virtual
Definition at line 159 of file element.h.
References m_link_type.
Referenced by SearchAndReplaceWidget::addElement(), ElementTextItemGroup::autoPos(), DynamicTextItemDelegate::availableInfo(), DynamicElementTextItem::elementUseForInfo(), ElementProvider::find(), ElementProvider::freeElement(), NewConductorPotentialSelector::getPotential(), LinkElementCommand::isLinkable(), LinkReportPotentialSelector::LinkReportPotentialSelector(), SlaveElement::linkToElement(), ReportElement::linkToElement(), MasterElement::linkToElement(), PotentialSelectorDialog::on_buttonBox_accepted(), LinkElementCommand::redo(), ElementPropertiesWidget::setElement(), ElementTextItemGroup::setHoldToBottomPage(), CompositeTextEditDialog::setUpComboBox(), setUpFormula(), LinkElementCommand::setUpNewLink(), and ElementTextItemGroup::updateXref().
linkTypeToString()
QString Element::linkTypeToString () const
Definition at line 1520 of file element.cpp.
References m_link_type, Master, NextReport, PreviousReport, Simple, Slave, and Terminale.
Referenced by projectDataBase::addElement().
location()
ElementsLocation Element::location () const
Definition at line 1760 of file element.cpp.
References m_location.
Referenced by Element(), fromXml(), and ExportDialog::generateDxf().
mouseMoveEvent()
void Element::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
Element::mouseMoveEvent.
Parameters
event
Definition at line 1591 of file element.cpp.
References QetGraphicsItem::mouseMoveEvent(), and terminals().
mouseReleaseEvent()
void Element::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Element::mouseReleaseEvent.
Parameters
event
Definition at line 1604 of file element.cpp.
References QetGraphicsItem::mouseReleaseEvent(), and terminals().
name()
QString Element::name () const override virtual
Element::name.
Returns
the human name of this element
Reimplemented from QetGraphicsItem.
Definition at line 1756 of file element.cpp.
References ElementsLocation::baseName(), m_location, m_names, and NamesList::name().
Referenced by DiagramEventAddElement::addElement(), addTextGroup(), buildFromXml(), hoverEnterEvent(), DynamicElementTextItemEditor::on_m_add_group_clicked(), and textGroup().
newUuid()
void Element::newUuid () inline
Definition at line 161 of file element.h.
References m_uuid.
orientation()
int Element::orientation () const inline
Indicate the current orientation of this element O = 0 1 = 90 2 = 180 3 = 270
Returns
the current orientation of this element
Definition at line 242 of file element.h.
References QET::correctAngle().
Referenced by toXml().
paint()
void Element::paint (QPainter * painter, const QStyleOptionGraphicsItem * options, QWidget *) override
Element::paint.
Parameters
painter
options
Definition at line 199 of file element.cpp.
References drawHighlight(), drawSelection(), m_low_zoom_picture, m_mouse_over, m_must_highlight, and m_picture.
parseDynamicText()
DynamicElementTextItem * Element::parseDynamicText (const QDomElement & dom_element) private
Element::parseDynamicText Create the dynamic text field describ in dom_element.
Parameters
dom_element
Returns
Definition at line 597 of file element.cpp.
References addDynamicTextItem(), DynamicElementTextItem::fromXml(), DynamicElementTextItem::m_uuid, and DynamicElementTextItem::xmlTagName().
Referenced by parseElement().
parseElement()
bool Element::parseElement (const QDomElement & dom) private
Element::parseElement Parse the element of the xml description of this element.
Parameters
dom
Returns
Definition at line 526 of file element.cpp.
References parseDynamicText(), parseInput(), and parseTerminal().
Referenced by buildFromXml().
parseInput()
bool Element::parseInput (const QDomElement & dom_element) private
Element::parseInput Parse the input (old text field) the parsed input are converted to dynamic text field, this function is only here to keep compatibility with old text.
Parameters
dom_element
Returns
Definition at line 542 of file element.cpp.
References QET::attributeIsAnInteger(), QET::attributeIsAReal(), DynamicElementTextItem::ElementInfo, DiagramTextItem::font, m_converted_text_from_xml_description, DiagramTextItem::setFont(), DynamicElementTextItem::setInfoName(), DynamicElementTextItem::setText(), DynamicElementTextItem::setTextFrom(), and size().
Referenced by parseElement().
parseTerminal()
Terminal * Element::parseTerminal (const QDomElement & dom_element) private
Element::parseTerminal Parse partTerminal from xml structure.
Parameters
dom_element
Returns
Definition at line 619 of file element.cpp.
References TerminalData::fromXml(), m_terminals, sort(), and QET::Icons::Terminal.
Referenced by parseElement().
pixmap()
QPixmap Element::pixmap ()
Element::pixmap.
Returns
the pixmap of this element
Definition at line 280 of file element.cpp.
References ElementPictureFactory::instance(), m_location, and ElementPictureFactory::pixmap().
Referenced by ElementsTreeView::startElementDrag().
removeDynamicTextItem()
void Element::removeDynamicTextItem (DynamicElementTextItem * deti)
Element::removeDynamicTextItem Remove deti, no matter if is a child of this element or a child of a group of this element. Set he parent item of deti to 0, deti is not deleted.
Parameters
deti
Definition at line 1287 of file element.cpp.
References m_dynamic_text_list, m_texts_group, removeTextFromGroup(), and textRemoved().
Referenced by DeleteQGraphicsItemCommand::redo(), and AddElementTextCommand::undo().
removeTextFromGroup()
bool Element::removeTextFromGroup (DynamicElementTextItem * text, ElementTextItemGroup * group)
Element::removeTextFromGroup Remove the text text from the group group, en reparent text to this element.
Returns
true if text was succesfully removed
Definition at line 1455 of file element.cpp.
References addDynamicTextItem(), m_texts_group, ElementTextItemGroup::removeFromGroup(), textRemovedFromGroup(), and ElementTextItemGroup::texts().
Referenced by DeleteQGraphicsItemCommand::redo(), removeDynamicTextItem(), and removeTextGroup().
removeTextGroup()
void Element::removeTextGroup (ElementTextItemGroup * group)
Element::removeTextGroup Remove the text group group from this element, and set the parent of group to 0. group is not deleted. All texts owned by the group will be reparented to this element.
Parameters
group
Definition at line 1378 of file element.cpp.
References m_texts_group, removeTextFromGroup(), textsGroupAboutToBeRemoved(), and DynamicElementTextItem::Type.
rSequenceStruct()
autonum::sequentialNumbers& Element::rSequenceStruct () inline
Definition at line 108 of file element.h.
References m_autoNum_seq.
Referenced by CrossRefItem::AddExtraInfo(), ElementXmlRetroCompatibility::loadSequential(), DynamicElementTextItem::reportReplacedCompositeText(), DynamicElementTextItem::updateReportText(), and ElementTextItemGroup::updateXref().
sequenceStruct()
autonum::sequentialNumbers Element::sequenceStruct () const inline
Definition at line 106 of file element.h.
References m_autoNum_seq.
setElementInformations()
void Element::setElementInformations (DiagramContext dc) virtual
Element::setElementInformations Set new information for this element. If new information is different of current infotmation emit elementInfoChange.
Parameters
dc
Definition at line 1547 of file element.cpp.
References actualLabel(), DiagramContext::addValue(), elementInfoChange(), and m_element_informations.
Referenced by fromXml().
setHighlighted()
void Element::setHighlighted (bool hl) virtual
Parameters
hl true pour mettre l'element en evidence, false sinon
Definition at line 178 of file element.cpp.
References m_must_highlight.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), LinkSingleElementWidget::LinkSingleElementWidget(), ElementTextItemGroup::mouseMoveEvent(), DynamicElementTextItem::mouseMoveEvent(), ElementTextItemGroup::mouseReleaseEvent(), LinkSingleElementWidget::on_m_show_linked_pb_clicked(), LinkSingleElementWidget::on_m_tree_widget_itemDoubleClicked(), LinkSingleElementWidget::setElement(), ReportElement::unlinkAllElements(), SlaveElement::unlinkElement(), MasterElement::unlinkElement(), and LinkSingleElementWidget::~LinkSingleElementWidget().
setHotspot()
QPoint Element::setHotspot (QPoint hs)
Definit le hotspot de l'element par rapport au coin superieur gauche de son rectangle delimitant. Necessite que la taille ait deja ete definie
Parameters
hs Coordonnees du hotspot
Definition at line 256 of file element.cpp.
References dimensions, and hotspot_coord.
Referenced by buildFromXml().
setPrefix()
void Element::setPrefix (QString prefix)
Element::setPrefix set Element Prefix.
Definition at line 1707 of file element.cpp.
References m_prefix.
Referenced by Element().
setSize()
void Element::setSize (int wid, int hei) protected
Element::setSize Define the size of the element. The size must be a multiple of 10. If not, the dimensions indicated will be arrrondies to higher tens.
Parameters
wid
hei
Definition at line 235 of file element.cpp.
References dimensions.
Referenced by buildFromXml().
setUpFormula()
void Element::setUpFormula (bool code_letter = true)
Element::setUpFormula Set up the formula used to create the label of this element.
Parameters
code_letter : Q_UNUSED(code_letter) if true set tagged text to code letter (ex K for coil) with condition : formula is empty, text tagged "label" is emptty or "_";
Definition at line 1654 of file element.cpp.
References actualLabel(), QETProject::addElementAutoNum(), DiagramContext::addValue(), AllReport, autonum::sequentialNumbers::clear(), QetGraphicsItem::diagram(), QETProject::elementAutoNum(), QETProject::elementAutoNumCurrentFormula(), QETProject::elementCurrentAutoNum(), elementInfoChange(), linkType(), m_autoNum_seq, m_element_informations, m_freeze_label, NumerotationContextCommands::next(), Diagram::project(), autonum::setSequential(), and Slave.
Referenced by DiagramEventAddElement::addElement().
size()
QSize Element::size () const
Returns
la taille de l'element sur le schema
Definition at line 247 of file element.cpp.
References dimensions.
Referenced by parseInput(), and ReportElement::~ReportElement().
terminals()
QList< Terminal * > Element::terminals () const
Element::terminals.
Returns
the list of terminals of this element.
Definition at line 136 of file element.cpp.
References m_terminals.
Referenced by AlignedFreeTerminals(), displayHelpLine(), NewConductorPotentialSelector::getPotential(), mouseMoveEvent(), mouseReleaseEvent(), relatedPotentialTerminal(), DynamicElementTextItem::setPotentialConductor(), DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements(), toXml(), and ReportElement::~ReportElement().
textAdded
void Element::textAdded (DynamicElementTextItem * deti) signal
Referenced by addDynamicTextItem(), and DynamicElementTextModel::DynamicElementTextModel().
textAddedToGroup
void Element::textAddedToGroup (DynamicElementTextItem * text, ElementTextItemGroup * group) signal
Referenced by addTextToGroup(), and DynamicElementTextModel::DynamicElementTextModel().
textGroup()
ElementTextItemGroup * Element::textGroup (const QString & name) const
Element::textGroup.
Parameters
name
Returns
the text group named name or nullptr if this element haven't got a group with this name
Definition at line 1407 of file element.cpp.
References m_texts_group, and name().
Referenced by addTextGroup().
textGroups()
QList< ElementTextItemGroup * > Element::textGroups () const
Element::textGroups.
Returns
All texts groups of this element
Definition at line 1420 of file element.cpp.
References m_texts_group.
Referenced by ImportElementTextPattern::apply(), and SearchAndReplaceWidget::searchTerms().
textRemoved
void Element::textRemoved (DynamicElementTextItem * deti) signal
Referenced by addTextToGroup(), DynamicElementTextModel::DynamicElementTextModel(), and removeDynamicTextItem().
textRemovedFromGroup
void Element::textRemovedFromGroup (DynamicElementTextItem * text, ElementTextItemGroup * group) signal
Referenced by DynamicElementTextModel::DynamicElementTextModel(), and removeTextFromGroup().
textsGroupAboutToBeRemoved
void Element::textsGroupAboutToBeRemoved (ElementTextItemGroup * group) signal
Referenced by DynamicElementTextModel::DynamicElementTextModel(), and removeTextGroup().
textsGroupAdded
void Element::textsGroupAdded (ElementTextItemGroup * group) signal
Referenced by addTextGroup(), and DynamicElementTextModel::DynamicElementTextModel().
toXml()
QDomElement Element::toXml (QDomDocument & document, QHash< Terminal *, int > & table_adr_id) const virtual
Element::toXml Allows to export the element in XML.
Parameters
document : XML document to use
table_adr_id : Correspondence table between the addresses of the terminals and their id in the XML representation; this table completed by this method
Returns
The XML element representing this electrical element
Definition at line 1130 of file element.cpp.
References connected_elements, isFree(), DiagramContext::keys(), m_autoNum_seq, m_dynamic_text_list, m_element_informations, m_freeze_label, m_location, m_prefix, m_texts_group, orientation(), ElementsLocation::path(), terminals(), autonum::sequentialNumbers::toXml(), DiagramContext::toXml(), and uuid().
Referenced by ExportElementTextPattern::xmlConf().
type()
int Element::type () const inline override
Definition at line 75 of file element.h.
References Type.
unlinkAllElements()
virtual void Element::unlinkAllElements () inline virtual
Reimplemented in MasterElement, ReportElement, and SlaveElement.
Definition at line 155 of file element.h.
Referenced by LinkReportPotentialSelector::LinkReportPotentialSelector(), LinkElementCommand::makeLink(), and Diagram::removeItem().
unlinkElement()
virtual void Element::unlinkElement (Element *) inline virtual
Reimplemented in MasterElement, ReportElement, and SlaveElement.
Definition at line 156 of file element.h.
Referenced by LinkElementCommand::makeLink().
uuid()
QUuid Element::uuid () const inline
Element::uuid.
Returns
the uuid of this element
Definition at line 250 of file element.h.
References m_uuid.
Referenced by projectDataBase::addElement(), projectDataBase::elementInfoChanged(), ElementProvider::fromUuids(), projectDataBase::removeElement(), Conductor::toXml(), and toXml().
valideXml()
bool Element::valideXml (QDomElement & e) static
Permet de savoir si un element XML (QDomElement) represente bien un element
Parameters
e Le QDomElement a valide
Returns
true si l'element XML est un Element, false sinon
Definition at line 651 of file element.cpp.
Referenced by Diagram::fromXml().
Friends And Related Function Documentation
DiagramEventAddElement
friend class DiagramEventAddElement friend
Definition at line 42 of file element.h.
Member Data Documentation
connected_elements
QList<Element *> Element::connected_elements protected
Definition at line 200 of file element.h.
Referenced by isFree(), linkedElements(), SlaveElement::linkToElement(), ReportElement::linkToElement(), MasterElement::linkToElement(), toXml(), SlaveElement::unlinkAllElements(), ReportElement::unlinkAllElements(), MasterElement::unlinkAllElements(), SlaveElement::unlinkElement(), and MasterElement::unlinkElement().
dimensions
QSize Element::dimensions private
Definition at line 219 of file element.h.
Referenced by boundingRect(), setHotspot(), setSize(), and size().
hotspot_coord
QPoint Element::hotspot_coord private
Definition at line 220 of file element.h.
Referenced by boundingRect(), hotspot(), and setHotspot().
m_autoNum_seq
autonum::sequentialNumbers Element::m_autoNum_seq protected
Definition at line 207 of file element.h.
Referenced by actualLabel(), fromXml(), rSequenceStruct(), sequenceStruct(), setUpFormula(), and toXml().
m_converted_text_from_xml_description
QHash<DynamicElementTextItem *, QPointF> Element::m_converted_text_from_xml_description protected
Definition at line 197 of file element.h.
Referenced by DiagramEventAddElement::addElement(), fromXml(), and parseInput().
m_dynamic_text_list
QList<DynamicElementTextItem *> Element::m_dynamic_text_list private
Definition at line 223 of file element.h.
Referenced by addDynamicTextItem(), DiagramEventAddElement::addElement(), addTextToGroup(), dynamicTextItems(), fromXml(), removeDynamicTextItem(), toXml(), and ~Element().
m_element_informations
DiagramContext Element::m_element_informations protected
Definition at line 206 of file element.h.
Referenced by actualLabel(), buildFromXml(), elementInformations(), fromXml(), setElementInformations(), setUpFormula(), and toXml().
m_F_str
QString Element::m_F_str protected
Definition at line 209 of file element.h.
m_freeze_label
bool Element::m_freeze_label = false protected
Definition at line 208 of file element.h.
Referenced by freezeLabel(), fromXml(), isFreezeLabel(), setUpFormula(), and toXml().
m_kind_informations
DiagramContext Element::m_kind_informations protected
Definition at line 206 of file element.h.
Referenced by buildFromXml(), fromXml(), and kindInformations().
m_link_type
kind Element::m_link_type = Element::Simple protected
Definition at line 203 of file element.h.
Referenced by fromXml(), linkType(), and linkTypeToString().
m_location
ElementsLocation Element::m_location protected
Definition at line 211 of file element.h.
Referenced by buildFromXml(), location(), name(), pixmap(), and toXml().
m_low_zoom_picture
const QPicture Element::m_low_zoom_picture protected
Definition at line 215 of file element.h.
Referenced by buildFromXml(), and paint().
m_mouse_over
bool Element::m_mouse_over = false private
Definition at line 221 of file element.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and paint().
m_must_highlight
bool Element::m_must_highlight = false private
Definition at line 218 of file element.h.
Referenced by paint(), and setHighlighted().
m_names
NamesList Element::m_names protected
Definition at line 212 of file element.h.
Referenced by buildFromXml(), and name().
m_picture
const QPicture Element::m_picture protected
Definition at line 214 of file element.h.
Referenced by buildFromXml(), and paint().
m_prefix
QString Element::m_prefix private
Definition at line 222 of file element.h.
Referenced by fromXml(), getPrefix(), setPrefix(), and toXml().
m_terminals
QList<Terminal *> Element::m_terminals protected
Definition at line 213 of file element.h.
Referenced by conductors(), parseTerminal(), terminals(), and ~Element().
m_texts_group
QList<ElementTextItemGroup *> Element::m_texts_group private
Definition at line 224 of file element.h.
Referenced by addTextGroup(), addTextToGroup(), removeDynamicTextItem(), removeTextFromGroup(), removeTextGroup(), textGroup(), textGroups(), and toXml().
m_uuid
QUuid Element::m_uuid protected
Definition at line 202 of file element.h.
Referenced by Element(), fromXml(), newUuid(), and uuid().
tmp_uuids_link
QList<QUuid> Element::tmp_uuids_link protected
Definition at line 201 of file element.h.
Referenced by fromXml(), and initLink().
The documentation for this class was generated from the following files:
element.h
element.cpp