QElectroTech: ECHSXmlToFile Class Reference
ECHSXmlToFile Class Reference
The ECHSXmlToFile class Manage the copy of a directory or element from an xml collection to a file.
#include <elementcollectionhandler.h>
Public Member Functions
ECHSXmlToFile (ElementsLocation &source, ElementsLocation &destination)
ElementsLocation copy () override
Public Member Functions inherited from ECHStrategy
ECHStrategy (ElementsLocation &source, ElementsLocation &destination)
virtual ~ECHStrategy ()
Private Member Functions
ElementsLocation copyDirectory (ElementsLocation &source, ElementsLocation &destination, const QString &rename=QString())
ElementsLocation copyElement (ElementsLocation &source, ElementsLocation &destination, const QString &rename=QString())
Additional Inherited Members
Public Attributes inherited from ECHStrategy
ElementsLocation m_source
ElementsLocation m_destination
Detailed Description
The ECHSXmlToFile class Manage the copy of a directory or element from an xml collection to a file.
Definition at line 70 of file elementcollectionhandler.h.
Constructor & Destructor Documentation
ECHSXmlToFile()
ECHSXmlToFile::ECHSXmlToFile (ElementsLocation & source, ElementsLocation & destination)
Definition at line 163 of file elementcollectionhandler.cpp.
Member Function Documentation
copy()
ElementsLocation ECHSXmlToFile::copy () override virtual
Implements ECHStrategy.
Definition at line 167 of file elementcollectionhandler.cpp.
References copyDirectory(), copyElement(), QET::Erase, ElementsLocation::exist(), ElementsLocation::fileName(), ElementsLocation::fileSystemPath(), ElementsLocation::isDirectory(), ElementsLocation::isElement(), ECHStrategy::m_destination, ECHStrategy::m_source, RenameDialog::newName(), QET::Rename, and RenameDialog::selectedAction().
copyDirectory()
ElementsLocation ECHSXmlToFile::copyDirectory (ElementsLocation & source, ElementsLocation & destination, const QString & rename = QString()) private
Definition at line 205 of file elementcollectionhandler.cpp.
References ElementsLocation::collectionPath(), copyElement(), XmlElementCollection::directoriesNames(), XmlElementCollection::directory(), XmlElementCollection::elementsNames(), ElementsLocation::exist(), ElementsLocation::fileName(), ElementsLocation::fileSystemPath(), ElementsLocation::nameList(), ElementsLocation::projectCollection(), ElementsLocation::projectCollectionPath(), NamesList::toXml(), and QET::writeXmlFile().
Referenced by copy().
copyElement()
ElementsLocation ECHSXmlToFile::copyElement (ElementsLocation & source, ElementsLocation & destination, const QString & rename = QString()) private
Definition at line 252 of file elementcollectionhandler.cpp.
References ElementsLocation::exist(), ElementsLocation::fileName(), ElementsLocation::fileSystemPath(), QET::writeXmlFile(), and ElementsLocation::xml().
Referenced by copy(), and copyDirectory().
The documentation for this class was generated from the following files:
elementcollectionhandler.h
elementcollectionhandler.cpp