QElectroTech: MoveElementsCommand Class Reference
MoveElementsCommand Class Reference
The MoveElementsCommand class This command moves some content on a particular diagram.
#include <diagramcommands.h>
Public Member Functions
MoveElementsCommand (Diagram *, const DiagramContent &, const QPointF &m, QUndoCommand *=nullptr)
MoveElementsCommand::MoveElementsCommand Constructor.
~MoveElementsCommand () override
MoveElementsCommand::~MoveElementsCommand Destructor.
void undo () override
MoveElementsCommand::undo.
void redo () override
MoveElementsCommand::redo.
virtual void move (const QPointF &)
MoveElementsCommand::move Move item and conductor to actual_movement.
Private Member Functions
MoveElementsCommand (const MoveElementsCommand &)
void setupAnimation (QObject *target, const QByteArray &propertyName, const QVariant &start, const QVariant &end)
MoveElementsCommand::setupAnimation Set up the animation for this undo command.
Private Attributes
Diagram * diagram
diagram the movement takes place on.
DiagramContent content_to_move
moved content
QPointF movement
applied movement
QParallelAnimationGroup * m_anim_group
animation group
bool first_redo
prevent the first call to redo()
Detailed Description
The MoveElementsCommand class This command moves some content on a particular diagram.
Definition at line 132 of file diagramcommands.h.
Constructor & Destructor Documentation
MoveElementsCommand() [1/2]
MoveElementsCommand::MoveElementsCommand (Diagram * dia, const DiagramContent & diagram_content, const QPointF & m, QUndoCommand * parent = nullptr)
MoveElementsCommand::MoveElementsCommand Constructor.
Parameters
dia diagram
diagram_content diagram content (contain all items to be moved)
m movement to applied
parent parent undo command
Definition at line 176 of file diagramcommands.cpp.
References DiagramContent::ConductorsToMove, DiagramContent::ConductorsToUpdate, content_to_move, DiagramContent::Elements, DiagramContent::ElementTextFields, DiagramContent::Images, DiagramContent::sentence(), DiagramContent::Shapes, DiagramContent::TextFields, and QET::Icons::tr.
~MoveElementsCommand()
MoveElementsCommand::~MoveElementsCommand () override
MoveElementsCommand::~MoveElementsCommand Destructor.
Definition at line 213 of file diagramcommands.cpp.
References m_anim_group.
MoveElementsCommand() [2/2]
MoveElementsCommand::MoveElementsCommand (const MoveElementsCommand &) private
Member Function Documentation
move()
void MoveElementsCommand::move (const QPointF & actual_movement) virtual
MoveElementsCommand::move Move item and conductor to actual_movement.
Parameters
actual_movement movement to be applied
Definition at line 248 of file diagramcommands.cpp.
References content_to_move, DiagramContent::items(), DiagramContent::m_conductors_to_move, DiagramContent::m_conductors_to_update, Conductor::pos, and setupAnimation().
Referenced by redo().
redo()
void MoveElementsCommand::redo () override
MoveElementsCommand::redo.
Definition at line 230 of file diagramcommands.cpp.
References diagram, first_redo, m_anim_group, move(), and movement.
setupAnimation()
void MoveElementsCommand::setupAnimation (QObject * target, const QByteArray & propertyName, const QVariant & start, const QVariant & end) private
MoveElementsCommand::setupAnimation Set up the animation for this undo command.
Parameters
target object to anim
propertyName property to animate
start value at start
end value at end
Definition at line 298 of file diagramcommands.cpp.
References m_anim_group.
Referenced by move().
undo()
void MoveElementsCommand::undo () override
MoveElementsCommand::undo.
Definition at line 220 of file diagramcommands.cpp.
References diagram, and m_anim_group.
Member Data Documentation
content_to_move
DiagramContent MoveElementsCommand::content_to_move private
moved content
Definition at line 158 of file diagramcommands.h.
Referenced by move(), and MoveElementsCommand().
diagram
Diagram* MoveElementsCommand::diagram private
diagram the movement takes place on.
Definition at line 156 of file diagramcommands.h.
Referenced by redo(), and undo().
first_redo
bool MoveElementsCommand::first_redo private
prevent the first call to redo()
Definition at line 164 of file diagramcommands.h.
Referenced by redo().
m_anim_group
QParallelAnimationGroup* MoveElementsCommand::m_anim_group private
animation group
Definition at line 162 of file diagramcommands.h.
Referenced by redo(), setupAnimation(), undo(), and ~MoveElementsCommand().
movement
QPointF MoveElementsCommand::movement private
applied movement
Definition at line 160 of file diagramcommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
diagramcommands.h
diagramcommands.cpp