QElectroTech: ESEventAddDynamicTextField Class Reference
ESEventAddDynamicTextField Class Reference
The ESEventAddDynamicTextField class This ESEvent manage creation of dynamic text field in an ElementScene.
#include <eseventadddynamictextfield.h>
Public Member Functions
ESEventAddDynamicTextField (ElementScene *scene)
ESEventAddDynamicTextField::ESEventAddDynamicTextField.
~ESEventAddDynamicTextField () override
ESEventAddDynamicTextField::~ESEventAddDynamicTextField.
bool mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
ESEventAddDynamicTextField::mouseMoveEvent.
bool mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
ESEventAddDynamicTextField::mouseReleaseEvent.
Public Member Functions inherited from ESEventInterface
ESEventInterface (ElementScene *scene)
virtual ~ESEventInterface ()
ESEventInterface::~ESEventInterface Destructor.
void init ()
ESEventInterface::init Init this event interface.
virtual bool mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
virtual bool mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual bool wheelEvent (QGraphicsSceneWheelEvent *event)
virtual bool keyPressEvent (QKeyEvent *event)
ESEventInterface::keyPressEvent By default, press escape key abort the curent action.
virtual bool KeyReleaseEvent (QKeyEvent *event)
virtual bool isRunning () const
virtual bool isFinish () const
Private Attributes
PartDynamicTextField * m_text
Additional Inherited Members
Protected Member Functions inherited from ESEventInterface
void updateHelpCross (const QPointF &p)
Protected Attributes inherited from ESEventInterface
ElementScene * m_scene
QETElementEditor * m_editor
QGraphicsLineItem * m_help_horiz
QGraphicsLineItem * m_help_verti
bool m_running
bool m_abort
Detailed Description
The ESEventAddDynamicTextField class This ESEvent manage creation of dynamic text field in an ElementScene.
Definition at line 31 of file eseventadddynamictextfield.h.
Constructor & Destructor Documentation
ESEventAddDynamicTextField()
ESEventAddDynamicTextField::ESEventAddDynamicTextField (ElementScene * scene)
ESEventAddDynamicTextField::ESEventAddDynamicTextField.
Parameters
scene
Definition at line 29 of file eseventadddynamictextfield.cpp.
References ESEventInterface::m_editor, ESEventInterface::m_running, ESEventInterface::m_scene, and m_text.
~ESEventAddDynamicTextField()
ESEventAddDynamicTextField::~ESEventAddDynamicTextField () override
ESEventAddDynamicTextField::~ESEventAddDynamicTextField.
Definition at line 40 of file eseventadddynamictextfield.cpp.
References m_text.
Member Function Documentation
mouseMoveEvent()
bool ESEventAddDynamicTextField::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override virtual
ESEventAddDynamicTextField::mouseMoveEvent.
Parameters
event
Returns
Reimplemented from ESEventInterface.
Definition at line 49 of file eseventadddynamictextfield.cpp.
References ESEventInterface::m_scene, m_text, ElementScene::snapToGrid(), and ESEventInterface::updateHelpCross().
mouseReleaseEvent()
bool ESEventAddDynamicTextField::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
ESEventAddDynamicTextField::mouseReleaseEvent.
Parameters
event
Returns
Reimplemented from ESEventInterface.
Definition at line 62 of file eseventadddynamictextfield.cpp.
References ESEventInterface::m_editor, ESEventInterface::m_running, ESEventInterface::m_scene, m_text, ElementScene::snapToGrid(), QET::Icons::tr, and ElementScene::undoStack().
Member Data Documentation
m_text
PartDynamicTextField* ESEventAddDynamicTextField::m_text private
Definition at line 41 of file eseventadddynamictextfield.h.
Referenced by ESEventAddDynamicTextField(), mouseMoveEvent(), mouseReleaseEvent(), and ~ESEventAddDynamicTextField().
The documentation for this class was generated from the following files:
eseventadddynamictextfield.h
eseventadddynamictextfield.cpp