QElectroTech: LineEditor Class Reference
LineEditor Class Reference
#include <lineeditor.h>
Public Slots
void updateLineEndType1 ()
Met a jour le type de la premiere extremite.
void updateLineEndLength1 ()
Met a jour la longueur de la premiere extremite.
void updateLineEndType2 ()
Met a jour le type de la seconde extremite.
void updateLineEndLength2 ()
Met a jour la longueur de la seconde extremite.
void lineEditingFinishedX1 ()
void lineEditingFinishedY1 ()
void lineEditingFinishedX2 ()
void lineEditingFinishedY2 ()
void updateForm () override
LineEditor::updateForm Update the value of the widgets.
Public Member Functions
LineEditor (QETElementEditor *, PartLine *=nullptr, QWidget *=nullptr)
~LineEditor () override
Destructeur.
bool setPart (CustomElementPart *) override
LineEditor::setPart Specifie to this editor the part to edit. Note that an editor can accept or refuse to edit a part. This editor accept only PartLine.
bool setParts (QList< CustomElementPart * > parts) override
CustomElementPart * currentPart () const override
QList< CustomElementPart * > currentParts () const override
QPointF editedP1 () const
LineEditor::editedP1.
QPointF editedP2 () const
LineEditor::editedP2.
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
virtual void updateForm ()=0
Private Member Functions
LineEditor (const LineEditor &)
void activeConnections (bool)
LineEditor::activeConnections Enable/disable connection between editor widget and slot editingFinished True == enable | false == disable.
void setUpChangeConnections ()
setUpChangeConnections Setup the connection from the line(s) to the widget, to update it when the line(s) are changed (moved ...)
void disconnectChangeConnections ()
Private Attributes
PartLine * part
StyleEditor * style_
QDoubleSpinBox * x1
QDoubleSpinBox * y1
QDoubleSpinBox * x2
QDoubleSpinBox * y2
QComboBox * end1_type
QComboBox * end2_type
QDoubleSpinBox * end1_length
QDoubleSpinBox * end2_length
bool m_locked
QList< QMetaObject::Connection > m_change_connections
Detailed Description
This class provides a widget to edit lines within the element editor.
Definition at line 31 of file lineeditor.h.
Constructor & Destructor Documentation
LineEditor() [1/2]
LineEditor::LineEditor (QETElementEditor * editor, PartLine * line = nullptr, QWidget * parent = nullptr)
Constructeur
Parameters
editor L'editeur d'element concerne
line La ligne a editer
parent le Widget parent
Definition at line 32 of file lineeditor.cpp.
References Qet::Circle, Qet::Diamond, end1_length, end1_type, end2_length, end2_type, QET::Icons::EndLineCircle, QET::Icons::EndLineDiamond, QET::Icons::EndLineNone, QET::Icons::EndLineSimple, QET::Icons::EndLineTriangle, Qet::None, Qet::Simple, style_, QET::Icons::tr, Qet::Triangle, updateForm(), x1, x2, y1, and y2.
~LineEditor()
LineEditor::~LineEditor () override
Destructeur.
Definition at line 92 of file lineeditor.cpp.
LineEditor() [2/2]
LineEditor::LineEditor (const LineEditor &) private
Member Function Documentation
activeConnections()
void LineEditor::activeConnections (bool active) private
LineEditor::activeConnections Enable/disable connection between editor widget and slot editingFinished True == enable | false == disable.
Parameters
active
Definition at line 395 of file lineeditor.cpp.
References end1_length, end1_type, end2_length, end2_type, lineEditingFinishedX1(), lineEditingFinishedX2(), lineEditingFinishedY1(), lineEditingFinishedY2(), updateLineEndLength1(), updateLineEndLength2(), updateLineEndType1(), updateLineEndType2(), x1, x2, y1, and y2.
Referenced by updateForm().
currentPart()
CustomElementPart * LineEditor::currentPart () const override virtual
Returns
la primitive actuellement editee, ou 0 si ce widget n'en edite pas
Implements ElementItemEditor.
Definition at line 158 of file lineeditor.cpp.
References part.
currentParts()
QList< CustomElementPart * > LineEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 162 of file lineeditor.cpp.
References StyleEditor::currentParts(), and style_.
disconnectChangeConnections()
void LineEditor::disconnectChangeConnections () private
Definition at line 104 of file lineeditor.cpp.
References m_change_connections.
Referenced by setPart().
editedP1()
QPointF LineEditor::editedP1 () const
LineEditor::editedP1.
Returns
The edited P1 in item coordinate
Definition at line 170 of file lineeditor.cpp.
References part, x1, and y1.
editedP2()
QPointF LineEditor::editedP2 () const
LineEditor::editedP2.
Returns
The edited P2 in item coordinate
Definition at line 178 of file lineeditor.cpp.
References part, x2, and y2.
lineEditingFinishedX1
void LineEditor::lineEditingFinishedX1 () slot
Definition at line 268 of file lineeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, part, CustomElementGraphicPart::property(), style_, QET::Icons::tr, ElementScene::undoStack(), x1, and y1.
Referenced by activeConnections().
lineEditingFinishedX2
void LineEditor::lineEditingFinishedX2 () slot
Definition at line 318 of file lineeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, part, CustomElementGraphicPart::property(), style_, QET::Icons::tr, ElementScene::undoStack(), x2, and y2.
Referenced by activeConnections().
lineEditingFinishedY1
void LineEditor::lineEditingFinishedY1 () slot
Definition at line 293 of file lineeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, part, CustomElementGraphicPart::property(), style_, QET::Icons::tr, ElementScene::undoStack(), x1, and y1.
Referenced by activeConnections().
lineEditingFinishedY2
void LineEditor::lineEditingFinishedY2 () slot
Definition at line 343 of file lineeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, part, CustomElementGraphicPart::property(), style_, QET::Icons::tr, ElementScene::undoStack(), x2, and y2.
Referenced by activeConnections().
setPart()
bool LineEditor::setPart (CustomElementPart * new_part) override virtual
LineEditor::setPart Specifie to this editor the part to edit. Note that an editor can accept or refuse to edit a part. This editor accept only PartLine.
Parameters
new_part
Returns
Implements ElementItemEditor.
Definition at line 119 of file lineeditor.cpp.
References disconnectChangeConnections(), part, setUpChangeConnections(), and updateForm().
Referenced by setParts().
setParts()
bool LineEditor::setParts (QList< CustomElementPart * > parts) override virtual
Reimplemented from ElementItemEditor.
Definition at line 145 of file lineeditor.cpp.
References setPart(), StyleEditor::setParts(), and style_.
setUpChangeConnections()
void LineEditor::setUpChangeConnections () private
setUpChangeConnections Setup the connection from the line(s) to the widget, to update it when the line(s) are changed (moved ...)
Definition at line 95 of file lineeditor.cpp.
References PartLine::firstEndLengthChanged(), PartLine::firstEndTypeChanged(), PartLine::lineChanged(), m_change_connections, part, PartLine::secondEndLengthChanged(), PartLine::secondEndTypeChanged(), and updateForm().
Referenced by setPart().
updateForm
void LineEditor::updateForm () override slot
LineEditor::updateForm Update the value of the widgets.
Definition at line 372 of file lineeditor.cpp.
References activeConnections(), end1_length, end1_type, end2_length, end2_type, part, x1, x2, y1, and y2.
Referenced by LineEditor(), setPart(), and setUpChangeConnections().
updateLineEndLength1
void LineEditor::updateLineEndLength1 () slot
Met a jour la longueur de la premiere extremite.
Definition at line 204 of file lineeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), end1_length, m_locked, part, CustomElementGraphicPart::property(), style_, QET::Icons::tr, and ElementScene::undoStack().
Referenced by activeConnections().
updateLineEndLength2
void LineEditor::updateLineEndLength2 () slot
Met a jour la longueur de la seconde extremite.
Definition at line 247 of file lineeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), end2_length, m_locked, part, CustomElementGraphicPart::property(), style_, QET::Icons::tr, and ElementScene::undoStack().
Referenced by activeConnections().
updateLineEndType1
void LineEditor::updateLineEndType1 () slot
Met a jour le type de la premiere extremite.
Definition at line 183 of file lineeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), end1_type, m_locked, part, CustomElementGraphicPart::property(), style_, QET::Icons::tr, and ElementScene::undoStack().
Referenced by activeConnections().
updateLineEndType2
void LineEditor::updateLineEndType2 () slot
Met a jour le type de la seconde extremite.
Definition at line 226 of file lineeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), end2_type, m_locked, part, CustomElementGraphicPart::property(), style_, QET::Icons::tr, and ElementScene::undoStack().
Referenced by activeConnections().
Member Data Documentation
end1_length
QDoubleSpinBox* LineEditor::end1_length private
Definition at line 47 of file lineeditor.h.
Referenced by activeConnections(), LineEditor(), updateForm(), and updateLineEndLength1().
end1_type
QComboBox* LineEditor::end1_type private
Definition at line 46 of file lineeditor.h.
Referenced by activeConnections(), LineEditor(), updateForm(), and updateLineEndType1().
end2_length
QDoubleSpinBox * LineEditor::end2_length private
Definition at line 47 of file lineeditor.h.
Referenced by activeConnections(), LineEditor(), updateForm(), and updateLineEndLength2().
end2_type
QComboBox * LineEditor::end2_type private
Definition at line 46 of file lineeditor.h.
Referenced by activeConnections(), LineEditor(), updateForm(), and updateLineEndType2().
m_change_connections
QList<QMetaObject::Connection> LineEditor::m_change_connections private
Definition at line 49 of file lineeditor.h.
Referenced by disconnectChangeConnections(), and setUpChangeConnections().
m_locked
bool LineEditor::m_locked private
Definition at line 48 of file lineeditor.h.
Referenced by lineEditingFinishedX1(), lineEditingFinishedX2(), lineEditingFinishedY1(), lineEditingFinishedY2(), updateLineEndLength1(), updateLineEndLength2(), updateLineEndType1(), and updateLineEndType2().
part
PartLine* LineEditor::part private
Definition at line 43 of file lineeditor.h.
Referenced by currentPart(), editedP1(), editedP2(), lineEditingFinishedX1(), lineEditingFinishedX2(), lineEditingFinishedY1(), lineEditingFinishedY2(), setPart(), setUpChangeConnections(), updateForm(), updateLineEndLength1(), updateLineEndLength2(), updateLineEndType1(), and updateLineEndType2().
style_
StyleEditor* LineEditor::style_ private
Definition at line 44 of file lineeditor.h.
Referenced by currentParts(), lineEditingFinishedX1(), lineEditingFinishedX2(), lineEditingFinishedY1(), lineEditingFinishedY2(), LineEditor(), setParts(), updateLineEndLength1(), updateLineEndLength2(), updateLineEndType1(), and updateLineEndType2().
x1
QDoubleSpinBox* LineEditor::x1 private
Definition at line 45 of file lineeditor.h.
Referenced by activeConnections(), editedP1(), lineEditingFinishedX1(), lineEditingFinishedY1(), LineEditor(), and updateForm().
x2
QDoubleSpinBox * LineEditor::x2 private
Definition at line 45 of file lineeditor.h.
Referenced by activeConnections(), editedP2(), lineEditingFinishedX2(), lineEditingFinishedY2(), LineEditor(), and updateForm().
y1
QDoubleSpinBox * LineEditor::y1 private
Definition at line 45 of file lineeditor.h.
Referenced by activeConnections(), editedP1(), lineEditingFinishedX1(), lineEditingFinishedY1(), LineEditor(), and updateForm().
y2
QDoubleSpinBox * LineEditor::y2 private
Definition at line 45 of file lineeditor.h.
Referenced by activeConnections(), editedP2(), lineEditingFinishedX2(), lineEditingFinishedY2(), LineEditor(), and updateForm().
The documentation for this class was generated from the following files:
lineeditor.h
lineeditor.cpp