QElectroTech: DiagramEventAddElement Class Reference
DiagramEventAddElement Class Reference
The DiagramEventAddElement class This diagram event add a new element, for each left click button at the position of click. Space key rotate current element by 90°, right click button finish this event.
#include <diagrameventaddelement.h>
Public Member Functions
DiagramEventAddElement (ElementsLocation &location, Diagram *diagram, QPointF pos=QPointF(0, 0))
DiagramEventAddElement::DiagramEventAddElement Defaut constructor.
~DiagramEventAddElement () override
DiagramEventAddElement::~DiagramEventAddElement Destructor Enable context menu for each view of diagram.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddElement::mouseMoveEvent Move the element to new pos of mouse the event is always accepted.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddElement::mousePressEvent Do nothing, but return true for not transit the event to other thing in diagram. the event is always accepted.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddElement::mouseReleaseEvent Right button finish this event (isRunning = false) and emit finish. Left button add an element to diagram the event is always accepted.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddElement::mouseDoubleClickEvent If mouse left double clic, finish this event (isRunning = false) and emit finish the event is always accepted.
void keyPressEvent (QKeyEvent *event) override
DiagramEventAddElement::keyPressEvent Press space key rotate the element to 90° (return true) else call DiagramEventInterface::keyPressEvent(event), and return the value.
void init () override
DiagramEventAddElement::init Init this event.
Public Member Functions inherited from DiagramEventInterface
DiagramEventInterface (Diagram *diagram)
~DiagramEventInterface () override=0
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual bool isRunning () const
Private Member Functions
bool buildElement ()
DiagramEventAddElement::buildElement Build the element, if the element is build successfully, we return true, otherwise false.
void addElement ()
DiagramEventAddElement::addElement Add an element at the current pos en current rotation, if project autoconductor option is enable, and the element can be wired, we do it.
Private Attributes
ElementsLocation m_location
Element * m_element
QString m_integrate_path
Additional Inherited Members
Signals inherited from DiagramEventInterface
void finish ()
Protected Attributes inherited from DiagramEventInterface
Diagram * m_diagram
bool m_running
bool m_abort
Detailed Description
The DiagramEventAddElement class This diagram event add a new element, for each left click button at the position of click. Space key rotate current element by 90°, right click button finish this event.
Definition at line 31 of file diagrameventaddelement.h.
Constructor & Destructor Documentation
DiagramEventAddElement()
DiagramEventAddElement::DiagramEventAddElement (ElementsLocation & location, Diagram * diagram, QPointF pos = QPointF(0,0))
DiagramEventAddElement::DiagramEventAddElement Defaut constructor.
Parameters
location :location of diagram
diagram : diagram owner of this event
pos : first pos of item (optional, by defaut QPointF(0,0))
Definition at line 33 of file diagrameventaddelement.cpp.
References buildElement(), ElementsLocation::exist(), init(), ElementsLocation::isElement(), DiagramEventInterface::m_diagram, m_element, and DiagramEventInterface::m_running.
~DiagramEventAddElement()
DiagramEventAddElement::~DiagramEventAddElement () override
DiagramEventAddElement::~DiagramEventAddElement Destructor Enable context menu for each view of diagram.
Definition at line 60 of file diagrameventaddelement.cpp.
References DiagramEventInterface::m_diagram, m_element, and Diagram::removeItem().
Member Function Documentation
addElement()
void DiagramEventAddElement::addElement () private
DiagramEventAddElement::addElement Add an element at the current pos en current rotation, if project autoconductor option is enable, and the element can be wired, we do it.
Definition at line 203 of file diagrameventaddelement.cpp.
References QET::Icons::Conductor, Element::freezeNewAddedElement(), Diagram::freezeNewConductors(), ElementFactory::Instance(), QETProject::isFreezeNewConductors(), Element::m_converted_text_from_xml_description, DiagramEventInterface::m_diagram, Element::m_dynamic_text_list, m_element, m_integrate_path, m_location, Element::name(), ConductorAutoNumerotation::numerate(), Diagram::project(), Conductor::setFreezeLabel(), Element::setUpFormula(), and QET::Icons::tr.
Referenced by mouseReleaseEvent().
buildElement()
bool DiagramEventAddElement::buildElement () private
DiagramEventAddElement::buildElement Build the element, if the element is build successfully, we return true, otherwise false.
Definition at line 175 of file diagrameventaddelement.cpp.
References ElementsLocation::exist(), QETProject::importElement(), ElementFactory::Instance(), DiagramEventInterface::m_diagram, m_element, m_integrate_path, m_location, Diagram::project(), and ElementsLocation::projectCollectionPath().
Referenced by DiagramEventAddElement().
init()
void DiagramEventAddElement::init () override virtual
DiagramEventAddElement::init Init this event.
Reimplemented from DiagramEventInterface.
Definition at line 165 of file diagrameventaddelement.cpp.
References DiagramEventInterface::m_diagram.
Referenced by DiagramEventAddElement().
keyPressEvent()
void DiagramEventAddElement::keyPressEvent (QKeyEvent * event) override virtual
DiagramEventAddElement::keyPressEvent Press space key rotate the element to 90° (return true) else call DiagramEventInterface::keyPressEvent(event), and return the value.
Parameters
event
Reimplemented from DiagramEventInterface.
Definition at line 149 of file diagrameventaddelement.cpp.
References DiagramEventInterface::keyPressEvent(), and m_element.
mouseDoubleClickEvent()
void DiagramEventAddElement::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddElement::mouseDoubleClickEvent If mouse left double clic, finish this event (isRunning = false) and emit finish the event is always accepted.
Parameters
event
Reimplemented from DiagramEventInterface.
Definition at line 129 of file diagrameventaddelement.cpp.
References DiagramEventInterface::finish(), DiagramEventInterface::m_diagram, m_element, DiagramEventInterface::m_running, and Diagram::removeItem().
mouseMoveEvent()
void DiagramEventAddElement::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddElement::mouseMoveEvent Move the element to new pos of mouse the event is always accepted.
Parameters
event
Reimplemented from DiagramEventInterface.
Definition at line 77 of file diagrameventaddelement.cpp.
References m_element, QetGraphicsItem::setPos(), and Diagram::snapToGrid().
mousePressEvent()
void DiagramEventAddElement::mousePressEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddElement::mousePressEvent Do nothing, but return true for not transit the event to other thing in diagram. the event is always accepted.
Parameters
event
Reimplemented from DiagramEventInterface.
Definition at line 91 of file diagrameventaddelement.cpp.
mouseReleaseEvent()
void DiagramEventAddElement::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddElement::mouseReleaseEvent Right button finish this event (isRunning = false) and emit finish. Left button add an element to diagram the event is always accepted.
Parameters
event
Reimplemented from DiagramEventInterface.
Definition at line 102 of file diagrameventaddelement.cpp.
References addElement(), DiagramEventInterface::finish(), DiagramEventInterface::m_diagram, m_element, DiagramEventInterface::m_running, and Diagram::removeItem().
Member Data Documentation
m_element
Element* DiagramEventAddElement::m_element private
Definition at line 52 of file diagrameventaddelement.h.
Referenced by addElement(), buildElement(), DiagramEventAddElement(), keyPressEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mouseReleaseEvent(), and ~DiagramEventAddElement().
m_integrate_path
QString DiagramEventAddElement::m_integrate_path private
Definition at line 53 of file diagrameventaddelement.h.
Referenced by addElement(), and buildElement().
m_location
ElementsLocation DiagramEventAddElement::m_location private
Definition at line 51 of file diagrameventaddelement.h.
Referenced by addElement(), and buildElement().
The documentation for this class was generated from the following files:
diagrameventaddelement.h
diagrameventaddelement.cpp