QElectroTech: ExportDialog Class Reference
ExportDialog Class Reference
#include <exportdialog.h>
Classes
class ExportDiagramLine
Public Slots
void slot_correctWidth (int)
void slot_correctHeight (int)
void slot_keepRatioChanged (int)
void slot_resetSize (int)
void slot_export ()
void slot_changeUseBorder ()
void slot_checkDiagramsCount ()
void slot_changeFilesExtension (bool=false)
void slot_previewDiagram (int)
void slot_exportToClipBoard (int)
void slot_selectAllClicked ()
void slot_deSelectAllClicked ()
Public Member Functions
ExportDialog (QETProject *, QWidget *=nullptr)
~ExportDialog () override
int diagramsToExportCount () const
Static Public Member Functions
static QPointF rotation_transformed (qreal, qreal, qreal, qreal, qreal)
Private Member Functions
ExportDialog (const ExportDialog &)
QWidget * initDiagramsListPart ()
void saveReloadDiagramParameters (Diagram *, bool=true)
void generateSvg (Diagram *, int, int, bool, QIODevice &)
void generateDxf (Diagram *, int, int, bool, QString &)
QImage generateImage (Diagram *, int, int, bool)
void exportDiagram (ExportDiagramLine *)
qreal diagramRatio (Diagram *)
QSize diagramSize (Diagram *)
Private Attributes
QHash< int, ExportDialog::ExportDiagramLine * > diagram_lines_
QGridLayout * diagrams_list_layout_
ExportPropertiesWidget * epw
QDialogButtonBox * buttons
QPushButton * selectAll
QPushButton * deSelectAll
QSignalMapper * preview_mapper_
QSignalMapper * width_mapper_
QSignalMapper * height_mapper_
QSignalMapper * ratio_mapper_
QSignalMapper * reset_mapper_
QSignalMapper * clipboard_mapper_
QETProject * project_
Detailed Description
This class provides a dialog enabling users to export 1 to n diagrams from a project as image files, with features like preview, copy to clipboard, resize, etc.
Definition at line 30 of file exportdialog.h.
Constructor & Destructor Documentation
ExportDialog() [1/2]
ExportDialog::ExportDialog (QETProject * project, QWidget * parent = nullptr)
Constructeur
Parameters
project Le projet a exporter
parent Le Widget parent de ce dialogue
Definition at line 45 of file exportdialog.cpp.
References buttons, QET::Icons::Cancel, ExportProperties::defaultExportProperties(), deSelectAll, ExportProperties::destination_directory, epw, QET::Horizontal, initDiagramsListPart(), project_, selectAll, slot_changeFilesExtension(), slot_changeUseBorder(), slot_deSelectAllClicked(), slot_export(), slot_selectAllClicked(), and QET::Icons::tr.
~ExportDialog()
ExportDialog::~ExportDialog () override
Destructeur - ne fait rien
Definition at line 107 of file exportdialog.cpp.
ExportDialog() [2/2]
ExportDialog::ExportDialog (const ExportDialog &) private
Member Function Documentation
diagramRatio()
qreal ExportDialog::diagramRatio (Diagram * diagram) private
Parameters
diagram Un schema
Returns
le rapport largeur / hauteur du schema
Definition at line 206 of file exportdialog.cpp.
References diagramSize().
Referenced by slot_correctHeight(), and slot_correctWidth().
diagramSize()
QSize ExportDialog::diagramSize (Diagram * diagram) private
Parameters
diagram Un schema
Returns
les dimensions du schema, en tenant compte du type d'export : cadre ou elements
Definition at line 217 of file exportdialog.cpp.
References QET::BorderArea, and epw.
Referenced by diagramRatio(), initDiagramsListPart(), and slot_resetSize().
diagramsToExportCount()
int ExportDialog::diagramsToExportCount () const
Returns
le nombre de schemas coches (donc a exporter)
Definition at line 113 of file exportdialog.cpp.
References diagram_lines_.
Referenced by slot_checkDiagramsCount().
exportDiagram()
void ExportDialog::exportDiagram (ExportDiagramLine * diagram_line) private
Exporte un schema
Parameters
diagram_line La ligne decrivant le schema a exporter et la maniere de l'exporter
Definition at line 752 of file exportdialog.cpp.
References QET::QetMessageBox::critical(), ExportProperties::destination_directory, epw, ExportProperties::format, generateDxf(), generateImage(), generateSvg(), and QET::Icons::tr.
Referenced by slot_export().
generateDxf()
void ExportDialog::generateDxf (Diagram * diagram, int width, int height, bool keep_aspect_ratio, QString & file_path) private
Exporte le schema en DXF
Parameters
diagram Schema a exporter en DXF
width Largeur de l'export DXF
height Hauteur de l'export DXF
keep_aspect_ratio True pour conserver le ratio, false sinon
file_path
Definition at line 402 of file exportdialog.cpp.
References Createdxf::drawArcEllipse(), Createdxf::drawCircle(), Createdxf::drawLine(), Createdxf::drawRectangle(), Createdxf::drawText(), Createdxf::dxfBegin(), Createdxf::dxfEnd(), epw, ElementPictureFactory::getPrimitives(), ElementPictureFactory::instance(), Element::location(), Diagram::margin, QetShapeItem::pen, Conductor::pos, rotation_transformed(), saveReloadDiagramParameters(), Createdxf::sheetHeight, Createdxf::sheetWidth, QetShapeItem::toDXF(), Createdxf::xScale, and Createdxf::yScale.
Referenced by exportDiagram().
generateImage()
QImage ExportDialog::generateImage (Diagram * diagram, int width, int height, bool keep_aspect_ratio) private
Genere l'image a exporter
Parameters
diagram Schema a exporter en SVG
width Largeur de l'export
height Hauteur de l'export
keep_aspect_ratio True pour conserver le ratio, false sinon
Returns
l'image a exporter
Definition at line 330 of file exportdialog.cpp.
References saveReloadDiagramParameters().
Referenced by exportDiagram(), slot_exportToClipBoard(), and slot_previewDiagram().
generateSvg()
void ExportDialog::generateSvg (Diagram * diagram, int width, int height, bool keep_aspect_ratio, QIODevice & io_device) private
Exporte le schema en SVG
Parameters
diagram Schema a exporter en SVG
width Largeur de l'export SVG
height Hauteur de l'export SVG
keep_aspect_ratio True pour conserver le ratio, false sinon
io_device Peripherique de sortie pour le code SVG (souvent : un fichier)
Definition at line 372 of file exportdialog.cpp.
References saveReloadDiagramParameters().
Referenced by exportDiagram(), and slot_exportToClipBoard().
initDiagramsListPart()
QWidget * ExportDialog::initDiagramsListPart () private
Met en place la liste des schemas
Returns
Le widget representant la liste des schemas
Definition at line 125 of file exportdialog.cpp.
References clipboard_mapper_, diagram_lines_, diagrams_list_layout_, diagramSize(), height_mapper_, preview_mapper_, project_, ratio_mapper_, reset_mapper_, slot_checkDiagramsCount(), slot_correctHeight(), slot_correctWidth(), slot_exportToClipBoard(), slot_keepRatioChanged(), slot_previewDiagram(), slot_resetSize(), QET::Icons::tr, and width_mapper_.
Referenced by ExportDialog().
rotation_transformed()
QPointF ExportDialog::rotation_transformed (qreal px, qreal py, qreal origin_x, qreal origin_y, qreal angle) static
Definition at line 668 of file exportdialog.cpp.
Referenced by Createdxf::drawArcEllipse(), and generateDxf().
saveReloadDiagramParameters()
void ExportDialog::saveReloadDiagramParameters (Diagram * diagram, bool save = true) private
Sauve ou restaure les parametres du schema
Parameters
diagram Schema dont on sauve ou restaure les parametres
save true pour memoriser les parametres du schema et appliquer ceux definis par le formulaire, false pour restaurer les parametres
Definition at line 352 of file exportdialog.cpp.
References epw.
Referenced by generateDxf(), generateImage(), and generateSvg().
slot_changeFilesExtension
void ExportDialog::slot_changeFilesExtension (bool force_extension = false) slot
Modifie les extensions des fichiers en fonction du format selectionne
Parameters
force_extension true pour ajouter l'extension si elle n'est pas presente, false pour se contenter de la modifier si elle est incorrecte.
Definition at line 850 of file exportdialog.cpp.
References diagram_lines_, epw, and ExportPropertiesWidget::format.
Referenced by ExportDialog().
slot_changeUseBorder
void ExportDialog::slot_changeUseBorder () slot
Slot appele lorsque l'utilisateur change la zone du schema qui doit etre exportee. Il faut alors ajuster les dimensions des schemas.
Definition at line 822 of file exportdialog.cpp.
References diagram_lines_, and slot_correctHeight().
Referenced by ExportDialog().
slot_checkDiagramsCount
void ExportDialog::slot_checkDiagramsCount () slot
Ce slot est appele quand un schema a ete coche ou decoche. Il active ou desactive le bouton "Exporter" en fonction du nombre de schemas coches, et il garde au plus un schema coche si on exporte vers le presse-papier.
Definition at line 840 of file exportdialog.cpp.
References buttons, and diagramsToExportCount().
Referenced by initDiagramsListPart().
slot_correctHeight
void ExportDialog::slot_correctHeight (int diagram_id) slot
Cette methode ajuste la hauteur d'un des schemas a exporter en fonction de sa largeur si et seulement si l'option "Conserver les proportions" est activee pour ce schema.
Parameters
diagram_id numero du schema concerne
Definition at line 260 of file exportdialog.cpp.
References diagram_lines_, and diagramRatio().
Referenced by initDiagramsListPart(), slot_changeUseBorder(), and slot_keepRatioChanged().
slot_correctWidth
void ExportDialog::slot_correctWidth (int diagram_id) slot
Cette methode ajuste la largeur d'un des schemas a exporter en fonction de sa hauteur si et seulement si l'option "Conserver les proportions" est activee pour ce schema.
Parameters
diagram_id numero du schema concerne
Definition at line 237 of file exportdialog.cpp.
References diagram_lines_, and diagramRatio().
Referenced by initDiagramsListPart().
slot_deSelectAllClicked
void ExportDialog::slot_deSelectAllClicked () slot
Definition at line 194 of file exportdialog.cpp.
References diagram_lines_.
Referenced by ExportDialog().
slot_export
void ExportDialog::slot_export () slot
Slot effectuant les exports apres la validation du dialogue.
Definition at line 695 of file exportdialog.cpp.
References diagram_lines_, epw, exportDiagram(), QET::Icons::tr, and QET::QetMessageBox::warning().
Referenced by ExportDialog().
slot_exportToClipBoard
void ExportDialog::slot_exportToClipBoard (int diagram_id) slot
Cette methode exporte un schema vers le presse-papier
Parameters
diagram_id numero du schema a previsualiser
Definition at line 933 of file exportdialog.cpp.
References diagram_lines_, epw, ExportPropertiesWidget::format, generateImage(), and generateSvg().
Referenced by initDiagramsListPart().
slot_keepRatioChanged
void ExportDialog::slot_keepRatioChanged (int diagram_id) slot
Prend en compte le fait qu'il faut desormais conserver ou non les proportions d'un des schemas
Parameters
diagram_id numero du schema concerne
Definition at line 282 of file exportdialog.cpp.
References diagram_lines_, QET::Icons::ObjectLocked, QET::Icons::ObjectUnlocked, and slot_correctHeight().
Referenced by initDiagramsListPart().
slot_previewDiagram
void ExportDialog::slot_previewDiagram (int diagram_id) slot
Cette methode fait apparaitre un dialogue permettant de previsualiser un des schemas a exporter
Parameters
diagram_id numero du schema a previsualiser
Definition at line 884 of file exportdialog.cpp.
References buttons, diagram_lines_, generateImage(), and QET::Icons::tr.
Referenced by initDiagramsListPart().
slot_resetSize
void ExportDialog::slot_resetSize (int diagram_id) slot
Reinitialise les dimensions d'un des schemas
Parameters
diagram_id numero du schema concerne
Definition at line 305 of file exportdialog.cpp.
References diagram_lines_, and diagramSize().
Referenced by initDiagramsListPart().
slot_selectAllClicked
void ExportDialog::slot_selectAllClicked () slot
Definition at line 188 of file exportdialog.cpp.
References diagram_lines_.
Referenced by ExportDialog().
Member Data Documentation
buttons
QDialogButtonBox* ExportDialog::buttons private
Definition at line 71 of file exportdialog.h.
Referenced by ExportDialog(), slot_checkDiagramsCount(), and slot_previewDiagram().
clipboard_mapper_
QSignalMapper* ExportDialog::clipboard_mapper_ private
Definition at line 82 of file exportdialog.h.
Referenced by initDiagramsListPart().
deSelectAll
QPushButton* ExportDialog::deSelectAll private
Definition at line 74 of file exportdialog.h.
Referenced by ExportDialog().
diagram_lines_
QHash<int, ExportDialog::ExportDiagramLine *> ExportDialog::diagram_lines_ private
Definition at line 67 of file exportdialog.h.
Referenced by diagramsToExportCount(), initDiagramsListPart(), slot_changeFilesExtension(), slot_changeUseBorder(), slot_correctHeight(), slot_correctWidth(), slot_deSelectAllClicked(), slot_export(), slot_exportToClipBoard(), slot_keepRatioChanged(), slot_previewDiagram(), slot_resetSize(), and slot_selectAllClicked().
diagrams_list_layout_
QGridLayout* ExportDialog::diagrams_list_layout_ private
Definition at line 69 of file exportdialog.h.
Referenced by initDiagramsListPart().
epw
ExportPropertiesWidget* ExportDialog::epw private
Definition at line 70 of file exportdialog.h.
Referenced by diagramSize(), exportDiagram(), ExportDialog(), generateDxf(), saveReloadDiagramParameters(), slot_changeFilesExtension(), slot_export(), and slot_exportToClipBoard().
height_mapper_
QSignalMapper* ExportDialog::height_mapper_ private
Definition at line 79 of file exportdialog.h.
Referenced by initDiagramsListPart().
preview_mapper_
QSignalMapper* ExportDialog::preview_mapper_ private
Definition at line 77 of file exportdialog.h.
Referenced by initDiagramsListPart().
project_
QETProject* ExportDialog::project_ private
Definition at line 85 of file exportdialog.h.
Referenced by ExportDialog(), and initDiagramsListPart().
ratio_mapper_
QSignalMapper* ExportDialog::ratio_mapper_ private
Definition at line 80 of file exportdialog.h.
Referenced by initDiagramsListPart().
reset_mapper_
QSignalMapper* ExportDialog::reset_mapper_ private
Definition at line 81 of file exportdialog.h.
Referenced by initDiagramsListPart().
selectAll
QPushButton* ExportDialog::selectAll private
Definition at line 73 of file exportdialog.h.
Referenced by ExportDialog().
width_mapper_
QSignalMapper* ExportDialog::width_mapper_ private
Definition at line 78 of file exportdialog.h.
Referenced by initDiagramsListPart().
The documentation for this class was generated from the following files:
exportdialog.h
exportdialog.cpp