QElectroTech: Terminal Class Reference
Terminal Class Reference
The Terminal class This class represents a terminal of an electrical element, i.e. a possible plug point for conductors. This class handles all mouse events for connecting conductors.
#include <terminal.h>
Public Types
enum { Type = UserType + 1002 }
Signals
void conductorWasAdded (Conductor *conductor)
void conductorWasRemoved (Conductor *conductor)
Public Member Functions
Terminal (QPointF, Qet::Orientation, Element *=nullptr)
Terminal (qreal, qreal, Qet::Orientation, Element *=nullptr)
Terminal (TerminalData *data, Element *e=nullptr)
Terminal (QPointF, Qet::Orientation, QString number, QString name, bool hiddenName, Element *=nullptr)
~Terminal () override
int type () const override
type Enable the use of qgraphicsitem_cast to safely cast a QGraphicsItem into a Terminal
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *) override
Terminal::paint Fonction de dessin des bornes.
void drawHelpLine (bool draw=true)
Terminal::drawHelpLine.
QLineF HelpLine () const
Terminal::HelpLine.
QRectF boundingRect () const override
Terminal::boundingRect.
Terminal * alignedWithTerminal () const
Terminal::alignedWithTerminal If this terminal is aligned with an other terminal and is orientation is opposed return the other terminal else return nullptr.
bool addConductor (Conductor *conductor)
Terminal::addConductor Add a conductor to this terminal.
void removeConductor (Conductor *conductor)
Terminal::removeConductor Remove a conductor from this terminal.
int conductorsCount () const
Terminal::conductorsCount.
Diagram * diagram () const
Terminal::diagram.
Element * parentElement () const
Terminal::parentElement.
QUuid uuid () const
QList< Conductor * > conductors () const
Terminal::conductors.
Qet::Orientation orientation () const
QPointF dockConductor () const
Terminal::dockConductor.
QString number () const
Terminal::number.
QString name () const
Terminal::name.
void setNumber (QString number)
Terminal::setNumber.
void setName (QString name, bool hiddenName)
Terminal::setName.
void updateConductor ()
Terminal::updateConductor Update the path of conductor docked to this terminal.
bool isLinkedTo (Terminal *)
Terminal::isLinkedTo.
bool canBeLinkedTo (Terminal *)
Terminal::canBeLinkedTo Checking if the terminal can be linked to other_terminal or not Reasons for not linable:
bool fromXml (QDomElement &)
Terminal::fromXml Permet de savoir si un element XML represente cette borne. Attention, l'element XML n'est pas verifie.
QDomElement toXml (QDomDocument &) const
Terminal::toXml Methode d'export en XML.
Static Public Member Functions
static bool valideXml (QDomElement &)
Terminal::valideXml Permet de savoir si un element XML represente une borne.
Static Public Attributes
static const qreal terminalSize = 4.0
static const qreal Z = 1000
static QColor neutralColor = QColor(Qt::blue)
default color
static QColor allowedColor = QColor(Qt::darkGreen)
color for legal actions
static QColor warningColor = QColor("#ff8000")
color for allowed but fuzzy or not recommended actions
static QColor forbiddenColor = QColor(Qt::red)
color for forbidden actions
Protected Member Functions
void hoverEnterEvent (QGraphicsSceneHoverEvent *) override
Terminal::hoverEnterEvent Gere l'entree de la souris sur la zone de la Borne.
void hoverMoveEvent (QGraphicsSceneHoverEvent *) override
Terminal::hoverMoveEvent Gere les mouvements de la souris sur la zone de la Borne.
void hoverLeaveEvent (QGraphicsSceneHoverEvent *) override
Terminal::hoverLeaveEvent Gere le fait que la souris sorte de la zone de la Borne.
void mousePressEvent (QGraphicsSceneMouseEvent *) override
Terminal::mousePressEvent Gere le fait qu'on enfonce un bouton de la souris sur la Borne.
void mouseMoveEvent (QGraphicsSceneMouseEvent *) override
Terminal::mouseMoveEvent Gere le fait qu'on bouge la souris sur la Borne.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *) override
Terminal::mouseReleaseEvent.
Private Member Functions
Terminal (const Terminal &)
void init (QString number, QString name, bool hiddenName)
Terminal::init Methode privee pour initialiser la borne.
void init (QPointF pf, Qet::Orientation o, QString number, QString name, bool hiddenName)
Terminal::init Additionaly to the init above, this method stores position and orientation into the data class.
Private Attributes
bool m_draw_help_line {false}
QGraphicsLineItem * m_help_line {nullptr}
QGraphicsLineItem * m_help_line_a {nullptr}
TerminalData * d
Element * parent_element_ {nullptr}
Parent electrical element.
QPointF dock_elmt_
docking point for parent element
QList< Conductor * > conductors_
List of conductors attached to the terminal.
QRectF * br_ {nullptr}
Terminal * previous_terminal_
Last terminal seen through an attached conductor.
bool hovered_
Whether the mouse pointer is hovering the terminal.
QColor hovered_color_
Color used for the hover effect.
QString number_terminal_
Number of Terminal.
QString name_terminal_
Name of Terminal.
bool name_terminal_hidden
Detailed Description
The Terminal class This class represents a terminal of an electrical element, i.e. a possible plug point for conductors. This class handles all mouse events for connecting conductors.
Definition at line 34 of file terminal.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 106 of file terminal.h.
Constructor & Destructor Documentation
Terminal() [1/5]
Terminal::Terminal (QPointF pf, Qet::Orientation o, Element * e = nullptr)
initialise une borne
Parameters
pf position du point d'amarrage pour un conducteur
o orientation de la borne : Qt::Horizontal ou Qt::Vertical
e Element auquel cette borne appartient
Definition at line 103 of file terminal.cpp.
References init().
Terminal() [2/5]
Terminal::Terminal (qreal pf_x, qreal pf_y, Qet::Orientation o, Element * e = nullptr)
initialise une borne
Parameters
pf_x Abscisse du point d'amarrage pour un conducteur
pf_y Ordonnee du point d'amarrage pour un conducteur
o orientation de la borne : Qt::Horizontal ou Qt::Vertical
e Element auquel cette borne appartient
Definition at line 118 of file terminal.cpp.
References init().
Terminal() [3/5]
Terminal::Terminal (TerminalData * data, Element * e = nullptr)
Definition at line 148 of file terminal.cpp.
References d, init(), and TerminalData::setParent().
Terminal() [4/5]
Terminal::Terminal (QPointF pf, Qet::Orientation o, QString num, QString name, bool hiddenName, Element * e = nullptr)
initialise une borne
Parameters
pf position du point d'amarrage pour un conducteur
o orientation de la borne : Qt::Horizontal ou Qt::Vertical
num number of terminal (ex 3 - 4 for NO)
name of terminal
hiddenName hide or show the name
e Element auquel cette borne appartient
Definition at line 135 of file terminal.cpp.
References init(), and name().
~Terminal()
Terminal::~Terminal () override
Destructeur La destruction de la borne entraine la destruction des conducteurs associes.
Definition at line 163 of file terminal.cpp.
References br_, and conductors_.
Terminal() [5/5]
Terminal::Terminal (const Terminal &) private
Member Function Documentation
addConductor()
bool Terminal::addConductor (Conductor * conductor)
Terminal::addConductor Add a conductor to this terminal.
Parameters
conductor : the conductor to add.
Returns
true if the conductor was successfully added
Definition at line 215 of file terminal.cpp.
References conductors_, conductorWasAdded(), Conductor::terminal1, and Conductor::terminal2.
Referenced by Diagram::addItem(), and NewConductorPotentialSelector::NewConductorPotentialSelector().
alignedWithTerminal()
Terminal * Terminal::alignedWithTerminal () const
Terminal::alignedWithTerminal If this terminal is aligned with an other terminal and is orientation is opposed return the other terminal else return nullptr.
Returns
Definition at line 441 of file terminal.cpp.
References diagram(), dockConductor(), HelpLine(), Qet::isOpposed(), QET::lineContainsPoint(), orientation(), and parent_element_.
Referenced by paint().
boundingRect()
QRectF Terminal::boundingRect () const override
Terminal::boundingRect.
Returns
Le rectangle (en precision flottante) delimitant la borne et ses alentours.
Definition at line 418 of file terminal.cpp.
References br_, d, dock_elmt_, and TerminalData::m_pos.
canBeLinkedTo()
bool Terminal::canBeLinkedTo (Terminal * other_terminal)
Terminal::canBeLinkedTo Checking if the terminal can be linked to other_terminal or not Reasons for not linable:
other_terminal is this terminal
this terminal is already connected to other_terminal
Parameters
other_terminal
Returns
true if this terminal can be linked to other_terminal, otherwise false
Definition at line 703 of file terminal.cpp.
References isLinkedTo().
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
conductors()
QList< Conductor * > Terminal::conductors () const
Terminal::conductors.
Returns
La liste des conducteurs lies a cette borne
Definition at line 715 of file terminal.cpp.
References conductors_.
Referenced by Element::AlignedFreeTerminals(), NewConductorPotentialSelector::getPotential(), paint(), relatedConductors(), Conductor::relatedPotentialConductors(), DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements(), and DeleteQGraphicsItemCommand::terminalInSamePotential().
conductorsCount()
int Terminal::conductorsCount () const inline
Terminal::conductorsCount.
Returns
the number of conductors attached to the terminal.
Definition at line 162 of file terminal.h.
References conductors_.
Referenced by mouseMoveEvent().
conductorWasAdded
void Terminal::conductorWasAdded (Conductor * conductor) signal
Referenced by addConductor(), and DynamicElementTextItem::itemChange().
conductorWasRemoved
void Terminal::conductorWasRemoved (Conductor * conductor) signal
Referenced by DynamicElementTextItem::itemChange(), and removeConductor().
diagram()
Diagram * Terminal::diagram () const
Terminal::diagram.
Returns
le Diagram auquel cette borne appartient, ou 0 si cette borne est independant
Definition at line 814 of file terminal.cpp.
Referenced by alignedWithTerminal(), Conductor::Conductor(), HelpLine(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and paint().
dockConductor()
QPointF Terminal::dockConductor () const
Terminal::dockConductor.
Returns
the position, relative to the scene, of the docking point for conductors.
Definition at line 805 of file terminal.cpp.
References d, and TerminalData::m_pos.
Referenced by alignedWithTerminal(), HelpLine(), and paint().
drawHelpLine()
void Terminal::drawHelpLine (bool draw = true)
Terminal::drawHelpLine.
Parameters
draw : true, display the help line false, hide it.
Definition at line 359 of file terminal.cpp.
References m_draw_help_line, m_help_line, and m_help_line_a.
Referenced by Element::displayHelpLine().
fromXml()
bool Terminal::fromXml (QDomElement & terminal)
Terminal::fromXml Permet de savoir si un element XML represente cette borne. Attention, l'element XML n'est pas verifie.
Parameters
terminal Le QDomElement a analyser
Returns
true si la borne "se reconnait" (memes coordonnes, meme orientation), false sinon
Definition at line 788 of file terminal.cpp.
References d, dock_elmt_, TerminalData::m_orientation, name_terminal_, name_terminal_hidden, and number_terminal_.
HelpLine()
QLineF Terminal::HelpLine () const
Terminal::HelpLine.
Returns
a line with coordinate P1 the dock point of conductor and P2 the border of diagram, according to the orientation of terminal The line is in scene coordinate;
Definition at line 386 of file terminal.cpp.
References diagram(), dockConductor(), Qet::East, Qet::North, orientation(), Qet::South, and Qet::West.
Referenced by alignedWithTerminal(), and paint().
hoverEnterEvent()
void Terminal::hoverEnterEvent (QGraphicsSceneHoverEvent *) override protected
Terminal::hoverEnterEvent Gere l'entree de la souris sur la zone de la Borne.
Definition at line 500 of file terminal.cpp.
References hovered_.
hoverLeaveEvent()
void Terminal::hoverLeaveEvent (QGraphicsSceneHoverEvent *) override protected
Terminal::hoverLeaveEvent Gere le fait que la souris sorte de la zone de la Borne.
Definition at line 516 of file terminal.cpp.
References hovered_.
hoverMoveEvent()
void Terminal::hoverMoveEvent (QGraphicsSceneHoverEvent *) override protected
Terminal::hoverMoveEvent Gere les mouvements de la souris sur la zone de la Borne.
Definition at line 509 of file terminal.cpp.
init() [1/2]
void Terminal::init (QPointF pf, Qet::Orientation o, QString number, QString name, bool hiddenName) private
Terminal::init Additionaly to the init above, this method stores position and orientation into the data class.
Parameters
pf
o
number
name
hiddenName
Definition at line 85 of file terminal.cpp.
References d, init(), TerminalData::m_orientation, TerminalData::m_pos, name(), number(), Qet::South, and Qet::West.
init() [2/2]
void Terminal::init (QString number, QString name, bool hiddenName) private
Terminal::init Methode privee pour initialiser la borne.
Parameters
number of terminal
name of terminal
hiddenName
Definition at line 43 of file terminal.cpp.
References br_, d, dock_elmt_, Qet::East, hovered_, hovered_color_, TerminalData::m_orientation, TerminalData::m_pos, name(), name_terminal_, name_terminal_hidden, neutralColor, Qet::North, number(), number_terminal_, previous_terminal_, Qet::South, terminalSize, QET::Icons::tr, Qet::West, and Z.
Referenced by init(), and Terminal().
isLinkedTo()
bool Terminal::isLinkedTo (Terminal * other_terminal)
Terminal::isLinkedTo.
Parameters
other_terminal Autre borne
Returns
true si cette borne est reliee a other_terminal, false sion
Definition at line 680 of file terminal.cpp.
References conductors_.
Referenced by canBeLinkedTo().
mouseMoveEvent()
void Terminal::mouseMoveEvent (QGraphicsSceneMouseEvent * e) override protected
Terminal::mouseMoveEvent Gere le fait qu'on bouge la souris sur la Borne.
Parameters
e L'evenement souris correspondant
Definition at line 540 of file terminal.cpp.
References allowedColor, canBeLinkedTo(), conductorsCount(), diagram(), forbiddenColor, hovered_, hovered_color_, neutralColor, previous_terminal_, and warningColor.
mousePressEvent()
void Terminal::mousePressEvent (QGraphicsSceneMouseEvent * e) override protected
Terminal::mousePressEvent Gere le fait qu'on enfonce un bouton de la souris sur la Borne.
Parameters
e L'evenement souris correspondant
Definition at line 526 of file terminal.cpp.
References d, diagram(), and TerminalData::m_pos.
mouseReleaseEvent()
void Terminal::mouseReleaseEvent (QGraphicsSceneMouseEvent * e) override protected
Terminal::mouseReleaseEvent.
Parameters
e
Definition at line 596 of file terminal.cpp.
References canBeLinkedTo(), QET::Icons::Conductor, diagram(), hovered_, hovered_color_, neutralColor, ConductorAutoNumerotation::numerate(), previous_terminal_, Conductor::properties, Conductor::relatedPotentialConductors(), Conductor::rSequenceNum(), Conductor::sequenceNum, and Conductor::setProperties().
name()
QString Terminal::name () const inline
Terminal::name.
Returns
the name of terminal.
Definition at line 178 of file terminal.h.
References name_terminal_.
Referenced by init(), setName(), and Terminal().
number()
QString Terminal::number () const inline
Terminal::number.
Returns
the number of terminal.
Definition at line 170 of file terminal.h.
References number_terminal_.
Referenced by init(), and setNumber().
orientation()
Qet::Orientation Terminal::orientation () const
Permet de connaitre l'orientation de la borne. Si le parent de la borne est bien un Element, cette fonction renvoie l'orientation par rapport a la scene de la borne, en tenant compte du fait que l'element ait pu etre pivote. Sinon elle renvoie son sens normal.
Returns
L'orientation actuelle de la Terminal.
Definition at line 175 of file terminal.cpp.
References d, and TerminalData::m_orientation.
Referenced by alignedWithTerminal(), HelpLine(), and paint().
paint()
void Terminal::paint (QPainter * p, const QStyleOptionGraphicsItem * options, QWidget *) override
Terminal::paint Fonction de dessin des bornes.
Parameters
p Le QPainter a utiliser
options Les options de dessin
Definition at line 253 of file terminal.cpp.
References alignedWithTerminal(), Diagram::background_color, conductors(), d, diagram(), dock_elmt_, dockConductor(), HelpLine(), hovered_, hovered_color_, Qet::isHorizontal(), m_draw_help_line, m_help_line, m_help_line_a, TerminalData::m_pos, and orientation().
parentElement()
Element * Terminal::parentElement () const
Terminal::parentElement.
Returns
L'element auquel cette borne est rattachee
Definition at line 822 of file terminal.cpp.
References parent_element_.
Referenced by NewConductorPotentialSelector::getPotential(), relatedPotentialTerminal(), DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements(), DeleteQGraphicsItemCommand::terminalInSamePotential(), and Conductor::toXml().
removeConductor()
void Terminal::removeConductor (Conductor * conductor)
Terminal::removeConductor Remove a conductor from this terminal.
Parameters
conductor : conductor to remove
Definition at line 239 of file terminal.cpp.
References conductors_, and conductorWasRemoved().
Referenced by NewConductorPotentialSelector::NewConductorPotentialSelector(), Diagram::removeItem(), and Conductor::~Conductor().
setName()
void Terminal::setName (QString name, bool hiddenName)
Terminal::setName.
Parameters
name : QString
hiddenName : bool
Definition at line 204 of file terminal.cpp.
References name(), name_terminal_, and name_terminal_hidden.
setNumber()
void Terminal::setNumber (QString number)
Terminal::setNumber.
Parameters
number
Definition at line 195 of file terminal.cpp.
References number(), and number_terminal_.
toXml()
QDomElement Terminal::toXml (QDomDocument & doc) const
Terminal::toXml Methode d'export en XML.
Parameters
doc Le Document XML a utiliser pour creer l'element XML
Returns
un QDomElement representant cette borne
Definition at line 725 of file terminal.cpp.
References d, dock_elmt_, TerminalData::m_orientation, name_terminal_, name_terminal_hidden, and number_terminal_.
type()
int Terminal::type () const inline override
type Enable the use of qgraphicsitem_cast to safely cast a QGraphicsItem into a Terminal
Returns
the QGraphicsItem type
Definition at line 62 of file terminal.h.
References Type.
updateConductor()
void Terminal::updateConductor ()
Terminal::updateConductor Update the path of conductor docked to this terminal.
Definition at line 670 of file terminal.cpp.
References conductors_, and Conductor::updatePath().
uuid()
QUuid Terminal::uuid () const
Definition at line 826 of file terminal.cpp.
References d, and TerminalData::m_uuid.
Referenced by Conductor::toXml().
valideXml()
bool Terminal::valideXml (QDomElement & terminal) static
Terminal::valideXml Permet de savoir si un element XML represente une borne.
Parameters
terminal Le QDomElement a analyser
Returns
true si le QDomElement passe en parametre est une borne, false sinon
Definition at line 746 of file terminal.cpp.
References Qet::East, Qet::North, Qet::South, and Qet::West.
Referenced by Element::fromXml().
Member Data Documentation
allowedColor
QColor Terminal::allowedColor = QColor(Qt::darkGreen) static
color for legal actions
Definition at line 114 of file terminal.h.
Referenced by mouseMoveEvent().
br_
QRectF* Terminal::br_ {nullptr} private
Pointer to a rectangle representing the terminal bounding rect; used to calculate the bounding rect once only; used a pointer because boundingRect() is supposed to be const.
Definition at line 139 of file terminal.h.
Referenced by boundingRect(), init(), and ~Terminal().
conductors_
QList<Conductor *> Terminal::conductors_ private
List of conductors attached to the terminal.
Definition at line 133 of file terminal.h.
Referenced by addConductor(), conductors(), conductorsCount(), isLinkedTo(), removeConductor(), updateConductor(), and ~Terminal().
d
TerminalData* Terminal::d private
Definition at line 126 of file terminal.h.
Referenced by boundingRect(), dockConductor(), fromXml(), init(), mousePressEvent(), orientation(), paint(), Terminal(), toXml(), and uuid().
dock_elmt_
QPointF Terminal::dock_elmt_ private
docking point for parent element
Definition at line 131 of file terminal.h.
Referenced by boundingRect(), fromXml(), init(), paint(), and toXml().
forbiddenColor
QColor Terminal::forbiddenColor = QColor(Qt::red) static
color for forbidden actions
Definition at line 118 of file terminal.h.
Referenced by mouseMoveEvent().
hovered_
bool Terminal::hovered_ private
Whether the mouse pointer is hovering the terminal.
Definition at line 143 of file terminal.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), init(), mouseMoveEvent(), mouseReleaseEvent(), and paint().
hovered_color_
QColor Terminal::hovered_color_ private
Color used for the hover effect.
Definition at line 145 of file terminal.h.
Referenced by init(), mouseMoveEvent(), mouseReleaseEvent(), and paint().
m_draw_help_line
bool Terminal::m_draw_help_line {false} private
Definition at line 121 of file terminal.h.
Referenced by drawHelpLine(), and paint().
m_help_line
QGraphicsLineItem* Terminal::m_help_line {nullptr} private
Definition at line 122 of file terminal.h.
Referenced by drawHelpLine(), and paint().
m_help_line_a
QGraphicsLineItem* Terminal::m_help_line_a {nullptr} private
Definition at line 123 of file terminal.h.
Referenced by drawHelpLine(), and paint().
name_terminal_
QString Terminal::name_terminal_ private
Name of Terminal.
Definition at line 149 of file terminal.h.
Referenced by fromXml(), init(), name(), setName(), and toXml().
name_terminal_hidden
bool Terminal::name_terminal_hidden private
Definition at line 150 of file terminal.h.
Referenced by fromXml(), init(), setName(), and toXml().
neutralColor
QColor Terminal::neutralColor = QColor(Qt::blue) static
default color
Definition at line 112 of file terminal.h.
Referenced by init(), mouseMoveEvent(), mouseReleaseEvent(), and PartTerminal::paint().
number_terminal_
QString Terminal::number_terminal_ private
Number of Terminal.
Definition at line 147 of file terminal.h.
Referenced by fromXml(), init(), number(), setNumber(), and toXml().
parent_element_
Element* Terminal::parent_element_ {nullptr} private
Parent electrical element.
Definition at line 129 of file terminal.h.
Referenced by alignedWithTerminal(), and parentElement().
previous_terminal_
Terminal* Terminal::previous_terminal_ private
Last terminal seen through an attached conductor.
Definition at line 141 of file terminal.h.
Referenced by init(), mouseMoveEvent(), and mouseReleaseEvent().
terminalSize
const qreal Terminal::terminalSize = 4.0 static
Definition at line 108 of file terminal.h.
Referenced by init().
warningColor
QColor Terminal::warningColor = QColor("#ff8000") static
color for allowed but fuzzy or not recommended actions
Definition at line 116 of file terminal.h.
Referenced by mouseMoveEvent().
Z
const qreal Terminal::Z = 1000 static
Definition at line 109 of file terminal.h.
Referenced by Diagram::changeZValue(), and init().
The documentation for this class was generated from the following files:
terminal.h
terminal.cpp