QElectroTech: StyleEditor Class Reference
StyleEditor Class Reference
#include <styleeditor.h>
Public Slots
void updateForm () override
StyleEditor::updateForm Update the edition form according to the value of edited part(s)
void updatePartAntialiasing ()
Update antialiasing with undo command.
void updatePartColor ()
Update color with undo command.
void updatePartLineStyle ()
Update style with undo command.
void updatePartLineWeight ()
Update weight with undo command.
void updatePartFilling ()
Update color filling with undo command.
Public Member Functions
StyleEditor (QETElementEditor *, CustomElementGraphicPart *=nullptr, QWidget *=nullptr)
~StyleEditor () override
Destructeur.
bool setPart (CustomElementPart *) override
StyleEditor::setPart Set the part to edit by this editor. Note : editor can accept or refuse to edit a part.
bool setParts (QList< CustomElementPart * >) override
StyleEditor::setParts Set several parts to edit by this editor. Note : editor can accept or refuse to edit several parts.
CustomElementPart * currentPart () const override
QList< CustomElementPart * > currentParts () const override
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
virtual void updateForm ()=0
Static Public Member Functions
static bool isStyleEditable (QList< CustomElementPart * > cep_list)
StyleEditor::isStyleEditable.
Private Member Functions
StyleEditor (const StyleEditor &)
void activeConnections (bool)
void makeUndo (const QString &undo_text, const char *property_name, const QVariant &new_value)
Private Attributes
CustomElementGraphicPart * part
QList< CustomElementGraphicPart * > m_part_list
QList< CustomElementPart * > m_cep_list
QCheckBox * antialiasing
QComboBox * filling_color
QComboBox * outline_color
QComboBox * size_weight
QComboBox * line_style
Detailed Description
This class provides a widget to edit styles (color, pen style and thickness, filling, antialiasing) common to most primitives within the element editor. Its appendWidget() method makes the insertion of another widget below it easier.
Definition at line 34 of file styleeditor.h.
Constructor & Destructor Documentation
StyleEditor() [1/2]
StyleEditor::StyleEditor (QETElementEditor * editor, CustomElementGraphicPart * p = nullptr, QWidget * parent = nullptr)
Constructeur
Parameters
editor L'editeur d'element concerne
p La partie a editer
parent le Widget parent
Definition at line 33 of file styleeditor.cpp.
References antialiasing, CustomElementGraphicPart::BdiagFilling, CustomElementGraphicPart::BigWeight, CustomElementGraphicPart::BlackColor, CustomElementGraphicPart::BlackFilling, CustomElementGraphicPart::BlueColor, CustomElementGraphicPart::BlueFilling, CustomElementGraphicPart::BrunColor, CustomElementGraphicPart::BrunFilling, QET::Icons::ColorBrown, QET::Icons::ColorGray, QET::Icons::ColorHTMLBlueBlue, QET::Icons::ColorHTMLBlueCornflowerBlue, QET::Icons::ColorHTMLBlueDarkBlue, QET::Icons::ColorHTMLBlueDeepSkyBlue, QET::Icons::ColorHTMLBlueDodgerBlue, QET::Icons::ColorHTMLBlueLightBlue, QET::Icons::ColorHTMLBlueLightSkyBlue, QET::Icons::ColorHTMLBlueLightSteelBlue, QET::Icons::ColorHTMLBlueMediumBlue, QET::Icons::ColorHTMLBlueMidnightBlue, QET::Icons::ColorHTMLBlueNavy, QET::Icons::ColorHTMLBluePowderBlue, QET::Icons::ColorHTMLBlueRoyalBlue, QET::Icons::ColorHTMLBlueSkyBlue, QET::Icons::ColorHTMLBlueSteelBlue, QET::Icons::ColorHTMLBrownBisque, QET::Icons::ColorHTMLBrownBlanchedAlmond, QET::Icons::ColorHTMLBrownBrown, QET::Icons::ColorHTMLBrownBurlywood, QET::Icons::ColorHTMLBrownChocolate, QET::Icons::ColorHTMLBrownCornsilk, QET::Icons::ColorHTMLBrownDarkGoldenrod, QET::Icons::ColorHTMLBrownGoldenrod, QET::Icons::ColorHTMLBrownMaroon, QET::Icons::ColorHTMLBrownNavajoWhite, QET::Icons::ColorHTMLBrownPeru, QET::Icons::ColorHTMLBrownRosyBrown, QET::Icons::ColorHTMLBrownSaddleBrown, QET::Icons::ColorHTMLBrownSandyBrown, QET::Icons::ColorHTMLBrownSienna, QET::Icons::ColorHTMLBrownTan, QET::Icons::ColorHTMLBrownWheat, QET::Icons::ColorHTMLCyanAqua, QET::Icons::ColorHTMLCyanAquamarine, QET::Icons::ColorHTMLCyanCadetBlue, QET::Icons::ColorHTMLCyanCyan, QET::Icons::ColorHTMLCyanDarkCyan, QET::Icons::ColorHTMLCyanDarkTurquoise, QET::Icons::ColorHTMLCyanLightCyan, QET::Icons::ColorHTMLCyanLightSeaGreen, QET::Icons::ColorHTMLCyanMediumTurquoise, QET::Icons::ColorHTMLCyanPaleTurquoise, QET::Icons::ColorHTMLCyanTeal, QET::Icons::ColorHTMLCyanTurquoise, QET::Icons::ColorHTMLGrayBlack, QET::Icons::ColorHTMLGrayDarkGray, QET::Icons::ColorHTMLGrayDarkSlateGray, QET::Icons::ColorHTMLGrayDimGray, QET::Icons::ColorHTMLGrayGainsboro, QET::Icons::ColorHTMLGrayGray, QET::Icons::ColorHTMLGrayLightGray, QET::Icons::ColorHTMLGrayLightSlateGray, QET::Icons::ColorHTMLGraySilver, QET::Icons::ColorHTMLGraySlateGray, QET::Icons::ColorHTMLGreenChartreuse, QET::Icons::ColorHTMLGreenDarkGreen, QET::Icons::ColorHTMLGreenDarkOliveGreen, QET::Icons::ColorHTMLGreenDarkSeaGreen, QET::Icons::ColorHTMLGreenForestGreen, QET::Icons::ColorHTMLGreenGreen, QET::Icons::ColorHTMLGreenGreenYellow, QET::Icons::ColorHTMLGreenLawnGreen, QET::Icons::ColorHTMLGreenLightGreen, QET::Icons::ColorHTMLGreenLime, QET::Icons::ColorHTMLGreenLimeGreen, QET::Icons::ColorHTMLGreenMediumAquamarine, QET::Icons::ColorHTMLGreenMediumSeaGreen, QET::Icons::ColorHTMLGreenMediumSpringGreen, QET::Icons::ColorHTMLGreenOlive, QET::Icons::ColorHTMLGreenOliveDrab, QET::Icons::ColorHTMLGreenPaleGreen, QET::Icons::ColorHTMLGreenSeaGreen, QET::Icons::ColorHTMLGreenSpringGreen, QET::Icons::ColorHTMLGreenYellowGreen, QET::Icons::ColorHTMLOrangeCoral, QET::Icons::ColorHTMLOrangeDarkOrange, QET::Icons::ColorHTMLOrangeOrange, QET::Icons::ColorHTMLOrangeOrangeRed, QET::Icons::ColorHTMLOrangeTomato, QET::Icons::ColorHTMLPinkDeepPink, QET::Icons::ColorHTMLPinkHotPink, QET::Icons::ColorHTMLPinkLightPink, QET::Icons::ColorHTMLPinkMediumVioletRed, QET::Icons::ColorHTMLPinkPaleVioletRed, QET::Icons::ColorHTMLPinkPink, QET::Icons::ColorHTMLPurpleBlueViolet, QET::Icons::ColorHTMLPurpleDarkMagenta, QET::Icons::ColorHTMLPurpleDarkOrchid, QET::Icons::ColorHTMLPurpleDarkSlateBlue, QET::Icons::ColorHTMLPurpleDarkViolet, QET::Icons::ColorHTMLPurpleFuchsia, QET::Icons::ColorHTMLPurpleIndigo, QET::Icons::ColorHTMLPurpleLavender, QET::Icons::ColorHTMLPurpleMagenta, QET::Icons::ColorHTMLPurpleMediumOrchid, QET::Icons::ColorHTMLPurpleMediumPurple, QET::Icons::ColorHTMLPurpleMediumSlateBlue, QET::Icons::ColorHTMLPurpleOrchid, QET::Icons::ColorHTMLPurplePlum, QET::Icons::ColorHTMLPurplePurple, QET::Icons::ColorHTMLPurpleSlateBlue, QET::Icons::ColorHTMLPurpleThistle, QET::Icons::ColorHTMLPurpleViolet, QET::Icons::ColorHTMLRedCrimson, QET::Icons::ColorHTMLRedDarkRed, QET::Icons::ColorHTMLRedDarkSalmon, QET::Icons::ColorHTMLRedFirebrick, QET::Icons::ColorHTMLRedIndianRed, QET::Icons::ColorHTMLRedLightCoral, QET::Icons::ColorHTMLRedLightSalmon, QET::Icons::ColorHTMLRedRed, QET::Icons::ColorHTMLRedSalmon, QET::Icons::ColorHTMLWhiteAliceBlue, QET::Icons::ColorHTMLWhiteAntiqueWhite, QET::Icons::ColorHTMLWhiteAzure, QET::Icons::ColorHTMLWhiteBeige, QET::Icons::ColorHTMLWhiteFloralWhite, QET::Icons::ColorHTMLWhiteGhostWhite, QET::Icons::ColorHTMLWhiteHoneydew, QET::Icons::ColorHTMLWhiteIvory, QET::Icons::ColorHTMLWhiteLavenderBlush, QET::Icons::ColorHTMLWhiteLinen, QET::Icons::ColorHTMLWhiteMintCream, QET::Icons::ColorHTMLWhiteMistyRose, QET::Icons::ColorHTMLWhiteOldLace, QET::Icons::ColorHTMLWhiteSeashell, QET::Icons::ColorHTMLWhiteSnow, QET::Icons::ColorHTMLWhiteWhite, QET::Icons::ColorHTMLWhiteWhiteSmoke, QET::Icons::ColorHTMLYellowDarkKhaki, QET::Icons::ColorHTMLYellowGold, QET::Icons::ColorHTMLYellowKhaki, QET::Icons::ColorHTMLYellowLemonChiffon, QET::Icons::ColorHTMLYellowLightGoldenrodYellow, QET::Icons::ColorHTMLYellowLightYellow, QET::Icons::ColorHTMLYellowMoccasin, QET::Icons::ColorHTMLYellowPaleGoldenrod, QET::Icons::ColorHTMLYellowPapayaWhip, QET::Icons::ColorHTMLYellowPeachPuff, QET::Icons::ColorHTMLYellowYellow, QET::Icons::ColorOrange, QET::Icons::ColorPurple, CustomElementGraphicPart::CyanColor, CustomElementGraphicPart::CyanFilling, CustomElementGraphicPart::DashdottedStyle, CustomElementGraphicPart::DashedStyle, CustomElementGraphicPart::DottedStyle, CustomElementGraphicPart::FdiagFilling, filling_color, CustomElementGraphicPart::GrayColor, CustomElementGraphicPart::GrayFilling, CustomElementGraphicPart::GreenColor, CustomElementGraphicPart::GreenFilling, CustomElementGraphicPart::HorFilling, CustomElementGraphicPart::HTMLBlueBlueColor, CustomElementGraphicPart::HTMLBlueBlueFilling, CustomElementGraphicPart::HTMLBlueCornflowerBlueColor, CustomElementGraphicPart::HTMLBlueCornflowerBlueFilling, CustomElementGraphicPart::HTMLBlueDarkBlueColor, CustomElementGraphicPart::HTMLBlueDarkBlueFilling, CustomElementGraphicPart::HTMLBlueDeepSkyBlueColor, CustomElementGraphicPart::HTMLBlueDeepSkyBlueFilling, CustomElementGraphicPart::HTMLBlueDodgerBlueColor, CustomElementGraphicPart::HTMLBlueDodgerBlueFilling, CustomElementGraphicPart::HTMLBlueLightBlueColor, CustomElementGraphicPart::HTMLBlueLightBlueFilling, CustomElementGraphicPart::HTMLBlueLightSkyBlueColor, CustomElementGraphicPart::HTMLBlueLightSkyBlueFilling, CustomElementGraphicPart::HTMLBlueLightSteelBlueColor, CustomElementGraphicPart::HTMLBlueLightSteelBlueFilling, CustomElementGraphicPart::HTMLBlueMediumBlueColor, CustomElementGraphicPart::HTMLBlueMediumBlueFilling, CustomElementGraphicPart::HTMLBlueMidnightBlueColor, CustomElementGraphicPart::HTMLBlueMidnightBlueFilling, CustomElementGraphicPart::HTMLBlueNavyColor, CustomElementGraphicPart::HTMLBlueNavyFilling, CustomElementGraphicPart::HTMLBluePowderBlueColor, CustomElementGraphicPart::HTMLBluePowderBlueFilling, CustomElementGraphicPart::HTMLBlueRoyalBlueColor, CustomElementGraphicPart::HTMLBlueRoyalBlueFilling, CustomElementGraphicPart::HTMLBlueSkyBlueColor, CustomElementGraphicPart::HTMLBlueSkyBlueFilling, CustomElementGraphicPart::HTMLBlueSteelBlueColor, CustomElementGraphicPart::HTMLBlueSteelBlueFilling, CustomElementGraphicPart::HTMLBrownBisqueColor, CustomElementGraphicPart::HTMLBrownBisqueFilling, CustomElementGraphicPart::HTMLBrownBlanchedAlmondColor, CustomElementGraphicPart::HTMLBrownBlanchedAlmondFilling, CustomElementGraphicPart::HTMLBrownBrownColor, CustomElementGraphicPart::HTMLBrownBrownFilling, CustomElementGraphicPart::HTMLBrownBurlywoodColor, CustomElementGraphicPart::HTMLBrownBurlywoodFilling, CustomElementGraphicPart::HTMLBrownChocolateColor, CustomElementGraphicPart::HTMLBrownChocolateFilling, CustomElementGraphicPart::HTMLBrownCornsilkColor, CustomElementGraphicPart::HTMLBrownCornsilkFilling, CustomElementGraphicPart::HTMLBrownDarkGoldenrodColor, CustomElementGraphicPart::HTMLBrownDarkGoldenrodFilling, CustomElementGraphicPart::HTMLBrownGoldenrodColor, CustomElementGraphicPart::HTMLBrownGoldenrodFilling, CustomElementGraphicPart::HTMLBrownMaroonColor, CustomElementGraphicPart::HTMLBrownMaroonFilling, CustomElementGraphicPart::HTMLBrownNavajoWhiteColor, CustomElementGraphicPart::HTMLBrownNavajoWhiteFilling, CustomElementGraphicPart::HTMLBrownPeruColor, CustomElementGraphicPart::HTMLBrownPeruFilling, CustomElementGraphicPart::HTMLBrownRosyBrownColor, CustomElementGraphicPart::HTMLBrownRosyBrownFilling, CustomElementGraphicPart::HTMLBrownSaddleBrownColor, CustomElementGraphicPart::HTMLBrownSaddleBrownFilling, CustomElementGraphicPart::HTMLBrownSandyBrownColor, CustomElementGraphicPart::HTMLBrownSandyBrownFilling, CustomElementGraphicPart::HTMLBrownSiennaColor, CustomElementGraphicPart::HTMLBrownSiennaFilling, CustomElementGraphicPart::HTMLBrownTanColor, CustomElementGraphicPart::HTMLBrownTanFilling, CustomElementGraphicPart::HTMLBrownWheatColor, CustomElementGraphicPart::HTMLBrownWheatFilling, CustomElementGraphicPart::HTMLCyanAquaColor, CustomElementGraphicPart::HTMLCyanAquaFilling, CustomElementGraphicPart::HTMLCyanAquamarineColor, CustomElementGraphicPart::HTMLCyanAquamarineFilling, CustomElementGraphicPart::HTMLCyanCadetBlueColor, CustomElementGraphicPart::HTMLCyanCadetBlueFilling, CustomElementGraphicPart::HTMLCyanCyanColor, CustomElementGraphicPart::HTMLCyanCyanFilling, CustomElementGraphicPart::HTMLCyanDarkCyanColor, CustomElementGraphicPart::HTMLCyanDarkCyanFilling, CustomElementGraphicPart::HTMLCyanDarkTurquoiseColor, CustomElementGraphicPart::HTMLCyanDarkTurquoiseFilling, CustomElementGraphicPart::HTMLCyanLightCyanColor, CustomElementGraphicPart::HTMLCyanLightCyanFilling, CustomElementGraphicPart::HTMLCyanLightSeaGreenColor, CustomElementGraphicPart::HTMLCyanLightSeaGreenFilling, CustomElementGraphicPart::HTMLCyanMediumTurquoiseColor, CustomElementGraphicPart::HTMLCyanMediumTurquoiseFilling, CustomElementGraphicPart::HTMLCyanPaleTurquoiseColor, CustomElementGraphicPart::HTMLCyanPaleTurquoiseFilling, CustomElementGraphicPart::HTMLCyanTealColor, CustomElementGraphicPart::HTMLCyanTealFilling, CustomElementGraphicPart::HTMLCyanTurquoiseColor, CustomElementGraphicPart::HTMLCyanTurquoiseFilling, CustomElementGraphicPart::HTMLGrayBlackColor, CustomElementGraphicPart::HTMLGrayBlackFilling, CustomElementGraphicPart::HTMLGrayDarkGrayColor, CustomElementGraphicPart::HTMLGrayDarkGrayFilling, CustomElementGraphicPart::HTMLGrayDarkSlateGrayColor, CustomElementGraphicPart::HTMLGrayDarkSlateGrayFilling, CustomElementGraphicPart::HTMLGrayDimGrayColor, CustomElementGraphicPart::HTMLGrayDimGrayFilling, CustomElementGraphicPart::HTMLGrayGainsboroColor, CustomElementGraphicPart::HTMLGrayGainsboroFilling, CustomElementGraphicPart::HTMLGrayGrayColor, CustomElementGraphicPart::HTMLGrayGrayFilling, CustomElementGraphicPart::HTMLGrayLightGrayColor, CustomElementGraphicPart::HTMLGrayLightGrayFilling, CustomElementGraphicPart::HTMLGrayLightSlateGrayColor, CustomElementGraphicPart::HTMLGrayLightSlateGrayFilling, CustomElementGraphicPart::HTMLGraySilverColor, CustomElementGraphicPart::HTMLGraySilverFilling, CustomElementGraphicPart::HTMLGraySlateGrayColor, CustomElementGraphicPart::HTMLGraySlateGrayFilling, CustomElementGraphicPart::HTMLGreenChartreuseColor, CustomElementGraphicPart::HTMLGreenChartreuseFilling, CustomElementGraphicPart::HTMLGreenDarkGreenColor, CustomElementGraphicPart::HTMLGreenDarkGreenFilling, CustomElementGraphicPart::HTMLGreenDarkOliveGreenColor, CustomElementGraphicPart::HTMLGreenDarkOliveGreenFilling, CustomElementGraphicPart::HTMLGreenDarkSeaGreenColor, CustomElementGraphicPart::HTMLGreenDarkSeaGreenFilling, CustomElementGraphicPart::HTMLGreenForestGreenColor, CustomElementGraphicPart::HTMLGreenForestGreenFilling, CustomElementGraphicPart::HTMLGreenGreenColor, CustomElementGraphicPart::HTMLGreenGreenFilling, CustomElementGraphicPart::HTMLGreenGreenYellowColor, CustomElementGraphicPart::HTMLGreenGreenYellowFilling, CustomElementGraphicPart::HTMLGreenLawnGreenColor, CustomElementGraphicPart::HTMLGreenLawnGreenFilling, CustomElementGraphicPart::HTMLGreenLightGreenColor, CustomElementGraphicPart::HTMLGreenLightGreenFilling, CustomElementGraphicPart::HTMLGreenLimeColor, CustomElementGraphicPart::HTMLGreenLimeFilling, CustomElementGraphicPart::HTMLGreenLimeGreenColor, CustomElementGraphicPart::HTMLGreenLimeGreenFilling, CustomElementGraphicPart::HTMLGreenMediumAquamarineColor, CustomElementGraphicPart::HTMLGreenMediumAquamarineFilling, CustomElementGraphicPart::HTMLGreenMediumSeaGreenColor, CustomElementGraphicPart::HTMLGreenMediumSeaGreenFilling, CustomElementGraphicPart::HTMLGreenMediumSpringGreenColor, CustomElementGraphicPart::HTMLGreenMediumSpringGreenFilling, CustomElementGraphicPart::HTMLGreenOliveColor, CustomElementGraphicPart::HTMLGreenOliveDrabColor, CustomElementGraphicPart::HTMLGreenOliveDrabFilling, CustomElementGraphicPart::HTMLGreenOliveFilling, CustomElementGraphicPart::HTMLGreenPaleGreenColor, CustomElementGraphicPart::HTMLGreenPaleGreenFilling, CustomElementGraphicPart::HTMLGreenSeaGreenColor, CustomElementGraphicPart::HTMLGreenSeaGreenFilling, CustomElementGraphicPart::HTMLGreenSpringGreenColor, CustomElementGraphicPart::HTMLGreenSpringGreenFilling, CustomElementGraphicPart::HTMLGreenYellowGreenColor, CustomElementGraphicPart::HTMLGreenYellowGreenFilling, CustomElementGraphicPart::HTMLOrangeCoralColor, CustomElementGraphicPart::HTMLOrangeCoralFilling, CustomElementGraphicPart::HTMLOrangeDarkOrangeColor, CustomElementGraphicPart::HTMLOrangeDarkOrangeFilling, CustomElementGraphicPart::HTMLOrangeOrangeColor, CustomElementGraphicPart::HTMLOrangeOrangeFilling, CustomElementGraphicPart::HTMLOrangeOrangeRedColor, CustomElementGraphicPart::HTMLOrangeOrangeRedFilling, CustomElementGraphicPart::HTMLOrangeTomatoColor, CustomElementGraphicPart::HTMLOrangeTomatoFilling, CustomElementGraphicPart::HTMLPinkDeepPinkColor, CustomElementGraphicPart::HTMLPinkDeepPinkFilling, CustomElementGraphicPart::HTMLPinkHotPinkColor, CustomElementGraphicPart::HTMLPinkHotPinkFilling, CustomElementGraphicPart::HTMLPinkLightPinkColor, CustomElementGraphicPart::HTMLPinkLightPinkFilling, CustomElementGraphicPart::HTMLPinkMediumVioletRedColor, CustomElementGraphicPart::HTMLPinkMediumVioletRedFilling, CustomElementGraphicPart::HTMLPinkPaleVioletRedColor, CustomElementGraphicPart::HTMLPinkPaleVioletRedFilling, CustomElementGraphicPart::HTMLPinkPinkColor, CustomElementGraphicPart::HTMLPinkPinkFilling, CustomElementGraphicPart::HTMLPurpleBlueVioletColor, CustomElementGraphicPart::HTMLPurpleBlueVioletFilling, CustomElementGraphicPart::HTMLPurpleDarkMagentaColor, CustomElementGraphicPart::HTMLPurpleDarkMagentaFilling, CustomElementGraphicPart::HTMLPurpleDarkOrchidColor, CustomElementGraphicPart::HTMLPurpleDarkOrchidFilling, CustomElementGraphicPart::HTMLPurpleDarkSlateBlueColor, CustomElementGraphicPart::HTMLPurpleDarkSlateBlueFilling, CustomElementGraphicPart::HTMLPurpleDarkVioletColor, CustomElementGraphicPart::HTMLPurpleDarkVioletFilling, CustomElementGraphicPart::HTMLPurpleFuchsiaColor, CustomElementGraphicPart::HTMLPurpleFuchsiaFilling, CustomElementGraphicPart::HTMLPurpleIndigoColor, CustomElementGraphicPart::HTMLPurpleIndigoFilling, CustomElementGraphicPart::HTMLPurpleLavenderColor, CustomElementGraphicPart::HTMLPurpleLavenderFilling, CustomElementGraphicPart::HTMLPurpleMagentaColor, CustomElementGraphicPart::HTMLPurpleMagentaFilling, CustomElementGraphicPart::HTMLPurpleMediumOrchidColor, CustomElementGraphicPart::HTMLPurpleMediumOrchidFilling, CustomElementGraphicPart::HTMLPurpleMediumPurpleColor, CustomElementGraphicPart::HTMLPurpleMediumPurpleFilling, CustomElementGraphicPart::HTMLPurpleMediumSlateBlueColor, CustomElementGraphicPart::HTMLPurpleMediumSlateBlueFilling, CustomElementGraphicPart::HTMLPurpleOrchidColor, CustomElementGraphicPart::HTMLPurpleOrchidFilling, CustomElementGraphicPart::HTMLPurplePlumColor, CustomElementGraphicPart::HTMLPurplePlumFilling, CustomElementGraphicPart::HTMLPurplePurpleColor, CustomElementGraphicPart::HTMLPurplePurpleFilling, CustomElementGraphicPart::HTMLPurpleSlateBlueColor, CustomElementGraphicPart::HTMLPurpleSlateBlueFilling, CustomElementGraphicPart::HTMLPurpleThistleColor, CustomElementGraphicPart::HTMLPurpleThistleFilling, CustomElementGraphicPart::HTMLPurpleVioletColor, CustomElementGraphicPart::HTMLPurpleVioletFilling, CustomElementGraphicPart::HTMLRedCrimsonColor, CustomElementGraphicPart::HTMLRedCrimsonFilling, CustomElementGraphicPart::HTMLRedDarkRedColor, CustomElementGraphicPart::HTMLRedDarkRedFilling, CustomElementGraphicPart::HTMLRedDarkSalmonColor, CustomElementGraphicPart::HTMLRedDarkSalmonFilling, CustomElementGraphicPart::HTMLRedFirebrickColor, CustomElementGraphicPart::HTMLRedFirebrickFilling, CustomElementGraphicPart::HTMLRedIndianRedColor, CustomElementGraphicPart::HTMLRedIndianRedFilling, CustomElementGraphicPart::HTMLRedLightCoralColor, CustomElementGraphicPart::HTMLRedLightCoralFilling, CustomElementGraphicPart::HTMLRedLightSalmonColor, CustomElementGraphicPart::HTMLRedLightSalmonFilling, CustomElementGraphicPart::HTMLRedRedColor, CustomElementGraphicPart::HTMLRedRedFilling, CustomElementGraphicPart::HTMLRedSalmonColor, CustomElementGraphicPart::HTMLRedSalmonFilling, CustomElementGraphicPart::HTMLWhiteAliceBlueColor, CustomElementGraphicPart::HTMLWhiteAliceBlueFilling, CustomElementGraphicPart::HTMLWhiteAntiqueWhiteColor, CustomElementGraphicPart::HTMLWhiteAntiqueWhiteFilling, CustomElementGraphicPart::HTMLWhiteAzureColor, CustomElementGraphicPart::HTMLWhiteAzureFilling, CustomElementGraphicPart::HTMLWhiteBeigeColor, CustomElementGraphicPart::HTMLWhiteBeigeFilling, CustomElementGraphicPart::HTMLWhiteFloralWhiteColor, CustomElementGraphicPart::HTMLWhiteFloralWhiteFilling, CustomElementGraphicPart::HTMLWhiteGhostWhiteColor, CustomElementGraphicPart::HTMLWhiteGhostWhiteFilling, CustomElementGraphicPart::HTMLWhiteHoneydewColor, CustomElementGraphicPart::HTMLWhiteHoneydewFilling, CustomElementGraphicPart::HTMLWhiteIvoryColor, CustomElementGraphicPart::HTMLWhiteIvoryFilling, CustomElementGraphicPart::HTMLWhiteLavenderBlushColor, CustomElementGraphicPart::HTMLWhiteLavenderBlushFilling, CustomElementGraphicPart::HTMLWhiteLinenColor, CustomElementGraphicPart::HTMLWhiteLinenFilling, CustomElementGraphicPart::HTMLWhiteMintCreamColor, CustomElementGraphicPart::HTMLWhiteMintCreamFilling, CustomElementGraphicPart::HTMLWhiteMistyRoseColor, CustomElementGraphicPart::HTMLWhiteMistyRoseFilling, CustomElementGraphicPart::HTMLWhiteOldLaceColor, CustomElementGraphicPart::HTMLWhiteOldLaceFilling, CustomElementGraphicPart::HTMLWhiteSeashellColor, CustomElementGraphicPart::HTMLWhiteSeashellFilling, CustomElementGraphicPart::HTMLWhiteSnowColor, CustomElementGraphicPart::HTMLWhiteSnowFilling, CustomElementGraphicPart::HTMLWhiteWhiteColor, CustomElementGraphicPart::HTMLWhiteWhiteFilling, CustomElementGraphicPart::HTMLWhiteWhiteSmokeColor, CustomElementGraphicPart::HTMLWhiteWhiteSmokeFilling, CustomElementGraphicPart::HTMLYellowDarkKhakiColor, CustomElementGraphicPart::HTMLYellowDarkKhakiFilling, CustomElementGraphicPart::HTMLYellowGoldColor, CustomElementGraphicPart::HTMLYellowGoldFilling, CustomElementGraphicPart::HTMLYellowKhakiColor, CustomElementGraphicPart::HTMLYellowKhakiFilling, CustomElementGraphicPart::HTMLYellowLemonChiffonColor, CustomElementGraphicPart::HTMLYellowLemonChiffonFilling, CustomElementGraphicPart::HTMLYellowLightGoldenrodYellowColor, CustomElementGraphicPart::HTMLYellowLightGoldenrodYellowFilling, CustomElementGraphicPart::HTMLYellowLightYellowColor, CustomElementGraphicPart::HTMLYellowLightYellowFilling, CustomElementGraphicPart::HTMLYellowMoccasinColor, CustomElementGraphicPart::HTMLYellowMoccasinFilling, CustomElementGraphicPart::HTMLYellowPaleGoldenrodColor, CustomElementGraphicPart::HTMLYellowPaleGoldenrodFilling, CustomElementGraphicPart::HTMLYellowPapayaWhipColor, CustomElementGraphicPart::HTMLYellowPapayaWhipFilling, CustomElementGraphicPart::HTMLYellowPeachPuffColor, CustomElementGraphicPart::HTMLYellowPeachPuffFilling, CustomElementGraphicPart::HTMLYellowYellowColor, CustomElementGraphicPart::HTMLYellowYellowFilling, CustomElementGraphicPart::LightgrayColor, CustomElementGraphicPart::LightgrayFilling, line_style, CustomElementGraphicPart::MagentaColor, CustomElementGraphicPart::MagentaFilling, CustomElementGraphicPart::NoneColor, CustomElementGraphicPart::NoneFilling, CustomElementGraphicPart::NoneWeight, CustomElementGraphicPart::NormalStyle, CustomElementGraphicPart::NormalWeight, CustomElementGraphicPart::OrangeColor, CustomElementGraphicPart::OrangeFilling, outline_color, CustomElementGraphicPart::PurpleColor, CustomElementGraphicPart::PurpleFilling, CustomElementGraphicPart::RedColor, CustomElementGraphicPart::RedFilling, size_weight, CustomElementGraphicPart::ThinWeight, QET::Icons::tr, CustomElementGraphicPart::UltraWeight, updateForm(), CustomElementGraphicPart::VerFilling, CustomElementGraphicPart::WhiteColor, CustomElementGraphicPart::WhiteFilling, CustomElementGraphicPart::YellowColor, and CustomElementGraphicPart::YellowFilling.
~StyleEditor()
StyleEditor::~StyleEditor () override
Destructeur.
Definition at line 406 of file styleeditor.cpp.
StyleEditor() [2/2]
StyleEditor::StyleEditor (const StyleEditor &) private
Member Function Documentation
activeConnections()
void StyleEditor::activeConnections (bool active) private
Active ou desactive les connexionx signaux/slots entre les widgets internes.
Parameters
active true pour activer les connexions, false pour les desactiver
Definition at line 569 of file styleeditor.cpp.
References antialiasing, filling_color, line_style, outline_color, size_weight, updatePartAntialiasing(), updatePartColor(), updatePartFilling(), updatePartLineStyle(), and updatePartLineWeight().
Referenced by updateForm().
currentPart()
CustomElementPart * StyleEditor::currentPart () const override virtual
Returns
la primitive actuellement editee, ou 0 si ce widget n'en edite pas
Implements ElementItemEditor.
Definition at line 539 of file styleeditor.cpp.
References part.
currentParts()
QList< CustomElementPart * > StyleEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 543 of file styleeditor.cpp.
References m_cep_list.
Referenced by PolygonEditor::currentParts(), RectangleEditor::currentParts(), EllipseEditor::currentParts(), LineEditor::currentParts(), ArcEditor::currentParts(), EllipseEditor::editingFinishedH(), EllipseEditor::editingFinishedV(), EllipseEditor::editingFinishedX(), EllipseEditor::editingFinishedY(), RectangleEditor::heightChanged(), LineEditor::lineEditingFinishedX1(), LineEditor::lineEditingFinishedX2(), LineEditor::lineEditingFinishedY1(), LineEditor::lineEditingFinishedY2(), ArcEditor::updateArcA(), ArcEditor::updateArcRectH(), ArcEditor::updateArcRectV(), ArcEditor::updateArcRectX(), ArcEditor::updateArcRectY(), ArcEditor::updateArcS(), LineEditor::updateLineEndLength1(), LineEditor::updateLineEndLength2(), LineEditor::updateLineEndType1(), LineEditor::updateLineEndType2(), RectangleEditor::widthChanged(), RectangleEditor::xPosChanged(), RectangleEditor::xRadiusChanged(), RectangleEditor::yPosChanged(), and RectangleEditor::yRadiusChanged().
isStyleEditable()
bool StyleEditor::isStyleEditable (QList< CustomElementPart * > cep_list) static
StyleEditor::isStyleEditable.
Parameters
cep_list
Returns
true if all of the content of cep_list can be edited by style editor, else return false.
Definition at line 553 of file styleeditor.cpp.
Referenced by setParts(), and QETElementEditor::slot_updateInformations().
makeUndo()
void StyleEditor::makeUndo (const QString & undo_text, const char * property_name, const QVariant & new_value) private
Definition at line 585 of file styleeditor.cpp.
References m_part_list, part, CustomElementGraphicPart::property(), and ElementItemEditor::undoStack().
Referenced by updatePartAntialiasing(), updatePartColor(), updatePartFilling(), updatePartLineStyle(), and updatePartLineWeight().
setPart()
bool StyleEditor::setPart (CustomElementPart * new_part) override virtual
StyleEditor::setPart Set the part to edit by this editor. Note : editor can accept or refuse to edit a part.
Parameters
new_part : part to edit
Returns
true if editor accept to edit this CustomElementPart otherwise false
Implements ElementItemEditor.
Definition at line 480 of file styleeditor.cpp.
References m_cep_list, m_part_list, part, and updateForm().
Referenced by setParts().
setParts()
bool StyleEditor::setParts (QList< CustomElementPart * > part_list) override virtual
StyleEditor::setParts Set several parts to edit by this editor. Note : editor can accept or refuse to edit several parts.
Parameters
part_list
Returns
true if every customeElementPart stored in part_list can be edited by this part editor, otherwise return false (see StyleEditor::isStyleEditable)
Reimplemented from ElementItemEditor.
Definition at line 510 of file styleeditor.cpp.
References isStyleEditable(), m_cep_list, m_part_list, part, setPart(), and updateForm().
Referenced by RectangleEditor::setParts(), EllipseEditor::setParts(), LineEditor::setParts(), and ArcEditor::setParts().
updateForm
void StyleEditor::updateForm () override slot
StyleEditor::updateForm Update the edition form according to the value of edited part(s)
Definition at line 438 of file styleeditor.cpp.
References activeConnections(), antialiasing, filling_color, line_style, m_part_list, outline_color, part, and size_weight.
Referenced by setPart(), setParts(), and StyleEditor().
updatePartAntialiasing
void StyleEditor::updatePartAntialiasing () slot
Update antialiasing with undo command.
Definition at line 410 of file styleeditor.cpp.
References antialiasing, makeUndo(), and QET::Icons::tr.
Referenced by activeConnections().
updatePartColor
void StyleEditor::updatePartColor () slot
Update color with undo command.
Definition at line 415 of file styleeditor.cpp.
References makeUndo(), outline_color, and QET::Icons::tr.
Referenced by activeConnections().
updatePartFilling
void StyleEditor::updatePartFilling () slot
Update color filling with undo command.
Definition at line 430 of file styleeditor.cpp.
References filling_color, makeUndo(), and QET::Icons::tr.
Referenced by activeConnections().
updatePartLineStyle
void StyleEditor::updatePartLineStyle () slot
Update style with undo command.
Definition at line 420 of file styleeditor.cpp.
References line_style, makeUndo(), and QET::Icons::tr.
Referenced by activeConnections().
updatePartLineWeight
void StyleEditor::updatePartLineWeight () slot
Update weight with undo command.
Definition at line 425 of file styleeditor.cpp.
References makeUndo(), size_weight, and QET::Icons::tr.
Referenced by activeConnections().
Member Data Documentation
antialiasing
QCheckBox* StyleEditor::antialiasing private
Definition at line 50 of file styleeditor.h.
Referenced by activeConnections(), StyleEditor(), updateForm(), and updatePartAntialiasing().
filling_color
QComboBox* StyleEditor::filling_color private
Definition at line 51 of file styleeditor.h.
Referenced by activeConnections(), StyleEditor(), updateForm(), and updatePartFilling().
line_style
QComboBox * StyleEditor::line_style private
Definition at line 51 of file styleeditor.h.
Referenced by activeConnections(), StyleEditor(), updateForm(), and updatePartLineStyle().
m_cep_list
QList<CustomElementPart *> StyleEditor::m_cep_list private
Definition at line 49 of file styleeditor.h.
Referenced by currentParts(), setPart(), and setParts().
m_part_list
QList<CustomElementGraphicPart *> StyleEditor::m_part_list private
Definition at line 48 of file styleeditor.h.
Referenced by makeUndo(), setPart(), setParts(), and updateForm().
outline_color
QComboBox * StyleEditor::outline_color private
Definition at line 51 of file styleeditor.h.
Referenced by activeConnections(), StyleEditor(), updateForm(), and updatePartColor().
part
CustomElementGraphicPart* StyleEditor::part private
Definition at line 47 of file styleeditor.h.
Referenced by currentPart(), makeUndo(), setPart(), setParts(), and updateForm().
size_weight
QComboBox * StyleEditor::size_weight private
Definition at line 51 of file styleeditor.h.
Referenced by activeConnections(), StyleEditor(), updateForm(), and updatePartLineWeight().
The documentation for this class was generated from the following files:
styleeditor.h
styleeditor.cpp