QElectroTech: TitleBlockTemplateView Class Reference
TitleBlockTemplateView Class Reference
#include <templateview.h>
Public Slots
void setTitleBlockTemplate (TitleBlockTemplate *)
void selectionChanged ()
void zoomIn ()
void zoomOut ()
void zoomFit ()
void zoomReset ()
QList< TitleBlockCell * > cut ()
QList< TitleBlockCell * > copy ()
bool mayPaste ()
QList< TitleBlockCell > pastedCells ()
void paste ()
void addColumnAtEnd ()
void addRowAtEnd ()
void addColumnBefore ()
void addRowBefore ()
void addColumnAfter ()
void addRowAfter ()
void editColumn (HelperCell *=nullptr)
void editRow (HelperCell *=nullptr)
void deleteColumn ()
void deleteRow ()
void mergeSelectedCells ()
void splitSelectedCell ()
void refresh ()
void changePreviewWidth ()
void setPreviewWidth (int)
void updateLayout ()
void rowsDimensionsChanged ()
void columnsDimensionsChanged ()
void updateDisplayedMinMaxWidth ()
void setReadOnly (bool)
Signals
void selectedCellsChanged (QList< TitleBlockCell * >)
void gridModificationRequested (TitleBlockTemplateCommand *)
void previewWidthChanged (int, int)
Public Member Functions
TitleBlockTemplateView (QWidget *=nullptr)
TitleBlockTemplateView (QGraphicsScene *, QWidget *=nullptr)
TitleBlockTemplateView::TitleBlockTemplateView.
~TitleBlockTemplateView () override
TitleBlockTemplate * titleBlockTemplate () const
virtual QList< TitleBlockCell * > selectedCells () const
virtual TitleBlockTemplateCellsSet selectedCellsSet () const
virtual TitleBlockTemplateCellsSet cells (const QRectF &) const
virtual void analyzeSelectedCells (bool *, bool *, int *)
TitleBlockTemplateView::analyzeSelectedCells.
virtual QSizeF templateSize () const
virtual qreal templateWidth () const
virtual qreal templateHeight () const
Protected Slots
virtual void applyColumnsWidths (bool=true)
virtual void applyRowsHeights (bool=true)
virtual void updateRowsHelperCells ()
virtual void updateColumnsHelperCells ()
Protected Member Functions
void drawBackground (QPainter *, const QRectF &) override
virtual void addCells ()
virtual void loadTemplate (TitleBlockTemplate *)
virtual void init ()
void wheelEvent (QWheelEvent *) override
virtual qreal zoomFactor () const
virtual void fillWithEmptyCells ()
bool event (QEvent *) override
virtual void normalizeCells (QList< TitleBlockCell > &, int x=0, int y=0) const
TitleBlockTemplateView::normalizeCells Given a cells list, change their position so the top left one is at row x and column y.
Private Slots
void updateLastContextMenuCell (HelperCell *)
void adjustSceneRect ()
Private Member Functions
TitleBlockTemplateView (const TitleBlockTemplateView &)
QList< QAction * > rowsActions () const
QList< QAction * > columnsActions () const
void updateTotalWidthLabel ()
void requestGridModification (TitleBlockTemplateCommand *)
int lastContextMenuCellIndex () const
int indexOf (QGraphicsLayoutItem *)
void removeItem (QGraphicsLayoutItem *)
TitleBlockTemplateCellsSet makeCellsSetFromGraphicsItems (const QList< QGraphicsItem * > &) const
TitleBlockTemplateView::makeCellsSetFromGraphicsItems.
QString makePrettyToolTip (const QString &)
TitleBlockTemplateView::makePrettyToolTip.
Private Attributes
TitleBlockTemplate * tbtemplate_
QGraphicsGridLayout * tbgrid_
QGraphicsWidget * form_
int preview_width_
SplittedHelperCell * total_width_helper_cell_
HelperCell * extra_cells_width_helper_cell_
QAction * add_column_before_
QAction * add_row_before_
QAction * add_column_after_
QAction * add_row_after_
QAction * edit_column_dim_
QAction * edit_row_dim_
QAction * delete_column_
QAction * delete_row_
QAction * change_preview_width_
HelperCell * last_context_menu_cell_
int apply_columns_widths_count_
int apply_rows_heights_count_
bool first_activation_
Boolean used to detect the first display of this widget.
bool read_only_
Boolean stating whether this view allows template edition.
Detailed Description
This QGraphicsView subclass is used in the title block template editor to offer a graphical preview of the template being edited, but also to handle cell selection and various actions.
Definition at line 32 of file templateview.h.
Constructor & Destructor Documentation
TitleBlockTemplateView() [1/3]
TitleBlockTemplateView::TitleBlockTemplateView (QWidget * parent = nullptr)
Constructor
Parameters
parent Parent QWidget.
Definition at line 40 of file templateview.cpp.
References init().
TitleBlockTemplateView() [2/3]
TitleBlockTemplateView::TitleBlockTemplateView (QGraphicsScene * scene, QWidget * parent = nullptr)
TitleBlockTemplateView::TitleBlockTemplateView.
Parameters
scene
parent Parent QWidget.
Definition at line 59 of file templateview.cpp.
References init().
~TitleBlockTemplateView()
TitleBlockTemplateView::~TitleBlockTemplateView () override
Destructor
Definition at line 76 of file templateview.cpp.
TitleBlockTemplateView() [3/3]
TitleBlockTemplateView::TitleBlockTemplateView (const TitleBlockTemplateView &) private
Member Function Documentation
addCells()
void TitleBlockTemplateView::addCells () protected virtual
Add the cells (both helper cells and regular visual cells) to the scene to get a visual representation of the edited title block template.
Definition at line 703 of file templateview.cpp.
References QET::Absolute, change_preview_width_, changePreviewWidth(), COL_OFFSET, columnsActions(), TitleBlockCell::Disabled, editColumn(), editRow(), extra_cells_width_helper_cell_, QET::Horizontal, ROW_OFFSET, rowsActions(), tbgrid_, tbtemplate_, TitleBlockDimension::toString(), total_width_helper_cell_, QET::Icons::tr, TitleBlockDimension::type, updateLastContextMenuCell(), updateTotalWidthLabel(), and QET::Vertical.
Referenced by loadTemplate().
addColumnAfter
void TitleBlockTemplateView::addColumnAfter () slot
Add a column right after the last index selected when calling the context menu.
Definition at line 304 of file templateview.cpp.
References ModifyTemplateGridCommand::addColumn(), lastContextMenuCellIndex(), read_only_, requestGridModification(), and tbtemplate_.
Referenced by init().
addColumnAtEnd
void TitleBlockTemplateView::addColumnAtEnd () slot
Add a column right after the last one.
Definition at line 265 of file templateview.cpp.
References ModifyTemplateGridCommand::addColumn(), read_only_, requestGridModification(), and tbtemplate_.
addColumnBefore
void TitleBlockTemplateView::addColumnBefore () slot
Add a column right before the last index selected when calling the context menu.
Definition at line 282 of file templateview.cpp.
References ModifyTemplateGridCommand::addColumn(), lastContextMenuCellIndex(), read_only_, requestGridModification(), and tbtemplate_.
Referenced by init().
addRowAfter
void TitleBlockTemplateView::addRowAfter () slot
Add a row right after the last index selected when calling the context menu.
Definition at line 315 of file templateview.cpp.
References ModifyTemplateGridCommand::addRow(), lastContextMenuCellIndex(), read_only_, requestGridModification(), and tbtemplate_.
Referenced by init().
addRowAtEnd
void TitleBlockTemplateView::addRowAtEnd () slot
Add a row right after the last one.
Definition at line 273 of file templateview.cpp.
References ModifyTemplateGridCommand::addRow(), read_only_, requestGridModification(), and tbtemplate_.
addRowBefore
void TitleBlockTemplateView::addRowBefore () slot
Add a row right before the last index selected when calling the context menu.
Definition at line 293 of file templateview.cpp.
References ModifyTemplateGridCommand::addRow(), lastContextMenuCellIndex(), read_only_, requestGridModification(), and tbtemplate_.
Referenced by init().
adjustSceneRect
void TitleBlockTemplateView::adjustSceneRect () private slot
Adjusts the bounding rect of the scene.
Definition at line 1112 of file templateview.cpp.
References templateSize().
Referenced by loadTemplate(), zoomFit(), and zoomReset().
analyzeSelectedCells()
void TitleBlockTemplateView::analyzeSelectedCells (bool * can_merge, bool * can_split, int * count) virtual
TitleBlockTemplateView::analyzeSelectedCells.
Parameters
can_merge : If non-zero, will be changed to reflect whether selected cells may be merged
can_split : If non-zero, will be changed to reflect whether selected cells may be splitted
count : If non-zero, will be changed to reflect the number of selected cells
Definition at line 457 of file templateview.cpp.
References MergeCellsCommand::canMerge(), SplitCellsCommand::canSplit(), selectedCellsSet(), and tbtemplate_.
applyColumnsWidths
void TitleBlockTemplateView::applyColumnsWidths (bool animate = true) protected virtual slot
Apply the columns widths currently specified by the edited title block template.
Parameters
animate true to animate the change, false otherwise.
Definition at line 574 of file templateview.cpp.
References apply_columns_widths_count_, COL_OFFSET, DEFAULT_ROWS_HELPER_CELLS_WIDTH, extra_cells_width_helper_cell_, form_, preview_width_, removeItem(), ROW_OFFSET, tbgrid_, tbtemplate_, total_width_helper_cell_, QET::Icons::tr, updateColumnsHelperCells(), and updateDisplayedMinMaxWidth().
Referenced by columnsDimensionsChanged(), loadTemplate(), and setPreviewWidth().
applyRowsHeights
void TitleBlockTemplateView::applyRowsHeights (bool animate = true) protected virtual slot
Apply the rows heights currently specified by the edited title block template.
Parameters
animate true to animate the change, false otherwise.
Definition at line 639 of file templateview.cpp.
References apply_rows_heights_count_, DEFAULT_COLS_HELPER_CELLS_HEIGHT, DEFAULT_PREVIEW_HELPER_CELL_HEIGHT, form_, ROW_OFFSET, tbgrid_, tbtemplate_, and updateRowsHelperCells().
Referenced by loadTemplate(), and rowsDimensionsChanged().
cells()
TitleBlockTemplateCellsSet TitleBlockTemplateView::cells (const QRectF & rect) const virtual
Returns
the visual cells contained in the rect
Parameters
rect Rectangle in the coordinates of the QGraphicsWidget representing the title block template.
Definition at line 442 of file templateview.cpp.
References form_, and makeCellsSetFromGraphicsItems().
Referenced by normalizeCells(), and selectedCells().
changePreviewWidth
void TitleBlockTemplateView::changePreviewWidth () slot
Ask the user a new width for the preview
Definition at line 790 of file templateview.cpp.
References TitleBlockDimensionWidget::label(), preview_width_, setPreviewWidth(), TitleBlockDimensionWidget::setValue(), QET::Icons::tr, TitleBlockDimension::value, and TitleBlockDimensionWidget::value().
Referenced by addCells(), and init().
columnsActions()
QList< QAction * > TitleBlockTemplateView::columnsActions () const private
Returns
the list of columns-specific actions.
Definition at line 906 of file templateview.cpp.
References add_column_after_, add_column_before_, delete_column_, and edit_column_dim_.
Referenced by addCells().
columnsDimensionsChanged
void TitleBlockTemplateView::columnsDimensionsChanged () slot
Update the displayed layout. Call this function when the dimensions of columns changed.
Definition at line 932 of file templateview.cpp.
References applyColumnsWidths().
copy
QList< TitleBlockCell * > TitleBlockTemplateView::copy () slot
Export currently selected cells to the clipboard.
Returns
the list of cells copied to the clipboard
Definition at line 156 of file templateview.cpp.
References selectedCells(), and tbtemplate_.
Referenced by cut().
cut
QList< TitleBlockCell * > TitleBlockTemplateView::cut () slot
Export currently selected cells to the clipboard before setting them as empty.
Returns
the list of cells copied to the clipboard
Definition at line 140 of file templateview.cpp.
References copy(), requestGridModification(), and tbtemplate_.
deleteColumn
void TitleBlockTemplateView::deleteColumn () slot
Remove the column at the last index selected when calling the context menu.
Definition at line 377 of file templateview.cpp.
References ModifyTemplateGridCommand::deleteColumn(), lastContextMenuCellIndex(), requestGridModification(), and tbtemplate_.
Referenced by init().
deleteRow
void TitleBlockTemplateView::deleteRow () slot
Remove the row at the last index selected when calling the context menu.
Definition at line 386 of file templateview.cpp.
References ModifyTemplateGridCommand::deleteRow(), lastContextMenuCellIndex(), requestGridModification(), and tbtemplate_.
Referenced by init().
drawBackground()
void TitleBlockTemplateView::drawBackground (QPainter * painter, const QRectF & rect) override protected
Reimplement the way the background is drawn to render the title block template.
Definition at line 418 of file templateview.cpp.
References tbtemplate_.
editColumn
void TitleBlockTemplateView::editColumn (HelperCell * cell = nullptr) slot
Edit the width of a column.
Parameters
cell (optional) HelperCell of the column to be modified. If 0, this method uses the last index selected when calling the context menu.
Definition at line 327 of file templateview.cpp.
References TitleBlockDimensionWidget::label(), lastContextMenuCellIndex(), read_only_, requestGridModification(), TitleBlockDimensionWidget::setReadOnly(), TitleBlockDimensionWidget::setValue(), tbtemplate_, QET::Icons::tr, and TitleBlockDimensionWidget::value().
Referenced by addCells(), and init().
editRow
void TitleBlockTemplateView::editRow (HelperCell * cell = nullptr) slot
Edit the height of a row.
Parameters
cell (optional) HelperCell of the row to be modified. If 0, this method uses the last index selected when calling the context menu.
Definition at line 353 of file templateview.cpp.
References TitleBlockDimensionWidget::label(), lastContextMenuCellIndex(), read_only_, requestGridModification(), TitleBlockDimensionWidget::setReadOnly(), TitleBlockDimensionWidget::setValue(), tbtemplate_, QET::Icons::tr, and TitleBlockDimensionWidget::value().
Referenced by addCells(), and init().
event()
bool TitleBlockTemplateView::event (QEvent * event) override protected
Parameters
event Object describing the received event
Definition at line 824 of file templateview.cpp.
References first_activation_, and zoomFit().
fillWithEmptyCells()
void TitleBlockTemplateView::fillWithEmptyCells () protected virtual
Fill the layout with empty cells where needed.
Definition at line 803 of file templateview.cpp.
References COL_OFFSET, ROW_OFFSET, tbgrid_, and tbtemplate_.
Referenced by loadTemplate().
gridModificationRequested
void TitleBlockTemplateView::gridModificationRequested (TitleBlockTemplateCommand *) signal
Referenced by requestGridModification().
indexOf()
int TitleBlockTemplateView::indexOf (QGraphicsLayoutItem * item) private
Parameters
item an item supposed to be contained in the grid layout.
Returns
the flat index if this item, or -1 if it could not be found.
Definition at line 1044 of file templateview.cpp.
References tbgrid_.
Referenced by removeItem().
init()
void TitleBlockTemplateView::init () protected virtual
Initialize this view (actions, signals/slots connections, etc.)
Definition at line 542 of file templateview.cpp.
References add_column_after_, add_column_before_, add_row_after_, add_row_before_, addColumnAfter(), addColumnBefore(), addRowAfter(), addRowBefore(), change_preview_width_, changePreviewWidth(), delete_column_, delete_row_, deleteColumn(), deleteRow(), edit_column_dim_, edit_row_dim_, editColumn(), editRow(), QET::Icons::EditTableDeleteColumn, QET::Icons::EditTableDeleteRow, QET::Icons::EditTableInsertColumnLeft, QET::Icons::EditTableInsertColumnRight, QET::Icons::EditTableInsertRowAbove, QET::Icons::EditTableInsertRowUnder, selectionChanged(), and QET::Icons::tr.
Referenced by TitleBlockTemplateView().
lastContextMenuCellIndex()
int TitleBlockTemplateView::lastContextMenuCellIndex () const private
Returns
the last index selected when triggering the context menu.
See also
updateLastContextMenuCell
Definition at line 1033 of file templateview.cpp.
References last_context_menu_cell_.
Referenced by addColumnAfter(), addColumnBefore(), addRowAfter(), addRowBefore(), deleteColumn(), deleteRow(), editColumn(), and editRow().
loadTemplate()
void TitleBlockTemplateView::loadTemplate (TitleBlockTemplate * tbt) protected virtual
Load the tbt title block template. If a different template was previously loaded, it is deleted.
Definition at line 863 of file templateview.cpp.
References addCells(), adjustSceneRect(), applyColumnsWidths(), applyRowsHeights(), fillWithEmptyCells(), form_, removeItem(), tbgrid_, and tbtemplate_.
Referenced by setTitleBlockTemplate(), and updateLayout().
makeCellsSetFromGraphicsItems()
TitleBlockTemplateCellsSet TitleBlockTemplateView::makeCellsSetFromGraphicsItems (const QList< QGraphicsItem * > & items) const private
TitleBlockTemplateView::makeCellsSetFromGraphicsItems.
Parameters
items : a list of QGraphicsItem
Returns
the corresponding TitleBlockTemplateCellsSet
Definition at line 1073 of file templateview.cpp.
Referenced by cells(), and selectedCellsSet().
makePrettyToolTip()
QString TitleBlockTemplateView::makePrettyToolTip (const QString & string) private
TitleBlockTemplateView::makePrettyToolTip.
Parameters
string : a text string
Returns
an HTML string that can be passed to setToolTip()
Definition at line 1091 of file templateview.cpp.
Referenced by updateDisplayedMinMaxWidth().
mayPaste
bool TitleBlockTemplateView::mayPaste () slot
Returns
true if the content of the clipboard looks interesting
Definition at line 180 of file templateview.cpp.
mergeSelectedCells
void TitleBlockTemplateView::mergeSelectedCells () slot
Merge the selected cells.
Definition at line 395 of file templateview.cpp.
References requestGridModification(), selectedCellsSet(), and tbtemplate_.
normalizeCells()
void TitleBlockTemplateView::normalizeCells (QList< TitleBlockCell > & cells, int x = 0, int y = 0) const protected virtual
TitleBlockTemplateView::normalizeCells Given a cells list, change their position so the top left one is at row x and column y.
Parameters
cells Cells list
x : row
y : column
Definition at line 840 of file templateview.cpp.
References cells().
Referenced by paste().
paste
void TitleBlockTemplateView::paste () slot
Import the cells described in the clipboard.
Definition at line 238 of file templateview.cpp.
References normalizeCells(), TitleBlockCell::num_col, TitleBlockCell::num_row, pastedCells(), requestGridModification(), selectedCellsSet(), tbtemplate_, and TitleBlockTemplateCellsSet::topLeftCell().
pastedCells
QList< TitleBlockCell > TitleBlockTemplateView::pastedCells () slot
Returns
a list containing the pasted cells
Definition at line 189 of file templateview.cpp.
References QET::attributeIsAnInteger(), TitleBlockCell::col_span, TitleBlockCell::loadContentFromXml(), TitleBlockCell::num_col, TitleBlockCell::num_row, and TitleBlockCell::row_span.
Referenced by paste().
previewWidthChanged
void TitleBlockTemplateView::previewWidthChanged (int , int) signal
Referenced by setPreviewWidth().
refresh
void TitleBlockTemplateView::refresh () slot
Refresh the regular cells.
Definition at line 771 of file templateview.cpp.
References COL_OFFSET, ROW_OFFSET, tbgrid_, and tbtemplate_.
removeItem()
void TitleBlockTemplateView::removeItem (QGraphicsLayoutItem * item) private
Removes an item from the grid layout
Parameters
item an item supposed to be contained in the grid layout.
Definition at line 1055 of file templateview.cpp.
References indexOf(), and tbgrid_.
Referenced by applyColumnsWidths(), and loadTemplate().
requestGridModification()
void TitleBlockTemplateView::requestGridModification (TitleBlockTemplateCommand * command) private
Emit the gridModificationRequested() signal with command after having set its view component.
See also
TitleBlockTemplateCommand::setView()
Parameters
command A command object modifying the rendered title block template.
Definition at line 1023 of file templateview.cpp.
References gridModificationRequested().
Referenced by addColumnAfter(), addColumnAtEnd(), addColumnBefore(), addRowAfter(), addRowAtEnd(), addRowBefore(), cut(), deleteColumn(), deleteRow(), editColumn(), editRow(), mergeSelectedCells(), paste(), and splitSelectedCell().
rowsActions()
QList< QAction * > TitleBlockTemplateView::rowsActions () const private
Returns
the list of rows-specific actions.
Definition at line 899 of file templateview.cpp.
References add_row_after_, add_row_before_, delete_row_, and edit_row_dim_.
Referenced by addCells().
rowsDimensionsChanged
void TitleBlockTemplateView::rowsDimensionsChanged () slot
Update the displayed layout. Call this function when the dimensions of rows changed.
Definition at line 924 of file templateview.cpp.
References applyRowsHeights().
selectedCells()
QList< TitleBlockCell * > TitleBlockTemplateView::selectedCells () const virtual
Returns
the selected logical cells, not including the spanned ones.
Definition at line 426 of file templateview.cpp.
References cells(), and selectedCellsSet().
Referenced by copy(), and selectionChanged().
selectedCellsChanged
void TitleBlockTemplateView::selectedCellsChanged (QList< TitleBlockCell * >) signal
Referenced by selectionChanged().
selectedCellsSet()
TitleBlockTemplateCellsSet TitleBlockTemplateView::selectedCellsSet () const virtual
Returns
the selected visual cells.
Definition at line 433 of file templateview.cpp.
References makeCellsSetFromGraphicsItems().
Referenced by analyzeSelectedCells(), mergeSelectedCells(), paste(), selectedCells(), and splitSelectedCell().
selectionChanged
void TitleBlockTemplateView::selectionChanged () slot
Emits the selectedCellsChanged() signal with the currently selected cells.
Definition at line 98 of file templateview.cpp.
References selectedCells(), and selectedCellsChanged().
Referenced by init().
setPreviewWidth
void TitleBlockTemplateView::setPreviewWidth (int width) slot
Set the new preview width to width
Parameters
width new preview width
Definition at line 991 of file templateview.cpp.
References applyColumnsWidths(), form_, preview_width_, previewWidthChanged(), tbgrid_, and updateTotalWidthLabel().
Referenced by changePreviewWidth().
setReadOnly
void TitleBlockTemplateView::setReadOnly (bool read_only) slot
Parameters
read_only whether this view should be read only.
Definition at line 975 of file templateview.cpp.
References add_column_after_, add_column_before_, add_row_after_, add_row_before_, delete_column_, delete_row_, and read_only_.
setTitleBlockTemplate
void TitleBlockTemplateView::setTitleBlockTemplate (TitleBlockTemplate * tbtemplate) slot
Parameters
tbtemplate Title block template to be rendered by this view. If set to zero, the View will render nothing.
Definition at line 83 of file templateview.cpp.
References loadTemplate(), and zoomFit().
splitSelectedCell
void TitleBlockTemplateView::splitSelectedCell () slot
Split the selected cell.
Definition at line 406 of file templateview.cpp.
References requestGridModification(), selectedCellsSet(), and tbtemplate_.
templateHeight()
qreal TitleBlockTemplateView::templateHeight () const virtual
Returns
the current height of the rendered title block template
Definition at line 505 of file templateview.cpp.
References DEFAULT_COLS_HELPER_CELLS_HEIGHT, DEFAULT_PREVIEW_HELPER_CELL_HEIGHT, and tbtemplate_.
Referenced by templateSize().
templateSize()
QSizeF TitleBlockTemplateView::templateSize () const virtual
Returns
the current size of the rendered title block template
Definition at line 485 of file templateview.cpp.
References templateHeight(), and templateWidth().
Referenced by adjustSceneRect().
templateWidth()
qreal TitleBlockTemplateView::templateWidth () const virtual
Returns
the current width of the rendered title block template
Definition at line 492 of file templateview.cpp.
References DEFAULT_ROWS_HELPER_CELLS_WIDTH, preview_width_, and tbtemplate_.
Referenced by templateSize().
titleBlockTemplate()
TitleBlockTemplate * TitleBlockTemplateView::titleBlockTemplate () const
Returns
The title block template object rendered by this view.
Definition at line 91 of file templateview.cpp.
References tbtemplate_.
updateColumnsHelperCells
void TitleBlockTemplateView::updateColumnsHelperCells () protected virtual slot
Update the content (type and value) of columns helper cells.
Definition at line 687 of file templateview.cpp.
References COL_OFFSET, tbgrid_, tbtemplate_, TitleBlockDimension::toString(), and TitleBlockDimension::type.
Referenced by applyColumnsWidths().
updateDisplayedMinMaxWidth
void TitleBlockTemplateView::updateDisplayedMinMaxWidth () slot
Update the tooltip that displays the minimum and/or maximum width of the template.
Definition at line 940 of file templateview.cpp.
References makePrettyToolTip(), tbtemplate_, total_width_helper_cell_, and QET::Icons::tr.
Referenced by applyColumnsWidths().
updateLastContextMenuCell
void TitleBlockTemplateView::updateLastContextMenuCell (HelperCell * last_context_menu_cell) private slot
Stores last_context_menu_cell as being the last helper cell the context menu was triggered on.
Definition at line 1105 of file templateview.cpp.
References last_context_menu_cell_.
Referenced by addCells().
updateLayout
void TitleBlockTemplateView::updateLayout () slot
Update the displayed layout. Call this function to refresh the display after the rendered title block template has been "deeply" modified, e.g. rows/columns have been added/modified or cells were merged/splitted.
Definition at line 915 of file templateview.cpp.
References loadTemplate(), and tbtemplate_.
updateRowsHelperCells
void TitleBlockTemplateView::updateRowsHelperCells () protected virtual slot
Update the content (type and value) of rows helper cells.
Definition at line 672 of file templateview.cpp.
References QET::Absolute, ROW_OFFSET, tbgrid_, tbtemplate_, and QET::Icons::tr.
Referenced by applyRowsHeights().
updateTotalWidthLabel()
void TitleBlockTemplateView::updateTotalWidthLabel () private
Update the label of the helper cell that indicates the preview width.
Definition at line 1007 of file templateview.cpp.
References preview_width_, total_width_helper_cell_, and QET::Icons::tr.
Referenced by addCells(), and setPreviewWidth().
wheelEvent()
void TitleBlockTemplateView::wheelEvent (QWheelEvent * e) override protected
Handles mouse wheel-related actions
Parameters
e QWheelEvent describing the wheel event
Definition at line 519 of file templateview.cpp.
References zoomIn(), and zoomOut().
zoomFactor()
qreal TitleBlockTemplateView::zoomFactor () const protected virtual
Returns
the zoom factor used by zoomIn() and zoomOut().
Definition at line 535 of file templateview.cpp.
Referenced by zoomIn(), and zoomOut().
zoomFit
void TitleBlockTemplateView::zoomFit () slot
Fit the rendered title block template in this view.
Definition at line 122 of file templateview.cpp.
References adjustSceneRect().
Referenced by event(), and setTitleBlockTemplate().
zoomIn
void TitleBlockTemplateView::zoomIn () slot
Zoom in by zoomFactor().
See also
zoomFactor()
Definition at line 106 of file templateview.cpp.
References zoomFactor().
Referenced by wheelEvent().
zoomOut
void TitleBlockTemplateView::zoomOut () slot
Zoom out by zoomFactor().
See also
zoomFactor()
Definition at line 114 of file templateview.cpp.
References zoomFactor().
Referenced by wheelEvent().
zoomReset
void TitleBlockTemplateView::zoomReset () slot
Reset the zoom level.
Definition at line 130 of file templateview.cpp.
References adjustSceneRect().
Member Data Documentation
add_column_after_
QAction* TitleBlockTemplateView::add_column_after_ private
Definition at line 137 of file templateview.h.
Referenced by columnsActions(), init(), and setReadOnly().
add_column_before_
QAction* TitleBlockTemplateView::add_column_before_ private
Definition at line 136 of file templateview.h.
Referenced by columnsActions(), init(), and setReadOnly().
add_row_after_
QAction * TitleBlockTemplateView::add_row_after_ private
Definition at line 137 of file templateview.h.
Referenced by init(), rowsActions(), and setReadOnly().
add_row_before_
QAction * TitleBlockTemplateView::add_row_before_ private
Definition at line 136 of file templateview.h.
Referenced by init(), rowsActions(), and setReadOnly().
apply_columns_widths_count_
int TitleBlockTemplateView::apply_columns_widths_count_ private
Definition at line 142 of file templateview.h.
Referenced by applyColumnsWidths().
apply_rows_heights_count_
int TitleBlockTemplateView::apply_rows_heights_count_ private
Definition at line 143 of file templateview.h.
Referenced by applyRowsHeights().
change_preview_width_
QAction* TitleBlockTemplateView::change_preview_width_ private
Definition at line 140 of file templateview.h.
Referenced by addCells(), and init().
delete_column_
QAction* TitleBlockTemplateView::delete_column_ private
Definition at line 139 of file templateview.h.
Referenced by columnsActions(), init(), and setReadOnly().
delete_row_
QAction * TitleBlockTemplateView::delete_row_ private
Definition at line 139 of file templateview.h.
Referenced by init(), rowsActions(), and setReadOnly().
edit_column_dim_
QAction* TitleBlockTemplateView::edit_column_dim_ private
Definition at line 138 of file templateview.h.
Referenced by columnsActions(), and init().
edit_row_dim_
QAction * TitleBlockTemplateView::edit_row_dim_ private
Definition at line 138 of file templateview.h.
Referenced by init(), and rowsActions().
extra_cells_width_helper_cell_
HelperCell* TitleBlockTemplateView::extra_cells_width_helper_cell_ private
Definition at line 135 of file templateview.h.
Referenced by addCells(), and applyColumnsWidths().
first_activation_
bool TitleBlockTemplateView::first_activation_ private
Boolean used to detect the first display of this widget.
Definition at line 144 of file templateview.h.
Referenced by event().
form_
QGraphicsWidget* TitleBlockTemplateView::form_ private
Definition at line 132 of file templateview.h.
Referenced by applyColumnsWidths(), applyRowsHeights(), cells(), loadTemplate(), and setPreviewWidth().
last_context_menu_cell_
HelperCell* TitleBlockTemplateView::last_context_menu_cell_ private
Definition at line 141 of file templateview.h.
Referenced by lastContextMenuCellIndex(), and updateLastContextMenuCell().
preview_width_
int TitleBlockTemplateView::preview_width_ private
Definition at line 133 of file templateview.h.
Referenced by applyColumnsWidths(), changePreviewWidth(), setPreviewWidth(), templateWidth(), and updateTotalWidthLabel().
read_only_
bool TitleBlockTemplateView::read_only_ private
Boolean stating whether this view allows template edition.
Definition at line 145 of file templateview.h.
Referenced by addColumnAfter(), addColumnAtEnd(), addColumnBefore(), addRowAfter(), addRowAtEnd(), addRowBefore(), editColumn(), editRow(), and setReadOnly().
tbgrid_
QGraphicsGridLayout* TitleBlockTemplateView::tbgrid_ private
Definition at line 131 of file templateview.h.
Referenced by addCells(), applyColumnsWidths(), applyRowsHeights(), fillWithEmptyCells(), indexOf(), loadTemplate(), refresh(), removeItem(), setPreviewWidth(), updateColumnsHelperCells(), and updateRowsHelperCells().
tbtemplate_
TitleBlockTemplate* TitleBlockTemplateView::tbtemplate_ private
Definition at line 130 of file templateview.h.
Referenced by addCells(), addColumnAfter(), addColumnAtEnd(), addColumnBefore(), addRowAfter(), addRowAtEnd(), addRowBefore(), analyzeSelectedCells(), applyColumnsWidths(), applyRowsHeights(), copy(), cut(), deleteColumn(), deleteRow(), drawBackground(), editColumn(), editRow(), fillWithEmptyCells(), loadTemplate(), mergeSelectedCells(), paste(), refresh(), splitSelectedCell(), templateHeight(), templateWidth(), titleBlockTemplate(), updateColumnsHelperCells(), updateDisplayedMinMaxWidth(), updateLayout(), and updateRowsHelperCells().
total_width_helper_cell_
SplittedHelperCell* TitleBlockTemplateView::total_width_helper_cell_ private
Definition at line 134 of file templateview.h.
Referenced by addCells(), applyColumnsWidths(), updateDisplayedMinMaxWidth(), and updateTotalWidthLabel().
The documentation for this class was generated from the following files:
templateview.h
templateview.cpp