QElectroTech: QETProject Class Reference
QETProject Class Reference
#include <qetproject.h>
Public Types
enum ProjectState {
Ok = 0, FileOpenFailed = 1, XmlParsingFailed = 2, ProjectParsingRunning = 3,
ProjectParsingFailed = 4, FileOpenDiscard = 5
}
Public Slots
Diagram * addNewDiagram (int pos=-1)
QETProject::addNewDiagram Add a new diagram in project at position pos.
void removeDiagram (Diagram *)
QETProject::removeDiagram Remove diagram from project.
void diagramOrderChanged (int, int)
void setModified (bool)
Signals
void projectFilePathChanged (QETProject *, const QString &)
void projectTitleChanged (QETProject *, const QString &)
void projectInformationsChanged (QETProject *)
void diagramAdded (QETProject *, Diagram *)
void diagramRemoved (QETProject *, Diagram *)
void projectModified (QETProject *, bool)
void projectDiagramsOrderChanged (QETProject *, int, int)
void diagramUsedTemplate (TitleBlockTemplatesCollection *, const QString &)
void readOnlyChanged (QETProject *, bool)
void reportPropertiesChanged (const QString &old_str, const QString &new_str)
void XRefPropertiesChanged ()
void addAutoNumDiagram ()
void elementAutoNumAdded (QString name)
void elementAutoNumRemoved (QString name)
void conductorAutoNumAdded ()
void conductorAutoNumRemoved ()
void folioAutoNumAdded ()
void folioAutoNumRemoved ()
void folioAutoNumChanged (QString)
void defaultTitleBlockPropertiesChanged ()
void conductorAutoNumChanged ()
Public Member Functions
QETProject (QObject *parent=nullptr)
QETProject::QETProject Create a empty project.
QETProject (const QString &path, QObject *=nullptr)
QETProject::QETProject Construct a project from a .qet file.
QETProject (KAutoSaveFile *backup, QObject *parent=nullptr)
QETProject::QETProject.
~QETProject () override
QETProject::~QETProject Destructor.
projectDataBase * dataBase ()
QETProject::dataBase.
QUuid uuid () const
QETProject::uuid.
ProjectState state () const
QList< Diagram * > diagrams () const
int folioIndex (const Diagram *) const
XmlElementCollection * embeddedElementCollection () const
QETProject::embeddedCollection.
TitleBlockTemplatesProjectCollection * embeddedTitleBlockTemplatesCollection ()
QString filePath ()
void setFilePath (const QString &)
QETProject::setFilePath Set the filepath of this project file Set a file path also create a backup file according to the path. If a previous path was set, the previous backup file is deleted and a new one is created according to the path.
QString currentDir () const
QString pathNameTitle () const
QString title () const
qreal declaredQElectroTechVersion ()
void setTitle (const QString &)
BorderProperties defaultBorderProperties () const
DEFAULT PROPERTIES.
void setDefaultBorderProperties (const BorderProperties &)
TitleBlockProperties defaultTitleBlockProperties () const
void setDefaultTitleBlockProperties (const TitleBlockProperties &)
QETProject::setDefaultTitleBlockProperties Specify the title block to be used at the creation of a new diagram for this project.
ConductorProperties defaultConductorProperties () const
void setDefaultConductorProperties (const ConductorProperties &)
QString defaultReportProperties () const
void setDefaultReportProperties (const QString &properties)
XRefProperties defaultXRefProperties (const QString &type) const
QHash< QString, XRefProperties > defaultXRefProperties () const
void setDefaultXRefProperties (const QString &type, const XRefProperties &properties)
void setDefaultXRefProperties (QHash< QString, XRefProperties > hash)
QHash< QString, NumerotationContext > conductorAutoNum () const
QETProject::conductorAutoNum.
QHash< QString, NumerotationContext > elementAutoNum () const
QETProject::elementAutoNum.
QHash< QString, NumerotationContext > folioAutoNum () const
QETProject::folioAutoNum.
void addConductorAutoNum (const QString &key, const NumerotationContext &context)
QETProject::addConductorAutoNum Add a new conductor numerotation context. If key already exist, replace old context by the new context.
void addElementAutoNum (const QString &key, const NumerotationContext &context)
QETProject::addElementAutoNum Add a new element numerotation context. If key already exist, replace old context by the new context.
void addFolioAutoNum (const QString &key, const NumerotationContext &context)
QETProject::addFolioAutoNum Add a new folio numerotation context. If key already exist, replace old context by the new context.
void removeConductorAutoNum (const QString &key)
QETProject::removeConductorAutoNum Remove Conductor Numerotation Context stored with key.
void removeElementAutoNum (const QString &key)
QETProject::removeElementAutonum Remove Element Numerotation Context stored with key.
void removeFolioAutoNum (const QString &key)
QETProject::removeFolioAutonum Remove Folio Numerotation Context stored with key.
NumerotationContext conductorAutoNum (const QString &key) const
QETProject::conductorAutoNum Return conductor numerotation context stored with key. If key is not found, return an empty numerotation context.
NumerotationContext folioAutoNum (const QString &key) const
QETProject::folioAutoNum Return folio numerotation context stored with key. If key is not found, return an empty numerotation context.
NumerotationContext elementAutoNum (const QString &key)
QETProject::elementAutoNum Return element numerotation context stored with key. If key is not found, return an empty numerotation context.
QString conductorAutoNumFormula (const QString &key) const
QETProject::conductorAutoNumFormula.
QString conductorCurrentAutoNum () const
QETProject::conductorCurrentAutoNum.
void setCurrentConductorAutoNum (QString autoNum)
QETProject::setCurrentConductorAutoNum.
QString elementAutoNumFormula (const QString &key) const
QETProject::elementAutoNumFormula.
QString elementAutoNumCurrentFormula () const
QETProject::elementAutoNumCurrentFormula.
QString elementCurrentAutoNum () const
QETProject::elementCurrentAutoNum.
void setCurrrentElementAutonum (QString autoNum)
QETProject::setCurrrentElementAutonum.
void freezeExistentElementLabel (bool freeze, int from, int to)
QETProject::freezeExistentElementLabel Freeze Existent Elements in the selected folios.
void freezeNewElementLabel (bool freeze, int from, int to)
QETProject::freezeNewElementLabel Freeze New Elements in the selected folios.
bool isFreezeNewElements ()
QETProject::freezeNewElements.
void setFreezeNewElements (bool)
QETProject::setfreezeNewElements Set Project Wide freeze new elements.
void freezeExistentConductorLabel (bool freeze, int from, int to)
QETProject::freezeExistentConductorLabel Freeze Existent Conductors in the selected folios.
void freezeNewConductorLabel (bool freeze, int from, int to)
QETProject::freezeNewConductorLabel Freeze New Conductors in the selected folios.
bool isFreezeNewConductors ()
QETProject::isFreezeNewConductors.
void setFreezeNewConductors (bool)
QETProject::setfreezeNewConductors Set Project Wide freeze new conductors.
bool autoConductor () const
QETProject::autoConductor.
bool autoElement () const
bool autoFolio () const
void setAutoConductor (bool ac)
QETProject::setAutoConductor.
void setAutoElement (bool ae)
void autoFolioNumberingNewFolios ()
QETProject::autoFolioNumberingNewFolios emit Signal to add new Diagram with autonum properties.
void autoFolioNumberingSelectedFolios (int, int, const QString &)
QETProject::autoFolioNumberingNewFolios.
QDomDocument toXml ()
QETProject::toXml.
bool close ()
QETResult write ()
QETProject::write Save the project in a file.
bool isReadOnly () const
QETProject::isReadOnly.
void setReadOnly (bool)
QETProject::setReadOnly Set this project to read only if read_only = true.
bool isEmpty () const
ElementsLocation importElement (ElementsLocation &location)
QETProject::importElement Import the element represented by location to the embbeded collection of this project.
QString integrateTitleBlockTemplate (const TitleBlockTemplateLocation &, MoveTitleBlockTemplatesHandler *handler)
QETProject::integrateTitleBlockTemplate Integrate a title block template into this project.
bool usesElement (const ElementsLocation &) const
QList< ElementsLocation > unusedElements () const
QETProject::unusedElements.
bool usesTitleBlockTemplate (const TitleBlockTemplateLocation &)
bool projectWasModified ()
bool projectOptionsWereModified ()
DiagramContext projectProperties ()
void setProjectProperties (const DiagramContext &)
QUndoStack * undoStack ()
Properties
bool autoConductor
Private Slots
void updateDiagramsFolioData ()
void updateDiagramsTitleBlockTemplate (TitleBlockTemplatesCollection *, const QString &)
void removeDiagramsTitleBlockTemplate (TitleBlockTemplatesCollection *, const QString &)
void usedTitleBlockTemplateChanged (const QString &)
void undoStackChanged (bool a)
Private Member Functions
QETProject (const QETProject &)
void readProjectXml (QDomDocument &xml_project)
QETProject::readProjectXml Read and make the project from an xml description.
void readDiagramsXml (QDomDocument &xml_project)
QETProject::readDiagramsXml Load the diagrams from the xml description of the project. Note a project can have 0 diagram.
void readElementsCollectionXml (QDomDocument &xml_project)
QETProject::readElementsCollectionXml Load the diagrams from the xml description of the project.
void readProjectPropertiesXml (QDomDocument &xml_project)
QETProject::readProjectPropertiesXml Load project properties from the XML description of the project.
void readDefaultPropertiesXml (QDomDocument &xml_project)
QETProject::readDefaultPropertiesXml load default properties for new diagram, found in the xml of this project or by default find in the QElectroTech global conf.
void writeProjectPropertiesXml (QDomElement &)
void writeDefaultPropertiesXml (QDomElement &)
QETProject::writeDefaultPropertiesXml Export all defaults properties used by a new diagram and his content size of border content of titleblock default conductor defaut folio report default Xref.
void addDiagram (Diagram *diagram, int pos=-1)
QETProject::addDiagram Add a diagram in this project.
NamesList namesListForIntegrationCategory ()
void writeBackup ()
QETProject::writeBackup Write a backup file of this project, in the case that QET crash.
void init ()
QETProject::init.
ProjectState openFile (QFile *file)
QETProject::openFile.
Private Attributes
QString m_file_path
File path this project is saved to.
ProjectState m_state
Current state of the project.
QList< Diagram * > m_diagrams_list
Diagrams carried by the project.
QString project_title_
Project title.
qreal m_project_qet_version = -1
QElectroTech version declared in the XML document at opening time.
bool m_modified = false
Whether options were modified.
bool m_read_only = false
Whether the project is read only.
QString read_only_file_path_
Filepath for which this project is considered read only.
BorderProperties default_border_properties_ = BorderProperties::defaultProperties()
Default dimensions and properties for new diagrams created within the project.
ConductorProperties default_conductor_properties_ = ConductorProperties::defaultProperties()
Default conductor properties for new diagrams created within the project.
TitleBlockProperties default_titleblock_properties_
Default title block properties for new diagrams created within the project.
QString m_default_report_properties = ReportProperties::defaultProperties()
Default report properties.
QHash< QString, XRefProperties > m_default_xref_properties = XRefProperties::defaultProperties()
Default xref properties.
TitleBlockTemplatesProjectCollection m_titleblocks_collection
Embedded title block templates collection.
DiagramContext m_project_properties
project-wide variables that will be made available to child diagrams
QUndoStack * m_undo_stack
undo stack for this project
QHash< QString, NumerotationContext > m_conductor_autonum
Conductor auto numerotation.
QString m_current_conductor_autonum
QHash< QString, NumerotationContext > m_folio_autonum
Folio auto numbering.
QHash< QString, NumerotationContext > m_element_autonum
Element Auto Numbering.
QString m_current_element_autonum
bool m_auto_conductor = true
XmlElementCollection * m_elements_collection = nullptr
bool m_freeze_new_elements = false
bool m_freeze_new_conductors = false
QTimer m_save_backup_timer
QTimer m_autosave_timer
KAutoSaveFile m_backup_file
QUuid m_uuid = QUuid::createUuid()
projectDataBase m_data_base
Detailed Description
This class represents a QET project. Typically saved as a .qet file, it consists in an XML document grouping 0 to n diagrams and embedding an elements collection. This collection enables users to export diagrams on remote machines without wondering whether required elements are available to them.
Definition at line 50 of file qetproject.h.
Member Enumeration Documentation
ProjectState
enum QETProject::ProjectState
Enumerator
Ok
FileOpenFailed
no error
XmlParsingFailed
file opening failed
ProjectParsingRunning
XML parsing failed.
ProjectParsingFailed
the XML content is currently being processed
FileOpenDiscard
the parsing of the XML content failed
Definition at line 55 of file qetproject.h.
Constructor & Destructor Documentation
QETProject() [1/4]
QETProject::QETProject (QObject * parent = nullptr)
QETProject::QETProject Create a empty project.
Parameters
parent
Definition at line 45 of file qetproject.cpp.
References TitleBlockProperties::defaultProperties(), init(), m_elements_collection, and setDefaultTitleBlockProperties().
QETProject() [2/4]
QETProject::QETProject (const QString & path, QObject * parent = nullptr)
QETProject::QETProject Construct a project from a .qet file.
Parameters
path : path of the file
parent : parent QObject
Definition at line 62 of file qetproject.cpp.
References init(), m_state, and openFile().
QETProject() [3/4]
QETProject::QETProject (KAutoSaveFile * backup, QObject * parent = nullptr)
QETProject::QETProject.
Parameters
backup : backup file to open, QETProject take ownership of backup.
parent : parent QObject
Definition at line 81 of file qetproject.cpp.
References init(), m_file_path, m_state, openFile(), setFilePath(), and setReadOnly().
~QETProject()
QETProject::~QETProject () override
QETProject::~QETProject Destructor.
Definition at line 114 of file qetproject.cpp.
References m_diagrams_list.
QETProject() [4/4]
QETProject::QETProject (const QETProject &) private
Member Function Documentation
addAutoNumDiagram
void QETProject::addAutoNumDiagram () signal
Referenced by autoFolioNumberingNewFolios(), and ProjectView::setProject().
addConductorAutoNum()
void QETProject::addConductorAutoNum (const QString & key, const NumerotationContext & context)
QETProject::addConductorAutoNum Add a new conductor numerotation context. If key already exist, replace old context by the new context.
Parameters
key
context
Definition at line 587 of file qetproject.cpp.
References m_conductor_autonum.
Referenced by Diagram::loadCndFolioSeq(), ConductorAutoNumerotation::newProperties(), ConductorAutoNumerotation::numerateNewConductor(), and ProjectAutoNumConfigPage::saveContextConductor().
addDiagram()
void QETProject::addDiagram (Diagram * diagram, int pos = -1) private
QETProject::addDiagram Add a diagram in this project.
Parameters
diagram added diagram
pos postion of the new diagram, by default at the end
Definition at line 1591 of file qetproject.cpp.
References projectDataBase::addDiagram(), Diagram::border_and_titleblock, m_data_base, m_diagrams_list, BorderTitleBlock::needFolioData(), updateDiagramsFolioData(), usedTitleBlockTemplateChanged(), and Diagram::usedTitleBlockTemplateChanged().
Referenced by addNewDiagram(), and readDiagramsXml().
addElementAutoNum()
void QETProject::addElementAutoNum (const QString & key, const NumerotationContext & context)
QETProject::addElementAutoNum Add a new element numerotation context. If key already exist, replace old context by the new context.
Parameters
key
context
Definition at line 598 of file qetproject.cpp.
References elementAutoNumAdded(), and m_element_autonum.
Referenced by Diagram::loadElmtFolioSeq(), ProjectAutoNumConfigPage::saveContextElement(), and Element::setUpFormula().
addFolioAutoNum()
void QETProject::addFolioAutoNum (const QString & key, const NumerotationContext & context)
QETProject::addFolioAutoNum Add a new folio numerotation context. If key already exist, replace old context by the new context.
Parameters
key
context
Definition at line 611 of file qetproject.cpp.
References m_folio_autonum.
Referenced by autoFolioNumberingSelectedFolios(), and ProjectAutoNumConfigPage::saveContextFolio().
addNewDiagram
Diagram * QETProject::addNewDiagram (int pos = -1) slot
QETProject::addNewDiagram Add a new diagram in project at position pos.
Parameters
pos
Returns
the new created diagram
Definition at line 1151 of file qetproject.cpp.
References addDiagram(), Diagram::border_and_titleblock, defaultBorderProperties(), Diagram::defaultConductorProperties, defaultConductorProperties(), defaultTitleBlockProperties(), QET::Diagram, diagramAdded(), BorderTitleBlock::importBorder(), BorderTitleBlock::importTitleBlock(), and isReadOnly().
Referenced by ProjectView::initActions(), and ProjectView::setProject().
autoConductor()
bool QETProject::autoConductor () const
QETProject::autoConductor.
Returns
true if use of auto conductor is authorized. See also Q_PROPERTY autoConductor
Definition at line 766 of file qetproject.cpp.
References m_auto_conductor.
autoElement()
bool QETProject::autoElement () const
autoFolio()
bool QETProject::autoFolio () const
autoFolioNumberingNewFolios()
void QETProject::autoFolioNumberingNewFolios ()
QETProject::autoFolioNumberingNewFolios emit Signal to add new Diagram with autonum properties.
Definition at line 788 of file qetproject.cpp.
References addAutoNumDiagram().
Referenced by ProjectAutoNumConfigPage::applyAutoNum().
autoFolioNumberingSelectedFolios()
void QETProject::autoFolioNumberingSelectedFolios (int from, int to, const QString & autonum)
QETProject::autoFolioNumberingNewFolios.
Parameters
from
to
autonum : used, index from selected tabs "from" and "to" rename folios with selected autonum
Definition at line 799 of file qetproject.cpp.
References addFolioAutoNum(), folioAutoNum(), m_diagrams_list, m_project_properties, NumerotationContextCommands::next(), title(), and NumerotationContextCommands::toRepresentedString().
Referenced by ProjectAutoNumConfigPage::applyAutoNum().
close()
bool QETProject::close ()
Ferme le projet
Definition at line 880 of file qetproject.cpp.
conductorAutoNum() [1/2]
QHash< QString, NumerotationContext > QETProject::conductorAutoNum () const
QETProject::conductorAutoNum.
Returns
All value of conductor autonum stored in project
Definition at line 493 of file qetproject.cpp.
References m_conductor_autonum.
Referenced by AutoNumberingDockWidget::conductorAutoNumChanged(), DiagramPropertiesDialog::DiagramPropertiesDialog(), DiagramPropertiesDialog::editAutonum(), Diagram::loadCndFolioSeq(), ConductorAutoNumerotation::newProperties(), ConductorAutoNumerotation::numerateNewConductor(), MultiPasteDialog::on_m_button_box_accepted(), ProjectAutoNumConfigPage::readValuesFromProject(), AutoNumberingDockWidget::setContext(), ProjectAutoNumConfigPage::updateContextConductor(), and writeDefaultPropertiesXml().
conductorAutoNum() [2/2]
NumerotationContext QETProject::conductorAutoNum (const QString & key) const
QETProject::conductorAutoNum Return conductor numerotation context stored with key. If key is not found, return an empty numerotation context.
Parameters
key
Definition at line 650 of file qetproject.cpp.
References m_conductor_autonum.
conductorAutoNumAdded
void QETProject::conductorAutoNumAdded () signal
Referenced by ProjectAutoNumConfigPage::saveContextConductor().
conductorAutoNumChanged
void QETProject::conductorAutoNumChanged () signal
Referenced by DiagramPropertiesDialog::DiagramPropertiesDialog().
conductorAutoNumFormula()
QString QETProject::conductorAutoNumFormula (const QString & key) const
QETProject::conductorAutoNumFormula.
Parameters
key : autonum title
Returns
Formula of element autonum stored in conductor autonum
Definition at line 548 of file qetproject.cpp.
References m_conductor_autonum, and autonum::numerotationContextToFormula().
Referenced by writeDefaultPropertiesXml().
conductorAutoNumRemoved
void QETProject::conductorAutoNumRemoved () signal
Referenced by ProjectAutoNumConfigPage::removeContextConductor().
conductorCurrentAutoNum()
QString QETProject::conductorCurrentAutoNum () const
QETProject::conductorCurrentAutoNum.
Returns
current conductor autonum title
Definition at line 560 of file qetproject.cpp.
References m_current_conductor_autonum.
Referenced by Diagram::loadCndFolioSeq(), ConductorAutoNumerotation::newProperties(), and ConductorAutoNumerotation::numerateNewConductor().
currentDir()
QString QETProject::currentDir () const
Returns
le dossier contenant le fichier projet si celui-ci a ete enregistre ; dans le cas contraire, cette methode retourne l'emplacement du bureau de l'utilisateur.
Definition at line 298 of file qetproject.cpp.
References m_file_path.
dataBase()
projectDataBase * QETProject::dataBase ()
QETProject::dataBase.
Returns
The data base of this project
Definition at line 124 of file qetproject.cpp.
References m_data_base.
Referenced by Diagram::addItem(), BOMExportDialog::getBom(), ProjectDBModelPropertiesWidget::on_m_refresh_pb_clicked(), Diagram::removeItem(), and ChangeElementInformationCommand::updateProjectDB().
declaredQElectroTechVersion()
qreal QETProject::declaredQElectroTechVersion ()
Returns
la version de QElectroTech declaree dans le fichier projet lorsque celui-ci a ete ouvert ; si ce projet n'a jamais ete enregistre / ouvert depuis un fichier, cette methode retourne -1.
Definition at line 375 of file qetproject.cpp.
References m_project_qet_version.
defaultBorderProperties()
BorderProperties QETProject::defaultBorderProperties () const
DEFAULT PROPERTIES.
Returns
les dimensions par defaut utilisees lors de la creation d'un nouveau schema dans ce projet.
Definition at line 399 of file qetproject.cpp.
References default_border_properties_.
Referenced by addNewDiagram().
defaultConductorProperties()
ConductorProperties QETProject::defaultConductorProperties () const
Returns
le type de conducteur par defaut utilise lors de la creation d'un nouveau schema dans ce projet.
Definition at line 454 of file qetproject.cpp.
References default_conductor_properties_.
Referenced by addNewDiagram().
defaultReportProperties()
QString QETProject::defaultReportProperties () const
Definition at line 466 of file qetproject.cpp.
References m_default_report_properties.
Referenced by DynamicElementTextItem::reportChanged(), DynamicElementTextItem::reportFormulaChanged(), and writeDefaultPropertiesXml().
defaultTitleBlockProperties()
TitleBlockProperties QETProject::defaultTitleBlockProperties () const
Returns
le cartouche par defaut utilise lors de la creation d'un nouveau schema dans ce projet.
Definition at line 416 of file qetproject.cpp.
References default_titleblock_properties_.
Referenced by addNewDiagram(), and AutoNumberingDockWidget::setActive().
defaultTitleBlockPropertiesChanged
void QETProject::defaultTitleBlockPropertiesChanged () signal
Referenced by setDefaultTitleBlockProperties().
defaultXRefProperties() [1/2]
QHash<QString, XRefProperties> QETProject::defaultXRefProperties () const inline
Definition at line 107 of file qetproject.h.
References m_default_xref_properties.
Referenced by writeDefaultPropertiesXml().
defaultXRefProperties() [2/2]
XRefProperties QETProject::defaultXRefProperties (const QString & type) const inline
Definition at line 106 of file qetproject.h.
References m_default_xref_properties.
Referenced by MasterElement::aboutDeleteXref(), ElementTextItemGroup::autoPos(), CrossRefItem::elementPositionText(), CrossRefItem::init(), MasterElement::linkToElement(), DynamicElementTextItem::setPlainText(), CrossRefItem::updateProperties(), DynamicElementTextItem::updateXref(), ElementTextItemGroup::updateXref(), and MasterElement::xrefPropertiesChanged().
diagramAdded
void QETProject::diagramAdded (QETProject * , Diagram *) signal
Referenced by addNewDiagram(), GenericPanel::fillProjectItem(), and ProjectView::setProject().
diagramOrderChanged
void QETProject::diagramOrderChanged (int old_index, int new_index) slot
Gere le fait que l'ordre des schemas ait change
Parameters
old_index ancien indice du schema deplace
new_index nouvel indice du schema deplace Si l'ancien ou le nouvel index est negatif ou superieur au nombre de schemas dans le projet, cette methode ne fait rien. Les index vont de 0 a "nombre de schemas - 1"
Definition at line 1198 of file qetproject.cpp.
References m_diagrams_list, projectDiagramsOrderChanged(), setModified(), and updateDiagramsFolioData().
Referenced by ProjectView::tabMoved().
diagramRemoved
void QETProject::diagramRemoved (QETProject * , Diagram *) signal
Referenced by GenericPanel::fillProjectItem(), removeDiagram(), DynamicElementTextItem::setConnectionForReportFormula(), LinkSingleElementWidget::setElement(), CrossRefItem::setUpConnection(), DynamicElementTextItem::setupFormulaConnection(), DynamicElementTextItem::updateXref(), and ElementTextItemGroup::updateXref().
diagrams()
QList< Diagram * > QETProject::diagrams () const
Returns
la liste des schemas de ce projet
Definition at line 217 of file qetproject.cpp.
References m_diagrams_list.
Referenced by ProjectAutoNumConfigPage::applyManagement(), ElementProvider::ElementProvider(), ConductorNumExport::fillHash(), SearchAndReplaceWidget::fillItemsList(), ProjectView::loadDiagrams(), AutoNumberingManagementW::on_m_apply_folios_rb_clicked(), FolioAutonumberingW::on_m_autonumber_tabs_rb_clicked(), FolioAutonumberingW::on_m_from_cb_currentIndexChanged(), AutoNumberingManagementW::on_m_from_folios_cb_currentIndexChanged(), readDiagramsXml(), QETDiagramEditor::setUpActions(), usesElement(), and usesTitleBlockTemplate().
diagramUsedTemplate
void QETProject::diagramUsedTemplate (TitleBlockTemplatesCollection * , const QString &) signal
Referenced by GenericPanel::fillProjectItem(), GenericPanel::fillTemplatesCollectionItem(), and usedTitleBlockTemplateChanged().
elementAutoNum() [1/2]
QHash< QString, NumerotationContext > QETProject::elementAutoNum () const
QETProject::elementAutoNum.
Returns
All value of element autonum stored in project
Definition at line 501 of file qetproject.cpp.
References m_element_autonum.
Referenced by AutoNumberingDockWidget::elementAutoNumChanged(), Diagram::loadElmtFolioSeq(), MultiPasteDialog::on_m_button_box_accepted(), ProjectAutoNumConfigPage::readValuesFromProject(), AutoNumberingDockWidget::setContext(), Element::setUpFormula(), ProjectAutoNumConfigPage::updateContextElement(), and writeDefaultPropertiesXml().
elementAutoNum() [2/2]
NumerotationContext QETProject::elementAutoNum (const QString & key)
QETProject::elementAutoNum Return element numerotation context stored with key. If key is not found, return an empty numerotation context.
Parameters
key
Definition at line 661 of file qetproject.cpp.
References m_element_autonum.
elementAutoNumAdded
void QETProject::elementAutoNumAdded (QString name) signal
Referenced by addElementAutoNum().
elementAutoNumCurrentFormula()
QString QETProject::elementAutoNumCurrentFormula () const
QETProject::elementAutoNumCurrentFormula.
Returns
current formula being used by project
Definition at line 523 of file qetproject.cpp.
References elementAutoNumFormula(), and m_current_element_autonum.
Referenced by AutoNumberingDockWidget::setActive(), and Element::setUpFormula().
elementAutoNumFormula()
QString QETProject::elementAutoNumFormula (const QString & key) const
QETProject::elementAutoNumFormula.
Parameters
key : autonum title
Returns
Formula of element autonum stored in element autonum
Definition at line 510 of file qetproject.cpp.
References m_element_autonum, and autonum::numerotationContextToFormula().
Referenced by elementAutoNumCurrentFormula(), and writeDefaultPropertiesXml().
elementAutoNumRemoved
void QETProject::elementAutoNumRemoved (QString name) signal
Referenced by removeElementAutoNum().
elementCurrentAutoNum()
QString QETProject::elementCurrentAutoNum () const
QETProject::elementCurrentAutoNum.
Returns
current element autonum title
Definition at line 531 of file qetproject.cpp.
References m_current_element_autonum.
Referenced by Diagram::loadElmtFolioSeq(), AutoNumberingDockWidget::setActive(), and Element::setUpFormula().
embeddedElementCollection()
XmlElementCollection * QETProject::embeddedElementCollection () const
QETProject::embeddedCollection.
Returns
The embedded collection
Definition at line 236 of file qetproject.cpp.
References m_elements_collection.
Referenced by ProjectView::cleanProject(), ElementsCollectionModel::elementIntegratedToCollection(), ElementsLocation::exist(), ElementCollectionHandler::importFromProject(), ElementsCollectionModel::itemRemovedFromCollection(), ElementsLocation::nameList(), XmlProjectElementCollectionItem::populate(), ElementsLocation::projectCollection(), ElementsLocation::pugiXml(), XmlProjectElementCollectionItem::setProject(), ElementsLocation::setXml(), ElementsCollectionModel::updateItem(), and ElementsLocation::xml().
embeddedTitleBlockTemplatesCollection()
TitleBlockTemplatesProjectCollection * QETProject::embeddedTitleBlockTemplatesCollection ()
Returns
the title block templates collection enbeedded within this project
Definition at line 243 of file qetproject.cpp.
References m_titleblocks_collection.
Referenced by ProjectView::cleanProject(), QETTitleBlockTemplateEditor::edit(), NewDiagramPage::NewDiagramPage(), Diagram::setTitleBlockTemplate(), Diagram::titleBlockTemplateRemoved(), and usedTitleBlockTemplateChanged().
filePath()
QString QETProject::filePath ()
Returns
le chemin du fichier dans lequel ce projet est enregistre
Definition at line 250 of file qetproject.cpp.
References m_file_path.
Referenced by QETApp::checkBackupFiles(), projectDataBase::exportDb(), QETDiagramEditor::generateTerminalBlock(), setFilePath(), updateDiagramsFolioData(), and write().
folioAutoNum() [1/2]
QHash< QString, NumerotationContext > QETProject::folioAutoNum () const
QETProject::folioAutoNum.
Returns
All value of folio autonum stored in project
Definition at line 576 of file qetproject.cpp.
References m_folio_autonum.
Referenced by autoFolioNumberingSelectedFolios(), AutoNumberingDockWidget::folioAutoNumChanged(), ProjectAutoNumConfigPage::readValuesFromProject(), AutoNumberingDockWidget::setContext(), ProjectAutoNumConfigPage::updateContextFolio(), updateDiagramsFolioData(), and writeDefaultPropertiesXml().
folioAutoNum() [2/2]
NumerotationContext QETProject::folioAutoNum (const QString & key) const
QETProject::folioAutoNum Return folio numerotation context stored with key. If key is not found, return an empty numerotation context.
Parameters
key
Definition at line 672 of file qetproject.cpp.
References m_folio_autonum.
folioAutoNumAdded
void QETProject::folioAutoNumAdded () signal
Referenced by ProjectAutoNumConfigPage::saveContextFolio().
folioAutoNumChanged
void QETProject::folioAutoNumChanged (QString) signal
folioAutoNumRemoved
void QETProject::folioAutoNumRemoved () signal
Referenced by ProjectAutoNumConfigPage::removeContextFolio().
folioIndex()
int QETProject::folioIndex (const Diagram * diagram) const
Parameters
diagram Pointer to a Diagram object
Returns
the folio number of the given diagram object within the project, or -1 if it is not part of this project. Note: this returns 0 for the first diagram, not 1
Definition at line 227 of file qetproject.cpp.
References m_diagrams_list.
Referenced by ProjectView::diagramAdded().
freezeExistentConductorLabel()
void QETProject::freezeExistentConductorLabel (bool freeze, int from, int to)
QETProject::freezeExistentConductorLabel Freeze Existent Conductors in the selected folios.
Parameters
freeze
from - first folio index to apply freeze
to - last folio index to apply freeze
Definition at line 684 of file qetproject.cpp.
References m_diagrams_list.
Referenced by ProjectAutoNumConfigPage::applyManagement().
freezeExistentElementLabel()
void QETProject::freezeExistentElementLabel (bool freeze, int from, int to)
QETProject::freezeExistentElementLabel Freeze Existent Elements in the selected folios.
Parameters
freeze
from - first folio index to apply freeze
to - last folio index to apply freeze
Definition at line 726 of file qetproject.cpp.
References m_diagrams_list.
Referenced by ProjectAutoNumConfigPage::applyManagement().
freezeNewConductorLabel()
void QETProject::freezeNewConductorLabel (bool freeze, int from, int to)
QETProject::freezeNewConductorLabel Freeze New Conductors in the selected folios.
Parameters
freeze
from - first folio index to apply freeze
to - last folio index to apply freeze
Definition at line 697 of file qetproject.cpp.
References m_diagrams_list.
Referenced by ProjectAutoNumConfigPage::applyManagement().
freezeNewElementLabel()
void QETProject::freezeNewElementLabel (bool freeze, int from, int to)
QETProject::freezeNewElementLabel Freeze New Elements in the selected folios.
Parameters
freeze
from - first folio index to apply freeze
to - last folio index to apply freeze
Definition at line 739 of file qetproject.cpp.
References m_diagrams_list.
Referenced by ProjectAutoNumConfigPage::applyManagement().
importElement()
ElementsLocation QETProject::importElement (ElementsLocation & location)
QETProject::importElement Import the element represented by location to the embbeded collection of this project.
Parameters
location
Returns
the location of the imported element, location can be null.
Definition at line 972 of file qetproject.cpp.
References ImportElementDialog::action(), XmlElementCollection::addElement(), ElementsLocation::collectionPath(), XmlElementCollection::copy(), QET::Erase, XmlElementCollection::exist(), ElementsLocation::exist(), ElementsLocation::fileName(), QET::Ignore, ElementsLocation::isElement(), ElementsLocation::isFileSystem(), ElementsLocation::isProject(), m_elements_collection, ElementsLocation::parent(), ElementsLocation::project(), ElementsLocation::projectCollectionPath(), QET::Rename, and ElementsLocation::uuid().
Referenced by DiagramEventAddElement::buildElement().
init()
void QETProject::init () private
QETProject::init.
Definition at line 139 of file qetproject.cpp.
References TitleBlockTemplatesCollection::aboutToRemove(), BACKUP_INTERVAL, TitleBlockTemplatesCollection::changed(), m_autosave_timer, m_file_path, m_save_backup_timer, m_titleblocks_collection, m_undo_stack, removeDiagramsTitleBlockTemplate(), undoStackChanged(), updateDiagramsTitleBlockTemplate(), and writeBackup().
Referenced by QETProject().
integrateTitleBlockTemplate()
QString QETProject::integrateTitleBlockTemplate (const TitleBlockTemplateLocation & src_tbt, MoveTitleBlockTemplatesHandler * handler)
QETProject::integrateTitleBlockTemplate Integrate a title block template into this project.
Parameters
src_tbt The location of the title block template to be integrated into this project
handler
Returns
the name of the template after integration, or an empty QString if a problem occurred.
Definition at line 1065 of file qetproject.cpp.
References QET::Abort, QET::Erase, TitleBlockTemplateLocation::getTemplateXmlDescription(), QET::Ignore, m_titleblocks_collection, QET::Managed, TitleBlockTemplateLocation::name(), QET::Rename, QET::Retry, TitleBlockTemplatesProjectCollection::setTemplateXmlDescription(), TitleBlockTemplatesProjectCollection::templates(), and QET::Icons::tr.
Referenced by DiagramView::handleTitleBlockDrop(), and setDefaultTitleBlockProperties().
isEmpty()
bool QETProject::isEmpty () const
Returns
true si le projet peut etre considere comme vide, c'est-a-dire :
soit avec une collection embarquee vide
soit avec uniquement des schemas consideres comme vides
soit avec un titre de projet
Definition at line 950 of file qetproject.cpp.
References m_diagrams_list, and project_title_.
isFreezeNewConductors()
bool QETProject::isFreezeNewConductors ()
QETProject::isFreezeNewConductors.
Returns
freeze new conductors Project Wide status
Definition at line 707 of file qetproject.cpp.
References m_freeze_new_conductors.
Referenced by DiagramEventAddElement::addElement(), and MultiPasteDialog::on_m_button_box_accepted().
isFreezeNewElements()
bool QETProject::isFreezeNewElements ()
QETProject::freezeNewElements.
Returns
freeze new elements Project Wide status
Definition at line 749 of file qetproject.cpp.
References m_freeze_new_elements.
isReadOnly()
bool QETProject::isReadOnly () const
QETProject::isReadOnly.
Returns
true si le projet est en mode readonly, false sinon
Definition at line 924 of file qetproject.cpp.
References m_file_path, m_read_only, and read_only_file_path_.
Referenced by addNewDiagram(), ElementsLocation::isWritable(), pathNameTitle(), removeDiagram(), setTitle(), and write().
namesListForIntegrationCategory()
NamesList QETProject::namesListForIntegrationCategory () private
Returns
La liste des noms a utiliser pour la categorie dediee aux elements integres automatiquement dans le projet.
Definition at line 1617 of file qetproject.cpp.
References NamesList::addName().
openFile()
QETProject::ProjectState QETProject::openFile (QFile * file) private
QETProject::openFile.
Parameters
file
Returns
Definition at line 172 of file qetproject.cpp.
References FileOpenFailed, readProjectXml(), setFilePath(), setReadOnly(), and XmlParsingFailed.
Referenced by QETProject().
pathNameTitle()
QString QETProject::pathNameTitle () const
Returns
une chaine de caractere du type "Projet titre du projet". Si le projet n'a pas de titre, le nom du fichier est utilise. Si le projet n'est pas associe a un fichier, cette methode retourne "Projet sans titre". De plus, si le projet est en lecture seule, le tag "[lecture seule]" est ajoute.
Definition at line 317 of file qetproject.cpp.
References isReadOnly(), m_file_path, m_modified, project_title_, and QET::Icons::tr.
projectDiagramsOrderChanged
void QETProject::projectDiagramsOrderChanged (QETProject * , int , int) signal
Referenced by diagramOrderChanged(), GenericPanel::fillProjectItem(), DynamicElementTextItem::removeConnectionForReportFormula(), DynamicElementTextItem::setConnectionForReportFormula(), CrossRefItem::setUpConnection(), Conductor::setUpConnectionForFormula(), DynamicElementTextItem::setupFormulaConnection(), DynamicElementTextItem::updateXref(), and ElementTextItemGroup::updateXref().
projectFilePathChanged
void QETProject::projectFilePathChanged (QETProject * , const QString &) signal
Referenced by setFilePath().
projectInformationsChanged
void QETProject::projectInformationsChanged (QETProject *) signal
Referenced by setFilePath(), setModified(), setTitle(), GenericPanel::updateProjectItem(), and write().
projectModified
void QETProject::projectModified (QETProject * , bool) signal
Referenced by setModified(), and ProjectView::setProject().
projectOptionsWereModified()
bool QETProject::projectOptionsWereModified ()
Returns
true if project options (title, project-wide properties, settings for new diagrams, diagrams order...) were modified, false otherwise.
Definition at line 1660 of file qetproject.cpp.
References m_modified.
Referenced by projectWasModified().
projectProperties()
DiagramContext QETProject::projectProperties ()
Returns
the project-wide properties made available to child diagrams.
Definition at line 1669 of file qetproject.cpp.
References m_project_properties.
Referenced by autonum::AssignVariables::assignProjectVar().
projectTitleChanged
void QETProject::projectTitleChanged (QETProject * , const QString &) signal
Referenced by ProjectView::setProject(), and setTitle().
projectWasModified()
bool QETProject::projectWasModified ()
Cette methode sert a reperer un projet vide, c-a-d un projet identique a ce que l'on obtient en faisant Fichier > Nouveau.
Returns
true si les schemas, la collection embarquee ou les proprietes de ce projet ont ete modifies. Concretement, le projet doit avoir un titre vide et ni ses schemas ni sa collection embarquee ne doivent avoir ete modifies.
See also
diagramsWereModified(), embeddedCollectionWasModified()
Definition at line 1690 of file qetproject.cpp.
References m_titleblocks_collection, m_undo_stack, projectOptionsWereModified(), and TitleBlockTemplatesProjectCollection::templates().
readDefaultPropertiesXml()
void QETProject::readDefaultPropertiesXml (QDomDocument & xml_project) private
QETProject::readDefaultPropertiesXml load default properties for new diagram, found in the xml of this project or by default find in the QElectroTech global conf.
Parameters
xml_project : the xml description of the project
Definition at line 1407 of file qetproject.cpp.
References default_border_properties_, default_conductor_properties_, default_titleblock_properties_, ReportProperties::defaultProperties(), BorderProperties::defaultProperties(), TitleBlockProperties::defaultProperties(), XRefProperties::defaultProperties(), ConductorProperties::defaultProperties(), QET::findInDomElement(), BorderProperties::fromXml(), TitleBlockProperties::fromXml(), XRefProperties::fromXml(), NumerotationContext::fromXml(), ConductorProperties::fromXml(), m_conductor_autonum, m_current_conductor_autonum, m_current_element_autonum, m_default_report_properties, m_default_xref_properties, m_element_autonum, m_folio_autonum, m_freeze_new_conductors, m_freeze_new_elements, and setDefaultReportProperties().
Referenced by readProjectXml().
readDiagramsXml()
void QETProject::readDiagramsXml (QDomDocument & xml_project) private
QETProject::readDiagramsXml Load the diagrams from the xml description of the project. Note a project can have 0 diagram.
Parameters
xml_project
Definition at line 1292 of file qetproject.cpp.
References addDiagram(), QET::attributeIsAnInteger(), QET::Diagram, diagrams(), DialogWaiting::hasInstance(), Diagram::initFromXml(), DialogWaiting::instance(), m_data_base, DialogWaiting::progressBarValue(), DialogWaiting::setDetail(), DialogWaiting::setProgressBar(), DialogWaiting::setProgressBarRange(), DialogWaiting::setTitle(), setTitle(), Diagram::title(), QET::Icons::tr, and projectDataBase::updateDB().
Referenced by readProjectXml().
readElementsCollectionXml()
void QETProject::readElementsCollectionXml (QDomDocument & xml_project) private
QETProject::readElementsCollectionXml Load the diagrams from the xml description of the project.
Parameters
xml_project : the xml description of the project
Definition at line 1369 of file qetproject.cpp.
References m_elements_collection.
Referenced by readProjectXml().
readOnlyChanged
void QETProject::readOnlyChanged (QETProject * , bool) signal
Referenced by ProjectView::setProject(), setReadOnly(), and GenericPanel::updateProjectItem().
readProjectPropertiesXml()
void QETProject::readProjectPropertiesXml (QDomDocument & xml_project) private
QETProject::readProjectPropertiesXml Load project properties from the XML description of the project.
Parameters
xml_project : the xml description of the project
Definition at line 1395 of file qetproject.cpp.
References QET::findInDomElement(), DiagramContext::fromXml(), and m_project_properties.
Referenced by readProjectXml().
readProjectXml()
void QETProject::readProjectXml (QDomDocument & xml_project) private
QETProject::readProjectXml Read and make the project from an xml description.
Parameters
xml_project : the description of the project from an xml
Definition at line 1226 of file qetproject.cpp.
References QET::Icons::Cancel, FileOpenDiscard, TitleBlockTemplatesProjectCollection::fromXml(), m_data_base, m_project_qet_version, m_state, m_titleblocks_collection, Ok, ProjectParsingFailed, ProjectParsingRunning, readDefaultPropertiesXml(), readDiagramsXml(), readElementsCollectionXml(), readProjectPropertiesXml(), setTitle(), QET::Icons::tr, projectDataBase::updateDB(), QET::version, and QET::QetMessageBox::warning().
Referenced by openFile().
removeConductorAutoNum()
void QETProject::removeConductorAutoNum (const QString & key)
QETProject::removeConductorAutoNum Remove Conductor Numerotation Context stored with key.
Parameters
key
Definition at line 620 of file qetproject.cpp.
References m_conductor_autonum.
removeDiagram
void QETProject::removeDiagram (Diagram * diagram) slot
QETProject::removeDiagram Remove diagram from project.
Parameters
diagram
Definition at line 1173 of file qetproject.cpp.
References diagramRemoved(), isReadOnly(), m_data_base, m_diagrams_list, projectDataBase::removeDiagram(), and updateDiagramsFolioData().
removeDiagramsTitleBlockTemplate
void QETProject::removeDiagramsTitleBlockTemplate (TitleBlockTemplatesCollection * collection, const QString & template_name) private slot
Inform each diagram that the template_name title block is about to be removed.
Parameters
collection Title block templates collection
template_name Name of the removed template
Definition at line 1767 of file qetproject.cpp.
References m_diagrams_list.
Referenced by init().
removeElementAutoNum()
void QETProject::removeElementAutoNum (const QString & key)
QETProject::removeElementAutonum Remove Element Numerotation Context stored with key.
Parameters
key
Definition at line 629 of file qetproject.cpp.
References elementAutoNumRemoved(), and m_element_autonum.
Referenced by ProjectAutoNumConfigPage::removeContextElement().
removeFolioAutoNum()
void QETProject::removeFolioAutoNum (const QString & key)
QETProject::removeFolioAutonum Remove Folio Numerotation Context stored with key.
Parameters
key
Definition at line 640 of file qetproject.cpp.
References m_folio_autonum.
reportPropertiesChanged
void QETProject::reportPropertiesChanged (const QString & old_str, const QString & new_str) signal
Referenced by DynamicElementTextItem::itemChange(), DynamicElementTextItem::reportChanged(), and setDefaultReportProperties().
setAutoConductor()
void QETProject::setAutoConductor (bool ac)
QETProject::setAutoConductor.
Parameters
ac Enable the use of auto conductor if true See also Q_PROPERTY autoConductor
Definition at line 777 of file qetproject.cpp.
References m_auto_conductor.
setAutoElement()
void QETProject::setAutoElement (bool ae)
setCurrentConductorAutoNum()
void QETProject::setCurrentConductorAutoNum (QString autoNum)
QETProject::setCurrentConductorAutoNum.
Parameters
autoNum set the current conductor autonum to autonum
Definition at line 568 of file qetproject.cpp.
References m_current_conductor_autonum.
Referenced by MultiPasteDialog::on_m_button_box_accepted(), AutoNumberingDockWidget::on_m_conductor_cb_activated(), and ProjectAutoNumConfigPage::saveContextConductor().
setCurrrentElementAutonum()
void QETProject::setCurrrentElementAutonum (QString autoNum)
QETProject::setCurrrentElementAutonum.
Parameters
autoNum : set the current element autonum to autonum
Definition at line 539 of file qetproject.cpp.
References m_current_element_autonum.
Referenced by MultiPasteDialog::on_m_button_box_accepted(), AutoNumberingDockWidget::on_m_element_cb_activated(), and ProjectAutoNumConfigPage::saveContextElement().
setDefaultBorderProperties()
void QETProject::setDefaultBorderProperties (const BorderProperties & border)
Permet de specifier les dimensions par defaut utilisees lors de la creation d'un nouveau schema dans ce projet.
Parameters
border dimensions d'un schema
Definition at line 408 of file qetproject.cpp.
References default_border_properties_.
setDefaultConductorProperties()
void QETProject::setDefaultConductorProperties (const ConductorProperties & conductor)
Permet de specifier e type de conducteur par defaut utilise lors de la creation d'un nouveau schema dans ce projet.
Definition at line 462 of file qetproject.cpp.
References default_conductor_properties_.
setDefaultReportProperties()
void QETProject::setDefaultReportProperties (const QString & properties)
Definition at line 470 of file qetproject.cpp.
References m_default_report_properties, and reportPropertiesChanged().
Referenced by readDefaultPropertiesXml().
setDefaultTitleBlockProperties()
void QETProject::setDefaultTitleBlockProperties (const TitleBlockProperties & titleblock)
QETProject::setDefaultTitleBlockProperties Specify the title block to be used at the creation of a new diagram for this project.
Parameters
titleblock
Definition at line 425 of file qetproject.cpp.
References TitleBlockProperties::collection, QET::Common, QETApp::commonTitleBlockTemplatesCollection(), QET::Custom, QETApp::customTitleBlockTemplatesCollection(), default_titleblock_properties_, defaultTitleBlockPropertiesChanged(), QET::Embedded, integrateTitleBlockTemplate(), and TitleBlockProperties::template_name.
Referenced by AutoNumberingDockWidget::on_m_folio_cb_activated(), and QETProject().
setDefaultXRefProperties() [1/2]
void QETProject::setDefaultXRefProperties (const QString & type, const XRefProperties & properties)
Definition at line 478 of file qetproject.cpp.
References m_default_xref_properties, and XRefPropertiesChanged().
setDefaultXRefProperties() [2/2]
void QETProject::setDefaultXRefProperties (QHash< QString, XRefProperties > hash)
Definition at line 483 of file qetproject.cpp.
References m_default_xref_properties, and XRefPropertiesChanged().
setFilePath()
void QETProject::setFilePath (const QString & filepath)
QETProject::setFilePath Set the filepath of this project file Set a file path also create a backup file according to the path. If a previous path was set, the previous backup file is deleted and a new one is created according to the path.
Parameters
filepath
Definition at line 262 of file qetproject.cpp.
References DiagramContext::addValue(), filePath(), m_backup_file, m_file_path, m_project_properties, projectFilePathChanged(), projectInformationsChanged(), setReadOnly(), and updateDiagramsFolioData().
Referenced by openFile(), and QETProject().
setFreezeNewConductors()
void QETProject::setFreezeNewConductors (bool set)
QETProject::setfreezeNewConductors Set Project Wide freeze new conductors.
Definition at line 715 of file qetproject.cpp.
References m_freeze_new_conductors.
Referenced by ProjectAutoNumConfigPage::applyManagement().
setFreezeNewElements()
void QETProject::setFreezeNewElements (bool set)
QETProject::setfreezeNewElements Set Project Wide freeze new elements.
Definition at line 757 of file qetproject.cpp.
References m_freeze_new_elements.
Referenced by ProjectAutoNumConfigPage::applyManagement().
setModified
void QETProject::setModified (bool modified) slot
Mark this project as modified and emit the projectModified() signal.
Definition at line 1213 of file qetproject.cpp.
References m_modified, projectInformationsChanged(), and projectModified().
Referenced by ProjectView::diagramAdded(), diagramOrderChanged(), undoStackChanged(), and write().
setProjectProperties()
void QETProject::setProjectProperties (const DiagramContext & context)
Use context as project-wide properties made available to child diagrams.
Definition at line 1676 of file qetproject.cpp.
References m_project_properties, and updateDiagramsFolioData().
setReadOnly()
void QETProject::setReadOnly (bool read_only)
QETProject::setReadOnly Set this project to read only if read_only = true.
Parameters
read_only
Definition at line 933 of file qetproject.cpp.
References m_file_path, m_read_only, read_only_file_path_, and readOnlyChanged().
Referenced by openFile(), QETProject(), and setFilePath().
setTitle()
void QETProject::setTitle (const QString & title)
Parameters
title le nouveau titre du projet
Definition at line 382 of file qetproject.cpp.
References isReadOnly(), project_title_, projectInformationsChanged(), projectTitleChanged(), title(), and updateDiagramsFolioData().
Referenced by readDiagramsXml(), and readProjectXml().
state()
QETProject::ProjectState QETProject::state () const
Cette methode peut etre utilisee pour tester la bonne ouverture d'un projet
Returns
l'etat du projet
See also
ProjectState
Definition at line 210 of file qetproject.cpp.
References m_state.
Referenced by QETDiagramEditor::openBackupFiles().
title()
QString QETProject::title () const
Returns
le titre du projet
Definition at line 366 of file qetproject.cpp.
References project_title_.
Referenced by autoFolioNumberingSelectedFolios(), XmlProjectElementCollectionItem::localName(), setTitle(), ConductorNumExport::toCsv(), toXml(), ProjectView::tryClosingDiagrams(), and updateDiagramsFolioData().
toXml()
QDomDocument QETProject::toXml ()
QETProject::toXml.
Returns
un document XML representant le projet
Definition at line 824 of file qetproject.cpp.
References TitleBlockTemplatesProjectCollection::getTemplateXmlDescription(), m_diagrams_list, m_elements_collection, m_titleblocks_collection, project_title_, XmlElementCollection::root(), TitleBlockTemplatesProjectCollection::templates(), title(), QET::version, writeDefaultPropertiesXml(), and writeProjectPropertiesXml().
Referenced by write(), and writeBackup().
undoStack()
QUndoStack* QETProject::undoStack () inline
Definition at line 168 of file qetproject.h.
References m_undo_stack.
Referenced by ProjectView::doSave(), SearchAndReplaceWorker::replaceAdvanced(), SearchAndReplaceWorker::replaceConductor(), SearchAndReplaceWorker::replaceDiagram(), SearchAndReplaceWorker::replaceElement(), SearchAndReplaceWorker::replaceIndiText(), and Diagram::undoStack().
undoStackChanged
void QETProject::undoStackChanged (bool a) inline private slot
Definition at line 204 of file qetproject.h.
References setModified().
Referenced by init().
unusedElements()
QList< ElementsLocation > QETProject::unusedElements () const
QETProject::unusedElements.
Returns
the list of unused element (exactly her location) An unused element, is an element present in the embedded collection but not present in a diagram of this project. Be aware that an element can be not present in a diagram, but managed by an undo command (delete an element), so an unused element can be used after an undo.
Definition at line 1117 of file qetproject.cpp.
References XmlElementCollection::elementsLocation(), ElementsLocation::isElement(), m_elements_collection, and usesElement().
Referenced by XmlElementCollection::cleanUnusedElement().
updateDiagramsFolioData
void QETProject::updateDiagramsFolioData () private slot
Indique a chaque schema du projet quel est son numero de folio et combien de folio le projet contient.
Definition at line 1705 of file qetproject.cpp.
References DiagramContext::addValue(), filePath(), folioAutoNum(), m_diagrams_list, m_project_properties, NumerotationContextCommands::next(), title(), and NumerotationContextCommands::toRepresentedString().
Referenced by addDiagram(), diagramOrderChanged(), removeDiagram(), setFilePath(), setProjectProperties(), setTitle(), and write().
updateDiagramsTitleBlockTemplate
void QETProject::updateDiagramsTitleBlockTemplate (TitleBlockTemplatesCollection * collection, const QString & template_name) private slot
Inform each diagram that the template_name title block changed.
Parameters
collection Title block templates collection
template_name Name of the changed template
Definition at line 1754 of file qetproject.cpp.
References m_diagrams_list.
Referenced by init().
usedTitleBlockTemplateChanged
void QETProject::usedTitleBlockTemplateChanged (const QString & template_name) private slot
Handles the fact a digram changed the title block template it used
Parameters
template_name Name of the template
Definition at line 1780 of file qetproject.cpp.
References diagramUsedTemplate(), and embeddedTitleBlockTemplatesCollection().
Referenced by addDiagram().
usesElement()
bool QETProject::usesElement (const ElementsLocation & location) const
Permet de savoir si un element est utilise dans un projet
Parameters
location Emplacement d'un element
Returns
true si l'element location est utilise sur au moins un des schemas de ce projet, false sinon
Definition at line 1100 of file qetproject.cpp.
References diagrams().
Referenced by unusedElements().
usesTitleBlockTemplate()
bool QETProject::usesTitleBlockTemplate (const TitleBlockTemplateLocation & location)
Parameters
location Location of a title block template
Returns
true if the provided template is used by at least one diagram within this project, false otherwise
Definition at line 1133 of file qetproject.cpp.
References diagrams(), TitleBlockTemplateLocation::name(), and TitleBlockTemplateLocation::parentProject().
uuid()
QUuid QETProject::uuid () const
QETProject::uuid.
Returns
the uuid of this project
Definition at line 132 of file qetproject.cpp.
References m_uuid.
Referenced by projectDataBase::exportDb().
write()
QETResult QETProject::write ()
QETProject::write Save the project in a file.
See also
filePath()
setFilePath()
Returns
true if the project was successfully saved, else false
Definition at line 891 of file qetproject.cpp.
References DiagramContext::addValue(), filePath(), isReadOnly(), m_file_path, m_project_properties, projectInformationsChanged(), setModified(), toXml(), updateDiagramsFolioData(), and QET::writeXmlFile().
writeBackup()
void QETProject::writeBackup () private
QETProject::writeBackup Write a backup file of this project, in the case that QET crash.
Definition at line 1647 of file qetproject.cpp.
References m_backup_file, toXml(), and QET::writeToFile().
Referenced by init().
writeDefaultPropertiesXml()
void QETProject::writeDefaultPropertiesXml (QDomElement & xml_element) private
QETProject::writeDefaultPropertiesXml Export all defaults properties used by a new diagram and his content size of border content of titleblock default conductor defaut folio report default Xref.
Parameters
xml_element : xml element to use for store default propertie.
Definition at line 1512 of file qetproject.cpp.
References conductorAutoNum(), conductorAutoNumFormula(), default_border_properties_, default_conductor_properties_, default_titleblock_properties_, defaultReportProperties(), defaultXRefProperties(), elementAutoNum(), elementAutoNumFormula(), folioAutoNum(), m_current_conductor_autonum, m_current_element_autonum, m_freeze_new_conductors, m_freeze_new_elements, BorderProperties::toXml(), TitleBlockProperties::toXml(), and ConductorProperties::toXml().
Referenced by toXml().
writeProjectPropertiesXml()
void QETProject::writeProjectPropertiesXml (QDomElement & xml_element) private
Export project properties under the xml_element XML element.
Definition at line 1498 of file qetproject.cpp.
References m_project_properties, and DiagramContext::toXml().
Referenced by toXml().
XRefPropertiesChanged
void QETProject::XRefPropertiesChanged () signal
Referenced by CrossRefItem::init(), MasterElement::itemChange(), DynamicElementTextItem::itemChange(), setDefaultXRefProperties(), ElementTextItemGroup::setHoldToBottomPage(), DynamicElementTextItem::updateXref(), and ElementTextItemGroup::updateXref().
Member Data Documentation
default_border_properties_
BorderProperties QETProject::default_border_properties_ = BorderProperties::defaultProperties() private
Default dimensions and properties for new diagrams created within the project.
Definition at line 240 of file qetproject.h.
Referenced by defaultBorderProperties(), readDefaultPropertiesXml(), setDefaultBorderProperties(), and writeDefaultPropertiesXml().
default_conductor_properties_
ConductorProperties QETProject::default_conductor_properties_ = ConductorProperties::defaultProperties() private
Default conductor properties for new diagrams created within the project.
Definition at line 242 of file qetproject.h.
Referenced by defaultConductorProperties(), readDefaultPropertiesXml(), setDefaultConductorProperties(), and writeDefaultPropertiesXml().
default_titleblock_properties_
TitleBlockProperties QETProject::default_titleblock_properties_ private
Default title block properties for new diagrams created within the project.
Definition at line 244 of file qetproject.h.
Referenced by defaultTitleBlockProperties(), readDefaultPropertiesXml(), setDefaultTitleBlockProperties(), and writeDefaultPropertiesXml().
m_auto_conductor
bool QETProject::m_auto_conductor = true private
Definition at line 263 of file qetproject.h.
Referenced by autoConductor(), and setAutoConductor().
m_autosave_timer
QTimer QETProject::m_autosave_timer private
Definition at line 268 of file qetproject.h.
Referenced by init().
m_backup_file
KAutoSaveFile QETProject::m_backup_file private
Definition at line 269 of file qetproject.h.
Referenced by setFilePath(), and writeBackup().
m_conductor_autonum
QHash<QString, NumerotationContext> QETProject::m_conductor_autonum private
Conductor auto numerotation.
Definition at line 256 of file qetproject.h.
Referenced by addConductorAutoNum(), conductorAutoNum(), conductorAutoNumFormula(), readDefaultPropertiesXml(), and removeConductorAutoNum().
m_current_conductor_autonum
QString QETProject::m_current_conductor_autonum private
Definition at line 257 of file qetproject.h.
Referenced by conductorCurrentAutoNum(), readDefaultPropertiesXml(), setCurrentConductorAutoNum(), and writeDefaultPropertiesXml().
m_current_element_autonum
QString QETProject::m_current_element_autonum private
Definition at line 262 of file qetproject.h.
Referenced by elementAutoNumCurrentFormula(), elementCurrentAutoNum(), readDefaultPropertiesXml(), setCurrrentElementAutonum(), and writeDefaultPropertiesXml().
m_data_base
projectDataBase QETProject::m_data_base private
Definition at line 271 of file qetproject.h.
Referenced by addDiagram(), dataBase(), readDiagramsXml(), readProjectXml(), and removeDiagram().
m_default_report_properties
QString QETProject::m_default_report_properties = ReportProperties::defaultProperties() private
Default report properties.
Definition at line 246 of file qetproject.h.
Referenced by defaultReportProperties(), readDefaultPropertiesXml(), and setDefaultReportProperties().
m_default_xref_properties
QHash<QString, XRefProperties> QETProject::m_default_xref_properties = XRefProperties::defaultProperties() private
Default xref properties.
Definition at line 248 of file qetproject.h.
Referenced by defaultXRefProperties(), readDefaultPropertiesXml(), and setDefaultXRefProperties().
m_diagrams_list
QList<Diagram *> QETProject::m_diagrams_list private
Diagrams carried by the project.
Definition at line 228 of file qetproject.h.
Referenced by addDiagram(), autoFolioNumberingSelectedFolios(), diagramOrderChanged(), diagrams(), folioIndex(), freezeExistentConductorLabel(), freezeExistentElementLabel(), freezeNewConductorLabel(), freezeNewElementLabel(), isEmpty(), removeDiagram(), removeDiagramsTitleBlockTemplate(), toXml(), updateDiagramsFolioData(), updateDiagramsTitleBlockTemplate(), and ~QETProject().
m_element_autonum
QHash<QString, NumerotationContext> QETProject::m_element_autonum private
Element Auto Numbering.
Definition at line 261 of file qetproject.h.
Referenced by addElementAutoNum(), elementAutoNum(), elementAutoNumFormula(), readDefaultPropertiesXml(), and removeElementAutoNum().
m_elements_collection
XmlElementCollection* QETProject::m_elements_collection = nullptr private
Definition at line 264 of file qetproject.h.
Referenced by embeddedElementCollection(), importElement(), QETProject(), readElementsCollectionXml(), toXml(), and unusedElements().
m_file_path
QString QETProject::m_file_path private
File path this project is saved to.
Definition at line 224 of file qetproject.h.
Referenced by currentDir(), filePath(), init(), isReadOnly(), pathNameTitle(), QETProject(), setFilePath(), setReadOnly(), and write().
m_folio_autonum
QHash<QString, NumerotationContext> QETProject::m_folio_autonum private
Folio auto numbering.
Definition at line 259 of file qetproject.h.
Referenced by addFolioAutoNum(), folioAutoNum(), readDefaultPropertiesXml(), and removeFolioAutoNum().
m_freeze_new_conductors
bool QETProject::m_freeze_new_conductors = false private
Definition at line 266 of file qetproject.h.
Referenced by isFreezeNewConductors(), readDefaultPropertiesXml(), setFreezeNewConductors(), and writeDefaultPropertiesXml().
m_freeze_new_elements
bool QETProject::m_freeze_new_elements = false private
Definition at line 265 of file qetproject.h.
Referenced by isFreezeNewElements(), readDefaultPropertiesXml(), setFreezeNewElements(), and writeDefaultPropertiesXml().
m_modified
bool QETProject::m_modified = false private
Whether options were modified.
Definition at line 234 of file qetproject.h.
Referenced by pathNameTitle(), projectOptionsWereModified(), and setModified().
m_project_properties
DiagramContext QETProject::m_project_properties private
project-wide variables that will be made available to child diagrams
Definition at line 252 of file qetproject.h.
Referenced by autoFolioNumberingSelectedFolios(), projectProperties(), readProjectPropertiesXml(), setFilePath(), setProjectProperties(), updateDiagramsFolioData(), write(), and writeProjectPropertiesXml().
m_project_qet_version
qreal QETProject::m_project_qet_version = -1 private
QElectroTech version declared in the XML document at opening time.
Definition at line 232 of file qetproject.h.
Referenced by declaredQElectroTechVersion(), and readProjectXml().
m_read_only
bool QETProject::m_read_only = false private
Whether the project is read only.
Definition at line 236 of file qetproject.h.
Referenced by isReadOnly(), and setReadOnly().
m_save_backup_timer
QTimer QETProject::m_save_backup_timer private
Definition at line 267 of file qetproject.h.
Referenced by init().
m_state
ProjectState QETProject::m_state private
Current state of the project.
Definition at line 226 of file qetproject.h.
Referenced by QETProject(), readProjectXml(), and state().
m_titleblocks_collection
TitleBlockTemplatesProjectCollection QETProject::m_titleblocks_collection private
Embedded title block templates collection.
Definition at line 250 of file qetproject.h.
Referenced by embeddedTitleBlockTemplatesCollection(), init(), integrateTitleBlockTemplate(), projectWasModified(), readProjectXml(), and toXml().
m_undo_stack
QUndoStack* QETProject::m_undo_stack private
undo stack for this project
Definition at line 254 of file qetproject.h.
Referenced by init(), projectWasModified(), and undoStack().
m_uuid
QUuid QETProject::m_uuid = QUuid::createUuid() private
Definition at line 270 of file qetproject.h.
Referenced by uuid().
project_title_
QString QETProject::project_title_ private
Project title.
Definition at line 230 of file qetproject.h.
Referenced by isEmpty(), pathNameTitle(), setTitle(), title(), and toXml().
read_only_file_path_
QString QETProject::read_only_file_path_ private
Filepath for which this project is considered read only.
Definition at line 238 of file qetproject.h.
Referenced by isReadOnly(), and setReadOnly().
Property Documentation
autoConductor
bool QETProject::autoConductor read write
Definition at line 1 of file qetproject.h.
The documentation for this class was generated from the following files:
qetproject.h
qetproject.cpp