QElectroTech: DiagramView Class Reference
DiagramView Class Reference
#include <diagramview.h>
Public Slots
void selectNothing ()
void selectAll ()
void selectInvert ()
void setVisualisationMode ()
void setSelectionMode ()
void zoom (const qreal zoom_factor)
DiagramView::zoom Zomm the view. A zoom_factor > 1 zoom in. A zoom_factor < 1 zoom out.
void zoomFit ()
void zoomContent ()
void zoomReset ()
void cut ()
void copy ()
void paste (const QPointF &=QPointF(), QClipboard::Mode=QClipboard::Clipboard)
DiagramView::paste Import the element stored in the clipboard to the diagram.
void pasteHere ()
void adjustSceneRect ()
DiagramView::adjustSceneRect Calcul and set the area of the scene visualized by this view.
void updateWindowTitle ()
void editSelectedConductorColor ()
DiagramView::editSelectedConductorColor Edit the color of the selected conductor; does nothing if multiple conductors are selected.
void editConductorColor (Conductor *)
void resetConductors ()
Signals
void modeChanged ()
Signal emitted after the selection mode changed.
void titleChanged (DiagramView *, const QString &)
Signal emitted after the diagram title changed.
void findElementRequired (const ElementsLocation &)
Signal emitted when users wish to locate an element from the diagram within elements collection.
void editElementRequired (const ElementsLocation &)
Signal emitted when users wish to edit an element from the diagram.
void showDiagram (Diagram *)
Signal emmitted when diagram must be show.
void freeRubberBandChanged (QPolygonF polygon)
Public Member Functions
DiagramView (Diagram *diagram, QWidget *=nullptr)
~DiagramView () override
QString title () const
void editDiagramProperties ()
DiagramView::editDiagramProperties Edit the properties of the viewed digram.
Diagram * diagram ()
QETDiagramEditor * diagramEditor () const
void editSelection ()
DiagramView::editSelection Edit the selected item if he can be edited and if only one item is selected.
void setEventInterface (DVEventInterface *event_interface)
DiagramView::setEventInterface Set an event interface to diagram view. If diagram view already have an event interface, he delete it before. Diagram view take ownership of event interface and delete it when event interface is finish.
QList< QAction * > contextMenuActions () const
DiagramView::contextMenuActions.
Protected Member Functions
void mouseDoubleClickEvent (QMouseEvent *) override
DiagramView::mouseDoubleClickEvent.
void contextMenuEvent (QContextMenuEvent *) override
DiagramView::contextMenuEvent.
void wheelEvent (QWheelEvent *) override
DiagramView::wheelEvent Manage wheel event of mouse.
void focusInEvent (QFocusEvent *) override
void keyPressEvent (QKeyEvent *) override
DiagramView::keyPressEvent Handles "key press" events. Reimplemented here to switch to visualisation mode if needed.
void keyReleaseEvent (QKeyEvent *) override
bool event (QEvent *) override
DiagramView::event Manage the event on this diagram view. -At first activation (QEvent::WindowActivate or QEvent::Show) we zoomFit. -Convert event interpreted to mouse event to gesture event if needed. -send Shortcut to view (by default send to QMenu /QAction) Gere les evenements de la DiagramView.
void paintEvent (QPaintEvent *event) override
DiagramView::paintEvent Reimplemented from QGraphicsView.
void mousePressEvent (QMouseEvent *) override
void mouseMoveEvent (QMouseEvent *) override
DiagramView::mouseMoveEvent Manage the event move mouse.
void mouseReleaseEvent (QMouseEvent *) override
DiagramView::mouseReleaseEvent Manage event release click mouse.
void dragEnterEvent (QDragEnterEvent *) override
void dragMoveEvent (QDragMoveEvent *) override
void dropEvent (QDropEvent *) override
virtual bool switchToVisualisationModeIfNeeded (QInputEvent *e)
virtual bool switchToSelectionModeIfNeeded (QInputEvent *e)
virtual bool isCtrlShifting (QInputEvent *)
virtual bool selectedItemHasFocus ()
Private Slots
void adjustGridToZoom ()
void applyReadOnly ()
Private Member Functions
DiagramView (const DiagramView &)
void handleElementDrop (QDropEvent *)
DiagramView::handleElementDrop Handle the drop of an element.
void handleTitleBlockDrop (QDropEvent *)
DiagramView::handleTitleBlockDrop Handle the dropEvent that contain data of a titleblock.
void handleTextDrop (QDropEvent *)
DiagramView::handleTextDrop handle the drop of text.
void scrollOnMovement (QKeyEvent *)
bool gestureEvent (QGestureEvent *event)
DiagramView::gestureEvent Use the pinch of the trackpad for zoom.
QRectF viewedSceneRect () const
bool mustIntegrateTitleBlockTemplate (const TitleBlockTemplateLocation &) const
bool gestures () const
DiagramView::gestures.
Private Attributes
Diagram * m_diagram = nullptr
DVEventInterface * m_event_interface = nullptr
QAction * m_paste_here = nullptr
QAction * m_multi_paste = nullptr
QPoint m_paste_here_pos
QPointF m_drag_last_pos
bool m_fresh_focus_in
bool m_first_activation = true
QList< QAction * > m_separators
QPolygonF m_free_rubberband
bool m_free_rubberbanding = false
Detailed Description
This class provides a widget to render an electric diagram in an editable, interactive way.
Definition at line 37 of file diagramview.h.
Constructor & Destructor Documentation
DiagramView() [1/2]
DiagramView::DiagramView (Diagram * diagram, QWidget * parent = nullptr)
Constructeur
Parameters
diagram Schema a afficher ; si diagram vaut 0, un nouveau Diagram est utilise
parent Le QWidget parent de cette vue de schema
Definition at line 54 of file diagramview.cpp.
References adjustSceneRect(), diagram(), editElementRequired(), QET::Icons::EditPaste, editSelectedConductorColor(), findElementRequired(), Diagram::loadCndFolioSeq(), Diagram::loadElmtFolioSeq(), m_diagram, m_multi_paste, m_paste_here, m_separators, pasteHere(), QET::Icons::QETLogo, setSelectionMode(), showDiagram(), QET::Icons::tr, and updateWindowTitle().
~DiagramView()
DiagramView::~DiagramView () override
Destructeur
Definition at line 116 of file diagramview.cpp.
DiagramView() [2/2]
DiagramView::DiagramView (const DiagramView &) private
Member Function Documentation
adjustGridToZoom
void DiagramView::adjustGridToZoom () private slot
Enables or disables the drawing grid according to the amount of pixels display
Definition at line 864 of file diagramview.cpp.
References diagramEditor(), m_diagram, Diagram::setDisplayGrid(), and viewedSceneRect().
Referenced by zoom(), zoomContent(), zoomFit(), and zoomReset().
adjustSceneRect
void DiagramView::adjustSceneRect () slot
DiagramView::adjustSceneRect Calcul and set the area of the scene visualized by this view.
Definition at line 837 of file diagramview.cpp.
References m_diagram, and Diagram::margin.
Referenced by DiagramView(), handleTitleBlockDrop(), mouseMoveEvent(), paste(), QETDiagramEditor::selectionGroupTriggered(), zoom(), and zoomFit().
applyReadOnly
void DiagramView::applyReadOnly () private slot
Fait en sorte que le schema ne soit editable que s'il n'est pas en lecture seule
Definition at line 908 of file diagramview.cpp.
References m_diagram.
Referenced by setSelectionMode(), and setVisualisationMode().
contextMenuActions()
QList< QAction * > DiagramView::contextMenuActions () const
DiagramView::contextMenuActions.
Returns
a list of actions currently available for a context menu.
Definition at line 1152 of file diagramview.cpp.
References diagramEditor(), Diagram::isEmpty(), m_diagram, m_multi_paste, m_paste_here, and m_separators.
Referenced by contextMenuEvent(), and QetShapeItem::contextMenuEvent().
contextMenuEvent()
void DiagramView::contextMenuEvent (QContextMenuEvent * e) override protected
DiagramView::contextMenuEvent.
Parameters
e
Definition at line 1194 of file diagramview.cpp.
References Diagram::clipboardMayContainDiagram(), contextMenuActions(), Diagram::isEmpty(), m_diagram, m_paste_here, and m_paste_here_pos.
copy
void DiagramView::copy () slot
Copie les elements selectionnes du schema dans le presse-papier
Definition at line 353 of file diagramview.cpp.
References m_diagram.
Referenced by cut().
cut
void DiagramView::cut () slot
Copie les elements selectionnes du schema dans le presse-papier puis les supprime
Definition at line 343 of file diagramview.cpp.
References copy(), and m_diagram.
diagram()
Diagram* DiagramView::diagram () inline
Definition at line 67 of file diagramview.h.
References m_diagram.
Referenced by QETDiagramEditor::addItemGroupTriggered(), QETDiagramEditor::currentElement(), DiagramView(), QETDiagramEditor::diagramWasAdded(), editConductorColor(), handleElementDrop(), mouseReleaseEvent(), AutoNumberingDockWidget::on_m_conductor_cb_activated(), AutoNumberingDockWidget::on_m_element_cb_activated(), QETDiagramEditor::rowColumnGroupTriggered(), QETDiagramEditor::selectionChanged(), QETDiagramEditor::selectionGroupTriggered(), AutoNumberingDockWidget::setActive(), AutoNumberingDockWidget::setConductorActive(), AutoNumberingDockWidget::setProject(), QETDiagramEditor::setUpActions(), QETDiagramEditor::slot_updateComplexActions(), and ProjectView::updateTabTitle().
diagramEditor()
QETDiagramEditor * DiagramView::diagramEditor () const
Returns
l'editeur de schemas parent ou 0
Definition at line 1228 of file diagramview.cpp.
Referenced by adjustGridToZoom(), contextMenuActions(), editDiagramProperties(), and keyPressEvent().
dragEnterEvent()
void DiagramView::dragEnterEvent (QDragEnterEvent * e) override protected
Accepte ou refuse le drag'n drop en fonction du type de donnees entrant
Parameters
e le QDragEnterEvent correspondant au drag'n drop tente
Definition at line 144 of file diagramview.cpp.
dragMoveEvent()
void DiagramView::dragMoveEvent (QDragMoveEvent * e) override protected
Accepte ou refuse le drag'n drop en fonction du type de donnees entrant
Parameters
e le QDragMoveEvent correspondant au drag'n drop tente
Definition at line 160 of file diagramview.cpp.
dropEvent()
void DiagramView::dropEvent (QDropEvent * e) override protected
Handle the drops accepted on diagram (elements and title block templates).
Parameters
e the QDropEvent describing the current drag'n drop
Definition at line 169 of file diagramview.cpp.
References handleElementDrop(), handleTextDrop(), and handleTitleBlockDrop().
editConductorColor
void DiagramView::editConductorColor (Conductor * edited_conductor) slot
Edit the color of the given conductor
Parameters
edited_conductor Conductor we want to change the color
Definition at line 936 of file diagramview.cpp.
References ConductorProperties::color, diagram(), m_diagram, and QET::Icons::tr.
Referenced by editSelectedConductorColor().
editDiagramProperties()
void DiagramView::editDiagramProperties ()
DiagramView::editDiagramProperties Edit the properties of the viewed digram.
Definition at line 829 of file diagramview.cpp.
References diagramEditor(), DiagramPropertiesDialog::diagramPropertiesDialog(), and m_diagram.
Referenced by mouseDoubleClickEvent().
editElementRequired
void DiagramView::editElementRequired (const ElementsLocation &) signal
Signal emitted when users wish to edit an element from the diagram.
Referenced by ProjectView::diagramAdded(), and DiagramView().
editSelectedConductorColor
void DiagramView::editSelectedConductorColor () slot
DiagramView::editSelectedConductorColor Edit the color of the selected conductor; does nothing if multiple conductors are selected.
Definition at line 920 of file diagramview.cpp.
References DiagramContent::AnyConductor, DiagramContent::conductors(), editConductorColor(), m_diagram, and DiagramContent::SelectedOnly.
Referenced by DiagramView().
editSelection()
void DiagramView::editSelection ()
DiagramView::editSelection Edit the selected item if he can be edited and if only one item is selected.
Definition at line 1118 of file diagramview.cpp.
References m_diagram.
Referenced by QETDiagramEditor::selectionGroupTriggered().
event()
bool DiagramView::event (QEvent * e) override protected
DiagramView::event Manage the event on this diagram view. -At first activation (QEvent::WindowActivate or QEvent::Show) we zoomFit. -Convert event interpreted to mouse event to gesture event if needed. -send Shortcut to view (by default send to QMenu /QAction) Gere les evenements de la DiagramView.
Parameters
e : the event.
Returns
Definition at line 1006 of file diagramview.cpp.
References gestureEvent(), m_first_activation, selectedItemHasFocus(), and zoomFit().
Referenced by gestureEvent(), handleElementDrop(), paintEvent(), and wheelEvent().
findElementRequired
void DiagramView::findElementRequired (const ElementsLocation &) signal
Signal emitted when users wish to locate an element from the diagram within elements collection.
Referenced by ProjectView::diagramAdded(), and DiagramView().
focusInEvent()
void DiagramView::focusInEvent (QFocusEvent * e) override protected
Handles "Focus in" events. Reimplemented here to store the fact the focus was freshly acquired again using the mouse. This information is later used in DiagramView::mousePressEvent().
Definition at line 637 of file diagramview.cpp.
References m_fresh_focus_in.
freeRubberBandChanged
void DiagramView::freeRubberBandChanged (QPolygonF polygon) signal
Signal emmtted when free rubberband changed. When free rubberband selection ends this signal will be emitted with null value.
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
gestureEvent()
bool DiagramView::gestureEvent (QGestureEvent * event) private
DiagramView::gestureEvent Use the pinch of the trackpad for zoom.
Parameters
event
Returns
Definition at line 616 of file diagramview.cpp.
References event(), and zoom().
Referenced by event().
gestures()
bool DiagramView::gestures () const private
DiagramView::gestures.
Returns
Definition at line 570 of file diagramview.cpp.
Referenced by wheelEvent().
handleElementDrop()
void DiagramView::handleElementDrop (QDropEvent * event) private
DiagramView::handleElementDrop Handle the drop of an element.
Parameters
event the QDropEvent describing the current drag'n drop
Definition at line 185 of file diagramview.cpp.
References diagram(), event(), ElementsLocation::exist(), ElementsLocation::isElement(), and Diagram::setEventInterface().
Referenced by dropEvent().
handleTextDrop()
void DiagramView::handleTextDrop (QDropEvent * e) private
DiagramView::handleTextDrop handle the drop of text.
Parameters
e the QDropEvent describing the current drag'n drop
Definition at line 255 of file diagramview.cpp.
References m_diagram.
Referenced by dropEvent().
handleTitleBlockDrop()
void DiagramView::handleTitleBlockDrop (QDropEvent * e) private
DiagramView::handleTitleBlockDrop Handle the dropEvent that contain data of a titleblock.
Parameters
e
Definition at line 206 of file diagramview.cpp.
References adjustSceneRect(), Diagram::border_and_titleblock, BorderTitleBlock::exportTitleBlock(), TitleBlockTemplateLocation::fromString(), QETProject::integrateTitleBlockTemplate(), TitleBlockTemplateLocation::isValid(), m_diagram, mustIntegrateTitleBlockTemplate(), TitleBlockTemplateLocation::name(), TitleBlockTemplateLocation::parentProject(), Diagram::project(), TitleBlockProperties::template_name, and Diagram::undoStack().
Referenced by dropEvent().
isCtrlShifting()
bool DiagramView::isCtrlShifting (QInputEvent * e) protected virtual
Returns
true if the user is pressing Ctrl and Shift simultaneously.
Definition at line 1087 of file diagramview.cpp.
Referenced by switchToSelectionModeIfNeeded(), and switchToVisualisationModeIfNeeded().
keyPressEvent()
void DiagramView::keyPressEvent (QKeyEvent * e) override protected
DiagramView::keyPressEvent Handles "key press" events. Reimplemented here to switch to visualisation mode if needed.
Parameters
e
Definition at line 649 of file diagramview.cpp.
References DiagramContent::All, ProjectView::changeFirstTab(), ProjectView::changeLastTab(), ProjectView::changeTabDown(), ProjectView::changeTabUp(), QETDiagramEditor::currentProjectView(), diagramEditor(), DiagramContent::hasTextEditing(), DiagramContent::items(), DVEventInterface::keyPressEvent(), m_diagram, m_event_interface, scrollOnMovement(), DiagramContent::selectedTexts(), switchToVisualisationModeIfNeeded(), and zoom().
keyReleaseEvent()
void DiagramView::keyReleaseEvent (QKeyEvent * e) override protected
Handles "key release" events. Reimplemented here to switch to selection mode if needed.
Definition at line 734 of file diagramview.cpp.
References DVEventInterface::KeyReleaseEvent(), m_event_interface, and switchToSelectionModeIfNeeded().
modeChanged
void DiagramView::modeChanged () signal
Signal emitted after the selection mode changed.
Referenced by setSelectionMode(), and setVisualisationMode().
mouseDoubleClickEvent()
void DiagramView::mouseDoubleClickEvent (QMouseEvent * e) override protected
DiagramView::mouseDoubleClickEvent.
Parameters
e
Definition at line 1242 of file diagramview.cpp.
References BorderTitleBlock::columnsRect(), editDiagramProperties(), m_diagram, m_event_interface, BorderTitleBlock::rowsRect(), and BorderTitleBlock::titleBlockRect().
mouseMoveEvent()
void DiagramView::mouseMoveEvent (QMouseEvent * e) override protected
DiagramView::mouseMoveEvent Manage the event move mouse.
Definition at line 455 of file diagramview.cpp.
References adjustSceneRect(), freeRubberBandChanged(), m_diagram, m_drag_last_pos, m_event_interface, m_free_rubberband, m_free_rubberbanding, and DVEventInterface::mouseMoveEvent().
mousePressEvent()
void DiagramView::mousePressEvent (QMouseEvent * e) override protected
Manage the events press click : click to add an independent text field
Definition at line 398 of file diagramview.cpp.
References m_drag_last_pos, m_event_interface, m_free_rubberband, m_free_rubberbanding, m_fresh_focus_in, DVEventInterface::mousePressEvent(), and switchToVisualisationModeIfNeeded().
mouseReleaseEvent()
void DiagramView::mouseReleaseEvent (QMouseEvent * e) override protected
DiagramView::mouseReleaseEvent Manage event release click mouse.
Definition at line 516 of file diagramview.cpp.
References ConductorCreator::create(), diagram(), freeRubberBandChanged(), m_diagram, m_event_interface, m_free_rubberband, m_free_rubberbanding, DVEventInterface::mouseReleaseEvent(), and QET::Icons::tr.
mustIntegrateTitleBlockTemplate()
bool DiagramView::mustIntegrateTitleBlockTemplate (const TitleBlockTemplateLocation & tbt_loc) const private
Parameters
tbt_loc A title block template location
Returns
true if the title block template needs to be integrated in the parent project before being applied to the current diagram, or false if it can be directly applied
Definition at line 896 of file diagramview.cpp.
References m_diagram, and TitleBlockTemplateLocation::parentProject().
Referenced by handleTitleBlockDrop().
paintEvent()
void DiagramView::paintEvent (QPaintEvent * event) override protected
DiagramView::paintEvent Reimplemented from QGraphicsView.
Parameters
event
Definition at line 1037 of file diagramview.cpp.
References event(), m_free_rubberband, and m_free_rubberbanding.
paste
void DiagramView::paste (const QPointF & pos = QPointF(), QClipboard::Mode clipboard_mode = QClipboard::Clipboard) slot
DiagramView::paste Import the element stored in the clipboard to the diagram.
Parameters
pos : top left corner of the bounding rect of imported elements
clipboard_mode
Definition at line 366 of file diagramview.cpp.
References adjustSceneRect(), DiagramContent::count(), Diagram::fromXml(), and m_diagram.
Referenced by pasteHere().
pasteHere
void DiagramView::pasteHere () slot
Colle le contenu du presse-papier sur le schema a la position de la souris
Definition at line 390 of file diagramview.cpp.
References m_paste_here_pos, and paste().
Referenced by DiagramView().
resetConductors
void DiagramView::resetConductors () slot
Reinitialise le profil des conducteurs selectionnes
Definition at line 973 of file diagramview.cpp.
References m_diagram.
scrollOnMovement()
void DiagramView::scrollOnMovement (QKeyEvent * e) private
Handles element movement when editor is zoomed in and scrolls vertical and horizontal bar. If element is moved to the right side of the editor or below the editor SceneRect is expanded
Definition at line 746 of file diagramview.cpp.
References Diagram::adjustSceneRect(), DiagramContent::All, DiagramContent::items(), m_diagram, and viewedSceneRect().
Referenced by keyPressEvent().
selectAll
void DiagramView::selectAll () slot
Selectionne tous les objets du schema
Definition at line 122 of file diagramview.cpp.
References m_diagram.
Referenced by QETDiagramEditor::selectGroupTriggered().
selectedItemHasFocus()
bool DiagramView::selectedItemHasFocus () protected virtual
Returns
true if there is a selected item and that item has the focus.
Definition at line 1106 of file diagramview.cpp.
References m_diagram.
Referenced by event(), switchToSelectionModeIfNeeded(), and switchToVisualisationModeIfNeeded().
selectInvert
void DiagramView::selectInvert () slot
Inverse l'etat de selection de tous les objets du schema
Definition at line 136 of file diagramview.cpp.
References m_diagram.
Referenced by QETDiagramEditor::selectGroupTriggered().
selectNothing
void DiagramView::selectNothing () slot
Deslectionne tous les objets selectionnes
Definition at line 129 of file diagramview.cpp.
References m_diagram.
Referenced by QETDiagramEditor::selectGroupTriggered().
setEventInterface()
void DiagramView::setEventInterface (DVEventInterface * event_interface)
DiagramView::setEventInterface Set an event interface to diagram view. If diagram view already have an event interface, he delete it before. Diagram view take ownership of event interface and delete it when event interface is finish.
Definition at line 1140 of file diagramview.cpp.
References DVEventInterface::finish(), and m_event_interface.
setSelectionMode
void DiagramView::setSelectionMode () slot
Set the Diagram in Selection mode
Definition at line 280 of file diagramview.cpp.
References applyReadOnly(), and modeChanged().
Referenced by DiagramView(), and switchToSelectionModeIfNeeded().
setVisualisationMode
void DiagramView::setVisualisationMode () slot
Set the Diagram in visualisation mode
Definition at line 270 of file diagramview.cpp.
References applyReadOnly(), and modeChanged().
Referenced by switchToVisualisationModeIfNeeded().
showDiagram
void DiagramView::showDiagram (Diagram *) signal
Signal emmitted when diagram must be show.
Referenced by ProjectView::diagramAdded(), and DiagramView().
switchToSelectionModeIfNeeded()
bool DiagramView::switchToSelectionModeIfNeeded (QInputEvent * e) protected virtual
Switch back to selection mode if the user is not pressing Ctrl and Shift.
Returns
true if the view was switched to selection mode, false otherwise.
Definition at line 1076 of file diagramview.cpp.
References isCtrlShifting(), selectedItemHasFocus(), and setSelectionMode().
Referenced by keyReleaseEvent().
switchToVisualisationModeIfNeeded()
bool DiagramView::switchToVisualisationModeIfNeeded (QInputEvent * e) protected virtual
Switch to visualisation mode if the user is pressing Ctrl and Shift.
Returns
true if the view was switched to visualisation mode, false otherwise.
Definition at line 1061 of file diagramview.cpp.
References isCtrlShifting(), selectedItemHasFocus(), and setVisualisationMode().
Referenced by keyPressEvent(), and mousePressEvent().
title()
QString DiagramView::title () const
Returns
le titre de cette vue ; cela correspond au titre du schema visualise precede de la mention "Schema". Si le titre du schema est vide, la mention "Schema sans titre" est utilisee
See also
Diagram::title()
Definition at line 814 of file diagramview.cpp.
References m_diagram, and QET::Icons::tr.
Referenced by updateWindowTitle().
titleChanged
void DiagramView::titleChanged (DiagramView * , const QString &) signal
Signal emitted after the diagram title changed.
Referenced by ProjectView::diagramAdded(), and updateWindowTitle().
updateWindowTitle
void DiagramView::updateWindowTitle () slot
Met a jour le titre du widget
Definition at line 857 of file diagramview.cpp.
References title(), and titleChanged().
Referenced by DiagramView().
viewedSceneRect()
QRectF DiagramView::viewedSceneRect () const private
Returns
le rectangle du schema (classe Diagram) visualise par ce DiagramView
Definition at line 875 of file diagramview.cpp.
Referenced by adjustGridToZoom(), and scrollOnMovement().
wheelEvent()
void DiagramView::wheelEvent (QWheelEvent * event) override protected
DiagramView::wheelEvent Manage wheel event of mouse.
Parameters
event QWheelEvent
Definition at line 581 of file diagramview.cpp.
References event(), gestures(), m_event_interface, DVEventInterface::wheelEvent(), and zoom().
zoom
void DiagramView::zoom (const qreal zoom_factor) slot
DiagramView::zoom Zomm the view. A zoom_factor > 1 zoom in. A zoom_factor < 1 zoom out.
Parameters
zoom_factor
Definition at line 294 of file diagramview.cpp.
References adjustGridToZoom(), adjustSceneRect(), Diagram::adjustSceneRect(), and m_diagram.
Referenced by gestureEvent(), keyPressEvent(), wheelEvent(), and QETDiagramEditor::zoomGroupTriggered().
zoomContent
void DiagramView::zoomContent () slot
Adjust zoom to fit all elements in the view, regardless of diagram borders.
Definition at line 327 of file diagramview.cpp.
References adjustGridToZoom(), and m_diagram.
Referenced by QETDiagramEditor::zoomGroupTriggered().
zoomFit
void DiagramView::zoomFit () slot
Agrandit ou rectrecit le schema de facon a ce que tous les elements du schema soient visibles a l'ecran. S'il n'y a aucun element sur le schema, le zoom est reinitialise
Definition at line 318 of file diagramview.cpp.
References adjustGridToZoom(), adjustSceneRect(), and m_diagram.
Referenced by event(), and QETDiagramEditor::zoomGroupTriggered().
zoomReset
void DiagramView::zoomReset () slot
Reinitialise le zoom
Definition at line 335 of file diagramview.cpp.
References adjustGridToZoom().
Referenced by QETDiagramEditor::zoomGroupTriggered().
Member Data Documentation
m_diagram
Diagram* DiagramView::m_diagram = nullptr private
Definition at line 51 of file diagramview.h.
Referenced by adjustGridToZoom(), adjustSceneRect(), applyReadOnly(), contextMenuActions(), contextMenuEvent(), copy(), cut(), diagram(), DiagramView(), editConductorColor(), editDiagramProperties(), editSelectedConductorColor(), editSelection(), handleTextDrop(), handleTitleBlockDrop(), keyPressEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mouseReleaseEvent(), mustIntegrateTitleBlockTemplate(), paste(), resetConductors(), scrollOnMovement(), selectAll(), selectedItemHasFocus(), selectInvert(), selectNothing(), title(), zoom(), zoomContent(), and zoomFit().
m_drag_last_pos
QPointF DiagramView::m_drag_last_pos private
Definition at line 56 of file diagramview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_event_interface
DVEventInterface* DiagramView::m_event_interface = nullptr private
Definition at line 52 of file diagramview.h.
Referenced by keyPressEvent(), keyReleaseEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), setEventInterface(), and wheelEvent().
m_first_activation
bool DiagramView::m_first_activation = true private
Definition at line 58 of file diagramview.h.
Referenced by event().
m_free_rubberband
QPolygonF DiagramView::m_free_rubberband private
Definition at line 60 of file diagramview.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
m_free_rubberbanding
bool DiagramView::m_free_rubberbanding = false private
Definition at line 61 of file diagramview.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
m_fresh_focus_in
bool DiagramView::m_fresh_focus_in private
Definition at line 57 of file diagramview.h.
Referenced by focusInEvent(), and mousePressEvent().
m_multi_paste
QAction* DiagramView::m_multi_paste = nullptr private
Definition at line 54 of file diagramview.h.
Referenced by contextMenuActions(), and DiagramView().
m_paste_here
QAction* DiagramView::m_paste_here = nullptr private
Definition at line 53 of file diagramview.h.
Referenced by contextMenuActions(), contextMenuEvent(), and DiagramView().
m_paste_here_pos
QPoint DiagramView::m_paste_here_pos private
Definition at line 55 of file diagramview.h.
Referenced by contextMenuEvent(), and pasteHere().
m_separators
QList<QAction *> DiagramView::m_separators private
Definition at line 59 of file diagramview.h.
Referenced by contextMenuActions(), and DiagramView().
The documentation for this class was generated from the following files:
diagramview.h
diagramview.cpp