QElectroTech: ElementProvider Class Reference
ElementProvider Class Reference
#include <elementprovider.h>
Public Member Functions
ElementProvider (QETProject *prj, Diagram *diagram=nullptr)
ElementProvider::ElementProvider Constructor.
ElementProvider (Diagram *diag)
ElementProvider::ElementProvider Constructor.
QList< Element * > freeElement (const int filter) const
ElementProvider::FreeElement Search and return the asked element corresponding with the given filter All returned element are free, ie element aren't connected with another element.
QList< Element * > fromUuids (QList< QUuid >) const
ElementProvider::fromUuids.
QList< Element * > find (const int filter) const
ElementProvider::find Search and return the asked element corresponding with the given filter.
QVector< QetGraphicsTableItem * > table (QetGraphicsTableItem *table=nullptr, QAbstractItemModel *model=nullptr)
ElementProvider::table.
QetGraphicsTableItem * tableFromUuid (const QUuid &uuid)
ElementProvider::tableFromUuid.
Private Attributes
QList< Diagram * > m_diagram_list
Detailed Description
this class can search in the given diagram or project some kind of element like 'folio report' or 'master' and return it. We can get element element with specific status like 'free'.
Definition at line 36 of file elementprovider.h.
Constructor & Destructor Documentation
ElementProvider() [1/2]
ElementProvider::ElementProvider (QETProject * prj, Diagram * diagram = nullptr)
ElementProvider::ElementProvider Constructor.
Parameters
prj the project where we must find element
diagram the diagram to exclude from the search
Definition at line 30 of file elementprovider.cpp.
References QETProject::diagrams(), and m_diagram_list.
ElementProvider() [2/2]
ElementProvider::ElementProvider (Diagram * diag)
ElementProvider::ElementProvider Constructor.
Parameters
diag Diagram to search
Definition at line 40 of file elementprovider.cpp.
References m_diagram_list.
Member Function Documentation
find()
QList< Element * > ElementProvider::find (const int filter) const
ElementProvider::find Search and return the asked element corresponding with the given filter.
Parameters
filter the filter for search element (You can find all filter with the define in Element.h)
Definition at line 96 of file elementprovider.cpp.
References Diagram::elements(), Element::linkType(), and m_diagram_list.
Referenced by LinkSingleElementWidget::availableElements(), projectDataBase::populateElementInfoTable(), and projectDataBase::populateElementTable().
freeElement()
QList< Element * > ElementProvider::freeElement (const int filter) const
ElementProvider::FreeElement Search and return the asked element corresponding with the given filter All returned element are free, ie element aren't connected with another element.
Parameters
filter the filter for search element (You can find all filter with the define in Element.h)
Returns
Definition at line 54 of file elementprovider.cpp.
References Diagram::elements(), Element::isFree(), Element::linkType(), and m_diagram_list.
Referenced by LinkSingleElementWidget::availableElements(), and MasterPropertiesWidget::updateUi().
fromUuids()
QList< Element * > ElementProvider::fromUuids (QList< QUuid > uuid_list) const
ElementProvider::fromUuids.
Parameters
uuid_list list of uuid must be found
Returns
all elements with uuid corresponding to uuid in uuid_list
Definition at line 75 of file elementprovider.cpp.
References Diagram::elements(), m_diagram_list, and Element::uuid().
Referenced by Element::initLink().
table()
QVector< QetGraphicsTableItem * > ElementProvider::table (QetGraphicsTableItem * table = nullptr, QAbstractItemModel * model = nullptr)
ElementProvider::table.
Parameters
table
model
Returns
All tables wich display the derivated class of model (if set) and not already in all the chain of next/previous table of table (if set) If table and model are nullptr, return every tables
Definition at line 120 of file elementprovider.cpp.
References m_diagram_list, and QetGraphicsTableItem::Type.
Referenced by Diagram::refreshContents(), tableFromUuid(), and GraphicsTablePropertiesEditor::updateUi().
tableFromUuid()
QetGraphicsTableItem * ElementProvider::tableFromUuid (const QUuid & uuid)
ElementProvider::tableFromUuid.
Parameters
uuid
Returns
the table with uuid uuid or nullptr if not found
Definition at line 172 of file elementprovider.cpp.
References table().
Referenced by QetGraphicsTableItem::initLink().
Member Data Documentation
m_diagram_list
QList<Diagram *> ElementProvider::m_diagram_list private
Definition at line 48 of file elementprovider.h.
Referenced by ElementProvider(), find(), freeElement(), fromUuids(), and table().
The documentation for this class was generated from the following files:
elementprovider.h
elementprovider.cpp