QElectroTech: ElementPropertiesWidget Class Reference
ElementPropertiesWidget Class Reference
#include <elementpropertieswidget.h>
Public Slots
void findInPanel ()
ElementPropertiesWidget::findInPanel If m_element is a custom element, emit findElementRequired.
void editElement ()
ElementPropertiesWidget::editElement If m_element is a custom element, emit findElementRequired and editElementRequired.
Signals
void findEditClicked ()
Public Member Functions
ElementPropertiesWidget (Element *elmt, QWidget *parent=nullptr)
ElementPropertiesWidget::ElementPropertiesWidget Default constructor.
ElementPropertiesWidget (DynamicElementTextItem *text, QWidget *parent=nullptr)
ElementPropertiesWidget::ElementPropertiesWidget Same as default constructor, the edited element, is the parent element of text. The only difference with default constructor, is that the current tab is the tab for dynamic texts, and the item in the tree that represent text is expanded and selected.
ElementPropertiesWidget (ElementTextItemGroup *group, QWidget *parent=nullptr)
ElementPropertiesWidget::ElementPropertiesWidget Same as default constructor, the edited element, is the parent element of group. The only difference with default constructor, is that the current tab is the tab for dynamic texts, and the item in the tree that represent group is expanded and selected.
void setElement (Element *element) override
ElementPropertiesWidget::setElement Set element to be the edited element.
void setDynamicText (DynamicElementTextItem *text)
ElementPropertiesWidget::setDynamicText convenience function: same as call : ElementPropertiesWidget::setElement, with parameter the parent element of text. Set the dynamics text tab as current tab, expand and select the item that represent text.
void setTextsGroup (ElementTextItemGroup *group)
ElementPropertiesWidget::setTextsGroup Conveniance function : same as call : ElementPropertiesWidget::setElement, with parameter the parent element of group. Set the dynamics text tab as current tab, expand and select the item that represent group.
void apply () override
ElementPropertiesWidget::apply Apply the new properties by pushing an undo command to the parent project's undo stack of element.
void reset () override
ElementPropertiesWidget::reset Reset the edited properties.
bool setLiveEdit (bool live_edit) override
PropertiesEditorWidget::setLiveEdit Set the editor in live edit mode. When an editor is in live edit mode, every change is applied immediately (no need to call apply). If live edit can be enable, return true, else false. By default this method do nothing and return false (live edit is disable). Herited class of PropertiesEditorWidget must reimplemente this methode to manage the live edit mode.
Public Member Functions inherited from AbstractElementPropertiesEditorWidget
AbstractElementPropertiesEditorWidget (QWidget *parent=nullptr)
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual QUndoCommand * associatedUndo () const
PropertiesEditorWidget::associatedUndo By default, return a nullptr.
virtual QString title () const
PropertiesEditorWidget::title.
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Private Member Functions
void buildGui ()
ElementPropertiesWidget::build Build the content of this widget.
void updateUi () override
ElementPropertiesWidget::updateUi Update the content of this widget.
void addGeneralWidget ()
ElementPropertiesWidget::addGeneralWidget Add or update the general widget on this tab widget.
QWidget * generalWidget ()
ElementPropertiesWidget::generalWidget.
Private Attributes
Diagram * m_diagram
QTabWidget * m_tab
QList< AbstractElementPropertiesEditorWidget * > m_list_editor
QWidget * m_general_widget
Additional Inherited Members
Protected Member Functions inherited from PropertiesEditorWidget
virtual void enableLiveEdit ()
virtual void disableLiveEdit ()
Protected Attributes inherited from AbstractElementPropertiesEditorWidget
QPointer< Element > m_element
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
Definition at line 31 of file elementpropertieswidget.h.
Constructor & Destructor Documentation
ElementPropertiesWidget() [1/3]
ElementPropertiesWidget::ElementPropertiesWidget (Element * elmt, QWidget * parent = nullptr) explicit
ElementPropertiesWidget::ElementPropertiesWidget Default constructor.
Parameters
elmt
parent
Definition at line 40 of file elementpropertieswidget.cpp.
References buildGui(), and setElement().
ElementPropertiesWidget() [2/3]
ElementPropertiesWidget::ElementPropertiesWidget (DynamicElementTextItem * text, QWidget * parent = nullptr) explicit
ElementPropertiesWidget::ElementPropertiesWidget Same as default constructor, the edited element, is the parent element of text. The only difference with default constructor, is that the current tab is the tab for dynamic texts, and the item in the tree that represent text is expanded and selected.
Parameters
text
parent
Definition at line 61 of file elementpropertieswidget.cpp.
References buildGui(), QetGraphicsItem::diagram(), m_diagram, DynamicElementTextItem::parentElement(), and setDynamicText().
ElementPropertiesWidget() [3/3]
ElementPropertiesWidget::ElementPropertiesWidget (ElementTextItemGroup * group, QWidget * parent = nullptr) explicit
ElementPropertiesWidget::ElementPropertiesWidget Same as default constructor, the edited element, is the parent element of group. The only difference with default constructor, is that the current tab is the tab for dynamic texts, and the item in the tree that represent group is expanded and selected.
Parameters
group
parent
Definition at line 85 of file elementpropertieswidget.cpp.
References buildGui(), QetGraphicsItem::diagram(), m_diagram, setTextsGroup(), and Element::Type.
Member Function Documentation
addGeneralWidget()
void ElementPropertiesWidget::addGeneralWidget () private
ElementPropertiesWidget::addGeneralWidget Add or update the general widget on this tab widget.
Definition at line 336 of file elementpropertieswidget.cpp.
References generalWidget(), m_general_widget, m_tab, and QET::Icons::tr.
Referenced by setElement(), and updateUi().
apply()
void ElementPropertiesWidget::apply () override virtual
ElementPropertiesWidget::apply Apply the new properties by pushing an undo command to the parent project's undo stack of element.
Reimplemented from PropertiesEditorWidget.
Definition at line 184 of file elementpropertieswidget.cpp.
References PropertiesEditorWidget::associatedUndo(), AbstractElementPropertiesEditorWidget::m_element, m_list_editor, and PropertiesEditorWidget::updateUi().
buildGui()
void ElementPropertiesWidget::buildGui () private
ElementPropertiesWidget::build Build the content of this widget.
Definition at line 256 of file elementpropertieswidget.cpp.
References m_tab.
Referenced by ElementPropertiesWidget().
editElement
void ElementPropertiesWidget::editElement () slot
ElementPropertiesWidget::editElement If m_element is a custom element, emit findElementRequired and editElementRequired.
Definition at line 242 of file elementpropertieswidget.cpp.
References Diagram::editElementRequired(), findEditClicked(), Diagram::findElementRequired(), m_diagram, and AbstractElementPropertiesEditorWidget::m_element.
Referenced by generalWidget().
findEditClicked
void ElementPropertiesWidget::findEditClicked () signal
Referenced by editElement(), Element::editProperty(), and findInPanel().
findInPanel
void ElementPropertiesWidget::findInPanel () slot
ElementPropertiesWidget::findInPanel If m_element is a custom element, emit findElementRequired.
Definition at line 229 of file elementpropertieswidget.cpp.
References findEditClicked(), Diagram::findElementRequired(), m_diagram, and AbstractElementPropertiesEditorWidget::m_element.
Referenced by generalWidget().
generalWidget()
QWidget * ElementPropertiesWidget::generalWidget () private
ElementPropertiesWidget::generalWidget.
Returns
build and return the "general" widget
Definition at line 353 of file elementpropertieswidget.cpp.
References editElement(), QET::Icons::ElementEdit, findInPanel(), m_diagram, AbstractElementPropertiesEditorWidget::m_element, m_tab, QET::Icons::tr, and QET::Icons::ZoomDraw.
Referenced by addGeneralWidget().
reset()
void ElementPropertiesWidget::reset () override virtual
ElementPropertiesWidget::reset Reset the edited properties.
Reimplemented from PropertiesEditorWidget.
Definition at line 210 of file elementpropertieswidget.cpp.
References m_list_editor, and PropertiesEditorWidget::reset().
setDynamicText()
void ElementPropertiesWidget::setDynamicText (DynamicElementTextItem * text)
ElementPropertiesWidget::setDynamicText convenience function: same as call : ElementPropertiesWidget::setElement, with parameter the parent element of text. Set the dynamics text tab as current tab, expand and select the item that represent text.
Parameters
text
Definition at line 136 of file elementpropertieswidget.cpp.
References m_list_editor, m_tab, DynamicElementTextItem::parentElement(), DynamicElementTextItemEditor::setCurrentText(), and setElement().
Referenced by ElementPropertiesWidget().
setElement()
void ElementPropertiesWidget::setElement (Element * element) override virtual
ElementPropertiesWidget::setElement Set element to be the edited element.
Parameters
element
Implements AbstractElementPropertiesEditorWidget.
Definition at line 105 of file elementpropertieswidget.cpp.
References addGeneralWidget(), Element::linkType(), AbstractElementPropertiesEditorWidget::m_element, m_list_editor, AbstractElementPropertiesEditorWidget::setElement(), and updateUi().
Referenced by ElementPropertiesWidget(), setDynamicText(), and setTextsGroup().
setLiveEdit()
bool ElementPropertiesWidget::setLiveEdit (bool live_edit) override virtual
PropertiesEditorWidget::setLiveEdit Set the editor in live edit mode. When an editor is in live edit mode, every change is applied immediately (no need to call apply). If live edit can be enable, return true, else false. By default this method do nothing and return false (live edit is disable). Herited class of PropertiesEditorWidget must reimplemente this methode to manage the live edit mode.
Parameters
live_edit true to enable live edit
Returns
true if live edit is enable, else false.
Reimplemented from PropertiesEditorWidget.
Definition at line 214 of file elementpropertieswidget.cpp.
References m_list_editor, PropertiesEditorWidget::m_live_edit, and PropertiesEditorWidget::setLiveEdit().
setTextsGroup()
void ElementPropertiesWidget::setTextsGroup (ElementTextItemGroup * group)
ElementPropertiesWidget::setTextsGroup Conveniance function : same as call : ElementPropertiesWidget::setElement, with parameter the parent element of group. Set the dynamics text tab as current tab, expand and select the item that represent group.
Parameters
group
Definition at line 162 of file elementpropertieswidget.cpp.
References m_list_editor, m_tab, DynamicElementTextItemEditor::setCurrentGroup(), setElement(), and Element::Type.
Referenced by ElementPropertiesWidget().
updateUi()
void ElementPropertiesWidget::updateUi () override private virtual
ElementPropertiesWidget::updateUi Update the content of this widget.
Reimplemented from PropertiesEditorWidget.
Definition at line 268 of file elementpropertieswidget.cpp.
References addGeneralWidget(), AbstractElementPropertiesEditorWidget::m_element, m_general_widget, m_list_editor, PropertiesEditorWidget::m_live_edit, m_tab, Element::Master, Element::NextReport, Element::PreviousReport, Element::Simple, Element::Slave, and Element::Terminale.
Referenced by setElement().
Member Data Documentation
m_diagram
Diagram* ElementPropertiesWidget::m_diagram private
Definition at line 60 of file elementpropertieswidget.h.
Referenced by editElement(), ElementPropertiesWidget(), findInPanel(), and generalWidget().
m_general_widget
QWidget* ElementPropertiesWidget::m_general_widget private
Definition at line 63 of file elementpropertieswidget.h.
Referenced by addGeneralWidget(), and updateUi().
m_list_editor
QList<AbstractElementPropertiesEditorWidget *> ElementPropertiesWidget::m_list_editor private
Definition at line 62 of file elementpropertieswidget.h.
Referenced by apply(), reset(), setDynamicText(), setElement(), setLiveEdit(), setTextsGroup(), and updateUi().
m_tab
QTabWidget* ElementPropertiesWidget::m_tab private
Definition at line 61 of file elementpropertieswidget.h.
Referenced by addGeneralWidget(), buildGui(), generalWidget(), setDynamicText(), setTextsGroup(), and updateUi().
The documentation for this class was generated from the following files:
elementpropertieswidget.h
elementpropertieswidget.cpp