QElectroTech: ElementPictureFactory Class Reference
ElementPictureFactory Class Reference
The ElementPictureFactory class This class is singleton factory, use to create and get the picture use by elements.
#include <elementpicturefactory.h>
Classes
struct primitives
Public Member Functions
void getPictures (const ElementsLocation &location, QPicture &picture, QPicture &low_picture)
ElementPictureFactory::getPictures Set the picture of the element at location. Note, picture can be null.
QPixmap pixmap (const ElementsLocation &location)
ElementPictureFactory::pixmap.
ElementPictureFactory::primitives getPrimitives (const ElementsLocation &location)
ElementPictureFactory::getPrimitives.
Static Public Member Functions
static ElementPictureFactory * instance ()
instance
static void dropInstance ()
dropInstance Drop the instance of factory
Private Member Functions
ElementPictureFactory ()
ElementPictureFactory (const ElementPictureFactory &)
ElementPictureFactory operator= (const ElementPictureFactory &)
~ElementPictureFactory ()
bool build (const ElementsLocation &location, QPicture *picture=nullptr, QPicture *low_picture=nullptr)
ElementPictureFactory::build Build the picture from location.
void parseElement (const QDomElement &dom, QPainter &painter, primitives &prim) const
void parseLine (const QDomElement &dom, QPainter &painter, primitives &prim) const
void parseRect (const QDomElement &dom, QPainter &painter, primitives &prim) const
void parseEllipse (const QDomElement &dom, QPainter &painter, primitives &prim) const
void parseCircle (const QDomElement &dom, QPainter &painter, primitives &prim) const
void parseArc (const QDomElement &dom, QPainter &painter, primitives &prim) const
void parsePolygon (const QDomElement &dom, QPainter &painter, primitives &prim) const
void parseText (const QDomElement &dom, QPainter &painter, primitives &prim) const
void setPainterStyle (const QDomElement &dom, QPainter &painter) const
ElementPictureFactory::setPainterStyle apply the style store in dom to painter.
Private Attributes
QHash< QUuid, QPicture > m_pictures_H
QHash< QUuid, QPicture > m_low_pictures_H
QHash< QUuid, QPixmap > m_pixmap_H
QHash< QUuid, primitives > m_primitives_H
Static Private Attributes
static ElementPictureFactory * m_factory = nullptr
Detailed Description
The ElementPictureFactory class This class is singleton factory, use to create and get the picture use by elements.
Definition at line 37 of file elementpicturefactory.h.
Constructor & Destructor Documentation
ElementPictureFactory() [1/2]
ElementPictureFactory::ElementPictureFactory () inline private
Definition at line 90 of file elementpicturefactory.h.
Referenced by instance().
ElementPictureFactory() [2/2]
ElementPictureFactory::ElementPictureFactory (const ElementPictureFactory &) private
~ElementPictureFactory()
ElementPictureFactory::~ElementPictureFactory () private
Definition at line 129 of file elementpicturefactory.cpp.
References m_primitives_H.
Member Function Documentation
build()
bool ElementPictureFactory::build (const ElementsLocation & location, QPicture * picture = nullptr, QPicture * low_picture = nullptr) private
ElementPictureFactory::build Build the picture from location.
Parameters
location
picture
low_picture if picture and/or low_picture are not null this function draw on it and don't store it. if null, this function create a QPicture for normal and low zoom, draw on it and store it in m_pictures_H and m_low_pictures_H
Returns
Definition at line 147 of file elementpicturefactory.cpp.
References QET::attributeIsAnInteger(), m_low_pictures_H, m_pictures_H, m_primitives_H, parseElement(), QET::Icons::tr, ElementsLocation::uuid(), QET::version, and ElementsLocation::xml().
Referenced by getPictures(), getPrimitives(), and pixmap().
dropInstance()
static void ElementPictureFactory::dropInstance () inline static
dropInstance Drop the instance of factory
Definition at line 73 of file elementpicturefactory.h.
References m_factory.
Referenced by QETApp::~QETApp().
getPictures()
void ElementPictureFactory::getPictures (const ElementsLocation & location, QPicture & picture, QPicture & low_picture)
ElementPictureFactory::getPictures Set the picture of the element at location. Note, picture can be null.
Parameters
location
picture
low_picture
Definition at line 42 of file elementpicturefactory.cpp.
References build(), ElementsLocation::exist(), m_low_pictures_H, m_pictures_H, and ElementsLocation::uuid().
Referenced by Element::buildFromXml().
getPrimitives()
ElementPictureFactory::primitives ElementPictureFactory::getPrimitives (const ElementsLocation & location)
ElementPictureFactory::getPrimitives.
Parameters
location
Returns
The primtive used to draw the element at location
Definition at line 120 of file elementpicturefactory.cpp.
References build(), m_primitives_H, and ElementsLocation::uuid().
Referenced by ExportDialog::generateDxf().
instance()
static ElementPictureFactory* ElementPictureFactory::instance () inline static
instance
Returns
The instance of the factory
Definition at line 55 of file elementpicturefactory.h.
References ElementPictureFactory(), and m_factory.
Referenced by Element::buildFromXml(), ExportDialog::generateDxf(), ElementsLocation::icon(), and Element::pixmap().
operator=()
ElementPictureFactory ElementPictureFactory::operator= (const ElementPictureFactory &) private
parseArc()
void ElementPictureFactory::parseArc (const QDomElement & dom, QPainter & painter, ElementPictureFactory::primitives & prim) const private
Definition at line 423 of file elementpicturefactory.cpp.
References QET::attributeIsAReal(), ElementPictureFactory::primitives::m_arcs, and setPainterStyle().
Referenced by parseElement().
parseCircle()
void ElementPictureFactory::parseCircle (const QDomElement & dom, QPainter & painter, ElementPictureFactory::primitives & prim) const private
Definition at line 406 of file elementpicturefactory.cpp.
References QET::attributeIsAReal(), ElementPictureFactory::primitives::m_circles, and setPainterStyle().
Referenced by parseElement().
parseElement()
void ElementPictureFactory::parseElement (const QDomElement & dom, QPainter & painter, primitives & prim) const private
Definition at line 248 of file elementpicturefactory.cpp.
References parseArc(), parseCircle(), parseEllipse(), parseLine(), parsePolygon(), parseRect(), and parseText().
Referenced by build().
parseEllipse()
void ElementPictureFactory::parseEllipse (const QDomElement & dom, QPainter & painter, ElementPictureFactory::primitives & prim) const private
Definition at line 382 of file elementpicturefactory.cpp.
References QET::attributeIsAReal(), ElementPictureFactory::primitives::m_arcs, and setPainterStyle().
Referenced by parseElement().
parseLine()
void ElementPictureFactory::parseLine (const QDomElement & dom, QPainter & painter, primitives & prim) const private
Definition at line 259 of file elementpicturefactory.cpp.
References QET::attributeIsAReal(), Qet::Circle, Qet::Diamond, Qet::endTypeFromString(), PartLine::fourEndPoints(), ElementPictureFactory::primitives::m_lines, PartLine::requiredLengthForEndType(), setPainterStyle(), Qet::Simple, and Qet::Triangle.
Referenced by parseElement().
parsePolygon()
void ElementPictureFactory::parsePolygon (const QDomElement & dom, QPainter & painter, ElementPictureFactory::primitives & prim) const private
Definition at line 450 of file elementpicturefactory.cpp.
References QET::attributeIsAReal(), ElementPictureFactory::primitives::m_polygons, and setPainterStyle().
Referenced by parseElement().
parseRect()
void ElementPictureFactory::parseRect (const QDomElement & dom, QPainter & painter, ElementPictureFactory::primitives & prim) const private
Definition at line 358 of file elementpicturefactory.cpp.
References QET::attributeIsAReal(), ElementPictureFactory::primitives::m_rectangles, and setPainterStyle().
Referenced by parseElement().
parseText()
void ElementPictureFactory::parseText (const QDomElement & dom, QPainter & painter, ElementPictureFactory::primitives & prim) const private
Definition at line 487 of file elementpicturefactory.cpp.
References QETApp::diagramTextsFont(), ElementPictureFactory::primitives::m_texts, and setPainterStyle().
Referenced by parseElement().
pixmap()
QPixmap ElementPictureFactory::pixmap (const ElementsLocation & location)
ElementPictureFactory::pixmap.
Parameters
location
Returns
the pixmap of the element at location Note pixmap can be null
Definition at line 76 of file elementpicturefactory.cpp.
References build(), m_pictures_H, m_pixmap_H, ElementsLocation::pugiXml(), and ElementsLocation::uuid().
Referenced by Element::pixmap().
setPainterStyle()
void ElementPictureFactory::setPainterStyle (const QDomElement & dom, QPainter & painter) const private
ElementPictureFactory::setPainterStyle apply the style store in dom to painter.
Parameters
dom
painter
Definition at line 555 of file elementpicturefactory.cpp.
Referenced by parseArc(), parseCircle(), parseEllipse(), parseLine(), parsePolygon(), parseRect(), and parseText().
Member Data Documentation
m_factory
ElementPictureFactory * ElementPictureFactory::m_factory = nullptr static private
Definition at line 110 of file elementpicturefactory.h.
Referenced by dropInstance(), and instance().
m_low_pictures_H
QHash<QUuid, QPicture> ElementPictureFactory::m_low_pictures_H private
Definition at line 107 of file elementpicturefactory.h.
Referenced by build(), and getPictures().
m_pictures_H
QHash<QUuid, QPicture> ElementPictureFactory::m_pictures_H private
Definition at line 106 of file elementpicturefactory.h.
Referenced by build(), getPictures(), and pixmap().
m_pixmap_H
QHash<QUuid, QPixmap> ElementPictureFactory::m_pixmap_H private
Definition at line 108 of file elementpicturefactory.h.
Referenced by pixmap().
m_primitives_H
QHash<QUuid, primitives> ElementPictureFactory::m_primitives_H private
Definition at line 109 of file elementpicturefactory.h.
Referenced by build(), getPrimitives(), and ~ElementPictureFactory().
The documentation for this class was generated from the following files:
elementpicturefactory.h
elementpicturefactory.cpp