QElectroTech: QTextOrientationSpinBoxWidget Class Reference
QTextOrientationSpinBoxWidget Class Reference
#include <qtextorientationspinboxwidget.h>
Public Slots
void setOrientation (const double &)
void setValue (const double &)
void setReadOnly (bool)
Signals
void editingFinished (double)
void editingFinished ()
Public Member Functions
QTextOrientationSpinBoxWidget (QWidget *=nullptr)
~QTextOrientationSpinBoxWidget () override
QTextOrientationWidget * orientationWidget () const
QDoubleSpinBox * spinBox () const
double orientation () const
double value () const
bool isReadOnly () const
Private Slots
void emitChangeSignals ()
Private Member Functions
QTextOrientationSpinBoxWidget (const QTextOrientationSpinBoxWidget &)
void build ()
Private Attributes
QTextOrientationWidget * orientation_widget_
QDoubleSpinBox * spin_box_
Detailed Description
This class provides a widget grouping a QTextOrientationWidget and QSpinBox next to each other.
See also
QTextOrientationWidget
Definition at line 27 of file qtextorientationspinboxwidget.h.
Constructor & Destructor Documentation
QTextOrientationSpinBoxWidget() [1/2]
QTextOrientationSpinBoxWidget::QTextOrientationSpinBoxWidget (QWidget * parent = nullptr)
Constructeur
Parameters
parent QWidget parent de ce QTextOrientationSpinBoxWidget
Definition at line 24 of file qtextorientationspinboxwidget.cpp.
References build().
~QTextOrientationSpinBoxWidget()
QTextOrientationSpinBoxWidget::~QTextOrientationSpinBoxWidget () override
Destructeur
Definition at line 33 of file qtextorientationspinboxwidget.cpp.
QTextOrientationSpinBoxWidget() [2/2]
QTextOrientationSpinBoxWidget::QTextOrientationSpinBoxWidget (const QTextOrientationSpinBoxWidget &) private
Member Function Documentation
build()
void QTextOrientationSpinBoxWidget::build () private
Construit le widget
Definition at line 101 of file qtextorientationspinboxwidget.cpp.
References editingFinished(), emitChangeSignals(), orientation_widget_, setOrientation(), setValue(), and spin_box_.
Referenced by QTextOrientationSpinBoxWidget().
editingFinished [1/2]
void QTextOrientationSpinBoxWidget::editingFinished () signal
Referenced by build(), and emitChangeSignals().
editingFinished [2/2]
void QTextOrientationSpinBoxWidget::editingFinished (double) signal
Signals emitted when users have finished editing the orientation.
emitChangeSignals
void QTextOrientationSpinBoxWidget::emitChangeSignals () private slot
Emet le signal orientationEditingFinished avec la valeur de l'orientation en cours
Definition at line 131 of file qtextorientationspinboxwidget.cpp.
References editingFinished(), and orientation().
Referenced by build().
isReadOnly()
bool QTextOrientationSpinBoxWidget::isReadOnly () const
Returns
true si le widget est en mode "lecture seule", false sinon
Definition at line 69 of file qtextorientationspinboxwidget.cpp.
References orientation_widget_.
orientation()
double QTextOrientationSpinBoxWidget::orientation () const
Returns
l'orientation en cours
Definition at line 53 of file qtextorientationspinboxwidget.cpp.
References orientation_widget_.
Referenced by emitChangeSignals(), RotateTextsCommand::openDialog(), and value().
orientationWidget()
QTextOrientationWidget * QTextOrientationSpinBoxWidget::orientationWidget () const
Returns
un pointeur vers le QTextOrientationWidget
Definition at line 39 of file qtextorientationspinboxwidget.cpp.
References orientation_widget_.
setOrientation
void QTextOrientationSpinBoxWidget::setOrientation (const double & value) slot
Parameters
value Nouvelle valeur de l'orientation a afficher
Definition at line 76 of file qtextorientationspinboxwidget.cpp.
References orientation_widget_, setValue(), spin_box_, and value().
Referenced by build(), and setValue().
setReadOnly
void QTextOrientationSpinBoxWidget::setReadOnly (bool ro) slot
Parameters
ro true pour passer le widget en mode "lecture seule", false sinon
Definition at line 93 of file qtextorientationspinboxwidget.cpp.
References orientation_widget_, QET::Icons::ro, and spin_box_.
setValue
void QTextOrientationSpinBoxWidget::setValue (const double & value) slot
Synonyme pour setOrientation(value)
Parameters
value Nouvelle valeur de l'orientation a afficher
See also
setOrientation
Definition at line 86 of file qtextorientationspinboxwidget.cpp.
References setOrientation(), and value().
Referenced by build(), and setOrientation().
spinBox()
QDoubleSpinBox * QTextOrientationSpinBoxWidget::spinBox () const
Returns
un pointeur vers le QSpinBox
Definition at line 46 of file qtextorientationspinboxwidget.cpp.
References spin_box_.
Referenced by RotateTextsCommand::openDialog().
value()
double QTextOrientationSpinBoxWidget::value () const
Synonyme pour orientation()
Returns
l'orientation en cours
See also
orientation()
Definition at line 62 of file qtextorientationspinboxwidget.cpp.
References orientation().
Referenced by setOrientation(), and setValue().
Member Data Documentation
orientation_widget_
QTextOrientationWidget* QTextOrientationSpinBoxWidget::orientation_widget_ private
Definition at line 65 of file qtextorientationspinboxwidget.h.
Referenced by build(), isReadOnly(), orientation(), orientationWidget(), setOrientation(), and setReadOnly().
spin_box_
QDoubleSpinBox* QTextOrientationSpinBoxWidget::spin_box_ private
Definition at line 66 of file qtextorientationspinboxwidget.h.
Referenced by build(), setOrientation(), setReadOnly(), and spinBox().
The documentation for this class was generated from the following files:
qtextorientationspinboxwidget.h
qtextorientationspinboxwidget.cpp