QElectroTech: PropertiesEditorDockWidget Class Reference
PropertiesEditorDockWidget Class Reference
#include <propertieseditordockwidget.h>
Public Member Functions
PropertiesEditorDockWidget (QWidget *parent=nullptr)
PropertiesEditorDockWidget::PropertiesEditorDockWidget Constructor.
~PropertiesEditorDockWidget () override
PropertiesEditorDockWidget::~PropertiesEditorDockWidget Destructor.
virtual void clear ()
PropertiesEditorDockWidget::clear Remove all editor present in this dock and delete it. They also disabled the button box at the bottom of this dock.
virtual void apply ()
PropertiesEditorDockWidget::apply Call the apply method for each editor present in this dock.
virtual void reset ()
PropertiesEditorDockWidget::reset Call the reset method for each editor present in this widget.
bool addEditor (PropertiesEditorWidget *editor, int index=0)
PropertiesEditorDockWidget::addEditor Add an editor in this dock at index in the main vertical layout (note the button box are displayed at bottom of this layout by default) When an editor is added, we enable the button box.
QList< PropertiesEditorWidget * > editors () const
PropertiesEditorDockWidget::editors.
bool removeEditor (PropertiesEditorWidget *editor)
PropertiesEditorDockWidget::removeEditor Remove editor from this dock. The editor wasn't delete a the end of this method If the editor was the last on this widget, we disabled the button box.
Protected Attributes
QList< PropertiesEditorWidget * > m_editor_list
Private Attributes
Ui::PropertiesEditorDockWidget * ui
Detailed Description
Definition at line 29 of file propertieseditordockwidget.h.
Constructor & Destructor Documentation
PropertiesEditorDockWidget()
PropertiesEditorDockWidget::PropertiesEditorDockWidget (QWidget * parent = nullptr) explicit
PropertiesEditorDockWidget::PropertiesEditorDockWidget Constructor.
Parameters
parent : parent widget
Definition at line 27 of file propertieseditordockwidget.cpp.
References ui.
~PropertiesEditorDockWidget()
PropertiesEditorDockWidget::~PropertiesEditorDockWidget () override
PropertiesEditorDockWidget::~PropertiesEditorDockWidget Destructor.
Definition at line 38 of file propertieseditordockwidget.cpp.
References clear(), and ui.
Member Function Documentation
addEditor()
bool PropertiesEditorDockWidget::addEditor (PropertiesEditorWidget * editor, int index = 0)
PropertiesEditorDockWidget::addEditor Add an editor in this dock at index in the main vertical layout (note the button box are displayed at bottom of this layout by default) When an editor is added, we enable the button box.
Parameters
editor : editor to add;
index : index of editor in the layout
Returns
true if was added (or already add) or false if can't be add (editor = nullptr)
Definition at line 91 of file propertieseditordockwidget.cpp.
References m_editor_list, and ui.
Referenced by DiagramPropertiesEditorDockWidget::addEditor().
apply()
void PropertiesEditorDockWidget::apply () virtual
PropertiesEditorDockWidget::apply Call the apply method for each editor present in this dock.
Definition at line 65 of file propertieseditordockwidget.cpp.
References PropertiesEditorWidget::apply(), and m_editor_list.
clear()
void PropertiesEditorDockWidget::clear () virtual
PropertiesEditorDockWidget::clear Remove all editor present in this dock and delete it. They also disabled the button box at the bottom of this dock.
Definition at line 49 of file propertieseditordockwidget.cpp.
References m_editor_list, and ui.
Referenced by DiagramPropertiesEditorDockWidget::diagramWasDeleted(), DiagramPropertiesEditorDockWidget::selectionChanged(), DiagramPropertiesEditorDockWidget::setDiagram(), and ~PropertiesEditorDockWidget().
editors()
QList< PropertiesEditorWidget * > PropertiesEditorDockWidget::editors () const
PropertiesEditorDockWidget::editors.
Returns
all editor used in this dock
Definition at line 106 of file propertieseditordockwidget.cpp.
References m_editor_list.
Referenced by DiagramPropertiesEditorDockWidget::selectionChanged().
removeEditor()
bool PropertiesEditorDockWidget::removeEditor (PropertiesEditorWidget * editor)
PropertiesEditorDockWidget::removeEditor Remove editor from this dock. The editor wasn't delete a the end of this method If the editor was the last on this widget, we disabled the button box.
Parameters
editor : editor to remove
Returns
true on success, else false
Definition at line 118 of file propertieseditordockwidget.cpp.
References m_editor_list, and ui.
Referenced by DiagramPropertiesEditorDockWidget::removeEditor().
reset()
void PropertiesEditorDockWidget::reset () virtual
PropertiesEditorDockWidget::reset Call the reset method for each editor present in this widget.
Definition at line 75 of file propertieseditordockwidget.cpp.
References m_editor_list, and PropertiesEditorWidget::reset().
Member Data Documentation
m_editor_list
QList<PropertiesEditorWidget *> PropertiesEditorDockWidget::m_editor_list protected
Definition at line 45 of file propertieseditordockwidget.h.
Referenced by addEditor(), apply(), clear(), editors(), removeEditor(), and reset().
ui
Ui::PropertiesEditorDockWidget* PropertiesEditorDockWidget::ui private
Definition at line 48 of file propertieseditordockwidget.h.
Referenced by addEditor(), clear(), PropertiesEditorDockWidget(), removeEditor(), and ~PropertiesEditorDockWidget().
The documentation for this class was generated from the following files:
propertieseditordockwidget.h
propertieseditordockwidget.cpp