QElectroTech: ImportElementTextPatternDialog Class Reference
ImportElementTextPatternDialog Class Reference
The ImportElementTextPatternDialog class A dialog use for ask user to select a element text pattern. This dialog is highly inspired from QInputDialog::getItem. In fact this the same + a check box.
#include <importelementtextpatterndialog.h>
Public Member Functions
ImportElementTextPatternDialog (QWidget *parent=nullptr)
~ImportElementTextPatternDialog ()
void setLabelText (const QString &label)
void setComboBoxItems (const QStringList &items)
QString textValue () const
Static Public Member Functions
static QString getItem (QWidget *parent, const QString &title, const QString &label, const QStringList &items, bool *ok=nullptr, bool *erase=nullptr)
ImportElementTextPatternDialog::getItem For all arguments see QInputDialog::getItem, except for erase, they store the state of the check box.
Private Attributes
Ui::ImportElementTextPatternDialog * ui
Detailed Description
The ImportElementTextPatternDialog class A dialog use for ask user to select a element text pattern. This dialog is highly inspired from QInputDialog::getItem. In fact this the same + a check box.
Definition at line 33 of file importelementtextpatterndialog.h.
Constructor & Destructor Documentation
ImportElementTextPatternDialog()
ImportElementTextPatternDialog::ImportElementTextPatternDialog (QWidget * parent = nullptr) explicit
Definition at line 21 of file importelementtextpatterndialog.cpp.
References ui.
Referenced by getItem().
~ImportElementTextPatternDialog()
ImportElementTextPatternDialog::~ImportElementTextPatternDialog ()
Definition at line 27 of file importelementtextpatterndialog.cpp.
References ui.
Member Function Documentation
getItem()
QString ImportElementTextPatternDialog::getItem (QWidget * parent, const QString & title, const QString & label, const QStringList & items, bool * ok = nullptr, bool * erase = nullptr) static
ImportElementTextPatternDialog::getItem For all arguments see QInputDialog::getItem, except for erase, they store the state of the check box.
Parameters
parent
title
label
items
ok
erase
Returns
Definition at line 43 of file importelementtextpatterndialog.cpp.
References ImportElementTextPatternDialog().
Referenced by ImportElementTextPattern::getName().
setComboBoxItems()
void ImportElementTextPatternDialog::setComboBoxItems (const QStringList & items)
Definition at line 68 of file importelementtextpatterndialog.cpp.
References ui.
setLabelText()
void ImportElementTextPatternDialog::setLabelText (const QString & label)
Definition at line 64 of file importelementtextpatterndialog.cpp.
References ui.
textValue()
QString ImportElementTextPatternDialog::textValue () const
Definition at line 72 of file importelementtextpatterndialog.cpp.
References ui.
Member Data Documentation
ui
Ui::ImportElementTextPatternDialog* ImportElementTextPatternDialog::ui private
Definition at line 49 of file importelementtextpatterndialog.h.
Referenced by ImportElementTextPatternDialog(), setComboBoxItems(), setLabelText(), textValue(), and ~ImportElementTextPatternDialog().
The documentation for this class was generated from the following files:
importelementtextpatterndialog.h
importelementtextpatterndialog.cpp