QElectroTech: ElementsPanelWidget Class Reference
ElementsPanelWidget Class Reference
The ElementsPanelWidget class This class embeds an elements panel under a toolbar providing various actions to manage elements.
#include <elementspanelwidget.h>
Public Slots
void openDirectoryForSelectedItem ()
void copyPathForSelectedItem ()
void reloadAndFilter ()
void activateProject ()
void closeProject ()
void editProjectProperties ()
void editDiagramProperties ()
void newDiagram ()
void deleteDiagram ()
void moveDiagramUp ()
void moveDiagramDown ()
void moveDiagramUpTop ()
void moveDiagramUpx10 ()
void moveDiagramDownx10 ()
void addTitleBlockTemplate ()
void editTitleBlockTemplate ()
void removeTitleBlockTemplate ()
void updateButtons ()
void handleContextMenu (const QPoint &)
void filterEdited (const QString &)
Signals
void requestForDiagram (Diagram *)
void requestForProject (QETProject *)
void requestForNewDiagram (QETProject *)
void requestForProjectClosing (QETProject *)
void requestForProjectPropertiesEdition (QETProject *)
void requestForDiagramPropertiesEdition (Diagram *)
void requestForDiagramDeletion (Diagram *)
void requestForDiagramMoveUp (Diagram *)
void requestForDiagramMoveDown (Diagram *)
void requestForDiagramMoveUpTop (Diagram *)
void requestForDiagramMoveUpx10 (Diagram *)
void requestForDiagramMoveDownx10 (Diagram *)
Public Member Functions
ElementsPanelWidget (QWidget *=nullptr)
~ElementsPanelWidget () override
ElementsPanel & elementsPanel () const
ElementsPanelWidget::elementsPanel.
Protected Member Functions
void keyPressEvent (QKeyEvent *e) override
Private Member Functions
ElementsPanelWidget (const ElementsPanelWidget &)
Private Attributes
ElementsPanel * elements_panel
QAction * open_directory
QAction * copy_path
QAction * prj_activate
QAction * prj_close
QAction * prj_edit_prop
QAction * prj_prop_diagram
QAction * prj_add_diagram
QAction * prj_del_diagram
QAction * prj_move_diagram_up
QAction * prj_move_diagram_top
QAction * prj_move_diagram_down
QAction * prj_move_diagram_upx10
QAction * prj_move_diagram_downx10
QAction * tbt_add
QAction * tbt_edit
QAction * tbt_remove
QMenu * context_menu
QLineEdit * filter_textfield
QString previous_filter_
Detailed Description
The ElementsPanelWidget class This class embeds an elements panel under a toolbar providing various actions to manage elements.
See also
ElementsPanel
Definition at line 29 of file elementspanelwidget.h.
Constructor & Destructor Documentation
ElementsPanelWidget() [1/2]
ElementsPanelWidget::ElementsPanelWidget (QWidget * parent = nullptr)
Constructeur
Parameters
parent Le QWidget parent de ce widget
Definition at line 41 of file elementspanelwidget.cpp.
References activateProject(), addTitleBlockTemplate(), closeProject(), context_menu, copy_path, copyPathForSelectedItem(), deleteDiagram(), QET::Icons::DiagramAdd, QET::Icons::DiagramDelete, QET::Icons::DialogInformation, QET::Icons::DocumentClose, editDiagramProperties(), editProjectProperties(), editTitleBlockTemplate(), elements_panel, filter_textfield, filterEdited(), QET::Icons::FolderOpen, QET::Icons::GoDown, QET::Icons::GoDownDouble, QET::Icons::GoTop, QET::Icons::GoUp, QET::Icons::GoUpDouble, handleContextMenu(), QET::Icons::IC_CopyFile, QETApp::instance(), moveDiagramDown(), moveDiagramDownx10(), moveDiagramUp(), moveDiagramUpTop(), moveDiagramUpx10(), newDiagram(), open_directory, openDirectoryForSelectedItem(), prj_activate, prj_add_diagram, prj_close, prj_del_diagram, prj_edit_prop, prj_move_diagram_down, prj_move_diagram_downx10, prj_move_diagram_top, prj_move_diagram_up, prj_move_diagram_upx10, prj_prop_diagram, QET::Icons::ProjectFile, removeTitleBlockTemplate(), requestForDiagram(), tbt_add, tbt_edit, tbt_remove, QET::Icons::TitleBlock, QET::Icons::tr, and updateButtons().
~ElementsPanelWidget()
ElementsPanelWidget::~ElementsPanelWidget () override
Destructeur
Definition at line 120 of file elementspanelwidget.cpp.
ElementsPanelWidget() [2/2]
ElementsPanelWidget::ElementsPanelWidget (const ElementsPanelWidget &) private
Member Function Documentation
activateProject
void ElementsPanelWidget::activateProject () slot
Emit the requestForProject signal with te selected project
Definition at line 165 of file elementspanelwidget.cpp.
References elements_panel, and requestForProject().
Referenced by ElementsPanelWidget().
addTitleBlockTemplate
void ElementsPanelWidget::addTitleBlockTemplate () slot
Opens a template editor to create a new title block template.
Definition at line 267 of file elementspanelwidget.cpp.
References elements_panel, QETApp::instance(), and QET::TitleBlockTemplatesCollection.
Referenced by ElementsPanelWidget().
closeProject
void ElementsPanelWidget::closeProject () slot
Emet le signal requestForProjectClosing avec le projet selectionne
Definition at line 174 of file elementspanelwidget.cpp.
References elements_panel, and requestForProjectClosing().
Referenced by ElementsPanelWidget().
copyPathForSelectedItem
void ElementsPanelWidget::copyPathForSelectedItem () slot
Copy the full path to the file represented by the selected item to the clipboard.
Definition at line 140 of file elementspanelwidget.cpp.
References elements_panel.
Referenced by ElementsPanelWidget().
deleteDiagram
void ElementsPanelWidget::deleteDiagram () slot
Emet le signal requestForDiagramDeletion avec le schema selectionne
Definition at line 210 of file elementspanelwidget.cpp.
References elements_panel, and requestForDiagramDeletion().
Referenced by ElementsPanelWidget().
editDiagramProperties
void ElementsPanelWidget::editDiagramProperties () slot
Emet le signal requestForDiagramPropertiesEdition avec le schema selectionne
Definition at line 192 of file elementspanelwidget.cpp.
References elements_panel, and requestForDiagramPropertiesEdition().
Referenced by ElementsPanelWidget().
editProjectProperties
void ElementsPanelWidget::editProjectProperties () slot
Emet le signal requestForProjectPropertiesEdition avec le projet selectionne
Definition at line 183 of file elementspanelwidget.cpp.
References elements_panel, and requestForProjectPropertiesEdition().
Referenced by ElementsPanelWidget().
editTitleBlockTemplate
void ElementsPanelWidget::editTitleBlockTemplate () slot
Opens an editor to edit the currently selected title block template, if any.
Definition at line 281 of file elementspanelwidget.cpp.
References elements_panel, QETApp::instance(), and QET::TitleBlockTemplate.
Referenced by ElementsPanelWidget().
elementsPanel()
ElementsPanel & ElementsPanelWidget::elementsPanel () const inline
ElementsPanelWidget::elementsPanel.
Returns
The elements panel embedded within this widget.
Definition at line 110 of file elementspanelwidget.h.
References elements_panel.
filterEdited
void ElementsPanelWidget::filterEdited (const QString & next_text) slot
Definition at line 392 of file elementspanelwidget.cpp.
References QET::BeginFilter, elements_panel, QET::EndFilter, previous_filter_, and QET::RegularFilter.
Referenced by ElementsPanelWidget().
handleContextMenu
void ElementsPanelWidget::handleContextMenu (const QPoint & pos) slot
Gere le menu contextuel du panel d'elements
Parameters
pos Position ou le menu contextuel a ete demande
Definition at line 346 of file elementspanelwidget.cpp.
References context_menu, copy_path, QET::Diagram, elements_panel, open_directory, prj_activate, prj_add_diagram, prj_close, prj_del_diagram, prj_edit_prop, prj_move_diagram_down, prj_move_diagram_downx10, prj_move_diagram_top, prj_move_diagram_up, prj_move_diagram_upx10, prj_prop_diagram, QET::Project, tbt_add, tbt_edit, tbt_remove, QET::TitleBlockTemplate, QET::TitleBlockTemplatesCollection, and updateButtons().
Referenced by ElementsPanelWidget().
keyPressEvent()
void ElementsPanelWidget::keyPressEvent (QKeyEvent * e) override protected
Treat key press event inside elements panel widget
Definition at line 409 of file elementspanelwidget.cpp.
References elements_panel, requestForDiagramDeletion(), requestForDiagramMoveDown(), requestForDiagramMoveUp(), and requestForDiagramMoveUpTop().
moveDiagramDown
void ElementsPanelWidget::moveDiagramDown () slot
Emet le signal requestForDiagramMoveDown avec le schema selectionne
Definition at line 239 of file elementspanelwidget.cpp.
References elements_panel, and requestForDiagramMoveDown().
Referenced by ElementsPanelWidget().
moveDiagramDownx10
void ElementsPanelWidget::moveDiagramDownx10 () slot
Emet le signal requestForDiagramMoveDownx10 avec le schema selectionne
Definition at line 257 of file elementspanelwidget.cpp.
References elements_panel, and requestForDiagramMoveDownx10().
Referenced by ElementsPanelWidget().
moveDiagramUp
void ElementsPanelWidget::moveDiagramUp () slot
Emet le signal requestForDiagramMoveUp avec le schema selectionne
Definition at line 230 of file elementspanelwidget.cpp.
References elements_panel, and requestForDiagramMoveUp().
Referenced by ElementsPanelWidget().
moveDiagramUpTop
void ElementsPanelWidget::moveDiagramUpTop () slot
Emet le signal requestForDiagramMoveUpTop avec le schema selectionne
Definition at line 219 of file elementspanelwidget.cpp.
References elements_panel, and requestForDiagramMoveUpTop().
Referenced by ElementsPanelWidget().
moveDiagramUpx10
void ElementsPanelWidget::moveDiagramUpx10 () slot
Emet le signal requestForDiagramMoveUpx10 avec le schema selectionne
Definition at line 248 of file elementspanelwidget.cpp.
References elements_panel, and requestForDiagramMoveUpx10().
Referenced by ElementsPanelWidget().
newDiagram
void ElementsPanelWidget::newDiagram () slot
Emet le signal requestForNewDiagram avec le projet selectionne
Definition at line 201 of file elementspanelwidget.cpp.
References elements_panel, and requestForNewDiagram().
Referenced by ElementsPanelWidget().
openDirectoryForSelectedItem
void ElementsPanelWidget::openDirectoryForSelectedItem () slot
Require the desktop environment to open the directory containing the file represented by the selected item, if any.
Definition at line 127 of file elementspanelwidget.cpp.
References elements_panel.
Referenced by ElementsPanelWidget().
reloadAndFilter
void ElementsPanelWidget::reloadAndFilter () slot
Recharge le panel d'elements
Definition at line 153 of file elementspanelwidget.cpp.
References elements_panel, and filter_textfield.
Referenced by QETDiagramEditor::reloadOldElementPanel().
removeTitleBlockTemplate
void ElementsPanelWidget::removeTitleBlockTemplate () slot
Delete the currently selected title block template, if any.
Definition at line 293 of file elementspanelwidget.cpp.
References elements_panel, TitleBlockTemplateDeleter::exec(), and QET::TitleBlockTemplate.
Referenced by ElementsPanelWidget().
requestForDiagram
void ElementsPanelWidget::requestForDiagram (Diagram *) signal
Referenced by ElementsPanelWidget().
requestForDiagramDeletion
void ElementsPanelWidget::requestForDiagramDeletion (Diagram *) signal
Referenced by deleteDiagram(), and keyPressEvent().
requestForDiagramMoveDown
void ElementsPanelWidget::requestForDiagramMoveDown (Diagram *) signal
Referenced by keyPressEvent(), and moveDiagramDown().
requestForDiagramMoveDownx10
void ElementsPanelWidget::requestForDiagramMoveDownx10 (Diagram *) signal
Referenced by moveDiagramDownx10().
requestForDiagramMoveUp
void ElementsPanelWidget::requestForDiagramMoveUp (Diagram *) signal
Referenced by keyPressEvent(), and moveDiagramUp().
requestForDiagramMoveUpTop
void ElementsPanelWidget::requestForDiagramMoveUpTop (Diagram *) signal
Referenced by keyPressEvent(), and moveDiagramUpTop().
requestForDiagramMoveUpx10
void ElementsPanelWidget::requestForDiagramMoveUpx10 (Diagram *) signal
Referenced by moveDiagramUpx10().
requestForDiagramPropertiesEdition
void ElementsPanelWidget::requestForDiagramPropertiesEdition (Diagram *) signal
Referenced by editDiagramProperties().
requestForNewDiagram
void ElementsPanelWidget::requestForNewDiagram (QETProject *) signal
Referenced by newDiagram().
requestForProject
void ElementsPanelWidget::requestForProject (QETProject *) signal
Referenced by activateProject().
requestForProjectClosing
void ElementsPanelWidget::requestForProjectClosing (QETProject *) signal
Referenced by closeProject().
requestForProjectPropertiesEdition
void ElementsPanelWidget::requestForProjectPropertiesEdition (QETProject *) signal
Referenced by editProjectProperties().
updateButtons
void ElementsPanelWidget::updateButtons () slot
Met a jour les boutons afin d'assurer la coherence de l'interface
Definition at line 306 of file elementspanelwidget.cpp.
References QET::Diagram, elements_panel, TitleBlockTemplateLocation::isReadOnly(), TitleBlockTemplateLocation::parentCollection(), prj_add_diagram, prj_del_diagram, prj_move_diagram_down, prj_move_diagram_downx10, prj_move_diagram_top, prj_move_diagram_up, prj_move_diagram_upx10, QET::Project, tbt_add, tbt_edit, tbt_remove, QET::TitleBlockTemplate, and QET::TitleBlockTemplatesCollection.
Referenced by ElementsPanelWidget(), and handleContextMenu().
Member Data Documentation
context_menu
QMenu* ElementsPanelWidget::context_menu private
Definition at line 56 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), and handleContextMenu().
copy_path
QAction * ElementsPanelWidget::copy_path private
Definition at line 43 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), and handleContextMenu().
elements_panel
ElementsPanel* ElementsPanelWidget::elements_panel private
Definition at line 42 of file elementspanelwidget.h.
Referenced by activateProject(), addTitleBlockTemplate(), closeProject(), copyPathForSelectedItem(), deleteDiagram(), editDiagramProperties(), editProjectProperties(), editTitleBlockTemplate(), elementsPanel(), ElementsPanelWidget(), filterEdited(), handleContextMenu(), keyPressEvent(), moveDiagramDown(), moveDiagramDownx10(), moveDiagramUp(), moveDiagramUpTop(), moveDiagramUpx10(), newDiagram(), openDirectoryForSelectedItem(), reloadAndFilter(), removeTitleBlockTemplate(), and updateButtons().
filter_textfield
QLineEdit* ElementsPanelWidget::filter_textfield private
Definition at line 57 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), and reloadAndFilter().
open_directory
QAction* ElementsPanelWidget::open_directory private
Definition at line 43 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), and handleContextMenu().
previous_filter_
QString ElementsPanelWidget::previous_filter_ private
Definition at line 103 of file elementspanelwidget.h.
Referenced by filterEdited().
prj_activate
QAction* ElementsPanelWidget::prj_activate private
Definition at line 44 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), and handleContextMenu().
prj_add_diagram
QAction * ElementsPanelWidget::prj_add_diagram private
Definition at line 48 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
prj_close
QAction * ElementsPanelWidget::prj_close private
Definition at line 45 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), and handleContextMenu().
prj_del_diagram
QAction * ElementsPanelWidget::prj_del_diagram private
Definition at line 49 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
prj_edit_prop
QAction * ElementsPanelWidget::prj_edit_prop private
Definition at line 46 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), and handleContextMenu().
prj_move_diagram_down
QAction * ElementsPanelWidget::prj_move_diagram_down private
Definition at line 52 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
prj_move_diagram_downx10
QAction * ElementsPanelWidget::prj_move_diagram_downx10 private
Definition at line 54 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
prj_move_diagram_top
QAction * ElementsPanelWidget::prj_move_diagram_top private
Definition at line 51 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
prj_move_diagram_up
QAction * ElementsPanelWidget::prj_move_diagram_up private
Definition at line 50 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
prj_move_diagram_upx10
QAction * ElementsPanelWidget::prj_move_diagram_upx10 private
Definition at line 53 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
prj_prop_diagram
QAction * ElementsPanelWidget::prj_prop_diagram private
Definition at line 47 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), and handleContextMenu().
tbt_add
QAction* ElementsPanelWidget::tbt_add private
Definition at line 55 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
tbt_edit
QAction * ElementsPanelWidget::tbt_edit private
Definition at line 55 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
tbt_remove
QAction * ElementsPanelWidget::tbt_remove private
Definition at line 55 of file elementspanelwidget.h.
Referenced by ElementsPanelWidget(), handleContextMenu(), and updateButtons().
The documentation for this class was generated from the following files:
elementspanelwidget.h
elementspanelwidget.cpp