QElectroTech: QETInformation Namespace Reference
QETInformation Namespace Reference
Functions
QStringList titleblockInfoKeys ()
QETInformation::titleblockInfoKeys.
QString titleblockTranslatedInfoKey (const QString &info)
QETInformation::titleblockTranslatedInfoKey.
QString titleblockInfoKeysToVar (const QString &info)
QETInformation::titleblockInfoKeysToVar.
QHash< QString, QString > titleblockTranslatedKeyHashVar ()
QETInformation::titleblockTranslatedKeyHashVar.
Function Documentation
titleblockInfoKeys()
QStringList QETInformation::titleblockInfoKeys ()
QETInformation::titleblockInfoKeys.
Returns
all available key for use with a titleblock
Definition at line 27 of file qetinformation.cpp.
Referenced by titleblockTranslatedKeyHashVar().
titleblockInfoKeysToVar()
QString QETInformation::titleblockInfoKeysToVar (const QString & info)
QETInformation::titleblockInfoKeysToVar.
Parameters
info
Returns
var in form %{my-var} corresponding to the info. if there is not available var for the given info, the returned var is %{void}
Definition at line 91 of file qetinformation.cpp.
Referenced by titleblockTranslatedKeyHashVar().
titleblockTranslatedInfoKey()
QString QETInformation::titleblockTranslatedInfoKey (const QString & info)
QETInformation::titleblockTranslatedInfoKey.
Parameters
info : info key to be translated
Returns
the translated information given by info If info don't match, return an empty string
Definition at line 60 of file qetinformation.cpp.
References QET::Icons::tr.
Referenced by titleblockTranslatedKeyHashVar().
titleblockTranslatedKeyHashVar()
QHash< QString, QString > QETInformation::titleblockTranslatedKeyHashVar ()
QETInformation::titleblockTranslatedKeyHashVar.
Returns
a QHash with for key, the translated information key of title block, and for value the corresponding var.
Definition at line 121 of file qetinformation.cpp.
References titleblockInfoKeys(), titleblockInfoKeysToVar(), and titleblockTranslatedInfoKey().
Referenced by TitleBlockTemplateCellWidget::editTranslatableValue().