QElectroTech: qdesigner_internal::HtmlTextEdit Class Reference
qdesigner_internal::HtmlTextEdit Class Reference
Public Member Functions
HtmlTextEdit (QWidget *parent=nullptr)
void contextMenuEvent (QContextMenuEvent *event) override
Private Slots
void actionTriggered (QAction *action)
Detailed Description
Definition at line 312 of file richtexteditor.cpp.
Constructor & Destructor Documentation
HtmlTextEdit()
qdesigner_internal::HtmlTextEdit::HtmlTextEdit (QWidget * parent = nullptr) inline
Definition at line 317 of file richtexteditor.cpp.
Member Function Documentation
actionTriggered
void qdesigner_internal::HtmlTextEdit::actionTriggered (QAction * action) private slot
Definition at line 360 of file richtexteditor.cpp.
contextMenuEvent()
void qdesigner_internal::HtmlTextEdit::contextMenuEvent (QContextMenuEvent * event) override
Definition at line 327 of file richtexteditor.cpp.
References qdesigner_internal::ColorAction::chooseColor(), qdesigner_internal::ColorAction::color(), qdesigner_internal::ColorAction::ColorAction(), qdesigner_internal::ColorAction::colorChanged(), qdesigner_internal::ColorAction::m_color, and qdesigner_internal::ColorAction::setColor().
The documentation for this class was generated from the following file:
richtexteditor.cpp