QElectroTech: ECHSFileToFile Class Reference
ECHSFileToFile Class Reference
The ECHSFileToFile class Manage the copy of directory or element from a file system collection to another file system collection.
#include <elementcollectionhandler.h>
Public Member Functions
ECHSFileToFile (ElementsLocation &source, ElementsLocation &destination)
ElementsLocation copy () override
Public Member Functions inherited from ECHStrategy
ECHStrategy (ElementsLocation &source, ElementsLocation &destination)
virtual ~ECHStrategy ()
Private Member Functions
ElementsLocation copyDirectory (ElementsLocation &source, ElementsLocation &destination, const QString &rename=QString())
ElementsLocation copyElement (ElementsLocation &source, ElementsLocation &destination, const QString &rename=QString())
Additional Inherited Members
Public Attributes inherited from ECHStrategy
ElementsLocation m_source
ElementsLocation m_destination
Detailed Description
The ECHSFileToFile class Manage the copy of directory or element from a file system collection to another file system collection.
Definition at line 47 of file elementcollectionhandler.h.
Constructor & Destructor Documentation
ECHSFileToFile()
ECHSFileToFile::ECHSFileToFile (ElementsLocation & source, ElementsLocation & destination)
Definition at line 38 of file elementcollectionhandler.cpp.
Member Function Documentation
copy()
ElementsLocation ECHSFileToFile::copy () override virtual
Implements ECHStrategy.
Definition at line 42 of file elementcollectionhandler.cpp.
References copyDirectory(), copyElement(), QET::Erase, ElementsLocation::exist(), ElementsLocation::fileName(), ElementsLocation::fileSystemPath(), ElementsLocation::isDirectory(), ElementsLocation::isElement(), ECHStrategy::m_destination, ECHStrategy::m_source, RenameDialog::newName(), QET::Rename, and RenameDialog::selectedAction().
copyDirectory()
ElementsLocation ECHSFileToFile::copyDirectory (ElementsLocation & source, ElementsLocation & destination, const QString & rename = QString()) private
Definition at line 80 of file elementcollectionhandler.cpp.
References copyElement(), and ElementsLocation::fileSystemPath().
Referenced by copy().
copyElement()
ElementsLocation ECHSFileToFile::copyElement (ElementsLocation & source, ElementsLocation & destination, const QString & rename = QString()) private
Definition at line 134 of file elementcollectionhandler.cpp.
References ElementsLocation::fileName(), and ElementsLocation::fileSystemPath().
Referenced by copy(), and copyDirectory().
The documentation for this class was generated from the following files:
elementcollectionhandler.h
elementcollectionhandler.cpp