QElectroTech: ElementsCollectionWidget Class Reference
ElementsCollectionWidget Class Reference
The ElementsCollectionWidget class This widget embedd a tree view that display the element collection (common, custom, embedded) and all action needed to use this widget. This is the element collection widget used in the diagram editor.
#include <elementscollectionwidget.h>
Public Slots
void reload ()
ElementsCollectionWidget::reload, the displayed collections.
void loadingFinished ()
ElementsCollectionWidget::loadingFinished Process when collection finished to be loaded.
Public Member Functions
ElementsCollectionWidget (QWidget *parent=nullptr)
ElementsCollectionWidget::ElementsCollectionWidget Default constructor.
void expandFirstItems ()
ElementsCollectionWidget::expandFirstItems Expand each first item in the tree view.
void addProject (QETProject *project)
ElementsCollectionWidget::addProject Add project to be displayed.
void removeProject (QETProject *project)
void highlightUnusedElement ()
ElementsCollectionWidget::highlightUnusedElement highlight the unused element.
void setCurrentLocation (const ElementsLocation &location)
ElementsCollectionWidget::setCurrentLocation Set the current item to be the item for location.
Protected Member Functions
void leaveEvent (QEvent *event) override
Private Member Functions
void setUpAction ()
void setUpWidget ()
ElementsCollectionWidget::setUpWidget Setup this widget.
void setUpConnection ()
ElementsCollectionWidget::setUpConnection Setup the connection used in this widget.
void customContextMenu (const QPoint &point)
ElementsCollectionWidget::customContextMenu Display the context menu of this widget at point.
void openDir ()
ElementsCollectionWidget::openDir Open the directory represented by the current selected item.
void editElement ()
ElementsCollectionWidget::editElement Edit the element represented by the current selected item.
void deleteElement ()
ElementsCollectionWidget::deleteElement Delete the element represented by the current selected item.
void deleteDirectory ()
ElementsCollectionWidget::deleteDirectory Delete directory represented by the current selected item.
void editDirectory ()
ElementsCollectionWidget::editDirectory Edit the directory represented by the current selected item.
void newDirectory ()
ElementsCollectionWidget::newDirectory Create a new directory.
void newElement ()
ElementsCollectionWidget::newElement Create a new element.
void showThisDir ()
ElementsCollectionWidget::showThisDir Hide all directories except the pointed dir;.
void resetShowThisDir ()
ElementsCollectionWidget::resetShowThisDir reset show this dir, all collection are show. If search field isn't empty, apply the search after show all collection.
void dirProperties ()
ElementsCollectionWidget::dirProperties Open an informative dialog about the curent index.
void search ()
ElementsCollectionWidget::search Search every item (directory or element) that match the text of m_search_field and display it, other item who does not match text is hidden.
void hideCollection (bool hide=true)
ElementsCollectionWidget::hideCollection Hide all collection displayed in this tree.
void hideItem (bool hide, const QModelIndex &index=QModelIndex(), bool recursive=true)
ElementsCollectionWidget::hideItem Hide the item index. If recursive is true, hide all subchilds of index.
void showAndExpandItem (const QModelIndex &index, bool parent=true, bool child=false)
ElementsCollectionWidget::showAndExpandItem Show the item index and expand it. If parent is true, ensure parents of index is show and expanded If child is true, ensure all childs of index is show and expended.
ElementCollectionItem * elementCollectionItemForIndex (const QModelIndex &index)
ElementsCollectionWidget::elementCollectionItemForIndex.
void locationWasSaved (const ElementsLocation &location)
ElementsCollectionWidget::locationWasSaved This method is connected with the signal savedToLocation of Element editor (see ElementsCollectionWidget::editElement()) Update or add the item represented by location to m_model.
Private Attributes
ElementsCollectionModel * m_model = nullptr
ElementsCollectionModel * m_new_model = nullptr
QLineEdit * m_search_field
QTimer m_search_timer
ElementsTreeView * m_tree_view
QVBoxLayout * m_main_vlayout
QMenu * m_context_menu
QModelIndex m_index_at_context_menu
QModelIndex m_showed_index
QProgressBar * m_progress_bar
QAction * m_open_dir
QAction * m_edit_element
QAction * m_delete_element
QAction * m_delete_dir
QAction * m_reload
QAction * m_edit_dir
QAction * m_new_directory
QAction * m_new_element
QAction * m_show_this_dir
QAction * m_show_all_dir
QAction * m_dir_propertie
bool m_first_show = true
QList< QETProject * > m_waiting_project
Detailed Description
The ElementsCollectionWidget class This widget embedd a tree view that display the element collection (common, custom, embedded) and all action needed to use this widget. This is the element collection widget used in the diagram editor.
Definition at line 42 of file elementscollectionwidget.h.
Constructor & Destructor Documentation
ElementsCollectionWidget()
ElementsCollectionWidget::ElementsCollectionWidget (QWidget * parent = nullptr)
ElementsCollectionWidget::ElementsCollectionWidget Default constructor.
Parameters
parent : parent widget of this widget.
Definition at line 45 of file elementscollectionwidget.cpp.
References m_search_timer, setUpAction(), setUpConnection(), and setUpWidget().
Member Function Documentation
addProject()
void ElementsCollectionWidget::addProject (QETProject * project)
ElementsCollectionWidget::addProject Add project to be displayed.
Parameters
project
Definition at line 87 of file elementscollectionwidget.cpp.
References ElementsCollectionModel::loadCollections(), m_model, m_progress_bar, m_tree_view, and m_waiting_project.
Referenced by QETDiagramEditor::addProject().
customContextMenu()
void ElementsCollectionWidget::customContextMenu (const QPoint & point) private
ElementsCollectionWidget::customContextMenu Display the context menu of this widget at point.
Parameters
point
Definition at line 261 of file elementscollectionwidget.cpp.
References elementCollectionItemForIndex(), XmlProjectElementCollectionItem::isCollectionRoot(), FileElementCollectionItem::isCollectionRoot(), FileElementCollectionItem::isCommonCollection(), ElementCollectionItem::isDir(), FileElementCollectionItem::isDir(), ElementCollectionItem::isElement(), m_context_menu, m_delete_dir, m_delete_element, m_dir_propertie, m_edit_dir, m_edit_element, m_index_at_context_menu, m_new_directory, m_new_element, m_open_dir, m_reload, m_show_all_dir, m_show_this_dir, m_showed_index, m_tree_view, FileElementCollectionItem::Type, ElementCollectionItem::type(), and XmlProjectElementCollectionItem::Type.
Referenced by setUpConnection().
deleteDirectory()
void ElementsCollectionWidget::deleteDirectory () private
ElementsCollectionWidget::deleteDirectory Delete directory represented by the current selected item.
Definition at line 417 of file elementscollectionwidget.cpp.
References ElementCollectionItem::collectionPath(), ElementsLocation::collectionPath(), elementCollectionItemForIndex(), ElementsLocation::exist(), ElementsLocation::fileSystemPath(), ElementsLocation::isDirectory(), ElementsLocation::isFileSystem(), m_index_at_context_menu, m_model, QET::QetMessageBox::question(), QET::Icons::tr, and QET::QetMessageBox::warning().
Referenced by setUpConnection().
deleteElement()
void ElementsCollectionWidget::deleteElement () private
ElementsCollectionWidget::deleteElement Delete the element represented by the current selected item.
Definition at line 374 of file elementscollectionwidget.cpp.
References ElementCollectionItem::collectionPath(), ElementsLocation::collectionPath(), elementCollectionItemForIndex(), ElementsLocation::exist(), ElementsLocation::fileSystemPath(), ElementsLocation::isElement(), ElementsLocation::isFileSystem(), m_index_at_context_menu, m_model, QET::QetMessageBox::question(), QET::Icons::tr, and QET::QetMessageBox::warning().
Referenced by setUpConnection().
dirProperties()
void ElementsCollectionWidget::dirProperties () private
ElementsCollectionWidget::dirProperties Open an informative dialog about the curent index.
Definition at line 585 of file elementscollectionwidget.cpp.
References ElementCollectionItem::collectionPath(), ElementCollectionItem::directoriesChild(), elementCollectionItemForIndex(), ElementCollectionItem::elementsChild(), QET::QetMessageBox::information(), ElementCollectionItem::isDir(), ElementCollectionItem::localName(), m_index_at_context_menu, QET::Icons::tr, FileElementCollectionItem::Type, and ElementCollectionItem::type().
Referenced by setUpConnection().
editDirectory()
void ElementsCollectionWidget::editDirectory () private
ElementsCollectionWidget::editDirectory Edit the directory represented by the current selected item.
Definition at line 461 of file elementscollectionwidget.cpp.
References ElementCollectionItem::clearData(), FileElementCollectionItem::collectionPath(), elementCollectionItemForIndex(), FileElementCollectionItem::isCommonCollection(), m_index_at_context_menu, FileElementCollectionItem::Type, and ElementCollectionItem::type().
Referenced by setUpConnection().
editElement()
void ElementsCollectionWidget::editElement () private
ElementsCollectionWidget::editElement Edit the element represented by the current selected item.
Definition at line 352 of file elementscollectionwidget.cpp.
References ElementCollectionItem::collectionPath(), elementCollectionItemForIndex(), QETApp::elementEditors(), QETApp::instance(), ElementCollectionItem::isElement(), locationWasSaved(), m_index_at_context_menu, QETApp::openElementLocations(), and QETElementEditor::saveToLocation().
Referenced by setUpConnection().
elementCollectionItemForIndex()
ElementCollectionItem * ElementsCollectionWidget::elementCollectionItemForIndex (const QModelIndex & index) private
ElementsCollectionWidget::elementCollectionItemForIndex.
Parameters
index
Returns
The internal pointer of index casted to ElementCollectionItem;
Definition at line 819 of file elementscollectionwidget.cpp.
References m_model.
Referenced by customContextMenu(), deleteDirectory(), deleteElement(), dirProperties(), editDirectory(), editElement(), newDirectory(), newElement(), openDir(), resetShowThisDir(), setUpConnection(), and showThisDir().
expandFirstItems()
void ElementsCollectionWidget::expandFirstItems ()
ElementsCollectionWidget::expandFirstItems Expand each first item in the tree view.
Definition at line 73 of file elementscollectionwidget.cpp.
References m_model, and showAndExpandItem().
Referenced by loadingFinished(), search(), and QETDiagramEditor::setUpElementsCollectionWidget().
hideCollection()
void ElementsCollectionWidget::hideCollection (bool hide = true) private
ElementsCollectionWidget::hideCollection Hide all collection displayed in this tree.
Parameters
hide- true = hide , false = visible
Definition at line 767 of file elementscollectionwidget.cpp.
References hideItem(), and m_model.
Referenced by search(), and showThisDir().
hideItem()
void ElementsCollectionWidget::hideItem (bool hide, const QModelIndex & index = QModelIndex(), bool recursive = true) private
ElementsCollectionWidget::hideItem Hide the item index. If recursive is true, hide all subchilds of index.
Parameters
hide : - true = hide , false = visible
index : - index to hide
recursive : - true = apply to child , false = only for index
Definition at line 781 of file elementscollectionwidget.cpp.
References m_model, and m_tree_view.
Referenced by hideCollection(), and showAndExpandItem().
highlightUnusedElement()
void ElementsCollectionWidget::highlightUnusedElement ()
ElementsCollectionWidget::highlightUnusedElement highlight the unused element.
See also
ElementsCollectionModel::highlightUnusedElement()
Definition at line 111 of file elementscollectionwidget.cpp.
References ElementsCollectionModel::highlightUnusedElement(), and m_model.
Referenced by QETDiagramEditor::save(), and QETDiagramEditor::saveAs().
leaveEvent()
void ElementsCollectionWidget::leaveEvent (QEvent * event) override protected
Definition at line 133 of file elementscollectionwidget.cpp.
References QETApp::diagramEditorAncestorOf().
loadingFinished
void ElementsCollectionWidget::loadingFinished () slot
ElementsCollectionWidget::loadingFinished Process when collection finished to be loaded.
Definition at line 656 of file elementscollectionwidget.cpp.
References expandFirstItems(), ElementsCollectionModel::highlightUnusedElement(), m_index_at_context_menu, m_model, m_new_model, m_progress_bar, m_showed_index, and m_tree_view.
Referenced by reload().
locationWasSaved()
void ElementsCollectionWidget::locationWasSaved (const ElementsLocation & location) private
ElementsCollectionWidget::locationWasSaved This method is connected with the signal savedToLocation of Element editor (see ElementsCollectionWidget::editElement()) Update or add the item represented by location to m_model.
Parameters
location
Definition at line 684 of file elementscollectionwidget.cpp.
References ElementsCollectionModel::addLocation(), ElementsLocation::exist(), ElementsCollectionModel::indexFromLocation(), m_model, and setUpData().
Referenced by editElement(), and newElement().
newDirectory()
void ElementsCollectionWidget::newDirectory () private
ElementsCollectionWidget::newDirectory Create a new directory.
Definition at line 483 of file elementscollectionwidget.cpp.
References ElementsCollectionModel::addLocation(), FileElementCollectionItem::collectionPath(), ElementsCategoryEditor::createdLocation(), elementCollectionItemForIndex(), FileElementCollectionItem::isCommonCollection(), m_index_at_context_menu, m_model, FileElementCollectionItem::Type, and ElementCollectionItem::type().
Referenced by setUpConnection().
newElement()
void ElementsCollectionWidget::newElement () private
ElementsCollectionWidget::newElement Create a new element.
Definition at line 504 of file elementscollectionwidget.cpp.
References FileElementCollectionItem::collectionPath(), elementCollectionItemForIndex(), QETApp::instance(), FileElementCollectionItem::isCommonCollection(), locationWasSaved(), m_index_at_context_menu, NewElementWizard::preselectedLocation(), QETElementEditor::saveToLocation(), FileElementCollectionItem::Type, and ElementCollectionItem::type().
Referenced by setUpConnection().
openDir()
void ElementsCollectionWidget::openDir () private
ElementsCollectionWidget::openDir Open the directory represented by the current selected item.
Definition at line 325 of file elementscollectionwidget.cpp.
References elementCollectionItemForIndex(), m_index_at_context_menu, FileElementCollectionItem::Type, ElementCollectionItem::type(), and XmlProjectElementCollectionItem::Type.
Referenced by setUpConnection().
reload
void ElementsCollectionWidget::reload () slot
ElementsCollectionWidget::reload, the displayed collections.
Definition at line 615 of file elementscollectionwidget.cpp.
References ElementsCollectionModel::loadCollections(), ElementsCollectionModel::loadingFinished(), loadingFinished(), ElementsCollectionModel::loadingProgressRangeChanged(), ElementsCollectionModel::loadingProgressValueChanged(), m_model, m_new_model, m_progress_bar, m_tree_view, m_waiting_project, and ElementsCollectionModel::project().
Referenced by setUpConnection().
removeProject()
void ElementsCollectionWidget::removeProject (QETProject * project)
Definition at line 101 of file elementscollectionwidget.cpp.
References m_model, and ElementsCollectionModel::removeProject().
Referenced by QETDiagramEditor::projectWasClosed().
resetShowThisDir()
void ElementsCollectionWidget::resetShowThisDir () private
ElementsCollectionWidget::resetShowThisDir reset show this dir, all collection are show. If search field isn't empty, apply the search after show all collection.
Definition at line 567 of file elementscollectionwidget.cpp.
References elementCollectionItemForIndex(), m_showed_index, and search().
Referenced by setUpConnection(), and showThisDir().
search()
void ElementsCollectionWidget::search () private
ElementsCollectionWidget::search Search every item (directory or element) that match the text of m_search_field and display it, other item who does not match text is hidden.
Definition at line 712 of file elementscollectionwidget.cpp.
References expandFirstItems(), hideCollection(), m_model, m_search_field, m_showed_index, m_tree_view, and showAndExpandItem().
Referenced by resetShowThisDir(), setUpConnection(), and showThisDir().
setCurrentLocation()
void ElementsCollectionWidget::setCurrentLocation (const ElementsLocation & location)
ElementsCollectionWidget::setCurrentLocation Set the current item to be the item for location.
Parameters
location
Definition at line 122 of file elementscollectionwidget.cpp.
References ElementsLocation::exist(), ElementsCollectionModel::indexFromLocation(), m_model, and m_tree_view.
Referenced by QETDiagramEditor::findElementInPanel().
setUpAction()
void ElementsCollectionWidget::setUpAction () private
Definition at line 141 of file elementscollectionwidget.cpp.
References QET::Icons::ElementDelete, QET::Icons::ElementEdit, QET::Icons::ElementNew, QET::Icons::FolderDelete, QET::Icons::FolderEdit, QET::Icons::FolderNew, QET::Icons::FolderOnlyThis, QET::Icons::FolderOpen, QET::Icons::FolderProperties, QET::Icons::FolderShowAll, m_delete_dir, m_delete_element, m_dir_propertie, m_edit_dir, m_edit_element, m_new_directory, m_new_element, m_open_dir, m_reload, m_show_all_dir, m_show_this_dir, QET::Icons::tr, and QET::Icons::ViewRefresh.
Referenced by ElementsCollectionWidget().
setUpConnection()
void ElementsCollectionWidget::setUpConnection () private
ElementsCollectionWidget::setUpConnection Setup the connection used in this widget.
Definition at line 209 of file elementscollectionwidget.cpp.
References customContextMenu(), deleteDirectory(), deleteElement(), QETApp::diagramEditorAncestorOf(), dirProperties(), editDirectory(), editElement(), elementCollectionItemForIndex(), ElementCollectionItem::localName(), m_delete_dir, m_delete_element, m_dir_propertie, m_edit_dir, m_edit_element, m_index_at_context_menu, m_new_directory, m_new_element, m_open_dir, m_reload, m_search_field, m_search_timer, m_show_all_dir, m_show_this_dir, m_tree_view, newDirectory(), newElement(), openDir(), reload(), resetShowThisDir(), search(), and showThisDir().
Referenced by ElementsCollectionWidget().
setUpWidget()
void ElementsCollectionWidget::setUpWidget () private
ElementsCollectionWidget::setUpWidget Setup this widget.
Definition at line 172 of file elementscollectionwidget.cpp.
References m_context_menu, m_main_vlayout, m_progress_bar, m_search_field, m_tree_view, and QET::Icons::tr.
Referenced by ElementsCollectionWidget().
showAndExpandItem()
void ElementsCollectionWidget::showAndExpandItem (const QModelIndex & index, bool parent = true, bool child = false) private
ElementsCollectionWidget::showAndExpandItem Show the item index and expand it. If parent is true, ensure parents of index is show and expanded If child is true, ensure all childs of index is show and expended.
Parameters
index- index to show
parent- Apply to parent
child- Apply to all childs
Definition at line 801 of file elementscollectionwidget.cpp.
References hideItem(), and m_tree_view.
Referenced by expandFirstItems(), search(), and showThisDir().
showThisDir()
void ElementsCollectionWidget::showThisDir () private
ElementsCollectionWidget::showThisDir Hide all directories except the pointed dir;.
Definition at line 536 of file elementscollectionwidget.cpp.
References elementCollectionItemForIndex(), hideCollection(), m_index_at_context_menu, m_showed_index, resetShowThisDir(), search(), and showAndExpandItem().
Referenced by setUpConnection().
Member Data Documentation
m_context_menu
QMenu* ElementsCollectionWidget::m_context_menu private
Definition at line 95 of file elementscollectionwidget.h.
Referenced by customContextMenu(), and setUpWidget().
m_delete_dir
QAction * ElementsCollectionWidget::m_delete_dir private
Definition at line 103 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_delete_element
QAction * ElementsCollectionWidget::m_delete_element private
Definition at line 102 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_dir_propertie
QAction * ElementsCollectionWidget::m_dir_propertie private
Definition at line 110 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_edit_dir
QAction * ElementsCollectionWidget::m_edit_dir private
Definition at line 105 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_edit_element
QAction * ElementsCollectionWidget::m_edit_element private
Definition at line 101 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_first_show
bool ElementsCollectionWidget::m_first_show = true private
Definition at line 112 of file elementscollectionwidget.h.
m_index_at_context_menu
QModelIndex ElementsCollectionWidget::m_index_at_context_menu private
Definition at line 96 of file elementscollectionwidget.h.
Referenced by customContextMenu(), deleteDirectory(), deleteElement(), dirProperties(), editDirectory(), editElement(), loadingFinished(), newDirectory(), newElement(), openDir(), setUpConnection(), and showThisDir().
m_main_vlayout
QVBoxLayout* ElementsCollectionWidget::m_main_vlayout private
Definition at line 94 of file elementscollectionwidget.h.
Referenced by setUpWidget().
m_model
ElementsCollectionModel* ElementsCollectionWidget::m_model = nullptr private
Definition at line 89 of file elementscollectionwidget.h.
Referenced by addProject(), deleteDirectory(), deleteElement(), elementCollectionItemForIndex(), expandFirstItems(), hideCollection(), hideItem(), highlightUnusedElement(), loadingFinished(), locationWasSaved(), newDirectory(), reload(), removeProject(), search(), and setCurrentLocation().
m_new_directory
QAction * ElementsCollectionWidget::m_new_directory private
Definition at line 106 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_new_element
QAction * ElementsCollectionWidget::m_new_element private
Definition at line 107 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_new_model
ElementsCollectionModel* ElementsCollectionWidget::m_new_model = nullptr private
Definition at line 90 of file elementscollectionwidget.h.
Referenced by loadingFinished(), and reload().
m_open_dir
QAction* ElementsCollectionWidget::m_open_dir private
Definition at line 100 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_progress_bar
QProgressBar* ElementsCollectionWidget::m_progress_bar private
Definition at line 98 of file elementscollectionwidget.h.
Referenced by addProject(), loadingFinished(), reload(), and setUpWidget().
m_reload
QAction * ElementsCollectionWidget::m_reload private
Definition at line 104 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_search_field
QLineEdit* ElementsCollectionWidget::m_search_field private
Definition at line 91 of file elementscollectionwidget.h.
Referenced by search(), setUpConnection(), and setUpWidget().
m_search_timer
QTimer ElementsCollectionWidget::m_search_timer private
Definition at line 92 of file elementscollectionwidget.h.
Referenced by ElementsCollectionWidget(), and setUpConnection().
m_show_all_dir
QAction * ElementsCollectionWidget::m_show_all_dir private
Definition at line 109 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_show_this_dir
QAction * ElementsCollectionWidget::m_show_this_dir private
Definition at line 108 of file elementscollectionwidget.h.
Referenced by customContextMenu(), setUpAction(), and setUpConnection().
m_showed_index
QModelIndex ElementsCollectionWidget::m_showed_index private
Definition at line 97 of file elementscollectionwidget.h.
Referenced by customContextMenu(), loadingFinished(), resetShowThisDir(), search(), and showThisDir().
m_tree_view
ElementsTreeView* ElementsCollectionWidget::m_tree_view private
Definition at line 93 of file elementscollectionwidget.h.
Referenced by addProject(), customContextMenu(), hideItem(), loadingFinished(), reload(), search(), setCurrentLocation(), setUpConnection(), setUpWidget(), and showAndExpandItem().
m_waiting_project
QList<QETProject *> ElementsCollectionWidget::m_waiting_project private
Definition at line 113 of file elementscollectionwidget.h.
Referenced by addProject(), and reload().
The documentation for this class was generated from the following files:
elementscollectionwidget.h
elementscollectionwidget.cpp