QElectroTech: Conductor Class Reference
Conductor Class Reference
#include <conductor.h>
Public Types
enum { Type = UserType + 1001 }
enum Highlight { None, Normal, Alert }
Public Slots
void displayedTextChanged ()
Conductor::displayedTextChanged Update the properties (text) of this conductor and other conductors at the same potential of this conductor.
Signals
void propertiesChange ()
Public Member Functions
Conductor (Terminal *, Terminal *)
Conductor::Conductor Default constructor.
~Conductor () override
Conductor::~Conductor Destructor. The conductor is removed from is terminal.
bool isValid () const
Conductor::isValid.
int type () const override
type Enable the use of qgraphicsitem_cast to safely cast a QGraphicsItem into a conductor.
Diagram * diagram () const
ConductorTextItem * textItem () const
void updatePath (const QRectF &=QRectF())
void updatePathAnimate (const int=1)
int fakePath ()
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *) override
QRectF boundingRect () const override
Conductor::boundingRect.
QPainterPath shape () const override
Conductor::shape.
virtual QPainterPath nearShape () const
Conductor::nearShape.
qreal length () const
Conductor::length.
ConductorSegment * middleSegment ()
QPointF posForText (Qt::Orientations &flag)
Conductor::posForText Calculate and return the better pos for text.
void refreshText ()
Conductor::refreshText Refresh the text of this conductor. recalcule and set the text according to the formula.
void setPath (const QPainterPath &path)
QPainterPath path () const
bool fromXml (QDomElement &)
Conductor::fromXml Load the conductor and her information from xml element.
QDomElement toXml (QDomDocument &, QHash< Terminal *, int > &) const
Conductor::toXml Exporte les caracteristiques du conducteur sous forme d'une element XML.
QVector< QPointF > handlerPoints () const
Conductor::handlerPoints.
const QList< ConductorSegment * > segmentsList () const
void setPropertyToPotential (const ConductorProperties &property, bool only_text=false)
Conductor::setPropertiesToPotential.
void setProperties (const ConductorProperties &property)
Conductor::setProperties Set property as current property of conductor.
ConductorProperties properties () const
Conductor::properties.
void setProfile (const ConductorProfile &, Qt::Corner)
ConductorProfile profile (Qt::Corner) const
void setProfiles (const ConductorProfilesGroup &)
Conductor::setProfiles.
ConductorProfilesGroup profiles () const
void calculateTextItemPosition ()
Conductor::calculateTextItemPosition Move the text at middle of conductor (if is vertical or horizontal) otherwise, move conductor at the middle of the longest segment of conductor. If text was moved by user, this function do nothing, except check if text is near conductor.
virtual Highlight highlight () const
virtual void setHighlighted (Highlight)
QSet< Conductor * > relatedPotentialConductors (const bool all_diagram=true, QList< Terminal * > *t_list=nullptr)
Conductor::relatedPotentialConductors Return all conductors at the same potential of this conductor, this conductor isn't part of the returned QSet.
QETDiagramEditor * diagramEditor () const
Conductor::diagramEditor.
void editProperty ()
Conductor::editProperty.
autonum::sequentialNumbers sequenceNum () const
autonum::sequentialNumbers & rSequenceNum ()
void setSequenceNum (const autonum::sequentialNumbers &sn)
void setFreezeLabel (bool freeze)
Conductor::setFreezeLabel Freeze this conductor label if true Unfreeze this conductor label if false.
Static Public Member Functions
static bool valideXml (QDomElement &)
Public Attributes
Terminal * terminal1
Terminal * terminal2
Protected Member Functions
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
Conductor::mouseDoubleClickEvent Manage the mouse double click.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
Conductor::mousePressEvent Manage the mouse press event.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Conductor::mouseReleaseEvent.
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
Conductor::hoverEnterEvent Manage the hover enter event.
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
Conductor::hoverLeaveEvent Manage the mouse leave event.
QVariant itemChange (GraphicsItemChange, const QVariant &) override
Conductor::itemChange.
bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
Conductor::sceneEventFilter.
Properties
QPointF pos
int animPath
ConductorProperties properties
autonum::sequentialNumbers sequenceNum
Private Member Functions
Conductor (const Conductor &)
bool pathFromXml (const QDomElement &)
Conductor::pathFromXml Generate the path (of the line) from xml file by checking the segments in the xml file.
void setUpConnectionForFormula (QString old_formula, QString new_formula)
Conductor::setUpConnectionForFormula setup connection according to the variable of formula.
void adjusteHandlerPos ()
Conductor::adjusteHandlerPos Adjust the position of the handler item.
void handlerMousePressEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
Conductor::handlerMousePressEvent.
void handlerMouseMoveEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
Conductor::handlerMouseMoveEvent.
void handlerMouseReleaseEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
Conductor::handlerMouseReleaseEvent.
void addHandler ()
Conductor::addHandler Add handlers for this item.
void removeHandler ()
Conductor::removeHandler Remove the handlers of this item.
void segmentsToPath ()
Conductor::segmentsToPath Generate the QPainterPath from the list of points.
void saveProfile (bool=true)
void generateConductorPath (const QPointF &, Qet::Orientation, const QPointF &, Qet::Orientation)
void updateConductorPath (const QPointF &, Qet::Orientation, const QPointF &, Qet::Orientation)
uint segmentsCount (QET::ConductorSegmentType=QET::Both) const
QList< QPointF > segmentsToPoints () const
QList< ConductorBend > bends () const
QList< QPointF > junctions () const
void pointsToSegments (const QList< QPointF > &)
Qt::Corner currentPathType () const
void deleteSegments ()
Supprime les segments.
QHash< ConductorSegmentProfile *, qreal > shareOffsetBetweenSegments (const qreal &offset, const QList< ConductorSegmentProfile * > &, const qreal &=0.01) const
Static Private Member Functions
static int getCoeff (const qreal &, const qreal &)
static int getSign (const qreal &)
static QPointF extendTerminal (const QPointF &, Qet::Orientation, qreal=9.0)
static Qt::Corner movementType (const QPointF &, const QPointF &)
static QPointF movePointIntoPolygon (const QPointF &, const QPainterPath &)
Private Attributes
autonum::sequentialNumbers m_autoNum_seq
QVector< QetGraphicsHandlerItem * > m_handler_vector
int m_vector_index = -1
bool m_mouse_over
ConductorProperties m_properties
Functional properties.
ConductorTextItem * m_text_item
Text input for non simple, non-singleline conductors.
ConductorSegment * segments
Segments composing the conductor.
bool m_moving_segment
Attributs related to mouse interaction.
int moved_point
qreal m_previous_z_value
ConductorSegment * m_moved_segment
QPointF before_mov_text_pos_
bool modified_path
Whether the conductor was manually modified by users.
bool has_to_save_profile
Whether the current profile should be saved as soon as possible.
ConductorProfilesGroup conductor_profiles
Highlight must_highlight_
Define whether and how the conductor should be highlighted.
bool m_valid
bool m_freeze_label = false
QPainterPath m_path
Static Private Attributes
static QPen conductor_pen = QPen()
QPen et QBrush objects used to draw conductors.
static QBrush conductor_brush = QBrush()
static bool pen_and_brush_initialized = false
Detailed Description
This class represents a conductor, i.e. a wire between two element terminals.
Definition at line 42 of file conductor.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 64 of file conductor.h.
Highlight
enum Conductor::Highlight
Enumerator
None
Normal
Alert
Definition at line 65 of file conductor.h.
Constructor & Destructor Documentation
Conductor() [1/2]
Conductor::Conductor (Terminal * p1, Terminal * p2)
Conductor::Conductor Default constructor.
Parameters
p1 : first terminal of this conductor.
p2 : second terminal of this conductor.
Definition at line 77 of file conductor.cpp.
References conductor_brush, conductor_pen, conductor_profiles, Diagram::defaultConductorProperties, Terminal::diagram(), displayedTextChanged(), generateConductorPath(), m_previous_z_value, m_properties, m_text_item, m_valid, pen_and_brush_initialized, setProperties(), terminal1, terminal2, ConductorProperties::text, and DiagramTextItem::textEdited().
~Conductor()
Conductor::~Conductor () override
Conductor::~Conductor Destructor. The conductor is removed from is terminal.
Definition at line 137 of file conductor.cpp.
References deleteSegments(), Terminal::removeConductor(), removeHandler(), terminal1, and terminal2.
Conductor() [2/2]
Conductor::Conductor (const Conductor &) private
Member Function Documentation
addHandler()
void Conductor::addHandler () private
Conductor::addHandler Add handlers for this item.
Definition at line 845 of file conductor.cpp.
References QetGraphicsHandlerItem::handlerForPoint(), handlerPoints(), and m_handler_vector.
Referenced by handlerMouseReleaseEvent(), itemChange(), and segmentsToPath().
adjusteHandlerPos()
void Conductor::adjusteHandlerPos () private
Conductor::adjusteHandlerPos Adjust the position of the handler item.
Definition at line 753 of file conductor.cpp.
References handlerPoints(), and m_handler_vector.
Referenced by itemChange(), and segmentsToPath().
bends()
QList< ConductorBend > Conductor::bends () const private
Returns
la liste des bifurcations de ce conducteur ; ConductorBend est un typedef pour une QPair<QPointF, Qt::Corner>. Le point indique la position (en coordonnees locales) de la bifurcation tandis que le Corner indique le type de bifurcation.
Definition at line 1843 of file conductor.cpp.
References length(), segments, QET::Icons::sl, and type().
Referenced by junctions().
boundingRect()
QRectF Conductor::boundingRect () const override
Conductor::boundingRect.
Returns
Definition at line 878 of file conductor.cpp.
References QET::Icons::br, and shape().
Referenced by calculateTextItemPosition(), and ConductorTextItem::setPos().
calculateTextItemPosition()
void Conductor::calculateTextItemPosition ()
Conductor::calculateTextItemPosition Move the text at middle of conductor (if is vertical or horizontal) otherwise, move conductor at the middle of the longest segment of conductor. If text was moved by user, this function do nothing, except check if text is near conductor.
Definition at line 1290 of file conductor.cpp.
References boundingRect(), diagram(), ConductorProperties::horiz_rotate_text, QET::Horizontal, longuestConductorInPotential(), ConductorProperties::m_horizontal_alignment, m_properties, m_text_item, ConductorProperties::m_vertical_alignment, movePointIntoPolygon(), ConductorProperties::Multi, nearShape(), QET::Icons::Orientations, pos, posForText(), relatedPotentialConductors(), textItem(), ConductorProperties::type, ConductorProperties::verti_rotate_text, and QET::Vertical.
Referenced by Diagram::addItem(), handlerMouseMoveEvent(), itemChange(), setProfile(), setProfiles(), setProperties(), and updatePath().
currentPathType()
Qt::Corner Conductor::currentPathType () const private
Returns
le type de trajet actuel de ce conducteur
Definition at line 1911 of file conductor.cpp.
References movementType(), terminal1, and terminal2.
Referenced by saveProfile(), setProfile(), setProfiles(), updateConductorPath(), and updatePath().
deleteSegments()
void Conductor::deleteSegments () private
Supprime les segments.
Definition at line 1939 of file conductor.cpp.
References segments.
Referenced by pointsToSegments(), and ~Conductor().
diagram()
Diagram * Conductor::diagram () const
Returns
le Diagram auquel ce conducteur appartient, ou 0 si ce conducteur est independant
Definition at line 559 of file conductor.cpp.
Referenced by calculateTextItemPosition(), diagramEditor(), displayedTextChanged(), PotentialSelectorDialog::on_buttonBox_accepted(), paint(), ConductorPropertiesDialog::PropertiesDialog(), refreshText(), saveProfile(), DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements(), setProperties(), and setUpConnectionForFormula().
diagramEditor()
QETDiagramEditor * Conductor::diagramEditor () const
Conductor::diagramEditor.
Returns
The parent diagram editor or nullptr;
Definition at line 1703 of file conductor.cpp.
References diagram().
Referenced by editProperty(), and ConductorAutoNumerotation::numeratePotential().
displayedTextChanged
void Conductor::displayedTextChanged () slot
Conductor::displayedTextChanged Update the properties (text) of this conductor and other conductors at the same potential of this conductor.
Definition at line 1606 of file conductor.cpp.
References diagram(), ConductorProperties::m_formula, m_properties, m_text_item, properties, relatedPotentialConductors(), ConductorProperties::text, QET::Icons::tr, and Diagram::undoStack().
Referenced by Conductor().
editProperty()
void Conductor::editProperty ()
Conductor::editProperty.
Definition at line 1717 of file conductor.cpp.
References diagramEditor(), and ConductorPropertiesDialog::PropertiesDialog().
Referenced by mouseDoubleClickEvent(), and sceneEventFilter().
extendTerminal()
QPointF Conductor::extendTerminal (const QPointF & terminal, Qet::Orientation terminal_orientation, qreal ext_size = 9.0) static private
Prolonge une borne.
Parameters
terminal Le point correspondant a la borne
terminal_orientation L'orientation de la borne
ext_size la taille de la prolongation
Returns
le point correspondant a la borne apres prolongation
Definition at line 449 of file conductor.cpp.
References Qet::East, Qet::North, Qet::South, and Qet::West.
Referenced by generateConductorPath().
fakePath()
int Conductor::fakePath () inline
Definition at line 85 of file conductor.h.
fromXml()
bool Conductor::fromXml (QDomElement & dom_element)
Conductor::fromXml Load the conductor and her information from xml element.
Parameters
dom_element
Returns
true is loading success else return false
Definition at line 976 of file conductor.cpp.
References autonum::sequentialNumbers::fromXml(), ConductorProperties::fromXml(), ConductorXmlRetroCompatibility::loadSequential(), m_autoNum_seq, m_freeze_label, m_text_item, pathFromXml(), and setProperties().
generateConductorPath()
void Conductor::generateConductorPath (const QPointF & p1, Qet::Orientation o1, const QPointF & p2, Qet::Orientation o2) private
Calcule un trajet "par defaut" pour le conducteur
Parameters
p1 Coordonnees du point d'amarrage de la borne 1
o1 Orientation de la borne 1
p2 Coordonnees du point d'amarrage de la borne 2
o2 Orientation de la borne 2
Definition at line 346 of file conductor.cpp.
References Qet::East, extendTerminal(), Qet::North, pointsToSegments(), segmentsToPath(), Qet::South, Qet::West, Diagram::xGrid, and Diagram::yGrid.
Referenced by Conductor(), pathFromXml(), setProfile(), setProfiles(), and updatePath().
getCoeff()
int Conductor::getCoeff (const qreal & value1, const qreal & value2) static private
Parameters
value1 Premiere valeur
value2 Deuxieme valeur
Returns
1 si les deux valeurs sont de meme signe, -1 sinon
Definition at line 1408 of file conductor.cpp.
References getSign().
Referenced by updateConductorPath().
getSign()
int Conductor::getSign (const qreal & value) static private
Parameters
value valeur
Returns
1 si valeur est negatif, 1 s'il est positif ou nul
Definition at line 1416 of file conductor.cpp.
Referenced by getCoeff(), shareOffsetBetweenSegments(), and updateConductorPath().
handlerMouseMoveEvent()
void Conductor::handlerMouseMoveEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
Conductor::handlerMouseMoveEvent.
Parameters
qghi
event
Definition at line 794 of file conductor.cpp.
References calculateTextItemPosition(), has_to_save_profile, m_moved_segment, m_moving_segment, ConductorSegment::middle(), modified_path, segmentsToPath(), and Diagram::snapToGrid().
Referenced by sceneEventFilter().
handlerMousePressEvent()
void Conductor::handlerMousePressEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
Conductor::handlerMousePressEvent.
Parameters
qghi
event
Definition at line 771 of file conductor.cpp.
References before_mov_text_pos_, m_handler_vector, m_moved_segment, m_moving_segment, m_text_item, m_vector_index, pos, segmentsList(), and QetGraphicsHandlerItem::setColor().
Referenced by sceneEventFilter().
handlerMouseReleaseEvent()
void Conductor::handlerMouseReleaseEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
Conductor::handlerMouseReleaseEvent.
Parameters
qghi
event
Definition at line 822 of file conductor.cpp.
References addHandler(), has_to_save_profile, m_moving_segment, m_vector_index, removeHandler(), and saveProfile().
Referenced by sceneEventFilter().
handlerPoints()
QVector< QPointF > Conductor::handlerPoints () const
Conductor::handlerPoints.
Returns
The points used to draw the handler square, used to modify the path of the conductor. The points stored in the QVector are the middle point of each segments that compose the conductor, at exception of the first and last segment because there just here to extend the terminal.
Definition at line 1153 of file conductor.cpp.
References ConductorSegment::middle(), segmentsList(), and QET::Icons::sl.
Referenced by addHandler(), adjusteHandlerPos(), and segmentsToPath().
highlight()
Conductor::Highlight Conductor::highlight () const virtual
Returns
true si le conducteur est mis en evidence
Definition at line 1589 of file conductor.cpp.
References must_highlight_.
hoverEnterEvent()
void Conductor::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Conductor::hoverEnterEvent Manage the hover enter event.
Parameters
event
Definition at line 646 of file conductor.cpp.
References m_mouse_over.
hoverLeaveEvent()
void Conductor::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Conductor::hoverLeaveEvent Manage the mouse leave event.
Parameters
event
Definition at line 657 of file conductor.cpp.
References m_mouse_over.
isValid()
bool Conductor::isValid () const
Conductor::isValid.
Returns
true if conductor is valid else false; A non valid conductor, is a conductor without two terminal
Definition at line 150 of file conductor.cpp.
References m_valid.
Referenced by Diagram::fromXml().
itemChange()
QVariant Conductor::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Conductor::itemChange.
Parameters
change
value
Returns
Definition at line 669 of file conductor.cpp.
References addHandler(), adjusteHandlerPos(), calculateTextItemPosition(), m_previous_z_value, and removeHandler().
junctions()
QList< QPointF > Conductor::junctions () const private
Returns
la liste des positions des jonctions avec d'autres conducteurs
Definition at line 1773 of file conductor.cpp.
References bends(), isContained(), relatedConductors(), segmentsList(), and segmentsToPoints().
Referenced by paint().
length()
qreal Conductor::length () const
Conductor::length.
Returns
the length of this conductor
Definition at line 1189 of file conductor.cpp.
References path().
Referenced by bends(), longuestConductorInPotential(), middleSegment(), movePointIntoPolygon(), posForText(), shareOffsetBetweenSegments(), and toXml().
middleSegment()
ConductorSegment * Conductor::middleSegment ()
Returns
Le segment qui contient le point au milieu du conducteur
Definition at line 1196 of file conductor.cpp.
References length(), and segments.
Referenced by paint().
mouseDoubleClickEvent()
void Conductor::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Conductor::mouseDoubleClickEvent Manage the mouse double click.
Parameters
event
Definition at line 613 of file conductor.cpp.
References editProperty().
mousePressEvent()
void Conductor::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Conductor::mousePressEvent Manage the mouse press event.
Parameters
event
Definition at line 623 of file conductor.cpp.
mouseReleaseEvent()
void Conductor::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Conductor::mouseReleaseEvent.
Parameters
event
Definition at line 635 of file conductor.cpp.
movementType()
Qt::Corner Conductor::movementType (const QPointF & start, const QPointF & end) static private
Parameters
start Point de depart
end Point d'arrivee
Returns
le coin vers lequel se dirige le trajet de start vers end
Definition at line 1900 of file conductor.cpp.
Referenced by currentPathType().
movePointIntoPolygon()
QPointF Conductor::movePointIntoPolygon (const QPointF & point, const QPainterPath & polygon) static private
Parameters
point Un point situe a l'exterieur du polygone
polygon Le polygone dans lequel on veut rapatrier le point
Returns
la position du point, une fois ramene dans le polygone, ou plus exactement sur le bord du polygone
Definition at line 1953 of file conductor.cpp.
References length(), and QET::orthogonalProjection().
Referenced by calculateTextItemPosition().
nearShape()
QPainterPath Conductor::nearShape () const virtual
Conductor::nearShape.
Returns
: An area in which it is considered a point is near this conductor.
Definition at line 904 of file conductor.cpp.
References conductor_pen, and path().
Referenced by calculateTextItemPosition(), and ConductorTextItem::mouseMoveEvent().
paint()
void Conductor::paint (QPainter * qp, const QStyleOptionGraphicsItem * options, QWidget * qw) override
Dessine le conducteur sans antialiasing.
Parameters
qp Le QPainter a utiliser pour dessiner le conducteur
options Les options de style pour le conducteur
qw Le QWidget sur lequel on dessine
Definition at line 475 of file conductor.cpp.
References Alert, ConductorProperties::color, ConductorProperties::cond_size, conductor_brush, conductor_pen, diagram(), SingleLineProperties::draw(), QET::Horizontal, junctions(), ConductorProperties::m_bicolor, ConductorProperties::m_color_2, ConductorProperties::m_dash_size, m_mouse_over, m_properties, middleSegment(), must_highlight_, Normal, path(), ConductorProperties::Single, ConductorProperties::singleLineProperties, ConductorProperties::style, ConductorProperties::type, and QET::Vertical.
path()
QPainterPath Conductor::path () const
Definition at line 1491 of file conductor.cpp.
References m_path.
Referenced by length(), nearShape(), paint(), segmentsToPath(), setPath(), and shape().
pathFromXml()
bool Conductor::pathFromXml (const QDomElement & e) private
Conductor::pathFromXml Generate the path (of the line) from xml file by checking the segments in the xml file.
Parameters
e
Returns
true if generate path success else return false
Definition at line 1075 of file conductor.cpp.
References generateConductorPath(), modified_path, pointsToSegments(), saveProfile(), segmentsToPath(), terminal1, and terminal2.
Referenced by fromXml().
pointsToSegments()
void Conductor::pointsToSegments (const QList< QPointF > & points_list) private
Regenere les segments de ce conducteur a partir de la liste de points passee en parametre
Parameters
points_list Liste de points a utiliser pour generer les segments
Definition at line 958 of file conductor.cpp.
References deleteSegments(), and segments.
Referenced by generateConductorPath(), pathFromXml(), and updateConductorPath().
posForText()
QPointF Conductor::posForText (Qt::Orientations & flag)
Conductor::posForText Calculate and return the better pos for text.
Parameters
flag : flag is used to know if text pos is near of a vertical or horizontal conductor segment.
Definition at line 1219 of file conductor.cpp.
References QET::Horizontal, ConductorSegment::isFirstSegment(), ConductorSegment::isHorizontal(), ConductorSegment::length(), length(), ConductorSegment::middle(), ConductorSegment::previousSegment(), segments, and QET::Vertical.
Referenced by calculateTextItemPosition().
profile()
ConductorProfile Conductor::profile (Qt::Corner path_type) const
Returns
le profil de ce conducteur
Definition at line 1443 of file conductor.cpp.
References conductor_profiles.
profiles()
ConductorProfilesGroup Conductor::profiles () const
Returns
les profils de ce conducteur
Definition at line 1916 of file conductor.cpp.
References conductor_profiles.
properties()
ConductorProperties Conductor::properties () const
Conductor::properties.
Returns
the properties of this Conductor
Definition at line 1581 of file conductor.cpp.
References m_properties.
propertiesChange
void Conductor::propertiesChange () signal
Referenced by DynamicElementTextItem::conductorWasRemoved(), DynamicElementTextItem::setPotentialConductor(), and setProperties().
refreshText()
void Conductor::refreshText ()
Conductor::refreshText Refresh the text of this conductor. recalcule and set the text according to the formula.
Definition at line 1452 of file conductor.cpp.
References diagram(), autonum::AssignVariables::formulaToLabel(), m_autoNum_seq, ConductorProperties::m_formula, m_freeze_label, m_properties, m_text_item, DiagramTextItem::setPlainText(), and ConductorProperties::text.
Referenced by setSequenceNum(), and setUpConnectionForFormula().
relatedPotentialConductors()
QSet< Conductor * > Conductor::relatedPotentialConductors (const bool all_diagram = true, QList< Terminal * > * t_list = nullptr)
Conductor::relatedPotentialConductors Return all conductors at the same potential of this conductor, this conductor isn't part of the returned QSet.
Parameters
all_diagram : if true search in all diagram of the project, false search only in the parent diagram of this conductor
t_list : a list of terminal already found for this potential.
Returns
a QSet of conductor at the same potential.
Definition at line 1647 of file conductor.cpp.
References Terminal::conductors(), relatedPotentialTerminal(), terminal1, and terminal2.
Referenced by calculateTextItemPosition(), displayedTextChanged(), ElementsMover::endMovement(), ConductorCreator::existingPotential(), NewConductorPotentialSelector::getPotential(), longuestConductorInPotential(), Terminal::mouseReleaseEvent(), PotentialSelectorDialog::on_buttonBox_accepted(), DiagramContent::operator+=(), ConductorPropertiesDialog::PropertiesDialog(), and setPropertyToPotential().
removeHandler()
void Conductor::removeHandler () private
Conductor::removeHandler Remove the handlers of this item.
Definition at line 865 of file conductor.cpp.
References m_handler_vector.
Referenced by handlerMouseReleaseEvent(), itemChange(), segmentsToPath(), and ~Conductor().
rSequenceNum()
autonum::sequentialNumbers& Conductor::rSequenceNum () inline
Definition at line 132 of file conductor.h.
References m_autoNum_seq.
Referenced by ConductorXmlRetroCompatibility::loadSequential(), Terminal::mouseReleaseEvent(), ConductorAutoNumerotation::numerateNewConductor(), and ConductorAutoNumerotation::numeratePotential().
saveProfile()
void Conductor::saveProfile (bool undo = true) private
Sauvegarde le profil courant du conducteur pour l'utiliser ulterieurement dans priv_modifieConductor.
Definition at line 1386 of file conductor.cpp.
References before_mov_text_pos_, conductor_profiles, currentPathType(), diagram(), m_text_item, and pos.
Referenced by handlerMouseReleaseEvent(), and pathFromXml().
sceneEventFilter()
bool Conductor::sceneEventFilter (QGraphicsItem * watched, QEvent * event) override protected
Conductor::sceneEventFilter.
Parameters
watched
event
Returns
Definition at line 710 of file conductor.cpp.
References editProperty(), handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), m_handler_vector, m_vector_index, and QetGraphicsHandlerItem::Type.
segmentsCount()
uint Conductor::segmentsCount (QET::ConductorSegmentType type = QET::Both) const private
Parameters
type Type de Segments
Returns
Le nombre de segments composant le conducteur.
Definition at line 916 of file conductor.cpp.
References QET::Both, segmentsList(), and type().
Referenced by updatePath().
segmentsList()
const QList< ConductorSegment * > Conductor::segmentsList () const
Returns
les segments de ce conducteur
Definition at line 1171 of file conductor.cpp.
References segments.
Referenced by handlerMousePressEvent(), handlerPoints(), junctions(), segmentsCount(), and toXml().
segmentsToPath()
void Conductor::segmentsToPath () private
Conductor::segmentsToPath Generate the QPainterPath from the list of points.
Definition at line 177 of file conductor.cpp.
References addHandler(), adjusteHandlerPos(), handlerPoints(), m_handler_vector, m_moving_segment, path(), removeHandler(), segments, and setPath().
Referenced by generateConductorPath(), handlerMouseMoveEvent(), pathFromXml(), and updateConductorPath().
segmentsToPoints()
QList< QPointF > Conductor::segmentsToPoints () const private
Genere une liste de points a partir des segments de ce conducteur
Returns
La liste de points representant ce conducteur
Definition at line 930 of file conductor.cpp.
References segments.
Referenced by junctions().
sequenceNum()
autonum::sequentialNumbers Conductor::sequenceNum () const inline
Definition at line 131 of file conductor.h.
References m_autoNum_seq.
setFreezeLabel()
void Conductor::setFreezeLabel (bool freeze)
Conductor::setFreezeLabel Freeze this conductor label if true Unfreeze this conductor label if false.
Parameters
freeze
Definition at line 2035 of file conductor.cpp.
References ConductorProperties::m_formula, m_freeze_label, m_properties, and setUpConnectionForFormula().
Referenced by DiagramEventAddElement::addElement(), Diagram::freezeConductors(), and MultiPasteDialog::on_m_button_box_accepted().
setHighlighted()
void Conductor::setHighlighted (Conductor::Highlight hl) virtual
Parameters
hl true pour mettre le conducteur en evidence, false sinon
Definition at line 1596 of file conductor.cpp.
References must_highlight_.
setPath()
void Conductor::setPath (const QPainterPath & path)
Definition at line 1481 of file conductor.cpp.
References m_path, and path().
Referenced by segmentsToPath().
setProfile()
void Conductor::setProfile (const ConductorProfile & cp, Qt::Corner path_type)
Applique un nouveau profil a ce conducteur
Parameters
cp Profil a appliquer a ce conducteur
path_type Type de trajet pour lequel ce profil convient
Definition at line 1425 of file conductor.cpp.
References calculateTextItemPosition(), conductor_profiles, currentPathType(), generateConductorPath(), modified_path, ConductorProperties::Multi, terminal1, terminal2, type(), and updateConductorPath().
setProfiles()
void Conductor::setProfiles (const ConductorProfilesGroup & cpg)
Conductor::setProfiles.
Parameters
cpg : the new profils of conductor
Definition at line 1924 of file conductor.cpp.
References calculateTextItemPosition(), conductor_profiles, currentPathType(), generateConductorPath(), modified_path, ConductorProperties::Multi, properties, terminal1, terminal2, type(), and updateConductorPath().
setProperties()
void Conductor::setProperties (const ConductorProperties & property)
Conductor::setProperties Set property as current property of conductor.
Parameters
property : properties
Definition at line 1538 of file conductor.cpp.
References calculateTextItemPosition(), diagram(), DiagramTextItem::font, autonum::AssignVariables::formulaToLabel(), m_autoNum_seq, ConductorProperties::m_formula, m_properties, ConductorProperties::m_show_text, m_text_item, ConductorProperties::Multi, propertiesChange(), DiagramTextItem::setColor(), DiagramTextItem::setFont(), DiagramTextItem::setPlainText(), setUpConnectionForFormula(), ConductorProperties::text, ConductorProperties::text_color, ConductorProperties::text_size, and ConductorProperties::type.
Referenced by Conductor(), ConductorCreator::ConductorCreator(), ElementsMover::endMovement(), fromXml(), Terminal::mouseReleaseEvent(), ConductorAutoNumerotation::numerateNewConductor(), ConductorAutoNumerotation::numeratePotential(), DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements(), and setPropertyToPotential().
setPropertyToPotential()
void Conductor::setPropertyToPotential (const ConductorProperties & property, bool only_text = false)
Conductor::setPropertiesToPotential.
Parameters
property
only_text Set propertie to conductor and every conductors in the same potential of conductor. If only_text is true only formula, text, function and tension/protocol is set to other conductor in the same potential, the other values of property stay unmodified
Definition at line 1507 of file conductor.cpp.
References ConductorProperties::m_formula, ConductorProperties::m_function, m_properties, ConductorProperties::m_tension_protocol, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, properties, relatedPotentialConductors(), setProperties(), and ConductorProperties::text.
setSequenceNum()
void Conductor::setSequenceNum (const autonum::sequentialNumbers & sn)
Definition at line 1721 of file conductor.cpp.
References m_autoNum_seq, and refreshText().
Referenced by ConductorCreator::ConductorCreator().
setUpConnectionForFormula()
void Conductor::setUpConnectionForFormula (QString old_formula, QString new_formula) private
Conductor::setUpConnectionForFormula setup connection according to the variable of formula.
Parameters
old_formula
new_formula
Definition at line 1733 of file conductor.cpp.
References diagram(), m_freeze_label, QETProject::projectDiagramsOrderChanged(), and refreshText().
Referenced by setFreezeLabel(), and setProperties().
shape()
QPainterPath Conductor::shape () const override
Conductor::shape.
Returns
the shape of conductor. The shape thickness is bigger when conductor is hovered
Definition at line 889 of file conductor.cpp.
References conductor_pen, m_mouse_over, and path().
Referenced by boundingRect().
shareOffsetBetweenSegments()
QHash< ConductorSegmentProfile *, qreal > Conductor::shareOffsetBetweenSegments (const qreal & offset, const QList< ConductorSegmentProfile * > & segments_list, const qreal & precision = 0.01) const private
Parameters
offset Longueur a repartir entre les segments
segments_list Segments sur lesquels il faut repartir la longueur
precision seuil en-deca duquel on considere qu'il ne reste rien a repartir
Definition at line 287 of file conductor.cpp.
References getSign(), and length().
Referenced by updateConductorPath().
textItem()
ConductorTextItem * Conductor::textItem () const
4
Returns
le champ de texte associe a ce conducteur
Definition at line 566 of file conductor.cpp.
References m_text_item.
Referenced by calculateTextItemPosition().
toXml()
QDomElement Conductor::toXml (QDomDocument & dom_document, QHash< Terminal *, int > & table_adr_id) const
Conductor::toXml Exporte les caracteristiques du conducteur sous forme d'une element XML.
Parameters
dom_document : Le document XML a utiliser pour creer l'element XML
table_adr_id : Hash stockant les correspondances entre les ids des bornes dans le document XML et leur adresse en memoire
Returns
Un element XML representant le conducteur
Definition at line 1010 of file conductor.cpp.
References length(), m_autoNum_seq, m_freeze_label, m_properties, m_text_item, modified_path, Terminal::parentElement(), pos, segmentsList(), terminal1, terminal2, autonum::sequentialNumbers::toXml(), Terminal::uuid(), Element::uuid(), ConductorTextItem::wasMovedByUser(), and ConductorTextItem::wasRotateByUser().
type()
int Conductor::type () const inline override
type Enable the use of qgraphicsitem_cast to safely cast a QGraphicsItem into a conductor.
Returns
the QGraphicsItem type
Definition at line 77 of file conductor.h.
References Type.
Referenced by bends(), segmentsCount(), setProfile(), and setProfiles().
updateConductorPath()
void Conductor::updateConductorPath (const QPointF & p1, Qet::Orientation o1, const QPointF & p2, Qet::Orientation o2) private
Gere les updates
Parameters
p1 Coordonnees du point d'amarrage de la borne 1
o1 Orientation de la borne 1
p2 Coordonnees du point d'amarrage de la borne 2
o2 Orientation de la borne 2
Definition at line 218 of file conductor.cpp.
References QET::Both, conductor_profiles, currentPathType(), getCoeff(), getSign(), ConductorProfile::height(), ConductorProfile::horizontalSegments(), ConductorProfile::isNull(), pointsToSegments(), ConductorProfile::segments, ConductorProfile::segmentsCount(), segmentsToPath(), shareOffsetBetweenSegments(), ConductorProfile::verticalSegments(), and ConductorProfile::width().
Referenced by setProfile(), setProfiles(), and updatePath().
updatePath()
void Conductor::updatePath (const QRectF & rect = QRectF())
Met a jour la representation graphique du conducteur en recalculant son trace. Cette fonction est typiquement appelee lorsqu'une seule des bornes du conducteur a change de position.
Parameters
rect Rectangle a mettre a jour
See also
QGraphicsPathItem::update()
Definition at line 161 of file conductor.cpp.
References calculateTextItemPosition(), conductor_profiles, currentPathType(), generateConductorPath(), segmentsCount(), terminal1, terminal2, and updateConductorPath().
Referenced by ElementsMover::continueMovement(), Terminal::updateConductor(), and updatePathAnimate().
updatePathAnimate()
void Conductor::updatePathAnimate (const int = 1) inline
Definition at line 84 of file conductor.h.
References updatePath().
valideXml()
bool Conductor::valideXml (QDomElement & e) static
Methode de validation d'element XML
Parameters
e Un element XML sense represente un Conducteur
Returns
true si l'element XML represente bien un Conducteur ; false sinon
Definition at line 575 of file conductor.cpp.
Referenced by Diagram::fromXml().
Member Data Documentation
before_mov_text_pos_
QPointF Conductor::before_mov_text_pos_ private
Definition at line 178 of file conductor.h.
Referenced by handlerMousePressEvent(), and saveProfile().
conductor_brush
QBrush Conductor::conductor_brush = QBrush() static private
Definition at line 193 of file conductor.h.
Referenced by Conductor(), and paint().
conductor_pen
QPen Conductor::conductor_pen = QPen() static private
QPen et QBrush objects used to draw conductors.
Definition at line 192 of file conductor.h.
Referenced by Conductor(), nearShape(), paint(), and shape().
conductor_profiles
ConductorProfilesGroup Conductor::conductor_profiles private
conductor profile: "photography" of what the conductor is supposed to look like - there is one profile per kind of traject
Definition at line 185 of file conductor.h.
Referenced by Conductor(), profile(), profiles(), saveProfile(), setProfile(), setProfiles(), updateConductorPath(), and updatePath().
has_to_save_profile
bool Conductor::has_to_save_profile private
Whether the current profile should be saved as soon as possible.
Definition at line 182 of file conductor.h.
Referenced by handlerMouseMoveEvent(), and handlerMouseReleaseEvent().
m_autoNum_seq
autonum::sequentialNumbers Conductor::m_autoNum_seq private
Definition at line 137 of file conductor.h.
Referenced by fromXml(), refreshText(), rSequenceNum(), sequenceNum(), setProperties(), setSequenceNum(), and toXml().
m_freeze_label
bool Conductor::m_freeze_label = false private
Definition at line 189 of file conductor.h.
Referenced by fromXml(), refreshText(), setFreezeLabel(), setUpConnectionForFormula(), and toXml().
m_handler_vector
QVector<QetGraphicsHandlerItem *> Conductor::m_handler_vector private
Definition at line 164 of file conductor.h.
Referenced by addHandler(), adjusteHandlerPos(), handlerMousePressEvent(), removeHandler(), sceneEventFilter(), and segmentsToPath().
m_mouse_over
bool Conductor::m_mouse_over private
Definition at line 166 of file conductor.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), paint(), and shape().
m_moved_segment
ConductorSegment* Conductor::m_moved_segment private
Definition at line 177 of file conductor.h.
Referenced by handlerMouseMoveEvent(), and handlerMousePressEvent().
m_moving_segment
bool Conductor::m_moving_segment private
Attributs related to mouse interaction.
Definition at line 174 of file conductor.h.
Referenced by handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), and segmentsToPath().
m_path
QPainterPath Conductor::m_path private
Definition at line 195 of file conductor.h.
Referenced by path(), and setPath().
m_previous_z_value
qreal Conductor::m_previous_z_value private
Definition at line 176 of file conductor.h.
Referenced by Conductor(), and itemChange().
m_properties
ConductorProperties Conductor::m_properties private
Functional properties.
Definition at line 168 of file conductor.h.
Referenced by calculateTextItemPosition(), Conductor(), displayedTextChanged(), paint(), properties(), refreshText(), setFreezeLabel(), setProperties(), setPropertyToPotential(), and toXml().
m_text_item
ConductorTextItem* Conductor::m_text_item private
Text input for non simple, non-singleline conductors.
Definition at line 170 of file conductor.h.
Referenced by calculateTextItemPosition(), Conductor(), displayedTextChanged(), fromXml(), handlerMousePressEvent(), refreshText(), saveProfile(), setProperties(), textItem(), and toXml().
m_valid
bool Conductor::m_valid private
Definition at line 188 of file conductor.h.
Referenced by Conductor(), and isValid().
m_vector_index
int Conductor::m_vector_index = -1 private
Definition at line 165 of file conductor.h.
Referenced by handlerMousePressEvent(), handlerMouseReleaseEvent(), and sceneEventFilter().
modified_path
bool Conductor::modified_path private
Whether the conductor was manually modified by users.
Definition at line 180 of file conductor.h.
Referenced by handlerMouseMoveEvent(), pathFromXml(), setProfile(), setProfiles(), and toXml().
moved_point
int Conductor::moved_point private
Definition at line 175 of file conductor.h.
must_highlight_
Highlight Conductor::must_highlight_ private
Define whether and how the conductor should be highlighted.
Definition at line 187 of file conductor.h.
Referenced by highlight(), paint(), and setHighlighted().
pen_and_brush_initialized
bool Conductor::pen_and_brush_initialized = false static private
Definition at line 194 of file conductor.h.
Referenced by Conductor().
segments
ConductorSegment* Conductor::segments private
Segments composing the conductor.
Definition at line 172 of file conductor.h.
Referenced by bends(), deleteSegments(), middleSegment(), pointsToSegments(), posForText(), segmentsList(), segmentsToPath(), and segmentsToPoints().
terminal1
Terminal* Conductor::terminal1
Definition at line 67 of file conductor.h.
Referenced by Terminal::addConductor(), Diagram::addItem(), Conductor(), currentPathType(), NewConductorPotentialSelector::NewConductorPotentialSelector(), pathFromXml(), relatedConductors(), relatedPotentialConductors(), Diagram::removeItem(), setProfile(), setProfiles(), toXml(), updatePath(), and ~Conductor().
terminal2
Terminal* Conductor::terminal2
Definition at line 68 of file conductor.h.
Referenced by Terminal::addConductor(), Diagram::addItem(), Conductor(), currentPathType(), NewConductorPotentialSelector::NewConductorPotentialSelector(), pathFromXml(), relatedConductors(), relatedPotentialConductors(), Diagram::removeItem(), setProfile(), setProfiles(), toXml(), updatePath(), and ~Conductor().
Property Documentation
animPath
int Conductor::animPath read write
Definition at line 223 of file conductor.h.
pos
QPointF Conductor::pos read write
Definition at line 223 of file conductor.h.
Referenced by calculateTextItemPosition(), ExportDialog::generateDxf(), handlerMousePressEvent(), MoveElementsCommand::move(), saveProfile(), and toXml().
properties
ConductorProperties Conductor::properties read write
Definition at line 223 of file conductor.h.
Referenced by DynamicTextItemDelegate::availableInfo(), ConductorPropertiesDialog::ConductorPropertiesDialog(), displayedTextChanged(), ElementsMover::endMovement(), SearchAndReplaceWidget::fillItemsList(), NewConductorPotentialSelector::getPotential(), LinkReportPotentialSelector::LinkReportPotentialSelector(), Terminal::mouseReleaseEvent(), ConductorAutoNumerotation::numeratePotential(), PotentialSelectorDialog::on_buttonBox_accepted(), ConductorPropertiesDialog::PropertiesDialog(), SearchAndReplaceWorker::replaceAdvanced(), SearchAndReplaceWidget::searchTerms(), setProfiles(), and setPropertyToPotential().
sequenceNum
autonum::sequentialNumbers Conductor::sequenceNum read write
Definition at line 223 of file conductor.h.
Referenced by NewConductorPotentialSelector::getPotential(), Terminal::mouseReleaseEvent(), and PotentialSelectorDialog::on_buttonBox_accepted().
The documentation for this class was generated from the following files:
conductor.h
conductor.cpp