QElectroTech: ConductorAutoNumerotation Class Reference
ConductorAutoNumerotation Class Reference
The ConductorAutoNumerotation class.
#include <conductorautonumerotation.h>
Public Member Functions
ConductorAutoNumerotation (Conductor *conductor, Diagram *diagram, QUndoCommand *undo_parent=nullptr)
ConductorAutoNumerotation::ConductorAutoNumerotation Constructor of autonum, after create a class, call numerate to apply the autonum. When autonum is applyed, they do with an undo command added to the stack of diagram. If you give a parent_undo at constructor, the undo command create in this class have parent_undo for parent, and wasn't added to the stack of diagram (it's the responsabillty of the parent_undo)
void numerate ()
ConductorAutoNumerotation::numerate execute the automatic numerotation.
void applyText (const QString &)
ConductorAutoNumerotation::applyText apply the text t to conductor_ and all conductors at the same potential.
Static Public Member Functions
static void newProperties (Diagram *diagram, ConductorProperties &cp, autonum::sequentialNumbers &seq)
ConductorAutoNumerotation::newProperties Create a new properties according to the current autonum rule of diagram.
Private Member Functions
void numeratePotential ()
ConductorAutoNumerotation::numeratePotential Numerate a conductor on an existing potential.
void numerateNewConductor ()
ConductorAutoNumerotation::numerateNewConductor create and apply a new numerotation to m_conductor.
Private Attributes
Diagram * m_diagram
Conductor * m_conductor
QList< Conductor * > conductor_list
QUndoCommand * m_parent_undo
Detailed Description
The ConductorAutoNumerotation class.
Definition at line 32 of file conductorautonumerotation.h.
Constructor & Destructor Documentation
ConductorAutoNumerotation()
ConductorAutoNumerotation::ConductorAutoNumerotation (Conductor * conductor, Diagram * diagram, QUndoCommand * parent_undo = nullptr)
ConductorAutoNumerotation::ConductorAutoNumerotation Constructor of autonum, after create a class, call numerate to apply the autonum. When autonum is applyed, they do with an undo command added to the stack of diagram. If you give a parent_undo at constructor, the undo command create in this class have parent_undo for parent, and wasn't added to the stack of diagram (it's the responsabillty of the parent_undo)
Parameters
conductor : the conductor to apply automatic numerotation
diagram : the diagram of conductor
parent_undo : parent undo command
Definition at line 42 of file conductorautonumerotation.cpp.
Member Function Documentation
applyText()
void ConductorAutoNumerotation::applyText (const QString & t)
ConductorAutoNumerotation::applyText apply the text t to conductor_ and all conductors at the same potential.
Parameters
t : Conductor text
Definition at line 69 of file conductorautonumerotation.cpp.
References conductor_list, m_conductor, m_diagram, m_parent_undo, ConductorProperties::text, QET::Icons::tr, and Diagram::undoStack().
Referenced by numerateNewConductor().
newProperties()
void ConductorAutoNumerotation::newProperties (Diagram * diagram, ConductorProperties & cp, autonum::sequentialNumbers & seq) static
ConductorAutoNumerotation::newProperties Create a new properties according to the current autonum rule of diagram.
Parameters
diagram : Diagram class
cp : ConductorProperties
seq : sequentialNumbers
Definition at line 140 of file conductorautonumerotation.cpp.
References QETProject::addConductorAutoNum(), QETProject::conductorAutoNum(), QETProject::conductorCurrentAutoNum(), Diagram::conductorsAutonumName(), NumerotationContext::isEmpty(), ConductorProperties::m_formula, NumerotationContextCommands::next(), autonum::numerotationContextToFormula(), Diagram::project(), and autonum::setSequential().
Referenced by ConductorCreator::setUpPropertieToUse().
numerate()
void ConductorAutoNumerotation::numerate ()
ConductorAutoNumerotation::numerate execute the automatic numerotation.
Definition at line 56 of file conductorautonumerotation.cpp.
References conductor_list, m_conductor, ConductorProperties::Multi, numerateNewConductor(), and numeratePotential().
Referenced by DiagramEventAddElement::addElement(), ElementsMover::endMovement(), Terminal::mouseReleaseEvent(), and MultiPasteDialog::on_m_button_box_accepted().
numerateNewConductor()
void ConductorAutoNumerotation::numerateNewConductor () private
ConductorAutoNumerotation::numerateNewConductor create and apply a new numerotation to m_conductor.
Definition at line 220 of file conductorautonumerotation.cpp.
References QETProject::addConductorAutoNum(), applyText(), QETProject::conductorAutoNum(), QETProject::conductorCurrentAutoNum(), Diagram::conductorsAutonumName(), autonum::AssignVariables::formulaToLabel(), NumerotationContext::isEmpty(), m_conductor, m_diagram, ConductorProperties::m_formula, NumerotationContextCommands::next(), autonum::numerotationContextToFormula(), Diagram::project(), Conductor::rSequenceNum(), Conductor::setProperties(), and autonum::setSequential().
Referenced by numerate().
numeratePotential()
void ConductorAutoNumerotation::numeratePotential () private
ConductorAutoNumerotation::numeratePotential Numerate a conductor on an existing potential.
Definition at line 165 of file conductorautonumerotation.cpp.
References ConductorProperties::applyForEqualAttributes(), conductor_list, Conductor::diagramEditor(), QET::eachStrIsEqual(), m_conductor, ConductorProperties::m_formula, m_parent_undo, Conductor::properties, Conductor::rSequenceNum(), Conductor::setProperties(), and ConductorProperties::text.
Referenced by numerate().
Member Data Documentation
conductor_list
QList<Conductor *> ConductorAutoNumerotation::conductor_list private
Definition at line 55 of file conductorautonumerotation.h.
Referenced by applyText(), numerate(), and numeratePotential().
m_conductor
Conductor* ConductorAutoNumerotation::m_conductor private
Definition at line 54 of file conductorautonumerotation.h.
Referenced by applyText(), numerate(), numerateNewConductor(), and numeratePotential().
m_diagram
Diagram* ConductorAutoNumerotation::m_diagram private
Definition at line 53 of file conductorautonumerotation.h.
Referenced by applyText(), and numerateNewConductor().
m_parent_undo
QUndoCommand* ConductorAutoNumerotation::m_parent_undo private
Definition at line 56 of file conductorautonumerotation.h.
Referenced by applyText(), and numeratePotential().
The documentation for this class was generated from the following files:
conductorautonumerotation.h
conductorautonumerotation.cpp