QElectroTech: BorderTitleBlock Class Reference
BorderTitleBlock Class Reference
The BorderTitleBlock class This class represents the border and the titleblock which frame a particular electric diagram.
#include <bordertitleblock.h>
Public Slots
void titleBlockTemplateChanged (const QString &)
BorderTitleBlock::titleBlockTemplateChanged This slot may be used to inform this class that the given title block template has changed. The title block-dedicated rendering cache will thus be flushed.
void titleBlockTemplateRemoved (const QString &, const TitleBlockTemplate *=nullptr)
BorderTitleBlock::titleBlockTemplateRemoved This slot has to be used to inform this class that the given title block template is about to be removed and is no longer accessible. This class will either use the provided optional TitleBlockTemplate or the default title block provided by QETApp::defaultTitleBlockTemplate()
void displayTitleBlock (bool)
BorderTitleBlock::displayTitleBlock.
void displayColumns (bool)
BorderTitleBlock::displayColumns.
void displayRows (bool)
BorderTitleBlock::displayRows.
void displayBorder (bool)
BorderTitleBlock::displayBorder.
void slot_setAutoPageNum (QString)
BorderTitleBlock::slot_setAutoPageNum.
Signals
void borderChanged (QRectF old_border, QRectF new_border)
borderChanged Signal emitted after the border has changed
void displayChanged ()
displayChanged Signal emitted after display options have changed
void diagramTitleChanged (const QString &)
diagramTitleChanged Signal emitted after the title has changed
void titleBlockFolioChanged (const QString &)
titleBlockFolioChanged Signal emitted after Folio has changed
void needFolioData ()
needFolioData Signal emitted when the title block requires its data to be updated in order to generate the folio field.
void needTitleBlockTemplate (const QString &)
needTitleBlockTemplate Signal emitted when this object needs to set a specific title block template. This object cannot handle the job since it does not know of its parent project.
Public Member Functions
BorderTitleBlock (QObject *=nullptr)
BorderTitleBlock::BorderTitleBlock Simple constructor: build a border by recovering the dimensions in the application configuration.
~BorderTitleBlock () override
BorderTitleBlock::~BorderTitleBlock.
void draw (QPainter *painter)
BorderTitleBlock::draw Draw the border and the titleblock.
void drawDxf (int, int, bool, QString &, int)
BorderTitleBlock::drawDxf.
int columnsCount () const
qreal columnsWidth () const
qreal columnsTotalWidth () const
qreal columnsHeaderHeight () const
int rowsCount () const
qreal rowsHeight () const
qreal rowsTotalHeight () const
qreal rowsHeaderWidth () const
qreal diagramWidth () const
diagramWidth
qreal diagramHeight () const
diagramHeight
QRectF titleBlockRect () const
BorderTitleBlock::titleBlockRect.
DiagramContext titleblockInformation () const
BorderTitleBlock::titleblockInformation.
QRectF borderAndTitleBlockRect () const
BorderTitleBlock::borderAndTitleBlockRect.
QRectF columnsRect () const
BorderTitleBlock::columnsRect.
QRectF rowsRect () const
BorderTitleBlock::rowsRect.
QRectF outsideBorderRect () const
BorderTitleBlock::outsideBorderRect.
QRectF insideBorderRect () const
BorderTitleBlock::insideBorderRect.
QString author () const
QDate date () const
QString title () const
QString folio () const
QString finalfolio () const
QString plant () const
QString locmach () const
QString indexrev () const
QString fileName () const
QString version () const
DiagramContext additionalFields () const
QString autoPageNum () const
int folioTotal () const
bool titleBlockIsDisplayed () const
bool columnsAreDisplayed () const
bool rowsAreDisplayed () const
bool borderIsDisplayed () const
void setColumnsCount (int)
BorderTitleBlock::setColumnsCount Allows you to change the number of columns. If this number of columns is less than the minimum required, it is this minimum which is used.
void setRowsCount (int)
BorderTitleBlock::setRowsCount Allows you to change the number of lines. If this number of lines is lower than the minimum required, this function does nothing.
void setColumnsWidth (const qreal &)
BorderTitleBlock::setColumnsWidth Change the width of the columns. If the width indicated is less than the minimum required, it is this minimum which is used.
void setRowsHeight (const qreal &)
BorderTitleBlock::setRowsHeight Change the height of the lines. If the indicated height is lower than the minimum required, it is this minimum which is used.
void setColumnsHeaderHeight (const qreal &)
BorderTitleBlock::setColumnsHeaderHeight Change the height of the headers containing the column numbers. This must remain between 5 and 50 px.
void setRowsHeaderWidth (const qreal &)
BorderTitleBlock::setRowsHeaderWidth Change the width of the headers containing the line numbers. This must remain between 5 and 50 px.
void setDiagramHeight (const qreal &)
BorderTitleBlock::setDiagramHeight This method tries to get as close as possible to the given height as a parameter by modifying the number of rows in progress.
DiagramPosition convertPosition (const QPointF &)
BorderTitleBlock::convertPosition Convert a Point in cartesian coordinate (x : 12.5, 56.9) to a point in grid coordinate (ex : B2)
void setAuthor (const QString &author)
BorderTitleBlock::setAuthor.
void setDate (const QDate &date)
BorderTitleBlock::setDate.
void setTitle (const QString &title)
BorderTitleBlock::setTitle.
void setFolio (const QString &folio)
BorderTitleBlock::setFolio.
void setFolioData (int, int, const QString &=nullptr, const DiagramContext &=DiagramContext())
BorderTitleBlock::setFolioData.
void setPlant (const QString &plant)
BorderTitleBlock::setPlant.
void setLocMach (const QString &locmach)
BorderTitleBlock::setLocMach.
void setIndicerev (const QString &indexrev)
BorderTitleBlock::setIndicerev.
void setFileName (const QString &filename)
BorderTitleBlock::setFileName.
void setVersion (const QString &version)
BorderTitleBlock::setVersion.
void setAutoPageNum (const QString &auto_page_num)
BorderTitleBlock::setAutoPageNum.
void setPreviousFolioNum (const QString &previous)
BorderTitleBlock::setPreviousFolioNum.
void setNextFolioNum (const QString &next)
BorderTitleBlock::setNextFolioNum.
void titleBlockToXml (QDomElement &)
BorderTitleBlock::titleBlockToXml Exports the title block current values to XML.
void titleBlockFromXml (const QDomElement &)
BorderTitleBlock::titleBlockFromXml Reads the title block values from XML.
void borderToXml (QDomElement &)
BorderTitleBlock::borderToXml Exports the border current settings to XML.
void borderFromXml (const QDomElement &)
BorderTitleBlock::borderFromXml Reads the border settings from XML.
TitleBlockProperties exportTitleBlock ()
BorderTitleBlock::exportTitleBlock.
void importTitleBlock (const TitleBlockProperties &)
BorderTitleBlock::importTitleBlock.
BorderProperties exportBorder ()
BorderTitleBlock::exportBorder.
void importBorder (const BorderProperties &)
BorderTitleBlock::importBorder.
const TitleBlockTemplate * titleBlockTemplate ()
BorderTitleBlock::titleBlockTemplate.
void setTitleBlockTemplate (const TitleBlockTemplate *)
BorderTitleBlock::setTitleBlockTemplate.
QString titleBlockTemplateName () const
BorderTitleBlock::titleBlockTemplateName.
Private Member Functions
BorderTitleBlock (const BorderTitleBlock &)
QRectF titleBlockRectForQPainter () const
BorderTitleBlock::titleBlockRectForQPainter.
void updateRectangles ()
BorderTitleBlock::updateRectangles This method update the diagram rect according to the value of rows and columns (number and size)
void updateDiagramContextForTitleBlock (const DiagramContext &=DiagramContext())
BorderTitleBlock::updateDiagramContextForTitleBlock Update the informations given to the titleblock template by regenerating a DiagramContext object.
QString incrementLetters (const QString &)
BorderTitleBlock::incrementLetters increments string with Letters A to Z.
Private Attributes
QString btb_author_
titleblock author
QDate btb_date_
titleblock date
QString btb_title_
titleblock title
QString btb_folio_
titleblock folio
QString btb_plant_
titleblock plant
QString btb_locmach_
titleblock locmach
QString btb_indexrev_
titleblock index rev
QString btb_final_folio_
titleblock final folio
QString btb_auto_page_num_
titleblock auto page num
int folio_index_
titleblock index
int folio_total_
titleblock total
QString btb_filename_
titleblock filename
QString btb_version_
DiagramContext additional_fields_
titleblock additional fields
Qt::Edge m_edge
titleblock edge
QString m_next_folio_num
titleblock next folio num
QString m_previous_folio_num
titleblock previous folio num
int columns_count_
columns count
qreal columns_width_
columns width
qreal columns_header_height_
columns header height
int rows_count_
rows count
qreal rows_height_
rows height
qreal rows_header_width_
rows header width
qreal titleblock_height_
QRectF diagram_rect_
bool display_titleblock_
bool display_columns_
bool display_rows_
bool display_border_
TitleBlockTemplateRenderer * m_titleblock_template_renderer
Detailed Description
The BorderTitleBlock class This class represents the border and the titleblock which frame a particular electric diagram.
Definition at line 36 of file bordertitleblock.h.
Constructor & Destructor Documentation
BorderTitleBlock() [1/2]
BorderTitleBlock::BorderTitleBlock (QObject * parent = nullptr)
BorderTitleBlock::BorderTitleBlock Simple constructor: build a border by recovering the dimensions in the application configuration.
Parameters
parent :
Definition at line 46 of file bordertitleblock.cpp.
References QETApp::defaultTitleBlockTemplate(), display_border_, display_titleblock_, importBorder(), importTitleBlock(), m_titleblock_template_renderer, setFolioData(), setTitleBlockTemplate(), and updateRectangles().
~BorderTitleBlock()
BorderTitleBlock::~BorderTitleBlock () override
BorderTitleBlock::~BorderTitleBlock.
Definition at line 74 of file bordertitleblock.cpp.
BorderTitleBlock() [2/2]
BorderTitleBlock::BorderTitleBlock (const BorderTitleBlock &) private
Member Function Documentation
additionalFields()
DiagramContext BorderTitleBlock::additionalFields () const inline
Returns
the value of the title block Additional Fields
Definition at line 127 of file bordertitleblock.h.
References additional_fields_.
Referenced by autonum::AssignVariables::assignTitleBlockVar().
author()
QString BorderTitleBlock::author () const inline
Returns
the value of the title block "Author" field
Definition at line 107 of file bordertitleblock.h.
References btb_author_.
Referenced by exportTitleBlock(), and setAuthor().
autoPageNum()
QString BorderTitleBlock::autoPageNum () const inline
Returns
the value of the title block
Definition at line 130 of file bordertitleblock.h.
References btb_auto_page_num_.
Referenced by exportTitleBlock().
borderAndTitleBlockRect()
QRectF BorderTitleBlock::borderAndTitleBlockRect () const
BorderTitleBlock::borderAndTitleBlockRect.
Returns
the bounding rectangle of diagram and titleblock. It's like unite outsideBorderRect and titleBlockRect. The rect is in scene coordinate
Definition at line 134 of file bordertitleblock.cpp.
References diagram_rect_, and titleBlockRect().
Referenced by Diagram::adjustSceneRect(), Diagram::imageSize(), and Diagram::toPaintDevice().
borderChanged
void BorderTitleBlock::borderChanged (QRectF old_border, QRectF new_border) signal
borderChanged Signal emitted after the border has changed
Parameters
old_border Former border
new_border New border
Referenced by Diagram::Diagram(), and updateRectangles().
borderFromXml()
void BorderTitleBlock::borderFromXml (const QDomElement & xml_elmt)
BorderTitleBlock::borderFromXml Reads the border settings from XML.
Parameters
xml_elmt the XML element values will be read from
Definition at line 241 of file bordertitleblock.cpp.
References displayColumns(), displayRows(), setColumnsCount(), setColumnsWidth(), setDiagramHeight(), setRowsCount(), setRowsHeight(), and updateRectangles().
Referenced by Diagram::fromXml().
borderIsDisplayed()
bool BorderTitleBlock::borderIsDisplayed () const inline
Returns
true si la bordure est affichee, false sinon
Definition at line 145 of file bordertitleblock.h.
References display_border_.
Referenced by Diagram::applyProperties().
borderToXml()
void BorderTitleBlock::borderToXml (QDomElement & xml_elmt)
BorderTitleBlock::borderToXml Exports the border current settings to XML.
Parameters
xml_elmt the XML element attributes will be added to
Definition at line 223 of file bordertitleblock.cpp.
References columnsAreDisplayed(), columnsCount(), columnsWidth(), diagramHeight(), rowsAreDisplayed(), rowsCount(), and rowsHeight().
Referenced by Diagram::toXml().
columnsAreDisplayed()
bool BorderTitleBlock::columnsAreDisplayed () const inline
Returns
true si les entetes des colonnes sont affiches, false sinon
Definition at line 140 of file bordertitleblock.h.
References display_columns_.
Referenced by Diagram::borderOptions(), borderToXml(), and exportBorder().
columnsCount()
int BorderTitleBlock::columnsCount () const inline
Returns
the number of columns
Definition at line 55 of file bordertitleblock.h.
References columns_count_.
Referenced by borderToXml(), exportBorder(), and setColumnsCount().
columnsHeaderHeight()
qreal BorderTitleBlock::columnsHeaderHeight () const inline
Returns
the column headers height, in pixels
Definition at line 62 of file bordertitleblock.h.
References columns_header_height_.
Referenced by diagramHeight(), and exportBorder().
columnsRect()
QRectF BorderTitleBlock::columnsRect () const
BorderTitleBlock::columnsRect.
Returns
The columns rect in scene coordinate. If column is not displayed, return a null QRectF
Definition at line 143 of file bordertitleblock.cpp.
References columns_count_, columns_header_height_, columns_width_, display_columns_, Diagram::margin, and rows_header_width_.
Referenced by DiagramView::mouseDoubleClickEvent().
columnsTotalWidth()
qreal BorderTitleBlock::columnsTotalWidth () const inline
Returns
the total width of all columns, headers excluded
Definition at line 59 of file bordertitleblock.h.
References columns_count_, and columns_width_.
Referenced by diagramWidth().
columnsWidth()
qreal BorderTitleBlock::columnsWidth () const inline
Returns
the columns width, in pixels
Definition at line 57 of file bordertitleblock.h.
References columns_width_.
Referenced by borderToXml(), convertPosition(), exportBorder(), and setColumnsWidth().
convertPosition()
DiagramPosition BorderTitleBlock::convertPosition (const QPointF & pos)
BorderTitleBlock::convertPosition Convert a Point in cartesian coordinate (x : 12.5, 56.9) to a point in grid coordinate (ex : B2)
Parameters
pos : position to convert
Returns
the converted point in grid coordinate.
Definition at line 880 of file bordertitleblock.cpp.
References columnsWidth(), incrementLetters(), insideBorderRect(), and rowsHeight().
Referenced by Diagram::convertPosition().
date()
QDate BorderTitleBlock::date () const inline
Returns
the value of the title block "Date" field
Definition at line 109 of file bordertitleblock.h.
References btb_date_.
Referenced by exportTitleBlock(), and setDate().
diagramHeight()
qreal BorderTitleBlock::diagramHeight () const inline
diagramHeight
Returns
the diagram height, i.e. the height of the border without title block
Definition at line 89 of file bordertitleblock.h.
References columnsHeaderHeight(), and rowsTotalHeight().
Referenced by borderToXml(), and updateRectangles().
diagramTitleChanged
void BorderTitleBlock::diagramTitleChanged (const QString &) signal
diagramTitleChanged Signal emitted after the title has changed
Referenced by Diagram::Diagram(), and setTitle().
diagramWidth()
qreal BorderTitleBlock::diagramWidth () const inline
diagramWidth
Returns
the diagram width, i.e. the width of the border without title block
Definition at line 82 of file bordertitleblock.h.
References columnsTotalWidth(), and rowsHeaderWidth().
Referenced by updateRectangles().
displayBorder
void BorderTitleBlock::displayBorder (bool db) slot
BorderTitleBlock::displayBorder.
Parameters
db : true to display the border of the diagram, false otherwise
Note
: if the border display is deactivated, the rows and columns will not be drawn.
Definition at line 468 of file bordertitleblock.cpp.
References display_border_, and displayChanged().
Referenced by Diagram::applyProperties(), and Diagram::setBorderOptions().
displayChanged
void BorderTitleBlock::displayChanged () signal
displayChanged Signal emitted after display options have changed
Referenced by displayBorder(), displayColumns(), displayRows(), displayTitleBlock(), and importTitleBlock().
displayColumns
void BorderTitleBlock::displayColumns (bool dc) slot
BorderTitleBlock::displayColumns.
Parameters
dc : true to display the column headers, false otherwise
Definition at line 442 of file bordertitleblock.cpp.
References display_columns_, and displayChanged().
Referenced by borderFromXml(), importBorder(), and Diagram::setBorderOptions().
displayRows
void BorderTitleBlock::displayRows (bool dr) slot
BorderTitleBlock::displayRows.
Parameters
dr : true to display line headers, false otherwise
Definition at line 453 of file bordertitleblock.cpp.
References display_rows_, and displayChanged().
Referenced by borderFromXml(), and importBorder().
displayTitleBlock
void BorderTitleBlock::displayTitleBlock (bool di) slot
BorderTitleBlock::displayTitleBlock.
Parameters
di : true to display the title block, false otherwise
Definition at line 431 of file bordertitleblock.cpp.
References display_titleblock_, and displayChanged().
Referenced by Diagram::applyProperties(), and Diagram::setBorderOptions().
draw()
void BorderTitleBlock::draw (QPainter * painter)
BorderTitleBlock::draw Draw the border and the titleblock.
Parameters
painter : QPainter to use for draw this.
Definition at line 504 of file bordertitleblock.cpp.
References columns_count_, columns_header_height_, columns_width_, diagram_rect_, QETApp::diagramTextsFont(), display_border_, display_columns_, display_rows_, display_titleblock_, incrementLetters(), m_edge, m_titleblock_template_renderer, rows_count_, rows_header_width_, rows_height_, titleBlockRectForQPainter(), and translate().
Referenced by Diagram::drawBackground().
drawDxf()
void BorderTitleBlock::drawDxf (int width, int height, bool keep_aspect_ratio, QString & file_path, int color)
BorderTitleBlock::drawDxf.
Parameters
width
height
keep_aspect_ratio
file_path
color
Definition at line 615 of file bordertitleblock.cpp.
References columns_count_, columns_header_height_, columns_width_, diagram_rect_, display_border_, display_columns_, display_rows_, display_titleblock_, Createdxf::drawRectangle(), Createdxf::drawTextAligned(), incrementLetters(), m_titleblock_template_renderer, rows_count_, rows_header_width_, rows_height_, Createdxf::sheetHeight, titleBlockRect(), Createdxf::xScale, and Createdxf::yScale.
exportBorder()
BorderProperties BorderTitleBlock::exportBorder ()
BorderTitleBlock::exportBorder.
Returns
border properties
Definition at line 333 of file bordertitleblock.cpp.
References BorderProperties::columns_count, BorderProperties::columns_header_height, BorderProperties::columns_width, columnsAreDisplayed(), columnsCount(), columnsHeaderHeight(), columnsWidth(), BorderProperties::display_columns, BorderProperties::display_rows, BorderProperties::rows_count, BorderProperties::rows_header_width, BorderProperties::rows_height, rowsAreDisplayed(), rowsCount(), rowsHeaderWidth(), and rowsHeight().
Referenced by QETDiagramEditor::rowColumnGroupTriggered().
exportTitleBlock()
TitleBlockProperties BorderTitleBlock::exportTitleBlock ()
BorderTitleBlock::exportTitleBlock.
Returns
the properties of the titleblock
Definition at line 279 of file bordertitleblock.cpp.
References additional_fields_, TitleBlockProperties::author, author(), TitleBlockProperties::auto_page_num, autoPageNum(), TitleBlockProperties::collection, TitleBlockProperties::context, TitleBlockProperties::date, date(), TitleBlockProperties::display_at, QET::Embedded, TitleBlockProperties::filename, fileName(), TitleBlockProperties::folio, folio(), TitleBlockProperties::indexrev, indexrev(), TitleBlockProperties::locmach, locmach(), m_edge, TitleBlockProperties::plant, plant(), TitleBlockProperties::template_name, TitleBlockProperties::title, title(), titleBlockTemplateName(), TitleBlockProperties::version, and version().
Referenced by DiagramView::handleTitleBlockDrop(), SearchAndReplaceWorker::replaceAdvanced(), SearchAndReplaceWidget::searchTerms(), and titleBlockToXml().
fileName()
QString BorderTitleBlock::fileName () const inline
Returns
the value of the title block "File" field
Definition at line 123 of file bordertitleblock.h.
References btb_filename_.
Referenced by exportTitleBlock().
finalfolio()
QString BorderTitleBlock::finalfolio () const inline
Returns
the value of the title block "Folio" field as displayed
Definition at line 115 of file bordertitleblock.h.
References btb_final_folio_.
Referenced by GenericPanel::updateDiagramItem().
folio()
QString BorderTitleBlock::folio () const inline
Returns
the value of the title block "Folio" field
Definition at line 113 of file bordertitleblock.h.
References btb_folio_.
Referenced by exportTitleBlock(), DynamicElementTextItem::setConnectionForReportFormula(), setFolio(), DynamicElementTextItem::setupFormulaConnection(), and ProjectView::updateTabTitle().
folioTotal()
int BorderTitleBlock::folioTotal () const inline
Returns
the value of the total number of folios
Definition at line 132 of file bordertitleblock.h.
References folio_total_.
importBorder()
void BorderTitleBlock::importBorder (const BorderProperties & bp)
BorderTitleBlock::importBorder.
Parameters
bp : the new properties of the border
Definition at line 351 of file bordertitleblock.cpp.
References BorderProperties::columns_count, BorderProperties::columns_header_height, BorderProperties::columns_width, BorderProperties::display_columns, BorderProperties::display_rows, displayColumns(), displayRows(), BorderProperties::rows_count, BorderProperties::rows_header_width, BorderProperties::rows_height, setColumnsCount(), setColumnsHeaderHeight(), setColumnsWidth(), setRowsCount(), setRowsHeaderWidth(), and setRowsHeight().
Referenced by QETProject::addNewDiagram(), and BorderTitleBlock().
importTitleBlock()
void BorderTitleBlock::importTitleBlock (const TitleBlockProperties & ip)
BorderTitleBlock::importTitleBlock.
Parameters
ip the new properties of titleblock
Definition at line 304 of file bordertitleblock.cpp.
References additional_fields_, TitleBlockProperties::author, TitleBlockProperties::auto_page_num, TitleBlockProperties::context, TitleBlockProperties::date, TitleBlockProperties::display_at, displayChanged(), QET::displayedVersion, TitleBlockProperties::filename, TitleBlockProperties::folio, TitleBlockProperties::indexrev, TitleBlockProperties::locmach, m_edge, needFolioData(), needTitleBlockTemplate(), TitleBlockProperties::plant, setAuthor(), setAutoPageNum(), setDate(), setFileName(), setFolio(), setIndicerev(), setLocMach(), setPlant(), setTitle(), setVersion(), TitleBlockProperties::template_name, and TitleBlockProperties::title.
Referenced by QETProject::addNewDiagram(), BorderTitleBlock(), and titleBlockFromXml().
incrementLetters()
QString BorderTitleBlock::incrementLetters (const QString & string) private
BorderTitleBlock::incrementLetters increments string with Letters A to Z.
Parameters
string
Returns
string ++Letters eg:
A-> B
Z -> AA
Definition at line 980 of file bordertitleblock.cpp.
Referenced by convertPosition(), draw(), and drawDxf().
indexrev()
QString BorderTitleBlock::indexrev () const inline
Returns
the value of the revision index block "Folio" field
Definition at line 121 of file bordertitleblock.h.
References btb_indexrev_.
Referenced by exportTitleBlock(), and setIndicerev().
insideBorderRect()
QRectF BorderTitleBlock::insideBorderRect () const
BorderTitleBlock::insideBorderRect.
Returns
The rect of the inside border, in other word, the drawing area. This method take care about if rows or columns are displayed or not. The rect is in scene coordinate
Definition at line 185 of file bordertitleblock.cpp.
References columns_count_, columns_header_height_, columns_width_, display_columns_, display_rows_, Diagram::margin, rows_count_, rows_header_width_, and rows_height_.
Referenced by QetGraphicsTableItem::adjustTableToFolio(), convertPosition(), Diagram::drawBackground(), and DiagramEventAddShape::updateHelpCross().
locmach()
QString BorderTitleBlock::locmach () const inline
Returns
the value of the title block "Locmach" field
Definition at line 119 of file bordertitleblock.h.
References btb_locmach_.
Referenced by exportTitleBlock(), and setLocMach().
needFolioData
void BorderTitleBlock::needFolioData () signal
needFolioData Signal emitted when the title block requires its data to be updated in order to generate the folio field.
Referenced by QETProject::addDiagram(), and importTitleBlock().
needTitleBlockTemplate
void BorderTitleBlock::needTitleBlockTemplate (const QString &) signal
needTitleBlockTemplate Signal emitted when this object needs to set a specific title block template. This object cannot handle the job since it does not know of its parent project.
Referenced by Diagram::Diagram(), and importTitleBlock().
outsideBorderRect()
QRectF BorderTitleBlock::outsideBorderRect () const
BorderTitleBlock::outsideBorderRect.
Returns
The rect of outside border (diagram with columns and rows) The rect is in scene coordinate
Definition at line 171 of file bordertitleblock.cpp.
References columns_count_, columns_header_height_, columns_width_, Diagram::margin, rows_count_, rows_header_width_, and rows_height_.
plant()
QString BorderTitleBlock::plant () const inline
Returns
the value of the title block "Plant" field
Definition at line 117 of file bordertitleblock.h.
References btb_plant_.
Referenced by exportTitleBlock(), and setPlant().
rowsAreDisplayed()
bool BorderTitleBlock::rowsAreDisplayed () const inline
Returns
true si les entetes des lignes sont affiches, false sinon
Definition at line 143 of file bordertitleblock.h.
References display_rows_.
Referenced by borderToXml(), and exportBorder().
rowsCount()
int BorderTitleBlock::rowsCount () const inline
Returns
the number of rows
Definition at line 67 of file bordertitleblock.h.
References rows_count_.
Referenced by borderToXml(), exportBorder(), and setRowsCount().
rowsHeaderWidth()
qreal BorderTitleBlock::rowsHeaderWidth () const inline
Returns
la rows header width, in pixels
Definition at line 74 of file bordertitleblock.h.
References rows_header_width_.
Referenced by diagramWidth(), and exportBorder().
rowsHeight()
qreal BorderTitleBlock::rowsHeight () const inline
Returns
the rows height, in pixels
Definition at line 69 of file bordertitleblock.h.
References rows_height_.
Referenced by borderToXml(), convertPosition(), exportBorder(), and setRowsHeight().
rowsRect()
QRectF BorderTitleBlock::rowsRect () const
BorderTitleBlock::rowsRect.
Returns
The rows rect in scene coordinate. If row is not displayed, return a null QRectF
Definition at line 157 of file bordertitleblock.cpp.
References columns_header_height_, display_rows_, Diagram::margin, rows_count_, rows_header_width_, and rows_height_.
Referenced by DiagramView::mouseDoubleClickEvent().
rowsTotalHeight()
qreal BorderTitleBlock::rowsTotalHeight () const inline
Returns
the total height of all rows, headers excluded
Definition at line 71 of file bordertitleblock.h.
References rows_count_, and rows_height_.
Referenced by diagramHeight().
setAuthor()
void BorderTitleBlock::setAuthor (const QString & author)
BorderTitleBlock::setAuthor.
Parameters
author the new value of the "Author" field
Definition at line 900 of file bordertitleblock.cpp.
References author(), and btb_author_.
Referenced by importTitleBlock().
setAutoPageNum()
void BorderTitleBlock::setAutoPageNum (const QString & auto_page_num)
BorderTitleBlock::setAutoPageNum.
Parameters
auto_page_num the new value of the "auto_page_num" field
Definition at line 1083 of file bordertitleblock.cpp.
References btb_auto_page_num_.
Referenced by importTitleBlock().
setColumnsCount()
void BorderTitleBlock::setColumnsCount (int nb_c)
BorderTitleBlock::setColumnsCount Allows you to change the number of columns. If this number of columns is less than the minimum required, it is this minimum which is used.
Parameters
nb_c : new number of columns
See also
minNbColumns()
Definition at line 765 of file bordertitleblock.cpp.
References columns_count_, columnsCount(), MIN_COLUMN_COUNT, and updateRectangles().
Referenced by borderFromXml(), and importBorder().
setColumnsHeaderHeight()
void BorderTitleBlock::setColumnsHeaderHeight (const qreal & new_chh)
BorderTitleBlock::setColumnsHeaderHeight Change the height of the headers containing the column numbers. This must remain between 5 and 50 px.
Parameters
new_chh : new height of column headers
Definition at line 800 of file bordertitleblock.cpp.
References columns_header_height_, and updateRectangles().
Referenced by importBorder().
setColumnsWidth()
void BorderTitleBlock::setColumnsWidth (const qreal & new_cw)
BorderTitleBlock::setColumnsWidth Change the width of the columns. If the width indicated is less than the minimum required, it is this minimum which is used.
Parameters
new_cw : new column width
See also
minColumnsWidth()
Definition at line 784 of file bordertitleblock.cpp.
References columns_width_, columnsWidth(), MIN_COLUMN_WIDTH, and updateRectangles().
Referenced by borderFromXml(), and importBorder().
setDate()
void BorderTitleBlock::setDate (const QDate & date)
BorderTitleBlock::setDate.
Parameters
date the new value of the "Date" field
Definition at line 908 of file bordertitleblock.cpp.
References btb_date_, and date().
Referenced by importTitleBlock().
setDiagramHeight()
void BorderTitleBlock::setDiagramHeight (const qreal & height)
BorderTitleBlock::setDiagramHeight This method tries to get as close as possible to the given height as a parameter by modifying the number of rows in progress.
Parameters
height :
Definition at line 867 of file bordertitleblock.cpp.
References rows_height_, and setRowsCount().
Referenced by borderFromXml().
setFileName()
void BorderTitleBlock::setFileName (const QString & filename)
BorderTitleBlock::setFileName.
Parameters
filename the new value of the "filename" field
Definition at line 1067 of file bordertitleblock.cpp.
References btb_filename_.
Referenced by importTitleBlock().
setFolio()
void BorderTitleBlock::setFolio (const QString & folio)
BorderTitleBlock::setFolio.
Parameters
folio the new value of the "Folio" field
Definition at line 929 of file bordertitleblock.cpp.
References btb_folio_, folio(), and titleBlockFolioChanged().
Referenced by importTitleBlock().
setFolioData()
void BorderTitleBlock::setFolioData (int index, int total, const QString & autonum = nullptr, const DiagramContext & project_properties = DiagramContext())
BorderTitleBlock::setFolioData.
Parameters
index : schema number (from 1 to total)
total : total number of diagrams in the project
autonum :
project_properties : Project-wide properties, to be merged with diagram-wide ones.
Definition at line 1013 of file bordertitleblock.cpp.
References btb_final_folio_, btb_folio_, folio_index_, folio_total_, and updateDiagramContextForTitleBlock().
Referenced by BorderTitleBlock().
setIndicerev()
void BorderTitleBlock::setIndicerev (const QString & indexrev)
BorderTitleBlock::setIndicerev.
Parameters
indexrev the new value of the "indexrev" field
Definition at line 1059 of file bordertitleblock.cpp.
References btb_indexrev_, and indexrev().
Referenced by importTitleBlock().
setLocMach()
void BorderTitleBlock::setLocMach (const QString & locmach)
BorderTitleBlock::setLocMach.
Parameters
locmach the new value of the "locmach" field
Definition at line 1051 of file bordertitleblock.cpp.
References btb_locmach_, and locmach().
Referenced by importTitleBlock().
setNextFolioNum()
void BorderTitleBlock::setNextFolioNum (const QString & next)
BorderTitleBlock::setNextFolioNum.
Parameters
next the new value of the "next-folio-num" field
Definition at line 1103 of file bordertitleblock.cpp.
References DiagramContext::addValue(), TitleBlockTemplateRenderer::context(), m_next_folio_num, m_titleblock_template_renderer, and TitleBlockTemplateRenderer::setContext().
setPlant()
void BorderTitleBlock::setPlant (const QString & plant)
BorderTitleBlock::setPlant.
Parameters
plant the new value of the "plant" field
Definition at line 1043 of file bordertitleblock.cpp.
References btb_plant_, and plant().
Referenced by importTitleBlock().
setPreviousFolioNum()
void BorderTitleBlock::setPreviousFolioNum (const QString & previous)
BorderTitleBlock::setPreviousFolioNum.
Parameters
previous the new value of the "previous-folio-num" field
Definition at line 1091 of file bordertitleblock.cpp.
References DiagramContext::addValue(), TitleBlockTemplateRenderer::context(), m_previous_folio_num, m_titleblock_template_renderer, and TitleBlockTemplateRenderer::setContext().
setRowsCount()
void BorderTitleBlock::setRowsCount (int nb_r)
BorderTitleBlock::setRowsCount Allows you to change the number of lines. If this number of lines is lower than the minimum required, this function does nothing.
Parameters
nb_r : new number of lines
See also
minNbRows()
Definition at line 818 of file bordertitleblock.cpp.
References MIN_ROW_COUNT, rows_count_, rowsCount(), and updateRectangles().
Referenced by borderFromXml(), importBorder(), and setDiagramHeight().
setRowsHeaderWidth()
void BorderTitleBlock::setRowsHeaderWidth (const qreal & new_rhw)
BorderTitleBlock::setRowsHeaderWidth Change the width of the headers containing the line numbers. This must remain between 5 and 50 px.
Parameters
new_rhw : new width of line headers
Definition at line 853 of file bordertitleblock.cpp.
References rows_header_width_, and updateRectangles().
Referenced by importBorder().
setRowsHeight()
void BorderTitleBlock::setRowsHeight (const qreal & new_rh)
BorderTitleBlock::setRowsHeight Change the height of the lines. If the indicated height is lower than the minimum required, it is this minimum which is used.
Parameters
new_rh : new row height
See also
minRowsHeight()
Definition at line 837 of file bordertitleblock.cpp.
References MIN_ROW_HEIGHT, rows_height_, rowsHeight(), and updateRectangles().
Referenced by borderFromXml(), and importBorder().
setTitle()
void BorderTitleBlock::setTitle (const QString & title)
BorderTitleBlock::setTitle.
Parameters
title the new value of the "Title" field
Definition at line 916 of file bordertitleblock.cpp.
References btb_title_, diagramTitleChanged(), and title().
Referenced by importTitleBlock().
setTitleBlockTemplate()
void BorderTitleBlock::setTitleBlockTemplate (const TitleBlockTemplate * titleblock_template)
BorderTitleBlock::setTitleBlockTemplate.
Parameters
titleblock_template The new titleblock template to use to render the titleblock
See also
TitleBlockTemplateRenderer::setTitleBlockTemplate()
Definition at line 377 of file bordertitleblock.cpp.
References m_titleblock_template_renderer.
Referenced by BorderTitleBlock(), and titleBlockTemplateRemoved().
setVersion()
void BorderTitleBlock::setVersion (const QString & version)
BorderTitleBlock::setVersion.
Parameters
version the new value of the "version" field
Definition at line 1075 of file bordertitleblock.cpp.
References btb_version_, and version().
Referenced by importTitleBlock().
slot_setAutoPageNum
void BorderTitleBlock::slot_setAutoPageNum (QString pageAutoNum) slot
BorderTitleBlock::slot_setAutoPageNum.
Parameters
pageAutoNum : Set Page (Folio) Auto Num
Definition at line 479 of file bordertitleblock.cpp.
References btb_auto_page_num_.
title()
QString BorderTitleBlock::title () const inline
Returns
the value of the title block "Title" field
Definition at line 111 of file bordertitleblock.h.
References btb_title_.
Referenced by exportTitleBlock(), setTitle(), and Diagram::title().
titleBlockFolioChanged
void BorderTitleBlock::titleBlockFolioChanged (const QString &) signal
titleBlockFolioChanged Signal emitted after Folio has changed
Referenced by Diagram::Diagram(), ProjectView::diagramAdded(), DynamicElementTextItem::removeConnectionForReportFormula(), DynamicElementTextItem::setConnectionForReportFormula(), setFolio(), and DynamicElementTextItem::setupFormulaConnection().
titleBlockFromXml()
void BorderTitleBlock::titleBlockFromXml (const QDomElement & xml_elmt)
BorderTitleBlock::titleBlockFromXml Reads the title block values from XML.
Parameters
xml_elmt the XML element values will be read from
Definition at line 212 of file bordertitleblock.cpp.
References TitleBlockProperties::fromXml(), and importTitleBlock().
Referenced by Diagram::fromXml().
titleblockInformation()
DiagramContext BorderTitleBlock::titleblockInformation () const
BorderTitleBlock::titleblockInformation.
Returns
Definition at line 99 of file bordertitleblock.cpp.
References TitleBlockTemplateRenderer::context(), and m_titleblock_template_renderer.
Referenced by projectDataBase::addDiagram().
titleBlockIsDisplayed()
bool BorderTitleBlock::titleBlockIsDisplayed () const inline
Returns
true si le cartouche est affiche, false sinon
Definition at line 136 of file bordertitleblock.h.
References display_titleblock_.
Referenced by Diagram::applyProperties(), and Diagram::borderOptions().
titleBlockRect()
QRectF BorderTitleBlock::titleBlockRect () const
BorderTitleBlock::titleBlockRect.
Returns
the rectangle of the titleblock in scene coordinate.
Definition at line 81 of file bordertitleblock.cpp.
References diagram_rect_, m_edge, and m_titleblock_template_renderer.
Referenced by borderAndTitleBlockRect(), drawDxf(), DiagramView::mouseDoubleClickEvent(), and titleBlockRectForQPainter().
titleBlockRectForQPainter()
QRectF BorderTitleBlock::titleBlockRectForQPainter () const private
BorderTitleBlock::titleBlockRectForQPainter.
Returns
The title block rect to use with the QPainter in the method draw. The returned rect is alway horizontal (like displayed at the bottom of rect) only the top left change of pos according to the edge where the title block need to be displayed. Rect according to edge: Bottom : top left is at the bottom left edge of the diagram rect. Right : top left is at the bottom right of diagram rect. Befor use this rect you need to rotate the QPainter by -90 for snap the rect at the right edge of diagram.
Definition at line 115 of file bordertitleblock.cpp.
References diagram_rect_, m_edge, m_titleblock_template_renderer, and titleBlockRect().
Referenced by draw().
titleBlockTemplate()
const TitleBlockTemplate * BorderTitleBlock::titleBlockTemplate ()
BorderTitleBlock::titleBlockTemplate.
Returns
the titleblock template used to render the titleblock
See also
TitleBlockTemplateRenderer::titleBlockTemplate()
Definition at line 367 of file bordertitleblock.cpp.
References m_titleblock_template_renderer.
Referenced by titleBlockTemplateName().
titleBlockTemplateChanged
void BorderTitleBlock::titleBlockTemplateChanged (const QString & template_name) slot
BorderTitleBlock::titleBlockTemplateChanged This slot may be used to inform this class that the given title block template has changed. The title block-dedicated rendering cache will thus be flushed.
Parameters
template_name : Name of the title block template that has changed
Definition at line 399 of file bordertitleblock.cpp.
References m_titleblock_template_renderer, and titleBlockTemplateName().
Referenced by Diagram::titleBlockTemplateChanged().
titleBlockTemplateName()
QString BorderTitleBlock::titleBlockTemplateName () const
BorderTitleBlock::titleBlockTemplateName.
Returns
The name of the template used to render the titleblock.
Definition at line 387 of file bordertitleblock.cpp.
References m_titleblock_template_renderer, and titleBlockTemplate().
Referenced by exportTitleBlock(), Diagram::setTitleBlockTemplate(), titleBlockTemplateChanged(), Diagram::titleBlockTemplateChanged(), titleBlockTemplateRemoved(), Diagram::titleBlockTemplateRemoved(), and Diagram::usesTitleBlockTemplate().
titleBlockTemplateRemoved
void BorderTitleBlock::titleBlockTemplateRemoved (const QString & removed_template_name, const TitleBlockTemplate * new_template = nullptr) slot
BorderTitleBlock::titleBlockTemplateRemoved This slot has to be used to inform this class that the given title block template is about to be removed and is no longer accessible. This class will either use the provided optional TitleBlockTemplate or the default title block provided by QETApp::defaultTitleBlockTemplate()
Parameters
removed_template_name : Name of the title block template that has changed
new_template (Optional) title block template to use instead
Definition at line 414 of file bordertitleblock.cpp.
References QETApp::defaultTitleBlockTemplate(), setTitleBlockTemplate(), and titleBlockTemplateName().
Referenced by Diagram::setTitleBlockTemplate(), and Diagram::titleBlockTemplateRemoved().
titleBlockToXml()
void BorderTitleBlock::titleBlockToXml (QDomElement & xml_elmt)
BorderTitleBlock::titleBlockToXml Exports the title block current values to XML.
Parameters
xml_elmt the XML element attributes will be added to
Definition at line 203 of file bordertitleblock.cpp.
References exportTitleBlock(), and TitleBlockProperties::toXml().
Referenced by Diagram::toXml().
updateDiagramContextForTitleBlock()
void BorderTitleBlock::updateDiagramContextForTitleBlock (const DiagramContext & initial_context = DiagramContext()) private
BorderTitleBlock::updateDiagramContextForTitleBlock Update the informations given to the titleblock template by regenerating a DiagramContext object.
Parameters
initial_context : Base diagram context that will be overridden by diagram-wide values
Definition at line 942 of file bordertitleblock.cpp.
References additional_fields_, DiagramContext::addValue(), btb_author_, btb_auto_page_num_, btb_date_, btb_filename_, btb_final_folio_, btb_indexrev_, btb_locmach_, btb_plant_, btb_title_, btb_version_, folio_index_, folio_total_, DiagramContext::keys(), m_next_folio_num, m_previous_folio_num, and m_titleblock_template_renderer.
Referenced by setFolioData().
updateRectangles()
void BorderTitleBlock::updateRectangles () private
BorderTitleBlock::updateRectangles This method update the diagram rect according to the value of rows and columns (number and size)
Definition at line 488 of file bordertitleblock.cpp.
References borderChanged(), diagram_rect_, diagramHeight(), diagramWidth(), and Diagram::margin.
Referenced by borderFromXml(), BorderTitleBlock(), setColumnsCount(), setColumnsHeaderHeight(), setColumnsWidth(), setRowsCount(), setRowsHeaderWidth(), and setRowsHeight().
version()
QString BorderTitleBlock::version () const inline
Returns
the value of the title block Additional Fields
Definition at line 125 of file bordertitleblock.h.
References btb_version_.
Referenced by exportTitleBlock(), and setVersion().
Member Data Documentation
additional_fields_
DiagramContext BorderTitleBlock::additional_fields_ private
titleblock additional fields
Definition at line 263 of file bordertitleblock.h.
Referenced by additionalFields(), exportTitleBlock(), importTitleBlock(), and updateDiagramContextForTitleBlock().
btb_author_
QString BorderTitleBlock::btb_author_ private
titleblock author
Definition at line 249 of file bordertitleblock.h.
Referenced by author(), setAuthor(), and updateDiagramContextForTitleBlock().
btb_auto_page_num_
QString BorderTitleBlock::btb_auto_page_num_ private
titleblock auto page num
Definition at line 257 of file bordertitleblock.h.
Referenced by autoPageNum(), setAutoPageNum(), slot_setAutoPageNum(), and updateDiagramContextForTitleBlock().
btb_date_
QDate BorderTitleBlock::btb_date_ private
titleblock date
Definition at line 250 of file bordertitleblock.h.
Referenced by date(), setDate(), and updateDiagramContextForTitleBlock().
btb_filename_
QString BorderTitleBlock::btb_filename_ private
titleblock filename
Definition at line 260 of file bordertitleblock.h.
Referenced by fileName(), setFileName(), and updateDiagramContextForTitleBlock().
btb_final_folio_
QString BorderTitleBlock::btb_final_folio_ private
titleblock final folio
Definition at line 256 of file bordertitleblock.h.
Referenced by finalfolio(), setFolioData(), and updateDiagramContextForTitleBlock().
btb_folio_
QString BorderTitleBlock::btb_folio_ private
titleblock folio
Definition at line 252 of file bordertitleblock.h.
Referenced by folio(), setFolio(), and setFolioData().
btb_indexrev_
QString BorderTitleBlock::btb_indexrev_ private
titleblock index rev
Definition at line 255 of file bordertitleblock.h.
Referenced by indexrev(), setIndicerev(), and updateDiagramContextForTitleBlock().
btb_locmach_
QString BorderTitleBlock::btb_locmach_ private
titleblock locmach
Definition at line 254 of file bordertitleblock.h.
Referenced by locmach(), setLocMach(), and updateDiagramContextForTitleBlock().
btb_plant_
QString BorderTitleBlock::btb_plant_ private
titleblock plant
Definition at line 253 of file bordertitleblock.h.
Referenced by plant(), setPlant(), and updateDiagramContextForTitleBlock().
btb_title_
QString BorderTitleBlock::btb_title_ private
titleblock title
Definition at line 251 of file bordertitleblock.h.
Referenced by setTitle(), title(), and updateDiagramContextForTitleBlock().
btb_version_
QString BorderTitleBlock::btb_version_ private
titleblock version
Definition at line 261 of file bordertitleblock.h.
Referenced by setVersion(), updateDiagramContextForTitleBlock(), and version().
columns_count_
int BorderTitleBlock::columns_count_ private
columns count
Definition at line 270 of file bordertitleblock.h.
Referenced by columnsCount(), columnsRect(), columnsTotalWidth(), draw(), drawDxf(), insideBorderRect(), outsideBorderRect(), and setColumnsCount().
columns_header_height_
qreal BorderTitleBlock::columns_header_height_ private
columns header height
Definition at line 272 of file bordertitleblock.h.
Referenced by columnsHeaderHeight(), columnsRect(), draw(), drawDxf(), insideBorderRect(), outsideBorderRect(), rowsRect(), and setColumnsHeaderHeight().
columns_width_
qreal BorderTitleBlock::columns_width_ private
columns width
Definition at line 271 of file bordertitleblock.h.
Referenced by columnsRect(), columnsTotalWidth(), columnsWidth(), draw(), drawDxf(), insideBorderRect(), outsideBorderRect(), and setColumnsWidth().
diagram_rect_
QRectF BorderTitleBlock::diagram_rect_ private
Definition at line 283 of file bordertitleblock.h.
Referenced by borderAndTitleBlockRect(), draw(), drawDxf(), titleBlockRect(), titleBlockRectForQPainter(), and updateRectangles().
display_border_
bool BorderTitleBlock::display_border_ private
Definition at line 289 of file bordertitleblock.h.
Referenced by borderIsDisplayed(), BorderTitleBlock(), displayBorder(), draw(), and drawDxf().
display_columns_
bool BorderTitleBlock::display_columns_ private
Definition at line 287 of file bordertitleblock.h.
Referenced by columnsAreDisplayed(), columnsRect(), displayColumns(), draw(), drawDxf(), and insideBorderRect().
display_rows_
bool BorderTitleBlock::display_rows_ private
Definition at line 288 of file bordertitleblock.h.
Referenced by displayRows(), draw(), drawDxf(), insideBorderRect(), rowsAreDisplayed(), and rowsRect().
display_titleblock_
bool BorderTitleBlock::display_titleblock_ private
Definition at line 286 of file bordertitleblock.h.
Referenced by BorderTitleBlock(), displayTitleBlock(), draw(), drawDxf(), and titleBlockIsDisplayed().
folio_index_
int BorderTitleBlock::folio_index_ private
titleblock index
Definition at line 258 of file bordertitleblock.h.
Referenced by setFolioData(), and updateDiagramContextForTitleBlock().
folio_total_
int BorderTitleBlock::folio_total_ private
titleblock total
Definition at line 259 of file bordertitleblock.h.
Referenced by folioTotal(), setFolioData(), and updateDiagramContextForTitleBlock().
m_edge
Qt::Edge BorderTitleBlock::m_edge private
titleblock edge
Definition at line 264 of file bordertitleblock.h.
Referenced by draw(), exportTitleBlock(), importTitleBlock(), titleBlockRect(), and titleBlockRectForQPainter().
m_next_folio_num
QString BorderTitleBlock::m_next_folio_num private
titleblock next folio num
Definition at line 265 of file bordertitleblock.h.
Referenced by setNextFolioNum(), and updateDiagramContextForTitleBlock().
m_previous_folio_num
QString BorderTitleBlock::m_previous_folio_num private
titleblock previous folio num
Definition at line 266 of file bordertitleblock.h.
Referenced by setPreviousFolioNum(), and updateDiagramContextForTitleBlock().
m_titleblock_template_renderer
TitleBlockTemplateRenderer* BorderTitleBlock::m_titleblock_template_renderer private
Definition at line 290 of file bordertitleblock.h.
Referenced by BorderTitleBlock(), draw(), drawDxf(), setNextFolioNum(), setPreviousFolioNum(), setTitleBlockTemplate(), titleblockInformation(), titleBlockRect(), titleBlockRectForQPainter(), titleBlockTemplate(), titleBlockTemplateChanged(), titleBlockTemplateName(), and updateDiagramContextForTitleBlock().
rows_count_
int BorderTitleBlock::rows_count_ private
rows count
Definition at line 275 of file bordertitleblock.h.
Referenced by draw(), drawDxf(), insideBorderRect(), outsideBorderRect(), rowsCount(), rowsRect(), rowsTotalHeight(), and setRowsCount().
rows_header_width_
qreal BorderTitleBlock::rows_header_width_ private
rows header width
Definition at line 277 of file bordertitleblock.h.
Referenced by columnsRect(), draw(), drawDxf(), insideBorderRect(), outsideBorderRect(), rowsHeaderWidth(), rowsRect(), and setRowsHeaderWidth().
rows_height_
qreal BorderTitleBlock::rows_height_ private
rows height
Definition at line 276 of file bordertitleblock.h.
Referenced by draw(), drawDxf(), insideBorderRect(), outsideBorderRect(), rowsHeight(), rowsRect(), rowsTotalHeight(), setDiagramHeight(), and setRowsHeight().
titleblock_height_
qreal BorderTitleBlock::titleblock_height_ private
Definition at line 280 of file bordertitleblock.h.
The documentation for this class was generated from the following files:
bordertitleblock.h
bordertitleblock.cpp