QElectroTech: NewConductorPotentialSelector Class Reference
NewConductorPotentialSelector Class Reference
The NewConductorPotentialSelector class Use for get the conductor propertie when two potentials is linked by a conductor.
Public Member Functions
NewConductorPotentialSelector (Conductor *conductor)
bool isValid () const override
void getPotential (Terminal *terminal, autonum::sequentialNumbers &seq_num, int &number, QList< ConductorProperties > &properties_list, QList< Conductor * > &c_list)
getPotential Get the conductor propertie of the potential at terminal, and the number of wire in this potential.
~NewConductorPotentialSelector () override
Public Member Functions inherited from AbstractPotentialSelector
AbstractPotentialSelector ()
virtual ~AbstractPotentialSelector ()
Private Attributes
bool m_is_valid
Additional Inherited Members
Public Attributes inherited from AbstractPotentialSelector
autonum::sequentialNumbers m_seq_num_1
autonum::sequentialNumbers m_seq_num_2
int m_conductor_number_1
int m_conductor_number_2
QList< ConductorProperties > m_properties_list_1
QList< ConductorProperties > m_properties_list_2
QList< Conductor * > m_conductors_list_1
QList< Conductor * > m_conductors_list_2
Detailed Description
The NewConductorPotentialSelector class Use for get the conductor propertie when two potentials is linked by a conductor.
Definition at line 36 of file potentialselectordialog.cpp.
Constructor & Destructor Documentation
NewConductorPotentialSelector()
NewConductorPotentialSelector::NewConductorPotentialSelector (Conductor * conductor) inline
Definition at line 39 of file potentialselectordialog.cpp.
References Terminal::addConductor(), getPotential(), AbstractPotentialSelector::m_conductor_number_1, AbstractPotentialSelector::m_conductor_number_2, AbstractPotentialSelector::m_conductors_list_1, AbstractPotentialSelector::m_conductors_list_2, m_is_valid, AbstractPotentialSelector::m_properties_list_1, AbstractPotentialSelector::m_properties_list_2, AbstractPotentialSelector::m_seq_num_1, AbstractPotentialSelector::m_seq_num_2, Terminal::removeConductor(), Conductor::terminal1, and Conductor::terminal2.
~NewConductorPotentialSelector()
NewConductorPotentialSelector::~NewConductorPotentialSelector () inline override
Definition at line 131 of file potentialselectordialog.cpp.
Member Function Documentation
getPotential()
void NewConductorPotentialSelector::getPotential (Terminal * terminal, autonum::sequentialNumbers & seq_num, int & number, QList< ConductorProperties > & properties_list, QList< Conductor * > & c_list) inline
getPotential Get the conductor propertie of the potential at terminal, and the number of wire in this potential.
Parameters
terminal
seq_num
number
properties_list
c_list
Definition at line 82 of file potentialselectordialog.cpp.
References Element::AllReport, Terminal::conductors(), Element::isFree(), Element::linkedElements(), Element::linkType(), Terminal::parentElement(), Conductor::properties, Conductor::relatedPotentialConductors(), Conductor::sequenceNum, Element::Terminale, and Element::terminals().
Referenced by NewConductorPotentialSelector().
isValid()
bool NewConductorPotentialSelector::isValid () const inline override virtual
Implements AbstractPotentialSelector.
Definition at line 70 of file potentialselectordialog.cpp.
References m_is_valid.
Member Data Documentation
m_is_valid
bool NewConductorPotentialSelector::m_is_valid private
Definition at line 134 of file potentialselectordialog.cpp.
Referenced by isValid(), and NewConductorPotentialSelector().
The documentation for this class was generated from the following file:
potentialselectordialog.cpp