QElectroTech: ElementsLocation Class Reference
ElementsLocation Class Reference
The ElementsLocation class This class represents the location, the location of an element or of a category, even of a collection ... in a collection. She encapsulates a virtual path.
#include <elementslocation.h>
Public Member Functions
ElementsLocation ()
ElementsLocation::ElementsLocation Constructor.
ElementsLocation (const QString &path, QETProject *project=nullptr)
ElementsLocation::ElementsLocation.
ElementsLocation (const ElementsLocation &)
ElementsLocation::ElementsLocation The copy constructor.
ElementsLocation (const QMimeData *data)
ElementsLocation::ElementLocation Constructor, build an ElementLocation from a QMimeData, the mime data format must be "application/x-qet-element-uri" or "application/x-qet-category-uri". This location can be null even if format is valid.
virtual ~ElementsLocation ()
ElementsLocation::~ElementsLocation Destructeur.
ElementsLocation & operator= (const ElementsLocation &)
ElementsLocation::operator = Assignment operator.
bool operator== (const ElementsLocation &) const
ElementsLocation::operator ==.
bool operator!= (const ElementsLocation &) const
ElementsLocation::operator != Operateur de comparaison.
QString baseName () const
ElementsLocation::baseName.
QString collectionPath (bool protocol=true) const
ElementsLocation::collectionPath Return the path of the represented element relative to collection if protocol is true the path is prepended by the collection type (common://, custom:// or embed://) else if false, only the collection path is returned without the collection type.
QString projectCollectionPath () const
ElementsLocation::projectCollectionPath.
QString fileSystemPath () const
ElementsLocation::fileSystemPath.
QString path () const
ElementsLocation::path.
void setPath (const QString &path)
ElementsLocation::setPath Set the path of this item. The path can be relative to a collection (start by common:// , custom:// or embed://) or not.
bool addToPath (const QString &)
ElementsLocation::addToPath Add a string to the actual path of this location.
ElementsLocation parent () const
ElementsLocation::parent.
QETProject * project () const
ElementsLocation::project.
void setProject (QETProject *)
ElementsLocation::setProject.
bool isNull () const
ElementsLocation::isNull.
QString toString () const
ElementsLocation::toString.
bool isElement () const
ElementsLocation::isElement.
bool isDirectory () const
ElementsLocation::isDirectory.
bool isFileSystem () const
ElementsLocation::isFileSystem.
bool isCommonCollection () const
ElementsLocation::isCommonCollection.
bool isCustomCollection () const
ElementsLocation::isCustomCollection.
bool isProject () const
ElementsLocation::isProject.
bool exist () const
ElementsLocation::exist.
bool isWritable () const
ElementsLocation::isWritable.
XmlElementCollection * projectCollection () const
ElementsLocation::projectCollection.
NamesList nameList ()
ElementsLocation::nameList.
QDomElement xml () const
ElementsLocation::xml.
pugi::xml_document pugiXml () const
ElementsLocation::pugiXml.
bool setXml (const QDomDocument &xml_document) const
ElementsLocation::setXml Replace the current xml description by xml_document; The document element of xml_document must have tagname "definition" to be written This definition must be writable.
QUuid uuid () const
ElementsLocation::uuid.
QIcon icon () const
ElementLocation::icon.
QString name () const
ElementLocation::name.
QString fileName () const
ElementLocation::fileName.
DiagramContext elementInformations () const
ElementsLocation::elementInformations.
Static Public Attributes
static int MetaTypeId = qRegisterMetaType<ElementsLocation>("ElementsLocation")
Id of the corresponding Qt meta type.
Private Attributes
QString m_collection_path
QString m_file_system_path
QETProject * m_project = nullptr
std::stringstream m_string_stream
Detailed Description
The ElementsLocation class This class represents the location, the location of an element or of a category, even of a collection ... in a collection. She encapsulates a virtual path.
Definition at line 45 of file elementslocation.h.
Constructor & Destructor Documentation
ElementsLocation() [1/4]
ElementsLocation::ElementsLocation ()
ElementsLocation::ElementsLocation Constructor.
Definition at line 36 of file elementslocation.cpp.
ElementsLocation() [2/4]
ElementsLocation::ElementsLocation (const QString & path, QETProject * project = nullptr)
ElementsLocation::ElementsLocation.
Parameters
path : Item location path
project : Project of the location of the element
Definition at line 46 of file elementslocation.cpp.
References path(), and setPath().
ElementsLocation() [3/4]
ElementsLocation::ElementsLocation (const ElementsLocation & other)
ElementsLocation::ElementsLocation The copy constructor.
Parameters
other : Alternate item location to copy
Definition at line 66 of file elementslocation.cpp.
ElementsLocation() [4/4]
ElementsLocation::ElementsLocation (const QMimeData * data)
ElementsLocation::ElementLocation Constructor, build an ElementLocation from a QMimeData, the mime data format must be "application/x-qet-element-uri" or "application/x-qet-category-uri". This location can be null even if format is valid.
Parameters
data
Definition at line 80 of file elementslocation.cpp.
References setPath().
~ElementsLocation()
ElementsLocation::~ElementsLocation () virtual
ElementsLocation::~ElementsLocation Destructeur.
Definition at line 56 of file elementslocation.cpp.
Member Function Documentation
addToPath()
bool ElementsLocation::addToPath (const QString & string)
ElementsLocation::addToPath Add a string to the actual path of this location.
Parameters
string
Returns
True if the operation success
Definition at line 320 of file elementslocation.cpp.
References isFileSystem(), m_collection_path, and m_file_system_path.
Referenced by ElementsCategoryEditor::acceptCreation(), ElementDialog::checkCurrentLocation(), ElementCollectionHandler::createDir(), NewElementWizard::createNewElement(), ElementCollectionHandler::importFromProject(), ElementDialog::location(), and NewElementWizard::validStep2().
baseName()
QString ElementsLocation::baseName () const
ElementsLocation::baseName.
Returns
The base name of the element or directory. Unlike ElementsLocation::fileName, this method don't return the extension name. For exemple if this location represent an element they return myElement.
See also
fileName()
Definition at line 142 of file elementslocation.cpp.
References m_collection_path.
Referenced by Element::name().
collectionPath()
QString ElementsLocation::collectionPath (bool protocol = true) const
ElementsLocation::collectionPath Return the path of the represented element relative to collection if protocol is true the path is prepended by the collection type (common://, custom:// or embed://) else if false, only the collection path is returned without the collection type.
Parameters
protocol
Returns
the path
Definition at line 160 of file elementslocation.cpp.
References m_collection_path, and path().
Referenced by XmlElementCollection::addElement(), ElementsCollectionModel::addLocation(), ElementsCollectionModel::canDropMimeData(), XmlElementCollection::cleanUnusedElement(), ECHSToXml::copy(), ECHSXmlToFile::copyDirectory(), XmlElementCollection::copyDirectory(), XmlElementCollection::copyElement(), ElementCollectionHandler::createDir(), ElementsCollectionWidget::deleteDirectory(), ElementsCollectionWidget::deleteElement(), ElementsCollectionModel::dropMimeData(), exist(), QETProject::importElement(), ElementCollectionHandler::importFromProject(), ElementsCollectionModel::indexFromLocation(), nameList(), operator<<(), projectCollectionPath(), and setXml().
elementInformations()
DiagramContext ElementsLocation::elementInformations () const
ElementsLocation::elementInformations.
Returns
the element information of the element represented by this location. If the location is a directory, the returned diagram context is empty
Definition at line 811 of file elementslocation.cpp.
References DiagramContext::fromXml(), isDirectory(), and pugiXml().
Referenced by XmlProjectElementCollectionItem::setUpData(), and FileElementCollectionItem::setUpData().
exist()
bool ElementsLocation::exist () const
ElementsLocation::exist.
Returns
True if this location represent an existing directory or element.
Definition at line 472 of file elementslocation.cpp.
References collectionPath(), QETProject::embeddedElementCollection(), XmlElementCollection::exist(), fileSystemPath(), isDirectory(), isElement(), and m_project.
Referenced by ElementsCategoryEditor::acceptCreation(), XmlElementCollection::addElement(), DiagramEventAddElement::buildElement(), ElementDialog::checkAccept(), ElementDialog::checkCurrentLocation(), ECHSFileToFile::copy(), XmlElementCollection::copy(), ECHSXmlToFile::copy(), ECHSToXml::copy(), ElementCollectionHandler::copy(), ECHSXmlToFile::copyDirectory(), ECHSXmlToFile::copyElement(), ElementCollectionHandler::createDir(), ElementFactory::createElement(), ElementsCollectionWidget::deleteDirectory(), ElementsCollectionWidget::deleteElement(), DiagramEventAddElement::DiagramEventAddElement(), ElementsCollectionModel::dropMimeData(), Element::Element(), ElementsCategoryEditor::ElementsCategoryEditor(), XmlElementCollection::elementsLocation(), QETElementEditor::fromLocation(), ElementPictureFactory::getPictures(), DiagramView::handleElementDrop(), QETProject::importElement(), ElementCollectionHandler::importFromProject(), ElementsCollectionWidget::locationWasSaved(), operator<<(), QETElementEditor::pasteFromElement(), ElementsCollectionWidget::setCurrentLocation(), ElementCollectionHandler::setNames(), setXml(), ElementsTreeView::startDrag(), ElementsTreeView::startElementDrag(), NewElementWizard::validStep1(), and NewElementWizard::validStep2().
fileName()
QString ElementsLocation::fileName () const
ElementLocation::fileName.
Returns
Return the file name of the represented item, whatever the storage system (file system, xml collection) with is file extension. For example if this location represent an element, they return myElement.elmt. For a directory return myDirectory.
See also
baseName
Definition at line 793 of file elementslocation.cpp.
References m_collection_path.
Referenced by ECHSFileToFile::copy(), ECHSXmlToFile::copy(), ECHSToXml::copy(), ECHSXmlToFile::copyDirectory(), XmlElementCollection::copyDirectory(), ECHSFileToFile::copyElement(), ECHSXmlToFile::copyElement(), XmlElementCollection::copyElement(), ElementsCollectionModel::dropMimeData(), autonum::elementPrefixForLocation(), QETProject::importElement(), ElementCollectionHandler::importFromProject(), and name().
fileSystemPath()
QString ElementsLocation::fileSystemPath () const
ElementsLocation::fileSystemPath.
Returns
The file system path of this element, (the separator is always '/' see QDir::toNativeSeparators()) If this element is embedded in a project return an empty string;
Definition at line 193 of file elementslocation.cpp.
References m_file_system_path, and m_project.
Referenced by XmlElementCollection::addElement(), ECHSFileToFile::copy(), ECHSXmlToFile::copy(), ECHSFileToFile::copyDirectory(), ECHSXmlToFile::copyDirectory(), XmlElementCollection::copyDirectory(), ECHSFileToFile::copyElement(), ECHSXmlToFile::copyElement(), XmlElementCollection::copyElement(), ElementCollectionHandler::createDir(), ElementsCollectionWidget::deleteDirectory(), ElementsCollectionWidget::deleteElement(), ElementsCategoryEditor::ElementsCategoryEditor(), exist(), isCommonCollection(), isCustomCollection(), isWritable(), nameList(), ElementCollectionHandler::setNames(), and setXml().
icon()
QIcon ElementsLocation::icon () const
ElementLocation::icon.
Returns
The icon of the represented element. If icon can't be set, return a null QIcon
Definition at line 756 of file elementslocation.cpp.
References QETApp::collectionCache(), ElementsCollectionCache::fetchElement(), ElementPictureFactory::instance(), m_project, and ElementsCollectionCache::pixmap().
Referenced by XmlProjectElementCollectionItem::setUpIcon(), and FileElementCollectionItem::setUpIcon().
isCommonCollection()
bool ElementsLocation::isCommonCollection () const
ElementsLocation::isCommonCollection.
Returns
True if this location represent an item from the common collection
Definition at line 440 of file elementslocation.cpp.
References QETApp::commonElementsDirN(), and fileSystemPath().
Referenced by ElementsCollectionModel::indexFromLocation().
isCustomCollection()
bool ElementsLocation::isCustomCollection () const
ElementsLocation::isCustomCollection.
Returns
True if this location represent an item from the custom collection
Definition at line 450 of file elementslocation.cpp.
References QETApp::customElementsDirN(), and fileSystemPath().
Referenced by ElementsCollectionModel::addLocation(), and ElementsCollectionModel::indexFromLocation().
isDirectory()
bool ElementsLocation::isDirectory () const
ElementsLocation::isDirectory.
Returns
true if this location represent a directory
Definition at line 420 of file elementslocation.cpp.
References isElement(), and m_collection_path.
Referenced by ElementDialog::checkCurrentLocation(), ECHSFileToFile::copy(), XmlElementCollection::copy(), ECHSXmlToFile::copy(), ECHSToXml::copy(), ElementCollectionHandler::createDir(), ElementsCollectionWidget::deleteDirectory(), elementInformations(), exist(), ElementDialog::location(), nameList(), ElementCollectionHandler::setNames(), and ElementsTreeView::startElementDrag().
isElement()
bool ElementsLocation::isElement () const
ElementsLocation::isElement.
Returns
true if this location represent an element
Definition at line 412 of file elementslocation.cpp.
References m_collection_path.
Referenced by XmlElementCollection::addElement(), ElementDialog::checkAccept(), ElementDialog::checkCurrentLocation(), ECHSFileToFile::copy(), XmlElementCollection::copy(), ECHSXmlToFile::copy(), ElementCollectionHandler::copy(), ElementFactory::createElement(), ElementsCollectionWidget::deleteElement(), DiagramEventAddElement::DiagramEventAddElement(), Element::Element(), ElementsCategoryEditor::ElementsCategoryEditor(), exist(), QETElementEditor::fromLocation(), DiagramView::handleElementDrop(), QETProject::importElement(), ElementCollectionHandler::importFromProject(), isDirectory(), ElementDialog::location(), nameList(), QETElementEditor::pasteFromElement(), pugiXml(), ElementCollectionHandler::setNames(), ElementsTreeView::startElementDrag(), QETProject::unusedElements(), uuid(), and xml().
isFileSystem()
bool ElementsLocation::isFileSystem () const
ElementsLocation::isFileSystem.
Returns
true if
Definition at line 428 of file elementslocation.cpp.
References m_file_system_path, and m_project.
Referenced by XmlElementCollection::addElement(), addToPath(), ElementCollectionHandler::copy(), XmlElementCollection::copyDirectory(), XmlElementCollection::copyElement(), ElementCollectionHandler::createDir(), ElementsCollectionWidget::deleteDirectory(), ElementsCollectionWidget::deleteElement(), QETProject::importElement(), isWritable(), projectCollectionPath(), ElementCollectionHandler::setNames(), and setXml().
isNull()
bool ElementsLocation::isNull () const
ElementsLocation::isNull.
Returns
true if the location seems usable (virtual path not empty).
Definition at line 387 of file elementslocation.cpp.
References m_collection_path.
Referenced by ElementsCategoryEditor::acceptCreation(), QETApp::elementEditors(), QETElementEditor::pasteFromElement(), QETElementEditor::slot_open(), QETElementEditor::slot_save(), QETElementEditor::slot_saveAs(), and QETElementEditor::slot_updateTitle().
isProject()
bool ElementsLocation::isProject () const
ElementsLocation::isProject.
Returns
True if this location represent an item from a project.
Definition at line 459 of file elementslocation.cpp.
References m_collection_path, and m_project.
Referenced by XmlElementCollection::addElement(), ElementsCollectionModel::addLocation(), XmlElementCollection::copy(), ECHSToXml::copy(), ElementCollectionHandler::copy(), ElementCollectionHandler::createDir(), autonum::elementPrefixForLocation(), ElementsCollectionCache::fetchElement(), QETProject::importElement(), ElementCollectionHandler::importFromProject(), operator<<(), ElementCollectionHandler::setNames(), and setXml().
isWritable()
bool ElementsLocation::isWritable () const
ElementsLocation::isWritable.
Returns
True if this element can be writable (can use set xml)
Definition at line 499 of file elementslocation.cpp.
References QETApp::commonElementsDirN(), fileSystemPath(), isFileSystem(), QETProject::isReadOnly(), and m_project.
Referenced by ElementsCategoryEditor::acceptCreation(), ElementsCategoryEditor::acceptUpdate(), ElementCollectionHandler::createDir(), ElementsCategoryEditor::ElementsCategoryEditor(), QETElementEditor::fromLocation(), QETElementEditor::setLocation(), ElementCollectionHandler::setNames(), and setXml().
name()
QString ElementsLocation::name () const
ElementLocation::name.
Returns
The name of the represented element in the current local
Definition at line 776 of file elementslocation.cpp.
References fileName(), QET::Icons::nl, and pugiXml().
Referenced by XmlProjectElementCollectionItem::localName(), and FileElementCollectionItem::localName().
nameList()
NamesList ElementsLocation::nameList ()
ElementsLocation::nameList.
Returns
the namelist of the represented element or directory. If namelist can't be set, return a empty namelist
Definition at line 532 of file elementslocation.cpp.
References collectionPath(), XmlElementCollection::directory(), QETProject::embeddedElementCollection(), fileSystemPath(), isDirectory(), isElement(), m_project, QET::Icons::nl, and pugiXml().
Referenced by XmlElementCollection::addElement(), ECHSXmlToFile::copyDirectory(), and ElementsCategoryEditor::ElementsCategoryEditor().
operator!=()
bool ElementsLocation::operator!= (const ElementsLocation & other) const
ElementsLocation::operator != Operateur de comparaison.
Parameters
other Autre emplacement d'element a comparer
Returns
true si other et cet ElementsLocation sont differents, false sinon
Definition at line 127 of file elementslocation.cpp.
References m_collection_path, and m_project.
operator=()
ElementsLocation & ElementsLocation::operator= (const ElementsLocation & other)
ElementsLocation::operator = Assignment operator.
Parameters
other : Other item location to assign
Returns
*this ElementsLocation
Definition at line 96 of file elementslocation.cpp.
References m_collection_path, m_file_system_path, and m_project.
operator==()
bool ElementsLocation::operator== (const ElementsLocation & other) const
ElementsLocation::operator ==.
Parameters
other : other item location to compare
Returns
true if other and this ElementsLocation are identical, false otherwise
Definition at line 113 of file elementslocation.cpp.
References m_collection_path, and m_project.
parent()
ElementsLocation ElementsLocation::parent () const
ElementsLocation::parent.
Returns
the location of the parent category, or a copy of this location when it represents a root category.
Definition at line 346 of file elementslocation.cpp.
References m_collection_path, and setPath().
Referenced by autonum::elementPrefixForLocation(), QETProject::importElement(), and ElementCollectionHandler::importFromProject().
path()
QString ElementsLocation::path () const
ElementsLocation::path.
Returns
The path of this location.
Definition at line 206 of file elementslocation.cpp.
References m_collection_path.
Referenced by collectionPath(), ElementsLocation(), Diagram::fromXml(), setPath(), and Element::toXml().
project()
QETProject * ElementsLocation::project () const
ElementsLocation::project.
Returns
the project of this location or 0 if it is not linked to a project.
Definition at line 365 of file elementslocation.cpp.
References m_project.
Referenced by XmlElementCollection::addElement(), ElementsCollectionModel::addLocation(), QETApp::elementEditors(), QETProject::importElement(), setPath(), setProject(), and setXml().
projectCollection()
XmlElementCollection * ElementsLocation::projectCollection () const
ElementsLocation::projectCollection.
Returns
If this location represente a item in an embedded project collection, return this collection else return nullptr.
Definition at line 519 of file elementslocation.cpp.
References QETProject::embeddedElementCollection(), and m_project.
Referenced by XmlElementCollection::addElement(), XmlElementCollection::copy(), ECHSToXml::copy(), ECHSXmlToFile::copyDirectory(), XmlElementCollection::copyDirectory(), and ElementCollectionHandler::createDir().
projectCollectionPath()
QString ElementsLocation::projectCollectionPath () const
ElementsLocation::projectCollectionPath.
Returns
The path is in form : project0+embed://dir/subdir/myElement.elmt If this item represent a file system thing, return a null QString;
Definition at line 176 of file elementslocation.cpp.
References collectionPath(), isFileSystem(), m_project, and QETApp::projectId().
Referenced by DiagramEventAddElement::buildElement(), XmlProjectElementCollectionItem::collectionPath(), ECHSToXml::copy(), ECHSXmlToFile::copyDirectory(), XmlElementCollection::copyDirectory(), XmlElementCollection::copyElement(), QETProject::importElement(), and operator<<().
pugiXml()
pugi::xml_document ElementsLocation::pugiXml () const
ElementsLocation::pugiXml.
Returns
the xml document of this element or directory The definition can be null
Definition at line 610 of file elementslocation.cpp.
References XmlElementCollection::element(), QETProject::embeddedElementCollection(), isElement(), m_collection_path, m_file_system_path, m_project, and m_string_stream.
Referenced by ElementFactory::createElement(), elementInformations(), name(), nameList(), ElementPictureFactory::pixmap(), and uuid().
setPath()
void ElementsLocation::setPath (const QString & path)
ElementsLocation::setPath Set the path of this item. The path can be relative to a collection (start by common:// , custom:// or embed://) or not.
Parameters
path
Definition at line 217 of file elementslocation.cpp.
References QETApp::commonElementsDirN(), QETApp::customElementsDirN(), m_collection_path, m_file_system_path, m_project, path(), project(), and QETApp::project().
Referenced by XmlElementCollection::copyDirectory(), ElementsLocation(), and parent().
setProject()
void ElementsLocation::setProject (QETProject * project)
ElementsLocation::setProject.
Parameters
project : the new project points to this location Indicate 0 so that this location is no longer linked to a project.
Definition at line 377 of file elementslocation.cpp.
References m_project, and project().
setXml()
bool ElementsLocation::setXml (const QDomDocument & xml_document) const
ElementsLocation::setXml Replace the current xml description by xml_document; The document element of xml_document must have tagname "definition" to be written This definition must be writable.
Parameters
xml_document
Returns
true if success
Definition at line 667 of file elementslocation.cpp.
References XmlElementCollection::addElementDefinition(), collectionPath(), QETProject::embeddedElementCollection(), exist(), fileSystemPath(), isFileSystem(), isProject(), isWritable(), project(), QETXML::writeXmlFile(), and xml().
Referenced by QETElementEditor::toLocation().
toString()
QString ElementsLocation::toString () const
ElementsLocation::toString.
Returns
A character string representing the location
Definition at line 396 of file elementslocation.cpp.
References m_collection_path, m_project, and QETApp::projectId().
Referenced by ElementsCollectionCache::fetchData(), ElementsCollectionCache::fetchElement(), QETElementEditor::isEditing(), and ElementsTreeView::startElementDrag().
uuid()
QUuid ElementsLocation::uuid () const
ElementsLocation::uuid.
Returns
The uuid of the pointed element Uuid can be null
Definition at line 737 of file elementslocation.cpp.
References isElement(), and pugiXml().
Referenced by ElementPictureFactory::build(), ElementsCollectionCache::fetchElement(), ElementPictureFactory::getPictures(), ElementPictureFactory::getPrimitives(), QETProject::importElement(), and ElementPictureFactory::pixmap().
xml()
QDomElement ElementsLocation::xml () const
ElementsLocation::xml.
Returns
The definition of this element or directory. The definition can be null.
Definition at line 575 of file elementslocation.cpp.
References XmlElementCollection::directory(), XmlElementCollection::element(), QETProject::embeddedElementCollection(), isElement(), m_collection_path, m_file_system_path, and m_project.
Referenced by XmlElementCollection::addElement(), ElementPictureFactory::build(), ECHSXmlToFile::copyElement(), XmlElementCollection::copyElement(), Element::Element(), QETElementEditor::fromLocation(), QETElementEditor::pasteFromElement(), ElementCollectionHandler::setNames(), and setXml().
Member Data Documentation
m_collection_path
QString ElementsLocation::m_collection_path private
Definition at line 96 of file elementslocation.h.
Referenced by addToPath(), baseName(), collectionPath(), fileName(), isDirectory(), isElement(), isNull(), isProject(), operator!=(), operator=(), operator==(), parent(), path(), pugiXml(), setPath(), toString(), and xml().
m_file_system_path
QString ElementsLocation::m_file_system_path private
Definition at line 97 of file elementslocation.h.
Referenced by addToPath(), fileSystemPath(), isFileSystem(), operator=(), pugiXml(), setPath(), and xml().
m_project
QETProject* ElementsLocation::m_project = nullptr private
Definition at line 98 of file elementslocation.h.
Referenced by exist(), fileSystemPath(), icon(), isFileSystem(), isProject(), isWritable(), nameList(), operator!=(), operator=(), operator==(), project(), projectCollection(), projectCollectionPath(), pugiXml(), setPath(), setProject(), toString(), and xml().
m_string_stream
std::stringstream ElementsLocation::m_string_stream mutable private
Definition at line 100 of file elementslocation.h.
Referenced by pugiXml().
MetaTypeId
int ElementsLocation::MetaTypeId = qRegisterMetaType<ElementsLocation>("ElementsLocation") static
Id of the corresponding Qt meta type.
Definition at line 104 of file elementslocation.h.
The documentation for this class was generated from the following files:
elementslocation.h
elementslocation.cpp