QElectroTech: qdesigner_internal::ColorAction Class Reference
qdesigner_internal::ColorAction Class Reference
Signals
void colorChanged (const QColor &color)
Public Member Functions
ColorAction (QObject *parent)
const QColor & color () const
void setColor (const QColor &color)
Private Slots
void chooseColor ()
Private Attributes
QColor m_color
Detailed Description
Definition at line 365 of file richtexteditor.cpp.
Constructor & Destructor Documentation
ColorAction()
qdesigner_internal::ColorAction::ColorAction (QObject * parent)
Definition at line 385 of file richtexteditor.cpp.
Referenced by qdesigner_internal::HtmlTextEdit::contextMenuEvent().
Member Function Documentation
chooseColor
void qdesigner_internal::ColorAction::chooseColor () private slot
Definition at line 407 of file richtexteditor.cpp.
Referenced by qdesigner_internal::HtmlTextEdit::contextMenuEvent().
color()
const QColor& qdesigner_internal::ColorAction::color () const inline
Definition at line 372 of file richtexteditor.cpp.
Referenced by qdesigner_internal::HtmlTextEdit::contextMenuEvent().
colorChanged
void qdesigner_internal::ColorAction::colorChanged (const QColor & color) signal
Referenced by qdesigner_internal::HtmlTextEdit::contextMenuEvent().
setColor()
void qdesigner_internal::ColorAction::setColor (const QColor & color)
Definition at line 393 of file richtexteditor.cpp.
Referenced by qdesigner_internal::HtmlTextEdit::contextMenuEvent().
Member Data Documentation
m_color
QColor qdesigner_internal::ColorAction::m_color private
Definition at line 382 of file richtexteditor.cpp.
Referenced by qdesigner_internal::HtmlTextEdit::contextMenuEvent().
The documentation for this class was generated from the following file:
richtexteditor.cpp