QElectroTech: ElementsCollectionCache Class Reference
ElementsCollectionCache Class Reference
#include <elementscollectioncache.h>
Public Member Functions
ElementsCollectionCache (const QString &database_path, QObject *=nullptr)
~ElementsCollectionCache () override
void setLocale (const QString &)
QString locale () const
bool setPixmapStorageFormat (const QString &)
QString pixmapStorageFormat () const
bool fetchElement (ElementsLocation &location)
ElementsCollectionCache::fetchElement Retrieve the data for a given element, using the cache if available, filling it otherwise. Data are then available through pixmap() and name() methods.
QString name () const
QPixmap pixmap () const
bool fetchData (const ElementsLocation &)
bool fetchNameFromCache (const QString &path, const QUuid &uuid)
ElementsCollectionCache::fetchNameFromCache Retrieve the name for an element, given its path and uuid The value is then available through the name() method.
bool fetchPixmapFromCache (const QString &path, const QUuid &uuid)
ElementsCollectionCache::fetchPixmapFromCache Retrieve the pixmap for an element, given its path and uuid. It is then available through the pixmap() method.
bool cacheName (const QString &path, const QUuid &uuid=QUuid::createUuid())
ElementsCollectionCache::cacheName Cache the current (i.e. last retrieved) name The cache entry will use the locale set via setLocale().
bool cachePixmap (const QString &path, const QUuid &uuid=QUuid::createUuid())
ElementsCollectionCache::cachePixmap Cache the current (i.e. last retrieved) pixmap.
Private Attributes
QSqlDatabase cache_db_
Object providing access to the SQLite database this cache relies on.
QSqlQuery * select_name_
Prepared statement to fetch names from the cache.
QSqlQuery * select_pixmap_
Prepared statement to fetch pixmaps from the cache.
QSqlQuery * insert_name_
Prepared statement to insert names into the cache.
QSqlQuery * insert_pixmap_
Prepared statement to insert pixmaps into the cache.
QString locale_
Locale to be used when dealing with names.
QString pixmap_storage_format_
Storage format for cached pixmaps.
QString current_name_
Last name fetched.
QPixmap current_pixmap_
Last pixmap fetched.
Detailed Description
This class implements a SQLite cache for data related to elements collections, mainly names and pixmaps. This avoids the cost of parsing XML definitions of elements and building full CustomElement objects when (re)loading the elements panel.
Definition at line 30 of file elementscollectioncache.h.
Constructor & Destructor Documentation
ElementsCollectionCache()
ElementsCollectionCache::ElementsCollectionCache (const QString & database_path, QObject * parent = nullptr)
Construct a cache for elements collections.
Parameters
database_path Path of the SQLite database to open.
parent Parent QObject
Definition at line 32 of file elementscollectioncache.cpp.
References cache_db_, insert_name_, insert_pixmap_, select_name_, and select_pixmap_.
~ElementsCollectionCache()
ElementsCollectionCache::~ElementsCollectionCache () override
Destructor
Definition at line 107 of file elementscollectioncache.cpp.
References cache_db_, insert_name_, insert_pixmap_, select_name_, and select_pixmap_.
Member Function Documentation
cacheName()
bool ElementsCollectionCache::cacheName (const QString & path, const QUuid & uuid = QUuid::createUuid())
ElementsCollectionCache::cacheName Cache the current (i.e. last retrieved) name The cache entry will use the locale set via setLocale().
Parameters
path : Element path (as obtained using ElementsLocation::toString())
uuid :Element uuid
Returns
True if the caching succeeded, false otherwise.
See also
name()
Definition at line 295 of file elementscollectioncache.cpp.
References cache_db_, current_name_, insert_name_, and locale_.
Referenced by fetchElement().
cachePixmap()
bool ElementsCollectionCache::cachePixmap (const QString & path, const QUuid & uuid = QUuid::createUuid())
ElementsCollectionCache::cachePixmap Cache the current (i.e. last retrieved) pixmap.
Parameters
path : Element path (as obtained using ElementsLocation::toString())
uuid : Element uuid
Returns
True if the caching succeeded, false otherwise.
See also
pixmap()
Definition at line 318 of file elementscollectioncache.cpp.
References cache_db_, current_pixmap_, insert_pixmap_, and pixmap_storage_format_.
Referenced by fetchElement().
fetchData()
bool ElementsCollectionCache::fetchData (const ElementsLocation & location)
Retrieve the data by building the full CustomElement object matching the given location, without using the cache. Data are then available through pixmap() and name() methods.
Parameters
location Location of a given Element.
Returns
True if the retrieval succeeded, false otherwise.
Definition at line 211 of file elementscollectioncache.cpp.
References current_name_, current_pixmap_, ElementFactory::Instance(), name(), pixmap(), and ElementsLocation::toString().
Referenced by fetchElement().
fetchElement()
bool ElementsCollectionCache::fetchElement (ElementsLocation & location)
ElementsCollectionCache::fetchElement Retrieve the data for a given element, using the cache if available, filling it otherwise. Data are then available through pixmap() and name() methods.
Parameters
location The definition of an element.
See also
pixmap()
name()
Returns
True if the retrieval succeeded, false otherwise.
Definition at line 161 of file elementscollectioncache.cpp.
References cache_db_, cacheName(), cachePixmap(), fetchData(), fetchNameFromCache(), fetchPixmapFromCache(), ElementsLocation::isProject(), ElementsLocation::toString(), and ElementsLocation::uuid().
Referenced by ElementsLocation::icon().
fetchNameFromCache()
bool ElementsCollectionCache::fetchNameFromCache (const QString & path, const QUuid & uuid)
ElementsCollectionCache::fetchNameFromCache Retrieve the name for an element, given its path and uuid The value is then available through the name() method.
Parameters
path : Element path (as obtained using ElementsLocation::toString())
uuid : Element uuid
Returns
True if the retrieval succeeded, false otherwise.
Definition at line 235 of file elementscollectioncache.cpp.
References current_name_, locale_, and select_name_.
Referenced by fetchElement().
fetchPixmapFromCache()
bool ElementsCollectionCache::fetchPixmapFromCache (const QString & path, const QUuid & uuid)
ElementsCollectionCache::fetchPixmapFromCache Retrieve the pixmap for an element, given its path and uuid. It is then available through the pixmap() method.
Parameters
path : Element path (as obtained using ElementsLocation::toString())
uuid : Element uuid
Returns
True if the retrieval succeeded, false otherwise.
Definition at line 264 of file elementscollectioncache.cpp.
References current_pixmap_, pixmap_storage_format_, and select_pixmap_.
Referenced by fetchElement().
locale()
QString ElementsCollectionCache::locale () const
Returns
The locale to be used when dealing with names.
Definition at line 126 of file elementscollectioncache.cpp.
References locale_.
Referenced by setLocale().
name()
QString ElementsCollectionCache::name () const
Returns
The last name fetched through fetchElement().
Definition at line 193 of file elementscollectioncache.cpp.
References current_name_.
Referenced by fetchData().
pixmap()
QPixmap ElementsCollectionCache::pixmap () const
Returns
The last pixmap fetched through fetchElement().
Definition at line 200 of file elementscollectioncache.cpp.
References current_pixmap_.
Referenced by fetchData(), and ElementsLocation::icon().
pixmapStorageFormat()
QString ElementsCollectionCache::pixmapStorageFormat () const
Returns
the pixmap storage format. Default is "PNG"
See also
setPixmapStorageFormat()
Definition at line 148 of file elementscollectioncache.cpp.
References pixmap_storage_format_.
setLocale()
void ElementsCollectionCache::setLocale (const QString & locale)
Define the locale to be used when dealing with names.
Parameters
locale New locale to be used.
Definition at line 119 of file elementscollectioncache.cpp.
References locale(), and locale_.
Referenced by QETApp::QETApp().
setPixmapStorageFormat()
bool ElementsCollectionCache::setPixmapStorageFormat (const QString & format)
Define the storage format for the pixmaps within the SQLite database. See Qt's QPixmap documentation for more information.
Parameters
format The new pixmap storage format.
Returns
True if the format change was accepted, false otherwise.
Definition at line 136 of file elementscollectioncache.cpp.
References pixmap_storage_format_.
Member Data Documentation
cache_db_
QSqlDatabase ElementsCollectionCache::cache_db_ private
Object providing access to the SQLite database this cache relies on.
Definition at line 57 of file elementscollectioncache.h.
Referenced by cacheName(), cachePixmap(), ElementsCollectionCache(), fetchElement(), and ~ElementsCollectionCache().
current_name_
QString ElementsCollectionCache::current_name_ private
Last name fetched.
Definition at line 64 of file elementscollectioncache.h.
Referenced by cacheName(), fetchData(), fetchNameFromCache(), and name().
current_pixmap_
QPixmap ElementsCollectionCache::current_pixmap_ private
Last pixmap fetched.
Definition at line 65 of file elementscollectioncache.h.
Referenced by cachePixmap(), fetchData(), fetchPixmapFromCache(), and pixmap().
insert_name_
QSqlQuery* ElementsCollectionCache::insert_name_ private
Prepared statement to insert names into the cache.
Definition at line 60 of file elementscollectioncache.h.
Referenced by cacheName(), ElementsCollectionCache(), and ~ElementsCollectionCache().
insert_pixmap_
QSqlQuery* ElementsCollectionCache::insert_pixmap_ private
Prepared statement to insert pixmaps into the cache.
Definition at line 61 of file elementscollectioncache.h.
Referenced by cachePixmap(), ElementsCollectionCache(), and ~ElementsCollectionCache().
locale_
QString ElementsCollectionCache::locale_ private
Locale to be used when dealing with names.
Definition at line 62 of file elementscollectioncache.h.
Referenced by cacheName(), fetchNameFromCache(), locale(), and setLocale().
pixmap_storage_format_
QString ElementsCollectionCache::pixmap_storage_format_ private
Storage format for cached pixmaps.
Definition at line 63 of file elementscollectioncache.h.
Referenced by cachePixmap(), fetchPixmapFromCache(), pixmapStorageFormat(), and setPixmapStorageFormat().
select_name_
QSqlQuery* ElementsCollectionCache::select_name_ private
Prepared statement to fetch names from the cache.
Definition at line 58 of file elementscollectioncache.h.
Referenced by ElementsCollectionCache(), fetchNameFromCache(), and ~ElementsCollectionCache().
select_pixmap_
QSqlQuery* ElementsCollectionCache::select_pixmap_ private
Prepared statement to fetch pixmaps from the cache.
Definition at line 59 of file elementscollectioncache.h.
Referenced by ElementsCollectionCache(), fetchPixmapFromCache(), and ~ElementsCollectionCache().
The documentation for this class was generated from the following files:
elementscollectioncache.h
elementscollectioncache.cpp