QElectroTech: ESEventAddRect Class Reference
ESEventAddRect Class Reference
#include <eseventaddrect.h>
Public Member Functions
ESEventAddRect (ElementScene *scene)
ESEventAddRect::ESEventAddRect.
~ESEventAddRect () override
ESEventAddRect::~ESEventAddRect.
bool mousePressEvent (QGraphicsSceneMouseEvent *event) override
ESEventAddRect::mousePressEvent.
bool mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
ESEventAddRect::mouseMoveEvent.
bool mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
ESEventAddRect::mouseReleaseEvent.
Public Member Functions inherited from ESEventInterface
ESEventInterface (ElementScene *scene)
virtual ~ESEventInterface ()
ESEventInterface::~ESEventInterface Destructor.
void init ()
ESEventInterface::init Init this event interface.
virtual bool mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
virtual bool wheelEvent (QGraphicsSceneWheelEvent *event)
virtual bool keyPressEvent (QKeyEvent *event)
ESEventInterface::keyPressEvent By default, press escape key abort the curent action.
virtual bool KeyReleaseEvent (QKeyEvent *event)
virtual bool isRunning () const
virtual bool isFinish () const
Private Attributes
PartRectangle * m_rect
Additional Inherited Members
Protected Member Functions inherited from ESEventInterface
void updateHelpCross (const QPointF &p)
Protected Attributes inherited from ESEventInterface
ElementScene * m_scene
QETElementEditor * m_editor
QGraphicsLineItem * m_help_horiz
QGraphicsLineItem * m_help_verti
bool m_running
bool m_abort
Detailed Description
Definition at line 28 of file eseventaddrect.h.
Constructor & Destructor Documentation
ESEventAddRect()
ESEventAddRect::ESEventAddRect (ElementScene * scene)
ESEventAddRect::ESEventAddRect.
Parameters
scene
Definition at line 29 of file eseventaddrect.cpp.
~ESEventAddRect()
ESEventAddRect::~ESEventAddRect () override
ESEventAddRect::~ESEventAddRect.
Definition at line 37 of file eseventaddrect.cpp.
References ESEventInterface::m_abort, m_rect, and ESEventInterface::m_running.
Member Function Documentation
mouseMoveEvent()
bool ESEventAddRect::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override virtual
ESEventAddRect::mouseMoveEvent.
Parameters
event
Returns
Reimplemented from ESEventInterface.
Definition at line 82 of file eseventaddrect.cpp.
References m_rect, ESEventInterface::m_scene, PartRectangle::rect, ElementScene::snapToGrid(), and ESEventInterface::updateHelpCross().
mousePressEvent()
bool ESEventAddRect::mousePressEvent (QGraphicsSceneMouseEvent * event) override virtual
ESEventAddRect::mousePressEvent.
Parameters
event
Returns
Reimplemented from ESEventInterface.
Definition at line 47 of file eseventaddrect.cpp.
References ESEventInterface::m_editor, m_rect, ESEventInterface::m_running, ESEventInterface::m_scene, QET::Icons::PartRectangle, ElementScene::snapToGrid(), and QET::Icons::tr.
mouseReleaseEvent()
bool ESEventAddRect::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
ESEventAddRect::mouseReleaseEvent.
Parameters
event
Returns
Reimplemented from ESEventInterface.
Definition at line 96 of file eseventaddrect.cpp.
References m_rect, and ESEventInterface::m_running.
Member Data Documentation
m_rect
PartRectangle* ESEventAddRect::m_rect private
Definition at line 39 of file eseventaddrect.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and ~ESEventAddRect().
The documentation for this class was generated from the following files:
eseventaddrect.h
eseventaddrect.cpp