QElectroTech: DynamicElementTextItem Class Reference
DynamicElementTextItem Class Reference
The DynamicElementTextItem class This class provide a simple text field of element who can be added or removed directly from the diagram editor. This text is created to compensate a big lack of the ElementTextItem : ElementTextItem can't be added or removed directly in the diagram editor.
#include <dynamicelementtextitem.h>
Public Types
enum TextFrom { UserText, ElementInfo, CompositeText }
enum { Type = UserType + 1010 }
Public Types inherited from DiagramTextItem
enum { Type = UserType + 1004 }
Signals
void textChanged (QString text)
void textFromChanged (DynamicElementTextItem::TextFrom text_from)
void infoNameChanged (QString info)
void compositeTextChanged (QString text)
void frameChanged (bool frame)
void plainTextChanged ()
void textWidthChanged (qreal width)
Signals inherited from DiagramTextItem
void colorChanged (QColor color)
void alignmentChanged (Qt::Alignment alignment)
void textEdited (const QString &old_str, const QString &new_str)
void fontChanged (QFont font)
Public Member Functions
int type () const override
DynamicElementTextItem (Element *parent_element)
DynamicElementTextItem::DynamicElementTextItem Constructor.
~DynamicElementTextItem () override
QDomElement toXml (QDomDocument &dom_doc) const override
DynamicElementTextItem::toXml Export this text to xml.
void fromXml (const QDomElement &dom_elmt) override
DynamicElementTextItem::fromXml Import this text from xml.
Element * parentElement () const
DynamicElementTextItem::ParentElement.
ElementTextItemGroup * parentGroup () const
DynamicElementTextItem::parentGroup.
Element * elementUseForInfo () const
DynamicElementTextItem::elementUseForInfo.
void refreshLabelConnection ()
DynamicElementTextItem::refreshLabelConnection Refresh the connection of this text when the source of text is label, or composite text, with a variable %{label}.
DynamicElementTextItem::TextFrom textFrom () const
DynamicElementTextItem::textFrom.
void setTextFrom (DynamicElementTextItem::TextFrom text_from)
DynamicElementTextItem::setTextFrom Set the final text is created from.
QString text () const
DynamicElementTextItem::text.
void setText (const QString &text)
DynamicElementTextItem::setText Set the text of this text.
void setInfoName (const QString &info_name)
DynamicElementTextItem::setInfoName Set the information name of the parent element.
QString infoName () const
DynamicElementTextItem::infoName.
void setCompositeText (const QString &text)
DynamicElementTextItem::setCompositeText Set the composite text of this text item to text.
QString compositeText () const
DynamicElementTextItem::compositeText.
void setFrame (const bool frame)
bool frame () const
QUuid uuid () const
void updateXref ()
DynamicElementTextItem::updateXref Create or delete the Xref according to the current properties of the project.
void setPlainText (const QString &text)
void setTextWidth (qreal width)
void setXref_item (Qt::AlignmentFlag m_exHrefPos)
Public Member Functions inherited from DiagramTextItem
DiagramTextItem (QGraphicsItem *=nullptr)
DiagramTextItem::DiagramTextItem.
DiagramTextItem (const QString &, QGraphicsItem *=nullptr)
DiagramTextItem::DiagramTextItem.
int type () const override
Diagram * diagram () const
DiagramTextItem::diagram.
void edit ()
Edit the text with HtmlEditor.
QPointF mapMovementToScene (const QPointF &) const
QPointF mapMovementFromScene (const QPointF &) const
QPointF mapMovementToParent (const QPointF &) const
QPointF mapMovementFromParent (const QPointF &) const
void setFont (const QFont &font)
void setColor (const QColor &color)
QColor color () const
void setNoEditable (bool e=true)
void setAlignment (const Qt::Alignment &alignment)
Qt::Alignment alignment () const
QRectF frameRect () const
DiagramTextItem::frameRect.
void setHtml (const QString &text)
void setPlainText (const QString &text)
bool isHtml () const
Static Public Member Functions
static QMetaEnum textFromMetaEnum ()
DynamicElementTextItem::textFromMetaEnum.
static QString xmlTagName ()
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
DynamicElementTextItem::mousePressEvent.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
DynamicElementTextItem::mouseMoveEvent.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
DynamicElementTextItem::mouseReleaseEvent.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
DynamicElementTextItem::mouseDoubleClickEvent Reimplemented functions, for add extra feature when this text is owned by a slave. In this case if the parent slave element is linked to a master, and this text display the label of the master (both if the 'text from' is 'element info' or 'composite text') the QGraphicsView go to master and select it.
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
DynamicElementTextItem::hoverEnterEvent If the parent element of this text is a folio report or a slave element, the element is linked and the text display the variable "label" we set the text blue for signal the user that the text act like a link when we double click on.
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
DynamicElementTextItem::hoverLeaveEvent.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
Protected Member Functions inherited from DiagramTextItem
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *) override
DiagramTextItem::paint Draw this text field. This method draw the text by calling QGraphicsTextItem::paint. If text is hovered, this method draw the bounding rect in grey.
void focusInEvent (QFocusEvent *) override
DiagramTextItem::focusInEvent.
void focusOutEvent (QFocusEvent *) override
DiagramTextItem::focusOutEvent.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
DiagramTextItem::mousePressEvent.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
DiagramTextItem::mouseMoveEvent.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
DiagramTextItem::mouseReleaseEvent.
void hoverEnterEvent (QGraphicsSceneHoverEvent *) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *) override
void hoverMoveEvent (QGraphicsSceneHoverEvent *) override
virtual void applyRotation (const qreal &)
void prepareAlignment ()
DiagramTextItem::prepareAlignment Call this function before changing the bounding rect of this text.
void finishAlignment ()
DiagramTextItem::finishAlignment Call this function after changing the bouding rect of this text to set the position of this text according to the alignment property.
Properties
QString text
TextFrom textFrom
QString infoName
QString compositeText
bool frame
qreal textWidth
Properties inherited from DiagramTextItem
QColor color
Qt::Alignment alignment
QString plainText
QFont font
Private Member Functions
DynamicElementTextItem ()
DynamicElementTextItem (const DynamicElementTextItem &)
void elementInfoChanged ()
void masterChanged ()
DynamicElementTextItem::masterChanged This function is only use when the parent element is a slave. Call when the master element linked to the parent slave element of this text change.
void reportChanged ()
DynamicElementTextItem::reportChanged This function is only use when parent element of this text is a folio report The linked report of the parent element was changed.
void reportFormulaChanged ()
DynamicElementTextItem::reportFormulaChanged The report formula use in the project was changed.
void setConnectionForReportFormula (const QString &formula)
void removeConnectionForReportFormula (const QString &formula)
void setupFormulaConnection ()
DynamicElementTextItem::setupFormulaConnection Setup the required connection for the formula of the label.
void clearFormulaConnection ()
void updateReportFormulaConnection ()
void updateReportText ()
DynamicElementTextItem::updateReportText This function is only use when this text is owned by a report, and this text have for info the Label.
void updateLabel ()
DynamicElementTextItem::updateLabel Update the displayed text, when this dynamic text is based on the label of the parent element. This function is notably use when the label itself is based from a formula. If this dynamic text isn't based on label, this function do nothing.
void conductorWasAdded (Conductor *conductor)
DynamicElementTextItem::conductorWasAdded Function only use when parent element is a folio report.
void conductorWasRemoved (Conductor *conductor)
DynamicElementTextItem::conductorWasRemoved Function only use when parent element is a folio report.
void setPotentialConductor ()
DynamicElementTextItem::setPotentialConductor This function is only used when the parent element of this text is a report element Get a conductor in the potential of the parent report.
void conductorPropertiesChanged ()
DynamicElementTextItem::conductorPropertiesChanged This function is only used when the parent element of this text is a report element.
QString reportReplacedCompositeText () const
DynamicElementTextItem::reportReplacedCompositeText This function is only used when the parent element of this text is a report element.
void zoomToLinkedElement ()
DynamicElementTextItem::zoomToLinkedElement If the parent element is a folio report or a slave element, and is linked, zoom to the linked element.
Private Attributes
QPointer< Element > m_parent_element
QPointer< Element > m_master_element
QPointer< Element > m_other_report
QPointer< Conductor > m_watched_conductor
QString m_text
QString m_info_name
QString m_composite_text
QString m_report_formula
QString m_F_str
DynamicElementTextItem::TextFrom m_text_from = UserText
QUuid m_uuid
QMetaObject::Connection m_report_formula_con
QList< QMetaObject::Connection > m_formula_connection
QList< QMetaObject::Connection > m_update_slave_Xref_connection
QColor m_user_color
bool m_frame = false
bool m_first_scene_change = true
CrossRefItem * m_Xref_item = nullptr
QGraphicsTextItem * m_slave_Xref_item = nullptr
qreal m_text_width = -1
QPointF m_initial_position
Friends
class DynamicTextItemDelegate
class CompositeTextEditDialog
class Element
Additional Inherited Members
Public Attributes inherited from DiagramTextItem
bool m_block_alignment = false
Protected Attributes inherited from DiagramTextItem
bool m_mouse_hover = false
bool m_first_move = true
bool m_no_editable
bool m_is_html = false
QString m_previous_html_text
QString m_previous_text
QPointF m_mouse_to_origin_movement
Detailed Description
The DynamicElementTextItem class This class provide a simple text field of element who can be added or removed directly from the diagram editor. This text is created to compensate a big lack of the ElementTextItem : ElementTextItem can't be added or removed directly in the diagram editor.
Definition at line 38 of file dynamicelementtextitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 61 of file dynamicelementtextitem.h.
TextFrom
enum DynamicElementTextItem::TextFrom
Enumerator
UserText
ElementInfo
CompositeText
Definition at line 55 of file dynamicelementtextitem.h.
Constructor & Destructor Documentation
DynamicElementTextItem() [1/3]
DynamicElementTextItem::DynamicElementTextItem (Element * parent_element)
DynamicElementTextItem::DynamicElementTextItem Constructor.
Parameters
parent_element
Definition at line 38 of file dynamicelementtextitem.cpp.
References QETApp::dynamicTextsItemFont(), m_parent_element, DiagramTextItem::setFont(), setText(), setTextWidth(), DiagramTextItem::textEdited(), and QET::Icons::tr.
~DynamicElementTextItem()
DynamicElementTextItem::~DynamicElementTextItem () override
Definition at line 65 of file dynamicelementtextitem.cpp.
DynamicElementTextItem() [2/3]
DynamicElementTextItem::DynamicElementTextItem () private
Definition at line 78 of file dynamicelementtextitem.cpp.
DynamicElementTextItem() [3/3]
DynamicElementTextItem::DynamicElementTextItem (const DynamicElementTextItem &) private
Member Function Documentation
clearFormulaConnection()
void DynamicElementTextItem::clearFormulaConnection () private
Definition at line 991 of file dynamicelementtextitem.cpp.
References m_formula_connection.
Referenced by setCompositeText(), setInfoName(), setTextFrom(), and setupFormulaConnection().
compositeText()
QString DynamicElementTextItem::compositeText () const
DynamicElementTextItem::compositeText.
Returns
Definition at line 501 of file dynamicelementtextitem.cpp.
References m_composite_text.
compositeTextChanged
void DynamicElementTextItem::compositeTextChanged (QString text) signal
Referenced by ElementTextItemGroup::addToGroup(), ElementTextItemGroup::removeFromGroup(), setCompositeText(), and DynamicElementTextModel::setConnection().
conductorPropertiesChanged()
void DynamicElementTextItem::conductorPropertiesChanged () private
DynamicElementTextItem::conductorPropertiesChanged This function is only used when the parent element of this text is a report element.
Definition at line 1143 of file dynamicelementtextitem.cpp.
References Element::AllReport, CompositeText, ElementInfo, m_info_name, m_parent_element, m_text_from, m_watched_conductor, reportReplacedCompositeText(), and setPlainText().
Referenced by conductorWasRemoved(), setInfoName(), and setPotentialConductor().
conductorWasAdded()
void DynamicElementTextItem::conductorWasAdded (Conductor * conductor) private
DynamicElementTextItem::conductorWasAdded Function only use when parent element is a folio report.
Parameters
conductor
Definition at line 1068 of file dynamicelementtextitem.cpp.
References setPotentialConductor().
Referenced by itemChange().
conductorWasRemoved()
void DynamicElementTextItem::conductorWasRemoved (Conductor * conductor) private
DynamicElementTextItem::conductorWasRemoved Function only use when parent element is a folio report.
Parameters
conductor
Definition at line 1079 of file dynamicelementtextitem.cpp.
References conductorPropertiesChanged(), m_watched_conductor, Conductor::propertiesChange(), and setPotentialConductor().
Referenced by itemChange().
elementInfoChanged()
void DynamicElementTextItem::elementInfoChanged () private
Definition at line 765 of file dynamicelementtextitem.cpp.
References Element::actualLabel(), CompositeText, ElementInfo, Element::elementInformations(), elementUseForInfo(), m_composite_text, m_info_name, m_text, m_text_from, plainTextChanged(), autonum::AssignVariables::replaceVariable(), setPlainText(), setupFormulaConnection(), UserText, and DiagramContext::value().
Referenced by masterChanged(), and setTextFrom().
elementUseForInfo()
Element * DynamicElementTextItem::elementUseForInfo () const
DynamicElementTextItem::elementUseForInfo.
Returns
a pointer to the element we must use for the variable information. If this text is owned by a simple element, the simple element is returned, this is the same element returned by the function parentElement(). If this text is owned by a master element, the master element is returned, this is the same element returned by the function parentElement(). If this text is owned by a report element, the report element is returned, this is the same element returned by the function parentElement(). If this text is owned by a terminal element, the terminal element is returned, this is the same element returned by the function parentElement(). If this text is owned by a slave element, we return the master element set as master of the parent slave element, if the parent slave is not linked to a master, this function return a nullptr. If this text have no parent element, return nullptr
Definition at line 258 of file dynamicelementtextitem.cpp.
References Element::linkedElements(), Element::linkType(), Element::Master, Element::NextReport, parentElement(), Element::PreviousReport, Element::Simple, Element::Slave, and Element::Terminale.
Referenced by DynamicTextItemDelegate::availableInfo(), elementInfoChanged(), DynamicElementTextModel::itemDataChanged(), DynamicElementTextModel::itemsForText(), masterChanged(), setCompositeText(), setInfoName(), DynamicTextItemDelegate::setModelData(), setTextFrom(), setupFormulaConnection(), and updateLabel().
frame()
bool DynamicElementTextItem::frame () const
Definition at line 513 of file dynamicelementtextitem.cpp.
References m_frame.
frameChanged
void DynamicElementTextItem::frameChanged (bool frame) signal
Referenced by DynamicElementTextModel::setConnection(), and setFrame().
fromXml()
void DynamicElementTextItem::fromXml (const QDomElement & dom_elmt) override virtual
DynamicElementTextItem::fromXml Import this text from xml.
Parameters
dom_elmt
Implements DiagramTextItem.
Definition at line 154 of file dynamicelementtextitem.cpp.
References DiagramTextItem::font, m_text_from, m_uuid, DiagramTextItem::setAlignment(), DiagramTextItem::setColor(), setCompositeText(), DiagramTextItem::setFont(), setFrame(), setInfoName(), setPlainText(), setText(), setTextFrom(), setTextWidth(), textFromMetaEnum(), and xmlTagName().
Referenced by ImportElementTextPattern::apply(), Element::fromXml(), and Element::parseDynamicText().
hoverEnterEvent()
void DynamicElementTextItem::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
DynamicElementTextItem::hoverEnterEvent If the parent element of this text is a folio report or a slave element, the element is linked and the text display the variable "label" we set the text blue for signal the user that the text act like a link when we double click on.
Parameters
event
Definition at line 614 of file dynamicelementtextitem.cpp.
References Element::AllReport, DiagramTextItem::color, CompositeText, ElementInfo, DiagramTextItem::hoverEnterEvent(), m_composite_text, m_info_name, m_other_report, m_text_from, m_user_color, and parentElement().
hoverLeaveEvent()
void DynamicElementTextItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
DynamicElementTextItem::hoverLeaveEvent.
Parameters
event
Definition at line 638 of file dynamicelementtextitem.cpp.
References DiagramTextItem::hoverLeaveEvent(), and m_user_color.
infoName()
QString DynamicElementTextItem::infoName () const
DynamicElementTextItem::infoName.
Returns
the info name of this text
Definition at line 445 of file dynamicelementtextitem.cpp.
References m_info_name.
infoNameChanged
void DynamicElementTextItem::infoNameChanged (QString info) signal
Referenced by ElementTextItemGroup::addToGroup(), ElementTextItemGroup::removeFromGroup(), DynamicElementTextModel::setConnection(), and setInfoName().
itemChange()
QVariant DynamicElementTextItem::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 682 of file dynamicelementtextitem.cpp.
References Element::AllReport, Terminal::conductorWasAdded(), conductorWasAdded(), Terminal::conductorWasRemoved(), conductorWasRemoved(), Element::linkedElementChanged(), m_first_scene_change, m_parent_element, m_report_formula, m_report_formula_con, Element::Master, masterChanged(), reportChanged(), reportFormulaChanged(), QETProject::reportPropertiesChanged(), setPotentialConductor(), Element::Slave, updateXref(), and QETProject::XRefPropertiesChanged().
masterChanged()
void DynamicElementTextItem::masterChanged () private
DynamicElementTextItem::masterChanged This function is only use when the parent element is a slave. Call when the master element linked to the parent slave element of this text change.
Definition at line 813 of file dynamicelementtextitem.cpp.
References CompositeText, ElementInfo, Element::elementInfoChange(), elementInfoChanged(), elementUseForInfo(), m_master_element, m_text_from, and updateXref().
Referenced by itemChange().
mouseDoubleClickEvent()
void DynamicElementTextItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
DynamicElementTextItem::mouseDoubleClickEvent Reimplemented functions, for add extra feature when this text is owned by a slave. In this case if the parent slave element is linked to a master, and this text display the label of the master (both if the 'text from' is 'element info' or 'composite text') the QGraphicsView go to master and select it.
Parameters
event
Definition at line 601 of file dynamicelementtextitem.cpp.
References DiagramTextItem::mouseDoubleClickEvent(), and zoomToLinkedElement().
mouseMoveEvent()
void DynamicElementTextItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
DynamicElementTextItem::mouseMoveEvent.
Parameters
event
Definition at line 546 of file dynamicelementtextitem.cpp.
References ElementTextsMover::beginMovement(), ElementTextsMover::continueMovement(), DiagramTextItem::diagram(), Diagram::elementTextsMover(), DiagramTextItem::m_first_move, m_initial_position, parentElement(), Element::setHighlighted(), and Diagram::snapToGrid().
mousePressEvent()
void DynamicElementTextItem::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
DynamicElementTextItem::mousePressEvent.
Parameters
event
Definition at line 527 of file dynamicelementtextitem.cpp.
References m_slave_Xref_item, m_user_color, and DiagramTextItem::mousePressEvent().
mouseReleaseEvent()
void DynamicElementTextItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
DynamicElementTextItem::mouseReleaseEvent.
Parameters
event
Definition at line 582 of file dynamicelementtextitem.cpp.
References m_parent_element.
paint()
void DynamicElementTextItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override protected
Definition at line 650 of file dynamicelementtextitem.cpp.
References DiagramTextItem::color, QETApp::dynamicTextsItemFont(), DiagramTextItem::font, DiagramTextItem::frameRect(), m_frame, DiagramTextItem::paint(), and QET::Icons::ro.
parentElement()
Element * DynamicElementTextItem::parentElement () const
DynamicElementTextItem::ParentElement.
Returns
a pointer to the parent element. Note the pointer can be null. Note that the text can return a parent element, even if the text belong to a group of this same element.
Definition at line 227 of file dynamicelementtextitem.cpp.
References m_parent_element.
Referenced by DynamicTextItemDelegate::availableInfo(), DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), ElementPropertiesWidget::ElementPropertiesWidget(), elementUseForInfo(), hoverEnterEvent(), mouseMoveEvent(), DeleteQGraphicsItemCommand::redo(), reportChanged(), reportFormulaChanged(), ElementPropertiesWidget::setDynamicText(), setPotentialConductor(), CompositeTextEditDialog::setUpComboBox(), and zoomToLinkedElement().
parentGroup()
ElementTextItemGroup * DynamicElementTextItem::parentGroup () const
DynamicElementTextItem::parentGroup.
Returns
The group where this text belong, if this item is note in a group, return nullptr.
Definition at line 236 of file dynamicelementtextitem.cpp.
Referenced by DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), DynamicElementTextModel::itemsForText(), DeleteQGraphicsItemCommand::redo(), updateXref(), and AddElementTextCommand::~AddElementTextCommand().
plainTextChanged
void DynamicElementTextItem::plainTextChanged () signal
Referenced by ElementTextItemGroup::addToGroup(), elementInfoChanged(), and ElementTextItemGroup::removeFromGroup().
refreshLabelConnection()
void DynamicElementTextItem::refreshLabelConnection ()
DynamicElementTextItem::refreshLabelConnection Refresh the connection of this text when the source of text is label, or composite text, with a variable %{label}.
Definition at line 293 of file dynamicelementtextitem.cpp.
References Element::AllReport, CompositeText, ElementInfo, m_composite_text, m_info_name, m_parent_element, m_text_from, setupFormulaConnection(), updateLabel(), updateReportFormulaConnection(), and updateReportText().
removeConnectionForReportFormula()
void DynamicElementTextItem::removeConnectionForReportFormula (const QString & formula) private
Definition at line 923 of file dynamicelementtextitem.cpp.
References Diagram::border_and_titleblock, m_F_str, m_other_report, Diagram::project(), QETProject::projectDiagramsOrderChanged(), BorderTitleBlock::titleBlockFolioChanged(), updateReportFormulaConnection(), and updateReportText().
Referenced by reportChanged(), setCompositeText(), setInfoName(), and updateReportFormulaConnection().
reportChanged()
void DynamicElementTextItem::reportChanged () private
DynamicElementTextItem::reportChanged This function is only use when parent element of this text is a folio report The linked report of the parent element was changed.
Definition at line 841 of file dynamicelementtextitem.cpp.
References CompositeText, QETProject::defaultReportProperties(), QetGraphicsItem::diagram(), DiagramTextItem::diagram(), ElementInfo, m_composite_text, m_info_name, m_other_report, m_parent_element, m_report_formula, m_report_formula_con, parentElement(), Diagram::project(), removeConnectionForReportFormula(), reportFormulaChanged(), QETProject::reportPropertiesChanged(), setConnectionForReportFormula(), setPotentialConductor(), textFrom, and updateReportText().
Referenced by itemChange().
reportFormulaChanged()
void DynamicElementTextItem::reportFormulaChanged () private
DynamicElementTextItem::reportFormulaChanged The report formula use in the project was changed.
Definition at line 886 of file dynamicelementtextitem.cpp.
References QETProject::defaultReportProperties(), QetGraphicsItem::diagram(), ElementInfo, m_info_name, m_report_formula, m_text_from, parentElement(), Diagram::project(), and updateReportText().
Referenced by itemChange(), and reportChanged().
reportReplacedCompositeText()
QString DynamicElementTextItem::reportReplacedCompositeText () const private
DynamicElementTextItem::reportReplacedCompositeText This function is only used when the parent element of this text is a report element.
Returns
the composite text with the variable replaced by the real value. If the parent element of this text is not a folio report, return a default QString.
Definition at line 1170 of file dynamicelementtextitem.cpp.
References Element::AllReport, QetGraphicsItem::diagram(), autonum::AssignVariables::formulaToLabel(), m_composite_text, m_other_report, m_parent_element, m_report_formula, m_watched_conductor, and Element::rSequenceStruct().
Referenced by conductorPropertiesChanged(), and updateReportText().
sceneEventFilter()
bool DynamicElementTextItem::sceneEventFilter (QGraphicsItem * watched, QEvent * event) override protected
Definition at line 744 of file dynamicelementtextitem.cpp.
References m_slave_Xref_item, and zoomToLinkedElement().
setCompositeText()
void DynamicElementTextItem::setCompositeText (const QString & text)
DynamicElementTextItem::setCompositeText Set the composite text of this text item to text.
Parameters
text
Definition at line 454 of file dynamicelementtextitem.cpp.
References Element::AllReport, clearFormulaConnection(), CompositeText, compositeTextChanged(), Element::elementInformations(), elementUseForInfo(), m_composite_text, m_parent_element, m_report_formula, m_text_from, removeConnectionForReportFormula(), autonum::AssignVariables::replaceVariable(), setConnectionForReportFormula(), setPlainText(), setupFormulaConnection(), text, updateLabel(), updateReportText(), and updateXref().
Referenced by fromXml().
setConnectionForReportFormula()
void DynamicElementTextItem::setConnectionForReportFormula (const QString & formula) private
Definition at line 894 of file dynamicelementtextitem.cpp.
References Diagram::border_and_titleblock, QETProject::diagramRemoved(), BorderTitleBlock::folio(), m_F_str, m_other_report, Diagram::project(), QETProject::projectDiagramsOrderChanged(), BorderTitleBlock::titleBlockFolioChanged(), updateReportFormulaConnection(), and updateReportText().
Referenced by reportChanged(), setCompositeText(), setInfoName(), and updateReportFormulaConnection().
setFrame()
void DynamicElementTextItem::setFrame (const bool frame)
Definition at line 506 of file dynamicelementtextitem.cpp.
References frame, frameChanged(), and m_frame.
Referenced by fromXml(), and Element::fromXml().
setInfoName()
void DynamicElementTextItem::setInfoName (const QString & info_name)
DynamicElementTextItem::setInfoName Set the information name of the parent element.
Parameters
info_name
Definition at line 400 of file dynamicelementtextitem.cpp.
References Element::AllReport, clearFormulaConnection(), conductorPropertiesChanged(), ElementInfo, elementUseForInfo(), infoNameChanged(), m_info_name, m_parent_element, m_report_formula, m_text_from, removeConnectionForReportFormula(), setConnectionForReportFormula(), setPlainText(), setupFormulaConnection(), updateLabel(), updateReportText(), and updateXref().
Referenced by fromXml(), Element::fromXml(), and Element::parseInput().
setPlainText()
void DynamicElementTextItem::setPlainText (const QString & text)
Definition at line 1322 of file dynamicelementtextitem.cpp.
References CrossRefItem::autoPos(), QETProject::defaultXRefProperties(), DiagramTextItem::diagram(), DiagramTextItem::finishAlignment(), XRefProperties::getXrefPos(), QET::GIBuildingFromXml, QET::GILoadingFromXml, m_master_element, m_parent_element, m_slave_Xref_item, m_text_width, m_Xref_item, DiagramTextItem::prepareAlignment(), Diagram::project(), QETProject::ProjectParsingRunning, DiagramTextItem::setPlainText(), setXref_item(), and text.
Referenced by conductorPropertiesChanged(), elementInfoChanged(), fromXml(), setCompositeText(), setInfoName(), setText(), setTextFrom(), updateLabel(), and updateReportText().
setPotentialConductor()
void DynamicElementTextItem::setPotentialConductor () private
DynamicElementTextItem::setPotentialConductor This function is only used when the parent element of this text is a report element Get a conductor in the potential of the parent report.
Definition at line 1094 of file dynamicelementtextitem.cpp.
References Element::AllReport, conductorPropertiesChanged(), m_other_report, m_watched_conductor, parentElement(), Conductor::propertiesChange(), and Element::terminals().
Referenced by conductorWasAdded(), conductorWasRemoved(), itemChange(), and reportChanged().
setText()
void DynamicElementTextItem::setText (const QString & text)
DynamicElementTextItem::setText Set the text of this text.
Parameters
text
Definition at line 387 of file dynamicelementtextitem.cpp.
References m_text, m_text_from, setPlainText(), text, textChanged(), and UserText.
Referenced by DynamicElementTextItem(), fromXml(), and Element::parseInput().
setTextFrom()
void DynamicElementTextItem::setTextFrom (DynamicElementTextItem::TextFrom text_from)
DynamicElementTextItem::setTextFrom Set the final text is created from.
Parameters
text_from
Definition at line 324 of file dynamicelementtextitem.cpp.
References clearFormulaConnection(), CompositeText, ElementInfo, Element::elementInfoChange(), elementInfoChanged(), elementUseForInfo(), m_composite_text, m_info_name, m_parent_element, m_text, m_text_from, Element::Master, autonum::AssignVariables::replaceVariable(), DiagramTextItem::setNoEditable(), setPlainText(), setupFormulaConnection(), Element::Slave, textFromChanged(), updateLabel(), updateXref(), and UserText.
Referenced by fromXml(), Element::fromXml(), and Element::parseInput().
setTextWidth()
void DynamicElementTextItem::setTextWidth (qreal width)
Definition at line 1369 of file dynamicelementtextitem.cpp.
References m_text_width, and textWidthChanged().
Referenced by DynamicElementTextItem(), fromXml(), and Element::fromXml().
setupFormulaConnection()
void DynamicElementTextItem::setupFormulaConnection () private
DynamicElementTextItem::setupFormulaConnection Setup the required connection for the formula of the label.
Definition at line 953 of file dynamicelementtextitem.cpp.
References Diagram::border_and_titleblock, clearFormulaConnection(), CompositeText, QetGraphicsItem::diagram(), DiagramTextItem::diagram(), QETProject::diagramRemoved(), ElementInfo, Element::elementInformations(), elementUseForInfo(), BorderTitleBlock::folio(), Element::isFreezeLabel(), m_composite_text, m_F_str, m_formula_connection, m_info_name, m_text_from, Diagram::project(), QETProject::projectDiagramsOrderChanged(), BorderTitleBlock::titleBlockFolioChanged(), updateLabel(), and DiagramContext::value().
Referenced by elementInfoChanged(), refreshLabelConnection(), setCompositeText(), setInfoName(), and setTextFrom().
setXref_item()
void DynamicElementTextItem::setXref_item (Qt::AlignmentFlag m_exHrefPos)
Definition at line 1376 of file dynamicelementtextitem.cpp.
References DiagramTextItem::alignment, and m_slave_Xref_item.
Referenced by setPlainText(), and updateXref().
text()
QString DynamicElementTextItem::text () const
DynamicElementTextItem::text.
Returns
the text of this text
Definition at line 378 of file dynamicelementtextitem.cpp.
References m_text.
textChanged
void DynamicElementTextItem::textChanged (QString text) signal
Referenced by ElementTextItemGroup::addToGroup(), ElementTextItemGroup::removeFromGroup(), DynamicElementTextModel::setConnection(), and setText().
textFrom()
DynamicElementTextItem::TextFrom DynamicElementTextItem::textFrom () const
DynamicElementTextItem::textFrom.
Returns
what the final text is created from.
Definition at line 315 of file dynamicelementtextitem.cpp.
References m_text_from.
textFromChanged
void DynamicElementTextItem::textFromChanged (DynamicElementTextItem::TextFrom text_from) signal
Referenced by ElementTextItemGroup::addToGroup(), ElementTextItemGroup::removeFromGroup(), DynamicElementTextModel::setConnection(), and setTextFrom().
textFromMetaEnum()
QMetaEnum DynamicElementTextItem::textFromMetaEnum () static
DynamicElementTextItem::textFromMetaEnum.
Returns
The QMetaEnum of the enum TextFrom
Definition at line 72 of file dynamicelementtextitem.cpp.
Referenced by PartDynamicTextField::fromXml(), fromXml(), PartDynamicTextField::toXml(), and toXml().
textWidthChanged
void DynamicElementTextItem::textWidthChanged (qreal width) signal
Referenced by ElementTextItemGroup::addToGroup(), ElementTextItemGroup::removeFromGroup(), DynamicElementTextModel::setConnection(), and setTextWidth().
toXml()
QDomElement DynamicElementTextItem::toXml (QDomDocument & dom_doc) const override virtual
DynamicElementTextItem::toXml Export this text to xml.
Parameters
dom_doc
Returns
Reimplemented from DiagramTextItem.
Definition at line 87 of file dynamicelementtextitem.cpp.
References DiagramTextItem::alignment, DiagramTextItem::color, QET::correctAngle(), DiagramTextItem::font, m_composite_text, m_frame, m_info_name, m_text_from, m_text_width, m_uuid, textFromMetaEnum(), and xmlTagName().
type()
int DynamicElementTextItem::type () const inline override
Definition at line 62 of file dynamicelementtextitem.h.
References Type.
updateLabel()
void DynamicElementTextItem::updateLabel () private
DynamicElementTextItem::updateLabel Update the displayed text, when this dynamic text is based on the label of the parent element. This function is notably use when the label itself is based from a formula. If this dynamic text isn't based on label, this function do nothing.
Definition at line 1042 of file dynamicelementtextitem.cpp.
References Element::actualLabel(), CompositeText, ElementInfo, Element::elementInformations(), elementUseForInfo(), m_composite_text, m_info_name, m_text_from, autonum::AssignVariables::replaceVariable(), and setPlainText().
Referenced by refreshLabelConnection(), setCompositeText(), setInfoName(), setTextFrom(), and setupFormulaConnection().
updateReportFormulaConnection()
void DynamicElementTextItem::updateReportFormulaConnection () private
Definition at line 998 of file dynamicelementtextitem.cpp.
References Element::AllReport, m_parent_element, m_report_formula, removeConnectionForReportFormula(), setConnectionForReportFormula(), and updateReportText().
Referenced by refreshLabelConnection(), removeConnectionForReportFormula(), and setConnectionForReportFormula().
updateReportText()
void DynamicElementTextItem::updateReportText () private
DynamicElementTextItem::updateReportText This function is only use when this text is owned by a report, and this text have for info the Label.
Definition at line 1012 of file dynamicelementtextitem.cpp.
References Element::AllReport, CompositeText, QetGraphicsItem::diagram(), ElementInfo, autonum::AssignVariables::formulaToLabel(), m_info_name, m_other_report, m_parent_element, m_report_formula, m_text_from, reportReplacedCompositeText(), Element::rSequenceStruct(), and setPlainText().
Referenced by refreshLabelConnection(), removeConnectionForReportFormula(), reportChanged(), reportFormulaChanged(), setCompositeText(), setConnectionForReportFormula(), setInfoName(), and updateReportFormulaConnection().
updateXref()
void DynamicElementTextItem::updateXref ()
DynamicElementTextItem::updateXref Create or delete the Xref according to the current properties of the project.
Definition at line 1251 of file dynamicelementtextitem.cpp.
References CompositeText, QETProject::defaultXRefProperties(), DiagramTextItem::diagram(), QETProject::diagramRemoved(), QETApp::diagramTextsFont(), ElementInfo, Element::elementInfoChange(), autonum::AssignVariables::formulaToLabel(), XRefProperties::getXrefPos(), XRefProperties::Label, m_composite_text, m_info_name, m_master_element, m_parent_element, m_slave_Xref_item, m_text_from, m_update_slave_Xref_connection, m_Xref_item, Element::Master, parentGroup(), Diagram::project(), QETProject::projectDiagramsOrderChanged(), setXref_item(), Element::Slave, XRefProperties::slaveLabel(), XRefProperties::snapTo(), and QETProject::XRefPropertiesChanged().
Referenced by itemChange(), DynamicElementTextModel::itemDataChanged(), masterChanged(), setCompositeText(), setInfoName(), and setTextFrom().
uuid()
QUuid DynamicElementTextItem::uuid () const
Definition at line 518 of file dynamicelementtextitem.cpp.
References m_uuid.
Referenced by DynamicElementTextModel::mimeData().
xmlTagName()
static QString DynamicElementTextItem::xmlTagName () inline static
Definition at line 94 of file dynamicelementtextitem.h.
Referenced by fromXml(), Element::fromXml(), Element::parseDynamicText(), and toXml().
zoomToLinkedElement()
void DynamicElementTextItem::zoomToLinkedElement () private
DynamicElementTextItem::zoomToLinkedElement If the parent element is a folio report or a slave element, and is linked, zoom to the linked element.
Definition at line 1206 of file dynamicelementtextitem.cpp.
References Element::AllReport, CompositeText, QetGraphicsItem::diagram(), ElementInfo, m_composite_text, m_info_name, m_master_element, m_other_report, m_text_from, parentElement(), Diagram::showMe(), and Element::Slave.
Referenced by mouseDoubleClickEvent(), and sceneEventFilter().
Friends And Related Function Documentation
CompositeTextEditDialog
friend class CompositeTextEditDialog friend
Definition at line 41 of file dynamicelementtextitem.h.
DynamicTextItemDelegate
friend class DynamicTextItemDelegate friend
Definition at line 40 of file dynamicelementtextitem.h.
Element
friend class Element friend
Definition at line 42 of file dynamicelementtextitem.h.
Member Data Documentation
m_composite_text
QString DynamicElementTextItem::m_composite_text private
Definition at line 146 of file dynamicelementtextitem.h.
Referenced by compositeText(), elementInfoChanged(), hoverEnterEvent(), refreshLabelConnection(), reportChanged(), reportReplacedCompositeText(), setCompositeText(), setTextFrom(), setupFormulaConnection(), toXml(), updateLabel(), updateXref(), and zoomToLinkedElement().
m_F_str
QString DynamicElementTextItem::m_F_str private
Definition at line 148 of file dynamicelementtextitem.h.
Referenced by removeConnectionForReportFormula(), setConnectionForReportFormula(), and setupFormulaConnection().
m_first_scene_change
bool DynamicElementTextItem::m_first_scene_change = true private
Definition at line 158 of file dynamicelementtextitem.h.
Referenced by itemChange().
m_formula_connection
QList<QMetaObject::Connection> DynamicElementTextItem::m_formula_connection private
Definition at line 153 of file dynamicelementtextitem.h.
Referenced by clearFormulaConnection(), and setupFormulaConnection().
m_frame
bool DynamicElementTextItem::m_frame = false private
Definition at line 157 of file dynamicelementtextitem.h.
Referenced by frame(), paint(), setFrame(), and toXml().
m_info_name
QString DynamicElementTextItem::m_info_name private
Definition at line 145 of file dynamicelementtextitem.h.
Referenced by conductorPropertiesChanged(), elementInfoChanged(), hoverEnterEvent(), infoName(), refreshLabelConnection(), reportChanged(), reportFormulaChanged(), setInfoName(), setTextFrom(), setupFormulaConnection(), toXml(), updateLabel(), updateReportText(), updateXref(), and zoomToLinkedElement().
m_initial_position
QPointF DynamicElementTextItem::m_initial_position private
Definition at line 162 of file dynamicelementtextitem.h.
Referenced by mouseMoveEvent().
m_master_element
QPointer<Element> DynamicElementTextItem::m_master_element private
Definition at line 140 of file dynamicelementtextitem.h.
Referenced by masterChanged(), setPlainText(), updateXref(), and zoomToLinkedElement().
m_other_report
QPointer<Element> DynamicElementTextItem::m_other_report private
Definition at line 141 of file dynamicelementtextitem.h.
Referenced by hoverEnterEvent(), removeConnectionForReportFormula(), reportChanged(), reportReplacedCompositeText(), setConnectionForReportFormula(), setPotentialConductor(), updateReportText(), and zoomToLinkedElement().
m_parent_element
QPointer<Element> DynamicElementTextItem::m_parent_element private
Definition at line 139 of file dynamicelementtextitem.h.
Referenced by conductorPropertiesChanged(), DynamicElementTextItem(), itemChange(), mouseReleaseEvent(), parentElement(), refreshLabelConnection(), reportChanged(), reportReplacedCompositeText(), setCompositeText(), setInfoName(), setPlainText(), setTextFrom(), updateReportFormulaConnection(), updateReportText(), and updateXref().
m_report_formula
QString DynamicElementTextItem::m_report_formula private
Definition at line 147 of file dynamicelementtextitem.h.
Referenced by itemChange(), reportChanged(), reportFormulaChanged(), reportReplacedCompositeText(), setCompositeText(), setInfoName(), updateReportFormulaConnection(), and updateReportText().
m_report_formula_con
QMetaObject::Connection DynamicElementTextItem::m_report_formula_con private
Definition at line 151 of file dynamicelementtextitem.h.
Referenced by itemChange(), and reportChanged().
m_slave_Xref_item
QGraphicsTextItem* DynamicElementTextItem::m_slave_Xref_item = nullptr private
Definition at line 160 of file dynamicelementtextitem.h.
Referenced by mousePressEvent(), sceneEventFilter(), setPlainText(), setXref_item(), and updateXref().
m_text
QString DynamicElementTextItem::m_text private
Definition at line 144 of file dynamicelementtextitem.h.
Referenced by elementInfoChanged(), setText(), setTextFrom(), and text().
m_text_from
DynamicElementTextItem::TextFrom DynamicElementTextItem::m_text_from = UserText private
Definition at line 149 of file dynamicelementtextitem.h.
Referenced by conductorPropertiesChanged(), elementInfoChanged(), fromXml(), hoverEnterEvent(), masterChanged(), refreshLabelConnection(), reportFormulaChanged(), setCompositeText(), setInfoName(), setText(), setTextFrom(), setupFormulaConnection(), textFrom(), toXml(), updateLabel(), updateReportText(), updateXref(), and zoomToLinkedElement().
m_text_width
qreal DynamicElementTextItem::m_text_width = -1 private
Definition at line 161 of file dynamicelementtextitem.h.
Referenced by setPlainText(), setTextWidth(), and toXml().
m_update_slave_Xref_connection
QList<QMetaObject::Connection> DynamicElementTextItem::m_update_slave_Xref_connection private
Definition at line 154 of file dynamicelementtextitem.h.
Referenced by updateXref().
m_user_color
QColor DynamicElementTextItem::m_user_color private
Definition at line 155 of file dynamicelementtextitem.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and mousePressEvent().
m_uuid
QUuid DynamicElementTextItem::m_uuid private
Definition at line 150 of file dynamicelementtextitem.h.
Referenced by fromXml(), Element::parseDynamicText(), toXml(), and uuid().
m_watched_conductor
QPointer<Conductor> DynamicElementTextItem::m_watched_conductor private
Definition at line 142 of file dynamicelementtextitem.h.
Referenced by DynamicTextItemDelegate::availableInfo(), conductorPropertiesChanged(), conductorWasRemoved(), reportReplacedCompositeText(), and setPotentialConductor().
m_Xref_item
CrossRefItem* DynamicElementTextItem::m_Xref_item = nullptr private
Definition at line 159 of file dynamicelementtextitem.h.
Referenced by setPlainText(), and updateXref().
Property Documentation
compositeText
QString DynamicElementTextItem::compositeText read write
Definition at line 42 of file dynamicelementtextitem.h.
Referenced by CompositeTextEditDialog::CompositeTextEditDialog(), DynamicElementTextModel::itemsForText(), DynamicElementTextModel::undoForEditedText(), and DynamicElementTextModel::updateDataFromText().
frame
bool DynamicElementTextItem::frame read write
Definition at line 42 of file dynamicelementtextitem.h.
Referenced by DynamicElementTextModel::itemsForText(), setFrame(), DynamicElementTextModel::undoForEditedText(), and DynamicElementTextModel::updateDataFromText().
infoName
QString DynamicElementTextItem::infoName read write
Definition at line 42 of file dynamicelementtextitem.h.
Referenced by DynamicElementTextModel::itemsForText(), DynamicElementTextModel::undoForEditedText(), and DynamicElementTextModel::updateDataFromText().
text
QString DynamicElementTextItem::text read write
Definition at line 42 of file dynamicelementtextitem.h.
Referenced by setCompositeText(), setPlainText(), setText(), and DynamicElementTextModel::undoForEditedText().
textFrom
TextFrom DynamicElementTextItem::textFrom read write
Definition at line 42 of file dynamicelementtextitem.h.
Referenced by DynamicElementTextModel::itemsForText(), reportChanged(), DynamicElementTextModel::undoForEditedText(), and DynamicElementTextModel::updateDataFromText().
textWidth
qreal DynamicElementTextItem::textWidth read write
Definition at line 42 of file dynamicelementtextitem.h.
Referenced by DynamicElementTextModel::itemsForText(), DynamicElementTextModel::undoForEditedText(), and DynamicElementTextModel::updateDataFromText().
The documentation for this class was generated from the following files:
dynamicelementtextitem.h
dynamicelementtextitem.cpp