QElectroTech: Machine_info Class Reference
Machine_info Class Reference
The Machine_info class This class hold information from your PC.
#include <machine_info.h>
Classes
struct Pc
Public Member Functions
Machine_info (QObject *parent=nullptr)
Machine_info::Machine_info.
int32_t i_max_screen_width ()
Machine_info::i_max_screen_width.
int32_t i_max_screen_height ()
Machine_info::i_max_screen_height.
QString compilation_info ()
Machine_info::compilation_info.
void send_info_to_debug ()
Machine_info::send_info_to_debug.
Private Member Functions
void init_get_Screen_info ()
Machine_info::init_get_Screen_info Finds the largest screen and saves the values.
void init_get_cpu_info ()
Machine_info::init_get_cpu_info.
void init_get_cpu_info_linux ()
Machine_info::init_get_cpu_info_linux.
void init_get_cpu_info_winnt ()
Machine_info::init_get_cpu_info_winnt.
void init_get_cpu_info_macos ()
Machine_info::init_get_cpu_info_macos.
Private Attributes
struct Machine_info::Pc pc
Detailed Description
The Machine_info class This class hold information from your PC.
Definition at line 28 of file machine_info.h.
Constructor & Destructor Documentation
Machine_info()
Machine_info::Machine_info (QObject * parent = nullptr) explicit
Machine_info::Machine_info.
Parameters
parent
Definition at line 36 of file machine_info.cpp.
References init_get_cpu_info(), and init_get_Screen_info().
Member Function Documentation
compilation_info()
QString Machine_info::compilation_info ()
Machine_info::compilation_info.
Returns
compilation_info
Definition at line 303 of file machine_info.cpp.
References Machine_info::Pc::CPU::Architecture, Machine_info::Pc::RAM::Available, Machine_info::Pc::built, Machine_info::Pc::Screen::count, Machine_info::Pc::cpu, Machine_info::Pc::Built::date, Machine_info::Pc::gpu, Machine_info::Pc::Screen::height, Machine_info::Pc::CPU::info, Machine_info::Pc::GPU::info, Machine_info::Pc::OS::kernel, Machine_info::Pc::OS::name, Machine_info::Pc::os, pc, Machine_info::Pc::ram, Machine_info::Pc::GPU::RAM, Machine_info::Pc::screen, Machine_info::Pc::CPU::ThreadCount, Machine_info::Pc::Built::time, Machine_info::Pc::RAM::Total, QET::Icons::tr, Machine_info::Pc::OS::type, Machine_info::Pc::Built::version, and Machine_info::Pc::Screen::width.
Referenced by AboutQETDialog::setVersion().
i_max_screen_height()
int32_t Machine_info::i_max_screen_height ()
Machine_info::i_max_screen_height.
Returns
max screen height
Definition at line 294 of file machine_info.cpp.
References Machine_info::Pc::Screen::Max_height, pc, and Machine_info::Pc::screen.
Referenced by ConfigDialog::ConfigDialog().
i_max_screen_width()
int32_t Machine_info::i_max_screen_width ()
Machine_info::i_max_screen_width.
Returns
max screen width
Definition at line 285 of file machine_info.cpp.
References Machine_info::Pc::Screen::Max_width, pc, and Machine_info::Pc::screen.
Referenced by ConfigDialog::ConfigDialog().
init_get_cpu_info()
void Machine_info::init_get_cpu_info () private
Machine_info::init_get_cpu_info.
Definition at line 141 of file machine_info.cpp.
References init_get_cpu_info_linux(), init_get_cpu_info_macos(), init_get_cpu_info_winnt(), Machine_info::Pc::os, pc, and Machine_info::Pc::OS::type.
Referenced by Machine_info().
init_get_cpu_info_linux()
void Machine_info::init_get_cpu_info_linux () private
Machine_info::init_get_cpu_info_linux.
Definition at line 158 of file machine_info.cpp.
References Machine_info::Pc::RAM::Available, Machine_info::Pc::cpu, Machine_info::Pc::gpu, Machine_info::Pc::CPU::info, Machine_info::Pc::GPU::info, pc, Machine_info::Pc::ram, Machine_info::Pc::GPU::RAM, and Machine_info::Pc::RAM::Total.
Referenced by init_get_cpu_info().
init_get_cpu_info_macos()
void Machine_info::init_get_cpu_info_macos () private
Machine_info::init_get_cpu_info_macos.
Definition at line 258 of file machine_info.cpp.
References Machine_info::Pc::cpu, Machine_info::Pc::CPU::info, pc, Machine_info::Pc::ram, and Machine_info::Pc::RAM::Total.
Referenced by init_get_cpu_info().
init_get_cpu_info_winnt()
void Machine_info::init_get_cpu_info_winnt () private
Machine_info::init_get_cpu_info_winnt.
Definition at line 204 of file machine_info.cpp.
References Machine_info::Pc::RAM::Available, Machine_info::Pc::cpu, Machine_info::Pc::gpu, Machine_info::Pc::CPU::info, Machine_info::Pc::GPU::info, pc, Machine_info::Pc::ram, Machine_info::Pc::GPU::RAM, and Machine_info::Pc::RAM::Total.
Referenced by init_get_cpu_info().
init_get_Screen_info()
void Machine_info::init_get_Screen_info () private
Machine_info::init_get_Screen_info Finds the largest screen and saves the values.
Definition at line 119 of file machine_info.cpp.
References Machine_info::Pc::Screen::count, Machine_info::Pc::Screen::height, Machine_info::Pc::Screen::Max_height, Machine_info::Pc::Screen::Max_width, pc, Machine_info::Pc::screen, and Machine_info::Pc::Screen::width.
Referenced by Machine_info().
send_info_to_debug()
void Machine_info::send_info_to_debug ()
Machine_info::send_info_to_debug.
Definition at line 45 of file machine_info.cpp.
References Machine_info::Pc::CPU::Architecture, Machine_info::Pc::RAM::Available, Machine_info::Pc::built, Machine_info::Pc::Screen::count, Machine_info::Pc::cpu, Machine_info::Pc::Built::date, QET::displayedVersion, Machine_info::Pc::gpu, Machine_info::Pc::Screen::height, Machine_info::Pc::CPU::info, Machine_info::Pc::GPU::info, Machine_info::Pc::OS::kernel, Machine_info::Pc::OS::name, Machine_info::Pc::os, pc, Machine_info::Pc::ram, Machine_info::Pc::GPU::RAM, Machine_info::Pc::screen, Machine_info::Pc::CPU::ThreadCount, Machine_info::Pc::Built::time, Machine_info::Pc::RAM::Total, QET::Icons::tr, Machine_info::Pc::OS::type, QET::version, Machine_info::Pc::Built::version, and Machine_info::Pc::Screen::width.
Referenced by main().
Member Data Documentation
pc
struct Machine_info::Pc Machine_info::pc private
Referenced by compilation_info(), i_max_screen_height(), i_max_screen_width(), init_get_cpu_info(), init_get_cpu_info_linux(), init_get_cpu_info_macos(), init_get_cpu_info_winnt(), init_get_Screen_info(), and send_info_to_debug().
The documentation for this class was generated from the following files:
machine_info.h
machine_info.cpp