QElectroTech: DiagramContent Class Reference
DiagramContent Class Reference
#include <diagramcontent.h>
Public Types
enum Filter {
Elements = 1, TextFields = 2, ElementTextFields = 4, Images = 8,
ConductorsToMove = 16, ConductorsToUpdate = 32, OtherConductors = 64, AnyConductor = 112,
Shapes = 128, TextGroup = 256, Tables = 512, All = 1023,
SelectedOnly = 1024
}
Used to filter the different items carried by this container.
Public Member Functions
DiagramContent ()
DiagramContent::DiagramContent.
DiagramContent (Diagram *diagram, bool selected=true)
DiagramContent::DiagramContent Constructor.
~DiagramContent ()
QList< DiagramTextItem * > selectedTexts () const
DiagramContent::selectedTexts.
QList< ElementTextItemGroup * > selectedTextsGroup () const
DiagramContent::selectedTextsGroup.
QList< Conductor * > conductors (int=AnyConductor) const
DiagramContent::conductors.
bool hasDeletableItems () const
DiagramContent::hasDeletableItems.
bool hasCopiableItems () const
DiagramContent::hasCopiableItems.
QList< QGraphicsItem * > items (int=All) const
DiagramContent::items.
QString sentence (int=All) const
DiagramContent::sentence.
int count (int=All) const
DiagramContent::count.
void clear ()
DiagramContent::clear Remove all items from the diagram content.
int removeNonMovableItems ()
DiagramContent::removeNonMovableItems Remove all non movable item.
DiagramContent & operator+= (const DiagramContent &other)
bool potentialIsManaged (QList< Conductor * >conductors)
DiagramContent::potentialIsManaged.
bool hasTextEditing ()
DiagramContent::hasTextEditing.
Public Attributes
QList< Element * > m_elements
QSet< IndependentTextItem * > m_text_fields
QSet< DiagramImageItem * > m_images
QSet< QetShapeItem * > m_shapes
QList< Conductor * > m_conductors_to_update
QList< Conductor * > m_conductors_to_move
QList< Conductor * > m_other_conductors
QList< Conductor * > m_potential_conductors
QSet< DynamicElementTextItem * > m_element_texts
QSet< ElementTextItemGroup * > m_texts_groups
QList< QGraphicsItem * > m_selected_items
QVector< QetGraphicsTableItem * > m_tables
Detailed Description
This class provides a container that makes the transmission of diagram content to other functions/methods easier. The different kind of items are made available through a handful of filter-aware methods. Considering selected elements are to be moved, the filter notably distinguishes conductors to be moved from those to be updated. Please note this container does not systematically contains a whole diagram: it may describe only a part of it, e.g. selected items.
Definition at line 45 of file diagramcontent.h.
Member Enumeration Documentation
Filter
enum DiagramContent::Filter
Used to filter the different items carried by this container.
Enumerator
Elements
TextFields
ElementTextFields
Images
ConductorsToMove
ConductorsToUpdate
OtherConductors
AnyConductor
Shapes
TextGroup
Tables
All
SelectedOnly
Definition at line 53 of file diagramcontent.h.
Constructor & Destructor Documentation
DiagramContent() [1/2]
DiagramContent::DiagramContent ()
DiagramContent::DiagramContent.
Definition at line 35 of file diagramcontent.cpp.
DiagramContent() [2/2]
DiagramContent::DiagramContent (Diagram * diagram, bool selected = true)
DiagramContent::DiagramContent Constructor.
Parameters
diagram : Construct a diagramContent and fill it with the selected item of diagram
selected : this diagramcontent get only selected items if true.
Definition at line 44 of file diagramcontent.cpp.
References m_conductors_to_move, m_conductors_to_update, m_elements, m_other_conductors, m_potential_conductors, m_selected_items, m_texts_groups, potentialIsManaged(), IndependentTextItem::Type, DiagramImageItem::Type, QetGraphicsTableItem::Type, DynamicElementTextItem::Type, QetShapeItem::Type, Conductor::Type, and Element::Type.
~DiagramContent()
DiagramContent::~DiagramContent ()
Definition at line 120 of file diagramcontent.cpp.
Member Function Documentation
clear()
void DiagramContent::clear ()
DiagramContent::clear Remove all items from the diagram content.
Definition at line 227 of file diagramcontent.cpp.
References m_conductors_to_move, m_conductors_to_update, m_element_texts, m_elements, m_images, m_other_conductors, m_selected_items, m_shapes, m_tables, m_text_fields, and m_texts_groups.
Referenced by ElementsMover::endMovement(), and MultiPasteDialog::updatePreview().
conductors()
QList< Conductor * > DiagramContent::conductors (int filter = AnyConductor) const
DiagramContent::conductors.
Parameters
filter
Returns
Every conductors according to the filter
Definition at line 167 of file diagramcontent.cpp.
References ConductorsToMove, ConductorsToUpdate, m_conductors_to_move, m_conductors_to_update, m_other_conductors, OtherConductors, and SelectedOnly.
Referenced by DiagramView::editSelectedConductorColor(), ConductorNumExport::fillHash(), items(), potentialIsManaged(), Diagram::potentials(), DeleteQGraphicsItemCommand::redo(), and sentence().
count()
int DiagramContent::count (int filter = All) const
DiagramContent::count.
Parameters
filter
Returns
The number of items, according to filter
Definition at line 401 of file diagramcontent.cpp.
References ConductorsToMove, ConductorsToUpdate, Elements, ElementTextFields, Images, m_conductors_to_move, m_conductors_to_update, m_element_texts, m_elements, m_images, m_other_conductors, m_shapes, m_tables, m_text_fields, m_texts_groups, OtherConductors, SelectedOnly, Shapes, Tables, TextFields, and TextGroup.
Referenced by ElementsMover::beginMovement(), MultiPasteDialog::on_m_button_box_accepted(), DiagramView::paste(), QETDiagramEditor::slot_updateComplexActions(), and MultiPasteDialog::updatePreview().
hasCopiableItems()
bool DiagramContent::hasCopiableItems () const
DiagramContent::hasCopiableItems.
Returns
true if this diagram content have copiable items.
Definition at line 213 of file diagramcontent.cpp.
References m_elements, m_images, m_shapes, and m_text_fields.
Referenced by QETDiagramEditor::slot_updateComplexActions().
hasDeletableItems()
bool DiagramContent::hasDeletableItems () const
DiagramContent::hasDeletableItems.
Returns
true if this diagram content have deletable item The deletable items correspond to the selected items of diagram at the moment of the creation of this DiagramContent, with the constructor : DiagramContent::DiagramContent(Diagram *diagram)
Definition at line 190 of file diagramcontent.cpp.
References m_selected_items, IndependentTextItem::Type, DiagramImageItem::Type, QetGraphicsTableItem::Type, DynamicElementTextItem::Type, QetShapeItem::Type, Conductor::Type, and Element::Type.
Referenced by QETDiagramEditor::slot_updateComplexActions().
hasTextEditing()
bool DiagramContent::hasTextEditing ()
DiagramContent::hasTextEditing.
Returns
true if handle a text currently in editing intercation
Definition at line 358 of file diagramcontent.cpp.
References selectedTexts().
Referenced by DiagramView::keyPressEvent().
items()
QList< QGraphicsItem * > DiagramContent::items (int filter = All) const
DiagramContent::items.
Parameters
filter
Returns
The items of this diagram content according to filter
Definition at line 374 of file diagramcontent.cpp.
References conductors(), Elements, ElementTextFields, Images, m_element_texts, m_elements, m_images, m_shapes, m_tables, m_text_fields, m_texts_groups, SelectedOnly, Shapes, Tables, TextFields, and TextGroup.
Referenced by Diagram::changeZValue(), ElementsMover::continueMovement(), DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), ElementsMover::endMovement(), DiagramView::keyPressEvent(), Diagram::keyPressEvent(), MoveElementsCommand::move(), PasteDiagramCommand::PasteDiagramCommand(), DeleteQGraphicsItemCommand::redo(), PasteDiagramCommand::redo(), DiagramView::scrollOnMovement(), DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements(), QETDiagramEditor::slot_updateComplexActions(), DeleteQGraphicsItemCommand::terminalInSamePotential(), DeleteQGraphicsItemCommand::undo(), PasteDiagramCommand::undo(), MultiPasteDialog::updatePreview(), DeleteQGraphicsItemCommand::~DeleteQGraphicsItemCommand(), MultiPasteDialog::~MultiPasteDialog(), and PasteDiagramCommand::~PasteDiagramCommand().
operator+=()
DiagramContent & DiagramContent::operator+= (const DiagramContent & other)
Definition at line 278 of file diagramcontent.cpp.
References m_conductors_to_move, m_conductors_to_update, m_element_texts, m_elements, m_images, m_other_conductors, m_potential_conductors, m_selected_items, m_shapes, m_tables, m_text_fields, m_texts_groups, potentialIsManaged(), and Conductor::relatedPotentialConductors().
potentialIsManaged()
bool DiagramContent::potentialIsManaged (QList< Conductor * > conductors)
DiagramContent::potentialIsManaged.
Parameters
conductors a list of conductors at the same potential.
Returns
true, if m_potential_conductors already have a conductor of this potential.
Definition at line 341 of file diagramcontent.cpp.
References conductors(), and m_potential_conductors.
Referenced by DiagramContent(), and operator+=().
removeNonMovableItems()
int DiagramContent::removeNonMovableItems ()
DiagramContent::removeNonMovableItems Remove all non movable item.
Returns
: return the numbers of removed item
Definition at line 247 of file diagramcontent.cpp.
References m_elements, m_images, and m_shapes.
Referenced by ElementsMover::beginMovement().
selectedTexts()
QList< DiagramTextItem * > DiagramContent::selectedTexts () const
DiagramContent::selectedTexts.
Returns
a list of every selected texts (every kind of texts) Note that the returned list of texts, correspond to the selected texts at the moment of the creation of this DiagramContent, with the constructor : DiagramContent::DiagramContent(Diagram *diagram)
Definition at line 130 of file diagramcontent.cpp.
References m_selected_items, IndependentTextItem::Type, ConductorTextItem::Type, and DynamicElementTextItem::Type.
Referenced by hasTextEditing(), DiagramView::keyPressEvent(), RotateTextsCommand::RotateTextsCommand(), and QETDiagramEditor::slot_updateComplexActions().
selectedTextsGroup()
QList< ElementTextItemGroup * > DiagramContent::selectedTextsGroup () const
DiagramContent::selectedTextsGroup.
Returns
a list of selected texts group Note that the returned list of texts group, correspond to the selected texts group at the moment of the creation of this DiagramContent, with the constructor : DiagramContent::DiagramContent(Diagram *diagram)
Definition at line 150 of file diagramcontent.cpp.
References m_selected_items.
Referenced by RotateTextsCommand::RotateTextsCommand(), and QETDiagramEditor::slot_updateComplexActions().
sentence()
QString DiagramContent::sentence (int filter = All) const
DiagramContent::sentence.
Parameters
filter
Returns
A string that describe the items of the diagram content according to filter. Exemple : X elements, Y conductors etc....
Definition at line 438 of file diagramcontent.cpp.
References conductors(), Elements, QET::ElementsAndConductorsSentence(), ElementTextFields, Images, m_element_texts, m_elements, m_images, m_shapes, m_tables, m_text_fields, Shapes, Tables, and TextFields.
Referenced by CutDiagramCommand::CutDiagramCommand(), DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), MoveElementsCommand::MoveElementsCommand(), and PasteDiagramCommand::PasteDiagramCommand().
Member Data Documentation
m_conductors_to_move
QList<Conductor *> DiagramContent::m_conductors_to_move
Definition at line 74 of file diagramcontent.h.
Referenced by clear(), conductors(), Diagram::content(), count(), DiagramContent(), MoveElementsCommand::move(), operator+=(), and PasteDiagramCommand::redo().
m_conductors_to_update
QList<Conductor *> DiagramContent::m_conductors_to_update
Definition at line 73 of file diagramcontent.h.
Referenced by clear(), conductors(), ElementsMover::continueMovement(), count(), DiagramContent(), MoveElementsCommand::move(), and operator+=().
m_element_texts
QSet<DynamicElementTextItem *> DiagramContent::m_element_texts
Definition at line 77 of file diagramcontent.h.
Referenced by ImportElementTextPattern::apply(), ElementsMover::beginMovement(), clear(), count(), DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), items(), DynamicElementTextItemEditor::on_m_remove_selection_clicked(), operator+=(), DeleteQGraphicsItemCommand::redo(), QETDiagramEditor::selectionGroupTriggered(), sentence(), QETDiagramEditor::slot_updateComplexActions(), and DeleteQGraphicsItemCommand::undo().
m_elements
QList<Element *> DiagramContent::m_elements
Definition at line 69 of file diagramcontent.h.
Referenced by ElementsMover::beginMovement(), clear(), Diagram::content(), count(), QETDiagramEditor::currentElement(), DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), DiagramContent(), ElementsMover::endMovement(), SearchAndReplaceWidget::fillItemsList(), hasCopiableItems(), items(), Diagram::keyPressEvent(), operator+=(), DeleteQGraphicsItemCommand::redo(), PasteDiagramCommand::redo(), removeNonMovableItems(), sentence(), DeleteQGraphicsItemCommand::setPotentialsOfRemovedElements(), and DeleteQGraphicsItemCommand::undo().
m_images
QSet<DiagramImageItem *> DiagramContent::m_images
Definition at line 71 of file diagramcontent.h.
Referenced by clear(), count(), hasCopiableItems(), items(), operator+=(), removeNonMovableItems(), and sentence().
m_other_conductors
QList<Conductor *> DiagramContent::m_other_conductors
Definition at line 75 of file diagramcontent.h.
Referenced by clear(), conductors(), count(), DiagramContent(), and operator+=().
m_potential_conductors
QList<Conductor *> DiagramContent::m_potential_conductors
Definition at line 76 of file diagramcontent.h.
Referenced by DiagramContent(), SearchAndReplaceWidget::fillItemsList(), operator+=(), and potentialIsManaged().
m_selected_items
QList<QGraphicsItem *> DiagramContent::m_selected_items
Definition at line 79 of file diagramcontent.h.
Referenced by clear(), DiagramContent(), hasDeletableItems(), operator+=(), selectedTexts(), and selectedTextsGroup().
m_shapes
QSet<QetShapeItem *> DiagramContent::m_shapes
Definition at line 72 of file diagramcontent.h.
Referenced by clear(), count(), hasCopiableItems(), items(), operator+=(), removeNonMovableItems(), and sentence().
m_tables
QVector<QetGraphicsTableItem *> DiagramContent::m_tables
Definition at line 80 of file diagramcontent.h.
Referenced by clear(), count(), DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), items(), operator+=(), and sentence().
m_text_fields
QSet<IndependentTextItem *> DiagramContent::m_text_fields
Definition at line 70 of file diagramcontent.h.
Referenced by clear(), Diagram::content(), count(), SearchAndReplaceWidget::fillItemsList(), hasCopiableItems(), items(), operator+=(), and sentence().
m_texts_groups
QSet<ElementTextItemGroup *> DiagramContent::m_texts_groups
Definition at line 78 of file diagramcontent.h.
Referenced by ElementsMover::beginMovement(), clear(), count(), DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), DiagramContent(), items(), and operator+=().
The documentation for this class was generated from the following files:
diagramcontent.h
diagramcontent.cpp