QElectroTech: ProjectPropertiesDialog Class Reference
ProjectPropertiesDialog Class Reference
The ProjectPropertiesDialog class this class builds a dialog to edit whole properties of a project.
#include <projectpropertiesdialog.h>
Public Types
enum Page { Main = 0, Diagram = 1, Autonum = 2 }
Public Member Functions
ProjectPropertiesDialog (QETProject *project, QWidget *parent=nullptr)
ProjectPropertiesDialog::ProjectPropertiesDialog Default constructor.
~ProjectPropertiesDialog () override
ProjectPropertiesDialog::~ProjectPropertiesDialog.
void exec ()
ProjectPropertiesDialog::exec execute this dialog.
void setCurrentPage (ProjectPropertiesDialog::Page)
ProjectPropertiesDialog::setCurrentPage Change the current displayed page by p.
void changeToFolio ()
ProjectPropertiesDialog::changeToFolio Change the current displayed tab to folio tab.
Private Attributes
ConfigDialog * m_properties_dialog
Detailed Description
The ProjectPropertiesDialog class this class builds a dialog to edit whole properties of a project.
Definition at line 30 of file projectpropertiesdialog.h.
Member Enumeration Documentation
Page
enum ProjectPropertiesDialog::Page
Enumerator
Main
Diagram
Autonum
Definition at line 32 of file projectpropertiesdialog.h.
Constructor & Destructor Documentation
ProjectPropertiesDialog()
ProjectPropertiesDialog::ProjectPropertiesDialog (QETProject * project, QWidget * parent = nullptr)
ProjectPropertiesDialog::ProjectPropertiesDialog Default constructor.
Parameters
project : project to edit properties
parent : parent widget of this dialog
Definition at line 30 of file projectpropertiesdialog.cpp.
References m_properties_dialog, and QET::Icons::tr.
~ProjectPropertiesDialog()
ProjectPropertiesDialog::~ProjectPropertiesDialog () override
ProjectPropertiesDialog::~ProjectPropertiesDialog.
Definition at line 47 of file projectpropertiesdialog.cpp.
References m_properties_dialog.
Member Function Documentation
changeToFolio()
void ProjectPropertiesDialog::changeToFolio ()
ProjectPropertiesDialog::changeToFolio Change the current displayed tab to folio tab.
Definition at line 73 of file projectpropertiesdialog.cpp.
References ProjectAutoNumConfigPage::changeToTab(), m_properties_dialog, and ConfigDialog::pages.
Referenced by NewDiagramPage::changeToAutoFolioTab(), and DiagramPropertiesDialog::editAutoFolioNum().
exec()
void ProjectPropertiesDialog::exec ()
ProjectPropertiesDialog::exec execute this dialog.
Definition at line 55 of file projectpropertiesdialog.cpp.
References m_properties_dialog.
Referenced by NewDiagramPage::changeToAutoFolioTab(), DiagramPropertiesDialog::editAutoFolioNum(), DiagramPropertiesDialog::editAutonum(), ProjectView::editProjectProperties(), and AutoNumberingDockWidget::on_m_configure_pb_clicked().
setCurrentPage()
void ProjectPropertiesDialog::setCurrentPage (ProjectPropertiesDialog::Page p)
ProjectPropertiesDialog::setCurrentPage Change the current displayed page by p.
Parameters
p : page to display
Definition at line 65 of file projectpropertiesdialog.cpp.
References m_properties_dialog.
Referenced by NewDiagramPage::changeToAutoFolioTab(), DiagramPropertiesDialog::editAutoFolioNum(), DiagramPropertiesDialog::editAutonum(), and AutoNumberingDockWidget::on_m_configure_pb_clicked().
Member Data Documentation
m_properties_dialog
ConfigDialog* ProjectPropertiesDialog::m_properties_dialog private
Definition at line 45 of file projectpropertiesdialog.h.
Referenced by changeToFolio(), exec(), ProjectPropertiesDialog(), setCurrentPage(), and ~ProjectPropertiesDialog().
The documentation for this class was generated from the following files:
projectpropertiesdialog.h
projectpropertiesdialog.cpp