QElectroTech: DynamicTextItemDelegate Class Reference
DynamicTextItemDelegate Class Reference
#include <dynamicelementtextmodel.h>
Public Member Functions
DynamicTextItemDelegate (QObject *parent=Q_NULLPTR)
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
Protected Member Functions
bool eventFilter (QObject *object, QEvent *event) override
Private Member Functions
QStringList availableInfo (DynamicElementTextItem *deti) const
DynamicTextItemDelegate::availableInfo.
Detailed Description
Definition at line 130 of file dynamicelementtextmodel.h.
Constructor & Destructor Documentation
DynamicTextItemDelegate()
DynamicTextItemDelegate::DynamicTextItemDelegate (QObject * parent = Q_NULLPTR)
Definition at line 1566 of file dynamicelementtextmodel.cpp.
Member Function Documentation
availableInfo()
QStringList DynamicTextItemDelegate::availableInfo (DynamicElementTextItem * deti) const private
DynamicTextItemDelegate::availableInfo.
Parameters
deti
Returns
A list of available info of element
Definition at line 1897 of file dynamicelementtextmodel.cpp.
References Element::AllReport, DiagramContext::contains(), QETApp::elementInfoKeys(), Element::elementInformations(), DynamicElementTextItem::elementUseForInfo(), Element::linkType(), ConductorProperties::m_function, ConductorProperties::m_tension_protocol, DynamicElementTextItem::m_watched_conductor, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, DynamicElementTextItem::parentElement(), and Conductor::properties.
Referenced by createEditor().
createEditor()
QWidget * DynamicTextItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 1570 of file dynamicelementtextmodel.cpp.
References DiagramTextItem::alignment, availableInfo(), DynamicElementTextModel::color, DynamicElementTextModel::compositeText, QETApp::elementTranslatedInfoKey(), DynamicElementTextModel::font, DynamicElementTextModel::grpAlignment, DynamicElementTextModel::grpPos, DynamicElementTextModel::grpRotation, DynamicElementTextModel::grpVAdjust, DynamicElementTextModel::infoText, DynamicElementTextModel::pos, DynamicElementTextModel::rotation, DynamicElementTextModel::size, DynamicElementTextModel::textFrom, DynamicElementTextModel::textFromIndex(), DynamicElementTextModel::textWidth, QET::Icons::tr, and DynamicElementTextModel::txtAlignment.
eventFilter()
bool DynamicTextItemDelegate::eventFilter (QObject * object, QEvent * event) override protected
Definition at line 1850 of file dynamicelementtextmodel.cpp.
setModelData()
void DynamicTextItemDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const override
Definition at line 1740 of file dynamicelementtextmodel.cpp.
References AlignmentTextDialog::alignment(), Element::elementInformations(), DynamicElementTextItem::elementUseForInfo(), CompositeTextEditDialog::plainText(), autonum::AssignVariables::replaceVariable(), and DynamicElementTextModel::textFromIndex().
The documentation for this class was generated from the following files:
dynamicelementtextmodel.h
dynamicelementtextmodel.cpp