QElectroTech: ProjectAutoNumConfigPage Class Reference
ProjectAutoNumConfigPage Class Reference
#include <projectconfigpages.h>
Signals
void setAutoNum (QString)
void setAutoNum (int, int)
void saveCurrentTbp ()
void loadSavedTbp ()
Public Member Functions
ProjectAutoNumConfigPage (QETProject *project, QWidget *parent=nullptr)
ProjectAutoNumConfigPage::ProjectAutoNumConfigPage Default constructor.
QString title () const override
ProjectAutoNumConfigPage::title Title of this config page.
QIcon icon () const override
ProjectAutoNumConfigPage::icon Icon of this config pafe.
void applyProjectConf () override
ProjectAutoNumConfigPage::applyProjectConf.
virtual void changeToTab (int)
ProjectAutoNumConfigPage::changeToTab.
Public Member Functions inherited from ProjectConfigPage
ProjectConfigPage (QETProject *, QWidget *=nullptr)
~ProjectConfigPage () override
virtual QETProject * project () const
virtual QETProject * setProject (QETProject *project, bool=true)
ProjectConfigPage::setProject Set new_project as the project being edited by this page.
void applyConf () override
Public Member Functions inherited from ConfigPage
ConfigPage (QWidget *parent)
~ConfigPage () override
Destructor.
Protected Member Functions
void initWidgets () override
ProjectAutoNumConfigPage::initWidgets Init some widget of this page.
void initLayout () override
void readValuesFromProject () override
ProjectAutoNumConfigPage::readValuesFromProject Read value stored on project, and update display.
void adjustReadOnly () override
ProjectAutoNumConfigPage::adjustReadOnly set this config page disable if project is read only.
Protected Member Functions inherited from ProjectConfigPage
virtual void init ()
Private Slots
void updateContextConductor (const QString &)
ProjectAutoNumConfigPage::updateContext_conductor Display the current selected context for conductor.
void saveContextConductor ()
ProjectAutoNumConfigPage::saveContext_conductor Save the current displayed conductor context in project.
void removeContextConductor ()
ProjectAutoNumConfigPage::removeContext Remove from project the current conductor numerotation context.
void updateContextFolio (const QString &)
ProjectAutoNumConfigPage::updateContext_folio Display the current selected context for folio.
void saveContextFolio ()
ProjectAutoNumConfigPage::saveContext_folio Save the current displayed folio context in project.
void removeContextFolio ()
ProjectAutoNumConfigPage::removeContext_folio Remove from project the current folio numerotation context.
void updateContextElement (const QString &)
ProjectAutoNumConfigPage::updateContextElement Display the current selected context for element.
void saveContextElement ()
ProjectAutoNumConfigPage::saveContextElement Save the current displayed Element formula in project.
void removeContextElement ()
ProjectAutoNumConfigPage::removeContextElement Remove from project the current element numerotation context.
void applyAutoNum ()
ProjectAutoNumConfigPage::applyAutoNum Apply auto folio numbering, New Folios or Selected Folios.
void applyManagement ()
ProjectAutoNumConfigPage::applyAutoManagement Apply Management Options in Selected Folios.
Private Member Functions
void buildConnections ()
ProjectAutoNumConfigPage::buildConnections setup some connections.
Private Attributes
SelectAutonumW * m_saw_conductor
SelectAutonumW * m_saw_folio
SelectAutonumW * m_saw_element
FolioAutonumberingW * m_faw
AutoNumberingManagementW * m_amw
Additional Inherited Members
Protected Attributes inherited from ProjectConfigPage
QETProject * m_project
Currently edited project.
Detailed Description
Definition at line 121 of file projectconfigpages.h.
Constructor & Destructor Documentation
ProjectAutoNumConfigPage()
ProjectAutoNumConfigPage::ProjectAutoNumConfigPage (QETProject * project, QWidget * parent = nullptr)
ProjectAutoNumConfigPage::ProjectAutoNumConfigPage Default constructor.
Parameters
project : project to edit
parent : parent widget
Definition at line 226 of file projectconfigpages.cpp.
References buildConnections(), initWidgets(), and readValuesFromProject().
Member Function Documentation
adjustReadOnly()
void ProjectAutoNumConfigPage::adjustReadOnly () override protected virtual
ProjectAutoNumConfigPage::adjustReadOnly set this config page disable if project is read only.
Implements ProjectConfigPage.
Definition at line 317 of file projectconfigpages.cpp.
applyAutoNum
void ProjectAutoNumConfigPage::applyAutoNum () private slot
ProjectAutoNumConfigPage::applyAutoNum Apply auto folio numbering, New Folios or Selected Folios.
Definition at line 486 of file projectconfigpages.cpp.
References QETProject::autoFolioNumberingNewFolios(), QETProject::autoFolioNumberingSelectedFolios(), FolioAutonumberingW::autoNumSelected(), FolioAutonumberingW::fromFolio(), loadSavedTbp(), m_faw, ProjectConfigPage::m_project, FolioAutonumberingW::newFolios, FolioAutonumberingW::newFoliosNumber(), ProjectConfigPage::project(), saveCurrentTbp(), setAutoNum(), and FolioAutonumberingW::toFolio().
Referenced by buildConnections().
applyManagement
void ProjectAutoNumConfigPage::applyManagement () private slot
ProjectAutoNumConfigPage::applyAutoManagement Apply Management Options in Selected Folios.
Definition at line 510 of file projectconfigpages.cpp.
References QETProject::diagrams(), QETProject::freezeExistentConductorLabel(), QETProject::freezeExistentElementLabel(), QETProject::freezeNewConductorLabel(), QETProject::freezeNewElementLabel(), m_amw, ProjectConfigPage::project(), QETProject::setFreezeNewConductors(), QETProject::setFreezeNewElements(), and AutoNumberingManagementW::ui.
Referenced by buildConnections().
applyProjectConf()
void ProjectAutoNumConfigPage::applyProjectConf () override virtual
ProjectAutoNumConfigPage::applyProjectConf.
Implements ProjectConfigPage.
Definition at line 256 of file projectconfigpages.cpp.
buildConnections()
void ProjectAutoNumConfigPage::buildConnections () private
ProjectAutoNumConfigPage::buildConnections setup some connections.
Definition at line 324 of file projectconfigpages.cpp.
References applyAutoNum(), applyManagement(), SelectAutonumW::applyPressed(), SelectAutonumW::contextComboBox(), m_amw, m_faw, m_saw_conductor, m_saw_element, m_saw_folio, SelectAutonumW::removeClicked(), removeContextConductor(), removeContextElement(), removeContextFolio(), saveContextConductor(), saveContextElement(), saveContextFolio(), updateContextConductor(), updateContextElement(), and updateContextFolio().
Referenced by ProjectAutoNumConfigPage().
changeToTab()
void ProjectAutoNumConfigPage::changeToTab (int i) virtual
ProjectAutoNumConfigPage::changeToTab.
Parameters
i index Change to Selected Tab
Definition at line 629 of file projectconfigpages.cpp.
Referenced by ProjectPropertiesDialog::changeToFolio().
icon()
QIcon ProjectAutoNumConfigPage::icon () const override virtual
ProjectAutoNumConfigPage::icon Icon of this config pafe.
Returns
Implements ConfigPage.
Definition at line 249 of file projectconfigpages.cpp.
References QET::Icons::AutoNum.
initLayout()
void ProjectAutoNumConfigPage::initLayout () inline override protected virtual
Use this pure virtual method to initialize your page layout. This method is always called after initWidgets().
Implements ProjectConfigPage.
Definition at line 135 of file projectconfigpages.h.
initWidgets()
void ProjectAutoNumConfigPage::initWidgets () override protected virtual
ProjectAutoNumConfigPage::initWidgets Init some widget of this page.
Implements ProjectConfigPage.
Definition at line 262 of file projectconfigpages.cpp.
References m_amw, m_faw, m_saw_conductor, m_saw_element, m_saw_folio, ProjectConfigPage::project(), and QET::Icons::tr.
Referenced by ProjectAutoNumConfigPage().
loadSavedTbp
void ProjectAutoNumConfigPage::loadSavedTbp () signal
Referenced by applyAutoNum().
readValuesFromProject()
void ProjectAutoNumConfigPage::readValuesFromProject () override protected virtual
ProjectAutoNumConfigPage::readValuesFromProject Read value stored on project, and update display.
Implements ProjectConfigPage.
Definition at line 295 of file projectconfigpages.cpp.
References QETProject::conductorAutoNum(), SelectAutonumW::contextComboBox(), QETProject::elementAutoNum(), QETProject::folioAutoNum(), m_faw, ProjectConfigPage::m_project, m_saw_conductor, m_saw_element, m_saw_folio, and FolioAutonumberingW::setContext().
Referenced by ProjectAutoNumConfigPage().
removeContextConductor
void ProjectAutoNumConfigPage::removeContextConductor () private slot
ProjectAutoNumConfigPage::removeContext Remove from project the current conductor numerotation context.
Definition at line 604 of file projectconfigpages.cpp.
References QETProject::conductorAutoNumRemoved(), SelectAutonumW::contextComboBox(), ProjectConfigPage::m_project, m_saw_conductor, ProjectConfigPage::project(), and QET::Icons::tr.
Referenced by buildConnections().
removeContextElement
void ProjectAutoNumConfigPage::removeContextElement () private slot
ProjectAutoNumConfigPage::removeContextElement Remove from project the current element numerotation context.
Definition at line 420 of file projectconfigpages.cpp.
References SelectAutonumW::contextComboBox(), ProjectConfigPage::m_project, m_saw_element, QETProject::removeElementAutoNum(), and QET::Icons::tr.
Referenced by buildConnections().
removeContextFolio
void ProjectAutoNumConfigPage::removeContextFolio () private slot
ProjectAutoNumConfigPage::removeContext_folio Remove from project the current folio numerotation context.
Definition at line 616 of file projectconfigpages.cpp.
References SelectAutonumW::contextComboBox(), QETProject::folioAutoNumRemoved(), ProjectConfigPage::m_project, m_saw_folio, ProjectConfigPage::project(), and QET::Icons::tr.
Referenced by buildConnections().
saveContextConductor
void ProjectAutoNumConfigPage::saveContextConductor () private slot
ProjectAutoNumConfigPage::saveContext_conductor Save the current displayed conductor context in project.
Definition at line 433 of file projectconfigpages.cpp.
References QETProject::addConductorAutoNum(), QETProject::conductorAutoNumAdded(), SelectAutonumW::contextComboBox(), ProjectConfigPage::m_project, m_saw_conductor, ProjectConfigPage::project(), QETProject::setCurrentConductorAutoNum(), SelectAutonumW::toNumContext(), and QET::Icons::tr.
Referenced by buildConnections().
saveContextElement
void ProjectAutoNumConfigPage::saveContextElement () private slot
ProjectAutoNumConfigPage::saveContextElement Save the current displayed Element formula in project.
Definition at line 389 of file projectconfigpages.cpp.
References QETProject::addElementAutoNum(), SelectAutonumW::contextComboBox(), ProjectConfigPage::m_project, m_saw_element, QETProject::setCurrrentElementAutonum(), title(), SelectAutonumW::toNumContext(), and QET::Icons::tr.
Referenced by buildConnections().
saveContextFolio
void ProjectAutoNumConfigPage::saveContextFolio () private slot
ProjectAutoNumConfigPage::saveContext_folio Save the current displayed folio context in project.
Definition at line 463 of file projectconfigpages.cpp.
References QETProject::addFolioAutoNum(), SelectAutonumW::contextComboBox(), QETProject::folioAutoNumAdded(), ProjectConfigPage::m_project, m_saw_folio, ProjectConfigPage::project(), SelectAutonumW::toNumContext(), and QET::Icons::tr.
Referenced by buildConnections().
saveCurrentTbp
void ProjectAutoNumConfigPage::saveCurrentTbp () signal
Referenced by applyAutoNum().
setAutoNum [1/2]
void ProjectAutoNumConfigPage::setAutoNum (int , int) signal
setAutoNum [2/2]
void ProjectAutoNumConfigPage::setAutoNum (QString) signal
Referenced by applyAutoNum().
title()
QString ProjectAutoNumConfigPage::title () const override virtual
ProjectAutoNumConfigPage::title Title of this config page.
Returns
Implements ConfigPage.
Definition at line 240 of file projectconfigpages.cpp.
References QET::Icons::tr.
Referenced by saveContextElement().
updateContextConductor
void ProjectAutoNumConfigPage::updateContextConductor (const QString & str) private slot
ProjectAutoNumConfigPage::updateContext_conductor Display the current selected context for conductor.
Parameters
str : key of context stored in project
Definition at line 353 of file projectconfigpages.cpp.
References QETProject::conductorAutoNum(), ProjectConfigPage::m_project, m_saw_conductor, SelectAutonumW::setContext(), and QET::Icons::tr.
Referenced by buildConnections().
updateContextElement
void ProjectAutoNumConfigPage::updateContextElement (const QString & str) private slot
ProjectAutoNumConfigPage::updateContextElement Display the current selected context for element.
Parameters
str : key of context stored in project
Definition at line 373 of file projectconfigpages.cpp.
References QETProject::elementAutoNum(), ProjectConfigPage::m_project, m_saw_element, SelectAutonumW::setContext(), and QET::Icons::tr.
Referenced by buildConnections().
updateContextFolio
void ProjectAutoNumConfigPage::updateContextFolio (const QString & str) private slot
ProjectAutoNumConfigPage::updateContext_folio Display the current selected context for folio.
Parameters
str : key of context stored in project
Definition at line 363 of file projectconfigpages.cpp.
References QETProject::folioAutoNum(), ProjectConfigPage::m_project, m_saw_folio, SelectAutonumW::setContext(), and QET::Icons::tr.
Referenced by buildConnections().
Member Data Documentation
m_amw
AutoNumberingManagementW* ProjectAutoNumConfigPage::m_amw private
Definition at line 166 of file projectconfigpages.h.
Referenced by applyManagement(), buildConnections(), and initWidgets().
m_faw
FolioAutonumberingW* ProjectAutoNumConfigPage::m_faw private
Definition at line 165 of file projectconfigpages.h.
Referenced by applyAutoNum(), buildConnections(), initWidgets(), and readValuesFromProject().
m_saw_conductor
SelectAutonumW* ProjectAutoNumConfigPage::m_saw_conductor private
Definition at line 162 of file projectconfigpages.h.
Referenced by buildConnections(), initWidgets(), readValuesFromProject(), removeContextConductor(), saveContextConductor(), and updateContextConductor().
m_saw_element
SelectAutonumW* ProjectAutoNumConfigPage::m_saw_element private
Definition at line 164 of file projectconfigpages.h.
Referenced by buildConnections(), initWidgets(), readValuesFromProject(), removeContextElement(), saveContextElement(), and updateContextElement().
m_saw_folio
SelectAutonumW* ProjectAutoNumConfigPage::m_saw_folio private
Definition at line 163 of file projectconfigpages.h.
Referenced by buildConnections(), initWidgets(), readValuesFromProject(), removeContextFolio(), saveContextFolio(), and updateContextFolio().
The documentation for this class was generated from the following files:
projectconfigpages.h
projectconfigpages.cpp