QElectroTech: FolioAutonumberingW Class Reference
FolioAutonumberingW Class Reference
#include <folioautonumbering.h>
Signals
void applyPressed ()
void m_autonumber_tabs_rb_clicked ()
Public Member Functions
FolioAutonumberingW (QETProject *project, QWidget *parent=nullptr)
~FolioAutonumberingW () override
void setContext (QList< QString > autonums)
FolioAutonumberingW::setContext construct autonums in the comboBox selected in the autonum_chooser QcomboBox.
NumerotationContext toNumContext () const
QString autoNumSelected ()
FolioAutonumberingW::autoNumSelected returns the current autonum selected.
int newFoliosNumber ()
FolioAutonumberingW::newFoliosNumber returns the number of folios to create.
int fromFolio ()
FolioAutonumberingW::fromFolio returns the current "From Folio" index.
int toFolio ()
FolioAutonumberingW::toFolio returns the current "To Folio" index.
Public Attributes
bool newFolios
Private Slots
void on_m_create_new_tabs_rb_clicked ()
FolioAutonumberingW::on_m_create_new_tabs_rb_clicked Enable New Tabs SpinBox.
void on_m_autonumber_tabs_rb_clicked ()
FolioAutonumberingW::on_m_autonumber_tabs_rb_clicked Enable From ComboBox, fill From ComboBox.
void on_m_new_tabs_sb_valueChanged (int)
FolioAutonumberingW::on_m_new_tabs_sb_valueChanged Enable Apply if any new folio is to be created.
void on_buttonBox_clicked (QAbstractButton *)
SelectAutonumW::on_buttonBox_clicked Action on buttonBox clicked.
void on_m_from_cb_currentIndexChanged (int)
FolioAutonumberingW::on_m_from_cb_currentIndexChanged Enable To ComboBox.
void applyEnable (bool=true)
SelectAutonumW::applyEnable enable/disable the apply button.
Private Member Functions
void updateFolioList ()
FolioAutonumberingW::updateFolioList update Folio List in From and To ComboBox.
Private Attributes
QETProject * project_
Ui::FolioAutonumberingW * ui
QList< NumPartEditorW * > num_part_list_
NumerotationContext m_context
Detailed Description
Definition at line 32 of file folioautonumbering.h.
Constructor & Destructor Documentation
FolioAutonumberingW()
FolioAutonumberingW::FolioAutonumberingW (QETProject * project, QWidget * parent = nullptr) explicit
Constructor
Definition at line 28 of file folioautonumbering.cpp.
References applyEnable(), and ui.
~FolioAutonumberingW()
FolioAutonumberingW::~FolioAutonumberingW () override
Destructor
Definition at line 44 of file folioautonumbering.cpp.
References ui.
Member Function Documentation
applyEnable
void FolioAutonumberingW::applyEnable (bool b = true) private slot
SelectAutonumW::applyEnable enable/disable the apply button.
Definition at line 203 of file folioautonumbering.cpp.
References ui.
Referenced by FolioAutonumberingW(), on_buttonBox_clicked(), on_m_autonumber_tabs_rb_clicked(), on_m_create_new_tabs_rb_clicked(), on_m_from_cb_currentIndexChanged(), and on_m_new_tabs_sb_valueChanged().
applyPressed
void FolioAutonumberingW::applyPressed () signal
Referenced by on_buttonBox_clicked().
autoNumSelected()
QString FolioAutonumberingW::autoNumSelected ()
FolioAutonumberingW::autoNumSelected returns the current autonum selected.
Definition at line 61 of file folioautonumbering.cpp.
References ui.
Referenced by ProjectAutoNumConfigPage::applyAutoNum().
fromFolio()
int FolioAutonumberingW::fromFolio ()
FolioAutonumberingW::fromFolio returns the current "From Folio" index.
Definition at line 69 of file folioautonumbering.cpp.
References ui.
Referenced by ProjectAutoNumConfigPage::applyAutoNum(), and toFolio().
m_autonumber_tabs_rb_clicked
void FolioAutonumberingW::m_autonumber_tabs_rb_clicked () signal
newFoliosNumber()
int FolioAutonumberingW::newFoliosNumber ()
FolioAutonumberingW::newFoliosNumber returns the number of folios to create.
Definition at line 85 of file folioautonumbering.cpp.
References ui.
Referenced by ProjectAutoNumConfigPage::applyAutoNum().
on_buttonBox_clicked
void FolioAutonumberingW::on_buttonBox_clicked (QAbstractButton * button) private slot
SelectAutonumW::on_buttonBox_clicked Action on buttonBox clicked.
Definition at line 165 of file folioautonumbering.cpp.
References applyEnable(), applyPressed(), QET::QetMessageBox::information(), QET::Icons::tr, ui, and updateFolioList().
on_m_autonumber_tabs_rb_clicked
void FolioAutonumberingW::on_m_autonumber_tabs_rb_clicked () private slot
FolioAutonumberingW::on_m_autonumber_tabs_rb_clicked Enable From ComboBox, fill From ComboBox.
Definition at line 118 of file folioautonumbering.cpp.
References applyEnable(), QETProject::diagrams(), newFolios, project_, Diagram::title(), and ui.
Referenced by updateFolioList().
on_m_create_new_tabs_rb_clicked
void FolioAutonumberingW::on_m_create_new_tabs_rb_clicked () private slot
FolioAutonumberingW::on_m_create_new_tabs_rb_clicked Enable New Tabs SpinBox.
Definition at line 106 of file folioautonumbering.cpp.
References applyEnable(), newFolios, and ui.
Referenced by updateFolioList().
on_m_from_cb_currentIndexChanged
void FolioAutonumberingW::on_m_from_cb_currentIndexChanged (int) private slot
FolioAutonumberingW::on_m_from_cb_currentIndexChanged Enable To ComboBox.
Definition at line 146 of file folioautonumbering.cpp.
References applyEnable(), QETProject::diagrams(), project_, and ui.
on_m_new_tabs_sb_valueChanged
void FolioAutonumberingW::on_m_new_tabs_sb_valueChanged (int) private slot
FolioAutonumberingW::on_m_new_tabs_sb_valueChanged Enable Apply if any new folio is to be created.
Definition at line 137 of file folioautonumbering.cpp.
References applyEnable(), and ui.
setContext()
void FolioAutonumberingW::setContext (QList< QString > autonums)
FolioAutonumberingW::setContext construct autonums in the comboBox selected in the autonum_chooser QcomboBox.
Definition at line 53 of file folioautonumbering.cpp.
References ui.
Referenced by ProjectAutoNumConfigPage::readValuesFromProject().
toFolio()
int FolioAutonumberingW::toFolio ()
FolioAutonumberingW::toFolio returns the current "To Folio" index.
Definition at line 77 of file folioautonumbering.cpp.
References fromFolio(), and ui.
Referenced by ProjectAutoNumConfigPage::applyAutoNum().
toNumContext()
NumerotationContext FolioAutonumberingW::toNumContext () const
updateFolioList()
void FolioAutonumberingW::updateFolioList () private
FolioAutonumberingW::updateFolioList update Folio List in From and To ComboBox.
Definition at line 92 of file folioautonumbering.cpp.
References newFolios, on_m_autonumber_tabs_rb_clicked(), on_m_create_new_tabs_rb_clicked(), and ui.
Referenced by on_buttonBox_clicked().
Member Data Documentation
m_context
NumerotationContext FolioAutonumberingW::m_context private
Definition at line 68 of file folioautonumbering.h.
newFolios
bool FolioAutonumberingW::newFolios
Definition at line 45 of file folioautonumbering.h.
Referenced by ProjectAutoNumConfigPage::applyAutoNum(), on_m_autonumber_tabs_rb_clicked(), on_m_create_new_tabs_rb_clicked(), and updateFolioList().
num_part_list_
QList<NumPartEditorW *> FolioAutonumberingW::num_part_list_ private
Definition at line 67 of file folioautonumbering.h.
project_
QETProject* FolioAutonumberingW::project_ private
Definition at line 65 of file folioautonumbering.h.
Referenced by on_m_autonumber_tabs_rb_clicked(), and on_m_from_cb_currentIndexChanged().
ui
Ui::FolioAutonumberingW* FolioAutonumberingW::ui private
Definition at line 66 of file folioautonumbering.h.
Referenced by applyEnable(), autoNumSelected(), FolioAutonumberingW(), fromFolio(), newFoliosNumber(), on_buttonBox_clicked(), on_m_autonumber_tabs_rb_clicked(), on_m_create_new_tabs_rb_clicked(), on_m_from_cb_currentIndexChanged(), on_m_new_tabs_sb_valueChanged(), setContext(), toFolio(), updateFolioList(), and ~FolioAutonumberingW().
The documentation for this class was generated from the following files:
folioautonumbering.h
folioautonumbering.cpp