QElectroTech: ExportConfigPage Class Reference
ExportConfigPage Class Reference
The ExportConfigPage class This configuration page enables users to set default export options.
#include <configpages.h>
Public Member Functions
ExportConfigPage (QWidget *=nullptr)
~ExportConfigPage () override
Destructeur.
void applyConf () override
QString title () const override
QIcon icon () const override
Public Member Functions inherited from ConfigPage
ConfigPage (QWidget *parent)
~ConfigPage () override
Destructor.
Public Attributes
ExportPropertiesWidget * epw
Private Member Functions
ExportConfigPage (const ExportConfigPage &)
Detailed Description
The ExportConfigPage class This configuration page enables users to set default export options.
Definition at line 79 of file configpages.h.
Constructor & Destructor Documentation
ExportConfigPage() [1/2]
ExportConfigPage::ExportConfigPage (QWidget * parent = nullptr)
Constructeur
Parameters
parent QWidget parent
Definition at line 242 of file configpages.cpp.
References ExportProperties::defaultExportProperties(), epw, and title().
~ExportConfigPage()
ExportConfigPage::~ExportConfigPage () override
Destructeur.
Definition at line 263 of file configpages.cpp.
ExportConfigPage() [2/2]
ExportConfigPage::ExportConfigPage (const ExportConfigPage &) private
Member Function Documentation
applyConf()
void ExportConfigPage::applyConf () override virtual
Applique la configuration de cette page
Implements ConfigPage.
Definition at line 269 of file configpages.cpp.
References epw.
icon()
QIcon ExportConfigPage::icon () const override virtual
Returns
l'icone de cette page
Implements ConfigPage.
Definition at line 276 of file configpages.cpp.
References QET::Icons::DocumentExport.
title()
QString ExportConfigPage::title () const override virtual
Returns
le titre de cette page
Implements ConfigPage.
Definition at line 281 of file configpages.cpp.
References QET::Icons::tr.
Referenced by ExportConfigPage().
Member Data Documentation
epw
ExportPropertiesWidget* ExportConfigPage::epw
Definition at line 96 of file configpages.h.
Referenced by applyConf(), and ExportConfigPage().
The documentation for this class was generated from the following files:
configpages.h
configpages.cpp