QElectroTech: ElementsTreeView Class Reference
ElementsTreeView Class Reference
The ElementsTreeView class This class just reimplement startDrag from QTreeView, for set a custom pixmap. This class must be used when the tree view have an ElementsCollectionModel as model. The pixmap used is the pixmap of the dragged element or a directory pixmap.
#include <elementstreeview.h>
Public Member Functions
ElementsTreeView (QWidget *parent=nullptr)
ElementsTreeView::ElementsTreeView.
Protected Member Functions
void startDrag (Qt::DropActions supportedActions) override
ElementsTreeView::startDrag Reimplemented from QTreeView.
virtual void startElementDrag (const ElementsLocation &location)
ElementsTreeView::startElementDrag Build a QDrag according to the content of location.
Detailed Description
The ElementsTreeView class This class just reimplement startDrag from QTreeView, for set a custom pixmap. This class must be used when the tree view have an ElementsCollectionModel as model. The pixmap used is the pixmap of the dragged element or a directory pixmap.
Definition at line 31 of file elementstreeview.h.
Constructor & Destructor Documentation
ElementsTreeView()
ElementsTreeView::ElementsTreeView (QWidget * parent = nullptr)
ElementsTreeView::ElementsTreeView.
Parameters
parent
Definition at line 35 of file elementstreeview.cpp.
Member Function Documentation
startDrag()
void ElementsTreeView::startDrag (Qt::DropActions supportedActions) override protected
ElementsTreeView::startDrag Reimplemented from QTreeView.
Parameters
supportedActions
Definition at line 44 of file elementstreeview.cpp.
References ElementsLocation::exist(), and startElementDrag().
startElementDrag()
void ElementsTreeView::startElementDrag (const ElementsLocation & location) protected virtual
ElementsTreeView::startElementDrag Build a QDrag according to the content of location.
Parameters
location : location to use for create the content of the QDrag
Definition at line 70 of file elementstreeview.cpp.
References ElementFactory::createElement(), ElementsLocation::exist(), QET::Icons::Folder, Element::hotspot(), ElementFactory::Instance(), ElementsLocation::isDirectory(), ElementsLocation::isElement(), MAX_DND_PIXMAP_HEIGHT, MAX_DND_PIXMAP_WIDTH, Element::pixmap(), and ElementsLocation::toString().
Referenced by startDrag().
The documentation for this class was generated from the following files:
elementstreeview.h
elementstreeview.cpp