QElectroTech: DiagramTextItem Class Reference
DiagramTextItem Class Reference abstract
#include <diagramtextitem.h>
Public Types
enum { Type = UserType + 1004 }
Signals
void colorChanged (QColor color)
void alignmentChanged (Qt::Alignment alignment)
void textEdited (const QString &old_str, const QString &new_str)
void fontChanged (QFont font)
Public Member Functions
DiagramTextItem (QGraphicsItem *=nullptr)
DiagramTextItem::DiagramTextItem.
DiagramTextItem (const QString &, QGraphicsItem *=nullptr)
DiagramTextItem::DiagramTextItem.
int type () const override
Diagram * diagram () const
DiagramTextItem::diagram.
virtual void fromXml (const QDomElement &)=0
virtual QDomElement toXml (QDomDocument &) const
DiagramTextItem::toXml This method do nothing and return an empty DomElement This is used to be inherited by child class.
void edit ()
Edit the text with HtmlEditor.
QPointF mapMovementToScene (const QPointF &) const
QPointF mapMovementFromScene (const QPointF &) const
QPointF mapMovementToParent (const QPointF &) const
QPointF mapMovementFromParent (const QPointF &) const
void setFont (const QFont &font)
void setColor (const QColor &color)
QColor color () const
void setNoEditable (bool e=true)
void setAlignment (const Qt::Alignment &alignment)
Qt::Alignment alignment () const
QRectF frameRect () const
DiagramTextItem::frameRect.
void setHtml (const QString &text)
void setPlainText (const QString &text)
bool isHtml () const
Public Attributes
bool m_block_alignment = false
Protected Member Functions
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *) override
DiagramTextItem::paint Draw this text field. This method draw the text by calling QGraphicsTextItem::paint. If text is hovered, this method draw the bounding rect in grey.
void focusInEvent (QFocusEvent *) override
DiagramTextItem::focusInEvent.
void focusOutEvent (QFocusEvent *) override
DiagramTextItem::focusOutEvent.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
DiagramTextItem::mousePressEvent.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
DiagramTextItem::mouseMoveEvent.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
DiagramTextItem::mouseReleaseEvent.
void hoverEnterEvent (QGraphicsSceneHoverEvent *) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *) override
void hoverMoveEvent (QGraphicsSceneHoverEvent *) override
virtual void applyRotation (const qreal &)
void prepareAlignment ()
DiagramTextItem::prepareAlignment Call this function before changing the bounding rect of this text.
void finishAlignment ()
DiagramTextItem::finishAlignment Call this function after changing the bouding rect of this text to set the position of this text according to the alignment property.
Protected Attributes
bool m_mouse_hover = false
bool m_first_move = true
bool m_no_editable
bool m_is_html = false
QString m_previous_html_text
QString m_previous_text
QPointF m_mouse_to_origin_movement
Properties
QColor color
Qt::Alignment alignment
QString plainText
QFont font
Private Member Functions
void build ()
DiagramTextItem::build Build this item with default value.
Private Attributes
QRectF m_alignment_rect
Qt::Alignment m_alignment = (Qt::AlignTop | Qt::AlignLeft)
Detailed Description
This class represents a selectable, movable and editable text field on a diagram.
See also
QGraphicsItem::GraphicsItemFlags
Definition at line 33 of file diagramtextitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 57 of file diagramtextitem.h.
Constructor & Destructor Documentation
DiagramTextItem() [1/2]
DiagramTextItem::DiagramTextItem (QGraphicsItem * parent = nullptr)
DiagramTextItem::DiagramTextItem.
Parameters
parent : parent item
Definition at line 28 of file diagramtextitem.cpp.
References build().
DiagramTextItem() [2/2]
DiagramTextItem::DiagramTextItem (const QString & text, QGraphicsItem * parent = nullptr)
DiagramTextItem::DiagramTextItem.
Parameters
text : text to display
parent : parent item
Definition at line 37 of file diagramtextitem.cpp.
References build().
Member Function Documentation
alignment()
Qt::Alignment DiagramTextItem::alignment () const
Definition at line 183 of file diagramtextitem.cpp.
References m_alignment.
alignmentChanged
void DiagramTextItem::alignmentChanged (Qt::Alignment alignment) signal
Referenced by setAlignment().
applyRotation()
void DiagramTextItem::applyRotation (const qreal & angle) protected virtual
Effectue la rotation du texte en elle-meme Pour les DiagramTextItem, la rotation s'effectue autour du point (0, 0). Cette methode peut toutefois etre redefinie dans des classes filles
Parameters
angle Angle de la rotation a effectuer
Definition at line 392 of file diagramtextitem.cpp.
References QET::correctAngle().
build()
void DiagramTextItem::build () private
DiagramTextItem::build Build this item with default value.
Definition at line 47 of file diagramtextitem.cpp.
References QETApp::diagramTextsItemFont(), setFont(), setNoEditable(), and QET::Icons::tr.
Referenced by DiagramTextItem().
color()
QColor DiagramTextItem::color () const
Definition at line 173 of file diagramtextitem.cpp.
colorChanged
void DiagramTextItem::colorChanged (QColor color) signal
Referenced by setColor(), and DynamicElementTextModel::setConnection().
diagram()
Diagram * DiagramTextItem::diagram () const
DiagramTextItem::diagram.
Returns
The diagram of this item or 0 if this text isn't in a diagram
Definition at line 63 of file diagramtextitem.cpp.
Referenced by IndependentTextItem::focusOutEvent(), mouseMoveEvent(), DynamicElementTextItem::mouseMoveEvent(), ConductorTextItem::mouseReleaseEvent(), mouseReleaseEvent(), DynamicElementTextItem::reportChanged(), DynamicElementTextItem::setPlainText(), DynamicElementTextItem::setupFormulaConnection(), and DynamicElementTextItem::updateXref().
edit()
void DiagramTextItem::edit ()
Edit the text with HtmlEditor.
Definition at line 453 of file diagramtextitem.cpp.
References qdesigner_internal::RichTextEditorDialog::applyEditText(), setHtml(), and qdesigner_internal::RichTextEditorDialog::setText().
finishAlignment()
void DiagramTextItem::finishAlignment () protected
DiagramTextItem::finishAlignment Call this function after changing the bouding rect of this text to set the position of this text according to the alignment property.
Definition at line 410 of file diagramtextitem.cpp.
References m_alignment, m_alignment_rect, and m_block_alignment.
Referenced by setFont(), and DynamicElementTextItem::setPlainText().
focusInEvent()
void DiagramTextItem::focusInEvent (QFocusEvent * event) override protected
DiagramTextItem::focusInEvent.
Parameters
event
Definition at line 267 of file diagramtextitem.cpp.
References m_previous_html_text, and m_previous_text.
focusOutEvent()
void DiagramTextItem::focusOutEvent (QFocusEvent * event) override protected
DiagramTextItem::focusOutEvent.
Parameters
event
Definition at line 281 of file diagramtextitem.cpp.
References m_previous_text, and textEdited().
Referenced by IndependentTextItem::focusOutEvent().
fontChanged
void DiagramTextItem::fontChanged (QFont font) signal
Referenced by ElementTextItemGroup::addToGroup(), ElementTextItemGroup::removeFromGroup(), DynamicElementTextModel::setConnection(), setFont(), and IndiTextPropertiesWidget::setText().
frameRect()
QRectF DiagramTextItem::frameRect () const
DiagramTextItem::frameRect.
Returns
the rect used to draw a frame around this text
Definition at line 192 of file diagramtextitem.cpp.
Referenced by DynamicElementTextItem::paint().
fromXml()
virtual void DiagramTextItem::fromXml (const QDomElement &) pure virtual
Implemented in DynamicElementTextItem, ConductorTextItem, and IndependentTextItem.
hoverEnterEvent()
void DiagramTextItem::hoverEnterEvent (QGraphicsSceneHoverEvent * e) override protected
When mouse over element change m_mouse_hover to true (used in paint() function)
Parameters
e QGraphicsSceneHoverEvent
Definition at line 472 of file diagramtextitem.cpp.
References m_mouse_hover.
Referenced by DynamicElementTextItem::hoverEnterEvent().
hoverLeaveEvent()
void DiagramTextItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * e) override protected
When mouse over element leave the position change m_mouse_hover to false (used in paint() function)
Parameters
e QGraphicsSceneHoverEvent
Definition at line 486 of file diagramtextitem.cpp.
References m_mouse_hover.
Referenced by DynamicElementTextItem::hoverLeaveEvent().
hoverMoveEvent()
void DiagramTextItem::hoverMoveEvent (QGraphicsSceneHoverEvent * e) override protected
Do nothing default function .
Parameters
e QGraphicsSceneHoverEvent
Definition at line 496 of file diagramtextitem.cpp.
isHtml()
bool DiagramTextItem::isHtml () const
Definition at line 224 of file diagramtextitem.cpp.
References m_is_html.
mapMovementFromParent()
QPointF DiagramTextItem::mapMovementFromParent (const QPointF & movement) const
Traduit en coordonnees locales un mouvement / vecteur initialement exprime en coordonnees du parent.
Parameters
movement Vecteur exprime en coordonnees du parent
Returns
le meme vecteur, exprime en coordonnees locales
Definition at line 140 of file diagramtextitem.cpp.
mapMovementFromScene()
QPointF DiagramTextItem::mapMovementFromScene (const QPointF & movement) const
Traduit en coordonnees locales un mouvement / vecteur initialement exprime en coordonnees de la scene.
Parameters
movement Vecteur exprime en coordonnees de la scene
Returns
le meme vecteur, exprime en coordonnees locales
Definition at line 102 of file diagramtextitem.cpp.
mapMovementToParent()
QPointF DiagramTextItem::mapMovementToParent (const QPointF & movement) const
Traduit en coordonnees de l'item parent un mouvement / vecteur initialement exprime en coordonnees locales.
Parameters
movement Vecteur exprime en coordonnees locales
Returns
le meme vecteur, exprime en coordonnees du parent
Definition at line 121 of file diagramtextitem.cpp.
mapMovementToScene()
QPointF DiagramTextItem::mapMovementToScene (const QPointF & movement) const
Traduit en coordonnees de la scene un mouvement / vecteur initialement exprime en coordonnees locales.
Parameters
movement Vecteur exprime en coordonnees locales
Returns
le meme vecteur, exprime en coordonnees de la scene
Definition at line 83 of file diagramtextitem.cpp.
mouseDoubleClickEvent()
void DiagramTextItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Gere les double-clics sur ce champ de texte.
Parameters
event un QGraphicsSceneMouseEvent decrivant le double-clic
Definition at line 303 of file diagramtextitem.cpp.
References m_no_editable.
Referenced by DynamicElementTextItem::mouseDoubleClickEvent().
mouseMoveEvent()
void DiagramTextItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
DiagramTextItem::mouseMoveEvent.
Parameters
event
Definition at line 334 of file diagramtextitem.cpp.
References ElementsMover::beginMovement(), ElementsMover::continueMovement(), diagram(), Diagram::elementsMover(), m_first_move, m_mouse_to_origin_movement, and Diagram::snapToGrid().
mousePressEvent()
void DiagramTextItem::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
DiagramTextItem::mousePressEvent.
Parameters
event
Definition at line 319 of file diagramtextitem.cpp.
References m_first_move, and m_mouse_to_origin_movement.
Referenced by ConductorTextItem::mousePressEvent(), and DynamicElementTextItem::mousePressEvent().
mouseReleaseEvent()
void DiagramTextItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
DiagramTextItem::mouseReleaseEvent.
Parameters
event
Definition at line 365 of file diagramtextitem.cpp.
References diagram(), Diagram::elementsMover(), and ElementsMover::endMovement().
paint()
void DiagramTextItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override protected
DiagramTextItem::paint Draw this text field. This method draw the text by calling QGraphicsTextItem::paint. If text is hovered, this method draw the bounding rect in grey.
Parameters
painter : painter to use
option : style option
widget : widget where must to draw
Definition at line 236 of file diagramtextitem.cpp.
References m_mouse_hover.
Referenced by DynamicElementTextItem::paint().
prepareAlignment()
void DiagramTextItem::prepareAlignment () protected
DiagramTextItem::prepareAlignment Call this function before changing the bounding rect of this text.
Definition at line 400 of file diagramtextitem.cpp.
References m_alignment_rect.
Referenced by setFont(), and DynamicElementTextItem::setPlainText().
setAlignment()
void DiagramTextItem::setAlignment (const Qt::Alignment & alignment)
Definition at line 177 of file diagramtextitem.cpp.
References alignment, alignmentChanged(), and m_alignment.
Referenced by DynamicElementTextItem::fromXml().
setColor()
void DiagramTextItem::setColor (const QColor & color)
Definition at line 167 of file diagramtextitem.cpp.
References color, and colorChanged().
Referenced by DynamicElementTextItem::fromXml(), and Conductor::setProperties().
setFont()
void DiagramTextItem::setFont (const QFont & font)
Definition at line 153 of file diagramtextitem.cpp.
References finishAlignment(), font, fontChanged(), and prepareAlignment().
Referenced by build(), DynamicElementTextItem::DynamicElementTextItem(), IndependentTextItem::fromXml(), DynamicElementTextItem::fromXml(), Element::fromXml(), IndependentTextItem::IndependentTextItem(), Element::parseInput(), and Conductor::setProperties().
setHtml()
void DiagramTextItem::setHtml (const QString & text)
Definition at line 212 of file diagramtextitem.cpp.
References m_is_html.
Referenced by edit(), IndependentTextItem::fromXml(), and ChangeDiagramTextCommand::redo().
setNoEditable()
void DiagramTextItem::setNoEditable (bool e = true) inline
Definition at line 75 of file diagramtextitem.h.
References m_no_editable.
Referenced by build(), and DynamicElementTextItem::setTextFrom().
setPlainText()
void DiagramTextItem::setPlainText (const QString & text)
Definition at line 218 of file diagramtextitem.cpp.
References m_is_html.
Referenced by Conductor::refreshText(), DynamicElementTextItem::setPlainText(), and Conductor::setProperties().
textEdited
void DiagramTextItem::textEdited (const QString & old_str, const QString & new_str) signal
Referenced by Conductor::Conductor(), DynamicElementTextItem::DynamicElementTextItem(), focusOutEvent(), and IndiTextPropertiesWidget::setText().
toXml()
QDomElement DiagramTextItem::toXml (QDomDocument &) const virtual
DiagramTextItem::toXml This method do nothing and return an empty DomElement This is used to be inherited by child class.
Returns
Reimplemented in DynamicElementTextItem, and IndependentTextItem.
Definition at line 73 of file diagramtextitem.cpp.
type()
int DiagramTextItem::type () const inline override
Definition at line 58 of file diagramtextitem.h.
References Type.
Member Data Documentation
m_alignment
Qt::Alignment DiagramTextItem::m_alignment = (Qt::AlignTop | Qt::AlignLeft) private
Definition at line 123 of file diagramtextitem.h.
Referenced by alignment(), finishAlignment(), and setAlignment().
m_alignment_rect
QRectF DiagramTextItem::m_alignment_rect private
Definition at line 122 of file diagramtextitem.h.
Referenced by finishAlignment(), and prepareAlignment().
m_block_alignment
bool DiagramTextItem::m_block_alignment = false
Definition at line 79 of file diagramtextitem.h.
Referenced by finishAlignment().
m_first_move
bool DiagramTextItem::m_first_move = true protected
Definition at line 111 of file diagramtextitem.h.
Referenced by mouseMoveEvent(), DynamicElementTextItem::mouseMoveEvent(), and mousePressEvent().
m_is_html
bool DiagramTextItem::m_is_html = false protected
Definition at line 113 of file diagramtextitem.h.
Referenced by isHtml(), setHtml(), and setPlainText().
m_mouse_hover
bool DiagramTextItem::m_mouse_hover = false protected
Definition at line 110 of file diagramtextitem.h.
Referenced by ConductorTextItem::hoverEnterEvent(), hoverEnterEvent(), ConductorTextItem::hoverLeaveEvent(), hoverLeaveEvent(), and paint().
m_mouse_to_origin_movement
QPointF DiagramTextItem::m_mouse_to_origin_movement protected
Definition at line 119 of file diagramtextitem.h.
Referenced by ConductorTextItem::mouseMoveEvent(), mouseMoveEvent(), and mousePressEvent().
m_no_editable
bool DiagramTextItem::m_no_editable protected
Definition at line 112 of file diagramtextitem.h.
Referenced by mouseDoubleClickEvent(), and setNoEditable().
m_previous_html_text
QString DiagramTextItem::m_previous_html_text protected
Definition at line 116 of file diagramtextitem.h.
Referenced by focusInEvent(), and IndependentTextItem::focusOutEvent().
m_previous_text
QString DiagramTextItem::m_previous_text protected
Definition at line 117 of file diagramtextitem.h.
Referenced by focusInEvent(), and focusOutEvent().
Property Documentation
alignment
Qt::Alignment DiagramTextItem::alignment read write
Definition at line 1 of file diagramtextitem.h.
Referenced by DynamicTextItemDelegate::createEditor(), DynamicElementTextModel::itemsForText(), setAlignment(), DynamicElementTextItem::setXref_item(), DynamicElementTextItem::toXml(), and DynamicElementTextModel::undoForEditedText().
color
QColor DiagramTextItem::color read write
Definition at line 1 of file diagramtextitem.h.
Referenced by DynamicElementTextItem::hoverEnterEvent(), DynamicElementTextModel::itemsForText(), DynamicElementTextItem::paint(), setColor(), DynamicElementTextItem::toXml(), DynamicElementTextModel::undoForEditedText(), and DynamicElementTextModel::updateDataFromText().
font
QFont DiagramTextItem::font read write
Definition at line 1 of file diagramtextitem.h.
Referenced by IndependentTextItem::fromXml(), DynamicElementTextItem::fromXml(), Element::fromXml(), DynamicElementTextModel::itemsForText(), DynamicElementTextItem::paint(), Element::parseInput(), setFont(), Conductor::setProperties(), IndependentTextItem::toXml(), DynamicElementTextItem::toXml(), DynamicElementTextModel::undoForEditedText(), and DynamicElementTextModel::updateDataFromText().
plainText
QString DiagramTextItem::plainText read write
Definition at line 1 of file diagramtextitem.h.
The documentation for this class was generated from the following files:
diagramtextitem.h
diagramtextitem.cpp