QElectroTech: RectangleEditor Class Reference
RectangleEditor Class Reference
The RectangleEditor class This class provides a widget to edit rectangles within the element editor.
#include <rectangleeditor.h>
Public Slots
void updateForm () override
RectangleEditor::updateForm.
Public Member Functions
RectangleEditor (QETElementEditor *editor, PartRectangle *rect=nullptr, QWidget *parent=nullptr)
RectangleEditor::RectangleEditor.
~RectangleEditor () override
RectangleEditor::~RectangleEditor.
bool setPart (CustomElementPart *part) override
RectangleEditor::setPart.
bool setParts (QList< CustomElementPart * > parts) override
CustomElementPart * currentPart () const override
RectangleEditor::currentPart.
QList< CustomElementPart * > currentParts () const override
QPointF editedTopLeft () const
RectangleEditor::topLeft.
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
virtual void updateForm ()=0
Private Member Functions
void editingFinished ()
RectangleEditor::editingFinished Slot called when a editor widget is finish to be edited Update the geometry of the rectangle according to value of editing widget.
void activeConnections (bool active)
RectangleEditor::activeConnections Enable/disable connection between editor widget and slot editingFinished True == enable | false == disable.
void xPosChanged ()
void yPosChanged ()
void widthChanged ()
void heightChanged ()
void xRadiusChanged ()
void yRadiusChanged ()
void setUpChangeConnections ()
setUpChangeConnections Setup the connection from the rectangles(s) to the widget, to update it when the rectangles(s) are changed (moved ...)
void disconnectChangeConnections ()
Private Attributes
bool m_locked = false
StyleEditor * m_style
PartRectangle * m_part
Ui::RectangleEditor * ui
QList< QMetaObject::Connection > m_change_connections
Detailed Description
The RectangleEditor class This class provides a widget to edit rectangles within the element editor.
Definition at line 35 of file rectangleeditor.h.
Constructor & Destructor Documentation
RectangleEditor()
RectangleEditor::RectangleEditor (QETElementEditor * editor, PartRectangle * rect = nullptr, QWidget * parent = nullptr) explicit
RectangleEditor::RectangleEditor.
Parameters
editor
rect
parent
Definition at line 32 of file rectangleeditor.cpp.
References m_style, and ui.
~RectangleEditor()
RectangleEditor::~RectangleEditor () override
RectangleEditor::~RectangleEditor.
Definition at line 45 of file rectangleeditor.cpp.
References ui.
Member Function Documentation
activeConnections()
void RectangleEditor::activeConnections (bool active) private
RectangleEditor::activeConnections Enable/disable connection between editor widget and slot editingFinished True == enable | false == disable.
Parameters
active
Definition at line 348 of file rectangleeditor.cpp.
References heightChanged(), ui, widthChanged(), xPosChanged(), xRadiusChanged(), yPosChanged(), and yRadiusChanged().
Referenced by updateForm().
currentPart()
CustomElementPart * RectangleEditor::currentPart () const override virtual
RectangleEditor::currentPart.
Returns
Implements ElementItemEditor.
Definition at line 115 of file rectangleeditor.cpp.
References m_part.
currentParts()
QList< CustomElementPart * > RectangleEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 119 of file rectangleeditor.cpp.
References StyleEditor::currentParts(), and m_style.
disconnectChangeConnections()
void RectangleEditor::disconnectChangeConnections () private
Definition at line 58 of file rectangleeditor.cpp.
References m_change_connections.
Referenced by setPart().
editedTopLeft()
QPointF RectangleEditor::editedTopLeft () const
RectangleEditor::topLeft.
Returns
The edited topLeft already mapped to part coordinate
Definition at line 127 of file rectangleeditor.cpp.
References m_part, and ui.
Referenced by editingFinished().
editingFinished()
void RectangleEditor::editingFinished () private
RectangleEditor::editingFinished Slot called when a editor widget is finish to be edited Update the geometry of the rectangle according to value of editing widget.
Definition at line 160 of file rectangleeditor.cpp.
References editedTopLeft(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, m_part, PartRectangle::rect, QPropertyUndoCommand::setAnimated(), QET::Icons::tr, ui, ElementScene::undoStack(), PartRectangle::XRadius(), and PartRectangle::YRadius().
heightChanged()
void RectangleEditor::heightChanged () private
Definition at line 269 of file rectangleeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, m_style, PartRectangle::rect, ui, and ElementScene::undoStack().
Referenced by activeConnections().
setPart()
bool RectangleEditor::setPart (CustomElementPart * part) override virtual
RectangleEditor::setPart.
Parameters
part
Returns
Implements ElementItemEditor.
Definition at line 71 of file rectangleeditor.cpp.
References disconnectChangeConnections(), m_part, setUpChangeConnections(), and updateForm().
Referenced by setParts().
setParts()
bool RectangleEditor::setParts (QList< CustomElementPart * > parts) override virtual
Reimplemented from ElementItemEditor.
Definition at line 101 of file rectangleeditor.cpp.
References m_style, setPart(), and StyleEditor::setParts().
setUpChangeConnections()
void RectangleEditor::setUpChangeConnections () private
setUpChangeConnections Setup the connection from the rectangles(s) to the widget, to update it when the rectangles(s) are changed (moved ...)
Definition at line 49 of file rectangleeditor.cpp.
References m_change_connections, m_part, PartRectangle::rectChanged(), updateForm(), PartRectangle::XRadiusChanged(), and PartRectangle::YRadiusChanged().
Referenced by setPart().
updateForm
void RectangleEditor::updateForm () override slot
RectangleEditor::updateForm.
Definition at line 134 of file rectangleeditor.cpp.
References activeConnections(), m_part, CustomElementGraphicPart::property(), ui, PartRectangle::XRadius(), and PartRectangle::YRadius().
Referenced by setPart(), and setUpChangeConnections().
widthChanged()
void RectangleEditor::widthChanged () private
Definition at line 243 of file rectangleeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, m_style, PartRectangle::rect, ui, and ElementScene::undoStack().
Referenced by activeConnections().
xPosChanged()
void RectangleEditor::xPosChanged () private
Definition at line 191 of file rectangleeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, m_style, PartRectangle::rect, ui, and ElementScene::undoStack().
Referenced by activeConnections().
xRadiusChanged()
void RectangleEditor::xRadiusChanged () private
Definition at line 295 of file rectangleeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), m_locked, m_style, QPropertyUndoCommand::setAnimated(), ui, ElementScene::undoStack(), and PartRectangle::XRadius().
Referenced by activeConnections().
yPosChanged()
void RectangleEditor::yPosChanged () private
Definition at line 217 of file rectangleeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, m_style, PartRectangle::rect, ui, and ElementScene::undoStack().
Referenced by activeConnections().
yRadiusChanged()
void RectangleEditor::yRadiusChanged () private
Definition at line 318 of file rectangleeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), m_locked, m_style, QPropertyUndoCommand::setAnimated(), ui, ElementScene::undoStack(), and PartRectangle::YRadius().
Referenced by activeConnections().
Member Data Documentation
m_change_connections
QList<QMetaObject::Connection> RectangleEditor::m_change_connections private
Definition at line 72 of file rectangleeditor.h.
Referenced by disconnectChangeConnections(), and setUpChangeConnections().
m_locked
bool RectangleEditor::m_locked = false private
Definition at line 68 of file rectangleeditor.h.
Referenced by editingFinished(), heightChanged(), widthChanged(), xPosChanged(), xRadiusChanged(), yPosChanged(), and yRadiusChanged().
m_part
PartRectangle* RectangleEditor::m_part private
Definition at line 70 of file rectangleeditor.h.
Referenced by currentPart(), editedTopLeft(), editingFinished(), setPart(), setUpChangeConnections(), and updateForm().
m_style
StyleEditor* RectangleEditor::m_style private
Definition at line 69 of file rectangleeditor.h.
Referenced by currentParts(), heightChanged(), RectangleEditor(), setParts(), widthChanged(), xPosChanged(), xRadiusChanged(), yPosChanged(), and yRadiusChanged().
ui
Ui::RectangleEditor* RectangleEditor::ui private
Definition at line 71 of file rectangleeditor.h.
Referenced by activeConnections(), editedTopLeft(), editingFinished(), heightChanged(), RectangleEditor(), updateForm(), widthChanged(), xPosChanged(), xRadiusChanged(), yPosChanged(), yRadiusChanged(), and ~RectangleEditor().
The documentation for this class was generated from the following files:
rectangleeditor.h
rectangleeditor.cpp