QElectroTech: LinkSingleElementWidget Class Reference
LinkSingleElementWidget Class Reference
The LinkSingleElementWidget class this class provide a widget to select an element to be linked to the element given in the constructor. The element given in constructor must be linked with only one other element (like report or slave element). This widget detect automaticaly the kind of element given in the constructor and search all element that can be linked with it. If the element is already linked, the widget ask user to unlink. This widget embedded the diagram command for undo/redo the action.
#include <linksingleelementwidget.h>
Public Slots
void updateUi () override
LinkSingleElementWidget::updateUi Update the content of this widget.
void buildTree ()
LinkSingleElementWidget::buildTree Build the content of the QTreeWidget.
Public Member Functions
LinkSingleElementWidget (Element *elmt, QWidget *parent=nullptr)
Methods.
~LinkSingleElementWidget () override
LinkSingleElementWidget::~LinkSingleElementWidget Default destructor.
void setElement (Element *element) override
LinkSingleElementWidget::setElement Set element to be the edited element.
void apply () override
LinkSingleElementWidget::apply Apply the new property of the edited element by pushing the associated undo command to parent project undo stack.
QUndoCommand * associatedUndo () const override
LinkSingleElementWidget::associatedUndo.
QString title () const override
LinkSingleElementWidget::title.
bool setLiveEdit (bool live_edit) override
LinkSingleElementWidget::setLiveEdit.
Public Member Functions inherited from AbstractElementPropertiesEditorWidget
AbstractElementPropertiesEditorWidget (QWidget *parent=nullptr)
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual void reset ()
virtual void updateUi ()
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Private Slots
void diagramWasRemovedFromProject ()
LinkSingleElementWidget::diagramWasRemovedFromProject This slot is called when a diagram is removed from the parent project of edited element to update the content of this widget.
void showedElementWasDeleted ()
void linkTriggered ()
LinkSingleElementWidget::linkTriggered Action linkis triggered.
void hideButtons ()
LinkSingleElementWidget::hideButtons Hide the button displayed when element is already linked.
void showButtons ()
LinkSingleElementWidget::showButtons Show the button displayed when element is already linked.
void headerCustomContextMenuRequested (const QPoint &pos)
void on_m_unlink_pb_clicked ()
void on_m_tree_widget_itemDoubleClicked (QTreeWidgetItem *item, int column)
LinkSingleElementWidget::on_m_tree_widget_itemDoubleClicked Highlight the element represented by item.
void on_m_tree_widget_customContextMenuRequested (const QPoint &pos)
void on_m_show_linked_pb_clicked ()
void on_m_show_this_pb_clicked ()
void on_m_search_field_textEdited (const QString &arg1)
LinkSingleElementWidget::on_m_search_field_textEdited Search all items which match with arg1 and shows it, other items is hidden. If arg1 is empty, show all items.
Private Member Functions
QList< Element * > availableElements ()
LinkSingleElementWidget::availableElements.
void setUpCompleter ()
LinkSingleElementWidget::setUpCompleter Setup the completer of search_field.
void clearTreeWidget ()
LinkSingleElementWidget::clearTreeWidget Clear the tree widget. Delete all QTreeWidget (in the tree widget and in the hash). Clear the hash.
void setUpHeaderLabels ()
Private Attributes
Ui::LinkSingleElementWidget * ui
bool m_unlink = false
Element::kind m_filter
QHash< QTreeWidgetItem *, Element * > m_qtwi_elmt_hash
QHash< QTreeWidgetItem *, QStringList > m_qtwi_strl_hash
QTreeWidgetItem * m_qtwi_at_context_menu = nullptr
QTreeWidgetItem * m_pending_qtwi = nullptr
Element * m_showed_element = nullptr
Element * m_element_to_link = nullptr
QMenu * m_context_menu
QAction * m_link_action
QAction * m_show_qtwi
QAction * m_show_element
QAction * m_save_header_state
Additional Inherited Members
Protected Member Functions inherited from PropertiesEditorWidget
virtual void enableLiveEdit ()
virtual void disableLiveEdit ()
Protected Attributes inherited from AbstractElementPropertiesEditorWidget
QPointer< Element > m_element
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
The LinkSingleElementWidget class this class provide a widget to select an element to be linked to the element given in the constructor. The element given in constructor must be linked with only one other element (like report or slave element). This widget detect automaticaly the kind of element given in the constructor and search all element that can be linked with it. If the element is already linked, the widget ask user to unlink. This widget embedded the diagram command for undo/redo the action.
Definition at line 41 of file linksingleelementwidget.h.
Constructor & Destructor Documentation
LinkSingleElementWidget()
LinkSingleElementWidget::LinkSingleElementWidget (Element * elmt, QWidget * parent = nullptr) explicit
Methods.
LinkSingleElementWidget::LinkSingleElementWidget Default constructor.
Parameters
elmt the edited element
parent the parent widget
Definition at line 36 of file linksingleelementwidget.cpp.
References Element::AllReport, headerCustomContextMenuRequested(), linkTriggered(), m_context_menu, AbstractElementPropertiesEditorWidget::m_element, m_link_action, m_qtwi_at_context_menu, m_save_header_state, m_show_element, m_show_qtwi, m_showed_element, on_m_tree_widget_itemDoubleClicked(), setElement(), Element::setHighlighted(), Element::Slave, QET::Icons::tr, and ui.
~LinkSingleElementWidget()
LinkSingleElementWidget::~LinkSingleElementWidget () override
LinkSingleElementWidget::~LinkSingleElementWidget Default destructor.
Definition at line 91 of file linksingleelementwidget.cpp.
References AbstractElementPropertiesEditorWidget::m_element, m_showed_element, Element::setHighlighted(), and ui.
Member Function Documentation
apply()
void LinkSingleElementWidget::apply () override virtual
LinkSingleElementWidget::apply Apply the new property of the edited element by pushing the associated undo command to parent project undo stack.
Reimplemented from PropertiesEditorWidget.
Definition at line 162 of file linksingleelementwidget.cpp.
References associatedUndo(), AbstractElementPropertiesEditorWidget::m_element, m_element_to_link, m_pending_qtwi, and m_unlink.
Referenced by linkTriggered(), and on_m_unlink_pb_clicked().
associatedUndo()
QUndoCommand * LinkSingleElementWidget::associatedUndo () const override virtual
LinkSingleElementWidget::associatedUndo.
Returns
the undo command associated to the current edition if there isn't change, return nulptr
Reimplemented from PropertiesEditorWidget.
Definition at line 178 of file linksingleelementwidget.cpp.
References AbstractElementPropertiesEditorWidget::m_element, m_element_to_link, m_unlink, LinkElementCommand::setLink(), and LinkElementCommand::unlinkAll().
Referenced by apply().
availableElements()
QList< Element * > LinkSingleElementWidget::availableElements () private
LinkSingleElementWidget::availableElements.
Returns
A QList with all available element to be linked with the edited element. This methode take care of the combo box "find in diagram"
Definition at line 368 of file linksingleelementwidget.cpp.
References Element::AllReport, ElementProvider::find(), ElementProvider::freeElement(), AbstractElementPropertiesEditorWidget::m_element, m_filter, and m_unlink.
Referenced by buildTree().
buildTree
void LinkSingleElementWidget::buildTree () slot
LinkSingleElementWidget::buildTree Build the content of the QTreeWidget.
Definition at line 228 of file linksingleelementwidget.cpp.
References Element::AllReport, availableElements(), clearTreeWidget(), autonum::AssignVariables::formulaToLabel(), AbstractElementPropertiesEditorWidget::m_element, ConductorProperties::m_function, m_qtwi_elmt_hash, m_qtwi_strl_hash, ConductorProperties::m_tension_protocol, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, setUpCompleter(), setUpHeaderLabels(), Element::Slave, ConductorProperties::text, and ui.
Referenced by on_m_unlink_pb_clicked(), and updateUi().
clearTreeWidget()
void LinkSingleElementWidget::clearTreeWidget () private
LinkSingleElementWidget::clearTreeWidget Clear the tree widget. Delete all QTreeWidget (in the tree widget and in the hash). Clear the hash.
Definition at line 414 of file linksingleelementwidget.cpp.
References m_qtwi_elmt_hash, m_qtwi_strl_hash, and ui.
Referenced by buildTree().
diagramWasRemovedFromProject
void LinkSingleElementWidget::diagramWasRemovedFromProject () private slot
LinkSingleElementWidget::diagramWasRemovedFromProject This slot is called when a diagram is removed from the parent project of edited element to update the content of this widget.
Definition at line 490 of file linksingleelementwidget.cpp.
References updateUi().
Referenced by setElement().
headerCustomContextMenuRequested
void LinkSingleElementWidget::headerCustomContextMenuRequested (const QPoint & pos) private slot
Definition at line 573 of file linksingleelementwidget.cpp.
References m_context_menu, m_save_header_state, and ui.
Referenced by LinkSingleElementWidget().
hideButtons
void LinkSingleElementWidget::hideButtons () private slot
LinkSingleElementWidget::hideButtons Hide the button displayed when element is already linked.
Definition at line 551 of file linksingleelementwidget.cpp.
References ui.
Referenced by updateUi().
linkTriggered
void LinkSingleElementWidget::linkTriggered () private slot
LinkSingleElementWidget::linkTriggered Action linkis triggered.
Definition at line 508 of file linksingleelementwidget.cpp.
References apply(), m_element_to_link, PropertiesEditorWidget::m_live_edit, m_pending_qtwi, m_qtwi_at_context_menu, m_qtwi_elmt_hash, and updateUi().
Referenced by LinkSingleElementWidget().
on_m_search_field_textEdited
void LinkSingleElementWidget::on_m_search_field_textEdited (const QString & arg1) private slot
LinkSingleElementWidget::on_m_search_field_textEdited Search all items which match with arg1 and shows it, other items is hidden. If arg1 is empty, show all items.
Parameters
arg1
Definition at line 668 of file linksingleelementwidget.cpp.
References m_qtwi_elmt_hash, and m_qtwi_strl_hash.
on_m_show_linked_pb_clicked
void LinkSingleElementWidget::on_m_show_linked_pb_clicked () private slot
Definition at line 646 of file linksingleelementwidget.cpp.
References QetGraphicsItem::diagram(), AbstractElementPropertiesEditorWidget::m_element, Element::setHighlighted(), and Diagram::showMe().
on_m_show_this_pb_clicked
void LinkSingleElementWidget::on_m_show_this_pb_clicked () private slot
Definition at line 656 of file linksingleelementwidget.cpp.
References m_show_element.
on_m_tree_widget_customContextMenuRequested
void LinkSingleElementWidget::on_m_tree_widget_customContextMenuRequested (const QPoint & pos) private slot
Definition at line 622 of file linksingleelementwidget.cpp.
References m_context_menu, m_link_action, m_qtwi_at_context_menu, m_show_element, m_show_qtwi, and ui.
on_m_tree_widget_itemDoubleClicked
void LinkSingleElementWidget::on_m_tree_widget_itemDoubleClicked (QTreeWidgetItem * item, int column) private slot
LinkSingleElementWidget::on_m_tree_widget_itemDoubleClicked Highlight the element represented by item.
Parameters
item
column
Definition at line 600 of file linksingleelementwidget.cpp.
References QetGraphicsItem::diagram(), m_qtwi_elmt_hash, m_showed_element, Element::setHighlighted(), showedElementWasDeleted(), and Diagram::showMe().
Referenced by LinkSingleElementWidget().
on_m_unlink_pb_clicked
void LinkSingleElementWidget::on_m_unlink_pb_clicked () private slot
Definition at line 581 of file linksingleelementwidget.cpp.
References apply(), buildTree(), PropertiesEditorWidget::m_live_edit, m_unlink, and updateUi().
setElement()
void LinkSingleElementWidget::setElement (Element * element) override virtual
LinkSingleElementWidget::setElement Set element to be the edited element.
Parameters
element
Implements AbstractElementPropertiesEditorWidget.
Definition at line 110 of file linksingleelementwidget.cpp.
References Element::AllReport, QETProject::diagramRemoved(), diagramWasRemovedFromProject(), Element::linkedElementChanged(), AbstractElementPropertiesEditorWidget::m_element, m_element_to_link, m_filter, m_pending_qtwi, m_showed_element, m_unlink, Element::Master, Element::NextReport, Element::PreviousReport, Element::setHighlighted(), Element::Simple, Element::Slave, and updateUi().
Referenced by LinkSingleElementWidget().
setLiveEdit()
bool LinkSingleElementWidget::setLiveEdit (bool live_edit) override virtual
LinkSingleElementWidget::setLiveEdit.
Parameters
live_edit
Returns
Reimplemented from PropertiesEditorWidget.
Definition at line 352 of file linksingleelementwidget.cpp.
References PropertiesEditorWidget::m_live_edit.
setUpCompleter()
void LinkSingleElementWidget::setUpCompleter () private
LinkSingleElementWidget::setUpCompleter Setup the completer of search_field.
Definition at line 393 of file linksingleelementwidget.cpp.
References m_qtwi_strl_hash, and ui.
Referenced by buildTree().
setUpHeaderLabels()
void LinkSingleElementWidget::setUpHeaderLabels () private
Definition at line 430 of file linksingleelementwidget.cpp.
References Element::AllReport, AbstractElementPropertiesEditorWidget::m_element, Element::Slave, QET::Icons::tr, and ui.
Referenced by buildTree().
showButtons
void LinkSingleElementWidget::showButtons () private slot
LinkSingleElementWidget::showButtons Show the button displayed when element is already linked.
Definition at line 564 of file linksingleelementwidget.cpp.
References ui.
Referenced by updateUi().
showedElementWasDeleted
void LinkSingleElementWidget::showedElementWasDeleted () private slot
Definition at line 499 of file linksingleelementwidget.cpp.
References m_showed_element.
Referenced by on_m_tree_widget_itemDoubleClicked().
title()
QString LinkSingleElementWidget::title () const override virtual
LinkSingleElementWidget::title.
Returns
the title used for this editor
Reimplemented from PropertiesEditorWidget.
Definition at line 199 of file linksingleelementwidget.cpp.
References Element::AllReport, AbstractElementPropertiesEditorWidget::m_element, and QET::Icons::tr.
updateUi
void LinkSingleElementWidget::updateUi () override slot
LinkSingleElementWidget::updateUi Update the content of this widget.
Definition at line 211 of file linksingleelementwidget.cpp.
References buildTree(), hideButtons(), AbstractElementPropertiesEditorWidget::m_element, m_unlink, and showButtons().
Referenced by diagramWasRemovedFromProject(), linkTriggered(), on_m_unlink_pb_clicked(), and setElement().
Member Data Documentation
m_context_menu
QMenu* LinkSingleElementWidget::m_context_menu private
Definition at line 100 of file linksingleelementwidget.h.
Referenced by headerCustomContextMenuRequested(), LinkSingleElementWidget(), and on_m_tree_widget_customContextMenuRequested().
m_element_to_link
Element * LinkSingleElementWidget::m_element_to_link = nullptr private
Definition at line 98 of file linksingleelementwidget.h.
Referenced by apply(), associatedUndo(), linkTriggered(), and setElement().
m_filter
Element::kind LinkSingleElementWidget::m_filter private
Definition at line 89 of file linksingleelementwidget.h.
Referenced by availableElements(), and setElement().
m_link_action
QAction* LinkSingleElementWidget::m_link_action private
Definition at line 101 of file linksingleelementwidget.h.
Referenced by LinkSingleElementWidget(), and on_m_tree_widget_customContextMenuRequested().
m_pending_qtwi
QTreeWidgetItem * LinkSingleElementWidget::m_pending_qtwi = nullptr private
Definition at line 95 of file linksingleelementwidget.h.
Referenced by apply(), linkTriggered(), and setElement().
m_qtwi_at_context_menu
QTreeWidgetItem* LinkSingleElementWidget::m_qtwi_at_context_menu = nullptr private
Definition at line 94 of file linksingleelementwidget.h.
Referenced by LinkSingleElementWidget(), linkTriggered(), and on_m_tree_widget_customContextMenuRequested().
m_qtwi_elmt_hash
QHash<QTreeWidgetItem*, Element*> LinkSingleElementWidget::m_qtwi_elmt_hash private
Definition at line 91 of file linksingleelementwidget.h.
Referenced by buildTree(), clearTreeWidget(), linkTriggered(), on_m_search_field_textEdited(), and on_m_tree_widget_itemDoubleClicked().
m_qtwi_strl_hash
QHash<QTreeWidgetItem*, QStringList> LinkSingleElementWidget::m_qtwi_strl_hash private
Definition at line 92 of file linksingleelementwidget.h.
Referenced by buildTree(), clearTreeWidget(), on_m_search_field_textEdited(), and setUpCompleter().
m_save_header_state
QAction * LinkSingleElementWidget::m_save_header_state private
Definition at line 104 of file linksingleelementwidget.h.
Referenced by headerCustomContextMenuRequested(), and LinkSingleElementWidget().
m_show_element
QAction * LinkSingleElementWidget::m_show_element private
Definition at line 103 of file linksingleelementwidget.h.
Referenced by LinkSingleElementWidget(), on_m_show_this_pb_clicked(), and on_m_tree_widget_customContextMenuRequested().
m_show_qtwi
QAction * LinkSingleElementWidget::m_show_qtwi private
Definition at line 102 of file linksingleelementwidget.h.
Referenced by LinkSingleElementWidget(), and on_m_tree_widget_customContextMenuRequested().
m_showed_element
Element* LinkSingleElementWidget::m_showed_element = nullptr private
Definition at line 97 of file linksingleelementwidget.h.
Referenced by LinkSingleElementWidget(), on_m_tree_widget_itemDoubleClicked(), setElement(), showedElementWasDeleted(), and ~LinkSingleElementWidget().
m_unlink
bool LinkSingleElementWidget::m_unlink = false private
Definition at line 88 of file linksingleelementwidget.h.
Referenced by apply(), associatedUndo(), availableElements(), on_m_unlink_pb_clicked(), setElement(), and updateUi().
ui
Ui::LinkSingleElementWidget* LinkSingleElementWidget::ui private
Definition at line 86 of file linksingleelementwidget.h.
Referenced by buildTree(), clearTreeWidget(), headerCustomContextMenuRequested(), hideButtons(), LinkSingleElementWidget(), on_m_tree_widget_customContextMenuRequested(), setUpCompleter(), setUpHeaderLabels(), showButtons(), and ~LinkSingleElementWidget().
The documentation for this class was generated from the following files:
linksingleelementwidget.h
linksingleelementwidget.cpp