QElectroTech: CutTemplateCellsCommand Class Reference
CutTemplateCellsCommand Class Reference
#include <templatecommands.h>
Public Member Functions
CutTemplateCellsCommand (TitleBlockTemplate *, QUndoCommand *=nullptr)
~CutTemplateCellsCommand () override
void undo () override
void redo () override
virtual void setCutCells (const QList< TitleBlockCell * > &)
Public Member Functions inherited from TitleBlockTemplateCommand
TitleBlockTemplateCommand (TitleBlockTemplate *=nullptr, QUndoCommand *=nullptr)
~TitleBlockTemplateCommand () override
TitleBlockTemplate * titleBlockTemplate () const
void setTitleBlockTemplate (TitleBlockTemplate *)
TitleBlockTemplateView * view () const
void setView (TitleBlockTemplateView *)
void refreshView ()
void refreshLayout ()
Public Attributes
QHash< TitleBlockCell *, TitleBlockCell::TemplateCellType > cut_cells_
Cut cells.
Protected Member Functions
virtual void updateText ()
Private Member Functions
CutTemplateCellsCommand (const CutTemplateCellsCommand &)
Additional Inherited Members
Protected Attributes inherited from TitleBlockTemplateCommand
TitleBlockTemplate * tbtemplate_
Modified TitleBlock Template.
TitleBlockTemplateView * view_
This class may trigger a view update.
Detailed Description
This class represents the action of cutting a cells set.
Definition at line 265 of file templatecommands.h.
Constructor & Destructor Documentation
CutTemplateCellsCommand() [1/2]
CutTemplateCellsCommand::CutTemplateCellsCommand (TitleBlockTemplate * tb_template, QUndoCommand * parent = nullptr)
Constructor
Definition at line 886 of file templatecommands.cpp.
~CutTemplateCellsCommand()
CutTemplateCellsCommand::~CutTemplateCellsCommand () override
Destructor
Definition at line 894 of file templatecommands.cpp.
CutTemplateCellsCommand() [2/2]
CutTemplateCellsCommand::CutTemplateCellsCommand (const CutTemplateCellsCommand &) private
Member Function Documentation
redo()
void CutTemplateCellsCommand::redo () override
Redo a cut operation
Definition at line 910 of file templatecommands.cpp.
References cut_cells_, TitleBlockCell::EmptyCell, and TitleBlockTemplateCommand::refreshView().
setCutCells()
void CutTemplateCellsCommand::setCutCells (const QList< TitleBlockCell * > & cells) virtual
Definition at line 917 of file templatecommands.cpp.
References cut_cells_, and updateText().
undo()
void CutTemplateCellsCommand::undo () override
Undo a cut operation
Definition at line 900 of file templatecommands.cpp.
References cut_cells_, and TitleBlockTemplateCommand::refreshView().
updateText()
void CutTemplateCellsCommand::updateText () protected virtual
Update the label describing this command
Definition at line 927 of file templatecommands.cpp.
References cut_cells_, and QET::Icons::tr.
Referenced by setCutCells().
Member Data Documentation
cut_cells_
QHash<TitleBlockCell *, TitleBlockCell::TemplateCellType> CutTemplateCellsCommand::cut_cells_
Cut cells.
Definition at line 284 of file templatecommands.h.
Referenced by redo(), setCutCells(), undo(), and updateText().
The documentation for this class was generated from the following files:
templatecommands.h
templatecommands.cpp