QElectroTech: ElementPropertiesEditorWidget Class Reference
ElementPropertiesEditorWidget Class Reference
The ElementPropertiesEditorWidget class This class provide a dialog for edit various property of element, like the type (master, slave, report etc....) and kind info.
#include <elementpropertieseditorwidget.h>
Public Member Functions
ElementPropertiesEditorWidget (QString &basic_type, DiagramContext &kind_info, DiagramContext &elmt_info, QWidget *parent=nullptr)
ElementPropertiesEditorWidget::ElementPropertiesEditorWidget Default constructor.
~ElementPropertiesEditorWidget () override
ElementPropertiesEditorWidget::~ElementPropertiesEditorWidget Default destructor.
void upDateInterface ()
ElementPropertiesEditorWidget::upDateInterface Update the interface with the curent value.
Private Slots
void on_m_buttonBox_accepted ()
ElementPropertiesEditorWidget::on_m_buttonBox_accepted Action on button accepted : the new information is set.
void on_m_base_type_cb_currentIndexChanged (int index)
ElementPropertiesEditorWidget::on_m_base_type_cb_currentIndexChanged.
Private Member Functions
void setUpInterface ()
ElementPropertiesEditorWidget::setUpInterface.
void updateTree ()
void populateTree ()
ElementPropertiesEditorWidget::populateTree Create QTreeWidgetItem of the tree widget and populate it.
Private Attributes
Ui::ElementPropertiesEditorWidget * ui
QString & m_basic_type
DiagramContext & m_kind_info
DiagramContext & m_elmt_info
Detailed Description
The ElementPropertiesEditorWidget class This class provide a dialog for edit various property of element, like the type (master, slave, report etc....) and kind info.
Definition at line 34 of file elementpropertieseditorwidget.h.
Constructor & Destructor Documentation
ElementPropertiesEditorWidget()
ElementPropertiesEditorWidget::ElementPropertiesEditorWidget (QString & basic_type, DiagramContext & kind_info, DiagramContext & elmt_info, QWidget * parent = nullptr) explicit
ElementPropertiesEditorWidget::ElementPropertiesEditorWidget Default constructor.
Parameters
basic_type : QString of the drawed element
kind_info : DiagramContext to store kindInfo of drawed element
elmt_info : the information of element (label, manufacturer etc...]
parent : parent widget
Definition at line 58 of file elementpropertieseditorwidget.cpp.
References setUpInterface(), ui, and upDateInterface().
~ElementPropertiesEditorWidget()
ElementPropertiesEditorWidget::~ElementPropertiesEditorWidget () override
ElementPropertiesEditorWidget::~ElementPropertiesEditorWidget Default destructor.
Definition at line 78 of file elementpropertieseditorwidget.cpp.
References ui.
Member Function Documentation
on_m_base_type_cb_currentIndexChanged
void ElementPropertiesEditorWidget::on_m_base_type_cb_currentIndexChanged (int index) private slot
ElementPropertiesEditorWidget::on_m_base_type_cb_currentIndexChanged.
Parameters
index : Action when combo-box base type index change
Definition at line 236 of file elementpropertieseditorwidget.cpp.
References ui, and updateTree().
Referenced by upDateInterface().
on_m_buttonBox_accepted
void ElementPropertiesEditorWidget::on_m_buttonBox_accepted () private slot
ElementPropertiesEditorWidget::on_m_buttonBox_accepted Action on button accepted : the new information is set.
Definition at line 197 of file elementpropertieseditorwidget.cpp.
References DiagramContext::addValue(), m_basic_type, m_elmt_info, m_kind_info, and ui.
populateTree()
void ElementPropertiesEditorWidget::populateTree () private
ElementPropertiesEditorWidget::populateTree Create QTreeWidgetItem of the tree widget and populate it.
Definition at line 175 of file elementpropertieseditorwidget.cpp.
References QETApp::elementTranslatedInfoKey(), m_elmt_info, ui, and DiagramContext::value().
Referenced by setUpInterface().
setUpInterface()
void ElementPropertiesEditorWidget::setUpInterface () private
ElementPropertiesEditorWidget::setUpInterface.
Definition at line 115 of file elementpropertieseditorwidget.cpp.
References populateTree(), QET::Icons::tr, and ui.
Referenced by ElementPropertiesEditorWidget().
upDateInterface()
void ElementPropertiesEditorWidget::upDateInterface ()
ElementPropertiesEditorWidget::upDateInterface Update the interface with the curent value.
Definition at line 87 of file elementpropertieseditorwidget.cpp.
References m_basic_type, m_kind_info, on_m_base_type_cb_currentIndexChanged(), and ui.
Referenced by ElementPropertiesEditorWidget().
updateTree()
void ElementPropertiesEditorWidget::updateTree () private
Definition at line 152 of file elementpropertieseditorwidget.cpp.
References ui.
Referenced by on_m_base_type_cb_currentIndexChanged().
Member Data Documentation
m_basic_type
QString& ElementPropertiesEditorWidget::m_basic_type private
Definition at line 58 of file elementpropertieseditorwidget.h.
Referenced by on_m_buttonBox_accepted(), and upDateInterface().
m_elmt_info
DiagramContext & ElementPropertiesEditorWidget::m_elmt_info private
Definition at line 60 of file elementpropertieseditorwidget.h.
Referenced by on_m_buttonBox_accepted(), and populateTree().
m_kind_info
DiagramContext& ElementPropertiesEditorWidget::m_kind_info private
Definition at line 59 of file elementpropertieseditorwidget.h.
Referenced by on_m_buttonBox_accepted(), and upDateInterface().
ui
Ui::ElementPropertiesEditorWidget* ElementPropertiesEditorWidget::ui private
Definition at line 57 of file elementpropertieseditorwidget.h.
Referenced by ElementPropertiesEditorWidget(), on_m_base_type_cb_currentIndexChanged(), on_m_buttonBox_accepted(), populateTree(), setUpInterface(), upDateInterface(), updateTree(), and ~ElementPropertiesEditorWidget().
The documentation for this class was generated from the following files:
elementpropertieseditorwidget.h
elementpropertieseditorwidget.cpp