QElectroTech: QETXML Namespace Reference
QETXML Namespace Reference
Functions
QDomElement penToXml (QDomDocument &parent_document, const QPen &pen)
QETXML::penToXml Write attribute of a QPen in xml element.
QPen penFromXml (const QDomElement &element)
QETXML::penFromXml Build a QPen from a xml description.
QDomElement brushToXml (QDomDocument &parent_document, const QBrush &brush)
QETXML::brushToXml Write attribute of a QBrush in xml element.
QBrush brushFromXml (const QDomElement &element)
QETXML::brushFromXml Build a QBrush from a xml description.
QDomElement fileSystemDirToXmlCollectionDir (QDomDocument &document, const QDir &dir, const QString &rename=QString())
QDomElement fileSystemElementToXmlCollectionElement (QDomDocument &document, QFile &file, const QString &rename=QString())
bool writeXmlFile (const QDomDocument &xml_document, const QString &file_path, QString *error_message=nullptr)
QETXML::writeXmlFile Export an XML document to an UTF-8 text file indented with 4 spaces, with LF end of lines and no BOM.
QDomElement textToDomElement (QDomDocument &document, const QString &tag_name, const QString &value)
QETXML::textToDomElement Return a QDomElement, created from document, with tag name tag_name and text value.
QVector< QDomElement > directChild (const QDomElement &element, const QString &tag_name)
QETXML::directChild.
QVector< QDomElement > subChild (const QDomElement &element, const QString parent_tag_name, const QString &children_tag_name)
QETXML::subChild.
QDomElement marginsToXml (QDomDocument &parent_document, const QMargins &margins)
QETXML::marginsToXml Save a QMargins to xml. the xml tag name is 'margins'.
QMargins marginsFromXml (const QDomElement &element)
QETXML::marginsFromXml.
QDomElement modelHeaderDataToXml (QDomDocument &parent_document, const QAbstractItemModel *model, QHash< int, QList< int >> horizontal_section_role, QHash< int, QList< int >> vertical_section_role)
QETXML::modelHeaderDataToXml Save to xml element all header data specified by horizontal_section_role and vertical_section_role.
void modelHeaderDataFromXml (const QDomElement &element, QAbstractItemModel *model)
QETXML::modelHeaderDataFromXml Restore from xml modele header data.
Detailed Description
This namespace contain some function to use xml with QET.
Function Documentation
brushFromXml()
QBrush QETXML::brushFromXml (const QDomElement & element)
QETXML::brushFromXml Build a QBrush from a xml description.
Parameters
element : the QDomElement that describe the pen
Returns
the created brush. If element is null or tagName isn't "brush" return a default constructed QBrush
Definition at line 135 of file qetxml.cpp.
Referenced by QetShapeItem::fromXml().
brushToXml()
QDomElement QETXML::brushToXml (QDomDocument & parent_document, const QBrush & brush)
QETXML::brushToXml Write attribute of a QBrush in xml element.
Parameters
parent_document : parent document for create the QDomElement
brush : the brush to store
Returns
A QDomElement with the attribute stored. The tagName of QDomeElement is "brush".
Definition at line 97 of file qetxml.cpp.
Referenced by QetShapeItem::toXml().
directChild()
QVector< QDomElement > QETXML::directChild (const QDomElement & element, const QString & tag_name)
QETXML::directChild.
Parameters
element
tag_name
Returns
All direct child of element with the tag name tag_name
Definition at line 313 of file qetxml.cpp.
Referenced by QetGraphicsTableItem::fromXml(), and modelHeaderDataFromXml().
fileSystemDirToXmlCollectionDir()
QDomElement QETXML::fileSystemDirToXmlCollectionDir (QDomDocument & document, const QDir & dir, const QString & rename = QString())
Definition at line 175 of file qetxml.cpp.
References QET::Icons::nl.
Referenced by XmlElementCollection::addElement(), and XmlElementCollection::copyDirectory().
fileSystemElementToXmlCollectionElement()
QDomElement QETXML::fileSystemElementToXmlCollectionElement (QDomDocument & document, QFile & file, const QString & rename = QString())
Definition at line 220 of file qetxml.cpp.
Referenced by XmlElementCollection::addElement(), and XmlElementCollection::copyElement().
marginsFromXml()
QMargins QETXML::marginsFromXml (const QDomElement & element)
QETXML::marginsFromXml.
Parameters
element
Returns
a QMargins from an xml description. The tag name must ne 'margins'
Definition at line 399 of file qetxml.cpp.
Referenced by QetGraphicsHeaderItem::fromXml().
marginsToXml()
QDomElement QETXML::marginsToXml (QDomDocument & parent_document, const QMargins & margins)
QETXML::marginsToXml Save a QMargins to xml. the xml tag name is 'margins'.
Parameters
parent_document
margins
Returns
Definition at line 377 of file qetxml.cpp.
Referenced by QetGraphicsHeaderItem::toXml().
modelHeaderDataFromXml()
void QETXML::modelHeaderDataFromXml (const QDomElement & element, QAbstractItemModel * model)
QETXML::modelHeaderDataFromXml Restore from xml modele header data.
Parameters
element
model
Definition at line 501 of file qetxml.cpp.
References directChild().
Referenced by ProjectDBModel::fromXml().
modelHeaderDataToXml()
QDomElement QETXML::modelHeaderDataToXml (QDomDocument & parent_document, const QAbstractItemModel * model, QHash< int, QList< int >> horizontal_section_role, QHash< int, QList< int >> vertical_section_role)
QETXML::modelHeaderDataToXml Save to xml element all header data specified by horizontal_section_role and vertical_section_role.
Parameters
parent_document
model
horizontal_section_role : key as header section and value as list of roles to save in xml
vertical_section_role :key as header section and value as list of roles to save in xml
Returns
Definition at line 429 of file qetxml.cpp.
References QET::Horizontal, and QET::Vertical.
Referenced by ProjectDBModel::toXml().
penFromXml()
QPen QETXML::penFromXml (const QDomElement & element)
QETXML::penFromXml Build a QPen from a xml description.
Parameters
element : The QDomElement that describe the pen
Returns
the created pen. If element is null or tagName isn't "pen" return a default constructed QPen
Definition at line 62 of file qetxml.cpp.
Referenced by QetShapeItem::fromXml().
penToXml()
QDomElement QETXML::penToXml (QDomDocument & parent_document, const QPen & pen)
QETXML::penToXml Write attribute of a QPen in xml element.
Parameters
parent_document : parent document for create the QDomElement
pen : the pen to store
Returns
: A QDomElement with the attribute stored. The tagName of QDomeElement is "pen".
Definition at line 33 of file qetxml.cpp.
Referenced by QetShapeItem::toXml().
subChild()
QVector< QDomElement > QETXML::subChild (const QDomElement & element, const QString parent_tag_name, const QString & children_tag_name)
QETXML::subChild.
Parameters
element
parent_tag_name
children_tag_name
Returns
When given an xml dom element element, returns a vector of all children dom_elements tagged children_tag_name nested in the parent dom elements tagged parent_tag_name, themselves children of the dom element element.
Definition at line 341 of file qetxml.cpp.
Referenced by Diagram::fromXml().
textToDomElement()
QDomElement QETXML::textToDomElement (QDomDocument & document, const QString & tag_name, const QString & value)
QETXML::textToDomElement Return a QDomElement, created from document, with tag name tag_name and text value.
Parameters
document
tag_name
value
Returns
a QDomElement, created from document
Definition at line 296 of file qetxml.cpp.
Referenced by autonum::sequentialNumbers::toXml().
writeXmlFile()
bool QETXML::writeXmlFile (const QDomDocument & xml_document, const QString & file_path, QString * error_message = nullptr)
QETXML::writeXmlFile Export an XML document to an UTF-8 text file indented with 4 spaces, with LF end of lines and no BOM.
Parameters
xml_document : An XML document to be exported
file_path : Path to the file to be written
error_message : If non-zero, will contain an error message explaining what happened when this function returns false.
Returns
false if an error occurred, true otherwise
Definition at line 257 of file qetxml.cpp.
References QET::Icons::tr.
Referenced by ElementsLocation::setXml().