QElectroTech: XRefPropertiesWidget Class Reference
XRefPropertiesWidget Class Reference
The XRefPropertiesWidget class This class provide a widget to edit the XRefProperties.
#include <xrefpropertieswidget.h>
Public Member Functions
XRefPropertiesWidget (QHash< QString, XRefProperties > properties=QHash< QString, XRefProperties >(), QWidget *parent=nullptr)
XRefPropertiesWidget::XRefPropertiesWidget Default constructor.
~XRefPropertiesWidget () override
XRefPropertiesWidget::~XRefPropertiesWidget Default destructor.
void setProperties (const QHash< QString, XRefProperties > &properties)
XRefPropertiesWidget::setProperties set new properties for this widget.
QHash< QString, XRefProperties > properties ()
XRefPropertiesWidget::properties.
void setReadOnly (bool=true)
XRefPropertiesWidget::setReadOnly Set all of this widget disable if true.
Private Slots
void updateDisplay ()
XRefPropertiesWidget::updateDisplay Update display with the curent displayed type.
void typeChanged ()
XRefPropertiesWidget::typeChanged manage the save of the current properties, when the combo box of type change.
void enableOffsetSB (int i)
XRefPropertiesWidget::enableOffsetSB Enable Offset SB only if Snap to Footer is selected.
Private Member Functions
void buildUi ()
XRefPropertiesWidget::buildUi Build some widget of this ui.
void saveProperties (int index)
XRefPropertiesWidget::saveProperties Save the properties of the type define at index of the combo box m_type_cb.
Private Attributes
Ui::XRefPropertiesWidget * ui
QHash< QString, XRefProperties > m_properties
int m_previous_type_index
Detailed Description
The XRefPropertiesWidget class This class provide a widget to edit the XRefProperties.
Definition at line 32 of file xrefpropertieswidget.h.
Constructor & Destructor Documentation
XRefPropertiesWidget()
XRefPropertiesWidget::XRefPropertiesWidget (QHash< QString, XRefProperties > properties = QHash <QString, XRefProperties>(), QWidget * parent = nullptr)
XRefPropertiesWidget::XRefPropertiesWidget Default constructor.
Parameters
properties properties to use
parent parent widget
Definition at line 31 of file xrefpropertieswidget.cpp.
References buildUi(), enableOffsetSB(), typeChanged(), ui, and updateDisplay().
~XRefPropertiesWidget()
XRefPropertiesWidget::~XRefPropertiesWidget () override
XRefPropertiesWidget::~XRefPropertiesWidget Default destructor.
Definition at line 48 of file xrefpropertieswidget.cpp.
References enableOffsetSB(), typeChanged(), and ui.
Member Function Documentation
buildUi()
void XRefPropertiesWidget::buildUi () private
XRefPropertiesWidget::buildUi Build some widget of this ui.
Definition at line 96 of file xrefpropertieswidget.cpp.
References m_previous_type_index, QET::Icons::tr, and ui.
Referenced by XRefPropertiesWidget().
enableOffsetSB
void XRefPropertiesWidget::enableOffsetSB (int i) private slot
XRefPropertiesWidget::enableOffsetSB Enable Offset SB only if Snap to Footer is selected.
Definition at line 214 of file xrefpropertieswidget.cpp.
References ui.
Referenced by XRefPropertiesWidget(), and ~XRefPropertiesWidget().
properties()
QHash< QString, XRefProperties > XRefPropertiesWidget::properties ()
XRefPropertiesWidget::properties.
Returns
the properties edited by this widget
Definition at line 72 of file xrefpropertieswidget.cpp.
References m_properties, saveProperties(), and ui.
Referenced by setProperties().
saveProperties()
void XRefPropertiesWidget::saveProperties (int index) private
XRefPropertiesWidget::saveProperties Save the properties of the type define at index of the combo box m_type_cb.
Parameters
index
Definition at line 118 of file xrefpropertieswidget.cpp.
References XRefProperties::Bottom, XRefProperties::Contacts, XRefProperties::Cross, XRefProperties::Label, m_properties, XRefProperties::setDisplayHas(), XRefProperties::setMasterLabel(), XRefProperties::setOffset(), XRefProperties::setPrefix(), XRefProperties::setShowPowerContac(), XRefProperties::setSlaveLabel(), XRefProperties::setSnapTo(), XRefProperties::setXrefPos(), and ui.
Referenced by properties(), and typeChanged().
setProperties()
void XRefPropertiesWidget::setProperties (const QHash< QString, XRefProperties > & properties)
XRefPropertiesWidget::setProperties set new properties for this widget.
Parameters
properties
Definition at line 61 of file xrefpropertieswidget.cpp.
References m_previous_type_index, m_properties, properties(), ui, and updateDisplay().
setReadOnly()
void XRefPropertiesWidget::setReadOnly (bool ro = true)
XRefPropertiesWidget::setReadOnly Set all of this widget disable if true.
Parameters
ro
Definition at line 82 of file xrefpropertieswidget.cpp.
References QET::Icons::ro, and ui.
typeChanged
void XRefPropertiesWidget::typeChanged () private slot
XRefPropertiesWidget::typeChanged manage the save of the current properties, when the combo box of type change.
Definition at line 200 of file xrefpropertieswidget.cpp.
References m_previous_type_index, saveProperties(), ui, and updateDisplay().
Referenced by XRefPropertiesWidget(), and ~XRefPropertiesWidget().
updateDisplay
void XRefPropertiesWidget::updateDisplay () private slot
XRefPropertiesWidget::updateDisplay Update display with the curent displayed type.
Definition at line 153 of file xrefpropertieswidget.cpp.
References XRefProperties::Bottom, XRefProperties::Contacts, XRefProperties::Cross, XRefProperties::displayHas(), XRefProperties::getXrefPos(), m_properties, XRefProperties::masterLabel(), XRefProperties::offset(), XRefProperties::prefix(), XRefProperties::showPowerContact(), XRefProperties::slaveLabel(), XRefProperties::snapTo(), and ui.
Referenced by setProperties(), typeChanged(), and XRefPropertiesWidget().
Member Data Documentation
m_previous_type_index
int XRefPropertiesWidget::m_previous_type_index private
Definition at line 58 of file xrefpropertieswidget.h.
Referenced by buildUi(), setProperties(), and typeChanged().
m_properties
QHash<QString, XRefProperties> XRefPropertiesWidget::m_properties private
Definition at line 57 of file xrefpropertieswidget.h.
Referenced by properties(), saveProperties(), setProperties(), and updateDisplay().
ui
Ui::XRefPropertiesWidget* XRefPropertiesWidget::ui private
Definition at line 56 of file xrefpropertieswidget.h.
Referenced by buildUi(), enableOffsetSB(), properties(), saveProperties(), setProperties(), setReadOnly(), typeChanged(), updateDisplay(), XRefPropertiesWidget(), and ~XRefPropertiesWidget().
The documentation for this class was generated from the following files:
xrefpropertieswidget.h
xrefpropertieswidget.cpp