QElectroTech: QetGraphicsItem Class Reference
QetGraphicsItem Class Reference abstract
#include <qetgraphicsitem.h>
Public Member Functions
QetGraphicsItem (QGraphicsItem *parent=nullptr)
QetGraphicsItem::QetGraphicsItem Default constructor.
~QetGraphicsItem () override=0
Diagram * diagram () const
QetGraphicsItem::diagram return the diagram of this item.
virtual void setPos (const QPointF &p)
QetGraphicsItem::setPos set the position of the item to p.
virtual void setPos (qreal x, qreal y)
QetGraphicsItem::setPos set the position of the item.
virtual bool isMovable () const
virtual void setMovable (bool movable)
virtual void editProperty ()
virtual QString name () const
QET::GraphicsItemState state () const
QetGraphicsItem::state.
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mousePressEvent handle the mouse click.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseDoubleClickEvent handle the mouse double click.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseMoveEvent handle mouse movement.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
QetGraphicsItem::mouseReleaseEvent handle mouse release click.
Protected Attributes
bool is_movable_
bool m_first_move
bool snap_to_grid_
QPointF m_mouse_to_origin_movement
QET::GraphicsItemState m_state = QET:: GIOK
Detailed Description
Definition at line 26 of file qetgraphicsitem.h.
Constructor & Destructor Documentation
QetGraphicsItem()
QetGraphicsItem::QetGraphicsItem (QGraphicsItem * parent = nullptr)
QetGraphicsItem::QetGraphicsItem Default constructor.
Parameters
parent : Parent Item
Definition at line 26 of file qetgraphicsitem.cpp.
~QetGraphicsItem()
QetGraphicsItem::~QetGraphicsItem () override pure virtual
Definition at line 33 of file qetgraphicsitem.cpp.
Member Function Documentation
diagram()
Diagram * QetGraphicsItem::diagram () const
QetGraphicsItem::diagram return the diagram of this item.
Definition at line 40 of file qetgraphicsitem.cpp.
Referenced by MasterElement::aboutDeleteXref(), Element::actualLabel(), projectDataBase::addElement(), CrossRefItem::AddExtraInfo(), QetGraphicsTableItem::adjustTableToFolio(), ImagePropertiesWidget::apply(), ShapeGraphicsItemPropertiesWidget::apply(), ImportElementTextPattern::apply(), QetGraphicsTableItem::checkInsufficientRowsCount(), comparPos(), QetShapeItem::contextMenuEvent(), DiagramImageItem::editProperty(), QetShapeItem::editProperty(), Element::editProperty(), CrossRefItem::elementPositionText(), ElementPropertiesWidget::ElementPropertiesWidget(), Element::freezeNewAddedElement(), QetGraphicsTableItem::fromXml(), Element::fromXml(), QetGraphicsTableItem::handlerMousePressEvent(), QetGraphicsTableItem::handlerMouseReleaseEvent(), QetShapeItem::handlerMouseReleaseEvent(), CrossRefItem::init(), QetGraphicsTableItem::initLink(), QetShapeItem::insertPoint(), MasterElement::itemChange(), ReportElement::linkToElement(), MasterElement::linkToElement(), ElementTextItemGroup::mouseDoubleClickEvent(), CrossRefItem::mouseDoubleClickEvent(), mouseMoveEvent(), mouseReleaseEvent(), PotentialSelectorDialog::on_buttonBox_accepted(), LinkSingleElementWidget::on_m_show_linked_pb_clicked(), LinkSingleElementWidget::on_m_tree_widget_itemDoubleClicked(), LinkElementCommand::redo(), QetShapeItem::removePoint(), DynamicElementTextItem::reportChanged(), DynamicElementTextItem::reportFormulaChanged(), DynamicElementTextItem::reportReplacedCompositeText(), MasterPropertiesWidget::setElement(), ElementTextItemGroup::setHoldToBottomPage(), CrossRefItem::setUpConnection(), Element::setUpFormula(), DynamicElementTextItem::setupFormulaConnection(), LinkElementCommand::undo(), ChangeElementInformationCommand::updateProjectDB(), CrossRefItem::updateProperties(), DynamicElementTextItem::updateReportText(), ElementTextItemGroup::updateXref(), MasterElement::xrefPropertiesChanged(), and DynamicElementTextItem::zoomToLinkedElement().
editProperty()
virtual void QetGraphicsItem::editProperty () inline virtual
Reimplemented in Element, QetShapeItem, and DiagramImageItem.
Definition at line 43 of file qetgraphicsitem.h.
Referenced by mouseDoubleClickEvent().
isMovable()
virtual bool QetGraphicsItem::isMovable () const inline virtual
Definition at line 40 of file qetgraphicsitem.h.
References is_movable_.
Referenced by ImagePropertiesWidget::setImageItem(), ImagePropertiesWidget::updateUi(), and ShapeGraphicsItemPropertiesWidget::updateUi().
mouseDoubleClickEvent()
void QetGraphicsItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
QetGraphicsItem::mouseDoubleClickEvent handle the mouse double click.
Parameters
event
Definition at line 97 of file qetgraphicsitem.cpp.
References editProperty().
mouseMoveEvent()
void QetGraphicsItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
QetGraphicsItem::mouseMoveEvent handle mouse movement.
Parameters
event
Definition at line 108 of file qetgraphicsitem.cpp.
References ElementsMover::beginMovement(), ElementsMover::continueMovement(), diagram(), Diagram::elementsMover(), m_first_move, m_mouse_to_origin_movement, and setPos().
Referenced by Element::mouseMoveEvent().
mousePressEvent()
void QetGraphicsItem::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
QetGraphicsItem::mousePressEvent handle the mouse click.
Parameters
event
Definition at line 79 of file qetgraphicsitem.cpp.
References m_first_move.
Referenced by QetShapeItem::mousePressEvent().
mouseReleaseEvent()
void QetGraphicsItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
QetGraphicsItem::mouseReleaseEvent handle mouse release click.
Parameters
event
Definition at line 149 of file qetgraphicsitem.cpp.
References diagram(), Diagram::elementsMover(), and ElementsMover::endMovement().
Referenced by Element::mouseReleaseEvent().
name()
virtual QString QetGraphicsItem::name () const inline virtual
Reimplemented in Element, QetShapeItem, and DiagramImageItem.
Definition at line 44 of file qetgraphicsitem.h.
Referenced by itemText(), and QetGraphicsTableItem::setTableName().
setMovable()
virtual void QetGraphicsItem::setMovable (bool movable) inline virtual
Definition at line 41 of file qetgraphicsitem.h.
References is_movable_.
Referenced by ImagePropertiesWidget::on_m_lock_pos_cb_clicked(), ShapeGraphicsItemPropertiesWidget::on_m_lock_pos_cb_clicked(), and ImagePropertiesWidget::reset().
setPos() [1/2]
void QetGraphicsItem::setPos (const QPointF & p) virtual
QetGraphicsItem::setPos set the position of the item to p.
Parameters
p the new position of item
Definition at line 49 of file qetgraphicsitem.cpp.
References is_movable_, and Diagram::snapToGrid().
Referenced by QetGraphicsTableItem::adjustTableToFolio(), QetGraphicsTableItem::fromXml(), DiagramEventAddImage::mouseMoveEvent(), DiagramEventAddElement::mouseMoveEvent(), mouseMoveEvent(), and setPos().
setPos() [2/2]
void QetGraphicsItem::setPos (qreal x, qreal y) virtual
QetGraphicsItem::setPos set the position of the item.
Parameters
x new abscisse of item
y new ordonne of item
Definition at line 62 of file qetgraphicsitem.cpp.
References setPos().
state()
QET::GraphicsItemState QetGraphicsItem::state () const
QetGraphicsItem::state.
Returns
the current state of this item
Definition at line 70 of file qetgraphicsitem.cpp.
References m_state.
Referenced by Element::buildFromXml(), and Element::Element().
Member Data Documentation
is_movable_
bool QetGraphicsItem::is_movable_ protected
Definition at line 56 of file qetgraphicsitem.h.
Referenced by DiagramImageItem::fromXml(), QetShapeItem::fromXml(), isMovable(), setMovable(), setPos(), DiagramImageItem::toXml(), and QetShapeItem::toXml().
m_first_move
bool QetGraphicsItem::m_first_move protected
Definition at line 57 of file qetgraphicsitem.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_mouse_to_origin_movement
QPointF QetGraphicsItem::m_mouse_to_origin_movement protected
Definition at line 59 of file qetgraphicsitem.h.
Referenced by mouseMoveEvent().
m_state
QET::GraphicsItemState QetGraphicsItem::m_state = QET:: GIOK protected
Definition at line 60 of file qetgraphicsitem.h.
Referenced by Element::buildFromXml(), Element::fromXml(), and state().
snap_to_grid_
bool QetGraphicsItem::snap_to_grid_ protected
Definition at line 58 of file qetgraphicsitem.h.
The documentation for this class was generated from the following files:
qetgraphicsitem.h
qetgraphicsitem.cpp