QElectroTech: GenericPanel Class Reference
GenericPanel Class Reference
The GenericPanel class The generic panel is a QTreeWidget subclass providing extra methods allowing developers to easily add objects (projects, diagrams, title block templates, elements, ...) to it; it also ensures the displayed information remains up to date.
#include <genericpanel.h>
Public Types
enum PanelOption {
AddChildDiagrams = 1, AddChildTemplatesCollection = 2, AddChildTemplates = 4, AddAllChildTemplates = 6,
AddAllChild = 63, All = 127
}
enum MetaData { Item = Qt::UserRole + 1, AliasItem, Parent, PanelFlags }
Signals
bool firstActivated ()
void panelContentChanged ()
Public Member Functions
GenericPanel (QWidget *=nullptr)
~GenericPanel () override
virtual int currentItemType ()
virtual QETProject * projectForItem (QTreeWidgetItem *) const
GenericPanel::projectForItem.
virtual Diagram * diagramForItem (QTreeWidgetItem *) const
GenericPanel::diagramForItem.
virtual TitleBlockTemplateLocation templateLocationForItem (QTreeWidgetItem *) const
GenericPanel::templateLocationForItem.
virtual QETProject * selectedProject () const
GenericPanel::selectedProject.
virtual Diagram * selectedDiagram () const
GenericPanel::selectedDiagram.
virtual TitleBlockTemplateLocation selectedTemplateLocation () const
GenericPanel::selectedTemplateLocation.
virtual QTreeWidgetItem * addProject (QETProject *, QTreeWidgetItem *=nullptr, PanelOptions=AddAllChild)
GenericPanel::addProject.
virtual QTreeWidgetItem * itemForProject (QETProject *)
virtual QTreeWidgetItem * addDiagram (Diagram *, QTreeWidgetItem *=nullptr, PanelOptions=AddAllChild)
GenericPanel::addDiagram.
virtual QTreeWidgetItem * addTemplatesCollection (TitleBlockTemplatesCollection *, QTreeWidgetItem *=nullptr, PanelOptions=AddAllChild)
GenericPanel::addTemplatesCollection.
virtual QTreeWidgetItem * itemForTemplatesCollection (TitleBlockTemplatesCollection *)
GenericPanel::itemForTemplatesCollection.
virtual QTreeWidgetItem * addTemplate (const TitleBlockTemplateLocation &, QTreeWidgetItem *=nullptr, PanelOptions=AddAllChild)
GenericPanel::addTemplate.
Protected Slots
virtual void projectInformationsChanged (QETProject *)
GenericPanel::projectInformationsChanged.
virtual void diagramAdded (QETProject *, Diagram *)
GenericPanel::diagramAdded.
virtual void diagramRemoved (QETProject *, Diagram *)
GenericPanel::diagramRemoved.
virtual void projectDiagramsOrderChanged (QETProject *, int, int)
GenericPanel::projectDiagramsOrderChanged.
virtual void diagramTitleChanged (Diagram *, const QString &)
GenericPanel::diagramTitleChanged Inform this panel the diagram diagram has changed its title to title.
virtual void templatesCollectionChanged (TitleBlockTemplatesCollection *, const QString &)
GenericPanel::templatesCollectionChanged.
virtual void diagramUsedTemplate (TitleBlockTemplatesCollection *, const QString &)
GenericPanel::diagramUsedTemplate.
Protected Member Functions
virtual QTreeWidgetItem * getItemForProject (QETProject *, bool *=nullptr)
virtual QTreeWidgetItem * updateProjectItem (QTreeWidgetItem *, QETProject *, PanelOptions=AddAllChild, bool=false)
GenericPanel::updateProjectItem.
virtual QTreeWidgetItem * fillProjectItem (QTreeWidgetItem *, QETProject *, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillProjectItem.
virtual QTreeWidgetItem * getItemForDiagram (Diagram *, bool *=nullptr)
GenericPanel::getItemForDiagram.
virtual QTreeWidgetItem * updateDiagramItem (QTreeWidgetItem *, Diagram *, PanelOptions=AddAllChild, bool=false)
GenericPanel::updateDiagramItem.
virtual QTreeWidgetItem * fillDiagramItem (QTreeWidgetItem *, Diagram *, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillDiagramItem.
virtual QTreeWidgetItem * getItemForTemplatesCollection (TitleBlockTemplatesCollection *, bool *=nullptr)
GenericPanel::getItemForTemplatesCollection.
virtual QTreeWidgetItem * updateTemplatesCollectionItem (QTreeWidgetItem *, TitleBlockTemplatesCollection *, PanelOptions=AddAllChild, bool=false)
GenericPanel::updateTemplatesCollectionItem.
virtual QTreeWidgetItem * fillTemplatesCollectionItem (QTreeWidgetItem *, TitleBlockTemplatesCollection *, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillTemplatesCollectionItem.
virtual QTreeWidgetItem * getItemForTemplate (const TitleBlockTemplateLocation &, bool *=nullptr)
GenericPanel::getItemForTemplate.
virtual QTreeWidgetItem * updateTemplateItem (QTreeWidgetItem *, const TitleBlockTemplateLocation &, PanelOptions=AddAllChild, bool=false)
GenericPanel::updateTemplateItem.
virtual QTreeWidgetItem * fillTemplateItem (QTreeWidgetItem *, const TitleBlockTemplateLocation &, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillTemplateItem.
virtual QTreeWidgetItem * updateItem (QTreeWidgetItem *, PanelOptions=AddAllChild, bool=false)
GenericPanel::updateItem This generic method is called at the end of each update*Item method. Its only purpose is being reimplemented in a subclass. The default implementation does nothing.
virtual QTreeWidgetItem * fillItem (QTreeWidgetItem *, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillItem This generic method is called at the end of each fill*Item method. Its only purpose is being reimplemented in a subclass. The default implementation does nothing.
virtual QString defaultText (QET::ItemType)
GenericPanel::defaultText.
virtual QIcon defaultIcon (QET::ItemType)
GenericPanel::defaultIcon.
virtual QTreeWidgetItem * makeItem (QET::ItemType, QTreeWidgetItem *=nullptr, const QString &=QString(), const QIcon &=QIcon())
GenericPanel::makeItem Create a QTreeWidgetItem.
virtual void deleteItem (QTreeWidgetItem *, bool=false)
GenericPanel::deleteItem Delete and item and its children.
virtual void markItemAsUnused (QTreeWidgetItem *)
GenericPanel::markItemAsUnused Mark the provided QTreeWidgetItem as unused in its parent project.
virtual void reparent (QTreeWidgetItem *, QTreeWidgetItem *)
GenericPanel::reparent.
QList< QTreeWidgetItem * > childItems (QTreeWidgetItem *, QET::ItemType, bool=false) const
GenericPanel::childItems.
template<typename T >
void removeObsoleteItems (const QList< T > &, QTreeWidgetItem *, QET::ItemType, bool)
template<typename T >
T valueForItem (QTreeWidgetItem *) const
void unregisterItem (QTreeWidgetItem *)
GenericPanel::unregisterItem.
bool event (QEvent *) override
GenericPanel::event Handle various events; reimplemented here to emit the signal firstActivated().
Private Slots
void emitFirstActivated ()
GenericPanel::emitFirstActivated Emit the signal firstActivated().
Private Attributes
bool first_activation_
first_activation_ boolean used to track the first time this widget is activated/shown
QHash< QETProject *, QTreeWidgetItem * > projects_
projects_ Allow quick retrieval of the item representing a given project
QHash< Diagram *, QTreeWidgetItem * > diagrams_
diagrams_ Allow quick retrieval of the item representing a given diagram
QHash< TitleBlockTemplateLocation, QTreeWidgetItem * > tb_templates_
tb_templates_ Allow quick retrieval of the item representing a title block template
Detailed Description
The GenericPanel class The generic panel is a QTreeWidget subclass providing extra methods allowing developers to easily add objects (projects, diagrams, title block templates, elements, ...) to it; it also ensures the displayed information remains up to date.
Definition at line 36 of file genericpanel.h.
Member Enumeration Documentation
MetaData
enum GenericPanel::MetaData
Enumerator
Item
AliasItem
Parent
PanelFlags
Definition at line 50 of file genericpanel.h.
PanelOption
enum GenericPanel::PanelOption
Enumerator
AddChildDiagrams
AddChildTemplatesCollection
AddChildTemplates
AddAllChildTemplates
AddAllChild
All
Definition at line 40 of file genericpanel.h.
Constructor & Destructor Documentation
GenericPanel()
GenericPanel::GenericPanel (QWidget * parent = nullptr)
Constructor
Parameters
parent Parent QWidget
Definition at line 31 of file genericpanel.cpp.
References header.
~GenericPanel()
GenericPanel::~GenericPanel () override
Destructor
Definition at line 42 of file genericpanel.cpp.
Member Function Documentation
addDiagram()
QTreeWidgetItem * GenericPanel::addDiagram (Diagram * diagram, QTreeWidgetItem * parent_item = nullptr, PanelOptions options = AddAllChild) virtual
GenericPanel::addDiagram.
Parameters
diagram
parent_item
options (unused)
Returns
diagram_qtwi
Definition at line 282 of file genericpanel.cpp.
References fillDiagramItem(), getItemForDiagram(), reparent(), and updateDiagramItem().
Referenced by diagramTitleChanged(), and fillProjectItem().
addProject()
QTreeWidgetItem * GenericPanel::addProject (QETProject * project, QTreeWidgetItem * parent_item = nullptr, PanelOptions options = AddAllChild) virtual
GenericPanel::addProject.
Parameters
project
parent_item
options
Returns
project_qtwi
Reimplemented in ElementsPanel.
Definition at line 123 of file genericpanel.cpp.
References fillProjectItem(), getItemForProject(), reparent(), and updateProjectItem().
Referenced by ElementsPanel::addProject(), diagramAdded(), diagramRemoved(), and projectInformationsChanged().
addTemplate()
QTreeWidgetItem * GenericPanel::addTemplate (const TitleBlockTemplateLocation & tb_template, QTreeWidgetItem * parent_item = nullptr, PanelOptions options = AddAllChild) virtual
GenericPanel::addTemplate.
Parameters
tb_template
parent_item
options
Returns
tb_template_qtwi
Definition at line 568 of file genericpanel.cpp.
References fillTemplateItem(), getItemForTemplate(), TitleBlockTemplateLocation::isValid(), reparent(), and updateTemplateItem().
Referenced by fillTemplatesCollectionItem().
addTemplatesCollection()
QTreeWidgetItem * GenericPanel::addTemplatesCollection (TitleBlockTemplatesCollection * tbt_collection, QTreeWidgetItem * parent_item = nullptr, PanelOptions options = AddAllChild) virtual
GenericPanel::addTemplatesCollection.
Parameters
tbt_collection
parent_item
options
Returns
tbt_collection_qtwi
Definition at line 417 of file genericpanel.cpp.
References fillTemplatesCollectionItem(), getItemForTemplatesCollection(), reparent(), and updateTemplatesCollectionItem().
Referenced by diagramUsedTemplate(), fillProjectItem(), ElementsPanel::reload(), and templatesCollectionChanged().
childItems()
QList< QTreeWidgetItem * > GenericPanel::childItems (QTreeWidgetItem * item, QET::ItemType type, bool recursive = false) const protected
GenericPanel::childItems.
Parameters
item Parent item that will be searched.
type Type of items to look for.
recursive Whether to search recursively.
Returns
the child items of item of type type
Definition at line 932 of file genericpanel.cpp.
Referenced by removeObsoleteItems().
currentItemType()
int GenericPanel::currentItemType () virtual
Returns
the type of the current item
Definition at line 48 of file genericpanel.cpp.
defaultIcon()
QIcon GenericPanel::defaultIcon (QET::ItemType type) protected virtual
GenericPanel::defaultIcon.
Parameters
type Item type we want the default icon for
Returns
the default icon for type
Definition at line 848 of file genericpanel.cpp.
References QET::Icons::Diagram, QET::Diagram, QET::ElementsContainer, QET::Icons::Folder, QET::Project, QET::Icons::ProjectFileGP, QET::Icons::TitleBlock, and QET::TitleBlockTemplatesCollectionItem.
Referenced by makeItem().
defaultText()
QString GenericPanel::defaultText (QET::ItemType type) protected virtual
GenericPanel::defaultText.
Parameters
type
Returns
the default text for type
Definition at line 825 of file genericpanel.cpp.
References QET::Diagram, QET::Element, QET::ElementsCategory, QET::ElementsCollection, QET::ElementsCollectionItem, QET::ElementsContainer, QET::Project, QET::TitleBlockTemplate, QET::TitleBlockTemplatesCollection, and QET::TitleBlockTemplatesCollectionItem.
Referenced by makeItem().
deleteItem()
void GenericPanel::deleteItem (QTreeWidgetItem * item, bool deleted_on_cascade = false) protected virtual
GenericPanel::deleteItem Delete and item and its children.
Parameters
item item to delete
deleted_on_cascade true if the item is not being directly deleted but is undergoing the deletion of its parent. (unused)
Definition at line 887 of file genericpanel.cpp.
References unregisterItem().
Referenced by ElementsPanel::projectWasClosed(), and removeObsoleteItems().
diagramAdded
void GenericPanel::diagramAdded (QETProject * project, Diagram * diagram) protected virtual slot
GenericPanel::diagramAdded.
Parameters
project
diagram (unused)
Definition at line 724 of file genericpanel.cpp.
References AddChildDiagrams, addProject(), and panelContentChanged().
Referenced by fillProjectItem().
diagramForItem()
Diagram * GenericPanel::diagramForItem (QTreeWidgetItem * item) const virtual
GenericPanel::diagramForItem.
Parameters
item
Returns
nullptr
Definition at line 72 of file genericpanel.cpp.
References QET::Diagram.
Referenced by selectedDiagram().
diagramRemoved
void GenericPanel::diagramRemoved (QETProject * project, Diagram * diagram) protected virtual slot
GenericPanel::diagramRemoved.
Parameters
project
diagram (unused)
Definition at line 735 of file genericpanel.cpp.
References AddChildDiagrams, addProject(), and panelContentChanged().
Referenced by fillProjectItem().
diagramTitleChanged
void GenericPanel::diagramTitleChanged (Diagram * diagram, const QString & title) protected virtual slot
GenericPanel::diagramTitleChanged Inform this panel the diagram diagram has changed its title to title.
Parameters
diagram
title (unused)
Definition at line 787 of file genericpanel.cpp.
References addDiagram(), and panelContentChanged().
Referenced by updateDiagramItem().
diagramUsedTemplate
void GenericPanel::diagramUsedTemplate (TitleBlockTemplatesCollection * collection, const QString & name) protected virtual slot
GenericPanel::diagramUsedTemplate.
Parameters
collection
name : (unused)
Definition at line 812 of file genericpanel.cpp.
References addTemplatesCollection(), and panelContentChanged().
Referenced by fillProjectItem().
emitFirstActivated
void GenericPanel::emitFirstActivated () private slot
GenericPanel::emitFirstActivated Emit the signal firstActivated().
Definition at line 1031 of file genericpanel.cpp.
References firstActivated().
Referenced by event().
event()
bool GenericPanel::event (QEvent * event) override protected
GenericPanel::event Handle various events; reimplemented here to emit the signal firstActivated().
Parameters
event
Returns
Definition at line 1016 of file genericpanel.cpp.
References emitFirstActivated(), and first_activation_.
fillDiagramItem()
QTreeWidgetItem * GenericPanel::fillDiagramItem (QTreeWidgetItem * diagram_qtwi, Diagram * diagram, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::fillDiagramItem.
Parameters
diagram_qtwi
diagram (unused)
options
freshly_created
Returns
fillItem(diagram_qtwi, options, freshly_created)
Definition at line 402 of file genericpanel.cpp.
References fillItem().
Referenced by addDiagram().
fillItem()
QTreeWidgetItem * GenericPanel::fillItem (QTreeWidgetItem * qtwi, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::fillItem This generic method is called at the end of each fill*Item method. Its only purpose is being reimplemented in a subclass. The default implementation does nothing.
Parameters
qtwi
options (unused)
freshly_created (unused)
Returns
qtwi
Definition at line 702 of file genericpanel.cpp.
Referenced by fillDiagramItem(), fillProjectItem(), fillTemplateItem(), and fillTemplatesCollectionItem().
fillProjectItem()
QTreeWidgetItem * GenericPanel::fillProjectItem (QTreeWidgetItem * project_qtwi, QETProject * project, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::fillProjectItem.
Parameters
project_qtwi
project
options
freshly_created
Returns
fillItem(project_qtwi, options, freshly_created)
Definition at line 227 of file genericpanel.cpp.
References AddChildDiagrams, AddChildTemplatesCollection, addDiagram(), addTemplatesCollection(), QET::Diagram, diagramAdded(), QETProject::diagramAdded(), diagramRemoved(), QETProject::diagramRemoved(), diagramUsedTemplate(), QETProject::diagramUsedTemplate(), fillItem(), projectDiagramsOrderChanged(), QETProject::projectDiagramsOrderChanged(), and removeObsoleteItems().
Referenced by addProject().
fillTemplateItem()
QTreeWidgetItem * GenericPanel::fillTemplateItem (QTreeWidgetItem * tb_template_qtwi, const TitleBlockTemplateLocation & tb_template, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::fillTemplateItem.
Parameters
tb_template_qtwi
tb_template (unused)
options
freshly_created
Returns
fillItem(tb_template_qtwi, options, freshly_created)
Definition at line 664 of file genericpanel.cpp.
References fillItem().
Referenced by addTemplate().
fillTemplatesCollectionItem()
QTreeWidgetItem * GenericPanel::fillTemplatesCollectionItem (QTreeWidgetItem * tbt_collection_qtwi, TitleBlockTemplatesCollection * tbt_collection, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::fillTemplatesCollectionItem.
Parameters
tbt_collection_qtwi
tbt_collection
options
freshly_created
Returns
fillItem(tbt_collection_qtwi, options, freshly_created)
Definition at line 515 of file genericpanel.cpp.
References AddChildTemplates, addTemplate(), TitleBlockTemplatesCollection::changed(), QETProject::diagramUsedTemplate(), fillItem(), removeObsoleteItems(), templatesCollectionChanged(), and QET::TitleBlockTemplate.
Referenced by addTemplatesCollection().
firstActivated
bool GenericPanel::firstActivated () signal
Referenced by ElementsPanel::ElementsPanel(), and emitFirstActivated().
getItemForDiagram()
QTreeWidgetItem * GenericPanel::getItemForDiagram (Diagram * diagram, bool * created = nullptr) protected virtual
GenericPanel::getItemForDiagram.
Parameters
diagram
created
Returns
diagram_qtwi
Definition at line 305 of file genericpanel.cpp.
References QET::Diagram, diagrams_, and makeItem().
Referenced by addDiagram().
getItemForProject()
QTreeWidgetItem * GenericPanel::getItemForProject (QETProject * project, bool * created = nullptr) protected virtual
Parameters
project A standard project.
created if provided with a pointer to a boolean, this method will update it to reflect whether the returned item has been freshly created or not.
Returns
the tree item representing the provided project. If it does not appear within this panel, it is created.
Definition at line 156 of file genericpanel.cpp.
References makeItem(), QET::Project, and projects_.
Referenced by addProject().
getItemForTemplate()
QTreeWidgetItem * GenericPanel::getItemForTemplate (const TitleBlockTemplateLocation & tb_template, bool * created = nullptr) protected virtual
GenericPanel::getItemForTemplate.
Parameters
tb_template
created
Returns
tb_template_qtwi
Definition at line 596 of file genericpanel.cpp.
References TitleBlockTemplateLocation::isValid(), makeItem(), tb_templates_, and QET::TitleBlockTemplate.
Referenced by addTemplate().
getItemForTemplatesCollection()
QTreeWidgetItem * GenericPanel::getItemForTemplatesCollection (TitleBlockTemplatesCollection * tbt_collection, bool * created = nullptr) protected virtual
GenericPanel::getItemForTemplatesCollection.
Parameters
tbt_collection
created
Returns
tbt_collection_item
Definition at line 458 of file genericpanel.cpp.
References makeItem(), tb_templates_, and QET::TitleBlockTemplatesCollection.
Referenced by addTemplatesCollection().
itemForProject()
QTreeWidgetItem * GenericPanel::itemForProject (QETProject * project) virtual
Parameters
project A standard project.
Returns
the tree item representing the provided project or 0 if this project does not appear within this panel.
Definition at line 143 of file genericpanel.cpp.
References projects_.
Referenced by projectDiagramsOrderChanged(), and ElementsPanel::projectWasClosed().
itemForTemplatesCollection()
QTreeWidgetItem * GenericPanel::itemForTemplatesCollection (TitleBlockTemplatesCollection * tbt_collection) virtual
GenericPanel::itemForTemplatesCollection.
Parameters
tbt_collection
Returns
tb_templates_.value(tbt_collection -> location(), nullptr)
nullptr
Definition at line 446 of file genericpanel.cpp.
References tb_templates_.
Referenced by ElementsPanel::addProject().
makeItem()
QTreeWidgetItem * GenericPanel::makeItem (QET::ItemType type, QTreeWidgetItem * parent = nullptr, const QString & label = QString(), const QIcon & icon = QIcon()) protected virtual
GenericPanel::makeItem Create a QTreeWidgetItem.
Parameters
type Item type (e.g QET::Diagram, QET::Project, ...)
parent Parent for the created item
label Label for the created item
icon Icon for the created item
Returns
the create QTreeWidgetItem
Definition at line 870 of file genericpanel.cpp.
References defaultIcon(), and defaultText().
Referenced by getItemForDiagram(), getItemForProject(), getItemForTemplate(), and getItemForTemplatesCollection().
markItemAsUnused()
void GenericPanel::markItemAsUnused (QTreeWidgetItem * qtwi) protected virtual
GenericPanel::markItemAsUnused Mark the provided QTreeWidgetItem as unused in its parent project.
Parameters
qtwi A QTreeWidgetItem
Definition at line 904 of file genericpanel.cpp.
References QET::Icons::tr.
Referenced by updateTemplateItem().
panelContentChanged
void GenericPanel::panelContentChanged () signal
Referenced by diagramAdded(), diagramRemoved(), diagramTitleChanged(), diagramUsedTemplate(), ElementsPanel::ElementsPanel(), projectDiagramsOrderChanged(), projectInformationsChanged(), ElementsPanel::projectWasClosed(), ElementsPanel::projectWasOpened(), and templatesCollectionChanged().
projectDiagramsOrderChanged
void GenericPanel::projectDiagramsOrderChanged (QETProject * project, int from, int to) protected virtual slot
GenericPanel::projectDiagramsOrderChanged.
Parameters
project project where diagram moved
from Index of diagram before move
to Index of diagram after move
Definition at line 747 of file genericpanel.cpp.
References itemForProject(), panelContentChanged(), and updateDiagramItem().
Referenced by fillProjectItem().
projectForItem()
QETProject * GenericPanel::projectForItem (QTreeWidgetItem * item) const virtual
GenericPanel::projectForItem.
Parameters
item
Returns
nullptr
Definition at line 59 of file genericpanel.cpp.
References QET::Project.
Referenced by ElementsPanel::filePathForItem(), and selectedProject().
projectInformationsChanged
void GenericPanel::projectInformationsChanged (QETProject * project) protected virtual slot
GenericPanel::projectInformationsChanged.
Parameters
project
Definition at line 714 of file genericpanel.cpp.
References AddAllChild, addProject(), and panelContentChanged().
Referenced by updateProjectItem().
removeObsoleteItems()
template<typename T > void GenericPanel::removeObsoleteItems (const QList< T > & expected_items, QTreeWidgetItem * item, QET::ItemType type, bool recursive) protected
This variant of childItems() removes any child considered obsolete, i.e. not found in expected_items.
Parameters
expected_items A list of non-obsolete values
item Parent item that will be searched.
type Type of items to look for.
recursive Whether to search recursively.
See also
GenericPanel::childItems()
Definition at line 961 of file genericpanel.cpp.
References childItems(), and deleteItem().
Referenced by fillProjectItem(), and fillTemplatesCollectionItem().
reparent()
void GenericPanel::reparent (QTreeWidgetItem * item, QTreeWidgetItem * parent) protected virtual
GenericPanel::reparent.
Parameters
item
parent
Definition at line 919 of file genericpanel.cpp.
Referenced by addDiagram(), addProject(), addTemplate(), and addTemplatesCollection().
selectedDiagram()
Diagram * GenericPanel::selectedDiagram () const virtual
GenericPanel::selectedDiagram.
Returns
diagramForItem(currentItem())
Definition at line 104 of file genericpanel.cpp.
References diagramForItem().
selectedProject()
QETProject * GenericPanel::selectedProject () const virtual
GenericPanel::selectedProject.
Returns
projectForItem(currentItem())
Definition at line 96 of file genericpanel.cpp.
References projectForItem().
selectedTemplateLocation()
TitleBlockTemplateLocation GenericPanel::selectedTemplateLocation () const virtual
GenericPanel::selectedTemplateLocation.
Returns
templateLocationForItem(currentItem())
Definition at line 112 of file genericpanel.cpp.
References templateLocationForItem().
Referenced by ElementsPanel::startDrag().
templateLocationForItem()
TitleBlockTemplateLocation GenericPanel::templateLocationForItem (QTreeWidgetItem * item) const virtual
GenericPanel::templateLocationForItem.
Parameters
item
Returns
TitleBlockTemplateLocation()
Definition at line 84 of file genericpanel.cpp.
References QET::TitleBlockTemplatesCollectionItem.
Referenced by ElementsPanel::filePathForItem(), and selectedTemplateLocation().
templatesCollectionChanged
void GenericPanel::templatesCollectionChanged (TitleBlockTemplatesCollection * collection, const QString & template_name) protected virtual slot
GenericPanel::templatesCollectionChanged.
Parameters
collection : Title block templates collection that changed and should be updated
template_name : Name of the changed template (unused)
Definition at line 799 of file genericpanel.cpp.
References addTemplatesCollection(), and panelContentChanged().
Referenced by fillTemplatesCollectionItem().
unregisterItem()
void GenericPanel::unregisterItem (QTreeWidgetItem * item) protected
GenericPanel::unregisterItem.
Parameters
item
Definition at line 996 of file genericpanel.cpp.
References QET::Diagram, diagrams_, QET::Project, projects_, tb_templates_, and QET::TitleBlockTemplatesCollectionItem.
Referenced by deleteItem().
updateDiagramItem()
QTreeWidgetItem * GenericPanel::updateDiagramItem (QTreeWidgetItem * diagram_qtwi, Diagram * diagram, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::updateDiagramItem.
Parameters
diagram_qtwi
diagram
options
freshly_created
Returns
updateItem(diagram_qtwi, options, freshly_created)
Definition at line 328 of file genericpanel.cpp.
References Diagram::border_and_titleblock, diagrams_, diagramTitleChanged(), Diagram::diagramTitleChanged(), BorderTitleBlock::finalfolio(), Item, QET::Icons::tr, and updateItem().
Referenced by addDiagram(), and projectDiagramsOrderChanged().
updateItem()
QTreeWidgetItem * GenericPanel::updateItem (QTreeWidgetItem * qtwi, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::updateItem This generic method is called at the end of each update*Item method. Its only purpose is being reimplemented in a subclass. The default implementation does nothing.
Parameters
qtwi
options (unused)
freshly_created (unused)
Returns
qtwi
Definition at line 683 of file genericpanel.cpp.
Referenced by updateDiagramItem(), updateProjectItem(), updateTemplateItem(), and updateTemplatesCollectionItem().
updateProjectItem()
QTreeWidgetItem * GenericPanel::updateProjectItem (QTreeWidgetItem * project_qtwi, QETProject * project, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::updateProjectItem.
Parameters
project_qtwi
project
options (unused)
freshly_created
Returns
updateItem(project_qtwi, options, freshly_created)
Definition at line 179 of file genericpanel.cpp.
References Item, projectInformationsChanged(), QETProject::projectInformationsChanged(), projects_, QETProject::readOnlyChanged(), QET::Icons::tr, and updateItem().
Referenced by addProject().
updateTemplateItem()
QTreeWidgetItem * GenericPanel::updateTemplateItem (QTreeWidgetItem * tb_template_qtwi, const TitleBlockTemplateLocation & tb_template, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::updateTemplateItem.
Parameters
tb_template_qtwi
tb_template
options
freshly_created
Returns
updateItem(tb_template_qtwi, options, freshly_created)
Reimplemented in ElementsPanel.
Definition at line 621 of file genericpanel.cpp.
References Item, markItemAsUnused(), TitleBlockTemplateLocation::name(), TitleBlockTemplateLocation::parentProject(), tb_templates_, TitleBlockTemplateLocation::toString(), QET::Icons::tr, and updateItem().
Referenced by addTemplate(), and ElementsPanel::updateTemplateItem().
updateTemplatesCollectionItem()
QTreeWidgetItem * GenericPanel::updateTemplatesCollectionItem (QTreeWidgetItem * tbt_collection_qtwi, TitleBlockTemplatesCollection * tbt_collection, PanelOptions options = AddAllChild, bool freshly_created = false) protected virtual
GenericPanel::updateTemplatesCollectionItem.
Parameters
tbt_collection_qtwi
tbt_collection
options
freshly_created
Returns
updateItem(tbt_collection_qtwi, options, freshly_created)
Reimplemented in ElementsPanel.
Definition at line 483 of file genericpanel.cpp.
References Item, TitleBlockTemplatesCollection::location(), tb_templates_, TitleBlockTemplateLocation::toString(), QET::Icons::tr, and updateItem().
Referenced by addTemplatesCollection(), and ElementsPanel::updateTemplatesCollectionItem().
valueForItem()
template<typename T > template Diagram * GenericPanel::valueForItem (QTreeWidgetItem *) const protected
Returns
the value stored in item
Definition at line 980 of file genericpanel.cpp.
References Item.
Member Data Documentation
diagrams_
QHash<Diagram *, QTreeWidgetItem *> GenericPanel::diagrams_ private
diagrams_ Allow quick retrieval of the item representing a given diagram
Definition at line 218 of file genericpanel.h.
Referenced by getItemForDiagram(), unregisterItem(), and updateDiagramItem().
first_activation_
bool GenericPanel::first_activation_ private
first_activation_ boolean used to track the first time this widget is activated/shown
Definition at line 208 of file genericpanel.h.
Referenced by event().
projects_
QHash<QETProject *, QTreeWidgetItem *> GenericPanel::projects_ private
projects_ Allow quick retrieval of the item representing a given project
Definition at line 213 of file genericpanel.h.
Referenced by getItemForProject(), itemForProject(), unregisterItem(), and updateProjectItem().
tb_templates_
QHash<TitleBlockTemplateLocation, QTreeWidgetItem *> GenericPanel::tb_templates_ private
tb_templates_ Allow quick retrieval of the item representing a title block template
Definition at line 224 of file genericpanel.h.
Referenced by getItemForTemplate(), getItemForTemplatesCollection(), itemForTemplatesCollection(), unregisterItem(), updateTemplateItem(), and updateTemplatesCollectionItem().
The documentation for this class was generated from the following files:
genericpanel.h
genericpanel.cpp