QElectroTech: AddTableDialog Class Reference
AddTableDialog Class Reference
The AddTableDialog class Provide a dialog used to edit the properties of table befor adding to a diagram. The main difference betwen this dialog and the widget used to edit the properties of table is that the dialog have two extra check box. One for adjust the size of the table to diagram Second for add new tables on new folios if the table can't fit into diagram.
#include <addtabledialog.h>
Public Member Functions
AddTableDialog (QWidget *content_widget, QWidget *parent=nullptr)
AddTableDialog::AddTableDialog.
~AddTableDialog ()
AddTableDialog::~AddNomenclatureDialog.
void setQueryWidget (QWidget *widget)
AddTableDialog::setQueryWidget Not implemented yet.
bool adjustTableToFolio () const
AddTableDialog::adjustTableToFolio.
bool addNewTableToNewDiagram () const
AddTableDialog::addNewTableToNewDiagram.
QString tableName () const
AddTableDialog::tableName.
QMargins headerMargins () const
AddTableDialog::headerMargins.
Qt::Alignment headerAlignment () const
AddTableDialog::headerAlignment.
QFont headerFont () const
AddTableDialog::headerFont.
QMargins tableMargins () const
AddTableDialog::tableMargins.
Qt::Alignment tableAlignment () const
AddTableDialog::tableAlignment.
QFont tableFont () const
AddTableDialog::tableFont.
QWidget * contentWidget () const
Private Slots
void on_m_header_font_pb_clicked ()
void on_m_table_font_pb_clicked ()
void on_m_edit_header_margins_pb_clicked ()
void on_m_table_margins_pb_clicked ()
void saveConfig ()
void loadConfig ()
void fillSavedQuery ()
Private Attributes
Ui::AddTableDialog * ui
QWidget * m_content_widget = nullptr
QMargins m_header_margins = QMargins(5,5,10,5)
QMargins m_table_margins = QMargins(5,5,10,5)
QFont m_header_font = QETApp::diagramTextsFont()
QFont m_table_font = QETApp::diagramTextsFont()
QString m_identifier
Detailed Description
The AddTableDialog class Provide a dialog used to edit the properties of table befor adding to a diagram. The main difference betwen this dialog and the widget used to edit the properties of table is that the dialog have two extra check box. One for adjust the size of the table to diagram Second for add new tables on new folios if the table can't fit into diagram.
Definition at line 37 of file addtabledialog.h.
Constructor & Destructor Documentation
AddTableDialog()
AddTableDialog::AddTableDialog (QWidget * content_widget, QWidget * parent = nullptr) explicit
AddTableDialog::AddTableDialog.
Parameters
content_widget : the widget to display in the "content" tab. This dialog take ownership of content_widget.
parent : parent widget.
Definition at line 32 of file addtabledialog.cpp.
References fillSavedQuery(), ConfigSaveLoaderWidget::loadClicked(), loadConfig(), m_content_widget, m_header_font, m_table_font, ConfigSaveLoaderWidget::saveClicked(), saveConfig(), QET::Icons::tr, and ui.
~AddTableDialog()
AddTableDialog::~AddTableDialog ()
AddTableDialog::~AddNomenclatureDialog.
Definition at line 51 of file addtabledialog.cpp.
References ui.
Member Function Documentation
addNewTableToNewDiagram()
bool AddTableDialog::addNewTableToNewDiagram () const
AddTableDialog::addNewTableToNewDiagram.
Returns
Definition at line 76 of file addtabledialog.cpp.
References ui.
Referenced by QetGraphicsTableFactory::create().
adjustTableToFolio()
bool AddTableDialog::adjustTableToFolio () const
AddTableDialog::adjustTableToFolio.
Returns
Definition at line 68 of file addtabledialog.cpp.
References ui.
Referenced by QetGraphicsTableFactory::create().
contentWidget()
QWidget * AddTableDialog::contentWidget () const
Definition at line 152 of file addtabledialog.cpp.
References m_content_widget.
Referenced by QetGraphicsTableFactory::newTable().
fillSavedQuery
void AddTableDialog::fillSavedQuery () private slot
Definition at line 288 of file addtabledialog.cpp.
References QETApp::configDir(), QET::Icons::it, and ui.
Referenced by AddTableDialog().
headerAlignment()
Qt::Alignment AddTableDialog::headerAlignment () const
AddTableDialog::headerAlignment.
Returns
Definition at line 100 of file addtabledialog.cpp.
References ui.
Referenced by QetGraphicsTableFactory::newTable().
headerFont()
QFont AddTableDialog::headerFont () const
AddTableDialog::headerFont.
Returns
Definition at line 116 of file addtabledialog.cpp.
References m_header_font.
Referenced by QetGraphicsTableFactory::newTable(), and saveConfig().
headerMargins()
QMargins AddTableDialog::headerMargins () const
AddTableDialog::headerMargins.
Returns
Definition at line 92 of file addtabledialog.cpp.
References m_header_margins.
Referenced by QetGraphicsTableFactory::newTable(), and saveConfig().
loadConfig
void AddTableDialog::loadConfig () private slot
Definition at line 233 of file addtabledialog.cpp.
References QETApp::configDir(), m_header_font, m_header_margins, m_table_font, m_table_margins, QETUtils::marginsFromString(), and ui.
Referenced by AddTableDialog().
on_m_edit_header_margins_pb_clicked
void AddTableDialog::on_m_edit_header_margins_pb_clicked () private slot
Definition at line 177 of file addtabledialog.cpp.
References MarginsEditDialog::getMargins(), and m_header_margins.
on_m_header_font_pb_clicked
void AddTableDialog::on_m_header_font_pb_clicked () private slot
Definition at line 156 of file addtabledialog.cpp.
References m_header_font, QET::Icons::tr, and ui.
on_m_table_font_pb_clicked
void AddTableDialog::on_m_table_font_pb_clicked () private slot
Definition at line 167 of file addtabledialog.cpp.
References m_table_font, QET::Icons::tr, and ui.
on_m_table_margins_pb_clicked
void AddTableDialog::on_m_table_margins_pb_clicked () private slot
Definition at line 185 of file addtabledialog.cpp.
References MarginsEditDialog::getMargins(), and m_table_margins.
saveConfig
void AddTableDialog::saveConfig () private slot
Definition at line 193 of file addtabledialog.cpp.
References QETApp::configDir(), headerFont(), headerMargins(), QETUtils::marginsToString(), tableFont(), tableMargins(), and ui.
Referenced by AddTableDialog().
setQueryWidget()
void AddTableDialog::setQueryWidget (QWidget * widget)
AddTableDialog::setQueryWidget Not implemented yet.
Parameters
widget
Definition at line 60 of file addtabledialog.cpp.
tableAlignment()
Qt::Alignment AddTableDialog::tableAlignment () const
AddTableDialog::tableAlignment.
Returns
Definition at line 132 of file addtabledialog.cpp.
References ui.
Referenced by QetGraphicsTableFactory::newTable().
tableFont()
QFont AddTableDialog::tableFont () const
AddTableDialog::tableFont.
Returns
Definition at line 148 of file addtabledialog.cpp.
References m_table_font.
Referenced by QetGraphicsTableFactory::newTable(), and saveConfig().
tableMargins()
QMargins AddTableDialog::tableMargins () const
AddTableDialog::tableMargins.
Returns
Definition at line 124 of file addtabledialog.cpp.
References m_table_margins.
Referenced by saveConfig().
tableName()
QString AddTableDialog::tableName () const
AddTableDialog::tableName.
Returns
Definition at line 84 of file addtabledialog.cpp.
References ui.
Referenced by QetGraphicsTableFactory::create(), and QetGraphicsTableFactory::newTable().
Member Data Documentation
m_content_widget
QWidget* AddTableDialog::m_content_widget = nullptr private
Definition at line 72 of file addtabledialog.h.
Referenced by AddTableDialog(), and contentWidget().
m_header_font
QFont AddTableDialog::m_header_font = QETApp::diagramTextsFont() private
Definition at line 77 of file addtabledialog.h.
Referenced by AddTableDialog(), headerFont(), loadConfig(), and on_m_header_font_pb_clicked().
m_header_margins
QMargins AddTableDialog::m_header_margins = QMargins(5,5,10,5) private
Definition at line 74 of file addtabledialog.h.
Referenced by headerMargins(), loadConfig(), and on_m_edit_header_margins_pb_clicked().
m_identifier
QString AddTableDialog::m_identifier private
Definition at line 80 of file addtabledialog.h.
m_table_font
QFont AddTableDialog::m_table_font = QETApp::diagramTextsFont() private
Definition at line 78 of file addtabledialog.h.
Referenced by AddTableDialog(), loadConfig(), on_m_table_font_pb_clicked(), and tableFont().
m_table_margins
QMargins AddTableDialog::m_table_margins = QMargins(5,5,10,5) private
Definition at line 75 of file addtabledialog.h.
Referenced by loadConfig(), on_m_table_margins_pb_clicked(), and tableMargins().
ui
Ui::AddTableDialog* AddTableDialog::ui private
Definition at line 70 of file addtabledialog.h.
Referenced by addNewTableToNewDiagram(), AddTableDialog(), adjustTableToFolio(), fillSavedQuery(), headerAlignment(), loadConfig(), on_m_header_font_pb_clicked(), on_m_table_font_pb_clicked(), saveConfig(), tableAlignment(), tableName(), and ~AddTableDialog().
The documentation for this class was generated from the following files:
addtabledialog.h
addtabledialog.cpp