QElectroTech: Diagram Class Reference
Diagram Class Reference
The Diagram class This class represents an electric diagram. It manages its various child elements, conductors and texts and handles their graphic rendering.
#include <diagram.h>
Public Types
enum BorderOptions { EmptyBorder, TitleBlock, Columns }
The BorderOptions enum Represents available options when rendering a particular diagram: EmptyBorder: display border only TitleBlock: display title block Columns: display columns.
enum NumerotationType { Conductors }
Represents available option of Numerotation type.
Public Slots
void adjustSceneRect ()
Diagram::adjustSceneRect Recalcul and adjust the size of the scene.
void titleChanged (const QString &)
Diagram::titleChanged emit(diagramTitleChanged(this, title));.
void titleBlockTemplateChanged (const QString &)
Diagram::titleBlockTemplateChanged This slot may be used to inform the diagram object that the given title block template has changed. The diagram will thus flush its title block-dedicated rendering cache.
void titleBlockTemplateRemoved (const QString &, const QString &=QString())
Diagram::titleBlockTemplateRemoved This slot has to be be used to inform this class that the given title block template is about to be removed and is no longer accessible. This class will either use the provided optional TitleBlockTemplate or the default title block provided by QETApp::defaultTitleBlockTemplate()
void setTitleBlockTemplate (const QString &)
Diagram::setTitleBlockTemplate Set the template to use to render the title block of this diagram.
void updateLabels ()
Diagram::updateLabels Update elements and conductors that reference folio field in their labels.
void loadElmtFolioSeq ()
Diagram::loadElmtFolioSeq This class loads all folio sequential variables related to the current autonum.
void loadCndFolioSeq ()
Diagram::loadCndFolioSeq This class loads all conductor folio sequential variables related to the current autonum.
void selectAll ()
Diagram::selectAll Select all schema objects.
void deselectAll ()
Diagram::deselectAll Deselects all selected objects.
void invertSelection ()
Diagram::invertSelection Reverses the selection state of all schema objects Inverse l'etat de selection de tous les objets du schema.
Signals
void showDiagram (Diagram *)
void usedTitleBlockTemplateChanged (const QString &)
void diagramTitleChanged (Diagram *, const QString &)
void findElementRequired (const ElementsLocation &)
void editElementRequired (const ElementsLocation &)
Signal emitted when users wish to edit an element from the diagram.
void diagramActivated ()
Public Member Functions
QUuid uuid ()
Diagram::uuid.
void setEventInterface (DiagramEventInterface *event_interface)
Diagram::setEventInterface Set event_interface has current interface. Diagram become the ownership of event_interface If there is a previous interface, they will be delete before and call init() to the new interface.
void clearEventInterface ()
Diagram::clearEventInterface Clear the current event interface.
QString conductorsAutonumName () const
Diagram::conductorsAutonumName.
void setConductorsAutonumName (const QString &name)
Diagram::setConductorsAutonumName.
QETProject * project () const
Diagram::project.
int folioIndex () const
Diagram::folioIndex.
qreal declaredQElectroTechVersion (bool=true) const
Diagram::declaredQElectroTechVersion.
void showMe ()
bool isReadOnly () const
Diagram::isReadOnly.
void setConductor (bool)
Diagram::setConductor Display or hide the conductor setter, i.e. a dashed conductor stub which appears when creating a conductor between two terminals.
void setConductorStart (QPointF)
Diagram::setConductorStart Set the start point of the conductor setter.
void setConductorStop (QPointF)
Diagram::setConductorStop Set the end point of the conductor setter.
QList< QSet< Conductor * > > potentials ()
Diagram::potential.
QDomDocument toXml (bool=true)
Diagram::toXml Exports all or part of the schema.
bool initFromXml (QDomElement &, QPointF=QPointF(), bool=true, DiagramContent *=nullptr)
Diagram::initFromXml Imports the described schema in an XML element. This method delegates its work to Diagram :: fromXml If the import is successful, this method also initializes the XML document internal allowing to manage the recording of this diagram in the project to which it belongs.
bool fromXml (QDomDocument &, QPointF=QPointF(), bool=true, DiagramContent *=nullptr)
Diagram::fromXml Imports the described schema into an XML document. If a position is specified, the imported elements are positioned so that the upper left corner of the smallest rectangle that can surround them all (the bounding rect) is at this position.
bool fromXml (QDomElement &, QPointF=QPointF(), bool=true, DiagramContent *=nullptr)
Diagram::fromXml Imports the described schema in an XML element. If a position is specified, the imported elements are positioned in such a way that the upper left corner of the smallest rectangle that can surround them all (the bounding rect) either at this position.
void folioSequentialsToXml (QHash< QString, QStringList > *, QDomElement *, const QString &, const QString &, QDomDocument *)
Diagram::folioSequentialsToXml Add folio sequential to QDomElement.
void folioSequentialsFromXml (const QDomElement &, QHash< QString, QStringList > *, const QString &, const QString &, const QString &, const QString &)
Diagram::folioSequentialsFromXml Load folio sequential from QDomElement.
void refreshContents ()
Diagram::refreshContents refresh all content of diagram.
virtual void addItem (QGraphicsItem *item)
Diagram::addItem Réimplemented from QGraphicsScene::addItem(QGraphicsItem *item) Do some specific operation if item need it (for exemple an element)
virtual void removeItem (QGraphicsItem *item)
Diagram::removeItem Reimplemented from QGraphicsScene::removeItem(QGraphicsItem *item) Do some specific operation if item need it (for exemple an element)
ExportProperties applyProperties (const ExportProperties &)
Diagram::applyProperties This method allows you to apply new rendering options while accessing the current rendering properties.
void setDisplayGrid (bool)
Diagram::setDisplayGrid Set whether the diagram grid should be drawn.
bool displayGrid ()
Diagram::displayGrid.
void setUseBorder (bool)
Diagram::setUseBorder Set whether the diagram border (including rows/colums headers and the title block) should be rendered along with the diagram. When set to false, the size of the smallest rectangle containing all items is considered as the diagram size.
bool useBorder ()
Diagram::useBorder.
void setBorderOptions (BorderOptions)
Diagram::setBorderOptions Set the rendering options for the diagram border (including rows/colums headers and the title block)
BorderOptions borderOptions ()
Diagram::borderOptions.
DiagramPosition convertPosition (const QPointF &)
Diagram::convertPosition.
bool drawTerminals () const
Diagram::drawTerminals.
void setDrawTerminals (bool)
Diagram::setDrawTerminals Defines whether or not to display the terminals.
bool drawColoredConductors () const
Diagram::drawColoredConductors.
void setDrawColoredConductors (bool)
Diagram::setDrawColoredConductors Defines whether or not to respect the colors of the conductors. If not, the conductors are all drawn in black.
QString title () const
Diagram::title.
bool toPaintDevice (QPaintDevice &, int=-1, int=-1, Qt::AspectRatioMode=Qt::KeepAspectRatio)
QSize imageSize () const
Diagram::imageSize Allows you to know the dimensions that the image generated by the toImage() method will have.
bool isEmpty () const
Diagram::isEmpty An empty schema contains no element, conductor, or text field.
QList< Element * > elements () const
Diagram::elements.
QList< Conductor * > conductors () const
Diagram::conductors.
QSet< Conductor * > selectedConductors () const
Diagram::selectedConductors.
DiagramContent content () const
Diagram::content.
bool canRotateSelection () const
Diagram::canRotateSelection.
ElementsMover & elementsMover ()
Diagram::elementsMover.
ElementTextsMover & elementTextsMover ()
Diagram::elementTextsMover.
bool usesElement (const ElementsLocation &)
Diagram::usesElement Used to find out if an element is used on a schema.
bool usesTitleBlockTemplate (const QString &)
Diagram::usesTitleBlockTemplate.
QUndoStack & undoStack ()
Diagram::undoStack.
QGIManager & qgiManager ()
Diagram::qgiManager.
void freezeElements (bool freeze)
Diagram::freezeElements Freeze every existent element label.
void unfreezeElements ()
Diagram::unfreezeElements Unfreeze every existent element label.
void setFreezeNewElements (bool)
Diagram::freezeNewElements Set new element label to be frozen.
bool freezeNewElements ()
Diagram::freezeNewElements.
void freezeConductors (bool freeze)
Diagram::freezeConductors Freeze every existent conductor label.
void setFreezeNewConductors (bool)
Diagram::setfreezeNewConductors Set new conductor label to be frozen.
bool freezeNewConductors ()
Diagram::freezeNewConductors.
void insertFolioSeqHash (QHash< QString, QStringList > *hash, const QString &title, const QString &seq, NumerotationContext *nc)
Diagram::insertFolioSeqHash This class inserts a stringlist containing all sequential variables related to an autonum in a QHash.
void loadFolioSeqHash (QHash< QString, QStringList > *hash, const QString &title, const QString &seq, NumerotationContext *nc)
Diagram::loadFolioSeqHash This class loads all folio sequential variables related to the current autonum.
void changeZValue (QET::DepthOption option)
Diagram::changeZValue Change the Z value of the current selected item, according to option.
Static Public Member Functions
static bool clipboardMayContainDiagram ()
Diagram::clipboardMayContainDiagram.
static QPointF snapToGrid (const QPointF &p)
Diagram::snapToGrid Return a nearest snap point of p.
Public Attributes
ConductorProperties defaultConductorProperties
Default properties for new conductors.
BorderTitleBlock border_and_titleblock
Diagram dimensions and title block.
QHash< QString, QStringList > m_elmt_unitfolio_max
Hash containing max values for folio sequential autonums in this diagram.
QHash< QString, QStringList > m_elmt_tenfolio_max
QHash< QString, QStringList > m_elmt_hundredfolio_max
QHash< QString, QStringList > m_cnd_unitfolio_max
Hash containing max values for folio sequential autonums in this diagram.
QHash< QString, QStringList > m_cnd_tenfolio_max
QHash< QString, QStringList > m_cnd_hundredfolio_max
Static Public Attributes
static int xGrid = 10
abscissa grid step size
static int yGrid = 10
ordinate grid step size
static int xKeyGrid = 10
Key grid x step size.
static int yKeyGrid = 10
Key grid y step size.
static int xKeyGridFine = 1
Key grid fine x step size.
static int yKeyGridFine = 1
Key grid fine y step size.
static const qreal margin = 5.0
margin around the diagram
static QColor background_color = Qt::white
background color of diagram
Protected Member Functions
void drawBackground (QPainter *, const QRectF &) override
Diagram::drawBackground Draw the background of the diagram, ie the grid.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
Diagram::mouseDoubleClickEvent This event is managed by diagram event interface if any.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
Diagram::mousePressEvent This event is managed by diagram event interface if any.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
Diagram::mouseMoveEvent This event is managed by diagram event interface if any.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Diagram::mouseReleaseEvent This event is managed by diagram event interface if any.
void wheelEvent (QGraphicsSceneWheelEvent *event) override
Diagram::wheelEvent This event is managed by diagram event interface if any.
void keyPressEvent (QKeyEvent *event) override
Diagram::keyPressEvent This event is managed by diagram event interface if any. Else move selected elements.
void keyReleaseEvent (QKeyEvent *) override
Diagram::keyReleaseEvent This event is managed by diagram event interface if any. Else move selected element.
Private Member Functions
Diagram (QETProject *project)
Diagram::Diagram Constructor.
~Diagram () override
Diagram::~Diagram Destructor.
Diagram (const Diagram &diagram)
Private Attributes
friend DiagramFolioList
friend QETProject
QGraphicsLineItem * conductor_setter_
ElementsMover m_elements_mover
ElementTextsMover m_element_texts_mover
QGIManager * qgi_manager_
QETProject * m_project
QDomDocument xml_document_
qreal diagram_qet_version_
bool draw_grid_
bool use_border_
bool draw_terminals_
bool draw_colored_conductors_
QString m_conductors_autonum_name
DiagramEventInterface * m_event_interface
bool m_freeze_new_elements
bool m_freeze_new_conductors_
QUuid m_uuid = QUuid::createUuid()
Detailed Description
The Diagram class This class represents an electric diagram. It manages its various child elements, conductors and texts and handles their graphic rendering.
Definition at line 55 of file diagram.h.
Member Enumeration Documentation
BorderOptions
enum Diagram::BorderOptions
The BorderOptions enum Represents available options when rendering a particular diagram: EmptyBorder: display border only TitleBlock: display title block Columns: display columns.
Enumerator
EmptyBorder
TitleBlock
Columns
Definition at line 77 of file diagram.h.
NumerotationType
enum Diagram::NumerotationType
Represents available option of Numerotation type.
Enumerator
Conductors
Definition at line 79 of file diagram.h.
Constructor & Destructor Documentation
Diagram() [1/2]
Diagram::Diagram (QETProject * project) private
Diagram::Diagram Constructor.
Parameters
project : The project of this diagram and also parent QObject
Definition at line 64 of file diagram.cpp.
References adjustSceneRect(), border_and_titleblock, BorderTitleBlock::borderChanged(), conductor_setter_, diagramActivated(), BorderTitleBlock::diagramTitleChanged(), loadCndFolioSeq(), loadElmtFolioSeq(), BorderTitleBlock::needTitleBlockTemplate(), qgi_manager_, setTitleBlockTemplate(), BorderTitleBlock::titleBlockFolioChanged(), titleChanged(), and updateLabels().
~Diagram()
Diagram::~Diagram () override private
Diagram::~Diagram Destructor.
Definition at line 120 of file diagram.cpp.
References conductor_setter_, m_event_interface, qgi_manager_, and undoStack().
Diagram() [2/2]
Diagram::Diagram (const Diagram & diagram) private
Member Function Documentation
addItem()
void Diagram::addItem (QGraphicsItem * item) virtual
Diagram::addItem Réimplemented from QGraphicsScene::addItem(QGraphicsItem *item) Do some specific operation if item need it (for exemple an element)
Parameters
item
Definition at line 1550 of file diagram.cpp.
References Terminal::addConductor(), projectDataBase::addElement(), Conductor::calculateTextItemPosition(), QETProject::dataBase(), isReadOnly(), m_project, Conductor::terminal1, Conductor::terminal2, Conductor::Type, and Element::Type.
Referenced by fromXml(), DiagramEventAddImage::mouseMoveEvent(), DiagramEventAddShape::mousePressEvent(), QetGraphicsTableFactory::newTable(), PasteDiagramCommand::redo(), DeleteQGraphicsItemCommand::undo(), and DiagramEventAddShape::updateHelpCross().
adjustSceneRect
void Diagram::adjustSceneRect () slot
Diagram::adjustSceneRect Recalcul and adjust the size of the scene.
Definition at line 2166 of file diagram.cpp.
References border_and_titleblock, and BorderTitleBlock::borderAndTitleBlockRect().
Referenced by Diagram(), fromXml(), MultiPasteDialog::on_m_button_box_accepted(), DiagramView::scrollOnMovement(), MultiPasteDialog::updatePreview(), and DiagramView::zoom().
applyProperties()
ExportProperties Diagram::applyProperties (const ExportProperties & new_properties)
Diagram::applyProperties This method allows you to apply new rendering options while accessing the current rendering properties.
Parameters
new_properties : New rendering options to apply
Returns
rendering options before applying new_properties
Definition at line 2186 of file diagram.cpp.
References border_and_titleblock, QET::BorderArea, BorderTitleBlock::borderIsDisplayed(), BorderTitleBlock::displayBorder(), displayGrid(), BorderTitleBlock::displayTitleBlock(), ExportProperties::draw_border, ExportProperties::draw_colored_conductors, ExportProperties::draw_grid, ExportProperties::draw_terminals, ExportProperties::draw_titleblock, drawColoredConductors(), drawTerminals(), QET::ElementsArea, ExportProperties::exported_area, setDisplayGrid(), setDrawColoredConductors(), setDrawTerminals(), setUseBorder(), BorderTitleBlock::titleBlockIsDisplayed(), and useBorder().
borderOptions()
Diagram::BorderOptions Diagram::borderOptions () inline
Diagram::borderOptions.
Returns
The rendering optios for the diagram border
See also
setBorderOptions
Definition at line 384 of file diagram.h.
References border_and_titleblock, Columns, BorderTitleBlock::columnsAreDisplayed(), EmptyBorder, TitleBlock, and BorderTitleBlock::titleBlockIsDisplayed().
canRotateSelection()
bool Diagram::canRotateSelection () const
Diagram::canRotateSelection.
Returns
True if a least one of selected items can be rotated
Definition at line 2395 of file diagram.cpp.
References IndependentTextItem::Type, ConductorTextItem::Type, DiagramImageItem::Type, DynamicElementTextItem::Type, and Element::Type.
Referenced by QETDiagramEditor::slot_updateComplexActions().
changeZValue()
void Diagram::changeZValue (QET::DepthOption option)
Diagram::changeZValue Change the Z value of the current selected item, according to option.
Parameters
option
Definition at line 1784 of file diagram.cpp.
References QET::BringForward, DiagramContent::Elements, DiagramContent::Images, DiagramContent::items(), QET::Lower, QET::Raise, DiagramContent::SelectedOnly, QET::SendBackward, DiagramContent::Shapes, QET::Icons::tr, undoStack(), and Terminal::Z.
Referenced by QETDiagramEditor::setUpActions().
clearEventInterface()
void Diagram::clearEventInterface ()
Diagram::clearEventInterface Clear the current event interface.
Definition at line 551 of file diagram.cpp.
References m_event_interface.
clipboardMayContainDiagram()
bool Diagram::clipboardMayContainDiagram () static
Diagram::clipboardMayContainDiagram.
Returns
true if the clipboard appears to contain a schema
Definition at line 2312 of file diagram.cpp.
Referenced by DiagramView::contextMenuEvent(), and QETDiagramEditor::slot_updatePasteAction().
conductors()
QList< Conductor * > Diagram::conductors () const
Diagram::conductors.
Returns
the list containing all conductors
Definition at line 2044 of file diagram.cpp.
Referenced by freezeConductors(), potentials(), refreshContents(), and updateLabels().
conductorsAutonumName()
QString Diagram::conductorsAutonumName () const
Diagram::conductorsAutonumName.
Returns
the name of autonum to use.
Definition at line 564 of file diagram.cpp.
References m_conductors_autonum_name.
Referenced by DiagramPropertiesDialog::DiagramPropertiesDialog(), ConductorAutoNumerotation::newProperties(), ConductorAutoNumerotation::numerateNewConductor(), AutoNumberingDockWidget::setActive(), and AutoNumberingDockWidget::setConductorActive().
content()
DiagramContent Diagram::content () const
Diagram::content.
Returns
The content of the diagram. The conductors are all seated in conductorsToMove.
Definition at line 2375 of file diagram.cpp.
References DiagramContent::m_conductors_to_move, DiagramContent::m_elements, and DiagramContent::m_text_fields.
Referenced by potentials(), and updateLabels().
convertPosition()
DiagramPosition Diagram::convertPosition (const QPointF & pos)
Diagram::convertPosition.
Parameters
pos : Cartesian position (ex: 10.3, 45.2) to transform into position in the grid (ex: B2)
Returns
a position in the grid corresponding to pos
Definition at line 2223 of file diagram.cpp.
References border_and_titleblock, BorderTitleBlock::convertPosition(), and DiagramPosition::setPosition().
Referenced by projectDataBase::addElement(), autonum::AssignVariables::AssignVariables(), and comparPos().
declaredQElectroTechVersion()
qreal Diagram::declaredQElectroTechVersion (bool fallback_to_project = true) const
Diagram::declaredQElectroTechVersion.
Parameters
fallback_to_project : When a diagram does not have a declared version, this method will use the one declared by its parent project only if fallback_to_project is true.
Returns
the declared QElectroTech version of this diagram
Definition at line 2348 of file diagram.cpp.
References diagram_qet_version_, and m_project.
Referenced by fromXml().
deselectAll
void Diagram::deselectAll () slot
Diagram::deselectAll Deselects all selected objects.
Definition at line 1690 of file diagram.cpp.
References isEmpty().
diagramActivated
void Diagram::diagramActivated () signal
Referenced by Diagram().
diagramTitleChanged
void Diagram::diagramTitleChanged (Diagram * , const QString &) signal
Referenced by titleChanged(), and GenericPanel::updateDiagramItem().
displayGrid()
bool Diagram::displayGrid () inline
Diagram::displayGrid.
Returns
draw_grid_ true if the grid is drawn, false otherwise.
Definition at line 341 of file diagram.h.
References draw_grid_.
Referenced by applyProperties().
drawBackground()
void Diagram::drawBackground (QPainter * p, const QRectF & r) override protected
Diagram::drawBackground Draw the background of the diagram, ie the grid.
Parameters
p : The QPainter to use for drawing
r : The rectangle of the area to be drawn
Definition at line 158 of file diagram.cpp.
References background_color, border_and_titleblock, BorderTitleBlock::draw(), draw_grid_, BorderTitleBlock::insideBorderRect(), use_border_, xGrid, and yGrid.
drawColoredConductors()
bool Diagram::drawColoredConductors () const inline
Diagram::drawColoredConductors.
Returns
true if conductors colors are rendered, false otherwise.
Definition at line 421 of file diagram.h.
References draw_colored_conductors_.
Referenced by applyProperties().
drawTerminals()
bool Diagram::drawTerminals () const inline
Diagram::drawTerminals.
Returns
true if terminals are rendered, false otherwise
Definition at line 413 of file diagram.h.
References draw_terminals_.
Referenced by applyProperties().
editElementRequired
void Diagram::editElementRequired (const ElementsLocation &) signal
Signal emitted when users wish to edit an element from the diagram.
Referenced by ElementPropertiesWidget::editElement().
elements()
QList< Element * > Diagram::elements () const
Diagram::elements.
Returns
the list containing all elements
Definition at line 2031 of file diagram.cpp.
Referenced by ElementProvider::find(), ElementProvider::freeElement(), freezeElements(), ElementProvider::fromUuids(), refreshContents(), unfreezeElements(), and usesElement().
elementsMover()
ElementsMover & Diagram::elementsMover ()
Diagram::elementsMover.
Returns
Definition at line 2057 of file diagram.cpp.
References m_elements_mover.
Referenced by QetGraphicsItem::mouseMoveEvent(), DiagramTextItem::mouseMoveEvent(), QetGraphicsItem::mouseReleaseEvent(), and DiagramTextItem::mouseReleaseEvent().
elementTextsMover()
ElementTextsMover & Diagram::elementTextsMover ()
Diagram::elementTextsMover.
Returns
Definition at line 2065 of file diagram.cpp.
References m_element_texts_mover.
Referenced by ElementTextItemGroup::mouseMoveEvent(), DynamicElementTextItem::mouseMoveEvent(), and ElementTextItemGroup::mouseReleaseEvent().
findElementRequired
void Diagram::findElementRequired (const ElementsLocation &) signal
Signal emitted when users wish to locate an element from the diagram within elements collection
Referenced by ElementPropertiesWidget::editElement(), and ElementPropertiesWidget::findInPanel().
folioIndex()
int Diagram::folioIndex () const
Diagram::folioIndex.
Returns
the folio number of this diagram within its parent project, or -1 if it is has no parent project
Definition at line 2335 of file diagram.cpp.
References m_project.
Referenced by comparPos(), AutoNumberingManagementW::on_m_apply_folios_rb_clicked(), and ProjectView::updateTabTitle().
folioSequentialsFromXml()
void Diagram::folioSequentialsFromXml (const QDomElement & root, QHash< QString, QStringList > * hash, const QString & folioSeq, const QString & seq, const QString & type, const QString & autonumFolioSeqType)
Diagram::folioSequentialsFromXml Load folio sequential from QDomElement.
Parameters
root containing all folio sequentials
hash : to be loaded with content
folioSeq type
seq type
type of sequential
autonumFolioSeqType
Definition at line 1491 of file diagram.cpp.
References QET::findInDomElement(), and title().
Referenced by fromXml().
folioSequentialsToXml()
void Diagram::folioSequentialsToXml (QHash< QString, QStringList > * hash, QDomElement * domElement, const QString & seq_type, const QString & type, QDomDocument * doc)
Diagram::folioSequentialsToXml Add folio sequential to QDomElement.
Parameters
hash to retrieve content with content
domElement to add attributes
seq_type type
type
doc
Definition at line 980 of file diagram.cpp.
Referenced by toXml().
freezeConductors()
void Diagram::freezeConductors (bool freeze)
Diagram::freezeConductors Freeze every existent conductor label.
Definition at line 2140 of file diagram.cpp.
References conductors(), and Conductor::setFreezeLabel().
freezeElements()
void Diagram::freezeElements (bool freeze)
Diagram::freezeElements Freeze every existent element label.
Definition at line 2104 of file diagram.cpp.
References elements(), and Element::freezeLabel().
freezeNewConductors()
bool Diagram::freezeNewConductors ()
Diagram::freezeNewConductors.
Returns
current freeze new conductor status .
Definition at line 2158 of file diagram.cpp.
References m_freeze_new_conductors_.
Referenced by DiagramEventAddElement::addElement(), and MultiPasteDialog::on_m_button_box_accepted().
freezeNewElements()
bool Diagram::freezeNewElements ()
Diagram::freezeNewElements.
Returns
current freeze new element status .
Definition at line 2132 of file diagram.cpp.
References m_freeze_new_elements.
fromXml() [1/2]
bool Diagram::fromXml (QDomDocument & document, QPointF position = QPointF(), bool consider_informations = true, DiagramContent * content_ptr = nullptr)
Diagram::fromXml Imports the described schema into an XML document. If a position is specified, the imported elements are positioned so that the upper left corner of the smallest rectangle that can surround them all (the bounding rect) is at this position.
Parameters
document : The XML document to analyze
position : The position of the diagram matters
consider_informations : If true, additional information (author, title, ...) will be taken into account
content_ptr : if this pointer to a DiagramContent is different from 0, it will be filled with the content added to the schema by the fromXml
Returns
true if the import was successful, false otherwise
Definition at line 1029 of file diagram.cpp.
Referenced by fromXml(), initFromXml(), DiagramView::paste(), and MultiPasteDialog::updatePreview().
fromXml() [2/2]
bool Diagram::fromXml (QDomElement & document, QPointF position = QPointF(), bool consider_informations = true, DiagramContent * content_ptr = nullptr)
Diagram::fromXml Imports the described schema in an XML element. If a position is specified, the imported elements are positioned in such a way that the upper left corner of the smallest rectangle that can surround them all (the bounding rect) either at this position.
Parameters
document : The XML document to analyze
position : The position of the diagram matters
consider_informations : If true, additional information (author, title, ...) will be taken into account
content_ptr : if this pointer to a DiagramContent is different from 0, it will be filled with the content added to the schema by the fromXml
Returns
true if the import was successful, false otherwise
Definition at line 1180 of file diagram.cpp.
References addItem(), adjustSceneRect(), border_and_titleblock, BorderTitleBlock::borderFromXml(), QET::Icons::Conductor, declaredQElectroTechVersion(), defaultConductorProperties, diagram_qet_version_, QET::findInDomElement(), findTerminal(), folioSequentialsFromXml(), ConductorProperties::fromXml(), Element::fromXml(), fromXml(), ElementCollectionHandler::importFromProject(), ElementFactory::Instance(), Conductor::isValid(), m_cnd_hundredfolio_max, m_cnd_tenfolio_max, m_cnd_unitfolio_max, m_conductors_autonum_name, m_elmt_hundredfolio_max, m_elmt_tenfolio_max, m_elmt_unitfolio_max, m_freeze_new_conductors_, m_freeze_new_elements, m_project, ElementsLocation::path(), QETApp::project(), QETProject::ProjectParsingRunning, removeItem(), snapToGrid(), QETXML::subChild(), BorderTitleBlock::titleBlockFromXml(), Conductor::valideXml(), Element::valideXml(), and QetGraphicsTableItem::xmlTagName().
imageSize()
QSize Diagram::imageSize () const
Diagram::imageSize Allows you to know the dimensions that the image generated by the toImage() method will have.
Returns
The size of the image generated by toImage()
Definition at line 651 of file diagram.cpp.
References border_and_titleblock, BorderTitleBlock::borderAndTitleBlockRect(), margin, and use_border_.
initFromXml()
bool Diagram::initFromXml (QDomElement & document, QPointF position = QPointF(), bool consider_informations = true, DiagramContent * content_ptr = nullptr)
Diagram::initFromXml Imports the described schema in an XML element. This method delegates its work to Diagram :: fromXml If the import is successful, this method also initializes the XML document internal allowing to manage the recording of this diagram in the project to which it belongs.
See also
Diagram::fromXml
Parameters
document : The XML document to analyze
position : The position of the diagram matters
consider_informations : If true, additional information (author, title, ...) will be taken into account
content_ptr : if this pointer to a DiagramContent is different from 0, it will be filled with the content added to the schema by the fromXml
Returns
true if the import was successful, false otherwise
Definition at line 1067 of file diagram.cpp.
References fromXml().
Referenced by QETProject::readDiagramsXml().
insertFolioSeqHash()
void Diagram::insertFolioSeqHash (QHash< QString, QStringList > * hash, const QString & title, const QString & type, NumerotationContext * nc)
Diagram::insertFolioSeqHash This class inserts a stringlist containing all sequential variables related to an autonum in a QHash.
Parameters
hash : to be accessed
title : autonum title
type : to be treated
nc : Context to be manipulated
Definition at line 1733 of file diagram.cpp.
References NumerotationContext::itemAt(), NumerotationContext::replaceValue(), NumerotationContext::size(), and title().
Referenced by loadCndFolioSeq(), and loadElmtFolioSeq().
invertSelection
void Diagram::invertSelection () slot
Diagram::invertSelection Reverses the selection state of all schema objects Inverse l'etat de selection de tous les objets du schema.
Definition at line 1701 of file diagram.cpp.
References isEmpty().
isEmpty()
bool Diagram::isEmpty () const
Diagram::isEmpty An empty schema contains no element, conductor, or text field.
Returns
true if the schema is considered empty, false otherwise.
Definition at line 680 of file diagram.cpp.
Referenced by DiagramView::contextMenuActions(), DiagramView::contextMenuEvent(), deselectAll(), invertSelection(), DiagramEventAddImage::openDialog(), selectAll(), and toXml().
isReadOnly()
bool Diagram::isReadOnly () const
Diagram::isReadOnly.
Returns
true if this diagram is read only. This method is same has call Diagram::project() -> isReadOnly()
Definition at line 2363 of file diagram.cpp.
References m_project.
Referenced by addItem(), keyPressEvent(), keyReleaseEvent(), DiagramEventAddShape::mousePressEvent(), removeItem(), RotateSelectionCommand::RotateSelectionCommand(), QETDiagramEditor::rowColumnGroupTriggered(), and QETDiagramEditor::slot_updateComplexActions().
keyPressEvent()
void Diagram::keyPressEvent (QKeyEvent * event) override protected
Diagram::keyPressEvent This event is managed by diagram event interface if any. Else move selected elements.
Parameters
event
Definition at line 324 of file diagram.cpp.
References DiagramContent::All, ElementsMover::beginMovement(), ElementsMover::continueMovement(), isReadOnly(), DiagramContent::items(), DiagramEventInterface::keyPressEvent(), DiagramContent::m_elements, m_elements_mover, m_event_interface, undoStack(), xKeyGrid, xKeyGridFine, yKeyGrid, and yKeyGridFine.
keyReleaseEvent()
void Diagram::keyReleaseEvent (QKeyEvent * e) override protected
Diagram::keyReleaseEvent This event is managed by diagram event interface if any. Else move selected element.
Parameters
e
Definition at line 479 of file diagram.cpp.
References ElementsMover::endMovement(), isReadOnly(), DiagramEventInterface::keyReleaseEvent(), m_elements_mover, and m_event_interface.
loadCndFolioSeq
void Diagram::loadCndFolioSeq () slot
Diagram::loadCndFolioSeq This class loads all conductor folio sequential variables related to the current autonum.
Definition at line 1942 of file diagram.cpp.
References QETProject::addConductorAutoNum(), QETProject::conductorAutoNum(), QETProject::conductorCurrentAutoNum(), insertFolioSeqHash(), loadFolioSeqHash(), m_cnd_hundredfolio_max, m_cnd_tenfolio_max, m_cnd_unitfolio_max, autonum::numerotationContextToFormula(), project(), and title().
Referenced by Diagram(), DiagramView::DiagramView(), and AutoNumberingDockWidget::on_m_conductor_cb_activated().
loadElmtFolioSeq
void Diagram::loadElmtFolioSeq () slot
Diagram::loadElmtFolioSeq This class loads all folio sequential variables related to the current autonum.
Definition at line 1857 of file diagram.cpp.
References QETProject::addElementAutoNum(), QETProject::elementAutoNum(), QETProject::elementCurrentAutoNum(), insertFolioSeqHash(), loadFolioSeqHash(), m_elmt_hundredfolio_max, m_elmt_tenfolio_max, m_elmt_unitfolio_max, project(), and title().
Referenced by Diagram(), DiagramView::DiagramView(), and AutoNumberingDockWidget::on_m_element_cb_activated().
loadFolioSeqHash()
void Diagram::loadFolioSeqHash (QHash< QString, QStringList > * hash, const QString & title, const QString & type, NumerotationContext * nc)
Diagram::loadFolioSeqHash This class loads all folio sequential variables related to the current autonum.
Parameters
hash : to be accessed
title : autonum title
type : to be treated
nc : Context to be manipulated
Definition at line 1760 of file diagram.cpp.
References NumerotationContext::itemAt(), NumerotationContext::replaceValue(), NumerotationContext::size(), and title().
Referenced by loadCndFolioSeq(), and loadElmtFolioSeq().
mouseDoubleClickEvent()
void Diagram::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Diagram::mouseDoubleClickEvent This event is managed by diagram event interface if any.
Parameters
event :
Definition at line 228 of file diagram.cpp.
References m_event_interface, and DiagramEventInterface::mouseDoubleClickEvent().
mouseMoveEvent()
void Diagram::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
Diagram::mouseMoveEvent This event is managed by diagram event interface if any.
Parameters
event
Definition at line 266 of file diagram.cpp.
References m_event_interface, and DiagramEventInterface::mouseMoveEvent().
mousePressEvent()
void Diagram::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Diagram::mousePressEvent This event is managed by diagram event interface if any.
Parameters
event
Definition at line 247 of file diagram.cpp.
References m_event_interface, and DiagramEventInterface::mousePressEvent().
mouseReleaseEvent()
void Diagram::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Diagram::mouseReleaseEvent This event is managed by diagram event interface if any.
Parameters
event
Definition at line 285 of file diagram.cpp.
References m_event_interface, and DiagramEventInterface::mouseReleaseEvent().
potentials()
QList< QSet< Conductor * > > Diagram::potentials ()
Diagram::potential.
Returns
all potential in the diagram each potential are in the QList and each conductors of one potential are in the QSet
Definition at line 690 of file diagram.cpp.
References DiagramContent::conductors(), conductors(), and content().
project()
QETProject * Diagram::project () const
Diagram::project.
Returns
the project to which this schema belongs or 0 if it is an independent schema.
Definition at line 2326 of file diagram.cpp.
References m_project.
Referenced by MasterElement::aboutDeleteXref(), DiagramEventAddElement::addElement(), autonum::AssignVariables::assignProjectVar(), ElementTextItemGroup::autoPos(), DiagramEventAddElement::buildElement(), QetGraphicsTableFactory::create(), DiagramPropertiesDialog::DiagramPropertiesDialog(), DiagramPropertiesDialog::editAutoFolioNum(), DiagramPropertiesDialog::editAutonum(), CrossRefItem::elementPositionText(), DiagramView::handleTitleBlockDrop(), CrossRefItem::init(), MasterElement::linkToElement(), loadCndFolioSeq(), loadElmtFolioSeq(), ConductorAutoNumerotation::newProperties(), QetGraphicsTableFactory::newTable(), ConductorAutoNumerotation::numerateNewConductor(), MultiPasteDialog::on_m_button_box_accepted(), refreshContents(), DynamicElementTextItem::removeConnectionForReportFormula(), DynamicElementTextItem::reportChanged(), DynamicElementTextItem::reportFormulaChanged(), DynamicElementTextItem::setConnectionForReportFormula(), MasterPropertiesWidget::setElement(), ElementTextItemGroup::setHoldToBottomPage(), DynamicElementTextItem::setPlainText(), CrossRefItem::setUpConnection(), Element::setUpFormula(), DynamicElementTextItem::setupFormulaConnection(), undoStack(), ChangeElementInformationCommand::updateProjectDB(), CrossRefItem::updateProperties(), DynamicElementTextItem::updateXref(), ElementTextItemGroup::updateXref(), and MasterElement::xrefPropertiesChanged().
qgiManager()
QGIManager & Diagram::qgiManager () inline
Diagram::qgiManager.
Returns
the diagram graphics item manager
Definition at line 405 of file diagram.h.
References qgi_manager_.
Referenced by DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), and DeleteQGraphicsItemCommand::~DeleteQGraphicsItemCommand().
refreshContents()
void Diagram::refreshContents ()
Diagram::refreshContents refresh all content of diagram.
refresh conductor text.
linking the elements waiting to be linked
Refresh the connection of the dynamic element text item (use for text with source of text label)
Definition at line 1526 of file diagram.cpp.
References conductors(), elements(), project(), and ElementProvider::table().
removeItem()
void Diagram::removeItem (QGraphicsItem * item) virtual
Diagram::removeItem Reimplemented from QGraphicsScene::removeItem(QGraphicsItem *item) Do some specific operation if item need it (for exemple an element)
Parameters
item
Definition at line 1581 of file diagram.cpp.
References QETProject::dataBase(), isReadOnly(), m_project, Terminal::removeConductor(), projectDataBase::removeElement(), Conductor::terminal1, Conductor::terminal2, Conductor::Type, Element::Type, and Element::unlinkAllElements().
Referenced by fromXml(), DiagramEventAddElement::mouseDoubleClickEvent(), DiagramEventAddShape::mouseReleaseEvent(), DiagramEventAddElement::mouseReleaseEvent(), DeleteQGraphicsItemCommand::redo(), PasteDiagramCommand::undo(), MultiPasteDialog::updatePreview(), DiagramEventAddElement::~DiagramEventAddElement(), DiagramEventAddImage::~DiagramEventAddImage(), DiagramEventAddShape::~DiagramEventAddShape(), and MultiPasteDialog::~MultiPasteDialog().
selectAll
void Diagram::selectAll () slot
Diagram::selectAll Select all schema objects.
Definition at line 1676 of file diagram.cpp.
References isEmpty().
selectedConductors()
QSet< Conductor * > Diagram::selectedConductors () const
Diagram::selectedConductors.
Returns
the list of conductors selected on the diagram
Definition at line 2297 of file diagram.cpp.
Referenced by QETDiagramEditor::slot_updateComplexActions().
setBorderOptions()
void Diagram::setBorderOptions (Diagram::BorderOptions bo) inline
Diagram::setBorderOptions Set the rendering options for the diagram border (including rows/colums headers and the title block)
Parameters
bo Enabled options ORed together
See also
BorderOptions
Definition at line 373 of file diagram.h.
References border_and_titleblock, Columns, BorderTitleBlock::displayBorder(), BorderTitleBlock::displayColumns(), BorderTitleBlock::displayTitleBlock(), EmptyBorder, and TitleBlock.
setConductor()
void Diagram::setConductor (bool adding) inline
Diagram::setConductor Display or hide the conductor setter, i.e. a dashed conductor stub which appears when creating a conductor between two terminals.
Parameters
adding true add conductor ,false remove conductor
Definition at line 300 of file diagram.h.
setConductorsAutonumName()
void Diagram::setConductorsAutonumName (const QString & name)
Diagram::setConductorsAutonumName.
Parameters
name : name of autonum to use.
Definition at line 572 of file diagram.cpp.
References m_conductors_autonum_name.
Referenced by DiagramPropertiesDialog::DiagramPropertiesDialog(), and AutoNumberingDockWidget::on_m_conductor_cb_activated().
setConductorStart()
void Diagram::setConductorStart (QPointF start) inline
Diagram::setConductorStart Set the start point of the conductor setter.
Parameters
start the point (in scene coordinates) which the newly created conductor should start from.
Definition at line 314 of file diagram.h.
References conductor_setter_.
setConductorStop()
void Diagram::setConductorStop (QPointF end) inline
Diagram::setConductorStop Set the end point of the conductor setter.
Parameters
end the point (in scene coordinates) upon to which the newly created conductor should be drawn.
Definition at line 324 of file diagram.h.
References conductor_setter_.
setDisplayGrid()
void Diagram::setDisplayGrid (bool dg) inline
Diagram::setDisplayGrid Set whether the diagram grid should be drawn.
Parameters
dg true to render the grid, false otherwise.
Definition at line 333 of file diagram.h.
References draw_grid_.
Referenced by DiagramView::adjustGridToZoom(), and applyProperties().
setDrawColoredConductors()
void Diagram::setDrawColoredConductors (bool dcc)
Diagram::setDrawColoredConductors Defines whether or not to respect the colors of the conductors. If not, the conductors are all drawn in black.
Parameters
dcc true to respect the colors, false otherwise
Definition at line 2288 of file diagram.cpp.
References draw_colored_conductors_.
Referenced by applyProperties().
setDrawTerminals()
void Diagram::setDrawTerminals (bool dt)
Diagram::setDrawTerminals Defines whether or not to display the terminals.
Parameters
dt : true to display the bounds, false otherwise
Definition at line 2271 of file diagram.cpp.
Referenced by applyProperties().
setEventInterface()
void Diagram::setEventInterface (DiagramEventInterface * event_interface)
Diagram::setEventInterface Set event_interface has current interface. Diagram become the ownership of event_interface If there is a previous interface, they will be delete before and call init() to the new interface.
Parameters
event_interface
Definition at line 531 of file diagram.cpp.
References DiagramEventInterface::finish(), and m_event_interface.
Referenced by QETDiagramEditor::addItemGroupTriggered(), and DiagramView::handleElementDrop().
setFreezeNewConductors()
void Diagram::setFreezeNewConductors (bool b)
Diagram::setfreezeNewConductors Set new conductor label to be frozen.
Definition at line 2150 of file diagram.cpp.
References m_freeze_new_conductors_.
setFreezeNewElements()
void Diagram::setFreezeNewElements (bool b)
Diagram::freezeNewElements Set new element label to be frozen.
Definition at line 2124 of file diagram.cpp.
References m_freeze_new_elements.
setTitleBlockTemplate
void Diagram::setTitleBlockTemplate (const QString & template_name) slot
Diagram::setTitleBlockTemplate Set the template to use to render the title block of this diagram.
Parameters
template_name Name of the title block template.
Definition at line 1656 of file diagram.cpp.
References border_and_titleblock, QETProject::embeddedTitleBlockTemplatesCollection(), TitleBlockTemplatesProjectCollection::getTemplate(), m_project, BorderTitleBlock::titleBlockTemplateName(), BorderTitleBlock::titleBlockTemplateRemoved(), and usedTitleBlockTemplateChanged().
Referenced by Diagram().
setUseBorder()
void Diagram::setUseBorder (bool ub) inline
Diagram::setUseBorder Set whether the diagram border (including rows/colums headers and the title block) should be rendered along with the diagram. When set to false, the size of the smallest rectangle containing all items is considered as the diagram size.
Parameters
ub true to take the border into account, false otherwise
Definition at line 353 of file diagram.h.
References use_border_.
Referenced by applyProperties().
showDiagram
void Diagram::showDiagram (Diagram *) signal
Referenced by showMe().
showMe()
void Diagram::showMe () inline
Definition at line 161 of file diagram.h.
References showDiagram().
Referenced by CrossRefItem::mouseDoubleClickEvent(), ElementTextItemGroup::mouseDoubleClickEvent(), LinkSingleElementWidget::on_m_show_linked_pb_clicked(), LinkSingleElementWidget::on_m_tree_widget_itemDoubleClicked(), RotateSelectionCommand::redo(), LinkElementCommand::redo(), RotateSelectionCommand::undo(), DeleteQGraphicsItemCommand::undo(), LinkElementCommand::undo(), and DynamicElementTextItem::zoomToLinkedElement().
snapToGrid()
QPointF Diagram::snapToGrid (const QPointF & p) static
Diagram::snapToGrid Return a nearest snap point of p.
Parameters
p point to find the nearest snaped point
Returns
Definition at line 2240 of file diagram.cpp.
References xGrid, and yGrid.
Referenced by ElementTextsMover::continueMovement(), fromXml(), QetGraphicsTableItem::handlerMouseMoveEvent(), QetShapeItem::handlerMouseMoveEvent(), Conductor::handlerMouseMoveEvent(), QetShapeItem::insertPoint(), DiagramEventAddShape::mouseMoveEvent(), DiagramEventAddElement::mouseMoveEvent(), ConductorTextItem::mouseMoveEvent(), ElementTextItemGroup::mouseMoveEvent(), DiagramTextItem::mouseMoveEvent(), DynamicElementTextItem::mouseMoveEvent(), DiagramEventAddShape::mousePressEvent(), DiagramEventAddShape::mouseReleaseEvent(), QetShapeItem::setNextPoint(), QetGraphicsItem::setPos(), and DiagramEventAddShape::updateHelpCross().
title()
QString Diagram::title () const
Diagram::title.
Returns
title of the titleblock
Definition at line 2023 of file diagram.cpp.
References border_and_titleblock, and BorderTitleBlock::title().
Referenced by folioSequentialsFromXml(), insertFolioSeqHash(), loadCndFolioSeq(), loadElmtFolioSeq(), loadFolioSeqHash(), AutoNumberingManagementW::on_m_apply_folios_rb_clicked(), FolioAutonumberingW::on_m_autonumber_tabs_rb_clicked(), QETProject::readDiagramsXml(), titleChanged(), and ProjectView::updateTabTitle().
titleBlockTemplateChanged
void Diagram::titleBlockTemplateChanged (const QString & template_name) slot
Diagram::titleBlockTemplateChanged This slot may be used to inform the diagram object that the given title block template has changed. The diagram will thus flush its title block-dedicated rendering cache.
Parameters
template_name Name of the title block template that has changed
Definition at line 1622 of file diagram.cpp.
References border_and_titleblock, BorderTitleBlock::titleBlockTemplateChanged(), and BorderTitleBlock::titleBlockTemplateName().
titleBlockTemplateRemoved
void Diagram::titleBlockTemplateRemoved (const QString & template_name, const QString & new_template = QString()) slot
Diagram::titleBlockTemplateRemoved This slot has to be be used to inform this class that the given title block template is about to be removed and is no longer accessible. This class will either use the provided optional TitleBlockTemplate or the default title block provided by QETApp::defaultTitleBlockTemplate()
Parameters
template_name Name of the title block template that has changed
new_template (Optional) Name of the title block template to use instead
Definition at line 1639 of file diagram.cpp.
References border_and_titleblock, QETProject::embeddedTitleBlockTemplatesCollection(), TitleBlockTemplatesProjectCollection::getTemplate(), m_project, BorderTitleBlock::titleBlockTemplateName(), and BorderTitleBlock::titleBlockTemplateRemoved().
titleChanged
void Diagram::titleChanged (const QString & title) slot
Diagram::titleChanged emit(diagramTitleChanged(this, title));.
Parameters
title
Definition at line 1611 of file diagram.cpp.
References diagramTitleChanged(), and title().
Referenced by Diagram().
toPaintDevice()
bool Diagram::toPaintDevice (QPaintDevice & pix, int width = -1, int height = -1, Qt::AspectRatioMode aspectRatioMode = Qt::KeepAspectRatio)
Exporte le schema vers une image
Returns
Une QImage representant le schema
Definition at line 580 of file diagram.cpp.
References border_and_titleblock, BorderTitleBlock::borderAndTitleBlockRect(), margin, and use_border_.
toXml()
QDomDocument Diagram::toXml (bool whole_content = true)
Diagram::toXml Exports all or part of the schema.
Parameters
whole_content : Boolean (to true by default) indicating if the generated XML must represent the entire schema or only the selected content
Returns
An XML Document (QDomDocument)
Definition at line 721 of file diagram.cpp.
References border_and_titleblock, BorderTitleBlock::borderToXml(), defaultConductorProperties, folioSequentialsToXml(), isEmpty(), m_cnd_hundredfolio_max, m_cnd_tenfolio_max, m_cnd_unitfolio_max, m_conductors_autonum_name, m_elmt_hundredfolio_max, m_elmt_tenfolio_max, m_elmt_unitfolio_max, m_freeze_new_conductors_, m_freeze_new_elements, m_project, QETApp::projectId(), BorderTitleBlock::titleBlockToXml(), ConductorProperties::toXml(), IndependentTextItem::Type, DiagramImageItem::Type, QetGraphicsTableItem::Type, QetShapeItem::Type, Conductor::Type, Element::Type, and QET::version.
Referenced by MultiPasteDialog::MultiPasteDialog().
undoStack()
QUndoStack & Diagram::undoStack () inline
Diagram::undoStack.
Returns
the diagram undo stack
Definition at line 397 of file diagram.h.
References project(), and QETProject::undoStack().
Referenced by ImagePropertiesWidget::apply(), IndiTextPropertiesWidget::apply(), ShapeGraphicsItemPropertiesWidget::apply(), ImportElementTextPattern::apply(), ConductorAutoNumerotation::applyText(), changeZValue(), ConductorCreator::ConductorCreator(), Conductor::displayedTextChanged(), ElementTextsMover::endMovement(), IndependentTextItem::focusOutEvent(), QetGraphicsTableItem::handlerMouseReleaseEvent(), QetShapeItem::handlerMouseReleaseEvent(), DiagramView::handleTitleBlockDrop(), QetShapeItem::insertPoint(), ElementTextItemGroup::keyPressEvent(), keyPressEvent(), DiagramEventAddShape::mouseDoubleClickEvent(), DiagramEventAddShape::mousePressEvent(), PotentialSelectorDialog::on_buttonBox_accepted(), MultiPasteDialog::on_m_button_box_accepted(), ConductorPropertiesDialog::PropertiesDialog(), QetShapeItem::removePoint(), QETDiagramEditor::rowColumnGroupTriggered(), QETDiagramEditor::selectionGroupTriggered(), and ~Diagram().
unfreezeElements()
void Diagram::unfreezeElements ()
Diagram::unfreezeElements Unfreeze every existent element label.
Definition at line 2114 of file diagram.cpp.
References elements(), and Element::freezeLabel().
updateLabels
void Diagram::updateLabels () slot
Diagram::updateLabels Update elements and conductors that reference folio field in their labels.
Definition at line 1716 of file diagram.cpp.
References conductors(), and content().
Referenced by Diagram().
useBorder()
bool Diagram::useBorder () inline
Diagram::useBorder.
Returns
use_border_ true if the border is rendered and take into account, false otherwise.
Definition at line 362 of file diagram.h.
References use_border_.
Referenced by applyProperties().
usedTitleBlockTemplateChanged
void Diagram::usedTitleBlockTemplateChanged (const QString &) signal
Referenced by QETProject::addDiagram(), and setTitleBlockTemplate().
usesElement()
bool Diagram::usesElement (const ElementsLocation & location)
Diagram::usesElement Used to find out if an element is used on a schema.
Parameters
location : Location of an element
Returns
true if the location element is used on this schema, false otherwise
Definition at line 2080 of file diagram.cpp.
References elements().
usesTitleBlockTemplate()
bool Diagram::usesTitleBlockTemplate (const QString & name)
Diagram::usesTitleBlockTemplate.
Parameters
name : a title block template name
Returns
true if the provided template is used by this diagram, false otherwise.
Definition at line 2096 of file diagram.cpp.
References border_and_titleblock, and BorderTitleBlock::titleBlockTemplateName().
uuid()
QUuid Diagram::uuid ()
Diagram::uuid.
Returns
the uuid of this diagram
Definition at line 519 of file diagram.cpp.
References m_uuid.
Referenced by projectDataBase::addDiagram(), projectDataBase::addElement(), and projectDataBase::removeDiagram().
wheelEvent()
void Diagram::wheelEvent (QGraphicsSceneWheelEvent * event) override protected
Diagram::wheelEvent This event is managed by diagram event interface if any.
Parameters
event
Definition at line 304 of file diagram.cpp.
References m_event_interface, and DiagramEventInterface::wheelEvent().
Member Data Documentation
background_color
QColor Diagram::background_color = Qt::white static
background color of diagram
Diagram::background_color static variable to keep track of present background color of the diagram.
Definition at line 99 of file diagram.h.
Referenced by DiagramPrintDialog::DiagramPrintDialog(), drawBackground(), Terminal::paint(), QETDiagramEditor::setUpActions(), DiagramEventAddShape::updateHelpCross(), and DiagramPrintDialog::~DiagramPrintDialog().
border_and_titleblock
BorderTitleBlock Diagram::border_and_titleblock
Diagram dimensions and title block.
Definition at line 83 of file diagram.h.
Referenced by projectDataBase::addDiagram(), QETProject::addDiagram(), QETProject::addNewDiagram(), adjustSceneRect(), QetGraphicsTableItem::adjustTableToFolio(), applyProperties(), autonum::AssignVariables::assignTitleBlockVar(), borderOptions(), convertPosition(), Diagram(), drawBackground(), fromXml(), DiagramView::handleTitleBlockDrop(), imageSize(), DynamicElementTextItem::removeConnectionForReportFormula(), SearchAndReplaceWorker::replaceAdvanced(), QETDiagramEditor::rowColumnGroupTriggered(), SearchAndReplaceWidget::searchTerms(), setBorderOptions(), DynamicElementTextItem::setConnectionForReportFormula(), AutoNumberingDockWidget::setProject(), setTitleBlockTemplate(), DynamicElementTextItem::setupFormulaConnection(), title(), titleBlockTemplateChanged(), titleBlockTemplateRemoved(), toPaintDevice(), toXml(), GenericPanel::updateDiagramItem(), DiagramEventAddShape::updateHelpCross(), ProjectView::updateTabTitle(), and usesTitleBlockTemplate().
conductor_setter_
QGraphicsLineItem* Diagram::conductor_setter_ private
Definition at line 110 of file diagram.h.
Referenced by Diagram(), setConductorStart(), setConductorStop(), and ~Diagram().
defaultConductorProperties
ConductorProperties Diagram::defaultConductorProperties
Default properties for new conductors.
Definition at line 81 of file diagram.h.
Referenced by QETProject::addNewDiagram(), Conductor::Conductor(), fromXml(), and toXml().
diagram_qet_version_
qreal Diagram::diagram_qet_version_ private
Definition at line 118 of file diagram.h.
Referenced by declaredQElectroTechVersion(), and fromXml().
DiagramFolioList
friend Diagram::DiagramFolioList private
Definition at line 57 of file diagram.h.
draw_colored_conductors_
bool Diagram::draw_colored_conductors_ private
Definition at line 123 of file diagram.h.
Referenced by drawColoredConductors(), and setDrawColoredConductors().
draw_grid_
bool Diagram::draw_grid_ private
Definition at line 120 of file diagram.h.
Referenced by displayGrid(), drawBackground(), and setDisplayGrid().
draw_terminals_
bool Diagram::draw_terminals_ private
Definition at line 122 of file diagram.h.
Referenced by drawTerminals().
m_cnd_hundredfolio_max
QHash<QString, QStringList> Diagram::m_cnd_hundredfolio_max
Definition at line 107 of file diagram.h.
Referenced by fromXml(), loadCndFolioSeq(), and toXml().
m_cnd_tenfolio_max
QHash<QString, QStringList> Diagram::m_cnd_tenfolio_max
Definition at line 106 of file diagram.h.
Referenced by fromXml(), loadCndFolioSeq(), and toXml().
m_cnd_unitfolio_max
QHash<QString, QStringList> Diagram::m_cnd_unitfolio_max
Hash containing max values for folio sequential autonums in this diagram.
Definition at line 105 of file diagram.h.
Referenced by fromXml(), loadCndFolioSeq(), and toXml().
m_conductors_autonum_name
QString Diagram::m_conductors_autonum_name private
Definition at line 125 of file diagram.h.
Referenced by conductorsAutonumName(), fromXml(), setConductorsAutonumName(), and toXml().
m_element_texts_mover
ElementTextsMover Diagram::m_element_texts_mover private
Definition at line 112 of file diagram.h.
Referenced by elementTextsMover().
m_elements_mover
ElementsMover Diagram::m_elements_mover private
Definition at line 111 of file diagram.h.
Referenced by elementsMover(), keyPressEvent(), and keyReleaseEvent().
m_elmt_hundredfolio_max
QHash<QString, QStringList> Diagram::m_elmt_hundredfolio_max
Definition at line 103 of file diagram.h.
Referenced by fromXml(), loadElmtFolioSeq(), autonum::setSequential(), and toXml().
m_elmt_tenfolio_max
QHash<QString, QStringList> Diagram::m_elmt_tenfolio_max
Definition at line 102 of file diagram.h.
Referenced by fromXml(), loadElmtFolioSeq(), autonum::setSequential(), and toXml().
m_elmt_unitfolio_max
QHash<QString, QStringList> Diagram::m_elmt_unitfolio_max
Hash containing max values for folio sequential autonums in this diagram.
Definition at line 101 of file diagram.h.
Referenced by fromXml(), loadElmtFolioSeq(), autonum::setSequential(), and toXml().
m_event_interface
DiagramEventInterface* Diagram::m_event_interface private
Definition at line 126 of file diagram.h.
Referenced by clearEventInterface(), keyPressEvent(), keyReleaseEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), setEventInterface(), wheelEvent(), and ~Diagram().
m_freeze_new_conductors_
bool Diagram::m_freeze_new_conductors_ private
Definition at line 129 of file diagram.h.
Referenced by freezeNewConductors(), fromXml(), setFreezeNewConductors(), and toXml().
m_freeze_new_elements
bool Diagram::m_freeze_new_elements private
Definition at line 128 of file diagram.h.
Referenced by freezeNewElements(), fromXml(), setFreezeNewElements(), and toXml().
m_project
QETProject* Diagram::m_project private
Definition at line 114 of file diagram.h.
Referenced by addItem(), declaredQElectroTechVersion(), folioIndex(), fromXml(), isReadOnly(), project(), removeItem(), setTitleBlockTemplate(), titleBlockTemplateRemoved(), and toXml().
m_uuid
QUuid Diagram::m_uuid = QUuid::createUuid() private
Definition at line 130 of file diagram.h.
Referenced by uuid().
margin
const qreal Diagram::margin = 5.0 static
margin around the diagram
Definition at line 97 of file diagram.h.
Referenced by DiagramView::adjustSceneRect(), BorderTitleBlock::columnsRect(), ExportDialog::generateDxf(), imageSize(), BorderTitleBlock::insideBorderRect(), BorderTitleBlock::outsideBorderRect(), BorderTitleBlock::rowsRect(), toPaintDevice(), and BorderTitleBlock::updateRectangles().
QETProject
friend Diagram::QETProject private
Definition at line 58 of file diagram.h.
qgi_manager_
QGIManager* Diagram::qgi_manager_ private
Definition at line 113 of file diagram.h.
Referenced by Diagram(), qgiManager(), and ~Diagram().
use_border_
bool Diagram::use_border_ private
Definition at line 121 of file diagram.h.
Referenced by drawBackground(), imageSize(), setUseBorder(), toPaintDevice(), and useBorder().
xGrid
int Diagram::xGrid = 10 static
abscissa grid step size
Definition at line 85 of file diagram.h.
Referenced by drawBackground(), Conductor::generateConductorPath(), and snapToGrid().
xKeyGrid
int Diagram::xKeyGrid = 10 static
Key grid x step size.
Definition at line 89 of file diagram.h.
Referenced by keyPressEvent().
xKeyGridFine
int Diagram::xKeyGridFine = 1 static
Key grid fine x step size.
Definition at line 93 of file diagram.h.
Referenced by keyPressEvent().
xml_document_
QDomDocument Diagram::xml_document_ private
Definition at line 116 of file diagram.h.
yGrid
int Diagram::yGrid = 10 static
ordinate grid step size
Definition at line 87 of file diagram.h.
Referenced by drawBackground(), Conductor::generateConductorPath(), and snapToGrid().
yKeyGrid
int Diagram::yKeyGrid = 10 static
Key grid y step size.
Definition at line 91 of file diagram.h.
Referenced by keyPressEvent().
yKeyGridFine
int Diagram::yKeyGridFine = 1 static
Key grid fine y step size.
Definition at line 95 of file diagram.h.
Referenced by keyPressEvent().
The documentation for this class was generated from the following files:
diagram.h
diagram.cpp