QElectroTech: SingleLineProperties Class Reference
SingleLineProperties Class Reference
The SingleLineProperties class This class represents the properties of a singleline conductor.
#include <conductorproperties.h>
Public Member Functions
SingleLineProperties ()
virtual ~SingleLineProperties ()
Destructeur.
void setPhasesCount (int)
unsigned short int phasesCount ()
bool isPen () const
void draw (QPainter *, QET::ConductorSegmentType, const QRectF &)
void toXml (QDomElement &) const
void fromXml (QDomElement &)
void toSettings (QSettings &, const QString &=QString()) const
void fromSettings (QSettings &, const QString &=QString())
int operator== (const SingleLineProperties &) const
int operator!= (const SingleLineProperties &) const
Public Attributes
bool hasGround
Whether the singleline conductor should display the ground symbol.
bool hasNeutral
Whether the singleline conductor should display the neutral symbol.
bool is_pen
Protective Earth Neutral: visually merge neutral and ground.
Private Member Functions
void drawGround (QPainter *, QET::ConductorSegmentType, QPointF, qreal)
void drawNeutral (QPainter *, QET::ConductorSegmentType, QPointF, qreal)
void drawPen (QPainter *, QET::ConductorSegmentType, QPointF, qreal)
SingleLineProperties::drawPen Draw the PEN (Protective Earth Neutral) symbol using painter at position center, using a size hint of size.
Private Attributes
unsigned short int phases
Detailed Description
The SingleLineProperties class This class represents the properties of a singleline conductor.
Definition at line 31 of file conductorproperties.h.
Constructor & Destructor Documentation
SingleLineProperties()
SingleLineProperties::SingleLineProperties ()
Constructeur par defaut
Definition at line 25 of file conductorproperties.cpp.
~SingleLineProperties()
SingleLineProperties::~SingleLineProperties () virtual
Destructeur.
Definition at line 34 of file conductorproperties.cpp.
Member Function Documentation
draw()
void SingleLineProperties::draw (QPainter * painter, QET::ConductorSegmentType direction, const QRectF & rect)
Dessine les symboles propres a un conducteur unifilaire
Parameters
painter QPainter a utiliser pour dessiner les symboles
direction direction du segment sur lequel les symboles apparaitront
rect rectangle englobant le dessin ; utilise pour specifier a la fois la position et la taille du dessin
Definition at line 65 of file conductorproperties.cpp.
References drawGround(), drawNeutral(), drawPen(), hasGround, hasNeutral, QET::Horizontal, isPen(), and phases.
Referenced by Conductor::paint(), ReplaceConductorDialog::updatePreview(), and ConductorPropertiesWidget::updatePreview().
drawGround()
void SingleLineProperties::drawGround (QPainter * painter, QET::ConductorSegmentType direction, QPointF center, qreal size) private
Dessine le segment correspondant au symbole de la terre sur un conducteur unifilaire
Parameters
painter QPainter a utiliser pour dessiner le segment
direction direction du segment sur lequel le symbole apparaitra
center centre du segment
size taille du segment
Definition at line 121 of file conductorproperties.cpp.
References QET::Horizontal.
Referenced by draw(), and drawPen().
drawNeutral()
void SingleLineProperties::drawNeutral (QPainter * painter, QET::ConductorSegmentType direction, QPointF center, qreal size) private
Dessine le cercle correspondant au symbole du neutre sur un conducteur unifilaire
Parameters
painter QPainter a utiliser pour dessiner le segment
direction direction du segment sur lequel le symbole apparaitra
center centre du cercle
size diametre du cercle
Definition at line 156 of file conductorproperties.cpp.
Referenced by draw(), and drawPen().
drawPen()
void SingleLineProperties::drawPen (QPainter * painter, QET::ConductorSegmentType direction, QPointF center, qreal size) private
SingleLineProperties::drawPen Draw the PEN (Protective Earth Neutral) symbol using painter at position center, using a size hint of size.
Parameters
painter
direction : Indicate the direction of the underlying conductor segment
center
size
Definition at line 188 of file conductorproperties.cpp.
References drawGround(), drawNeutral(), and QET::Horizontal.
Referenced by draw().
fromSettings()
void SingleLineProperties::fromSettings (QSettings & settings, const QString & prefix = QString())
Parameters
settings Parametres a lire
prefix prefix a ajouter devant les noms des parametres
Definition at line 853 of file conductorproperties.cpp.
References hasGround, hasNeutral, is_pen, and phases.
Referenced by ConductorProperties::fromSettings().
fromXml()
void SingleLineProperties::fromXml (QDomElement & e)
Importe les parametres du conducteur unifilaire a partir des attributs XML de l'element e
Parameters
e Element XML dont les attributs seront lus
Definition at line 227 of file conductorproperties.cpp.
References hasGround, hasNeutral, is_pen, and setPhasesCount().
Referenced by ConductorProperties::fromXml().
isPen()
bool SingleLineProperties::isPen () const
Returns
true if the singleline conductor should be drawn using the PEN (Protective Earth Neutral) representation and if it features the ground and the neutral.
Definition at line 55 of file conductorproperties.cpp.
References hasGround, hasNeutral, and is_pen.
Referenced by draw(), ReplaceConductorDialog::setProperties(), ConductorPropertiesWidget::setProperties(), and toXml().
operator!=()
int SingleLineProperties::operator!= (const SingleLineProperties & other) const
Parameters
other l'autre ensemble de proprietes avec lequel il faut effectuer la comparaison
Returns
true si les deux ensembles de proprietes sont differents, false sinon
Definition at line 833 of file conductorproperties.cpp.
operator==()
int SingleLineProperties::operator== (const SingleLineProperties & other) const
Parameters
other l'autre ensemble de proprietes avec lequel il faut effectuer la comparaison
Returns
true si les deux ensembles de proprietes sont identiques, false sinon
Definition at line 820 of file conductorproperties.cpp.
References hasGround, hasNeutral, is_pen, and phases.
phasesCount()
unsigned short int SingleLineProperties::phasesCount ()
Returns
le nombre de phases (0, 1, 2, ou 3)
Definition at line 46 of file conductorproperties.cpp.
References phases.
Referenced by ConductorPropertiesWidget::setProperties(), and ReplaceConductorDialog::setProperties().
setPhasesCount()
void SingleLineProperties::setPhasesCount (int n)
Definit le nombre de phases (0, 1, 2, ou 3)
Parameters
n Nombre de phases
Definition at line 41 of file conductorproperties.cpp.
References phases.
Referenced by fromXml(), ReplaceConductorDialog::properties(), and ConductorPropertiesWidget::properties().
toSettings()
void SingleLineProperties::toSettings (QSettings & settings, const QString & prefix = QString()) const
Parameters
settings Parametres a ecrire
prefix prefix a ajouter devant les noms des parametres
Definition at line 841 of file conductorproperties.cpp.
References hasGround, hasNeutral, is_pen, and phases.
Referenced by ConductorProperties::toSettings().
toXml()
void SingleLineProperties::toXml (QDomElement & e) const
Exporte les parametres du conducteur unifilaire sous formes d'attributs XML ajoutes a l'element e.
Parameters
e Element XML auquel seront ajoutes des attributs
Definition at line 215 of file conductorproperties.cpp.
References hasGround, hasNeutral, isPen(), and phases.
Referenced by ConductorProperties::toXml().
Member Data Documentation
hasGround
bool SingleLineProperties::hasGround
Whether the singleline conductor should display the ground symbol.
Definition at line 46 of file conductorproperties.h.
Referenced by draw(), fromSettings(), fromXml(), isPen(), operator==(), ConductorPropertiesWidget::properties(), ReplaceConductorDialog::properties(), ReplaceConductorDialog::setProperties(), ConductorPropertiesWidget::setProperties(), toSettings(), and toXml().
hasNeutral
bool SingleLineProperties::hasNeutral
Whether the singleline conductor should display the neutral symbol.
Definition at line 48 of file conductorproperties.h.
Referenced by draw(), fromSettings(), fromXml(), isPen(), operator==(), ConductorPropertiesWidget::properties(), ReplaceConductorDialog::properties(), ReplaceConductorDialog::setProperties(), ConductorPropertiesWidget::setProperties(), toSettings(), and toXml().
is_pen
bool SingleLineProperties::is_pen
Protective Earth Neutral: visually merge neutral and ground.
Definition at line 50 of file conductorproperties.h.
Referenced by fromSettings(), fromXml(), isPen(), operator==(), ConductorPropertiesWidget::properties(), ReplaceConductorDialog::properties(), and toSettings().
phases
unsigned short int SingleLineProperties::phases private
Definition at line 56 of file conductorproperties.h.
Referenced by draw(), fromSettings(), operator==(), phasesCount(), setPhasesCount(), toSettings(), and toXml().
The documentation for this class was generated from the following files:
conductorproperties.h
conductorproperties.cpp