QElectroTech: MasterPropertiesWidget Class Reference
MasterPropertiesWidget Class Reference
The MasterPropertiesWidget class This class is a widget for make link between a master element with several slave element. This class embenddedthe undo/redo command when apply new connection.
#include <masterpropertieswidget.h>
Public Slots
void updateUi () override
MasterPropertiesWidget::updateUi Build the interface of the widget.
Public Member Functions
MasterPropertiesWidget (Element *elmt, QWidget *parent=nullptr)
MasterPropertiesWidget::MasterPropertiesWidget Default constructor.
~MasterPropertiesWidget () override
MasterPropertiesWidget::~MasterPropertiesWidget Destructor.
void setElement (Element *element) override
MasterPropertiesWidget::setElement Set the element to be edited.
void apply () override
MasterPropertiesWidget::apply If link betwen edited element and other change, apply the change with a QUndoCommand (got with method associatedUndo) pushed to the stack of element project. Return true if link change, else false.
void reset () override
MasterPropertiesWidget::reset Reset curent widget, clear eveything and rebuild widget.
QUndoCommand * associatedUndo () const override
MasterPropertiesWidget::associatedUndo If link between the edited element and other change, return a QUndoCommand with this change. If no change return nullptr.
QString title () const override
title
bool setLiveEdit (bool live_edit) override
MasterPropertiesWidget::setLiveEdit.
Public Member Functions inherited from AbstractElementPropertiesEditorWidget
AbstractElementPropertiesEditorWidget (QWidget *parent=nullptr)
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual void updateUi ()
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Private Slots
void headerCustomContextMenuRequested (const QPoint &pos)
MasterPropertiesWidget::headerCustomContextMenuRequested.
void on_link_button_clicked ()
MasterPropertiesWidget::on_link_button_clicked move curent item in the free_list to linked_list.
void on_unlink_button_clicked ()
MasterPropertiesWidget::on_unlink_button_clicked move curent item in linked_list to free_list.
void showElementFromTWI (QTreeWidgetItem *qtwi, int column)
MasterPropertiesWidget::showElementFromTWI Show the element corresponding to the given QTreeWidgetItem.
void showedElementWasDeleted ()
MasterPropertiesWidget::showedElementWasDeleted Set to nullptr the current showed element when he was deleted.
void diagramWasdeletedFromProject ()
MasterPropertiesWidget::diagramWasdeletedFromProject This slot is called when a diagram is removed from the parent project of edited element to update the content of this widget.
void customContextMenu (const QPoint &pos, int i=0)
MasterPropertiesWidget::customContextMenu Display a context menu.
Private Attributes
Ui::MasterPropertiesWidget * ui
QHash< QTreeWidgetItem *, Element * > m_qtwi_hash
QTreeWidgetItem * m_qtwi_at_context_menu = nullptr
QPointer< Element > m_showed_element
QETProject * m_project
QMenu * m_context_menu
QAction * m_link_action
QAction * m_unlink_action
QAction * m_show_qtwi
QAction * m_show_element
QAction * m_save_header_state
Additional Inherited Members
Protected Member Functions inherited from PropertiesEditorWidget
virtual void enableLiveEdit ()
virtual void disableLiveEdit ()
Protected Attributes inherited from AbstractElementPropertiesEditorWidget
QPointer< Element > m_element
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
The MasterPropertiesWidget class This class is a widget for make link between a master element with several slave element. This class embenddedthe undo/redo command when apply new connection.
Definition at line 43 of file masterpropertieswidget.h.
Constructor & Destructor Documentation
MasterPropertiesWidget()
MasterPropertiesWidget::MasterPropertiesWidget (Element * elmt, QWidget * parent = nullptr) explicit
MasterPropertiesWidget::MasterPropertiesWidget Default constructor.
Parameters
elmt
parent
Definition at line 33 of file masterpropertieswidget.cpp.
References headerCustomContextMenuRequested(), m_context_menu, AbstractElementPropertiesEditorWidget::m_element, m_link_action, m_qtwi_at_context_menu, m_save_header_state, m_show_element, m_show_qtwi, m_showed_element, m_unlink_action, on_link_button_clicked(), on_unlink_button_clicked(), setElement(), showElementFromTWI(), QET::Icons::tr, and ui.
~MasterPropertiesWidget()
MasterPropertiesWidget::~MasterPropertiesWidget () override
MasterPropertiesWidget::~MasterPropertiesWidget Destructor.
Definition at line 110 of file masterpropertieswidget.cpp.
References AbstractElementPropertiesEditorWidget::m_element, m_showed_element, and ui.
Member Function Documentation
apply()
void MasterPropertiesWidget::apply () override virtual
MasterPropertiesWidget::apply If link betwen edited element and other change, apply the change with a QUndoCommand (got with method associatedUndo) pushed to the stack of element project. Return true if link change, else false.
Note
is void no Return ???
Reimplemented from PropertiesEditorWidget.
Definition at line 172 of file masterpropertieswidget.cpp.
References associatedUndo(), and AbstractElementPropertiesEditorWidget::m_element.
Referenced by on_link_button_clicked(), and on_unlink_button_clicked().
associatedUndo()
QUndoCommand * MasterPropertiesWidget::associatedUndo () const override virtual
MasterPropertiesWidget::associatedUndo If link between the edited element and other change, return a QUndoCommand with this change. If no change return nullptr.
Returns
Reimplemented from PropertiesEditorWidget.
Definition at line 197 of file masterpropertieswidget.cpp.
References AbstractElementPropertiesEditorWidget::m_element, m_qtwi_hash, LinkElementCommand::setLink(), ui, and LinkElementCommand::unlinkAll().
Referenced by apply().
customContextMenu
void MasterPropertiesWidget::customContextMenu (const QPoint & pos, int i = 0) private slot
MasterPropertiesWidget::customContextMenu Display a context menu.
Parameters
pos
i : the tree widget where the context menu was requested.
Definition at line 436 of file masterpropertieswidget.cpp.
References m_context_menu, m_link_action, m_qtwi_at_context_menu, m_show_element, m_show_qtwi, m_unlink_action, and ui.
diagramWasdeletedFromProject
void MasterPropertiesWidget::diagramWasdeletedFromProject () private slot
MasterPropertiesWidget::diagramWasdeletedFromProject This slot is called when a diagram is removed from the parent project of edited element to update the content of this widget.
Definition at line 421 of file masterpropertieswidget.cpp.
References updateUi().
Referenced by setElement().
headerCustomContextMenuRequested
void MasterPropertiesWidget::headerCustomContextMenuRequested (const QPoint & pos) private slot
MasterPropertiesWidget::headerCustomContextMenuRequested.
Parameters
pos
Definition at line 338 of file masterpropertieswidget.cpp.
References m_context_menu, m_save_header_state, and ui.
Referenced by MasterPropertiesWidget().
on_link_button_clicked
void MasterPropertiesWidget::on_link_button_clicked () private slot
MasterPropertiesWidget::on_link_button_clicked move curent item in the free_list to linked_list.
Definition at line 349 of file masterpropertieswidget.cpp.
References apply(), PropertiesEditorWidget::m_live_edit, and ui.
Referenced by MasterPropertiesWidget().
on_unlink_button_clicked
void MasterPropertiesWidget::on_unlink_button_clicked () private slot
MasterPropertiesWidget::on_unlink_button_clicked move curent item in linked_list to free_list.
Definition at line 368 of file masterpropertieswidget.cpp.
References apply(), PropertiesEditorWidget::m_live_edit, and ui.
Referenced by MasterPropertiesWidget().
reset()
void MasterPropertiesWidget::reset () override virtual
MasterPropertiesWidget::reset Reset curent widget, clear eveything and rebuild widget.
Reimplemented from PropertiesEditorWidget.
Definition at line 181 of file masterpropertieswidget.cpp.
References m_qtwi_hash, and updateUi().
setElement()
void MasterPropertiesWidget::setElement (Element * element) override virtual
MasterPropertiesWidget::setElement Set the element to be edited.
Parameters
element
Implements AbstractElementPropertiesEditorWidget.
Definition at line 126 of file masterpropertieswidget.cpp.
References QetGraphicsItem::diagram(), diagramWasdeletedFromProject(), Element::linkedElementChanged(), AbstractElementPropertiesEditorWidget::m_element, m_project, m_showed_element, Diagram::project(), and updateUi().
Referenced by MasterPropertiesWidget().
setLiveEdit()
bool MasterPropertiesWidget::setLiveEdit (bool live_edit) override virtual
MasterPropertiesWidget::setLiveEdit.
Parameters
live_edit = true : live edit is enable else false : live edit is disable.
Returns
always true because live edit is handled by this editor widget
Reimplemented from PropertiesEditorWidget.
Definition at line 234 of file masterpropertieswidget.cpp.
References PropertiesEditorWidget::m_live_edit.
showedElementWasDeleted
void MasterPropertiesWidget::showedElementWasDeleted () private slot
MasterPropertiesWidget::showedElementWasDeleted Set to nullptr the current showed element when he was deleted.
Definition at line 412 of file masterpropertieswidget.cpp.
References m_showed_element.
Referenced by showElementFromTWI().
showElementFromTWI
void MasterPropertiesWidget::showElementFromTWI (QTreeWidgetItem * qtwi, int column) private slot
MasterPropertiesWidget::showElementFromTWI Show the element corresponding to the given QTreeWidgetItem.
Parameters
qtwi
column
Definition at line 389 of file masterpropertieswidget.cpp.
References AbstractElementPropertiesEditorWidget::m_element, m_qtwi_hash, m_showed_element, and showedElementWasDeleted().
Referenced by MasterPropertiesWidget().
title()
QString MasterPropertiesWidget::title () const inline override virtual
title
Returns
QString title
Reimplemented from PropertiesEditorWidget.
Definition at line 60 of file masterpropertieswidget.h.
References QET::Icons::tr.
updateUi
void MasterPropertiesWidget::updateUi () override slot
MasterPropertiesWidget::updateUi Build the interface of the widget.
Definition at line 244 of file masterpropertieswidget.cpp.
References autonum::AssignVariables::formulaToLabel(), ElementProvider::freeElement(), AbstractElementPropertiesEditorWidget::m_element, m_project, m_qtwi_hash, Element::Slave, and ui.
Referenced by diagramWasdeletedFromProject(), reset(), and setElement().
Member Data Documentation
m_context_menu
QMenu* MasterPropertiesWidget::m_context_menu private
Definition at line 82 of file masterpropertieswidget.h.
Referenced by customContextMenu(), headerCustomContextMenuRequested(), and MasterPropertiesWidget().
m_link_action
QAction* MasterPropertiesWidget::m_link_action private
Definition at line 83 of file masterpropertieswidget.h.
Referenced by customContextMenu(), and MasterPropertiesWidget().
m_project
QETProject* MasterPropertiesWidget::m_project private
Definition at line 81 of file masterpropertieswidget.h.
Referenced by setElement(), and updateUi().
m_qtwi_at_context_menu
QTreeWidgetItem* MasterPropertiesWidget::m_qtwi_at_context_menu = nullptr private
Definition at line 79 of file masterpropertieswidget.h.
Referenced by customContextMenu(), and MasterPropertiesWidget().
m_qtwi_hash
QHash<QTreeWidgetItem *, Element *> MasterPropertiesWidget::m_qtwi_hash private
Definition at line 78 of file masterpropertieswidget.h.
Referenced by associatedUndo(), reset(), showElementFromTWI(), and updateUi().
m_save_header_state
QAction * MasterPropertiesWidget::m_save_header_state private
Definition at line 87 of file masterpropertieswidget.h.
Referenced by headerCustomContextMenuRequested(), and MasterPropertiesWidget().
m_show_element
QAction * MasterPropertiesWidget::m_show_element private
Definition at line 86 of file masterpropertieswidget.h.
Referenced by customContextMenu(), and MasterPropertiesWidget().
m_show_qtwi
QAction * MasterPropertiesWidget::m_show_qtwi private
Definition at line 85 of file masterpropertieswidget.h.
Referenced by customContextMenu(), and MasterPropertiesWidget().
m_showed_element
QPointer<Element> MasterPropertiesWidget::m_showed_element private
Definition at line 80 of file masterpropertieswidget.h.
Referenced by MasterPropertiesWidget(), setElement(), showedElementWasDeleted(), showElementFromTWI(), and ~MasterPropertiesWidget().
m_unlink_action
QAction * MasterPropertiesWidget::m_unlink_action private
Definition at line 84 of file masterpropertieswidget.h.
Referenced by customContextMenu(), and MasterPropertiesWidget().
ui
Ui::MasterPropertiesWidget* MasterPropertiesWidget::ui private
Definition at line 77 of file masterpropertieswidget.h.
Referenced by associatedUndo(), customContextMenu(), headerCustomContextMenuRequested(), MasterPropertiesWidget(), on_link_button_clicked(), on_unlink_button_clicked(), updateUi(), and ~MasterPropertiesWidget().
The documentation for this class was generated from the following files:
masterpropertieswidget.h
masterpropertieswidget.cpp