QElectroTech: QET Namespace Reference
QET Namespace Reference
Namespaces
Icons
QetMessageBox
Enumerations
enum GraphicsItemState { GIOK, GIBuildingFromXml, GILoadingFromXml }
enum DepthOption { BringForward, Raise, Lower, SendBackward }
List the various kind of changes for the zValue.
enum OrientedMovement {
ToNorth, ToNorthEast, ToEast, ToSouthEast,
ToSouth, ToSouthWest, ToWest, ToNorthWest
}
Oriented movements.
enum OperationAreas {
ChangeInnerPoints = -4, RotateArea = -3, MoveArea = -2, NoOperation = -1,
ResizeFromTopLeftCorner = 0, ResizeFromTopCenterCorner = 1, ResizeFromTopRightCorner = 2, ResizeFromMiddleLeftCorner = 3,
ResizeFromMiddleRightCorner = 4, ResizeFromBottomLeftCorner = 5, ResizeFromBottomCenterCorner = 6, ResizeFromBottomRightCorner = 7
}
List areas related to some common operations.
enum ScalingMethod { FreeScaling, SnapScalingPointToGrid, RoundScaleRatios }
Supported types of interactive scaling, typically for a single element primitive.
enum ConductorSegmentType { Horizontal = 1, Vertical = 2, Both = 3 }
Known kinds of conductor segments.
enum ItemType {
Element = 1, ElementsCategory = 2, ElementsCollection = 4, ElementsContainer = 6,
ElementsCollectionItem = 7, TitleBlockTemplate = 8, TitleBlockTemplatesCollection = 16, TitleBlockTemplatesCollectionItem = 24,
Diagram = 32, Project = 64, All = 127
}
enum Filtering { BeginFilter, RegularFilter, EndFilter }
enum Action {
Retry, Ignore, Erase, Abort,
Managed, Rename
}
enum DiagramArea { BorderArea, ElementsArea }
enum TitleBlockColumnLength { Absolute, RelativeToTotalLength, RelativeToRemainingLength }
enum used to specify the type of a length
enum QetCollection { Common, Custom, Embedded }
Enum used to specify the origin of a collection of thing (title block, element etc...)
Functions
QString license ()
QString qetCollectionToString (const QetCollection &c)
QET::qetCollectionToString.
QetCollection qetCollectionFromString (const QString &str)
QET::qetCollectionFromString.
bool lineContainsPoint (const QLineF &, const QPointF &)
bool orthogonalProjection (const QPointF &, const QLineF &, QPointF *=nullptr)
bool attributeIsAnInteger (const QDomElement &, const QString &, int *=nullptr)
bool attributeIsAReal (const QDomElement &, const QString &, qreal *=nullptr)
QString ElementsAndConductorsSentence (int elements=0, int conductors=0, int indi_texts=0, int images=0, int shapes=0, int element_text=0, int tables_count=0)
QET::ElementsAndConductorsSentence Permet de composer rapidement la proposition "x elements et y conducteurs" ou encore "x elements, y conducteurs et z champs de texte".
QList< QDomElement > findInDomElement (const QDomElement &, const QString &)
QList< QDomElement > findInDomElement (const QDomElement &, const QString &, const QString &)
QList< QChar > forbiddenCharacters ()
QString stringToFileName (const QString &)
QString escapeSpaces (const QString &)
QString unescapeSpaces (const QString &)
QString joinWithSpaces (const QStringList &)
QStringList splitWithSpaces (const QString &)
QString diagramAreaToString (const QET::DiagramArea &)
QET::DiagramArea diagramAreaFromString (const QString &)
qreal round (qreal, qreal)
qreal correctAngle (const qreal &)
bool compareCanonicalFilePaths (const QString &, const QString &)
bool writeXmlFile (QDomDocument &xml_doc, const QString &filepath, QString *error_message=nullptr)
bool writeToFile (QDomDocument &xml_doc, QFile *file, QString *error_message=nullptr)
bool eachStrIsEqual (const QStringList &qsl)
QET::eachStrIsEqual.
QActionGroup * depthActionGroup (QObject *parent=nullptr)
QET::depthActionGroup.
Variables
const QString version = "0.80"
QElectroTech version (as string, used to mark projects and elements XML documents)
const QString displayedVersion = "0.80-DEV"
QElectroTech displayed version.
Detailed Description
This file provides useful functions and enums that may be used from anywhere else within the QElectroTech application.
This namespace is meant to delare icons used within the QElectroTech application.
Enumeration Type Documentation
Action
enum QET::Action
This enums lists the various ways to handle a standard problem when copying or moving element items (collections, categories, elements).
See also
MoveElementsHandler
Enumerator
Retry
The operation must be tried again.
Ignore
Skip the current item.
Erase
Erase the target content.
Abort
abort the whole operation, ignoring the curent item
Managed
the current item was handled by the Strategy object: do not treat it and continue
Rename
the target has to be renamed
Definition at line 127 of file qet.h.
ConductorSegmentType
enum QET::ConductorSegmentType
Known kinds of conductor segments.
Enumerator
Horizontal
Horizontal segment.
Vertical
Vertical segment.
Both
Invalid segment.
Definition at line 88 of file qet.h.
DepthOption
enum QET::DepthOption
List the various kind of changes for the zValue.
Enumerator
BringForward
Bring item to the foreground so they have the highest zValue.
Raise
Raise item one layer above their current one; zValues are incremented.
Lower
Send item one layer below their current one; zValues are decremented.
SendBackward
Send item to the background so they have the lowest zValue.
Definition at line 45 of file qet.h.
DiagramArea
enum QET::DiagramArea
This enum represents diagram areas that may be exported/printed.
Enumerator
BorderArea
Export the diagram along with its border and title block.
ElementsArea
Export the content of the diagram only.
Definition at line 139 of file qet.h.
Filtering
enum QET::Filtering
This enum represents the various steps when applying a filter.
Enumerator
BeginFilter
RegularFilter
EndFilter
Definition at line 116 of file qet.h.
GraphicsItemState
enum QET::GraphicsItemState
Enumerator
GIOK
General state.
GIBuildingFromXml
Item is currently building from a xml description (element)
GILoadingFromXml
Item is loading her properties from a xml description.
Definition at line 38 of file qet.h.
ItemType
enum QET::ItemType
This enums lists the various kind of items users can manage within the application.
Enumerator
Element
ElementsCategory
ElementsCollection
ElementsContainer
ElementsCollectionItem
TitleBlockTemplate
TitleBlockTemplatesCollection
TitleBlockTemplatesCollectionItem
Diagram
Project
All
Definition at line 99 of file qet.h.
OperationAreas
enum QET::OperationAreas
List areas related to some common operations.
Enumerator
ChangeInnerPoints
RotateArea
MoveArea
NoOperation
ResizeFromTopLeftCorner
ResizeFromTopCenterCorner
ResizeFromTopRightCorner
ResizeFromMiddleLeftCorner
ResizeFromMiddleRightCorner
ResizeFromBottomLeftCorner
ResizeFromBottomCenterCorner
ResizeFromBottomRightCorner
Definition at line 65 of file qet.h.
OrientedMovement
enum QET::OrientedMovement
Oriented movements.
Enumerator
ToNorth
ToNorthEast
ToEast
ToSouthEast
ToSouth
ToSouthWest
ToWest
ToNorthWest
Definition at line 53 of file qet.h.
QetCollection
enum QET::QetCollection
Enum used to specify the origin of a collection of thing (title block, element etc...)
Enumerator
Common
From common collection.
Custom
From user collection.
Embedded
From an embedded collection (a project for exemple)
Definition at line 152 of file qet.h.
ScalingMethod
enum QET::ScalingMethod
Supported types of interactive scaling, typically for a single element primitive.
Enumerator
FreeScaling
do not interfer with the default scaling process
SnapScalingPointToGrid
snap the point used to define the new bounding rectangle to the grid
RoundScaleRatios
adjust the scaling movement so that the induced scaling ratios are rounded
Definition at line 81 of file qet.h.
TitleBlockColumnLength
enum QET::TitleBlockColumnLength
enum used to specify the type of a length
Enumerator
Absolute
the length is absolute and should be applied as is
RelativeToTotalLength
the length is just a fraction of the total available length
RelativeToRemainingLength
the length is just a fraction of the length that is still available when other types of lengths have been removed
Definition at line 145 of file qet.h.
Function Documentation
attributeIsAnInteger()
bool QET::attributeIsAnInteger (const QDomElement & e, const QString & nom_attribut, int * entier = nullptr)
Permet de savoir si l'attribut nom_attribut d'un element XML e est bien un entier. Si oui, sa valeur est copiee dans entier.
Parameters
e Element XML
nom_attribut Nom de l'attribut a analyser
entier Pointeur facultatif vers un entier
Returns
true si l'attribut est bien un entier, false sinon
Definition at line 210 of file qet.cpp.
Referenced by ElementPictureFactory::build(), Element::buildFromXml(), TitleBlockTemplate::checkCell(), TitleBlockCell::loadContentFromXml(), Element::parseInput(), TitleBlockTemplateView::pastedCells(), and QETProject::readDiagramsXml().
attributeIsAReal()
bool QET::attributeIsAReal (const QDomElement & e, const QString & nom_attribut, qreal * reel = nullptr)
Permet de savoir si l'attribut nom_attribut d'un element XML e est bien un reel. Si oui, sa valeur est copiee dans reel.
Parameters
e Element XML
nom_attribut Nom de l'attribut a analyser
reel Pointeur facultatif vers un double
Returns
true si l'attribut est bien un reel, false sinon
Definition at line 231 of file qet.cpp.
Referenced by TerminalData::fromXml(), PartPolygon::fromXml(), ElementPictureFactory::parseArc(), ElementPictureFactory::parseCircle(), ElementPictureFactory::parseEllipse(), Element::parseInput(), ElementPictureFactory::parseLine(), ElementPictureFactory::parsePolygon(), and ElementPictureFactory::parseRect().
compareCanonicalFilePaths()
bool QET::compareCanonicalFilePaths (const QString & first, const QString & second)
Parameters
first Un premier chemin vers un fichier
second Un second chemin vers un fichier
Returns
true si les deux chemins existent existent et sont identiques lorsqu'ils sont exprimes sous forme canonique
Definition at line 559 of file qet.cpp.
Referenced by QETTitleBlockTemplateEditor::isEditing(), and QETElementEditor::isEditing().
correctAngle()
qreal QET::correctAngle (const qreal & angle)
Parameters
angle Un angle quelconque
Returns
l'angle passe en parametre, mais ramene entre -360.0 + 360.0 degres
Definition at line 545 of file qet.cpp.
Referenced by DiagramTextItem::applyRotation(), Element::orientation(), PartText::setRotation(), IndependentTextItem::toXml(), DiagramImageItem::toXml(), PartDynamicTextField::toXml(), DynamicElementTextItem::toXml(), DynamicElementTextModel::undoForEditedText(), and DynamicTextFieldEditor::updateForm().
depthActionGroup()
QActionGroup * QET::depthActionGroup (QObject * parent = nullptr)
QET::depthActionGroup.
Parameters
parent
Returns
an action group which contain 4 actions (forward, raise, lower, backward) already made with icon, shortcut and data (see QET::DepthOption)
Definition at line 676 of file qet.cpp.
References QET::Icons::BringForward, BringForward, Lower, QET::Icons::Lower, Raise, QET::Icons::Raise, SendBackward, QET::Icons::SendBackward, and QET::Icons::tr.
Referenced by QETElementEditor::setupActions(), and QETDiagramEditor::setUpActions().
diagramAreaFromString()
QET::DiagramArea QET::diagramAreaFromString (const QString & string)
Parameters
string une chaine representant un type de zone de schema
Returns
le type de zone de schema correspondant ; si la chaine est invalide, QET::ElementsArea est retourne.
Definition at line 528 of file qet.cpp.
References BorderArea, and ElementsArea.
Referenced by ExportProperties::fromSettings().
diagramAreaToString()
QString QET::diagramAreaToString (const QET::DiagramArea & diagram_area)
Parameters
diagram_area un type de zone de schema
Returns
une chaine representant le type de zone de schema
Definition at line 518 of file qet.cpp.
References ElementsArea.
Referenced by ExportProperties::toSettings().
eachStrIsEqual()
bool QET::eachStrIsEqual (const QStringList & qsl)
QET::eachStrIsEqual.
Parameters
qsl list of string to compare
Returns
true if every string is identical, else false; The list must not be empty If the list can be empty, call isEmpty() before calling this function
Definition at line 624 of file qet.cpp.
Referenced by ConductorAutoNumerotation::numeratePotential(), and LinkElementCommand::redo().
ElementsAndConductorsSentence()
QString QET::ElementsAndConductorsSentence (int elements_count = 0, int conductors_count = 0, int texts_count = 0, int images_count = 0, int shapes_count = 0, int element_text_count = 0, int tables_count = 0)
QET::ElementsAndConductorsSentence Permet de composer rapidement la proposition "x elements et y conducteurs" ou encore "x elements, y conducteurs et z champs de texte".
Parameters
elements_count nombre d'elements
conductors_count nombre de conducteurs
texts_count nombre de champs de texte
images_count nombre d'images
shapes_count
element_text_count
tables_count
Returns
la proposition decrivant le nombre d'elements, de conducteurs et de textes
Definition at line 258 of file qet.cpp.
References QET::Icons::tr.
Referenced by MoveConductorsTextsCommand::regenerateTextLabel(), ResetConductorCommand::ResetConductorCommand(), and DiagramContent::sentence().
escapeSpaces()
QString QET::escapeSpaces (const QString & string)
Parameters
string une chaine de caracteres
Returns
la meme chaine de caracteres, mais avec les espaces et backslashes echappes
Definition at line 433 of file qet.cpp.
Referenced by joinWithSpaces().
findInDomElement() [1/2]
QList< QDomElement > QET::findInDomElement (const QDomElement & e, const QString & tag_name)
Returns
the list of tag_name elements directly under the e XML element.
Definition at line 333 of file qet.cpp.
Referenced by ImportElementTextPattern::apply(), Diagram::folioSequentialsFromXml(), TitleBlockProperties::fromXml(), NumerotationContext::fromXml(), QetShapeItem::fromXml(), DiagramContext::fromXml(), ElementTextItemGroup::fromXml(), TitleBlockTemplatesProjectCollection::fromXml(), Element::fromXml(), Diagram::fromXml(), QETProject::readDefaultPropertiesXml(), and QETProject::readProjectPropertiesXml().
findInDomElement() [2/2]
QList< QDomElement > QET::findInDomElement (const QDomElement & e, const QString & parent, const QString & children)
Etant donne un element XML e, renvoie la liste de tous les elements children imbriques dans les elements parent, eux-memes enfants de l'elememt e
Parameters
e Element XML a explorer
parent tag XML intermediaire
children tag XML a rechercher
Returns
La liste des elements XML children
Definition at line 352 of file qet.cpp.
forbiddenCharacters()
QList< QChar > QET::forbiddenCharacters ()
Returns
la liste des caracteres interdits dans les noms de fichiers sous Windows
Definition at line 401 of file qet.cpp.
Referenced by stringToFileName().
joinWithSpaces()
QString QET::joinWithSpaces (const QStringList & string_list)
Assemble une liste de chaines en une seule. Un espace separe chaque chaine. Les espaces et backslashes des chaines sont echappes.
Parameters
string_list une liste de chaine
Returns
l'assemblage des chaines
Definition at line 452 of file qet.cpp.
References escapeSpaces().
Referenced by main().
license()
QString QET::license ()
Returns
le texte de la licence de QElectroTech (GNU/GPL)
Definition at line 373 of file qet.cpp.
References QET::Icons::tr.
Referenced by QETApp::printLicense(), and AboutQETDialog::setLicence().
lineContainsPoint()
bool QET::lineContainsPoint (const QLineF & line, const QPointF & point)
Parameters
line Un segment de droite
point Un point
Returns
true si le point appartient au segment de droite, false sinon
Definition at line 150 of file qet.cpp.
Referenced by Terminal::alignedWithTerminal(), and orthogonalProjection().
orthogonalProjection()
bool QET::orthogonalProjection (const QPointF & point, const QLineF & line, QPointF * intersection = nullptr)
Parameters
point Un point donne
line Un segment de droite donnee
intersection si ce pointeur est different de 0, le QPointF ainsi designe contiendra les coordonnees du projete orthogonal, meme si celui-ci n'appartient pas au segment de droite
Returns
true si le projete orthogonal du point sur la droite appartient au segment de droite.
Definition at line 166 of file qet.cpp.
References QET::Icons::it, and lineContainsPoint().
Referenced by Conductor::movePointIntoPolygon().
qetCollectionFromString()
QET::QetCollection QET::qetCollectionFromString (const QString & str)
QET::qetCollectionFromString.
Parameters
str string to convert
Returns
The corresponding QetCollection value from a string. If the string don't match anything, we return the failsafe value QetCollection::Common
Definition at line 658 of file qet.cpp.
References Common, Custom, and Embedded.
Referenced by TitleBlockProperties::fromSettings(), and TitleBlockProperties::fromXml().
qetCollectionToString()
QString QET::qetCollectionToString (const QetCollection & c)
QET::qetCollectionToString.
Parameters
c QetCollection value to convert
Returns
The QetCollection enum value converted to a QString
Definition at line 637 of file qet.cpp.
References Common, Custom, and Embedded.
Referenced by TitleBlockProperties::toSettings(), and TitleBlockProperties::toXml().
round()
qreal QET::round (qreal x, qreal epsilon)
Round x to the nearest multiple of the invert of epsilon. For instance, epsilon = 10 will round to 1/10 = 0.1
Definition at line 537 of file qet.cpp.
Referenced by ElementPrimitiveDecorator::deltaForRoundScaling().
splitWithSpaces()
QStringList QET::splitWithSpaces (const QString & string)
Parameters
string Une chaine de caracteres contenant des sous-chaines a extraire separees par des espaces non echappes. Les espaces des sous-chaines sont echappes.
Returns
La liste des sous-chaines, sans echappement.
Definition at line 469 of file qet.cpp.
References unescapeSpaces().
Referenced by QETApp::receiveMessage().
stringToFileName()
QString QET::stringToFileName (const QString & name)
Cette fonction transforme une chaine de caracteres (typiquement : un nom de schema, de projet, d'element) en un nom de fichier potable. Par nom de fichier potable, on entend un nom : ne comprenant pas de caracteres interdits sous Windows ne comprenant pas d'espace
Parameters
name Chaine de caractere a transformer en nom de fichier potable
Definition at line 414 of file qet.cpp.
References forbiddenCharacters().
Referenced by ExportDialog::ExportDiagramLine::ExportDiagramLine(), and ProjectView::printProject().
unescapeSpaces()
QString QET::unescapeSpaces (const QString & string)
Parameters
string une chaine de caracteres
Returns
la meme chaine de caracteres, mais avec les espaces et backslashes non echappes
Definition at line 442 of file qet.cpp.
Referenced by splitWithSpaces().
writeToFile()
bool QET::writeToFile (QDomDocument & xml_doc, QFile * file, QString * error_message = nullptr)
Definition at line 703 of file qet.cpp.
References QET::Icons::tr.
Referenced by QETProject::writeBackup().
writeXmlFile()
bool QET::writeXmlFile (QDomDocument & xml_doc, const QString & filepath, QString * error_message = nullptr)
Export an XML document to an UTF-8 text file indented with 4 spaces, with LF end of lines and no BOM.
Parameters
xml_doc An XML document to be exported
filepath Path to the file to be written
error_message If non-zero, will contain an error message explaining what happened when this function returns false.
Returns
false if an error occurred, true otherwise
Definition at line 584 of file qet.cpp.
References QET::Icons::tr.
Referenced by ECHSXmlToFile::copyDirectory(), ECHSXmlToFile::copyElement(), ElementCollectionHandler::createDir(), ExportElementTextPattern::ExportElementTextPattern(), TitleBlockTemplate::saveToXmlFile(), ElementCollectionHandler::setNames(), TitleBlockTemplatesFilesCollection::setTemplateXmlDescription(), QETElementEditor::toFile(), and QETProject::write().
Variable Documentation
displayedVersion
const QString QET::displayedVersion = "0.80-DEV"
QElectroTech displayed version.
Definition at line 34 of file qet.h.
Referenced by DiagramPrintDialog::exec(), BorderTitleBlock::importTitleBlock(), QETApp::printVersion(), Machine_info::send_info_to_debug(), and AboutQETDialog::setVersion().
version
const QString QET::version = "0.80"
QElectroTech version (as string, used to mark projects and elements XML documents)
Definition at line 32 of file qet.h.
Referenced by ElementPictureFactory::build(), Element::buildFromXml(), QETProject::readProjectXml(), Machine_info::send_info_to_debug(), ElementScene::toXml(), QETProject::toXml(), and Diagram::toXml().