QElectroTech: ReplaceConductorDialog Class Reference
ReplaceConductorDialog Class Reference
The ReplaceConductorDialog class A Qdialog to edit a conductor properties, use for the search and replace feature of QElectrotech.
#include <replaceconductordialog.h>
Public Member Functions
ReplaceConductorDialog (const ConductorProperties &properties, QWidget *parent=0)
ReplaceConductorDialog::ReplaceConductorDialog.
~ReplaceConductorDialog ()
void updatePreview (bool b=true)
ReplaceConductorDialog::updatePreview Update the preview for single line.
void setProperties (const ConductorProperties &properties)
ConductorProperties properties () const
ReplaceConductorDialog::properties.
Private Slots
void on_m_erase_formula_cb_clicked ()
void on_m_erase_text_cb_clicked ()
void on_m_erase_function_cb_clicked ()
void on_m_erase_tension_protocol_cb_clicked ()
void on_m_erase_m_wire_color_cb_clicked ()
void on_m_erase_m_wire_section_cb_clicked ()
void on_m_earth_cb_toggled (bool checked)
void on_m_neutral_cb_toggled (bool checked)
void on_m_update_preview_pb_clicked ()
void on_m_color_pb_clicked ()
void on_m_color_2_pb_clicked ()
Private Member Functions
void initWidget ()
void setColorButton (const QColor &color)
void setColorButton2 (const QColor &color)
Private Attributes
Ui::ReplaceConductorDialog * ui
ConductorProperties m_properties
Detailed Description
The ReplaceConductorDialog class A Qdialog to edit a conductor properties, use for the search and replace feature of QElectrotech.
Definition at line 33 of file replaceconductordialog.h.
Constructor & Destructor Documentation
ReplaceConductorDialog()
ReplaceConductorDialog::ReplaceConductorDialog (const ConductorProperties & properties, QWidget * parent = 0) explicit
ReplaceConductorDialog::ReplaceConductorDialog.
Parameters
properties
parent
Definition at line 32 of file replaceconductordialog.cpp.
References initWidget(), properties(), setProperties(), and ui.
~ReplaceConductorDialog()
ReplaceConductorDialog::~ReplaceConductorDialog ()
Definition at line 43 of file replaceconductordialog.cpp.
References ui.
Member Function Documentation
initWidget()
void ReplaceConductorDialog::initWidget () private
Definition at line 193 of file replaceconductordialog.cpp.
References QET::Icons::tr, and ui.
Referenced by ReplaceConductorDialog().
on_m_color_2_pb_clicked
void ReplaceConductorDialog::on_m_color_2_pb_clicked () private slot
Definition at line 334 of file replaceconductordialog.cpp.
References ConductorProperties::m_color_2, m_properties, and setColorButton2().
on_m_color_pb_clicked
void ReplaceConductorDialog::on_m_color_pb_clicked () private slot
Definition at line 326 of file replaceconductordialog.cpp.
References ConductorProperties::color, m_properties, and setColorButton().
on_m_earth_cb_toggled
void ReplaceConductorDialog::on_m_earth_cb_toggled (bool checked) private slot
Definition at line 304 of file replaceconductordialog.cpp.
References ui.
on_m_erase_formula_cb_clicked
void ReplaceConductorDialog::on_m_erase_formula_cb_clicked () private slot
Definition at line 252 of file replaceconductordialog.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_erase_function_cb_clicked
void ReplaceConductorDialog::on_m_erase_function_cb_clicked () private slot
Definition at line 268 of file replaceconductordialog.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_erase_m_wire_color_cb_clicked
void ReplaceConductorDialog::on_m_erase_m_wire_color_cb_clicked () private slot
Definition at line 286 of file replaceconductordialog.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_erase_m_wire_section_cb_clicked
void ReplaceConductorDialog::on_m_erase_m_wire_section_cb_clicked () private slot
Definition at line 295 of file replaceconductordialog.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_erase_tension_protocol_cb_clicked
void ReplaceConductorDialog::on_m_erase_tension_protocol_cb_clicked () private slot
Definition at line 276 of file replaceconductordialog.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_erase_text_cb_clicked
void ReplaceConductorDialog::on_m_erase_text_cb_clicked () private slot
Definition at line 260 of file replaceconductordialog.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_neutral_cb_toggled
void ReplaceConductorDialog::on_m_neutral_cb_toggled (bool checked) private slot
Definition at line 313 of file replaceconductordialog.cpp.
References ui.
on_m_update_preview_pb_clicked
void ReplaceConductorDialog::on_m_update_preview_pb_clicked () private slot
Definition at line 322 of file replaceconductordialog.cpp.
References updatePreview().
properties()
ConductorProperties ReplaceConductorDialog::properties () const
ReplaceConductorDialog::properties.
Returns
the properties edited by this widget
Definition at line 134 of file replaceconductordialog.cpp.
References ConductorProperties::color, ConductorProperties::cond_size, SingleLineProperties::hasGround, SingleLineProperties::hasNeutral, ConductorProperties::horiz_rotate_text, SingleLineProperties::is_pen, ConductorProperties::m_bicolor, ConductorProperties::m_color_2, ConductorProperties::m_dash_size, ConductorProperties::m_formula, ConductorProperties::m_function, ConductorProperties::m_horizontal_alignment, ConductorProperties::m_show_text, ConductorProperties::m_tension_protocol, ConductorProperties::m_vertical_alignment, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, ConductorProperties::Multi, SingleLineProperties::setPhasesCount(), ConductorProperties::Single, ConductorProperties::singleLineProperties, ConductorProperties::style, ConductorProperties::text, ConductorProperties::text_size, ConductorProperties::type, ui, and ConductorProperties::verti_rotate_text.
Referenced by SearchAndReplaceWidget::on_m_conductor_pb_clicked(), ReplaceConductorDialog(), setProperties(), and updatePreview().
setColorButton()
void ReplaceConductorDialog::setColorButton (const QColor & color) private
Definition at line 229 of file replaceconductordialog.cpp.
References ui.
Referenced by on_m_color_pb_clicked(), and setProperties().
setColorButton2()
void ReplaceConductorDialog::setColorButton2 (const QColor & color) private
Definition at line 239 of file replaceconductordialog.cpp.
References ui.
Referenced by on_m_color_2_pb_clicked(), and setProperties().
setProperties()
void ReplaceConductorDialog::setProperties (const ConductorProperties & properties)
Definition at line 75 of file replaceconductordialog.cpp.
References ConductorProperties::color, SingleLineProperties::hasGround, SingleLineProperties::hasNeutral, ConductorProperties::horiz_rotate_text, SingleLineProperties::isPen(), ConductorProperties::m_bicolor, ConductorProperties::m_color_2, ConductorProperties::m_dash_size, ConductorProperties::m_formula, ConductorProperties::m_function, ConductorProperties::m_horizontal_alignment, m_properties, ConductorProperties::m_show_text, ConductorProperties::m_tension_protocol, ConductorProperties::m_vertical_alignment, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, SingleLineProperties::phasesCount(), properties(), setColorButton(), setColorButton2(), SearchAndReplaceWorker::setupLineEdit(), ConductorProperties::Single, ConductorProperties::singleLineProperties, ConductorProperties::style, ConductorProperties::text, ConductorProperties::text_size, ConductorProperties::type, ui, updatePreview(), and ConductorProperties::verti_rotate_text.
Referenced by ReplaceConductorDialog().
updatePreview()
void ReplaceConductorDialog::updatePreview (bool b = true)
ReplaceConductorDialog::updatePreview Update the preview for single line.
Parameters
b : true: update from the value displayed by this widget false: update from the properties given at the constructor of this widget
Definition at line 55 of file replaceconductordialog.cpp.
References SingleLineProperties::draw(), QET::Horizontal, m_properties, properties(), ConductorProperties::singleLineProperties, and ui.
Referenced by on_m_update_preview_pb_clicked(), and setProperties().
Member Data Documentation
m_properties
ConductorProperties ReplaceConductorDialog::m_properties private
Definition at line 66 of file replaceconductordialog.h.
Referenced by on_m_color_2_pb_clicked(), on_m_color_pb_clicked(), setProperties(), and updatePreview().
ui
Ui::ReplaceConductorDialog* ReplaceConductorDialog::ui private
Definition at line 65 of file replaceconductordialog.h.
Referenced by initWidget(), on_m_earth_cb_toggled(), on_m_erase_formula_cb_clicked(), on_m_erase_function_cb_clicked(), on_m_erase_m_wire_color_cb_clicked(), on_m_erase_m_wire_section_cb_clicked(), on_m_erase_tension_protocol_cb_clicked(), on_m_erase_text_cb_clicked(), on_m_neutral_cb_toggled(), properties(), ReplaceConductorDialog(), setColorButton(), setColorButton2(), setProperties(), updatePreview(), and ~ReplaceConductorDialog().
The documentation for this class was generated from the following files:
replaceconductordialog.h
replaceconductordialog.cpp