QElectroTech: ReplaceFolioWidget Class Reference
ReplaceFolioWidget Class Reference
#include <replacefoliowidget.h>
Public Member Functions
ReplaceFolioWidget (QWidget *parent=nullptr)
~ReplaceFolioWidget ()
TitleBlockProperties titleBlockProperties () const
ReplaceFolioWidget::titleBlockProperties.
void setTitleBlockProperties (const TitleBlockProperties &properties)
ReplaceFolioWidget::setTitleBlockProperties Set the title block properties edited by this widget.
Private Slots
void on_m_title_cb_clicked ()
void on_m_author_cb_clicked ()
void on_m_file_cb_clicked ()
void on_m_folio_cb_clicked ()
void on_m_plant_cb_clicked ()
void on_m_loc_cb_clicked ()
void on_m_indice_cb_clicked ()
Private Attributes
Ui::ReplaceFolioWidget * ui
DiagramContextWidget * m_diagram_context_widget = nullptr
Detailed Description
Definition at line 34 of file replacefoliowidget.h.
Constructor & Destructor Documentation
ReplaceFolioWidget()
ReplaceFolioWidget::ReplaceFolioWidget (QWidget * parent = nullptr) explicit
Definition at line 27 of file replacefoliowidget.cpp.
References m_diagram_context_widget, and ui.
~ReplaceFolioWidget()
ReplaceFolioWidget::~ReplaceFolioWidget ()
Definition at line 36 of file replacefoliowidget.cpp.
References ui.
Member Function Documentation
on_m_author_cb_clicked
void ReplaceFolioWidget::on_m_author_cb_clicked () private slot
Definition at line 162 of file replacefoliowidget.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_file_cb_clicked
void ReplaceFolioWidget::on_m_file_cb_clicked () private slot
Definition at line 169 of file replacefoliowidget.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_folio_cb_clicked
void ReplaceFolioWidget::on_m_folio_cb_clicked () private slot
Definition at line 176 of file replacefoliowidget.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_indice_cb_clicked
void ReplaceFolioWidget::on_m_indice_cb_clicked () private slot
Definition at line 197 of file replacefoliowidget.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_loc_cb_clicked
void ReplaceFolioWidget::on_m_loc_cb_clicked () private slot
Definition at line 190 of file replacefoliowidget.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_plant_cb_clicked
void ReplaceFolioWidget::on_m_plant_cb_clicked () private slot
Definition at line 183 of file replacefoliowidget.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
on_m_title_cb_clicked
void ReplaceFolioWidget::on_m_title_cb_clicked () private slot
Definition at line 155 of file replacefoliowidget.cpp.
References SearchAndReplaceWorker::eraseText(), and ui.
setTitleBlockProperties()
void ReplaceFolioWidget::setTitleBlockProperties (const TitleBlockProperties & properties)
ReplaceFolioWidget::setTitleBlockProperties Set the title block properties edited by this widget.
Parameters
properties
Definition at line 78 of file replacefoliowidget.cpp.
References TitleBlockProperties::author, TitleBlockProperties::context, TitleBlockProperties::CurrentDate, TitleBlockProperties::date, SearchAndReplaceWorker::eraseDate(), TitleBlockProperties::filename, TitleBlockProperties::folio, TitleBlockProperties::indexrev, TitleBlockProperties::locmach, m_diagram_context_widget, TitleBlockProperties::plant, DiagramContextWidget::setContext(), SearchAndReplaceWorker::setupLineEdit(), TitleBlockProperties::title, ui, and TitleBlockProperties::useDate.
Referenced by ReplaceFolioDialog::setTitleBlockProperties().
titleBlockProperties()
TitleBlockProperties ReplaceFolioWidget::titleBlockProperties () const
ReplaceFolioWidget::titleBlockProperties.
Returns
the title block properties edited by this widget
Definition at line 45 of file replacefoliowidget.cpp.
References TitleBlockProperties::author, DiagramContextWidget::context(), TitleBlockProperties::context, TitleBlockProperties::date, SearchAndReplaceWorker::eraseDate(), TitleBlockProperties::filename, TitleBlockProperties::folio, TitleBlockProperties::indexrev, TitleBlockProperties::locmach, m_diagram_context_widget, TitleBlockProperties::plant, TitleBlockProperties::title, ui, TitleBlockProperties::useDate, and TitleBlockProperties::UseDateValue.
Referenced by ReplaceFolioDialog::titleBlockProperties().
Member Data Documentation
m_diagram_context_widget
DiagramContextWidget* ReplaceFolioWidget::m_diagram_context_widget = nullptr private
Definition at line 56 of file replacefoliowidget.h.
Referenced by ReplaceFolioWidget(), setTitleBlockProperties(), and titleBlockProperties().
ui
Ui::ReplaceFolioWidget* ReplaceFolioWidget::ui private
Definition at line 55 of file replacefoliowidget.h.
Referenced by on_m_author_cb_clicked(), on_m_file_cb_clicked(), on_m_folio_cb_clicked(), on_m_indice_cb_clicked(), on_m_loc_cb_clicked(), on_m_plant_cb_clicked(), on_m_title_cb_clicked(), ReplaceFolioWidget(), setTitleBlockProperties(), titleBlockProperties(), and ~ReplaceFolioWidget().
The documentation for this class was generated from the following files:
replacefoliowidget.h
replacefoliowidget.cpp