QElectroTech: EllipseEditor Class Reference
EllipseEditor Class Reference
#include <ellipseeditor.h>
Public Slots
void editingFinishedX ()
void editingFinishedY ()
void editingFinishedH ()
void editingFinishedV ()
void updateForm () override
Public Member Functions
EllipseEditor (QETElementEditor *, PartEllipse *=nullptr, QWidget *=nullptr)
~EllipseEditor () override
Destructeur.
bool setPart (CustomElementPart *) override
bool setParts (QList< CustomElementPart * > parts) override
CustomElementPart * currentPart () const override
QList< CustomElementPart * > currentParts () const override
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
virtual void updateForm ()=0
Private Member Functions
EllipseEditor (const EllipseEditor &)
void activeConnections (bool)
void setUpChangeConnections ()
setUpChangeConnections Setup the connection from the ellipse(s) to the widget, to update it when the ellipse(s) are changed (moved ...)
void disconnectChangeConnections ()
Private Attributes
PartEllipse * part
StyleEditor * style_
QDoubleSpinBox * x
QDoubleSpinBox * y
QDoubleSpinBox * h
QDoubleSpinBox * v
bool m_locked
QList< QMetaObject::Connection > m_change_connections
Detailed Description
This class provides a widget to edit ellipses within the element editor.
Definition at line 30 of file ellipseeditor.h.
Constructor & Destructor Documentation
EllipseEditor() [1/2]
EllipseEditor::EllipseEditor (QETElementEditor * editor, PartEllipse * ellipse = nullptr, QWidget * parent = nullptr)
Constructeur
Parameters
editor L'editeur d'element concerne
ellipse L'ellipse a editer
parent le Widget parent
Definition at line 30 of file ellipseeditor.cpp.
References activeConnections(), h, style_, QET::Icons::tr, updateForm(), v, x, and y.
~EllipseEditor()
EllipseEditor::~EllipseEditor () override
Destructeur.
Definition at line 70 of file ellipseeditor.cpp.
EllipseEditor() [2/2]
EllipseEditor::EllipseEditor (const EllipseEditor &) private
Member Function Documentation
activeConnections()
void EllipseEditor::activeConnections (bool active) private
Active ou desactive les connexionx signaux/slots entre les widgets internes.
Parameters
active true pour activer les connexions, false pour les desactiver
Definition at line 252 of file ellipseeditor.cpp.
References editingFinishedH(), editingFinishedV(), editingFinishedX(), editingFinishedY(), h, v, x, and y.
Referenced by EllipseEditor(), and updateForm().
currentPart()
CustomElementPart * EllipseEditor::currentPart () const override virtual
Returns
la primitive actuellement editee, ou 0 si ce widget n'en edite pas
Implements ElementItemEditor.
Definition at line 129 of file ellipseeditor.cpp.
References part.
currentParts()
QList< CustomElementPart * > EllipseEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 133 of file ellipseeditor.cpp.
References StyleEditor::currentParts(), and style_.
disconnectChangeConnections()
void EllipseEditor::disconnectChangeConnections () private
Definition at line 78 of file ellipseeditor.cpp.
References m_change_connections.
Referenced by setPart().
editingFinishedH
void EllipseEditor::editingFinishedH () slot
Definition at line 187 of file ellipseeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), h, m_locked, part, CustomElementGraphicPart::property(), style_, PastePartsCommand::undo(), and ElementScene::undoStack().
Referenced by activeConnections().
editingFinishedV
void EllipseEditor::editingFinishedV () slot
Definition at line 210 of file ellipseeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), m_locked, part, CustomElementGraphicPart::property(), style_, PastePartsCommand::undo(), ElementScene::undoStack(), and v.
Referenced by activeConnections().
editingFinishedX
void EllipseEditor::editingFinishedX () slot
Definition at line 137 of file ellipseeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), h, m_locked, part, CustomElementGraphicPart::property(), style_, PastePartsCommand::undo(), ElementScene::undoStack(), v, x, and y.
Referenced by activeConnections().
editingFinishedY
void EllipseEditor::editingFinishedY () slot
Definition at line 161 of file ellipseeditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), h, m_locked, part, CustomElementGraphicPart::property(), style_, PastePartsCommand::undo(), ElementScene::undoStack(), v, x, and y.
Referenced by activeConnections().
setPart()
bool EllipseEditor::setPart (CustomElementPart * new_part) override virtual
Permet de specifier a cet editeur quelle primitive il doit editer. A noter qu'un editeur peut accepter ou refuser d'editer une primitive. L'editeur d'ellipse acceptera d'editer la primitive new_part s'il s'agit d'un objet de la classe PartEllipse.
Parameters
new_part Nouvelle primitive a editer
Returns
true si l'editeur a accepter d'editer la primitive, false sinon
Implements ElementItemEditor.
Definition at line 94 of file ellipseeditor.cpp.
References disconnectChangeConnections(), part, setUpChangeConnections(), and updateForm().
Referenced by setParts().
setParts()
bool EllipseEditor::setParts (QList< CustomElementPart * > parts) override virtual
Reimplemented from ElementItemEditor.
Definition at line 116 of file ellipseeditor.cpp.
References setPart(), StyleEditor::setParts(), and style_.
setUpChangeConnections()
void EllipseEditor::setUpChangeConnections () private
setUpChangeConnections Setup the connection from the ellipse(s) to the widget, to update it when the ellipse(s) are changed (moved ...)
Definition at line 73 of file ellipseeditor.cpp.
References m_change_connections, part, AbstractPartEllipse::rectChanged(), and updateForm().
Referenced by setPart().
updateForm
void EllipseEditor::updateForm () override slot
Met a jour le formulaire d'edition
Definition at line 236 of file ellipseeditor.cpp.
References activeConnections(), h, part, CustomElementGraphicPart::property(), v, x, and y.
Referenced by EllipseEditor(), setPart(), and setUpChangeConnections().
Member Data Documentation
h
QDoubleSpinBox * EllipseEditor::h private
Definition at line 45 of file ellipseeditor.h.
Referenced by activeConnections(), editingFinishedH(), editingFinishedX(), editingFinishedY(), EllipseEditor(), and updateForm().
m_change_connections
QList<QMetaObject::Connection> EllipseEditor::m_change_connections private
Definition at line 47 of file ellipseeditor.h.
Referenced by disconnectChangeConnections(), and setUpChangeConnections().
m_locked
bool EllipseEditor::m_locked private
Definition at line 46 of file ellipseeditor.h.
Referenced by editingFinishedH(), editingFinishedV(), editingFinishedX(), and editingFinishedY().
part
PartEllipse* EllipseEditor::part private
Definition at line 43 of file ellipseeditor.h.
Referenced by currentPart(), editingFinishedH(), editingFinishedV(), editingFinishedX(), editingFinishedY(), setPart(), setUpChangeConnections(), and updateForm().
style_
StyleEditor* EllipseEditor::style_ private
Definition at line 44 of file ellipseeditor.h.
Referenced by currentParts(), editingFinishedH(), editingFinishedV(), editingFinishedX(), editingFinishedY(), EllipseEditor(), and setParts().
v
QDoubleSpinBox * EllipseEditor::v private
Definition at line 45 of file ellipseeditor.h.
Referenced by activeConnections(), editingFinishedV(), editingFinishedX(), editingFinishedY(), EllipseEditor(), and updateForm().
x
QDoubleSpinBox* EllipseEditor::x private
Definition at line 45 of file ellipseeditor.h.
Referenced by activeConnections(), editingFinishedX(), editingFinishedY(), EllipseEditor(), and updateForm().
y
QDoubleSpinBox * EllipseEditor::y private
Definition at line 45 of file ellipseeditor.h.
Referenced by activeConnections(), editingFinishedX(), editingFinishedY(), EllipseEditor(), and updateForm().
The documentation for this class was generated from the following files:
ellipseeditor.h
ellipseeditor.cpp