QElectroTech: ConductorCreator Class Reference
ConductorCreator Class Reference
The ConductorCreator class This class create one or several or several conductors in a given context.
#include <conductorcreator.h>
Public Member Functions
ConductorCreator (Diagram *d, QList< Terminal * > terminals_list)
ConductorCreator::ConductorCreator Create an electrical potential between all terminals of terminals_list. the terminals of the list must be in the same diagram.
Static Public Member Functions
static void create (Diagram *d, const QPolygonF &polygon)
ConductorCreator::create Create an electrical potential between the terminals of the diagram d, contained in the polygon.
Private Member Functions
void setUpPropertieToUse ()
ConductorCreator::propertieToUse.
QList< Conductor * > existingPotential ()
ConductorCreator::existingPotential Return the list of existing potential of the terminal list.
Terminal * hubTerminal ()
ConductorCreator::hubTerminal.
Private Attributes
QList< Terminal * > m_terminals_list
ConductorProperties m_properties
autonum::sequentialNumbers m_sequential_number
Detailed Description
The ConductorCreator class This class create one or several or several conductors in a given context.
Definition at line 38 of file conductorcreator.h.
Constructor & Destructor Documentation
ConductorCreator()
ConductorCreator::ConductorCreator (Diagram * d, QList< Terminal * > terminals_list)
ConductorCreator::ConductorCreator Create an electrical potential between all terminals of terminals_list. the terminals of the list must be in the same diagram.
Parameters
d Diagram
terminals_list QList<Terminal *>
Definition at line 37 of file conductorcreator.cpp.
References QET::Icons::Conductor, hubTerminal(), m_properties, m_sequential_number, m_terminals_list, Conductor::setProperties(), Conductor::setSequenceNum(), setUpPropertieToUse(), QET::Icons::tr, and Diagram::undoStack().
Member Function Documentation
create()
void ConductorCreator::create (Diagram * d, const QPolygonF & polygon) static
ConductorCreator::create Create an electrical potential between the terminals of the diagram d, contained in the polygon.
Parameters
d Diagram
polygon : polygon in diagram coordinate
Definition at line 77 of file conductorcreator.cpp.
References Terminal::Type.
Referenced by DiagramView::mouseReleaseEvent().
existingPotential()
QList< Conductor * > ConductorCreator::existingPotential () private
ConductorCreator::existingPotential Return the list of existing potential of the terminal list.
Returns
c_list QList<Conductor *>
Definition at line 139 of file conductorcreator.cpp.
References Element::AllReport, Element::conductors(), Element::linkedElements(), m_terminals_list, and Conductor::relatedPotentialConductors().
Referenced by setUpPropertieToUse().
hubTerminal()
Terminal * ConductorCreator::hubTerminal () private
ConductorCreator::hubTerminal.
Returns
hub_terminal
Definition at line 181 of file conductorcreator.cpp.
References m_terminals_list.
Referenced by ConductorCreator().
setUpPropertieToUse()
void ConductorCreator::setUpPropertieToUse () private
ConductorCreator::propertieToUse.
Returns
the conductor properties to use for the new conductors.
Definition at line 99 of file conductorcreator.cpp.
References PotentialSelectorDialog::chosenProperties(), existingPotential(), m_properties, m_sequential_number, m_terminals_list, and ConductorAutoNumerotation::newProperties().
Referenced by ConductorCreator().
Member Data Documentation
m_properties
ConductorProperties ConductorCreator::m_properties private
Definition at line 51 of file conductorcreator.h.
Referenced by ConductorCreator(), and setUpPropertieToUse().
m_sequential_number
autonum::sequentialNumbers ConductorCreator::m_sequential_number private
Definition at line 52 of file conductorcreator.h.
Referenced by ConductorCreator(), and setUpPropertieToUse().
m_terminals_list
QList<Terminal *> ConductorCreator::m_terminals_list private
Definition at line 50 of file conductorcreator.h.
Referenced by ConductorCreator(), existingPotential(), hubTerminal(), and setUpPropertieToUse().
The documentation for this class was generated from the following files:
conductorcreator.h
conductorcreator.cpp