QElectroTech: nomenclature Class Reference
nomenclature Class Reference
#include <nomenclature.h>
Public Member Functions
nomenclature (QETProject *project, QWidget *parent=nullptr)
nomenclature::nomenclature Constructor
virtual ~nomenclature ()
bool saveToCSVFile ()
Private Member Functions
QString getNomenclature ()
nomenclature::getNomenclature Create and formated a nomenclature to csv file.
QString getElementInfo (Element *elmt)
nomenclature::getElementInfo
Private Attributes
QETProject * m_project
QList< Diagram * > m_list_diagram
QWidget * m_parent
Detailed Description
This class represents a nomenclature...
Definition at line 36 of file nomenclature.h.
Constructor & Destructor Documentation
nomenclature()
nomenclature::nomenclature (QETProject * project, QWidget * parent = nullptr)
nomenclature::nomenclature Constructor
Parameters
project : an project (QETProject) of QET file
parent
Definition at line 32 of file nomenclature.cpp.
References m_list_diagram, m_parent, and m_project.
~nomenclature()
nomenclature::~nomenclature () virtual
Destructor
Definition at line 43 of file nomenclature.cpp.
Member Function Documentation
getElementInfo()
QString nomenclature::getElementInfo (Element * elmt) private
nomenclature::getElementInfo
Parameters
elmt : the element to getinfo
Returns
: QString with information about element formated to csv file
Definition at line 170 of file nomenclature.cpp.
References Diagram::border_and_titleblock, QetGraphicsItem::diagram(), BorderTitleBlock::folio(), autonum::AssignVariables::formulaToLabel(), and Element::rSequenceStruct().
Referenced by getNomenclature().
getNomenclature()
QString nomenclature::getNomenclature () private
nomenclature::getNomenclature Create and formated a nomenclature to csv file.
Returns
The QString of nomenclature
Definition at line 90 of file nomenclature.cpp.
References ElementProvider::find(), ElementProvider::freeElement(), getElementInfo(), m_list_diagram, m_project, Element::Master, Element::Simple, Element::Slave, Element::Terminale, and QET::Icons::tr.
Referenced by saveToCSVFile().
saveToCSVFile()
bool nomenclature::saveToCSVFile ()
Save to csv file
Parameters
true if success
Definition at line 50 of file nomenclature.cpp.
References QET::QetMessageBox::critical(), getNomenclature(), m_parent, m_project, and QET::Icons::tr.
Member Data Documentation
m_list_diagram
QList<Diagram *> nomenclature::m_list_diagram private
Definition at line 40 of file nomenclature.h.
Referenced by getNomenclature(), and nomenclature().
m_parent
QWidget* nomenclature::m_parent private
Definition at line 41 of file nomenclature.h.
Referenced by nomenclature(), and saveToCSVFile().
m_project
QETProject* nomenclature::m_project private
Definition at line 39 of file nomenclature.h.
Referenced by getNomenclature(), nomenclature(), and saveToCSVFile().
The documentation for this class was generated from the following files:
nomenclature.h
nomenclature.cpp