QElectroTech: ShapeGraphicsItemPropertiesWidget Class Reference
ShapeGraphicsItemPropertiesWidget Class Reference
The ShapeGraphicsItemPropertiesWidget class Provide a widget to edit the properties of a QetShapeItem.
#include <shapegraphicsitempropertieswidget.h>
Public Slots
void apply () override
ShapeGraphicsItemPropertiesWidget::apply Apply the current change, by pushing an undo command to the undo stack of the shape diagram.
void reset () override
ShapeGraphicsItemPropertiesWidget::reset Reset the change.
Public Member Functions
ShapeGraphicsItemPropertiesWidget (QetShapeItem *item, QWidget *parent=nullptr)
ShapeGraphicsItemPropertiesWidget::ShapeGraphicsItemPropertiesWidget Constructor.
ShapeGraphicsItemPropertiesWidget (QList< QetShapeItem * > items_list, QWidget *parent=nullptr)
~ShapeGraphicsItemPropertiesWidget () override
ShapeGraphicsItemPropertiesWidget::~ShapeGraphicsItemPropertiesWidget Destructor.
void setItem (QetShapeItem *shape)
ShapeGraphicsItemPropertiesWidget::setItem Set shape as the current edited item.
void setItems (QList< QetShapeItem * > shapes_list)
ShapeGraphicsItemPropertiesWidget::setItems Set a list of shapes to be edited.
QUndoCommand * associatedUndo () const override
ShapeGraphicsItemPropertiesWidget::associatedUndo.
QString title () const override
PropertiesEditorWidget::title.
void updateUi () override
ShapeGraphicsItemPropertiesWidget::updateUi.
bool setLiveEdit (bool live_edit) override
ShapeGraphicsItemPropertiesWidget::setLiveEdit.
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual void apply ()
virtual void reset ()
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Private Slots
void on_m_lock_pos_cb_clicked ()
void on_m_color_kpb_changed (const QColor &newColor)
void on_m_brush_color_kpb_changed (const QColor &newColor)
Private Member Functions
void setUpEditConnection ()
ShapeGraphicsItemPropertiesWidget::setUpEditConnection Disconnect the previous connection, and reconnect the connection between the editors widgets and void ShapeGraphicsItemPropertiesWidget::apply function.
Private Attributes
Ui::ShapeGraphicsItemPropertiesWidget * ui
QetShapeItem * m_shape
QList< QPointer< QetShapeItem > > m_shapes_list
QList< QMetaObject::Connection > m_connect_list
QList< QMetaObject::Connection > m_edit_connection
Additional Inherited Members
Protected Member Functions inherited from PropertiesEditorWidget
virtual void enableLiveEdit ()
virtual void disableLiveEdit ()
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
The ShapeGraphicsItemPropertiesWidget class Provide a widget to edit the properties of a QetShapeItem.
Definition at line 33 of file shapegraphicsitempropertieswidget.h.
Constructor & Destructor Documentation
ShapeGraphicsItemPropertiesWidget() [1/2]
ShapeGraphicsItemPropertiesWidget::ShapeGraphicsItemPropertiesWidget (QetShapeItem * item, QWidget * parent = nullptr) explicit
ShapeGraphicsItemPropertiesWidget::ShapeGraphicsItemPropertiesWidget Constructor.
Parameters
item : shape to edit
parent : parent widget
Definition at line 30 of file shapegraphicsitempropertieswidget.cpp.
References setItem(), and ui.
ShapeGraphicsItemPropertiesWidget() [2/2]
ShapeGraphicsItemPropertiesWidget::ShapeGraphicsItemPropertiesWidget (QList< QetShapeItem * > items_list, QWidget * parent = nullptr)
Definition at line 39 of file shapegraphicsitempropertieswidget.cpp.
References setItems(), and ui.
~ShapeGraphicsItemPropertiesWidget()
ShapeGraphicsItemPropertiesWidget::~ShapeGraphicsItemPropertiesWidget () override
ShapeGraphicsItemPropertiesWidget::~ShapeGraphicsItemPropertiesWidget Destructor.
Definition at line 51 of file shapegraphicsitempropertieswidget.cpp.
References ui.
Member Function Documentation
apply
void ShapeGraphicsItemPropertiesWidget::apply () override slot
ShapeGraphicsItemPropertiesWidget::apply Apply the current change, by pushing an undo command to the undo stack of the shape diagram.
Definition at line 126 of file shapegraphicsitempropertieswidget.cpp.
References associatedUndo(), QetGraphicsItem::diagram(), m_shape, m_shapes_list, and Diagram::undoStack().
Referenced by on_m_brush_color_kpb_changed(), on_m_color_kpb_changed(), and setUpEditConnection().
associatedUndo()
QUndoCommand * ShapeGraphicsItemPropertiesWidget::associatedUndo () const override virtual
ShapeGraphicsItemPropertiesWidget::associatedUndo.
Returns
an undo command that represent the change edited by this widget. The returned undo command is a QPropertyUndoCommand with the properties "pen". If there isn't change, return nullptr
Reimplemented from PropertiesEditorWidget.
Definition at line 167 of file shapegraphicsitempropertieswidget.cpp.
References QetShapeItem::brush, QetShapeItem::isClosed(), PropertiesEditorWidget::m_live_edit, m_shape, m_shapes_list, QetShapeItem::pen, QET::Icons::tr, and ui.
Referenced by apply().
on_m_brush_color_kpb_changed
void ShapeGraphicsItemPropertiesWidget::on_m_brush_color_kpb_changed (const QColor & newColor) private slot
Definition at line 523 of file shapegraphicsitempropertieswidget.cpp.
References apply(), and PropertiesEditorWidget::m_live_edit.
on_m_color_kpb_changed
void ShapeGraphicsItemPropertiesWidget::on_m_color_kpb_changed (const QColor & newColor) private slot
Definition at line 516 of file shapegraphicsitempropertieswidget.cpp.
References apply(), and PropertiesEditorWidget::m_live_edit.
on_m_lock_pos_cb_clicked
void ShapeGraphicsItemPropertiesWidget::on_m_lock_pos_cb_clicked () private slot
Definition at line 504 of file shapegraphicsitempropertieswidget.cpp.
References m_shape, m_shapes_list, QetGraphicsItem::setMovable(), and ui.
reset
void ShapeGraphicsItemPropertiesWidget::reset () override slot
ShapeGraphicsItemPropertiesWidget::reset Reset the change.
Definition at line 157 of file shapegraphicsitempropertieswidget.cpp.
References updateUi().
setItem()
void ShapeGraphicsItemPropertiesWidget::setItem (QetShapeItem * shape)
ShapeGraphicsItemPropertiesWidget::setItem Set shape as the current edited item.
Parameters
shape
Definition at line 61 of file shapegraphicsitempropertieswidget.cpp.
References QetShapeItem::brushChanged(), QetShapeItem::closeChanged(), QetShapeItem::Line, m_connect_list, PropertiesEditorWidget::m_live_edit, m_shape, QetShapeItem::penChanged(), QetShapeItem::Polygon, setUpEditConnection(), QetShapeItem::shapeType(), ui, and updateUi().
Referenced by setItems(), and ShapeGraphicsItemPropertiesWidget().
setItems()
void ShapeGraphicsItemPropertiesWidget::setItems (QList< QetShapeItem * > shapes_list)
ShapeGraphicsItemPropertiesWidget::setItems Set a list of shapes to be edited.
Parameters
shapes_list
Definition at line 95 of file shapegraphicsitempropertieswidget.cpp.
References m_connect_list, m_shape, m_shapes_list, setItem(), setUpEditConnection(), and updateUi().
Referenced by ShapeGraphicsItemPropertiesWidget().
setLiveEdit()
bool ShapeGraphicsItemPropertiesWidget::setLiveEdit (bool live_edit) override virtual
ShapeGraphicsItemPropertiesWidget::setLiveEdit.
Parameters
live_edit
Returns
always true
Reimplemented from PropertiesEditorWidget.
Definition at line 462 of file shapegraphicsitempropertieswidget.cpp.
References m_edit_connection, PropertiesEditorWidget::m_live_edit, and setUpEditConnection().
setUpEditConnection()
void ShapeGraphicsItemPropertiesWidget::setUpEditConnection () private
ShapeGraphicsItemPropertiesWidget::setUpEditConnection Disconnect the previous connection, and reconnect the connection between the editors widgets and void ShapeGraphicsItemPropertiesWidget::apply function.
Definition at line 486 of file shapegraphicsitempropertieswidget.cpp.
References apply(), QetShapeItem::closeChanged(), m_edit_connection, m_shape, m_shapes_list, QetShapeItem::penChanged(), ui, and updateUi().
Referenced by setItem(), setItems(), setLiveEdit(), and updateUi().
title()
QString ShapeGraphicsItemPropertiesWidget::title () const inline override virtual
PropertiesEditorWidget::title.
Returns
the title of this editor
Reimplemented from PropertiesEditorWidget.
Definition at line 50 of file shapegraphicsitempropertieswidget.h.
References QET::Icons::tr.
updateUi()
void ShapeGraphicsItemPropertiesWidget::updateUi () override virtual
ShapeGraphicsItemPropertiesWidget::updateUi.
Reimplemented from PropertiesEditorWidget.
Definition at line 362 of file shapegraphicsitempropertieswidget.cpp.
References QetShapeItem::brush, QetShapeItem::isClosed(), QetGraphicsItem::isMovable(), m_edit_connection, m_shape, m_shapes_list, QetShapeItem::pen, QetShapeItem::Polygon, setUpEditConnection(), QetShapeItem::shapeType(), and ui.
Referenced by reset(), setItem(), setItems(), and setUpEditConnection().
Member Data Documentation
m_connect_list
QList<QMetaObject::Connection> ShapeGraphicsItemPropertiesWidget::m_connect_list private
Definition at line 66 of file shapegraphicsitempropertieswidget.h.
Referenced by setItem(), and setItems().
m_edit_connection
QList<QMetaObject::Connection> ShapeGraphicsItemPropertiesWidget::m_edit_connection private
Definition at line 67 of file shapegraphicsitempropertieswidget.h.
Referenced by setLiveEdit(), setUpEditConnection(), and updateUi().
m_shape
QetShapeItem* ShapeGraphicsItemPropertiesWidget::m_shape private
Definition at line 64 of file shapegraphicsitempropertieswidget.h.
Referenced by apply(), associatedUndo(), on_m_lock_pos_cb_clicked(), setItem(), setItems(), setUpEditConnection(), and updateUi().
m_shapes_list
QList<QPointer<QetShapeItem> > ShapeGraphicsItemPropertiesWidget::m_shapes_list private
Definition at line 65 of file shapegraphicsitempropertieswidget.h.
Referenced by apply(), associatedUndo(), on_m_lock_pos_cb_clicked(), setItems(), setUpEditConnection(), and updateUi().
ui
Ui::ShapeGraphicsItemPropertiesWidget* ShapeGraphicsItemPropertiesWidget::ui private
Definition at line 63 of file shapegraphicsitempropertieswidget.h.
Referenced by associatedUndo(), on_m_lock_pos_cb_clicked(), setItem(), setUpEditConnection(), ShapeGraphicsItemPropertiesWidget(), updateUi(), and ~ShapeGraphicsItemPropertiesWidget().
The documentation for this class was generated from the following files:
shapegraphicsitempropertieswidget.h
shapegraphicsitempropertieswidget.cpp