QElectroTech: ConductorProfile Class Reference
ConductorProfile Class Reference
#include <conductorprofile.h>
Public Member Functions
ConductorProfile ()
Constructeur.
ConductorProfile (Conductor *conductor)
ConductorProfile (const ConductorProfile &)
ConductorProfile & operator= (const ConductorProfile &)
virtual ~ConductorProfile ()
destructeur
bool isNull () const
void setNull ()
supprime les segments du profil de conducteur
qreal width () const
qreal height () const
uint segmentsCount (QET::ConductorSegmentType) const
QList< ConductorSegmentProfile * > horizontalSegments ()
QList< ConductorSegmentProfile * > verticalSegments ()
void fromConductor (Conductor *)
Public Attributes
QList< ConductorSegmentProfile * > segments
Segments composing the conductor.
Qet::Orientation beginOrientation
Orientation of the start terminal.
Qet::Orientation endOrientation
Orientation of the end terminal.
Detailed Description
This class represents the profile of a conductor, i.e. its primary characteristics.
Definition at line 28 of file conductorprofile.h.
Constructor & Destructor Documentation
ConductorProfile() [1/3]
ConductorProfile::ConductorProfile ()
Constructeur.
Definition at line 24 of file conductorprofile.cpp.
ConductorProfile() [2/3]
ConductorProfile::ConductorProfile (Conductor * conductor)
Constructeur
Parameters
conductor conducteur dont il faut extraire le profil
Definition at line 31 of file conductorprofile.cpp.
References fromConductor().
ConductorProfile() [3/3]
ConductorProfile::ConductorProfile (const ConductorProfile & c)
Constructeur de copie
Parameters
c autre conducteur
Definition at line 39 of file conductorprofile.cpp.
References beginOrientation, endOrientation, and segments.
~ConductorProfile()
ConductorProfile::~ConductorProfile () virtual
destructeur
Definition at line 67 of file conductorprofile.cpp.
References setNull().
Member Function Documentation
fromConductor()
void ConductorProfile::fromConductor (Conductor * conductor)
Reconstruit le profil a partir d'un conducteur existant
Definition at line 135 of file conductorprofile.cpp.
References beginOrientation, endOrientation, segments, and setNull().
Referenced by ConductorProfile().
height()
qreal ConductorProfile::height () const
Returns
la hauteur occupee par le conducteur
Definition at line 92 of file conductorprofile.cpp.
References segments.
Referenced by Conductor::updateConductorPath().
horizontalSegments()
QList< ConductorSegmentProfile * > ConductorProfile::horizontalSegments ()
Returns
les segments horizontaux de ce profil
Definition at line 115 of file conductorprofile.cpp.
References segments.
Referenced by Conductor::updateConductorPath().
isNull()
bool ConductorProfile::isNull () const
Returns
true si le profil est nul
Definition at line 72 of file conductorprofile.cpp.
References segments.
Referenced by Conductor::updateConductorPath().
operator=()
ConductorProfile & ConductorProfile::operator= (const ConductorProfile & c)
Operateur =
Parameters
c autre conducteur
Definition at line 51 of file conductorprofile.cpp.
References beginOrientation, endOrientation, segments, and setNull().
segmentsCount()
uint ConductorProfile::segmentsCount (QET::ConductorSegmentType type) const
Parameters
type Type de Segments
Returns
Le nombre de segments composant le conducteur.
Definition at line 104 of file conductorprofile.cpp.
References QET::Both, QET::Horizontal, segments, and QET::Vertical.
Referenced by Conductor::updateConductorPath().
setNull()
void ConductorProfile::setNull ()
supprime les segments du profil de conducteur
Definition at line 77 of file conductorprofile.cpp.
References segments.
Referenced by fromConductor(), operator=(), and ~ConductorProfile().
verticalSegments()
QList< ConductorSegmentProfile * > ConductorProfile::verticalSegments ()
Returns
les segments verticaux de ce profil
Definition at line 124 of file conductorprofile.cpp.
References segments.
Referenced by Conductor::updateConductorPath().
width()
qreal ConductorProfile::width () const
Returns
la largeur occupee par le conducteur
Definition at line 83 of file conductorprofile.cpp.
References segments.
Referenced by Conductor::updateConductorPath().
Member Data Documentation
beginOrientation
Qet::Orientation ConductorProfile::beginOrientation
Orientation of the start terminal.
Definition at line 42 of file conductorprofile.h.
Referenced by ConductorProfile(), fromConductor(), and operator=().
endOrientation
Qet::Orientation ConductorProfile::endOrientation
Orientation of the end terminal.
Definition at line 44 of file conductorprofile.h.
Referenced by ConductorProfile(), fromConductor(), and operator=().
segments
QList<ConductorSegmentProfile *> ConductorProfile::segments
Segments composing the conductor.
Definition at line 40 of file conductorprofile.h.
Referenced by ConductorProfile(), fromConductor(), height(), horizontalSegments(), isNull(), operator<<(), operator=(), segmentsCount(), setNull(), Conductor::updateConductorPath(), verticalSegments(), and width().
The documentation for this class was generated from the following files:
conductorprofile.h
conductorprofile.cpp