QElectroTech: PolygonEditor Class Reference
PolygonEditor Class Reference
#include <polygoneditor.h>
Public Member Functions
PolygonEditor (QETElementEditor *editor, PartPolygon *part=nullptr, QWidget *parent=nullptr)
PolygonEditor::PolygonEditor.
~PolygonEditor () override
PolygonEditor::~PolygonEditor.
bool setPart (CustomElementPart *part) override
PolygonEditor::setPart.
CustomElementPart * currentPart () const override
PolygonEditor::currentPart.
QList< CustomElementPart * > currentParts () const override
void updateForm () override
PolygonEditor::updateForm Update the widget.
QVector< QPointF > pointsFromTree ()
PolygonEditor::pointsFromTree.
bool eventFilter (QObject *watched, QEvent *event) override
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
virtual bool setParts (QList< CustomElementPart * >)
Private Slots
void on_m_close_polygon_cb_stateChanged (int arg1)
PolygonEditor::on_m_close_polygon_cb_stateChanged.
void on_m_points_list_tree_itemChanged (QTreeWidgetItem *item, int column)
PolygonEditor::on_m_points_list_tree_itemChanged Update the polygon according to the current value of the tree editor.
void on_m_points_list_tree_itemSelectionChanged ()
PolygonEditor::on_m_points_list_tree_itemSelectionChanged Used to change the color of the current selected point.
void on_m_add_point_action_triggered ()
void on_m_remove_point_action_triggered ()
Private Member Functions
void setUpChangeConnections ()
setUpChangeConnections Setup the connection from the line(s) to the widget, to update it when the line(s) are changed (moved ...)
void disconnectChangeConnections ()
Private Attributes
Ui::PolygonEditor * ui
StyleEditor * m_style = nullptr
PartPolygon * m_part = nullptr
QList< QMetaObject::Connection > m_change_connections
Detailed Description
Definition at line 31 of file polygoneditor.h.
Constructor & Destructor Documentation
PolygonEditor()
PolygonEditor::PolygonEditor (QETElementEditor * editor, PartPolygon * part = nullptr, QWidget * parent = nullptr) explicit
PolygonEditor::PolygonEditor.
Parameters
editor
part
parent
Definition at line 32 of file polygoneditor.cpp.
References m_style, ui, and updateForm().
~PolygonEditor()
PolygonEditor::~PolygonEditor () override
PolygonEditor::~PolygonEditor.
Definition at line 51 of file polygoneditor.cpp.
References ui.
Member Function Documentation
currentPart()
CustomElementPart * PolygonEditor::currentPart () const override virtual
PolygonEditor::currentPart.
Returns
the curent edited part
Implements ElementItemEditor.
Definition at line 118 of file polygoneditor.cpp.
References m_part.
currentParts()
QList< CustomElementPart * > PolygonEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 122 of file polygoneditor.cpp.
References StyleEditor::currentParts(), and m_style.
disconnectChangeConnections()
void PolygonEditor::disconnectChangeConnections () private
Definition at line 75 of file polygoneditor.cpp.
References m_change_connections.
Referenced by setPart().
eventFilter()
bool PolygonEditor::eventFilter (QObject * watched, QEvent * event) override
Definition at line 177 of file polygoneditor.cpp.
References m_part, PartPolygon::resetAllHandlerColor(), and ui.
on_m_add_point_action_triggered
void PolygonEditor::on_m_add_point_action_triggered () private slot
Definition at line 279 of file polygoneditor.cpp.
References ElementItemEditor::elementScene(), m_part, PartPolygon::polygon, PartPolygon::resetAllHandlerColor(), PartPolygon::setHandlerColor(), QET::Icons::tr, ui, and ElementScene::undoStack().
on_m_close_polygon_cb_stateChanged
void PolygonEditor::on_m_close_polygon_cb_stateChanged (int arg1) private slot
PolygonEditor::on_m_close_polygon_cb_stateChanged.
Definition at line 193 of file polygoneditor.cpp.
References PartPolygon::isClosed(), m_part, CustomElementGraphicPart::property(), QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_points_list_tree_itemChanged
void PolygonEditor::on_m_points_list_tree_itemChanged (QTreeWidgetItem * item, int column) private slot
PolygonEditor::on_m_points_list_tree_itemChanged Update the polygon according to the current value of the tree editor.
Definition at line 217 of file polygoneditor.cpp.
References m_part, pointsFromTree(), PartPolygon::polygon, CustomElementGraphicPart::property(), QET::Icons::tr, ElementItemEditor::undoStack(), and QET::QetMessageBox::warning().
on_m_points_list_tree_itemSelectionChanged
void PolygonEditor::on_m_points_list_tree_itemSelectionChanged () private slot
PolygonEditor::on_m_points_list_tree_itemSelectionChanged Used to change the color of the current selected point.
Definition at line 254 of file polygoneditor.cpp.
References m_part, PartPolygon::polygon, PartPolygon::resetAllHandlerColor(), PartPolygon::setHandlerColor(), and ui.
on_m_remove_point_action_triggered
void PolygonEditor::on_m_remove_point_action_triggered () private slot
Definition at line 314 of file polygoneditor.cpp.
References ElementItemEditor::elementScene(), m_part, PartPolygon::polygon, QET::Icons::tr, ui, and ElementScene::undoStack().
pointsFromTree()
QVector< QPointF > PolygonEditor::pointsFromTree ()
PolygonEditor::pointsFromTree.
Returns
the point of polygon from the current value of the tree editor if part coordinate.
Definition at line 157 of file polygoneditor.cpp.
References m_part, and ui.
Referenced by on_m_points_list_tree_itemChanged().
setPart()
bool PolygonEditor::setPart (CustomElementPart * new_part) override virtual
PolygonEditor::setPart.
Parameters
new_part
Returns
Implements ElementItemEditor.
Definition at line 88 of file polygoneditor.cpp.
References disconnectChangeConnections(), m_part, setUpChangeConnections(), and updateForm().
setUpChangeConnections()
void PolygonEditor::setUpChangeConnections () private
setUpChangeConnections Setup the connection from the line(s) to the widget, to update it when the line(s) are changed (moved ...)
Definition at line 55 of file polygoneditor.cpp.
References PartPolygon::closedChange(), m_change_connections, m_part, PartPolygon::polygonChanged(), and updateForm().
Referenced by setPart().
updateForm()
void PolygonEditor::updateForm () override virtual
PolygonEditor::updateForm Update the widget.
Implements ElementItemEditor.
Definition at line 130 of file polygoneditor.cpp.
References PartPolygon::isClosed(), m_part, PartPolygon::polygon, and ui.
Referenced by PolygonEditor(), setPart(), and setUpChangeConnections().
Member Data Documentation
m_change_connections
QList<QMetaObject::Connection> PolygonEditor::m_change_connections private
Definition at line 66 of file polygoneditor.h.
Referenced by disconnectChangeConnections(), and setUpChangeConnections().
m_part
PartPolygon* PolygonEditor::m_part = nullptr private
Definition at line 65 of file polygoneditor.h.
Referenced by currentPart(), eventFilter(), on_m_add_point_action_triggered(), on_m_close_polygon_cb_stateChanged(), on_m_points_list_tree_itemChanged(), on_m_points_list_tree_itemSelectionChanged(), on_m_remove_point_action_triggered(), pointsFromTree(), setPart(), setUpChangeConnections(), and updateForm().
m_style
StyleEditor* PolygonEditor::m_style = nullptr private
Definition at line 64 of file polygoneditor.h.
Referenced by currentParts(), and PolygonEditor().
ui
Ui::PolygonEditor* PolygonEditor::ui private
Definition at line 63 of file polygoneditor.h.
Referenced by eventFilter(), on_m_add_point_action_triggered(), on_m_close_polygon_cb_stateChanged(), on_m_points_list_tree_itemSelectionChanged(), on_m_remove_point_action_triggered(), pointsFromTree(), PolygonEditor(), updateForm(), and ~PolygonEditor().
The documentation for this class was generated from the following files:
polygoneditor.h
polygoneditor.cpp