QElectroTech: AutoNumberingDockWidget Class Reference
AutoNumberingDockWidget Class Reference
#include <autonumberingdockwidget.h>
Public Slots
void setActive ()
AutoNumberingDockWidget::setActive Set current used autonumberings.
void setConductorActive (DiagramView *)
AutoNumberingDockWidget::setConductorActive.
Signals
void folioAutoNumChanged (QString)
Public Member Functions
AutoNumberingDockWidget (QWidget *parent=nullptr)
AutoNumberingDockWidget::AutoNumberingDockWidget Constructor.
~AutoNumberingDockWidget () override
AutoNumberingDockWidget::~AutoNumberingDockWidget Destructor.
void setContext ()
AutoNumberingDockWidget::setContext Add all itens to comboboxes.
void setProject (QETProject *, ProjectView *)
AutoNumberingDockWidget::setProject.
Private Slots
void on_m_conductor_cb_activated (int)
AutoNumberingDockWidget::on_m_conductor_cb_activated Set new conductor AutoNum.
void on_m_element_cb_activated (int)
AutoNumberingDockWidget::on_m_element_cb_activated Set new element AutoNum.
void on_m_folio_cb_activated (int)
AutoNumberingDockWidget::on_m_folio_cb_activated Set new folio AutoNum.
void conductorAutoNumChanged ()
AutoNumberingDockWidget::conductorAutoNumChanged Add new or remove conductor auto num from combobox.
void elementAutoNumChanged ()
AutoNumberingDockWidget::elementAutoNumChanged Add new or remove element auto num from combobox.
void folioAutoNumChanged ()
AutoNumberingDockWidget::folioAutoNumChanged Add new or remove folio auto num from combobox.
void clear ()
AutoNumberingDockWidget::clear Remove all combo box values.
void projectClosed ()
void on_m_configure_pb_clicked ()
Private Attributes
Ui::AutoNumberingDockWidget * ui
QETProject * m_project = nullptr
ProjectView * m_project_view = nullptr
Detailed Description
Definition at line 29 of file autonumberingdockwidget.h.
Constructor & Destructor Documentation
AutoNumberingDockWidget()
AutoNumberingDockWidget::AutoNumberingDockWidget (QWidget * parent = nullptr) explicit
AutoNumberingDockWidget::AutoNumberingDockWidget Constructor.
Parameters
parent : parent widget
Definition at line 32 of file autonumberingdockwidget.cpp.
References ui.
~AutoNumberingDockWidget()
AutoNumberingDockWidget::~AutoNumberingDockWidget () override
AutoNumberingDockWidget::~AutoNumberingDockWidget Destructor.
Definition at line 44 of file autonumberingdockwidget.cpp.
References ui.
Member Function Documentation
clear
void AutoNumberingDockWidget::clear () private slot
AutoNumberingDockWidget::clear Remove all combo box values.
Definition at line 54 of file autonumberingdockwidget.cpp.
References ui.
Referenced by projectClosed(), and setContext().
conductorAutoNumChanged
void AutoNumberingDockWidget::conductorAutoNumChanged () private slot
AutoNumberingDockWidget::conductorAutoNumChanged Add new or remove conductor auto num from combobox.
Definition at line 212 of file autonumberingdockwidget.cpp.
References QETProject::conductorAutoNum(), m_project, setActive(), and ui.
Referenced by setProject().
elementAutoNumChanged
void AutoNumberingDockWidget::elementAutoNumChanged () private slot
AutoNumberingDockWidget::elementAutoNumChanged Add new or remove element auto num from combobox.
Definition at line 241 of file autonumberingdockwidget.cpp.
References QETProject::elementAutoNum(), m_project, setActive(), and ui.
Referenced by setProject().
folioAutoNumChanged [1/2]
void AutoNumberingDockWidget::folioAutoNumChanged () private slot
AutoNumberingDockWidget::folioAutoNumChanged Add new or remove folio auto num from combobox.
Definition at line 268 of file autonumberingdockwidget.cpp.
References QETProject::folioAutoNum(), m_project, setActive(), and ui.
Referenced by on_m_folio_cb_activated(), and setProject().
folioAutoNumChanged [2/2]
void AutoNumberingDockWidget::folioAutoNumChanged (QString) signal
on_m_conductor_cb_activated
void AutoNumberingDockWidget::on_m_conductor_cb_activated (int) private slot
AutoNumberingDockWidget::on_m_conductor_cb_activated Set new conductor AutoNum.
Definition at line 228 of file autonumberingdockwidget.cpp.
References ProjectView::currentDiagram(), DiagramView::diagram(), Diagram::loadCndFolioSeq(), m_project, m_project_view, Diagram::setConductorsAutonumName(), QETProject::setCurrentConductorAutoNum(), and ui.
on_m_configure_pb_clicked
void AutoNumberingDockWidget::on_m_configure_pb_clicked () private slot
Definition at line 300 of file autonumberingdockwidget.cpp.
References ProjectPropertiesDialog::Autonum, ProjectPropertiesDialog::exec(), m_project, and ProjectPropertiesDialog::setCurrentPage().
on_m_element_cb_activated
void AutoNumberingDockWidget::on_m_element_cb_activated (int) private slot
AutoNumberingDockWidget::on_m_element_cb_activated Set new element AutoNum.
Definition at line 258 of file autonumberingdockwidget.cpp.
References ProjectView::currentDiagram(), DiagramView::diagram(), Diagram::loadElmtFolioSeq(), m_project, m_project_view, QETProject::setCurrrentElementAutonum(), and ui.
on_m_folio_cb_activated
void AutoNumberingDockWidget::on_m_folio_cb_activated (int) private slot
AutoNumberingDockWidget::on_m_folio_cb_activated Set new folio AutoNum.
Definition at line 285 of file autonumberingdockwidget.cpp.
References TitleBlockProperties::folio, folioAutoNumChanged(), m_project, TitleBlockProperties::setAutoPageNum(), QETProject::setDefaultTitleBlockProperties(), and ui.
projectClosed
void AutoNumberingDockWidget::projectClosed () private slot
Definition at line 61 of file autonumberingdockwidget.cpp.
References clear(), m_project, and m_project_view.
Referenced by setProject().
setActive
void AutoNumberingDockWidget::setActive () slot
AutoNumberingDockWidget::setActive Set current used autonumberings.
Definition at line 183 of file autonumberingdockwidget.cpp.
References TitleBlockProperties::auto_page_num, Diagram::conductorsAutonumName(), ProjectView::currentDiagram(), QETProject::defaultTitleBlockProperties(), DiagramView::diagram(), QETProject::elementAutoNumCurrentFormula(), QETProject::elementCurrentAutoNum(), TitleBlockProperties::folio, m_project, m_project_view, and ui.
Referenced by conductorAutoNumChanged(), elementAutoNumChanged(), folioAutoNumChanged(), setContext(), and setProject().
setConductorActive
void AutoNumberingDockWidget::setConductorActive (DiagramView * dv) slot
AutoNumberingDockWidget::setConductorActive.
Parameters
dv activated diagramview
Definition at line 171 of file autonumberingdockwidget.cpp.
References Diagram::conductorsAutonumName(), DiagramView::diagram(), and ui.
Referenced by setProject().
setContext()
void AutoNumberingDockWidget::setContext ()
AutoNumberingDockWidget::setContext Add all itens to comboboxes.
Definition at line 139 of file autonumberingdockwidget.cpp.
References clear(), QETProject::conductorAutoNum(), QETProject::elementAutoNum(), QETProject::folioAutoNum(), m_project, setActive(), and ui.
Referenced by setProject().
setProject()
void AutoNumberingDockWidget::setProject (QETProject * project, ProjectView * projectview)
AutoNumberingDockWidget::setProject.
Parameters
project project to be setted
projectview projectview to be setted assign Project and ProjectView, connect all signals and setContext
Definition at line 75 of file autonumberingdockwidget.cpp.
References Diagram::border_and_titleblock, conductorAutoNumChanged(), ProjectView::currentDiagram(), DiagramView::diagram(), elementAutoNumChanged(), folioAutoNumChanged(), m_project, m_project_view, projectClosed(), setActive(), setConductorActive(), setContext(), QET::Icons::tr, and ui.
Referenced by QETDiagramEditor::addProject(), and QETDiagramEditor::slot_updateAutoNumDock().
Member Data Documentation
m_project
QETProject* AutoNumberingDockWidget::m_project = nullptr private
Definition at line 61 of file autonumberingdockwidget.h.
Referenced by conductorAutoNumChanged(), elementAutoNumChanged(), folioAutoNumChanged(), on_m_conductor_cb_activated(), on_m_configure_pb_clicked(), on_m_element_cb_activated(), on_m_folio_cb_activated(), projectClosed(), setActive(), setContext(), and setProject().
m_project_view
ProjectView* AutoNumberingDockWidget::m_project_view = nullptr private
Definition at line 62 of file autonumberingdockwidget.h.
Referenced by on_m_conductor_cb_activated(), on_m_element_cb_activated(), projectClosed(), setActive(), and setProject().
ui
Ui::AutoNumberingDockWidget* AutoNumberingDockWidget::ui private
Definition at line 60 of file autonumberingdockwidget.h.
Referenced by AutoNumberingDockWidget(), clear(), conductorAutoNumChanged(), elementAutoNumChanged(), folioAutoNumChanged(), on_m_conductor_cb_activated(), on_m_element_cb_activated(), on_m_folio_cb_activated(), setActive(), setConductorActive(), setContext(), setProject(), and ~AutoNumberingDockWidget().
The documentation for this class was generated from the following files:
autonumberingdockwidget.h
autonumberingdockwidget.cpp