QElectroTech: PasteDiagramCommand Class Reference
PasteDiagramCommand Class Reference
The PasteDiagramCommand class This command pastes some content onto a particular diagram.
#include <diagramcommands.h>
Public Member Functions
PasteDiagramCommand (Diagram *, const DiagramContent &, QUndoCommand *=nullptr)
PasteDiagramCommand::PasteDiagramCommand Constructor.
~PasteDiagramCommand () override
PasteDiagramCommand::~PasteDiagramCommand Destructor.
void undo () override
PasteDiagramCommand::undo Undo this command.
void redo () override
PasteDiagramCommand::redo Redo this commnand.
Private Member Functions
PasteDiagramCommand (const PasteDiagramCommand &)
Private Attributes
DiagramContent content
pasted content
Diagram * diagram
diagram content is pasted onto
int filter
filter stating what kinds of items should be pasted
bool first_redo
prevent the first call to redo()
Detailed Description
The PasteDiagramCommand class This command pastes some content onto a particular diagram.
Definition at line 88 of file diagramcommands.h.
Constructor & Destructor Documentation
PasteDiagramCommand() [1/2]
PasteDiagramCommand::PasteDiagramCommand (Diagram * dia, const DiagramContent & c, QUndoCommand * parent = nullptr)
PasteDiagramCommand::PasteDiagramCommand Constructor.
Parameters
dia : diagram where we must to paste
c : content to past
parent : parent undo command
Definition at line 52 of file diagramcommands.cpp.
References content, diagram, filter, DiagramContent::items(), DiagramContent::sentence(), and QET::Icons::tr.
~PasteDiagramCommand()
PasteDiagramCommand::~PasteDiagramCommand () override
PasteDiagramCommand::~PasteDiagramCommand Destructor.
Definition at line 67 of file diagramcommands.cpp.
References content, diagram, filter, and DiagramContent::items().
PasteDiagramCommand() [2/2]
PasteDiagramCommand::PasteDiagramCommand (const PasteDiagramCommand &) private
Member Function Documentation
redo()
void PasteDiagramCommand::redo () override
PasteDiagramCommand::redo Redo this commnand.
Definition at line 87 of file diagramcommands.cpp.
References Diagram::addItem(), DiagramContext::addValue(), content, diagram, filter, first_redo, DiagramContent::items(), DiagramContent::m_conductors_to_move, DiagramContent::m_elements, and ConductorProperties::text.
undo()
void PasteDiagramCommand::undo () override
PasteDiagramCommand::undo Undo this command.
Definition at line 75 of file diagramcommands.cpp.
References content, diagram, filter, DiagramContent::items(), and Diagram::removeItem().
Member Data Documentation
content
DiagramContent PasteDiagramCommand::content private
pasted content
Definition at line 105 of file diagramcommands.h.
Referenced by PasteDiagramCommand(), redo(), undo(), and ~PasteDiagramCommand().
diagram
Diagram* PasteDiagramCommand::diagram private
diagram content is pasted onto
Definition at line 107 of file diagramcommands.h.
Referenced by PasteDiagramCommand(), redo(), undo(), and ~PasteDiagramCommand().
filter
int PasteDiagramCommand::filter private
filter stating what kinds of items should be pasted
Definition at line 109 of file diagramcommands.h.
Referenced by PasteDiagramCommand(), redo(), undo(), and ~PasteDiagramCommand().
first_redo
bool PasteDiagramCommand::first_redo private
prevent the first call to redo()
Definition at line 111 of file diagramcommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
diagramcommands.h
diagramcommands.cpp