QElectroTech: PastePartsCommand Class Reference
PastePartsCommand Class Reference
The PastePartsCommand class Undo command for paste element primitive in an element editor.
#include <pastepartscommand.h>
Public Member Functions
PastePartsCommand (ElementView *view, const ElementContent &content_to_paste, QUndoCommand *parent=nullptr)
PastePartsCommand::PastePartsCommand.
~PastePartsCommand () override
PastePartsCommand::~PastePartsCommand.
void undo () override
PastePartsCommand::undo.
void redo () override
PastePartsCommand::redo.
virtual void setOffset (int old_offset_paste_count, const QPointF &old_start_top_left_corner, int new_offset_paste_count, const QPointF &new_start_top_left_corner)
PastePartsCommand::setOffset Describe the offset to use with this undo command.
Public Member Functions inherited from ElementEditionCommand
ElementEditionCommand (ElementScene *=nullptr, ElementView *=nullptr, QUndoCommand *=nullptr)
ElementEditionCommand::ElementEditionCommand Constructs an ElementEditionCommand, thus embedding the provided scene and view.
ElementEditionCommand (const QString &, ElementScene *=nullptr, ElementView *=nullptr, QUndoCommand *=nullptr)
ElementEditionCommand::ElementEditionCommand Constructs an ElementEditionCommand, thus embedding the provided scene and view.
~ElementEditionCommand () override
ElementScene * elementScene () const
void setElementScene (ElementScene *)
ElementView * elementView () const
void setElementView (ElementView *)
Private Member Functions
PastePartsCommand (const PastePartsCommand &)
Private Attributes
ElementContent m_pasted_content
int m_old_offset_paste_count
int m_new_offset_paste_count
QPointF m_old_start_top_left_corner
QPointF m_new_start_top_left_corner
bool m_uses_offset = false
bool m_first_redo = true
Additional Inherited Members
Protected Attributes inherited from ElementEditionCommand
ElementScene * m_scene
Element editor/view/scene the command should take place on.
ElementView * m_view
Detailed Description
The PastePartsCommand class Undo command for paste element primitive in an element editor.
Definition at line 30 of file pastepartscommand.h.
Constructor & Destructor Documentation
PastePartsCommand() [1/2]
PastePartsCommand::PastePartsCommand (ElementView * view, const ElementContent & content_to_paste, QUndoCommand * parent = nullptr)
PastePartsCommand::PastePartsCommand.
Parameters
view : view where this command work
content_to_paste : content to paste
parent : parent undo command
Note
all terminal stored in content_to_paste get a new uuid in the constructor of this class to avoid have several terminal of an element with the same uuid.
Definition at line 31 of file pastepartscommand.cpp.
References m_pasted_content, ElementEditionCommand::m_scene, QGIManager::manage(), ElementScene::qgiManager(), PartTerminal::setNewUuid(), QET::Icons::tr, and PartTerminal::Type.
~PastePartsCommand()
PastePartsCommand::~PastePartsCommand () override
PastePartsCommand::~PastePartsCommand.
Definition at line 52 of file pastepartscommand.cpp.
References m_pasted_content, ElementEditionCommand::m_scene, ElementScene::qgiManager(), and QGIManager::release().
PastePartsCommand() [2/2]
PastePartsCommand::PastePartsCommand (const PastePartsCommand &) private
Member Function Documentation
redo()
void PastePartsCommand::redo () override
PastePartsCommand::redo.
Definition at line 80 of file pastepartscommand.cpp.
References ElementView::adjustSceneRect(), m_first_redo, m_new_offset_paste_count, m_new_start_top_left_corner, m_pasted_content, ElementEditionCommand::m_scene, m_uses_offset, ElementEditionCommand::m_view, ElementView::offset_paste_count_, ElementScene::slot_select(), and ElementView::start_top_left_corner_.
setOffset()
void PastePartsCommand::setOffset (int old_offset_paste_count, const QPointF & old_start_top_left_corner, int new_offset_paste_count, const QPointF & new_start_top_left_corner) virtual
PastePartsCommand::setOffset Describe the offset to use with this undo command.
Parameters
old_offset_paste_count
old_start_top_left_corner
new_offset_paste_count
new_start_top_left_corner
Definition at line 110 of file pastepartscommand.cpp.
References m_new_offset_paste_count, m_new_start_top_left_corner, m_old_offset_paste_count, m_old_start_top_left_corner, and m_uses_offset.
undo()
void PastePartsCommand::undo () override
PastePartsCommand::undo.
Definition at line 60 of file pastepartscommand.cpp.
References ElementView::adjustSceneRect(), m_old_offset_paste_count, m_old_start_top_left_corner, m_pasted_content, ElementEditionCommand::m_scene, m_uses_offset, ElementEditionCommand::m_view, ElementView::offset_paste_count_, and ElementView::start_top_left_corner_.
Referenced by EllipseEditor::editingFinishedH(), EllipseEditor::editingFinishedV(), EllipseEditor::editingFinishedX(), and EllipseEditor::editingFinishedY().
Member Data Documentation
m_first_redo
bool PastePartsCommand::m_first_redo = true private
Definition at line 53 of file pastepartscommand.h.
Referenced by redo().
m_new_offset_paste_count
int PastePartsCommand::m_new_offset_paste_count private
Definition at line 47 of file pastepartscommand.h.
Referenced by redo(), and setOffset().
m_new_start_top_left_corner
QPointF PastePartsCommand::m_new_start_top_left_corner private
Definition at line 50 of file pastepartscommand.h.
Referenced by redo(), and setOffset().
m_old_offset_paste_count
int PastePartsCommand::m_old_offset_paste_count private
Definition at line 46 of file pastepartscommand.h.
Referenced by setOffset(), and undo().
m_old_start_top_left_corner
QPointF PastePartsCommand::m_old_start_top_left_corner private
Definition at line 49 of file pastepartscommand.h.
Referenced by setOffset(), and undo().
m_pasted_content
ElementContent PastePartsCommand::m_pasted_content private
Definition at line 44 of file pastepartscommand.h.
Referenced by PastePartsCommand(), redo(), undo(), and ~PastePartsCommand().
m_uses_offset
bool PastePartsCommand::m_uses_offset = false private
Definition at line 52 of file pastepartscommand.h.
Referenced by redo(), setOffset(), and undo().
The documentation for this class was generated from the following files:
pastepartscommand.h
pastepartscommand.cpp