QElectroTech: SearchAndReplaceWidget Class Reference
SearchAndReplaceWidget Class Reference
#include <searchandreplacewidget.h>
Public Member Functions
SearchAndReplaceWidget (QWidget *parent=nullptr)
SearchAndReplaceWidget::SearchAndReplaceWidget Constructor.
~SearchAndReplaceWidget () override
SearchAndReplaceWidget::~SearchAndReplaceWidget Destructor.
bool event (QEvent *event) override
SearchAndReplaceWidget::event Reimplemented to clear the the lines edit and hide the advanced widgets, when this widget become hidden.
void clear ()
SearchAndReplaceWidget::clear Clear the content of the search and replace line edit Clear all tree items in the tree widget (except the category items).
void setEditor (QETDiagramEditor *editor)
SearchAndReplaceWidget::setEditor Set the diagram editor of this widget.
Private Slots
void on_m_quit_button_clicked ()
SearchAndReplaceWidget::on_m_quit_button_clicked.
void on_m_advanced_pb_toggled (bool checked)
void on_m_tree_widget_itemDoubleClicked (QTreeWidgetItem *item, int column)
void on_m_reload_pb_clicked ()
void on_m_tree_widget_currentItemChanged (QTreeWidgetItem *current, QTreeWidgetItem *previous)
void on_m_next_pb_clicked ()
void on_m_previous_pb_clicked ()
void on_m_folio_pb_clicked ()
void on_m_replace_pb_clicked ()
SearchAndReplaceWidget::on_m_replace_pb_clicked Replace the current selection.
void on_m_replace_all_pb_clicked ()
SearchAndReplaceWidget::on_m_replace_all_pb_clicked Replace all checked item.
void on_m_element_pb_clicked ()
void on_m_mode_cb_currentIndexChanged (int index)
SearchAndReplaceWidget::on_m_mode_cb_currentIndexChanged Update the search when user change mode.
void on_m_case_sensitive_cb_stateChanged (int arg1)
SearchAndReplaceWidget::on_m_case_sensitive_cb_stateChanged Update the search when change the case sensitive.
void on_m_conductor_pb_clicked ()
SearchAndReplaceWidget::on_m_conductor_pb_clicked Open a dialog to edit the condutor properties.
void on_m_advanced_replace_pb_clicked ()
SearchAndReplaceWidget::on_m_advanced_replace_pb_clicked Open the advanced editor.
Private Member Functions
void setUpTreeItems ()
SearchAndReplaceWidget::setUpTreeItems Set up the main tree widget items.
void setHideAdvanced (bool hide)
SearchAndReplaceWidget::setHideAdvanced Hide advanced widgets.
void fillItemsList ()
SearchAndReplaceWidget::fillItemsList Fill the tree.
void addElement (Element *element)
SearchAndReplaceWidget::addElement Add a tree widget item for element.
void search ()
SearchAndReplaceWidget::search Start the search.
void setVisibleAllParents (QTreeWidgetItem *item, bool expend_parent=true)
SearchAndReplaceWidget::setVisibleAllParents Set visible all parents of item until the invisible root item.
QTreeWidgetItem * nextItem (QTreeWidgetItem *item=nullptr, QTreeWidgetItemIterator::IteratorFlag flags=QTreeWidgetItemIterator::All) const
SearchAndReplaceWidget::nextItem.
QTreeWidgetItem * previousItem (QTreeWidgetItem *item=nullptr, QTreeWidgetItemIterator::IteratorFlag flags=QTreeWidgetItemIterator::All) const
SearchAndReplaceWidget::previousItem.
void updateNextPreviousButtons ()
SearchAndReplaceWidget::updateNextPreviousButtons According to the current item, if there is a next or a previous item, we enable/disable the buttons next/previous item.
void itemChanged (QTreeWidgetItem *item, int column)
SearchAndReplaceWidget::itemChanged Reimplemented from QTreeWidget. Use to update the check state of items.
void setChildCheckState (QTreeWidgetItem *item, Qt::CheckState check, bool deep=true)
SearchAndReplaceWidget::setChildCheckState.
void updateParentCheckState (QTreeWidgetItem *item, bool all_parents=true)
SearchAndReplaceWidget::updateParentCheckState.
void activateNextChecked ()
SearchAndReplaceWidget::activateNextChecked Activate the next checked (and visible) item.
QList< Diagram * > selectedDiagram () const
SearchAndReplaceWidget::selectedDiagram.
QList< Element * > selectedElement () const
SearchAndReplaceWidget::selectedElement.
QList< Conductor * > selectedConductor () const
SearchAndReplaceWidget::selectedConductor.
QList< IndependentTextItem * > selectedText () const
SearchAndReplaceWidget::selectedText.
Static Private Member Functions
static QStringList searchTerms (Diagram *diagram)
SearchAndReplaceWidget::searchTerms.
static QStringList searchTerms (Element *element)
SearchAndReplaceWidget::searchTerms.
static QStringList searchTerms (Conductor *conductor)
SearchAndReplaceWidget::searchTerms.
static QStringList searchTerms (QString str)
Private Attributes
Ui::SearchAndReplaceWidget * ui
QETDiagramEditor * m_editor
QTreeWidgetItem * m_root_qtwi = nullptr
QTreeWidgetItem * m_folio_qtwi = nullptr
QTreeWidgetItem * m_indi_text_qtwi = nullptr
QTreeWidgetItem * m_elements_qtwi = nullptr
QTreeWidgetItem * m_simple_elmt_qtwi = nullptr
QTreeWidgetItem * m_master_elmt_qtwi = nullptr
QTreeWidgetItem * m_slave_elmt_qtwi = nullptr
QTreeWidgetItem * m_report_elmt_qtwi = nullptr
QTreeWidgetItem * m_terminal_elmt_qtwi = nullptr
QTreeWidgetItem * m_conductor_qtwi = nullptr
QList< QTreeWidgetItem * > m_qtwi_elmts
QList< QTreeWidgetItem * > m_category_qtwi
QHash< QTreeWidgetItem *, QPointer< Element > > m_element_hash
QHash< QTreeWidgetItem *, QPointer< IndependentTextItem > > m_text_hash
QHash< QTreeWidgetItem *, QPointer< Conductor > > m_conductor_hash
QPointer< Element > m_highlighted_element
QPointer< QGraphicsObject > m_last_selected
QHash< QTreeWidgetItem *, QPointer< Diagram > > m_diagram_hash
SearchAndReplaceWorker m_worker
QWidgetAnimation * m_vertical_animation
QWidgetAnimation * m_horizontal_animation
Detailed Description
Definition at line 37 of file searchandreplacewidget.h.
Constructor & Destructor Documentation
SearchAndReplaceWidget()
SearchAndReplaceWidget::SearchAndReplaceWidget (QWidget * parent = nullptr) explicit
SearchAndReplaceWidget::SearchAndReplaceWidget Constructor.
Parameters
parent
Definition at line 43 of file searchandreplacewidget.cpp.
References QWidgetAnimation::availableSpace, QET::Horizontal, m_horizontal_animation, m_vertical_animation, QWidgetAnimation::minimumSizeHint, search(), setHideAdvanced(), setUpTreeItems(), ui, QET::Vertical, and QWidgetAnimation::widgetToSubtract().
~SearchAndReplaceWidget()
SearchAndReplaceWidget::~SearchAndReplaceWidget () override
SearchAndReplaceWidget::~SearchAndReplaceWidget Destructor.
Definition at line 73 of file searchandreplacewidget.cpp.
References ui.
Member Function Documentation
activateNextChecked()
void SearchAndReplaceWidget::activateNextChecked () private
SearchAndReplaceWidget::activateNextChecked Activate the next checked (and visible) item.
Definition at line 656 of file searchandreplacewidget.cpp.
References on_m_next_pb_clicked(), and ui.
Referenced by on_m_replace_pb_clicked().
addElement()
void SearchAndReplaceWidget::addElement (Element * element) private
SearchAndReplaceWidget::addElement Add a tree widget item for element.
Parameters
element
Definition at line 315 of file searchandreplacewidget.cpp.
References Element::elementInformations(), Element::linkType(), m_element_hash, m_elements_qtwi, m_master_elmt_qtwi, m_report_elmt_qtwi, m_simple_elmt_qtwi, m_slave_elmt_qtwi, m_terminal_elmt_qtwi, Element::Master, Element::NextReport, Element::PreviousReport, searchTerms(), Element::Simple, Element::Slave, Element::Terminale, QET::Icons::tr, and DiagramContext::value().
Referenced by fillItemsList().
clear()
void SearchAndReplaceWidget::clear ()
SearchAndReplaceWidget::clear Clear the content of the search and replace line edit Clear all tree items in the tree widget (except the category items).
Definition at line 110 of file searchandreplacewidget.cpp.
References itemChanged(), m_category_qtwi, m_conductor_hash, m_diagram_hash, m_element_hash, m_text_hash, ui, and updateNextPreviousButtons().
Referenced by event(), and on_m_reload_pb_clicked().
event()
bool SearchAndReplaceWidget::event (QEvent * event) override
SearchAndReplaceWidget::event Reimplemented to clear the the lines edit and hide the advanced widgets, when this widget become hidden.
Parameters
event
Returns
Definition at line 84 of file searchandreplacewidget.cpp.
References clear(), fillItemsList(), QET::Icons::Hide, m_highlighted_element, m_root_qtwi, and ui.
fillItemsList()
void SearchAndReplaceWidget::fillItemsList () private
SearchAndReplaceWidget::fillItemsList Fill the tree.
Definition at line 233 of file searchandreplacewidget.cpp.
References addElement(), QETDiagramEditor::currentProject(), QETProject::diagrams(), itemChanged(), m_conductor_hash, m_conductor_qtwi, m_diagram_hash, m_editor, m_element_hash, DiagramContent::m_elements, m_folio_qtwi, m_indi_text_qtwi, DiagramContent::m_potential_conductors, m_qtwi_elmts, DiagramContent::m_text_fields, m_text_hash, on_m_reload_pb_clicked(), Conductor::properties, searchTerms(), ConductorProperties::text, ui, and updateNextPreviousButtons().
Referenced by event(), and on_m_reload_pb_clicked().
itemChanged()
void SearchAndReplaceWidget::itemChanged (QTreeWidgetItem * item, int column) private
SearchAndReplaceWidget::itemChanged Reimplemented from QTreeWidget. Use to update the check state of items.
Parameters
item
column
Definition at line 575 of file searchandreplacewidget.cpp.
References setChildCheckState(), ui, and updateParentCheckState().
Referenced by clear(), and fillItemsList().
nextItem()
QTreeWidgetItem * SearchAndReplaceWidget::nextItem (QTreeWidgetItem * item = nullptr, QTreeWidgetItemIterator::IteratorFlag flags = QTreeWidgetItemIterator::All) const private
SearchAndReplaceWidget::nextItem.
Parameters
item : find the next item from item, if item is nullptr, start the search for the root of the tree
flags
Returns
the next item according to flag or nullptr if there is not a next item
Definition at line 461 of file searchandreplacewidget.cpp.
References QET::Icons::it, m_root_qtwi, and ui.
Referenced by on_m_next_pb_clicked(), and updateNextPreviousButtons().
on_m_advanced_pb_toggled
void SearchAndReplaceWidget::on_m_advanced_pb_toggled (bool checked) private slot
Definition at line 860 of file searchandreplacewidget.cpp.
References setHideAdvanced().
on_m_advanced_replace_pb_clicked
void SearchAndReplaceWidget::on_m_advanced_replace_pb_clicked () private slot
SearchAndReplaceWidget::on_m_advanced_replace_pb_clicked Open the advanced editor.
Definition at line 1268 of file searchandreplacewidget.cpp.
References replaceAdvancedDialog::advancedStruct(), SearchAndReplaceWorker::m_advanced_struct, m_worker, QET::Icons::tr, and ui.
on_m_case_sensitive_cb_stateChanged
void SearchAndReplaceWidget::on_m_case_sensitive_cb_stateChanged (int arg1) private slot
SearchAndReplaceWidget::on_m_case_sensitive_cb_stateChanged Update the search when change the case sensitive.
Parameters
arg1
Definition at line 1226 of file searchandreplacewidget.cpp.
References search().
on_m_conductor_pb_clicked
void SearchAndReplaceWidget::on_m_conductor_pb_clicked () private slot
SearchAndReplaceWidget::on_m_conductor_pb_clicked Open a dialog to edit the condutor properties.
Definition at line 1236 of file searchandreplacewidget.cpp.
References SearchAndReplaceWorker::invalidConductorProperties(), SearchAndReplaceWorker::m_conductor_properties, m_worker, ReplaceConductorDialog::properties(), QET::Icons::tr, and ui.
on_m_element_pb_clicked
void SearchAndReplaceWidget::on_m_element_pb_clicked () private slot
Definition at line 1183 of file searchandreplacewidget.cpp.
References ReplaceElementDialog::context(), SearchAndReplaceWorker::m_element_context, m_worker, QET::Icons::tr, and ui.
on_m_folio_pb_clicked
void SearchAndReplaceWidget::on_m_folio_pb_clicked () private slot
Definition at line 1022 of file searchandreplacewidget.cpp.
References SearchAndReplaceWorker::m_titleblock_properties, m_worker, ReplaceFolioDialog::setTitleBlockProperties(), ReplaceFolioDialog::titleBlockProperties(), QET::Icons::tr, and ui.
on_m_mode_cb_currentIndexChanged
void SearchAndReplaceWidget::on_m_mode_cb_currentIndexChanged (int index) private slot
SearchAndReplaceWidget::on_m_mode_cb_currentIndexChanged Update the search when user change mode.
Parameters
index
Definition at line 1215 of file searchandreplacewidget.cpp.
References search().
on_m_next_pb_clicked
void SearchAndReplaceWidget::on_m_next_pb_clicked () private slot
Definition at line 973 of file searchandreplacewidget.cpp.
References m_category_qtwi, nextItem(), on_m_tree_widget_itemDoubleClicked(), and ui.
Referenced by activateNextChecked(), on_m_previous_pb_clicked(), and search().
on_m_previous_pb_clicked
void SearchAndReplaceWidget::on_m_previous_pb_clicked () private slot
Definition at line 992 of file searchandreplacewidget.cpp.
References m_category_qtwi, on_m_next_pb_clicked(), on_m_tree_widget_itemDoubleClicked(), previousItem(), and ui.
on_m_quit_button_clicked
void SearchAndReplaceWidget::on_m_quit_button_clicked () private slot
SearchAndReplaceWidget::on_m_quit_button_clicked.
Definition at line 849 of file searchandreplacewidget.cpp.
on_m_reload_pb_clicked
void SearchAndReplaceWidget::on_m_reload_pb_clicked () private slot
Definition at line 900 of file searchandreplacewidget.cpp.
References clear(), fillItemsList(), m_highlighted_element, m_last_selected, m_root_qtwi, and ui.
Referenced by fillItemsList(), and on_m_replace_all_pb_clicked().
on_m_replace_all_pb_clicked
void SearchAndReplaceWidget::on_m_replace_all_pb_clicked () private slot
SearchAndReplaceWidget::on_m_replace_all_pb_clicked Replace all checked item.
Definition at line 1151 of file searchandreplacewidget.cpp.
References SearchAndReplaceWorker::m_indi_text, m_worker, on_m_reload_pb_clicked(), SearchAndReplaceWorker::replaceAdvanced(), SearchAndReplaceWorker::replaceConductor(), SearchAndReplaceWorker::replaceDiagram(), SearchAndReplaceWorker::replaceElement(), SearchAndReplaceWorker::replaceIndiText(), search(), selectedConductor(), selectedDiagram(), selectedElement(), selectedText(), QET::Icons::tr, and ui.
on_m_replace_pb_clicked
void SearchAndReplaceWidget::on_m_replace_pb_clicked () private slot
SearchAndReplaceWidget::on_m_replace_pb_clicked Replace the current selection.
Definition at line 1053 of file searchandreplacewidget.cpp.
References activateNextChecked(), m_category_qtwi, m_conductor_hash, m_diagram_hash, m_element_hash, SearchAndReplaceWorker::m_indi_text, m_text_hash, m_worker, SearchAndReplaceWorker::replaceAdvanced(), SearchAndReplaceWorker::replaceConductor(), SearchAndReplaceWorker::replaceDiagram(), SearchAndReplaceWorker::replaceElement(), SearchAndReplaceWorker::replaceIndiText(), QET::Icons::tr, and ui.
on_m_tree_widget_currentItemChanged
void SearchAndReplaceWidget::on_m_tree_widget_currentItemChanged (QTreeWidgetItem * current, QTreeWidgetItem * previous) private slot
Definition at line 919 of file searchandreplacewidget.cpp.
References m_category_qtwi, m_conductor_hash, m_element_hash, m_highlighted_element, m_last_selected, m_text_hash, ui, and updateNextPreviousButtons().
on_m_tree_widget_itemDoubleClicked
void SearchAndReplaceWidget::on_m_tree_widget_itemDoubleClicked (QTreeWidgetItem * item, int column) private slot
Definition at line 864 of file searchandreplacewidget.cpp.
References m_conductor_hash, m_diagram_hash, m_element_hash, and m_text_hash.
Referenced by on_m_next_pb_clicked(), and on_m_previous_pb_clicked().
previousItem()
QTreeWidgetItem * SearchAndReplaceWidget::previousItem (QTreeWidgetItem * item = nullptr, QTreeWidgetItemIterator::IteratorFlag flags = QTreeWidgetItemIterator::All) const private
SearchAndReplaceWidget::previousItem.
Parameters
item : find the previous item from item, if item is nullptr, start the search for the root of the tree
flags
Returns
the previous item according to flag or nullptr if there is not a previous item
Definition at line 494 of file searchandreplacewidget.cpp.
References QET::Icons::it, m_root_qtwi, and ui.
Referenced by on_m_previous_pb_clicked(), and updateNextPreviousButtons().
search()
void SearchAndReplaceWidget::search () private
SearchAndReplaceWidget::search Start the search.
Definition at line 359 of file searchandreplacewidget.cpp.
References QET::Icons::it, m_category_qtwi, m_conductor_hash, m_diagram_hash, m_element_hash, m_root_qtwi, m_text_hash, on_m_next_pb_clicked(), setVisibleAllParents(), and ui.
Referenced by on_m_case_sensitive_cb_stateChanged(), on_m_mode_cb_currentIndexChanged(), on_m_replace_all_pb_clicked(), and SearchAndReplaceWidget().
searchTerms() [1/4]
QStringList SearchAndReplaceWidget::searchTerms (Conductor * conductor) static private
SearchAndReplaceWidget::searchTerms.
Parameters
conductor
Returns
all QString use as terms for search.
Definition at line 832 of file searchandreplacewidget.cpp.
References ConductorProperties::m_function, ConductorProperties::m_tension_protocol, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, Conductor::properties, and ConductorProperties::text.
searchTerms() [2/4]
QStringList SearchAndReplaceWidget::searchTerms (Diagram * diagram) static private
SearchAndReplaceWidget::searchTerms.
Parameters
diagram
Returns
All QStrings use as terms for search.
Definition at line 764 of file searchandreplacewidget.cpp.
References TitleBlockProperties::author, Diagram::border_and_titleblock, TitleBlockProperties::context, TitleBlockProperties::date, BorderTitleBlock::exportTitleBlock(), TitleBlockProperties::filename, TitleBlockProperties::folio, TitleBlockProperties::indexrev, DiagramContext::keys(), TitleBlockProperties::locmach, TitleBlockProperties::plant, TitleBlockProperties::title, and DiagramContext::value().
Referenced by addElement(), and fillItemsList().
searchTerms() [3/4]
QStringList SearchAndReplaceWidget::searchTerms (Element * element) static private
SearchAndReplaceWidget::searchTerms.
Parameters
element
Returns
All QString use as terms for search
Definition at line 789 of file searchandreplacewidget.cpp.
References DynamicElementTextItem::CompositeText, Element::dynamicTextItems(), QETApp::elementInfoKeys(), Element::elementInformations(), Element::textGroups(), DynamicElementTextItem::UserText, and DiagramContext::value().
searchTerms() [4/4]
static QStringList SearchAndReplaceWidget::searchTerms (QString str) static private
selectedConductor()
QList< Conductor * > SearchAndReplaceWidget::selectedConductor () const private
SearchAndReplaceWidget::selectedConductor.
Returns
The list of visible and selected conductor in the tree widget
Definition at line 717 of file searchandreplacewidget.cpp.
References m_conductor_hash.
Referenced by on_m_replace_all_pb_clicked().
selectedDiagram()
QList< Diagram * > SearchAndReplaceWidget::selectedDiagram () const private
SearchAndReplaceWidget::selectedDiagram.
Returns
The list of visible and selected diagram in the tree widget
Definition at line 673 of file searchandreplacewidget.cpp.
References m_diagram_hash.
Referenced by on_m_replace_all_pb_clicked().
selectedElement()
QList< Element * > SearchAndReplaceWidget::selectedElement () const private
SearchAndReplaceWidget::selectedElement.
Returns
The list of visible and selected element in the tree widget
Definition at line 695 of file searchandreplacewidget.cpp.
References m_element_hash.
Referenced by on_m_replace_all_pb_clicked().
selectedText()
QList< IndependentTextItem * > SearchAndReplaceWidget::selectedText () const private
SearchAndReplaceWidget::selectedText.
Returns
The list of visible and selected independant text in the tree widget
Definition at line 740 of file searchandreplacewidget.cpp.
References m_text_hash.
Referenced by on_m_replace_all_pb_clicked().
setChildCheckState()
void SearchAndReplaceWidget::setChildCheckState (QTreeWidgetItem * item, Qt::CheckState check, bool deep = true) private
SearchAndReplaceWidget::setChildCheckState.
Parameters
item : Parent of the items to be evaluated
check : check state
deep : if true, we evaluate every subchilds.
Definition at line 592 of file searchandreplacewidget.cpp.
Referenced by itemChanged().
setEditor()
void SearchAndReplaceWidget::setEditor (QETDiagramEditor * editor)
SearchAndReplaceWidget::setEditor Set the diagram editor of this widget.
Parameters
editor
Definition at line 144 of file searchandreplacewidget.cpp.
References m_editor.
Referenced by QETDiagramEditor::QETDiagramEditor().
setHideAdvanced()
void SearchAndReplaceWidget::setHideAdvanced (bool hide) private
SearchAndReplaceWidget::setHideAdvanced Hide advanced widgets.
Parameters
hide
Definition at line 223 of file searchandreplacewidget.cpp.
References m_horizontal_animation, m_vertical_animation, and QWidgetAnimation::setHidden().
Referenced by on_m_advanced_pb_toggled(), and SearchAndReplaceWidget().
setUpTreeItems()
void SearchAndReplaceWidget::setUpTreeItems () private
SearchAndReplaceWidget::setUpTreeItems Set up the main tree widget items.
Definition at line 152 of file searchandreplacewidget.cpp.
References QET::Icons::Conductor, QET::Icons::Diagram, QET::Icons::Element, QET::Icons::ElementMaster, QET::Icons::ElementSlave, QET::Icons::ElementTerminal, QET::Icons::FolioXrefComing, m_category_qtwi, m_conductor_qtwi, m_elements_qtwi, m_folio_qtwi, m_indi_text_qtwi, m_master_elmt_qtwi, m_qtwi_elmts, m_report_elmt_qtwi, m_root_qtwi, m_simple_elmt_qtwi, m_slave_elmt_qtwi, m_terminal_elmt_qtwi, QET::Icons::PartText, QET::Icons::ProjectProperties, QET::Icons::tr, ui, and updateNextPreviousButtons().
Referenced by SearchAndReplaceWidget().
setVisibleAllParents()
void SearchAndReplaceWidget::setVisibleAllParents (QTreeWidgetItem * item, bool expend_parent = true) private
SearchAndReplaceWidget::setVisibleAllParents Set visible all parents of item until the invisible root item.
Parameters
item
expend_parent
Definition at line 441 of file searchandreplacewidget.cpp.
Referenced by search().
updateNextPreviousButtons()
void SearchAndReplaceWidget::updateNextPreviousButtons () private
SearchAndReplaceWidget::updateNextPreviousButtons According to the current item, if there is a next or a previous item, we enable/disable the buttons next/previous item.
Definition at line 524 of file searchandreplacewidget.cpp.
References m_category_qtwi, nextItem(), previousItem(), and ui.
Referenced by clear(), fillItemsList(), on_m_tree_widget_currentItemChanged(), and setUpTreeItems().
updateParentCheckState()
void SearchAndReplaceWidget::updateParentCheckState (QTreeWidgetItem * item, bool all_parents = true) private
SearchAndReplaceWidget::updateParentCheckState.
Parameters
item : a child item of the parent to be evaluated.
all_parents : if true, we evaluate every parents, until the root item.
Definition at line 611 of file searchandreplacewidget.cpp.
Referenced by itemChanged().
Member Data Documentation
m_category_qtwi
QList<QTreeWidgetItem *> SearchAndReplaceWidget::m_category_qtwi private
Definition at line 118 of file searchandreplacewidget.h.
Referenced by clear(), on_m_next_pb_clicked(), on_m_previous_pb_clicked(), on_m_replace_pb_clicked(), on_m_tree_widget_currentItemChanged(), search(), setUpTreeItems(), and updateNextPreviousButtons().
m_conductor_hash
QHash<QTreeWidgetItem *, QPointer <Conductor> > SearchAndReplaceWidget::m_conductor_hash private
Definition at line 122 of file searchandreplacewidget.h.
Referenced by clear(), fillItemsList(), on_m_replace_pb_clicked(), on_m_tree_widget_currentItemChanged(), on_m_tree_widget_itemDoubleClicked(), search(), and selectedConductor().
m_conductor_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_conductor_qtwi = nullptr private
Definition at line 116 of file searchandreplacewidget.h.
Referenced by fillItemsList(), and setUpTreeItems().
m_diagram_hash
QHash<QTreeWidgetItem *, QPointer <Diagram> > SearchAndReplaceWidget::m_diagram_hash private
Definition at line 125 of file searchandreplacewidget.h.
Referenced by clear(), fillItemsList(), on_m_replace_pb_clicked(), on_m_tree_widget_itemDoubleClicked(), search(), and selectedDiagram().
m_editor
QETDiagramEditor* SearchAndReplaceWidget::m_editor private
Definition at line 106 of file searchandreplacewidget.h.
Referenced by fillItemsList(), and setEditor().
m_element_hash
QHash<QTreeWidgetItem *, QPointer <Element> > SearchAndReplaceWidget::m_element_hash private
Definition at line 119 of file searchandreplacewidget.h.
Referenced by addElement(), clear(), fillItemsList(), on_m_replace_pb_clicked(), on_m_tree_widget_currentItemChanged(), on_m_tree_widget_itemDoubleClicked(), search(), and selectedElement().
m_elements_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_elements_qtwi = nullptr private
Definition at line 110 of file searchandreplacewidget.h.
Referenced by addElement(), and setUpTreeItems().
m_folio_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_folio_qtwi = nullptr private
Definition at line 108 of file searchandreplacewidget.h.
Referenced by fillItemsList(), and setUpTreeItems().
m_highlighted_element
QPointer<Element> SearchAndReplaceWidget::m_highlighted_element private
Definition at line 123 of file searchandreplacewidget.h.
Referenced by event(), on_m_reload_pb_clicked(), and on_m_tree_widget_currentItemChanged().
m_horizontal_animation
QWidgetAnimation* SearchAndReplaceWidget::m_horizontal_animation private
Definition at line 128 of file searchandreplacewidget.h.
Referenced by SearchAndReplaceWidget(), and setHideAdvanced().
m_indi_text_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_indi_text_qtwi = nullptr private
Definition at line 109 of file searchandreplacewidget.h.
Referenced by fillItemsList(), and setUpTreeItems().
m_last_selected
QPointer<QGraphicsObject> SearchAndReplaceWidget::m_last_selected private
Definition at line 124 of file searchandreplacewidget.h.
Referenced by on_m_reload_pb_clicked(), and on_m_tree_widget_currentItemChanged().
m_master_elmt_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_master_elmt_qtwi = nullptr private
Definition at line 112 of file searchandreplacewidget.h.
Referenced by addElement(), and setUpTreeItems().
m_qtwi_elmts
QList<QTreeWidgetItem *> SearchAndReplaceWidget::m_qtwi_elmts private
Definition at line 117 of file searchandreplacewidget.h.
Referenced by fillItemsList(), and setUpTreeItems().
m_report_elmt_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_report_elmt_qtwi = nullptr private
Definition at line 114 of file searchandreplacewidget.h.
Referenced by addElement(), and setUpTreeItems().
m_root_qtwi
QTreeWidgetItem* SearchAndReplaceWidget::m_root_qtwi = nullptr private
Definition at line 107 of file searchandreplacewidget.h.
Referenced by event(), nextItem(), on_m_reload_pb_clicked(), previousItem(), search(), and setUpTreeItems().
m_simple_elmt_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_simple_elmt_qtwi = nullptr private
Definition at line 111 of file searchandreplacewidget.h.
Referenced by addElement(), and setUpTreeItems().
m_slave_elmt_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_slave_elmt_qtwi = nullptr private
Definition at line 113 of file searchandreplacewidget.h.
Referenced by addElement(), and setUpTreeItems().
m_terminal_elmt_qtwi
QTreeWidgetItem * SearchAndReplaceWidget::m_terminal_elmt_qtwi = nullptr private
Definition at line 115 of file searchandreplacewidget.h.
Referenced by addElement(), and setUpTreeItems().
m_text_hash
QHash<QTreeWidgetItem *, QPointer <IndependentTextItem> > SearchAndReplaceWidget::m_text_hash private
Definition at line 121 of file searchandreplacewidget.h.
Referenced by clear(), fillItemsList(), on_m_replace_pb_clicked(), on_m_tree_widget_currentItemChanged(), on_m_tree_widget_itemDoubleClicked(), search(), and selectedText().
m_vertical_animation
QWidgetAnimation* SearchAndReplaceWidget::m_vertical_animation private
Definition at line 127 of file searchandreplacewidget.h.
Referenced by SearchAndReplaceWidget(), and setHideAdvanced().
m_worker
SearchAndReplaceWorker SearchAndReplaceWidget::m_worker private
Definition at line 126 of file searchandreplacewidget.h.
Referenced by on_m_advanced_replace_pb_clicked(), on_m_conductor_pb_clicked(), on_m_element_pb_clicked(), on_m_folio_pb_clicked(), on_m_replace_all_pb_clicked(), and on_m_replace_pb_clicked().
ui
Ui::SearchAndReplaceWidget* SearchAndReplaceWidget::ui private
Definition at line 105 of file searchandreplacewidget.h.
Referenced by activateNextChecked(), clear(), event(), fillItemsList(), itemChanged(), nextItem(), on_m_advanced_replace_pb_clicked(), on_m_conductor_pb_clicked(), on_m_element_pb_clicked(), on_m_folio_pb_clicked(), on_m_next_pb_clicked(), on_m_previous_pb_clicked(), on_m_reload_pb_clicked(), on_m_replace_all_pb_clicked(), on_m_replace_pb_clicked(), on_m_tree_widget_currentItemChanged(), previousItem(), search(), SearchAndReplaceWidget(), setUpTreeItems(), updateNextPreviousButtons(), and ~SearchAndReplaceWidget().
The documentation for this class was generated from the following files:
searchandreplacewidget.h
searchandreplacewidget.cpp