QElectroTech: FileElementCollectionItem Class Reference
FileElementCollectionItem Class Reference
The FileElementCollectionItem class This class specialise ElementCollectionItem for manage a collection in a file system. They represente a directory or an element.
#include <fileelementcollectionitem.h>
Public Types
enum { Type = UserType+2 }
Public Types inherited from ElementCollectionItem
enum { Type = UserType+1 }
Public Member Functions
FileElementCollectionItem ()
FileElementCollectionItem::FileElementCollectionItem Constructor.
int type () const override
bool setRootPath (const QString &path, bool set_data=true, bool hide_element=false)
FileElementCollectionItem::setRootPath Set path has root path for this file item. Use this function only to set the beginning of a file collection.
QString fileSystemPath () const
FileElementCollectionItem::fileSystemPath.
QString dirPath () const
FileElementCollectionItem::dirPath.
bool isDir () const override
FileElementCollectionItem::isDir.
bool isElement () const override
FileElementCollectionItem::isElement.
QString localName () override
FileElementCollectionItem::localName.
QString localName (const ElementsLocation &location)
FileElementCollectionItem::localName Surcharged method, unlike the default method, avoid to create an elementLocation and so, gain time.
QString name () const override
FileElementCollectionItem::name.
QString collectionPath () const override
FileElementCollectionItem::collectionPath.
bool isCollectionRoot () const override
FileElementCollectionItem::isCollectionRoot.
bool isCommonCollection () const
FileElementCollectionItem::isCommonCollection.
bool isCustomCollection () const
FileElementCollectionItem::isCustomCollection.
void addChildAtPath (const QString &collection_name) override
FileElementCollectionItem::addChildAtPath Ask to this item item to add a child with collection name collection_name.
void setUpData () override
FileElementCollectionItem::setUpData SetUp the data of this item.
void setUpIcon () override
FileElementCollectionItem::setUpIcon SetUp the icon of this item. Because icon use several memory, we use this method for setup icon instead setUpData.
Public Member Functions inherited from ElementCollectionItem
ElementCollectionItem ()
ElementCollectionItem::ElementCollectionItem Constructor.
int type () const override
virtual void clearData ()
ElementCollectionItem::clearData Reset the data.
ElementCollectionItem * lastItemForPath (const QString &path, QString &no_found_path)
ElementCollectionItem::lastItemForPath Return the last existing item in this ElementCollectionItem hierarchy according to the given path. Next_item is the first non existing item in this hierarchy according to the given path.
ElementCollectionItem * childWithCollectionName (const QString &name) const
ElementCollectionItem::childWithCollectionName Return the child with the collection name name, else return nullptr.
QList< QStandardItem * > directChilds () const
ElementCollectionItem::directChilds Return the direct child of this item.
int rowForInsertItem (const QString &name)
ElementCollectionItem::rowForInsertItem Return the row for insert a new child item to this item with name.
ElementCollectionItem * itemAtPath (const QString &path)
ElementCollectionItem::itemAtPath.
QList< ElementCollectionItem * > elementsDirectChild () const
ElementCollectionItem::elementsDirectChild.
QList< ElementCollectionItem * > directoriesDirectChild () const
ElementCollectionItem::directoriesDirectChild.
QList< ElementCollectionItem * > elementsChild () const
ElementCollectionItem::elementsChild.
QList< ElementCollectionItem * > directoriesChild () const
ElementCollectionItem::directoriesChild.
QList< ElementCollectionItem * > items () const
ElementCollectionItem::items.
Private Member Functions
void setPathName (const QString &path_name, bool set_data=true, bool hide_element=false)
FileElementCollectionItem::setPathName Set the name of this item in the file system path. This item must have a parent, because they should be a child item of another. For create a new file collection see setRootPath.
void populate (bool set_data=true, bool hide_element=false)
FileElementCollectionItem::populate Create the childs of this item.
Private Attributes
QString m_path
Detailed Description
The FileElementCollectionItem class This class specialise ElementCollectionItem for manage a collection in a file system. They represente a directory or an element.
Definition at line 29 of file fileelementcollectionitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 34 of file fileelementcollectionitem.h.
Constructor & Destructor Documentation
FileElementCollectionItem()
FileElementCollectionItem::FileElementCollectionItem ()
FileElementCollectionItem::FileElementCollectionItem Constructor.
Definition at line 30 of file fileelementcollectionitem.cpp.
Referenced by addChildAtPath(), and populate().
Member Function Documentation
addChildAtPath()
void FileElementCollectionItem::addChildAtPath (const QString & collection_name) override virtual
FileElementCollectionItem::addChildAtPath Ask to this item item to add a child with collection name collection_name.
Parameters
collection_name
Implements ElementCollectionItem.
Definition at line 249 of file fileelementcollectionitem.cpp.
References FileElementCollectionItem(), ElementCollectionItem::rowForInsertItem(), setPathName(), and setUpData().
Referenced by ElementsCollectionModel::dropMimeData().
collectionPath()
QString FileElementCollectionItem::collectionPath () const override virtual
FileElementCollectionItem::collectionPath.
Returns
The path of this item relative to the collection.
Implements ElementCollectionItem.
Definition at line 191 of file fileelementcollectionitem.cpp.
References ElementCollectionItem::collectionPath(), QETApp::commonElementsDirN(), ElementCollectionItem::isCollectionRoot(), isCollectionRoot(), m_path, Type, and type().
Referenced by ElementsCollectionModel::dropMimeData(), ElementsCollectionWidget::editDirectory(), localName(), ElementsCollectionWidget::newDirectory(), ElementsCollectionWidget::newElement(), setUpData(), and setUpIcon().
dirPath()
QString FileElementCollectionItem::dirPath () const
FileElementCollectionItem::dirPath.
Returns
the dir path of this item (if this item is a dir return the path, if item is an element return the path of the parent directory)
Definition at line 79 of file fileelementcollectionitem.cpp.
References fileSystemPath(), isDir(), Type, and type().
fileSystemPath()
QString FileElementCollectionItem::fileSystemPath () const
FileElementCollectionItem::fileSystemPath.
Returns
the file system path of this item
Definition at line 61 of file fileelementcollectionitem.cpp.
References fileSystemPath(), isCollectionRoot(), and m_path.
Referenced by dirPath(), ElementsCollectionModel::dropMimeData(), fileSystemPath(), isCommonCollection(), isCustomCollection(), localName(), and populate().
isCollectionRoot()
bool FileElementCollectionItem::isCollectionRoot () const override virtual
FileElementCollectionItem::isCollectionRoot.
Returns
true if this item represent the root of collection
Implements ElementCollectionItem.
Definition at line 216 of file fileelementcollectionitem.cpp.
References QETApp::commonElementsDirN(), QETApp::customElementsDirN(), and m_path.
Referenced by collectionPath(), ElementsCollectionWidget::customContextMenu(), fileSystemPath(), localName(), name(), and setUpIcon().
isCommonCollection()
bool FileElementCollectionItem::isCommonCollection () const
FileElementCollectionItem::isCommonCollection.
Returns
True if this item represent the common collection
Definition at line 229 of file fileelementcollectionitem.cpp.
References QETApp::commonElementsDirN(), and fileSystemPath().
Referenced by ElementsCollectionWidget::customContextMenu(), ElementsCollectionModel::dropMimeData(), ElementsCollectionWidget::editDirectory(), ElementsCollectionWidget::newDirectory(), and ElementsCollectionWidget::newElement().
isCustomCollection()
bool FileElementCollectionItem::isCustomCollection () const
FileElementCollectionItem::isCustomCollection.
Returns
True if this item represent the custom collection
Definition at line 238 of file fileelementcollectionitem.cpp.
References QETApp::customElementsDirN(), and fileSystemPath().
Referenced by ElementsCollectionModel::addLocation().
isDir()
bool FileElementCollectionItem::isDir () const override virtual
FileElementCollectionItem::isDir.
Returns
true if this item represent a directory
Implements ElementCollectionItem.
Definition at line 93 of file fileelementcollectionitem.cpp.
References m_path.
Referenced by ElementsCollectionWidget::customContextMenu(), dirPath(), isElement(), localName(), setUpData(), and setUpIcon().
isElement()
bool FileElementCollectionItem::isElement () const override virtual
FileElementCollectionItem::isElement.
Returns
true if this item represent an element
Implements ElementCollectionItem.
Definition at line 106 of file fileelementcollectionitem.cpp.
References isDir().
Referenced by ElementsCollectionModel::dropMimeData(), and localName().
localName() [1/2]
QString FileElementCollectionItem::localName () override virtual
FileElementCollectionItem::localName.
Returns
the located name of this item
Implements ElementCollectionItem.
Definition at line 115 of file fileelementcollectionitem.cpp.
References collectionPath(), QETApp::commonElementsDirN(), QETApp::customElementsDirN(), fileSystemPath(), isCollectionRoot(), isDir(), isElement(), m_path, ElementsLocation::name(), QET::Icons::nl, and QET::Icons::tr.
Referenced by localName(), and setUpData().
localName() [2/2]
QString FileElementCollectionItem::localName (const ElementsLocation & location)
FileElementCollectionItem::localName Surcharged method, unlike the default method, avoid to create an elementLocation and so, gain time.
Parameters
location
Returns
Definition at line 160 of file fileelementcollectionitem.cpp.
References isDir(), isElement(), localName(), and ElementsLocation::name().
name()
QString FileElementCollectionItem::name () const override virtual
FileElementCollectionItem::name.
Returns
The collection name of this item
Implements ElementCollectionItem.
Definition at line 179 of file fileelementcollectionitem.cpp.
References isCollectionRoot(), and m_path.
populate()
void FileElementCollectionItem::populate (bool set_data = true, bool hide_element = false) private
FileElementCollectionItem::populate Create the childs of this item.
Parameters
set_data : if true, call setUpData for every child of this item
hide_element
Definition at line 350 of file fileelementcollectionitem.cpp.
References FileElementCollectionItem(), fileSystemPath(), setPathName(), and setUpData().
Referenced by setPathName(), and setRootPath().
setPathName()
void FileElementCollectionItem::setPathName (const QString & path_name, bool set_data = true, bool hide_element = false) private
FileElementCollectionItem::setPathName Set the name of this item in the file system path. This item must have a parent, because they should be a child item of another. For create a new file collection see setRootPath.
Parameters
path_name
set_data
hide_element
Definition at line 333 of file fileelementcollectionitem.cpp.
References m_path, and populate().
Referenced by addChildAtPath(), and populate().
setRootPath()
bool FileElementCollectionItem::setRootPath (const QString & path, bool set_data = true, bool hide_element = false)
FileElementCollectionItem::setRootPath Set path has root path for this file item. Use this function only to set the beginning of a file collection.
Parameters
path
set_data
hide_element
Returns
true if path exist.
Definition at line 42 of file fileelementcollectionitem.cpp.
References m_path, and populate().
Referenced by ElementsCollectionModel::addCommonCollection(), and ElementsCollectionModel::addCustomCollection().
setUpData()
void FileElementCollectionItem::setUpData () override virtual
FileElementCollectionItem::setUpData SetUp the data of this item.
Implements ElementCollectionItem.
Definition at line 264 of file fileelementcollectionitem.cpp.
References collectionPath(), ElementsLocation::elementInformations(), isDir(), DiagramContext::keys(), localName(), and DiagramContext::value().
Referenced by addChildAtPath(), ElementsCollectionModel::addCommonCollection(), ElementsCollectionModel::addCustomCollection(), and populate().
setUpIcon()
void FileElementCollectionItem::setUpIcon () override virtual
FileElementCollectionItem::setUpIcon SetUp the icon of this item. Because icon use several memory, we use this method for setup icon instead setUpData.
Implements ElementCollectionItem.
Definition at line 301 of file fileelementcollectionitem.cpp.
References collectionPath(), QETApp::commonElementsDirN(), QET::Icons::Folder, ElementsLocation::icon(), isCollectionRoot(), isDir(), and m_path.
type()
int FileElementCollectionItem::type () const inline override
Definition at line 35 of file fileelementcollectionitem.h.
References Type.
Referenced by collectionPath(), dirPath(), and ElementsCollectionModel::dropMimeData().
Member Data Documentation
m_path
QString FileElementCollectionItem::m_path private
Definition at line 64 of file fileelementcollectionitem.h.
Referenced by collectionPath(), fileSystemPath(), isCollectionRoot(), isDir(), localName(), name(), setPathName(), setRootPath(), and setUpIcon().
The documentation for this class was generated from the following files:
fileelementcollectionitem.h
fileelementcollectionitem.cpp