QElectroTech: ConductorNumExport Class Reference
ConductorNumExport Class Reference
The ConductorNumExport class A class to export the num of conductors into a csv file.
#include <conductornumexport.h>
Public Member Functions
ConductorNumExport (QETProject *project, QWidget *parent=nullptr)
ConductorNumExport::ConductorNumExport.
bool toCsv ()
ConductorNumExport::toCsv Export the num of conductors into a csv file.
QString wiresNum () const
ConductorNumExport::wiresNum.
Private Member Functions
void fillHash ()
ConductorNumExport::fillHash make/fill of m_hash.
Private Attributes
QETProject * m_project = nullptr
QHash< QString, int > m_hash
QWidget * m_parent_widget = nullptr
Detailed Description
The ConductorNumExport class A class to export the num of conductors into a csv file.
Definition at line 30 of file conductornumexport.h.
Constructor & Destructor Documentation
ConductorNumExport()
ConductorNumExport::ConductorNumExport (QETProject * project, QWidget * parent = nullptr)
ConductorNumExport::ConductorNumExport.
Parameters
project : the project to export the conductors num
parent : parent widget
Definition at line 33 of file conductornumexport.cpp.
References fillHash().
Member Function Documentation
fillHash()
void ConductorNumExport::fillHash () private
ConductorNumExport::fillHash make/fill of m_hash.
Definition at line 112 of file conductornumexport.cpp.
References Element::AllReport, DiagramContent::conductors(), QETProject::diagrams(), m_hash, and m_project.
Referenced by ConductorNumExport().
toCsv()
bool ConductorNumExport::toCsv ()
ConductorNumExport::toCsv Export the num of conductors into a csv file.
Returns
true if suceesfully exported.
Definition at line 45 of file conductornumexport.cpp.
References QET::QetMessageBox::critical(), m_parent_widget, m_project, QETProject::title(), QET::Icons::tr, and wiresNum().
Referenced by QETDiagramEditor::setUpActions().
wiresNum()
QString ConductorNumExport::wiresNum () const
ConductorNumExport::wiresNum.
Returns
the wire num formated in csv
Definition at line 92 of file conductornumexport.cpp.
References m_hash.
Referenced by toCsv().
Member Data Documentation
m_hash
QHash<QString, int> ConductorNumExport::m_hash private
Definition at line 42 of file conductornumexport.h.
Referenced by fillHash(), and wiresNum().
m_parent_widget
QWidget* ConductorNumExport::m_parent_widget = nullptr private
Definition at line 43 of file conductornumexport.h.
Referenced by toCsv().
m_project
QETProject* ConductorNumExport::m_project = nullptr private
Definition at line 41 of file conductornumexport.h.
Referenced by fillHash(), and toCsv().
The documentation for this class was generated from the following files:
conductornumexport.h
conductornumexport.cpp