QElectroTech: XmlProjectElementCollectionItem Class Reference
XmlProjectElementCollectionItem Class Reference
The XmlProjectElementCollectionItem class This class specialise ElementCollectionItem for manage an xml collection embedded in a project.
#include <xmlprojectelementcollectionitem.h>
Public Types
enum { Type = UserType+3 }
Public Types inherited from ElementCollectionItem
enum { Type = UserType+1 }
Public Member Functions
XmlProjectElementCollectionItem ()
XmlProjectElementCollectionItem::XmlProjectElementCollectionItem Constructor.
int type () const override
bool isDir () const override
XmlProjectElementCollectionItem::isDir.
bool isElement () const override
XmlProjectElementCollectionItem::isElement.
QString localName () override
XmlProjectElementCollectionItem::localName.
QString name () const override
XmlProjectElementCollectionItem::name.
QString collectionPath () const override
XmlProjectElementCollectionItem::collectionPath.
virtual QString embeddedPath () const
XmlProjectElementCollectionItem::embeddedPath.
bool isCollectionRoot () const override
XmlProjectElementCollectionItem::isCollectionRoot.
void addChildAtPath (const QString &collection_name) override
XmlProjectElementCollectionItem::addChildAtPath Ask to this item item to add a new child with collection name collection_name (the child must exist in the xml element collection)
QETProject * project () const
XmlProjectElementCollectionItem::project.
void setProject (QETProject *project, bool set_data=true, bool hide_element=false)
XmlProjectElementCollectionItem::setProject Set the project for this item. Use this method for set this item the root of the collection.
void setUpData () override
XmlProjectElementCollectionItem::setUpData SetUp the data of this item.
void setUpIcon () override
XmlProjectElementCollectionItem::setUpIcon SetUp the icon of this item. Because icon use several memory, we use this method for setup icon instead setUpData.
Public Member Functions inherited from ElementCollectionItem
ElementCollectionItem ()
ElementCollectionItem::ElementCollectionItem Constructor.
int type () const override
virtual void clearData ()
ElementCollectionItem::clearData Reset the data.
ElementCollectionItem * lastItemForPath (const QString &path, QString &no_found_path)
ElementCollectionItem::lastItemForPath Return the last existing item in this ElementCollectionItem hierarchy according to the given path. Next_item is the first non existing item in this hierarchy according to the given path.
ElementCollectionItem * childWithCollectionName (const QString &name) const
ElementCollectionItem::childWithCollectionName Return the child with the collection name name, else return nullptr.
QList< QStandardItem * > directChilds () const
ElementCollectionItem::directChilds Return the direct child of this item.
int rowForInsertItem (const QString &name)
ElementCollectionItem::rowForInsertItem Return the row for insert a new child item to this item with name.
ElementCollectionItem * itemAtPath (const QString &path)
ElementCollectionItem::itemAtPath.
QList< ElementCollectionItem * > elementsDirectChild () const
ElementCollectionItem::elementsDirectChild.
QList< ElementCollectionItem * > directoriesDirectChild () const
ElementCollectionItem::directoriesDirectChild.
QList< ElementCollectionItem * > elementsChild () const
ElementCollectionItem::elementsChild.
QList< ElementCollectionItem * > directoriesChild () const
ElementCollectionItem::directoriesChild.
QList< ElementCollectionItem * > items () const
ElementCollectionItem::items.
Private Member Functions
void populate (bool set_data=true, bool hide_element=false)
XmlProjectElementCollectionItem::populate Create the childs of this item.
void setXmlElement (const QDomElement &element, QETProject *project, bool set_data=true, bool hide_element=false)
XmlProjectElementCollectionItem::setXmlElement Set the managed content of this item.
Private Attributes
QETProject * m_project = nullptr
QDomElement m_dom_element
Detailed Description
The XmlProjectElementCollectionItem class This class specialise ElementCollectionItem for manage an xml collection embedded in a project.
Definition at line 31 of file xmlprojectelementcollectionitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 36 of file xmlprojectelementcollectionitem.h.
Constructor & Destructor Documentation
XmlProjectElementCollectionItem()
XmlProjectElementCollectionItem::XmlProjectElementCollectionItem ()
XmlProjectElementCollectionItem::XmlProjectElementCollectionItem Constructor.
Definition at line 27 of file xmlprojectelementcollectionitem.cpp.
Referenced by addChildAtPath(), and populate().
Member Function Documentation
addChildAtPath()
void XmlProjectElementCollectionItem::addChildAtPath (const QString & collection_name) override virtual
XmlProjectElementCollectionItem::addChildAtPath Ask to this item item to add a new child with collection name collection_name (the child must exist in the xml element collection)
Parameters
collection_name : name of the child item to add.
Implements ElementCollectionItem.
Definition at line 136 of file xmlprojectelementcollectionitem.cpp.
References m_dom_element, m_project, ElementCollectionItem::rowForInsertItem(), setUpData(), setXmlElement(), and XmlProjectElementCollectionItem().
collectionPath()
QString XmlProjectElementCollectionItem::collectionPath () const override virtual
XmlProjectElementCollectionItem::collectionPath.
Returns
The path of this item relative to the collection.
Implements ElementCollectionItem.
Definition at line 86 of file xmlprojectelementcollectionitem.cpp.
References embeddedPath(), m_project, ElementsLocation::projectCollectionPath(), and QET::Icons::tr.
Referenced by ElementsCollectionModel::dropMimeData(), and setUpData().
embeddedPath()
QString XmlProjectElementCollectionItem::embeddedPath () const virtual
XmlProjectElementCollectionItem::embeddedPath.
Returns
The embedde path of this item The path is in form : embed://dir/subdir/myElement.elmt
Definition at line 100 of file xmlprojectelementcollectionitem.cpp.
References embeddedPath(), isCollectionRoot(), and name().
Referenced by collectionPath(), embeddedPath(), localName(), setUpData(), and setUpIcon().
isCollectionRoot()
bool XmlProjectElementCollectionItem::isCollectionRoot () const override virtual
XmlProjectElementCollectionItem::isCollectionRoot.
Returns
true if this item represent the root of collection
Implements ElementCollectionItem.
Definition at line 120 of file xmlprojectelementcollectionitem.cpp.
References Type, and type().
Referenced by ElementsCollectionWidget::customContextMenu(), embeddedPath(), localName(), and setUpIcon().
isDir()
bool XmlProjectElementCollectionItem::isDir () const override virtual
XmlProjectElementCollectionItem::isDir.
Returns
true if this item represent a directory
Implements ElementCollectionItem.
Definition at line 34 of file xmlprojectelementcollectionitem.cpp.
References m_dom_element.
Referenced by setUpData(), and setUpIcon().
isElement()
bool XmlProjectElementCollectionItem::isElement () const override virtual
XmlProjectElementCollectionItem::isElement.
Returns
true if this item represent an element
Implements ElementCollectionItem.
Definition at line 44 of file xmlprojectelementcollectionitem.cpp.
References m_dom_element.
Referenced by ElementsCollectionModel::dropMimeData().
localName()
QString XmlProjectElementCollectionItem::localName () override virtual
XmlProjectElementCollectionItem::localName.
Returns
the located name of this item
Implements ElementCollectionItem.
Definition at line 54 of file xmlprojectelementcollectionitem.cpp.
References embeddedPath(), isCollectionRoot(), m_project, ElementsLocation::name(), QETProject::title(), and QET::Icons::tr.
Referenced by setUpData().
name()
QString XmlProjectElementCollectionItem::name () const override virtual
XmlProjectElementCollectionItem::name.
Returns
The collection name of this item
Implements ElementCollectionItem.
Definition at line 77 of file xmlprojectelementcollectionitem.cpp.
References m_dom_element.
Referenced by embeddedPath().
populate()
void XmlProjectElementCollectionItem::populate (bool set_data = true, bool hide_element = false) private
XmlProjectElementCollectionItem::populate Create the childs of this item.
Parameters
set_data : if true, call setUpData for every child of this item
hide_element : bool
Definition at line 244 of file xmlprojectelementcollectionitem.cpp.
References XmlElementCollection::directories(), XmlElementCollection::elements(), QETProject::embeddedElementCollection(), m_dom_element, m_project, setUpData(), setXmlElement(), sort(), and XmlProjectElementCollectionItem().
Referenced by setProject(), and setXmlElement().
project()
QETProject * XmlProjectElementCollectionItem::project () const
XmlProjectElementCollectionItem::project.
Returns
the paretn project of the managed collection
Definition at line 162 of file xmlprojectelementcollectionitem.cpp.
References m_project.
Referenced by setProject(), and setXmlElement().
setProject()
void XmlProjectElementCollectionItem::setProject (QETProject * project, bool set_data = true, bool hide_element = false)
XmlProjectElementCollectionItem::setProject Set the project for this item. Use this method for set this item the root of the collection.
Parameters
project : project to manage the collection
set_data : if true, call setUpData for every child of this item
hide_element : bool
Definition at line 175 of file xmlprojectelementcollectionitem.cpp.
References QETProject::embeddedElementCollection(), m_dom_element, m_project, populate(), project(), and XmlElementCollection::root().
Referenced by ElementsCollectionModel::addProject().
setUpData()
void XmlProjectElementCollectionItem::setUpData () override virtual
XmlProjectElementCollectionItem::setUpData SetUp the data of this item.
Implements ElementCollectionItem.
Definition at line 191 of file xmlprojectelementcollectionitem.cpp.
References collectionPath(), ElementsLocation::elementInformations(), embeddedPath(), isDir(), DiagramContext::keys(), localName(), m_project, and DiagramContext::value().
Referenced by addChildAtPath(), ElementsCollectionModel::addProject(), and populate().
setUpIcon()
void XmlProjectElementCollectionItem::setUpIcon () override virtual
XmlProjectElementCollectionItem::setUpIcon SetUp the icon of this item. Because icon use several memory, we use this method for setup icon instead setUpData.
Implements ElementCollectionItem.
Definition at line 223 of file xmlprojectelementcollectionitem.cpp.
References embeddedPath(), QET::Icons::Folder, ElementsLocation::icon(), isCollectionRoot(), isDir(), m_project, and QET::Icons::ProjectFileGP.
Referenced by ElementsCollectionModel::data().
setXmlElement()
void XmlProjectElementCollectionItem::setXmlElement (const QDomElement & element, QETProject * project, bool set_data = true, bool hide_element = false) private
XmlProjectElementCollectionItem::setXmlElement Set the managed content of this item.
Parameters
element : the dom element (directory or element), to be managed by this item
project : the parent project of managed collection
set_data : if true, call setUpData for every child of this item
hide_element : bool
Definition at line 283 of file xmlprojectelementcollectionitem.cpp.
References m_dom_element, m_project, populate(), and project().
Referenced by addChildAtPath(), and populate().
type()
int XmlProjectElementCollectionItem::type () const inline override
Definition at line 37 of file xmlprojectelementcollectionitem.h.
References Type.
Referenced by ElementsCollectionModel::dropMimeData(), and isCollectionRoot().
Member Data Documentation
m_dom_element
QDomElement XmlProjectElementCollectionItem::m_dom_element private
Definition at line 64 of file xmlprojectelementcollectionitem.h.
Referenced by addChildAtPath(), isDir(), isElement(), name(), populate(), setProject(), and setXmlElement().
m_project
QETProject* XmlProjectElementCollectionItem::m_project = nullptr private
Definition at line 63 of file xmlprojectelementcollectionitem.h.
Referenced by addChildAtPath(), collectionPath(), localName(), populate(), project(), setProject(), setUpData(), setUpIcon(), and setXmlElement().
The documentation for this class was generated from the following files:
xmlprojectelementcollectionitem.h
xmlprojectelementcollectionitem.cpp