QElectroTech: ElementScene Class Reference
ElementScene Class Reference
The ElementScene class This class is the canvas allowing the visual edition of an electrial element. It displays the various primitives composing the drawing of the element, the border due to its fixed size and its hotspot.
#include <elementscene.h>
Public Types
enum Behavior { Normal, PasteArea, AddPart }
enum ItemOption {
SortByZValue = 1, IncludeTerminals = 2, IncludeHelperItems = 4, Selected = 8,
NonSelected = 16, SelectedOrNot = 24
}
Public Slots
void slot_select (const ElementContent &)
ElementScene::slot_select Select the item in content, every others items in the scene are deselected.
void slot_selectAll ()
ElementScene::slot_selectAll Select all items.
void slot_deselectAll ()
ElementScene::slot_deselectAll deselect all item.
void slot_invertSelection ()
ElementScene::slot_invertSelection Inverse Selection.
void slot_delete ()
ElementScene::slot_delete Delete selected items.
void slot_editNames ()
ElementScene::slot_editNames Launch a dialog for edit the names of the edited element.
void slot_editAuthorInformations ()
ElementScene::slot_editAuthorInformations Starts a dialog to edit the additional information of this element. Concretely, this free field is intended to receive information on the author of the element, its license, etc.
void slot_editProperties ()
ElementScene::slot_editProperties Open dialog to edit the element properties.
void managePrimitivesGroups ()
ElementScene::managePrimitivesGroups Ensure the decorator is adequately shown, hidden or updated so it always represents the current selection.
void stackAction (ElementEditionCommand *)
ElementScene::stackAction Push the provided command on the undo stack.
Signals
void partsAdded ()
Signal emitted after one or several parts were added.
void partsRemoved ()
Signal emitted after one or several parts were removed.
void partsZValueChanged ()
Signal emitted when the zValue of one or several parts change.
void pasteAreaDefined (const QRectF &)
Signal emitted when users have defined the copy/paste area.
void needZoomFit ()
Signal emitted when need zoomFit.
void elementInfoChanged ()
Public Member Functions
ElementScene (QETElementEditor *, QObject *=nullptr)
ElementScene::ElementScene constructor.
~ElementScene () override
ElementScene::~ElementScene.
void setEventInterface (ESEventInterface *event_interface)
ElementScene::setEventInterface Set a new event interface.
void clearEventInterface ()
ElementScene::clearEventInterface Clear the current event interface.
void setBehavior (ElementScene::Behavior)
ElementScene::setBehavior Modify the current behavior of this scene.
ElementScene::Behavior behavior () const
QPointF snapToGrid (QPointF point)
ElementScene::snapToGrid Rounds the coordinates of the point passed as a parameter so that this point is aligned with the grid.
void setNames (const NamesList &)
ElementScene::setNames.
NamesList names () const
ElementScene::names.
QString informations () const
ElementScene::informations.
void setInformations (const QString &)
ElementScene::setInformations.
QString elementType () const
DiagramContext elementKindInfo () const
DiagramContext elementInformation () const
virtual int xGrid () const
ElementScene::xGrid.
virtual int yGrid () const
ElementScene::yGrid.
virtual void setGrid (int, int)
ElementScene::setGrid.
virtual const QDomDocument toXml (bool=true)
ElementScene::toXml Export this element as a xml file.
virtual QRectF boundingRectFromXml (const QDomDocument &)
ElementScene::boundingRectFromXml.
virtual void fromXml (const QDomDocument &, const QPointF &=QPointF(), bool=true, ElementContent *=nullptr)
ElementScene::fromXml Imports the element described in an XML document. If a position is specified, the imported elements are positioned in such a way that the upper left corner of the smallest rectangle that can surround them all (the bounding rect) either at this position.
virtual void reset ()
ElementScene::reset Remove all QGraphicsItems in the scene and clear the undo stack.
virtual QList< CustomElementPart * > primitives () const
ElementScene::primitives.
virtual QList< QGraphicsItem * > zItems (ItemOptions options=ItemOptions(SortByZValue|IncludeTerminals|SelectedOrNot)) const
ElementScene::zItems.
virtual ElementContent selectedContent () const
ElementScene::selectedContent.
virtual void getPasteArea (const QRectF &)
ElementScene::getPasteArea.
QRectF elementSceneGeometricRect () const
ElementScene::elementSceneGeometricRect.
bool containsTerminals () const
ElementScene::containsTerminals.
QUndoStack & undoStack ()
ElementScene::undoStack.
QGIManager & qgiManager ()
ElementScene::qgiManager.
bool wasCopiedFromThisElement (const QString &)
ElementScene::wasCopiedFromThisElement.
void cut ()
ElementScene::cut Handles the fact of cutting the selection = exporting it in XML to the clipboard then deleting it.
void copy ()
ElementScene::copy Handles the fact of copying the selection = exporting it as XML to the clipboard.
QETElementEditor * editor () const
ElementScene::editor.
void setElementInfo (const DiagramContext &dc)
ElementScene::setElementInfo.
Static Public Member Functions
static bool clipboardMayContainElement ()
ElementScene::clipboardMayContainElement.
Protected Member Functions
void mouseMoveEvent (QGraphicsSceneMouseEvent *) override
ElementScene::mouseMoveEvent.
void mousePressEvent (QGraphicsSceneMouseEvent *) override
ElementScene::mousePressEvent.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *) override
ElementScene::mouseReleaseEvent.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
ElementScene::mouseDoubleClickEvent.
void keyPressEvent (QKeyEvent *event) override
ElementScene::keyPressEvent manage key press event.
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) override
ElementScene::contextMenuEvent Display the context menu event, only if behavior are Normal.
void drawForeground (QPainter *, const QRectF &) override
ElementScene::drawForeground Draws the background of the editor, ie the hotspot indicator.
Private Member Functions
ElementScene (const ElementScene &)
QRectF elementContentBoundingRect (const ElementContent &) const
ElementScene::elementContentBoundingRect.
bool applyInformations (const QDomDocument &)
ElementScene::applyInformations Applies the information (dimensions, hostpot, orientations, internal connections, names and additional information) contained in an XML document.
ElementContent loadContent (const QDomDocument &)
ElementScene::loadContent Create and load the content describe in the xml document.
ElementContent addContent (const ElementContent &)
ElementScene::addContent Add content content to this element.
ElementContent addContentAtPos (const ElementContent &, const QPointF &)
ElementScene::addContentAtPos Add content content to this element.
void addPrimitive (QGraphicsItem *)
ElementScene::addPrimitive Add a primitive to the scene by wrapping it within an ElementPrimitiveDecorator group.
void initPasteArea ()
ElementScene::initPasteArea Initializes the paste area.
void centerElementToOrigine ()
ElementScene::centerElementToOrigine try to center better is possible the element to the scene (the calcul isn't optimal but work good)
Static Private Member Functions
static bool zValueLessThan (QGraphicsItem *, QGraphicsItem *)
ElementScene::zValueLessThan.
Private Attributes
NamesList m_names_list
QString m_informations
List of localized names.
QString m_elmt_type
Extra informations.
DiagramContext m_elmt_kindInfo
element type
DiagramContext m_elmt_information
QGIManager m_qgi_manager
element kind info
QUndoStack m_undo_stack
ESEventInterface * m_event_interface = nullptr
Behavior m_behavior
QETElementEditor * m_element_editor = nullptr
QGraphicsRectItem * m_paste_area
QRectF m_defined_paste_area
QString m_last_copied
ElementPrimitiveDecorator * m_decorator = nullptr
Decorator item displayed when at least one item is selected.
int m_x_grid
int m_y_grid
QMutex * m_decorator_lock
Friends
class ChangePropertiesCommand
Detailed Description
The ElementScene class This class is the canvas allowing the visual edition of an electrial element. It displays the various primitives composing the drawing of the element, the border due to its fixed size and its hotspot.
Definition at line 39 of file elementscene.h.
Member Enumeration Documentation
Behavior
enum ElementScene::Behavior
Enumerator
Normal
PasteArea
AddPart
Definition at line 46 of file elementscene.h.
ItemOption
enum ElementScene::ItemOption
Enumerator
SortByZValue
IncludeTerminals
IncludeHelperItems
Selected
NonSelected
SelectedOrNot
Definition at line 47 of file elementscene.h.
Constructor & Destructor Documentation
ElementScene() [1/2]
ElementScene::ElementScene (QETElementEditor * editor, QObject * parent = nullptr)
ElementScene::ElementScene constructor.
Parameters
editor : Element editor concerned
parent : Widget parent
Definition at line 51 of file elementscene.cpp.
References initPasteArea(), m_behavior, m_decorator_lock, m_undo_stack, managePrimitivesGroups(), Normal, and setGrid().
~ElementScene()
ElementScene::~ElementScene () override
ElementScene::~ElementScene.
Definition at line 79 of file elementscene.cpp.
References m_decorator, m_decorator_lock, m_event_interface, m_undo_stack, and managePrimitivesGroups().
ElementScene() [2/2]
ElementScene::ElementScene (const ElementScene &) private
Member Function Documentation
addContent()
ElementContent ElementScene::addContent (const ElementContent & content) private
ElementScene::addContent Add content content to this element.
Parameters
content : content (= list of parts) to load
Returns
Content adds
Definition at line 1185 of file elementscene.cpp.
References addPrimitive().
Referenced by fromXml().
addContentAtPos()
ElementContent ElementScene::addContentAtPos (const ElementContent & content, const QPointF & pos) private
ElementScene::addContentAtPos Add content content to this element.
Parameters
content : content (= list of parts) to load
pos : Position of the upper left corner of the content after being added
Returns
Content adds
Definition at line 1205 of file elementscene.cpp.
References addPrimitive(), and elementContentBoundingRect().
Referenced by fromXml().
addPrimitive()
void ElementScene::addPrimitive (QGraphicsItem * primitive) private
ElementScene::addPrimitive Add a primitive to the scene by wrapping it within an ElementPrimitiveDecorator group.
Parameters
primitive
Definition at line 1233 of file elementscene.cpp.
Referenced by addContent(), and addContentAtPos().
applyInformations()
bool ElementScene::applyInformations (const QDomDocument & xml_document) private
ElementScene::applyInformations Applies the information (dimensions, hostpot, orientations, internal connections, names and additional information) contained in an XML document.
Parameters
xml_document : Document XML a analyser
Returns
true if reading and applying the information went well, false otherwise.
Definition at line 1065 of file elementscene.cpp.
References NamesList::fromXml(), DiagramContext::fromXml(), m_elmt_information, m_elmt_kindInfo, m_elmt_type, m_names_list, and setInformations().
Referenced by fromXml().
behavior()
ElementScene::Behavior ElementScene::behavior () const
Definition at line 352 of file elementscene.cpp.
References m_behavior.
boundingRectFromXml()
QRectF ElementScene::boundingRectFromXml (const QDomDocument & xml_document) virtual
ElementScene::boundingRectFromXml.
Parameters
xml_document : an XML document describing an element
Returns
the boundingRect of the element's content
Definition at line 496 of file elementscene.cpp.
References elementContentBoundingRect(), and loadContent().
centerElementToOrigine()
void ElementScene::centerElementToOrigine () private
ElementScene::centerElementToOrigine try to center better is possible the element to the scene (the calcul isn't optimal but work good)
Definition at line 1291 of file elementscene.cpp.
References elementSceneGeometricRect(), needZoomFit(), and ElementPrimitiveDecorator::Type.
Referenced by toXml().
clearEventInterface()
void ElementScene::clearEventInterface ()
ElementScene::clearEventInterface Clear the current event interface.
Definition at line 333 of file elementscene.cpp.
References m_event_interface.
clipboardMayContainElement()
bool ElementScene::clipboardMayContainElement () static
ElementScene::clipboardMayContainElement.
Returns
true if the clipboard appears to contain an element
Definition at line 621 of file elementscene.cpp.
Referenced by QETElementEditor::slot_updateMenus().
containsTerminals()
bool ElementScene::containsTerminals () const
ElementScene::containsTerminals.
Returns
true if the element has at least one terminal, false if it has none.
Definition at line 589 of file elementscene.cpp.
contextMenuEvent()
void ElementScene::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) override protected
ElementScene::contextMenuEvent Display the context menu event, only if behavior are Normal.
Parameters
event
Definition at line 275 of file elementscene.cpp.
References m_behavior, m_element_editor, and Normal.
copy()
void ElementScene::copy ()
ElementScene::copy Handles the fact of copying the selection = exporting it as XML to the clipboard.
Definition at line 662 of file elementscene.cpp.
References m_last_copied, and toXml().
Referenced by cut().
cut()
void ElementScene::cut ()
ElementScene::cut Handles the fact of cutting the selection = exporting it in XML to the clipboard then deleting it.
Definition at line 648 of file elementscene.cpp.
References copy(), and undoStack().
drawForeground()
void ElementScene::drawForeground (QPainter * p, const QRectF & rect) override protected
ElementScene::drawForeground Draws the background of the editor, ie the hotspot indicator.
Parameters
p : The QPainter to use for drawing
rect : The rectangle of the area to be drawn
Definition at line 294 of file elementscene.cpp.
editor()
QETElementEditor * ElementScene::editor () const
ElementScene::editor.
Returns
Definition at line 683 of file elementscene.cpp.
References m_element_editor.
Referenced by PartPolygon::contextMenuEvent().
elementContentBoundingRect()
QRectF ElementScene::elementContentBoundingRect (const ElementContent & content) const private
ElementScene::elementContentBoundingRect.
Parameters
content : Content (= parts) of an element
Returns
the boundingRect of these parts, expressed in the coordinates of the scene
Definition at line 1039 of file elementscene.cpp.
References ElementPrimitiveDecorator::Type.
Referenced by addContentAtPos(), and boundingRectFromXml().
elementInfoChanged
void ElementScene::elementInfoChanged () signal
Referenced by PartDynamicTextField::itemChange(), and setElementInfo().
elementInformation()
DiagramContext ElementScene::elementInformation () const inline
Definition at line 103 of file elementscene.h.
References m_elmt_information.
elementKindInfo()
DiagramContext ElementScene::elementKindInfo () const inline
Definition at line 102 of file elementscene.h.
References m_elmt_kindInfo.
elementSceneGeometricRect()
QRectF ElementScene::elementSceneGeometricRect () const
ElementScene::elementSceneGeometricRect.
Returns
the minimum, margin-less rectangle the element can fit into, in scene coordinates. It is different from itemsBoundingRect() because it is not supposed to imply any margin.
Definition at line 569 of file elementscene.cpp.
References ElementPrimitiveDecorator::Type, and PartDynamicTextField::Type.
Referenced by centerElementToOrigine(), and toXml().
elementType()
QString ElementScene::elementType () const inline
Definition at line 101 of file elementscene.h.
References m_elmt_type.
fromXml()
void ElementScene::fromXml (const QDomDocument & xml_document, const QPointF & position = QPointF(), bool consider_informations = true, ElementContent * content_ptr = nullptr) virtual
ElementScene::fromXml Imports the element described in an XML document. If a position is specified, the imported elements are positioned in such a way that the upper left corner of the smallest rectangle that can surround them all (the bounding rect) either at this position.
Parameters
xml_document : an XML document describing the element
position : The position of the imported parts
consider_informations : If true, additional information (dimensions, hotspot, etc.) will be taken into account
content_ptr : if this pointer to an ElementContent is different from 0, it will be filled with the content added to the element by the fromXml
Definition at line 537 of file elementscene.cpp.
References addContent(), addContentAtPos(), applyInformations(), and loadContent().
getPasteArea()
void ElementScene::getPasteArea (const QRectF & to_paste) virtual
ElementScene::getPasteArea.
Parameters
to_paste : Rectangle enclosing the parts to be glued
Returns
the rectangle where you will have to glue these parts
Definition at line 992 of file elementscene.cpp.
References m_behavior, m_paste_area, and PasteArea.
informations()
QString ElementScene::informations () const inline
ElementScene::informations.
Returns
extra informations of the currently edited element
Definition at line 203 of file elementscene.h.
References m_informations.
Referenced by slot_editAuthorInformations(), and toXml().
initPasteArea()
void ElementScene::initPasteArea () private
ElementScene::initPasteArea Initializes the paste area.
Definition at line 1243 of file elementscene.cpp.
References m_paste_area.
Referenced by ElementScene().
keyPressEvent()
void ElementScene::keyPressEvent (QKeyEvent * event) override protected
ElementScene::keyPressEvent manage key press event.
Parameters
event
Definition at line 194 of file elementscene.cpp.
References QPropertyUndoCommand::enableAnimation(), ESEventInterface::isFinish(), m_event_interface, partsAdded(), QET::Icons::tr, PartText::Type, and undoStack().
loadContent()
ElementContent ElementScene::loadContent (const QDomDocument & xml_document) private
ElementScene::loadContent Create and load the content describe in the xml document.
Parameters
xml_document : xml dom document to analyze
Returns
the loaded content
Definition at line 1113 of file elementscene.cpp.
References PartDynamicTextField::fromTextFieldXml(), CustomElementPart::fromXml(), m_element_editor, QET::Icons::PartArc, QET::Icons::PartEllipse, QET::Icons::PartLine, QET::Icons::PartPolygon, QET::Icons::PartRectangle, and QET::Icons::PartText.
Referenced by boundingRectFromXml(), and fromXml().
managePrimitivesGroups
void ElementScene::managePrimitivesGroups () slot
ElementScene::managePrimitivesGroups Ensure the decorator is adequately shown, hidden or updated so it always represents the current selection.
Definition at line 1318 of file elementscene.cpp.
References IncludeTerminals, m_decorator, m_decorator_lock, Selected, stackAction(), and zItems().
Referenced by ElementScene(), and ~ElementScene().
mouseDoubleClickEvent()
void ElementScene::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
ElementScene::mouseDoubleClickEvent.
Parameters
event
Definition at line 174 of file elementscene.cpp.
References ESEventInterface::isFinish(), m_event_interface, and partsAdded().
mouseMoveEvent()
void ElementScene::mouseMoveEvent (QGraphicsSceneMouseEvent * e) override protected
ElementScene::mouseMoveEvent.
Parameters
e
Definition at line 97 of file elementscene.cpp.
References ESEventInterface::isFinish(), m_behavior, m_event_interface, m_paste_area, partsAdded(), PasteArea, and snapToGrid().
mousePressEvent()
void ElementScene::mousePressEvent (QGraphicsSceneMouseEvent * e) override protected
ElementScene::mousePressEvent.
Parameters
e
Definition at line 128 of file elementscene.cpp.
References ESEventInterface::isFinish(), m_event_interface, and partsAdded().
mouseReleaseEvent()
void ElementScene::mouseReleaseEvent (QGraphicsSceneMouseEvent * e) override protected
ElementScene::mouseReleaseEvent.
Parameters
e
Definition at line 147 of file elementscene.cpp.
References ESEventInterface::isFinish(), m_behavior, m_defined_paste_area, m_event_interface, m_paste_area, Normal, partsAdded(), PasteArea, and pasteAreaDefined().
names()
NamesList ElementScene::names () const inline
ElementScene::names.
Returns
the list of names of the currently edited element
Definition at line 195 of file elementscene.h.
References m_names_list.
needZoomFit
void ElementScene::needZoomFit () signal
Signal emitted when need zoomFit.
Referenced by centerElementToOrigine().
partsAdded
void ElementScene::partsAdded () signal
Signal emitted after one or several parts were added.
Referenced by keyPressEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
partsRemoved
void ElementScene::partsRemoved () signal
Signal emitted after one or several parts were removed.
Referenced by slot_delete().
partsZValueChanged
void ElementScene::partsZValueChanged () signal
Signal emitted when the zValue of one or several parts change.
pasteAreaDefined
void ElementScene::pasteAreaDefined (const QRectF &) signal
Signal emitted when users have defined the copy/paste area.
Referenced by mouseReleaseEvent().
primitives()
QList< CustomElementPart * > ElementScene::primitives () const virtual
ElementScene::primitives.
Returns
the list of primitives currently present on the scene.
Definition at line 895 of file elementscene.cpp.
qgiManager()
QGIManager & ElementScene::qgiManager ()
ElementScene::qgiManager.
Returns
the QGraphicsItem manager of this item editor
Definition at line 612 of file elementscene.cpp.
References m_qgi_manager.
Referenced by PastePartsCommand::PastePartsCommand(), reset(), and PastePartsCommand::~PastePartsCommand().
reset()
void ElementScene::reset () virtual
ElementScene::reset Remove all QGraphicsItems in the scene and clear the undo stack.
Definition at line 1006 of file elementscene.cpp.
References m_decorator, qgiManager(), QGIManager::release(), QetGraphicsHandlerItem::Type, and undoStack().
selectedContent()
ElementContent ElementScene::selectedContent () const virtual
ElementScene::selectedContent.
Returns
the selected graphic parts
Definition at line 977 of file elementscene.cpp.
References zItems().
setBehavior()
void ElementScene::setBehavior (ElementScene::Behavior b)
ElementScene::setBehavior Modify the current behavior of this scene.
Parameters
b
Definition at line 348 of file elementscene.cpp.
References m_behavior.
Referenced by ESEventInterface::init(), and ESEventInterface::~ESEventInterface().
setElementInfo()
void ElementScene::setElementInfo (const DiagramContext & dc)
ElementScene::setElementInfo.
Parameters
dc
Definition at line 691 of file elementscene.cpp.
References elementInfoChanged(), and m_elmt_information.
Referenced by ChangePropertiesCommand::redo(), and ChangePropertiesCommand::undo().
setEventInterface()
void ElementScene::setEventInterface (ESEventInterface * event_interface)
ElementScene::setEventInterface Set a new event interface.
Parameters
event_interface
Definition at line 317 of file elementscene.cpp.
References ESEventInterface::init(), and m_event_interface.
setGrid()
void ElementScene::setGrid (int x_g, int y_g) virtual
ElementScene::setGrid.
Parameters
x_g : Horizontal grid size
y_g : Vertical grid size
Definition at line 381 of file elementscene.cpp.
References m_x_grid, and m_y_grid.
Referenced by ElementView::drawBackground(), and ElementScene().
setInformations()
void ElementScene::setInformations (const QString & infos) inline
ElementScene::setInformations.
Parameters
infos new extra information for the currently edited element
Definition at line 211 of file elementscene.h.
References m_informations.
Referenced by applyInformations().
setNames()
void ElementScene::setNames (const NamesList & nameslist) inline
ElementScene::setNames.
Parameters
nameslist New set of naes for the currently edited element
Definition at line 187 of file elementscene.h.
slot_delete
void ElementScene::slot_delete () slot
ElementScene::slot_delete Delete selected items.
Definition at line 766 of file elementscene.cpp.
References m_undo_stack, and partsRemoved().
slot_deselectAll
void ElementScene::slot_deselectAll () slot
ElementScene::slot_deselectAll deselect all item.
Definition at line 744 of file elementscene.cpp.
References slot_select().
slot_editAuthorInformations
void ElementScene::slot_editAuthorInformations () slot
ElementScene::slot_editAuthorInformations Starts a dialog to edit the additional information of this element. Concretely, this free field is intended to receive information on the author of the element, its license, etc.
Definition at line 790 of file elementscene.cpp.
References QET::Icons::Cancel, informations(), m_element_editor, QET::Icons::tr, and undoStack().
slot_editNames
void ElementScene::slot_editNames () slot
ElementScene::slot_editNames Launch a dialog for edit the names of the edited element.
Definition at line 864 of file elementscene.cpp.
References NameListWidget::isEmpty(), m_element_editor, m_names_list, NameListDialog::namelistWidget(), NameListWidget::names(), NameListDialog::setInformationText(), NameListWidget::setNames(), NameListWidget::setReadOnly(), QET::Icons::tr, and undoStack().
slot_editProperties
void ElementScene::slot_editProperties () slot
ElementScene::slot_editProperties Open dialog to edit the element properties.
Definition at line 842 of file elementscene.cpp.
References ChangePropertiesCommand, m_elmt_information, m_elmt_kindInfo, m_elmt_type, and undoStack().
slot_invertSelection
void ElementScene::slot_invertSelection () slot
ElementScene::slot_invertSelection Inverse Selection.
Definition at line 753 of file elementscene.cpp.
slot_select
void ElementScene::slot_select (const ElementContent & content) slot
ElementScene::slot_select Select the item in content, every others items in the scene are deselected.
Parameters
content
Definition at line 706 of file elementscene.cpp.
References QetGraphicsHandlerItem::Type.
Referenced by PastePartsCommand::redo(), slot_deselectAll(), and slot_selectAll().
slot_selectAll
void ElementScene::slot_selectAll () slot
ElementScene::slot_selectAll Select all items.
Definition at line 736 of file elementscene.cpp.
References slot_select().
snapToGrid()
QPointF ElementScene::snapToGrid (QPointF point)
ElementScene::snapToGrid Rounds the coordinates of the point passed as a parameter so that this point is aligned with the grid.
Parameters
point : a reference to a QPointF. This object will be modified.
Returns
point
Definition at line 1270 of file elementscene.cpp.
References m_x_grid, and m_y_grid.
Referenced by PartEllipse::handlerMouseMoveEvent(), PartArc::handlerMouseMoveEvent(), PartRectangle::handlerMouseMoveEvent(), PartPolygon::handlerMouseMoveEvent(), PartLine::handlerMouseMoveEvent(), ESEventAddRect::mouseMoveEvent(), ESEventAddDynamicTextField::mouseMoveEvent(), mouseMoveEvent(), ESEventAddRect::mousePressEvent(), ESEventAddArc::mousePressEvent(), ESEventAddPolygon::mousePressEvent(), ESEventAddEllipse::mousePressEvent(), and ESEventAddDynamicTextField::mouseReleaseEvent().
stackAction
void ElementScene::stackAction (ElementEditionCommand * command) slot
ElementScene::stackAction Push the provided command on the undo stack.
Parameters
command
Definition at line 1364 of file elementscene.cpp.
References undoStack().
Referenced by managePrimitivesGroups().
toXml()
const QDomDocument ElementScene::toXml (bool all_parts = true) virtual
ElementScene::toXml Export this element as a xml file.
Parameters
all_parts : (true by default) if true, export the entire element in xml, if false, only export the selected parts.
Returns
an xml document that describe the element.
Definition at line 394 of file elementscene.cpp.
References centerElementToOrigine(), elementSceneGeometricRect(), informations(), m_elmt_information, m_elmt_kindInfo, m_elmt_type, m_names_list, NamesList::toXml(), DiagramContext::toXml(), QET::version, and zItems().
Referenced by copy().
undoStack()
QUndoStack & ElementScene::undoStack ()
ElementScene::undoStack.
Returns
the undo stack of this element editor
Definition at line 603 of file elementscene.cpp.
References m_undo_stack.
Referenced by cut(), RectangleEditor::editingFinished(), EllipseEditor::editingFinishedH(), EllipseEditor::editingFinishedV(), EllipseEditor::editingFinishedX(), EllipseEditor::editingFinishedY(), PartEllipse::handlerMouseReleaseEvent(), PartArc::handlerMouseReleaseEvent(), PartRectangle::handlerMouseReleaseEvent(), PartPolygon::handlerMouseReleaseEvent(), PartLine::handlerMouseReleaseEvent(), RectangleEditor::heightChanged(), PartPolygon::insertPoint(), keyPressEvent(), LineEditor::lineEditingFinishedX1(), LineEditor::lineEditingFinishedX2(), LineEditor::lineEditingFinishedY1(), LineEditor::lineEditingFinishedY2(), ESEventAddPolygon::mouseDoubleClickEvent(), ESEventAddDynamicTextField::mouseReleaseEvent(), CustomElementGraphicPart::mouseReleaseEvent(), PolygonEditor::on_m_add_point_action_triggered(), PolygonEditor::on_m_remove_point_action_triggered(), PartPolygon::removePoint(), reset(), slot_editAuthorInformations(), slot_editNames(), slot_editProperties(), stackAction(), ArcEditor::updateArcA(), ArcEditor::updateArcRectH(), ArcEditor::updateArcRectV(), ArcEditor::updateArcRectX(), ArcEditor::updateArcRectY(), ArcEditor::updateArcS(), LineEditor::updateLineEndLength1(), LineEditor::updateLineEndLength2(), LineEditor::updateLineEndType1(), LineEditor::updateLineEndType2(), RectangleEditor::widthChanged(), RectangleEditor::xPosChanged(), RectangleEditor::xRadiusChanged(), RectangleEditor::yPosChanged(), and RectangleEditor::yRadiusChanged().
wasCopiedFromThisElement()
bool ElementScene::wasCopiedFromThisElement (const QString & clipboard_content)
ElementScene::wasCopiedFromThisElement.
Parameters
clipboard_content : character string, probably coming from the clipboard.
Returns
true if clipboard_content has been copied from this element.
Definition at line 637 of file elementscene.cpp.
References m_last_copied.
xGrid()
int ElementScene::xGrid () const virtual
ElementScene::xGrid.
Returns
the horizontal size of the grid
Definition at line 361 of file elementscene.cpp.
References m_x_grid.
yGrid()
int ElementScene::yGrid () const virtual
ElementScene::yGrid.
Returns
vertical grid size
Definition at line 370 of file elementscene.cpp.
References m_y_grid.
zItems()
QList< QGraphicsItem * > ElementScene::zItems (ItemOptions options = ItemOptions(SortByZValue | IncludeTerminals | SelectedOrNot)) const virtual
ElementScene::zItems.
Parameters
options
Returns
the parts of the element ordered by increasing zValue
Definition at line 911 of file elementscene.cpp.
References IncludeHelperItems, IncludeTerminals, NonSelected, Selected, SelectedOrNot, sort(), SortByZValue, QetGraphicsHandlerItem::Type, ElementPrimitiveDecorator::Type, and zValueLessThan().
Referenced by managePrimitivesGroups(), selectedContent(), and toXml().
zValueLessThan()
bool ElementScene::zValueLessThan (QGraphicsItem * item1, QGraphicsItem * item2) static private
ElementScene::zValueLessThan.
Parameters
item1 : QGraphicsItem
item2 : QGraphicsItem
Returns
true if item1's zValue() is less than item2's.
Definition at line 1282 of file elementscene.cpp.
Referenced by zItems().
Friends And Related Function Documentation
ChangePropertiesCommand
friend class ChangePropertiesCommand friend
Definition at line 41 of file elementscene.h.
Referenced by slot_editProperties().
Member Data Documentation
m_behavior
Behavior ElementScene::m_behavior private
Definition at line 76 of file elementscene.h.
Referenced by behavior(), contextMenuEvent(), ElementScene(), getPasteArea(), mouseMoveEvent(), mouseReleaseEvent(), and setBehavior().
m_decorator
ElementPrimitiveDecorator* ElementScene::m_decorator = nullptr private
Decorator item displayed when at least one item is selected.
Definition at line 85 of file elementscene.h.
Referenced by managePrimitivesGroups(), reset(), and ~ElementScene().
m_decorator_lock
QMutex* ElementScene::m_decorator_lock private
Definition at line 151 of file elementscene.h.
Referenced by ElementScene(), managePrimitivesGroups(), and ~ElementScene().
m_defined_paste_area
QRectF ElementScene::m_defined_paste_area private
Definition at line 80 of file elementscene.h.
Referenced by mouseReleaseEvent().
m_element_editor
QETElementEditor* ElementScene::m_element_editor = nullptr private
Definition at line 77 of file elementscene.h.
Referenced by contextMenuEvent(), editor(), loadContent(), slot_editAuthorInformations(), and slot_editNames().
m_elmt_information
DiagramContext ElementScene::m_elmt_information private
Definition at line 71 of file elementscene.h.
Referenced by applyInformations(), ChangePropertiesCommand::ChangePropertiesCommand(), elementInformation(), setElementInfo(), slot_editProperties(), and toXml().
m_elmt_kindInfo
DiagramContext ElementScene::m_elmt_kindInfo private
element type
Definition at line 70 of file elementscene.h.
Referenced by applyInformations(), ChangePropertiesCommand::ChangePropertiesCommand(), elementKindInfo(), ChangePropertiesCommand::redo(), slot_editProperties(), toXml(), and ChangePropertiesCommand::undo().
m_elmt_type
QString ElementScene::m_elmt_type private
Extra informations.
Definition at line 69 of file elementscene.h.
Referenced by applyInformations(), ChangePropertiesCommand::ChangePropertiesCommand(), elementType(), ChangePropertiesCommand::redo(), slot_editProperties(), toXml(), and ChangePropertiesCommand::undo().
m_event_interface
ESEventInterface* ElementScene::m_event_interface = nullptr private
Definition at line 75 of file elementscene.h.
Referenced by clearEventInterface(), keyPressEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), setEventInterface(), and ~ElementScene().
m_informations
QString ElementScene::m_informations private
List of localized names.
Definition at line 68 of file elementscene.h.
Referenced by informations(), and setInformations().
m_last_copied
QString ElementScene::m_last_copied private
Definition at line 82 of file elementscene.h.
Referenced by copy(), and wasCopiedFromThisElement().
m_names_list
NamesList ElementScene::m_names_list private
Definition at line 67 of file elementscene.h.
Referenced by applyInformations(), names(), slot_editNames(), and toXml().
m_paste_area
QGraphicsRectItem* ElementScene::m_paste_area private
Definition at line 79 of file elementscene.h.
Referenced by getPasteArea(), initPasteArea(), mouseMoveEvent(), and mouseReleaseEvent().
m_qgi_manager
QGIManager ElementScene::m_qgi_manager private
element kind info
Definition at line 72 of file elementscene.h.
Referenced by qgiManager().
m_undo_stack
QUndoStack ElementScene::m_undo_stack private
Definition at line 73 of file elementscene.h.
Referenced by ElementScene(), slot_delete(), undoStack(), and ~ElementScene().
m_x_grid
int ElementScene::m_x_grid private
Definition at line 87 of file elementscene.h.
Referenced by setGrid(), snapToGrid(), and xGrid().
m_y_grid
int ElementScene::m_y_grid private
Definition at line 88 of file elementscene.h.
Referenced by setGrid(), snapToGrid(), and yGrid().
The documentation for this class was generated from the following files:
elementscene.h
elementscene.cpp