QElectroTech: ElementsCategoryEditor Class Reference
ElementsCategoryEditor Class Reference
The ElementsCategoryEditor class This class provides a dialog to edit an existing category or create a new one.
#include <elementscategoryeditor.h>
Public Slots
void acceptCreation ()
ElementsCategoryEditor::acceptCreation Valid the creation of the category.
void acceptUpdate ()
ElementsCategoryEditor::acceptUpdate Valid the update of the category.
Public Member Functions
ElementsCategoryEditor (const ElementsLocation &location, bool edit=true, QWidget *parent=nullptr)
ElementsCategoryEditor::ElementsCategoryEditor Constructor.
~ElementsCategoryEditor () override
ElementsCategoryEditor::~ElementsCategoryEditor Destructor.
ElementsLocation createdLocation () const
ElementsCategoryEditor::createdLocation.
Private Member Functions
ElementsCategoryEditor (const ElementsCategoryEditor &)
void setUpWidget ()
ElementsCategoryEditor::setUpWidget.
Private Attributes
QDialogButtonBox * m_buttons
NameListWidget * m_names_list
QLabel * m_file_name
QFileNameEdit * m_file_line_edit
bool m_edit_mode
ElementsLocation m_location
ElementsLocation m_created_location
Detailed Description
The ElementsCategoryEditor class This class provides a dialog to edit an existing category or create a new one.
Definition at line 33 of file elementscategoryeditor.h.
Constructor & Destructor Documentation
ElementsCategoryEditor() [1/2]
ElementsCategoryEditor::ElementsCategoryEditor (const ElementsLocation & location, bool edit = true, QWidget * parent = nullptr)
ElementsCategoryEditor::ElementsCategoryEditor Constructor.
Parameters
location : location of the category to edit, or parent directory/category for the creation of a new category
edit : true = edit mode, false = creation mode
parent : parent widget
Definition at line 37 of file elementscategoryeditor.cpp.
References acceptCreation(), acceptUpdate(), NamesList::addName(), ElementsLocation::exist(), ElementsLocation::fileSystemPath(), ElementsLocation::isElement(), ElementsLocation::isWritable(), m_buttons, m_edit_mode, m_file_line_edit, m_location, m_names_list, ElementsLocation::nameList(), setUpWidget(), QET::Icons::tr, and QET::QetMessageBox::warning().
~ElementsCategoryEditor()
ElementsCategoryEditor::~ElementsCategoryEditor () override
ElementsCategoryEditor::~ElementsCategoryEditor Destructor.
Definition at line 90 of file elementscategoryeditor.cpp.
ElementsCategoryEditor() [2/2]
ElementsCategoryEditor::ElementsCategoryEditor (const ElementsCategoryEditor &) private
Member Function Documentation
acceptCreation
void ElementsCategoryEditor::acceptCreation () slot
ElementsCategoryEditor::acceptCreation Valid the creation of the category.
Definition at line 131 of file elementscategoryeditor.cpp.
References ElementsLocation::addToPath(), ElementCollectionHandler::createDir(), QET::QetMessageBox::critical(), ElementsLocation::exist(), NameListWidget::isEmpty(), ElementsLocation::isNull(), ElementsLocation::isWritable(), m_created_location, m_file_line_edit, m_location, m_names_list, NameListWidget::names(), QET::Icons::nl, and QET::Icons::tr.
Referenced by ElementsCategoryEditor().
acceptUpdate
void ElementsCategoryEditor::acceptUpdate () slot
ElementsCategoryEditor::acceptUpdate Valid the update of the category.
Definition at line 182 of file elementscategoryeditor.cpp.
References NameListWidget::isEmpty(), ElementsLocation::isWritable(), m_location, m_names_list, NameListWidget::names(), and ElementCollectionHandler::setNames().
Referenced by ElementsCategoryEditor().
createdLocation()
ElementsLocation ElementsCategoryEditor::createdLocation () const
ElementsCategoryEditor::createdLocation.
Returns
the location of the created directory
Definition at line 97 of file elementscategoryeditor.cpp.
References m_created_location.
Referenced by ElementsCollectionWidget::newDirectory().
setUpWidget()
void ElementsCategoryEditor::setUpWidget () private
ElementsCategoryEditor::setUpWidget.
Definition at line 105 of file elementscategoryeditor.cpp.
References QET::Icons::Cancel, m_buttons, m_file_line_edit, m_file_name, m_names_list, and QET::Icons::tr.
Referenced by ElementsCategoryEditor().
Member Data Documentation
m_buttons
QDialogButtonBox* ElementsCategoryEditor::m_buttons private
Definition at line 47 of file elementscategoryeditor.h.
Referenced by ElementsCategoryEditor(), and setUpWidget().
m_created_location
ElementsLocation ElementsCategoryEditor::m_created_location private
Definition at line 53 of file elementscategoryeditor.h.
Referenced by acceptCreation(), and createdLocation().
m_edit_mode
bool ElementsCategoryEditor::m_edit_mode private
Definition at line 51 of file elementscategoryeditor.h.
Referenced by ElementsCategoryEditor().
m_file_line_edit
QFileNameEdit* ElementsCategoryEditor::m_file_line_edit private
Definition at line 50 of file elementscategoryeditor.h.
Referenced by acceptCreation(), ElementsCategoryEditor(), and setUpWidget().
m_file_name
QLabel* ElementsCategoryEditor::m_file_name private
Definition at line 49 of file elementscategoryeditor.h.
Referenced by setUpWidget().
m_location
ElementsLocation ElementsCategoryEditor::m_location private
Definition at line 52 of file elementscategoryeditor.h.
Referenced by acceptCreation(), acceptUpdate(), and ElementsCategoryEditor().
m_names_list
NameListWidget* ElementsCategoryEditor::m_names_list private
Definition at line 48 of file elementscategoryeditor.h.
Referenced by acceptCreation(), acceptUpdate(), ElementsCategoryEditor(), and setUpWidget().
The documentation for this class was generated from the following files:
elementscategoryeditor.h
elementscategoryeditor.cpp