QElectroTech: ImportElementTextPattern Class Reference
ImportElementTextPattern Class Reference
#include <elementtextpattern.h>
Public Member Functions
ImportElementTextPattern (Element *elmt)
Private Member Functions
QString getName (const QStringList &list, bool *ok, bool *erase) const
ImportElementTextPattern::getName Open a dialog to let user select a conf.
QWidget * parentWidget () const
void apply (QString name, bool erase=false) const
ImportElementTextPattern::apply Apply the user choice.
Private Attributes
Element * m_element = nullptr
Detailed Description
Definition at line 42 of file elementtextpattern.h.
Constructor & Destructor Documentation
ImportElementTextPattern()
ImportElementTextPattern::ImportElementTextPattern (Element * elmt)
Definition at line 127 of file elementtextpattern.cpp.
References apply(), QETApp::configDir(), getName(), QET::QetMessageBox::information(), parentWidget(), and QET::Icons::tr.
Member Function Documentation
apply()
void ImportElementTextPattern::apply (QString name, bool erase = false) const private
ImportElementTextPattern::apply Apply the user choice.
Parameters
name : the name of the selected pattern
erase : erase the existing texts and groups of element.
Definition at line 199 of file elementtextpattern.cpp.
References QETApp::configDir(), QetGraphicsItem::diagram(), Element::dynamicTextItems(), QET::findInDomElement(), DynamicElementTextItem::fromXml(), m_element, DiagramContent::m_element_texts, Element::textGroups(), QET::Icons::tr, and Diagram::undoStack().
Referenced by ImportElementTextPattern().
getName()
QString ImportElementTextPattern::getName (const QStringList & list, bool * ok, bool * erase) const private
ImportElementTextPattern::getName Open a dialog to let user select a conf.
Parameters
list
ok
erase
Returns
Definition at line 170 of file elementtextpattern.cpp.
References ImportElementTextPatternDialog::getItem(), parentWidget(), and QET::Icons::tr.
Referenced by ImportElementTextPattern().
parentWidget()
QWidget * ImportElementTextPattern::parentWidget () const private
Definition at line 183 of file elementtextpattern.cpp.
References m_element.
Referenced by getName(), and ImportElementTextPattern().
Member Data Documentation
m_element
Element* ImportElementTextPattern::m_element = nullptr private
Definition at line 55 of file elementtextpattern.h.
Referenced by apply(), and parentWidget().
The documentation for this class was generated from the following files:
elementtextpattern.h
elementtextpattern.cpp