QElectroTech: GraphicsTablePropertiesEditor Class Reference
GraphicsTablePropertiesEditor Class Reference
The GraphicsTablePropertiesEditor class This widget is used to edit the property of both QetGraphicsTableItem and QetGraphicsHeaderItem.
#include <graphicstablepropertieseditor.h>
Public Member Functions
GraphicsTablePropertiesEditor (QetGraphicsTableItem *table=nullptr, QWidget *parent=nullptr)
GraphicsTablePropertiesEditor::GraphicsTablePropertiesEditor.
~GraphicsTablePropertiesEditor () override
GraphicsTablePropertiesEditor::~GraphicsTablePropertiesEditor.
void setTable (QetGraphicsTableItem *table)
GraphicsTablePropertiesEditor::setTable Set the table to be edited.
virtual void apply () override
GraphicsTablePropertiesEditor::apply Apply the current edition.
QUndoCommand * associatedUndo () const override
GraphicsTablePropertiesEditor::associatedUndo.
virtual bool setLiveEdit (bool live_edit) override
PropertiesEditorWidget::setLiveEdit Set the editor in live edit mode. When an editor is in live edit mode, every change is applied immediately (no need to call apply). If live edit can be enable, return true, else false. By default this method do nothing and return false (live edit is disable). Herited class of PropertiesEditorWidget must reimplemente this methode to manage the live edit mode.
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual void reset ()
virtual QString title () const
PropertiesEditorWidget::title.
virtual void updateUi ()
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Private Slots
void on_m_header_font_pb_clicked ()
GraphicsTablePropertiesEditor::on_m_header_font_pb_clicked.
void on_m_table_font_pb_clicked ()
GraphicsTablePropertiesEditor::on_m_table_font_pb_clicked.
virtual void updateUi () override
GraphicsTablePropertiesEditor::updateUi.
void updateInfoLabel ()
void on_m_table_name_le_textEdited (const QString &arg1)
void on_m_previous_table_cb_activated (int index)
void on_m_previous_pb_clicked ()
void on_m_next_pb_clicked ()
void on_m_auto_geometry_pb_clicked ()
GraphicsTablePropertiesEditor::on_m_auto_geometry_pb_clicked.
void on_m_apply_geometry_to_linked_table_pb_clicked ()
GraphicsTablePropertiesEditor::on_m_apply_geometry_to_linked_table_pb_clicked.
Private Member Functions
void setUpEditConnection ()
GraphicsTablePropertiesEditor::setUpEditConnection.
Private Attributes
Ui::GraphicsTablePropertiesEditor * ui
QPointer< QetGraphicsTableItem > m_table_item
QList< QMetaObject::Connection > m_connect_list
QList< QMetaObject::Connection > m_edit_connection
QButtonGroup * m_header_button_group = nullptr
QButtonGroup * m_table_button_group = nullptr
QWidget * m_current_model_editor = nullptr
QVector< QetGraphicsTableItem * > m_other_table_vector
Additional Inherited Members
Protected Member Functions inherited from PropertiesEditorWidget
virtual void enableLiveEdit ()
virtual void disableLiveEdit ()
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
The GraphicsTablePropertiesEditor class This widget is used to edit the property of both QetGraphicsTableItem and QetGraphicsHeaderItem.
Definition at line 38 of file graphicstablepropertieseditor.h.
Constructor & Destructor Documentation
GraphicsTablePropertiesEditor()
GraphicsTablePropertiesEditor::GraphicsTablePropertiesEditor (QetGraphicsTableItem * table = nullptr, QWidget * parent = nullptr) explicit
GraphicsTablePropertiesEditor::GraphicsTablePropertiesEditor.
Parameters
table
parent
Definition at line 37 of file graphicstablepropertieseditor.cpp.
References m_header_button_group, m_table_button_group, setTable(), and ui.
~GraphicsTablePropertiesEditor()
GraphicsTablePropertiesEditor::~GraphicsTablePropertiesEditor () override
GraphicsTablePropertiesEditor::~GraphicsTablePropertiesEditor.
Definition at line 62 of file graphicstablepropertieseditor.cpp.
References ui.
Member Function Documentation
apply()
void GraphicsTablePropertiesEditor::apply () override virtual
GraphicsTablePropertiesEditor::apply Apply the current edition.
Reimplemented from PropertiesEditorWidget.
Definition at line 103 of file graphicstablepropertieseditor.cpp.
References associatedUndo(), and m_table_item.
Referenced by setUpEditConnection().
associatedUndo()
QUndoCommand * GraphicsTablePropertiesEditor::associatedUndo () const override virtual
GraphicsTablePropertiesEditor::associatedUndo.
Returns
the undo command associated to the edition
Reimplemented from PropertiesEditorWidget.
Definition at line 119 of file graphicstablepropertieseditor.cpp.
References QET::Horizontal, m_header_button_group, PropertiesEditorWidget::m_live_edit, m_table_button_group, m_table_item, QETUtils::marginsFromString(), QETUtils::marginsToString(), QET::Icons::tr, and ui.
Referenced by apply().
on_m_apply_geometry_to_linked_table_pb_clicked
void GraphicsTablePropertiesEditor::on_m_apply_geometry_to_linked_table_pb_clicked () private slot
GraphicsTablePropertiesEditor::on_m_apply_geometry_to_linked_table_pb_clicked.
Definition at line 425 of file graphicstablepropertieseditor.cpp.
References m_table_item, and QET::Icons::tr.
on_m_auto_geometry_pb_clicked
void GraphicsTablePropertiesEditor::on_m_auto_geometry_pb_clicked () private slot
GraphicsTablePropertiesEditor::on_m_auto_geometry_pb_clicked.
Definition at line 415 of file graphicstablepropertieseditor.cpp.
References QetGraphicsTableItem::adjustTableToFolio(), and m_table_item.
on_m_header_font_pb_clicked
void GraphicsTablePropertiesEditor::on_m_header_font_pb_clicked () private slot
GraphicsTablePropertiesEditor::on_m_header_font_pb_clicked.
Definition at line 203 of file graphicstablepropertieseditor.cpp.
References QET::Horizontal, m_table_item, and QET::Icons::tr.
on_m_next_pb_clicked
void GraphicsTablePropertiesEditor::on_m_next_pb_clicked () private slot
Definition at line 403 of file graphicstablepropertieseditor.cpp.
References m_table_item.
on_m_previous_pb_clicked
void GraphicsTablePropertiesEditor::on_m_previous_pb_clicked () private slot
Definition at line 394 of file graphicstablepropertieseditor.cpp.
References m_table_item.
on_m_previous_table_cb_activated
void GraphicsTablePropertiesEditor::on_m_previous_table_cb_activated (int index) private slot
Definition at line 385 of file graphicstablepropertieseditor.cpp.
References m_other_table_vector, m_table_item, and ui.
on_m_table_font_pb_clicked
void GraphicsTablePropertiesEditor::on_m_table_font_pb_clicked () private slot
GraphicsTablePropertiesEditor::on_m_table_font_pb_clicked.
Definition at line 224 of file graphicstablepropertieseditor.cpp.
References m_table_item, and QET::Icons::tr.
on_m_table_name_le_textEdited
void GraphicsTablePropertiesEditor::on_m_table_name_le_textEdited (const QString & arg1) private slot
Definition at line 381 of file graphicstablepropertieseditor.cpp.
References m_table_item.
setLiveEdit()
bool GraphicsTablePropertiesEditor::setLiveEdit (bool live_edit) override virtual
PropertiesEditorWidget::setLiveEdit Set the editor in live edit mode. When an editor is in live edit mode, every change is applied immediately (no need to call apply). If live edit can be enable, return true, else false. By default this method do nothing and return false (live edit is disable). Herited class of PropertiesEditorWidget must reimplemente this methode to manage the live edit mode.
Parameters
live_edit true to enable live edit
Returns
true if live edit is enable, else false.
Reimplemented from PropertiesEditorWidget.
Definition at line 189 of file graphicstablepropertieseditor.cpp.
References PropertiesEditorWidget::m_live_edit, and setUpEditConnection().
setTable()
void GraphicsTablePropertiesEditor::setTable (QetGraphicsTableItem * table)
GraphicsTablePropertiesEditor::setTable Set the table to be edited.
Parameters
table
Definition at line 71 of file graphicstablepropertieseditor.cpp.
References m_connect_list, m_current_model_editor, m_table_item, QetGraphicsTableItem::model(), PropertiesEditorFactory::propertiesEditor(), ui, and updateUi().
Referenced by GraphicsTablePropertiesEditor().
setUpEditConnection()
void GraphicsTablePropertiesEditor::setUpEditConnection () private
GraphicsTablePropertiesEditor::setUpEditConnection.
Definition at line 348 of file graphicstablepropertieseditor.cpp.
References apply(), m_edit_connection, m_header_button_group, PropertiesEditorWidget::m_live_edit, m_table_button_group, ui, and updateInfoLabel().
Referenced by setLiveEdit(), and updateUi().
updateInfoLabel
void GraphicsTablePropertiesEditor::updateInfoLabel () private slot
Definition at line 313 of file graphicstablepropertieseditor.cpp.
References m_table_item, QET::Icons::tr, and ui.
Referenced by setUpEditConnection(), and updateUi().
updateUi
void GraphicsTablePropertiesEditor::updateUi () override private virtual slot
GraphicsTablePropertiesEditor::updateUi.
Definition at line 246 of file graphicstablepropertieseditor.cpp.
References QET::Horizontal, m_edit_connection, m_header_button_group, m_other_table_vector, m_table_button_group, m_table_item, QETUtils::marginsFromString(), setUpEditConnection(), ElementProvider::table(), QET::Icons::tr, ui, and updateInfoLabel().
Referenced by setTable().
Member Data Documentation
m_connect_list
QList<QMetaObject::Connection> GraphicsTablePropertiesEditor::m_connect_list private
Definition at line 69 of file graphicstablepropertieseditor.h.
Referenced by setTable().
m_current_model_editor
QWidget* GraphicsTablePropertiesEditor::m_current_model_editor = nullptr private
Definition at line 73 of file graphicstablepropertieseditor.h.
Referenced by setTable().
m_edit_connection
QList<QMetaObject::Connection> GraphicsTablePropertiesEditor::m_edit_connection private
Definition at line 70 of file graphicstablepropertieseditor.h.
Referenced by setUpEditConnection(), and updateUi().
m_header_button_group
QButtonGroup* GraphicsTablePropertiesEditor::m_header_button_group = nullptr private
Definition at line 71 of file graphicstablepropertieseditor.h.
Referenced by associatedUndo(), GraphicsTablePropertiesEditor(), setUpEditConnection(), and updateUi().
m_other_table_vector
QVector<QetGraphicsTableItem *> GraphicsTablePropertiesEditor::m_other_table_vector private
Definition at line 74 of file graphicstablepropertieseditor.h.
Referenced by on_m_previous_table_cb_activated(), and updateUi().
m_table_button_group
QButtonGroup * GraphicsTablePropertiesEditor::m_table_button_group = nullptr private
Definition at line 72 of file graphicstablepropertieseditor.h.
Referenced by associatedUndo(), GraphicsTablePropertiesEditor(), setUpEditConnection(), and updateUi().
m_table_item
QPointer<QetGraphicsTableItem> GraphicsTablePropertiesEditor::m_table_item private
Definition at line 68 of file graphicstablepropertieseditor.h.
Referenced by apply(), associatedUndo(), on_m_apply_geometry_to_linked_table_pb_clicked(), on_m_auto_geometry_pb_clicked(), on_m_header_font_pb_clicked(), on_m_next_pb_clicked(), on_m_previous_pb_clicked(), on_m_previous_table_cb_activated(), on_m_table_font_pb_clicked(), on_m_table_name_le_textEdited(), setTable(), updateInfoLabel(), and updateUi().
ui
Ui::GraphicsTablePropertiesEditor* GraphicsTablePropertiesEditor::ui private
Definition at line 67 of file graphicstablepropertieseditor.h.
Referenced by associatedUndo(), GraphicsTablePropertiesEditor(), on_m_previous_table_cb_activated(), setTable(), setUpEditConnection(), updateInfoLabel(), updateUi(), and ~GraphicsTablePropertiesEditor().
The documentation for this class was generated from the following files:
graphicstablepropertieseditor.h
graphicstablepropertieseditor.cpp