QElectroTech: FormulaAutonumberingW Class Reference
FormulaAutonumberingW Class Reference
#include <formulaautonumberingw.h>
Signals
void applyPressed ()
void textChanged (QString)
Public Member Functions
FormulaAutonumberingW (QWidget *parent=nullptr)
~FormulaAutonumberingW () override
QString formula ()
FormulaAutonumberingW::formula.
void setContext (const QString &)
FormulaAutonumberingW::setContext.
void clearContext ()
FormulaAutonumberingW::clearContext.
Public Attributes
Ui::FormulaAutonumberingW * ui
Private Slots
void on_m_formula_le_textChanged (QString)
FormulaAutonumberingW::on_m_formula_le_textChanged Update Apply Button.
Private Attributes
QString formula_
Detailed Description
This class implements the element autonumbering widget. It loads the current formula applied to new elements and allows the user to overwrite it with a new formula. Formula is added while parsing label in customelement.cpp
Definition at line 35 of file formulaautonumberingw.h.
Constructor & Destructor Documentation
FormulaAutonumberingW()
FormulaAutonumberingW::FormulaAutonumberingW (QWidget * parent = nullptr) explicit
Constructor
Definition at line 28 of file formulaautonumberingw.cpp.
References formula_, setContext(), and ui.
~FormulaAutonumberingW()
FormulaAutonumberingW::~FormulaAutonumberingW () override
Destructor
Definition at line 40 of file formulaautonumberingw.cpp.
References ui.
Member Function Documentation
applyPressed
void FormulaAutonumberingW::applyPressed () signal
clearContext()
void FormulaAutonumberingW::clearContext ()
FormulaAutonumberingW::clearContext.
Parameters
clear formula line edit text
Definition at line 57 of file formulaautonumberingw.cpp.
References ui.
Referenced by SelectAutonumW::contextToFormula().
formula()
QString FormulaAutonumberingW::formula ()
FormulaAutonumberingW::formula.
Returns
formula to be stored into project
Definition at line 65 of file formulaautonumberingw.cpp.
References ui.
Referenced by SelectAutonumW::formula(), and setContext().
on_m_formula_le_textChanged
void FormulaAutonumberingW::on_m_formula_le_textChanged (QString text) private slot
FormulaAutonumberingW::on_m_formula_le_textChanged Update Apply Button.
Definition at line 73 of file formulaautonumberingw.cpp.
References textChanged().
setContext()
void FormulaAutonumberingW::setContext (const QString & formula)
FormulaAutonumberingW::setContext.
Parameters
formula to be inserted into context
Definition at line 49 of file formulaautonumberingw.cpp.
References formula(), and ui.
Referenced by SelectAutonumW::contextToFormula(), and FormulaAutonumberingW().
textChanged
void FormulaAutonumberingW::textChanged (QString) signal
Referenced by on_m_formula_le_textChanged().
Member Data Documentation
formula_
QString FormulaAutonumberingW::formula_ private
Definition at line 61 of file formulaautonumberingw.h.
Referenced by FormulaAutonumberingW().
ui
Ui::FormulaAutonumberingW* FormulaAutonumberingW::ui
Definition at line 46 of file formulaautonumberingw.h.
Referenced by clearContext(), formula(), FormulaAutonumberingW(), SelectAutonumW::SelectAutonumW(), setContext(), and ~FormulaAutonumberingW().
The documentation for this class was generated from the following files:
formulaautonumberingw.h
formulaautonumberingw.cpp