QElectroTech: Machine_info::Pc::OS Struct Reference
Machine_info::Pc::OS Struct Reference
#include <machine_info.h>
Public Attributes
QString type =QString(QSysInfo::kernelType())
QString name =QString(QSysInfo::prettyProductName())
QString kernel =QString(QSysInfo::kernelVersion())
Detailed Description
Definition at line 88 of file machine_info.h.
Member Data Documentation
kernel
QString Machine_info::Pc::OS::kernel =QString(QSysInfo::kernelVersion())
Definition at line 92 of file machine_info.h.
Referenced by Machine_info::compilation_info(), and Machine_info::send_info_to_debug().
name
QString Machine_info::Pc::OS::name =QString(QSysInfo::prettyProductName())
Definition at line 91 of file machine_info.h.
Referenced by Machine_info::compilation_info(), and Machine_info::send_info_to_debug().
type
QString Machine_info::Pc::OS::type =QString(QSysInfo::kernelType())
Definition at line 90 of file machine_info.h.
Referenced by Machine_info::compilation_info(), Machine_info::init_get_cpu_info(), and Machine_info::send_info_to_debug().
The documentation for this struct was generated from the following file:
machine_info.h