QElectroTech: ElementItemEditor Class Reference
ElementItemEditor Class Reference abstract
#include <elementitemeditor.h>
Public Member Functions
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
virtual bool setPart (CustomElementPart *)=0
virtual bool setParts (QList< CustomElementPart * >)
virtual CustomElementPart * currentPart () const =0
virtual QList< CustomElementPart * > currentParts () const =0
virtual void updateForm ()=0
Private Member Functions
ElementItemEditor (const ElementItemEditor &)
Private Attributes
QETElementEditor * element_editor
QString element_type_name
Detailed Description
This is the base class for primitives editors within the element editor. It provides methods to access the editor itself, the undo stack, the edition scene and even a method to easily take a ChangePartCommand into account.
Definition at line 33 of file elementitemeditor.h.
Constructor & Destructor Documentation
ElementItemEditor() [1/2]
ElementItemEditor::ElementItemEditor (QETElementEditor * editor, QWidget * parent = nullptr)
Constructeur
Parameters
editor QETElementEditor auquel cet editeur appartient
parent QWidget parent de cet editeur
Definition at line 27 of file elementitemeditor.cpp.
~ElementItemEditor()
ElementItemEditor::~ElementItemEditor () inline override
Definition at line 39 of file elementitemeditor.h.
ElementItemEditor() [2/2]
ElementItemEditor::ElementItemEditor (const ElementItemEditor &) private
Member Function Documentation
currentPart()
virtual CustomElementPart* ElementItemEditor::currentPart () const pure virtual
Implemented in TerminalEditor, StyleEditor, ArcEditor, LineEditor, EllipseEditor, RectangleEditor, TextEditor, DynamicTextFieldEditor, and PolygonEditor.
currentParts()
virtual QList<CustomElementPart*> ElementItemEditor::currentParts () const pure virtual
Implemented in TerminalEditor, StyleEditor, ArcEditor, LineEditor, EllipseEditor, RectangleEditor, TextEditor, DynamicTextFieldEditor, and PolygonEditor.
detach()
void ElementItemEditor::detach () virtual
Detache l'editeur de la primitive qu'il edite. Equivaut a setPart(0)
See also
setPart
Definition at line 63 of file elementitemeditor.cpp.
References setPart().
elementEditor()
QETElementEditor * ElementItemEditor::elementEditor () const virtual
Returns
le QETElementEditor auquel cet editeur appartient
Definition at line 34 of file elementitemeditor.cpp.
References element_editor.
Referenced by DynamicTextFieldEditor::fillInfoComboBox(), and DynamicTextFieldEditor::on_m_elmt_info_cb_activated().
elementScene()
ElementScene * ElementItemEditor::elementScene () const virtual
Returns
l'ElementScene contenant les parties editees par cet editeur
Definition at line 39 of file elementitemeditor.cpp.
References element_editor.
Referenced by RectangleEditor::editingFinished(), EllipseEditor::editingFinishedH(), EllipseEditor::editingFinishedV(), EllipseEditor::editingFinishedX(), EllipseEditor::editingFinishedY(), DynamicTextFieldEditor::fillInfoComboBox(), RectangleEditor::heightChanged(), LineEditor::lineEditingFinishedX1(), LineEditor::lineEditingFinishedX2(), LineEditor::lineEditingFinishedY1(), LineEditor::lineEditingFinishedY2(), PolygonEditor::on_m_add_point_action_triggered(), DynamicTextFieldEditor::on_m_elmt_info_cb_activated(), PolygonEditor::on_m_remove_point_action_triggered(), undoStack(), ArcEditor::updateArcA(), ArcEditor::updateArcRectH(), ArcEditor::updateArcRectV(), ArcEditor::updateArcRectX(), ArcEditor::updateArcRectY(), ArcEditor::updateArcS(), LineEditor::updateLineEndLength1(), LineEditor::updateLineEndLength2(), LineEditor::updateLineEndType1(), LineEditor::updateLineEndType2(), RectangleEditor::widthChanged(), RectangleEditor::xPosChanged(), RectangleEditor::xRadiusChanged(), RectangleEditor::yPosChanged(), and RectangleEditor::yRadiusChanged().
elementTypeName()
QString ElementItemEditor::elementTypeName () const virtual
Returns
Le nom du type d'element edite
Definition at line 49 of file elementitemeditor.cpp.
References element_type_name.
setElementTypeName()
void ElementItemEditor::setElementTypeName (const QString & name) virtual
Parameters
name Nom du type d'element edite
Definition at line 54 of file elementitemeditor.cpp.
References element_type_name.
setPart()
virtual bool ElementItemEditor::setPart (CustomElementPart *) pure virtual
Implemented in RectangleEditor, TextEditor, DynamicTextFieldEditor, PolygonEditor, TerminalEditor, StyleEditor, ArcEditor, LineEditor, and EllipseEditor.
Referenced by detach().
setParts()
virtual bool ElementItemEditor::setParts (QList< CustomElementPart * >) inline virtual
Reimplemented in StyleEditor, TextEditor, DynamicTextFieldEditor, TerminalEditor, ArcEditor, LineEditor, EllipseEditor, and RectangleEditor.
Definition at line 54 of file elementitemeditor.h.
undoStack()
QUndoStack & ElementItemEditor::undoStack () const virtual
Returns
la QUndoStack a utiliser pour les annulations
Definition at line 44 of file elementitemeditor.cpp.
References elementScene().
Referenced by StyleEditor::makeUndo(), DynamicTextFieldEditor::on_m_alignment_pb_clicked(), PolygonEditor::on_m_close_polygon_cb_stateChanged(), DynamicTextFieldEditor::on_m_color_kpb_changed(), TextEditor::on_m_color_pb_changed(), DynamicTextFieldEditor::on_m_composite_text_pb_clicked(), DynamicTextFieldEditor::on_m_elmt_info_cb_activated(), TextEditor::on_m_font_pb_clicked(), DynamicTextFieldEditor::on_m_font_pb_clicked(), DynamicTextFieldEditor::on_m_frame_cb_clicked(), PolygonEditor::on_m_points_list_tree_itemChanged(), DynamicTextFieldEditor::on_m_rotation_sb_editingFinished(), DynamicTextFieldEditor::on_m_size_sb_editingFinished(), DynamicTextFieldEditor::on_m_text_from_cb_activated(), DynamicTextFieldEditor::on_m_user_text_le_editingFinished(), DynamicTextFieldEditor::on_m_width_sb_editingFinished(), DynamicTextFieldEditor::on_m_x_sb_editingFinished(), DynamicTextFieldEditor::on_m_y_sb_editingFinished(), TextEditor::setUpEditConnection(), TerminalEditor::updateTerminalO(), TerminalEditor::updateXPos(), and TerminalEditor::updateYPos().
updateForm()
virtual void ElementItemEditor::updateForm () pure virtual
Implemented in DynamicTextFieldEditor, PolygonEditor, and TextEditor.
Member Data Documentation
element_editor
QETElementEditor* ElementItemEditor::element_editor private
Definition at line 62 of file elementitemeditor.h.
Referenced by elementEditor(), and elementScene().
element_type_name
QString ElementItemEditor::element_type_name private
Definition at line 63 of file elementitemeditor.h.
Referenced by elementTypeName(), and setElementTypeName().
The documentation for this class was generated from the following files:
elementitemeditor.h
elementitemeditor.cpp