QElectroTech: ArcEditor Class Reference
ArcEditor Class Reference
#include <arceditor.h>
Public Slots
void updateArcS ()
ArcEditor::updateArcS Update the start angle of the arc according to the edited value.
void updateArcA ()
ArcEditor::updateArcA Update the span angle of the arc according to the edited value.
void updateArcRectX ()
ArcEditor::updateArcRect Update the geometrie of the rect that define this arc according the the edited values.
void updateArcRectY ()
void updateArcRectH ()
void updateArcRectV ()
void updateForm () override
ArcEditor::updateForm Update the value of the widgets.
Public Member Functions
ArcEditor (QETElementEditor *, PartArc *=nullptr, QWidget *=nullptr)
~ArcEditor () override
Destructeur.
bool setPart (CustomElementPart *) override
ArcEditor::setPart Specifie to this editor the part to edit. Note that an editor can accept or refuse to edit a part. This editor accept only partArc.
bool setParts (QList< CustomElementPart * > parts) override
CustomElementPart * currentPart () const override
ArcEditor::currentPart.
QList< CustomElementPart * > currentParts () const override
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
virtual void updateForm ()=0
Private Member Functions
ArcEditor (const ArcEditor &)
void activeConnections (bool)
ArcEditor::activeConnections Enable/disable connection between editor widget and slot editingFinished True == enable | false == disable.
void setUpChangeConnections ()
setUpChangeConnections Setup the connection from the arc(s) to the widget, to update it when the arc(s) are changed (moved ...)
void disconnectChangeConnections ()
Private Attributes
PartArc * part
StyleEditor * style_
QDoubleSpinBox * x
QDoubleSpinBox * y
QDoubleSpinBox * h
QDoubleSpinBox * v
QSpinBox * angle
QSpinBox * start_angle
bool m_locked
QList< QMetaObject::Connection > m_change_connections
Detailed Description
This class provides a widget to edit elliptical arcs within the element editor.
Definition at line 31 of file arceditor.h.
Constructor & Destructor Documentation
ArcEditor() [1/2]
ArcEditor::ArcEditor (QETElementEditor * editor, PartArc * arc = nullptr, QWidget * parent = nullptr)
Constructeur
Parameters
editor L'editeur d'element concerne
arc L'arc a editer
parent le Widget parent
Definition at line 30 of file arceditor.cpp.
References activeConnections(), angle, h, start_angle, style_, QET::Icons::tr, updateForm(), v, x, and y.
~ArcEditor()
ArcEditor::~ArcEditor () override
Destructeur.
Definition at line 78 of file arceditor.cpp.
ArcEditor() [2/2]
ArcEditor::ArcEditor (const ArcEditor &) private
Member Function Documentation
activeConnections()
void ArcEditor::activeConnections (bool active) private
ArcEditor::activeConnections Enable/disable connection between editor widget and slot editingFinished True == enable | false == disable.
Parameters
active
Definition at line 326 of file arceditor.cpp.
References angle, h, start_angle, updateArcA(), updateArcRectH(), updateArcRectV(), updateArcRectX(), updateArcRectY(), updateArcS(), v, x, and y.
Referenced by ArcEditor(), and updateForm().
currentPart()
CustomElementPart * ArcEditor::currentPart () const override virtual
ArcEditor::currentPart.
Returns
the curent edited part, or 0 if there is no edited part
Implements ElementItemEditor.
Definition at line 143 of file arceditor.cpp.
References part.
currentParts()
QList< CustomElementPart * > ArcEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 147 of file arceditor.cpp.
References StyleEditor::currentParts(), and style_.
disconnectChangeConnections()
void ArcEditor::disconnectChangeConnections () private
Definition at line 89 of file arceditor.cpp.
References m_change_connections.
Referenced by setPart().
setPart()
bool ArcEditor::setPart (CustomElementPart * new_part) override virtual
ArcEditor::setPart Specifie to this editor the part to edit. Note that an editor can accept or refuse to edit a part. This editor accept only partArc.
Parameters
new_part
Returns
Implements ElementItemEditor.
Definition at line 104 of file arceditor.cpp.
References disconnectChangeConnections(), part, setUpChangeConnections(), and updateForm().
Referenced by setParts().
setParts()
bool ArcEditor::setParts (QList< CustomElementPart * > parts) override virtual
Reimplemented from ElementItemEditor.
Definition at line 129 of file arceditor.cpp.
References setPart(), StyleEditor::setParts(), and style_.
setUpChangeConnections()
void ArcEditor::setUpChangeConnections () private
setUpChangeConnections Setup the connection from the arc(s) to the widget, to update it when the arc(s) are changed (moved ...)
Definition at line 80 of file arceditor.cpp.
References m_change_connections, part, AbstractPartEllipse::rectChanged(), AbstractPartEllipse::spanAngleChanged(), AbstractPartEllipse::startAngleChanged(), and updateForm().
Referenced by setPart().
updateArcA
void ArcEditor::updateArcA () slot
ArcEditor::updateArcA Update the span angle of the arc according to the edited value.
Definition at line 181 of file arceditor.cpp.
References angle, StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, part, CustomElementGraphicPart::property(), style_, and ElementScene::undoStack().
Referenced by activeConnections().
updateArcRectH
void ArcEditor::updateArcRectH () slot
Definition at line 256 of file arceditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), h, m_locked, part, CustomElementGraphicPart::property(), style_, and ElementScene::undoStack().
Referenced by activeConnections().
updateArcRectV
void ArcEditor::updateArcRectV () slot
Definition at line 279 of file arceditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, part, CustomElementGraphicPart::property(), style_, ElementScene::undoStack(), and v.
Referenced by activeConnections().
updateArcRectX
void ArcEditor::updateArcRectX () slot
ArcEditor::updateArcRect Update the geometrie of the rect that define this arc according the the edited values.
Definition at line 206 of file arceditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), h, m_locked, part, CustomElementGraphicPart::property(), style_, ElementScene::undoStack(), v, x, and y.
Referenced by activeConnections().
updateArcRectY
void ArcEditor::updateArcRectY () slot
Definition at line 230 of file arceditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), h, m_locked, part, CustomElementGraphicPart::property(), style_, ElementScene::undoStack(), v, x, and y.
Referenced by activeConnections().
updateArcS
void ArcEditor::updateArcS () slot
ArcEditor::updateArcS Update the start angle of the arc according to the edited value.
Definition at line 155 of file arceditor.cpp.
References StyleEditor::currentParts(), ElementItemEditor::elementScene(), QPropertyUndoCommand::enableAnimation(), m_locked, part, CustomElementGraphicPart::property(), start_angle, style_, and ElementScene::undoStack().
Referenced by activeConnections().
updateForm
void ArcEditor::updateForm () override slot
ArcEditor::updateForm Update the value of the widgets.
Definition at line 306 of file arceditor.cpp.
References activeConnections(), angle, h, part, CustomElementGraphicPart::property(), start_angle, v, x, and y.
Referenced by ArcEditor(), setPart(), and setUpChangeConnections().
Member Data Documentation
angle
QSpinBox* ArcEditor::angle private
Definition at line 47 of file arceditor.h.
Referenced by activeConnections(), ArcEditor(), updateArcA(), and updateForm().
h
QDoubleSpinBox * ArcEditor::h private
Definition at line 46 of file arceditor.h.
Referenced by activeConnections(), ArcEditor(), updateArcRectH(), updateArcRectX(), updateArcRectY(), and updateForm().
m_change_connections
QList<QMetaObject::Connection> ArcEditor::m_change_connections private
Definition at line 50 of file arceditor.h.
Referenced by disconnectChangeConnections(), and setUpChangeConnections().
m_locked
bool ArcEditor::m_locked private
Definition at line 48 of file arceditor.h.
Referenced by updateArcA(), updateArcRectH(), updateArcRectV(), updateArcRectX(), updateArcRectY(), and updateArcS().
part
PartArc* ArcEditor::part private
Definition at line 44 of file arceditor.h.
Referenced by currentPart(), setPart(), setUpChangeConnections(), updateArcA(), updateArcRectH(), updateArcRectV(), updateArcRectX(), updateArcRectY(), updateArcS(), and updateForm().
start_angle
QSpinBox * ArcEditor::start_angle private
Definition at line 47 of file arceditor.h.
Referenced by activeConnections(), ArcEditor(), updateArcS(), and updateForm().
style_
StyleEditor* ArcEditor::style_ private
Definition at line 45 of file arceditor.h.
Referenced by ArcEditor(), currentParts(), setParts(), updateArcA(), updateArcRectH(), updateArcRectV(), updateArcRectX(), updateArcRectY(), and updateArcS().
v
QDoubleSpinBox * ArcEditor::v private
Definition at line 46 of file arceditor.h.
Referenced by activeConnections(), ArcEditor(), updateArcRectV(), updateArcRectX(), updateArcRectY(), and updateForm().
x
QDoubleSpinBox* ArcEditor::x private
Definition at line 46 of file arceditor.h.
Referenced by activeConnections(), ArcEditor(), updateArcRectX(), updateArcRectY(), and updateForm().
y
QDoubleSpinBox * ArcEditor::y private
Definition at line 46 of file arceditor.h.
Referenced by activeConnections(), ArcEditor(), updateArcRectX(), updateArcRectY(), and updateForm().
The documentation for this class was generated from the following files:
arceditor.h
arceditor.cpp