QElectroTech: DiagramEventAddImage Class Reference
DiagramEventAddImage Class Reference
The DiagramEventAddImage class This diagram event, handle the adding of an image in a diagram.
#include <diagrameventaddimage.h>
Public Member Functions
DiagramEventAddImage (Diagram *diagram)
DiagramEventAddImage::DiagramEventAddImage Default constructor.
~DiagramEventAddImage () override
DiagramEventAddImage::~DiagramEventAddImage.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddImage::mousePressEvent Action when mouse is pressed.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddImage::mouseMoveEvent Action when mouse move.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
DiagramEventAddImage::mouseDoubleClickEvent This method is only use to overwrite double click. When double click, image propertie dialog isn't open.
void wheelEvent (QGraphicsSceneWheelEvent *event) override
DiagramEventAddImage::wheelEvent Action when mouse wheel is rotate.
bool isNull () const
DiagramEventAddImage::isNull.
Public Member Functions inherited from DiagramEventInterface
DiagramEventInterface (Diagram *diagram)
~DiagramEventInterface () override=0
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
DiagramEventInterface::keyPressEvent By default, press escape key abort the curent action.
virtual void keyReleaseEvent (QKeyEvent *event)
virtual bool isRunning () const
virtual void init ()
Private Member Functions
void openDialog ()
DiagramEventAddImage::openDialog Open dialog for select the image to add.
Private Attributes
DiagramImageItem * m_image
bool m_is_added
Additional Inherited Members
Signals inherited from DiagramEventInterface
void finish ()
Protected Attributes inherited from DiagramEventInterface
Diagram * m_diagram
bool m_running
bool m_abort
Detailed Description
The DiagramEventAddImage class This diagram event, handle the adding of an image in a diagram.
Definition at line 30 of file diagrameventaddimage.h.
Constructor & Destructor Documentation
DiagramEventAddImage()
DiagramEventAddImage::DiagramEventAddImage (Diagram * diagram)
DiagramEventAddImage::DiagramEventAddImage Default constructor.
Parameters
diagram : diagram where operate this event
Definition at line 29 of file diagrameventaddimage.cpp.
References openDialog().
~DiagramEventAddImage()
DiagramEventAddImage::~DiagramEventAddImage () override
DiagramEventAddImage::~DiagramEventAddImage.
Definition at line 40 of file diagrameventaddimage.cpp.
References DiagramEventInterface::m_abort, DiagramEventInterface::m_diagram, m_image, m_is_added, DiagramEventInterface::m_running, and Diagram::removeItem().
Member Function Documentation
isNull()
bool DiagramEventAddImage::isNull () const
DiagramEventAddImage::isNull.
Returns
: true if image can't be loaded, otherwise return false.
Definition at line 142 of file diagrameventaddimage.cpp.
References m_image.
Referenced by QETDiagramEditor::addItemGroupTriggered().
mouseDoubleClickEvent()
void DiagramEventAddImage::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddImage::mouseDoubleClickEvent This method is only use to overwrite double click. When double click, image propertie dialog isn't open.
Parameters
event : event of mouse double click.
Reimplemented from DiagramEventInterface.
Definition at line 114 of file diagrameventaddimage.cpp.
mouseMoveEvent()
void DiagramEventAddImage::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddImage::mouseMoveEvent Action when mouse move.
Parameters
event : event of mouse move
Reimplemented from DiagramEventInterface.
Definition at line 86 of file diagrameventaddimage.cpp.
References Diagram::addItem(), DiagramImageItem::boundingRect(), DiagramEventInterface::m_diagram, m_image, m_is_added, and QetGraphicsItem::setPos().
mousePressEvent()
void DiagramEventAddImage::mousePressEvent (QGraphicsSceneMouseEvent * event) override virtual
DiagramEventAddImage::mousePressEvent Action when mouse is pressed.
Parameters
event : event of mouse pressed
Reimplemented from DiagramEventInterface.
Definition at line 57 of file diagrameventaddimage.cpp.
References DiagramImageItem::boundingRect(), DiagramEventInterface::finish(), DiagramEventInterface::m_diagram, m_image, and DiagramEventInterface::m_running.
openDialog()
void DiagramEventAddImage::openDialog () private
DiagramEventAddImage::openDialog Open dialog for select the image to add.
Definition at line 152 of file diagrameventaddimage.cpp.
References QET::QetMessageBox::critical(), Diagram::isEmpty(), DiagramEventInterface::m_diagram, m_image, DiagramEventInterface::m_running, and QET::Icons::tr.
Referenced by DiagramEventAddImage().
wheelEvent()
void DiagramEventAddImage::wheelEvent (QGraphicsSceneWheelEvent * event) override virtual
DiagramEventAddImage::wheelEvent Action when mouse wheel is rotate.
Parameters
event evet of mouse wheel
Reimplemented from DiagramEventInterface.
Definition at line 123 of file diagrameventaddimage.cpp.
References m_image, and m_is_added.
Member Data Documentation
m_image
DiagramImageItem* DiagramEventAddImage::m_image private
Definition at line 47 of file diagrameventaddimage.h.
Referenced by isNull(), mouseMoveEvent(), mousePressEvent(), openDialog(), wheelEvent(), and ~DiagramEventAddImage().
m_is_added
bool DiagramEventAddImage::m_is_added private
Definition at line 48 of file diagrameventaddimage.h.
Referenced by mouseMoveEvent(), wheelEvent(), and ~DiagramEventAddImage().
The documentation for this class was generated from the following files:
diagrameventaddimage.h
diagrameventaddimage.cpp