QElectroTech: NewDiagramPage Class Reference
NewDiagramPage Class Reference
The NewDiagramPage class This configuration page enables users to define the properties of new diagrams to come.
#include <configpages.h>
Public Slots
void changeToAutoFolioTab ()
NewDiagramPage::changeToAutoFolioTab Set the current tab to Autonum.
void setFolioAutonum (QString)
NewDiagramPage::setFolioAutonum Set temporary TBP to use in auto folio num.
void saveCurrentTbp ()
NewDiagramPage::saveCurrentTbp Save current TBP to retrieve after auto folio num.
void loadSavedTbp ()
NewDiagramPage::loadSavedTbp Retrieve saved auto folio num.
Public Member Functions
NewDiagramPage (QETProject *project=nullptr, QWidget *=nullptr, ProjectPropertiesDialog *teste=nullptr)
NewDiagramPage::NewDiagramPage Default constructor.
~NewDiagramPage () override
NewDiagramPage::~NewDiagramPage.
void applyConf () override
NewDiagramPage::applyConf Apply conf for this page. If there is a project, save in the project, else save to the default conf of QElectroTech.
QString title () const override
NewDiagramPage::title.
QIcon icon () const override
NewDiagramPage::icon.
Public Member Functions inherited from ConfigPage
ConfigPage (QWidget *parent)
~ConfigPage () override
Destructor.
Private Member Functions
NewDiagramPage (const NewDiagramPage &)
Private Attributes
ProjectPropertiesDialog * ppd_
QETProject * m_project
Project to edit propertie.
BorderPropertiesWidget * bpw
Widget to edit default diagram dimensions.
TitleBlockPropertiesWidget * ipw
Widget to edit default title block properties.
ConductorPropertiesWidget * m_cpw
Widget to edit default conductor properties.
ReportPropertieWidget * rpw
Widget to edit default report label.
XRefPropertiesWidget * xrefpw
Widget to edit default xref properties.
TitleBlockProperties savedTbp
Used to save current TBP and retrieve later.
Detailed Description
The NewDiagramPage class This configuration page enables users to define the properties of new diagrams to come.
Definition at line 39 of file configpages.h.
Constructor & Destructor Documentation
NewDiagramPage() [1/2]
NewDiagramPage::NewDiagramPage (QETProject * project = nullptr, QWidget * parent = nullptr, ProjectPropertiesDialog * ppd = nullptr)
NewDiagramPage::NewDiagramPage Default constructor.
Parameters
project : QETProject
parent : QWidget
ppd : ProjectPropertiesDialog
Definition at line 42 of file configpages.cpp.
References bpw, changeToAutoFolioTab(), QETApp::commonTitleBlockTemplatesCollection(), QETApp::customTitleBlockTemplatesCollection(), ReportProperties::defaultProperties(), BorderProperties::defaultProperties(), TitleBlockProperties::defaultProperties(), XRefProperties::defaultProperties(), ConductorProperties::defaultProperties(), QETProject::embeddedTitleBlockTemplatesCollection(), ipw, m_cpw, m_project, rpw, ConductorPropertiesWidget::setHiddenAvailableAutonum(), QET::Icons::tr, and xrefpw.
~NewDiagramPage()
NewDiagramPage::~NewDiagramPage () override
NewDiagramPage::~NewDiagramPage.
Definition at line 106 of file configpages.cpp.
References changeToAutoFolioTab(), and ipw.
NewDiagramPage() [2/2]
NewDiagramPage::NewDiagramPage (const NewDiagramPage &) private
Member Function Documentation
applyConf()
void NewDiagramPage::applyConf () override virtual
NewDiagramPage::applyConf Apply conf for this page. If there is a project, save in the project, else save to the default conf of QElectroTech.
Implements ConfigPage.
Definition at line 116 of file configpages.cpp.
References bpw, ipw, m_cpw, m_project, rpw, ReportPropertieWidget::toSettings(), XRefProperties::toSettings(), and xrefpw.
Referenced by loadSavedTbp(), and setFolioAutonum().
changeToAutoFolioTab
void NewDiagramPage::changeToAutoFolioTab () slot
NewDiagramPage::changeToAutoFolioTab Set the current tab to Autonum.
Definition at line 203 of file configpages.cpp.
References ProjectPropertiesDialog::Autonum, ProjectPropertiesDialog::changeToFolio(), ProjectPropertiesDialog::exec(), m_project, ppd_, and ProjectPropertiesDialog::setCurrentPage().
Referenced by NewDiagramPage(), and ~NewDiagramPage().
icon()
QIcon NewDiagramPage::icon () const override virtual
NewDiagramPage::icon.
Returns
icon of this page
Implements ConfigPage.
Definition at line 185 of file configpages.cpp.
References m_project, QET::Icons::NewDiagram, and QET::Icons::Projects.
loadSavedTbp
void NewDiagramPage::loadSavedTbp () slot
NewDiagramPage::loadSavedTbp Retrieve saved auto folio num.
Definition at line 233 of file configpages.cpp.
References applyConf(), ipw, savedTbp, and TitleBlockPropertiesWidget::setProperties().
saveCurrentTbp
void NewDiagramPage::saveCurrentTbp () slot
NewDiagramPage::saveCurrentTbp Save current TBP to retrieve after auto folio num.
Definition at line 225 of file configpages.cpp.
References ipw, TitleBlockPropertiesWidget::properties(), and savedTbp.
setFolioAutonum
void NewDiagramPage::setFolioAutonum (QString autoNum) slot
NewDiagramPage::setFolioAutonum Set temporary TBP to use in auto folio num.
Definition at line 215 of file configpages.cpp.
References applyConf(), ipw, TitleBlockPropertiesWidget::propertiesAutoNum(), and TitleBlockPropertiesWidget::setProperties().
title()
QString NewDiagramPage::title () const override virtual
NewDiagramPage::title.
Returns
title of this page
Implements ConfigPage.
Definition at line 194 of file configpages.cpp.
References m_project, and QET::Icons::tr.
Member Data Documentation
bpw
BorderPropertiesWidget* NewDiagramPage::bpw private
Widget to edit default diagram dimensions.
Definition at line 66 of file configpages.h.
Referenced by applyConf(), and NewDiagramPage().
ipw
TitleBlockPropertiesWidget* NewDiagramPage::ipw private
Widget to edit default title block properties.
Definition at line 67 of file configpages.h.
Referenced by applyConf(), loadSavedTbp(), NewDiagramPage(), saveCurrentTbp(), setFolioAutonum(), and ~NewDiagramPage().
m_cpw
ConductorPropertiesWidget* NewDiagramPage::m_cpw private
Widget to edit default conductor properties.
Definition at line 68 of file configpages.h.
Referenced by applyConf(), and NewDiagramPage().
m_project
QETProject* NewDiagramPage::m_project private
Project to edit propertie.
Definition at line 65 of file configpages.h.
Referenced by applyConf(), changeToAutoFolioTab(), icon(), NewDiagramPage(), and title().
ppd_
ProjectPropertiesDialog* NewDiagramPage::ppd_ private
Definition at line 64 of file configpages.h.
Referenced by changeToAutoFolioTab().
rpw
ReportPropertieWidget* NewDiagramPage::rpw private
Widget to edit default report label.
Definition at line 69 of file configpages.h.
Referenced by applyConf(), and NewDiagramPage().
savedTbp
TitleBlockProperties NewDiagramPage::savedTbp private
Used to save current TBP and retrieve later.
Definition at line 71 of file configpages.h.
Referenced by loadSavedTbp(), and saveCurrentTbp().
xrefpw
XRefPropertiesWidget* NewDiagramPage::xrefpw private
Widget to edit default xref properties.
Definition at line 70 of file configpages.h.
Referenced by applyConf(), and NewDiagramPage().
The documentation for this class was generated from the following files:
configpages.h
configpages.cpp