QElectroTech: xpath_string Class Reference
xpath_string Class Reference
Public Member Functions
xpath_string ()
void append (const xpath_string &o, xpath_allocator *alloc)
const char_t * c_str () const
size_t length () const
char_t * data (xpath_allocator *alloc)
bool empty () const
bool operator== (const xpath_string &o) const
bool operator!= (const xpath_string &o) const
bool uses_heap () const
Static Public Member Functions
static xpath_string from_const (const char_t *str)
static xpath_string from_heap_preallocated (const char_t *begin, const char_t *end)
static xpath_string from_heap (const char_t *begin, const char_t *end, xpath_allocator *alloc)
Private Member Functions
xpath_string (const char_t *buffer, bool uses_heap_, size_t length_heap)
Static Private Member Functions
static char_t * duplicate_string (const char_t *string, size_t length, xpath_allocator *alloc)
Private Attributes
const char_t * _buffer
bool _uses_heap
size_t _length_heap
Detailed Description
Definition at line 7794 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_string() [1/2]
xpath_string::xpath_string (const char_t * buffer, bool uses_heap_, size_t length_heap) inline private
Definition at line 7811 of file pugixml.cpp.
xpath_string() [2/2]
xpath_string::xpath_string () inline
Definition at line 7841 of file pugixml.cpp.
Referenced by from_const(), from_heap(), and from_heap_preallocated().
Member Function Documentation
append()
void xpath_string::append (const xpath_string & o, xpath_allocator * alloc) inline
Definition at line 7845 of file pugixml.cpp.
References _buffer, _length_heap, _uses_heap, length(), and xpath_allocator::reallocate().
Referenced by string_value().
c_str()
const char_t* xpath_string::c_str () const inline
Definition at line 7880 of file pugixml.cpp.
References _buffer.
Referenced by xpath_ast_node::compare_eq(), xpath_ast_node::compare_rel(), xpath_ast_node::eval_boolean(), xpath_ast_node::eval_number(), and xpath_ast_node::eval_string().
data()
char_t* xpath_string::data (xpath_allocator * alloc) inline
Definition at line 7890 of file pugixml.cpp.
References _buffer, _length_heap, _uses_heap, duplicate_string(), and strlength().
Referenced by xpath_ast_node::eval_string(), and from_heap().
duplicate_string()
static char_t* xpath_string::duplicate_string (const char_t * string, size_t length, xpath_allocator * alloc) inline static private
Definition at line 7800 of file pugixml.cpp.
References xpath_allocator::allocate(), and length().
Referenced by data(), and from_heap().
empty()
bool xpath_string::empty () const inline
Definition at line 7908 of file pugixml.cpp.
References _buffer.
Referenced by xpath_ast_node::eval_boolean().
from_const()
static xpath_string xpath_string::from_const (const char_t * str) inline static
Definition at line 7816 of file pugixml.cpp.
References xpath_string().
Referenced by convert_number_to_string(), xpath_ast_node::eval_string(), and string_value().
from_heap()
static xpath_string xpath_string::from_heap (const char_t * begin, const char_t * end, xpath_allocator * alloc) inline static
Definition at line 7828 of file pugixml.cpp.
References data(), duplicate_string(), length(), and xpath_string().
Referenced by xpath_ast_node::eval_string().
from_heap_preallocated()
static xpath_string xpath_string::from_heap_preallocated (const char_t * begin, const char_t * end) inline static
Definition at line 7821 of file pugixml.cpp.
References xpath_string().
Referenced by convert_number_to_string(), xpath_ast_node::eval_string(), and xpath_ast_node::eval_string_concat().
length()
size_t xpath_string::length () const inline
Definition at line 7885 of file pugixml.cpp.
References _buffer, _length_heap, _uses_heap, and strlength().
Referenced by append(), duplicate_string(), xpath_ast_node::eval_number(), xpath_ast_node::eval_string(), and from_heap().
operator!=()
bool xpath_string::operator!= (const xpath_string & o) const inline
Definition at line 7918 of file pugixml.cpp.
References _buffer, and strequal().
operator==()
bool xpath_string::operator== (const xpath_string & o) const inline
Definition at line 7913 of file pugixml.cpp.
References _buffer, and strequal().
uses_heap()
bool xpath_string::uses_heap () const inline
Definition at line 7923 of file pugixml.cpp.
References _uses_heap.
Referenced by xpath_ast_node::eval_string().
Member Data Documentation
_buffer
const char_t* xpath_string::_buffer private
Definition at line 7796 of file pugixml.cpp.
Referenced by append(), c_str(), data(), empty(), length(), operator!=(), and operator==().
_length_heap
size_t xpath_string::_length_heap private
Definition at line 7798 of file pugixml.cpp.
Referenced by append(), data(), and length().
_uses_heap
bool xpath_string::_uses_heap private
Definition at line 7797 of file pugixml.cpp.
Referenced by append(), data(), length(), and uses_heap().
The documentation for this class was generated from the following file:
pugixml.cpp