QElectroTech: DiagramContextWidget Class Reference
DiagramContextWidget Class Reference
#include <diagramcontextwidget.h>
Public Slots
void clear ()
DiagramContextWidget::clear Clear any values entered within this widget.
int highlightNonAcceptableKeys ()
DiagramContextWidget::highlightNonAcceptableKeys Highlight keys that would not be accepted by a DiagramContext object.
void refreshFormatLabel ()
DiagramContextWidget::refreshFormatLabel Sets the text describing the acceptable format for keys when adding extra key/value pairs.
Public Member Functions
DiagramContextWidget (QWidget *parent=nullptr)
~DiagramContextWidget ()
DiagramContext context () const
DiagramContextWidget::context.
void setContext (const DiagramContext &context)
DiagramContextWidget::setContext Load the content from context into this widget.
int nameLessRowsCount () const
DiagramContextWidget::nameLessRowsCount.
Private Slots
void checkTableRows ()
DiagramContextWidget::checkTableRows Adds a row in the additional fields table if needed.
Private Attributes
Ui::DiagramContextWidget * ui
Detailed Description
Definition at line 28 of file diagramcontextwidget.h.
Constructor & Destructor Documentation
DiagramContextWidget()
DiagramContextWidget::DiagramContextWidget (QWidget * parent = nullptr) explicit
Definition at line 21 of file diagramcontextwidget.cpp.
References checkTableRows(), and ui.
~DiagramContextWidget()
DiagramContextWidget::~DiagramContextWidget ()
Definition at line 29 of file diagramcontextwidget.cpp.
References ui.
Member Function Documentation
checkTableRows
void DiagramContextWidget::checkTableRows () private slot
DiagramContextWidget::checkTableRows Adds a row in the additional fields table if needed.
Definition at line 170 of file diagramcontextwidget.cpp.
References nameLessRowsCount(), refreshFormatLabel(), and ui.
Referenced by DiagramContextWidget(), and setContext().
clear
void DiagramContextWidget::clear () slot
DiagramContextWidget::clear Clear any values entered within this widget.
Definition at line 104 of file diagramcontextwidget.cpp.
References refreshFormatLabel(), and ui.
Referenced by setContext().
context()
DiagramContext DiagramContextWidget::context () const
DiagramContextWidget::context.
Returns
The diagram context object edited by this widget
Definition at line 38 of file diagramcontextwidget.cpp.
References DiagramContext::addValue(), and ui.
Referenced by setContext(), and ReplaceFolioWidget::titleBlockProperties().
highlightNonAcceptableKeys
int DiagramContextWidget::highlightNonAcceptableKeys () slot
DiagramContextWidget::highlightNonAcceptableKeys Highlight keys that would not be accepted by a DiagramContext object.
Returns
the number of highlighted keys.
Definition at line 119 of file diagramcontextwidget.cpp.
References ui, and DiagramContext::validKeyRegExp().
Referenced by refreshFormatLabel().
nameLessRowsCount()
int DiagramContextWidget::nameLessRowsCount () const
DiagramContextWidget::nameLessRowsCount.
Returns
The count of name-less rows in the table
Definition at line 86 of file diagramcontextwidget.cpp.
References ui.
Referenced by checkTableRows().
refreshFormatLabel
void DiagramContextWidget::refreshFormatLabel () slot
DiagramContextWidget::refreshFormatLabel Sets the text describing the acceptable format for keys when adding extra key/value pairs.
Definition at line 153 of file diagramcontextwidget.cpp.
References highlightNonAcceptableKeys(), QET::Icons::tr, and ui.
Referenced by checkTableRows(), and clear().
setContext()
void DiagramContextWidget::setContext (const DiagramContext & context)
DiagramContextWidget::setContext Load the content from context into this widget.
Parameters
context
Definition at line 67 of file diagramcontextwidget.cpp.
References DiagramContext::Alphabetical, checkTableRows(), clear(), context(), DiagramContext::keys(), and ui.
Referenced by ReplaceFolioWidget::setTitleBlockProperties().
Member Data Documentation
ui
Ui::DiagramContextWidget* DiagramContextWidget::ui private
Definition at line 49 of file diagramcontextwidget.h.
Referenced by checkTableRows(), clear(), context(), DiagramContextWidget(), highlightNonAcceptableKeys(), nameLessRowsCount(), refreshFormatLabel(), setContext(), and ~DiagramContextWidget().
The documentation for this class was generated from the following files:
diagramcontextwidget.h
diagramcontextwidget.cpp