QElectroTech: PartDynamicTextField Class Reference
PartDynamicTextField Class Reference
The PartDynamicTextField class This class represents an editable dynamic text field which may be used to compose the drawing of an electrical element within the element editor. The field will remain editable once the element is added onto a diagram.
#include <partdynamictextfield.h>
Public Types
enum { Type = UserType + 1110 }
Signals
void taggChanged (QString tagg)
void textChanged (QString text)
void textFromChanged (DynamicElementTextItem::TextFrom text_from)
void infoNameChanged (QString info)
void compositeTextChanged (QString text)
void colorChanged (QColor color)
void frameChanged (bool frame)
void textWidthChanged (qreal width)
void alignmentChanged (Qt::Alignment alignment)
void fontChanged (QFont font)
Public Member Functions
void setProperty (const char *name, const QVariant &value) override
PROPERTY.
QVariant property (const char *name) const override
PartDynamicTextField (QETElementEditor *editor, QGraphicsItem *parent=nullptr)
int type () const override
QString name () const override
QString xmlName () const override
bool isUseless () const override
QRectF sceneGeometricRect () const override
void startUserTransformation (const QRectF &initial_selection_rect) override
PartDynamicTextField::startUserTransformation.
void handleUserTransformation (const QRectF &initial_selection_rect, const QRectF &new_selection_rect) override
PartDynamicTextField::handleUserTransformation.
const QDomElement toXml (QDomDocument &dom_doc) const override
PartDynamicTextField::toXml.
void fromXml (const QDomElement &dom_elmt) override
PartDynamicTextField::fromXml.
void fromTextFieldXml (const QDomElement &dom_element)
PartDynamicTextField::fromTextFieldXml Setup this text from the xml definition of a text field (The xml tagg of a text field is "input");.
DynamicElementTextItem::TextFrom textFrom () const
PartDynamicTextField::textFrom.
void setTextFrom (DynamicElementTextItem::TextFrom text_from)
PartDynamicTextField::setTextFrom Set the final text is created from.
QString text () const
PartDynamicTextField::text.
void setText (const QString &text)
PartDynamicTextField::setText Set the text of this text.
void setInfoName (const QString &info_name)
QString infoName () const
PartDynamicTextField::infoName.
void setCompositeText (const QString &text)
PartDynamicTextField::setCompositeText Set the composite text of this text item to text.
QString compositeText () const
PartDynamicTextField::compositeText.
void setColor (const QColor &color)
PartDynamicTextField::setColor.
QColor color () const
PartDynamicTextField::color.
void setFrame (bool frame)
bool frame () const
void setTextWidth (qreal width)
void setPlainText (const QString &text)
void setAlignment (Qt::Alignment alignment)
Qt::Alignment alignment () const
void setFont (const QFont &font)
Public Member Functions inherited from CustomElementPart
CustomElementPart (QETElementEditor *editor)
CustomElementPart Constructor.
virtual ~CustomElementPart ()
~CustomElementPart Destructor
virtual QETElementEditor * elementEditor () const
virtual void updateCurrentPartEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QGraphicsItem * toItem ()
virtual QET::ScalingMethod preferredScalingMethod () const
Static Public Member Functions
static QString xmlTaggName ()
Protected Member Functions
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
PartDynamicTextField::mouseMoveEvent.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
PartDynamicTextField::mousePressEvent.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
PartDynamicTextField::mouseReleaseEvent.
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
PartDynamicTextField::itemChange.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
Protected Member Functions inherited from CustomElementPart
QList< QPointF > mapPoints (const QRectF &, const QRectF &, const QList< QPointF > &)
Properties
QString text
DynamicElementTextItem::TextFrom textFrom
QString infoName
QString compositeText
QColor color
bool frame
qreal textWidth
Qt::Alignment alignment
QFont font
Private Member Functions
void elementInfoChanged ()
PartDynamicTextField::elementInfoChanged Used to up to date this text field, when the element information (see elementScene) changed.
void prepareAlignment ()
void finishAlignment ()
Private Attributes
QPointF m_origine_pos
QPointF m_saved_point
QString m_text
QString m_info_name
QString m_composite_text
DynamicElementTextItem::TextFrom m_text_from = DynamicElementTextItem::UserText
QUuid m_uuid
bool m_frame = false
bool m_first_add = true
bool m_block_alignment = false
qreal m_text_width = -1
Qt::Alignment m_alignment = Qt::AlignTop|Qt::AlignLeft
QRectF m_alignment_rect
Detailed Description
The PartDynamicTextField class This class represents an editable dynamic text field which may be used to compose the drawing of an electrical element within the element editor. The field will remain editable once the element is added onto a diagram.
Definition at line 33 of file partdynamictextfield.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 67 of file partdynamictextfield.h.
Constructor & Destructor Documentation
PartDynamicTextField()
PartDynamicTextField::PartDynamicTextField (QETElementEditor * editor, QGraphicsItem * parent = nullptr)
Definition at line 27 of file partdynamictextfield.cpp.
References QETApp::dynamicTextsItemFont(), setFont(), setText(), setTextFrom(), setTextWidth(), and DynamicElementTextItem::UserText.
Member Function Documentation
alignment()
Qt::Alignment PartDynamicTextField::alignment () const
Definition at line 406 of file partdynamictextfield.cpp.
References m_alignment.
alignmentChanged
void PartDynamicTextField::alignmentChanged (Qt::Alignment alignment) signal
Referenced by setAlignment().
color()
QColor PartDynamicTextField::color () const
PartDynamicTextField::color.
Returns
The color of this text
Definition at line 357 of file partdynamictextfield.cpp.
colorChanged
void PartDynamicTextField::colorChanged (QColor color) signal
Referenced by setColor(), and DynamicTextFieldEditor::setUpConnections().
compositeText()
QString PartDynamicTextField::compositeText () const
PartDynamicTextField::compositeText.
Returns
the composite text of this text
Definition at line 340 of file partdynamictextfield.cpp.
References m_composite_text.
compositeTextChanged
void PartDynamicTextField::compositeTextChanged (QString text) signal
Referenced by setCompositeText(), and DynamicTextFieldEditor::setUpConnections().
elementInfoChanged()
void PartDynamicTextField::elementInfoChanged () private
PartDynamicTextField::elementInfoChanged Used to up to date this text field, when the element information (see elementScene) changed.
Definition at line 535 of file partdynamictextfield.cpp.
References DynamicElementTextItem::CompositeText, DynamicElementTextItem::ElementInfo, CustomElementPart::elementScene(), m_composite_text, m_info_name, m_text_from, autonum::AssignVariables::replaceVariable(), and setPlainText().
Referenced by itemChange().
finishAlignment()
void PartDynamicTextField::finishAlignment () private
Definition at line 550 of file partdynamictextfield.cpp.
References m_alignment, m_alignment_rect, and m_block_alignment.
Referenced by setFont(), and setPlainText().
fontChanged
void PartDynamicTextField::fontChanged (QFont font) signal
Referenced by setFont(), and DynamicTextFieldEditor::setUpConnections().
frame()
bool PartDynamicTextField::frame () const
Definition at line 367 of file partdynamictextfield.cpp.
References m_frame.
frameChanged
void PartDynamicTextField::frameChanged (bool frame) signal
Referenced by setFrame(), and DynamicTextFieldEditor::setUpConnections().
fromTextFieldXml()
void PartDynamicTextField::fromTextFieldXml (const QDomElement & dom_element)
PartDynamicTextField::fromTextFieldXml Setup this text from the xml definition of a text field (The xml tagg of a text field is "input");.
Parameters
dom_element
Definition at line 225 of file partdynamictextfield.cpp.
References QETApp::diagramTextsFont(), DynamicElementTextItem::ElementInfo, setFont(), setInfoName(), setText(), setTextFrom(), and DynamicElementTextItem::UserText.
Referenced by ElementScene::loadContent().
fromXml()
void PartDynamicTextField::fromXml (const QDomElement & dom_elmt) override virtual
PartDynamicTextField::fromXml.
Parameters
dom_elmt
Implements CustomElementPart.
Definition at line 155 of file partdynamictextfield.cpp.
References alignment, QETApp::dynamicTextsItemFont(), m_block_alignment, m_composite_text, m_info_name, m_text, m_text_from, m_uuid, setAlignment(), setColor(), setFont(), setFrame(), setPlainText(), setTextWidth(), DynamicElementTextItem::textFromMetaEnum(), and xmlName().
handleUserTransformation()
void PartDynamicTextField::handleUserTransformation (const QRectF & initial_selection_rect, const QRectF & new_selection_rect) override virtual
PartDynamicTextField::handleUserTransformation.
Parameters
initial_selection_rect
new_selection_rect Handle the user-induced transformation from initial_selection_rect to new_selection_rect
Implements CustomElementPart.
Definition at line 79 of file partdynamictextfield.cpp.
References m_saved_point, and CustomElementPart::mapPoints().
infoName()
QString PartDynamicTextField::infoName () const
PartDynamicTextField::infoName.
Returns
the info name of this text
Definition at line 320 of file partdynamictextfield.cpp.
References m_info_name.
infoNameChanged
void PartDynamicTextField::infoNameChanged (QString info) signal
Referenced by setInfoName(), and DynamicTextFieldEditor::setUpConnections().
isUseless()
bool PartDynamicTextField::isUseless () const inline override virtual
Returns
whether the primitive appears to be useless (e.g. 0-length line) Typically, useless primitives are discarded when saving the element.
Implements CustomElementPart.
Definition at line 73 of file partdynamictextfield.h.
itemChange()
QVariant PartDynamicTextField::itemChange (GraphicsItemChange change, const QVariant & value) override protected
PartDynamicTextField::itemChange.
Parameters
change
value
Returns
Definition at line 468 of file partdynamictextfield.cpp.
References elementInfoChanged(), ElementScene::elementInfoChanged(), CustomElementPart::elementScene(), m_first_add, and CustomElementPart::updateCurrentPartEditor().
mouseMoveEvent()
void PartDynamicTextField::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
PartDynamicTextField::mouseMoveEvent.
Parameters
event
Definition at line 424 of file partdynamictextfield.cpp.
References CustomElementPart::elementScene(), and m_origine_pos.
mousePressEvent()
void PartDynamicTextField::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
PartDynamicTextField::mousePressEvent.
Parameters
event
Definition at line 437 of file partdynamictextfield.cpp.
References m_origine_pos.
mouseReleaseEvent()
void PartDynamicTextField::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
PartDynamicTextField::mouseReleaseEvent.
Parameters
event
Definition at line 448 of file partdynamictextfield.cpp.
References CustomElementPart::elementScene(), m_origine_pos, setText(), QET::Icons::tr, and CustomElementPart::undoStack().
name()
QString PartDynamicTextField::name () const override virtual
Returns
the name of the primitive
Implements CustomElementPart.
Definition at line 52 of file partdynamictextfield.cpp.
References QET::Icons::tr.
Referenced by property(), setProperty(), and toXml().
paint()
void PartDynamicTextField::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override protected
Definition at line 486 of file partdynamictextfield.cpp.
References color, font, m_frame, QET::Icons::ro, and setFont().
prepareAlignment()
void PartDynamicTextField::prepareAlignment () private
Definition at line 546 of file partdynamictextfield.cpp.
References m_alignment_rect.
Referenced by setFont(), and setPlainText().
property()
QVariant PartDynamicTextField::property (const char * name) const inline override virtual
Get the current value of a specific primitive property
Implements CustomElementPart.
Definition at line 50 of file partdynamictextfield.h.
References name().
sceneGeometricRect()
QRectF PartDynamicTextField::sceneGeometricRect () const inline override virtual
Implements CustomElementPart.
Definition at line 74 of file partdynamictextfield.h.
setAlignment()
void PartDynamicTextField::setAlignment (Qt::Alignment alignment)
Definition at line 401 of file partdynamictextfield.cpp.
References alignment, alignmentChanged(), and m_alignment.
Referenced by fromXml().
setColor()
void PartDynamicTextField::setColor (const QColor & color)
PartDynamicTextField::setColor.
Parameters
color set text color to color
Definition at line 348 of file partdynamictextfield.cpp.
References color, and colorChanged().
Referenced by fromXml().
setCompositeText()
void PartDynamicTextField::setCompositeText (const QString & text)
PartDynamicTextField::setCompositeText Set the composite text of this text item to text.
Parameters
text
Definition at line 329 of file partdynamictextfield.cpp.
References DynamicElementTextItem::CompositeText, compositeTextChanged(), CustomElementPart::elementScene(), m_composite_text, m_text_from, autonum::AssignVariables::replaceVariable(), setPlainText(), and text.
Referenced by setTextFrom().
setFont()
void PartDynamicTextField::setFont (const QFont & font)
Definition at line 410 of file partdynamictextfield.cpp.
References finishAlignment(), font, fontChanged(), and prepareAlignment().
Referenced by fromTextFieldXml(), fromXml(), paint(), and PartDynamicTextField().
setFrame()
void PartDynamicTextField::setFrame (bool frame)
Definition at line 361 of file partdynamictextfield.cpp.
References frame, frameChanged(), and m_frame.
Referenced by fromXml().
setInfoName()
void PartDynamicTextField::setInfoName (const QString & info_name)
Definition at line 309 of file partdynamictextfield.cpp.
References DynamicElementTextItem::ElementInfo, CustomElementPart::elementScene(), infoNameChanged(), m_info_name, m_text_from, and setPlainText().
Referenced by fromTextFieldXml(), and setTextFrom().
setPlainText()
void PartDynamicTextField::setPlainText (const QString & text)
Definition at line 382 of file partdynamictextfield.cpp.
References finishAlignment(), m_text_width, prepareAlignment(), setTextWidth(), and text.
Referenced by elementInfoChanged(), fromXml(), setCompositeText(), setInfoName(), setText(), and setTextFrom().
setProperty()
void PartDynamicTextField::setProperty (const char * name, const QVariant & value) inline override virtual
PROPERTY.
Implements CustomElementPart.
Definition at line 49 of file partdynamictextfield.h.
References name().
setText()
void PartDynamicTextField::setText (const QString & text)
PartDynamicTextField::setText Set the text of this text.
Parameters
text
Definition at line 303 of file partdynamictextfield.cpp.
References m_text, setPlainText(), text, and textChanged().
Referenced by fromTextFieldXml(), mouseReleaseEvent(), and PartDynamicTextField().
setTextFrom()
void PartDynamicTextField::setTextFrom (DynamicElementTextItem::TextFrom text_from)
PartDynamicTextField::setTextFrom Set the final text is created from.
Parameters
text_from
Definition at line 272 of file partdynamictextfield.cpp.
References DynamicElementTextItem::CompositeText, DynamicElementTextItem::ElementInfo, m_composite_text, m_info_name, m_text, m_text_from, setCompositeText(), setInfoName(), setPlainText(), textFromChanged(), and DynamicElementTextItem::UserText.
Referenced by fromTextFieldXml(), and PartDynamicTextField().
setTextWidth()
void PartDynamicTextField::setTextWidth (qreal width)
Definition at line 371 of file partdynamictextfield.cpp.
References m_text_width, textWidth, and textWidthChanged().
Referenced by fromXml(), PartDynamicTextField(), and setPlainText().
startUserTransformation()
void PartDynamicTextField::startUserTransformation (const QRectF & initial_selection_rect) override virtual
PartDynamicTextField::startUserTransformation.
Parameters
initial_selection_rect Start the user-induced transformation, provided this primitive is contained within the initial_selection_rect bounding rectangle.
Implements CustomElementPart.
Definition at line 67 of file partdynamictextfield.cpp.
References m_saved_point.
taggChanged
void PartDynamicTextField::taggChanged (QString tagg) signal
Referenced by DynamicTextFieldEditor::setUpConnections().
text()
QString PartDynamicTextField::text () const
PartDynamicTextField::text.
Returns
the text of this text
Definition at line 294 of file partdynamictextfield.cpp.
References m_text.
textChanged
void PartDynamicTextField::textChanged (QString text) signal
Referenced by setText(), and DynamicTextFieldEditor::setUpConnections().
textFrom()
DynamicElementTextItem::TextFrom PartDynamicTextField::textFrom () const
PartDynamicTextField::textFrom.
Returns
what the final text is created from.
Definition at line 263 of file partdynamictextfield.cpp.
References m_text_from.
textFromChanged
void PartDynamicTextField::textFromChanged (DynamicElementTextItem::TextFrom text_from) signal
Referenced by setTextFrom(), and DynamicTextFieldEditor::setUpConnections().
textWidthChanged
void PartDynamicTextField::textWidthChanged (qreal width) signal
Referenced by setTextWidth(), and DynamicTextFieldEditor::setUpConnections().
toXml()
const QDomElement PartDynamicTextField::toXml (QDomDocument & dom_doc) const override virtual
PartDynamicTextField::toXml.
Parameters
dom_doc
Returns
Implements CustomElementPart.
Definition at line 93 of file partdynamictextfield.cpp.
References alignment, color, QET::correctAngle(), font, m_composite_text, m_frame, m_info_name, m_text_from, m_text_width, m_uuid, name(), DynamicElementTextItem::textFromMetaEnum(), and xmlName().
type()
int PartDynamicTextField::type () const inline override
Definition at line 68 of file partdynamictextfield.h.
References Type.
xmlName()
QString PartDynamicTextField::xmlName () const override virtual
Returns
the name that will be used as XML tag when exporting the primitive
Implements CustomElementPart.
Definition at line 56 of file partdynamictextfield.cpp.
Referenced by fromXml(), and toXml().
xmlTaggName()
static QString PartDynamicTextField::xmlTaggName () inline static
Definition at line 72 of file partdynamictextfield.h.
Member Data Documentation
m_alignment
Qt::Alignment PartDynamicTextField::m_alignment = Qt::AlignTop|Qt::AlignLeft private
Definition at line 124 of file partdynamictextfield.h.
Referenced by alignment(), finishAlignment(), and setAlignment().
m_alignment_rect
QRectF PartDynamicTextField::m_alignment_rect private
Definition at line 125 of file partdynamictextfield.h.
Referenced by finishAlignment(), and prepareAlignment().
m_block_alignment
bool PartDynamicTextField::m_block_alignment = false private
Definition at line 122 of file partdynamictextfield.h.
Referenced by finishAlignment(), and fromXml().
m_composite_text
QString PartDynamicTextField::m_composite_text private
Definition at line 117 of file partdynamictextfield.h.
Referenced by compositeText(), elementInfoChanged(), fromXml(), setCompositeText(), setTextFrom(), and toXml().
m_first_add
bool PartDynamicTextField::m_first_add = true private
Definition at line 121 of file partdynamictextfield.h.
Referenced by itemChange().
m_frame
bool PartDynamicTextField::m_frame = false private
Definition at line 120 of file partdynamictextfield.h.
Referenced by frame(), paint(), setFrame(), and toXml().
m_info_name
QString PartDynamicTextField::m_info_name private
Definition at line 116 of file partdynamictextfield.h.
Referenced by elementInfoChanged(), fromXml(), infoName(), setInfoName(), setTextFrom(), and toXml().
m_origine_pos
QPointF PartDynamicTextField::m_origine_pos private
Definition at line 113 of file partdynamictextfield.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_saved_point
QPointF PartDynamicTextField::m_saved_point private
Definition at line 114 of file partdynamictextfield.h.
Referenced by handleUserTransformation(), and startUserTransformation().
m_text
QString PartDynamicTextField::m_text private
Definition at line 115 of file partdynamictextfield.h.
Referenced by fromXml(), setText(), setTextFrom(), and text().
m_text_from
DynamicElementTextItem::TextFrom PartDynamicTextField::m_text_from = DynamicElementTextItem::UserText private
Definition at line 118 of file partdynamictextfield.h.
Referenced by elementInfoChanged(), fromXml(), setCompositeText(), setInfoName(), setTextFrom(), textFrom(), and toXml().
m_text_width
qreal PartDynamicTextField::m_text_width = -1 private
Definition at line 123 of file partdynamictextfield.h.
Referenced by setPlainText(), setTextWidth(), and toXml().
m_uuid
QUuid PartDynamicTextField::m_uuid private
Definition at line 119 of file partdynamictextfield.h.
Referenced by fromXml(), and toXml().
Property Documentation
alignment
Qt::Alignment PartDynamicTextField::alignment read write
Definition at line 1 of file partdynamictextfield.h.
Referenced by fromXml(), setAlignment(), and toXml().
color
QColor PartDynamicTextField::color read write
Definition at line 1 of file partdynamictextfield.h.
Referenced by paint(), setColor(), and toXml().
compositeText
QString PartDynamicTextField::compositeText read write
Definition at line 1 of file partdynamictextfield.h.
font
QFont PartDynamicTextField::font read write
Definition at line 1 of file partdynamictextfield.h.
Referenced by paint(), setFont(), and toXml().
frame
bool PartDynamicTextField::frame read write
Definition at line 1 of file partdynamictextfield.h.
Referenced by setFrame().
infoName
QString PartDynamicTextField::infoName read write
Definition at line 1 of file partdynamictextfield.h.
text
QString PartDynamicTextField::text read write
Definition at line 1 of file partdynamictextfield.h.
Referenced by setCompositeText(), setPlainText(), and setText().
textFrom
DynamicElementTextItem::TextFrom PartDynamicTextField::textFrom read write
Definition at line 1 of file partdynamictextfield.h.
textWidth
qreal PartDynamicTextField::textWidth read write
Definition at line 1 of file partdynamictextfield.h.
Referenced by setTextWidth().
The documentation for this class was generated from the following files:
partdynamictextfield.h
partdynamictextfield.cpp