QElectroTech: NameListDialog Class Reference
NameListDialog Class Reference
The NameListDialog class Provide a dialog for let user define localized string;.
#include <namelistdialog.h>
Public Member Functions
NameListDialog (QWidget *parent=nullptr)
~NameListDialog ()
void setInformationText (const QString &text)
NameListWidget * namelistWidget () const
NameListDialog::namelistWidget.
void setHelpText (const QString &text)
void showHelpDialog ()
Private Attributes
Ui::NameListDialog * ui
NameListWidget * m_namelist_widget = nullptr
QString m_help_text
Detailed Description
The NameListDialog class Provide a dialog for let user define localized string;.
Definition at line 33 of file namelistdialog.h.
Constructor & Destructor Documentation
NameListDialog()
NameListDialog::NameListDialog (QWidget * parent = nullptr) explicit
Definition at line 25 of file namelistdialog.cpp.
References m_namelist_widget, and ui.
~NameListDialog()
NameListDialog::~NameListDialog ()
Definition at line 38 of file namelistdialog.cpp.
References ui.
Member Function Documentation
namelistWidget()
NameListWidget * NameListDialog::namelistWidget () const
NameListDialog::namelistWidget.
Returns
the name list widget used by this dialog. The ownership of the namelistwidget stay to this dialog
Definition at line 51 of file namelistdialog.cpp.
References m_namelist_widget.
Referenced by TitleBlockTemplateCellWidget::editTranslatableValue(), and ElementScene::slot_editNames().
setHelpText()
void NameListDialog::setHelpText (const QString & text)
Definition at line 55 of file namelistdialog.cpp.
References m_help_text, showHelpDialog(), and ui.
Referenced by TitleBlockTemplateCellWidget::editTranslatableValue().
setInformationText()
void NameListDialog::setInformationText (const QString & text)
Definition at line 42 of file namelistdialog.cpp.
References ui.
Referenced by TitleBlockTemplateCellWidget::editTranslatableValue(), and ElementScene::slot_editNames().
showHelpDialog()
void NameListDialog::showHelpDialog ()
Definition at line 65 of file namelistdialog.cpp.
References QET::QetMessageBox::information(), m_help_text, and QET::Icons::tr.
Referenced by setHelpText().
Member Data Documentation
m_help_text
QString NameListDialog::m_help_text private
Definition at line 49 of file namelistdialog.h.
Referenced by setHelpText(), and showHelpDialog().
m_namelist_widget
NameListWidget* NameListDialog::m_namelist_widget = nullptr private
Definition at line 48 of file namelistdialog.h.
Referenced by NameListDialog(), and namelistWidget().
ui
Ui::NameListDialog* NameListDialog::ui private
Definition at line 47 of file namelistdialog.h.
Referenced by NameListDialog(), setHelpText(), setInformationText(), and ~NameListDialog().
The documentation for this class was generated from the following files:
namelistdialog.h
namelistdialog.cpp