QElectroTech: QFileNameEdit Class Reference
QFileNameEdit Class Reference
#include <qfilenameedit.h>
Public Member Functions
QFileNameEdit (QWidget *=nullptr)
QFileNameEdit (const QString &, QWidget *=nullptr)
~QFileNameEdit () override
bool isEmpty ()
bool isValid ()
Private Slots
void validationFailed ()
Private Member Functions
QFileNameEdit (const QFileNameEdit &)
void init ()
void displayToolTip ()
Private Attributes
QRegExp regexp_
QETRegExpValidator * validator_
QString tooltip_text_
Detailed Description
This class represents a textfield dedicated to input a portable filename (not a path). It enables users to input a name matching the regular expression ^[0-9a-z_-.]+$, thus avoiding problems with diacritics, non-printable, non-ASCII or uppercase characters, which should improve the portability of elements created by users.
Definition at line 32 of file qfilenameedit.h.
Constructor & Destructor Documentation
QFileNameEdit() [1/3]
QFileNameEdit::QFileNameEdit (QWidget * parent = nullptr)
Constructeur
Parameters
parent QWidget parent de ce champ de texte
Definition at line 28 of file qfilenameedit.cpp.
References init().
QFileNameEdit() [2/3]
QFileNameEdit::QFileNameEdit (const QString & contents, QWidget * parent = nullptr)
Constructeur
Parameters
contents Contenu initial du champ
parent QWidget parent de ce champ de texte
Definition at line 37 of file qfilenameedit.cpp.
References init(), and regexp_.
~QFileNameEdit()
QFileNameEdit::~QFileNameEdit () override
Destructeur
Definition at line 47 of file qfilenameedit.cpp.
QFileNameEdit() [3/3]
QFileNameEdit::QFileNameEdit (const QFileNameEdit &) private
Member Function Documentation
displayToolTip()
void QFileNameEdit::displayToolTip () private
Affiche l'info-bulle informant l'utilisateur des caracteres autorises.
Definition at line 86 of file qfilenameedit.cpp.
References tooltip_text_.
Referenced by validationFailed().
init()
void QFileNameEdit::init () private
Construit l'objet
Definition at line 67 of file qfilenameedit.cpp.
References regexp_, tooltip_text_, QET::Icons::tr, validationFailed(), and validator_.
Referenced by QFileNameEdit().
isEmpty()
bool QFileNameEdit::isEmpty ()
Returns
true si le champ de texte est vide, false sinon
Definition at line 53 of file qfilenameedit.cpp.
Referenced by ElementDialog::checkCurrentLocation().
isValid()
bool QFileNameEdit::isValid ()
Returns
true si le champ de texte n'est pas vide et est valide
Definition at line 60 of file qfilenameedit.cpp.
References regexp_.
validationFailed
void QFileNameEdit::validationFailed () private slot
Gere le fait que la validation du champ de texte ait echoue.
Definition at line 98 of file qfilenameedit.cpp.
References displayToolTip().
Referenced by init().
Member Data Documentation
regexp_
QRegExp QFileNameEdit::regexp_ private
Definition at line 57 of file qfilenameedit.h.
Referenced by init(), isValid(), and QFileNameEdit().
tooltip_text_
QString QFileNameEdit::tooltip_text_ private
Definition at line 59 of file qfilenameedit.h.
Referenced by displayToolTip(), and init().
validator_
QETRegExpValidator* QFileNameEdit::validator_ private
Definition at line 58 of file qfilenameedit.h.
Referenced by init().
The documentation for this class was generated from the following files:
qfilenameedit.h
qfilenameedit.cpp