QElectroTech: XRefProperties Class Reference
XRefProperties Class Reference
The XRefProperties class this class store properties used by XrefItem.
#include <xrefproperties.h>
Public Types
enum DisplayHas { Cross, Contacts }
enum SnapTo { Bottom, Label }
Public Member Functions
XRefProperties ()
XRefProperties::XRefProperties Default Constructor.
void toSettings (QSettings &settings, const QString=QString()) const override
XRefProperties::toSettings Save to settings.
void fromSettings (const QSettings &settings, const QString=QString()) override
XRefProperties::fromSettings load from settings.
QDomElement toXml (QDomDocument &xml_document) const override
XRefProperties::toXml Save to xml.
bool fromXml (const QDomElement &xml_element) override
XRefProperties::fromXml Load from xml.
bool operator== (const XRefProperties &xrp) const
bool operator!= (const XRefProperties &xrp) const
void setShowPowerContac (const bool a)
bool showPowerContact () const
void setDisplayHas (const DisplayHas dh)
DisplayHas displayHas () const
void setSnapTo (const SnapTo st)
SnapTo snapTo () const
void setXrefPos (const Qt::AlignmentFlag xref)
Qt::AlignmentFlag getXrefPos () const
void setPrefix (const QString &key, const QString &value)
QString prefix (const QString &key) const
void setMasterLabel (const QString master)
QString masterLabel () const
void setSlaveLabel (const QString slave)
QString slaveLabel () const
void setOffset (const int offset)
int offset () const
void setKey (QString &key)
Public Member Functions inherited from PropertiesInterface
PropertiesInterface ()
PropertiesInterface::PropertiesInterface.
virtual ~PropertiesInterface ()
PropertiesInterface::~PropertiesInterface.
Static Public Member Functions
static QHash< QString, XRefProperties > defaultProperties ()
XRefProperties::defaultProperties.
Private Attributes
bool m_show_power_ctc
DisplayHas m_display
SnapTo m_snap_to
Qt::AlignmentFlag m_xref_pos
QHash< QString, QString > m_prefix
QStringList m_prefix_keys
QString m_master_label
QString m_slave_label
int m_offset
QString m_key
Detailed Description
The XRefProperties class this class store properties used by XrefItem.
Definition at line 28 of file xrefproperties.h.
Member Enumeration Documentation
DisplayHas
enum XRefProperties::DisplayHas
Enumerator
Cross
Contacts
Definition at line 33 of file xrefproperties.h.
SnapTo
enum XRefProperties::SnapTo
Enumerator
Bottom
Label
Definition at line 38 of file xrefproperties.h.
Constructor & Destructor Documentation
XRefProperties()
XRefProperties::XRefProperties ()
XRefProperties::XRefProperties Default Constructor.
Definition at line 26 of file xrefproperties.cpp.
References Bottom, Cross, m_display, m_master_label, m_offset, m_prefix_keys, m_show_power_ctc, m_slave_label, m_snap_to, and m_xref_pos.
Member Function Documentation
defaultProperties()
QHash< QString, XRefProperties > XRefProperties::defaultProperties () static
XRefProperties::defaultProperties.
Returns
the default properties stored in the setting file For the xref, there is 2 propreties. For coil, stored with the string "coil" in the returned QHash. For protection, stored with the string "protection" in the returned QHash.
Definition at line 165 of file xrefproperties.cpp.
References fromSettings().
Referenced by NewDiagramPage::NewDiagramPage(), and QETProject::readDefaultPropertiesXml().
displayHas()
DisplayHas XRefProperties::displayHas () const inline
Definition at line 59 of file xrefproperties.h.
References m_display.
Referenced by CrossRefItem::NCElements(), CrossRefItem::NOElements(), XRefPropertiesWidget::updateDisplay(), and CrossRefItem::updateLabel().
fromSettings()
void XRefProperties::fromSettings (const QSettings & settings, const QString prefix = QString()) override virtual
XRefProperties::fromSettings load from settings.
Parameters
settings QSettings to use
prefix prefix before properties name
Implements PropertiesInterface.
Definition at line 73 of file xrefproperties.cpp.
References Bottom, Contacts, Cross, Label, m_display, m_master_label, m_offset, m_prefix, m_prefix_keys, m_show_power_ctc, m_slave_label, m_snap_to, m_xref_pos, and prefix().
Referenced by defaultProperties().
fromXml()
bool XRefProperties::fromXml (const QDomElement & xml_element) override virtual
XRefProperties::fromXml Load from xml.
Parameters
xml_element QDomElement to use for load
Implements PropertiesInterface.
Definition at line 133 of file xrefproperties.cpp.
References Bottom, Contacts, Cross, Label, m_display, m_master_label, m_offset, m_prefix, m_prefix_keys, m_show_power_ctc, m_slave_label, m_snap_to, and m_xref_pos.
Referenced by QETProject::readDefaultPropertiesXml().
getXrefPos()
Qt::AlignmentFlag XRefProperties::getXrefPos () const inline
Definition at line 65 of file xrefproperties.h.
References m_xref_pos.
Referenced by DynamicElementTextItem::setPlainText(), XRefPropertiesWidget::updateDisplay(), and DynamicElementTextItem::updateXref().
masterLabel()
QString XRefProperties::masterLabel () const inline
Definition at line 70 of file xrefproperties.h.
References m_master_label.
Referenced by CrossRefItem::elementPositionText(), and XRefPropertiesWidget::updateDisplay().
offset()
int XRefProperties::offset () const inline
Definition at line 76 of file xrefproperties.h.
References m_offset.
Referenced by CrossRefItem::autoPos(), ElementTextItemGroup::autoPos(), setOffset(), toSettings(), toXml(), and XRefPropertiesWidget::updateDisplay().
operator!=()
bool XRefProperties::operator!= (const XRefProperties & xrp) const
Definition at line 194 of file xrefproperties.cpp.
operator==()
bool XRefProperties::operator== (const XRefProperties & xrp) const
Definition at line 184 of file xrefproperties.cpp.
References m_display, m_master_label, m_offset, m_prefix, m_show_power_ctc, m_snap_to, and m_xref_pos.
prefix()
QString XRefProperties::prefix (const QString & key) const inline
Definition at line 67 of file xrefproperties.h.
References m_prefix.
Referenced by CrossRefItem::elementPositionText(), fromSettings(), toSettings(), and XRefPropertiesWidget::updateDisplay().
setDisplayHas()
void XRefProperties::setDisplayHas (const DisplayHas dh) inline
Definition at line 58 of file xrefproperties.h.
References m_display.
Referenced by XRefPropertiesWidget::saveProperties().
setKey()
void XRefProperties::setKey (QString & key) inline
Definition at line 78 of file xrefproperties.h.
References m_key.
setMasterLabel()
void XRefProperties::setMasterLabel (const QString master) inline
Definition at line 69 of file xrefproperties.h.
References m_master_label.
Referenced by XRefPropertiesWidget::saveProperties().
setOffset()
void XRefProperties::setOffset (const int offset) inline
Definition at line 75 of file xrefproperties.h.
References m_offset, and offset().
Referenced by XRefPropertiesWidget::saveProperties().
setPrefix()
void XRefProperties::setPrefix (const QString & key, const QString & value) inline
Definition at line 66 of file xrefproperties.h.
References m_prefix.
Referenced by XRefPropertiesWidget::saveProperties().
setShowPowerContac()
void XRefProperties::setShowPowerContac (const bool a) inline
Definition at line 55 of file xrefproperties.h.
References m_show_power_ctc.
Referenced by XRefPropertiesWidget::saveProperties().
setSlaveLabel()
void XRefProperties::setSlaveLabel (const QString slave) inline
Definition at line 72 of file xrefproperties.h.
References m_slave_label.
Referenced by XRefPropertiesWidget::saveProperties().
setSnapTo()
void XRefProperties::setSnapTo (const SnapTo st) inline
Definition at line 61 of file xrefproperties.h.
References m_snap_to.
Referenced by XRefPropertiesWidget::saveProperties().
setXrefPos()
void XRefProperties::setXrefPos (const Qt::AlignmentFlag xref) inline
Definition at line 64 of file xrefproperties.h.
References m_xref_pos.
Referenced by XRefPropertiesWidget::saveProperties().
showPowerContact()
bool XRefProperties::showPowerContact () const inline
Definition at line 56 of file xrefproperties.h.
References m_show_power_ctc.
Referenced by CrossRefItem::NCElements(), CrossRefItem::NOElements(), and XRefPropertiesWidget::updateDisplay().
slaveLabel()
QString XRefProperties::slaveLabel () const inline
Definition at line 73 of file xrefproperties.h.
References m_slave_label.
Referenced by XRefPropertiesWidget::updateDisplay(), DynamicElementTextItem::updateXref(), and ElementTextItemGroup::updateXref().
snapTo()
SnapTo XRefProperties::snapTo () const inline
Definition at line 62 of file xrefproperties.h.
References m_snap_to.
Referenced by MasterElement::aboutDeleteXref(), CrossRefItem::autoPos(), ElementTextItemGroup::autoPos(), MasterElement::linkToElement(), CrossRefItem::setUpConnection(), XRefPropertiesWidget::updateDisplay(), CrossRefItem::updateProperties(), DynamicElementTextItem::updateXref(), ElementTextItemGroup::updateXref(), and MasterElement::xrefPropertiesChanged().
toSettings()
void XRefProperties::toSettings (QSettings & settings, const QString prefix = QString()) const override virtual
XRefProperties::toSettings Save to settings.
Parameters
settings QSettings to use
prefix prefix before properties name
Implements PropertiesInterface.
Definition at line 44 of file xrefproperties.cpp.
References Bottom, Cross, m_display, m_master_label, m_offset, m_prefix, m_show_power_ctc, m_slave_label, m_snap_to, m_xref_pos, offset(), and prefix().
Referenced by NewDiagramPage::applyConf().
toXml()
QDomElement XRefProperties::toXml (QDomDocument & xml_document) const override virtual
XRefProperties::toXml Save to xml.
Parameters
xml_document : QDomElement to use for saving
Returns
QDomElement
Implements PropertiesInterface.
Definition at line 99 of file xrefproperties.cpp.
References Bottom, Cross, m_display, m_key, m_master_label, m_offset, m_prefix, m_show_power_ctc, m_slave_label, m_snap_to, m_xref_pos, and offset().
Member Data Documentation
m_display
DisplayHas XRefProperties::m_display private
Definition at line 82 of file xrefproperties.h.
Referenced by displayHas(), fromSettings(), fromXml(), operator==(), setDisplayHas(), toSettings(), toXml(), and XRefProperties().
m_key
QString XRefProperties::m_key private
Definition at line 90 of file xrefproperties.h.
Referenced by setKey(), and toXml().
m_master_label
QString XRefProperties::m_master_label private
Definition at line 87 of file xrefproperties.h.
Referenced by fromSettings(), fromXml(), masterLabel(), operator==(), setMasterLabel(), toSettings(), toXml(), and XRefProperties().
m_offset
int XRefProperties::m_offset private
Definition at line 89 of file xrefproperties.h.
Referenced by fromSettings(), fromXml(), offset(), operator==(), setOffset(), toSettings(), toXml(), and XRefProperties().
m_prefix
QHash<QString, QString> XRefProperties::m_prefix private
Definition at line 85 of file xrefproperties.h.
Referenced by fromSettings(), fromXml(), operator==(), prefix(), setPrefix(), toSettings(), and toXml().
m_prefix_keys
QStringList XRefProperties::m_prefix_keys private
Definition at line 86 of file xrefproperties.h.
Referenced by fromSettings(), fromXml(), and XRefProperties().
m_show_power_ctc
bool XRefProperties::m_show_power_ctc private
Definition at line 81 of file xrefproperties.h.
Referenced by fromSettings(), fromXml(), operator==(), setShowPowerContac(), showPowerContact(), toSettings(), toXml(), and XRefProperties().
m_slave_label
QString XRefProperties::m_slave_label private
Definition at line 88 of file xrefproperties.h.
Referenced by fromSettings(), fromXml(), setSlaveLabel(), slaveLabel(), toSettings(), toXml(), and XRefProperties().
m_snap_to
SnapTo XRefProperties::m_snap_to private
Definition at line 83 of file xrefproperties.h.
Referenced by fromSettings(), fromXml(), operator==(), setSnapTo(), snapTo(), toSettings(), toXml(), and XRefProperties().
m_xref_pos
Qt::AlignmentFlag XRefProperties::m_xref_pos private
Definition at line 84 of file xrefproperties.h.
Referenced by fromSettings(), fromXml(), getXrefPos(), operator==(), setXrefPos(), toSettings(), toXml(), and XRefProperties().
The documentation for this class was generated from the following files:
xrefproperties.h
xrefproperties.cpp