QElectroTech: SummaryQueryWidget Class Reference
SummaryQueryWidget Class Reference
#include <summaryquerywidget.h>
Public Member Functions
SummaryQueryWidget (QWidget *parent=nullptr)
SummaryQueryWidget::SummaryQueryWidget.
~SummaryQueryWidget ()
SummaryQueryWidget::~SummaryQueryWidget.
QString queryStr () const
SummaryQueryWidget::queryStr.
void setQuery (const QString &query)
SummaryQueryWidget::setQuery.
Static Public Member Functions
static QString modelIdentifier ()
Private Slots
void on_m_available_list_itemDoubleClicked (QListWidgetItem *item)
SummaryQueryWidget::on_m_available_list_itemDoubleClicked.
void on_m_choosen_list_itemDoubleClicked (QListWidgetItem *item)
SummaryQueryWidget::on_m_choosen_list_itemDoubleClicked.
void on_m_up_pb_clicked ()
SummaryQueryWidget::on_m_up_pb_clicked.
void on_m_add_pb_clicked ()
SummaryQueryWidget::on_m_add_pb_clicked.
void on_m_remove_pb_clicked ()
SummaryQueryWidget::on_m_remove_pb_clicked.
void on_m_down_pb_clicked ()
SummaryQueryWidget::on_m_down_pb_clicked.
void on_m_edit_sql_query_cb_clicked ()
SummaryQueryWidget::on_m_edit_sql_query_cb_clicked.
void reset ()
SummaryQueryWidget::reset Clear this widget aka set to initial state.
void saveConfig ()
SummaryQueryWidget::saveConfig.
void loadConfig ()
SummaryQueryWidget::loadConfig.
Private Member Functions
void setUpItems ()
SummaryQueryWidget::setUpItems.
void fillSavedQuery ()
SummaryQueryWidget::fillSavedQuery Fill the combo box of the saved query.
void updateQueryLine ()
SummaryQueryWidget::updateQueryLine.
QStringList selectedKeys () const
SummaryQueryWidget::selectedKeys.
Private Attributes
Ui::SummaryQueryWidget * ui
QList< QListWidgetItem * > m_items_list
QString m_custom_query
Detailed Description
Definition at line 29 of file summaryquerywidget.h.
Constructor & Destructor Documentation
SummaryQueryWidget()
SummaryQueryWidget::SummaryQueryWidget (QWidget * parent = nullptr) explicit
SummaryQueryWidget::SummaryQueryWidget.
Parameters
parent
Definition at line 28 of file summaryquerywidget.cpp.
References fillSavedQuery(), ConfigSaveLoaderWidget::loadClicked(), loadConfig(), ConfigSaveLoaderWidget::saveClicked(), saveConfig(), setUpItems(), and ui.
~SummaryQueryWidget()
SummaryQueryWidget::~SummaryQueryWidget ()
SummaryQueryWidget::~SummaryQueryWidget.
Definition at line 44 of file summaryquerywidget.cpp.
References ui.
Member Function Documentation
fillSavedQuery()
void SummaryQueryWidget::fillSavedQuery () private
SummaryQueryWidget::fillSavedQuery Fill the combo box of the saved query.
Definition at line 139 of file summaryquerywidget.cpp.
References QETApp::configDir(), QET::Icons::it, and ui.
Referenced by SummaryQueryWidget().
loadConfig
void SummaryQueryWidget::loadConfig () private slot
SummaryQueryWidget::loadConfig.
Definition at line 321 of file summaryquerywidget.cpp.
References QETApp::configDir(), setQuery(), and ui.
Referenced by SummaryQueryWidget().
modelIdentifier()
static QString SummaryQueryWidget::modelIdentifier () inline static
Definition at line 37 of file summaryquerywidget.h.
on_m_add_pb_clicked
void SummaryQueryWidget::on_m_add_pb_clicked () private slot
SummaryQueryWidget::on_m_add_pb_clicked.
Definition at line 218 of file summaryquerywidget.cpp.
References ui, and updateQueryLine().
Referenced by on_m_available_list_itemDoubleClicked().
on_m_available_list_itemDoubleClicked
void SummaryQueryWidget::on_m_available_list_itemDoubleClicked (QListWidgetItem * item) private slot
SummaryQueryWidget::on_m_available_list_itemDoubleClicked.
Parameters
item
Definition at line 182 of file summaryquerywidget.cpp.
References on_m_add_pb_clicked().
on_m_choosen_list_itemDoubleClicked
void SummaryQueryWidget::on_m_choosen_list_itemDoubleClicked (QListWidgetItem * item) private slot
SummaryQueryWidget::on_m_choosen_list_itemDoubleClicked.
Parameters
item
Definition at line 192 of file summaryquerywidget.cpp.
References on_m_remove_pb_clicked().
on_m_down_pb_clicked
void SummaryQueryWidget::on_m_down_pb_clicked () private slot
SummaryQueryWidget::on_m_down_pb_clicked.
Definition at line 242 of file summaryquerywidget.cpp.
References ui, and updateQueryLine().
on_m_edit_sql_query_cb_clicked
void SummaryQueryWidget::on_m_edit_sql_query_cb_clicked () private slot
SummaryQueryWidget::on_m_edit_sql_query_cb_clicked.
Definition at line 259 of file summaryquerywidget.cpp.
References m_custom_query, ui, and updateQueryLine().
on_m_remove_pb_clicked
void SummaryQueryWidget::on_m_remove_pb_clicked () private slot
SummaryQueryWidget::on_m_remove_pb_clicked.
Definition at line 230 of file summaryquerywidget.cpp.
References ui, and updateQueryLine().
Referenced by on_m_choosen_list_itemDoubleClicked().
on_m_up_pb_clicked
void SummaryQueryWidget::on_m_up_pb_clicked () private slot
SummaryQueryWidget::on_m_up_pb_clicked.
Definition at line 201 of file summaryquerywidget.cpp.
References ui, and updateQueryLine().
queryStr()
QString SummaryQueryWidget::queryStr () const
SummaryQueryWidget::queryStr.
Returns
The current query string
Definition at line 53 of file summaryquerywidget.cpp.
References selectedKeys(), and ui.
Referenced by ProjectDBModelPropertiesWidget::on_m_edit_query_pb_clicked(), saveConfig(), and updateQueryLine().
reset
void SummaryQueryWidget::reset () private slot
SummaryQueryWidget::reset Clear this widget aka set to initial state.
Definition at line 279 of file summaryquerywidget.cpp.
References ui.
Referenced by setQuery().
saveConfig
void SummaryQueryWidget::saveConfig () private slot
SummaryQueryWidget::saveConfig.
Definition at line 291 of file summaryquerywidget.cpp.
References QETApp::configDir(), queryStr(), and ui.
Referenced by SummaryQueryWidget().
selectedKeys()
QStringList SummaryQueryWidget::selectedKeys () const private
SummaryQueryWidget::selectedKeys.
Returns
Definition at line 164 of file summaryquerywidget.cpp.
References ui.
Referenced by queryStr().
setQuery()
void SummaryQueryWidget::setQuery (const QString & query)
SummaryQueryWidget::setQuery.
Parameters
query set the current query to query. If it's possible, rebuild the state of the widget from the query
Definition at line 88 of file summaryquerywidget.cpp.
References m_items_list, reset(), and ui.
Referenced by loadConfig(), and ProjectDBModelPropertiesWidget::on_m_edit_query_pb_clicked().
setUpItems()
void SummaryQueryWidget::setUpItems () private
SummaryQueryWidget::setUpItems.
Definition at line 119 of file summaryquerywidget.cpp.
References QETApp::diagramInfoKeys(), QETApp::diagramTranslatedInfoKey(), m_items_list, QET::Icons::tr, and ui.
Referenced by SummaryQueryWidget().
updateQueryLine()
void SummaryQueryWidget::updateQueryLine () private
SummaryQueryWidget::updateQueryLine.
Definition at line 156 of file summaryquerywidget.cpp.
References queryStr(), and ui.
Referenced by on_m_add_pb_clicked(), on_m_down_pb_clicked(), on_m_edit_sql_query_cb_clicked(), on_m_remove_pb_clicked(), and on_m_up_pb_clicked().
Member Data Documentation
m_custom_query
QString SummaryQueryWidget::m_custom_query private
Definition at line 62 of file summaryquerywidget.h.
Referenced by on_m_edit_sql_query_cb_clicked().
m_items_list
QList<QListWidgetItem *> SummaryQueryWidget::m_items_list private
Definition at line 61 of file summaryquerywidget.h.
Referenced by setQuery(), and setUpItems().
ui
Ui::SummaryQueryWidget* SummaryQueryWidget::ui private
Definition at line 60 of file summaryquerywidget.h.
Referenced by fillSavedQuery(), loadConfig(), on_m_add_pb_clicked(), on_m_down_pb_clicked(), on_m_edit_sql_query_cb_clicked(), on_m_remove_pb_clicked(), on_m_up_pb_clicked(), queryStr(), reset(), saveConfig(), selectedKeys(), setQuery(), setUpItems(), SummaryQueryWidget(), updateQueryLine(), and ~SummaryQueryWidget().
The documentation for this class was generated from the following files:
summaryquerywidget.h
summaryquerywidget.cpp