.TH "sources/properties Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/properties Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpropertiesinterface\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpropertiesinterface\&.h\fP"
.br
.ti -1c
.RI "file \fBreportproperties\&.cpp\fP"
.br
.ti -1c
.RI "file \fBreportproperties\&.h\fP"
.br
.ti -1c
.RI "file \fBterminaldata\&.cpp\fP"
.br
.ti -1c
.RI "file \fBterminaldata\&.h\fP"
.br
.ti -1c
.RI "file \fBxrefproperties\&.cpp\fP"
.br
.ti -1c
.RI "file \fBxrefproperties\&.h\fP"
.br
.in -1c
