.TH "sources/ElementsCollection Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBui\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBelementcollectionhandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementcollectionhandler\&.h\fP"
.br
.ti -1c
.RI "file \fBelementcollectionitem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementcollectionitem\&.h\fP"
.br
.ti -1c
.RI "file \fBelementscollectionmodel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementscollectionmodel\&.h\fP"
.br
.ti -1c
.RI "file \fBelementscollectionwidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementscollectionwidget\&.h\fP"
.br
.ti -1c
.RI "file \fBelementslocation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementslocation\&.h\fP"
.br
.ti -1c
.RI "file \fBelementstreeview\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementstreeview\&.h\fP"
.br
.ti -1c
.RI "file \fBfileelementcollectionitem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfileelementcollectionitem\&.h\fP"
.br
.ti -1c
.RI "file \fBxmlelementcollection\&.cpp\fP"
.br
.ti -1c
.RI "file \fBxmlelementcollection\&.h\fP"
.br
.ti -1c
.RI "file \fBxmlprojectelementcollectionitem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBxmlprojectelementcollectionitem\&.h\fP"
.br
.in -1c
