.TH "sources/diagramevent Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramevent Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdiagrameventaddelement\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagrameventaddelement\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagrameventaddimage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagrameventaddimage\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagrameventaddshape\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagrameventaddshape\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagrameventaddtext\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagrameventaddtext\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagrameventinterface\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagrameventinterface\&.h\fP"
.br
.in -1c
