.TH "sources Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources Directory Reference \- \fBQETXML::fileSystemDirToXmlCollectionDir\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBautoNum\fP"
.br
.ti -1c
.RI "directory \fBdataBase\fP"
.br
.ti -1c
.RI "directory \fBdiagramevent\fP"
.br
.ti -1c
.RI "directory \fBdvevent\fP"
.br
.ti -1c
.RI "directory \fBeditor\fP"
.br
.ti -1c
.RI "directory \fBElementsCollection\fP"
.br
.ti -1c
.RI "directory \fBfactory\fP"
.br
.ti -1c
.RI "directory \fBNameList\fP"
.br
.ti -1c
.RI "directory \fBproperties\fP"
.br
.ti -1c
.RI "directory \fBPropertiesEditor\fP"
.br
.ti -1c
.RI "directory \fBqetgraphicsitem\fP"
.br
.ti -1c
.RI "directory \fBQetGraphicsItemModeler\fP"
.br
.ti -1c
.RI "directory \fBQPropertyUndoCommand\fP"
.br
.ti -1c
.RI "directory \fBQWidgetAnimation\fP"
.br
.ti -1c
.RI "directory \fBrichtext\fP"
.br
.ti -1c
.RI "directory \fBSearchAndReplace\fP"
.br
.ti -1c
.RI "directory \fBtitleblock\fP"
.br
.ti -1c
.RI "directory \fBui\fP"
.br
.ti -1c
.RI "directory \fBundocommand\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBborderproperties\&.cpp\fP"
.br
.ti -1c
.RI "file \fBborderproperties\&.h\fP"
.br
.ti -1c
.RI "file \fBbordertitleblock\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbordertitleblock\&.h\fP"
.br
.ti -1c
.RI "file \fBconductorautonumerotation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconductorautonumerotation\&.h\fP"
.br
.ti -1c
.RI "file \fBconductornumexport\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconductornumexport\&.h\fP"
.br
.ti -1c
.RI "file \fBconductorprofile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconductorprofile\&.h\fP"
.br
.ti -1c
.RI "file \fBconductorproperties\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconductorproperties\&.h\fP"
.br
.ti -1c
.RI "file \fBconductorsegment\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconductorsegment\&.h\fP"
.br
.ti -1c
.RI "file \fBconductorsegmentprofile\&.h\fP"
.br
.ti -1c
.RI "file \fBconfigdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconfigdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBconfigpage\&.h\fP"
.br
.ti -1c
.RI "file \fBconfigpages\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconfigpages\&.h\fP"
.br
.ti -1c
.RI "file \fBcreatedxf\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcreatedxf\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagram\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagram\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagramcommands\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagramcommands\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagramcontent\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagramcontent\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagramcontext\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagramcontext\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagramposition\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagramposition\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagramprintdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagramprintdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagramschooser\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagramschooser\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagramview\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdiagramview\&.h\fP"
.br
.ti -1c
.RI "file \fBelementdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBelementprovider\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementprovider\&.h\fP"
.br
.ti -1c
.RI "file \fBelementscategoryeditor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementscategoryeditor\&.h\fP"
.br
.ti -1c
.RI "file \fBelementscollectioncache\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementscollectioncache\&.h\fP"
.br
.ti -1c
.RI "file \fBelementsmover\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementsmover\&.h\fP"
.br
.ti -1c
.RI "file \fBelementspanel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementspanel\&.h\fP"
.br
.ti -1c
.RI "file \fBelementspanelwidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementspanelwidget\&.h\fP"
.br
.ti -1c
.RI "file \fBelementtextpattern\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementtextpattern\&.h\fP"
.br
.ti -1c
.RI "file \fBelementtextsmover\&.cpp\fP"
.br
.ti -1c
.RI "file \fBelementtextsmover\&.h\fP"
.br
.ti -1c
.RI "file \fBexportdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBexportdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBexportproperties\&.cpp\fP"
.br
.ti -1c
.RI "file \fBexportproperties\&.h\fP"
.br
.ti -1c
.RI "file \fBexportpropertieswidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBexportpropertieswidget\&.h\fP"
.br
.ti -1c
.RI "file \fBgenericpanel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgenericpanel\&.h\fP"
.br
.ti -1c
.RI "file \fBmachine_info\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmachine_info\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnewelementwizard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnewelementwizard\&.h\fP"
.br
.ti -1c
.RI "file \fBprojectconfigpages\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprojectconfigpages\&.h\fP"
.br
.ti -1c
.RI "file \fBprojectview\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprojectview\&.h\fP"
.br
.ti -1c
.RI "file \fBqet\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqet\&.h\fP"
.br
.ti -1c
.RI "file \fBqetapp\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetapp\&.h\fP"
.br
.ti -1c
.RI "file \fBqetarguments\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetarguments\&.h\fP"
.br
.ti -1c
.RI "file \fBqetdiagrameditor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetdiagrameditor\&.h\fP"
.br
.ti -1c
.RI "file \fBqeticons\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqeticons\&.h\fP"
.br
.ti -1c
.RI "file \fBqetinformation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetinformation\&.h\fP"
.br
.ti -1c
.RI "file \fBqetmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetmainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBqetmessagebox\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetmessagebox\&.h\fP"
.br
.ti -1c
.RI "file \fBqetprintpreviewdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetprintpreviewdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBqetproject\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetproject\&.h\fP"
.br
.ti -1c
.RI "file \fBqetregexpvalidator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetregexpvalidator\&.h\fP"
.br
.ti -1c
.RI "file \fBqetresult\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetresult\&.h\fP"
.br
.ti -1c
.RI "file \fBqetxml\&.cpp\fP"
.br
.RI "\fBQETXML::fileSystemElementToXmlCollectionElement\fP\&. "
.ti -1c
.RI "file \fBqetxml\&.h\fP"
.br
.ti -1c
.RI "file \fBqfilenameedit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqfilenameedit\&.h\fP"
.br
.ti -1c
.RI "file \fBqgimanager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqgimanager\&.h\fP"
.br
.ti -1c
.RI "file \fBqtextorientationspinboxwidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqtextorientationspinboxwidget\&.h\fP"
.br
.ti -1c
.RI "file \fBqtextorientationwidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqtextorientationwidget\&.h\fP"
.br
.ti -1c
.RI "file \fBrecentfiles\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrecentfiles\&.h\fP"
.br
.ti -1c
.RI "file \fBtitleblockcell\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtitleblockcell\&.h\fP"
.br
.ti -1c
.RI "file \fBtitleblockproperties\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtitleblockproperties\&.h\fP"
.br
.ti -1c
.RI "file \fBtitleblocktemplate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtitleblocktemplate\&.h\fP"
.br
.ti -1c
.RI "file \fBtitleblocktemplaterenderer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtitleblocktemplaterenderer\&.h\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBQETXML::fileSystemDirToXmlCollectionDir\fP\&. 


.PP
\fBParameters\fP
.RS 4
\fIdocument\fP : owner document of returned QDomElement, use to create the QDomElement\&. 
.br
\fIdir\fP : file system direcory to convert to QDomElement directory 
.br
\fIrename\fP : by default the attribute 'name' of the returned QDomElement is the same name of but we can override itwith rename 
.RE
.PP
\fBReturns\fP
.RS 4
A file system directory converted to a QDomElement directory ready to be inserted into a \fBXmlElementCollection\fP\&. If the QDomElement can't be created, return a null QDomElement\&. 
.RE
.PP

