.TH "sources/undocommand Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/undocommand Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaddelementtextcommand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaddelementtextcommand\&.h\fP"
.br
.ti -1c
.RI "file \fBchangeelementinformationcommand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBchangeelementinformationcommand\&.h\fP"
.br
.ti -1c
.RI "file \fBchangetitleblockcommand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBchangetitleblockcommand\&.h\fP"
.br
.ti -1c
.RI "file \fBdeleteqgraphicsitemcommand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdeleteqgraphicsitemcommand\&.h\fP"
.br
.ti -1c
.RI "file \fBitemmodelcommand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBitemmodelcommand\&.h\fP"
.br
.ti -1c
.RI "file \fBlinkelementcommand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlinkelementcommand\&.h\fP"
.br
.ti -1c
.RI "file \fBrotateselectioncommand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrotateselectioncommand\&.h\fP"
.br
.ti -1c
.RI "file \fBrotatetextscommand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrotatetextscommand\&.h\fP"
.br
.in -1c
