.TH "sources/PropertiesEditor Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/PropertiesEditor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpropertieseditordialog\&.h\fP"
.br
.ti -1c
.RI "file \fBpropertieseditordockwidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpropertieseditordockwidget\&.h\fP"
.br
.ti -1c
.RI "file \fBpropertieseditorwidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpropertieseditorwidget\&.h\fP"
.br
.in -1c
