.TH "sources/richtext Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/richtext Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrichtexteditor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrichtexteditor_p\&.h\fP"
.br
.ti -1c
.RI "file \fBui_addlinkdialog\&.h\fP"
.br
.in -1c
