.TH "sources/utils Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconductorcreator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconductorcreator\&.h\fP"
.br
.ti -1c
.RI "file \fBmacosxopenevent\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmacosxopenevent\&.h\fP"
.br
.ti -1c
.RI "file \fBqetutils\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetutils\&.h\fP"
.br
.in -1c
