.TH "sources/editor/esevent Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/esevent Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBeseventaddarc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventaddarc\&.h\fP"
.br
.ti -1c
.RI "file \fBeseventadddynamictextfield\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventadddynamictextfield\&.h\fP"
.br
.ti -1c
.RI "file \fBeseventaddellipse\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventaddellipse\&.h\fP"
.br
.ti -1c
.RI "file \fBeseventaddline\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventaddline\&.h\fP"
.br
.ti -1c
.RI "file \fBeseventaddpolygon\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventaddpolygon\&.h\fP"
.br
.ti -1c
.RI "file \fBeseventaddrect\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventaddrect\&.h\fP"
.br
.ti -1c
.RI "file \fBeseventaddterminal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventaddterminal\&.h\fP"
.br
.ti -1c
.RI "file \fBeseventaddtext\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventaddtext\&.h\fP"
.br
.ti -1c
.RI "file \fBeseventinterface\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeseventinterface\&.h\fP"
.br
.in -1c
