.TH "sources/QetGraphicsItemModeler Directory Reference" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/QetGraphicsItemModeler Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqetgraphicshandleritem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetgraphicshandleritem\&.h\fP"
.br
.ti -1c
.RI "file \fBqetgraphicshandlerutility\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqetgraphicshandlerutility\&.h\fP"
.br
.in -1c
