.TH "sources/undocommand/addelementtextcommand.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/undocommand/addelementtextcommand.h
.SH SYNOPSIS
.br
.PP
\fC#include <QUndoCommand>\fP
.br
\fC#include <QPointer>\fP
.br
\fC#include <QDomElement>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddElementTextCommand\fP"
.br
.RI "The \fBAddElementTextCommand\fP class Manage the adding of element text\&. "
.ti -1c
.RI "class \fBAddTextsGroupCommand\fP"
.br
.RI "The \fBAddTextsGroupCommand\fP class Manage the adding of a texts group\&. "
.ti -1c
.RI "class \fBRemoveTextsGroupCommand\fP"
.br
.RI "The \fBRemoveTextsGroupCommand\fP class Manage the removinf of a texts group\&. "
.ti -1c
.RI "class \fBAddTextToGroupCommand\fP"
.br
.RI "The \fBAddTextToGroupCommand\fP class\&. "
.ti -1c
.RI "class \fBRemoveTextFromGroupCommand\fP"
.br
.RI "The \fBRemoveTextFromGroupCommand\fP class\&. "
.ti -1c
.RI "class \fBAlignmentTextsGroupCommand\fP"
.br
.RI "The \fBAlignmentTextsGroupCommand\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
