.TH "sources/factory/ui/addtabledialog.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/factory/ui/addtabledialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include 'qetapp\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddTableDialog\fP"
.br
.RI "The \fBAddTableDialog\fP class Provide a dialog used to edit the properties of table befor adding to a diagram\&. The main difference betwen this dialog and the widget used to edit the properties of table is that the dialog have two extra check box\&. One for adjust the size of the table to diagram Second for add new tables on new folios if the table can't fit into diagram\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
