.TH "advancedReplaceStruct" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
advancedReplaceStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <searchandreplaceworker\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwho\fP = \-1"
.br
.ti -1c
.RI "QString \fBwhat\fP"
.br
.ti -1c
.RI "QString \fBsearch\fP"
.br
.ti -1c
.RI "QString \fBreplace\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QString advancedReplaceStruct::replace"

.SS "QString advancedReplaceStruct::search"

.SS "QString advancedReplaceStruct::what"

.SS "int advancedReplaceStruct::who = \-1"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
