.TH "sources/ui/alignmenttextdialog.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/alignmenttextdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'alignmenttextdialog\&.h'\fP
.br
\fC#include 'ui_alignmenttextdialog\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
