.TH "sources/autoNum/ui/autonumberingmanagementw.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/autoNum/ui/autonumberingmanagementw.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'autonumberingmanagementw\&.h'\fP
.br
\fC#include 'ui_autonumberingmanagementw\&.h'\fP
.br
\fC#include 'numparteditorw\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include 'numerotationcontextcommands\&.h'\fP
.br
\fC#include 'formulaautonumberingw\&.h'\fP
.br
\fC#include 'ui_formulaautonumberingw\&.h'\fP
.br
\fC#include 'qdebug\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
