.TH "sources/ui/borderpropertieswidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/borderpropertieswidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'borderpropertieswidget\&.h'\fP
.br
\fC#include 'ui_borderpropertieswidget\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
