.TH "sources/bordertitleblock.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/bordertitleblock.h
.SH SYNOPSIS
.br
.PP
\fC#include 'diagramcontext\&.h'\fP
.br
\fC#include 'titleblockproperties\&.h'\fP
.br
\fC#include 'borderproperties\&.h'\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QRectF>\fP
.br
\fC#include <QDate>\fP
.br
\fC#include 'numerotationcontext\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBorderTitleBlock\fP"
.br
.RI "The \fBBorderTitleBlock\fP class This class represents the border and the titleblock which frame a particular electric diagram\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
