.TH "sources/bordertitleblock.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/bordertitleblock.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QPainter>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'titleblocktemplate\&.h'\fP
.br
\fC#include 'titleblocktemplaterenderer\&.h'\fP
.br
\fC#include 'bordertitleblock\&.h'\fP
.br
\fC#include 'diagramposition\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'createdxf\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMIN_COLUMN_COUNT\fP   3"
.br
.ti -1c
.RI "#define \fBMIN_ROW_COUNT\fP   3"
.br
.ti -1c
.RI "#define \fBMIN_COLUMN_WIDTH\fP   5\&.0"
.br
.ti -1c
.RI "#define \fBMIN_ROW_HEIGHT\fP   5\&.0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MIN_COLUMN_COUNT   3"

.SS "#define MIN_COLUMN_WIDTH   5\&.0"

.SS "#define MIN_ROW_COUNT   3"

.SS "#define MIN_ROW_HEIGHT   5\&.0"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
