.TH "sources/undocommand/changeelementinformationcommand.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/undocommand/changeelementinformationcommand.h
.SH SYNOPSIS
.br
.PP
\fC#include <QUndoCommand>\fP
.br
\fC#include 'diagramcontext\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChangeElementInformationCommand\fP"
.br
.RI "The \fBChangeElementInformationCommand\fP class This class manage undo/redo to change the element information\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
