.TH "sources/undocommand/changetitleblockcommand.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/undocommand/changetitleblockcommand.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'changetitleblockcommand\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
