.TH "sources/undocommand/changetitleblockcommand.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/undocommand/changetitleblockcommand.h
.SH SYNOPSIS
.br
.PP
\fC#include <QUndoCommand>\fP
.br
\fC#include 'titleblockproperties\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChangeTitleBlockCommand\fP"
.br
.RI "The \fBChangeTitleBlockCommand\fP class This command changes the title block properties for a particular diagram\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
