.TH "sources/ui/compositetexteditdialog.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/compositetexteditdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompositeTextEditDialog\fP"
.br
.RI "The \fBCompositeTextEditDialog\fP class \fBCompositeTextEditDialog\fP display a dialog use to write the complex text of a dynamic element text item\&. This dialog provide a QComboBox to quickly add an information of the element in the composite text\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
