.TH "sources/utils/conductorcreator.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/utils/conductorcreator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'conductorcreator\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qgraphicsitem\&.h'\fP
.br
\fC#include 'terminal\&.h'\fP
.br
\fC#include 'conductor\&.h'\fP
.br
\fC#include 'potentialselectordialog\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include 'conductorautonumerotation\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include <QPolygonF>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
