.TH "sources/conductorprofile.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/conductorprofile.h
.SH SYNOPSIS
.br
.PP
\fC#include <QList>\fP
.br
\fC#include 'qet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConductorProfile\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug & \fBoperator<<\fP (QDebug d, \fBConductorProfile\fP &)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug& operator<< (QDebug d, \fBConductorProfile\fP & t)"
Permet de debugger un profil de conducteur 
.PP
\fBParameters\fP
.RS 4
\fId\fP Object QDebug a utiliser pour l'affichage des informations de debug 
.br
\fIt\fP Profil de conducteur a debugger 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
