.TH "sources/ui/conductorpropertieswidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/conductorpropertieswidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'conductorpropertieswidget\&.h'\fP
.br
\fC#include 'ui_conductorpropertieswidget\&.h'\fP
.br
\fC#include 'conductorproperties\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qtextorientationspinboxwidget\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
