.TH "sources/conductornumexport.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/conductornumexport.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'conductornumexport\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'diagramcontent\&.h'\fP
.br
\fC#include 'conductor\&.h'\fP
.br
\fC#include 'terminal\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'conductortextitem\&.h'\fP
.br
\fC#include <QFileDialog>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
