.TH "sources/conductorprofile.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/conductorprofile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'conductorprofile\&.h'\fP
.br
\fC#include 'qetgraphicsitem/conductor\&.h'\fP
.br
\fC#include 'conductorsegmentprofile\&.h'\fP
.br
\fC#include 'terminal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug & \fBoperator<<\fP (QDebug d, \fBConductorProfile\fP &t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug& operator<< (QDebug d, \fBConductorProfile\fP & t)"
Permet de debugger un profil de conducteur 
.PP
\fBParameters\fP
.RS 4
\fId\fP Object QDebug a utiliser pour l'affichage des informations de debug 
.br
\fIt\fP Profil de conducteur a debugger 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
