.TH "sources/conductornumexport.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/conductornumexport.h
.SH SYNOPSIS
.br
.PP
\fC#include <QHash>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConductorNumExport\fP"
.br
.RI "The \fBConductorNumExport\fP class A class to export the num of conductors into a csv file\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
