.TH "sources/utils/conductorcreator.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/utils/conductorcreator.h
.SH SYNOPSIS
.br
.PP
\fC#include 'conductorproperties\&.h'\fP
.br
\fC#include 'assignvariables\&.h'\fP
.br
\fC#include <QList>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConductorCreator\fP"
.br
.RI "The \fBConductorCreator\fP class This class create one or several or several conductors in a given context\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
