.TH "sources/ui/conductorpropertiesdialog.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/conductorpropertiesdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'conductorpropertiesdialog\&.h'\fP
.br
\fC#include 'ui_conductorpropertiesdialog\&.h'\fP
.br
\fC#include 'conductor\&.h'\fP
.br
\fC#include 'conductorpropertieswidget\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
