.TH "sources/ui/configsaveloaderwidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/configsaveloaderwidget.h
.SH SYNOPSIS
.br
.PP
\fC#include <QGroupBox>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigSaveLoaderWidget\fP"
.br
.RI "The \fBConfigSaveLoaderWidget\fP class This group box provide 4 widget: A combo box with the available config\&. A push button to load the selected config of combo box A line edit to edit the text of the config to save A push button to save the config\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
