.TH "sources/configpages.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/configpages.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'configpages\&.h'\fP
.br
\fC#include 'borderpropertieswidget\&.h'\fP
.br
\fC#include 'conductorpropertieswidget\&.h'\fP
.br
\fC#include 'titleblockpropertieswidget\&.h'\fP
.br
\fC#include 'bordertitleblock\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'exportpropertieswidget\&.h'\fP
.br
\fC#include 'ui/reportpropertiewidget\&.h'\fP
.br
\fC#include 'ui/xrefpropertieswidget\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'reportproperties\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include <QFontDialog>\fP
.br
\fC#include <QFont>\fP
.br
\fC#include <QSizePolicy>\fP
.br
\fC#include <utility>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
