.TH "sources/configpages.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/configpages.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include 'configpage\&.h'\fP
.br
\fC#include 'projectpropertiesdialog\&.h'\fP
.br
\fC#include 'titleblockpropertieswidget\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNewDiagramPage\fP"
.br
.RI "The \fBNewDiagramPage\fP class This configuration page enables users to define the properties of new diagrams to come\&. "
.ti -1c
.RI "class \fBExportConfigPage\fP"
.br
.RI "The \fBExportConfigPage\fP class This configuration page enables users to set default export options\&. "
.ti -1c
.RI "class \fBPrintConfigPage\fP"
.br
.RI "The \fBPrintConfigPage\fP class This configuration page enables users to set default printing options\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
