.TH "sources/qetgraphicsitem/crossrefitem.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/crossrefitem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'crossrefitem\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'diagramposition\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qgraphicsitemutility\&.h'\fP
.br
\fC#include 'assignvariables\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include 'elementtextitemgroup\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
