.TH "sources/editor/graphicspart/customelementpart.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/graphicspart/customelementpart.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'customelementpart\&.h'\fP
.br
\fC#include 'qetelementeditor\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
