.TH "sources/editor/graphicspart/customelementgraphicpart.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/graphicspart/customelementgraphicpart.h
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsObject>\fP
.br
\fC#include 'customelementpart\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomElementGraphicPart\fP"
.br
.RI "The \fBCustomElementGraphicPart\fP class This class is the base for all home-made primitive like line, rectangle, ellipse etc\&.\&.\&.\&. It provides methods and enums to manage style attributes available for primitive (color, pen style, etc\&.\&.\&.) "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSHADOWS_HEIGHT\fP   4\&.0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBCustomElementGraphicPart\fP \fBCEGP\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SHADOWS_HEIGHT   4\&.0"

.SH "Typedef Documentation"
.PP 
.SS "typedef \fBCustomElementGraphicPart\fP \fBCEGP\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
