.TH "sources/editor/graphicspart/customelementpart.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/graphicspart/customelementpart.h
.SH SYNOPSIS
.br
.PP
\fC#include 'qet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomElementPart\fP"
.br
.RI "The \fBCustomElementPart\fP class This abstract class represents a primitive of the visual representation of an electrical element\&. The \fBElement\fP, FixedElement and CustomElement classes do not embed its attributes and methods in order to remain lightweight; indeed, there is no point for those classes to store their visual representation with anything more complex than a QImage\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
