.TH "sources/diagramevent/diagrameventaddshape.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramevent/diagrameventaddshape.h
.SH SYNOPSIS
.br
.PP
\fC#include 'diagrameventinterface\&.h'\fP
.br
\fC#include 'qetshapeitem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiagramEventAddShape\fP"
.br
.RI "The \fBDiagramEventAddShape\fP class This event manage the creation of a shape\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
