.TH "sources/diagramcontent.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramcontent.h
.SH SYNOPSIS
.br
.PP
\fC#include <QSet>\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiagramContent\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug & \fBoperator<<\fP (QDebug, \fBDiagramContent\fP &)"
.br
.RI "operator << Use to debug a diagram content "
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug& operator<< (QDebug d, \fBDiagramContent\fP & content)"

.PP
operator << Use to debug a diagram content 
.PP
\fBParameters\fP
.RS 4
\fId\fP : QDebug to use for display the debug info 
.br
\fIcontent\fP : content to debug 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
