.TH "sources/diagramevent/diagrameventaddshape.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramevent/diagrameventaddshape.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'diagrameventaddshape\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
