.TH "sources/diagram.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagram.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets>\fP
.br
\fC#include <QtXml>\fP
.br
\fC#include <QHash>\fP
.br
\fC#include <QUuid>\fP
.br
\fC#include 'bordertitleblock\&.h'\fP
.br
\fC#include 'conductorproperties\&.h'\fP
.br
\fC#include 'exportproperties\&.h'\fP
.br
\fC#include 'qgimanager\&.h'\fP
.br
\fC#include 'numerotationcontext\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'properties/xrefproperties\&.h'\fP
.br
\fC#include 'elementsmover\&.h'\fP
.br
\fC#include 'elementtextsmover\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiagram\fP"
.br
.RI "The \fBDiagram\fP class This class represents an electric diagram\&. It manages its various child elements, conductors and texts and handles their graphic rendering\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
