.TH "sources/diagramcontent.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramcontent.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'diagramcontent\&.h'\fP
.br
\fC#include <QGraphicsItem>\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'independenttextitem\&.h'\fP
.br
\fC#include 'conductor\&.h'\fP
.br
\fC#include 'diagramimageitem\&.h'\fP
.br
\fC#include 'qetshapeitem\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include 'elementtextitemgroup\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'terminal\&.h'\fP
.br
\fC#include 'conductortextitem\&.h'\fP
.br
\fC#include 'qetgraphicstableitem\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug & \fBoperator<<\fP (QDebug d, \fBDiagramContent\fP &content)"
.br
.RI "operator << Use to debug a diagram content "
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug& operator<< (QDebug d, \fBDiagramContent\fP & content)"

.PP
operator << Use to debug a diagram content 
.PP
\fBParameters\fP
.RS 4
\fId\fP : QDebug to use for display the debug info 
.br
\fIcontent\fP : content to debug 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
