.TH "sources/diagramprintdialog.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramprintdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets>\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'exportproperties\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiagramPrintDialog\fP"
.br
.RI "The \fBDiagramPrintDialog\fP class This class implements both the dialog allowing users to configure the printing of a project file and the printing itself\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
