.TH "sources/diagramevent/diagrameventaddelement.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramevent/diagrameventaddelement.h
.SH SYNOPSIS
.br
.PP
\fC#include 'diagrameventinterface\&.h'\fP
.br
\fC#include 'elementslocation\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiagramEventAddElement\fP"
.br
.RI "The \fBDiagramEventAddElement\fP class This diagram event add a new element, for each left click button at the position of click\&. Space key rotate current element by 90°, right click button finish this event\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
