.TH "sources/qetgraphicsitem/diagramtextitem.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/diagramtextitem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'diagramtextitem\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'richtext/richtexteditor_p\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
