.TH "sources/diagramevent/diagrameventinterface.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramevent/diagrameventinterface.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'diagrameventinterface\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include <QGraphicsSceneMouseEvent>\fP
.br
\fC#include <QKeyEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
