.TH "sources/diagramview.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramview.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'diagramview\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qetgraphicsitem/conductor\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include 'diagramposition\&.h'\fP
.br
\fC#include 'conductorpropertieswidget\&.h'\fP
.br
\fC#include 'qetgraphicsitem/conductortextitem\&.h'\fP
.br
\fC#include 'qetgraphicsitem/independenttextitem\&.h'\fP
.br
\fC#include 'qetgraphicsitem/diagramimageitem\&.h'\fP
.br
\fC#include 'templatelocation\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'projectview\&.h'\fP
.br
\fC#include 'integrationmovetemplateshandler\&.h'\fP
.br
\fC#include 'qetdiagrameditor\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include <QGraphicsObject>\fP
.br
\fC#include <QGraphicsPixmapItem>\fP
.br
\fC#include <QGraphicsSceneMouseEvent>\fP
.br
\fC#include 'factory/elementfactory\&.h'\fP
.br
\fC#include 'diagrampropertiesdialog\&.h'\fP
.br
\fC#include 'dveventinterface\&.h'\fP
.br
\fC#include 'diagrameventaddelement\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'qetshapeitem\&.h'\fP
.br
\fC#include 'undocommand/deleteqgraphicsitemcommand\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include 'multipastedialog\&.h'\fP
.br
\fC#include 'changetitleblockcommand\&.h'\fP
.br
\fC#include 'conductorcreator\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
