.TH "sources/diagramevent/diagrameventaddimage.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramevent/diagrameventaddimage.h
.SH SYNOPSIS
.br
.PP
\fC#include 'diagrameventinterface\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiagramEventAddImage\fP"
.br
.RI "The \fBDiagramEventAddImage\fP class This diagram event, handle the adding of an image in a diagram\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
