.TH "sources/diagramcommands.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramcommands.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include 'qetgraphicsitem/element\&.h'\fP
.br
\fC#include 'qetgraphicsitem/conductor\&.h'\fP
.br
\fC#include 'qetgraphicsitem/conductortextitem\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qetgraphicsitem/independenttextitem\&.h'\fP
.br
\fC#include 'qgimanager\&.h'\fP
.br
\fC#include 'qetgraphicsitem/diagramtextitem\&.h'\fP
.br
\fC#include 'qetgraphicsitem/diagramimageitem\&.h'\fP
.br
\fC#include 'elementtextitemgroup\&.h'\fP
.br
\fC#include <QPropertyAnimation>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBitemText\fP (const \fBQetGraphicsItem\fP *item)"
.br
.ti -1c
.RI "QString \fBitemText\fP (const \fBIndependentTextItem\fP *item)"
.br
.ti -1c
.RI "QString \fBitemText\fP (const \fBConductor\fP *item)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QString itemText (const \fBConductor\fP * item)"

.SS "QString itemText (const \fBIndependentTextItem\fP * item)"

.SS "QString itemText (const \fBQetGraphicsItem\fP * item)"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
