.TH "sources/diagramevent/diagrameventinterface.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramevent/diagrameventinterface.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiagramEventInterface\fP"
.br
.RI "The \fBDiagramEventInterface\fP class \fBisRunning()\fP return true if action is running (do something)\&. By default return false\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
