.TH "sources/diagramposition.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/diagramposition.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'diagramposition\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
