.TH "sources/qetgraphicsitem/dynamicelementtextitem.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/dynamicelementtextitem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'diagramtextitem\&.h'\fP
.br
\fC#include 'xrefproperties\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include <QUuid>\fP
.br
\fC#include <QPointer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDynamicElementTextItem\fP"
.br
.RI "The \fBDynamicElementTextItem\fP class This class provide a simple text field of element who can be added or removed directly from the diagram editor\&. This text is created to compensate a big lack of the ElementTextItem : ElementTextItem can't be added or removed directly in the diagram editor\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
