.TH "sources/ui/dynamicelementtextmodel.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/dynamicelementtextmodel.h
.SH SYNOPSIS
.br
.PP
\fC#include <QStandardItemModel>\fP
.br
\fC#include <qstyleditemdelegate\&.h>\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDynamicElementTextModel\fP"
.br
.RI "The \fBDynamicElementTextModel\fP class A model to use with QtView\&. This model display and can edit the value of dynamic text of an element\&. Set the delegate \fBDynamicTextItemDelegate\fP as delegate of this model\&. "
.ti -1c
.RI "class \fBDynamicTextItemDelegate\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
