.TH "sources/ui/dynamicelementtextitemeditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/dynamicelementtextitemeditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'dynamicelementtextitemeditor\&.h'\fP
.br
\fC#include 'ui_dynamicelementtextitemeditor\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'dynamicelementtextmodel\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'undocommand/deleteqgraphicsitemcommand\&.h'\fP
.br
\fC#include 'undocommand/addelementtextcommand\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'elementtextitemgroup\&.h'\fP
.br
\fC#include 'elementtextpattern\&.h'\fP
.br
\fC#include <QTreeView>\fP
.br
\fC#include <QUndoCommand>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
