.TH "sources/editor/ui/dynamictextfieldeditor.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/ui/dynamictextfieldeditor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'elementitemeditor\&.h'\fP
.br
\fC#include 'partdynamictextfield\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDynamicTextFieldEditor\fP"
.br
.RI "The \fBDynamicTextFieldEditor\fP class This class provide a widget used to edit the property of a dynamic text field\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
