.TH "sources/editor/ui/dynamictextfieldeditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/ui/dynamictextfieldeditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'dynamictextfieldeditor\&.h'\fP
.br
\fC#include 'ui_dynamictextfieldeditor\&.h'\fP
.br
\fC#include 'customelementpart\&.h'\fP
.br
\fC#include 'partdynamictextfield\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'qetelementeditor\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'compositetexteditdialog\&.h'\fP
.br
\fC#include 'alignmenttextdialog\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <QPointer>\fP
.br
\fC#include <QGraphicsItem>\fP
.br
\fC#include <QColorDialog>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
