.TH "ECHSToXml" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ECHSToXml \- The \fBECHSToXml\fP class Manage the copy of a directory or element from a collection (no matter if the source is a file system collection or an xml collection) to an xml collection\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <elementcollectionhandler\&.h>\fP
.PP
Inherits \fBECHStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBECHSToXml\fP (\fBElementsLocation\fP &source, \fBElementsLocation\fP &destination)"
.br
.ti -1c
.RI "\fBElementsLocation\fP \fBcopy\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBECHSToXml\fP class Manage the copy of a directory or element from a collection (no matter if the source is a file system collection or an xml collection) to an xml collection\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ECHSToXml::ECHSToXml (\fBElementsLocation\fP & source, \fBElementsLocation\fP & destination)"

.SH "Member Function Documentation"
.PP 
.SS "\fBElementsLocation\fP ECHSToXml::copy ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBECHStrategy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
