.TH "sources/editor/editorcommands.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/editorcommands.h
.SH SYNOPSIS
.br
.PP
\fC#include 'customelementpart\&.h'\fP
.br
\fC#include 'elementview\&.h'\fP
.br
\fC#include 'elementscene\&.h'\fP
.br
\fC#include 'elementcontent\&.h'\fP
.br
\fC#include 'qgimanager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementEditionCommand\fP"
.br
.RI "The \fBElementEditionCommand\fP class \fBElementEditionCommand\fP is the base class for all commands classes involved in the edition of an electrical element\&. It provides commonly required methods and attributes, such as accessors to the modified scene and view\&. "
.ti -1c
.RI "class \fBDeletePartsCommand\fP"
.br
.ti -1c
.RI "class \fBCutPartsCommand\fP"
.br
.ti -1c
.RI "class \fBMovePartsCommand\fP"
.br
.ti -1c
.RI "class \fBAddPartCommand\fP"
.br
.ti -1c
.RI "class \fBChangeNamesCommand\fP"
.br
.ti -1c
.RI "class \fBChangeZValueCommand\fP"
.br
.ti -1c
.RI "class \fBChangeInformationsCommand\fP"
.br
.ti -1c
.RI "class \fBScalePartsCommand\fP"
.br
.ti -1c
.RI "class \fBChangePropertiesCommand\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
