.TH "EditorDelegate" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditorDelegate \- The \fBEditorDelegate\fP class This delegate is only use for disable the edition of the first column of the information tree widget\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits QItemDelegate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditorDelegate\fP (QObject *parent)"
.br
.ti -1c
.RI "QWidget * \fBcreateEditor\fP (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBEditorDelegate\fP class This delegate is only use for disable the edition of the first column of the information tree widget\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EditorDelegate::EditorDelegate (QObject * parent)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QWidget* EditorDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
