.TH "sources/editor/elementscene.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/elementscene.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets>\fP
.br
\fC#include <QtXml>\fP
.br
\fC#include 'qgimanager\&.h'\fP
.br
\fC#include 'elementcontent\&.h'\fP
.br
\fC#include 'diagramcontext\&.h'\fP
.br
\fC#include 'nameslist\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementScene\fP"
.br
.RI "The \fBElementScene\fP class This class is the canvas allowing the visual edition of an electrial element\&. It displays the various primitives composing the drawing of the element, the border due to its fixed size and its hotspot\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
