.TH "sources/ElementsCollection/elementscollectionwidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/elementscollectionwidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementscollectionwidget\&.h'\fP
.br
\fC#include 'elementscollectionmodel\&.h'\fP
.br
\fC#include 'elementcollectionitem\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'fileelementcollectionitem\&.h'\fP
.br
\fC#include 'elementslocation\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'elementscategoryeditor\&.h'\fP
.br
\fC#include 'newelementwizard\&.h'\fP
.br
\fC#include 'xmlprojectelementcollectionitem\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'qetelementeditor\&.h'\fP
.br
\fC#include 'elementstreeview\&.h'\fP
.br
\fC#include 'qetdiagrameditor\&.h'\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <QTimer>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
