.TH "sources/elementspanelwidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/elementspanelwidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'elementspanel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementsPanelWidget\fP"
.br
.RI "The \fBElementsPanelWidget\fP class This class embeds an elements panel under a toolbar providing various actions to manage elements\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
