.TH "sources/editor/elementprimitivedecorator.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/elementprimitivedecorator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementprimitivedecorator\&.h'\fP
.br
\fC#include 'elementscene\&.h'\fP
.br
\fC#include 'customelementpart\&.h'\fP
.br
\fC#include 'editorcommands\&.h'\fP
.br
\fC#include 'qet\&.h'\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QGraphicsSceneHoverEvent>\fP
.br
\fC#include <QStyleOptionGraphicsItem>\fP
.br
\fC#include <QGraphicsScene>\fP
.br
\fC#include 'QetGraphicsItemModeler/qetgraphicshandleritem\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
