.TH "sources/dataBase/ui/elementquerywidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/dataBase/ui/elementquerywidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementquerywidget\&.h'\fP
.br
\fC#include 'ui_elementquerywidget\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include <QRegularExpression>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
