.TH "sources/editor/ui/elementpropertieseditorwidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/ui/elementpropertieseditorwidget.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QAbstractButton>\fP
.br
\fC#include 'diagramcontext\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementPropertiesEditorWidget\fP"
.br
.RI "The \fBElementPropertiesEditorWidget\fP class This class provide a dialog for edit various property of element, like the type (master, slave, report etc\&.\&.\&.\&.) and kind info\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
