.TH "sources/ElementsCollection/elementslocation.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/elementslocation.h
.SH SYNOPSIS
.br
.PP
\fC#include 'nameslist\&.h'\fP
.br
\fC#include 'diagramcontext\&.h'\fP
.br
\fC#include 'pugixml\&.hpp'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QIcon>\fP
.br
\fC#include 'sstream'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementsLocation\fP"
.br
.RI "The \fBElementsLocation\fP class This class represents the location, the location of an element or of a category, even of a collection \&.\&.\&. in a collection\&. She encapsulates a virtual path\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug \fBoperator<<\fP (QDebug debug, const \fBElementsLocation\fP &location)"
.br
.RI "operator << debug for processing \fBElementsLocation\fP "
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug operator<< (QDebug debug, const \fBElementsLocation\fP & location)"

.PP
operator << debug for processing \fBElementsLocation\fP 
.PP
\fBParameters\fP
.RS 4
\fIdebug\fP 
.br
\fIlocation\fP 
.RE
.PP
\fBReturns\fP
.RS 4
debug msg 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
