.TH "sources/ElementsCollection/elementcollectionhandler.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/elementcollectionhandler.h
.SH SYNOPSIS
.br
.PP
\fC#include 'elementslocation\&.h'\fP
.br
\fC#include 'nameslist\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBECHStrategy\fP"
.br
.RI "The \fBECHStrategy\fP class Abstract class for manage copy of directory or element from a collection to another\&. "
.ti -1c
.RI "class \fBECHSFileToFile\fP"
.br
.RI "The \fBECHSFileToFile\fP class Manage the copy of directory or element from a file system collection to another file system collection\&. "
.ti -1c
.RI "class \fBECHSXmlToFile\fP"
.br
.RI "The \fBECHSXmlToFile\fP class Manage the copy of a directory or element from an xml collection to a file\&. "
.ti -1c
.RI "class \fBECHSToXml\fP"
.br
.RI "The \fBECHSToXml\fP class Manage the copy of a directory or element from a collection (no matter if the source is a file system collection or an xml collection) to an xml collection\&. "
.ti -1c
.RI "class \fBElementCollectionHandler\fP"
.br
.RI "The \fBElementCollectionHandler\fP class Provide several method to copy element or directory from a collection to another collection\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
