.TH "sources/elementspanel.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/elementspanel.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementspanel\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'templatescollection\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENABLE_PANEL_DND_CHECKS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENABLE_PANEL_DND_CHECKS"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
