.TH "sources/elementtextpattern.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/elementtextpattern.h
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QDomDocument>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExportElementTextPattern\fP"
.br
.ti -1c
.RI "class \fBImportElementTextPattern\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
