.TH "sources/ElementsCollection/elementscollectionwidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/elementscollectionwidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'elementslocation\&.h'\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QModelIndex>\fP
.br
\fC#include <QTimer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementsCollectionWidget\fP"
.br
.RI "The \fBElementsCollectionWidget\fP class This widget embedd a tree view that display the element collection (common, custom, embedded) and all action needed to use this widget\&. This is the element collection widget used in the diagram editor\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
