.TH "ElementPictureFactory::primitives" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementPictureFactory::primitives
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <elementpicturefactory\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< QLineF > \fBm_lines\fP"
.br
.ti -1c
.RI "QList< QRectF > \fBm_rectangles\fP"
.br
.ti -1c
.RI "QList< QRectF > \fBm_circles\fP"
.br
.ti -1c
.RI "QList< QVector< QPointF > > \fBm_polygons\fP"
.br
.ti -1c
.RI "QList< QVector< qreal > > \fBm_arcs\fP"
.br
.ti -1c
.RI "QList< QGraphicsSimpleTextItem * > \fBm_texts\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QList<QVector<qreal> > ElementPictureFactory::primitives::m_arcs"

.SS "QList<QRectF> ElementPictureFactory::primitives::m_circles"

.SS "QList<QLineF> ElementPictureFactory::primitives::m_lines"

.SS "QList<QVector<QPointF> > ElementPictureFactory::primitives::m_polygons"

.SS "QList<QRectF> ElementPictureFactory::primitives::m_rectangles"

.SS "QList<QGraphicsSimpleTextItem*> ElementPictureFactory::primitives::m_texts"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
