.TH "sources/elementsmover.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/elementsmover.h
.SH SYNOPSIS
.br
.PP
\fC#include <QPointF>\fP
.br
\fC#include 'diagramcontent\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementsMover\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
