.TH "sources/ElementsCollection/elementcollectionhandler.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/elementcollectionhandler.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementcollectionhandler\&.h'\fP
.br
\fC#include 'renamedialog\&.h'\fP
.br
\fC#include 'xmlelementcollection\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'qetxml\&.h'\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QDir>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
