.TH "ElementXmlRetroCompatibility" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementXmlRetroCompatibility
.SH SYNOPSIS
.br
.PP
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBloadSequential\fP (const QDomElement &dom_element, const QString &seq, QStringList *list)"
.br
.ti -1c
.RI "static void \fBloadSequential\fP (const QDomElement &dom_element, \fBElement\fP *element)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBElement\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void ElementXmlRetroCompatibility::loadSequential (const QDomElement & dom_element, const QString & seq, QStringList * list)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SS "static void ElementXmlRetroCompatibility::loadSequential (const QDomElement & dom_element, \fBElement\fP * element)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBElement\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
