.TH "sources/editor/elementscene.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/elementscene.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementscene\&.h'\fP
.br
\fC#include 'qetelementeditor\&.h'\fP
.br
\fC#include 'elementprimitivedecorator\&.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'partline\&.h'\fP
.br
\fC#include 'partrectangle\&.h'\fP
.br
\fC#include 'partellipse\&.h'\fP
.br
\fC#include 'partpolygon\&.h'\fP
.br
\fC#include 'partterminal\&.h'\fP
.br
\fC#include 'parttext\&.h'\fP
.br
\fC#include 'partarc\&.h'\fP
.br
\fC#include 'editorcommands\&.h'\fP
.br
\fC#include 'elementcontent\&.h'\fP
.br
\fC#include 'ui/elementpropertieseditorwidget\&.h'\fP
.br
\fC#include 'eseventinterface\&.h'\fP
.br
\fC#include 'QetGraphicsItemModeler/qetgraphicshandleritem\&.h'\fP
.br
\fC#include 'partdynamictextfield\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'namelistdialog\&.h'\fP
.br
\fC#include 'namelistwidget\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <QKeyEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
