.TH "sources/qetgraphicsitem/elementtextitemgroup.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/elementtextitemgroup.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementtextitemgroup\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'addelementtextcommand\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'crossrefitem\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'masterelement\&.h'\fP
.br
\fC#include 'qgraphicsitemutility\&.h'\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QGraphicsSceneMouseEvent>\fP
.br
\fC#include <utility>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsorting\fP (QGraphicsItem *qgia, QGraphicsItem *qgib)"
.br
.RI "sorting "
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool sorting (QGraphicsItem * qgia, QGraphicsItem * qgib)"

.PP
sorting 
.PP
\fBParameters\fP
.RS 4
\fIqgia\fP 
.br
\fIqgib\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
