.TH "sources/elementsmover.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/elementsmover.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementsmover\&.h'\fP
.br
\fC#include 'conductor\&.h'\fP
.br
\fC#include 'conductortextitem\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'independenttextitem\&.h'\fP
.br
\fC#include 'diagramimageitem\&.h'\fP
.br
\fC#include 'conductorautonumerotation\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include 'elementtextitemgroup\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
