.TH "sources/ElementsCollection/elementslocation.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/elementslocation.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementslocation\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'xmlelementcollection\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'elementscollectioncache\&.h'\fP
.br
\fC#include 'elementpicturefactory\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'qetxml\&.h'\fP
.br
\fC#include <QPicture>\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug \fBoperator<<\fP (QDebug debug, const \fBElementsLocation\fP &location)"
.br
.RI "operator << debug for processing \fBElementsLocation\fP "
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug operator<< (QDebug debug, const \fBElementsLocation\fP & location)"

.PP
operator << debug for processing \fBElementsLocation\fP 
.PP
\fBParameters\fP
.RS 4
\fIdebug\fP 
.br
\fIlocation\fP 
.RE
.PP
\fBReturns\fP
.RS 4
debug msg 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
