.TH "sources/elementscategoryeditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/elementscategoryeditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementscategoryeditor\&.h'\fP
.br
\fC#include 'qet\&.h'\fP
.br
\fC#include 'qfilenameedit\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'elementcollectionhandler\&.h'\fP
.br
\fC#include 'namelistwidget\&.h'\fP
.br
\fC#include <QDialogButtonBox>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QHBoxLayout>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
