.TH "sources/editor/ui/elementpropertieseditorwidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/ui/elementpropertieseditorwidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementpropertieseditorwidget\&.h'\fP
.br
\fC#include 'ui_elementpropertieseditorwidget\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include <QItemDelegate>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEditorDelegate\fP"
.br
.RI "The \fBEditorDelegate\fP class This delegate is only use for disable the edition of the first column of the information tree widget\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
