.TH "sources/qetgraphicsitem/elementtextitemgroup.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/elementtextitemgroup.h
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsItemGroup>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QDomElement>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementTextItemGroup\fP"
.br
.RI "The \fBElementTextItemGroup\fP class This class represent a group of element text Texts in the group can be aligned left / center /right\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
