.TH "sources/elementdialog.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/elementdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QTreeView>\fP
.br
\fC#include <QDialogButtonBox>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QtConcurrent>\fP
.br
\fC#include 'elementdialog\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qfilenameedit\&.h'\fP
.br
\fC#include 'elementcollectionitem\&.h'\fP
.br
\fC#include 'elementscollectionmodel\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
