.TH "sources/dataBase/ui/elementquerywidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/dataBase/ui/elementquerywidget.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QButtonGroup>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementQueryWidget\fP"
.br
.RI "The \fBElementQueryWidget\fP class A widget use to edit a sql query for get element information This widget only work to get information from ProjectDataBase\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
