.TH "sources/ElementsCollection/elementscollectionmodel.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/elementscollectionmodel.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementscollectionmodel\&.h'\fP
.br
\fC#include 'elementcollectionitem\&.h'\fP
.br
\fC#include 'fileelementcollectionitem\&.h'\fP
.br
\fC#include 'xmlprojectelementcollectionitem\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'xmlelementcollection\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'elementcollectionhandler\&.h'\fP
.br
\fC#include <QFutureWatcher>\fP
.br
\fC#include <QtConcurrent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
