.TH "sources/elementprovider.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/elementprovider.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementprovider\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qetgraphicsitem/element\&.h'\fP
.br
\fC#include 'qetgraphicstableitem\&.h'\fP
.br
\fC#include <QAbstractItemModel>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
