.TH "sources/factory/elementfactory.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/factory/elementfactory.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'elementfactory\&.h'\fP
.br
\fC#include 'QDomElement'\fP
.br
\fC#include 'simpleelement\&.h'\fP
.br
\fC#include 'reportelement\&.h'\fP
.br
\fC#include 'masterelement\&.h'\fP
.br
\fC#include 'slaveelement\&.h'\fP
.br
\fC#include 'terminalelement\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
