.TH "sources/factory/elementpicturefactory.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/factory/elementpicturefactory.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMutex>\fP
.br
\fC#include <QSharedPointer>\fP
.br
\fC#include <QHash>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementPictureFactory\fP"
.br
.RI "The \fBElementPictureFactory\fP class This class is singleton factory, use to create and get the picture use by elements\&. "
.ti -1c
.RI "struct \fBElementPictureFactory::primitives\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
