.TH "EllipseEditor" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EllipseEditor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ellipseeditor\&.h>\fP
.PP
Inherits \fBElementItemEditor\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBeditingFinishedX\fP ()"
.br
.ti -1c
.RI "void \fBeditingFinishedY\fP ()"
.br
.ti -1c
.RI "void \fBeditingFinishedH\fP ()"
.br
.ti -1c
.RI "void \fBeditingFinishedV\fP ()"
.br
.ti -1c
.RI "void \fBupdateForm\fP () override"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEllipseEditor\fP (\fBQETElementEditor\fP *, \fBPartEllipse\fP *=nullptr, QWidget *=nullptr)"
.br
.ti -1c
.RI "\fB~EllipseEditor\fP () override"
.br
.RI "Destructeur\&. "
.ti -1c
.RI "bool \fBsetPart\fP (\fBCustomElementPart\fP *) override"
.br
.ti -1c
.RI "bool \fBsetParts\fP (QList< \fBCustomElementPart\fP * > parts) override"
.br
.ti -1c
.RI "\fBCustomElementPart\fP * \fBcurrentPart\fP () const override"
.br
.ti -1c
.RI "QList< \fBCustomElementPart\fP * > \fBcurrentParts\fP () const override"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBEllipseEditor\fP (const \fBEllipseEditor\fP &)"
.br
.ti -1c
.RI "void \fBactiveConnections\fP (bool)"
.br
.ti -1c
.RI "void \fBsetUpChangeConnections\fP ()"
.br
.RI "setUpChangeConnections Setup the connection from the ellipse(s) to the widget, to update it when the ellipse(s) are changed (moved \&.\&.\&.) "
.ti -1c
.RI "void \fBdisconnectChangeConnections\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPartEllipse\fP * \fBpart\fP"
.br
.ti -1c
.RI "\fBStyleEditor\fP * \fBstyle_\fP"
.br
.ti -1c
.RI "QDoubleSpinBox * \fBx\fP"
.br
.ti -1c
.RI "QDoubleSpinBox * \fBy\fP"
.br
.ti -1c
.RI "QDoubleSpinBox * \fBh\fP"
.br
.ti -1c
.RI "QDoubleSpinBox * \fBv\fP"
.br
.ti -1c
.RI "bool \fBm_locked\fP"
.br
.ti -1c
.RI "QList< QMetaObject::Connection > \fBm_change_connections\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class provides a widget to edit ellipses within the element editor\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EllipseEditor::EllipseEditor (\fBQETElementEditor\fP * editor, \fBPartEllipse\fP * ellipse = \fCnullptr\fP, QWidget * parent = \fCnullptr\fP)"
Constructeur 
.PP
\fBParameters\fP
.RS 4
\fIeditor\fP L'editeur d'element concerne 
.br
\fIellipse\fP L'ellipse a editer 
.br
\fIparent\fP le Widget parent 
.RE
.PP

.SS "EllipseEditor::~EllipseEditor ()\fC [override]\fP"

.PP
Destructeur\&. 
.SS "EllipseEditor::EllipseEditor (const \fBEllipseEditor\fP &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void EllipseEditor::activeConnections (bool active)\fC [private]\fP"
Active ou desactive les connexionx signaux/slots entre les widgets internes\&. 
.PP
\fBParameters\fP
.RS 4
\fIactive\fP true pour activer les connexions, false pour les desactiver 
.RE
.PP

.SS "\fBCustomElementPart\fP * EllipseEditor::currentPart () const\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
la primitive actuellement editee, ou 0 si ce widget n'en edite pas 
.RE
.PP

.PP
Implements \fBElementItemEditor\fP\&.
.SS "QList< \fBCustomElementPart\fP * > EllipseEditor::currentParts () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBElementItemEditor\fP\&.
.SS "void EllipseEditor::disconnectChangeConnections ()\fC [private]\fP"

.SS "void EllipseEditor::editingFinishedH ()\fC [slot]\fP"

.SS "void EllipseEditor::editingFinishedV ()\fC [slot]\fP"

.SS "void EllipseEditor::editingFinishedX ()\fC [slot]\fP"

.SS "void EllipseEditor::editingFinishedY ()\fC [slot]\fP"

.SS "bool EllipseEditor::setPart (\fBCustomElementPart\fP * new_part)\fC [override]\fP, \fC [virtual]\fP"
Permet de specifier a cet editeur quelle primitive il doit editer\&. A noter qu'un editeur peut accepter ou refuser d'editer une primitive\&. L'editeur d'ellipse acceptera d'editer la primitive new_part s'il s'agit d'un objet de la classe \fBPartEllipse\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_part\fP Nouvelle primitive a editer 
.RE
.PP
\fBReturns\fP
.RS 4
true si l'editeur a accepter d'editer la primitive, false sinon 
.RE
.PP

.PP
Implements \fBElementItemEditor\fP\&.
.SS "bool EllipseEditor::setParts (QList< \fBCustomElementPart\fP * > parts)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBElementItemEditor\fP\&.
.SS "void EllipseEditor::setUpChangeConnections ()\fC [private]\fP"

.PP
setUpChangeConnections Setup the connection from the ellipse(s) to the widget, to update it when the ellipse(s) are changed (moved \&.\&.\&.) 
.SS "void EllipseEditor::updateForm ()\fC [override]\fP, \fC [slot]\fP"
Met a jour le formulaire d'edition 
.SH "Member Data Documentation"
.PP 
.SS "QDoubleSpinBox * EllipseEditor::h\fC [private]\fP"

.SS "QList<QMetaObject::Connection> EllipseEditor::m_change_connections\fC [private]\fP"

.SS "bool EllipseEditor::m_locked\fC [private]\fP"

.SS "\fBPartEllipse\fP* EllipseEditor::part\fC [private]\fP"

.SS "\fBStyleEditor\fP* EllipseEditor::style_\fC [private]\fP"

.SS "QDoubleSpinBox * EllipseEditor::v\fC [private]\fP"

.SS "QDoubleSpinBox* EllipseEditor::x\fC [private]\fP"

.SS "QDoubleSpinBox * EllipseEditor::y\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
