.TH "ESEventAddDynamicTextField" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ESEventAddDynamicTextField \- The \fBESEventAddDynamicTextField\fP class This ESEvent manage creation of dynamic text field in an \fBElementScene\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eseventadddynamictextfield\&.h>\fP
.PP
Inherits \fBESEventInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBESEventAddDynamicTextField\fP (\fBElementScene\fP *scene)"
.br
.RI "\fBESEventAddDynamicTextField::ESEventAddDynamicTextField\fP\&. "
.ti -1c
.RI "\fB~ESEventAddDynamicTextField\fP () override"
.br
.RI "\fBESEventAddDynamicTextField::~ESEventAddDynamicTextField\fP\&. "
.ti -1c
.RI "bool \fBmouseMoveEvent\fP (QGraphicsSceneMouseEvent *event) override"
.br
.RI "\fBESEventAddDynamicTextField::mouseMoveEvent\fP\&. "
.ti -1c
.RI "bool \fBmouseReleaseEvent\fP (QGraphicsSceneMouseEvent *event) override"
.br
.RI "\fBESEventAddDynamicTextField::mouseReleaseEvent\fP\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPartDynamicTextField\fP * \fBm_text\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBESEventAddDynamicTextField\fP class This ESEvent manage creation of dynamic text field in an \fBElementScene\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ESEventAddDynamicTextField::ESEventAddDynamicTextField (\fBElementScene\fP * scene)"

.PP
\fBESEventAddDynamicTextField::ESEventAddDynamicTextField\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIscene\fP 
.RE
.PP

.SS "ESEventAddDynamicTextField::~ESEventAddDynamicTextField ()\fC [override]\fP"

.PP
\fBESEventAddDynamicTextField::~ESEventAddDynamicTextField\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool ESEventAddDynamicTextField::mouseMoveEvent (QGraphicsSceneMouseEvent * event)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBESEventAddDynamicTextField::mouseMoveEvent\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIevent\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Reimplemented from \fBESEventInterface\fP\&.
.SS "bool ESEventAddDynamicTextField::mouseReleaseEvent (QGraphicsSceneMouseEvent * event)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBESEventAddDynamicTextField::mouseReleaseEvent\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIevent\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Reimplemented from \fBESEventInterface\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPartDynamicTextField\fP* ESEventAddDynamicTextField::m_text\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
