.TH "sources/editor/esevent/eseventaddellipse.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/esevent/eseventaddellipse.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include 'eseventaddellipse\&.h'\fP
.br
\fC#include 'partellipse\&.h'\fP
.br
\fC#include 'editorcommands\&.h'\fP
.br
\fC#include 'elementscene\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
