.TH "sources/editor/esevent/eseventaddline.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/esevent/eseventaddline.h
.SH SYNOPSIS
.br
.PP
\fC#include 'eseventinterface\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBESEventAddLine\fP"
.br
.RI "The \fBESEventAddLine\fP class This ESEvent manage creation of line in a \fBElementScene\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
