.TH "sources/exportdialog.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/exportdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets>\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExportDialog\fP"
.br
.ti -1c
.RI "class \fBExportDialog::ExportDiagramLine\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
