.TH "sources/exportproperties.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/exportproperties.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'exportproperties\&.h'\fP
.br
\fC#include <QStandardPaths>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
