.TH "sources/ElementsCollection/fileelementcollectionitem.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/fileelementcollectionitem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'elementcollectionitem\&.h'\fP
.br
\fC#include 'elementslocation\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileElementCollectionItem\fP"
.br
.RI "The \fBFileElementCollectionItem\fP class This class specialise \fBElementCollectionItem\fP for manage a collection in a file system\&. They represente a directory or an element\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
