.TH "sources/ElementsCollection/fileelementcollectionitem.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/fileelementcollectionitem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'fileelementcollectionitem\&.h'\fP
.br
\fC#include 'elementslocation\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include <QDir>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
