.TH "sources/ui/formulaassistantdialog.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/formulaassistantdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'formulaassistantdialog\&.h'\fP
.br
\fC#include 'ui_formulaassistantdialog\&.h'\fP
.br
\fC#include <QPushButton>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
