.TH "sources/autoNum/ui/formulaautonumberingw.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/autoNum/ui/formulaautonumberingw.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'formulaautonumberingw\&.h'\fP
.br
\fC#include 'ui_formulaautonumberingw\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include <utility>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
