.TH "sources/genericpanel.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/genericpanel.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'genericpanel\&.h'\fP
.br
\fC#include <QTreeWidgetItem>\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'titleblock/templatescollection\&.h'\fP
.br
\fC#include 'titleblock/templatelocation\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
