.TH "sources/ui/configpage/generalconfigurationpage.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/configpage/generalconfigurationpage.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'generalconfigurationpage\&.h'\fP
.br
\fC#include 'ui_generalconfigurationpage\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QFontDialog>\fP
.br
\fC#include <QFileDialog>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
