.TH "sources/qetgraphicsitem/ViewItem/ui/graphicstablepropertieseditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/ViewItem/ui/graphicstablepropertieseditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'graphicstablepropertieseditor\&.h'\fP
.br
\fC#include 'ui_graphicstablepropertieseditor\&.h'\fP
.br
\fC#include 'qetgraphicstableitem\&.h'\fP
.br
\fC#include 'qetgraphicsheaderitem\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'itemmodelcommand\&.h'\fP
.br
\fC#include 'propertieseditorfactory\&.h'\fP
.br
\fC#include 'elementprovider\&.h'\fP
.br
\fC#include 'qetutils\&.h'\fP
.br
\fC#include <QAbstractItemModel>\fP
.br
\fC#include <QFontDialog>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
