.TH "sources/titleblock/helpercell.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/helpercell.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'helpercell\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
