.TH "sources/ui/imagepropertieswidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/imagepropertieswidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'imagepropertieswidget\&.h'\fP
.br
\fC#include 'ui_imagepropertieswidget\&.h'\fP
.br
\fC#include 'diagramimageitem\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
