.TH "sources/ui/importelementtextpatterndialog.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/importelementtextpatterndialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImportElementTextPatternDialog\fP"
.br
.RI "The \fBImportElementTextPatternDialog\fP class A dialog use for ask user to select a element text pattern\&. This dialog is highly inspired from QInputDialog::getItem\&. In fact this the same + a check box\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
