.TH "ImportElementDialog" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImportElementDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <importelementdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImportElementDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~ImportElementDialog\fP () override"
.br
.ti -1c
.RI "\fBQET::Action\fP \fBaction\fP () const"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUpWidget\fP ()"
.br
.ti -1c
.RI "void \fBsetUpConnection\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::ImportElementDialog * \fBui\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImportElementDialog::ImportElementDialog (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "ImportElementDialog::~ImportElementDialog ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBQET::Action\fP ImportElementDialog::action () const"

.SS "void ImportElementDialog::setUpConnection ()\fC [private]\fP"

.SS "void ImportElementDialog::setUpWidget ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "Ui::ImportElementDialog* ImportElementDialog::ui\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
