.TH "sources/ui/inditextpropertieswidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/inditextpropertieswidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'inditextpropertieswidget\&.h'\fP
.br
\fC#include 'ui_inditextpropertieswidget\&.h'\fP
.br
\fC#include 'independenttextitem\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include <QtGlobal>\fP
.br
\fC#include <QLineEdit>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
