.TH "sources/ui/inditextpropertieswidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/inditextpropertieswidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PropertiesEditor/propertieseditorwidget\&.h'\fP
.br
\fC#include <QPointer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIndiTextPropertiesWidget\fP"
.br
.RI "The \fBIndiTextPropertiesWidget\fP class This widget is used to edit the properties of one or several independent text item\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
