.TH "sources/ui/linksingleelementwidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/linksingleelementwidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'element\&.h'\fP
.br
\fC#include 'abstractelementpropertieseditorwidget\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLinkSingleElementWidget\fP"
.br
.RI "The \fBLinkSingleElementWidget\fP class this class provide a widget to select an element to be linked to the element given in the constructor\&. The element given in constructor must be linked with only one other element (like report or slave element)\&. This widget detect automaticaly the kind of element given in the constructor and search all element that can be linked with it\&. If the element is already linked, the widget ask user to unlink\&. This widget embedded the diagram command for undo/redo the action\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
