.TH "LinkReportPotentialSelector" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkReportPotentialSelector \- The \fBLinkReportPotentialSelector\fP class Use for get the conductor propertie when two potentials is linked with a folio report\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractPotentialSelector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkReportPotentialSelector\fP (\fBElement\fP *report)"
.br
.ti -1c
.RI "\fB~LinkReportPotentialSelector\fP () override"
.br
.ti -1c
.RI "bool \fBisValid\fP () const override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_is_valid\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBLinkReportPotentialSelector\fP class Use for get the conductor propertie when two potentials is linked with a folio report\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LinkReportPotentialSelector::LinkReportPotentialSelector (\fBElement\fP * report)\fC [inline]\fP"

.SS "LinkReportPotentialSelector::~LinkReportPotentialSelector ()\fC [inline]\fP, \fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool LinkReportPotentialSelector::isValid () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBAbstractPotentialSelector\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool LinkReportPotentialSelector::m_is_valid\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
