.TH "sources/undocommand/linkelementcommand.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/undocommand/linkelementcommand.h
.SH SYNOPSIS
.br
.PP
\fC#include <QUndoCommand>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLinkElementCommand\fP"
.br
.RI "The \fBLinkElementCommand\fP class This undo class manage link between elements\&. In the same instance of this class, we can link and unlink elements from an edited element This undo class support the merge\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
