.TH "sources/ui/linksingleelementwidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/linksingleelementwidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'linksingleelementwidget\&.h'\fP
.br
\fC#include 'ui_linksingleelementwidget\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'elementprovider\&.h'\fP
.br
\fC#include 'linkelementcommand\&.h'\fP
.br
\fC#include 'diagramposition\&.h'\fP
.br
\fC#include 'conductor\&.h'\fP
.br
\fC#include <QTreeWidgetItem>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
