.TH "Machine_info::Pc::OS" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Machine_info::Pc::OS
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <machine_info\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBtype\fP =QString(QSysInfo::kernelType())"
.br
.ti -1c
.RI "QString \fBname\fP =QString(QSysInfo::prettyProductName())"
.br
.ti -1c
.RI "QString \fBkernel\fP =QString(QSysInfo::kernelVersion())"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QString Machine_info::Pc::OS::kernel =QString(QSysInfo::kernelVersion())"

.SS "QString Machine_info::Pc::OS::name =QString(QSysInfo::prettyProductName())"

.SS "QString Machine_info::Pc::OS::type =QString(QSysInfo::kernelType())"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
