.TH "sources/machine_info.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/machine_info.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'machine_info\&.h'\fP
.br
\fC#include <QScreen>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QSysInfo>\fP
.br
\fC#include <QStorageInfo>\fP
.br
\fC#include <QLibraryInfo>\fP
.br
\fC#include 'qet\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
