.TH "Machine_info::Pc" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Machine_info::Pc
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBuilt\fP"
.br
.ti -1c
.RI "struct \fBCPU\fP"
.br
.ti -1c
.RI "struct \fBGPU\fP"
.br
.ti -1c
.RI "struct \fBOS\fP"
.br
.ti -1c
.RI "struct \fBRAM\fP"
.br
.ti -1c
.RI "struct \fBScreen\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBMachine_info::Pc::Screen\fP \fBscreen\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::Built\fP \fBbuilt\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::CPU\fP \fBcpu\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::RAM\fP \fBram\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::GPU\fP \fBgpu\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::OS\fP \fBos\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBMachine_info::Pc::Built\fP Machine_info::Pc::built"

.SS "struct \fBMachine_info::Pc::CPU\fP Machine_info::Pc::cpu"

.SS "struct \fBMachine_info::Pc::GPU\fP Machine_info::Pc::gpu"

.SS "struct \fBMachine_info::Pc::OS\fP Machine_info::Pc::os"

.SS "struct \fBMachine_info::Pc::RAM\fP Machine_info::Pc::ram"

.SS "struct \fBMachine_info::Pc::Screen\fP Machine_info::Pc::screen"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
