.TH "Machine_info::Pc::RAM" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Machine_info::Pc::RAM
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <machine_info\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBTotal\fP"
.br
.ti -1c
.RI "QString \fBAvailable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QString Machine_info::Pc::RAM::Available"

.SS "QString Machine_info::Pc::RAM::Total"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
