.TH "Machine_info::Pc::Screen" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Machine_info::Pc::Screen
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <machine_info\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBcount\fP"
.br
.ti -1c
.RI "int32_t \fBwidth\fP [10]"
.br
.ti -1c
.RI "int32_t \fBheight\fP [10]"
.br
.ti -1c
.RI "int32_t \fBMax_width\fP"
.br
.ti -1c
.RI "int32_t \fBMax_height\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int32_t Machine_info::Pc::Screen::count"

.SS "int32_t Machine_info::Pc::Screen::height[10]"

.SS "int32_t Machine_info::Pc::Screen::Max_height"

.SS "int32_t Machine_info::Pc::Screen::Max_width"

.SS "int32_t Machine_info::Pc::Screen::width[10]"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
