.TH "sources/machine_info.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/machine_info.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QThread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMachine_info\fP"
.br
.RI "The \fBMachine_info\fP class This class hold information from your PC\&. "
.ti -1c
.RI "struct \fBMachine_info::Pc\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::Screen\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::Built\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::CPU\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::RAM\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::GPU\fP"
.br
.ti -1c
.RI "struct \fBMachine_info::Pc::OS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
