.TH "sources/utils/macosxopenevent.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/utils/macosxopenevent.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'macosxopenevent\&.h'\fP
.br
\fC#include 'singleapplication\&.h'\fP
.br
\fC#include <QFileOpenEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
