.TH "sources/qetgraphicsitem/masterelement.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/masterelement.h
.SH SYNOPSIS
.br
.PP
\fC#include 'element\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMasterElement\fP"
.br
.RI "The \fBMasterElement\fP class This class is a custom element, with extended behavior to be a master element\&. Master element can be linked with slave element and display a cross ref item for know with what other element he is linked\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
