.TH "sources/ui/masterpropertieswidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/masterpropertieswidget.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QHash>\fP
.br
\fC#include 'abstractelementpropertieseditorwidget\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMasterPropertiesWidget\fP"
.br
.RI "The \fBMasterPropertiesWidget\fP class This class is a widget for make link between a master element with several slave element\&. This class embenddedthe undo/redo command when apply new connection\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
