.TH "sources/ui/masterpropertieswidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/masterpropertieswidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'masterpropertieswidget\&.h'\fP
.br
\fC#include 'ui_masterpropertieswidget\&.h'\fP
.br
\fC#include <QListWidgetItem>\fP
.br
\fC#include <diagramposition\&.h>\fP
.br
\fC#include <elementprovider\&.h>\fP
.br
\fC#include <diagram\&.h>\fP
.br
\fC#include <element\&.h>\fP
.br
\fC#include <linkelementcommand\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
