.TH "sources/qetgraphicsitem/masterelement.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/masterelement.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'masterelement\&.h'\fP
.br
\fC#include 'crossrefitem\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include <QRegularExpression>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
