.TH "sources/ui/multipastedialog.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/multipastedialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'multipastedialog\&.h'\fP
.br
\fC#include 'ui_multipastedialog\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'conductorautonumerotation\&.h'\fP
.br
\fC#include <QSettings>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
