.TH "sources/NameList/ui/namelistdialog.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/NameList/ui/namelistdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'namelistdialog\&.h'\fP
.br
\fC#include 'ui_namelistdialog\&.h'\fP
.br
\fC#include 'namelistwidget\&.h'\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
