.TH "sources/NameList/nameslist.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/NameList/nameslist.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtXml>\fP
.br
\fC#include 'pugixml\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNamesList\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQ_DECLARE_METATYPE\fP (\fBNamesList\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Q_DECLARE_METATYPE (\fBNamesList\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
