.TH "sources/NameList/ui/namelistwidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/NameList/ui/namelistwidget.h
.SH SYNOPSIS
.br
.PP
\fC#include 'nameslist\&.h'\fP
.br
\fC#include <QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNameListWidget\fP"
.br
.RI "The \fBNameListWidget\fP class Provide a widget for let user define localized string;\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
