.TH "sources/newelementwizard.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/newelementwizard.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'newelementwizard\&.h'\fP
.br
\fC#include 'namelistwidget\&.h'\fP
.br
\fC#include 'qetelementeditor\&.h'\fP
.br
\fC#include 'qfilenameedit\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'elementscollectionmodel\&.h'\fP
.br
\fC#include 'elementcollectionitem\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
