.TH "sources/autoNum/numerotationcontext.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/autoNum/numerotationcontext.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'numerotationcontext\&.h'\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'qet\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
