.TH "sources/autoNum/numerotationcontext.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/autoNum/numerotationcontext.h
.SH SYNOPSIS
.br
.PP
\fC#include <QStringList>\fP
.br
\fC#include <QVariant>\fP
.br
\fC#include <QDomElement>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNumerotationContext\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
