.TH "sources/autoNum/numerotationcontextcommands.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/autoNum/numerotationcontextcommands.h
.SH SYNOPSIS
.br
.PP
\fC#include 'numerotationcontext\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNumerotationContextCommands\fP"
.br
.RI "The \fBNumerotationContextCommands\fP class this class provide methods to handle content of \fBNumerotationContext\fP\&. "
.ti -1c
.RI "class \fBNumStrategy\fP"
.br
.ti -1c
.RI "class \fBUnitNum\fP"
.br
.ti -1c
.RI "class \fBUnitFNum\fP"
.br
.ti -1c
.RI "class \fBTenNum\fP"
.br
.ti -1c
.RI "class \fBTenFNum\fP"
.br
.ti -1c
.RI "class \fBHundredNum\fP"
.br
.ti -1c
.RI "class \fBHundredFNum\fP"
.br
.ti -1c
.RI "class \fBStringNum\fP"
.br
.ti -1c
.RI "class \fBIdFolioNum\fP"
.br
.ti -1c
.RI "class \fBFolioNum\fP"
.br
.ti -1c
.RI "class \fBPlantNum\fP"
.br
.ti -1c
.RI "class \fBLocmachNum\fP"
.br
.ti -1c
.RI "class \fBElementLineNum\fP"
.br
.ti -1c
.RI "class \fBElementColumnNum\fP"
.br
.ti -1c
.RI "class \fBElementPrefixNum\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
