.TH "sources/autoNum/ui/numparteditorw.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/autoNum/ui/numparteditorw.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QRegExp>\fP
.br
\fC#include 'numparteditorw\&.h'\fP
.br
\fC#include 'ui_numparteditorw\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
