.TH "sources/editor/graphicspart/partdynamictextfield.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/graphicspart/partdynamictextfield.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'partdynamictextfield\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'elementscene\&.h'\fP
.br
\fC#include <QGraphicsSceneMouseEvent>\fP
.br
\fC#include <QFont>\fP
.br
\fC#include <QColor>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
