.TH "PartEllipse" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartEllipse \- The \fBPartEllipse\fP class This class represents an ellipse primitive which may be used to compose the drawing of an electrical element within the element editor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <partellipse\&.h>\fP
.PP
Inherits \fBAbstractPartEllipse\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBType\fP = UserType + 1103 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartEllipse\fP (\fBQETElementEditor\fP *editor, QGraphicsItem *parent=nullptr)"
.br
.RI "\fBPartEllipse::PartEllipse\fP Constructor\&. "
.ti -1c
.RI "\fB~PartEllipse\fP () override"
.br
.RI "\fBPartEllipse::~PartEllipse\fP Destructor\&. "
.ti -1c
.RI "int \fBtype\fP () const override"
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *, const QStyleOptionGraphicsItem *, QWidget *=nullptr) override"
.br
.RI "\fBPartEllipse::paint\fP Draw this ellpise\&. "
.ti -1c
.RI "QString \fBname\fP () const override"
.br
.ti -1c
.RI "QString \fBxmlName\fP () const override"
.br
.ti -1c
.RI "const QDomElement \fBtoXml\fP (QDomDocument &) const override"
.br
.RI "\fBPartEllipse::toXml\fP Export this ellipse in xml\&. "
.ti -1c
.RI "void \fBfromXml\fP (const QDomElement &) override"
.br
.RI "\fBPartEllipse::fromXml\fP Import the properties of this ellipse from a xml element\&. "
.ti -1c
.RI "QPainterPath \fBshape\fP () const override"
.br
.RI "\fBPartEllipse::shape\fP\&. "
.ti -1c
.RI "QPainterPath \fBshadowShape\fP () const override"
.br
.ti -1c
.RI "void \fBsetRect\fP (const QRectF &\fBrect\fP) override"
.br
.RI "\fBAbstractPartEllipse::setRect\fP Sets the item's ellipse geometry to rect\&. The rectangle's left edge defines the left edge of the ellipse, and the rectangle's top edge describes the top of the ellipse The height and width of the rectangle describe the height and width of the ellipse\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBmouseReleaseEvent\fP (QGraphicsSceneMouseEvent *event) override"
.br
.RI "\fBPartEllipse::mouseReleaseEvent\fP Handle mouse release event\&. "
.ti -1c
.RI "QVariant \fBitemChange\fP (GraphicsItemChange change, const QVariant &value) override"
.br
.RI "\fBPartEllipse::itemChange\fP\&. "
.ti -1c
.RI "bool \fBsceneEventFilter\fP (QGraphicsItem *watched, QEvent *event) override"
.br
.RI "\fBPartEllipse::sceneEventFilter\fP\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBPartEllipse\fP (const \fBPartEllipse\fP &)"
.br
.ti -1c
.RI "void \fBswitchResizeMode\fP ()"
.br
.ti -1c
.RI "void \fBadjusteHandlerPos\fP ()"
.br
.RI "\fBPartEllipse::adjusteHandlerPos\fP\&. "
.ti -1c
.RI "void \fBhandlerMousePressEvent\fP (\fBQetGraphicsHandlerItem\fP *qghi, QGraphicsSceneMouseEvent *event)"
.br
.RI "\fBPartEllipse::handlerMousePressEvent\fP\&. "
.ti -1c
.RI "void \fBhandlerMouseMoveEvent\fP (\fBQetGraphicsHandlerItem\fP *qghi, QGraphicsSceneMouseEvent *event)"
.br
.RI "\fBPartEllipse::handlerMouseMoveEvent\fP\&. "
.ti -1c
.RI "void \fBhandlerMouseReleaseEvent\fP (\fBQetGraphicsHandlerItem\fP *qghi, QGraphicsSceneMouseEvent *event)"
.br
.RI "\fBPartEllipse::handlerMouseReleaseEvent\fP\&. "
.ti -1c
.RI "void \fBsceneSelectionChanged\fP ()"
.br
.RI "\fBPartEllipse::sceneSelectionChanged\fP When the scene selection change, if there are several primitive selected, we remove the handler of this item\&. "
.ti -1c
.RI "void \fBaddHandler\fP ()"
.br
.RI "\fBPartEllipse::addHandler\fP Add handlers for this item\&. "
.ti -1c
.RI "void \fBremoveHandler\fP ()"
.br
.RI "\fBPartEllipse::removeHandler\fP Remove the handlers of this item\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBQPropertyUndoCommand\fP * \fBm_undo_command\fP"
.br
.ti -1c
.RI "int \fBm_resize_mode\fP = 1"
.br
.ti -1c
.RI "int \fBm_vector_index\fP = \-1"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBPartEllipse\fP class This class represents an ellipse primitive which may be used to compose the drawing of an electrical element within the element editor\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIType \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PartEllipse::PartEllipse (\fBQETElementEditor\fP * editor, QGraphicsItem * parent = \fCnullptr\fP)"

.PP
\fBPartEllipse::PartEllipse\fP Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIeditor\fP : \fBQETElementEditor\fP of this part 
.br
\fIparent\fP : parent item 
.RE
.PP

.SS "PartEllipse::~PartEllipse ()\fC [override]\fP"

.PP
\fBPartEllipse::~PartEllipse\fP Destructor\&. 
.SS "PartEllipse::PartEllipse (const \fBPartEllipse\fP &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void PartEllipse::addHandler ()\fC [private]\fP"

.PP
\fBPartEllipse::addHandler\fP Add handlers for this item\&. 
.SS "void PartEllipse::adjusteHandlerPos ()\fC [private]\fP"

.PP
\fBPartEllipse::adjusteHandlerPos\fP\&. 
.SS "void PartEllipse::fromXml (const QDomElement & qde)\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBPartEllipse::fromXml\fP Import the properties of this ellipse from a xml element\&. 
.PP
\fBParameters\fP
.RS 4
\fIqde\fP : Xml document to use\&. 
.RE
.PP

.PP
Implements \fBCustomElementPart\fP\&.
.SS "void PartEllipse::handlerMouseMoveEvent (\fBQetGraphicsHandlerItem\fP * qghi, QGraphicsSceneMouseEvent * event)\fC [private]\fP"

.PP
\fBPartEllipse::handlerMouseMoveEvent\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIqghi\fP 
.br
\fIevent\fP 
.RE
.PP

.SS "void PartEllipse::handlerMousePressEvent (\fBQetGraphicsHandlerItem\fP * qghi, QGraphicsSceneMouseEvent * event)\fC [private]\fP"

.PP
\fBPartEllipse::handlerMousePressEvent\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIqghi\fP 
.br
\fIevent\fP 
.RE
.PP

.SS "void PartEllipse::handlerMouseReleaseEvent (\fBQetGraphicsHandlerItem\fP * qghi, QGraphicsSceneMouseEvent * event)\fC [private]\fP"

.PP
\fBPartEllipse::handlerMouseReleaseEvent\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIqghi\fP 
.br
\fIevent\fP 
.RE
.PP

.SS "QVariant PartEllipse::itemChange (GraphicsItemChange change, const QVariant & value)\fC [override]\fP, \fC [protected]\fP"

.PP
\fBPartEllipse::itemChange\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIchange\fP 
.br
\fIvalue\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "void PartEllipse::mouseReleaseEvent (QGraphicsSceneMouseEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
\fBPartEllipse::mouseReleaseEvent\fP Handle mouse release event\&. 
.PP
\fBParameters\fP
.RS 4
\fIevent\fP 
.RE
.PP

.SS "QString PartEllipse::name () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
the name of the primitive 
.RE
.PP

.PP
Implements \fBCustomElementPart\fP\&.
.SS "void PartEllipse::paint (QPainter * painter, const QStyleOptionGraphicsItem * options, QWidget * widget = \fCnullptr\fP)\fC [override]\fP"

.PP
\fBPartEllipse::paint\fP Draw this ellpise\&. 
.PP
\fBParameters\fP
.RS 4
\fIpainter\fP 
.br
\fIoptions\fP 
.br
\fIwidget\fP 
.RE
.PP

.SS "void PartEllipse::removeHandler ()\fC [private]\fP"

.PP
\fBPartEllipse::removeHandler\fP Remove the handlers of this item\&. 
.SS "bool PartEllipse::sceneEventFilter (QGraphicsItem * watched, QEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
\fBPartEllipse::sceneEventFilter\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIwatched\fP 
.br
\fIevent\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "void PartEllipse::sceneSelectionChanged ()\fC [private]\fP"

.PP
\fBPartEllipse::sceneSelectionChanged\fP When the scene selection change, if there are several primitive selected, we remove the handler of this item\&. 
.SS "void PartEllipse::setRect (const QRectF & rect)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBAbstractPartEllipse::setRect\fP Sets the item's ellipse geometry to rect\&. The rectangle's left edge defines the left edge of the ellipse, and the rectangle's top edge describes the top of the ellipse The height and width of the rectangle describe the height and width of the ellipse\&. 
.PP
\fBParameters\fP
.RS 4
\fIrect\fP 
.RE
.PP

.PP
Reimplemented from \fBAbstractPartEllipse\fP\&.
.SS "QPainterPath PartEllipse::shadowShape () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBCustomElementGraphicPart\fP\&.
.SS "QPainterPath PartEllipse::shape () const\fC [override]\fP"

.PP
\fBPartEllipse::shape\fP\&. 
.PP
\fBReturns\fP
.RS 4
the shape of this item 
.RE
.PP

.SS "void PartEllipse::switchResizeMode ()\fC [private]\fP"

.SS "const QDomElement PartEllipse::toXml (QDomDocument & xml_document) const\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBPartEllipse::toXml\fP Export this ellipse in xml\&. 
.PP
\fBParameters\fP
.RS 4
\fIxml_document\fP : Xml document to use for create the xml element\&. 
.RE
.PP
\fBReturns\fP
.RS 4
: an xml element that describe this ellipse 
.RE
.PP

.PP
Implements \fBCustomElementPart\fP\&.
.SS "int PartEllipse::type () const\fC [inline]\fP, \fC [override]\fP"
Enable the use of qgraphicsitem_cast to safely cast a QGraphicsItem into a \fBPartEllipse\fP\&. 
.PP
\fBReturns\fP
.RS 4
the QGraphicsItem type 
.RE
.PP

.SS "QString PartEllipse::xmlName () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
the name that will be used as XML tag when exporting the primitive 
.RE
.PP

.PP
Implements \fBCustomElementPart\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int PartEllipse::m_resize_mode = 1\fC [private]\fP"

.SS "\fBQPropertyUndoCommand\fP* PartEllipse::m_undo_command\fC [private]\fP"

.SS "int PartEllipse::m_vector_index = \-1\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
