.TH "sources/editor/graphicspart/partarc.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/graphicspart/partarc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'partarc\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'elementscene\&.h'\fP
.br
\fC#include 'QetGraphicsItemModeler/qetgraphicshandleritem\&.h'\fP
.br
\fC#include 'QetGraphicsItemModeler/qetgraphicshandlerutility\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
