.TH "sources/editor/graphicspart/partdynamictextfield.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/graphicspart/partdynamictextfield.h
.SH SYNOPSIS
.br
.PP
\fC#include 'customelementpart\&.h'\fP
.br
\fC#include 'QGraphicsTextItem'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPartDynamicTextField\fP"
.br
.RI "The \fBPartDynamicTextField\fP class This class represents an editable dynamic text field which may be used to compose the drawing of an electrical element within the element editor\&. The field will remain editable once the element is added onto a diagram\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
