.TH "sources/editor/graphicspart/partterminal.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/graphicspart/partterminal.h
.SH SYNOPSIS
.br
.PP
\fC#include 'customelementgraphicpart\&.h'\fP
.br
\fC#include 'QUuid'\fP
.br
\fC#include 'terminaldata\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPartTerminal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
