.TH "sources/editor/graphicspart/partarc.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/graphicspart/partarc.h
.SH SYNOPSIS
.br
.PP
\fC#include 'abstractpartellipse\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPartArc\fP"
.br
.RI "The \fBPartArc\fP class This class represents an elliptical arc primitive which may be used to compose the drawing of an electrical element within the element editor\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
