.TH "sources/editor/ui/polygoneditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/ui/polygoneditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'polygoneditor\&.h'\fP
.br
\fC#include 'ui_polygoneditor\&.h'\fP
.br
\fC#include 'partpolygon\&.h'\fP
.br
\fC#include 'elementscene\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'styleeditor\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
