.TH "sources/qetgraphicsitem/ViewItem/projectdbmodel.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/ViewItem/projectdbmodel.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'projectdbmodel\&.h'\fP
.br
\fC#include 'projectdatabase\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'qetxml\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include <QSqlError>\fP
.br
\fC#include <QSqlRecord>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
