.TH "sources/projectview.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/projectview.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include <QTabBar>\fP
.br
\fC#include 'templatelocation\&.h'\fP
.br
\fC#include 'qetresult\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProjectView\fP"
.br
.RI "The \fBProjectView\fP class This class provides a widget displaying the diagrams of a particular project using tabs\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
