.TH "sources/dataBase/projectdatabase.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/dataBase/projectdatabase.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QSqlDatabase>\fP
.br
\fC#include <QSqlQuery>\fP
.br
\fC#include <QPointer>\fP
.br
\fC#include <QFileDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBprojectDataBase\fP"
.br
.RI "The \fBprojectDataBase\fP class This class wrap a sqlite data base where you can find several thing about the content of a project\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
