.TH "sources/projectconfigpages.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/projectconfigpages.h
.SH SYNOPSIS
.br
.PP
\fC#include 'configpage\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProjectConfigPage\fP"
.br
.RI "The \fBProjectConfigPage\fP class This class, derived from \fBConfigPage\fP, aims at providing the basic skeleton for a project configuration page\&. "
.ti -1c
.RI "class \fBProjectMainConfigPage\fP"
.br
.ti -1c
.RI "class \fBProjectAutoNumConfigPage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
