.TH "sources/ui/projectpropertiesdialog.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/projectpropertiesdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'projectpropertiesdialog\&.h'\fP
.br
\fC#include 'configdialog\&.h'\fP
.br
\fC#include 'projectconfigpages\&.h'\fP
.br
\fC#include <QObject>\fP
.br
\fC#include 'configpages\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
