.TH "sources/dataBase/projectdatabase.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/dataBase/projectdatabase.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'projectdatabase\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'elementprovider\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'diagramposition\&.h'\fP
.br
\fC#include <QSqlError>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
