.TH "sources/qetgraphicsitem/ViewItem/ui/projectdbmodelpropertieswidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/ViewItem/ui/projectdbmodelpropertieswidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'projectdbmodelpropertieswidget\&.h'\fP
.br
\fC#include 'ui_projectdbmodelpropertieswidget\&.h'\fP
.br
\fC#include 'projectdbmodel\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'elementquerywidget\&.h'\fP
.br
\fC#include 'summaryquerywidget\&.h'\fP
.br
\fC#include <QDialogButtonBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
