.TH "sources/projectview.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/projectview.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'projectview\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'diagramview\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'diagramprintdialog\&.h'\fP
.br
\fC#include 'exportdialog\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qetelementeditor\&.h'\fP
.br
\fC#include 'borderpropertieswidget\&.h'\fP
.br
\fC#include 'titleblockpropertieswidget\&.h'\fP
.br
\fC#include 'conductorpropertieswidget\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'qettemplateeditor\&.h'\fP
.br
\fC#include 'projectpropertiesdialog\&.h'\fP
.br
\fC#include 'xmlelementcollection\&.h'\fP
.br
\fC#include 'autoNum/assignvariables\&.h'\fP
.br
\fC#include 'dialogwaiting\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
