.TH "sources/projectconfigpages.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/projectconfigpages.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'projectconfigpages\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'borderpropertieswidget\&.h'\fP
.br
\fC#include 'conductorpropertieswidget\&.h'\fP
.br
\fC#include 'diagramcontextwidget\&.h'\fP
.br
\fC#include 'titleblockpropertieswidget\&.h'\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include 'ui/reportpropertiewidget\&.h'\fP
.br
\fC#include 'ui/xrefpropertieswidget\&.h'\fP
.br
\fC#include 'selectautonumw\&.h'\fP
.br
\fC#include 'numerotationcontext\&.h'\fP
.br
\fC#include 'folioautonumbering\&.h'\fP
.br
\fC#include 'formulaautonumberingw\&.h'\fP
.br
\fC#include 'autonumberingmanagementw\&.h'\fP
.br
\fC#include 'ui_autonumberingmanagementw\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
