.TH "sources/factory/propertieseditorfactory.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/factory/propertieseditorfactory.h
.SH SYNOPSIS
.br
.PP
\fC#include <QList>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPropertiesEditorFactory\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPropertiesEditorWidget\fP * \fBPropertiesEditorFactory::propertiesEditor\fP (QAbstractItemModel *model, \fBPropertiesEditorWidget\fP *editor=nullptr, QWidget *parent=nullptr)"
.br
.RI "\fBPropertiesEditorFactory::propertiesEditor\fP\&. "
.ti -1c
.RI "\fBPropertiesEditorWidget\fP * \fBPropertiesEditorFactory::propertiesEditor\fP (QList< QGraphicsItem * > items, \fBPropertiesEditorWidget\fP *editor=nullptr, QWidget *parent=nullptr)"
.br
.RI "propertiesEditor "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
