.TH "sources/properties/propertiesinterface.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/properties/propertiesinterface.h
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QDomElement>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPropertiesInterface\fP"
.br
.RI "The \fBPropertiesInterface\fP class This class is an interface for have common way to use properties in QElectroTech\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
