.TH "PropertiesEditorDialog" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertiesEditorDialog \- The \fBPropertiesEditorDialog\fP class Create a dialog to edit some properties of a thing\&. Only create a instance of this class and call exec, all is done for you in this class\&. The first argument (a template) must be a subclass of QWidget and provide the 3 methods bellow : QString::title() void::apply() void::reset() You can subclass the interface \fBPropertiesEditorWidget\fP who provide all this methods\&. This dialog take ownership of the editor, so the editor will be deleted by this dialog\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <propertieseditordialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBPropertiesEditorDialog\fP (T editor, QWidget *parent=nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBPropertiesEditorDialog\fP class Create a dialog to edit some properties of a thing\&. Only create a instance of this class and call exec, all is done for you in this class\&. The first argument (a template) must be a subclass of QWidget and provide the 3 methods bellow : QString::title() void::apply() void::reset() You can subclass the interface \fBPropertiesEditorWidget\fP who provide all this methods\&. This dialog take ownership of the editor, so the editor will be deleted by this dialog\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > PropertiesEditorDialog::PropertiesEditorDialog (T editor, QWidget * parent = \fCnullptr\fP)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
