.TH "qdesigner_internal::AddLinkDialog" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qdesigner_internal::AddLinkDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaccept\fP () override"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddLinkDialog\fP (\fBRichTextEditor\fP *editor, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~AddLinkDialog\fP () override"
.br
.ti -1c
.RI "int \fBshowDialog\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRichTextEditor\fP * \fBm_editor\fP"
.br
.ti -1c
.RI "\fBUi::AddLinkDialog\fP * \fBm_ui\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "qdesigner_internal::AddLinkDialog::AddLinkDialog (\fBRichTextEditor\fP * editor, QWidget * parent = \fCnullptr\fP)"

.SS "qdesigner_internal::AddLinkDialog::~AddLinkDialog ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void qdesigner_internal::AddLinkDialog::accept ()\fC [override]\fP, \fC [slot]\fP"

.SS "int qdesigner_internal::AddLinkDialog::showDialog ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBRichTextEditor\fP* qdesigner_internal::AddLinkDialog::m_editor\fC [private]\fP"

.SS "\fBUi::AddLinkDialog\fP* qdesigner_internal::AddLinkDialog::m_ui\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
