.TH "qdesigner_internal::HtmlTextEdit" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qdesigner_internal::HtmlTextEdit
.SH SYNOPSIS
.br
.PP
.PP
Inherits QTextEdit\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHtmlTextEdit\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBcontextMenuEvent\fP (QContextMenuEvent *event) override"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBactionTriggered\fP (QAction *action)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "qdesigner_internal::HtmlTextEdit::HtmlTextEdit (QWidget * parent = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void qdesigner_internal::HtmlTextEdit::actionTriggered (QAction * action)\fC [private]\fP, \fC [slot]\fP"

.SS "void qdesigner_internal::HtmlTextEdit::contextMenuEvent (QContextMenuEvent * event)\fC [override]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
