.TH "qdesigner_internal::ColorAction" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qdesigner_internal::ColorAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits QAction\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcolorChanged\fP (const QColor &\fBcolor\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorAction\fP (QObject *parent)"
.br
.ti -1c
.RI "const QColor & \fBcolor\fP () const"
.br
.ti -1c
.RI "void \fBsetColor\fP (const QColor &\fBcolor\fP)"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBchooseColor\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QColor \fBm_color\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "qdesigner_internal::ColorAction::ColorAction (QObject * parent)"

.SH "Member Function Documentation"
.PP 
.SS "void qdesigner_internal::ColorAction::chooseColor ()\fC [private]\fP, \fC [slot]\fP"

.SS "const QColor& qdesigner_internal::ColorAction::color () const\fC [inline]\fP"

.SS "void qdesigner_internal::ColorAction::colorChanged (const QColor & color)\fC [signal]\fP"

.SS "void qdesigner_internal::ColorAction::setColor (const QColor & color)"

.SH "Member Data Documentation"
.PP 
.SS "QColor qdesigner_internal::ColorAction::m_color\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
