.TH "qdesigner_internal" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qdesigner_internal
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddLinkDialog\fP"
.br
.ti -1c
.RI "class \fBColorAction\fP"
.br
.ti -1c
.RI "class \fBHtmlTextEdit\fP"
.br
.ti -1c
.RI "class \fBRichTextEditor\fP"
.br
.ti -1c
.RI "class \fBRichTextEditorDialog\fP"
.br
.ti -1c
.RI "class \fBRichTextEditorToolBar\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBsimplifyRichTextFilter\fP (const QString &in, bool *isPlainTextPtr=nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Integration : QElectroTech Team Changelog:
.IP "\(bu" 2
09/04/2013 : Start integration\&.\&.\&.Compilation and object creation are successful 
.PP

.SH "Function Documentation"
.PP 
.SS "QString qdesigner_internal::simplifyRichTextFilter (const QString & in, bool * isPlainTextPtr = \fCnullptr\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
