.TH "sources/qet.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qet.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qet\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include <limits>\fP
.br
\fC#include <QGraphicsSceneContextMenuEvent>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QSaveFile>\fP
.br
\fC#include <QTextStream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
