.TH "QET::Icons" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QET::Icons
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitIcons\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QIcon \fBAdd\fP"
.br
.ti -1c
.RI "QIcon \fBAddFolio\fP"
.br
.ti -1c
.RI "QIcon \fBAllowed\fP"
.br
.ti -1c
.RI "QIcon \fBApplicationExit\fP"
.br
.ti -1c
.RI "QIcon \fBArrowLeft\fP"
.br
.ti -1c
.RI "QIcon \fBArrowLeftDouble\fP"
.br
.ti -1c
.RI "QIcon \fBArrowRight\fP"
.br
.ti -1c
.RI "QIcon \fBArrowRightDouble\fP"
.br
.ti -1c
.RI "QIcon \fBAutoconnect\fP"
.br
.ti -1c
.RI "QIcon \fBBringForward\fP"
.br
.ti -1c
.RI "QIcon \fBCancel\fP"
.br
.ti -1c
.RI "QIcon \fBConductor\fP"
.br
.ti -1c
.RI "QIcon \fBConductorEdit\fP"
.br
.ti -1c
.RI "QIcon \fBConductorSettings\fP"
.br
.ti -1c
.RI "QIcon \fBConfigure\fP"
.br
.ti -1c
.RI "QIcon \fBConfigureToolbars\fP"
.br
.ti -1c
.RI "QIcon \fBIC_CopyFile\fP"
.br
.ti -1c
.RI "QIcon \fBDefaultConductor\fP"
.br
.ti -1c
.RI "QIcon \fBDiagramAdd\fP"
.br
.ti -1c
.RI "QIcon \fBDiagram\fP"
.br
.ti -1c
.RI "QIcon \fBDiagramBg\fP"
.br
.ti -1c
.RI "QIcon \fBDiagramDelete\fP"
.br
.ti -1c
.RI "QIcon \fBDialogCancel\fP"
.br
.ti -1c
.RI "QIcon \fBDialogInformation\fP"
.br
.ti -1c
.RI "QIcon \fBDialogOk\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentClose\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentExport\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentSpreadsheet\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentImport\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentNew\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentOpen\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentOpenRecent\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentPrint\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentPrintFrame\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentSave\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentSaveAll\fP"
.br
.ti -1c
.RI "QIcon \fBDocumentSaveAs\fP"
.br
.ti -1c
.RI "QIcon \fBEast\fP"
.br
.ti -1c
.RI "QIcon \fBEditClear\fP"
.br
.ti -1c
.RI "QIcon \fBEditClearLocationBar\fP"
.br
.ti -1c
.RI "QIcon \fBEditCopy\fP"
.br
.ti -1c
.RI "QIcon \fBEditCut\fP"
.br
.ti -1c
.RI "QIcon \fBEditDelete\fP"
.br
.ti -1c
.RI "QIcon \fBEditPaste\fP"
.br
.ti -1c
.RI "QIcon \fBEditRedo\fP"
.br
.ti -1c
.RI "QIcon \fBEditRename\fP"
.br
.ti -1c
.RI "QIcon \fBEditSelectAll\fP"
.br
.ti -1c
.RI "QIcon \fBEditSelectInvert\fP"
.br
.ti -1c
.RI "QIcon \fBEditSelectNone\fP"
.br
.ti -1c
.RI "QIcon \fBEditTableCellMerge\fP"
.br
.ti -1c
.RI "QIcon \fBEditTableCellSplit\fP"
.br
.ti -1c
.RI "QIcon \fBEditTableDeleteColumn\fP"
.br
.ti -1c
.RI "QIcon \fBEditTableDeleteRow\fP"
.br
.ti -1c
.RI "QIcon \fBEditTableInsertColumnLeft\fP"
.br
.ti -1c
.RI "QIcon \fBEditTableInsertColumnRight\fP"
.br
.ti -1c
.RI "QIcon \fBEditTableInsertRowAbove\fP"
.br
.ti -1c
.RI "QIcon \fBEditTableInsertRowUnder\fP"
.br
.ti -1c
.RI "QIcon \fBEditText\fP"
.br
.ti -1c
.RI "QIcon \fBEditUndo\fP"
.br
.ti -1c
.RI "QIcon \fBElement\fP"
.br
.ti -1c
.RI "QIcon \fBElementDelete\fP"
.br
.ti -1c
.RI "QIcon \fBElementEdit\fP"
.br
.ti -1c
.RI "QIcon \fBElementNew\fP"
.br
.ti -1c
.RI "QIcon \fBElementSmall\fP"
.br
.ti -1c
.RI "QIcon \fBEndLineCircle\fP"
.br
.ti -1c
.RI "QIcon \fBEndLineDiamond\fP"
.br
.ti -1c
.RI "QIcon \fBEndLineNone\fP"
.br
.ti -1c
.RI "QIcon \fBEndLineSimple\fP"
.br
.ti -1c
.RI "QIcon \fBEndLineTriangle\fP"
.br
.ti -1c
.RI "QIcon \fBEPS\fP"
.br
.ti -1c
.RI "QIcon \fBFolder\fP"
.br
.ti -1c
.RI "QIcon \fBFolderDelete\fP"
.br
.ti -1c
.RI "QIcon \fBFolderEdit\fP"
.br
.ti -1c
.RI "QIcon \fBFolderNew\fP"
.br
.ti -1c
.RI "QIcon \fBFolderOnlyThis\fP"
.br
.ti -1c
.RI "QIcon \fBFolderOpen\fP"
.br
.ti -1c
.RI "QIcon \fBFolderProperties\fP"
.br
.ti -1c
.RI "QIcon \fBFolderShowAll\fP"
.br
.ti -1c
.RI "QIcon \fBForbidden\fP"
.br
.ti -1c
.RI "QIcon \fBFullScreenEnter\fP"
.br
.ti -1c
.RI "QIcon \fBFullScreenExit\fP"
.br
.ti -1c
.RI "QIcon \fBGoBottom\fP"
.br
.ti -1c
.RI "QIcon \fBGoDown\fP"
.br
.ti -1c
.RI "QIcon \fBGoDownDouble\fP"
.br
.ti -1c
.RI "QIcon \fBGoTop\fP"
.br
.ti -1c
.RI "QIcon \fBGoUp\fP"
.br
.ti -1c
.RI "QIcon \fBGoUpDouble\fP"
.br
.ti -1c
.RI "QIcon \fBGround\fP"
.br
.ti -1c
.RI "QIcon \fBGrid\fP"
.br
.ti -1c
.RI "QIcon \fBHide\fP"
.br
.ti -1c
.RI "QIcon \fBHome\fP"
.br
.ti -1c
.RI "QIcon \fBHotSpot\fP"
.br
.ti -1c
.RI "QIcon \fBInsertImage\fP"
.br
.ti -1c
.RI "QIcon \fBLower\fP"
.br
.ti -1c
.RI "QIcon \fBIC_MoveFile\fP"
.br
.ti -1c
.RI "QIcon \fBNames\fP"
.br
.ti -1c
.RI "QIcon \fBNeutral\fP"
.br
.ti -1c
.RI "QIcon \fBNewDiagram\fP"
.br
.ti -1c
.RI "QIcon \fBNorth\fP"
.br
.ti -1c
.RI "QIcon \fBObjectLocked\fP"
.br
.ti -1c
.RI "QIcon \fBObjectRotateRight\fP"
.br
.ti -1c
.RI "QIcon \fBObjectUnlocked\fP"
.br
.ti -1c
.RI "QIcon \fBOrientations\fP"
.br
.ti -1c
.RI "QIcon \fBPartArc\fP"
.br
.ti -1c
.RI "QIcon \fBPartCircle\fP"
.br
.ti -1c
.RI "QIcon \fBPartEllipse\fP"
.br
.ti -1c
.RI "QIcon \fBPartLine\fP"
.br
.ti -1c
.RI "QIcon \fBPartPolygon\fP"
.br
.ti -1c
.RI "QIcon \fBPartRectangle\fP"
.br
.ti -1c
.RI "QIcon \fBPartSelect\fP"
.br
.ti -1c
.RI "QIcon \fBPartText\fP"
.br
.ti -1c
.RI "QIcon \fBPartTextField\fP"
.br
.ti -1c
.RI "QIcon \fBPDF\fP"
.br
.ti -1c
.RI "QIcon \fBPhase\fP"
.br
.ti -1c
.RI "QIcon \fBPrintAllPages\fP"
.br
.ti -1c
.RI "QIcon \fBPrinter\fP"
.br
.ti -1c
.RI "QIcon \fBPrintLandscape\fP"
.br
.ti -1c
.RI "QIcon \fBPrintPortrait\fP"
.br
.ti -1c
.RI "QIcon \fBPrintTwoPages\fP"
.br
.ti -1c
.RI "QIcon \fBProject\fP"
.br
.ti -1c
.RI "QIcon \fBProjectClose\fP"
.br
.ti -1c
.RI "QIcon \fBProjectNew\fP"
.br
.ti -1c
.RI "QIcon \fBProjects\fP"
.br
.ti -1c
.RI "QIcon \fBProjectFile\fP"
.br
.ti -1c
.RI "QIcon \fBProjectFileGP\fP"
.br
.ti -1c
.RI "QIcon \fBProjectProperties\fP"
.br
.ti -1c
.RI "QIcon \fBQETIcon\fP"
.br
.ti -1c
.RI "QIcon \fBQETLogo\fP"
.br
.ti -1c
.RI "QIcon \fBQETOxygenLogo\fP"
.br
.ti -1c
.RI "QIcon \fBQtLogo\fP"
.br
.ti -1c
.RI "QIcon \fBRaise\fP"
.br
.ti -1c
.RI "QIcon \fBRemove\fP"
.br
.ti -1c
.RI "QIcon \fBRestore\fP"
.br
.ti -1c
.RI "QIcon \fBRunDxf\fP"
.br
.ti -1c
.RI "QIcon \fBSendBackward\fP"
.br
.ti -1c
.RI "QIcon \fBSettings\fP"
.br
.ti -1c
.RI "QIcon \fBSinglePage\fP"
.br
.ti -1c
.RI "QIcon \fBSouth\fP"
.br
.ti -1c
.RI "QIcon \fBStart\fP"
.br
.ti -1c
.RI "QIcon \fBTableOfContent\fP"
.br
.ti -1c
.RI "QIcon \fBTerminal\fP"
.br
.ti -1c
.RI "QIcon \fBTitleBlock\fP"
.br
.ti -1c
.RI "QIcon \fBTitleBlockBottom\fP"
.br
.ti -1c
.RI "QIcon \fBTitleBlockRight\fP"
.br
.ti -1c
.RI "QIcon \fBTransformRotate\fP"
.br
.ti -1c
.RI "QIcon \fBUserInformations\fP"
.br
.ti -1c
.RI "QIcon \fBViewFitWidth\fP"
.br
.ti -1c
.RI "QIcon \fBViewFitWindow\fP"
.br
.ti -1c
.RI "QIcon \fBViewMove\fP"
.br
.ti -1c
.RI "QIcon \fBViewRefresh\fP"
.br
.ti -1c
.RI "QIcon \fBWest\fP"
.br
.ti -1c
.RI "QIcon \fBWindowNew\fP"
.br
.ti -1c
.RI "QIcon \fBXmlTextFile\fP"
.br
.ti -1c
.RI "QIcon \fBZoomDraw\fP"
.br
.ti -1c
.RI "QIcon \fBZoomFitBest\fP"
.br
.ti -1c
.RI "QIcon \fBZoomIn\fP"
.br
.ti -1c
.RI "QIcon \fBZoomOriginal\fP"
.br
.ti -1c
.RI "QIcon \fBZoomOut\fP"
.br
.ti -1c
.RI "QIcon \fBadding_image\fP"
.br
.ti -1c
.RI "QIcon \fBresize_image\fP"
.br
.ti -1c
.RI "QIcon \fBar\fP"
.br
.ti -1c
.RI "QIcon \fBbr\fP"
.br
.ti -1c
.RI "QIcon \fBcatalonia\fP"
.br
.ti -1c
.RI "QIcon \fBcs\fP"
.br
.ti -1c
.RI "QIcon \fBde\fP"
.br
.ti -1c
.RI "QIcon \fBda\fP"
.br
.ti -1c
.RI "QIcon \fBgr\fP"
.br
.ti -1c
.RI "QIcon \fBen\fP"
.br
.ti -1c
.RI "QIcon \fBes\fP"
.br
.ti -1c
.RI "QIcon \fBfr\fP"
.br
.ti -1c
.RI "QIcon \fBhr\fP"
.br
.ti -1c
.RI "QIcon \fBhu\fP"
.br
.ti -1c
.RI "QIcon \fBit\fP"
.br
.ti -1c
.RI "QIcon \fBjp\fP"
.br
.ti -1c
.RI "QIcon \fBpl\fP"
.br
.ti -1c
.RI "QIcon \fBpt\fP"
.br
.ti -1c
.RI "QIcon \fBro\fP"
.br
.ti -1c
.RI "QIcon \fBru\fP"
.br
.ti -1c
.RI "QIcon \fBsl\fP"
.br
.ti -1c
.RI "QIcon \fBnl\fP"
.br
.ti -1c
.RI "QIcon \fBno\fP"
.br
.ti -1c
.RI "QIcon \fBbe\fP"
.br
.ti -1c
.RI "QIcon \fBtr\fP"
.br
.ti -1c
.RI "QIcon \fBtranslation\fP"
.br
.ti -1c
.RI "QIcon \fBlistDrawings\fP"
.br
.ti -1c
.RI "QIcon \fBAutoNum\fP"
.br
.ti -1c
.RI "QIcon \fBTerminalStrip\fP"
.br
.ti -1c
.RI "QIcon \fBQETManual\fP"
.br
.ti -1c
.RI "QIcon \fBQETDonate\fP"
.br
.ti -1c
.RI "QIcon \fBQETDownload\fP"
.br
.ti -1c
.RI "QIcon \fBQETVideo\fP"
.br
.ti -1c
.RI "QIcon \fBsuper\fP"
.br
.ti -1c
.RI "QIcon \fBsub\fP"
.br
.ti -1c
.RI "QIcon \fBtextGroup\fP"
.br
.ti -1c
.RI "QIcon \fBElementMaster\fP"
.br
.ti -1c
.RI "QIcon \fBElementSlave\fP"
.br
.ti -1c
.RI "QIcon \fBFolioXrefComing\fP"
.br
.ti -1c
.RI "QIcon \fBElementTerminal\fP"
.br
.ti -1c
.RI "QIcon \fBColorBrown\fP"
.br
.ti -1c
.RI "QIcon \fBColorGray\fP"
.br
.ti -1c
.RI "QIcon \fBColorOrange\fP"
.br
.ti -1c
.RI "QIcon \fBColorPurple\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPinkPink\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPinkLightPink\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPinkHotPink\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPinkDeepPink\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPinkPaleVioletRed\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPinkMediumVioletRed\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedLightSalmon\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedSalmon\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedDarkSalmon\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedLightCoral\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedIndianRed\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedCrimson\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedFirebrick\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedDarkRed\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLRedRed\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLOrangeOrangeRed\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLOrangeTomato\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLOrangeCoral\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLOrangeDarkOrange\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLOrangeOrange\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowYellow\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowLightYellow\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowLemonChiffon\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowLightGoldenrodYellow\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowPapayaWhip\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowMoccasin\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowPeachPuff\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowPaleGoldenrod\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowKhaki\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowDarkKhaki\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLYellowGold\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownCornsilk\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownBlanchedAlmond\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownBisque\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownNavajoWhite\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownWheat\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownBurlywood\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownTan\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownRosyBrown\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownSandyBrown\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownGoldenrod\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownDarkGoldenrod\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownPeru\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownChocolate\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownSaddleBrown\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownSienna\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownBrown\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBrownMaroon\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenDarkOliveGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenOlive\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenOliveDrab\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenYellowGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenLimeGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenLime\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenLawnGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenChartreuse\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenGreenYellow\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenSpringGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenMediumSpringGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenLightGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenPaleGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenDarkSeaGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenMediumAquamarine\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenMediumSeaGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenSeaGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenForestGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGreenDarkGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanAqua\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanCyan\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanLightCyan\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanPaleTurquoise\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanAquamarine\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanTurquoise\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanMediumTurquoise\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanDarkTurquoise\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanLightSeaGreen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanCadetBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanDarkCyan\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLCyanTeal\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueLightSteelBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBluePowderBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueLightBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueSkyBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueLightSkyBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueDeepSkyBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueDodgerBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueCornflowerBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueSteelBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueRoyalBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueMediumBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueDarkBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueNavy\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLBlueMidnightBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleLavender\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleThistle\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurplePlum\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleViolet\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleOrchid\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleFuchsia\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleMagenta\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleMediumOrchid\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleMediumPurple\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleBlueViolet\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleDarkViolet\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleDarkOrchid\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleDarkMagenta\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurplePurple\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleIndigo\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleDarkSlateBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleSlateBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLPurpleMediumSlateBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteWhite\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteSnow\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteHoneydew\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteMintCream\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteAzure\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteAliceBlue\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteGhostWhite\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteWhiteSmoke\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteSeashell\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteBeige\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteOldLace\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteFloralWhite\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteIvory\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteAntiqueWhite\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteLinen\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteLavenderBlush\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLWhiteMistyRose\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGrayGainsboro\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGrayLightGray\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGraySilver\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGrayDarkGray\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGrayGray\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGrayDimGray\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGrayLightSlateGray\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGraySlateGray\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGrayDarkSlateGray\fP"
.br
.ti -1c
.RI "QIcon \fBColorHTMLGrayBlack\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void QET::Icons::initIcons ()"
Initialise les icones de l'application QElectroTech 
.SH "Variable Documentation"
.PP 
.SS "QIcon QET::Icons::Add"

.SS "QIcon QET::Icons::AddFolio"

.SS "QIcon QET::Icons::adding_image"

.SS "QIcon QET::Icons::Allowed"

.SS "QIcon QET::Icons::ApplicationExit"

.SS "QIcon QET::Icons::ar"

.SS "QIcon QET::Icons::ArrowLeft"

.SS "QIcon QET::Icons::ArrowLeftDouble"

.SS "QIcon QET::Icons::ArrowRight"

.SS "QIcon QET::Icons::ArrowRightDouble"

.SS "QIcon QET::Icons::Autoconnect"

.SS "QIcon QET::Icons::AutoNum"

.SS "QIcon QET::Icons::be"

.SS "QIcon QET::Icons::br"

.SS "QIcon QET::Icons::BringForward"

.SS "QIcon QET::Icons::Cancel"

.SS "QIcon QET::Icons::catalonia"

.SS "QIcon QET::Icons::ColorBrown"

.SS "QIcon QET::Icons::ColorGray"

.SS "QIcon QET::Icons::ColorHTMLBlueBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueCornflowerBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueDarkBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueDeepSkyBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueDodgerBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueLightBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueLightSkyBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueLightSteelBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueMediumBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueMidnightBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueNavy"

.SS "QIcon QET::Icons::ColorHTMLBluePowderBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueRoyalBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueSkyBlue"

.SS "QIcon QET::Icons::ColorHTMLBlueSteelBlue"

.SS "QIcon QET::Icons::ColorHTMLBrownBisque"

.SS "QIcon QET::Icons::ColorHTMLBrownBlanchedAlmond"

.SS "QIcon QET::Icons::ColorHTMLBrownBrown"

.SS "QIcon QET::Icons::ColorHTMLBrownBurlywood"

.SS "QIcon QET::Icons::ColorHTMLBrownChocolate"

.SS "QIcon QET::Icons::ColorHTMLBrownCornsilk"

.SS "QIcon QET::Icons::ColorHTMLBrownDarkGoldenrod"

.SS "QIcon QET::Icons::ColorHTMLBrownGoldenrod"

.SS "QIcon QET::Icons::ColorHTMLBrownMaroon"

.SS "QIcon QET::Icons::ColorHTMLBrownNavajoWhite"

.SS "QIcon QET::Icons::ColorHTMLBrownPeru"

.SS "QIcon QET::Icons::ColorHTMLBrownRosyBrown"

.SS "QIcon QET::Icons::ColorHTMLBrownSaddleBrown"

.SS "QIcon QET::Icons::ColorHTMLBrownSandyBrown"

.SS "QIcon QET::Icons::ColorHTMLBrownSienna"

.SS "QIcon QET::Icons::ColorHTMLBrownTan"

.SS "QIcon QET::Icons::ColorHTMLBrownWheat"

.SS "QIcon QET::Icons::ColorHTMLCyanAqua"

.SS "QIcon QET::Icons::ColorHTMLCyanAquamarine"

.SS "QIcon QET::Icons::ColorHTMLCyanCadetBlue"

.SS "QIcon QET::Icons::ColorHTMLCyanCyan"

.SS "QIcon QET::Icons::ColorHTMLCyanDarkCyan"

.SS "QIcon QET::Icons::ColorHTMLCyanDarkTurquoise"

.SS "QIcon QET::Icons::ColorHTMLCyanLightCyan"

.SS "QIcon QET::Icons::ColorHTMLCyanLightSeaGreen"

.SS "QIcon QET::Icons::ColorHTMLCyanMediumTurquoise"

.SS "QIcon QET::Icons::ColorHTMLCyanPaleTurquoise"

.SS "QIcon QET::Icons::ColorHTMLCyanTeal"

.SS "QIcon QET::Icons::ColorHTMLCyanTurquoise"

.SS "QIcon QET::Icons::ColorHTMLGrayBlack"

.SS "QIcon QET::Icons::ColorHTMLGrayDarkGray"

.SS "QIcon QET::Icons::ColorHTMLGrayDarkSlateGray"

.SS "QIcon QET::Icons::ColorHTMLGrayDimGray"

.SS "QIcon QET::Icons::ColorHTMLGrayGainsboro"

.SS "QIcon QET::Icons::ColorHTMLGrayGray"

.SS "QIcon QET::Icons::ColorHTMLGrayLightGray"

.SS "QIcon QET::Icons::ColorHTMLGrayLightSlateGray"

.SS "QIcon QET::Icons::ColorHTMLGraySilver"

.SS "QIcon QET::Icons::ColorHTMLGraySlateGray"

.SS "QIcon QET::Icons::ColorHTMLGreenChartreuse"

.SS "QIcon QET::Icons::ColorHTMLGreenDarkGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenDarkOliveGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenDarkSeaGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenForestGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenGreenYellow"

.SS "QIcon QET::Icons::ColorHTMLGreenLawnGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenLightGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenLime"

.SS "QIcon QET::Icons::ColorHTMLGreenLimeGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenMediumAquamarine"

.SS "QIcon QET::Icons::ColorHTMLGreenMediumSeaGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenMediumSpringGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenOlive"

.SS "QIcon QET::Icons::ColorHTMLGreenOliveDrab"

.SS "QIcon QET::Icons::ColorHTMLGreenPaleGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenSeaGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenSpringGreen"

.SS "QIcon QET::Icons::ColorHTMLGreenYellowGreen"

.SS "QIcon QET::Icons::ColorHTMLOrangeCoral"

.SS "QIcon QET::Icons::ColorHTMLOrangeDarkOrange"

.SS "QIcon QET::Icons::ColorHTMLOrangeOrange"

.SS "QIcon QET::Icons::ColorHTMLOrangeOrangeRed"

.SS "QIcon QET::Icons::ColorHTMLOrangeTomato"

.SS "QIcon QET::Icons::ColorHTMLPinkDeepPink"

.SS "QIcon QET::Icons::ColorHTMLPinkHotPink"

.SS "QIcon QET::Icons::ColorHTMLPinkLightPink"

.SS "QIcon QET::Icons::ColorHTMLPinkMediumVioletRed"

.SS "QIcon QET::Icons::ColorHTMLPinkPaleVioletRed"

.SS "QIcon QET::Icons::ColorHTMLPinkPink"

.SS "QIcon QET::Icons::ColorHTMLPurpleBlueViolet"

.SS "QIcon QET::Icons::ColorHTMLPurpleDarkMagenta"

.SS "QIcon QET::Icons::ColorHTMLPurpleDarkOrchid"

.SS "QIcon QET::Icons::ColorHTMLPurpleDarkSlateBlue"

.SS "QIcon QET::Icons::ColorHTMLPurpleDarkViolet"

.SS "QIcon QET::Icons::ColorHTMLPurpleFuchsia"

.SS "QIcon QET::Icons::ColorHTMLPurpleIndigo"

.SS "QIcon QET::Icons::ColorHTMLPurpleLavender"

.SS "QIcon QET::Icons::ColorHTMLPurpleMagenta"

.SS "QIcon QET::Icons::ColorHTMLPurpleMediumOrchid"

.SS "QIcon QET::Icons::ColorHTMLPurpleMediumPurple"

.SS "QIcon QET::Icons::ColorHTMLPurpleMediumSlateBlue"

.SS "QIcon QET::Icons::ColorHTMLPurpleOrchid"

.SS "QIcon QET::Icons::ColorHTMLPurplePlum"

.SS "QIcon QET::Icons::ColorHTMLPurplePurple"

.SS "QIcon QET::Icons::ColorHTMLPurpleSlateBlue"

.SS "QIcon QET::Icons::ColorHTMLPurpleThistle"

.SS "QIcon QET::Icons::ColorHTMLPurpleViolet"

.SS "QIcon QET::Icons::ColorHTMLRedCrimson"

.SS "QIcon QET::Icons::ColorHTMLRedDarkRed"

.SS "QIcon QET::Icons::ColorHTMLRedDarkSalmon"

.SS "QIcon QET::Icons::ColorHTMLRedFirebrick"

.SS "QIcon QET::Icons::ColorHTMLRedIndianRed"

.SS "QIcon QET::Icons::ColorHTMLRedLightCoral"

.SS "QIcon QET::Icons::ColorHTMLRedLightSalmon"

.SS "QIcon QET::Icons::ColorHTMLRedRed"

.SS "QIcon QET::Icons::ColorHTMLRedSalmon"

.SS "QIcon QET::Icons::ColorHTMLWhiteAliceBlue"

.SS "QIcon QET::Icons::ColorHTMLWhiteAntiqueWhite"

.SS "QIcon QET::Icons::ColorHTMLWhiteAzure"

.SS "QIcon QET::Icons::ColorHTMLWhiteBeige"

.SS "QIcon QET::Icons::ColorHTMLWhiteFloralWhite"

.SS "QIcon QET::Icons::ColorHTMLWhiteGhostWhite"

.SS "QIcon QET::Icons::ColorHTMLWhiteHoneydew"

.SS "QIcon QET::Icons::ColorHTMLWhiteIvory"

.SS "QIcon QET::Icons::ColorHTMLWhiteLavenderBlush"

.SS "QIcon QET::Icons::ColorHTMLWhiteLinen"

.SS "QIcon QET::Icons::ColorHTMLWhiteMintCream"

.SS "QIcon QET::Icons::ColorHTMLWhiteMistyRose"

.SS "QIcon QET::Icons::ColorHTMLWhiteOldLace"

.SS "QIcon QET::Icons::ColorHTMLWhiteSeashell"

.SS "QIcon QET::Icons::ColorHTMLWhiteSnow"

.SS "QIcon QET::Icons::ColorHTMLWhiteWhite"

.SS "QIcon QET::Icons::ColorHTMLWhiteWhiteSmoke"

.SS "QIcon QET::Icons::ColorHTMLYellowDarkKhaki"

.SS "QIcon QET::Icons::ColorHTMLYellowGold"

.SS "QIcon QET::Icons::ColorHTMLYellowKhaki"

.SS "QIcon QET::Icons::ColorHTMLYellowLemonChiffon"

.SS "QIcon QET::Icons::ColorHTMLYellowLightGoldenrodYellow"

.SS "QIcon QET::Icons::ColorHTMLYellowLightYellow"

.SS "QIcon QET::Icons::ColorHTMLYellowMoccasin"

.SS "QIcon QET::Icons::ColorHTMLYellowPaleGoldenrod"

.SS "QIcon QET::Icons::ColorHTMLYellowPapayaWhip"

.SS "QIcon QET::Icons::ColorHTMLYellowPeachPuff"

.SS "QIcon QET::Icons::ColorHTMLYellowYellow"

.SS "QIcon QET::Icons::ColorOrange"

.SS "QIcon QET::Icons::ColorPurple"

.SS "QIcon QET::Icons::Conductor"

.SS "QIcon QET::Icons::ConductorEdit"

.SS "QIcon QET::Icons::ConductorSettings"

.SS "QIcon QET::Icons::Configure"

.SS "QIcon QET::Icons::ConfigureToolbars"

.SS "QIcon QET::Icons::cs"

.SS "QIcon QET::Icons::da"

.SS "QIcon QET::Icons::de"

.SS "QIcon QET::Icons::DefaultConductor"

.SS "QIcon QET::Icons::Diagram"

.SS "QIcon QET::Icons::DiagramAdd"

.SS "QIcon QET::Icons::DiagramBg"

.SS "QIcon QET::Icons::DiagramDelete"

.SS "QIcon QET::Icons::DialogCancel"

.SS "QIcon QET::Icons::DialogInformation"

.SS "QIcon QET::Icons::DialogOk"

.SS "QIcon QET::Icons::DocumentClose"

.SS "QIcon QET::Icons::DocumentExport"

.SS "QIcon QET::Icons::DocumentImport"

.SS "QIcon QET::Icons::DocumentNew"

.SS "QIcon QET::Icons::DocumentOpen"

.SS "QIcon QET::Icons::DocumentOpenRecent"

.SS "QIcon QET::Icons::DocumentPrint"

.SS "QIcon QET::Icons::DocumentPrintFrame"

.SS "QIcon QET::Icons::DocumentSave"

.SS "QIcon QET::Icons::DocumentSaveAll"

.SS "QIcon QET::Icons::DocumentSaveAs"

.SS "QIcon QET::Icons::DocumentSpreadsheet"

.SS "QIcon QET::Icons::East"

.SS "QIcon QET::Icons::EditClear"

.SS "QIcon QET::Icons::EditClearLocationBar"

.SS "QIcon QET::Icons::EditCopy"

.SS "QIcon QET::Icons::EditCut"

.SS "QIcon QET::Icons::EditDelete"

.SS "QIcon QET::Icons::EditPaste"

.SS "QIcon QET::Icons::EditRedo"

.SS "QIcon QET::Icons::EditRename"

.SS "QIcon QET::Icons::EditSelectAll"

.SS "QIcon QET::Icons::EditSelectInvert"

.SS "QIcon QET::Icons::EditSelectNone"

.SS "QIcon QET::Icons::EditTableCellMerge"

.SS "QIcon QET::Icons::EditTableCellSplit"

.SS "QIcon QET::Icons::EditTableDeleteColumn"

.SS "QIcon QET::Icons::EditTableDeleteRow"

.SS "QIcon QET::Icons::EditTableInsertColumnLeft"

.SS "QIcon QET::Icons::EditTableInsertColumnRight"

.SS "QIcon QET::Icons::EditTableInsertRowAbove"

.SS "QIcon QET::Icons::EditTableInsertRowUnder"

.SS "QIcon QET::Icons::EditText"

.SS "QIcon QET::Icons::EditUndo"

.SS "QIcon QET::Icons::Element"

.SS "QIcon QET::Icons::ElementDelete"

.SS "QIcon QET::Icons::ElementEdit"

.SS "QIcon QET::Icons::ElementMaster"

.SS "QIcon QET::Icons::ElementNew"

.SS "QIcon QET::Icons::ElementSlave"

.SS "QIcon QET::Icons::ElementSmall"

.SS "QIcon QET::Icons::ElementTerminal"

.SS "QIcon QET::Icons::en"

.SS "QIcon QET::Icons::EndLineCircle"

.SS "QIcon QET::Icons::EndLineDiamond"

.SS "QIcon QET::Icons::EndLineNone"

.SS "QIcon QET::Icons::EndLineSimple"

.SS "QIcon QET::Icons::EndLineTriangle"

.SS "QIcon QET::Icons::EPS"

.SS "QIcon QET::Icons::es"

.SS "QIcon QET::Icons::Folder"

.SS "QIcon QET::Icons::FolderDelete"

.SS "QIcon QET::Icons::FolderEdit"

.SS "QIcon QET::Icons::FolderNew"

.SS "QIcon QET::Icons::FolderOnlyThis"

.SS "QIcon QET::Icons::FolderOpen"

.SS "QIcon QET::Icons::FolderProperties"

.SS "QIcon QET::Icons::FolderShowAll"

.SS "QIcon QET::Icons::FolioXrefComing"

.SS "QIcon QET::Icons::Forbidden"

.SS "QIcon QET::Icons::fr"

.SS "QIcon QET::Icons::FullScreenEnter"

.SS "QIcon QET::Icons::FullScreenExit"

.SS "QIcon QET::Icons::GoBottom"

.SS "QIcon QET::Icons::GoDown"

.SS "QIcon QET::Icons::GoDownDouble"

.SS "QIcon QET::Icons::GoTop"

.SS "QIcon QET::Icons::GoUp"

.SS "QIcon QET::Icons::GoUpDouble"

.SS "QIcon QET::Icons::gr"

.SS "QIcon QET::Icons::Grid"

.SS "QIcon QET::Icons::Ground"

.SS "QIcon QET::Icons::Hide"

.SS "QIcon QET::Icons::Home"

.SS "QIcon QET::Icons::HotSpot"

.SS "QIcon QET::Icons::hr"

.SS "QIcon QET::Icons::hu"

.SS "QIcon QET::Icons::IC_CopyFile"

.SS "QIcon QET::Icons::IC_MoveFile"

.SS "QIcon QET::Icons::InsertImage"

.SS "QIcon QET::Icons::it"

.SS "QIcon QET::Icons::jp"

.SS "QIcon QET::Icons::listDrawings"

.SS "QIcon QET::Icons::Lower"

.SS "QIcon QET::Icons::Names"

.SS "QIcon QET::Icons::Neutral"

.SS "QIcon QET::Icons::NewDiagram"

.SS "QIcon QET::Icons::nl"

.SS "QIcon QET::Icons::no"

.SS "QIcon QET::Icons::North"

.SS "QIcon QET::Icons::ObjectLocked"

.SS "QIcon QET::Icons::ObjectRotateRight"

.SS "QIcon QET::Icons::ObjectUnlocked"

.SS "QIcon QET::Icons::Orientations"

.SS "QIcon QET::Icons::PartArc"

.SS "QIcon QET::Icons::PartCircle"

.SS "QIcon QET::Icons::PartEllipse"

.SS "QIcon QET::Icons::PartLine"

.SS "QIcon QET::Icons::PartPolygon"

.SS "QIcon QET::Icons::PartRectangle"

.SS "QIcon QET::Icons::PartSelect"

.SS "QIcon QET::Icons::PartText"

.SS "QIcon QET::Icons::PartTextField"

.SS "QIcon QET::Icons::PDF"

.SS "QIcon QET::Icons::Phase"

.SS "QIcon QET::Icons::pl"

.SS "QIcon QET::Icons::PrintAllPages"

.SS "QIcon QET::Icons::Printer"

.SS "QIcon QET::Icons::PrintLandscape"

.SS "QIcon QET::Icons::PrintPortrait"

.SS "QIcon QET::Icons::PrintTwoPages"

.SS "QIcon QET::Icons::Project"

.SS "QIcon QET::Icons::ProjectClose"

.SS "QIcon QET::Icons::ProjectFile"

.SS "QIcon QET::Icons::ProjectFileGP"

.SS "QIcon QET::Icons::ProjectNew"

.SS "QIcon QET::Icons::ProjectProperties"

.SS "QIcon QET::Icons::Projects"

.SS "QIcon QET::Icons::pt"

.SS "QIcon QET::Icons::QETDonate"

.SS "QIcon QET::Icons::QETDownload"

.SS "QIcon QET::Icons::QETIcon"

.SS "QIcon QET::Icons::QETLogo"

.SS "QIcon QET::Icons::QETManual"

.SS "QIcon QET::Icons::QETOxygenLogo"

.SS "QIcon QET::Icons::QETVideo"

.SS "QIcon QET::Icons::QtLogo"

.SS "QIcon QET::Icons::Raise"

.SS "QIcon QET::Icons::Remove"

.SS "QIcon QET::Icons::resize_image"

.SS "QIcon QET::Icons::Restore"

.SS "QIcon QET::Icons::ro"

.SS "QIcon QET::Icons::ru"

.SS "QIcon QET::Icons::RunDxf"

.SS "QIcon QET::Icons::SendBackward"

.SS "QIcon QET::Icons::Settings"

.SS "QIcon QET::Icons::SinglePage"

.SS "QIcon QET::Icons::sl"

.SS "QIcon QET::Icons::South"

.SS "QIcon QET::Icons::Start"

.SS "QIcon QET::Icons::sub"

.SS "QIcon QET::Icons::super"

.SS "QIcon QET::Icons::TableOfContent"

.SS "QIcon QET::Icons::Terminal"

.SS "QIcon QET::Icons::TerminalStrip"

.SS "QIcon QET::Icons::textGroup"

.SS "QIcon QET::Icons::TitleBlock"

.SS "QIcon QET::Icons::TitleBlockBottom"

.SS "QIcon QET::Icons::TitleBlockRight"

.SS "QIcon QET::Icons::tr"

.SS "QIcon QET::Icons::TransformRotate"

.SS "QIcon QET::Icons::translation"

.SS "QIcon QET::Icons::UserInformations"

.SS "QIcon QET::Icons::ViewFitWidth"

.SS "QIcon QET::Icons::ViewFitWindow"

.SS "QIcon QET::Icons::ViewMove"

.SS "QIcon QET::Icons::ViewRefresh"

.SS "QIcon QET::Icons::West"

.SS "QIcon QET::Icons::WindowNew"

.SS "QIcon QET::Icons::XmlTextFile"

.SS "QIcon QET::Icons::ZoomDraw"

.SS "QIcon QET::Icons::ZoomFitBest"

.SS "QIcon QET::Icons::ZoomIn"

.SS "QIcon QET::Icons::ZoomOriginal"

.SS "QIcon QET::Icons::ZoomOut"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
