.TH "sources/qetapp.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetapp.h
.SH SYNOPSIS
.br
.PP
\fC#include <QTranslator>\fP
.br
\fC#include <QSystemTrayIcon>\fP
.br
\fC#include <QPalette>\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include 'elementslocation\&.h'\fP
.br
\fC#include 'templatelocation\&.h'\fP
.br
\fC#include 'qetarguments\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQETApp\fP"
.br
.RI "The \fBQETApp\fP class This class represents the QElectroTech application\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQETAPP_COMMON_TBT_PROTOCOL\fP   'commontbt'"
.br
.ti -1c
.RI "#define \fBQETAPP_CUSTOM_TBT_PROTOCOL\fP   'customtbt'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QETAPP_COMMON_TBT_PROTOCOL   'commontbt'"

.SS "#define QETAPP_CUSTOM_TBT_PROTOCOL   'customtbt'"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
