.TH "sources/qetarguments.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetarguments.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetarguments\&.h'\fP
.br
\fC#include 'titleblock/templatescollection\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
