.TH "sources/qetapp.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetapp.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'configdialog\&.h'\fP
.br
\fC#include 'configpages\&.h'\fP
.br
\fC#include 'qetdiagrameditor\&.h'\fP
.br
\fC#include 'qetelementeditor\&.h'\fP
.br
\fC#include 'elementscollectioncache\&.h'\fP
.br
\fC#include 'titleblocktemplate\&.h'\fP
.br
\fC#include 'qettemplateeditor\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'qtextorientationspinboxwidget\&.h'\fP
.br
\fC#include 'recentfiles\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'templatescollection\&.h'\fP
.br
\fC#include 'generalconfigurationpage\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'projectview\&.h'\fP
.br
\fC#include 'elementpicturefactory\&.h'\fP
.br
\fC#include 'aboutqetdialog\&.h'\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <QProcessEnvironment>\fP
.br
\fC#include 'factory/elementfactory\&.h'\fP
.br
\fC#include <KAutoSaveFile>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQUOTE\fP(x)   \fBSTRINGIFY\fP(x)"
.br
.ti -1c
.RI "#define \fBSTRINGIFY\fP(x)   #x"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QUOTE(x)   \fBSTRINGIFY\fP(x)"

.SS "#define STRINGIFY(x)   #x"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
