.TH "sources/qetdiagrameditor.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetdiagrameditor.h
.SH SYNOPSIS
.br
.PP
\fC#include <QActionGroup>\fP
.br
\fC#include <QMdiArea>\fP
.br
\fC#include <QSignalMapper>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QUndoGroup>\fP
.br
\fC#include 'qetmainwindow\&.h'\fP
.br
\fC#include 'searchandreplacewidget\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQETDiagramEditor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
