.TH "sources/editor/qetelementeditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/qetelementeditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetelementeditor\&.h'\fP
.br
\fC#include 'qet\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'elementscene\&.h'\fP
.br
\fC#include 'elementview\&.h'\fP
.br
\fC#include 'customelementpart\&.h'\fP
.br
\fC#include 'newelementwizard\&.h'\fP
.br
\fC#include 'elementitemeditor\&.h'\fP
.br
\fC#include 'elementdialog\&.h'\fP
.br
\fC#include 'recentfiles\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'editorcommands\&.h'\fP
.br
\fC#include 'arceditor\&.h'\fP
.br
\fC#include 'ellipseeditor\&.h'\fP
.br
\fC#include 'lineeditor\&.h'\fP
.br
\fC#include 'polygoneditor\&.h'\fP
.br
\fC#include 'rectangleeditor\&.h'\fP
.br
\fC#include 'terminaleditor\&.h'\fP
.br
\fC#include 'texteditor\&.h'\fP
.br
\fC#include 'partterminal\&.h'\fP
.br
\fC#include 'styleeditor\&.h'\fP
.br
\fC#include 'dynamictextfieldeditor\&.h'\fP
.br
\fC#include 'eseventaddline\&.h'\fP
.br
\fC#include 'eseventaddrect\&.h'\fP
.br
\fC#include 'eseventaddellipse\&.h'\fP
.br
\fC#include 'eseventaddpolygon\&.h'\fP
.br
\fC#include 'eseventaddarc\&.h'\fP
.br
\fC#include 'eseventaddtext\&.h'\fP
.br
\fC#include 'eseventaddterminal\&.h'\fP
.br
\fC#include 'eseventadddynamictextfield\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QModelIndex>\fP
.br
\fC#include <utility>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQET_MAX_PARTS_IN_ELEMENT_EDITOR_LIST\fP   200"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QET_MAX_PARTS_IN_ELEMENT_EDITOR_LIST   200"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
