.TH "sources/qetgraphicsitem/ViewItem/qetgraphicstableitem.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/ViewItem/qetgraphicstableitem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetgraphicstableitem\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qetgraphicsheaderitem\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'qetxml\&.h'\fP
.br
\fC#include 'elementprovider\&.h'\fP
.br
\fC#include 'qetutils\&.h'\fP
.br
\fC#include 'projectdbmodel\&.h'\fP
.br
\fC#include <QAbstractItemModel>\fP
.br
\fC#include <QFontMetrics>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QGraphicsScene>\fP
.br
\fC#include <QGraphicsSceneMouseEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
