.TH "sources/qetgraphicsitem/ViewItem/qetgraphicsheaderitem.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/ViewItem/qetgraphicsheaderitem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetgraphicsheaderitem\&.h'\fP
.br
\fC#include 'qabstractitemmodel\&.h'\fP
.br
\fC#include 'qetxml\&.h'\fP
.br
\fC#include 'qetutils\&.h'\fP
.br
\fC#include <QFontMetrics>\fP
.br
\fC#include <QPainter>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
