.TH "sources/qetgraphicsitem/ViewItem/qetgraphicsheaderitem.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/ViewItem/qetgraphicsheaderitem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'qetapp\&.h'\fP
.br
\fC#include <QGraphicsObject>\fP
.br
\fC#include <QFont>\fP
.br
\fC#include <QMargins>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQetGraphicsHeaderItem\fP"
.br
.RI "The \fBQetGraphicsHeaderItem\fP class The header have a few parameters to edit her visual aspect\&. Margins, to edit the margin between the cell and the text\&. Text font\&. Text alignment in the cell These three parameters are not settable directly with the header but trough the model to be displayed by the header\&. Header search these parameters only in the section 0 for cell of header\&. By consequence, set data in other section is useless also these parameter can't be set individually for each cell\&. The margins is stored in the model in index Qt::UserRole+1 and for value a QString\&. See \fBQETUtils::marginsFromString\fP and \fBQETUtils::marginsToString\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
