.TH "sources/QetGraphicsItemModeler/qetgraphicshandleritem.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/QetGraphicsItemModeler/qetgraphicshandleritem.h
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsItem>\fP
.br
\fC#include <QPen>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQetGraphicsHandlerItem\fP"
.br
.RI "The \fBQetGraphicsHandlerItem\fP class This graphics item represents a point, destined to be used as an handler, for modifie the geometrie of a another graphics item (like shapes)\&. The graphics item to be modified, must call 'installSceneEventFilter' of this item with itself for argument,\&. The ghraphics item to be modified, need to reimplement 'sceneEventFilter' for create the modification behavior\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
