.TH "sources/factory/qetgraphicstablefactory.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/factory/qetgraphicstablefactory.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetgraphicstablefactory\&.h'\fP
.br
\fC#include 'qetgraphicstableitem\&.h'\fP
.br
\fC#include 'projectdbmodel\&.h'\fP
.br
\fC#include 'elementquerywidget\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qetgraphicsheaderitem\&.h'\fP
.br
\fC#include 'addtabledialog\&.h'\fP
.br
\fC#include 'qetutils\&.h'\fP
.br
\fC#include 'summaryquerywidget\&.h'\fP
.br
\fC#include <QDialog>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
