.TH "sources/QetGraphicsItemModeler/qetgraphicshandlerutility.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/QetGraphicsItemModeler/qetgraphicshandlerutility.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetgraphicshandlerutility\&.h'\fP
.br
\fC#include <QPainterPath>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
