.TH "sources/QetGraphicsItemModeler/qetgraphicshandleritem.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/QetGraphicsItemModeler/qetgraphicshandleritem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetgraphicshandleritem\&.h'\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <utility>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
