.TH "sources/qetinformation.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetinformation.h
.SH SYNOPSIS
.br
.PP
\fC#include <QStringList>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBQETInformation\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QStringList \fBQETInformation::titleblockInfoKeys\fP ()"
.br
.RI "\fBQETInformation::titleblockInfoKeys\fP\&. "
.ti -1c
.RI "QString \fBQETInformation::titleblockTranslatedInfoKey\fP (const QString &info)"
.br
.RI "\fBQETInformation::titleblockTranslatedInfoKey\fP\&. "
.ti -1c
.RI "QString \fBQETInformation::titleblockInfoKeysToVar\fP (const QString &info)"
.br
.RI "\fBQETInformation::titleblockInfoKeysToVar\fP\&. "
.ti -1c
.RI "QHash< QString, QString > \fBQETInformation::titleblockTranslatedKeyHashVar\fP ()"
.br
.RI "\fBQETInformation::titleblockTranslatedKeyHashVar\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
