.TH "sources/qetinformation.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetinformation.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetinformation\&.h'\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QHash>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
