.TH "sources/qetmainwindow.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetmainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QAction>\fP
.br
\fC#include <QWhatsThis>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QMenuBar>\fP
.br
\fC#include <QDragEnterEvent>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include 'qetmainwindow\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qetdiagrameditor\&.h'\fP
.br
\fC#include 'projectview\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
