.TH "sources/qetmessagebox.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetmessagebox.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMessageBox>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBQET\fP"
.br
.ti -1c
.RI " \fBQET::QetMessageBox\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QMessageBox::StandardButton \fBQET::QetMessageBox::critical\fP (QWidget *, const QString &, const QString &, QMessageBox::StandardButtons=QMessageBox::Ok, QMessageBox::StandardButton=QMessageBox::NoButton)"
.br
.ti -1c
.RI "QMessageBox::StandardButton \fBQET::QetMessageBox::information\fP (QWidget *, const QString &, const QString &, QMessageBox::StandardButtons=QMessageBox::Ok, QMessageBox::StandardButton=QMessageBox::NoButton)"
.br
.ti -1c
.RI "QMessageBox::StandardButton \fBQET::QetMessageBox::question\fP (QWidget *, const QString &, const QString &, QMessageBox::StandardButtons=QMessageBox::Ok, QMessageBox::StandardButton=QMessageBox::NoButton)"
.br
.ti -1c
.RI "QMessageBox::StandardButton \fBQET::QetMessageBox::warning\fP (QWidget *, const QString &, const QString &, QMessageBox::StandardButtons=QMessageBox::Ok, QMessageBox::StandardButton=QMessageBox::NoButton)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
