.TH "sources/qetproject.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetproject.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qetresult\&.h'\fP
.br
\fC#include 'movetemplateshandler\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'titleblocktemplate\&.h'\fP
.br
\fC#include 'ui/dialogwaiting\&.h'\fP
.br
\fC#include 'numerotationcontext\&.h'\fP
.br
\fC#include 'integrationmovetemplateshandler\&.h'\fP
.br
\fC#include 'xmlelementcollection\&.h'\fP
.br
\fC#include 'importelementdialog\&.h'\fP
.br
\fC#include 'numerotationcontextcommands\&.h'\fP
.br
\fC#include 'assignvariables\&.h'\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QStandardPaths>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <QtConcurrent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
