.TH "sources/qetproject.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetproject.h
.SH SYNOPSIS
.br
.PP
\fC#include 'nameslist\&.h'\fP
.br
\fC#include 'elementslocation\&.h'\fP
.br
\fC#include 'borderproperties\&.h'\fP
.br
\fC#include 'conductorproperties\&.h'\fP
.br
\fC#include 'titleblockproperties\&.h'\fP
.br
\fC#include 'templatescollection\&.h'\fP
.br
\fC#include 'properties/xrefproperties\&.h'\fP
.br
\fC#include 'projectdatabase\&.h'\fP
.br
\fC#include 'reportproperties\&.h'\fP
.br
\fC#include <KAutoSaveFile>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQETProject\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
