.TH "sources/qetregexpvalidator.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetregexpvalidator.h
.SH SYNOPSIS
.br
.PP
\fC#include <QRegExpValidator>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQETRegExpValidator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
