.TH "sources/qetgraphicsitem/qetshapeitem.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/qetshapeitem.h
.SH SYNOPSIS
.br
.PP
\fC#include <QPen>\fP
.br
\fC#include 'qetgraphicsitem\&.h'\fP
.br
\fC#include 'QetGraphicsItemModeler/qetgraphicshandleritem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQetShapeItem\fP"
.br
.RI "The \fBQetShapeItem\fP class this class is used to draw a basic shape (line, rectangle, ellipse) into a diagram, that can be saved to \&.qet file\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
