.TH "sources/titleblock/qettemplateeditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/qettemplateeditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qettemplateeditor\&.h'\fP
.br
\fC#include 'qetmessagebox\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'templatecellwidget\&.h'\fP
.br
\fC#include 'templatecommands\&.h'\fP
.br
\fC#include 'templateview\&.h'\fP
.br
\fC#include 'templatelocationsaver\&.h'\fP
.br
\fC#include 'templatelogomanager\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
