.TH "QETUtils" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QETUtils
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBmarginsToString\fP (const QMargins &margins)"
.br
.RI "\fBQETUtils::marginsToString\fP\&. "
.ti -1c
.RI "QMargins \fBmarginsFromString\fP (const QString &string)"
.br
.RI "\fBQETUtils::marginsFromString\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provide some small utils function 
.SH "Function Documentation"
.PP 
.SS "QMargins QETUtils::marginsFromString (const QString & string)"

.PP
\fBQETUtils::marginsFromString\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP 
.RE
.PP
\fBReturns\fP
.RS 4
QMargins margins 
.RE
.PP

.SS "QString QETUtils::marginsToString (const QMargins & margins)"

.PP
\fBQETUtils::marginsToString\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fImargins\fP 
.RE
.PP
\fBReturns\fP
.RS 4
QString str 'left;top;right;bottom' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
