.TH "sources/qfilenameedit.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qfilenameedit.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qfilenameedit\&.h'\fP
.br
\fC#include 'qetregexpvalidator\&.h'\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <QToolTip>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
