.TH "sources/QPropertyUndoCommand/qpropertyundocommand.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/QPropertyUndoCommand/qpropertyundocommand.h
.SH SYNOPSIS
.br
.PP
\fC#include <QUndoCommand>\fP
.br
\fC#include <QVariant>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQPropertyUndoCommand\fP"
.br
.RI "The \fBQPropertyUndoCommand\fP class This undo command manage QProperty of a QObject\&. This undo command can use QPropertyAnimation to animate the change when undo/redo is call To use animation call setAnimated(true)\&. By default animation is disable\&. Some QVariant date can't be animated and result this command don't work\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
