.TH "sources/QPropertyUndoCommand/qpropertyundocommand.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/QPropertyUndoCommand/qpropertyundocommand.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qpropertyundocommand\&.h'\fP
.br
\fC#include <QPropertyAnimation>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
