.TH "sources/QWidgetAnimation/qwidgetanimation.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/QWidgetAnimation/qwidgetanimation.h
.SH SYNOPSIS
.br
.PP
\fC#include <QPropertyAnimation>\fP
.br
\fC#include <QSize>\fP
.br
\fC#include <QRect>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQWidgetAnimation\fP"
.br
.RI "The \fBQWidgetAnimation\fP class This class animate the show and hide function of a QWidget\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
