.TH "sources/editor/ui/rectangleeditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/ui/rectangleeditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rectangleeditor\&.h'\fP
.br
\fC#include 'ui_rectangleeditor\&.h'\fP
.br
\fC#include 'styleeditor\&.h'\fP
.br
\fC#include 'partrectangle\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include 'elementscene\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
