.TH "sources/SearchAndReplace/ui/replacefoliowidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/SearchAndReplace/ui/replacefoliowidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'replacefoliowidget\&.h'\fP
.br
\fC#include 'ui_replacefoliowidget\&.h'\fP
.br
\fC#include 'diagramcontextwidget\&.h'\fP
.br
\fC#include 'searchandreplaceworker\&.h'\fP
.br
\fC#include <QDialogButtonBox>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSearchAndReplaceWorker\fP \fBsarw\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBSearchAndReplaceWorker\fP \fBsarw\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
