.TH "sources/SearchAndReplace/ui/replaceelementdialog.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/SearchAndReplace/ui/replaceelementdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'replaceelementdialog\&.h'\fP
.br
\fC#include 'ui_replaceelementdialog\&.h'\fP
.br
\fC#include 'elementinfopartwidget\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'searchandreplaceworker\&.h'\fP
.br
\fC#include <QAbstractButton>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
