.TH "ReportProperties" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReportProperties \- The \fBReportProperties\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reportproperties\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReportProperties\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBdefaultProperties\fP ()"
.br
.RI "\fBReportProperties::defaultProperties\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBReportProperties\fP class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ReportProperties::ReportProperties ()"

.SH "Member Function Documentation"
.PP 
.SS "QString ReportProperties::defaultProperties ()\fC [static]\fP"

.PP
\fBReportProperties::defaultProperties\fP\&. 
.PP
\fBReturns\fP
.RS 4
the default properties stored in the setting file 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
