.TH "sources/richtext/richtexteditor_p.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/richtext/richtexteditor_p.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QTextEdit>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBqdesigner_internal::RichTextEditorDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBqdesigner_internal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
