.TH "sources/richtext/richtexteditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/richtext/richtexteditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'richtexteditor_p\&.h'\fP
.br
\fC#include 'ui_addlinkdialog\&.h'\fP
.br
\fC#include <QtCore/QList>\fP
.br
\fC#include <QtCore/QMap>\fP
.br
\fC#include <QtCore/QPointer>\fP
.br
\fC#include <QtCore/QXmlStreamReader>\fP
.br
\fC#include <QtCore/QXmlStreamWriter>\fP
.br
\fC#include <QtCore/QXmlStreamAttributes>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QColorDialog>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QtGui/QFontDatabase>\fP
.br
\fC#include <QtGui/QTextCursor>\fP
.br
\fC#include <QtGui/QPainter>\fP
.br
\fC#include <QtGui/QIcon>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QtGui/QMoveEvent>\fP
.br
\fC#include <QTabWidget>\fP
.br
\fC#include <QtGui/QTextDocument>\fP
.br
\fC#include <QtGui/QTextBlock>\fP
.br
\fC#include <QToolBar>\fP
.br
\fC#include <QToolButton>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QDialogButtonBox>\fP
.br
\fC#include 'richtexteditor\&.moc'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBqdesigner_internal::RichTextEditor\fP"
.br
.ti -1c
.RI "class \fBqdesigner_internal::AddLinkDialog\fP"
.br
.ti -1c
.RI "class \fBqdesigner_internal::HtmlTextEdit\fP"
.br
.ti -1c
.RI "class \fBqdesigner_internal::ColorAction\fP"
.br
.ti -1c
.RI "class \fBqdesigner_internal::RichTextEditorToolBar\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBqdesigner_internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBqdesigner_internal::simplifyRichTextFilter\fP (const QString &in, bool *isPlainTextPtr=nullptr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
