.TH "sources/undocommand/rotateselectioncommand.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/undocommand/rotateselectioncommand.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rotateselectioncommand\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'conductortextitem\&.h'\fP
.br
\fC#include 'independenttextitem\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include 'elementtextitemgroup\&.h'\fP
.br
\fC#include 'diagramimageitem\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'conductor\&.h'\fP
.br
\fC#include 'qet\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include <QGraphicsItem>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
