.TH "sources/SearchAndReplace/ui/searchandreplacewidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/SearchAndReplace/ui/searchandreplacewidget.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QTreeWidgetItemIterator>\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'independenttextitem\&.h'\fP
.br
\fC#include 'searchandreplaceworker\&.h'\fP
.br
\fC#include 'QWidgetAnimation/qwidgetanimation\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSearchAndReplaceWidget\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
