.TH "sources/SearchAndReplace/ui/searchandreplacewidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/SearchAndReplace/ui/searchandreplacewidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'searchandreplacewidget\&.h'\fP
.br
\fC#include 'ui_searchandreplacewidget\&.h'\fP
.br
\fC#include 'qetdiagrameditor\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'independenttextitem\&.h'\fP
.br
\fC#include 'conductor\&.h'\fP
.br
\fC#include 'replacefoliowidget\&.h'\fP
.br
\fC#include 'replaceelementdialog\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'replaceconductordialog\&.h'\fP
.br
\fC#include 'replaceadvanceddialog\&.h'\fP
.br
\fC#include 'dynamicelementtextitem\&.h'\fP
.br
\fC#include 'elementtextitemgroup\&.h'\fP
.br
\fC#include 'QWidgetAnimation/qwidgetanimation\&.h'\fP
.br
\fC#include <QSettings>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
