.TH "sources/SearchAndReplace/searchandreplaceworker.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/SearchAndReplace/searchandreplaceworker.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDate>\fP
.br
\fC#include 'titleblockproperties\&.h'\fP
.br
\fC#include 'conductorproperties\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBadvancedReplaceStruct\fP"
.br
.ti -1c
.RI "class \fBSearchAndReplaceWorker\fP"
.br
.RI "The \fBSearchAndReplaceWorker\fP class This class is the worker use to change properties when use the search and replace function of \fBQET\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
