.TH "sources/SearchAndReplace/searchandreplaceworker.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/SearchAndReplace/searchandreplaceworker.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'searchandreplaceworker\&.h'\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'changetitleblockcommand\&.h'\fP
.br
\fC#include 'changeelementinformationcommand\&.h'\fP
.br
\fC#include 'element\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'independenttextitem\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
