.TH "sources/qetgraphicsitem/simpleelement.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/simpleelement.h
.SH SYNOPSIS
.br
.PP
\fC#include 'element\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleElement\fP"
.br
.RI "The \fBSimpleElement\fP class this class represente a simple element with no specific attribute\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
