.TH "sources/titleblock/templatecellwidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/templatecellwidget.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets>\fP
.br
\fC#include 'qet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTitleBlockTemplateCellWidget\fP"
.br
.RI "The \fBTitleBlockTemplateCellWidget\fP class This class implements an edition widget for cells that compose a title block template\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
