.TH "sources/titleblock/templatelocationsaver.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/templatelocationsaver.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'templatelocationsaver\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'templatescollection\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
