.TH "sources/titleblock/templateview.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/templateview.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'templateview\&.h'\fP
.br
\fC#include 'templatevisualcell\&.h'\fP
.br
\fC#include 'gridlayoutanimation\&.h'\fP
.br
\fC#include 'helpercell\&.h'\fP
.br
\fC#include 'splittedhelpercell\&.h'\fP
.br
\fC#include 'templatecommands\&.h'\fP
.br
\fC#include 'templatecellsset\&.h'\fP
.br
\fC#include 'dimensionwidget\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROW_OFFSET\fP   2"
.br
.ti -1c
.RI "#define \fBCOL_OFFSET\fP   1"
.br
.ti -1c
.RI "#define \fBDEFAULT_PREVIEW_WIDTH\fP   600"
.br
.ti -1c
.RI "#define \fBDEFAULT_PREVIEW_HELPER_CELL_HEIGHT\fP   15"
.br
.ti -1c
.RI "#define \fBDEFAULT_COLS_HELPER_CELLS_HEIGHT\fP   15"
.br
.ti -1c
.RI "#define \fBDEFAULT_ROWS_HELPER_CELLS_WIDTH\fP   50"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COL_OFFSET   1"

.SS "#define DEFAULT_COLS_HELPER_CELLS_HEIGHT   15"

.SS "#define DEFAULT_PREVIEW_HELPER_CELL_HEIGHT   15"

.SS "#define DEFAULT_PREVIEW_WIDTH   600"

.SS "#define DEFAULT_ROWS_HELPER_CELLS_WIDTH   50"

.SS "#define ROW_OFFSET   2"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
