.TH "sources/titleblock/templatecommands.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/templatecommands.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore>\fP
.br
\fC#include <QUndoCommand>\fP
.br
\fC#include 'dimension\&.h'\fP
.br
\fC#include 'templatecellsset\&.h'\fP
.br
\fC#include 'titleblockcell\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModifyTitleBlockCellCommand\fP"
.br
.ti -1c
.RI "class \fBTitleBlockTemplateCommand\fP"
.br
.ti -1c
.RI "class \fBModifyTemplateGridCommand\fP"
.br
.ti -1c
.RI "class \fBModifyTemplateDimension\fP"
.br
.ti -1c
.RI "class \fBMergeCellsCommand\fP"
.br
.ti -1c
.RI "class \fBSplitCellsCommand\fP"
.br
.ti -1c
.RI "class \fBChangeTemplateInformationsCommand\fP"
.br
.ti -1c
.RI "class \fBCutTemplateCellsCommand\fP"
.br
.ti -1c
.RI "class \fBPasteTemplateCellsCommand\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMODIFY_TITLE_BLOCK_CELL_COMMAND_ID\fP   6378"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MODIFY_TITLE_BLOCK_CELL_COMMAND_ID   6378"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
