.TH "sources/titleblock/templatecellsset.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/templatecellsset.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QMultiMap>\fP
.br
\fC#include 'templatecellsset\&.h'\fP
.br
\fC#include 'templatevisualcell\&.h'\fP
.br
\fC#include 'templateview\&.h'\fP
.br
\fC#include 'titleblockcell\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
