.TH "sources/titleblock/templatelogomanager.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/templatelogomanager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'templatelogomanager\&.h'\fP
.br
\fC#include 'titleblocktemplate\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include <QStandardPaths>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
