.TH "sources/titleblock/templatescollection.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/templatescollection.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore>\fP
.br
\fC#include <QtXml>\fP
.br
\fC#include 'templatelocation\&.h'\fP
.br
\fC#include 'qet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTitleBlockTemplatesCollection\fP"
.br
.ti -1c
.RI "class \fBTitleBlockTemplatesProjectCollection\fP"
.br
.ti -1c
.RI "class \fBTitleBlockTemplatesFilesCollection\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTITLEBLOCKS_FILE_EXTENSION\fP   '\&.titleblock'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TITLEBLOCKS_FILE_EXTENSION   '\&.titleblock'"

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
