.TH "sources/titleblock/templatecellwidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblock/templatecellwidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'templatecellwidget\&.h'\fP
.br
\fC#include 'titleblockcell\&.h'\fP
.br
\fC#include 'nameslist\&.h'\fP
.br
\fC#include 'titleblocktemplate\&.h'\fP
.br
\fC#include 'templatecommands\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'namelistdialog\&.h'\fP
.br
\fC#include 'namelistwidget\&.h'\fP
.br
\fC#include 'qetinformation\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
