.TH "TenNum" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TenNum
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <numerotationcontextcommands\&.h>\fP
.PP
Inherits \fBNumStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTenNum\fP (\fBDiagram\fP *)"
.br
.ti -1c
.RI "QString \fBtoRepresentedString\fP (const QString) const override"
.br
.RI "\fBTenNum::toRepresentedString\fP\&. "
.ti -1c
.RI "\fBNumerotationContext\fP \fBnext\fP (const \fBNumerotationContext\fP &, const int) const override"
.br
.RI "\fBTenNum::next\fP\&. "
.ti -1c
.RI "\fBNumerotationContext\fP \fBprevious\fP (const \fBNumerotationContext\fP &, const int) const override"
.br
.RI "\fBTenNum::previous\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TenNum::TenNum (\fBDiagram\fP * d)"
Constructor 
.SH "Member Function Documentation"
.PP 
.SS "\fBNumerotationContext\fP TenNum::next (const \fBNumerotationContext\fP & nc, const int i) const\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBTenNum::next\fP\&. 
.PP
\fBReturns\fP
.RS 4
the next \fBNumerotationContext\fP nc at position i 
.RE
.PP

.PP
Implements \fBNumStrategy\fP\&.
.SS "\fBNumerotationContext\fP TenNum::previous (const \fBNumerotationContext\fP & nc, const int i) const\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBTenNum::previous\fP\&. 
.PP
\fBReturns\fP
.RS 4
the previous \fBNumerotationContext\fP nc at posiiton i 
.RE
.PP

.PP
Implements \fBNumStrategy\fP\&.
.SS "QString TenNum::toRepresentedString (const QString num) const\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBTenNum::toRepresentedString\fP\&. 
.PP
\fBReturns\fP
.RS 4
the represented string of num 
.RE
.PP

.PP
Implements \fBNumStrategy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
