.TH "sources/properties/terminaldata.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/properties/terminaldata.h
.SH SYNOPSIS
.br
.PP
\fC#include 'propertiesinterface\&.h'\fP
.br
\fC#include 'qet\&.h'\fP
.br
\fC#include <QUuid>\fP
.br
\fC#include <QPointF>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerminalData\fP"
.br
.RI "The \fBTerminalData\fP class Data of the terminal\&. Stored in extra class so it can be used by \fBPartTerminal\fP and \fBTerminal\fP without defining everything again\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
