.TH "sources/editor/terminaleditor.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/terminaleditor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'terminaleditor\&.h'\fP
.br
\fC#include 'partterminal\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'QPropertyUndoCommand/qpropertyundocommand\&.h'\fP
.br
\fC#include <QDoubleSpinBox>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QLabel>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
