.TH "sources/qetgraphicsitem/terminal.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/qetgraphicsitem/terminal.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'terminal\&.h'\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'diagram\&.h'\fP
.br
\fC#include 'qetgraphicsitem/element\&.h'\fP
.br
\fC#include 'qetgraphicsitem/conductor\&.h'\fP
.br
\fC#include 'diagramcommands\&.h'\fP
.br
\fC#include 'conductorautonumerotation\&.h'\fP
.br
\fC#include 'conductortextitem\&.h'\fP
.br
\fC#include 'terminaldata\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QList< \fBTerminal\fP * > \fBrelatedPotentialTerminal\fP (const \fBTerminal\fP *terminal, const bool all_diagram)"
.br
.RI "Conductor::relatedPotentialTerminal Return terminal at the same potential from the same parent element of terminal\&. For folio report, return the terminal of linked other report\&. For \fBTerminal\fP element, return the other terminal of terminal element\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "QList<\fBTerminal\fP *> relatedPotentialTerminal (const \fBTerminal\fP * terminal, const bool all_diagram)"

.PP
Conductor::relatedPotentialTerminal Return terminal at the same potential from the same parent element of terminal\&. For folio report, return the terminal of linked other report\&. For \fBTerminal\fP element, return the other terminal of terminal element\&. 
.PP
\fBParameters\fP
.RS 4
\fIterminal\fP : to start search 
.br
\fIall_diagram\fP :if true return all related terminal, false return only terminal in the same diagram of t 
.RE
.PP
\fBReturns\fP
.RS 4
the list of terminal at the same potential 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
