.TH "sources/editor/ui/texteditor.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/editor/ui/texteditor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'elementitemeditor\&.h'\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QPointer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTextEditor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
