.TH "sources/titleblocktemplate.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblocktemplate.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'titleblocktemplate\&.h'\fP
.br
\fC#include 'qet\&.h'\fP
.br
\fC#include 'qetapp\&.h'\fP
.br
\fC#include 'nameslist\&.h'\fP
.br
\fC#include 'createdxf\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
