.TH "sources/titleblocktemplate.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblocktemplate.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtXml>\fP
.br
\fC#include <QtSvg>\fP
.br
\fC#include 'diagramcontext\&.h'\fP
.br
\fC#include 'titleblockcell\&.h'\fP
.br
\fC#include 'dimension\&.h'\fP
.br
\fC#include 'qet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTitleBlockTemplate\fP"
.br
.RI "The \fBTitleBlockTemplate\fP class This class represents an title block template for an electric diagram\&. It can read from an XML document the layout of the table that graphically represents the title block, and can produce a graphical rendering of it from a diagram context (object embedding the informations of the diagram we want to represent the title block\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
