.TH "sources/titleblocktemplaterenderer.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/titleblocktemplaterenderer.h
.SH SYNOPSIS
.br
.PP
\fC#include <QPicture>\fP
.br
\fC#include 'diagramcontext\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTitleBlockTemplateRenderer\fP"
.br
.RI "The \fBTitleBlockTemplateRenderer\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
