.TH "todo" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBDiagramPrintDialog::acceptPrintTypeDialog\fP ()\fP" 1c
  
.IP "\fBMember \fBQET::stringToFileName\fP (const QString &)\fP" 1c
virer les caracteres accentues ?  
.IP "\fBMember \fBQETDiagramEditor::activateDiagram\fP (\fBDiagram\fP *)\fP" 1c
gerer ce cas  
.IP "\fBMember \fBRecentFiles::~RecentFiles\fP () override\fP" 1c
determiner s'il faut detruire ou non le menu 
.PP

