.TH "Ui" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddLinkDialog\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represent a single part num widget\&. By this widget, we can define and edit how the num auto must work \&. This widget is called by selectautonumw\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
