.TH "sources/richtext/ui_addlinkdialog.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/richtext/ui_addlinkdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QButtonGroup>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QDialogButtonBox>\fP
.br
\fC#include <QFormLayout>\fP
.br
\fC#include <QFrame>\fP
.br
\fC#include <QHeaderView>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QSpacerItem>\fP
.br
\fC#include <QVBoxLayout>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_AddLinkDialog\fP"
.br
.ti -1c
.RI "class \fBUi::AddLinkDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
