.TH "sources/ElementsCollection/xmlprojectelementcollectionitem.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/xmlprojectelementcollectionitem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'elementcollectionitem\&.h'\fP
.br
\fC#include <QDomElement>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXmlProjectElementCollectionItem\fP"
.br
.RI "The \fBXmlProjectElementCollectionItem\fP class This class specialise \fBElementCollectionItem\fP for manage an xml collection embedded in a project\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
