.TH "sources/ElementsCollection/xmlprojectelementcollectionitem.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ElementsCollection/xmlprojectelementcollectionitem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qetproject\&.h'\fP
.br
\fC#include 'xmlelementcollection\&.h'\fP
.br
\fC#include 'qeticons\&.h'\fP
.br
\fC#include 'xmlprojectelementcollectionitem\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
