.TH "sources/properties/xrefproperties.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/properties/xrefproperties.h
.SH SYNOPSIS
.br
.PP
\fC#include 'propertiesinterface\&.h'\fP
.br
\fC#include <QStringList>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXRefProperties\fP"
.br
.RI "The \fBXRefProperties\fP class this class store properties used by XrefItem\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
