.TH "sources/ui/xrefpropertieswidget.cpp" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/xrefpropertieswidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'xrefpropertieswidget\&.h'\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'ui_xrefpropertieswidget\&.h'\fP
.br
\fC#include 'qdebug\&.h'\fP
.br
\fC#include <QMetaEnum>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
