.TH "sources/ui/xrefpropertieswidget.h" 3 "Thu Aug 27 2020" "Version 0.8-dev" "QElectroTech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ui/xrefpropertieswidget.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include 'properties/xrefproperties\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXRefPropertiesWidget\fP"
.br
.RI "The \fBXRefPropertiesWidget\fP class This class provide a widget to edit the \fBXRefProperties\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QElectroTech from the source code\&.
