QElectroTech: autonum::AssignVariables Class Reference
autonum::AssignVariables Class Reference
The AssignVariables class This class assign variable of a formula string. Return the final string used to be displayed from a formula string.
#include <assignvariables.h>
Static Public Member Functions
static QString formulaToLabel (QString formula, sequentialNumbers &seqStruct, Diagram *diagram, const Element *elmt=nullptr)
AssignVariables::formulaToLabel Return the formula with variable assigned (ready to be displayed)
static QString replaceVariable (const QString &formula, const DiagramContext &dc)
AssignVariables::replaceVariable Replace the variables in formula in form %{my-var} to the corresponding value stored in dc.
Private Member Functions
AssignVariables (const QString &formula, const sequentialNumbers &seqStruct, Diagram *diagram, const Element *elmt=nullptr)
void assignTitleBlockVar ()
void assignProjectVar ()
void assignSequence ()
Private Attributes
Diagram * m_diagram = nullptr
QString m_arg_formula
QString m_assigned_label
sequentialNumbers m_seq_struct
const Element * m_element = nullptr
Detailed Description
The AssignVariables class This class assign variable of a formula string. Return the final string used to be displayed from a formula string.
Definition at line 62 of file assignvariables.h.
Constructor & Destructor Documentation
AssignVariables()
autonum::AssignVariables::AssignVariables (const QString & formula, const sequentialNumbers & seqStruct, Diagram * diagram, const Element * elmt = nullptr) private
Definition at line 235 of file assignvariables.cpp.
References assignProjectVar(), assignSequence(), assignTitleBlockVar(), Diagram::convertPosition(), Element::getPrefix(), DiagramPosition::letter(), m_assigned_label, m_diagram, m_element, and DiagramPosition::number().
Member Function Documentation
assignProjectVar()
void autonum::AssignVariables::assignProjectVar () private
Definition at line 306 of file assignvariables.cpp.
References DiagramContext::keys(), m_assigned_label, m_diagram, Diagram::project(), and QETProject::projectProperties().
Referenced by AssignVariables().
assignSequence()
void autonum::AssignVariables::assignSequence () private
Definition at line 320 of file assignvariables.cpp.
References autonum::sequentialNumbers::hundred, autonum::sequentialNumbers::hundred_folio, m_assigned_label, m_seq_struct, autonum::sequentialNumbers::ten, autonum::sequentialNumbers::ten_folio, autonum::sequentialNumbers::unit, and autonum::sequentialNumbers::unit_folio.
Referenced by AssignVariables().
assignTitleBlockVar()
void autonum::AssignVariables::assignTitleBlockVar () private
Definition at line 292 of file assignvariables.cpp.
References BorderTitleBlock::additionalFields(), Diagram::border_and_titleblock, DiagramContext::keys(), m_assigned_label, and m_diagram.
Referenced by AssignVariables().
formulaToLabel()
QString autonum::AssignVariables::formulaToLabel (QString formula, sequentialNumbers & seqStruct, Diagram * diagram, const Element * elmt = nullptr) static
AssignVariables::formulaToLabel Return the formula with variable assigned (ready to be displayed)
Parameters
formula - the formula to work
seqStruct - struct where is stocked int values (struct is passed as a reference and modified by this static method)
diagram - the diagram where occure the formula.
elmt - parent element (if any) of the formula
Returns
the string with variable assigned.
Definition at line 187 of file assignvariables.cpp.
References m_assigned_label, and m_seq_struct.
Referenced by Element::actualLabel(), CrossRefItem::AddExtraInfo(), LinkSingleElementWidget::buildTree(), CrossRefItem::elementPositionText(), ConductorAutoNumerotation::numerateNewConductor(), Conductor::refreshText(), DynamicElementTextItem::reportReplacedCompositeText(), Conductor::setProperties(), DynamicElementTextItem::updateReportText(), ProjectView::updateTabTitle(), MasterPropertiesWidget::updateUi(), DynamicElementTextItem::updateXref(), and ElementTextItemGroup::updateXref().
replaceVariable()
QString autonum::AssignVariables::replaceVariable (const QString & formula, const DiagramContext & dc) static
AssignVariables::replaceVariable Replace the variables in formula in form %{my-var} to the corresponding value stored in dc.
Parameters
formula
dc
Returns
Definition at line 208 of file assignvariables.cpp.
References DiagramContext::value().
Referenced by PartDynamicTextField::elementInfoChanged(), DynamicElementTextItem::elementInfoChanged(), DynamicElementTextModel::itemDataChanged(), DynamicElementTextModel::itemsForText(), PartDynamicTextField::setCompositeText(), DynamicElementTextItem::setCompositeText(), DynamicTextItemDelegate::setModelData(), DynamicElementTextItem::setTextFrom(), and DynamicElementTextItem::updateLabel().
Member Data Documentation
m_arg_formula
QString autonum::AssignVariables::m_arg_formula private
Definition at line 75 of file assignvariables.h.
m_assigned_label
QString autonum::AssignVariables::m_assigned_label private
Definition at line 76 of file assignvariables.h.
Referenced by assignProjectVar(), assignSequence(), assignTitleBlockVar(), AssignVariables(), and formulaToLabel().
m_diagram
Diagram* autonum::AssignVariables::m_diagram = nullptr private
Definition at line 74 of file assignvariables.h.
Referenced by assignProjectVar(), assignTitleBlockVar(), and AssignVariables().
m_element
const Element* autonum::AssignVariables::m_element = nullptr private
Definition at line 78 of file assignvariables.h.
Referenced by AssignVariables().
m_seq_struct
sequentialNumbers autonum::AssignVariables::m_seq_struct private
Definition at line 77 of file assignvariables.h.
Referenced by assignSequence(), and formulaToLabel().
The documentation for this class was generated from the following files:
assignvariables.h
assignvariables.cpp