QElectroTech: ChangeZValueCommand Class Reference
ChangeZValueCommand Class Reference
#include <editorcommands.h>
Public Member Functions
ChangeZValueCommand (ElementScene *, QET::DepthOption, QUndoCommand *=nullptr)
~ChangeZValueCommand () override
Destructeur.
void undo () override
Annule les changements de zValue.
void redo () override
Refait les changements de zValue.
Public Member Functions inherited from ElementEditionCommand
ElementEditionCommand (ElementScene *=nullptr, ElementView *=nullptr, QUndoCommand *=nullptr)
ElementEditionCommand::ElementEditionCommand Constructs an ElementEditionCommand, thus embedding the provided scene and view.
ElementEditionCommand (const QString &, ElementScene *=nullptr, ElementView *=nullptr, QUndoCommand *=nullptr)
ElementEditionCommand::ElementEditionCommand Constructs an ElementEditionCommand, thus embedding the provided scene and view.
~ElementEditionCommand () override
ElementScene * elementScene () const
void setElementScene (ElementScene *)
ElementView * elementView () const
void setElementView (ElementView *)
Private Member Functions
ChangeZValueCommand (const ChangeZValueCommand &)
void applyBringForward (const QList< QGraphicsItem * > &)
void applyRaise (const QList< QGraphicsItem * > &)
void applyLower (const QList< QGraphicsItem * > &)
void applySendBackward (const QList< QGraphicsItem * > &)
Private Attributes
QHash< QGraphicsItem *, qreal > undo_hash
associates impacted primitives with their former zValues
QHash< QGraphicsItem *, qreal > redo_hash
associates impacted primitives with their new zValues
QET::DepthOption m_option
kind of treatment to apply
Additional Inherited Members
Protected Attributes inherited from ElementEditionCommand
ElementScene * m_scene
Element editor/view/scene the command should take place on.
ElementView * m_view
Detailed Description
This command changes the zValue of a set of primitives when editing an electrical element.
Definition at line 174 of file editorcommands.h.
Constructor & Destructor Documentation
ChangeZValueCommand() [1/2]
ChangeZValueCommand::ChangeZValueCommand (ElementScene * elmt, QET::DepthOption o, QUndoCommand * parent = nullptr)
Constructeur
Parameters
elmt ElementScene concernee
o Option decrivant le type de traitement applique aux zValues des parties de l'element
parent QUndoCommand parent
Definition at line 284 of file editorcommands.cpp.
References applyBringForward(), applyLower(), applyRaise(), applySendBackward(), QET::BringForward, QET::Lower, m_option, ElementEditionCommand::m_scene, QET::Raise, ElementScene::SelectedOrNot, QET::SendBackward, ElementScene::SortByZValue, QET::Icons::tr, and undo_hash.
~ChangeZValueCommand()
ChangeZValueCommand::~ChangeZValueCommand () override
Destructeur.
Definition at line 315 of file editorcommands.cpp.
ChangeZValueCommand() [2/2]
ChangeZValueCommand::ChangeZValueCommand (const ChangeZValueCommand &) private
Member Function Documentation
applyBringForward()
void ChangeZValueCommand::applyBringForward (const QList< QGraphicsItem * > & items_list) private
Amene les elements selectionnes au premier plan
Parameters
items_list Liste des elements (selectionnes et non selectionnes)
Definition at line 332 of file editorcommands.cpp.
References redo_hash.
Referenced by ChangeZValueCommand().
applyLower()
void ChangeZValueCommand::applyLower (const QList< QGraphicsItem * > & items_list) private
Descend les elements selectionnes d'un plan
Parameters
items_list Liste des elements (selectionnes et non selectionnes)
Definition at line 373 of file editorcommands.cpp.
References redo_hash.
Referenced by ChangeZValueCommand().
applyRaise()
void ChangeZValueCommand::applyRaise (const QList< QGraphicsItem * > & items_list) private
Remonte les elements selectionnes d'un plan
Parameters
items_list Liste des elements (selectionnes et non selectionnes)
Definition at line 350 of file editorcommands.cpp.
References redo_hash.
Referenced by ChangeZValueCommand().
applySendBackward()
void ChangeZValueCommand::applySendBackward (const QList< QGraphicsItem * > & items_list) private
Envoie les elements selectionnes au fond
Parameters
items_list Liste des elements (selectionnes et non selectionnes)
Definition at line 397 of file editorcommands.cpp.
References redo_hash.
Referenced by ChangeZValueCommand().
redo()
void ChangeZValueCommand::redo () override
Refait les changements de zValue.
Definition at line 324 of file editorcommands.cpp.
References redo_hash.
undo()
void ChangeZValueCommand::undo () override
Annule les changements de zValue.
Definition at line 319 of file editorcommands.cpp.
References undo_hash.
Member Data Documentation
m_option
QET::DepthOption ChangeZValueCommand::m_option private
kind of treatment to apply
Definition at line 201 of file editorcommands.h.
Referenced by ChangeZValueCommand().
redo_hash
QHash<QGraphicsItem *, qreal> ChangeZValueCommand::redo_hash private
associates impacted primitives with their new zValues
Definition at line 199 of file editorcommands.h.
Referenced by applyBringForward(), applyLower(), applyRaise(), applySendBackward(), and redo().
undo_hash
QHash<QGraphicsItem *, qreal> ChangeZValueCommand::undo_hash private
associates impacted primitives with their former zValues
Definition at line 197 of file editorcommands.h.
Referenced by ChangeZValueCommand(), and undo().
The documentation for this class was generated from the following files:
editorcommands.h
editorcommands.cpp