QElectroTech: ElementTextItemGroup Class Reference
ElementTextItemGroup Class Reference
The ElementTextItemGroup class This class represent a group of element text Texts in the group can be aligned left / center /right.
#include <elementtextitemgroup.h>
Signals
void rotationChanged (qreal)
void verticalAdjustmentChanged (int)
void alignmentChanged (Qt::Alignment)
void nameChanged (QString)
void holdToBottomPageChanged (bool)
void xChanged ()
void yChanged ()
void frameChanged (bool frame)
Public Member Functions
ElementTextItemGroup (const QString &name, Element *parent)
ElementTextItemGroup::ElementTextItemGroup.
~ElementTextItemGroup () override
void addToGroup (QGraphicsItem *item)
ElementTextItemGroup::addToGroup.
void removeFromGroup (QGraphicsItem *item)
ElementTextItemGroup::removeFromGroup.
void blockAlignmentUpdate (bool block)
ElementTextItemGroup::blockAlignmentUpdate If true, the texts in this group are never aligned, moved, rotated etc... the texts stay as it was, until blockAlignmentUpdate is set to false.
void setAlignment (Qt::Alignment alignement)
ElementTextItemGroup::setAlignement Set the alignement of this group.
Qt::Alignment alignment () const
void updateAlignment ()
ElementTextItemGroup::setAlignment Update the alignement of the items in this group, according to the current alignement.
int verticalAdjustment () const
void setVerticalAdjustment (int v)
ElementTextItemGroup::setVerticalAdjustment Set the value of the vertical adjustment to v. The vertical adjutment is use to adjust the space between the texts of this group.
void setName (QString name)
ElementTextItemGroup::setName.
QString name () const
void setHoldToBottomPage (bool hold)
bool holdToBottomPage () const
void setFrame (const bool frame)
bool frame () const
QList< DynamicElementTextItem * > texts () const
ElementTextItemGroup::texts.
Diagram * diagram () const
ElementTextItemGroup::diagram.
Element * parentElement () const
ElementTextItemGroup::parentElement.
QDomElement toXml (QDomDocument &dom_document) const
ElementTextItemGroup::toXml Export data of this group to xml.
void fromXml (QDomElement &dom_element)
ElementTextItemGroup::fromXml Import data of this group from xml.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
ElementTextItemGroup::paint.
QRectF boundingRect () const override
ElementTextItemGroup::boundingRect.
void setRotation (qreal angle)
void setPos (const QPointF &pos)
void setPos (qreal x, qreal y)
Static Public Member Functions
static QString xmlTaggName ()
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
ElementTextItemGroup::mousePressEvent.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
ElementTextItemGroup::mouseMoveEvent.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
ElementTextItemGroup::mouseReleaseEvent.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
void keyPressEvent (QKeyEvent *event) override
ElementTextItemGroup::keyPressEvent.
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
Properties
QPointF pos
qreal rotation
int verticalAdjustment
Qt::Alignment alignment
QString name
bool holdToBottomPage
bool frame
Private Member Functions
void updateXref ()
void adjustSlaveXrefPos ()
void autoPos ()
Private Attributes
Qt::Alignment m_alignment = Qt::AlignJustify
QString m_name
bool m_first_move = true
bool m_hold_to_bottom_of_page = false
bool m_block_alignment_update = false
bool m_frame = false
QPointF m_initial_position
int m_vertical_adjustment = 0
CrossRefItem * m_Xref_item = nullptr
Element * m_parent_element = nullptr
QList< QMetaObject::Connection > m_update_slave_Xref_connection
QGraphicsTextItem * m_slave_Xref_item = nullptr
QMetaObject::Connection m_XrefChanged_timer
QMetaObject::Connection m_linked_changed_timer
Detailed Description
The ElementTextItemGroup class This class represent a group of element text Texts in the group can be aligned left / center /right.
Definition at line 35 of file elementtextitemgroup.h.
Constructor & Destructor Documentation
ElementTextItemGroup()
ElementTextItemGroup::ElementTextItemGroup (const QString & name, Element * parent)
ElementTextItemGroup::ElementTextItemGroup.
Parameters
name :
parent :
Definition at line 49 of file elementtextitemgroup.cpp.
References Element::linkedElementChanged(), and updateXref().
~ElementTextItemGroup()
ElementTextItemGroup::~ElementTextItemGroup () override
Definition at line 63 of file elementtextitemgroup.cpp.
Member Function Documentation
addToGroup()
void ElementTextItemGroup::addToGroup (QGraphicsItem * item)
ElementTextItemGroup::addToGroup.
Parameters
item
Definition at line 70 of file elementtextitemgroup.cpp.
References DynamicElementTextItem::compositeTextChanged(), DiagramTextItem::fontChanged(), DynamicElementTextItem::infoNameChanged(), m_block_alignment_update, DynamicElementTextItem::plainTextChanged(), rotation, DynamicElementTextItem::textChanged(), DynamicElementTextItem::textFromChanged(), DynamicElementTextItem::textWidthChanged(), DynamicElementTextItem::Type, updateAlignment(), and updateXref().
Referenced by Element::addTextToGroup().
adjustSlaveXrefPos()
void ElementTextItemGroup::adjustSlaveXrefPos () private
Definition at line 779 of file elementtextitemgroup.cpp.
References boundingRect(), m_slave_Xref_item, and pos.
Referenced by updateAlignment(), and updateXref().
alignment()
Qt::Alignment ElementTextItemGroup::alignment () const
Definition at line 151 of file elementtextitemgroup.cpp.
References m_alignment.
alignmentChanged
void ElementTextItemGroup::alignmentChanged (Qt::Alignment) signal
Referenced by setAlignment(), and DynamicElementTextModel::setConnection().
autoPos()
void ElementTextItemGroup::autoPos () private
Definition at line 787 of file elementtextitemgroup.cpp.
References XRefProperties::Bottom, centerToBottomDiagram(), QETProject::defaultXRefProperties(), diagram(), Element::kindInformations(), Element::linkType(), m_parent_element, Element::Master, XRefProperties::offset(), Diagram::project(), rotation, rotationChanged(), XRefProperties::snapTo(), and MasterElement::XrefBoundingRect().
Referenced by setHoldToBottomPage(), and updateAlignment().
blockAlignmentUpdate()
void ElementTextItemGroup::blockAlignmentUpdate (bool block)
ElementTextItemGroup::blockAlignmentUpdate If true, the texts in this group are never aligned, moved, rotated etc... the texts stay as it was, until blockAlignmentUpdate is set to false.
Parameters
block
Definition at line 134 of file elementtextitemgroup.cpp.
References m_block_alignment_update.
boundingRect()
QRectF ElementTextItemGroup::boundingRect () const override
ElementTextItemGroup::boundingRect.
Returns
Definition at line 503 of file elementtextitemgroup.cpp.
References texts().
Referenced by adjustSlaveXrefPos(), and paint().
diagram()
Diagram * ElementTextItemGroup::diagram () const
ElementTextItemGroup::diagram.
Returns
The diagram of this group, or nullptr if this group is not in a diagram
Definition at line 345 of file elementtextitemgroup.cpp.
Referenced by autoPos(), keyPressEvent(), mouseMoveEvent(), and mouseReleaseEvent().
frame()
bool ElementTextItemGroup::frame () const
Definition at line 322 of file elementtextitemgroup.cpp.
References m_frame.
frameChanged
void ElementTextItemGroup::frameChanged (bool frame) signal
Referenced by DynamicElementTextModel::setConnection(), and setFrame().
fromXml()
void ElementTextItemGroup::fromXml (QDomElement & dom_element)
ElementTextItemGroup::fromXml Import data of this group from xml.
Parameters
dom_element
Definition at line 405 of file elementtextitemgroup.cpp.
References Element::addTextToGroup(), QET::findInDomElement(), m_block_alignment_update, parentElement(), setAlignment(), setFrame(), setHoldToBottomPage(), setName(), setPos(), setRotation(), setVerticalAdjustment(), and xmlTaggName().
Referenced by Element::fromXml().
holdToBottomPage()
bool ElementTextItemGroup::holdToBottomPage () const inline
Definition at line 73 of file elementtextitemgroup.h.
References m_hold_to_bottom_of_page.
holdToBottomPageChanged
void ElementTextItemGroup::holdToBottomPageChanged (bool) signal
Referenced by DynamicElementTextModel::setConnection(), and setHoldToBottomPage().
hoverEnterEvent()
void ElementTextItemGroup::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 679 of file elementtextitemgroup.cpp.
References m_slave_Xref_item.
hoverLeaveEvent()
void ElementTextItemGroup::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 690 of file elementtextitemgroup.cpp.
References m_slave_Xref_item.
keyPressEvent()
void ElementTextItemGroup::keyPressEvent (QKeyEvent * event) override protected
ElementTextItemGroup::keyPressEvent.
Parameters
event
Definition at line 650 of file elementtextitemgroup.cpp.
References diagram(), m_alignment, setAlignment(), and Diagram::undoStack().
mouseDoubleClickEvent()
void ElementTextItemGroup::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 614 of file elementtextitemgroup.cpp.
References QetGraphicsItem::diagram(), Element::linkedElements(), m_slave_Xref_item, parentElement(), Diagram::showMe(), and Element::Slave.
mouseMoveEvent()
void ElementTextItemGroup::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
ElementTextItemGroup::mouseMoveEvent.
Parameters
event
Definition at line 565 of file elementtextitemgroup.cpp.
References ElementTextsMover::beginMovement(), ElementTextsMover::continueMovement(), diagram(), Diagram::elementTextsMover(), m_first_move, m_initial_position, parentElement(), pos, Element::setHighlighted(), setPos(), and Diagram::snapToGrid().
mousePressEvent()
void ElementTextItemGroup::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
ElementTextItemGroup::mousePressEvent.
Parameters
event
Definition at line 549 of file elementtextitemgroup.cpp.
References m_first_move.
mouseReleaseEvent()
void ElementTextItemGroup::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
ElementTextItemGroup::mouseReleaseEvent.
Parameters
event
Definition at line 601 of file elementtextitemgroup.cpp.
References diagram(), Diagram::elementTextsMover(), ElementTextsMover::endMovement(), parentElement(), and Element::setHighlighted().
name()
QString ElementTextItemGroup::name () const inline
Definition at line 71 of file elementtextitemgroup.h.
References m_name.
nameChanged
void ElementTextItemGroup::nameChanged (QString) signal
Referenced by setName().
paint()
void ElementTextItemGroup::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override
ElementTextItemGroup::paint.
Parameters
painter
option
widget
Definition at line 451 of file elementtextitemgroup.cpp.
References boundingRect(), m_frame, QET::Icons::ro, and texts().
parentElement()
Element * ElementTextItemGroup::parentElement () const
ElementTextItemGroup::parentElement.
Returns
The parent element of this group or nullptr
Definition at line 357 of file elementtextitemgroup.cpp.
References Element::Type.
Referenced by Element::addTextGroup(), DeleteQGraphicsItemCommand::DeleteQGraphicsItemCommand(), fromXml(), mouseDoubleClickEvent(), mouseMoveEvent(), mouseReleaseEvent(), and DeleteQGraphicsItemCommand::redo().
removeFromGroup()
void ElementTextItemGroup::removeFromGroup (QGraphicsItem * item)
ElementTextItemGroup::removeFromGroup.
Parameters
item
Definition at line 101 of file elementtextitemgroup.cpp.
References DynamicElementTextItem::compositeTextChanged(), DiagramTextItem::fontChanged(), DynamicElementTextItem::infoNameChanged(), DynamicElementTextItem::plainTextChanged(), rotation, DynamicElementTextItem::textChanged(), DynamicElementTextItem::textFromChanged(), DynamicElementTextItem::textWidthChanged(), updateAlignment(), and updateXref().
Referenced by Element::removeTextFromGroup().
rotationChanged
void ElementTextItemGroup::rotationChanged (qreal) signal
Referenced by autoPos(), DynamicElementTextModel::setConnection(), and setRotation().
setAlignment()
void ElementTextItemGroup::setAlignment (Qt::Alignment alignement)
ElementTextItemGroup::setAlignement Set the alignement of this group.
Parameters
alignement
Definition at line 144 of file elementtextitemgroup.cpp.
References alignmentChanged(), m_alignment, and updateAlignment().
Referenced by fromXml(), Element::fromXml(), and keyPressEvent().
setFrame()
void ElementTextItemGroup::setFrame (const bool frame)
Definition at line 315 of file elementtextitemgroup.cpp.
References frame, frameChanged(), and m_frame.
Referenced by fromXml().
setHoldToBottomPage()
void ElementTextItemGroup::setHoldToBottomPage (bool hold)
Definition at line 274 of file elementtextitemgroup.cpp.
References autoPos(), QetGraphicsItem::diagram(), holdToBottomPageChanged(), Element::linkedElementChanged(), Element::linkType(), m_hold_to_bottom_of_page, m_linked_changed_timer, m_parent_element, m_XrefChanged_timer, Element::Master, Diagram::project(), and QETProject::XRefPropertiesChanged().
Referenced by fromXml(), and Element::fromXml().
setName()
void ElementTextItemGroup::setName (QString name)
ElementTextItemGroup::setName.
Parameters
name Set the name of this group
Definition at line 268 of file elementtextitemgroup.cpp.
References m_name, name, and nameChanged().
Referenced by fromXml().
setPos() [1/2]
void ElementTextItemGroup::setPos (const QPointF & pos)
Definition at line 525 of file elementtextitemgroup.cpp.
References pos, xChanged(), and yChanged().
Referenced by fromXml(), Element::fromXml(), mouseMoveEvent(), and updateAlignment().
setPos() [2/2]
void ElementTextItemGroup::setPos (qreal x, qreal y)
Definition at line 535 of file elementtextitemgroup.cpp.
References pos, xChanged(), and yChanged().
setRotation()
void ElementTextItemGroup::setRotation (qreal angle)
Definition at line 519 of file elementtextitemgroup.cpp.
References rotationChanged().
Referenced by fromXml(), Element::fromXml(), and updateAlignment().
setVerticalAdjustment()
void ElementTextItemGroup::setVerticalAdjustment (int v)
ElementTextItemGroup::setVerticalAdjustment Set the value of the vertical adjustment to v. The vertical adjutment is use to adjust the space between the texts of this group.
Parameters
v
Definition at line 256 of file elementtextitemgroup.cpp.
References m_vertical_adjustment, updateAlignment(), and verticalAdjustmentChanged().
Referenced by fromXml(), and Element::fromXml().
texts()
QList< DynamicElementTextItem * > ElementTextItemGroup::texts () const
ElementTextItemGroup::texts.
Returns
Every texts in this group
Definition at line 330 of file elementtextitemgroup.cpp.
References DynamicElementTextItem::Type.
Referenced by DynamicElementTextModel::addGroup(), AlignmentTextsGroupCommand::AlignmentTextsGroupCommand(), boundingRect(), paint(), Element::removeTextFromGroup(), RemoveTextsGroupCommand::RemoveTextsGroupCommand(), toXml(), updateAlignment(), and updateXref().
toXml()
QDomElement ElementTextItemGroup::toXml (QDomDocument & dom_document) const
ElementTextItemGroup::toXml Export data of this group to xml.
Parameters
dom_document
Returns
Definition at line 371 of file elementtextitemgroup.cpp.
References m_alignment, m_frame, m_hold_to_bottom_of_page, m_name, m_vertical_adjustment, pos, rotation, texts(), and xmlTaggName().
updateAlignment()
void ElementTextItemGroup::updateAlignment ()
ElementTextItemGroup::setAlignment Update the alignement of the items in this group, according to the current alignement.
Parameters
alignement
Definition at line 162 of file elementtextitemgroup.cpp.
References adjustSlaveXrefPos(), CrossRefItem::autoPos(), autoPos(), m_alignment, m_block_alignment_update, m_hold_to_bottom_of_page, m_slave_Xref_item, m_vertical_adjustment, m_Xref_item, pos, rotation, setPos(), setRotation(), sort(), sorting(), and texts().
Referenced by addToGroup(), removeFromGroup(), setAlignment(), and setVerticalAdjustment().
updateXref()
void ElementTextItemGroup::updateXref () private
Definition at line 698 of file elementtextitemgroup.cpp.
References adjustSlaveXrefPos(), CrossRefItem::autoPos(), DynamicElementTextItem::CompositeText, QETProject::defaultXRefProperties(), QetGraphicsItem::diagram(), QETProject::diagramRemoved(), QETApp::diagramTextsFont(), DynamicElementTextItem::ElementInfo, Element::elementInfoChange(), autonum::AssignVariables::formulaToLabel(), Element::kindInformations(), XRefProperties::Label, Element::linkedElements(), Element::linkType(), m_parent_element, m_slave_Xref_item, m_update_slave_Xref_connection, m_Xref_item, Element::Master, Diagram::project(), QETProject::projectDiagramsOrderChanged(), Element::rSequenceStruct(), Element::Slave, XRefProperties::slaveLabel(), XRefProperties::snapTo(), texts(), and QETProject::XRefPropertiesChanged().
Referenced by addToGroup(), ElementTextItemGroup(), and removeFromGroup().
verticalAdjustment()
int ElementTextItemGroup::verticalAdjustment () const inline
Definition at line 68 of file elementtextitemgroup.h.
References m_vertical_adjustment.
verticalAdjustmentChanged
void ElementTextItemGroup::verticalAdjustmentChanged (int) signal
Referenced by DynamicElementTextModel::setConnection(), and setVerticalAdjustment().
xChanged
void ElementTextItemGroup::xChanged () signal
Referenced by DynamicElementTextModel::setConnection(), and setPos().
xmlTaggName()
static QString ElementTextItemGroup::xmlTaggName () inline static
Definition at line 82 of file elementtextitemgroup.h.
Referenced by fromXml(), Element::fromXml(), and toXml().
yChanged
void ElementTextItemGroup::yChanged () signal
Referenced by DynamicElementTextModel::setConnection(), and setPos().
Member Data Documentation
m_alignment
Qt::Alignment ElementTextItemGroup::m_alignment = Qt::AlignJustify private
Definition at line 109 of file elementtextitemgroup.h.
Referenced by alignment(), keyPressEvent(), setAlignment(), toXml(), and updateAlignment().
m_block_alignment_update
bool ElementTextItemGroup::m_block_alignment_update = false private
Definition at line 113 of file elementtextitemgroup.h.
Referenced by addToGroup(), blockAlignmentUpdate(), fromXml(), and updateAlignment().
m_first_move
bool ElementTextItemGroup::m_first_move = true private
Definition at line 111 of file elementtextitemgroup.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_frame
bool ElementTextItemGroup::m_frame = false private
Definition at line 114 of file elementtextitemgroup.h.
Referenced by frame(), paint(), setFrame(), and toXml().
m_hold_to_bottom_of_page
bool ElementTextItemGroup::m_hold_to_bottom_of_page = false private
Definition at line 112 of file elementtextitemgroup.h.
Referenced by holdToBottomPage(), setHoldToBottomPage(), toXml(), and updateAlignment().
m_initial_position
QPointF ElementTextItemGroup::m_initial_position private
Definition at line 115 of file elementtextitemgroup.h.
Referenced by mouseMoveEvent().
m_linked_changed_timer
QMetaObject::Connection ElementTextItemGroup::m_linked_changed_timer private
Definition at line 122 of file elementtextitemgroup.h.
Referenced by setHoldToBottomPage().
m_name
QString ElementTextItemGroup::m_name private
Definition at line 110 of file elementtextitemgroup.h.
Referenced by name(), setName(), and toXml().
m_parent_element
Element* ElementTextItemGroup::m_parent_element = nullptr private
Definition at line 118 of file elementtextitemgroup.h.
Referenced by autoPos(), setHoldToBottomPage(), and updateXref().
m_slave_Xref_item
QGraphicsTextItem* ElementTextItemGroup::m_slave_Xref_item = nullptr private
Definition at line 120 of file elementtextitemgroup.h.
Referenced by adjustSlaveXrefPos(), hoverEnterEvent(), hoverLeaveEvent(), mouseDoubleClickEvent(), updateAlignment(), and updateXref().
m_update_slave_Xref_connection
QList<QMetaObject::Connection> ElementTextItemGroup::m_update_slave_Xref_connection private
Definition at line 119 of file elementtextitemgroup.h.
Referenced by updateXref().
m_vertical_adjustment
int ElementTextItemGroup::m_vertical_adjustment = 0 private
Definition at line 116 of file elementtextitemgroup.h.
Referenced by setVerticalAdjustment(), toXml(), updateAlignment(), and verticalAdjustment().
m_Xref_item
CrossRefItem* ElementTextItemGroup::m_Xref_item = nullptr private
Definition at line 117 of file elementtextitemgroup.h.
Referenced by updateAlignment(), and updateXref().
m_XrefChanged_timer
QMetaObject::Connection ElementTextItemGroup::m_XrefChanged_timer private
Definition at line 121 of file elementtextitemgroup.h.
Referenced by setHoldToBottomPage().
Property Documentation
alignment
Qt::Alignment ElementTextItemGroup::alignment read write
Definition at line 1 of file elementtextitemgroup.h.
Referenced by DynamicElementTextModel::addGroup(), DynamicElementTextModel::undoForEditedGroup(), and DynamicElementTextModel::updateDataFromGroup().
frame
bool ElementTextItemGroup::frame read write
Definition at line 1 of file elementtextitemgroup.h.
Referenced by DynamicElementTextModel::addGroup(), setFrame(), DynamicElementTextModel::undoForEditedGroup(), and DynamicElementTextModel::updateDataFromGroup().
holdToBottomPage
bool ElementTextItemGroup::holdToBottomPage read write
Definition at line 1 of file elementtextitemgroup.h.
Referenced by DynamicElementTextModel::addGroup(), DynamicElementTextModel::enableGroupRotationAndPos(), DynamicElementTextModel::undoForEditedGroup(), and DynamicElementTextModel::updateDataFromGroup().
name
QString ElementTextItemGroup::name read write
Definition at line 1 of file elementtextitemgroup.h.
Referenced by DynamicElementTextModel::addGroup(), setName(), DynamicElementTextModel::undoForEditedGroup(), and DynamicElementTextModel::updateDataFromGroup().
pos
QPointF ElementTextItemGroup::pos read write
Definition at line 1 of file elementtextitemgroup.h.
Referenced by DynamicElementTextModel::addGroup(), adjustSlaveXrefPos(), mouseMoveEvent(), setPos(), toXml(), DynamicElementTextModel::undoForEditedGroup(), updateAlignment(), and DynamicElementTextModel::updateDataFromGroup().
rotation
qreal ElementTextItemGroup::rotation read write
Definition at line 1 of file elementtextitemgroup.h.
Referenced by DynamicElementTextModel::addGroup(), addToGroup(), autoPos(), removeFromGroup(), toXml(), DynamicElementTextModel::undoForEditedGroup(), updateAlignment(), and DynamicElementTextModel::updateDataFromGroup().
verticalAdjustment
int ElementTextItemGroup::verticalAdjustment read write
Definition at line 1 of file elementtextitemgroup.h.
Referenced by DynamicElementTextModel::addGroup(), DynamicElementTextModel::undoForEditedGroup(), and DynamicElementTextModel::updateDataFromGroup().
The documentation for this class was generated from the following files:
elementtextitemgroup.h
elementtextitemgroup.cpp