QElectroTech: xpath_allocator Struct Reference
xpath_allocator Struct Reference
Public Member Functions
xpath_allocator (xpath_memory_block *root, bool *error=0)
void * allocate (size_t size)
void * reallocate (void *ptr, size_t old_size, size_t new_size)
void revert (const xpath_allocator &state)
void release ()
Public Attributes
xpath_memory_block * _root
size_t _root_size
bool * _error
Detailed Description
Definition at line 7617 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_allocator()
xpath_allocator::xpath_allocator (xpath_memory_block * root, bool * error = 0) inline
Definition at line 7623 of file pugixml.cpp.
Member Function Documentation
allocate()
void* xpath_allocator::allocate (size_t size) inline
Definition at line 7627 of file pugixml.cpp.
References _error, _root, _root_size, xml_memory_management_function_storage< T >::allocate, xpath_memory_block::capacity, xpath_memory_block::data, xpath_memory_block::next, and xpath_memory_block_alignment.
Referenced by xpath_parser::alloc_node(), xpath_parser::alloc_string(), convert_number_to_string(), xpath_string::duplicate_string(), xpath_ast_node::eval_string_concat(), reallocate(), xpath_node_set_raw::remove_duplicates(), and translate_table_generate().
reallocate()
void* xpath_allocator::reallocate (void * ptr, size_t old_size, size_t new_size) inline
Definition at line 7664 of file pugixml.cpp.
References _root, _root_size, allocate(), xpath_memory_block::data, xml_memory_management_function_storage< T >::deallocate, xpath_memory_block::next, and xpath_memory_block_alignment.
Referenced by xpath_string::append(), xpath_node_set_raw::append(), and xpath_node_set_raw::push_back_grow().
release()
void xpath_allocator::release () inline
Definition at line 7730 of file pugixml.cpp.
References _root, xml_memory_management_function_storage< T >::deallocate, and xpath_memory_block::next.
Referenced by xpath_query_impl::destroy(), and xpath_stack_data::~xpath_stack_data().
revert()
void xpath_allocator::revert (const xpath_allocator & state) inline
Definition at line 7711 of file pugixml.cpp.
References _root, _root_size, xml_memory_management_function_storage< T >::deallocate, and xpath_memory_block::next.
Referenced by xpath_allocator_capture::~xpath_allocator_capture().
Member Data Documentation
_error
bool* xpath_allocator::_error
Definition at line 7621 of file pugixml.cpp.
Referenced by allocate(), and xpath_parser::error_oom().
_root
xpath_memory_block* xpath_allocator::_root
Definition at line 7619 of file pugixml.cpp.
Referenced by allocate(), reallocate(), release(), and revert().
_root_size
size_t xpath_allocator::_root_size
Definition at line 7620 of file pugixml.cpp.
Referenced by allocate(), reallocate(), and revert().
The documentation for this struct was generated from the following file:
pugixml.cpp