QElectroTech: ChangeElementInformationCommand Class Reference
ChangeElementInformationCommand Class Reference
The ChangeElementInformationCommand class This class manage undo/redo to change the element information.
#include <changeelementinformationcommand.h>
Public Member Functions
ChangeElementInformationCommand (Element *elmt, DiagramContext &old_info, DiagramContext &new_info, QUndoCommand *parent=nullptr)
ChangeElementInformationCommand::ChangeElementInformationCommand Default constructor.
int id () const override
bool mergeWith (const QUndoCommand *other) override
void undo () override
ChangeElementInformationCommand::undo.
void redo () override
ChangeElementInformationCommand::redo.
Private Member Functions
void updateProjectDB ()
Private Attributes
Element * m_element
DiagramContext m_old_info
DiagramContext m_new_info
Detailed Description
The ChangeElementInformationCommand class This class manage undo/redo to change the element information.
Definition at line 30 of file changeelementinformationcommand.h.
Constructor & Destructor Documentation
ChangeElementInformationCommand()
ChangeElementInformationCommand::ChangeElementInformationCommand (Element * elmt, DiagramContext & old_info, DiagramContext & new_info, QUndoCommand * parent = nullptr)
ChangeElementInformationCommand::ChangeElementInformationCommand Default constructor.
Parameters
elmt : element to change information
old_info : old info of element
new_info : new info of element
parent
Definition at line 31 of file changeelementinformationcommand.cpp.
References QET::Icons::tr.
Member Function Documentation
id()
int ChangeElementInformationCommand::id () const inline override
Definition at line 39 of file changeelementinformationcommand.h.
mergeWith()
bool ChangeElementInformationCommand::mergeWith (const QUndoCommand * other) override
Definition at line 45 of file changeelementinformationcommand.cpp.
References m_element, m_new_info, and undo().
redo()
void ChangeElementInformationCommand::redo () override
ChangeElementInformationCommand::redo.
Definition at line 66 of file changeelementinformationcommand.cpp.
References m_element, m_new_info, and updateProjectDB().
undo()
void ChangeElementInformationCommand::undo () override
ChangeElementInformationCommand::undo.
Definition at line 58 of file changeelementinformationcommand.cpp.
References m_element, m_old_info, and updateProjectDB().
Referenced by mergeWith().
updateProjectDB()
void ChangeElementInformationCommand::updateProjectDB () private
Definition at line 71 of file changeelementinformationcommand.cpp.
References QETProject::dataBase(), QetGraphicsItem::diagram(), projectDataBase::elementInfoChanged(), m_element, and Diagram::project().
Referenced by redo(), and undo().
Member Data Documentation
m_element
Element* ChangeElementInformationCommand::m_element private
Definition at line 48 of file changeelementinformationcommand.h.
Referenced by mergeWith(), redo(), undo(), and updateProjectDB().
m_new_info
DiagramContext ChangeElementInformationCommand::m_new_info private
Definition at line 50 of file changeelementinformationcommand.h.
Referenced by mergeWith(), and redo().
m_old_info
DiagramContext ChangeElementInformationCommand::m_old_info private
Definition at line 49 of file changeelementinformationcommand.h.
Referenced by undo().
The documentation for this class was generated from the following files:
changeelementinformationcommand.h
changeelementinformationcommand.cpp