QElectroTech: NumerotationContext Class Reference
NumerotationContext Class Reference
#include <numerotationcontext.h>
Public Member Functions
NumerotationContext ()
NumerotationContext (QDomElement &)
void clear ()
NumerotationContext::clear, clear the content.
bool addValue (const QString &, const QVariant &=QVariant(1), const int=1, const int=0)
NumerotationContext::addValue add a new value on the contexte.
QString operator[] (const int &) const
NumerotationContext::operator [].
void operator<< (const NumerotationContext &)
NumerotationContext::operator << , append other.
int size () const
NumerotationContext::size.
bool isEmpty () const
NumerotationContext::isEmpty.
QStringList itemAt (const int) const
NumerotationContext::itemAt.
QString validRegExpNum () const
validRegExpNum
QString validRegExpNumber () const
NumerotationContext::validRegExpNumber.
bool keyIsAcceptable (const QString &) const
NumerotationContext::keyIsAcceptable.
bool keyIsNumber (const QString &) const
NumerotationContext::keyIsNumber.
QDomElement toXml (QDomDocument &, const QString &)
NumerotationContext::toXml Save the numerotation context in a QDomElement under the element name str.
void fromXml (QDomElement &)
NumerotationContext::fromXml load numerotation context from e.
void replaceValue (int, QString)
NumerotationContext::replaceValue This class replaces the current NC field value with content.
Private Attributes
QStringList content_
Detailed Description
This class represents a numerotation context, i.e. the data (type, value, increase) of a numerotation at a given time. It is notably used by conductor to store the informations they need to do their autonumerotation.
Definition at line 30 of file numerotationcontext.h.
Constructor & Destructor Documentation
NumerotationContext() [1/2]
NumerotationContext::NumerotationContext ()
Constructor
Definition at line 26 of file numerotationcontext.cpp.
NumerotationContext() [2/2]
NumerotationContext::NumerotationContext (QDomElement & e)
Constructor from xml
Definition at line 32 of file numerotationcontext.cpp.
References fromXml().
Member Function Documentation
addValue()
bool NumerotationContext::addValue (const QString & type, const QVariant & value = QVariant(1), const int increase = 1, const int initialvalue = 0)
NumerotationContext::addValue add a new value on the contexte.
Parameters
type the type of value
value the value itself
increase the increase number of value
initialvalue
Returns
true if value is append
Definition at line 52 of file numerotationcontext.cpp.
References content_, keyIsAcceptable(), and keyIsNumber().
Referenced by fromXml(), NumStrategy::nextNumber(), NumStrategy::nextString(), NumStrategy::previousNumber(), and NumPartEditorW::toNumContext().
clear()
void NumerotationContext::clear ()
NumerotationContext::clear, clear the content.
Definition at line 39 of file numerotationcontext.cpp.
References content_.
Referenced by fromXml().
fromXml()
void NumerotationContext::fromXml (QDomElement & e)
NumerotationContext::fromXml load numerotation context from e.
Definition at line 172 of file numerotationcontext.cpp.
References addValue(), clear(), and QET::findInDomElement().
Referenced by NumerotationContext(), and QETProject::readDefaultPropertiesXml().
isEmpty()
bool NumerotationContext::isEmpty () const
NumerotationContext::isEmpty.
Returns
true if numerotation contet is empty
Definition at line 101 of file numerotationcontext.cpp.
References content_.
Referenced by ConductorAutoNumerotation::newProperties(), ConductorAutoNumerotation::numerateNewConductor(), and autonum::setSequential().
itemAt()
QStringList NumerotationContext::itemAt (const int i) const
NumerotationContext::itemAt.
Parameters
i
Returns
the content at position i 1:type 2:value 3:increase
Definition at line 110 of file numerotationcontext.cpp.
References content_.
Referenced by Diagram::insertFolioSeqHash(), Diagram::loadFolioSeqHash(), NumerotationContextCommands::next(), NumStrategy::nextNumber(), NumStrategy::nextString(), autonum::numerotationContextToFormula(), NumPartEditorW::NumPartEditorW(), NumerotationContextCommands::previous(), NumStrategy::previousNumber(), autonum::setSequentialToList(), NumerotationContextCommands::toRepresentedString(), and toXml().
keyIsAcceptable()
bool NumerotationContext::keyIsAcceptable (const QString & type) const
NumerotationContext::keyIsAcceptable.
Returns
true if type is acceptable
Definition at line 134 of file numerotationcontext.cpp.
References validRegExpNum().
Referenced by addValue().
keyIsNumber()
bool NumerotationContext::keyIsNumber (const QString & type) const
NumerotationContext::keyIsNumber.
Returns
true if type represent a number
Definition at line 142 of file numerotationcontext.cpp.
References validRegExpNumber().
Referenced by addValue().
operator<<()
void NumerotationContext::operator<< (const NumerotationContext & other)
NumerotationContext::operator << , append other.
Definition at line 85 of file numerotationcontext.cpp.
References content_, and size().
operator[]()
QString NumerotationContext::operator[] (const int & i) const
NumerotationContext::operator [].
Parameters
i
Returns
the string at position i
Definition at line 78 of file numerotationcontext.cpp.
References content_.
replaceValue()
void NumerotationContext::replaceValue (int index, QString content)
NumerotationContext::replaceValue This class replaces the current NC field value with content.
Parameters
index of NC Item
content to replace current value
Definition at line 183 of file numerotationcontext.cpp.
References content_.
Referenced by Diagram::insertFolioSeqHash(), and Diagram::loadFolioSeqHash().
size()
int NumerotationContext::size () const
NumerotationContext::size.
Returns
size of context
Definition at line 93 of file numerotationcontext.cpp.
References content_.
Referenced by Diagram::insertFolioSeqHash(), Diagram::loadFolioSeqHash(), NumerotationContextCommands::next(), autonum::numerotationContextToFormula(), NumPartEditorW::NumPartEditorW(), operator<<(), NumerotationContextCommands::previous(), SelectAutonumW::setContext(), autonum::setSequentialToList(), and NumerotationContextCommands::toRepresentedString().
toXml()
QDomElement NumerotationContext::toXml (QDomDocument & d, const QString & str)
NumerotationContext::toXml Save the numerotation context in a QDomElement under the element name str.
Definition at line 150 of file numerotationcontext.cpp.
References content_, and itemAt().
validRegExpNum()
QString NumerotationContext::validRegExpNum () const
validRegExpNum
Returns
all type use to numerotation
Definition at line 118 of file numerotationcontext.cpp.
Referenced by keyIsAcceptable().
validRegExpNumber()
QString NumerotationContext::validRegExpNumber () const
NumerotationContext::validRegExpNumber.
Returns
all type represents a number
Definition at line 126 of file numerotationcontext.cpp.
Referenced by keyIsNumber().
Member Data Documentation
content_
QStringList NumerotationContext::content_ private
Definition at line 54 of file numerotationcontext.h.
Referenced by addValue(), clear(), isEmpty(), itemAt(), operator<<(), operator[](), replaceValue(), size(), and toXml().
The documentation for this class was generated from the following files:
numerotationcontext.h
numerotationcontext.cpp