QElectroTech: SelectAutonumW Class Reference
SelectAutonumW Class Reference
#include <selectautonumw.h>
Signals
void applyPressed ()
void removeClicked ()
Public Member Functions
SelectAutonumW (int type, QWidget *parent=nullptr)
SelectAutonumW (const NumerotationContext &context, int type, QWidget *parent=nullptr)
~SelectAutonumW () override
void setContext (const NumerotationContext &context)
SelectAutonumW::setContext build the context of current diagram selected in the diagram_chooser QcomboBox.
NumerotationContext toNumContext () const
SelectAutonumW::toNumContext.
void contextToFormula ()
SelectAutonumW::contextToFormula Apply formula to ElementAutonumbering Widget.
QString formula ()
SelectAutonumW::formula.
QComboBox * contextComboBox () const
Private Slots
void on_add_button_clicked ()
SelectAutonumW::on_add_button_clicked Action on add_button, add a NumPartEditor.
void on_remove_button_clicked ()
SelectAutonumW::on_remove_button_clicked Action on remove button, remove the last NumPartEditor.
void on_buttonBox_clicked (QAbstractButton *)
SelectAutonumW::on_buttonBox_clicked Action on button clicked.
void applyEnable (bool=true)
SelectAutonumW::applyEnable enable/disable the apply button.
void on_m_next_pb_clicked ()
SelectAutonumW::on_m_next_pb_clicked Increase NumerotationContext.
void on_m_previous_pb_clicked ()
SelectAutonumW::on_m_previous_pb_clicked Decrease NumerotationContext.
void on_m_comboBox_currentTextChanged (const QString &arg1)
void on_m_remove_pb_clicked ()
Private Attributes
Ui::SelectAutonumW * ui
QList< NumPartEditorW * > num_part_list_
NumerotationContext m_context
FormulaAutonumberingW * m_feaw
FormulaAutonumberingW * m_fcaw
int m_edited_type = -1
Detailed Description
Definition at line 34 of file selectautonumw.h.
Constructor & Destructor Documentation
SelectAutonumW() [1/2]
SelectAutonumW::SelectAutonumW (int type, QWidget * parent = nullptr) explicit
Constructor
Definition at line 30 of file selectautonumw.cpp.
References m_edited_type, m_fcaw, m_feaw, setContext(), FormulaAutonumberingW::ui, and ui.
SelectAutonumW() [2/2]
SelectAutonumW::SelectAutonumW (const NumerotationContext & context, int type, QWidget * parent = nullptr) explicit
Definition at line 53 of file selectautonumw.cpp.
References m_edited_type, m_fcaw, m_feaw, setContext(), FormulaAutonumberingW::ui, and ui.
~SelectAutonumW()
SelectAutonumW::~SelectAutonumW () override
Destructor
Definition at line 77 of file selectautonumw.cpp.
References ui.
Member Function Documentation
applyEnable
void SelectAutonumW::applyEnable (bool b = true) private slot
SelectAutonumW::applyEnable enable/disable the apply button.
Definition at line 249 of file selectautonumw.cpp.
References contextToFormula(), m_edited_type, num_part_list_, and ui.
Referenced by on_add_button_clicked(), on_buttonBox_clicked(), on_m_comboBox_currentTextChanged(), on_m_next_pb_clicked(), on_m_previous_pb_clicked(), on_remove_button_clicked(), and setContext().
applyPressed
void SelectAutonumW::applyPressed () signal
Referenced by ProjectAutoNumConfigPage::buildConnections(), and on_buttonBox_clicked().
contextComboBox()
QComboBox * SelectAutonumW::contextComboBox () const
Definition at line 169 of file selectautonumw.cpp.
References ui.
Referenced by ProjectAutoNumConfigPage::buildConnections(), ProjectAutoNumConfigPage::readValuesFromProject(), ProjectAutoNumConfigPage::removeContextConductor(), ProjectAutoNumConfigPage::removeContextElement(), ProjectAutoNumConfigPage::removeContextFolio(), ProjectAutoNumConfigPage::saveContextConductor(), ProjectAutoNumConfigPage::saveContextElement(), and ProjectAutoNumConfigPage::saveContextFolio().
contextToFormula()
void SelectAutonumW::contextToFormula ()
SelectAutonumW::contextToFormula Apply formula to ElementAutonumbering Widget.
Definition at line 271 of file selectautonumw.cpp.
References FormulaAutonumberingW::clearContext(), m_edited_type, m_fcaw, m_feaw, autonum::numerotationContextToFormula(), FormulaAutonumberingW::setContext(), and toNumContext().
Referenced by applyEnable().
formula()
QString SelectAutonumW::formula ()
SelectAutonumW::formula.
Returns
autonumbering widget formula
Definition at line 159 of file selectautonumw.cpp.
References FormulaAutonumberingW::formula(), m_edited_type, m_fcaw, and m_feaw.
on_add_button_clicked
void SelectAutonumW::on_add_button_clicked () private slot
SelectAutonumW::on_add_button_clicked Action on add_button, add a NumPartEditor.
Definition at line 128 of file selectautonumw.cpp.
References applyEnable(), m_edited_type, num_part_list_, and ui.
Referenced by setContext().
on_buttonBox_clicked
void SelectAutonumW::on_buttonBox_clicked (QAbstractButton * button) private slot
SelectAutonumW::on_buttonBox_clicked Action on button clicked.
Parameters
button
Definition at line 179 of file selectautonumw.cpp.
References applyEnable(), applyPressed(), QET::QetMessageBox::information(), m_context, m_edited_type, setContext(), QET::Icons::tr, and ui.
on_m_comboBox_currentTextChanged
void SelectAutonumW::on_m_comboBox_currentTextChanged (const QString & arg1) private slot
Definition at line 308 of file selectautonumw.cpp.
References applyEnable().
on_m_next_pb_clicked
void SelectAutonumW::on_m_next_pb_clicked () private slot
SelectAutonumW::on_m_next_pb_clicked Increase NumerotationContext.
Definition at line 290 of file selectautonumw.cpp.
References applyEnable(), NumerotationContextCommands::next(), setContext(), and toNumContext().
on_m_previous_pb_clicked
void SelectAutonumW::on_m_previous_pb_clicked () private slot
SelectAutonumW::on_m_previous_pb_clicked Decrease NumerotationContext.
Definition at line 301 of file selectautonumw.cpp.
References applyEnable(), NumerotationContextCommands::previous(), setContext(), and toNumContext().
on_m_remove_pb_clicked
void SelectAutonumW::on_m_remove_pb_clicked () private slot
Definition at line 314 of file selectautonumw.cpp.
References removeClicked().
on_remove_button_clicked
void SelectAutonumW::on_remove_button_clicked () private slot
SelectAutonumW::on_remove_button_clicked Action on remove button, remove the last NumPartEditor.
Definition at line 142 of file selectautonumw.cpp.
References applyEnable(), num_part_list_, and ui.
removeClicked
void SelectAutonumW::removeClicked () signal
Referenced by ProjectAutoNumConfigPage::buildConnections(), and on_m_remove_pb_clicked().
setContext()
void SelectAutonumW::setContext (const NumerotationContext & context)
SelectAutonumW::setContext build the context of current diagram selected in the diagram_chooser QcomboBox.
Parameters
context
Definition at line 88 of file selectautonumw.cpp.
References applyEnable(), m_context, m_edited_type, num_part_list_, on_add_button_clicked(), NumerotationContext::size(), and ui.
Referenced by on_buttonBox_clicked(), on_m_next_pb_clicked(), on_m_previous_pb_clicked(), SelectAutonumW(), ProjectAutoNumConfigPage::updateContextConductor(), ProjectAutoNumConfigPage::updateContextElement(), and ProjectAutoNumConfigPage::updateContextFolio().
toNumContext()
NumerotationContext SelectAutonumW::toNumContext () const
SelectAutonumW::toNumContext.
Returns
the content to num_part_list to NumerotationContext
Definition at line 117 of file selectautonumw.cpp.
References num_part_list_.
Referenced by contextToFormula(), on_m_next_pb_clicked(), on_m_previous_pb_clicked(), ProjectAutoNumConfigPage::saveContextConductor(), ProjectAutoNumConfigPage::saveContextElement(), and ProjectAutoNumConfigPage::saveContextFolio().
Member Data Documentation
m_context
NumerotationContext SelectAutonumW::m_context private
Definition at line 70 of file selectautonumw.h.
Referenced by on_buttonBox_clicked(), and setContext().
m_edited_type
int SelectAutonumW::m_edited_type = -1 private
Definition at line 73 of file selectautonumw.h.
Referenced by applyEnable(), contextToFormula(), formula(), on_add_button_clicked(), on_buttonBox_clicked(), SelectAutonumW(), and setContext().
m_fcaw
FormulaAutonumberingW* SelectAutonumW::m_fcaw private
Definition at line 72 of file selectautonumw.h.
Referenced by contextToFormula(), formula(), and SelectAutonumW().
m_feaw
FormulaAutonumberingW* SelectAutonumW::m_feaw private
Definition at line 71 of file selectautonumw.h.
Referenced by contextToFormula(), formula(), and SelectAutonumW().
num_part_list_
QList<NumPartEditorW *> SelectAutonumW::num_part_list_ private
Definition at line 69 of file selectautonumw.h.
Referenced by applyEnable(), on_add_button_clicked(), on_remove_button_clicked(), setContext(), and toNumContext().
ui
Ui::SelectAutonumW* SelectAutonumW::ui private
Definition at line 68 of file selectautonumw.h.
Referenced by applyEnable(), contextComboBox(), on_add_button_clicked(), on_buttonBox_clicked(), on_remove_button_clicked(), SelectAutonumW(), setContext(), and ~SelectAutonumW().
The documentation for this class was generated from the following files:
selectautonumw.h
selectautonumw.cpp