QElectroTech: TitleBlockTemplateLocation Class Reference
TitleBlockTemplateLocation Class Reference
#include <templatelocation.h>
Public Member Functions
TitleBlockTemplateLocation (const QString &=QString(), TitleBlockTemplatesCollection *=nullptr)
virtual ~TitleBlockTemplateLocation ()
TitleBlockTemplateLocation locationFromString (const QString &)
TitleBlockTemplatesCollection * parentCollection () const
void setParentCollection (TitleBlockTemplatesCollection *)
TitleBlockTemplateLocation::setParentCollection.
QString name () const
void setName (const QString &)
bool isValid () const
void fromString (const QString &)
QString toString () const
QETProject * parentProject () const
QString protocol () const
QDomElement getTemplateXmlDescription () const
TitleBlockTemplate * getTemplate () const
bool isReadOnly () const
bool operator== (const TitleBlockTemplateLocation &) const
Static Public Attributes
static int MetaTypeId = qRegisterMetaType<TitleBlockTemplateLocation>("TitleBlockTemplateLocation")
Id of the corresponding Qt meta type.
Private Attributes
TitleBlockTemplatesCollection * collection_
Collection the template belongs to.
QString name_
Name of the template.
Detailed Description
This class represents the location of a title block template.
Definition at line 29 of file templatelocation.h.
Constructor & Destructor Documentation
TitleBlockTemplateLocation()
TitleBlockTemplateLocation::TitleBlockTemplateLocation (const QString & name = QString(), TitleBlockTemplatesCollection * collection = nullptr)
Constructor
Parameters
collection Parent collection of the title block template
name Name of the title block template within its parent project or collection
Definition at line 30 of file templatelocation.cpp.
~TitleBlockTemplateLocation()
TitleBlockTemplateLocation::~TitleBlockTemplateLocation () virtual
Destructor
Definition at line 41 of file templatelocation.cpp.
Member Function Documentation
fromString()
void TitleBlockTemplateLocation::fromString (const QString & loc_str)
Parameters
loc_str String describing the location of a title block template.
Definition at line 94 of file templatelocation.cpp.
References collection_, name_, and QETApp::titleBlockTemplatesCollection().
Referenced by DiagramView::handleTitleBlockDrop(), and locationFromString().
getTemplate()
TitleBlockTemplate * TitleBlockTemplateLocation::getTemplate () const
This is a convenience method equivalent to parentCollection() -> getTemplate(...).
Definition at line 147 of file templatelocation.cpp.
References collection_, and name_.
Referenced by QETTitleBlockTemplateEditor::edit().
getTemplateXmlDescription()
QDomElement TitleBlockTemplateLocation::getTemplateXmlDescription () const
This is a convenience method equivalent to parentCollection() -> getTemplateXmlDescription
Definition at line 138 of file templatelocation.cpp.
References collection_, and name_.
Referenced by QETProject::integrateTitleBlockTemplate(), and IntegrationMoveTitleBlockTemplatesHandler::templateAlreadyExists().
isReadOnly()
bool TitleBlockTemplateLocation::isReadOnly () const
This is a convenience method equivalent to parentCollection() -> isReadOnly(name())
Definition at line 156 of file templatelocation.cpp.
References collection_, and name_.
Referenced by QETTitleBlockTemplateEditor::edit(), QETTitleBlockTemplateEditor::save(), and ElementsPanelWidget::updateButtons().
isValid()
bool TitleBlockTemplateLocation::isValid () const
Returns
true if this location is null, false otherwise
Definition at line 87 of file templatelocation.cpp.
References name_.
Referenced by GenericPanel::addTemplate(), TitleBlockTemplateDeleter::exec(), GenericPanel::getItemForTemplate(), DiagramView::handleTitleBlockDrop(), QETTitleBlockTemplateEditor::open(), QETTitleBlockTemplateEditor::save(), QETTitleBlockTemplateEditor::saveAs(), and ElementsPanel::startDrag().
locationFromString()
TitleBlockTemplateLocation TitleBlockTemplateLocation::locationFromString (const QString & loc_str)
Parameters
loc_str String describing the location of a title block template.
Definition at line 47 of file templatelocation.cpp.
References fromString().
name()
QString TitleBlockTemplateLocation::name () const
Returns
the name of this template within its parent project or collection.
Definition at line 73 of file templatelocation.cpp.
References name_.
Referenced by QETTitleBlockTemplateEditor::canClose(), QETTitleBlockTemplateEditor::currentlyEditedTitle(), QETTitleBlockTemplateEditor::duplicateCurrentLocation(), QETTitleBlockTemplateEditor::edit(), TitleBlockTemplateDeleter::exec(), DiagramView::handleTitleBlockDrop(), QETProject::integrateTitleBlockTemplate(), IntegrationMoveTitleBlockTemplatesHandler::newNameForTemplate(), QETTitleBlockTemplateEditor::saveAs(), TitleBlockTemplateLocationSaver::setLocation(), TitleBlockTemplateLocationChooser::setLocation(), setName(), IntegrationMoveTitleBlockTemplatesHandler::templateAlreadyExists(), GenericPanel::updateTemplateItem(), and QETProject::usesTitleBlockTemplate().
operator==()
bool TitleBlockTemplateLocation::operator== (const TitleBlockTemplateLocation & location) const
Parameters
location other location that should be compared to this one
Returns
true if locations are equal, false otherwise
Definition at line 165 of file templatelocation.cpp.
References collection_, and name_.
parentCollection()
TitleBlockTemplatesCollection * TitleBlockTemplateLocation::parentCollection () const
Returns
the parent collection of the template, or 0 if none was defined
Definition at line 57 of file templatelocation.cpp.
References collection_.
Referenced by QETTitleBlockTemplateEditor::duplicateCurrentLocation(), TitleBlockTemplateDeleter::exec(), ElementsPanel::filePathForItem(), QETTitleBlockTemplateEditor::firstActivation(), QETTitleBlockTemplateEditor::saveAs(), TitleBlockTemplateLocationSaver::setLocation(), TitleBlockTemplateLocationChooser::setLocation(), IntegrationMoveTitleBlockTemplatesHandler::templateAlreadyExists(), and ElementsPanelWidget::updateButtons().
parentProject()
QETProject * TitleBlockTemplateLocation::parentProject () const
This is a convenience method equivalent to parentCollection() -> parentProject().
Definition at line 116 of file templatelocation.cpp.
References collection_.
Referenced by DiagramView::handleTitleBlockDrop(), DiagramView::mustIntegrateTitleBlockTemplate(), GenericPanel::updateTemplateItem(), and QETProject::usesTitleBlockTemplate().
protocol()
QString TitleBlockTemplateLocation::protocol () const
This is a convenience method equivalent to parentCollection() -> protocol().
Definition at line 127 of file templatelocation.cpp.
References collection_.
Referenced by toString().
setName()
void TitleBlockTemplateLocation::setName (const QString & name)
Parameters
name The new name of this template.
Definition at line 80 of file templatelocation.cpp.
References name(), and name_.
Referenced by QETTitleBlockTemplateEditor::edit().
setParentCollection()
void TitleBlockTemplateLocation::setParentCollection (TitleBlockTemplatesCollection * collection)
TitleBlockTemplateLocation::setParentCollection.
Parameters
collection : TitleBlockTemplatesCollection
Definition at line 65 of file templatelocation.cpp.
References collection_.
Referenced by QETTitleBlockTemplateEditor::edit().
toString()
QString TitleBlockTemplateLocation::toString () const
Returns
A string representation of the location
Definition at line 108 of file templatelocation.cpp.
References name_, and protocol().
Referenced by IntegrationMoveTitleBlockTemplatesHandler::errorWithATemplate(), QETTitleBlockTemplateEditor::isEditing(), qHash(), ElementsPanel::startTitleBlockTemplateDrag(), GenericPanel::updateTemplateItem(), and GenericPanel::updateTemplatesCollectionItem().
Member Data Documentation
collection_
TitleBlockTemplatesCollection* TitleBlockTemplateLocation::collection_ private
Collection the template belongs to.
Definition at line 59 of file templatelocation.h.
Referenced by fromString(), getTemplate(), getTemplateXmlDescription(), isReadOnly(), operator==(), parentCollection(), parentProject(), protocol(), and setParentCollection().
MetaTypeId
int TitleBlockTemplateLocation::MetaTypeId = qRegisterMetaType<TitleBlockTemplateLocation>("TitleBlockTemplateLocation") static
Id of the corresponding Qt meta type.
Definition at line 63 of file templatelocation.h.
name_
QString TitleBlockTemplateLocation::name_ private
Name of the template.
Definition at line 60 of file templatelocation.h.
Referenced by fromString(), getTemplate(), getTemplateXmlDescription(), isReadOnly(), isValid(), name(), operator==(), setName(), and toString().
The documentation for this class was generated from the following files:
templatelocation.h
templatelocation.cpp