QElectroTech: TitleBlockTemplateDeleter Class Reference
TitleBlockTemplateDeleter Class Reference
#include <templatedeleter.h>
Public Slots
bool exec ()
Public Member Functions
TitleBlockTemplateDeleter (const TitleBlockTemplateLocation &, QWidget *=nullptr)
~TitleBlockTemplateDeleter () override
Private Member Functions
TitleBlockTemplateDeleter (const TitleBlockTemplateDeleter &)
Private Attributes
TitleBlockTemplateLocation template_location_
Detailed Description
This class is an abstraction layer to delete an existing title block template.
Definition at line 26 of file templatedeleter.h.
Constructor & Destructor Documentation
TitleBlockTemplateDeleter() [1/2]
TitleBlockTemplateDeleter::TitleBlockTemplateDeleter (const TitleBlockTemplateLocation & tbt_location, QWidget * parent = nullptr)
Constructor
Parameters
tbt_location Location of the title block template to be deleted
parent Parent QWidget
Definition at line 26 of file templatedeleter.cpp.
~TitleBlockTemplateDeleter()
TitleBlockTemplateDeleter::~TitleBlockTemplateDeleter () override
Destructor
Definition at line 35 of file templatedeleter.cpp.
TitleBlockTemplateDeleter() [2/2]
TitleBlockTemplateDeleter::TitleBlockTemplateDeleter (const TitleBlockTemplateDeleter &) private
Member Function Documentation
exec
bool TitleBlockTemplateDeleter::exec () slot
Delete the title block template: check the provided location matches an existing template, interactively require confirmationfrom the user before actually proceeding to the deletion.
Returns
true if the deletion succeeded, false otherwise.
Definition at line 44 of file templatedeleter.cpp.
References QET::Icons::Cancel, TitleBlockTemplateLocation::isValid(), TitleBlockTemplateLocation::name(), TitleBlockTemplateLocation::parentCollection(), QET::QetMessageBox::question(), template_location_, and QET::Icons::tr.
Referenced by ElementsPanelWidget::removeTitleBlockTemplate().
Member Data Documentation
template_location_
TitleBlockTemplateLocation TitleBlockTemplateDeleter::template_location_ private
Definition at line 41 of file templatedeleter.h.
Referenced by exec().
The documentation for this class was generated from the following files:
templatedeleter.h
templatedeleter.cpp