QElectroTech: ConductorPropertiesDialog Class Reference
ConductorPropertiesDialog Class Reference
#include <conductorpropertiesdialog.h>
Public Member Functions
ConductorPropertiesDialog (Conductor *conductor, QWidget *parent=nullptr)
ConductorPropertiesDialog::ConductorPropertiesDialog Constructor.
~ConductorPropertiesDialog () override
ConductorPropertiesDialog::~ConductorPropertiesDialog.
ConductorProperties properties () const
ConductorPropertiesDialog::properties.
bool applyAll () const
ConductorPropertiesDialog::applyAll.
Static Public Member Functions
static void PropertiesDialog (Conductor *conductor, QWidget *parent=nullptr)
ConductorPropertiesDialog::PropertiesDialog Static method for open and apply properties.
Private Attributes
Ui::ConductorPropertiesDialog * ui
ConductorPropertiesWidget * m_cpw
Detailed Description
Definition at line 32 of file conductorpropertiesdialog.h.
Constructor & Destructor Documentation
ConductorPropertiesDialog()
ConductorPropertiesDialog::ConductorPropertiesDialog (Conductor * conductor, QWidget * parent = nullptr) explicit
ConductorPropertiesDialog::ConductorPropertiesDialog Constructor.
Parameters
conductor : conductor to edit propertie
parent : parent widget
Definition at line 32 of file conductorpropertiesdialog.cpp.
References m_cpw, Conductor::properties, ConductorPropertiesWidget::setDisabledShowText(), ConductorPropertiesWidget::setHiddenAvailableAutonum(), and ui.
~ConductorPropertiesDialog()
ConductorPropertiesDialog::~ConductorPropertiesDialog () override
ConductorPropertiesDialog::~ConductorPropertiesDialog.
Definition at line 51 of file conductorpropertiesdialog.cpp.
References ui.
Member Function Documentation
applyAll()
bool ConductorPropertiesDialog::applyAll () const
ConductorPropertiesDialog::applyAll.
Returns
true -> must apply the propertie to all conductor at the same potential false -> must apply properties only for the edited conductor
Definition at line 105 of file conductorpropertiesdialog.cpp.
References ui.
Referenced by PropertiesDialog().
properties()
ConductorProperties ConductorPropertiesDialog::properties () const
ConductorPropertiesDialog::properties.
Returns
the edited properties
Definition at line 95 of file conductorpropertiesdialog.cpp.
References m_cpw.
Referenced by PropertiesDialog().
PropertiesDialog()
void ConductorPropertiesDialog::PropertiesDialog (Conductor * conductor, QWidget * parent = nullptr) static
ConductorPropertiesDialog::PropertiesDialog Static method for open and apply properties.
Parameters
conductor : conductor to edit propertie
parent : parent widget
Definition at line 62 of file conductorpropertiesdialog.cpp.
References applyAll(), Conductor::diagram(), properties(), Conductor::properties, Conductor::relatedPotentialConductors(), QET::Icons::tr, and Diagram::undoStack().
Referenced by Conductor::editProperty().
Member Data Documentation
m_cpw
ConductorPropertiesWidget* ConductorPropertiesDialog::m_cpw private
Definition at line 48 of file conductorpropertiesdialog.h.
Referenced by ConductorPropertiesDialog(), and properties().
ui
Ui::ConductorPropertiesDialog* ConductorPropertiesDialog::ui private
Definition at line 47 of file conductorpropertiesdialog.h.
Referenced by applyAll(), ConductorPropertiesDialog(), and ~ConductorPropertiesDialog().
The documentation for this class was generated from the following files:
conductorpropertiesdialog.h
conductorpropertiesdialog.cpp