QElectroTech: QPropertyUndoCommand Class Reference
QPropertyUndoCommand Class Reference
The QPropertyUndoCommand class This undo command manage QProperty of a QObject. This undo command can use QPropertyAnimation to animate the change when undo/redo is call To use animation call setAnimated(true). By default animation is disable. Some QVariant date can't be animated and result this command don't work.
#include <qpropertyundocommand.h>
Public Member Functions
QPropertyUndoCommand (QObject *object, const char *property_name, const QVariant &old_value, const QVariant &new_value, QUndoCommand *parent=nullptr)
QPropertyUndoCommand::QPropertyUndoCommand Default constructor with old and new value This command don't take ownership of object.
QPropertyUndoCommand (QObject *object, const char *property_name, const QVariant &old_value, QUndoCommand *parent=nullptr)
QPropertyUndoCommand::QPropertyUndoCommand Default constructor with old value. Call setNewValue to setup the new value of the edited QObject This command don't take ownership of object.
QPropertyUndoCommand (const QPropertyUndoCommand *other)
QPropertyUndoCommand::QPropertyUndoCommand.
void setNewValue (const QVariant &new_value)
QPropertyUndoCommand::setNewValue Set the new value of the property (set with redo) to new_value.
void enableAnimation (bool animate=true)
QPropertyUndoCommand::enableAnimation True to enable animation.
void setAnimated (bool animate=true, bool first_time=true)
QPropertyUndoCommand::setAnimated.
int id () const override
bool mergeWith (const QUndoCommand *other) override
QPropertyUndoCommand::mergeWith Try to merge this command with other command.
void redo () override
QPropertyUndoCommand::redo Redo this command.
void undo () override
QPropertyUndoCommand::undo Undo this command.
Private Attributes
QObject * m_object = nullptr
const char * m_property_name
QVariant m_old_value
QVariant m_new_value
bool m_animate = false
bool m_first_time = true
Detailed Description
The QPropertyUndoCommand class This undo command manage QProperty of a QObject. This undo command can use QPropertyAnimation to animate the change when undo/redo is call To use animation call setAnimated(true). By default animation is disable. Some QVariant date can't be animated and result this command don't work.
Definition at line 33 of file qpropertyundocommand.h.
Constructor & Destructor Documentation
QPropertyUndoCommand() [1/3]
QPropertyUndoCommand::QPropertyUndoCommand (QObject * object, const char * property_name, const QVariant & old_value, const QVariant & new_value, QUndoCommand * parent = nullptr)
QPropertyUndoCommand::QPropertyUndoCommand Default constructor with old and new value This command don't take ownership of object.
Parameters
object
property_name
old_value
new_value
parent
Definition at line 31 of file qpropertyundocommand.cpp.
QPropertyUndoCommand() [2/3]
QPropertyUndoCommand::QPropertyUndoCommand (QObject * object, const char * property_name, const QVariant & old_value, QUndoCommand * parent = nullptr)
QPropertyUndoCommand::QPropertyUndoCommand Default constructor with old value. Call setNewValue to setup the new value of the edited QObject This command don't take ownership of object.
Parameters
object
property_name
old_value
parent
Definition at line 53 of file qpropertyundocommand.cpp.
QPropertyUndoCommand() [3/3]
QPropertyUndoCommand::QPropertyUndoCommand (const QPropertyUndoCommand * other)
QPropertyUndoCommand::QPropertyUndoCommand.
Parameters
other
Definition at line 67 of file qpropertyundocommand.cpp.
References m_animate, m_first_time, m_new_value, m_object, m_old_value, and m_property_name.
Member Function Documentation
enableAnimation()
void QPropertyUndoCommand::enableAnimation (bool animate = true)
QPropertyUndoCommand::enableAnimation True to enable animation.
Parameters
animate
Definition at line 92 of file qpropertyundocommand.cpp.
References m_animate.
Referenced by ImagePropertiesWidget::associatedUndo(), RectangleEditor::editingFinished(), ElementTextsMover::endMovement(), PartEllipse::handlerMousePressEvent(), PartArc::handlerMousePressEvent(), PartLine::handlerMousePressEvent(), RectangleEditor::heightChanged(), ElementScene::keyPressEvent(), LineEditor::lineEditingFinishedX1(), LineEditor::lineEditingFinishedX2(), LineEditor::lineEditingFinishedY1(), LineEditor::lineEditingFinishedY2(), CustomElementGraphicPart::mouseReleaseEvent(), ArcEditor::updateArcA(), ArcEditor::updateArcRectH(), ArcEditor::updateArcRectV(), ArcEditor::updateArcRectX(), ArcEditor::updateArcRectY(), ArcEditor::updateArcS(), LineEditor::updateLineEndLength1(), LineEditor::updateLineEndLength2(), TerminalEditor::updateXPos(), TerminalEditor::updateYPos(), RectangleEditor::widthChanged(), RectangleEditor::xPosChanged(), and RectangleEditor::yPosChanged().
id()
int QPropertyUndoCommand::id () const inline override
Definition at line 51 of file qpropertyundocommand.h.
mergeWith()
bool QPropertyUndoCommand::mergeWith (const QUndoCommand * other) override
QPropertyUndoCommand::mergeWith Try to merge this command with other command.
Parameters
other
Returns
true if was merged, else false
Definition at line 115 of file qpropertyundocommand.cpp.
References m_new_value, m_object, m_property_name, and undo().
redo()
void QPropertyUndoCommand::redo () override
QPropertyUndoCommand::redo Redo this command.
Definition at line 129 of file qpropertyundocommand.cpp.
References m_animate, m_first_time, m_new_value, m_object, m_old_value, and m_property_name.
setAnimated()
void QPropertyUndoCommand::setAnimated (bool animate = true, bool first_time = true)
QPropertyUndoCommand::setAnimated.
Parameters
animate = true for animate this undo
first_time = if true, the first animation is done at the first call of redo if false, the first animation is done at the second call of redo.
Definition at line 103 of file qpropertyundocommand.cpp.
References m_animate, and m_first_time.
Referenced by IndiTextPropertiesWidget::associatedUndo(), RectangleEditor::editingFinished(), PartRectangle::handlerMouseReleaseEvent(), QetShapeItem::handlerMouseReleaseEvent(), DynamicElementTextModel::undoForEditedGroup(), DynamicElementTextModel::undoForEditedText(), RectangleEditor::xRadiusChanged(), and RectangleEditor::yRadiusChanged().
setNewValue()
void QPropertyUndoCommand::setNewValue (const QVariant & new_value)
QPropertyUndoCommand::setNewValue Set the new value of the property (set with redo) to new_value.
Parameters
new_value
Definition at line 83 of file qpropertyundocommand.cpp.
References m_new_value.
Referenced by PartEllipse::handlerMouseReleaseEvent(), PartArc::handlerMouseReleaseEvent(), PartPolygon::handlerMouseReleaseEvent(), and PartLine::handlerMouseReleaseEvent().
undo()
void QPropertyUndoCommand::undo () override
QPropertyUndoCommand::undo Undo this command.
Definition at line 154 of file qpropertyundocommand.cpp.
References m_animate, m_new_value, m_object, m_old_value, and m_property_name.
Referenced by mergeWith().
Member Data Documentation
m_animate
bool QPropertyUndoCommand::m_animate = false private
Definition at line 60 of file qpropertyundocommand.h.
Referenced by enableAnimation(), QPropertyUndoCommand(), redo(), setAnimated(), and undo().
m_first_time
bool QPropertyUndoCommand::m_first_time = true private
Definition at line 61 of file qpropertyundocommand.h.
Referenced by QPropertyUndoCommand(), redo(), and setAnimated().
m_new_value
QVariant QPropertyUndoCommand::m_new_value private
Definition at line 59 of file qpropertyundocommand.h.
Referenced by mergeWith(), QPropertyUndoCommand(), redo(), setNewValue(), and undo().
m_object
QObject* QPropertyUndoCommand::m_object = nullptr private
Definition at line 57 of file qpropertyundocommand.h.
Referenced by mergeWith(), QPropertyUndoCommand(), redo(), and undo().
m_old_value
QVariant QPropertyUndoCommand::m_old_value private
Definition at line 59 of file qpropertyundocommand.h.
Referenced by QPropertyUndoCommand(), redo(), and undo().
m_property_name
const char* QPropertyUndoCommand::m_property_name private
Definition at line 58 of file qpropertyundocommand.h.
Referenced by mergeWith(), QPropertyUndoCommand(), redo(), and undo().
The documentation for this class was generated from the following files:
qpropertyundocommand.h
qpropertyundocommand.cpp