QElectroTech: ElementCollectionItem Class Reference
ElementCollectionItem Class Reference abstract
The ElementCollectionItem class This class represent a item (a directory or an element) in a element collection. This class must be herited for specialisation. This item is used by ElementsCollectionModel for manage the elements collection.
#include <elementcollectionitem.h>
Public Types
enum { Type = UserType+1 }
Public Member Functions
ElementCollectionItem ()
ElementCollectionItem::ElementCollectionItem Constructor.
int type () const override
virtual bool isDir () const =0
virtual bool isElement () const =0
virtual QString localName ()=0
virtual QString name () const =0
virtual QString collectionPath () const =0
virtual bool isCollectionRoot () const =0
virtual void addChildAtPath (const QString &collection_name)=0
virtual void setUpData ()=0
virtual void setUpIcon ()=0
virtual void clearData ()
ElementCollectionItem::clearData Reset the data.
ElementCollectionItem * lastItemForPath (const QString &path, QString &no_found_path)
ElementCollectionItem::lastItemForPath Return the last existing item in this ElementCollectionItem hierarchy according to the given path. Next_item is the first non existing item in this hierarchy according to the given path.
ElementCollectionItem * childWithCollectionName (const QString &name) const
ElementCollectionItem::childWithCollectionName Return the child with the collection name name, else return nullptr.
QList< QStandardItem * > directChilds () const
ElementCollectionItem::directChilds Return the direct child of this item.
int rowForInsertItem (const QString &name)
ElementCollectionItem::rowForInsertItem Return the row for insert a new child item to this item with name.
ElementCollectionItem * itemAtPath (const QString &path)
ElementCollectionItem::itemAtPath.
QList< ElementCollectionItem * > elementsDirectChild () const
ElementCollectionItem::elementsDirectChild.
QList< ElementCollectionItem * > directoriesDirectChild () const
ElementCollectionItem::directoriesDirectChild.
QList< ElementCollectionItem * > elementsChild () const
ElementCollectionItem::elementsChild.
QList< ElementCollectionItem * > directoriesChild () const
ElementCollectionItem::directoriesChild.
QList< ElementCollectionItem * > items () const
ElementCollectionItem::items.
Detailed Description
The ElementCollectionItem class This class represent a item (a directory or an element) in a element collection. This class must be herited for specialisation. This item is used by ElementsCollectionModel for manage the elements collection.
Definition at line 29 of file elementcollectionitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 34 of file elementcollectionitem.h.
Constructor & Destructor Documentation
ElementCollectionItem()
ElementCollectionItem::ElementCollectionItem ()
ElementCollectionItem::ElementCollectionItem Constructor.
Definition at line 25 of file elementcollectionitem.cpp.
Member Function Documentation
addChildAtPath()
virtual void ElementCollectionItem::addChildAtPath (const QString & collection_name) pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
Referenced by ElementsCollectionModel::addLocation(), and ElementsCollectionModel::elementIntegratedToCollection().
childWithCollectionName()
ElementCollectionItem * ElementCollectionItem::childWithCollectionName (const QString & name) const
ElementCollectionItem::childWithCollectionName Return the child with the collection name name, else return nullptr.
Parameters
name
Returns
Definition at line 81 of file elementcollectionitem.cpp.
References directChilds(), and name().
Referenced by itemAtPath(), and lastItemForPath().
clearData()
void ElementCollectionItem::clearData () virtual
ElementCollectionItem::clearData Reset the data.
Definition at line 32 of file elementcollectionitem.cpp.
Referenced by ElementsCollectionWidget::editDirectory(), and ElementsCollectionModel::updateItem().
collectionPath()
virtual QString ElementCollectionItem::collectionPath () const pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
Referenced by ElementsCollectionModel::canDropMimeData(), FileElementCollectionItem::collectionPath(), ElementsCollectionWidget::deleteDirectory(), ElementsCollectionWidget::deleteElement(), ElementsCollectionWidget::dirProperties(), ElementsCollectionWidget::editElement(), ElementDialog::indexClicked(), ElementsCollectionModel::mimeData(), and NewElementWizard::validStep1().
directChilds()
QList< QStandardItem * > ElementCollectionItem::directChilds () const
ElementCollectionItem::directChilds Return the direct child of this item.
Returns
Definition at line 99 of file elementcollectionitem.cpp.
Referenced by childWithCollectionName(), directoriesDirectChild(), and elementsDirectChild().
directoriesChild()
QList< ElementCollectionItem * > ElementCollectionItem::directoriesChild () const
ElementCollectionItem::directoriesChild.
Returns
Every directories child (direct and indirect) of this item
Definition at line 221 of file elementcollectionitem.cpp.
References directoriesChild(), and directoriesDirectChild().
Referenced by directoriesChild(), ElementsCollectionWidget::dirProperties(), and elementsChild().
directoriesDirectChild()
QList< ElementCollectionItem * > ElementCollectionItem::directoriesDirectChild () const
ElementCollectionItem::directoriesDirectChild.
Returns
the direct directory child of this item
Definition at line 190 of file elementcollectionitem.cpp.
References directChilds(), and isDir().
Referenced by directoriesChild(), and rowForInsertItem().
elementsChild()
QList< ElementCollectionItem * > ElementCollectionItem::elementsChild () const
ElementCollectionItem::elementsChild.
Returns
Every elements child (direct and indirect) of this item
Definition at line 207 of file elementcollectionitem.cpp.
References directoriesChild(), and elementsDirectChild().
Referenced by ElementsCollectionWidget::dirProperties().
elementsDirectChild()
QList< ElementCollectionItem * > ElementCollectionItem::elementsDirectChild () const
ElementCollectionItem::elementsDirectChild.
Returns
The direct element child of this item
Definition at line 173 of file elementcollectionitem.cpp.
References directChilds(), and isElement().
Referenced by elementsChild(), and rowForInsertItem().
isCollectionRoot()
virtual bool ElementCollectionItem::isCollectionRoot () const pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
Referenced by FileElementCollectionItem::collectionPath().
isDir()
virtual bool ElementCollectionItem::isDir () const pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
Referenced by ElementsCollectionWidget::customContextMenu(), directoriesDirectChild(), ElementsCollectionWidget::dirProperties(), and NewElementWizard::validStep1().
isElement()
virtual bool ElementCollectionItem::isElement () const pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
Referenced by ElementsCollectionWidget::customContextMenu(), ElementsCollectionWidget::editElement(), elementsDirectChild(), ElementsCollectionModel::hideElement(), and ElementsCollectionModel::mimeData().
itemAtPath()
ElementCollectionItem * ElementCollectionItem::itemAtPath (const QString & path)
ElementCollectionItem::itemAtPath.
Parameters
path
Returns
the item at path or nullptr if doesn't exist
Definition at line 151 of file elementcollectionitem.cpp.
References childWithCollectionName().
Referenced by ElementsCollectionModel::indexFromLocation().
items()
QList< ElementCollectionItem * > ElementCollectionItem::items () const
ElementCollectionItem::items.
Returns
every childs of this item (direct and indirect childs)
Definition at line 237 of file elementcollectionitem.cpp.
References items().
Referenced by ElementsCollectionModel::items(), items(), and ElementsCollectionModel::projectItems().
lastItemForPath()
ElementCollectionItem * ElementCollectionItem::lastItemForPath (const QString & path, QString & no_found_path)
ElementCollectionItem::lastItemForPath Return the last existing item in this ElementCollectionItem hierarchy according to the given path. Next_item is the first non existing item in this hierarchy according to the given path.
Parameters
path : The path to find last item. The path must be in form : path/otherPath/.../.../myElement.elmt.
no_found_path : The first item that not exist in this hierarchy
Returns
: The last item that exist in this hierarchy, or nullptr can't find (an error was occurred, or path already exist)
Definition at line 52 of file elementcollectionitem.cpp.
References childWithCollectionName().
Referenced by ElementsCollectionModel::addLocation(), and ElementsCollectionModel::elementIntegratedToCollection().
localName()
virtual QString ElementCollectionItem::localName () pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
Referenced by ElementsCollectionWidget::dirProperties(), and ElementsCollectionWidget::setUpConnection().
name()
virtual QString ElementCollectionItem::name () const pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
Referenced by childWithCollectionName(), and rowForInsertItem().
rowForInsertItem()
int ElementCollectionItem::rowForInsertItem (const QString & name)
ElementCollectionItem::rowForInsertItem Return the row for insert a new child item to this item with name.
Parameters
name
Returns
If row can't be found (name is null, or already exist) return -1;
Definition at line 116 of file elementcollectionitem.cpp.
References directoriesDirectChild(), elementsDirectChild(), and name().
Referenced by XmlProjectElementCollectionItem::addChildAtPath(), and FileElementCollectionItem::addChildAtPath().
setUpData()
virtual void ElementCollectionItem::setUpData () pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
Referenced by setUpData(), and ElementsCollectionModel::updateItem().
setUpIcon()
virtual void ElementCollectionItem::setUpIcon () pure virtual
Implemented in FileElementCollectionItem, and XmlProjectElementCollectionItem.
type()
int ElementCollectionItem::type () const inline override
Definition at line 35 of file elementcollectionitem.h.
References Type.
Referenced by ElementsCollectionModel::addLocation(), ElementsCollectionWidget::customContextMenu(), ElementsCollectionWidget::dirProperties(), ElementsCollectionWidget::editDirectory(), ElementsCollectionModel::indexFromLocation(), ElementsCollectionWidget::newDirectory(), ElementsCollectionWidget::newElement(), and ElementsCollectionWidget::openDir().
The documentation for this class was generated from the following files:
elementcollectionitem.h
elementcollectionitem.cpp