QElectroTech: DynamicElementTextModel Class Reference
DynamicElementTextModel Class Reference
The DynamicElementTextModel class A model to use with QtView. This model display and can edit the value of dynamic text of an element. Set the delegate DynamicTextItemDelegate as delegate of this model.
#include <dynamicelementtextmodel.h>
Public Types
enum ValueType {
textFrom =1, userText, infoText, compositeText,
txtAlignment, size, font, color,
pos, frame, rotation, textWidth,
grpAlignment, grpPos, grpRotation, grpVAdjust,
grpName, grpHoldBottom, grpFrame
}
Signals
void dataChanged ()
Public Member Functions
DynamicElementTextModel (Element *element, QObject *parent=nullptr)
~DynamicElementTextModel () override
bool indexIsInGroup (const QModelIndex &index) const
DynamicElementTextModel::indexIsInGroup.
DynamicElementTextItem * textFromIndex (const QModelIndex &index) const
DynamicElementTextModel::textFromIndex.
DynamicElementTextItem * textFromItem (QStandardItem *item) const
DynamicElementTextModel::textFromItem.
QModelIndex indexFromText (DynamicElementTextItem *text) const
DynamicElementTextModel::indexFromText.
QUndoCommand * undoForEditedText (DynamicElementTextItem *deti, QUndoCommand *parent_undo=nullptr) const
DynamicElementTextModel::undoForEditedText.
QUndoCommand * undoForEditedGroup (ElementTextItemGroup *group, QUndoCommand *parent_undo=nullptr) const
DynamicElementTextModel::undoForEditedGroup.
ElementTextItemGroup * groupFromIndex (const QModelIndex &index) const
DynamicElementTextModel::groupFromIndex.
ElementTextItemGroup * groupFromItem (QStandardItem *item) const
DynamicElementTextModel::groupFromItem.
QModelIndex indexFromGroup (ElementTextItemGroup *group) const
DynamicElementTextModel::indexFromGroup.
bool indexIsText (const QModelIndex &index) const
DynamicElementTextModel::indexIsText.
bool indexIsGroup (const QModelIndex &index) const
DynamicElementTextModel::indexIsGroup.
bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const override
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
DynamicElementTextModel::dropMimeData.
QMimeData * mimeData (const QModelIndexList &indexes) const override
QStringList mimeTypes () const override
DynamicElementTextModel::mimeTypes.
Private Member Functions
QList< QStandardItem * > itemsForText (DynamicElementTextItem *deti)
DynamicElementTextModel::itemsForText.
void addText (DynamicElementTextItem *deti)
DynamicElementTextModel::addText.
void removeText (DynamicElementTextItem *deti)
DynamicElementTextModel::removeText.
void addGroup (ElementTextItemGroup *group)
DynamicElementTextModel::AddGroup Add a text item group to this model.
void removeGroup (ElementTextItemGroup *group)
DynamicElementTextModel::removeGroup Remove the text item group from this model.
void addTextToGroup (DynamicElementTextItem *deti, ElementTextItemGroup *group)
DynamicElementTextModel::textAddedToGroup Add the text text to the group group.
void removeTextFromGroup (DynamicElementTextItem *deti, ElementTextItemGroup *group)
void enableSourceText (DynamicElementTextItem *deti, DynamicElementTextItem::TextFrom tf)
DynamicElementTextModel::enableSourceText Enable the good field, according to the current source of text, for the edited text deti.
void enableGroupRotationAndPos (ElementTextItemGroup *group)
DynamicElementTextModel::enableGroupRotation Enable/disable the item "group rotation" according the option hold to bottom.
void itemDataChanged (QStandardItem *qsi)
void setConnection (DynamicElementTextItem *deti, bool set)
DynamicElementTextModel::setConnection Set up the connection for deti to keep up to date the data of this model and the text. Is notably use with the use of QUndoCommand.
void setConnection (ElementTextItemGroup *group, bool set)
DynamicElementTextModel::setConnection Set up the connection for group to keep up to date the data of this model and the group. Is notably use with the use of QUndoCommand.
void updateDataFromText (DynamicElementTextItem *deti, DynamicElementTextModel::ValueType type)
void updateDataFromGroup (ElementTextItemGroup *group, DynamicElementTextModel::ValueType type)
Private Attributes
QPointer< Element > m_element
QHash< DynamicElementTextItem *, QStandardItem * > m_texts_list
QHash< ElementTextItemGroup *, QStandardItem * > m_groups_list
QHash< DynamicElementTextItem *, QList< QMetaObject::Connection > > m_hash_text_connect
QHash< ElementTextItemGroup *, QList< QMetaObject::Connection > > m_hash_group_connect
bool m_block_dataChanged = false
Detailed Description
The DynamicElementTextModel class A model to use with QtView. This model display and can edit the value of dynamic text of an element. Set the delegate DynamicTextItemDelegate as delegate of this model.
Definition at line 35 of file dynamicelementtextmodel.h.
Member Enumeration Documentation
ValueType
enum DynamicElementTextModel::ValueType
Enumerator
textFrom
userText
infoText
compositeText
txtAlignment
size
font
color
pos
frame
rotation
textWidth
grpAlignment
grpPos
grpRotation
grpVAdjust
grpName
grpHoldBottom
grpFrame
Definition at line 40 of file dynamicelementtextmodel.h.
Constructor & Destructor Documentation
DynamicElementTextModel()
DynamicElementTextModel::DynamicElementTextModel (Element * element, QObject * parent = nullptr)
Definition at line 60 of file dynamicelementtextmodel.cpp.
References addGroup(), addText(), addTextToGroup(), QET::Horizontal, itemDataChanged(), itemsForText(), m_element, removeGroup(), removeText(), removeTextFromGroup(), Element::textAdded(), Element::textAddedToGroup(), Element::textRemoved(), Element::textRemovedFromGroup(), Element::textsGroupAboutToBeRemoved(), Element::textsGroupAdded(), and QET::Icons::tr.
~DynamicElementTextModel()
DynamicElementTextModel::~DynamicElementTextModel () override
Definition at line 84 of file dynamicelementtextmodel.cpp.
References m_hash_group_connect, m_hash_text_connect, and setConnection().
Member Function Documentation
addGroup()
void DynamicElementTextModel::addGroup (ElementTextItemGroup * group) private
DynamicElementTextModel::AddGroup Add a text item group to this model.
Parameters
group
Definition at line 691 of file dynamicelementtextmodel.cpp.
References ElementTextItemGroup::alignment, enableGroupRotationAndPos(), ElementTextItemGroup::frame, grpAlignment, grpFrame, grpHoldBottom, grpPos, grpRotation, grpVAdjust, ElementTextItemGroup::holdToBottomPage, itemsForText(), m_groups_list, ElementTextItemGroup::name, ElementTextItemGroup::pos, ElementTextItemGroup::rotation, setConnection(), QET::Icons::textGroup, ElementTextItemGroup::texts(), QET::Icons::tr, and ElementTextItemGroup::verticalAdjustment.
Referenced by DynamicElementTextModel().
addText()
void DynamicElementTextModel::addText (DynamicElementTextItem * deti) private
DynamicElementTextModel::addText.
Parameters
deti
Definition at line 377 of file dynamicelementtextmodel.cpp.
References itemsForText().
Referenced by DynamicElementTextModel().
addTextToGroup()
void DynamicElementTextModel::addTextToGroup (DynamicElementTextItem * deti, ElementTextItemGroup * group) private
DynamicElementTextModel::textAddedToGroup Add the text text to the group group.
Parameters
deti
group
Definition at line 859 of file dynamicelementtextmodel.cpp.
References itemsForText(), and m_groups_list.
Referenced by DynamicElementTextModel().
canDropMimeData()
bool DynamicElementTextModel::canDropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) const override
Definition at line 1001 of file dynamicelementtextmodel.cpp.
References indexIsInGroup(), and m_element.
dataChanged
void DynamicElementTextModel::dataChanged () signal
Referenced by itemDataChanged(), and DynamicElementTextItemEditor::setElement().
dropMimeData()
bool DynamicElementTextModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) override
DynamicElementTextModel::dropMimeData.
Parameters
data
action
row
column
parent
Returns
In any case return false, for overwrite the default behavior of model.
Definition at line 1062 of file dynamicelementtextmodel.cpp.
References groupFromIndex(), indexIsInGroup(), m_element, and QET::Icons::tr.
enableGroupRotationAndPos()
void DynamicElementTextModel::enableGroupRotationAndPos (ElementTextItemGroup * group) private
DynamicElementTextModel::enableGroupRotation Enable/disable the item "group rotation" according the option hold to bottom.
Parameters
group
Definition at line 1232 of file dynamicelementtextmodel.cpp.
References ElementTextItemGroup::holdToBottomPage, m_groups_list, rot_grp_row, x_grp_row, and y_grp_row.
Referenced by addGroup(), and updateDataFromGroup().
enableSourceText()
void DynamicElementTextModel::enableSourceText (DynamicElementTextItem * deti, DynamicElementTextItem::TextFrom tf) private
DynamicElementTextModel::enableSourceText Enable the good field, according to the current source of text, for the edited text deti.
Parameters
deti
tf
Definition at line 1199 of file dynamicelementtextmodel.cpp.
References compo_txt_row, DynamicElementTextItem::CompositeText, DynamicElementTextItem::ElementInfo, info_txt_row, m_texts_list, DynamicElementTextItem::UserText, and usr_txt_row.
Referenced by itemDataChanged(), itemsForText(), and updateDataFromText().
groupFromIndex()
ElementTextItemGroup * DynamicElementTextModel::groupFromIndex (const QModelIndex & index) const
DynamicElementTextModel::groupFromIndex.
Parameters
index
Returns
the group associated with index. Return value can be nullptr Index can be a child of an index associated with a group and can be the column 0 or 1.
Definition at line 887 of file dynamicelementtextmodel.cpp.
References groupFromItem().
Referenced by dropMimeData(), and DynamicElementTextItemEditor::on_m_remove_selection_clicked().
groupFromItem()
ElementTextItemGroup * DynamicElementTextModel::groupFromItem (QStandardItem * item) const
DynamicElementTextModel::groupFromItem.
Parameters
item
Returns
the group associated with item. Return value can be nullptr item can be a child of an item associated with a group and can be the column 0 or 1.
Definition at line 906 of file dynamicelementtextmodel.cpp.
References m_groups_list.
Referenced by groupFromIndex(), and itemDataChanged().
indexFromGroup()
QModelIndex DynamicElementTextModel::indexFromGroup (ElementTextItemGroup * group) const
DynamicElementTextModel::indexFromGroup.
Parameters
group
Returns
The index associated to the group group or a default QModelIndex if not match
Definition at line 933 of file dynamicelementtextmodel.cpp.
References m_groups_list.
Referenced by DynamicElementTextItemEditor::setCurrentGroup().
indexFromText()
QModelIndex DynamicElementTextModel::indexFromText (DynamicElementTextItem * text) const
DynamicElementTextModel::indexFromText.
Parameters
text
Returns
the QModelIndex for text, or a default QModelIndex if not match
Definition at line 478 of file dynamicelementtextmodel.cpp.
References m_texts_list.
Referenced by DynamicElementTextItemEditor::setCurrentText().
indexIsGroup()
bool DynamicElementTextModel::indexIsGroup (const QModelIndex & index) const
DynamicElementTextModel::indexIsGroup.
Parameters
index
Returns
True if index represente a group, both for the column 0 and 1. Return false if index is a child of an index associated to a group.
Definition at line 978 of file dynamicelementtextmodel.cpp.
References m_groups_list.
Referenced by DynamicElementTextItemEditor::on_m_tree_view_clicked().
indexIsInGroup()
bool DynamicElementTextModel::indexIsInGroup (const QModelIndex & index) const
DynamicElementTextModel::indexIsInGroup.
Parameters
index
Returns
True if the index represent a group or an item in a group
Definition at line 99 of file dynamicelementtextmodel.cpp.
References m_groups_list.
Referenced by canDropMimeData(), and dropMimeData().
indexIsText()
bool DynamicElementTextModel::indexIsText (const QModelIndex & index) const
DynamicElementTextModel::indexIsText.
Parameters
index
Returns
True if index represente a text, both for the column 0 and 1. Return false if index is a child of an index associated to a text.
Definition at line 948 of file dynamicelementtextmodel.cpp.
References m_texts_list.
Referenced by DynamicElementTextItemEditor::on_m_tree_view_clicked().
itemDataChanged()
void DynamicElementTextModel::itemDataChanged (QStandardItem * qsi) private
Definition at line 1269 of file dynamicelementtextmodel.cpp.
References compo_txt_row, compositeText, DynamicElementTextItem::CompositeText, dataChanged(), DynamicElementTextItem::ElementInfo, Element::elementInformations(), DynamicElementTextItem::elementUseForInfo(), enableSourceText(), groupFromItem(), info_txt_row, infoText, m_block_dataChanged, m_groups_list, m_texts_list, autonum::AssignVariables::replaceVariable(), textFrom, textFromItem(), QET::Icons::tr, DynamicElementTextItem::updateXref(), userText, DynamicElementTextItem::UserText, usr_txt_row, and DiagramContext::value().
Referenced by DynamicElementTextModel().
itemsForText()
QList< QStandardItem * > DynamicElementTextModel::itemsForText (DynamicElementTextItem * deti) private
DynamicElementTextModel::itemsForText.
Parameters
deti
Returns
The items for the text deti, if the text deti is already managed by this model the returned list is empty The returned items haven't got the same number of childs if the text is in a group or not.
Definition at line 124 of file dynamicelementtextmodel.cpp.
References DiagramTextItem::alignment, DiagramTextItem::color, color, DynamicElementTextItem::compositeText, compositeText, DynamicElementTextItem::ElementInfo, Element::elementInformations(), QETApp::elementTranslatedInfoKey(), DynamicElementTextItem::elementUseForInfo(), enableSourceText(), DiagramTextItem::font, font, DynamicElementTextItem::frame, frame, DynamicElementTextItem::infoName, infoText, m_texts_list, DynamicElementTextItem::parentGroup(), QET::Icons::PartText, pos, autonum::AssignVariables::replaceVariable(), rotation, setConnection(), size, textFrom, DynamicElementTextItem::textFrom, DynamicElementTextItem::textWidth, textWidth, QET::Icons::tr, txtAlignment, userText, and DynamicElementTextItem::UserText.
Referenced by addGroup(), addText(), addTextToGroup(), and DynamicElementTextModel().
mimeData()
QMimeData * DynamicElementTextModel::mimeData (const QModelIndexList & indexes) const override
Definition at line 1159 of file dynamicelementtextmodel.cpp.
References m_texts_list, and DynamicElementTextItem::uuid().
mimeTypes()
QStringList DynamicElementTextModel::mimeTypes () const override
DynamicElementTextModel::mimeTypes.
Returns
Definition at line 1185 of file dynamicelementtextmodel.cpp.
removeGroup()
void DynamicElementTextModel::removeGroup (ElementTextItemGroup * group) private
DynamicElementTextModel::removeGroup Remove the text item group from this model.
Parameters
group
Definition at line 842 of file dynamicelementtextmodel.cpp.
References m_groups_list, and setConnection().
Referenced by DynamicElementTextModel().
removeText()
void DynamicElementTextModel::removeText (DynamicElementTextItem * deti) private
DynamicElementTextModel::removeText.
Parameters
deti
Definition at line 386 of file dynamicelementtextmodel.cpp.
References m_texts_list, and setConnection().
Referenced by DynamicElementTextModel().
removeTextFromGroup()
void DynamicElementTextModel::removeTextFromGroup (DynamicElementTextItem * deti, ElementTextItemGroup * group) private
Definition at line 866 of file dynamicelementtextmodel.cpp.
References m_texts_list.
Referenced by DynamicElementTextModel().
setConnection() [1/2]
void DynamicElementTextModel::setConnection (DynamicElementTextItem * deti, bool set) private
DynamicElementTextModel::setConnection Set up the connection for deti to keep up to date the data of this model and the text. Is notably use with the use of QUndoCommand.
Parameters
deti - text to setup connection
set - true = set connection - false unset connection
Definition at line 1342 of file dynamicelementtextmodel.cpp.
References color, DiagramTextItem::colorChanged(), compositeText, DynamicElementTextItem::compositeTextChanged(), font, DiagramTextItem::fontChanged(), frame, DynamicElementTextItem::frameChanged(), DynamicElementTextItem::infoNameChanged(), infoText, m_hash_text_connect, pos, rotation, DynamicElementTextItem::textChanged(), textFrom, DynamicElementTextItem::textFromChanged(), textWidth, DynamicElementTextItem::textWidthChanged(), updateDataFromText(), and userText.
Referenced by addGroup(), itemsForText(), removeGroup(), removeText(), and ~DynamicElementTextModel().
setConnection() [2/2]
void DynamicElementTextModel::setConnection (ElementTextItemGroup * group, bool set) private
DynamicElementTextModel::setConnection Set up the connection for group to keep up to date the data of this model and the group. Is notably use with the use of QUndoCommand.
Parameters
group group to setup the connection
set true = set connection - false unset connection
Definition at line 1383 of file dynamicelementtextmodel.cpp.
References ElementTextItemGroup::alignmentChanged(), ElementTextItemGroup::frameChanged(), grpAlignment, grpFrame, grpHoldBottom, grpName, grpPos, grpRotation, grpVAdjust, ElementTextItemGroup::holdToBottomPageChanged(), m_hash_group_connect, ElementTextItemGroup::rotationChanged(), updateDataFromGroup(), ElementTextItemGroup::verticalAdjustmentChanged(), ElementTextItemGroup::xChanged(), and ElementTextItemGroup::yChanged().
textFromIndex()
DynamicElementTextItem * DynamicElementTextModel::textFromIndex (const QModelIndex & index) const
DynamicElementTextModel::textFromIndex.
Parameters
index
Returns
the text associated with index. Returned value can be nullptr Index can be a child of an index associated with a text and can be the column 0 or 1.
Definition at line 404 of file dynamicelementtextmodel.cpp.
References textFromItem().
Referenced by DynamicTextItemDelegate::createEditor(), DynamicElementTextItemEditor::on_m_remove_selection_clicked(), and DynamicTextItemDelegate::setModelData().
textFromItem()
DynamicElementTextItem * DynamicElementTextModel::textFromItem (QStandardItem * item) const
DynamicElementTextModel::textFromItem.
Parameters
item
Returns
the text associated with item. Return value can be nullptr item can be a child of an item associated with a text and can be the column 0 or 1. Note can return nullptr
Definition at line 424 of file dynamicelementtextmodel.cpp.
References m_groups_list, and m_texts_list.
Referenced by itemDataChanged(), and textFromIndex().
undoForEditedGroup()
QUndoCommand * DynamicElementTextModel::undoForEditedGroup (ElementTextItemGroup * group, QUndoCommand * parent_undo = nullptr) const
DynamicElementTextModel::undoForEditedGroup.
Parameters
group
parent_undo
Returns
A QUndoCommand that describe all changes made for group. Each change made for group is append as a child of the returned QUndoCommand. In other word, if the returned QUndoCommand have no child, that mean there is no change.
Definition at line 625 of file dynamicelementtextmodel.cpp.
References adjust_grp_row, align_grp_row, ElementTextItemGroup::alignment, ElementTextItemGroup::frame, frame_grp_row, hold_to_bottom_grp_row, ElementTextItemGroup::holdToBottomPage, m_groups_list, ElementTextItemGroup::name, ElementTextItemGroup::pos, pos, rot_grp_row, ElementTextItemGroup::rotation, rotation, QPropertyUndoCommand::setAnimated(), QET::Icons::tr, ElementTextItemGroup::verticalAdjustment, x_grp_row, and y_grp_row.
Referenced by DynamicElementTextItemEditor::apply(), and DynamicElementTextItemEditor::associatedUndo().
undoForEditedText()
QUndoCommand * DynamicElementTextModel::undoForEditedText (DynamicElementTextItem * deti, QUndoCommand * parent_undo = nullptr) const
DynamicElementTextModel::undoForEditedText.
Parameters
deti
parent_undo
Returns
A QUndoCommand that describe all changes made for deti. Each change made for deti is append as a child of the returned QUndoCommand. In other word, if the returned QUndoCommand have no child, that mean there is no change.
Definition at line 496 of file dynamicelementtextmodel.cpp.
References align_txt_row, DiagramTextItem::alignment, DiagramTextItem::color, color, color_txt_row, compo_txt_row, DynamicElementTextItem::compositeText, DynamicElementTextItem::CompositeText, QET::correctAngle(), DynamicElementTextItem::ElementInfo, DiagramTextItem::font, font, font_txt_row, DynamicElementTextItem::frame, frame, frame_txt_row, info_txt_row, DynamicElementTextItem::infoName, m_texts_list, rot_txt_row, QPropertyUndoCommand::setAnimated(), size_txt_row, src_txt_row, DynamicElementTextItem::text, DynamicElementTextItem::textFrom, DynamicElementTextItem::textWidth, QET::Icons::tr, DynamicElementTextItem::UserText, usr_txt_row, width_txt_row, x_txt_row, and y_txt_row.
Referenced by DynamicElementTextItemEditor::apply(), and DynamicElementTextItemEditor::associatedUndo().
updateDataFromGroup()
void DynamicElementTextModel::updateDataFromGroup (ElementTextItemGroup * group, DynamicElementTextModel::ValueType type) private
Definition at line 1507 of file dynamicelementtextmodel.cpp.
References adjust_grp_row, align_grp_row, ElementTextItemGroup::alignment, enableGroupRotationAndPos(), ElementTextItemGroup::frame, frame_grp_row, grpAlignment, grpFrame, grpHoldBottom, grpName, grpPos, grpRotation, grpVAdjust, hold_to_bottom_grp_row, ElementTextItemGroup::holdToBottomPage, m_block_dataChanged, m_groups_list, ElementTextItemGroup::name, ElementTextItemGroup::pos, rot_grp_row, ElementTextItemGroup::rotation, QET::Icons::tr, ElementTextItemGroup::verticalAdjustment, x_grp_row, and y_grp_row.
Referenced by setConnection().
updateDataFromText()
void DynamicElementTextModel::updateDataFromText (DynamicElementTextItem * deti, DynamicElementTextModel::ValueType type) private
Definition at line 1414 of file dynamicelementtextmodel.cpp.
References DiagramTextItem::color, color, color_txt_row, compo_txt_row, DynamicElementTextItem::compositeText, compositeText, DynamicElementTextItem::CompositeText, DynamicElementTextItem::ElementInfo, QETApp::elementTranslatedInfoKey(), enableSourceText(), DiagramTextItem::font, font, font_txt_row, DynamicElementTextItem::frame, frame, frame_txt_row, info_txt_row, DynamicElementTextItem::infoName, infoText, m_block_dataChanged, m_texts_list, pos, rot_txt_row, rotation, size, size_txt_row, textFrom, DynamicElementTextItem::textFrom, DynamicElementTextItem::textWidth, textWidth, QET::Icons::tr, userText, DynamicElementTextItem::UserText, usr_txt_row, width_txt_row, x_txt_row, and y_txt_row.
Referenced by setConnection().
Member Data Documentation
m_block_dataChanged
bool DynamicElementTextModel::m_block_dataChanged = false private
Definition at line 127 of file dynamicelementtextmodel.h.
Referenced by itemDataChanged(), updateDataFromGroup(), and updateDataFromText().
m_element
QPointer<Element> DynamicElementTextModel::m_element private
Definition at line 120 of file dynamicelementtextmodel.h.
Referenced by canDropMimeData(), dropMimeData(), and DynamicElementTextModel().
m_groups_list
QHash<ElementTextItemGroup *, QStandardItem *> DynamicElementTextModel::m_groups_list private
Definition at line 122 of file dynamicelementtextmodel.h.
Referenced by addGroup(), addTextToGroup(), enableGroupRotationAndPos(), groupFromItem(), indexFromGroup(), indexIsGroup(), indexIsInGroup(), itemDataChanged(), removeGroup(), textFromItem(), undoForEditedGroup(), and updateDataFromGroup().
m_hash_group_connect
QHash<ElementTextItemGroup *, QList<QMetaObject::Connection> > DynamicElementTextModel::m_hash_group_connect private
Definition at line 126 of file dynamicelementtextmodel.h.
Referenced by setConnection(), and ~DynamicElementTextModel().
m_hash_text_connect
QHash<DynamicElementTextItem *, QList<QMetaObject::Connection> > DynamicElementTextModel::m_hash_text_connect private
Definition at line 124 of file dynamicelementtextmodel.h.
Referenced by setConnection(), and ~DynamicElementTextModel().
m_texts_list
QHash<DynamicElementTextItem *, QStandardItem *> DynamicElementTextModel::m_texts_list private
Definition at line 121 of file dynamicelementtextmodel.h.
Referenced by enableSourceText(), indexFromText(), indexIsText(), itemDataChanged(), itemsForText(), mimeData(), removeText(), removeTextFromGroup(), textFromItem(), undoForEditedText(), and updateDataFromText().
The documentation for this class was generated from the following files:
dynamicelementtextmodel.h
dynamicelementtextmodel.cpp