QElectroTech: TitleBlockTemplateLocationSaver Class Reference
TitleBlockTemplateLocationSaver Class Reference
#include <templatelocationsaver.h>
Public Member Functions
TitleBlockTemplateLocationSaver (const TitleBlockTemplateLocation &, QWidget *=nullptr)
TitleBlockTemplateLocationSaver::TitleBlockTemplateLocationSaver Constructor.
~TitleBlockTemplateLocationSaver () override
Public Member Functions inherited from TitleBlockTemplateLocationChooser
TitleBlockTemplateLocationChooser (const TitleBlockTemplateLocation &, QWidget *=nullptr)
TitleBlockTemplateLocationChooser::TitleBlockTemplateLocationChooser Constructor.
~TitleBlockTemplateLocationChooser () override
virtual TitleBlockTemplateLocation location () const
virtual TitleBlockTemplatesCollection * collection () const
Protected Slots
void updateTemplates () override
virtual void updateNewName ()
Protected Slots inherited from TitleBlockTemplateLocationChooser
virtual void updateCollections ()
virtual void updateTemplates ()
Protected Attributes
QLineEdit * new_name_
New template name textfield.
Protected Attributes inherited from TitleBlockTemplateLocationChooser
QFormLayout * form_layout_
QComboBox * collections_
QHash< int, TitleBlockTemplatesCollection * > collections_index_
Collections index within the combo box.
QComboBox * templates_
Existing templates combo box.
Private Member Functions
TitleBlockTemplateLocationSaver (const TitleBlockTemplateLocationSaver &)
QString name () const override
void setLocation (const TitleBlockTemplateLocation &) override
void init ()
Additional Inherited Members
Protected Member Functions inherited from TitleBlockTemplateLocationChooser
void init ()
virtual int indexForCollection (TitleBlockTemplatesCollection *) const
TitleBlockTemplateLocationChooser::indexForCollection.
Detailed Description
This class is a widget that allows the user to choose a target title block template, with the intention to save it. Therefore, compared to a TitleBlockTemplateLocationChooser, it includes an extra field for the user to set the name of the new template if needed.
Definition at line 30 of file templatelocationsaver.h.
Constructor & Destructor Documentation
TitleBlockTemplateLocationSaver() [1/2]
TitleBlockTemplateLocationSaver::TitleBlockTemplateLocationSaver (const TitleBlockTemplateLocation & location, QWidget * parent = nullptr)
TitleBlockTemplateLocationSaver::TitleBlockTemplateLocationSaver Constructor.
Parameters
location
parent : QWidget
Definition at line 29 of file templatelocationsaver.cpp.
References init(), TitleBlockTemplateLocationChooser::location(), and setLocation().
~TitleBlockTemplateLocationSaver()
TitleBlockTemplateLocationSaver::~TitleBlockTemplateLocationSaver () override
Destructor
Definition at line 42 of file templatelocationsaver.cpp.
TitleBlockTemplateLocationSaver() [2/2]
TitleBlockTemplateLocationSaver::TitleBlockTemplateLocationSaver (const TitleBlockTemplateLocationSaver &) private
Member Function Documentation
init()
void TitleBlockTemplateLocationSaver::init () private
Initialize this widget.
Parameters
location Initial location displayed by the widget
Definition at line 77 of file templatelocationsaver.cpp.
References TitleBlockTemplateLocationChooser::form_layout_, new_name_, TitleBlockTemplateLocationChooser::templates_, QET::Icons::tr, updateNewName(), and updateTemplates().
Referenced by TitleBlockTemplateLocationSaver().
name()
QString TitleBlockTemplateLocationSaver::name () const override private virtual
Returns
the currently selected/entered name
Reimplemented from TitleBlockTemplateLocationChooser.
Definition at line 48 of file templatelocationsaver.cpp.
References new_name_, and TitleBlockTemplateLocationChooser::templates_.
setLocation()
void TitleBlockTemplateLocationSaver::setLocation (const TitleBlockTemplateLocation & location) override private virtual
Set the location displayed by this widget
Parameters
location to be displayed by this widget
Reimplemented from TitleBlockTemplateLocationChooser.
Definition at line 57 of file templatelocationsaver.cpp.
References TitleBlockTemplateLocationChooser::collections_, TitleBlockTemplateLocationChooser::indexForCollection(), TitleBlockTemplateLocationChooser::location(), TitleBlockTemplateLocation::name(), TitleBlockTemplateLocation::parentCollection(), and TitleBlockTemplateLocationChooser::templates_.
Referenced by TitleBlockTemplateLocationSaver().
updateNewName
void TitleBlockTemplateLocationSaver::updateNewName () protected virtual slot
Enable or diable the "new name" text field depending of the selected template.
Definition at line 102 of file templatelocationsaver.cpp.
References new_name_, and TitleBlockTemplateLocationChooser::templates_.
Referenced by init(), and updateTemplates().
updateTemplates
void TitleBlockTemplateLocationSaver::updateTemplates () override protected slot
Update the templates list according to the selected collection.
Definition at line 87 of file templatelocationsaver.cpp.
References TitleBlockTemplateLocationChooser::collection(), TitleBlockTemplateLocationChooser::templates_, QET::Icons::tr, updateNewName(), and TitleBlockTemplateLocationChooser::updateTemplates().
Referenced by init().
Member Data Documentation
new_name_
QLineEdit* TitleBlockTemplateLocationSaver::new_name_ protected
New template name textfield.
Definition at line 54 of file templatelocationsaver.h.
Referenced by init(), name(), and updateNewName().
The documentation for this class was generated from the following files:
templatelocationsaver.h
templatelocationsaver.cpp