QElectroTech: PartLine Class Reference
PartLine Class Reference
#include <partline.h>
Public Types
enum { Type = UserType + 1104 }
Public Types inherited from CustomElementGraphicPart
enum LineStyle { NormalStyle, DashedStyle, DottedStyle, DashdottedStyle }
enum LineWeight {
NoneWeight, ThinWeight, NormalWeight, UltraWeight,
BigWeight
}
enum Filling {
NoneFilling, BlackFilling, WhiteFilling, GreenFilling,
RedFilling, BlueFilling, GrayFilling, BrunFilling,
YellowFilling, CyanFilling, MagentaFilling, LightgrayFilling,
OrangeFilling, PurpleFilling, HTMLPinkPinkFilling, HTMLPinkLightPinkFilling,
HTMLPinkHotPinkFilling, HTMLPinkDeepPinkFilling, HTMLPinkPaleVioletRedFilling, HTMLPinkMediumVioletRedFilling,
HTMLRedLightSalmonFilling, HTMLRedSalmonFilling, HTMLRedDarkSalmonFilling, HTMLRedLightCoralFilling,
HTMLRedIndianRedFilling, HTMLRedCrimsonFilling, HTMLRedFirebrickFilling, HTMLRedDarkRedFilling,
HTMLRedRedFilling, HTMLOrangeOrangeRedFilling, HTMLOrangeTomatoFilling, HTMLOrangeCoralFilling,
HTMLOrangeDarkOrangeFilling, HTMLOrangeOrangeFilling, HTMLYellowYellowFilling, HTMLYellowLightYellowFilling,
HTMLYellowLemonChiffonFilling, HTMLYellowLightGoldenrodYellowFilling, HTMLYellowPapayaWhipFilling, HTMLYellowMoccasinFilling,
HTMLYellowPeachPuffFilling, HTMLYellowPaleGoldenrodFilling, HTMLYellowKhakiFilling, HTMLYellowDarkKhakiFilling,
HTMLYellowGoldFilling, HTMLBrownCornsilkFilling, HTMLBrownBlanchedAlmondFilling, HTMLBrownBisqueFilling,
HTMLBrownNavajoWhiteFilling, HTMLBrownWheatFilling, HTMLBrownBurlywoodFilling, HTMLBrownTanFilling,
HTMLBrownRosyBrownFilling, HTMLBrownSandyBrownFilling, HTMLBrownGoldenrodFilling, HTMLBrownDarkGoldenrodFilling,
HTMLBrownPeruFilling, HTMLBrownChocolateFilling, HTMLBrownSaddleBrownFilling, HTMLBrownSiennaFilling,
HTMLBrownBrownFilling, HTMLBrownMaroonFilling, HTMLGreenDarkOliveGreenFilling, HTMLGreenOliveFilling,
HTMLGreenOliveDrabFilling, HTMLGreenYellowGreenFilling, HTMLGreenLimeGreenFilling, HTMLGreenLimeFilling,
HTMLGreenLawnGreenFilling, HTMLGreenChartreuseFilling, HTMLGreenGreenYellowFilling, HTMLGreenSpringGreenFilling,
HTMLGreenMediumSpringGreenFilling, HTMLGreenLightGreenFilling, HTMLGreenPaleGreenFilling, HTMLGreenDarkSeaGreenFilling,
HTMLGreenMediumAquamarineFilling, HTMLGreenMediumSeaGreenFilling, HTMLGreenSeaGreenFilling, HTMLGreenForestGreenFilling,
HTMLGreenGreenFilling, HTMLGreenDarkGreenFilling, HTMLCyanAquaFilling, HTMLCyanCyanFilling,
HTMLCyanLightCyanFilling, HTMLCyanPaleTurquoiseFilling, HTMLCyanAquamarineFilling, HTMLCyanTurquoiseFilling,
HTMLCyanMediumTurquoiseFilling, HTMLCyanDarkTurquoiseFilling, HTMLCyanLightSeaGreenFilling, HTMLCyanCadetBlueFilling,
HTMLCyanDarkCyanFilling, HTMLCyanTealFilling, HTMLBlueLightSteelBlueFilling, HTMLBluePowderBlueFilling,
HTMLBlueLightBlueFilling, HTMLBlueSkyBlueFilling, HTMLBlueLightSkyBlueFilling, HTMLBlueDeepSkyBlueFilling,
HTMLBlueDodgerBlueFilling, HTMLBlueCornflowerBlueFilling, HTMLBlueSteelBlueFilling, HTMLBlueRoyalBlueFilling,
HTMLBlueBlueFilling, HTMLBlueMediumBlueFilling, HTMLBlueDarkBlueFilling, HTMLBlueNavyFilling,
HTMLBlueMidnightBlueFilling, HTMLPurpleLavenderFilling, HTMLPurpleThistleFilling, HTMLPurplePlumFilling,
HTMLPurpleVioletFilling, HTMLPurpleOrchidFilling, HTMLPurpleFuchsiaFilling, HTMLPurpleMagentaFilling,
HTMLPurpleMediumOrchidFilling, HTMLPurpleMediumPurpleFilling, HTMLPurpleBlueVioletFilling, HTMLPurpleDarkVioletFilling,
HTMLPurpleDarkOrchidFilling, HTMLPurpleDarkMagentaFilling, HTMLPurplePurpleFilling, HTMLPurpleIndigoFilling,
HTMLPurpleDarkSlateBlueFilling, HTMLPurpleSlateBlueFilling, HTMLPurpleMediumSlateBlueFilling, HTMLWhiteWhiteFilling,
HTMLWhiteSnowFilling, HTMLWhiteHoneydewFilling, HTMLWhiteMintCreamFilling, HTMLWhiteAzureFilling,
HTMLWhiteAliceBlueFilling, HTMLWhiteGhostWhiteFilling, HTMLWhiteWhiteSmokeFilling, HTMLWhiteSeashellFilling,
HTMLWhiteBeigeFilling, HTMLWhiteOldLaceFilling, HTMLWhiteFloralWhiteFilling, HTMLWhiteIvoryFilling,
HTMLWhiteAntiqueWhiteFilling, HTMLWhiteLinenFilling, HTMLWhiteLavenderBlushFilling, HTMLWhiteMistyRoseFilling,
HTMLGrayGainsboroFilling, HTMLGrayLightGrayFilling, HTMLGraySilverFilling, HTMLGrayDarkGrayFilling,
HTMLGrayGrayFilling, HTMLGrayDimGrayFilling, HTMLGrayLightSlateGrayFilling, HTMLGraySlateGrayFilling,
HTMLGrayDarkSlateGrayFilling, HTMLGrayBlackFilling, HorFilling, VerFilling,
BdiagFilling, FdiagFilling
}
enum Color {
BlackColor, WhiteColor, GreenColor, RedColor,
BlueColor, GrayColor, BrunColor, YellowColor,
CyanColor, MagentaColor, LightgrayColor, OrangeColor,
PurpleColor, HTMLPinkPinkColor, HTMLPinkLightPinkColor, HTMLPinkHotPinkColor,
HTMLPinkDeepPinkColor, HTMLPinkPaleVioletRedColor, HTMLPinkMediumVioletRedColor, HTMLRedLightSalmonColor,
HTMLRedSalmonColor, HTMLRedDarkSalmonColor, HTMLRedLightCoralColor, HTMLRedIndianRedColor,
HTMLRedCrimsonColor, HTMLRedFirebrickColor, HTMLRedDarkRedColor, HTMLRedRedColor,
HTMLOrangeOrangeRedColor, HTMLOrangeTomatoColor, HTMLOrangeCoralColor, HTMLOrangeDarkOrangeColor,
HTMLOrangeOrangeColor, HTMLYellowYellowColor, HTMLYellowLightYellowColor, HTMLYellowLemonChiffonColor,
HTMLYellowLightGoldenrodYellowColor, HTMLYellowPapayaWhipColor, HTMLYellowMoccasinColor, HTMLYellowPeachPuffColor,
HTMLYellowPaleGoldenrodColor, HTMLYellowKhakiColor, HTMLYellowDarkKhakiColor, HTMLYellowGoldColor,
HTMLBrownCornsilkColor, HTMLBrownBlanchedAlmondColor, HTMLBrownBisqueColor, HTMLBrownNavajoWhiteColor,
HTMLBrownWheatColor, HTMLBrownBurlywoodColor, HTMLBrownTanColor, HTMLBrownRosyBrownColor,
HTMLBrownSandyBrownColor, HTMLBrownGoldenrodColor, HTMLBrownDarkGoldenrodColor, HTMLBrownPeruColor,
HTMLBrownChocolateColor, HTMLBrownSaddleBrownColor, HTMLBrownSiennaColor, HTMLBrownBrownColor,
HTMLBrownMaroonColor, HTMLGreenDarkOliveGreenColor, HTMLGreenOliveColor, HTMLGreenOliveDrabColor,
HTMLGreenYellowGreenColor, HTMLGreenLimeGreenColor, HTMLGreenLimeColor, HTMLGreenLawnGreenColor,
HTMLGreenChartreuseColor, HTMLGreenGreenYellowColor, HTMLGreenSpringGreenColor, HTMLGreenMediumSpringGreenColor,
HTMLGreenLightGreenColor, HTMLGreenPaleGreenColor, HTMLGreenDarkSeaGreenColor, HTMLGreenMediumAquamarineColor,
HTMLGreenMediumSeaGreenColor, HTMLGreenSeaGreenColor, HTMLGreenForestGreenColor, HTMLGreenGreenColor,
HTMLGreenDarkGreenColor, HTMLCyanAquaColor, HTMLCyanCyanColor, HTMLCyanLightCyanColor,
HTMLCyanPaleTurquoiseColor, HTMLCyanAquamarineColor, HTMLCyanTurquoiseColor, HTMLCyanMediumTurquoiseColor,
HTMLCyanDarkTurquoiseColor, HTMLCyanLightSeaGreenColor, HTMLCyanCadetBlueColor, HTMLCyanDarkCyanColor,
HTMLCyanTealColor, HTMLBlueLightSteelBlueColor, HTMLBluePowderBlueColor, HTMLBlueLightBlueColor,
HTMLBlueSkyBlueColor, HTMLBlueLightSkyBlueColor, HTMLBlueDeepSkyBlueColor, HTMLBlueDodgerBlueColor,
HTMLBlueCornflowerBlueColor, HTMLBlueSteelBlueColor, HTMLBlueRoyalBlueColor, HTMLBlueBlueColor,
HTMLBlueMediumBlueColor, HTMLBlueDarkBlueColor, HTMLBlueNavyColor, HTMLBlueMidnightBlueColor,
HTMLPurpleLavenderColor, HTMLPurpleThistleColor, HTMLPurplePlumColor, HTMLPurpleVioletColor,
HTMLPurpleOrchidColor, HTMLPurpleFuchsiaColor, HTMLPurpleMagentaColor, HTMLPurpleMediumOrchidColor,
HTMLPurpleMediumPurpleColor, HTMLPurpleBlueVioletColor, HTMLPurpleDarkVioletColor, HTMLPurpleDarkOrchidColor,
HTMLPurpleDarkMagentaColor, HTMLPurplePurpleColor, HTMLPurpleIndigoColor, HTMLPurpleDarkSlateBlueColor,
HTMLPurpleSlateBlueColor, HTMLPurpleMediumSlateBlueColor, HTMLWhiteWhiteColor, HTMLWhiteSnowColor,
HTMLWhiteHoneydewColor, HTMLWhiteMintCreamColor, HTMLWhiteAzureColor, HTMLWhiteAliceBlueColor,
HTMLWhiteGhostWhiteColor, HTMLWhiteWhiteSmokeColor, HTMLWhiteSeashellColor, HTMLWhiteBeigeColor,
HTMLWhiteOldLaceColor, HTMLWhiteFloralWhiteColor, HTMLWhiteIvoryColor, HTMLWhiteAntiqueWhiteColor,
HTMLWhiteLinenColor, HTMLWhiteLavenderBlushColor, HTMLWhiteMistyRoseColor, HTMLGrayGainsboroColor,
HTMLGrayLightGrayColor, HTMLGraySilverColor, HTMLGrayDarkGrayColor, HTMLGrayGrayColor,
HTMLGrayDimGrayColor, HTMLGrayLightSlateGrayColor, HTMLGraySlateGrayColor, HTMLGrayDarkSlateGrayColor,
HTMLGrayBlackColor, NoneColor
}
Signals
void lineChanged ()
void firstEndTypeChanged ()
void secondEndTypeChanged ()
void firstEndLengthChanged ()
void secondEndLengthChanged ()
Public Member Functions
PartLine (QETElementEditor *, QGraphicsItem *=nullptr)
PartLine::PartLine Constructor.
~PartLine () override
Destructeur.
int type () const override
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *=nullptr) override
PartLine::paint Draw this line.
QString name () const override
QString xmlName () const override
const QDomElement toXml (QDomDocument &) const override
PartLine::toXml Export this line in xml.
void fromXml (const QDomElement &) override
PartLine::fromXml Import the properties of this line from a xml element.
virtual QPointF sceneP1 () const
PartLine::sceneP1.
virtual QPointF sceneP2 () const
PartLine::sceneP2.
QPainterPath shape () const override
PartLine::shape.
QPainterPath shadowShape () const override
QRectF boundingRect () const override
PartLine::boundingRect.
bool isUseless () const override
PartLine::isUseless.
QRectF sceneGeometricRect () const override
PartLine::sceneGeometricRect.
void startUserTransformation (const QRectF &) override
PartLine::startUserTransformation Start the user-induced transformation, provided this primitive is contained within the initial_selection_rect bounding rectangle.
void handleUserTransformation (const QRectF &, const QRectF &) override
PartLine::handleUserTransformation Handle the user-induced transformation from initial_selection_rect to new_selection_rect.
QLineF line () const
void setLine (const QLineF &line)
Qet::EndType firstEndType () const
void setFirstEndType (const Qet::EndType &et)
Qet::EndType secondEndType () const
void setSecondEndType (const Qet::EndType &et)
qreal firstEndLength () const
void setFirstEndLength (const qreal &l)
qreal secondEndLength () const
void setSecondEndLength (const qreal &l)
Public Member Functions inherited from CustomElementGraphicPart
CustomElementGraphicPart (QETElementEditor *editor, QGraphicsItem *parent=nullptr)
CustomElementGraphicPart::CustomElementGraphicPart Default constructor. By default, item is selectable, send geometry change (Qt > 4.6), accept mouse left button and accept hover event.
~CustomElementGraphicPart () override
CustomElementGraphicPart::~CustomElementGraphicPart Destructor.
LineStyle lineStyle () const
void setLineStyle (const LineStyle ls)
CustomElementGraphicPart::setLineStyle Set line style to ls.
LineWeight lineWeight () const
void setLineWeight (const LineWeight lw)
CustomElementGraphicPart::setLineWeight Set line weight to lw.
qreal penWeight () const
CustomElementGraphicPart::penWeight.
Filling filling () const
void setFilling (const Filling f)
CustomElementGraphicPart::setFilling Set filling to f.
Color color () const
void setColor (const Color c)
CustomElementGraphicPart::setColor Set color to c.
bool antialiased () const
void setAntialiased (const bool b)
CustomElementGraphicPart::setAntialiased Set antialias to b.
void setProperty (const char *name, const QVariant &value) override
QVariant property (const char *name) const override
virtual void setHandlerColor (QPointF, const QColor &)
virtual void resetAllHandlerColor ()
Public Member Functions inherited from CustomElementPart
CustomElementPart (QETElementEditor *editor)
CustomElementPart Constructor.
virtual ~CustomElementPart ()
~CustomElementPart Destructor
virtual QETElementEditor * elementEditor () const
virtual void updateCurrentPartEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QGraphicsItem * toItem ()
virtual QET::ScalingMethod preferredScalingMethod () const
Static Public Member Functions
static uint requiredLengthForEndType (const Qet::EndType &)
PartLine::requiredLengthForEndType.
static QList< QPointF > fourEndPoints (const QPointF &, const QPointF &, const qreal &)
PartLine::fourEndPoints Return the four interesting point needed to draw the shape at extremity of line (circle, diamond, arrow, triangle) This points are in order : O : point on the line, at a distance 'length' of the extremity A : point on the line at a 'length' of 2x the extremity length B : point at a distance of length O - O is the projection of B on the line C : point at a distance of length O - O is the projection of C on the line.
Static Public Member Functions inherited from CustomElementGraphicPart
static void drawCross (const QPointF &center, QPainter *painter)
CustomElementGraphicPart::drawCross Draw a cross at pos center.
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
PartLine::itemChange.
bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
PartLine::sceneEventFilter.
Protected Member Functions inherited from CustomElementGraphicPart
void stylesToXml (QDomElement &) const
CustomElementGraphicPart::stylesToXml Write the curent style to xml element. The style are stored like this: name-of-style:value;name-of-style:value Each style separate by ; and name-style/value are separate by :
void stylesFromXml (const QDomElement &)
CustomElementGraphicPart::stylesFromXml Read the style used by this, from a xml element.
void resetStyles ()
CustomElementGraphicPart::resetStyles Reset the curent style to default, same style of default constructor.
void applyStylesToQPainter (QPainter &) const
CustomElementGraphicPart::applyStylesToQPainter Apply the current style to the QPainter.
void drawShadowShape (QPainter *painter)
CustomElementGraphicPart::drawShadowShape Draw a transparent blue shadow arround the shape of this item. The QPainterPathStroker used to draw shadows have a width of SHADOWS_HEIGHT Be carefull if penWeight of this item is to 0 the outline of strock is bigger of 0.5.
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
CustomElementGraphicPart::itemChange Reimplemented from QGraphicsObject. If the item position change call updateCurrentPartEditor() the change is always send to QGraphicsObject.
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
CustomElementGraphicPart::hoverEnterEvent Reimplemented from QGraphicsObject. Set m_hovered to true.
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
CustomElementGraphicPart::hoverLeaveEvent Reimplemented from QGraphicsObject. Set m_hovered to false.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions inherited from CustomElementPart
QList< QPointF > mapPoints (const QRectF &, const QRectF &, const QList< QPointF > &)
Properties
Qet::EndType end1
Qet::EndType end2
qreal length1
qreal length2
QLineF line
Properties inherited from CustomElementGraphicPart
LineStyle line_style
LineWeight line_weight
Filling filling
Color color
bool antialias
Private Member Functions
PartLine (const PartLine &)
void adjusteHandlerPos ()
PartLine::adjusteHandlerPos Adjust the position of the handler item.
void handlerMousePressEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
PartLine::handlerMousePressEvent.
void handlerMouseMoveEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
PartLine::handlerMouseMoveEvent.
void handlerMouseReleaseEvent (QetGraphicsHandlerItem *qghi, QGraphicsSceneMouseEvent *event)
PartLine::handlerMouseReleaseEvent.
void sceneSelectionChanged ()
PartLine::sceneSelectionChanged When the scene selection change, if there are several primitive selected, we remove the handler of this item.
void addHandler ()
PartLine::addHandler Add handlers for this item.
void removeHandler ()
PartLine::removeHandler Remove the handlers of this item.
QPainterPath path () const
PartLine::path.
QList< QPointF > fourShapePoints () const
PartLine::fourShapePoints.
QRectF firstEndCircleRect () const
PartLine::firstEndCircleRect.
QRectF secondEndCircleRect () const
PartLine::secondEndCircleRect.
void debugPaint (QPainter *)
PartLine::debugPaint Display several composante of the drawing -the bounding rect -special points at each extremity -the quadrature of the circle at each extremity, even if itself is an other type.
Private Attributes
Qet::EndType first_end
qreal first_length
Qet::EndType second_end
qreal second_length
QList< QPointF > saved_points_
QLineF m_line
int m_vector_index = -1
QPropertyUndoCommand * m_undo_command
QVector< QetGraphicsHandlerItem * > m_handler_vector
Additional Inherited Members
Protected Attributes inherited from CustomElementGraphicPart
bool m_hovered
Detailed Description
This class represents a line primitive which may be used to compose the drawing of an electrical element within the element editor. Lines may have specific visual ends (e.g. arrows) through the setFirstEndType and setSecondEndType methods. Their size can be defined using the setFirstEndLength and setSecondEndLength methods. Please note ends are not drawn if the required length for their drawing is longer than the line itself. In case there is room for a single end only, the first one get priority.
Definition at line 36 of file partline.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 63 of file partline.h.
Constructor & Destructor Documentation
PartLine() [1/2]
PartLine::PartLine (QETElementEditor * editor, QGraphicsItem * parent = nullptr)
PartLine::PartLine Constructor.
Parameters
editor : QETElementEditor of this part
parent : parent item
Definition at line 31 of file partline.cpp.
~PartLine()
PartLine::~PartLine () override
Destructeur.
Definition at line 41 of file partline.cpp.
References m_undo_command, and removeHandler().
PartLine() [2/2]
PartLine::PartLine (const PartLine &) private
Member Function Documentation
addHandler()
void PartLine::addHandler () private
PartLine::addHandler Add handlers for this item.
Definition at line 313 of file partline.cpp.
References QetGraphicsHandlerItem::handlerForPoint(), m_handler_vector, and m_line.
Referenced by itemChange(), and sceneSelectionChanged().
adjusteHandlerPos()
void PartLine::adjusteHandlerPos () private
PartLine::adjusteHandlerPos Adjust the position of the handler item.
Definition at line 226 of file partline.cpp.
References m_handler_vector, and m_line.
Referenced by handlerMouseMoveEvent(), itemChange(), and setLine().
boundingRect()
QRectF PartLine::boundingRect () const override
PartLine::boundingRect.
Returns
the bounding rect of this part
Definition at line 522 of file partline.cpp.
References first_end, m_line, path(), CustomElementGraphicPart::penWeight(), second_end, and SHADOWS_HEIGHT.
Referenced by debugPaint().
debugPaint()
void PartLine::debugPaint (QPainter * painter) private
PartLine::debugPaint Display several composante of the drawing -the bounding rect -special points at each extremity -the quadrature of the circle at each extremity, even if itself is an other type.
Parameters
painter
Definition at line 497 of file partline.cpp.
References boundingRect(), first_length, firstEndCircleRect(), fourEndPoints(), m_line, second_length, and secondEndCircleRect().
firstEndCircleRect()
QRectF PartLine::firstEndCircleRect () const private
PartLine::firstEndCircleRect.
Returns
the rectangle bordering the entirety of the first extremity
Definition at line 458 of file partline.cpp.
References first_length, fourEndPoints(), and m_line.
Referenced by debugPaint().
firstEndLength()
qreal PartLine::firstEndLength () const inline
Definition at line 93 of file partline.h.
References first_length.
firstEndLengthChanged
void PartLine::firstEndLengthChanged () signal
Referenced by setFirstEndLength(), and LineEditor::setUpChangeConnections().
firstEndType()
Qet::EndType PartLine::firstEndType () const inline
Definition at line 89 of file partline.h.
References first_end.
firstEndTypeChanged
void PartLine::firstEndTypeChanged () signal
Referenced by setFirstEndType(), and LineEditor::setUpChangeConnections().
fourEndPoints()
QList< QPointF > PartLine::fourEndPoints (const QPointF & end_point, const QPointF & other_point, const qreal & length) static
PartLine::fourEndPoints Return the four interesting point needed to draw the shape at extremity of line (circle, diamond, arrow, triangle) This points are in order : O : point on the line, at a distance 'length' of the extremity A : point on the line at a 'length' of 2x the extremity length B : point at a distance of length O - O is the projection of B on the line C : point at a distance of length O - O is the projection of C on the line.
Parameters
end_point : The concerned extremity
other_point : other needed point to define the line
length : length to use between the extremity and the point O
Returns
Definition at line 601 of file partline.cpp.
Referenced by debugPaint(), firstEndCircleRect(), ElementPictureFactory::parseLine(), path(), and secondEndCircleRect().
fourShapePoints()
QList< QPointF > PartLine::fourShapePoints () const private
PartLine::fourShapePoints.
Returns
a list with the two points that delimite the line
the four points surrounding these two points
Definition at line 411 of file partline.cpp.
References m_line.
fromXml()
void PartLine::fromXml (const QDomElement & qde) override virtual
PartLine::fromXml Import the properties of this line from a xml element.
Parameters
qde : Xml document to use
Implements CustomElementPart.
Definition at line 129 of file partline.cpp.
References Qet::endTypeFromString(), first_end, first_length, m_line, second_end, second_length, and CustomElementGraphicPart::stylesFromXml().
handlerMouseMoveEvent()
void PartLine::handlerMouseMoveEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
PartLine::handlerMouseMoveEvent.
Parameters
qghi
event
Definition at line 263 of file partline.cpp.
References adjusteHandlerPos(), CustomElementPart::elementScene(), m_line, m_vector_index, and ElementScene::snapToGrid().
Referenced by sceneEventFilter().
handlerMousePressEvent()
void PartLine::handlerMousePressEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
PartLine::handlerMousePressEvent.
Parameters
qghi
event
Definition at line 247 of file partline.cpp.
References QPropertyUndoCommand::enableAnimation(), m_line, m_undo_command, and QET::Icons::tr.
Referenced by sceneEventFilter().
handlerMouseReleaseEvent()
void PartLine::handlerMouseReleaseEvent (QetGraphicsHandlerItem * qghi, QGraphicsSceneMouseEvent * event) private
PartLine::handlerMouseReleaseEvent.
Parameters
qghi
event
Definition at line 286 of file partline.cpp.
References CustomElementPart::elementScene(), m_line, m_undo_command, m_vector_index, QPropertyUndoCommand::setNewValue(), and ElementScene::undoStack().
Referenced by sceneEventFilter().
handleUserTransformation()
void PartLine::handleUserTransformation (const QRectF & initial_selection_rect, const QRectF & new_selection_rect) override virtual
PartLine::handleUserTransformation Handle the user-induced transformation from initial_selection_rect to new_selection_rect.
Parameters
initial_selection_rect
new_selection_rect
Implements CustomElementPart.
Definition at line 580 of file partline.cpp.
References m_line, CustomElementPart::mapPoints(), and saved_points_.
isUseless()
bool PartLine::isUseless () const override virtual
PartLine::isUseless.
Returns
true if this part is irrelevant and does not deserve to be Retained / registered. A line is relevant when is two point is different
Implements CustomElementPart.
Definition at line 546 of file partline.cpp.
References m_line.
Referenced by paint().
itemChange()
QVariant PartLine::itemChange (GraphicsItemChange change, const QVariant & value) override protected
PartLine::itemChange.
Parameters
change
value
Returns
Definition at line 148 of file partline.cpp.
References addHandler(), adjusteHandlerPos(), removeHandler(), and sceneSelectionChanged().
line()
QLineF PartLine::line () const
Definition at line 620 of file partline.cpp.
References m_line.
lineChanged
void PartLine::lineChanged () signal
Referenced by setLine(), and LineEditor::setUpChangeConnections().
name()
QString PartLine::name () const inline override virtual
Returns
the name of the primitive
Implements CustomElementPart.
Definition at line 71 of file partline.h.
References QET::Icons::tr.
paint()
void PartLine::paint (QPainter * painter, const QStyleOptionGraphicsItem * options, QWidget * widget = nullptr) override
PartLine::paint Draw this line.
Parameters
painter
options
widget
Definition at line 73 of file partline.cpp.
References CustomElementGraphicPart::applyStylesToQPainter(), CustomElementGraphicPart::drawShadowShape(), first_end, isUseless(), CustomElementGraphicPart::m_hovered, m_line, path(), and second_end.
path()
QPainterPath PartLine::path () const private
PartLine::path.
Returns
this line has a QPainterPath. It's notably use when this line have an end type (circle, triangle etc....), because return a QPainterPath with end already draw. Else if there isn't an end type get P1 and P2 of line is better (faster).
Returns
true si cette partie n'est pas pertinente et ne merite pas d'etre conservee / enregistree. Une ligne est pertinente des lors que ses deux points sont differents
Definition at line 674 of file partline.cpp.
References Qet::Circle, Qet::Diamond, first_end, first_length, fourEndPoints(), length1, length2, m_line, CustomElementGraphicPart::penWeight(), requiredLengthForEndType(), second_end, second_length, Qet::Simple, and Qet::Triangle.
Referenced by boundingRect(), paint(), shadowShape(), and shape().
removeHandler()
void PartLine::removeHandler () private
PartLine::removeHandler Remove the handlers of this item.
Definition at line 336 of file partline.cpp.
References m_handler_vector.
Referenced by itemChange(), sceneSelectionChanged(), and ~PartLine().
requiredLengthForEndType()
uint PartLine::requiredLengthForEndType (const Qet::EndType & end_type) static
PartLine::requiredLengthForEndType.
Parameters
end_type
Returns
the number of "length" needed to draw a extremity of type Qet::EndType.
Definition at line 54 of file partline.cpp.
References Qet::Circle, Qet::Diamond, Qet::Simple, and Qet::Triangle.
Referenced by ElementPictureFactory::parseLine(), and path().
sceneEventFilter()
bool PartLine::sceneEventFilter (QGraphicsItem * watched, QEvent * event) override protected
PartLine::sceneEventFilter.
Parameters
watched
event
Returns
Definition at line 188 of file partline.cpp.
References handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), m_handler_vector, m_vector_index, and QetGraphicsHandlerItem::Type.
sceneGeometricRect()
QRectF PartLine::sceneGeometricRect () const override virtual
PartLine::sceneGeometricRect.
Returns
the minimum, margin-less rectangle this part can fit into, in scene coordinates. It is different from boundingRect() because it is not supposed to imply any margin, and it is different from shape because it is a regular rectangle, not a complex shape.
Implements CustomElementPart.
Definition at line 557 of file partline.cpp.
References sceneP1(), and sceneP2().
sceneP1()
QPointF PartLine::sceneP1 () const virtual
PartLine::sceneP1.
Returns
the point p1 in scene coordinate
Definition at line 349 of file partline.cpp.
References m_line.
Referenced by sceneGeometricRect(), startUserTransformation(), and toXml().
sceneP2()
QPointF PartLine::sceneP2 () const virtual
PartLine::sceneP2.
Returns
the point p2 in scen coordinate
Definition at line 357 of file partline.cpp.
References m_line.
Referenced by sceneGeometricRect(), startUserTransformation(), and toXml().
sceneSelectionChanged()
void PartLine::sceneSelectionChanged () private
PartLine::sceneSelectionChanged When the scene selection change, if there are several primitive selected, we remove the handler of this item.
Definition at line 301 of file partline.cpp.
References addHandler(), and removeHandler().
Referenced by itemChange().
secondEndCircleRect()
QRectF PartLine::secondEndCircleRect () const private
PartLine::secondEndCircleRect.
Returns
the rectangle bordering the entirety of the second extremity
Definition at line 476 of file partline.cpp.
References fourEndPoints(), m_line, and second_length.
Referenced by debugPaint().
secondEndLength()
qreal PartLine::secondEndLength () const inline
Definition at line 95 of file partline.h.
References second_length.
secondEndLengthChanged
void PartLine::secondEndLengthChanged () signal
Referenced by setSecondEndLength(), and LineEditor::setUpChangeConnections().
secondEndType()
Qet::EndType PartLine::secondEndType () const inline
Definition at line 91 of file partline.h.
References second_end.
secondEndTypeChanged
void PartLine::secondEndTypeChanged () signal
Referenced by setSecondEndType(), and LineEditor::setUpChangeConnections().
setFirstEndLength()
void PartLine::setFirstEndLength (const qreal & l)
Definition at line 649 of file partline.cpp.
References first_length, firstEndLengthChanged(), and m_line.
setFirstEndType()
void PartLine::setFirstEndType (const Qet::EndType & et)
Definition at line 633 of file partline.cpp.
References first_end, and firstEndTypeChanged().
setLine()
void PartLine::setLine (const QLineF & line)
Definition at line 624 of file partline.cpp.
References adjusteHandlerPos(), line, lineChanged(), and m_line.
Referenced by ESEventAddLine::mousePressEvent().
setSecondEndLength()
void PartLine::setSecondEndLength (const qreal & l)
Definition at line 658 of file partline.cpp.
References m_line, second_length, and secondEndLengthChanged().
setSecondEndType()
void PartLine::setSecondEndType (const Qet::EndType & et)
Definition at line 641 of file partline.cpp.
References second_end, and secondEndTypeChanged().
shadowShape()
QPainterPath PartLine::shadowShape () const override virtual
Implements CustomElementGraphicPart.
Definition at line 386 of file partline.cpp.
References first_end, m_line, path(), CustomElementGraphicPart::penWeight(), second_end, and shape().
shape()
QPainterPath PartLine::shape () const override
PartLine::shape.
Returns
the shape of this item
Definition at line 365 of file partline.cpp.
References first_end, CustomElementGraphicPart::m_hovered, m_line, path(), CustomElementGraphicPart::penWeight(), second_end, and SHADOWS_HEIGHT.
Referenced by shadowShape().
startUserTransformation()
void PartLine::startUserTransformation (const QRectF & initial_selection_rect) override virtual
PartLine::startUserTransformation Start the user-induced transformation, provided this primitive is contained within the initial_selection_rect bounding rectangle.
Parameters
initial_selection_rect
Implements CustomElementPart.
Definition at line 567 of file partline.cpp.
References saved_points_, sceneP1(), and sceneP2().
toXml()
const QDomElement PartLine::toXml (QDomDocument & xml_document) const override virtual
PartLine::toXml Export this line in xml.
Parameters
xml_document : Xml document to use for create the xml element.
Returns
an xml element that describe this line
Implements CustomElementPart.
Definition at line 105 of file partline.cpp.
References Qet::endTypeToString(), first_end, first_length, sceneP1(), sceneP2(), second_end, second_length, and CustomElementGraphicPart::stylesToXml().
type()
int PartLine::type () const inline override
Enable the use of qgraphicsitem_cast to safely cast a QGraphicsItem into a PartLine.
Returns
the QGraphicsItem type
Definition at line 69 of file partline.h.
References Type.
xmlName()
QString PartLine::xmlName () const inline override virtual
Returns
the name that will be used as XML tag when exporting the primitive
Implements CustomElementPart.
Definition at line 72 of file partline.h.
Member Data Documentation
first_end
Qet::EndType PartLine::first_end private
Definition at line 119 of file partline.h.
Referenced by boundingRect(), firstEndType(), fromXml(), paint(), path(), setFirstEndType(), shadowShape(), shape(), and toXml().
first_length
qreal PartLine::first_length private
Definition at line 120 of file partline.h.
Referenced by debugPaint(), firstEndCircleRect(), firstEndLength(), fromXml(), path(), setFirstEndLength(), and toXml().
m_handler_vector
QVector<QetGraphicsHandlerItem *> PartLine::m_handler_vector private
Definition at line 128 of file partline.h.
Referenced by addHandler(), adjusteHandlerPos(), removeHandler(), and sceneEventFilter().
m_line
QLineF PartLine::m_line private
Definition at line 125 of file partline.h.
Referenced by addHandler(), adjusteHandlerPos(), boundingRect(), debugPaint(), firstEndCircleRect(), fourShapePoints(), fromXml(), handlerMouseMoveEvent(), handlerMousePressEvent(), handlerMouseReleaseEvent(), handleUserTransformation(), isUseless(), line(), paint(), path(), sceneP1(), sceneP2(), secondEndCircleRect(), setFirstEndLength(), setLine(), setSecondEndLength(), shadowShape(), and shape().
m_undo_command
QPropertyUndoCommand* PartLine::m_undo_command private
Definition at line 127 of file partline.h.
Referenced by handlerMousePressEvent(), handlerMouseReleaseEvent(), and ~PartLine().
m_vector_index
int PartLine::m_vector_index = -1 private
Definition at line 126 of file partline.h.
Referenced by handlerMouseMoveEvent(), handlerMouseReleaseEvent(), and sceneEventFilter().
saved_points_
QList<QPointF> PartLine::saved_points_ private
Definition at line 124 of file partline.h.
Referenced by handleUserTransformation(), and startUserTransformation().
second_end
Qet::EndType PartLine::second_end private
Definition at line 122 of file partline.h.
Referenced by boundingRect(), fromXml(), paint(), path(), secondEndType(), setSecondEndType(), shadowShape(), shape(), and toXml().
second_length
qreal PartLine::second_length private
Definition at line 123 of file partline.h.
Referenced by debugPaint(), fromXml(), path(), secondEndCircleRect(), secondEndLength(), setSecondEndLength(), and toXml().
Property Documentation
end1
Qet::EndType PartLine::end1 read write
Definition at line 1 of file partline.h.
end2
Qet::EndType PartLine::end2 read write
Definition at line 1 of file partline.h.
length1
qreal PartLine::length1 read write
Definition at line 1 of file partline.h.
Referenced by path().
length2
qreal PartLine::length2 read write
Definition at line 1 of file partline.h.
Referenced by path().
line
QLineF PartLine::line read write
Definition at line 1 of file partline.h.
Referenced by ESEventAddLine::mouseMoveEvent(), and setLine().
The documentation for this class was generated from the following files:
partline.h
partline.cpp