QElectroTech: DiagramPropertiesEditorDockWidget Class Reference
DiagramPropertiesEditorDockWidget Class Reference
#include <diagrampropertieseditordockwidget.h>
Public Member Functions
DiagramPropertiesEditorDockWidget (QWidget *parent=nullptr)
DiagramPropertiesEditorDockWidget::DiagramPropertiesEditorDockWidget Constructor.
void setDiagram (Diagram *diagram)
DiagramPropertiesEditorDockWidget::setDiagram Set the diagram to edit the selection. Connect the diagram signal selectionChanged() to this slot selectionChanged(); If diagram = nullptr, we just disconnect all signal and remove editor.
Public Member Functions inherited from PropertiesEditorDockWidget
PropertiesEditorDockWidget (QWidget *parent=nullptr)
PropertiesEditorDockWidget::PropertiesEditorDockWidget Constructor.
~PropertiesEditorDockWidget () override
PropertiesEditorDockWidget::~PropertiesEditorDockWidget Destructor.
virtual void clear ()
PropertiesEditorDockWidget::clear Remove all editor present in this dock and delete it. They also disabled the button box at the bottom of this dock.
virtual void apply ()
PropertiesEditorDockWidget::apply Call the apply method for each editor present in this dock.
virtual void reset ()
PropertiesEditorDockWidget::reset Call the reset method for each editor present in this widget.
bool addEditor (PropertiesEditorWidget *editor, int index=0)
PropertiesEditorDockWidget::addEditor Add an editor in this dock at index in the main vertical layout (note the button box are displayed at bottom of this layout by default) When an editor is added, we enable the button box.
QList< PropertiesEditorWidget * > editors () const
PropertiesEditorDockWidget::editors.
bool removeEditor (PropertiesEditorWidget *editor)
PropertiesEditorDockWidget::removeEditor Remove editor from this dock. The editor wasn't delete a the end of this method If the editor was the last on this widget, we disabled the button box.
Private Slots
void selectionChanged ()
DiagramPropertiesEditorDockWidget::selectionChanged The current selection of diagram was changed. We fill the dock with the appropriate ElementPropertiesWidget of the current selection.
void diagramWasDeleted ()
DiagramPropertiesEditorDockWidget::diagramWasDeleted Remove current editor and set m_diagram to nullptr.
Private Member Functions
bool addEditor (PropertiesEditorWidget *editor, int index=0)
bool removeEditor (PropertiesEditorWidget *editor)
Private Attributes
Diagram * m_diagram
int m_edited_qgi_type
Additional Inherited Members
Protected Attributes inherited from PropertiesEditorDockWidget
QList< PropertiesEditorWidget * > m_editor_list
Detailed Description
Definition at line 25 of file diagrampropertieseditordockwidget.h.
Constructor & Destructor Documentation
DiagramPropertiesEditorDockWidget()
DiagramPropertiesEditorDockWidget::DiagramPropertiesEditorDockWidget (QWidget * parent = nullptr)
DiagramPropertiesEditorDockWidget::DiagramPropertiesEditorDockWidget Constructor.
Parameters
parent : parent widget
Definition at line 28 of file diagrampropertieseditordockwidget.cpp.
Member Function Documentation
addEditor()
bool DiagramPropertiesEditorDockWidget::addEditor (PropertiesEditorWidget * editor, int index = 0) inline private
Definition at line 35 of file diagrampropertieseditordockwidget.h.
References PropertiesEditorDockWidget::addEditor().
Referenced by selectionChanged().
diagramWasDeleted
void DiagramPropertiesEditorDockWidget::diagramWasDeleted () private slot
DiagramPropertiesEditorDockWidget::diagramWasDeleted Remove current editor and set m_diagram to nullptr.
Definition at line 97 of file diagrampropertieseditordockwidget.cpp.
References PropertiesEditorDockWidget::clear(), m_diagram, and m_edited_qgi_type.
Referenced by setDiagram().
removeEditor()
bool DiagramPropertiesEditorDockWidget::removeEditor (PropertiesEditorWidget * editor) inline private
Definition at line 37 of file diagrampropertieseditordockwidget.h.
References PropertiesEditorDockWidget::removeEditor().
selectionChanged
void DiagramPropertiesEditorDockWidget::selectionChanged () private slot
DiagramPropertiesEditorDockWidget::selectionChanged The current selection of diagram was changed. We fill the dock with the appropriate ElementPropertiesWidget of the current selection.
Definition at line 71 of file diagrampropertieseditordockwidget.cpp.
References addEditor(), PropertiesEditorDockWidget::clear(), PropertiesEditorDockWidget::editors(), m_diagram, and PropertiesEditorFactory::propertiesEditor().
Referenced by setDiagram().
setDiagram()
void DiagramPropertiesEditorDockWidget::setDiagram (Diagram * diagram)
DiagramPropertiesEditorDockWidget::setDiagram Set the diagram to edit the selection. Connect the diagram signal selectionChanged() to this slot selectionChanged(); If diagram = nullptr, we just disconnect all signal and remove editor.
Parameters
diagram
Definition at line 41 of file diagrampropertieseditordockwidget.cpp.
References PropertiesEditorDockWidget::clear(), diagramWasDeleted(), m_diagram, m_edited_qgi_type, and selectionChanged().
Referenced by QETDiagramEditor::projectWasClosed(), and QETDiagramEditor::selectionChanged().
Member Data Documentation
m_diagram
Diagram* DiagramPropertiesEditorDockWidget::m_diagram private
Definition at line 45 of file diagrampropertieseditordockwidget.h.
Referenced by diagramWasDeleted(), selectionChanged(), and setDiagram().
m_edited_qgi_type
int DiagramPropertiesEditorDockWidget::m_edited_qgi_type private
Definition at line 46 of file diagrampropertieseditordockwidget.h.
Referenced by diagramWasDeleted(), and setDiagram().
The documentation for this class was generated from the following files:
diagrampropertieseditordockwidget.h
diagrampropertieseditordockwidget.cpp