QElectroTech: DynamicElementTextItemEditor Class Reference
DynamicElementTextItemEditor Class Reference
#include <dynamicelementtextitemeditor.h>
Public Member Functions
DynamicElementTextItemEditor (Element *element, QWidget *parent=nullptr)
~DynamicElementTextItemEditor () override
void setElement (Element *element) override
QString title () const override
PropertiesEditorWidget::title.
bool setLiveEdit (bool live_edit) override
PropertiesEditorWidget::setLiveEdit Set the editor in live edit mode. When an editor is in live edit mode, every change is applied immediately (no need to call apply). If live edit can be enable, return true, else false. By default this method do nothing and return false (live edit is disable). Herited class of PropertiesEditorWidget must reimplemente this methode to manage the live edit mode.
void apply () override
void setCurrentText (DynamicElementTextItem *text)
DynamicElementTextItemEditor::setCurrentText Expand and select the item for text text.
void setCurrentGroup (ElementTextItemGroup *group)
DynamicElementTextItemEditor::setCurrentGroup Expand and select the item for group group.
QUndoCommand * associatedUndo () const override
PropertiesEditorWidget::associatedUndo By default, return a nullptr.
Public Member Functions inherited from AbstractElementPropertiesEditorWidget
AbstractElementPropertiesEditorWidget (QWidget *parent=nullptr)
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual void reset ()
virtual void updateUi ()
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Private Slots
void on_m_add_text_clicked ()
DynamicElementTextItemEditor::on_m_add_text_clicked Add a new dynamic text.
void on_m_remove_selection_clicked ()
DynamicElementTextItemEditor::on_m_remove_selection_clicked Remove the selected item.
void on_m_add_group_clicked ()
DynamicElementTextItemEditor::on_m_add_group_clicked Add a new group.
void on_m_tree_view_clicked (const QModelIndex &index)
void on_m_export_pb_clicked ()
void on_m_import_pb_clicked ()
Private Member Functions
void dataEdited ()
Private Attributes
Ui::DynamicElementTextItemEditor * ui
DynamicElementTextModel * m_model = nullptr
Additional Inherited Members
Protected Member Functions inherited from PropertiesEditorWidget
virtual void enableLiveEdit ()
virtual void disableLiveEdit ()
Protected Attributes inherited from AbstractElementPropertiesEditorWidget
QPointer< Element > m_element
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
Definition at line 32 of file dynamicelementtextitemeditor.h.
Constructor & Destructor Documentation
DynamicElementTextItemEditor()
DynamicElementTextItemEditor::DynamicElementTextItemEditor (Element * element, QWidget * parent = nullptr) explicit
Definition at line 34 of file dynamicelementtextitemeditor.cpp.
References setElement(), and ui.
~DynamicElementTextItemEditor()
DynamicElementTextItemEditor::~DynamicElementTextItemEditor () override
Definition at line 46 of file dynamicelementtextitemeditor.cpp.
References ui.
Member Function Documentation
apply()
void DynamicElementTextItemEditor::apply () override virtual
Reimplemented from PropertiesEditorWidget.
Definition at line 73 of file dynamicelementtextitemeditor.cpp.
References AbstractElementPropertiesEditorWidget::m_element, m_model, QET::Icons::tr, DynamicElementTextModel::undoForEditedGroup(), and DynamicElementTextModel::undoForEditedText().
Referenced by dataEdited().
associatedUndo()
QUndoCommand * DynamicElementTextItemEditor::associatedUndo () const override virtual
PropertiesEditorWidget::associatedUndo By default, return a nullptr.
Returns
nullptr
Reimplemented from PropertiesEditorWidget.
Definition at line 170 of file dynamicelementtextitemeditor.cpp.
References AbstractElementPropertiesEditorWidget::m_element, m_model, QET::Icons::tr, DynamicElementTextModel::undoForEditedGroup(), and DynamicElementTextModel::undoForEditedText().
dataEdited()
void DynamicElementTextItemEditor::dataEdited () private
Definition at line 189 of file dynamicelementtextitemeditor.cpp.
References apply(), and PropertiesEditorWidget::m_live_edit.
Referenced by setElement().
on_m_add_group_clicked
void DynamicElementTextItemEditor::on_m_add_group_clicked () private slot
DynamicElementTextItemEditor::on_m_add_group_clicked Add a new group.
Definition at line 242 of file dynamicelementtextitemeditor.cpp.
References AbstractElementPropertiesEditorWidget::m_element, Element::name(), and QET::Icons::tr.
on_m_add_text_clicked
void DynamicElementTextItemEditor::on_m_add_text_clicked () private slot
DynamicElementTextItemEditor::on_m_add_text_clicked Add a new dynamic text.
Definition at line 199 of file dynamicelementtextitemeditor.cpp.
References AbstractElementPropertiesEditorWidget::m_element, and setCurrentText().
on_m_export_pb_clicked
void DynamicElementTextItemEditor::on_m_export_pb_clicked () private slot
Definition at line 260 of file dynamicelementtextitemeditor.cpp.
References AbstractElementPropertiesEditorWidget::m_element.
on_m_import_pb_clicked
void DynamicElementTextItemEditor::on_m_import_pb_clicked () private slot
Definition at line 265 of file dynamicelementtextitemeditor.cpp.
References AbstractElementPropertiesEditorWidget::m_element.
on_m_remove_selection_clicked
void DynamicElementTextItemEditor::on_m_remove_selection_clicked () private slot
DynamicElementTextItemEditor::on_m_remove_selection_clicked Remove the selected item.
Definition at line 220 of file dynamicelementtextitemeditor.cpp.
References DynamicElementTextModel::groupFromIndex(), AbstractElementPropertiesEditorWidget::m_element, DiagramContent::m_element_texts, m_model, DynamicElementTextModel::textFromIndex(), and ui.
on_m_tree_view_clicked
void DynamicElementTextItemEditor::on_m_tree_view_clicked (const QModelIndex & index) private slot
Definition at line 252 of file dynamicelementtextitemeditor.cpp.
References DynamicElementTextModel::indexIsGroup(), DynamicElementTextModel::indexIsText(), m_model, and ui.
setCurrentGroup()
void DynamicElementTextItemEditor::setCurrentGroup (ElementTextItemGroup * group)
DynamicElementTextItemEditor::setCurrentGroup Expand and select the item for group group.
Parameters
group
Definition at line 159 of file dynamicelementtextitemeditor.cpp.
References DynamicElementTextModel::indexFromGroup(), m_model, and ui.
Referenced by ElementPropertiesWidget::setTextsGroup().
setCurrentText()
void DynamicElementTextItemEditor::setCurrentText (DynamicElementTextItem * text)
DynamicElementTextItemEditor::setCurrentText Expand and select the item for text text.
Parameters
text
Definition at line 142 of file dynamicelementtextitemeditor.cpp.
References DynamicElementTextModel::indexFromText(), m_model, and ui.
Referenced by on_m_add_text_clicked(), and ElementPropertiesWidget::setDynamicText().
setElement()
void DynamicElementTextItemEditor::setElement (Element * element) override virtual
Implements AbstractElementPropertiesEditorWidget.
Definition at line 51 of file dynamicelementtextitemeditor.cpp.
References DynamicElementTextModel::dataChanged(), dataEdited(), AbstractElementPropertiesEditorWidget::m_element, m_model, and ui.
Referenced by DynamicElementTextItemEditor().
setLiveEdit()
bool DynamicElementTextItemEditor::setLiveEdit (bool live_edit) override virtual
PropertiesEditorWidget::setLiveEdit Set the editor in live edit mode. When an editor is in live edit mode, every change is applied immediately (no need to call apply). If live edit can be enable, return true, else false. By default this method do nothing and return false (live edit is disable). Herited class of PropertiesEditorWidget must reimplemente this methode to manage the live edit mode.
Parameters
live_edit true to enable live edit
Returns
true if live edit is enable, else false.
Reimplemented from PropertiesEditorWidget.
Definition at line 67 of file dynamicelementtextitemeditor.cpp.
References PropertiesEditorWidget::m_live_edit.
title()
QString DynamicElementTextItemEditor::title () const inline override virtual
PropertiesEditorWidget::title.
Returns
the title of this editor
Reimplemented from PropertiesEditorWidget.
Definition at line 43 of file dynamicelementtextitemeditor.h.
References QET::Icons::tr.
Member Data Documentation
m_model
DynamicElementTextModel* DynamicElementTextItemEditor::m_model = nullptr private
Definition at line 63 of file dynamicelementtextitemeditor.h.
Referenced by apply(), associatedUndo(), on_m_remove_selection_clicked(), on_m_tree_view_clicked(), setCurrentGroup(), setCurrentText(), and setElement().
ui
Ui::DynamicElementTextItemEditor* DynamicElementTextItemEditor::ui private
Definition at line 62 of file dynamicelementtextitemeditor.h.
Referenced by DynamicElementTextItemEditor(), on_m_remove_selection_clicked(), on_m_tree_view_clicked(), setCurrentGroup(), setCurrentText(), setElement(), and ~DynamicElementTextItemEditor().
The documentation for this class was generated from the following files:
dynamicelementtextitemeditor.h
dynamicelementtextitemeditor.cpp