QElectroTech: AddElementTextCommand Class Reference
AddElementTextCommand Class Reference
The AddElementTextCommand class Manage the adding of element text.
#include <addelementtextcommand.h>
Public Member Functions
AddElementTextCommand (Element *element, DynamicElementTextItem *deti, QUndoCommand *parent=nullptr)
AddElementTextCommand::AddElementTextCommand.
~AddElementTextCommand () override
AddElementTextCommand::~AddElementTextCommand.
void undo () override
AddElementTextCommand::undo.
void redo () override
AddElementTextCommand::redo.
Private Attributes
Element * m_element = nullptr
DynamicElementTextItem * m_text = nullptr
Detailed Description
The AddElementTextCommand class Manage the adding of element text.
Definition at line 33 of file addelementtextcommand.h.
Constructor & Destructor Documentation
AddElementTextCommand()
AddElementTextCommand::AddElementTextCommand (Element * element, DynamicElementTextItem * deti, QUndoCommand * parent = nullptr)
AddElementTextCommand::AddElementTextCommand.
Parameters
element
deti
parent
Definition at line 37 of file addelementtextcommand.cpp.
References QET::Icons::tr.
~AddElementTextCommand()
AddElementTextCommand::~AddElementTextCommand () override
AddElementTextCommand::~AddElementTextCommand.
Definition at line 50 of file addelementtextcommand.cpp.
References Element::dynamicTextItems(), m_element, m_text, and DynamicElementTextItem::parentGroup().
Member Function Documentation
redo()
void AddElementTextCommand::redo () override
AddElementTextCommand::redo.
Definition at line 72 of file addelementtextcommand.cpp.
References Element::addDynamicTextItem(), m_element, and m_text.
undo()
void AddElementTextCommand::undo () override
AddElementTextCommand::undo.
Definition at line 62 of file addelementtextcommand.cpp.
References m_element, m_text, and Element::removeDynamicTextItem().
Member Data Documentation
m_element
Element* AddElementTextCommand::m_element = nullptr private
Definition at line 45 of file addelementtextcommand.h.
Referenced by redo(), undo(), and ~AddElementTextCommand().
m_text
DynamicElementTextItem* AddElementTextCommand::m_text = nullptr private
Definition at line 46 of file addelementtextcommand.h.
Referenced by redo(), undo(), and ~AddElementTextCommand().
The documentation for this class was generated from the following files:
addelementtextcommand.h
addelementtextcommand.cpp