QElectroTech: xpath_node_set_raw Class Reference
xpath_node_set_raw Class Reference
Public Member Functions
xpath_node_set_raw ()
xpath_node * begin () const
xpath_node * end () const
bool empty () const
size_t size () const
xpath_node first () const
void push_back_grow (const xpath_node &node, xpath_allocator *alloc)
void push_back (const xpath_node &node, xpath_allocator *alloc)
void append (const xpath_node *begin_, const xpath_node *end_, xpath_allocator *alloc)
void sort_do ()
void truncate (xpath_node *pos)
void remove_duplicates (xpath_allocator *alloc)
xpath_node_set::type_t type () const
void set_type (xpath_node_set::type_t value)
Private Attributes
xpath_node_set::type_t _type
xpath_node * _begin
xpath_node * _end
xpath_node * _eos
Detailed Description
Definition at line 8883 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_node_set_raw()
xpath_node_set_raw::xpath_node_set_raw () inline
Definition at line 8892 of file pugixml.cpp.
Member Function Documentation
append()
void xpath_node_set_raw::append (const xpath_node * begin_, const xpath_node * end_, xpath_allocator * alloc) inline
Definition at line 8931 of file pugixml.cpp.
References _begin, _end, _eos, and xpath_allocator::reallocate().
Referenced by xpath_ast_node::eval_node_set().
begin()
xpath_node* xpath_node_set_raw::begin () const inline
Definition at line 8896 of file pugixml.cpp.
References _begin.
Referenced by xpath_ast_node::apply_predicate_boolean(), xpath_ast_node::apply_predicate_number(), xpath_ast_node::apply_predicate_number_const(), xpath_ast_node::compare_eq(), xpath_ast_node::compare_rel(), xpath_ast_node::eval_node_set(), xpath_ast_node::eval_number(), and xpath_ast_node::step_do().
empty()
bool xpath_node_set_raw::empty () const inline
Definition at line 8906 of file pugixml.cpp.
References _begin, and _end.
Referenced by xpath_ast_node::eval_boolean(), and xpath_ast_node::eval_string().
end()
xpath_node* xpath_node_set_raw::end () const inline
Definition at line 8901 of file pugixml.cpp.
References _end.
Referenced by xpath_ast_node::apply_predicate_boolean(), xpath_ast_node::apply_predicate_number(), xpath_ast_node::compare_eq(), xpath_ast_node::compare_rel(), xpath_ast_node::eval_node_set(), xpath_ast_node::eval_number(), and xpath_ast_node::step_do().
first()
xpath_node xpath_node_set_raw::first () const inline
Definition at line 8916 of file pugixml.cpp.
References _begin, _end, _type, and xpath_first().
Referenced by xpath_ast_node::eval_string().
push_back()
void xpath_node_set_raw::push_back (const xpath_node & node, xpath_allocator * alloc) inline
Definition at line 8923 of file pugixml.cpp.
References _end, _eos, and push_back_grow().
Referenced by xpath_ast_node::eval_node_set(), and xpath_ast_node::step_push().
push_back_grow()
PUGI__FN_NO_INLINE void xpath_node_set_raw::push_back_grow (const xpath_node & node, xpath_allocator * alloc)
Definition at line 9016 of file pugixml.cpp.
References _begin, _end, _eos, and xpath_allocator::reallocate().
Referenced by push_back().
remove_duplicates()
void xpath_node_set_raw::remove_duplicates (xpath_allocator * alloc) inline
Definition at line 8967 of file pugixml.cpp.
References _begin, _end, _type, xpath_allocator::allocate(), hash_insert(), QET::Icons::it, and unique().
Referenced by xpath_ast_node::eval_node_set(), and xpath_ast_node::step_do().
set_type()
void xpath_node_set_raw::set_type (xpath_node_set::type_t value) inline
Definition at line 9010 of file pugixml.cpp.
References _type.
Referenced by xpath_ast_node::eval_node_set(), and xpath_ast_node::step_do().
size()
size_t xpath_node_set_raw::size () const inline
Definition at line 8911 of file pugixml.cpp.
References _begin, and _end.
Referenced by xpath_ast_node::apply_predicate(), xpath_ast_node::apply_predicate_boolean(), xpath_ast_node::apply_predicate_number(), xpath_ast_node::apply_predicate_number_const(), xpath_ast_node::apply_predicates(), xpath_ast_node::eval_number(), and xpath_ast_node::step_do().
sort_do()
void xpath_node_set_raw::sort_do () inline
Definition at line 8955 of file pugixml.cpp.
References _begin, _end, _type, and xpath_sort().
Referenced by xpath_ast_node::eval_node_set().
truncate()
void xpath_node_set_raw::truncate (xpath_node * pos) inline
Definition at line 8960 of file pugixml.cpp.
References _begin, and _end.
Referenced by xpath_ast_node::apply_predicate_boolean(), xpath_ast_node::apply_predicate_number(), and xpath_ast_node::apply_predicate_number_const().
type()
xpath_node_set::type_t xpath_node_set_raw::type () const inline
Definition at line 9005 of file pugixml.cpp.
References _type.
Referenced by xpath_ast_node::apply_predicates(), xpath_ast_node::eval_node_set(), and xpath_ast_node::step_do().
Member Data Documentation
_begin
xpath_node* xpath_node_set_raw::_begin private
Definition at line 8887 of file pugixml.cpp.
Referenced by append(), begin(), empty(), first(), push_back_grow(), remove_duplicates(), size(), sort_do(), and truncate().
_end
xpath_node* xpath_node_set_raw::_end private
Definition at line 8888 of file pugixml.cpp.
Referenced by append(), empty(), end(), first(), push_back(), push_back_grow(), remove_duplicates(), size(), sort_do(), and truncate().
_eos
xpath_node* xpath_node_set_raw::_eos private
Definition at line 8889 of file pugixml.cpp.
Referenced by append(), push_back(), and push_back_grow().
_type
xpath_node_set::type_t xpath_node_set_raw::_type private
Definition at line 8885 of file pugixml.cpp.
Referenced by first(), remove_duplicates(), set_type(), sort_do(), and type().
The documentation for this class was generated from the following file:
pugixml.cpp