QElectroTech: QetGraphicsHeaderItem Class Reference
QetGraphicsHeaderItem Class Reference
The QetGraphicsHeaderItem class The header have a few parameters to edit her visual aspect. Margins, to edit the margin between the cell and the text. Text font. Text alignment in the cell These three parameters are not settable directly with the header but trough the model to be displayed by the header. Header search these parameters only in the section 0 for cell of header. By consequence, set data in other section is useless also these parameter can't be set individually for each cell. The margins is stored in the model in index Qt::UserRole+1 and for value a QString. See QETUtils::marginsFromString and QETUtils::marginsToString.
#include <qetgraphicsheaderitem.h>
Public Types
enum { Type = UserType + 1301 }
Signals
void sectionResized (int logicalIndex, int size)
void heightResized ()
Public Member Functions
QetGraphicsHeaderItem (QGraphicsItem *parent=nullptr)
QetGraphicsHeaderItem::QetGraphicsHeaderItem.
int type () const override
void setModel (QAbstractItemModel *model=nullptr)
QetGraphicsHeaderItem::setModel Set the model presented by this item Since QetGraphicsHeaderItem don't take ownership of model, if item already have a model, it's your responsability to delete it.
QAbstractItemModel * model () const
QetGraphicsHeaderItem::model.
virtual QRectF boundingRect () const override
QetGraphicsHeaderItem::boundingRect Reimplemented from QGraphicsObject::boundingRect() const;.
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
QetGraphicsHeaderItem::paint Reimplemented from QGraphicsObject::paint(QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) const;.
QRect rect () const
QetGraphicsHeaderItem::rect.
void resizeSection (int logicalIndex, int size)
QetGraphicsHeaderItem::resizeSection.
int sectionSize (int logical_index) const
QetGraphicsHeaderItem::sectionSize.
QVector< int > minimumSectionWidth () const
int minimumWidth () const
QDomElement toXml (QDomDocument &document) const
QetGraphicsHeaderItem::toXml save the header to xml.
void fromXml (const QDomElement &element)
QetGraphicsHeaderItem::fromXml Restore the header from xml.
Static Public Member Functions
static QString xmlTagName ()
Private Member Functions
void setUpMinimumSectionsSize ()
QetGraphicsHeaderItem::setUpMinimumSectionsSize Setup the minimum section size and height of the item. Not that this function doesn't change the current size of this item.
void setUpBoundingRect ()
QetGraphicsHeaderItem::setUpBoundingRect Setup the bounding rect of the item.
void headerDataChanged (Qt::Orientations orientation, int first, int last)
QetGraphicsHeaderItem::headerDataChanged Update the header when data of displayed model change.
void adjustSize ()
QetGraphicsHeaderItem::adjustSize If needed, this function resize the current height and section according to there minimum.
void modelReseted ()
Private Attributes
QRectF m_bounding_rect
QAbstractItemModel * m_model = nullptr
QVector< int > m_sections_minimum_width
QVector< int > m_current_sections_width
int m_section_height =1
int m_minimum_section_height =1
int m_minimum_width =1
QRect m_current_rect
Detailed Description
The QetGraphicsHeaderItem class The header have a few parameters to edit her visual aspect. Margins, to edit the margin between the cell and the text. Text font. Text alignment in the cell These three parameters are not settable directly with the header but trough the model to be displayed by the header. Header search these parameters only in the section 0 for cell of header. By consequence, set data in other section is useless also these parameter can't be set individually for each cell. The margins is stored in the model in index Qt::UserRole+1 and for value a QString. See QETUtils::marginsFromString and QETUtils::marginsToString.
Definition at line 40 of file qetgraphicsheaderitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 47 of file qetgraphicsheaderitem.h.
Constructor & Destructor Documentation
QetGraphicsHeaderItem()
QetGraphicsHeaderItem::QetGraphicsHeaderItem (QGraphicsItem * parent = nullptr)
QetGraphicsHeaderItem::QetGraphicsHeaderItem.
Parameters
parent
Definition at line 32 of file qetgraphicsheaderitem.cpp.
Member Function Documentation
adjustSize()
void QetGraphicsHeaderItem::adjustSize () private
QetGraphicsHeaderItem::adjustSize If needed, this function resize the current height and section according to there minimum.
Definition at line 298 of file qetgraphicsheaderitem.cpp.
References heightResized(), m_current_rect, m_current_sections_width, m_minimum_section_height, m_section_height, m_sections_minimum_width, and resizeSection().
Referenced by headerDataChanged(), modelReseted(), and setModel().
boundingRect()
QRectF QetGraphicsHeaderItem::boundingRect () const override virtual
QetGraphicsHeaderItem::boundingRect Reimplemented from QGraphicsObject::boundingRect() const;.
Returns
Definition at line 80 of file qetgraphicsheaderitem.cpp.
References m_bounding_rect.
fromXml()
void QetGraphicsHeaderItem::fromXml (const QDomElement & element)
QetGraphicsHeaderItem::fromXml Restore the header from xml.
Parameters
element
Definition at line 224 of file qetgraphicsheaderitem.cpp.
References QET::Horizontal, m_model, QETXML::marginsFromXml(), QETUtils::marginsToString(), and xmlTagName().
Referenced by QetGraphicsTableItem::fromXml().
headerDataChanged()
void QetGraphicsHeaderItem::headerDataChanged (Qt::Orientations orientation, int first, int last) private
QetGraphicsHeaderItem::headerDataChanged Update the header when data of displayed model change.
Parameters
orientation
first
last
Definition at line 282 of file qetgraphicsheaderitem.cpp.
References adjustSize(), and setUpMinimumSectionsSize().
Referenced by setModel().
heightResized
void QetGraphicsHeaderItem::heightResized () signal
Referenced by adjustSize(), and QetGraphicsTableItem::QetGraphicsTableItem().
minimumSectionWidth()
QVector<int> QetGraphicsHeaderItem::minimumSectionWidth () const inline
Definition at line 58 of file qetgraphicsheaderitem.h.
References m_sections_minimum_width.
Referenced by QetGraphicsTableItem::adjustColumnsWidth(), and QetGraphicsTableItem::setUpColumnAndRowMinimumSize().
minimumWidth()
int QetGraphicsHeaderItem::minimumWidth () const inline
Definition at line 59 of file qetgraphicsheaderitem.h.
References m_minimum_width.
model()
QAbstractItemModel * QetGraphicsHeaderItem::model () const
QetGraphicsHeaderItem::model.
Returns
the model that this item is presenting
Definition at line 71 of file qetgraphicsheaderitem.cpp.
References m_model.
Referenced by setModel().
modelReseted()
void QetGraphicsHeaderItem::modelReseted () private
Definition at line 322 of file qetgraphicsheaderitem.cpp.
References adjustSize(), m_current_sections_width, m_sections_minimum_width, and setUpMinimumSectionsSize().
Referenced by setModel().
paint()
void QetGraphicsHeaderItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override virtual
QetGraphicsHeaderItem::paint Reimplemented from QGraphicsObject::paint(QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) const;.
Parameters
painter
option
widget
Definition at line 91 of file qetgraphicsheaderitem.cpp.
References QET::Horizontal, m_current_rect, m_current_sections_width, m_model, m_section_height, and QETUtils::marginsFromString().
rect()
QRect QetGraphicsHeaderItem::rect () const
QetGraphicsHeaderItem::rect.
Returns
the current rect of the item aka the size of rectangle painted.
Definition at line 147 of file qetgraphicsheaderitem.cpp.
References m_current_rect.
Referenced by QetGraphicsTableItem::adjustTableToFolio(), QetGraphicsTableItem::headerSectionResized(), QetGraphicsTableItem::paint(), QetGraphicsTableItem::QetGraphicsTableItem(), QetGraphicsTableItem::setModel(), QetGraphicsTableItem::setUpBoundingRect(), and QetGraphicsTableItem::size().
resizeSection()
void QetGraphicsHeaderItem::resizeSection (int logicalIndex, int size)
QetGraphicsHeaderItem::resizeSection.
Parameters
logicalIndex
size
Definition at line 156 of file qetgraphicsheaderitem.cpp.
References m_current_rect, m_current_sections_width, m_model, m_sections_minimum_width, no_model_width, sectionResized(), and setUpBoundingRect().
Referenced by QetGraphicsTableItem::adjustColumnsWidth(), and adjustSize().
sectionResized
void QetGraphicsHeaderItem::sectionResized (int logicalIndex, int size) signal
Referenced by QetGraphicsTableItem::adjustColumnsWidth(), QetGraphicsTableItem::handlerMousePressEvent(), QetGraphicsTableItem::handlerMouseReleaseEvent(), QetGraphicsTableItem::QetGraphicsTableItem(), and resizeSection().
sectionSize()
int QetGraphicsHeaderItem::sectionSize (int logical_index) const
QetGraphicsHeaderItem::sectionSize.
Parameters
logical_index
Returns
the width (or height for vertical headers) of the given logicalIndex.
Definition at line 194 of file qetgraphicsheaderitem.cpp.
References m_current_sections_width.
Referenced by QetGraphicsTableItem::adjustColumnsWidth(), and QetGraphicsTableItem::paint().
setModel()
void QetGraphicsHeaderItem::setModel (QAbstractItemModel * model = nullptr)
QetGraphicsHeaderItem::setModel Set the model presented by this item Since QetGraphicsHeaderItem don't take ownership of model, if item already have a model, it's your responsability to delete it.
Parameters
model
Definition at line 43 of file qetgraphicsheaderitem.cpp.
References adjustSize(), headerDataChanged(), m_current_sections_width, m_model, m_sections_minimum_width, model(), modelReseted(), and setUpMinimumSectionsSize().
Referenced by QetGraphicsTableItem::setModel().
setUpBoundingRect()
void QetGraphicsHeaderItem::setUpBoundingRect () private
QetGraphicsHeaderItem::setUpBoundingRect Setup the bounding rect of the item.
Definition at line 271 of file qetgraphicsheaderitem.cpp.
References m_bounding_rect, and m_current_rect.
Referenced by resizeSection().
setUpMinimumSectionsSize()
void QetGraphicsHeaderItem::setUpMinimumSectionsSize () private
QetGraphicsHeaderItem::setUpMinimumSectionsSize Setup the minimum section size and height of the item. Not that this function doesn't change the current size of this item.
Definition at line 239 of file qetgraphicsheaderitem.cpp.
References QET::Horizontal, m_minimum_section_height, m_minimum_width, m_model, m_sections_minimum_width, QETUtils::marginsFromString(), no_model_height, and no_model_width.
Referenced by headerDataChanged(), modelReseted(), and setModel().
toXml()
QDomElement QetGraphicsHeaderItem::toXml (QDomDocument & document) const
QetGraphicsHeaderItem::toXml save the header to xml.
Parameters
document
Returns
Definition at line 209 of file qetgraphicsheaderitem.cpp.
References QET::Horizontal, m_model, QETUtils::marginsFromString(), QETXML::marginsToXml(), and xmlTagName().
Referenced by QetGraphicsTableItem::toXml().
type()
int QetGraphicsHeaderItem::type () const inline override
Definition at line 48 of file qetgraphicsheaderitem.h.
References Type.
xmlTagName()
static QString QetGraphicsHeaderItem::xmlTagName () inline static
Definition at line 63 of file qetgraphicsheaderitem.h.
Referenced by fromXml(), QetGraphicsTableItem::fromXml(), and toXml().
Member Data Documentation
m_bounding_rect
QRectF QetGraphicsHeaderItem::m_bounding_rect private
Definition at line 77 of file qetgraphicsheaderitem.h.
Referenced by boundingRect(), and setUpBoundingRect().
m_current_rect
QRect QetGraphicsHeaderItem::m_current_rect private
Definition at line 84 of file qetgraphicsheaderitem.h.
Referenced by adjustSize(), paint(), rect(), resizeSection(), and setUpBoundingRect().
m_current_sections_width
QVector<int> QetGraphicsHeaderItem::m_current_sections_width private
Definition at line 80 of file qetgraphicsheaderitem.h.
Referenced by adjustSize(), modelReseted(), paint(), resizeSection(), sectionSize(), and setModel().
m_minimum_section_height
int QetGraphicsHeaderItem::m_minimum_section_height =1 private
Definition at line 82 of file qetgraphicsheaderitem.h.
Referenced by adjustSize(), and setUpMinimumSectionsSize().
m_minimum_width
int QetGraphicsHeaderItem::m_minimum_width =1 private
Definition at line 83 of file qetgraphicsheaderitem.h.
Referenced by minimumWidth(), and setUpMinimumSectionsSize().
m_model
QAbstractItemModel* QetGraphicsHeaderItem::m_model = nullptr private
Definition at line 78 of file qetgraphicsheaderitem.h.
Referenced by fromXml(), model(), paint(), resizeSection(), setModel(), setUpMinimumSectionsSize(), and toXml().
m_section_height
int QetGraphicsHeaderItem::m_section_height =1 private
Definition at line 81 of file qetgraphicsheaderitem.h.
Referenced by adjustSize(), and paint().
m_sections_minimum_width
QVector<int> QetGraphicsHeaderItem::m_sections_minimum_width private
Definition at line 79 of file qetgraphicsheaderitem.h.
Referenced by adjustSize(), minimumSectionWidth(), modelReseted(), resizeSection(), setModel(), and setUpMinimumSectionsSize().
The documentation for this class was generated from the following files:
qetgraphicsheaderitem.h
qetgraphicsheaderitem.cpp