QElectroTech: ProjectView Class Reference
ProjectView Class Reference
#include <projectview.h>
Public Slots
void removeDiagram (DiagramView *)
ProjectView::removeDiagram Remove a diagram (folio) of the project.
void removeDiagram (Diagram *)
void showDiagram (DiagramView *)
void showDiagram (Diagram *)
void editProjectProperties ()
void editCurrentDiagramProperties ()
void editDiagramProperties (DiagramView *)
void editDiagramProperties (Diagram *)
void moveDiagramUp (DiagramView *)
void moveDiagramUp (Diagram *)
void moveDiagramDown (DiagramView *)
void moveDiagramDown (Diagram *)
void moveDiagramUpTop (DiagramView *)
void moveDiagramUpTop (Diagram *)
void moveDiagramUpx10 (DiagramView *)
void moveDiagramUpx10 (Diagram *)
void moveDiagramDownx10 (DiagramView *)
void moveDiagramDownx10 (Diagram *)
void printProject ()
void exportProject ()
QETResult save ()
QETResult saveAs ()
QETResult doSave ()
int cleanProject ()
void updateWindowTitle ()
ProjectView::updateWindowTitle Update the project view title.
void updateTabTitle (DiagramView *)
ProjectView::updateTabTitle Update the title of the tab which display the diagram view.
void updateAllTabsTitle ()
ProjectView::updateAllTabsTitle Update all tabs title.
void tabMoved (int, int)
Signals
void diagramAdded (DiagramView *)
void diagramRemoved (DiagramView *)
void diagramActivated (DiagramView *)
void projectClosed (ProjectView *)
void errorEncountered (const QString &)
void findElementRequired (const ElementsLocation &)
void editElementRequired (const ElementsLocation &)
Public Member Functions
ProjectView (QETProject *, QWidget *=nullptr)
~ProjectView () override
QETProject * project ()
void setProject (QETProject *)
ProjectView::setProject Set the project display by the project view.
QList< DiagramView * > diagram_views () const
DiagramView * currentDiagram () const
ProjectView::currentDiagram.
void closeEvent (QCloseEvent *) override
void changeTabUp ()
change current diagramview to previous tab
void changeTabDown ()
change current diagramview to next folio
void changeFirstTab ()
change current diagramview to first tab
void changeLastTab ()
change current diagramview to last tab
Private Slots
void tabChanged (int)
ProjectView::tabChanged Manage the tab change. If tab_id == -1 (there is no diagram opened), we display the fallback widget.
void tabDoubleClicked (int)
void setDisplayFallbackWidget (bool)
void adjustReadOnlyState ()
void diagramAdded (Diagram *diagram)
ProjectView::diagramAdded Slot called when qetproject emit diagramAdded.
Private Member Functions
ProjectView (const ProjectView &)
void initActions ()
void initWidgets ()
void initLayout ()
void loadDiagrams ()
ProjectView::loadDiagrams Load diagrams of project. We create a diagram view for each diagram, and add it to the project view.
DiagramView * findDiagram (Diagram *)
DiagramView * nextDiagram ()
DiagramView * previousDiagram ()
DiagramView * firstDiagram ()
DiagramView * lastDiagram ()
void rebuildDiagramsMap ()
bool tryClosing ()
bool tryClosingElementEditors ()
int tryClosingDiagrams ()
ProjectView::tryClosingDiagrams try to close this project, if diagram or project option are changed a dialog ask if user want to save the modification.
QString askUserForFilePath (bool=true)
QETResult noProjectResult () const
Private Attributes
QAction * m_add_new_diagram
QETProject * m_project
QVBoxLayout * layout_
QWidget * fallback_widget_
QLabel * fallback_label_
QTabWidget * m_tab
QMap< int, DiagramView * > m_diagram_ids
int m_previous_tab_index = -1
QList< DiagramView * > m_diagram_view_list
Detailed Description
This class provides a widget displaying the diagrams of a particular project using tabs.
Definition at line 77 of file projectview.h.
Constructor & Destructor Documentation
ProjectView() [1/2]
ProjectView::ProjectView (QETProject * project, QWidget * parent = nullptr)
Constructeur
Parameters
project projet a visualiser
parent Widget parent
Definition at line 42 of file projectview.cpp.
References initActions(), initLayout(), initWidgets(), project(), and setProject().
~ProjectView()
ProjectView::~ProjectView () override
Destructeur Supprime les DiagramView embarquees
Definition at line 57 of file projectview.cpp.
References m_diagram_ids.
ProjectView() [2/2]
ProjectView::ProjectView (const ProjectView &) private
Member Function Documentation
adjustReadOnlyState
void ProjectView::adjustReadOnlyState () private slot
Effectue les actions necessaires lorsque le projet visualise entre ou sort du mode lecture seule.
Definition at line 842 of file projectview.cpp.
References m_add_new_diagram, m_project, m_tab, and updateWindowTitle().
Referenced by setProject().
askUserForFilePath()
QString ProjectView::askUserForFilePath (bool assign = true) private
Ask the user to provide a file path in which the currently edited project will be saved.
Parameters
assign When true, assign the provided filepath to the project through setFilePath(). Defaults to true.
Returns
the file path, or an empty string if none were provided
Definition at line 315 of file projectview.cpp.
References m_project, and QET::Icons::tr.
Referenced by saveAs(), and tryClosing().
changeFirstTab()
void ProjectView::changeFirstTab ()
change current diagramview to first tab
Definition at line 190 of file projectview.cpp.
References firstDiagram(), and m_tab.
Referenced by DiagramView::keyPressEvent().
changeLastTab()
void ProjectView::changeLastTab ()
change current diagramview to last tab
Definition at line 175 of file projectview.cpp.
References lastDiagram(), and m_tab.
Referenced by DiagramView::keyPressEvent().
changeTabDown()
void ProjectView::changeTabDown ()
change current diagramview to next folio
Definition at line 129 of file projectview.cpp.
References m_tab, nextDiagram(), and rebuildDiagramsMap().
Referenced by DiagramView::keyPressEvent().
changeTabUp()
void ProjectView::changeTabUp ()
change current diagramview to previous tab
Definition at line 152 of file projectview.cpp.
References m_tab, previousDiagram(), and rebuildDiagramsMap().
Referenced by DiagramView::keyPressEvent().
cleanProject
int ProjectView::cleanProject () slot
Allow the user to clean the project, which includes: deleting unused title block templates deleting unused elements deleting empty categories
Returns
an integer value above zero if elements and/or categories were cleaned.
Definition at line 661 of file projectview.cpp.
References QET::Icons::Cancel, XmlElementCollection::cleanUnusedDirectory(), XmlElementCollection::cleanUnusedElement(), QET::QetMessageBox::critical(), TitleBlockTemplatesProjectCollection::deleteUnusedTitleBlocKTemplates(), QETProject::embeddedElementCollection(), QETProject::embeddedTitleBlockTemplatesCollection(), m_project, and QET::Icons::tr.
closeEvent()
void ProjectView::closeEvent (QCloseEvent * qce) override
Gere la fermeture du schema.
Parameters
qce Le QCloseEvent decrivant l'evenement
Definition at line 116 of file projectview.cpp.
References projectClosed(), and tryClosing().
currentDiagram()
DiagramView * ProjectView::currentDiagram () const
ProjectView::currentDiagram.
Returns
The current active diagram view or nullptr if there isn't diagramView in this project view.
Definition at line 105 of file projectview.cpp.
References m_diagram_ids, and m_tab.
Referenced by editCurrentDiagramProperties(), loadDiagrams(), AutoNumberingDockWidget::on_m_conductor_cb_activated(), AutoNumberingDockWidget::on_m_element_cb_activated(), AutoNumberingDockWidget::setActive(), and AutoNumberingDockWidget::setProject().
diagram_views()
QList< DiagramView * > ProjectView::diagram_views () const
Returns
la liste des schemas ouverts dans le projet
Definition at line 97 of file projectview.cpp.
References m_diagram_view_list.
Referenced by findDiagram(), and moveDiagramUpTop().
diagramActivated
void ProjectView::diagramActivated (DiagramView *) signal
Referenced by tabChanged().
diagramAdded [1/2]
void ProjectView::diagramAdded (Diagram * diagram) private slot
ProjectView::diagramAdded Slot called when qetproject emit diagramAdded.
Parameters
diagram
Definition at line 859 of file projectview.cpp.
References QET::Icons::Diagram, diagramAdded(), DiagramView::editElementRequired(), editElementRequired(), DiagramView::findElementRequired(), findElementRequired(), QETProject::folioIndex(), m_diagram_view_list, m_project, m_tab, rebuildDiagramsMap(), QETProject::setModified(), showDiagram(), DiagramView::showDiagram(), BorderTitleBlock::titleBlockFolioChanged(), DiagramView::titleChanged(), updateAllTabsTitle(), and updateTabTitle().
diagramAdded [2/2]
void ProjectView::diagramAdded (DiagramView *) signal
Referenced by diagramAdded(), loadDiagrams(), and setProject().
diagramRemoved
void ProjectView::diagramRemoved (DiagramView *) signal
Referenced by removeDiagram().
doSave
QETResult ProjectView::doSave () slot
Save project content, then write the project file. May call saveAs if no filepath was provided before.
Returns
a QETResult object reflecting the situation; note that a valid QETResult object is returned if the operation was cancelled.
Definition at line 636 of file projectview.cpp.
References m_project, noProjectResult(), project(), saveAs(), QETProject::undoStack(), and updateWindowTitle().
Referenced by save(), and saveAs().
editCurrentDiagramProperties
void ProjectView::editCurrentDiagramProperties () slot
Edite les proprietes du schema courant
Definition at line 433 of file projectview.cpp.
References currentDiagram(), and editDiagramProperties().
editDiagramProperties [1/2]
void ProjectView::editDiagramProperties (Diagram * diagram) slot
Edite les proprietes du schema diagram
Definition at line 449 of file projectview.cpp.
References editDiagramProperties(), and findDiagram().
editDiagramProperties [2/2]
void ProjectView::editDiagramProperties (DiagramView * diagram_view) slot
Edite les proprietes du schema diagram_view
Definition at line 440 of file projectview.cpp.
References showDiagram().
Referenced by editCurrentDiagramProperties(), editDiagramProperties(), and tabDoubleClicked().
editElementRequired
void ProjectView::editElementRequired (const ElementsLocation &) signal
Referenced by QETDiagramEditor::addProjectView(), and diagramAdded().
editProjectProperties
void ProjectView::editProjectProperties () slot
Enable the user to edit properties of the current project through a configuration dialog.
Definition at line 424 of file projectview.cpp.
References ProjectPropertiesDialog::exec(), and m_project.
errorEncountered
void ProjectView::errorEncountered (const QString &) signal
Referenced by tryClosing().
exportProject
void ProjectView::exportProject () slot
Exporte le schema.
Definition at line 594 of file projectview.cpp.
References m_project.
findDiagram()
DiagramView * ProjectView::findDiagram (Diagram * diagram) private
Parameters
diagram Schema a trouver
Returns
le DiagramView correspondant au schema passe en parametre, ou 0 si le schema n'est pas trouve
Definition at line 951 of file projectview.cpp.
References diagram_views().
Referenced by editDiagramProperties(), moveDiagramDown(), moveDiagramDownx10(), moveDiagramUp(), moveDiagramUpTop(), moveDiagramUpx10(), removeDiagram(), and showDiagram().
findElementRequired
void ProjectView::findElementRequired (const ElementsLocation &) signal
Referenced by QETDiagramEditor::addProjectView(), and diagramAdded().
firstDiagram()
DiagramView * ProjectView::firstDiagram () private
Returns
first folio of current project
Definition at line 198 of file projectview.cpp.
References m_diagram_ids.
Referenced by changeFirstTab().
initActions()
void ProjectView::initActions () private
Initialize actions for this widget.
Definition at line 721 of file projectview.cpp.
References QET::Icons::AddFolio, QETProject::addNewDiagram(), m_add_new_diagram, m_project, and QET::Icons::tr.
Referenced by ProjectView().
initLayout()
void ProjectView::initLayout () private
Initialize layout for this widget.
Definition at line 768 of file projectview.cpp.
References fallback_label_, fallback_widget_, layout_, and m_tab.
Referenced by ProjectView().
initWidgets()
void ProjectView::initWidgets () private
Initialize child widgets for this widget.
Definition at line 730 of file projectview.cpp.
References fallback_label_, fallback_widget_, m_add_new_diagram, m_tab, QET::Icons::ProjectFileGP, tabChanged(), tabDoubleClicked(), tabMoved(), and QET::Icons::tr.
Referenced by ProjectView().
lastDiagram()
DiagramView * ProjectView::lastDiagram () private
Returns
last folio of current project
Definition at line 183 of file projectview.cpp.
References m_diagram_ids.
Referenced by changeLastTab().
loadDiagrams()
void ProjectView::loadDiagrams () private
ProjectView::loadDiagrams Load diagrams of project. We create a diagram view for each diagram, and add it to the project view.
Definition at line 790 of file projectview.cpp.
References currentDiagram(), diagramAdded(), QETProject::diagrams(), DialogWaiting::hasInstance(), DialogWaiting::instance(), m_project, DialogWaiting::progressBarValue(), DialogWaiting::setDetail(), setDisplayFallbackWidget(), DialogWaiting::setProgressBar(), DialogWaiting::setTitle(), and QET::Icons::tr.
Referenced by setProject().
moveDiagramDown [1/2]
void ProjectView::moveDiagramDown (Diagram * diagram) slot
Deplace le schema diagram vers le bas / la droite
Definition at line 491 of file projectview.cpp.
References findDiagram(), and moveDiagramDown().
moveDiagramDown [2/2]
void ProjectView::moveDiagramDown (DiagramView * diagram_view) slot
Deplace le schema diagram_view vers le bas / la droite
Definition at line 477 of file projectview.cpp.
References m_diagram_ids, and m_tab.
Referenced by moveDiagramDown().
moveDiagramDownx10 [1/2]
void ProjectView::moveDiagramDownx10 (Diagram * diagram) slot
Deplace le schema diagram vers le bas / la droite x10
Definition at line 556 of file projectview.cpp.
References findDiagram(), and moveDiagramDownx10().
moveDiagramDownx10 [2/2]
void ProjectView::moveDiagramDownx10 (DiagramView * diagram_view) slot
Deplace le schema diagram_view vers le bas / la droite x10
Definition at line 542 of file projectview.cpp.
References m_diagram_ids, and m_tab.
Referenced by moveDiagramDownx10().
moveDiagramUp [1/2]
void ProjectView::moveDiagramUp (Diagram * diagram) slot
Deplace le schema diagram vers le haut / la gauche
Definition at line 470 of file projectview.cpp.
References findDiagram(), and moveDiagramUp().
moveDiagramUp [2/2]
void ProjectView::moveDiagramUp (DiagramView * diagram_view) slot
Deplace le schema diagram_view vers le haut / la gauche
Definition at line 456 of file projectview.cpp.
References m_diagram_ids, and m_tab.
Referenced by moveDiagramUp().
moveDiagramUpTop [1/2]
void ProjectView::moveDiagramUpTop (Diagram * diagram) slot
Definition at line 513 of file projectview.cpp.
References findDiagram(), and moveDiagramUpTop().
moveDiagramUpTop [2/2]
void ProjectView::moveDiagramUpTop (DiagramView * diagram_view) slot
Definition at line 498 of file projectview.cpp.
References diagram_views(), m_diagram_ids, and m_tab.
Referenced by moveDiagramUpTop().
moveDiagramUpx10 [1/2]
void ProjectView::moveDiagramUpx10 (Diagram * diagram) slot
Deplace le schema diagram vers le haut / la gauche x10
Definition at line 535 of file projectview.cpp.
References findDiagram(), and moveDiagramUpx10().
moveDiagramUpx10 [2/2]
void ProjectView::moveDiagramUpx10 (DiagramView * diagram_view) slot
Deplace le schema diagram_view vers le haut / la gauche x10
Definition at line 521 of file projectview.cpp.
References m_diagram_ids, and m_tab.
Referenced by moveDiagramUpx10().
nextDiagram()
DiagramView * ProjectView::nextDiagram () private
Returns
next folio of current diagramview
Definition at line 140 of file projectview.cpp.
References m_diagram_ids, and m_tab.
Referenced by changeTabDown().
noProjectResult()
QETResult ProjectView::noProjectResult () const private
Returns
the QETResult object to be returned when it appears this project view is not associated to any project.
Definition at line 342 of file projectview.cpp.
References QET::Icons::tr.
Referenced by doSave(), and saveAs().
previousDiagram()
DiagramView * ProjectView::previousDiagram () private
Returns
previous folio of current diagramview
Definition at line 163 of file projectview.cpp.
References m_diagram_ids, and m_tab.
Referenced by changeTabUp().
printProject
void ProjectView::printProject () slot
Ce slot demarre un dialogue permettant a l'utilisateur de parametrer et de lancer l'impression de toute ou partie du projet.
Definition at line 564 of file projectview.cpp.
References DiagramPrintDialog::exec(), m_project, DiagramPrintDialog::setDocName(), DiagramPrintDialog::setFileName(), QET::stringToFileName(), and QET::Icons::tr.
project()
QETProject * ProjectView::project ()
Returns
le projet actuellement visualise par le ProjectView
Definition at line 65 of file projectview.cpp.
References m_project.
Referenced by QETDiagramEditor::currentProject(), doSave(), QETDiagramEditor::generateTerminalBlock(), ProjectView(), setProject(), QETDiagramEditor::setUpActions(), and tryClosingDiagrams().
projectClosed
void ProjectView::projectClosed (ProjectView *) signal
Referenced by closeEvent().
rebuildDiagramsMap()
void ProjectView::rebuildDiagramsMap () private
Reconstruit la map associant les index des onglets avec les DiagramView
Definition at line 963 of file projectview.cpp.
References m_diagram_ids, m_diagram_view_list, and m_tab.
Referenced by changeTabDown(), changeTabUp(), diagramAdded(), removeDiagram(), and tabMoved().
removeDiagram [1/2]
void ProjectView::removeDiagram (Diagram * diagram) slot
Enleve un schema du ProjectView
Parameters
diagram Schema a enlever
Definition at line 392 of file projectview.cpp.
References findDiagram(), and removeDiagram().
removeDiagram [2/2]
void ProjectView::removeDiagram (DiagramView * diagram_view) slot
ProjectView::removeDiagram Remove a diagram (folio) of the project.
Parameters
diagram_view : diagram view to remove
Definition at line 352 of file projectview.cpp.
References QET::Icons::Cancel, diagramRemoved(), m_diagram_ids, m_diagram_view_list, m_project, m_tab, QET::QetMessageBox::question(), rebuildDiagramsMap(), QET::Icons::tr, and updateAllTabsTitle().
Referenced by removeDiagram().
save
QETResult ProjectView::save () slot
Save project properties along with all modified diagrams.
See also
filePath()
setFilePath()
Returns
a QETResult object reflecting the situation
Definition at line 610 of file projectview.cpp.
References doSave().
saveAs
QETResult ProjectView::saveAs () slot
Ask users for a filepath in order to save the project.
Parameters
options May be used to specify what should be saved; defaults to all modified diagrams.
Returns
a QETResult object reflecting the situation; note that a valid QETResult object is returned if the operation was cancelled.
Definition at line 621 of file projectview.cpp.
References askUserForFilePath(), doSave(), m_project, and noProjectResult().
Referenced by doSave().
setDisplayFallbackWidget
void ProjectView::setDisplayFallbackWidget (bool fallback) private slot
Parameters
fallback true pour afficher le widget de fallback, false pour afficher les onglets. Le widget de Fallback est le widget affiche lorsque le projet ne comporte aucun schema.
Definition at line 1017 of file projectview.cpp.
References fallback_widget_, and m_tab.
Referenced by loadDiagrams(), and tabChanged().
setProject()
void ProjectView::setProject (QETProject * project)
ProjectView::setProject Set the project display by the project view.
Parameters
project
Definition at line 74 of file projectview.cpp.
References QETProject::addAutoNumDiagram(), QETProject::addNewDiagram(), adjustReadOnlyState(), diagramAdded(), QETProject::diagramAdded(), loadDiagrams(), m_project, project(), QETProject::projectModified(), QETProject::projectTitleChanged(), QETProject::readOnlyChanged(), and updateWindowTitle().
Referenced by ProjectView().
showDiagram [1/2]
void ProjectView::showDiagram (Diagram * diagram) slot
Active l'onglet adequat pour afficher le schema passe en parametre
Parameters
diagram Schema a afficher
Definition at line 413 of file projectview.cpp.
References findDiagram(), and m_tab.
showDiagram [2/2]
void ProjectView::showDiagram (DiagramView * diagram) slot
Active l'onglet adequat pour afficher le schema passe en parametre
Parameters
diagram Schema a afficher
Definition at line 404 of file projectview.cpp.
References m_tab.
Referenced by diagramAdded(), and editDiagramProperties().
tabChanged
void ProjectView::tabChanged (int tab_id) private slot
ProjectView::tabChanged Manage the tab change. If tab_id == -1 (there is no diagram opened), we display the fallback widget.
Parameters
tab_id
Definition at line 981 of file projectview.cpp.
References diagramActivated(), m_diagram_ids, m_previous_tab_index, m_tab, and setDisplayFallbackWidget().
Referenced by initWidgets().
tabDoubleClicked
void ProjectView::tabDoubleClicked (int tab_id) private slot
Gere le double-clic sur un onglet : edite les proprietes du schema
Parameters
tab_id Index de l'onglet concerne
Definition at line 1003 of file projectview.cpp.
References editDiagramProperties(), and m_diagram_ids.
Referenced by initWidgets().
tabMoved
void ProjectView::tabMoved (int from, int to) slot
Parameters
from Index de l'onglet avant le deplacement
to Index de l'onglet apres le deplacement
Definition at line 930 of file projectview.cpp.
References QETProject::diagramOrderChanged(), m_diagram_ids, m_project, rebuildDiagramsMap(), and updateTabTitle().
Referenced by initWidgets().
tryClosing()
bool ProjectView::tryClosing () private
Cette methode essaye de fermer successivement les editeurs d'element puis les schemas du projet. L'utilisateur peut refuser de fermer un schema ou un editeur.
Returns
true si tout a pu etre ferme, false sinon
See also
tryClosingElementEditors()
tryClosingDiagrams()
Definition at line 211 of file projectview.cpp.
References askUserForFilePath(), QET::Icons::Cancel, errorEncountered(), QETResult::errorMessage(), QETResult::isOk(), m_project, tryClosingDiagrams(), tryClosingElementEditors(), and updateWindowTitle().
Referenced by closeEvent().
tryClosingDiagrams()
int ProjectView::tryClosingDiagrams () private
ProjectView::tryClosingDiagrams try to close this project, if diagram or project option are changed a dialog ask if user want to save the modification.
Returns
the answer of dialog or discard if no change.
Definition at line 284 of file projectview.cpp.
References QET::Icons::Cancel, m_project, project(), QET::QetMessageBox::question(), QETProject::title(), and QET::Icons::tr.
Referenced by tryClosing().
tryClosingElementEditors()
bool ProjectView::tryClosingElementEditors () private
Un projet comporte des elements integres. Cette methode ferme les editeurs d'elements associes a ce projet. L'utilisateur peut refuser la fermeture d'un editeur d'element.
Returns
true si tous les editeurs d'element ont pu etre fermes, false sinon
Definition at line 260 of file projectview.cpp.
References QETApp::elementEditors(), m_project, and QETApp::titleBlockTemplateEditors().
Referenced by tryClosing().
updateAllTabsTitle
void ProjectView::updateAllTabsTitle () slot
ProjectView::updateAllTabsTitle Update all tabs title.
Definition at line 920 of file projectview.cpp.
References m_diagram_ids, and updateTabTitle().
Referenced by diagramAdded(), and removeDiagram().
updateTabTitle
void ProjectView::updateTabTitle (DiagramView * diagram_view) slot
ProjectView::updateTabTitle Update the title of the tab which display the diagram view.
Parameters
diagram_view : The diagram view.
Definition at line 888 of file projectview.cpp.
References Diagram::border_and_titleblock, DiagramView::diagram(), BorderTitleBlock::folio(), Diagram::folioIndex(), autonum::AssignVariables::formulaToLabel(), m_diagram_ids, m_tab, and Diagram::title().
Referenced by diagramAdded(), tabMoved(), and updateAllTabsTitle().
updateWindowTitle
void ProjectView::updateWindowTitle () slot
ProjectView::updateWindowTitle Update the project view title.
Definition at line 828 of file projectview.cpp.
References m_project, and QET::Icons::tr.
Referenced by adjustReadOnlyState(), doSave(), setProject(), and tryClosing().
Member Data Documentation
fallback_label_
QLabel* ProjectView::fallback_label_ private
Definition at line 170 of file projectview.h.
Referenced by initLayout(), and initWidgets().
fallback_widget_
QWidget* ProjectView::fallback_widget_ private
Definition at line 169 of file projectview.h.
Referenced by initLayout(), initWidgets(), and setDisplayFallbackWidget().
layout_
QVBoxLayout* ProjectView::layout_ private
Definition at line 168 of file projectview.h.
Referenced by initLayout().
m_add_new_diagram
QAction* ProjectView::m_add_new_diagram private
Definition at line 166 of file projectview.h.
Referenced by adjustReadOnlyState(), initActions(), and initWidgets().
m_diagram_ids
QMap<int, DiagramView *> ProjectView::m_diagram_ids private
Definition at line 178 of file projectview.h.
Referenced by currentDiagram(), firstDiagram(), lastDiagram(), moveDiagramDown(), moveDiagramDownx10(), moveDiagramUp(), moveDiagramUpTop(), moveDiagramUpx10(), nextDiagram(), previousDiagram(), rebuildDiagramsMap(), removeDiagram(), tabChanged(), tabDoubleClicked(), tabMoved(), updateAllTabsTitle(), updateTabTitle(), and ~ProjectView().
m_diagram_view_list
QList<DiagramView *> ProjectView::m_diagram_view_list private
Definition at line 180 of file projectview.h.
Referenced by diagram_views(), diagramAdded(), rebuildDiagramsMap(), and removeDiagram().
m_previous_tab_index
int ProjectView::m_previous_tab_index = -1 private
Definition at line 179 of file projectview.h.
Referenced by tabChanged().
m_project
QETProject* ProjectView::m_project private
Definition at line 167 of file projectview.h.
Referenced by adjustReadOnlyState(), askUserForFilePath(), cleanProject(), diagramAdded(), doSave(), editProjectProperties(), exportProject(), initActions(), loadDiagrams(), printProject(), project(), removeDiagram(), saveAs(), setProject(), tabMoved(), tryClosing(), tryClosingDiagrams(), tryClosingElementEditors(), and updateWindowTitle().
m_tab
QTabWidget* ProjectView::m_tab private
Definition at line 175 of file projectview.h.
Referenced by adjustReadOnlyState(), changeFirstTab(), changeLastTab(), changeTabDown(), changeTabUp(), currentDiagram(), diagramAdded(), initLayout(), initWidgets(), moveDiagramDown(), moveDiagramDownx10(), moveDiagramUp(), moveDiagramUpTop(), moveDiagramUpx10(), nextDiagram(), previousDiagram(), rebuildDiagramsMap(), removeDiagram(), setDisplayFallbackWidget(), showDiagram(), tabChanged(), and updateTabTitle().
The documentation for this class was generated from the following files:
projectview.h
projectview.cpp