QElectroTech: xpath_ast_node Class Reference
xpath_ast_node Class Reference
Public Member Functions
xpath_ast_node (ast_type_t type, xpath_value_type rettype_, const char_t *value)
xpath_ast_node (ast_type_t type, xpath_value_type rettype_, double value)
xpath_ast_node (ast_type_t type, xpath_value_type rettype_, xpath_variable *value)
xpath_ast_node (ast_type_t type, xpath_value_type rettype_, xpath_ast_node *left=0, xpath_ast_node *right=0)
xpath_ast_node (ast_type_t type, xpath_ast_node *left, axis_t axis, nodetest_t test, const char_t *contents)
xpath_ast_node (ast_type_t type, xpath_ast_node *left, xpath_ast_node *right, predicate_t test)
void set_next (xpath_ast_node *value)
void set_right (xpath_ast_node *value)
bool eval_boolean (const xpath_context &c, const xpath_stack &stack)
double eval_number (const xpath_context &c, const xpath_stack &stack)
xpath_string eval_string_concat (const xpath_context &c, const xpath_stack &stack)
xpath_string eval_string (const xpath_context &c, const xpath_stack &stack)
xpath_node_set_raw eval_node_set (const xpath_context &c, const xpath_stack &stack, nodeset_eval_t eval)
void optimize (xpath_allocator *alloc)
void optimize_self (xpath_allocator *alloc)
bool is_posinv_expr () const
bool is_posinv_step () const
xpath_value_type rettype () const
Private Member Functions
xpath_ast_node (const xpath_ast_node &)
xpath_ast_node & operator= (const xpath_ast_node &)
void apply_predicate (xpath_node_set_raw &ns, size_t first, const xpath_stack &stack, bool once)
void apply_predicates (xpath_node_set_raw &ns, size_t first, const xpath_stack &stack, nodeset_eval_t eval)
bool step_push (xpath_node_set_raw &ns, xml_attribute_struct *a, xml_node_struct *parent, xpath_allocator *alloc)
bool step_push (xpath_node_set_raw &ns, xml_node_struct *n, xpath_allocator *alloc)
template<class T >
void step_fill (xpath_node_set_raw &ns, xml_node_struct *n, xpath_allocator *alloc, bool once, T)
template<class T >
void step_fill (xpath_node_set_raw &ns, xml_attribute_struct *a, xml_node_struct *p, xpath_allocator *alloc, bool once, T v)
template<class T >
void step_fill (xpath_node_set_raw &ns, const xpath_node &xn, xpath_allocator *alloc, bool once, T v)
template<class T >
xpath_node_set_raw step_do (const xpath_context &c, const xpath_stack &stack, nodeset_eval_t eval, T v)
Static Private Member Functions
template<class Comp >
static bool compare_eq (xpath_ast_node *lhs, xpath_ast_node *rhs, const xpath_context &c, const xpath_stack &stack, const Comp &comp)
static bool eval_once (xpath_node_set::type_t type, nodeset_eval_t eval)
template<class Comp >
static bool compare_rel (xpath_ast_node *lhs, xpath_ast_node *rhs, const xpath_context &c, const xpath_stack &stack, const Comp &comp)
static void apply_predicate_boolean (xpath_node_set_raw &ns, size_t first, xpath_ast_node *expr, const xpath_stack &stack, bool once)
static void apply_predicate_number (xpath_node_set_raw &ns, size_t first, xpath_ast_node *expr, const xpath_stack &stack, bool once)
static void apply_predicate_number_const (xpath_node_set_raw &ns, size_t first, xpath_ast_node *expr, const xpath_stack &stack)
Private Attributes
char _type
char _rettype
char _axis
char _test
xpath_ast_node * _left
xpath_ast_node * _right
xpath_ast_node * _next
union {
const char_t * string
double number
xpath_variable * variable
const char_t * nodetest
const unsigned char * table
} _data
Detailed Description
Definition at line 9519 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_ast_node() [1/7]
xpath_ast_node::xpath_ast_node (const xpath_ast_node &) private
xpath_ast_node() [2/7]
xpath_ast_node::xpath_ast_node (ast_type_t type, xpath_value_type rettype_, const char_t * value) inline
Definition at line 10270 of file pugixml.cpp.
References _data, and ast_string_constant.
xpath_ast_node() [3/7]
xpath_ast_node::xpath_ast_node (ast_type_t type, xpath_value_type rettype_, double value) inline
Definition at line 10277 of file pugixml.cpp.
References _data, and ast_number_constant.
xpath_ast_node() [4/7]
xpath_ast_node::xpath_ast_node (ast_type_t type, xpath_value_type rettype_, xpath_variable * value) inline
Definition at line 10284 of file pugixml.cpp.
References _data, and ast_variable.
xpath_ast_node() [5/7]
xpath_ast_node::xpath_ast_node (ast_type_t type, xpath_value_type rettype_, xpath_ast_node * left = 0, xpath_ast_node * right = 0) inline
Definition at line 10291 of file pugixml.cpp.
xpath_ast_node() [6/7]
xpath_ast_node::xpath_ast_node (ast_type_t type, xpath_ast_node * left, axis_t axis, nodetest_t test, const char_t * contents) inline
Definition at line 10296 of file pugixml.cpp.
References _data, and ast_step.
xpath_ast_node() [7/7]
xpath_ast_node::xpath_ast_node (ast_type_t type, xpath_ast_node * left, xpath_ast_node * right, predicate_t test) inline
Definition at line 10303 of file pugixml.cpp.
References ast_filter, and ast_predicate.
Member Function Documentation
apply_predicate()
void xpath_ast_node::apply_predicate (xpath_node_set_raw & ns, size_t first, const xpath_stack & stack, bool once) inline private
Definition at line 9798 of file pugixml.cpp.
References _right, _test, _type, apply_predicate_boolean(), apply_predicate_number(), apply_predicate_number_const(), ast_filter, ast_predicate, predicate_constant, predicate_constant_one, rettype(), and xpath_node_set_raw::size().
Referenced by eval_node_set().
apply_predicate_boolean()
static void xpath_ast_node::apply_predicate_boolean (xpath_node_set_raw & ns, size_t first, xpath_ast_node * expr, const xpath_stack & stack, bool once) inline static private
Definition at line 9718 of file pugixml.cpp.
References xpath_node_set_raw::begin(), xpath_node_set_raw::end(), eval_boolean(), QET::Icons::it, rettype(), xpath_node_set_raw::size(), and xpath_node_set_raw::truncate().
Referenced by apply_predicate().
apply_predicate_number()
static void xpath_ast_node::apply_predicate_number (xpath_node_set_raw & ns, size_t first, xpath_ast_node * expr, const xpath_stack & stack, bool once) inline static private
Definition at line 9744 of file pugixml.cpp.
References xpath_node_set_raw::begin(), xpath_node_set_raw::end(), eval_number(), QET::Icons::it, rettype(), xpath_node_set_raw::size(), and xpath_node_set_raw::truncate().
Referenced by apply_predicate().
apply_predicate_number_const()
static void xpath_ast_node::apply_predicate_number_const (xpath_node_set_raw & ns, size_t first, xpath_ast_node * expr, const xpath_stack & stack) inline static private
Definition at line 9770 of file pugixml.cpp.
References xpath_node_set_raw::begin(), eval_number(), rettype(), xpath_node_set_raw::size(), and xpath_node_set_raw::truncate().
Referenced by apply_predicate().
apply_predicates()
void xpath_ast_node::apply_predicates (xpath_node_set_raw & ns, size_t first, const xpath_stack & stack, nodeset_eval_t eval) inline private
Definition at line 9812 of file pugixml.cpp.
References _next, _right, eval_once(), xpath_node_set_raw::size(), and xpath_node_set_raw::type().
Referenced by step_do().
compare_eq()
template<class Comp > static bool xpath_ast_node::compare_eq (xpath_ast_node * lhs, xpath_ast_node * rhs, const xpath_context & c, const xpath_stack & stack, const Comp & comp) inline static private
Definition at line 9554 of file pugixml.cpp.
References xpath_node_set_raw::begin(), xpath_string::c_str(), convert_string_to_number(), xpath_node_set_raw::end(), eval_boolean(), eval_node_set(), eval_number(), eval_string(), nodeset_eval_all, xpath_stack::result, rettype(), string_value(), and swap().
Referenced by eval_boolean().
compare_rel()
template<class Comp > static bool xpath_ast_node::compare_rel (xpath_ast_node * lhs, xpath_ast_node * rhs, const xpath_context & c, const xpath_stack & stack, const Comp & comp) inline static private
Definition at line 9647 of file pugixml.cpp.
References xpath_node_set_raw::begin(), xpath_string::c_str(), convert_string_to_number(), xpath_node_set_raw::end(), eval_node_set(), eval_number(), nodeset_eval_all, xpath_stack::result, rettype(), and string_value().
Referenced by eval_boolean().
eval_boolean()
bool xpath_ast_node::eval_boolean (const xpath_context & c, const xpath_stack & stack) inline
Definition at line 10319 of file pugixml.cpp.
References _data, _left, _rettype, _right, _type, ast_func_boolean, ast_func_contains, ast_func_false, ast_func_lang, ast_func_not, ast_func_starts_with, ast_func_true, ast_op_and, ast_op_equal, ast_op_greater, ast_op_greater_or_equal, ast_op_less, ast_op_less_or_equal, ast_op_not_equal, ast_op_or, ast_opt_compare_attribute, ast_string_constant, ast_variable, xpath_string::c_str(), compare_eq(), compare_rel(), convert_number_to_boolean(), xpath_string::empty(), xpath_node_set_raw::empty(), eval_boolean(), eval_node_set(), eval_number(), eval_string(), find_substring(), is_xpath_attribute(), xpath_context::n, nodeset_eval_any, nodetest, xpath_stack::result, starts_with(), strequal(), string, tolower_ascii(), and variable.
Referenced by apply_predicate_boolean(), compare_eq(), eval_boolean(), eval_number(), and eval_string().
eval_node_set()
xpath_node_set_raw xpath_ast_node::eval_node_set (const xpath_context & c, const xpath_stack & stack, nodeset_eval_t eval) inline
Definition at line 10882 of file pugixml.cpp.
References _axis, _data, _left, _rettype, _right, _test, _type, xpath_node_set_raw::append(), apply_predicate(), ast_filter, ast_func_id, ast_op_union, ast_step, ast_step_root, ast_variable, axis_ancestor, axis_ancestor_or_self, axis_attribute, axis_child, axis_descendant, axis_descendant_or_self, axis_following, axis_following_sibling, axis_namespace, axis_parent, axis_preceding, axis_preceding_sibling, axis_self, xpath_node_set_raw::begin(), xpath_node_set_raw::end(), eval_node_set(), eval_once(), xpath_context::n, nodeset_eval_all, nodeset_eval_first, predicate_constant_one, predicate_posinv, xpath_node_set_raw::push_back(), xpath_node_set_raw::remove_duplicates(), xpath_stack::result, xpath_node_set_raw::set_type(), xpath_node_set_raw::sort_do(), step_do(), xpath_stack::temp, and xpath_node_set_raw::type().
Referenced by compare_eq(), compare_rel(), eval_boolean(), eval_node_set(), eval_number(), eval_string(), and step_do().
eval_number()
double xpath_ast_node::eval_number (const xpath_context & c, const xpath_stack & stack) inline
Definition at line 10459 of file pugixml.cpp.
References _data, _left, _rettype, _right, _type, ast_func_ceiling, ast_func_count, ast_func_floor, ast_func_last, ast_func_number_0, ast_func_number_1, ast_func_position, ast_func_round, ast_func_string_length_0, ast_func_string_length_1, ast_func_sum, ast_number_constant, ast_op_add, ast_op_divide, ast_op_mod, ast_op_multiply, ast_op_negate, ast_op_subtract, ast_variable, xpath_node_set_raw::begin(), xpath_string::c_str(), convert_string_to_number(), xpath_node_set_raw::end(), eval_boolean(), eval_node_set(), eval_number(), eval_string(), QET::Icons::it, xpath_string::length(), xpath_context::n, nodeset_eval_all, xpath_context::position, xpath_stack::result, round_nearest_nzero(), xpath_node_set_raw::size(), xpath_context::size, and string_value().
Referenced by apply_predicate_number(), apply_predicate_number_const(), compare_eq(), compare_rel(), eval_boolean(), eval_number(), and eval_string().
eval_once()
static bool xpath_ast_node::eval_once (xpath_node_set::type_t type, nodeset_eval_t eval) inline static private
Definition at line 9642 of file pugixml.cpp.
References nodeset_eval_all, and nodeset_eval_any.
Referenced by apply_predicates(), eval_node_set(), and step_do().
eval_string()
xpath_string xpath_ast_node::eval_string (const xpath_context & c, const xpath_stack & stack) inline
Definition at line 10639 of file pugixml.cpp.
References _data, _left, _next, _rettype, _right, _type, ast_func_concat, ast_func_local_name_0, ast_func_local_name_1, ast_func_name_0, ast_func_name_1, ast_func_namespace_uri_0, ast_func_namespace_uri_1, ast_func_normalize_space_0, ast_func_normalize_space_1, ast_func_string_0, ast_func_string_1, ast_func_substring_2, ast_func_substring_3, ast_func_substring_after, ast_func_substring_before, ast_func_translate, ast_opt_translate_table, ast_string_constant, ast_variable, xpath_string::c_str(), convert_number_to_string(), xpath_string::data(), xpath_node_set_raw::empty(), eval_boolean(), eval_node_set(), eval_number(), eval_string(), eval_string_concat(), find_substring(), xpath_node_set_raw::first(), xpath_string::from_const(), xpath_string::from_heap(), xpath_string::from_heap_preallocated(), is_nan(), xpath_string::length(), local_name(), xpath_context::n, namespace_uri(), nodeset_eval_first, normalize_space(), qualified_name(), xpath_stack::result, round_nearest(), string_value(), xpath_stack::temp, translate(), translate_table(), and xpath_string::uses_heap().
Referenced by compare_eq(), eval_boolean(), eval_number(), eval_string(), and eval_string_concat().
eval_string_concat()
xpath_string xpath_ast_node::eval_string_concat (const xpath_context & c, const xpath_stack & stack) inline
Definition at line 10597 of file pugixml.cpp.
References _left, _next, _right, _type, xpath_allocator::allocate(), ast_func_concat, eval_string(), xpath_string::from_heap_preallocated(), xpath_stack::result, and xpath_stack::temp.
Referenced by eval_string().
is_posinv_expr()
bool xpath_ast_node::is_posinv_expr () const inline
Definition at line 11094 of file pugixml.cpp.
References _left, _next, _right, _type, ast_filter, ast_func_last, ast_func_position, ast_number_constant, ast_predicate, ast_step, ast_step_root, ast_string_constant, ast_variable, and is_posinv_expr().
Referenced by is_posinv_expr(), and optimize_self().
is_posinv_step()
bool xpath_ast_node::is_posinv_step () const inline
Definition at line 11125 of file pugixml.cpp.
References _next, _right, _type, ast_predicate, ast_step, and predicate_posinv.
Referenced by optimize_self().
operator=()
xpath_ast_node& xpath_ast_node::operator= (const xpath_ast_node &) private
optimize()
void xpath_ast_node::optimize (xpath_allocator * alloc) inline
Definition at line 11014 of file pugixml.cpp.
References _left, _next, _right, optimize(), and optimize_self().
Referenced by optimize().
optimize_self()
void xpath_ast_node::optimize_self (xpath_allocator * alloc) inline
Definition at line 11029 of file pugixml.cpp.
References _axis, _data, _left, _next, _rettype, _right, _test, _type, ast_filter, ast_func_last, ast_func_position, ast_func_translate, ast_number_constant, ast_op_equal, ast_opt_compare_attribute, ast_opt_translate_table, ast_predicate, ast_step, ast_string_constant, ast_variable, axis_attribute, axis_child, axis_descendant, axis_descendant_or_self, axis_self, is_posinv_expr(), is_posinv_step(), nodetest_name, nodetest_type_node, number, predicate_constant, predicate_constant_one, predicate_default, predicate_posinv, string, table, and translate_table_generate().
Referenced by optimize().
rettype()
xpath_value_type xpath_ast_node::rettype () const inline
Definition at line 11140 of file pugixml.cpp.
References _rettype.
Referenced by apply_predicate(), apply_predicate_boolean(), apply_predicate_number(), apply_predicate_number_const(), compare_eq(), compare_rel(), evaluate_node_set_prepare(), xpath_parser::parse_expression_rec(), xpath_parser::parse_filter_expression(), xpath_parser::parse_path_or_unary_expression(), and xpath_parser::parse_step().
set_next()
void xpath_ast_node::set_next (xpath_ast_node * value) inline
Definition at line 10309 of file pugixml.cpp.
References _next.
Referenced by xpath_parser::parse_primary_expression(), and xpath_parser::parse_step().
set_right()
void xpath_ast_node::set_right (xpath_ast_node * value) inline
Definition at line 10314 of file pugixml.cpp.
References _right.
Referenced by xpath_parser::parse_step().
step_do()
template<class T > xpath_node_set_raw xpath_ast_node::step_do (const xpath_context & c, const xpath_stack & stack, nodeset_eval_t eval, T v) inline private
Definition at line 10222 of file pugixml.cpp.
References _left, _next, _right, _test, apply_predicates(), axis_ancestor, axis_ancestor_or_self, axis_attribute, axis_child, axis_preceding, axis_preceding_sibling, axis_self, xpath_node_set_raw::begin(), xpath_node_set_raw::end(), eval_node_set(), eval_once(), QET::Icons::it, xpath_context::n, nodeset_eval_all, nodetest_name, predicate_constant_one, xpath_node_set_raw::remove_duplicates(), xpath_stack::result, xpath_node_set_raw::set_type(), xpath_node_set_raw::size(), step_fill(), xpath_stack::temp, and xpath_node_set_raw::type().
Referenced by eval_node_set().
step_fill() [1/3]
template<class T > void xpath_ast_node::step_fill (xpath_node_set_raw & ns, const xpath_node & xn, xpath_allocator * alloc, bool once, T v) inline private
Definition at line 10211 of file pugixml.cpp.
References axis_ancestor, axis_ancestor_or_self, axis_descendant_or_self, axis_following, axis_parent, axis_preceding, axis_self, and step_fill().
step_fill() [2/3]
template<class T > void xpath_ast_node::step_fill (xpath_node_set_raw & ns, xml_attribute_struct * a, xml_node_struct * p, xpath_allocator * alloc, bool once, T v) inline private
Definition at line 10130 of file pugixml.cpp.
References _test, axis_ancestor, axis_ancestor_or_self, axis_descendant_or_self, axis_following, axis_parent, axis_preceding, axis_self, nodetest_type_node, step_fill(), and step_push().
step_fill() [3/3]
template<class T > void xpath_ast_node::step_fill (xpath_node_set_raw & ns, xml_node_struct * n, xpath_allocator * alloc, bool once, T) inline private
Definition at line 9937 of file pugixml.cpp.
References axis_ancestor, axis_ancestor_or_self, axis_attribute, axis_child, axis_descendant, axis_descendant_or_self, axis_following, axis_following_sibling, axis_parent, axis_preceding, axis_preceding_sibling, axis_self, node_is_ancestor(), and step_push().
Referenced by step_do(), and step_fill().
step_push() [1/2]
bool xpath_ast_node::step_push (xpath_node_set_raw & ns, xml_attribute_struct * a, xml_node_struct * parent, xpath_allocator * alloc) inline private
Definition at line 9822 of file pugixml.cpp.
References _data, _test, is_xpath_attribute(), nodetest_all, nodetest_all_in_namespace, nodetest_name, nodetest_type_node, xpath_node_set_raw::push_back(), starts_with(), and strequal().
Referenced by step_fill().
step_push() [2/2]
bool xpath_ast_node::step_push (xpath_node_set_raw & ns, xml_node_struct * n, xpath_allocator * alloc) inline private
Definition at line 9862 of file pugixml.cpp.
References _data, _test, nodetest_all, nodetest_all_in_namespace, nodetest_name, nodetest_pi, nodetest_type_comment, nodetest_type_node, nodetest_type_pi, nodetest_type_text, PUGI__NODETYPE, xpath_node_set_raw::push_back(), starts_with(), and strequal().
Member Data Documentation
_axis
char xpath_ast_node::_axis private
Definition at line 9527 of file pugixml.cpp.
Referenced by eval_node_set(), and optimize_self().
_data
union { ... } xpath_ast_node::_data
Referenced by eval_boolean(), eval_node_set(), eval_number(), eval_string(), optimize_self(), step_push(), and xpath_ast_node().
_left
xpath_ast_node* xpath_ast_node::_left private
Definition at line 9533 of file pugixml.cpp.
Referenced by eval_boolean(), eval_node_set(), eval_number(), eval_string(), eval_string_concat(), is_posinv_expr(), optimize(), optimize_self(), and step_do().
_next
xpath_ast_node* xpath_ast_node::_next private
Definition at line 9535 of file pugixml.cpp.
Referenced by apply_predicates(), eval_string(), eval_string_concat(), is_posinv_expr(), is_posinv_step(), optimize(), optimize_self(), set_next(), and step_do().
_rettype
char xpath_ast_node::_rettype private
Definition at line 9524 of file pugixml.cpp.
Referenced by eval_boolean(), eval_node_set(), eval_number(), eval_string(), optimize_self(), and rettype().
_right
xpath_ast_node* xpath_ast_node::_right private
Definition at line 9534 of file pugixml.cpp.
Referenced by apply_predicate(), apply_predicates(), eval_boolean(), eval_node_set(), eval_number(), eval_string(), eval_string_concat(), is_posinv_expr(), is_posinv_step(), optimize(), optimize_self(), set_right(), and step_do().
_test
char xpath_ast_node::_test private
Definition at line 9530 of file pugixml.cpp.
Referenced by apply_predicate(), eval_node_set(), optimize_self(), step_do(), step_fill(), and step_push().
_type
char xpath_ast_node::_type private
Definition at line 9523 of file pugixml.cpp.
Referenced by apply_predicate(), eval_boolean(), eval_node_set(), eval_number(), eval_string(), eval_string_concat(), is_posinv_expr(), is_posinv_step(), and optimize_self().
nodetest
const char_t* xpath_ast_node::nodetest
Definition at line 9546 of file pugixml.cpp.
Referenced by eval_boolean().
number
double xpath_ast_node::number
Definition at line 9542 of file pugixml.cpp.
Referenced by optimize_self().
string
const char_t* xpath_ast_node::string
Definition at line 9540 of file pugixml.cpp.
Referenced by eval_boolean(), and optimize_self().
table
const unsigned char* xpath_ast_node::table
Definition at line 9548 of file pugixml.cpp.
Referenced by optimize_self().
variable
xpath_variable* xpath_ast_node::variable
Definition at line 9544 of file pugixml.cpp.
Referenced by eval_boolean().
The documentation for this class was generated from the following file:
pugixml.cpp