QElectroTech: TerminalEditor Class Reference
TerminalEditor Class Reference
The TerminalEditor class This class provides a widget to edit terminals within the element editor. The class is capable to change the values of multiple parts of the same time. The displayed values are from the first selected element.
#include <terminaleditor.h>
Public Slots
void updateTerminalO ()
Met a jour l'orientation de la borne et cree un objet d'annulation.
void updateXPos ()
TerminalEditor::updateXPos.
void updateYPos ()
TerminalEditor::updateYPos.
void updateForm () override
update Number and name, create cancel object
Public Member Functions
TerminalEditor (QETElementEditor *, QList< PartTerminal * > &terms, QWidget *=nullptr)
TerminalEditor::TerminalEditor Constructeur.
TerminalEditor (QETElementEditor *, QWidget *=nullptr)
TerminalEditor::TerminalEditor.
~TerminalEditor () override
TerminalEditor::~TerminalEditor Destructeur.
bool setPart (CustomElementPart *) override
bool setParts (QList< CustomElementPart * > parts) override
CustomElementPart * currentPart () const override
QList< CustomElementPart * > currentParts () const override
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
virtual void updateForm ()=0
Private Member Functions
TerminalEditor (const TerminalEditor &)
void init ()
TerminalEditor::init.
void activeConnections (bool)
Private Attributes
QList< PartTerminal * > m_terminals
PartTerminal * m_part {nullptr}
QDoubleSpinBox * qle_x
QDoubleSpinBox * qle_y
QComboBox * orientation
bool m_locked {false}
Detailed Description
The TerminalEditor class This class provides a widget to edit terminals within the element editor. The class is capable to change the values of multiple parts of the same time. The displayed values are from the first selected element.
Definition at line 33 of file terminaleditor.h.
Constructor & Destructor Documentation
TerminalEditor() [1/3]
TerminalEditor::TerminalEditor (QETElementEditor * editor, QList< PartTerminal * > & terms, QWidget * parent = nullptr)
TerminalEditor::TerminalEditor Constructeur.
Parameters
editor : L'editeur d'element concerne
terms : La borne a editer
parent : QWidget parent de ce widget
Definition at line 50 of file terminaleditor.cpp.
References init().
TerminalEditor() [2/3]
TerminalEditor::TerminalEditor (QETElementEditor * editor, QWidget * parent = nullptr)
TerminalEditor::TerminalEditor.
Parameters
editor
parent
Definition at line 33 of file terminaleditor.cpp.
References init(), m_part, and m_terminals.
~TerminalEditor()
TerminalEditor::~TerminalEditor () override
TerminalEditor::~TerminalEditor Destructeur.
Definition at line 101 of file terminaleditor.cpp.
TerminalEditor() [3/3]
TerminalEditor::TerminalEditor (const TerminalEditor &) private
Member Function Documentation
activeConnections()
void TerminalEditor::activeConnections (bool active) private
Active ou desactive les connexionx signaux/slots entre les widgets internes.
Parameters
active true pour activer les connexions, false pour les desactiver
Definition at line 253 of file terminaleditor.cpp.
References orientation, qle_x, qle_y, updateTerminalO(), updateXPos(), and updateYPos().
Referenced by init(), and updateForm().
currentPart()
CustomElementPart * TerminalEditor::currentPart () const override virtual
Returns
la primitive actuellement editee, ou 0 si ce widget n'en edite pas
Implements ElementItemEditor.
Definition at line 164 of file terminaleditor.cpp.
References m_part.
currentParts()
QList< CustomElementPart * > TerminalEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 168 of file terminaleditor.cpp.
References m_terminals.
init()
void TerminalEditor::init () private
TerminalEditor::init.
Definition at line 62 of file terminaleditor.cpp.
References activeConnections(), QET::Icons::East, Qet::East, QET::Icons::North, Qet::North, orientation, qle_x, qle_y, QET::Icons::South, Qet::South, QET::Icons::tr, updateForm(), QET::Icons::West, and Qet::West.
Referenced by TerminalEditor().
setPart()
bool TerminalEditor::setPart (CustomElementPart * new_part) override virtual
Permet de specifier a cet editeur quelle primitive il doit editer. A noter qu'un editeur peut accepter ou refuser d'editer une primitive. L'editeur de borne acceptera d'editer la primitive new_part s'il s'agit d'un objet de la classe PartTerminal.
Parameters
new_part Nouvelle primitive a editer
Returns
true si l'editeur a accepter d'editer la primitive, false sinon
Implements ElementItemEditor.
Definition at line 112 of file terminaleditor.cpp.
References m_part, m_terminals, PartTerminal::orientationChanged(), and updateForm().
setParts()
bool TerminalEditor::setParts (QList< CustomElementPart * > parts) override virtual
Reimplemented from ElementItemEditor.
Definition at line 134 of file terminaleditor.cpp.
References m_part, m_terminals, PartTerminal::orientationChanged(), and updateForm().
updateForm
void TerminalEditor::updateForm () override slot
update Number and name, create cancel object
Met a jour le formulaire d'edition
Definition at line 240 of file terminaleditor.cpp.
References activeConnections(), m_part, orientation, CustomElementGraphicPart::property(), qle_x, and qle_y.
Referenced by init(), setPart(), and setParts().
updateTerminalO
void TerminalEditor::updateTerminalO () slot
Met a jour l'orientation de la borne et cree un objet d'annulation.
Definition at line 177 of file terminaleditor.cpp.
References m_locked, m_terminals, orientation, CustomElementGraphicPart::property(), QET::Icons::tr, and ElementItemEditor::undoStack().
Referenced by activeConnections().
updateXPos
void TerminalEditor::updateXPos () slot
TerminalEditor::updateXPos.
Definition at line 197 of file terminaleditor.cpp.
References QPropertyUndoCommand::enableAnimation(), m_locked, m_terminals, CustomElementGraphicPart::property(), qle_x, QET::Icons::tr, and ElementItemEditor::undoStack().
Referenced by activeConnections().
updateYPos
void TerminalEditor::updateYPos () slot
TerminalEditor::updateYPos.
Definition at line 218 of file terminaleditor.cpp.
References QPropertyUndoCommand::enableAnimation(), m_locked, m_terminals, CustomElementGraphicPart::property(), qle_y, QET::Icons::tr, and ElementItemEditor::undoStack().
Referenced by activeConnections().
Member Data Documentation
m_locked
bool TerminalEditor::m_locked {false} private
Definition at line 53 of file terminaleditor.h.
Referenced by updateTerminalO(), updateXPos(), and updateYPos().
m_part
PartTerminal* TerminalEditor::m_part {nullptr} private
Definition at line 50 of file terminaleditor.h.
Referenced by currentPart(), setPart(), setParts(), TerminalEditor(), and updateForm().
m_terminals
QList<PartTerminal *> TerminalEditor::m_terminals private
Definition at line 49 of file terminaleditor.h.
Referenced by currentParts(), setPart(), setParts(), TerminalEditor(), updateTerminalO(), updateXPos(), and updateYPos().
orientation
QComboBox* TerminalEditor::orientation private
Definition at line 52 of file terminaleditor.h.
Referenced by activeConnections(), init(), updateForm(), and updateTerminalO().
qle_x
QDoubleSpinBox* TerminalEditor::qle_x private
Definition at line 51 of file terminaleditor.h.
Referenced by activeConnections(), init(), updateForm(), and updateXPos().
qle_y
QDoubleSpinBox * TerminalEditor::qle_y private
Definition at line 51 of file terminaleditor.h.
Referenced by activeConnections(), init(), updateForm(), and updateYPos().
The documentation for this class was generated from the following files:
terminaleditor.h
terminaleditor.cpp