QElectroTech: ConductorXmlRetroCompatibility Class Reference
ConductorXmlRetroCompatibility Class Reference
Static Private Member Functions
static void loadSequential (const QDomElement &dom_element, const QString &seq, QStringList *list)
static void loadSequential (const QDomElement &dom_element, Conductor *conductor)
Friends
class Conductor
Detailed Description
Definition at line 42 of file conductor.cpp.
Member Function Documentation
loadSequential() [1/2]
static void ConductorXmlRetroCompatibility::loadSequential (const QDomElement & dom_element, Conductor * conductor) inline static private
Definition at line 56 of file conductor.cpp.
References autonum::sequentialNumbers::hundred, autonum::sequentialNumbers::hundred_folio, loadSequential(), Conductor::rSequenceNum(), autonum::sequentialNumbers::ten, autonum::sequentialNumbers::ten_folio, autonum::sequentialNumbers::unit, and autonum::sequentialNumbers::unit_folio.
loadSequential() [2/2]
static void ConductorXmlRetroCompatibility::loadSequential (const QDomElement & dom_element, const QString & seq, QStringList * list) inline static private
Definition at line 46 of file conductor.cpp.
Referenced by Conductor::fromXml(), and loadSequential().
Friends And Related Function Documentation
Conductor
friend class Conductor friend
Definition at line 44 of file conductor.cpp.
The documentation for this class was generated from the following file:
conductor.cpp