QElectroTech: QetGraphicsTableFactory Class Reference
QetGraphicsTableFactory Class Reference
The QetGraphicsTableFactory class.
#include <qetgraphicstablefactory.h>
Public Member Functions
QetGraphicsTableFactory ()
Static Public Member Functions
static void createAndAddNomenclature (Diagram *diagram)
QetGraphicsTableFactory::createAndAddNomenclature Open a dialog for ask user the config of the table, create a nomenclature table and add it to diagram.
static void createAndAddSummary (Diagram *diagram)
QetGraphicsTableFactory::createAndAddSummary Open a dialog for ask user the config of the table, create a summary table and add it to diagram.
Static Private Member Functions
static void create (Diagram *diagram, AddTableDialog *dialog)
static QetGraphicsTableItem * newTable (Diagram *diagram, AddTableDialog *dialog, QetGraphicsTableItem *previous_table=nullptr)
QetGraphicsTableFactory::newTable Create a new table .
Detailed Description
The QetGraphicsTableFactory class.
Definition at line 28 of file qetgraphicstablefactory.h.
Constructor & Destructor Documentation
QetGraphicsTableFactory()
QetGraphicsTableFactory::QetGraphicsTableFactory ()
Definition at line 31 of file qetgraphicstablefactory.cpp.
Member Function Documentation
create()
void QetGraphicsTableFactory::create (Diagram * diagram, AddTableDialog * dialog) static private
Definition at line 74 of file qetgraphicstablefactory.cpp.
References AddTableDialog::addNewTableToNewDiagram(), AddTableDialog::adjustTableToFolio(), QetGraphicsTableItem::adjustTableToFolio(), newTable(), Diagram::project(), and AddTableDialog::tableName().
Referenced by createAndAddNomenclature(), and createAndAddSummary().
createAndAddNomenclature()
void QetGraphicsTableFactory::createAndAddNomenclature (Diagram * diagram) static
QetGraphicsTableFactory::createAndAddNomenclature Open a dialog for ask user the config of the table, create a nomenclature table and add it to diagram.
Parameters
diagram
Definition at line 42 of file qetgraphicstablefactory.cpp.
References create(), and QET::Icons::tr.
Referenced by QETDiagramEditor::setUpActions().
createAndAddSummary()
void QetGraphicsTableFactory::createAndAddSummary (Diagram * diagram) static
QetGraphicsTableFactory::createAndAddSummary Open a dialog for ask user the config of the table, create a summary table and add it to diagram.
Parameters
diagram
Definition at line 61 of file qetgraphicstablefactory.cpp.
References create(), and QET::Icons::tr.
Referenced by QETDiagramEditor::setUpActions().
newTable()
QetGraphicsTableItem * QetGraphicsTableFactory::newTable (Diagram * diagram, AddTableDialog * dialog, QetGraphicsTableItem * previous_table = nullptr) static private
QetGraphicsTableFactory::newTable Create a new table .
Parameters
diagram : Diagram where we must add the new table.
dialog : dialog conf, it's used to setup the model.
previous_table : If you know that the new table will have a previous table and you already now the previous table, set it now they will improve time needed for creating the new table by avoiding to create a new model.
Returns
the new table
Definition at line 121 of file qetgraphicstablefactory.cpp.
References Diagram::addItem(), AddTableDialog::contentWidget(), AddTableDialog::headerAlignment(), AddTableDialog::headerFont(), AddTableDialog::headerMargins(), QET::Horizontal, QETUtils::marginsToString(), Diagram::project(), AddTableDialog::tableAlignment(), AddTableDialog::tableFont(), and AddTableDialog::tableName().
Referenced by create().
The documentation for this class was generated from the following files:
qetgraphicstablefactory.h
qetgraphicstablefactory.cpp