QElectroTech: TitleBlockTemplate Class Reference
TitleBlockTemplate Class Reference
The TitleBlockTemplate class This class represents an title block template for an electric diagram. It can read from an XML document the layout of the table that graphically represents the title block, and can produce a graphical rendering of it from a diagram context (object embedding the informations of the diagram we want to represent the title block.
#include <titleblocktemplate.h>
Public Member Functions
TitleBlockTemplate (QObject *=nullptr)
TitleBlockTemplate::TitleBlockTemplate Constructor.
~TitleBlockTemplate () override
TitleBlockTemplate::~TitleBlockTemplate Destructor.
TitleBlockCell * createCell (const TitleBlockCell *=nullptr)
TitleBlockTemplate::createCell Create a new cell and associate it with this template, which means that it will be deleted when this template is destroyed.
bool loadFromXmlFile (const QString &)
TitleBlockTemplate::loadFromXmlFile Load a titleblock template from an XML file.
bool loadFromXmlElement (const QDomElement &)
TitleBlockTemplate::loadFromXmlElement.
bool saveToXmlFile (const QString &)
TitleBlockTemplate::saveToXmlFile Save the title block template into an XML file.
bool saveToXmlElement (QDomElement &) const
TitleBlockTemplate::saveToXmlElement Save the title block template as XML.
void exportCellToXml (TitleBlockCell *, QDomElement &) const
TitleBlockTemplate::exportCellToXml.
TitleBlockTemplate * clone () const
TitleBlockTemplate::clone.
QString name () const
TitleBlockTemplate::name.
QString information () const
TitleBlockTemplate::information.
void setInformation (const QString &)
TitleBlockTemplate::setInformation.
int rowDimension (int)
TitleBlockTemplate::rowDimension.
void setRowDimension (int, const TitleBlockDimension &)
TitleBlockTemplate::setRowDimension Set the height of a row.
TitleBlockDimension columnDimension (int)
TitleBlockTemplate::columnDimension.
void setColumnDimension (int, const TitleBlockDimension &)
TitleBlockTemplate::setColumnDimension Set the width of a column.
int columnsCount () const
TitleBlockTemplate::columnsCount.
int rowsCount () const
TitleBlockTemplate::rowsCount.
QList< int > columnsWidth (int) const
TitleBlockTemplate::columnsWidth.
QList< int > rowsHeights () const
TitleBlockTemplate::rowsHeights.
int columnTypeCount (QET::TitleBlockColumnLength)
TitleBlockTemplate::columnTypeCount.
int columnTypeTotal (QET::TitleBlockColumnLength)
TitleBlockTemplate::columnTypeTotal.
int minimumWidth ()
int maximumWidth ()
TitleBlockTemplate::maximumWidth.
int width (int)
TitleBlockTemplate::width.
int height () const
TitleBlockTemplate::height.
bool moveRow (int, int)
TitleBlockTemplate::moveRow Move a row within this template.
void addRow (int=-1)
TitleBlockTemplate::addRow Add a new 25px-wide row at the provided index.
bool insertRow (int, const QList< TitleBlockCell * > &, int=-1)
TitleBlockTemplate::insertRow.
QList< TitleBlockCell * > takeRow (int)
TitleBlockTemplate::takeRow Removes the row at index i.
QList< TitleBlockCell * > createRow ()
TitleBlockTemplate::createRow.
bool moveColumn (int, int)
TitleBlockTemplate::moveColumn Move the column at index "from" to index "to".
void addColumn (int=-1)
TitleBlockTemplate::addColumn Add a new 50px-wide column at the provided index.
bool insertColumn (const TitleBlockDimension &, const QList< TitleBlockCell * > &, int=-1)
TitleBlockTemplate::insertColumn.
QList< TitleBlockCell * > takeColumn (int)
TitleBlockTemplate::takeColumn Removes the column at index i.
QList< TitleBlockCell * > createColumn ()
TitleBlockTemplate::createColumn.
TitleBlockCell * cell (int, int) const
TitleBlockTemplate::cell.
QSet< TitleBlockCell * > spannedCells (const TitleBlockCell *, bool=false) const
TitleBlockTemplate::spannedCells.
QHash< TitleBlockCell *, QPair< int, int > > getAllSpans () const
TitleBlockTemplate::getAllSpans Export the span parameters of all cell in the current grid.
void setAllSpans (const QHash< TitleBlockCell *, QPair< int, int > > &)
TitleBlockTemplate::setAllSpans Restore a set of span parameters.
bool addLogo (const QString &, QByteArray *, const QString &="svg", const QString &="xml")
TitleBlockTemplate::addLogo.
bool addLogoFromFile (const QString &, const QString &=QString())
TitleBlockTemplate::addLogoFromFile.
bool saveLogoToFile (const QString &, const QString &)
TitleBlockTemplate::saveLogoToFile.
bool removeLogo (const QString &)
TitleBlockTemplate::removeLogo.
bool renameLogo (const QString &, const QString &)
TitleBlockTemplate::renameLogo Rename the logo_name logo to new_name.
void setLogoStorage (const QString &, const QString &)
TitleBlockTemplate::setLogoStorage Set the kind of storage for the logo_name logo.
QList< QString > logos () const
TitleBlockTemplate::logos.
QString logoType (const QString &) const
TitleBlockTemplate::logoType.
QSvgRenderer * vectorLogo (const QString &) const
TitleBlockTemplate::vectorLogo.
QPixmap bitmapLogo (const QString &) const
TitleBlockTemplate::bitmapLogo.
void render (QPainter &, const DiagramContext &, int) const
TitleBlockTemplate::render Render the titleblock.
void renderDxf (QRectF &, const DiagramContext &, int, QString &, int) const
TitleBlockTemplate::renderDxf Render the titleblock in DXF.
void renderCell (QPainter &, const TitleBlockCell &, const DiagramContext &, const QRect &) const
TitleBlockTemplate::renderCell Render a titleblock cell.
void applyCellSpans ()
TitleBlockTemplate::applyCellSpans Forget any previously applied span, then apply again all spans defined by existing cells.
void forgetSpanning ()
TitleBlockTemplate::forgetSpanning Set the spanner_cell attribute of every cell to 0.
void forgetSpanning (TitleBlockCell *, bool=true)
TitleBlockTemplate::forgetSpanning Set the spanner_cell attribute of every cell spanned by spanning_cell to 0.
bool checkCellSpan (TitleBlockCell *)
TitleBlockTemplate::checkCellSpan Check whether a given cell can be spanned according to its row_span and col_span attributes. the following attributes of cell are updated according to what is really possible: applied_col_span applied_row_span span_state.
void applyCellSpan (TitleBlockCell *)
TitleBlockTemplate::applyCellSpan Ensure the spans of the provided cell are applied within the grid structure.
void applyRowColNums ()
TitleBlockTemplate::applyRowColNums Ensure all cells have the right col+row numbers.
void rowColsChanged ()
TitleBlockTemplate::rowColsChanged Take care of consistency and span-related problematics when adding/moving/deleting rows and columns.
QStringList listOfVariables ()
TitleBlockTemplate::listOfVariables Get list of variables.
Static Public Member Functions
static QFont fontForCell (const TitleBlockCell &)
TitleBlockTemplate::fontForCell.
Protected Member Functions
void loadInformation (const QDomElement &)
TitleBlockTemplate::loadInformation Import text informations from a given XML title block template.
bool loadLogos (const QDomElement &, bool=false)
TitleBlockTemplate::loadLogos Import the logos from a given XML titleblock template.
bool loadLogo (const QDomElement &)
TitleBlockTemplate::loadLogo Import the logo from a given XML logo description.
bool loadGrid (const QDomElement &)
bool loadCells (const QDomElement &)
TitleBlockTemplate::loadCells Analyze an XML element, looking for grid cells. The grid cells are checked and stored in this object.
void loadCell (const QDomElement &)
TitleBlockTemplate::loadCell Load a cell into this template.
void saveInformation (QDomElement &) const
TitleBlockTemplate::saveInformation Export this template's extra information.
void saveLogos (QDomElement &) const
TitleBlockTemplate::saveLogos Export this template's logos as XML.
void saveLogo (const QString &, QDomElement &) const
TitleBlockTemplate::saveLogo Export a specific logo as XML.
void saveGrid (QDomElement &) const
TitleBlockTemplate::saveGrid Export this template's cells grid as XML.
void saveCells (QDomElement &) const
TitleBlockTemplate::saveCells Export this template's cells as XML (without the grid-related information, usch as rows and cols)
void saveCell (TitleBlockCell *, QDomElement &, bool=false) const
TitleBlockTemplate::saveCell Export a specific cell as XML.
QList< TitleBlockCell * > createCellsList (int)
TitleBlockTemplate::createCellsList.
Private Member Functions
TitleBlockTemplate (const TitleBlockTemplate &)
void parseRows (const QString &)
TitleBlockTemplate::parseRows Parse the rows heights.
void parseColumns (const QString &)
TitleBlockTemplate::parseColumns Parse the columns widths.
bool checkCell (const QDomElement &, TitleBlockCell **=nullptr)
TitleBlockTemplate::checkCell Load the essential attributes of a cell: row and column indices and spans.
void flushCells ()
void initCells ()
TitleBlockTemplate::initCells Initialize the internal cells grid with the row and column counts. Note that this method does nothing if one of the internal lists columns_width_ and rows_heights_ is empty.
int lengthRange (int, int, const QList< int > &) const
TitleBlockTemplate::lengthRange.
QString finalTextForCell (const TitleBlockCell &, const DiagramContext &) const
TitleBlockTemplate::finalTextForCell.
QString interpreteVariables (const QString &, const DiagramContext &) const
TitleBlockTemplate::interpreteVariables.
void renderTextCell (QPainter &, const QString &, const TitleBlockCell &, const QRectF &) const
TitleBlockTemplate::renderTextCell This method uses a painter to render the text of a cell into the cell_rect rectangle. The alignment, font_size and other cell parameters are taken into account when rendering.
void renderTextCellDxf (QString &, const QString &, const TitleBlockCell &, qreal, qreal, qreal, qreal, int) const
TitleBlockTemplate::renderTextCellDxf.
Private Attributes
QString name_
name_ : name identifying the Title Block Template within its parent collection
QString information_
QHash< QString, QByteArray > data_logos_
data_logos_ : Logos raw data
QHash< QString, QString > storage_logos_
storage_logos_ : Logos applied storage type (e.g. "xml" or "base64")
QHash< QString, QString > type_logos_
type_logos_ : Logos types (e.g. "png", "jpeg", "svg")
QHash< QString, QSvgRenderer * > vector_logos_
vector_logos_ : Rendered objects for vector logos
QHash< QString, QPixmap > bitmap_logos_
bitmap_logos_ : Pixmaps for bitmap logos
QList< int > rows_heights_
rows heights – simple integers
QList< TitleBlockDimension > columns_width_
columns_width_ : columns widths –
QList< TitleBlockCell * > registered_cells_
registered_cells_ : Cells objects created rattached to this template, but not mandatorily used
QList< QList< TitleBlockCell * > > cells_
Cells grid.
Detailed Description
The TitleBlockTemplate class This class represents an title block template for an electric diagram. It can read from an XML document the layout of the table that graphically represents the title block, and can produce a graphical rendering of it from a diagram context (object embedding the informations of the diagram we want to represent the title block.
Definition at line 36 of file titleblocktemplate.h.
Constructor & Destructor Documentation
TitleBlockTemplate() [1/2]
TitleBlockTemplate::TitleBlockTemplate (QObject * parent = nullptr)
TitleBlockTemplate::TitleBlockTemplate Constructor.
Parameters
parent parent QObject
Definition at line 31 of file titleblocktemplate.cpp.
Referenced by clone().
~TitleBlockTemplate()
TitleBlockTemplate::~TitleBlockTemplate () override
TitleBlockTemplate::~TitleBlockTemplate Destructor.
Definition at line 40 of file titleblocktemplate.cpp.
References loadLogos(), and registered_cells_.
TitleBlockTemplate() [2/2]
TitleBlockTemplate::TitleBlockTemplate (const TitleBlockTemplate &) private
Member Function Documentation
addColumn()
void TitleBlockTemplate::addColumn (int i = -1)
TitleBlockTemplate::addColumn Add a new 50px-wide column at the provided index.
Parameters
i : Index of the added column, -1 meaning "last position"
Definition at line 1090 of file titleblocktemplate.cpp.
References QET::Absolute, createColumn(), and insertColumn().
addLogo()
bool TitleBlockTemplate::addLogo (const QString & logo_name, QByteArray * logo_data, const QString & logo_type = "svg", const QString & logo_storage = "xml")
TitleBlockTemplate::addLogo.
Parameters
logo_name : Logo name to be added / replaced
logo_data : Logo data
logo_type :
logo_storage :
Returns
true or false
Definition at line 1239 of file titleblocktemplate.cpp.
References bitmap_logos_, data_logos_, removeLogo(), storage_logos_, type_logos_, and vector_logos_.
Referenced by addLogoFromFile(), and loadLogo().
addLogoFromFile()
bool TitleBlockTemplate::addLogoFromFile (const QString & filepath, const QString & name = QString())
TitleBlockTemplate::addLogoFromFile.
Parameters
filepath : Path of the image file to add as a logo
name : Name used to store the logo; if none is provided, the basename of the first argument is used.
Returns
true if the logo could be deleted, false otherwise
Definition at line 1293 of file titleblocktemplate.cpp.
References addLogo(), and name().
addRow()
void TitleBlockTemplate::addRow (int i = -1)
TitleBlockTemplate::addRow Add a new 25px-wide row at the provided index.
Parameters
i : Index of the added row, -1 meaning "last position"
Definition at line 1015 of file titleblocktemplate.cpp.
References createRow(), and insertRow().
applyCellSpan()
void TitleBlockTemplate::applyCellSpan (TitleBlockCell * cell)
TitleBlockTemplate::applyCellSpan Ensure the spans of the provided cell are applied within the grid structure.
Note
: this function does not check whether the spans of the provided cell make sense.
Parameters
cell : Potentially spanning cell
Definition at line 1983 of file titleblocktemplate.cpp.
References cell(), cells_, and TitleBlockCell::Disabled.
Referenced by applyCellSpans().
applyCellSpans()
void TitleBlockTemplate::applyCellSpans ()
TitleBlockTemplate::applyCellSpans Forget any previously applied span, then apply again all spans defined by existing cells.
Definition at line 1905 of file titleblocktemplate.cpp.
References applyCellSpan(), cells_, checkCellSpan(), columns_width_, forgetSpanning(), and rows_heights_.
Referenced by loadGrid(), and rowColsChanged().
applyRowColNums()
void TitleBlockTemplate::applyRowColNums ()
TitleBlockTemplate::applyRowColNums Ensure all cells have the right col+row numbers.
Definition at line 2016 of file titleblocktemplate.cpp.
References cells_, columns_width_, and rows_heights_.
Referenced by loadGrid(), and rowColsChanged().
bitmapLogo()
QPixmap TitleBlockTemplate::bitmapLogo (const QString & logo_name) const
TitleBlockTemplate::bitmapLogo.
Parameters
logo_name : Name of a logo embedded within this title block template.
Returns
the pixmap for the required bitmap logo, or a null pixmap if no such bitmap logo was found in this template.
Definition at line 1444 of file titleblocktemplate.cpp.
References bitmap_logos_.
cell()
TitleBlockCell * TitleBlockTemplate::cell (int row, int col) const
TitleBlockTemplate::cell.
Parameters
row : A row number (starting from 0)
col : A column number (starting from 0)
Returns
the cell located at (row, col)
Definition at line 1143 of file titleblocktemplate.cpp.
References cells_, columns_width_, and rows_heights_.
Referenced by applyCellSpan(), checkCellSpan(), exportCellToXml(), finalTextForCell(), fontForCell(), renderCell(), renderTextCell(), renderTextCellDxf(), saveCell(), setAllSpans(), and spannedCells().
checkCell()
bool TitleBlockTemplate::checkCell (const QDomElement & xml_element, TitleBlockCell ** titleblock_cell_ptr = nullptr) private
TitleBlockTemplate::checkCell Load the essential attributes of a cell: row and column indices and spans.
Parameters
xml_element : XML element representing a cell, i.e. either an titleblock logo or an titleblock field.
titleblock_cell_ptr : Pointer to a TitleBlockCell object pointer - if non-zero and if this method returns true, will be filled with the created TitleBlockCell
Returns
TRUE if the cell appears to be ok, FALSE otherwise
Definition at line 648 of file titleblocktemplate.cpp.
References QET::attributeIsAnInteger(), cells_, columns_width_, TitleBlockCell::EmptyCell, and rows_heights_.
Referenced by loadCell().
checkCellSpan()
bool TitleBlockTemplate::checkCellSpan (TitleBlockCell * cell)
TitleBlockTemplate::checkCellSpan Check whether a given cell can be spanned according to its row_span and col_span attributes. the following attributes of cell are updated according to what is really possible: applied_col_span applied_row_span span_state.
Parameters
cell : Cell we want to check
Returns
false if no check could be performed, true otherwise
Definition at line 1927 of file titleblocktemplate.cpp.
References cell(), cells_, columnsCount(), TitleBlockCell::Disabled, TitleBlockCell::EmptyCell, TitleBlockCell::Enabled, TitleBlockCell::Restricted, and rowsCount().
Referenced by applyCellSpans().
clone()
TitleBlockTemplate * TitleBlockTemplate::clone () const
TitleBlockTemplate::clone.
Returns
a deep copy of the current title block template (i.e. title block cells are duplicated too and associated with their parent template).
Definition at line 190 of file titleblocktemplate.cpp.
References bitmap_logos_, cells_, columns_width_, createCell(), data_logos_, information_, name_, rows_heights_, storage_logos_, TitleBlockTemplate(), type_logos_, and vector_logos_.
columnDimension()
TitleBlockDimension TitleBlockTemplate::columnDimension (int i)
TitleBlockTemplate::columnDimension.
Parameters
i : column index
Returns
the width of the column at index i
Definition at line 779 of file titleblocktemplate.cpp.
References columns_width_.
columnsCount()
int TitleBlockTemplate::columnsCount () const
TitleBlockTemplate::columnsCount.
Returns
the number of columns in this template
Definition at line 806 of file titleblocktemplate.cpp.
References columns_width_.
Referenced by checkCellSpan().
columnsWidth()
QList< int > TitleBlockTemplate::columnsWidth (int total_width) const
TitleBlockTemplate::columnsWidth.
Parameters
total_width : The total width of the titleblock to render
Returns
the list of the columns widths for this rendering
Definition at line 823 of file titleblocktemplate.cpp.
References QET::Absolute, columns_width_, QET::RelativeToRemainingLength, QET::RelativeToTotalLength, TitleBlockDimension::type, and TitleBlockDimension::value.
Referenced by render(), renderDxf(), and width().
columnTypeCount()
int TitleBlockTemplate::columnTypeCount (QET::TitleBlockColumnLength type)
TitleBlockTemplate::columnTypeCount.
Parameters
type : a column type
Returns
the count of type columns
Definition at line 902 of file titleblocktemplate.cpp.
References columns_width_.
Referenced by maximumWidth().
columnTypeTotal()
int TitleBlockTemplate::columnTypeTotal (QET::TitleBlockColumnLength type)
TitleBlockTemplate::columnTypeTotal.
Parameters
type : a column type
Returns
the sum of values attached to type columns
Definition at line 917 of file titleblocktemplate.cpp.
References columns_width_.
Referenced by maximumWidth(), and minimumWidth().
createCell()
TitleBlockCell * TitleBlockTemplate::createCell (const TitleBlockCell * existing_cell = nullptr)
TitleBlockTemplate::createCell Create a new cell and associate it with this template, which means that it will be deleted when this template is destroyed.
Parameters
existing_cell (optional) An existing cell that will be copied
Returns
A pointer to the newly created cell
Definition at line 52 of file titleblocktemplate.cpp.
References registered_cells_.
Referenced by clone(), and createCellsList().
createCellsList()
QList< TitleBlockCell * > TitleBlockTemplate::createCellsList (int count) protected
TitleBlockTemplate::createCellsList.
Parameters
count : Number of cells expected in the list
Returns
a list containing count newly created (and registered) cells
See also
createCell()
Definition at line 68 of file titleblocktemplate.cpp.
References createCell().
Referenced by createColumn(), and createRow().
createColumn()
QList< TitleBlockCell * > TitleBlockTemplate::createColumn ()
TitleBlockTemplate::createColumn.
Returns
a new column that fits the current grid
Definition at line 1133 of file titleblocktemplate.cpp.
References createCellsList(), and rows_heights_.
Referenced by addColumn(), and initCells().
createRow()
QList< TitleBlockCell * > TitleBlockTemplate::createRow ()
TitleBlockTemplate::createRow.
Returns
a new row that fits the current grid
Definition at line 1064 of file titleblocktemplate.cpp.
References columns_width_, and createCellsList().
Referenced by addRow().
exportCellToXml()
void TitleBlockTemplate::exportCellToXml (TitleBlockCell * cell, QDomElement & xml_element) const
TitleBlockTemplate::exportCellToXml.
Parameters
cell : Cell to export
xml_element : Parent XML element to be used when exporting cell
Definition at line 179 of file titleblocktemplate.cpp.
References cell(), and saveCell().
finalTextForCell()
QString TitleBlockTemplate::finalTextForCell (const TitleBlockCell & cell, const DiagramContext & diagram_context) const private
TitleBlockTemplate::finalTextForCell.
Parameters
cell : A cell from this template
diagram_context : Diagram context to use to generate the final text for the given cell
Returns
the final text that has to be drawn in the given cell
Definition at line 1660 of file titleblocktemplate.cpp.
References cell(), TitleBlockCell::display_label, interpreteVariables(), NamesList::isEmpty(), TitleBlockCell::label, NamesList::name(), QET::Icons::tr, and TitleBlockCell::value.
Referenced by renderCell(), and renderDxf().
flushCells()
void TitleBlockTemplate::flushCells () private
fontForCell()
QFont TitleBlockTemplate::fontForCell (const TitleBlockCell & cell) static
TitleBlockTemplate::fontForCell.
Parameters
cell : An existing cell
Returns
The font that should be used to render this cell according to its properties.
Definition at line 80 of file titleblocktemplate.cpp.
References cell(), QETApp::diagramTextsFont(), and TitleBlockCell::font_size.
Referenced by TitleBlockCell::attribute(), TitleBlockTemplateCellWidget::edit(), renderTextCell(), and renderTextCellDxf().
forgetSpanning() [1/2]
void TitleBlockTemplate::forgetSpanning ()
TitleBlockTemplate::forgetSpanning Set the spanner_cell attribute of every cell to 0.
Definition at line 1868 of file titleblocktemplate.cpp.
References cells_, columns_width_, and rows_heights_.
Referenced by applyCellSpans().
forgetSpanning() [2/2]
void TitleBlockTemplate::forgetSpanning (TitleBlockCell * spanning_cell, bool modify_cell = true)
TitleBlockTemplate::forgetSpanning Set the spanner_cell attribute of every cell spanned by spanning_cell to 0.
Parameters
spanning_cell :
modify_cell : (Optional, defaults to true) Whether to set row_span and col_span of spanning_cell to 0.
Definition at line 1885 of file titleblocktemplate.cpp.
References TitleBlockCell::Enabled, and spannedCells().
getAllSpans()
QHash< TitleBlockCell *, QPair< int, int > > TitleBlockTemplate::getAllSpans () const
TitleBlockTemplate::getAllSpans Export the span parameters of all cell in the current grid.
Returns
Definition at line 1199 of file titleblocktemplate.cpp.
References cells_, columns_width_, and rows_heights_.
height()
int TitleBlockTemplate::height () const
TitleBlockTemplate::height.
Returns
the total height of this template
Definition at line 983 of file titleblocktemplate.cpp.
References rows_heights_.
Referenced by render().
information()
QString TitleBlockTemplate::information () const
TitleBlockTemplate::information.
Returns
the information field attached to this template
Definition at line 735 of file titleblocktemplate.cpp.
References information_.
Referenced by saveInformation().
initCells()
void TitleBlockTemplate::initCells () private
TitleBlockTemplate::initCells Initialize the internal cells grid with the row and column counts. Note that this method does nothing if one of the internal lists columns_width_ and rows_heights_ is empty.
Definition at line 709 of file titleblocktemplate.cpp.
References cells_, columns_width_, createColumn(), registered_cells_, and rows_heights_.
Referenced by loadGrid().
insertColumn()
bool TitleBlockTemplate::insertColumn (const TitleBlockDimension & dimension, const QList< TitleBlockCell * > & column, int i = -1)
TitleBlockTemplate::insertColumn.
Parameters
dimension : Size of the column to be added
column : Column to be added
i : Index of the column after insertion, -1 meaning "last position"
Returns
true
Definition at line 1102 of file titleblocktemplate.cpp.
References cells_, columns_width_, and rowColsChanged().
Referenced by addColumn().
insertRow()
bool TitleBlockTemplate::insertRow (int dimension, const QList< TitleBlockCell * > & row, int i = -1)
TitleBlockTemplate::insertRow.
Parameters
dimension : dimension Size of the row to be added (always absolute, in pixels)
row : column Row to be added
i : Index of the column after insertion, -1 meaning "last position"
Returns
true
Definition at line 1029 of file titleblocktemplate.cpp.
References cells_, columns_width_, rowColsChanged(), and rows_heights_.
Referenced by addRow().
interpreteVariables()
QString TitleBlockTemplate::interpreteVariables (const QString & string, const DiagramContext & diagram_context) const private
TitleBlockTemplate::interpreteVariables.
Parameters
string : A text containing 0 to n variables, e.g. "%var" or "%{var}"
diagram_context : Diagram context to use to interprete variables
Returns
the provided string with variables replaced by the values from the diagram context
Definition at line 1686 of file titleblocktemplate.cpp.
References DiagramContext::DecreasingLength, and DiagramContext::keys().
Referenced by finalTextForCell().
lengthRange()
int TitleBlockTemplate::lengthRange (int start, int end, const QList< int > & lengths_list) const private
TitleBlockTemplate::lengthRange.
Parameters
start : start border number
end : end border number
lengths_list :
Returns
the width between two borders
Definition at line 2044 of file titleblocktemplate.cpp.
Referenced by render(), and renderDxf().
listOfVariables()
QStringList TitleBlockTemplate::listOfVariables ()
TitleBlockTemplate::listOfVariables Get list of variables.
Returns
The list of string with variables
Definition at line 1705 of file titleblocktemplate.cpp.
References cells_, columns_width_, TitleBlockCell::EmptyCell, and rows_heights_.
loadCell()
void TitleBlockTemplate::loadCell (const QDomElement & cell_element) protected
TitleBlockTemplate::loadCell Load a cell into this template.
Parameters
cell_element : XML element describing a cell within a title block template
Definition at line 491 of file titleblocktemplate.cpp.
References checkCell().
Referenced by loadCells().
loadCells()
bool TitleBlockTemplate::loadCells (const QDomElement & xml_element) protected
TitleBlockTemplate::loadCells Analyze an XML element, looking for grid cells. The grid cells are checked and stored in this object.
Parameters
xml_element XML element to analyze
Returns
systematically true
Definition at line 469 of file titleblocktemplate.cpp.
References loadCell().
Referenced by loadGrid().
loadFromXmlElement()
bool TitleBlockTemplate::loadFromXmlElement (const QDomElement & xml_element)
TitleBlockTemplate::loadFromXmlElement.
Parameters
xml_element : An XML document to read the template from.
Returns
true if the reading succeeds, false otherwise.
Definition at line 117 of file titleblocktemplate.cpp.
References loadGrid(), loadInformation(), loadLogos(), and name_.
Referenced by loadFromXmlFile().
loadFromXmlFile()
bool TitleBlockTemplate::loadFromXmlFile (const QString & filepath)
TitleBlockTemplate::loadFromXmlFile Load a titleblock template from an XML file.
Parameters
filepath : A file path to read the template from.
Returns
true if the reading succeeds, false otherwise.
Definition at line 90 of file titleblocktemplate.cpp.
References loadFromXmlElement().
loadGrid()
bool TitleBlockTemplate::loadGrid (const QDomElement & xml_element) protected
Import the grid from a given XML titleblock template.
Parameters
xml_element An XML element representing an titleblock template.
Returns
true if the reading succeeds, false otherwise.
Definition at line 350 of file titleblocktemplate.cpp.
References applyCellSpans(), applyRowColNums(), initCells(), loadCells(), parseColumns(), and parseRows().
Referenced by loadFromXmlElement().
loadInformation()
void TitleBlockTemplate::loadInformation (const QDomElement & xml_element) protected
TitleBlockTemplate::loadInformation Import text informations from a given XML title block template.
Parameters
xml_element
Definition at line 255 of file titleblocktemplate.cpp.
References setInformation().
Referenced by loadFromXmlElement().
loadLogo()
bool TitleBlockTemplate::loadLogo (const QDomElement & xml_element) protected
TitleBlockTemplate::loadLogo Import the logo from a given XML logo description.
Parameters
xml_element : An XML element representing a logo within an titleblock template.
Returns
true if the reading succeeds, false otherwise.
Definition at line 312 of file titleblocktemplate.cpp.
References addLogo().
Referenced by loadLogos().
loadLogos()
bool TitleBlockTemplate::loadLogos (const QDomElement & xml_element, bool reset = false) protected
TitleBlockTemplate::loadLogos Import the logos from a given XML titleblock template.
Parameters
xml_element : An XML element representing an titleblock template.
reset : true to delete all previously known logos before, false otherwise.
Returns
true if the reading succeeds, false otherwise.
Definition at line 273 of file titleblocktemplate.cpp.
References bitmap_logos_, data_logos_, loadLogo(), storage_logos_, and vector_logos_.
Referenced by loadFromXmlElement(), and ~TitleBlockTemplate().
logos()
QList< QString > TitleBlockTemplate::logos () const
TitleBlockTemplate::logos.
Returns
The names of logos embedded within this title block template.
Definition at line 1405 of file titleblocktemplate.cpp.
References data_logos_.
logoType()
QString TitleBlockTemplate::logoType (const QString & logo_name) const
TitleBlockTemplate::logoType.
Parameters
logo_name : Name of a logo embedded within this title block template.
Returns
the kind of storage used for the required logo, or a null QString if no such logo was found in this template.
Definition at line 1416 of file titleblocktemplate.cpp.
References type_logos_.
maximumWidth()
int TitleBlockTemplate::maximumWidth ()
TitleBlockTemplate::maximumWidth.
Returns
the maximum width for this template, or -1 if it does not have any.
Definition at line 957 of file titleblocktemplate.cpp.
References QET::Absolute, columns_width_, columnTypeCount(), and columnTypeTotal().
minimumWidth()
int TitleBlockTemplate::minimumWidth ()
Returns
the minimum width for this template
Definition at line 932 of file titleblocktemplate.cpp.
References QET::Absolute, columnTypeTotal(), and QET::RelativeToTotalLength.
moveColumn()
bool TitleBlockTemplate::moveColumn (int from, int to)
TitleBlockTemplate::moveColumn Move the column at index "from" to index "to".
Parameters
from : Source index of the moved column
to : Target index of the moved column
Returns
true or false
Definition at line 1075 of file titleblocktemplate.cpp.
References cells_, columns_width_, and rowColsChanged().
moveRow()
bool TitleBlockTemplate::moveRow (int from, int to)
TitleBlockTemplate::moveRow Move a row within this template.
Parameters
from : Index of the moved row
to : Arrival index of the moved row
Returns
true on row Changed or false
Definition at line 998 of file titleblocktemplate.cpp.
References cells_, columns_width_, rowColsChanged(), and rows_heights_.
name()
QString TitleBlockTemplate::name () const
TitleBlockTemplate::name.
Returns
the name of this template
Definition at line 727 of file titleblocktemplate.cpp.
References name_.
Referenced by addLogoFromFile().
parseColumns()
void TitleBlockTemplate::parseColumns (const QString & cols_string) private
TitleBlockTemplate::parseColumns Parse the columns widths.
Parameters
cols_string : A string describing the columns widths of the titleblock
Definition at line 416 of file titleblocktemplate.cpp.
References QET::Absolute, columns_width_, QET::RelativeToRemainingLength, and QET::RelativeToTotalLength.
Referenced by loadGrid().
parseRows()
void TitleBlockTemplate::parseRows (const QString & rows_string) private
TitleBlockTemplate::parseRows Parse the rows heights.
Parameters
rows_string : A string describing the rows heights of the titleblock
Definition at line 382 of file titleblocktemplate.cpp.
References rows_heights_.
Referenced by loadGrid().
removeLogo()
bool TitleBlockTemplate::removeLogo (const QString & logo_name)
TitleBlockTemplate::removeLogo.
Parameters
logo_name : Name of the logo to remove
Returns
true if the logo could be deleted, false otherwise
TODO check existing cells using this logo.
Definition at line 1343 of file titleblocktemplate.cpp.
References bitmap_logos_, data_logos_, storage_logos_, and vector_logos_.
Referenced by addLogo().
renameLogo()
bool TitleBlockTemplate::renameLogo (const QString & logo_name, const QString & new_name)
TitleBlockTemplate::renameLogo Rename the logo_name logo to new_name.
Parameters
logo_name : Name of the logo to be renamed
new_name : New name of the renamed logo
Returns
TODO check existing cells using this logo.
Definition at line 1367 of file titleblocktemplate.cpp.
References bitmap_logos_, data_logos_, storage_logos_, and vector_logos_.
render()
void TitleBlockTemplate::render (QPainter & painter, const DiagramContext & diagram_context, int titleblock_width) const
TitleBlockTemplate::render Render the titleblock.
Parameters
painter : Painter to use to render the titleblock
diagram_context : Diagram context to use to generate the titleblock strings
titleblock_width : Width of the titleblock to render
Definition at line 1461 of file titleblocktemplate.cpp.
References cells_, columns_width_, columnsWidth(), TitleBlockCell::Disabled, TitleBlockCell::EmptyCell, height(), lengthRange(), renderCell(), and rows_heights_.
Referenced by renderCell().
renderCell()
void TitleBlockTemplate::renderCell (QPainter & painter, const TitleBlockCell & cell, const DiagramContext & diagram_context, const QRect & cell_rect) const
TitleBlockTemplate::renderCell Render a titleblock cell.
Parameters
painter : Painter to use to render the titleblock
cell :
diagram_context : Diagram context to use to generate the titleblock strings
cell_rect : Rectangle the cell must be rendered into.
Definition at line 1609 of file titleblocktemplate.cpp.
References bitmap_logos_, cell(), finalTextForCell(), TitleBlockCell::logo_reference, TitleBlockCell::LogoCell, render(), renderTextCell(), TitleBlockCell::TextCell, TitleBlockCell::type(), and vector_logos_.
Referenced by render().
renderDxf()
void TitleBlockTemplate::renderDxf (QRectF & title_block_rect, const DiagramContext & diagram_context, int titleblock_width, QString & file_path, int color) const
TitleBlockTemplate::renderDxf Render the titleblock in DXF.
Parameters
title_block_rect :
diagram_context : Diagram context to use to generate the titleblock strings
titleblock_width : Width of the titleblock to render
file_path :
color :
Definition at line 1523 of file titleblocktemplate.cpp.
References cells_, columns_width_, columnsWidth(), TitleBlockCell::Disabled, Createdxf::drawRectangle(), TitleBlockCell::EmptyCell, finalTextForCell(), lengthRange(), renderTextCellDxf(), rows_heights_, Createdxf::sheetHeight, TitleBlockCell::TextCell, Createdxf::xScale, and Createdxf::yScale.
renderTextCell()
void TitleBlockTemplate::renderTextCell (QPainter & painter, const QString & text, const TitleBlockCell & cell, const QRectF & cell_rect) const private
TitleBlockTemplate::renderTextCell This method uses a painter to render the text of a cell into the cell_rect rectangle. The alignment, font_size and other cell parameters are taken into account when rendering.
Parameters
painter : QPainter used to render the text
text : Text to render
cell : Cell the rendered text is rattached to
cell_rect : Rectangle delimiting the cell area
Definition at line 1738 of file titleblocktemplate.cpp.
References TitleBlockCell::alignment, cell(), fontForCell(), and TitleBlockCell::hadjust.
Referenced by renderCell().
renderTextCellDxf()
void TitleBlockTemplate::renderTextCellDxf (QString & file_path, const QString & text, const TitleBlockCell & cell, qreal x, qreal y, qreal w, qreal h, int color) const private
TitleBlockTemplate::renderTextCellDxf.
Parameters
file_path
text
cell
x
y
w
h
color
Definition at line 1792 of file titleblocktemplate.cpp.
References TitleBlockCell::alignment, cell(), Createdxf::drawTextAligned(), fontForCell(), TitleBlockCell::hadjust, Createdxf::xScale, and Createdxf::yScale.
Referenced by renderDxf().
rowColsChanged()
void TitleBlockTemplate::rowColsChanged ()
TitleBlockTemplate::rowColsChanged Take care of consistency and span-related problematics when adding/moving/deleting rows and columns.
Definition at line 2030 of file titleblocktemplate.cpp.
References applyCellSpans(), and applyRowColNums().
Referenced by insertColumn(), insertRow(), moveColumn(), moveRow(), takeColumn(), and takeRow().
rowDimension()
int TitleBlockTemplate::rowDimension (int i)
TitleBlockTemplate::rowDimension.
Parameters
i : row index
Returns
the height of the row at index i
Definition at line 752 of file titleblocktemplate.cpp.
References rows_heights_.
rowsCount()
int TitleBlockTemplate::rowsCount () const
TitleBlockTemplate::rowsCount.
Returns
the number of rows in this template
Definition at line 814 of file titleblocktemplate.cpp.
References rows_heights_.
Referenced by checkCellSpan().
rowsHeights()
QList< int > TitleBlockTemplate::rowsHeights () const
TitleBlockTemplate::rowsHeights.
Returns
the heights of all the rows in this template
Definition at line 893 of file titleblocktemplate.cpp.
References rows_heights_.
saveCell()
void TitleBlockTemplate::saveCell (TitleBlockCell * cell, QDomElement & xml_element, bool save_empty = false) const protected
TitleBlockTemplate::saveCell Export a specific cell as XML.
Parameters
cell : Cell to be exported as XML
xml_element : XML element under which the <cell> element will be attached
save_empty : If true, the cell will be saved even if it is an empty one
Definition at line 611 of file titleblocktemplate.cpp.
References cell(), and TitleBlockCell::EmptyCell.
Referenced by exportCellToXml(), and saveCells().
saveCells()
void TitleBlockTemplate::saveCells (QDomElement & xml_element) const protected
TitleBlockTemplate::saveCells Export this template's cells as XML (without the grid-related information, usch as rows and cols)
Parameters
xml_element : XML element under which the <cell> elements will be attached
Definition at line 591 of file titleblocktemplate.cpp.
References cells_, columns_width_, TitleBlockCell::EmptyCell, rows_heights_, and saveCell().
Referenced by saveGrid().
saveGrid()
void TitleBlockTemplate::saveGrid (QDomElement & xml_element) const protected
TitleBlockTemplate::saveGrid Export this template's cells grid as XML.
Parameters
xml_element : XML element under which the <grid> element will be attached
Definition at line 567 of file titleblocktemplate.cpp.
References columns_width_, rows_heights_, saveCells(), and TitleBlockDimension::toShortString().
Referenced by saveToXmlElement().
saveInformation()
void TitleBlockTemplate::saveInformation (QDomElement & xml_element) const protected
TitleBlockTemplate::saveInformation Export this template's extra information.
Parameters
xml_element : XML element under which extra informations will be attached
Definition at line 503 of file titleblocktemplate.cpp.
References information().
Referenced by saveToXmlElement().
saveLogo()
void TitleBlockTemplate::saveLogo (const QString & logo_name, QDomElement & xml_element) const protected
TitleBlockTemplate::saveLogo Export a specific logo as XML.
Parameters
logo_name : Name of the logo to be exported
xml_element : XML element in which the logo will be exported
Definition at line 537 of file titleblocktemplate.cpp.
References data_logos_, storage_logos_, and type_logos_.
Referenced by saveLogos().
saveLogos()
void TitleBlockTemplate::saveLogos (QDomElement & xml_element) const protected
TitleBlockTemplate::saveLogos Export this template's logos as XML.
Parameters
xml_element : XML Element under which the <logos> element will be attached
Definition at line 519 of file titleblocktemplate.cpp.
References saveLogo(), and type_logos_.
Referenced by saveToXmlElement().
saveLogoToFile()
bool TitleBlockTemplate::saveLogoToFile (const QString & logo_name, const QString & filepath)
TitleBlockTemplate::saveLogoToFile.
Parameters
logo_name : Name used to store the logo
filepath : Path the logo will be saved as
Returns
true if the logo could be exported, false otherwise
Definition at line 1322 of file titleblocktemplate.cpp.
References data_logos_.
saveToXmlElement()
bool TitleBlockTemplate::saveToXmlElement (QDomElement & xml_element) const
TitleBlockTemplate::saveToXmlElement Save the title block template as XML.
Parameters
xml_element : The XML element this title block template should be saved to.
Returns
true if the export succeeds, false otherwise
Definition at line 161 of file titleblocktemplate.cpp.
References name_, saveGrid(), saveInformation(), and saveLogos().
Referenced by saveToXmlFile().
saveToXmlFile()
bool TitleBlockTemplate::saveToXmlFile (const QString & filepath)
TitleBlockTemplate::saveToXmlFile Save the title block template into an XML file.
Parameters
filepath : The file path this title block template should be saved to.
Returns
true if the operation succeeds, false otherwise
Definition at line 141 of file titleblocktemplate.cpp.
References saveToXmlElement(), and QET::writeXmlFile().
setAllSpans()
void TitleBlockTemplate::setAllSpans (const QHash< TitleBlockCell *, QPair< int, int > > & spans)
TitleBlockTemplate::setAllSpans Restore a set of span parameters.
Parameters
spans :
Definition at line 1221 of file titleblocktemplate.cpp.
References cell().
setColumnDimension()
void TitleBlockTemplate::setColumnDimension (int i, const TitleBlockDimension & dimension)
TitleBlockTemplate::setColumnDimension Set the width of a column.
Parameters
i : column index
dimension : New width of the column at index i
Definition at line 793 of file titleblocktemplate.cpp.
References columns_width_.
setInformation()
void TitleBlockTemplate::setInformation (const QString & info)
TitleBlockTemplate::setInformation.
Parameters
info information to be attached to this template
Definition at line 743 of file titleblocktemplate.cpp.
References information_.
Referenced by loadInformation().
setLogoStorage()
void TitleBlockTemplate::setLogoStorage (const QString & logo_name, const QString & storage)
TitleBlockTemplate::setLogoStorage Set the kind of storage for the logo_name logo.
Parameters
logo_name : Name of the logo which kind of storage is to be changed
storage : The kind of storage to use for the logo, e.g. "xml" or "base64".
Definition at line 1394 of file titleblocktemplate.cpp.
References storage_logos_.
setRowDimension()
void TitleBlockTemplate::setRowDimension (int i, const TitleBlockDimension & dimension)
TitleBlockTemplate::setRowDimension Set the height of a row.
Parameters
i : row index
dimension : New height of the row at index i
Definition at line 766 of file titleblocktemplate.cpp.
References rows_heights_, and TitleBlockDimension::value.
spannedCells()
QSet< TitleBlockCell * > TitleBlockTemplate::spannedCells (const TitleBlockCell * given_cell, bool ignore_span_state = false) const
TitleBlockTemplate::spannedCells.
Parameters
given_cell : cell A cell belonging to this title block template
ignore_span_state : (Optional, defaults to false) If true, will consider cells theoretically spanned (i.e. row_span and col_span attributes). Otherwise, will take span_state attribute into account.
Returns
the set of cells spanned by the provided cell Note the returned set does not include the spanning, provided cell
Definition at line 1161 of file titleblocktemplate.cpp.
References cell(), and TitleBlockCell::Disabled.
Referenced by forgetSpanning().
takeColumn()
QList< TitleBlockCell * > TitleBlockTemplate::takeColumn (int i)
TitleBlockTemplate::takeColumn Removes the column at index i.
Parameters
i : Index of the column to be removed
Returns
the removed column
Definition at line 1118 of file titleblocktemplate.cpp.
References cells_, columns_width_, and rowColsChanged().
takeRow()
QList< TitleBlockCell * > TitleBlockTemplate::takeRow (int i)
TitleBlockTemplate::takeRow Removes the row at index i.
Parameters
i : Index of the column to be removed
Returns
the removed column
Definition at line 1048 of file titleblocktemplate.cpp.
References cells_, columns_width_, rowColsChanged(), and rows_heights_.
vectorLogo()
QSvgRenderer * TitleBlockTemplate::vectorLogo (const QString & logo_name) const
TitleBlockTemplate::vectorLogo.
Parameters
logo_name : Name of a vector logo embedded within this title block template.
Returns
the rendering object for the required vector logo, or 0 if no such vector logo was found in this template.
Definition at line 1430 of file titleblocktemplate.cpp.
References vector_logos_.
width()
int TitleBlockTemplate::width (int total_width)
TitleBlockTemplate::width.
Parameters
total_width : The total width initially planned for the rendering
Returns
the total effective width of this template
Definition at line 971 of file titleblocktemplate.cpp.
References columnsWidth().
Member Data Documentation
bitmap_logos_
QHash<QString, QPixmap> TitleBlockTemplate::bitmap_logos_ private
bitmap_logos_ : Pixmaps for bitmap logos
Definition at line 193 of file titleblocktemplate.h.
Referenced by addLogo(), bitmapLogo(), clone(), loadLogos(), removeLogo(), renameLogo(), and renderCell().
cells_
QList< QList<TitleBlockCell *> > TitleBlockTemplate::cells_ private
Cells grid.
Definition at line 206 of file titleblocktemplate.h.
Referenced by applyCellSpan(), applyCellSpans(), applyRowColNums(), cell(), checkCell(), checkCellSpan(), clone(), forgetSpanning(), getAllSpans(), initCells(), insertColumn(), insertRow(), listOfVariables(), moveColumn(), moveRow(), render(), renderDxf(), saveCells(), takeColumn(), and takeRow().
columns_width_
QList<TitleBlockDimension> TitleBlockTemplate::columns_width_ private
columns_width_ : columns widths –
See also
TitleBlockColDimension
Definition at line 200 of file titleblocktemplate.h.
Referenced by applyCellSpans(), applyRowColNums(), cell(), checkCell(), clone(), columnDimension(), columnsCount(), columnsWidth(), columnTypeCount(), columnTypeTotal(), createRow(), forgetSpanning(), getAllSpans(), initCells(), insertColumn(), insertRow(), listOfVariables(), maximumWidth(), moveColumn(), moveRow(), parseColumns(), render(), renderDxf(), saveCells(), saveGrid(), setColumnDimension(), takeColumn(), and takeRow().
data_logos_
QHash<QString, QByteArray > TitleBlockTemplate::data_logos_ private
data_logos_ : Logos raw data
Definition at line 175 of file titleblocktemplate.h.
Referenced by addLogo(), clone(), loadLogos(), logos(), removeLogo(), renameLogo(), saveLogo(), and saveLogoToFile().
information_
QString TitleBlockTemplate::information_ private
Definition at line 171 of file titleblocktemplate.h.
Referenced by clone(), information(), and setInformation().
name_
QString TitleBlockTemplate::name_ private
name_ : name identifying the Title Block Template within its parent collection
Definition at line 170 of file titleblocktemplate.h.
Referenced by clone(), loadFromXmlElement(), name(), and saveToXmlElement().
registered_cells_
QList<TitleBlockCell *> TitleBlockTemplate::registered_cells_ private
registered_cells_ : Cells objects created rattached to this template, but not mandatorily used
Definition at line 205 of file titleblocktemplate.h.
Referenced by createCell(), initCells(), and ~TitleBlockTemplate().
rows_heights_
QList<int> TitleBlockTemplate::rows_heights_ private
rows heights – simple integers
Definition at line 195 of file titleblocktemplate.h.
Referenced by applyCellSpans(), applyRowColNums(), cell(), checkCell(), clone(), createColumn(), forgetSpanning(), getAllSpans(), height(), initCells(), insertRow(), listOfVariables(), moveRow(), parseRows(), render(), renderDxf(), rowDimension(), rowsCount(), rowsHeights(), saveCells(), saveGrid(), setRowDimension(), and takeRow().
storage_logos_
QHash<QString, QString> TitleBlockTemplate::storage_logos_ private
storage_logos_ : Logos applied storage type (e.g. "xml" or "base64")
Definition at line 180 of file titleblocktemplate.h.
Referenced by addLogo(), clone(), loadLogos(), removeLogo(), renameLogo(), saveLogo(), and setLogoStorage().
type_logos_
QHash<QString, QString> TitleBlockTemplate::type_logos_ private
type_logos_ : Logos types (e.g. "png", "jpeg", "svg")
Definition at line 185 of file titleblocktemplate.h.
Referenced by addLogo(), clone(), logoType(), saveLogo(), and saveLogos().
vector_logos_
QHash<QString, QSvgRenderer *> TitleBlockTemplate::vector_logos_ private
vector_logos_ : Rendered objects for vector logos
Definition at line 189 of file titleblocktemplate.h.
Referenced by addLogo(), clone(), loadLogos(), removeLogo(), renameLogo(), renderCell(), and vectorLogo().
The documentation for this class was generated from the following files:
titleblocktemplate.h
titleblocktemplate.cpp