QElectroTech: TitleBlockPropertiesWidget Class Reference
TitleBlockPropertiesWidget Class Reference
#include <titleblockpropertieswidget.h>
Signals
void set_auto_page_num () const
void openAutoNumFolioEditor (QString)
Public Member Functions
TitleBlockPropertiesWidget (const TitleBlockProperties &titleblock=TitleBlockProperties(), bool current_date=false, QETProject *project=nullptr, QWidget *parent=nullptr)
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget default constructor.
TitleBlockPropertiesWidget (TitleBlockTemplatesCollection *tbt_collection, const TitleBlockProperties &titleblock=TitleBlockProperties(), bool current_date=false, QETProject *project=nullptr, QWidget *parent=nullptr)
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget default constructor with tempalte list.
TitleBlockPropertiesWidget (QList< TitleBlockTemplatesCollection * > tbt_collection, const TitleBlockProperties &titleblock=TitleBlockProperties(), bool current_date=false, QETProject *project=nullptr, QWidget *parent=nullptr)
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget Default constructor with several template collection.
~TitleBlockPropertiesWidget () override
TitleBlockPropertiesWidget::~TitleBlockPropertiesWidget destructor.
void setProperties (const TitleBlockProperties &properties)
TitleBlockPropertiesWidget::setProperties.
TitleBlockProperties properties () const
TitleBlockPropertiesWidget::properties.
TitleBlockProperties propertiesAutoNum (QString autoNum) const
TitleBlockPropertiesWidget::properties.
TitleBlockTemplateLocation currentTitleBlockLocation () const
void setPropertiesWithAutoNum (const TitleBlockProperties &properties, QString autoNum)
void setTitleBlockTemplatesVisible (const bool &visible)
TitleBlockPropertiesWidget::setTitleBlockTemplatesVisible if true, title block template combo box and menu button is visible.
void setReadOnly (const bool &ro)
TitleBlockPropertiesWidget::setReadOnly if true, this widget is disable.
Private Slots
void editCurrentTitleBlockTemplate ()
void duplicateCurrentTitleBlockTemplate ()
void updateTemplateList ()
TitleBlockPropertiesWidget::updateTemplateList Update the title block template list available in the combo box.
void changeCurrentTitleBlockTemplate (int)
TitleBlockPropertiesWidget::changeCurrentTitleBlockTemplate Load the additionnal field of title block "text".
void on_m_date_now_pb_clicked ()
TitleBlockPropertiesWidget::on_m_date_now_pb_clicked Set the date to current date.
void on_m_edit_autofolionum_pb_clicked ()
TitleBlockPropertiesWidget::on_m_edit_autofolionum_pb_clicked Open Auto Folio Num dialog.
Private Member Functions
void addCollection (TitleBlockTemplatesCollection *tbt_collection)
TitleBlockPropertiesWidget::addCollection add a collection of title block available in the combo box.
QString currentTitleBlockTemplateName () const
TitleBlockPropertiesWidget::currentTitleBlockTemplateName.
void initDialog (const bool &current_date, QETProject *project)
TitleBlockPropertiesWidget::initDialog Init this dialog.
int getIndexFor (const QString &tbt_name, const QET::QetCollection collection) const
TitleBlockPropertiesWidget::getIndexFor Find the index of the combo box for the title block tbt_name available on the collection collection.
Private Attributes
Ui::TitleBlockPropertiesWidget * ui
DiagramContextWidget * m_dcw
QAction * m_tbt_edit
QAction * m_tbt_duplicate
QMenu * m_tbt_menu
QList< TitleBlockTemplatesCollection * > m_tbt_collection_list
QList< QET::QetCollection > m_map_index_to_collection_type
QList< QString > keys_2
Detailed Description
Definition at line 37 of file titleblockpropertieswidget.h.
Constructor & Destructor Documentation
TitleBlockPropertiesWidget() [1/3]
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget (const TitleBlockProperties & titleblock = TitleBlockProperties(), bool current_date = false, QETProject * project = nullptr, QWidget * parent = nullptr) explicit
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget default constructor.
Parameters
titleblock properties to edit
current_date if true, display the radio button "current date"
project : QETProject
parent parent widget
Definition at line 35 of file titleblockpropertieswidget.cpp.
References initDialog(), setProperties(), and ui.
TitleBlockPropertiesWidget() [2/3]
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget (TitleBlockTemplatesCollection * tbt_collection, const TitleBlockProperties & titleblock = TitleBlockProperties(), bool current_date = false, QETProject * project = nullptr, QWidget * parent = nullptr) explicit
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget default constructor with tempalte list.
Parameters
tbt_collection template list
titleblock properties to edit
current_date if true, display the radio button "current date"
project : QETProject
parent parent widget
Definition at line 57 of file titleblockpropertieswidget.cpp.
References addCollection(), initDialog(), setProperties(), ui, and updateTemplateList().
TitleBlockPropertiesWidget() [3/3]
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget (QList< TitleBlockTemplatesCollection * > tbt_collection, const TitleBlockProperties & titleblock = TitleBlockProperties(), bool current_date = false, QETProject * project = nullptr, QWidget * parent = nullptr) explicit
TitleBlockPropertiesWidget::TitleBlockPropertiesWidget Default constructor with several template collection.
Parameters
tbt_collection template list
titleblock properties to edit
current_date if true, display the radio button "current date"
project : QETProject
parent parent widget
Definition at line 82 of file titleblockpropertieswidget.cpp.
References addCollection(), initDialog(), setProperties(), ui, and updateTemplateList().
~TitleBlockPropertiesWidget()
TitleBlockPropertiesWidget::~TitleBlockPropertiesWidget () override
TitleBlockPropertiesWidget::~TitleBlockPropertiesWidget destructor.
Definition at line 103 of file titleblockpropertieswidget.cpp.
References ui.
Member Function Documentation
addCollection()
void TitleBlockPropertiesWidget::addCollection (TitleBlockTemplatesCollection * tbt_collection) private
TitleBlockPropertiesWidget::addCollection add a collection of title block available in the combo box.
Parameters
tbt_collection
Definition at line 298 of file titleblockpropertieswidget.cpp.
References m_tbt_collection_list.
Referenced by TitleBlockPropertiesWidget().
changeCurrentTitleBlockTemplate
void TitleBlockPropertiesWidget::changeCurrentTitleBlockTemplate (int index) private slot
TitleBlockPropertiesWidget::changeCurrentTitleBlockTemplate Load the additionnal field of title block "text".
Definition at line 429 of file titleblockpropertieswidget.cpp.
References DiagramContext::addValue(), m_dcw, m_map_index_to_collection_type, m_tbt_collection_list, and ui.
Referenced by initDialog().
currentTitleBlockLocation()
TitleBlockTemplateLocation TitleBlockPropertiesWidget::currentTitleBlockLocation () const
Definition at line 249 of file titleblockpropertieswidget.cpp.
References currentTitleBlockTemplateName(), TitleBlockTemplatesCollection::location(), m_map_index_to_collection_type, m_tbt_collection_list, and ui.
Referenced by duplicateCurrentTitleBlockTemplate(), and editCurrentTitleBlockTemplate().
currentTitleBlockTemplateName()
QString TitleBlockPropertiesWidget::currentTitleBlockTemplateName () const private
TitleBlockPropertiesWidget::currentTitleBlockTemplateName.
Returns
the current title block name
Definition at line 286 of file titleblockpropertieswidget.cpp.
References ui.
Referenced by currentTitleBlockLocation(), properties(), and propertiesAutoNum().
duplicateCurrentTitleBlockTemplate
void TitleBlockPropertiesWidget::duplicateCurrentTitleBlockTemplate () private slot
Definition at line 381 of file titleblockpropertieswidget.cpp.
References currentTitleBlockLocation(), QETApp::instance(), and QETApp::openTitleBlockTemplate().
Referenced by initDialog().
editCurrentTitleBlockTemplate
void TitleBlockPropertiesWidget::editCurrentTitleBlockTemplate () private slot
Definition at line 377 of file titleblockpropertieswidget.cpp.
References currentTitleBlockLocation(), QETApp::instance(), and QETApp::openTitleBlockTemplate().
Referenced by initDialog().
getIndexFor()
int TitleBlockPropertiesWidget::getIndexFor (const QString & tbt_name, const QET::QetCollection collection) const private
TitleBlockPropertiesWidget::getIndexFor Find the index of the combo box for the title block tbt_name available on the collection collection.
Parameters
tbt_name : title block name
collection : title block collection
Returns
the index of the title block or -1 if no match
Definition at line 365 of file titleblockpropertieswidget.cpp.
References m_map_index_to_collection_type, and ui.
Referenced by setProperties().
initDialog()
void TitleBlockPropertiesWidget::initDialog (const bool & current_date, QETProject * project) private
TitleBlockPropertiesWidget::initDialog Init this dialog.
Parameters
current_date : true for display current date radio button
project
Definition at line 311 of file titleblockpropertieswidget.cpp.
References changeCurrentTitleBlockTemplate(), duplicateCurrentTitleBlockTemplate(), editCurrentTitleBlockTemplate(), keys_2, m_dcw, m_tbt_duplicate, m_tbt_edit, m_tbt_menu, setTitleBlockTemplatesVisible(), QET::Icons::tr, and ui.
Referenced by TitleBlockPropertiesWidget().
on_m_date_now_pb_clicked
void TitleBlockPropertiesWidget::on_m_date_now_pb_clicked () private slot
TitleBlockPropertiesWidget::on_m_date_now_pb_clicked Set the date to current date.
Definition at line 458 of file titleblockpropertieswidget.cpp.
References ui.
on_m_edit_autofolionum_pb_clicked
void TitleBlockPropertiesWidget::on_m_edit_autofolionum_pb_clicked () private slot
TitleBlockPropertiesWidget::on_m_edit_autofolionum_pb_clicked Open Auto Folio Num dialog.
Definition at line 466 of file titleblockpropertieswidget.cpp.
References openAutoNumFolioEditor(), QET::Icons::tr, and ui.
openAutoNumFolioEditor
void TitleBlockPropertiesWidget::openAutoNumFolioEditor (QString) signal
Referenced by on_m_edit_autofolionum_pb_clicked().
properties()
TitleBlockProperties TitleBlockPropertiesWidget::properties () const
TitleBlockPropertiesWidget::properties.
Returns
the edited properties
Definition at line 170 of file titleblockpropertieswidget.cpp.
References TitleBlockProperties::author, TitleBlockProperties::auto_page_num, TitleBlockProperties::collection, TitleBlockProperties::context, TitleBlockProperties::CurrentDate, currentTitleBlockTemplateName(), TitleBlockProperties::date, TitleBlockProperties::display_at, TitleBlockProperties::filename, TitleBlockProperties::folio, TitleBlockProperties::indexrev, TitleBlockProperties::locmach, m_dcw, m_map_index_to_collection_type, TitleBlockProperties::plant, TitleBlockProperties::template_name, TitleBlockProperties::title, ui, TitleBlockProperties::useDate, and TitleBlockProperties::UseDateValue.
Referenced by NewDiagramPage::saveCurrentTbp(), and setProperties().
propertiesAutoNum()
TitleBlockProperties TitleBlockPropertiesWidget::propertiesAutoNum (QString autoNum) const
TitleBlockPropertiesWidget::properties.
Returns
return properties to enable folio autonum
Definition at line 211 of file titleblockpropertieswidget.cpp.
References TitleBlockProperties::author, TitleBlockProperties::auto_page_num, TitleBlockProperties::collection, TitleBlockProperties::context, TitleBlockProperties::CurrentDate, currentTitleBlockTemplateName(), TitleBlockProperties::date, TitleBlockProperties::display_at, TitleBlockProperties::filename, TitleBlockProperties::folio, TitleBlockProperties::indexrev, TitleBlockProperties::locmach, m_dcw, m_map_index_to_collection_type, TitleBlockProperties::plant, TitleBlockProperties::template_name, TitleBlockProperties::title, ui, TitleBlockProperties::useDate, and TitleBlockProperties::UseDateValue.
Referenced by NewDiagramPage::setFolioAutonum().
set_auto_page_num
void TitleBlockPropertiesWidget::set_auto_page_num () const signal
setProperties()
void TitleBlockPropertiesWidget::setProperties (const TitleBlockProperties & properties)
TitleBlockPropertiesWidget::setProperties.
Parameters
properties
Definition at line 112 of file titleblockpropertieswidget.cpp.
References TitleBlockProperties::author, TitleBlockProperties::auto_page_num, TitleBlockProperties::collection, TitleBlockProperties::context, TitleBlockProperties::CurrentDate, TitleBlockProperties::date, TitleBlockProperties::display_at, TitleBlockProperties::filename, TitleBlockProperties::folio, getIndexFor(), TitleBlockProperties::indexrev, TitleBlockProperties::locmach, m_dcw, TitleBlockProperties::plant, properties(), TitleBlockProperties::template_name, TitleBlockProperties::title, ui, and TitleBlockProperties::useDate.
Referenced by NewDiagramPage::loadSavedTbp(), NewDiagramPage::setFolioAutonum(), and TitleBlockPropertiesWidget().
setPropertiesWithAutoNum()
void TitleBlockPropertiesWidget::setPropertiesWithAutoNum (const TitleBlockProperties & properties, QString autoNum)
setReadOnly()
void TitleBlockPropertiesWidget::setReadOnly (const bool & ro)
TitleBlockPropertiesWidget::setReadOnly if true, this widget is disable.
Definition at line 278 of file titleblockpropertieswidget.cpp.
References QET::Icons::ro, and ui.
setTitleBlockTemplatesVisible()
void TitleBlockPropertiesWidget::setTitleBlockTemplatesVisible (const bool & visible)
TitleBlockPropertiesWidget::setTitleBlockTemplatesVisible if true, title block template combo box and menu button is visible.
Definition at line 267 of file titleblockpropertieswidget.cpp.
References ui.
Referenced by initDialog(), and updateTemplateList().
updateTemplateList
void TitleBlockPropertiesWidget::updateTemplateList () private slot
TitleBlockPropertiesWidget::updateTemplateList Update the title block template list available in the combo box.
Definition at line 389 of file titleblockpropertieswidget.cpp.
References QET::Common, QET::Custom, QET::Embedded, QET::Icons::Home, m_map_index_to_collection_type, m_tbt_collection_list, QET::Icons::QETLogo, setTitleBlockTemplatesVisible(), QET::Icons::TitleBlock, QET::Icons::tr, and ui.
Referenced by TitleBlockPropertiesWidget().
Member Data Documentation
keys_2
QList<QString> TitleBlockPropertiesWidget::keys_2 private
Definition at line 99 of file titleblockpropertieswidget.h.
Referenced by initDialog().
m_dcw
DiagramContextWidget* TitleBlockPropertiesWidget::m_dcw private
Definition at line 94 of file titleblockpropertieswidget.h.
Referenced by changeCurrentTitleBlockTemplate(), initDialog(), properties(), propertiesAutoNum(), and setProperties().
m_map_index_to_collection_type
QList<QET::QetCollection> TitleBlockPropertiesWidget::m_map_index_to_collection_type private
Definition at line 98 of file titleblockpropertieswidget.h.
Referenced by changeCurrentTitleBlockTemplate(), currentTitleBlockLocation(), getIndexFor(), properties(), propertiesAutoNum(), and updateTemplateList().
m_tbt_collection_list
QList<TitleBlockTemplatesCollection *> TitleBlockPropertiesWidget::m_tbt_collection_list private
Definition at line 97 of file titleblockpropertieswidget.h.
Referenced by addCollection(), changeCurrentTitleBlockTemplate(), currentTitleBlockLocation(), and updateTemplateList().
m_tbt_duplicate
QAction * TitleBlockPropertiesWidget::m_tbt_duplicate private
Definition at line 95 of file titleblockpropertieswidget.h.
Referenced by initDialog().
m_tbt_edit
QAction* TitleBlockPropertiesWidget::m_tbt_edit private
Definition at line 95 of file titleblockpropertieswidget.h.
Referenced by initDialog().
m_tbt_menu
QMenu* TitleBlockPropertiesWidget::m_tbt_menu private
Definition at line 96 of file titleblockpropertieswidget.h.
Referenced by initDialog().
ui
Ui::TitleBlockPropertiesWidget* TitleBlockPropertiesWidget::ui private
Definition at line 93 of file titleblockpropertieswidget.h.
Referenced by changeCurrentTitleBlockTemplate(), currentTitleBlockLocation(), currentTitleBlockTemplateName(), getIndexFor(), initDialog(), on_m_date_now_pb_clicked(), on_m_edit_autofolionum_pb_clicked(), properties(), propertiesAutoNum(), setProperties(), setReadOnly(), setTitleBlockTemplatesVisible(), TitleBlockPropertiesWidget(), updateTemplateList(), and ~TitleBlockPropertiesWidget().
The documentation for this class was generated from the following files:
titleblockpropertieswidget.h
titleblockpropertieswidget.cpp