QElectroTech: FormulaAssistantDialog Class Reference
FormulaAssistantDialog Class Reference
#include <formulaassistantdialog.h>
Public Member Functions
FormulaAssistantDialog (QWidget *parent=nullptr)
~FormulaAssistantDialog () override
void setForbiddenVariables (const QStringList &list)
void setText (const QString &text)
void setFormula (const QString &text)
QString formula () const
Private Slots
void on_m_line_edit_textChanged (const QString &arg1)
Private Attributes
Ui::FormulaAssistantDialog * ui
QRegularExpression m_rx
QString m_formula
Detailed Description
Definition at line 28 of file formulaassistantdialog.h.
Constructor & Destructor Documentation
FormulaAssistantDialog()
FormulaAssistantDialog::FormulaAssistantDialog (QWidget * parent = nullptr)
Definition at line 23 of file formulaassistantdialog.cpp.
References ui.
~FormulaAssistantDialog()
FormulaAssistantDialog::~FormulaAssistantDialog () override
Definition at line 30 of file formulaassistantdialog.cpp.
References ui.
Member Function Documentation
formula()
QString FormulaAssistantDialog::formula () const
Definition at line 50 of file formulaassistantdialog.cpp.
References ui.
Referenced by PotentialSelectorDialog::on_buttonBox_accepted().
on_m_line_edit_textChanged
void FormulaAssistantDialog::on_m_line_edit_textChanged (const QString & arg1) private slot
Definition at line 55 of file formulaassistantdialog.cpp.
References m_rx, and ui.
setForbiddenVariables()
void FormulaAssistantDialog::setForbiddenVariables (const QStringList & list)
Definition at line 35 of file formulaassistantdialog.cpp.
References m_rx.
Referenced by PotentialSelectorDialog::on_buttonBox_accepted().
setFormula()
void FormulaAssistantDialog::setFormula (const QString & text)
Definition at line 45 of file formulaassistantdialog.cpp.
References ui.
Referenced by PotentialSelectorDialog::on_buttonBox_accepted().
setText()
void FormulaAssistantDialog::setText (const QString & text)
Definition at line 40 of file formulaassistantdialog.cpp.
References ui.
Referenced by PotentialSelectorDialog::on_buttonBox_accepted().
Member Data Documentation
m_formula
QString FormulaAssistantDialog::m_formula private
Definition at line 47 of file formulaassistantdialog.h.
m_rx
QRegularExpression FormulaAssistantDialog::m_rx private
Definition at line 46 of file formulaassistantdialog.h.
Referenced by on_m_line_edit_textChanged(), and setForbiddenVariables().
ui
Ui::FormulaAssistantDialog* FormulaAssistantDialog::ui private
Definition at line 45 of file formulaassistantdialog.h.
Referenced by formula(), FormulaAssistantDialog(), on_m_line_edit_textChanged(), setFormula(), setText(), and ~FormulaAssistantDialog().
The documentation for this class was generated from the following files:
formulaassistantdialog.h
formulaassistantdialog.cpp