QElectroTech: GeneralConfigurationPage Class Reference
GeneralConfigurationPage Class Reference
#include <generalconfigurationpage.h>
Public Member Functions
GeneralConfigurationPage (QWidget *parent=nullptr)
GeneralConfigurationPage::GeneralConfigurationPage.
~GeneralConfigurationPage () override
virtual void applyConf () override
GeneralConfigurationPage::applyConf Write all configuration in settings file.
virtual QString title () const override
GeneralConfigurationPage::title.
virtual QIcon icon () const override
GeneralConfigurationPage::icon.
Public Member Functions inherited from ConfigPage
ConfigPage (QWidget *parent)
~ConfigPage () override
Destructor.
Private Slots
void on_m_font_pb_clicked ()
GeneralConfigurationPage::on_m_font_pb_clicked Apply font to config.
void on_m_dyn_text_font_pb_clicked ()
GeneralConfigurationPage::m_dyn_text_font_pb_clicked Apply font to config.
void on_m_common_elmt_path_cb_currentIndexChanged (int index)
void on_m_custom_elmt_path_cb_currentIndexChanged (int index)
void on_m_custom_tbt_path_cb_currentIndexChanged (int index)
void on_m_indi_text_font_pb_clicked ()
Private Member Functions
void fillLang ()
GeneralConfigurationPage::fillLang fill all available lang.
Private Attributes
Ui::GeneralConfigurationPage * ui
Detailed Description
Definition at line 28 of file generalconfigurationpage.h.
Constructor & Destructor Documentation
GeneralConfigurationPage()
GeneralConfigurationPage::GeneralConfigurationPage (QWidget * parent = nullptr) explicit
GeneralConfigurationPage::GeneralConfigurationPage.
Parameters
parent
Definition at line 31 of file generalconfigurationpage.cpp.
References fillLang(), and ui.
~GeneralConfigurationPage()
GeneralConfigurationPage::~GeneralConfigurationPage () override
Definition at line 128 of file generalconfigurationpage.cpp.
References ui.
Member Function Documentation
applyConf()
void GeneralConfigurationPage::applyConf () override virtual
GeneralConfigurationPage::applyConf Write all configuration in settings file.
Implements ConfigPage.
Definition at line 137 of file generalconfigurationpage.cpp.
References QETApp::instance(), QETApp::resetUserElementsDir(), ui, and QETApp::useSystemPalette().
fillLang()
void GeneralConfigurationPage::fillLang () private
GeneralConfigurationPage::fillLang fill all available lang.
Definition at line 253 of file generalconfigurationpage.cpp.
References QET::Icons::ar, QET::Icons::be, QET::Icons::br, QET::Icons::catalonia, QET::Icons::cs, QET::Icons::da, QET::Icons::de, QET::Icons::en, QET::Icons::es, QET::Icons::fr, QET::Icons::gr, QET::Icons::hr, QET::Icons::hu, QET::Icons::it, QET::Icons::jp, QET::Icons::nl, QET::Icons::no, QET::Icons::pl, QET::Icons::pt, QET::Icons::ro, QET::Icons::ru, QET::Icons::sl, QET::Icons::tr, QET::Icons::translation, and ui.
Referenced by GeneralConfigurationPage().
icon()
QIcon GeneralConfigurationPage::icon () const override virtual
GeneralConfigurationPage::icon.
Returns
The icon of this page
Implements ConfigPage.
Definition at line 245 of file generalconfigurationpage.cpp.
References QET::Icons::Settings.
on_m_common_elmt_path_cb_currentIndexChanged
void GeneralConfigurationPage::on_m_common_elmt_path_cb_currentIndexChanged (int index) private slot
Definition at line 341 of file generalconfigurationpage.cpp.
References QET::Icons::tr, and ui.
on_m_custom_elmt_path_cb_currentIndexChanged
void GeneralConfigurationPage::on_m_custom_elmt_path_cb_currentIndexChanged (int index) private slot
Definition at line 355 of file generalconfigurationpage.cpp.
References QET::Icons::tr, and ui.
on_m_custom_tbt_path_cb_currentIndexChanged
void GeneralConfigurationPage::on_m_custom_tbt_path_cb_currentIndexChanged (int index) private slot
Definition at line 369 of file generalconfigurationpage.cpp.
References QET::Icons::tr, and ui.
on_m_dyn_text_font_pb_clicked
void GeneralConfigurationPage::on_m_dyn_text_font_pb_clicked () private slot
GeneralConfigurationPage::m_dyn_text_font_pb_clicked Apply font to config.
Definition at line 323 of file generalconfigurationpage.cpp.
References ui.
on_m_font_pb_clicked
void GeneralConfigurationPage::on_m_font_pb_clicked () private slot
GeneralConfigurationPage::on_m_font_pb_clicked Apply font to config.
Definition at line 301 of file generalconfigurationpage.cpp.
References ui.
on_m_indi_text_font_pb_clicked
void GeneralConfigurationPage::on_m_indi_text_font_pb_clicked () private slot
Definition at line 384 of file generalconfigurationpage.cpp.
References ui.
title()
QString GeneralConfigurationPage::title () const override virtual
GeneralConfigurationPage::title.
Returns
The title of this page
Implements ConfigPage.
Definition at line 237 of file generalconfigurationpage.cpp.
References QET::Icons::tr.
Member Data Documentation
ui
Ui::GeneralConfigurationPage* GeneralConfigurationPage::ui private
Definition at line 52 of file generalconfigurationpage.h.
Referenced by applyConf(), fillLang(), GeneralConfigurationPage(), on_m_common_elmt_path_cb_currentIndexChanged(), on_m_custom_elmt_path_cb_currentIndexChanged(), on_m_custom_tbt_path_cb_currentIndexChanged(), on_m_dyn_text_font_pb_clicked(), on_m_font_pb_clicked(), on_m_indi_text_font_pb_clicked(), and ~GeneralConfigurationPage().
The documentation for this class was generated from the following files:
generalconfigurationpage.h
generalconfigurationpage.cpp