QElectroTech: SearchAndReplaceWorker Class Reference
SearchAndReplaceWorker Class Reference
The SearchAndReplaceWorker class This class is the worker use to change properties when use the search and replace function of QET.
#include <searchandreplaceworker.h>
Public Member Functions
SearchAndReplaceWorker ()
void replaceDiagram (QList< Diagram * > diagram_list)
SearchAndReplaceWorker::replaceDiagram Replace all properties of each diagram in diagram_list, by the current titleblock propertie of this worker.
void replaceDiagram (Diagram *diagram)
void replaceElement (QList< Element * > list)
SearchAndReplaceWorker::replaceElement Replace all properties of each elements in list All element must belong to the same project, if not this function do nothing. All change are made through a undo command append to undo list of the project.
void replaceElement (Element *element)
void replaceIndiText (QList< IndependentTextItem * > list)
SearchAndReplaceWorker::replaceIndiText Replace all displayed text of independent text of list Each must belong to the same project, if not this function do nothing.
void replaceIndiText (IndependentTextItem *text)
void replaceConductor (QList< Conductor * > list)
SearchAndReplaceWorker::replaceConductor Replace all properties of each conductor in list All conductor must belong to the same project, if not this function do nothing. All change are made through a undo command append to undo list of the project.
void replaceConductor (Conductor *conductor)
void replaceAdvanced (QList< Diagram * > diagrams=QList< Diagram * >(), QList< Element * > elements=QList< Element * >(), QList< IndependentTextItem * > texts=QList< IndependentTextItem * >(), QList< Conductor * > conductors=QList< Conductor * >())
SearchAndReplaceWorker::replaceAdvanced Apply the change of text according to the current advancedStruct All items in the 4 list must belong to the same QETProject, if not this function do nothing.
Static Public Member Functions
static QString eraseText ()
static QDate eraseDate ()
static void setupLineEdit (QLineEdit *l, QCheckBox *cb, QString str)
SearchAndReplaceWorker::setupLineEdit With search and replace, when the variable to edit is a text, the editor is always the same no matter if it is for a folio, element or conductor. The editor is a QLineEdit to edit the text and checkbox to erase the text if checked. This function fill the editor, from the current string.
static ConductorProperties invalidConductorProperties ()
static ConductorProperties applyChange (const ConductorProperties &original, const ConductorProperties &change)
SearchAndReplaceWorker::applyChange.
static QString applyChange (const QString &original, const QString &change)
SearchAndReplaceWorker::applyChange.
Private Member Functions
TitleBlockProperties replaceAdvanced (Diagram *diagram)
SearchAndReplaceWorker::replaceAdvanced.
DiagramContext replaceAdvanced (Element *element)
SearchAndReplaceWorker::replaceAdvanced.
ConductorProperties replaceAdvanced (Conductor *conductor)
SearchAndReplaceWorker::replaceAdvanced.
Private Attributes
TitleBlockProperties m_titleblock_properties
DiagramContext m_element_context
QString m_indi_text
ConductorProperties m_conductor_properties
advancedReplaceStruct m_advanced_struct
Friends
class SearchAndReplaceWidget
Detailed Description
The SearchAndReplaceWorker class This class is the worker use to change properties when use the search and replace function of QET.
Definition at line 51 of file searchandreplaceworker.h.
Constructor & Destructor Documentation
SearchAndReplaceWorker()
SearchAndReplaceWorker::SearchAndReplaceWorker ()
Definition at line 29 of file searchandreplaceworker.cpp.
References invalidConductorProperties(), and m_conductor_properties.
Member Function Documentation
applyChange() [1/2]
ConductorProperties SearchAndReplaceWorker::applyChange (const ConductorProperties & original, const ConductorProperties & change) static
SearchAndReplaceWorker::applyChange.
Parameters
original : the original properties
change : the change properties, to be merged with original
Returns
a new conductor properties with the change applyed.
Definition at line 406 of file searchandreplaceworker.cpp.
References ConductorProperties::color, ConductorProperties::cond_size, ConductorProperties::horiz_rotate_text, ConductorProperties::m_bicolor, ConductorProperties::m_color_2, ConductorProperties::m_dash_size, ConductorProperties::m_formula, ConductorProperties::m_function, ConductorProperties::m_horizontal_alignment, ConductorProperties::m_show_text, ConductorProperties::m_tension_protocol, ConductorProperties::m_vertical_alignment, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, ConductorProperties::singleLineProperties, ConductorProperties::style, ConductorProperties::text, ConductorProperties::text_size, and ConductorProperties::verti_rotate_text.
Referenced by replaceConductor(), replaceDiagram(), and replaceElement().
applyChange() [2/2]
QString SearchAndReplaceWorker::applyChange (const QString & original, const QString & change) static
SearchAndReplaceWorker::applyChange.
Parameters
original : the original string
change : the changed string:
Returns
the string to be use in the properties
Definition at line 443 of file searchandreplaceworker.cpp.
References eraseText().
eraseDate()
static QDate SearchAndReplaceWorker::eraseDate () inline static
Definition at line 74 of file searchandreplaceworker.h.
Referenced by replaceDiagram(), ReplaceFolioWidget::setTitleBlockProperties(), and ReplaceFolioWidget::titleBlockProperties().
eraseText()
static QString SearchAndReplaceWorker::eraseText () inline static
Definition at line 72 of file searchandreplaceworker.h.
Referenced by applyChange(), ReplaceFolioWidget::on_m_author_cb_clicked(), ReplaceConductorDialog::on_m_erase_formula_cb_clicked(), ReplaceConductorDialog::on_m_erase_function_cb_clicked(), ReplaceConductorDialog::on_m_erase_m_wire_color_cb_clicked(), ReplaceConductorDialog::on_m_erase_m_wire_section_cb_clicked(), ReplaceConductorDialog::on_m_erase_tension_protocol_cb_clicked(), ReplaceConductorDialog::on_m_erase_text_cb_clicked(), ElementInfoPartWidget::on_m_erase_text_clicked(), ReplaceFolioWidget::on_m_file_cb_clicked(), ReplaceFolioWidget::on_m_folio_cb_clicked(), ReplaceFolioWidget::on_m_indice_cb_clicked(), ReplaceFolioWidget::on_m_loc_cb_clicked(), ReplaceFolioWidget::on_m_plant_cb_clicked(), ReplaceFolioWidget::on_m_title_cb_clicked(), and setupLineEdit().
invalidConductorProperties()
ConductorProperties SearchAndReplaceWorker::invalidConductorProperties () static
Definition at line 380 of file searchandreplaceworker.cpp.
References ConductorProperties::color, ConductorProperties::cond_size, ConductorProperties::horiz_rotate_text, ConductorProperties::m_color_2, ConductorProperties::m_dash_size, ConductorProperties::m_horizontal_alignment, ConductorProperties::m_vertical_alignment, ConductorProperties::style, ConductorProperties::text, ConductorProperties::text_size, and ConductorProperties::verti_rotate_text.
Referenced by SearchAndReplaceWidget::on_m_conductor_pb_clicked(), and SearchAndReplaceWorker().
replaceAdvanced() [1/4]
ConductorProperties SearchAndReplaceWorker::replaceAdvanced (Conductor * conductor) private
SearchAndReplaceWorker::replaceAdvanced.
Parameters
conductor
Returns
the conductor properties with the change applied, according to the state of m_advanced_struct
Definition at line 508 of file searchandreplaceworker.cpp.
References m_advanced_struct, ConductorProperties::m_formula, ConductorProperties::m_function, ConductorProperties::m_tension_protocol, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, Conductor::properties, advancedReplaceStruct::replace, advancedReplaceStruct::search, ConductorProperties::text, advancedReplaceStruct::what, and advancedReplaceStruct::who.
replaceAdvanced() [2/4]
TitleBlockProperties SearchAndReplaceWorker::replaceAdvanced (Diagram * diagram) private
SearchAndReplaceWorker::replaceAdvanced.
Parameters
diagram
Returns
the titleblock properties with the change applied, according to the state of m_advanced_struct
Definition at line 457 of file searchandreplaceworker.cpp.
References TitleBlockProperties::author, Diagram::border_and_titleblock, BorderTitleBlock::exportTitleBlock(), TitleBlockProperties::filename, TitleBlockProperties::folio, TitleBlockProperties::indexrev, TitleBlockProperties::locmach, m_advanced_struct, TitleBlockProperties::plant, advancedReplaceStruct::replace, advancedReplaceStruct::search, TitleBlockProperties::title, advancedReplaceStruct::what, and advancedReplaceStruct::who.
replaceAdvanced() [3/4]
DiagramContext SearchAndReplaceWorker::replaceAdvanced (Element * element) private
SearchAndReplaceWorker::replaceAdvanced.
Parameters
element
Returns
The diagram context with the change applied, according to the state of m_advanced_struct
Definition at line 483 of file searchandreplaceworker.cpp.
References DiagramContext::addValue(), DiagramContext::contains(), Element::elementInformations(), m_advanced_struct, advancedReplaceStruct::replace, advancedReplaceStruct::search, advancedReplaceStruct::what, and advancedReplaceStruct::who.
replaceAdvanced() [4/4]
void SearchAndReplaceWorker::replaceAdvanced (QList< Diagram * > diagrams = QList<Diagram *>(), QList< Element * > elements = QList<Element *>(), QList< IndependentTextItem * > texts = QList<IndependentTextItem *>(), QList< Conductor * > conductors = QList<Conductor *>())
SearchAndReplaceWorker::replaceAdvanced Apply the change of text according to the current advancedStruct All items in the 4 list must belong to the same QETProject, if not this function do nothing.
Parameters
diagrams :
elements :
texts :
conductors :
Definition at line 249 of file searchandreplaceworker.cpp.
References m_advanced_struct, advancedReplaceStruct::replace, advancedReplaceStruct::search, QET::Icons::tr, QETProject::undoStack(), and advancedReplaceStruct::who.
Referenced by SearchAndReplaceWidget::on_m_replace_all_pb_clicked(), and SearchAndReplaceWidget::on_m_replace_pb_clicked().
replaceConductor() [1/2]
void SearchAndReplaceWorker::replaceConductor (Conductor * conductor)
Definition at line 232 of file searchandreplaceworker.cpp.
References replaceConductor().
replaceConductor() [2/2]
void SearchAndReplaceWorker::replaceConductor (QList< Conductor * > list)
SearchAndReplaceWorker::replaceConductor Replace all properties of each conductor in list All conductor must belong to the same project, if not this function do nothing. All change are made through a undo command append to undo list of the project.
Parameters
list
Definition at line 197 of file searchandreplaceworker.cpp.
References applyChange(), m_conductor_properties, QET::Icons::tr, and QETProject::undoStack().
Referenced by SearchAndReplaceWidget::on_m_replace_all_pb_clicked(), SearchAndReplaceWidget::on_m_replace_pb_clicked(), and replaceConductor().
replaceDiagram() [1/2]
void SearchAndReplaceWorker::replaceDiagram (Diagram * diagram)
Definition at line 87 of file searchandreplaceworker.cpp.
References replaceDiagram().
replaceDiagram() [2/2]
void SearchAndReplaceWorker::replaceDiagram (QList< Diagram * > diagram_list)
SearchAndReplaceWorker::replaceDiagram Replace all properties of each diagram in diagram_list, by the current titleblock propertie of this worker.
Parameters
diagram_list : list of diagram to be changed, all diagrams must belong to the same project;
Definition at line 41 of file searchandreplaceworker.cpp.
References DiagramContext::add(), applyChange(), TitleBlockProperties::author, TitleBlockProperties::context, TitleBlockProperties::date, eraseDate(), TitleBlockProperties::filename, TitleBlockProperties::folio, TitleBlockProperties::indexrev, TitleBlockProperties::locmach, m_titleblock_properties, TitleBlockProperties::plant, TitleBlockProperties::title, QET::Icons::tr, and QETProject::undoStack().
Referenced by SearchAndReplaceWidget::on_m_replace_all_pb_clicked(), SearchAndReplaceWidget::on_m_replace_pb_clicked(), and replaceDiagram().
replaceElement() [1/2]
void SearchAndReplaceWorker::replaceElement (Element * element)
Definition at line 145 of file searchandreplaceworker.cpp.
References replaceElement().
replaceElement() [2/2]
void SearchAndReplaceWorker::replaceElement (QList< Element * > list)
SearchAndReplaceWorker::replaceElement Replace all properties of each elements in list All element must belong to the same project, if not this function do nothing. All change are made through a undo command append to undo list of the project.
Parameters
list
Definition at line 103 of file searchandreplaceworker.cpp.
References DiagramContext::addValue(), applyChange(), QETApp::elementInfoKeys(), m_element_context, Element::Master, Element::Simple, Element::Terminale, QET::Icons::tr, QETProject::undoStack(), and DiagramContext::value().
Referenced by SearchAndReplaceWidget::on_m_replace_all_pb_clicked(), SearchAndReplaceWidget::on_m_replace_pb_clicked(), and replaceElement().
replaceIndiText() [1/2]
void SearchAndReplaceWorker::replaceIndiText (IndependentTextItem * text)
Definition at line 181 of file searchandreplaceworker.cpp.
References replaceIndiText().
replaceIndiText() [2/2]
void SearchAndReplaceWorker::replaceIndiText (QList< IndependentTextItem * > list)
SearchAndReplaceWorker::replaceIndiText Replace all displayed text of independent text of list Each must belong to the same project, if not this function do nothing.
Parameters
list
Definition at line 158 of file searchandreplaceworker.cpp.
References m_indi_text, QET::Icons::tr, and QETProject::undoStack().
Referenced by SearchAndReplaceWidget::on_m_replace_all_pb_clicked(), SearchAndReplaceWidget::on_m_replace_pb_clicked(), and replaceIndiText().
setupLineEdit()
void SearchAndReplaceWorker::setupLineEdit (QLineEdit * l, QCheckBox * cb, QString str) static
SearchAndReplaceWorker::setupLineEdit With search and replace, when the variable to edit is a text, the editor is always the same no matter if it is for a folio, element or conductor. The editor is a QLineEdit to edit the text and checkbox to erase the text if checked. This function fill the editor, from the current string.
Parameters
l
cb
str
Definition at line 371 of file searchandreplaceworker.cpp.
References eraseText().
Referenced by ReplaceConductorDialog::setProperties(), ElementInfoPartWidget::setText(), and ReplaceFolioWidget::setTitleBlockProperties().
Friends And Related Function Documentation
SearchAndReplaceWidget
friend class SearchAndReplaceWidget friend
Definition at line 97 of file searchandreplaceworker.h.
Member Data Documentation
m_advanced_struct
advancedReplaceStruct SearchAndReplaceWorker::m_advanced_struct private
Definition at line 95 of file searchandreplaceworker.h.
Referenced by SearchAndReplaceWidget::on_m_advanced_replace_pb_clicked(), and replaceAdvanced().
m_conductor_properties
ConductorProperties SearchAndReplaceWorker::m_conductor_properties private
Definition at line 94 of file searchandreplaceworker.h.
Referenced by SearchAndReplaceWidget::on_m_conductor_pb_clicked(), replaceConductor(), and SearchAndReplaceWorker().
m_element_context
DiagramContext SearchAndReplaceWorker::m_element_context private
Definition at line 92 of file searchandreplaceworker.h.
Referenced by SearchAndReplaceWidget::on_m_element_pb_clicked(), and replaceElement().
m_indi_text
QString SearchAndReplaceWorker::m_indi_text private
Definition at line 93 of file searchandreplaceworker.h.
Referenced by SearchAndReplaceWidget::on_m_replace_all_pb_clicked(), SearchAndReplaceWidget::on_m_replace_pb_clicked(), and replaceIndiText().
m_titleblock_properties
TitleBlockProperties SearchAndReplaceWorker::m_titleblock_properties private
Definition at line 91 of file searchandreplaceworker.h.
Referenced by SearchAndReplaceWidget::on_m_folio_pb_clicked(), and replaceDiagram().
The documentation for this class was generated from the following files:
searchandreplaceworker.h
searchandreplaceworker.cpp