QElectroTech: TitleBlockTemplateCellsSet Class Reference
TitleBlockTemplateCellsSet Class Reference
#include <templatecellsset.h>
Public Member Functions
TitleBlockTemplateCellsSet (const TitleBlockTemplateView *)
virtual ~TitleBlockTemplateCellsSet ()
QPainterPath painterPath () const
bool isRectangle () const
bool allCellsAreSelected () const
bool hasExternalSpan () const
TitleBlockTemplateVisualCell * topLeftCell () const
TitleBlockTemplateVisualCell * bottomRightCell () const
QRectF mergeAreaRect () const
TitleBlockTemplateCellsSet mergeArea (const QRectF &=QRectF()) const
QSet< TitleBlockCell * > cells (bool=true) const
Public Attributes
const TitleBlockTemplateView * parent_view_
the view displaying the cells
Detailed Description
This class represents a set of cells (selected or not) when editing a title block template.
Definition at line 28 of file templatecellsset.h.
Constructor & Destructor Documentation
TitleBlockTemplateCellsSet()
TitleBlockTemplateCellsSet::TitleBlockTemplateCellsSet (const TitleBlockTemplateView * parent_view)
Constructor
Parameters
parent_view View this set of cells are rattached to
Definition at line 30 of file templatecellsset.cpp.
~TitleBlockTemplateCellsSet()
TitleBlockTemplateCellsSet::~TitleBlockTemplateCellsSet () virtual
Destructor
Definition at line 38 of file templatecellsset.cpp.
Member Function Documentation
allCellsAreSelected()
bool TitleBlockTemplateCellsSet::allCellsAreSelected () const
Returns
true if all cells within this set are selected
Definition at line 69 of file templatecellsset.cpp.
bottomRightCell()
TitleBlockTemplateVisualCell * TitleBlockTemplateCellsSet::bottomRightCell () const
Returns
the bottom right cell within this set, or 0 if this set is empty
Definition at line 129 of file templatecellsset.cpp.
Referenced by MergeCellsCommand::getBottomRightCell(), and mergeAreaRect().
cells()
QSet< TitleBlockCell * > TitleBlockTemplateCellsSet::cells (bool include_spanned = true) const
Returns
the list of cells rendered by the current selection
Parameters
include_spanned whether to include spanned cells or not
Definition at line 191 of file templatecellsset.cpp.
Referenced by hasExternalSpan(), mergeArea(), and MergeCellsCommand::MergeCellsCommand().
hasExternalSpan()
bool TitleBlockTemplateCellsSet::hasExternalSpan () const
Returns
true if this set includes at least one cell which is spanned by a cell not present in this set, false otherwise.
Definition at line 82 of file templatecellsset.cpp.
References cells().
isRectangle()
bool TitleBlockTemplateCellsSet::isRectangle () const
Returns
true if the cells within this set are composing a rectangle shape, false otherwise.
Definition at line 56 of file templatecellsset.cpp.
References painterPath().
Referenced by MergeCellsCommand::canMerge().
mergeArea()
TitleBlockTemplateCellsSet TitleBlockTemplateCellsSet::mergeArea (const QRectF & rect = QRectF()) const
Parameters
rect (Optional) The merge area to be considered; if a null QRectF is provided, this method will use mergeAreaRect().
Returns
the cells contained in the merge area of this cells set
Definition at line 177 of file templatecellsset.cpp.
References cells(), mergeAreaRect(), and parent_view_.
mergeAreaRect()
QRectF TitleBlockTemplateCellsSet::mergeAreaRect () const
Returns
the merge area, i.e. the rectangle delimited by the top left cell and the bottom right cell within this cells set.
Definition at line 158 of file templatecellsset.cpp.
References bottomRightCell(), parent_view_, and topLeftCell().
Referenced by mergeArea().
painterPath()
QPainterPath TitleBlockTemplateCellsSet::painterPath () const
Returns
a QPainterPath composed of the rectangles from cells within this set
Definition at line 44 of file templatecellsset.cpp.
Referenced by isRectangle().
topLeftCell()
TitleBlockTemplateVisualCell * TitleBlockTemplateCellsSet::topLeftCell () const
Returns
the top left cell within this set, or 0 if this set is empty
Definition at line 98 of file templatecellsset.cpp.
Referenced by MergeCellsCommand::canMerge(), mergeAreaRect(), MergeCellsCommand::MergeCellsCommand(), and TitleBlockTemplateView::paste().
Member Data Documentation
parent_view_
const TitleBlockTemplateView* TitleBlockTemplateCellsSet::parent_view_
the view displaying the cells
Definition at line 48 of file templatecellsset.h.
Referenced by mergeArea(), and mergeAreaRect().
The documentation for this class was generated from the following files:
templatecellsset.h
templatecellsset.cpp