QElectroTech: QETTitleBlockTemplateEditor Class Reference
QETTitleBlockTemplateEditor Class Reference
#include <qettemplateeditor.h>
Public Slots
void readSettings ()
QETTitleBlockTemplateEditor::readSettings Read settings.
void writeSettings ()
QETTitleBlockTemplateEditor::writeSettings Write the settings.
void selectedCellsChanged (const QList< TitleBlockCell * > &)
void duplicateCurrentLocation ()
bool edit (const TitleBlockTemplateLocation &)
bool edit (QETProject *, const QString &)
bool edit (const QString &)
bool editCopyOf (const TitleBlockTemplate *)
bool edit (TitleBlockTemplate *)
void editLogos ()
void newTemplate ()
void open ()
void openFromFile ()
bool save ()
bool saveAs ()
bool saveAsFile ()
void setReadOnly (bool)
void quit ()
void savePreviewWidthToApplicationSettings (int, int)
QETTitleBlockTemplateEditor::savePreviewWidthToApplicationSettings Save the new preview width to application settings.
void editTemplateInformation ()
Public Slots inherited from QETMainWindow
void toggleFullScreen ()
void updateFullScreenAction ()
void checkToolbarsmenu ()
Public Member Functions
QETTitleBlockTemplateEditor (QWidget *=nullptr)
~QETTitleBlockTemplateEditor () override
TitleBlockTemplateLocation location () const
bool isEditing (const QString &ilepath)
void setOpenForDuplication (bool)
QETTitleBlockTemplateEditor::setOpenForDuplication.
bool openForDuplication () const
Public Member Functions inherited from QETMainWindow
QETMainWindow (QWidget *=nullptr, Qt::WindowFlags=Qt::Widget)
~QETMainWindow () override
Protected Member Functions
bool canClose ()
void firstActivation (QEvent *) override
void closeEvent (QCloseEvent *) override
Protected Member Functions inherited from QETMainWindow
void initCommonActions ()
void initCommonMenus ()
void insertMenu (QMenu *, QMenu *, bool=true)
QAction * actionForMenu (QMenu *)
bool event (QEvent *) override
void dragEnterEvent (QDragEnterEvent *e) override
void dropEvent (QDropEvent *e) override
Private Slots
TitleBlockTemplateLocation getTitleBlockTemplateLocationFromUser (const QString &=QString(), bool existing_only=true)
void pushCellUndoCommand (ModifyTitleBlockCellCommand *)
void pushGridUndoCommand (TitleBlockTemplateCommand *)
void pushUndoCommand (QUndoCommand *)
void updateEditorTitle ()
void updateActions ()
bool saveAs (const TitleBlockTemplateLocation &)
bool saveAs (const QString &)
Private Member Functions
QETTitleBlockTemplateEditor (const QETTitleBlockTemplateEditor &)
void initActions ()
void initMenus ()
void initToolbars ()
void initWidgets ()
void initLogoManager ()
QString currentlyEditedTitle () const
Private Attributes
QMenu * file_menu_
menus TODO
QMenu * edit_menu_
QMenu * display_menu_
QAction * new_
actions
QAction * open_
QAction * open_from_file_
QAction * save_
QAction * save_as_
QAction * save_as_file_
QAction * quit_
QAction * undo_
QAction * redo_
QAction * cut_
QAction * copy_
QAction * paste_
QAction * edit_logos_
QAction * edit_info_
QAction * add_row_
QAction * add_col_
QAction * merge_cells_
QAction * split_cell_
QAction * zoom_in_
QAction * zoom_out_
QAction * zoom_fit_
QAction * zoom_reset_
TitleBlockTemplateLocation location_
Location of the currently edited template.
QString filepath_
Filepath of the currently edited template, if opened from a file.
bool opened_from_file_
Whether to consider the location or the filepath.
bool read_only_
whether the currently edited template is considered read only
bool duplicate_
bool first_activation_
Used to track the first activation of the editor main window.
TitleBlockTemplate * tb_template_
Template Object edited.
QGraphicsScene * template_edition_area_scene_
Template preview.
TitleBlockTemplateView * template_edition_area_view_
QDockWidget * template_cell_editor_dock_widget_
Individual cell widget edition.
TitleBlockTemplateCellWidget * template_cell_editor_widget_
TitleBlockTemplateLogoManager * logo_manager_
Logo manager widget.
QUndoStack * undo_stack_
Undo interface.
QUndoView * undo_view_
QDockWidget * undo_dock_widget_
Additional Inherited Members
Protected Attributes inherited from QETMainWindow
QAction * configure_action_
Launch the QElectroTech configuration dialog.
QAction * fullscreen_action_
Toggle full screen.
QAction * whatsthis_action_
Toggle "What's this" mode.
QAction * about_qet_
Launch the "About QElectroTech" dialog.
QAction * manual_online_
Launch browser on QElectroTech online manual.
QAction * youtube_
Launch browser on QElectroTech Youtube channel.
QAction * upgrade_
Launch browser on QElectroTech Windows Nightly builds.
QAction * upgrade_M
Launch browser on QElectroTech MAC_OS_X builds.
QAction * donate_
Launch browser to donate link.
QAction * about_qt_
launch the "About Qt" dialog
QMenu * settings_menu_
Settings menu.
QMenu * help_menu_
Help menu.
QMenu * display_toolbars_
Show/hide toolbars/docks.
QHash< QMenu *, QAction * > menu_actions_
Store actions retrieved when inserting menus.
bool first_activation_
Used to detect whether the window is activated for the first time.
Detailed Description
This class implements the main window of QElectroTech's titleblock template editor. This editor aims at allowing users to easily create their own title block templates.
Definition at line 36 of file qettemplateeditor.h.
Constructor & Destructor Documentation
QETTitleBlockTemplateEditor() [1/2]
QETTitleBlockTemplateEditor::QETTitleBlockTemplateEditor (QWidget * parent = nullptr)
Parameters
parent parent QWidget of this window
Definition at line 33 of file qettemplateeditor.cpp.
References initActions(), initMenus(), initToolbars(), initWidgets(), QET::Icons::QETLogo, and readSettings().
Referenced by newTemplate().
~QETTitleBlockTemplateEditor()
QETTitleBlockTemplateEditor::~QETTitleBlockTemplateEditor () override
Destructor
Definition at line 54 of file qettemplateeditor.cpp.
QETTitleBlockTemplateEditor() [2/2]
QETTitleBlockTemplateEditor::QETTitleBlockTemplateEditor (const QETTitleBlockTemplateEditor &) private
Member Function Documentation
canClose()
bool QETTitleBlockTemplateEditor::canClose () protected
Returns
true if the currently edited template can be closed. A template can be closed if it has not been modified. If the template has been modified, this method asks the user what he wants to do.
Definition at line 107 of file qettemplateeditor.cpp.
References QET::Icons::Cancel, location_, TitleBlockTemplateLocation::name(), QET::QetMessageBox::question(), save(), QET::Icons::tr, and undo_stack_.
Referenced by closeEvent().
closeEvent()
void QETTitleBlockTemplateEditor::closeEvent (QCloseEvent * qce) override protected
Handle the closing of the main window
Parameters
qce The QCloseEvent event
Definition at line 146 of file qettemplateeditor.cpp.
References canClose(), and writeSettings().
currentlyEditedTitle()
QString QETTitleBlockTemplateEditor::currentlyEditedTitle () const private
Returns
a string describing what is being edited, along with [Changed] or [Read only] tags. Useful to compose the window title.
Definition at line 560 of file qettemplateeditor.cpp.
References filepath_, location_, TitleBlockTemplateLocation::name(), opened_from_file_, read_only_, QET::Icons::tr, and undo_stack_.
Referenced by updateEditorTitle().
duplicateCurrentLocation
void QETTitleBlockTemplateEditor::duplicateCurrentLocation () slot
Ask the user for a new template name in order to duplicate the currently edited template.
Definition at line 158 of file qettemplateeditor.cpp.
References location_, TitleBlockTemplateLocation::name(), opened_from_file_, TitleBlockTemplateLocation::parentCollection(), saveAs(), and QET::Icons::tr.
Referenced by firstActivation().
edit [1/4]
bool QETTitleBlockTemplateEditor::edit (const QString & file_path) slot
Parameters
file_path Path of the template file to edit.
Returns
false if a problem occurred while opening the template, true otherwise.
TODO the file opening failed, warn the user?
TODO the file editing failed, warn the user?
Definition at line 249 of file qettemplateeditor.cpp.
References edit(), filepath_, opened_from_file_, setReadOnly(), and QET::TitleBlockTemplate.
edit [2/4]
bool QETTitleBlockTemplateEditor::edit (const TitleBlockTemplateLocation & location) slot
Parameters
location Location of the tile block template to be edited.
TODO The TBT does not exist, manage error
Definition at line 187 of file qettemplateeditor.cpp.
References QETApp::defaultTitleBlockTemplate(), editCopyOf(), TitleBlockTemplateLocation::getTemplate(), TitleBlockTemplateLocation::isReadOnly(), location(), location_, TitleBlockTemplateLocation::name(), opened_from_file_, and setReadOnly().
Referenced by edit(), editCopyOf(), newTemplate(), and selectedCellsChanged().
edit [3/4]
bool QETTitleBlockTemplateEditor::edit (QETProject * project, const QString & template_name) slot
Edit the given template.
Parameters
project Parent project of the template to edit.
template_name Name of the template to edit within its parent project.
Returns
true if this editor was able to edit the given template, false otherwise
TODO The TBT does not exist, manage error
Definition at line 215 of file qettemplateeditor.cpp.
References QETApp::defaultTitleBlockTemplate(), editCopyOf(), QETProject::embeddedTitleBlockTemplatesCollection(), TitleBlockTemplatesProjectCollection::getTemplate(), location_, opened_from_file_, TitleBlockTemplateLocation::setName(), TitleBlockTemplateLocation::setParentCollection(), and setReadOnly().
edit [4/4]
bool QETTitleBlockTemplateEditor::edit (TitleBlockTemplate * tbt) slot
Parameters
tbt Title block template to be directly edited
Returns
false if a problem occurred while opening the template, true otherwise.
Definition at line 284 of file qettemplateeditor.cpp.
References tb_template_, template_cell_editor_widget_, template_edition_area_view_, and updateEditorTitle().
editCopyOf
bool QETTitleBlockTemplateEditor::editCopyOf (const TitleBlockTemplate * tbt) slot
Parameters
tbt Title block template to be edited
Returns
false if a problem occurred while opening the template, true otherwise.
Definition at line 275 of file qettemplateeditor.cpp.
References edit().
Referenced by edit().
editLogos
void QETTitleBlockTemplateEditor::editLogos () slot
Launches the logo manager widget, which allows the user to manage the logos embedded within the edited template.
Definition at line 297 of file qettemplateeditor.cpp.
References initLogoManager(), logo_manager_, and tb_template_.
Referenced by initActions(), and initWidgets().
editTemplateInformation
void QETTitleBlockTemplateEditor::editTemplateInformation () slot
Edit extra information attached to the template.
Definition at line 927 of file qettemplateeditor.cpp.
References QET::Icons::Cancel, QET::QetMessageBox::information(), pushUndoCommand(), read_only_, setReadOnly(), tb_template_, and QET::Icons::tr.
Referenced by initActions().
firstActivation()
void QETTitleBlockTemplateEditor::firstActivation (QEvent * event) override protected virtual
Parameters
event Object describing the received event.
Reimplemented from QETMainWindow.
Definition at line 134 of file qettemplateeditor.cpp.
References duplicate_, duplicateCurrentLocation(), QETMainWindow::event(), location_, opened_from_file_, and TitleBlockTemplateLocation::parentCollection().
getTitleBlockTemplateLocationFromUser
TitleBlockTemplateLocation QETTitleBlockTemplateEditor::getTitleBlockTemplateLocationFromUser (const QString & title = QString(), bool existing_only = true) private slot
Ask the user for a title block template location
Parameters
title Title displayed by the dialog window
existing_only True for the user to be forced to choose an existing template, false if he may specify the template name
Returns
The location chosen by the user, or an empty TitleBlockTemplateLocation if the user cancelled the dialog
Definition at line 878 of file qettemplateeditor.cpp.
References QET::Icons::Cancel, and location().
Referenced by open(), and saveAs().
initActions()
void QETTitleBlockTemplateEditor::initActions () private
Initialize the various actions.
Definition at line 333 of file qettemplateeditor.cpp.
References add_col_, add_row_, QET::Icons::ApplicationExit, copy_, cut_, QET::Icons::DocumentNew, QET::Icons::DocumentOpen, QET::Icons::DocumentSave, QET::Icons::DocumentSaveAs, edit_info_, edit_logos_, QET::Icons::EditCopy, QET::Icons::EditCut, editLogos(), QET::Icons::EditPaste, QET::Icons::EditRedo, QET::Icons::EditTableCellMerge, QET::Icons::EditTableCellSplit, QET::Icons::EditTableInsertColumnRight, QET::Icons::EditTableInsertRowAbove, editTemplateInformation(), QET::Icons::EditUndo, QET::Icons::InsertImage, merge_cells_, new_, newTemplate(), open(), open_, open_from_file_, openFromFile(), paste_, quit(), quit_, redo_, save(), save_, save_as_, save_as_file_, saveAs(), saveAsFile(), split_cell_, template_edition_area_view_, QET::Icons::tr, undo_, undo_stack_, QET::Icons::UserInformations, zoom_fit_, zoom_in_, zoom_out_, zoom_reset_, QET::Icons::ZoomFitBest, QET::Icons::ZoomIn, QET::Icons::ZoomOriginal, and QET::Icons::ZoomOut.
Referenced by QETTitleBlockTemplateEditor().
initLogoManager()
void QETTitleBlockTemplateEditor::initLogoManager () private
Initialize the logo manager
Definition at line 545 of file qettemplateeditor.cpp.
References logo_manager_, read_only_, setReadOnly(), tb_template_, and template_cell_editor_widget_.
Referenced by editLogos().
initMenus()
void QETTitleBlockTemplateEditor::initMenus () private
Initialize the various menus.
Definition at line 405 of file qettemplateeditor.cpp.
References add_col_, add_row_, copy_, cut_, display_menu_, edit_info_, edit_logos_, edit_menu_, file_menu_, QETMainWindow::insertMenu(), merge_cells_, new_, open_, open_from_file_, paste_, quit_, redo_, save_, save_as_, save_as_file_, QETMainWindow::settings_menu_, split_cell_, QET::Icons::tr, undo_, zoom_fit_, zoom_in_, zoom_out_, and zoom_reset_.
Referenced by QETTitleBlockTemplateEditor().
initToolbars()
void QETTitleBlockTemplateEditor::initToolbars () private
Initalize toolbars.
Definition at line 446 of file qettemplateeditor.cpp.
References merge_cells_, new_, open_, redo_, save_, save_as_, split_cell_, QET::Icons::tr, undo_, zoom_fit_, zoom_in_, zoom_out_, and zoom_reset_.
Referenced by QETTitleBlockTemplateEditor().
initWidgets()
void QETTitleBlockTemplateEditor::initWidgets () private
Initialize layouts and widgets
Definition at line 476 of file qettemplateeditor.cpp.
References editLogos(), pushCellUndoCommand(), pushGridUndoCommand(), savePreviewWidthToApplicationSettings(), selectedCellsChanged(), tb_template_, template_cell_editor_dock_widget_, template_cell_editor_widget_, template_edition_area_scene_, template_edition_area_view_, QET::Icons::tr, undo_dock_widget_, undo_stack_, undo_view_, updateActions(), and updateEditorTitle().
Referenced by QETTitleBlockTemplateEditor().
isEditing()
bool QETTitleBlockTemplateEditor::isEditing (const QString & filepath)
Returns
true if the provided filepath matches the currently edited template.
Parameters
filepath path of a title block template on the filesystem
Definition at line 68 of file qettemplateeditor.cpp.
References QET::compareCanonicalFilePaths(), filepath_, location_, opened_from_file_, QETApp::realPath(), and TitleBlockTemplateLocation::toString().
location()
TitleBlockTemplateLocation QETTitleBlockTemplateEditor::location () const
Returns
the location of the currently edited template
Definition at line 60 of file qettemplateeditor.cpp.
References location_.
Referenced by edit(), getTitleBlockTemplateLocationFromUser(), open(), and saveAs().
newTemplate
void QETTitleBlockTemplateEditor::newTemplate () slot
Launch a new title block template editor.
Definition at line 324 of file qettemplateeditor.cpp.
References edit(), and QETTitleBlockTemplateEditor().
Referenced by initActions().
open
void QETTitleBlockTemplateEditor::open () slot
Ask the user to choose a title block template from the known collections then open it for edition.
Definition at line 751 of file qettemplateeditor.cpp.
References getTitleBlockTemplateLocationFromUser(), QETApp::instance(), TitleBlockTemplateLocation::isValid(), location(), and QET::Icons::tr.
Referenced by initActions().
openForDuplication()
bool QETTitleBlockTemplateEditor::openForDuplication () const
Returns
true if this editor will prompt the user for a new template name as soon as the window appears in order to duplicate the edited one.
Definition at line 98 of file qettemplateeditor.cpp.
References duplicate_.
openFromFile
void QETTitleBlockTemplateEditor::openFromFile () slot
Ask the user to choose a file supposed to contain a title block template, then open it for edition.
Definition at line 765 of file qettemplateeditor.cpp.
References QETApp::customTitleBlockTemplatesDir(), filepath_, QETApp::instance(), TITLEBLOCKS_FILE_EXTENSION, and QET::Icons::tr.
Referenced by initActions().
pushCellUndoCommand
void QETTitleBlockTemplateEditor::pushCellUndoCommand (ModifyTitleBlockCellCommand * command) private slot
Configure an undo Command before adding it to the undo stack.
Parameters
command to be added to the undo stack
Definition at line 634 of file qettemplateeditor.cpp.
References pushUndoCommand(), and template_edition_area_view_.
Referenced by initWidgets().
pushGridUndoCommand
void QETTitleBlockTemplateEditor::pushGridUndoCommand (TitleBlockTemplateCommand * command) private slot
Add an undo Command to the undo stack.
Parameters
command QUndoCommand to be added to the undo stack
Definition at line 643 of file qettemplateeditor.cpp.
References pushUndoCommand().
Referenced by initWidgets().
pushUndoCommand
void QETTitleBlockTemplateEditor::pushUndoCommand (QUndoCommand * command) private slot
Add an undo Command to the undo stack.
Parameters
command QUndoCommand to be added to the undo stack
Definition at line 651 of file qettemplateeditor.cpp.
References undo_stack_.
Referenced by editTemplateInformation(), pushCellUndoCommand(), and pushGridUndoCommand().
quit
void QETTitleBlockTemplateEditor::quit () slot
Close the current editor.
Definition at line 907 of file qettemplateeditor.cpp.
Referenced by initActions().
readSettings
void QETTitleBlockTemplateEditor::readSettings () slot
QETTitleBlockTemplateEditor::readSettings Read settings.
Definition at line 592 of file qettemplateeditor.cpp.
Referenced by QETTitleBlockTemplateEditor().
save
bool QETTitleBlockTemplateEditor::save () slot
Save the currently edited title block template back to its parent project.
Definition at line 789 of file qettemplateeditor.cpp.
References filepath_, TitleBlockTemplateLocation::isReadOnly(), TitleBlockTemplateLocation::isValid(), location_, opened_from_file_, saveAs(), and saveAsFile().
Referenced by canClose(), and initActions().
saveAs [1/3]
bool QETTitleBlockTemplateEditor::saveAs () slot
Ask the user where he wishes to save the currently edited template.
Definition at line 811 of file qettemplateeditor.cpp.
References getTitleBlockTemplateLocationFromUser(), TitleBlockTemplateLocation::isValid(), location(), and QET::Icons::tr.
Referenced by duplicateCurrentLocation(), initActions(), save(), and saveAsFile().
saveAs [2/3]
bool QETTitleBlockTemplateEditor::saveAs (const QString & filepath) private slot
Save the template in the provided filepath.
See also
TitleBlockTemplate::saveToXmlFile()
Parameters
filepath location Location where the title block template should be saved.
Definition at line 736 of file qettemplateeditor.cpp.
References filepath_, opened_from_file_, setReadOnly(), tb_template_, and undo_stack_.
saveAs [3/3]
bool QETTitleBlockTemplateEditor::saveAs (const TitleBlockTemplateLocation & location) private slot
Save the template under the provided location.
See also
QETProject::setTemplateXmlDescription()
Parameters
location Location where the title block template should be saved.
Definition at line 712 of file qettemplateeditor.cpp.
References location(), location_, TitleBlockTemplateLocation::name(), opened_from_file_, TitleBlockTemplateLocation::parentCollection(), setReadOnly(), tb_template_, and undo_stack_.
saveAsFile
bool QETTitleBlockTemplateEditor::saveAsFile () slot
Ask the user where on the filesystem he wishes to save the currently edited template.
Definition at line 825 of file qettemplateeditor.cpp.
References QETApp::customTitleBlockTemplatesDir(), filepath_, saveAs(), TITLEBLOCKS_FILE_EXTENSION, and QET::Icons::tr.
Referenced by initActions(), and save().
savePreviewWidthToApplicationSettings
void QETTitleBlockTemplateEditor::savePreviewWidthToApplicationSettings (int former_preview_width, int new_preview_width) slot
QETTitleBlockTemplateEditor::savePreviewWidthToApplicationSettings Save the new preview width to application settings.
Parameters
former_preview_width : former_preview_width Unused, former preview width
new_preview_width : new_preview_width New preview width
Definition at line 917 of file qettemplateeditor.cpp.
Referenced by initWidgets().
selectedCellsChanged
void QETTitleBlockTemplateEditor::selectedCellsChanged (const QList< TitleBlockCell * > & selected_cells) slot
Update various things when user changes the selected cells.
Parameters
selected_cells List of selected cells.
Definition at line 620 of file qettemplateeditor.cpp.
References edit(), template_cell_editor_widget_, and updateActions().
Referenced by initWidgets().
setOpenForDuplication()
void QETTitleBlockTemplateEditor::setOpenForDuplication (bool duplicate)
QETTitleBlockTemplateEditor::setOpenForDuplication.
Parameters
duplicate : true for this editor to prompt the user for a new template name as soon as the window appears in order to duplicate the edited one.
Definition at line 90 of file qettemplateeditor.cpp.
References duplicate_.
setReadOnly
void QETTitleBlockTemplateEditor::setReadOnly (bool read_only) slot
Parameters
read_only True to restrict this editor to visualization of the currently edited template, false to allow full edition.
Definition at line 857 of file qettemplateeditor.cpp.
References logo_manager_, read_only_, template_cell_editor_widget_, template_edition_area_view_, updateActions(), and updateEditorTitle().
Referenced by edit(), editTemplateInformation(), initLogoManager(), and saveAs().
updateActions
void QETTitleBlockTemplateEditor::updateActions () private slot
Ensure the user interface remains consistent by enabling or disabling adequate actions.
Definition at line 689 of file qettemplateeditor.cpp.
References add_col_, add_row_, copy_, cut_, merge_cells_, paste_, read_only_, save_, split_cell_, and template_edition_area_view_.
Referenced by initWidgets(), selectedCellsChanged(), and setReadOnly().
updateEditorTitle
void QETTitleBlockTemplateEditor::updateEditorTitle () private slot
Set the title of this editor.
Definition at line 658 of file qettemplateeditor.cpp.
References currentlyEditedTitle(), and QET::Icons::tr.
Referenced by edit(), initWidgets(), and setReadOnly().
writeSettings
void QETTitleBlockTemplateEditor::writeSettings () slot
QETTitleBlockTemplateEditor::writeSettings Write the settings.
Definition at line 609 of file qettemplateeditor.cpp.
Referenced by closeEvent().
Member Data Documentation
add_col_
QAction * QETTitleBlockTemplateEditor::add_col_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and updateActions().
add_row_
QAction * QETTitleBlockTemplateEditor::add_row_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and updateActions().
copy_
QAction * QETTitleBlockTemplateEditor::copy_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and updateActions().
cut_
QAction * QETTitleBlockTemplateEditor::cut_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and updateActions().
display_menu_
QMenu * QETTitleBlockTemplateEditor::display_menu_ private
Definition at line 49 of file qettemplateeditor.h.
Referenced by initMenus().
duplicate_
bool QETTitleBlockTemplateEditor::duplicate_ private
Whether to ask the user a new template name when the window appears in order to rename the edited template.
Definition at line 66 of file qettemplateeditor.h.
Referenced by firstActivation(), openForDuplication(), and setOpenForDuplication().
edit_info_
QAction * QETTitleBlockTemplateEditor::edit_info_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), and initMenus().
edit_logos_
QAction * QETTitleBlockTemplateEditor::edit_logos_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), and initMenus().
edit_menu_
QMenu * QETTitleBlockTemplateEditor::edit_menu_ private
Definition at line 49 of file qettemplateeditor.h.
Referenced by initMenus().
file_menu_
QMenu* QETTitleBlockTemplateEditor::file_menu_ private
menus TODO
Definition at line 49 of file qettemplateeditor.h.
Referenced by initMenus().
filepath_
QString QETTitleBlockTemplateEditor::filepath_ private
Filepath of the currently edited template, if opened from a file.
Definition at line 57 of file qettemplateeditor.h.
Referenced by currentlyEditedTitle(), edit(), isEditing(), openFromFile(), save(), saveAs(), and saveAsFile().
first_activation_
bool QETTitleBlockTemplateEditor::first_activation_ private
Used to track the first activation of the editor main window.
Definition at line 68 of file qettemplateeditor.h.
location_
TitleBlockTemplateLocation QETTitleBlockTemplateEditor::location_ private
Location of the currently edited template.
Definition at line 55 of file qettemplateeditor.h.
Referenced by canClose(), currentlyEditedTitle(), duplicateCurrentLocation(), edit(), firstActivation(), isEditing(), location(), save(), and saveAs().
logo_manager_
TitleBlockTemplateLogoManager* QETTitleBlockTemplateEditor::logo_manager_ private
Logo manager widget.
Definition at line 78 of file qettemplateeditor.h.
Referenced by editLogos(), initLogoManager(), and setReadOnly().
merge_cells_
QAction * QETTitleBlockTemplateEditor::merge_cells_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), initToolbars(), and updateActions().
new_
QAction* QETTitleBlockTemplateEditor::new_ private
actions
Definition at line 51 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
open_
QAction * QETTitleBlockTemplateEditor::open_ private
Definition at line 51 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
open_from_file_
QAction * QETTitleBlockTemplateEditor::open_from_file_ private
Definition at line 51 of file qettemplateeditor.h.
Referenced by initActions(), and initMenus().
opened_from_file_
bool QETTitleBlockTemplateEditor::opened_from_file_ private
Whether to consider the location or the filepath.
Definition at line 59 of file qettemplateeditor.h.
Referenced by currentlyEditedTitle(), duplicateCurrentLocation(), edit(), firstActivation(), isEditing(), save(), and saveAs().
paste_
QAction * QETTitleBlockTemplateEditor::paste_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and updateActions().
quit_
QAction * QETTitleBlockTemplateEditor::quit_ private
Definition at line 51 of file qettemplateeditor.h.
Referenced by initActions(), and initMenus().
read_only_
bool QETTitleBlockTemplateEditor::read_only_ private
whether the currently edited template is considered read only
Definition at line 61 of file qettemplateeditor.h.
Referenced by currentlyEditedTitle(), editTemplateInformation(), initLogoManager(), setReadOnly(), and updateActions().
redo_
QAction * QETTitleBlockTemplateEditor::redo_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
save_
QAction * QETTitleBlockTemplateEditor::save_ private
Definition at line 51 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), initToolbars(), and updateActions().
save_as_
QAction * QETTitleBlockTemplateEditor::save_as_ private
Definition at line 51 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
save_as_file_
QAction * QETTitleBlockTemplateEditor::save_as_file_ private
Definition at line 51 of file qettemplateeditor.h.
Referenced by initActions(), and initMenus().
split_cell_
QAction * QETTitleBlockTemplateEditor::split_cell_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), initToolbars(), and updateActions().
tb_template_
TitleBlockTemplate* QETTitleBlockTemplateEditor::tb_template_ private
Template Object edited.
Definition at line 70 of file qettemplateeditor.h.
Referenced by edit(), editLogos(), editTemplateInformation(), initLogoManager(), initWidgets(), and saveAs().
template_cell_editor_dock_widget_
QDockWidget* QETTitleBlockTemplateEditor::template_cell_editor_dock_widget_ private
Individual cell widget edition.
Definition at line 75 of file qettemplateeditor.h.
Referenced by initWidgets().
template_cell_editor_widget_
TitleBlockTemplateCellWidget* QETTitleBlockTemplateEditor::template_cell_editor_widget_ private
Definition at line 76 of file qettemplateeditor.h.
Referenced by edit(), initLogoManager(), initWidgets(), selectedCellsChanged(), and setReadOnly().
template_edition_area_scene_
QGraphicsScene* QETTitleBlockTemplateEditor::template_edition_area_scene_ private
Template preview.
Definition at line 72 of file qettemplateeditor.h.
Referenced by initWidgets().
template_edition_area_view_
TitleBlockTemplateView* QETTitleBlockTemplateEditor::template_edition_area_view_ private
Definition at line 73 of file qettemplateeditor.h.
Referenced by edit(), initActions(), initWidgets(), pushCellUndoCommand(), setReadOnly(), and updateActions().
undo_
QAction* QETTitleBlockTemplateEditor::undo_ private
Definition at line 52 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
undo_dock_widget_
QDockWidget* QETTitleBlockTemplateEditor::undo_dock_widget_ private
Definition at line 82 of file qettemplateeditor.h.
Referenced by initWidgets().
undo_stack_
QUndoStack* QETTitleBlockTemplateEditor::undo_stack_ private
Undo interface.
Definition at line 80 of file qettemplateeditor.h.
Referenced by canClose(), currentlyEditedTitle(), initActions(), initWidgets(), pushUndoCommand(), and saveAs().
undo_view_
QUndoView* QETTitleBlockTemplateEditor::undo_view_ private
Definition at line 81 of file qettemplateeditor.h.
Referenced by initWidgets().
zoom_fit_
QAction * QETTitleBlockTemplateEditor::zoom_fit_ private
Definition at line 53 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
zoom_in_
QAction* QETTitleBlockTemplateEditor::zoom_in_ private
Definition at line 53 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
zoom_out_
QAction * QETTitleBlockTemplateEditor::zoom_out_ private
Definition at line 53 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
zoom_reset_
QAction * QETTitleBlockTemplateEditor::zoom_reset_ private
Definition at line 53 of file qettemplateeditor.h.
Referenced by initActions(), initMenus(), and initToolbars().
The documentation for this class was generated from the following files:
qettemplateeditor.h
qettemplateeditor.cpp