QElectroTech: pugi Namespace Reference
pugi Namespace Reference
Classes
struct xml_attribute_struct
struct xml_node_struct
Functions
static PUGI__FN void unspecified_bool_xml_attribute (xml_attribute ***)
static PUGI__FN void unspecified_bool_xml_node (xml_node ***)
static PUGI__FN void unspecified_bool_xml_text (xml_text ***)
PUGI__FN std::string PUGIXML_FUNCTION as_utf8 (const wchar_t *str)
PUGI__FN std::string PUGIXML_FUNCTION as_utf8 (const std::basic_string< wchar_t > &str)
PUGI__FN std::basic_string< wchar_t > PUGIXML_FUNCTION as_wide (const char *str)
PUGI__FN std::basic_string< wchar_t > PUGIXML_FUNCTION as_wide (const std::string &str)
PUGI__FN void PUGIXML_FUNCTION set_memory_management_functions (allocation_function allocate, deallocation_function deallocate)
PUGI__FN allocation_function PUGIXML_FUNCTION get_memory_allocation_function ()
PUGI__FN deallocation_function PUGIXML_FUNCTION get_memory_deallocation_function ()
static PUGI__FN void unspecified_bool_xpath_node (xpath_node ***)
static PUGI__FN void unspecified_bool_xpath_query (xpath_query ***)
Function Documentation
as_utf8() [1/2]
PUGI__FN std::string PUGIXML_FUNCTION pugi::as_utf8 (const std::basic_string< wchar_t > & str)
Definition at line 7305 of file pugixml.cpp.
References as_utf8_impl().
as_utf8() [2/2]
PUGI__FN std::string PUGIXML_FUNCTION pugi::as_utf8 (const wchar_t * str)
Definition at line 7298 of file pugixml.cpp.
References as_utf8_impl(), and strlength_wide().
as_wide() [1/2]
PUGI__FN std::basic_string<wchar_t> PUGIXML_FUNCTION pugi::as_wide (const char * str)
Definition at line 7310 of file pugixml.cpp.
References as_wide_impl().
as_wide() [2/2]
PUGI__FN std::basic_string<wchar_t> PUGIXML_FUNCTION pugi::as_wide (const std::string & str)
Definition at line 7317 of file pugixml.cpp.
References as_wide_impl().
get_memory_allocation_function()
PUGI__FN allocation_function PUGIXML_FUNCTION pugi::get_memory_allocation_function ()
Definition at line 7329 of file pugixml.cpp.
get_memory_deallocation_function()
PUGI__FN deallocation_function PUGIXML_FUNCTION pugi::get_memory_deallocation_function ()
Definition at line 7334 of file pugixml.cpp.
set_memory_management_functions()
PUGI__FN void PUGIXML_FUNCTION pugi::set_memory_management_functions (allocation_function allocate, deallocation_function deallocate)
Definition at line 7323 of file pugixml.cpp.
unspecified_bool_xml_attribute()
static PUGI__FN void pugi::unspecified_bool_xml_attribute (xml_attribute ***) static
Definition at line 5124 of file pugixml.cpp.
unspecified_bool_xml_node()
static PUGI__FN void pugi::unspecified_bool_xml_node (xml_node ***) static
Definition at line 5420 of file pugixml.cpp.
unspecified_bool_xml_text()
static PUGI__FN void pugi::unspecified_bool_xml_text (xml_text ***) static
Definition at line 6440 of file pugixml.cpp.
unspecified_bool_xpath_node()
static PUGI__FN void pugi::unspecified_bool_xpath_node (xpath_node ***) static
Definition at line 12139 of file pugixml.cpp.
unspecified_bool_xpath_query()
static PUGI__FN void pugi::unspecified_bool_xpath_query (xpath_query ***) static
Definition at line 12828 of file pugixml.cpp.