QElectroTech: ProjectDBModelPropertiesWidget Class Reference
ProjectDBModelPropertiesWidget Class Reference
The projectDBModelPropertiesWidget class This class is an editor for a NomenclatureModel.
#include <projectdbmodelpropertieswidget.h>
Public Member Functions
ProjectDBModelPropertiesWidget (ProjectDBModel *model=nullptr, QWidget *parent=nullptr)
projectDBModelPropertiesWidget::projectDBModelPropertiesWidget
~ProjectDBModelPropertiesWidget ()
projectDBModelPropertiesWidget::~projectDBModelPropertiesWidget
void setModel (ProjectDBModel *model)
projectDBModelPropertiesWidget::setModel
Public Member Functions inherited from PropertiesEditorWidget
PropertiesEditorWidget (QWidget *parent=nullptr)
PropertiesEditorWidget::PropertiesEditorWidget Constructor.
virtual void apply ()
virtual void reset ()
virtual QUndoCommand * associatedUndo () const
PropertiesEditorWidget::associatedUndo By default, return a nullptr.
virtual QString title () const
PropertiesEditorWidget::title.
virtual void updateUi ()
virtual bool setLiveEdit (bool live_edit)
PropertiesEditorWidget::setLiveEdit Set the editor in live edit mode. When an editor is in live edit mode, every change is applied immediately (no need to call apply). If live edit can be enable, return true, else false. By default this method do nothing and return false (live edit is disable). Herited class of PropertiesEditorWidget must reimplemente this methode to manage the live edit mode.
bool isLiveEdit () const
PropertiesEditorWidget::isLiveEdit.
Private Slots
void on_m_edit_query_pb_clicked ()
projectDBModelPropertiesWidget::on_m_edit_query_pb_clicked
void on_m_refresh_pb_clicked ()
Private Attributes
Ui::ProjectDBModelPropertiesWidget * ui
ProjectDBModel * m_model = nullptr
Additional Inherited Members
Protected Member Functions inherited from PropertiesEditorWidget
virtual void enableLiveEdit ()
virtual void disableLiveEdit ()
Protected Attributes inherited from PropertiesEditorWidget
bool m_live_edit
Detailed Description
The projectDBModelPropertiesWidget class This class is an editor for a NomenclatureModel.
Definition at line 33 of file projectdbmodelpropertieswidget.h.
Constructor & Destructor Documentation
ProjectDBModelPropertiesWidget()
ProjectDBModelPropertiesWidget::ProjectDBModelPropertiesWidget (ProjectDBModel * model = nullptr, QWidget * parent = nullptr) explicit
projectDBModelPropertiesWidget::projectDBModelPropertiesWidget
Parameters
model
parent
Definition at line 32 of file projectdbmodelpropertieswidget.cpp.
References setModel(), and ui.
~ProjectDBModelPropertiesWidget()
ProjectDBModelPropertiesWidget::~ProjectDBModelPropertiesWidget ()
projectDBModelPropertiesWidget::~projectDBModelPropertiesWidget
Definition at line 43 of file projectdbmodelpropertieswidget.cpp.
References ui.
Member Function Documentation
on_m_edit_query_pb_clicked
void ProjectDBModelPropertiesWidget::on_m_edit_query_pb_clicked () private slot
projectDBModelPropertiesWidget::on_m_edit_query_pb_clicked
Definition at line 60 of file projectdbmodelpropertieswidget.cpp.
References QET::Icons::Cancel, ProjectDBModel::identifier(), m_model, SummaryQueryWidget::queryStr(), ElementQueryWidget::queryStr(), ProjectDBModel::queryString(), SummaryQueryWidget::setQuery(), ElementQueryWidget::setQuery(), and ProjectDBModel::setQuery().
on_m_refresh_pb_clicked
void ProjectDBModelPropertiesWidget::on_m_refresh_pb_clicked () private slot
Definition at line 96 of file projectdbmodelpropertieswidget.cpp.
References QETProject::dataBase(), m_model, ProjectDBModel::project(), and projectDataBase::updateDB().
setModel()
void ProjectDBModelPropertiesWidget::setModel (ProjectDBModel * model)
projectDBModelPropertiesWidget::setModel
Parameters
model
Definition at line 51 of file projectdbmodelpropertieswidget.cpp.
References m_model, and ui.
Referenced by ProjectDBModelPropertiesWidget().
Member Data Documentation
m_model
ProjectDBModel* ProjectDBModelPropertiesWidget::m_model = nullptr private
Definition at line 49 of file projectdbmodelpropertieswidget.h.
Referenced by on_m_edit_query_pb_clicked(), on_m_refresh_pb_clicked(), and setModel().
ui
Ui::ProjectDBModelPropertiesWidget* ProjectDBModelPropertiesWidget::ui private
Definition at line 48 of file projectdbmodelpropertieswidget.h.
Referenced by ProjectDBModelPropertiesWidget(), setModel(), and ~ProjectDBModelPropertiesWidget().
The documentation for this class was generated from the following files:
projectdbmodelpropertieswidget.h
projectdbmodelpropertieswidget.cpp