QElectroTech: NameListWidget Class Reference
NameListWidget Class Reference
The NameListWidget class Provide a widget for let user define localized string;.
#include <namelistwidget.h>
Public Member Functions
NameListWidget (QWidget *parent=nullptr)
~NameListWidget ()
void addLine ()
NameListWidget::addLine Add a new line to the name list widget.
void setNames (const NamesList &name_list)
NameListWidget::setNames Set the current names of this dialog from name_list.
NamesList names () const
NameListWidget::names.
void setReadOnly (bool ro)
NameListWidget::setReadOnly Set this dialog to read only or not.
bool isEmpty () const
NameListWidget::isEmpty.
void setClipboardValue (QHash< QString, QString > value)
Private Slots
void on_m_clipboard_cb_activated (int index)
Private Member Functions
void clean ()
NameListWidget::clean Clean the lists of names by removing the emtpy lines.
Private Attributes
Ui::NameListWidget * ui
bool m_read_only = false
Detailed Description
The NameListWidget class Provide a widget for let user define localized string;.
Definition at line 32 of file namelistwidget.h.
Constructor & Destructor Documentation
NameListWidget()
NameListWidget::NameListWidget (QWidget * parent = nullptr) explicit
Definition at line 24 of file namelistwidget.cpp.
References addLine(), and ui.
~NameListWidget()
NameListWidget::~NameListWidget ()
Definition at line 33 of file namelistwidget.cpp.
References ui.
Member Function Documentation
addLine()
void NameListWidget::addLine ()
NameListWidget::addLine Add a new line to the name list widget.
Definition at line 42 of file namelistwidget.cpp.
References clean(), m_read_only, and ui.
Referenced by NameListWidget().
clean()
void NameListWidget::clean () private
NameListWidget::clean Clean the lists of names by removing the emtpy lines.
Definition at line 150 of file namelistwidget.cpp.
References ui.
Referenced by addLine().
isEmpty()
bool NameListWidget::isEmpty () const
NameListWidget::isEmpty.
Returns
true if empty. An empty dialog, is a dialog without any edited lang.
Definition at line 125 of file namelistwidget.cpp.
References NamesList::isEmpty(), and names().
Referenced by ElementsCategoryEditor::acceptCreation(), ElementsCategoryEditor::acceptUpdate(), ElementScene::slot_editNames(), and NewElementWizard::validateCurrentPage().
names()
NamesList NameListWidget::names () const
NameListWidget::names.
Returns
the current name list edited by this dialog
Definition at line 82 of file namelistwidget.cpp.
References NamesList::addName(), and ui.
Referenced by ElementsCategoryEditor::acceptCreation(), ElementsCategoryEditor::acceptUpdate(), TitleBlockTemplateCellWidget::editTranslatableValue(), isEmpty(), and ElementScene::slot_editNames().
on_m_clipboard_cb_activated
void NameListWidget::on_m_clipboard_cb_activated (int index) private slot
Definition at line 163 of file namelistwidget.cpp.
References ui.
setClipboardValue()
void NameListWidget::setClipboardValue (QHash< QString, QString > value)
Definition at line 129 of file namelistwidget.cpp.
References ui.
Referenced by TitleBlockTemplateCellWidget::editTranslatableValue().
setNames()
void NameListWidget::setNames (const NamesList & name_list)
NameListWidget::setNames Set the current names of this dialog from name_list.
Parameters
name_list
Definition at line 60 of file namelistwidget.cpp.
References NamesList::langs(), m_read_only, and ui.
Referenced by TitleBlockTemplateCellWidget::editTranslatableValue(), and ElementScene::slot_editNames().
setReadOnly()
void NameListWidget::setReadOnly (bool ro)
NameListWidget::setReadOnly Set this dialog to read only or not.
Parameters
ro
Definition at line 104 of file namelistwidget.cpp.
References m_read_only, QET::Icons::ro, and ui.
Referenced by ElementScene::slot_editNames().
Member Data Documentation
m_read_only
bool NameListWidget::m_read_only = false private
Definition at line 55 of file namelistwidget.h.
Referenced by addLine(), setNames(), and setReadOnly().
ui
Ui::NameListWidget* NameListWidget::ui private
Definition at line 54 of file namelistwidget.h.
Referenced by addLine(), clean(), NameListWidget(), names(), on_m_clipboard_cb_activated(), setClipboardValue(), setNames(), setReadOnly(), and ~NameListWidget().
The documentation for this class was generated from the following files:
namelistwidget.h
namelistwidget.cpp