QElectroTech: CustomElementGraphicPart Class Reference
CustomElementGraphicPart Class Reference abstract
The CustomElementGraphicPart class This class is the base for all home-made primitive like line, rectangle, ellipse etc.... It provides methods and enums to manage style attributes available for primitive (color, pen style, etc...)
#include <customelementgraphicpart.h>
Public Types
enum LineStyle { NormalStyle, DashedStyle, DottedStyle, DashdottedStyle }
enum LineWeight {
NoneWeight, ThinWeight, NormalWeight, UltraWeight,
BigWeight
}
enum Filling {
NoneFilling, BlackFilling, WhiteFilling, GreenFilling,
RedFilling, BlueFilling, GrayFilling, BrunFilling,
YellowFilling, CyanFilling, MagentaFilling, LightgrayFilling,
OrangeFilling, PurpleFilling, HTMLPinkPinkFilling, HTMLPinkLightPinkFilling,
HTMLPinkHotPinkFilling, HTMLPinkDeepPinkFilling, HTMLPinkPaleVioletRedFilling, HTMLPinkMediumVioletRedFilling,
HTMLRedLightSalmonFilling, HTMLRedSalmonFilling, HTMLRedDarkSalmonFilling, HTMLRedLightCoralFilling,
HTMLRedIndianRedFilling, HTMLRedCrimsonFilling, HTMLRedFirebrickFilling, HTMLRedDarkRedFilling,
HTMLRedRedFilling, HTMLOrangeOrangeRedFilling, HTMLOrangeTomatoFilling, HTMLOrangeCoralFilling,
HTMLOrangeDarkOrangeFilling, HTMLOrangeOrangeFilling, HTMLYellowYellowFilling, HTMLYellowLightYellowFilling,
HTMLYellowLemonChiffonFilling, HTMLYellowLightGoldenrodYellowFilling, HTMLYellowPapayaWhipFilling, HTMLYellowMoccasinFilling,
HTMLYellowPeachPuffFilling, HTMLYellowPaleGoldenrodFilling, HTMLYellowKhakiFilling, HTMLYellowDarkKhakiFilling,
HTMLYellowGoldFilling, HTMLBrownCornsilkFilling, HTMLBrownBlanchedAlmondFilling, HTMLBrownBisqueFilling,
HTMLBrownNavajoWhiteFilling, HTMLBrownWheatFilling, HTMLBrownBurlywoodFilling, HTMLBrownTanFilling,
HTMLBrownRosyBrownFilling, HTMLBrownSandyBrownFilling, HTMLBrownGoldenrodFilling, HTMLBrownDarkGoldenrodFilling,
HTMLBrownPeruFilling, HTMLBrownChocolateFilling, HTMLBrownSaddleBrownFilling, HTMLBrownSiennaFilling,
HTMLBrownBrownFilling, HTMLBrownMaroonFilling, HTMLGreenDarkOliveGreenFilling, HTMLGreenOliveFilling,
HTMLGreenOliveDrabFilling, HTMLGreenYellowGreenFilling, HTMLGreenLimeGreenFilling, HTMLGreenLimeFilling,
HTMLGreenLawnGreenFilling, HTMLGreenChartreuseFilling, HTMLGreenGreenYellowFilling, HTMLGreenSpringGreenFilling,
HTMLGreenMediumSpringGreenFilling, HTMLGreenLightGreenFilling, HTMLGreenPaleGreenFilling, HTMLGreenDarkSeaGreenFilling,
HTMLGreenMediumAquamarineFilling, HTMLGreenMediumSeaGreenFilling, HTMLGreenSeaGreenFilling, HTMLGreenForestGreenFilling,
HTMLGreenGreenFilling, HTMLGreenDarkGreenFilling, HTMLCyanAquaFilling, HTMLCyanCyanFilling,
HTMLCyanLightCyanFilling, HTMLCyanPaleTurquoiseFilling, HTMLCyanAquamarineFilling, HTMLCyanTurquoiseFilling,
HTMLCyanMediumTurquoiseFilling, HTMLCyanDarkTurquoiseFilling, HTMLCyanLightSeaGreenFilling, HTMLCyanCadetBlueFilling,
HTMLCyanDarkCyanFilling, HTMLCyanTealFilling, HTMLBlueLightSteelBlueFilling, HTMLBluePowderBlueFilling,
HTMLBlueLightBlueFilling, HTMLBlueSkyBlueFilling, HTMLBlueLightSkyBlueFilling, HTMLBlueDeepSkyBlueFilling,
HTMLBlueDodgerBlueFilling, HTMLBlueCornflowerBlueFilling, HTMLBlueSteelBlueFilling, HTMLBlueRoyalBlueFilling,
HTMLBlueBlueFilling, HTMLBlueMediumBlueFilling, HTMLBlueDarkBlueFilling, HTMLBlueNavyFilling,
HTMLBlueMidnightBlueFilling, HTMLPurpleLavenderFilling, HTMLPurpleThistleFilling, HTMLPurplePlumFilling,
HTMLPurpleVioletFilling, HTMLPurpleOrchidFilling, HTMLPurpleFuchsiaFilling, HTMLPurpleMagentaFilling,
HTMLPurpleMediumOrchidFilling, HTMLPurpleMediumPurpleFilling, HTMLPurpleBlueVioletFilling, HTMLPurpleDarkVioletFilling,
HTMLPurpleDarkOrchidFilling, HTMLPurpleDarkMagentaFilling, HTMLPurplePurpleFilling, HTMLPurpleIndigoFilling,
HTMLPurpleDarkSlateBlueFilling, HTMLPurpleSlateBlueFilling, HTMLPurpleMediumSlateBlueFilling, HTMLWhiteWhiteFilling,
HTMLWhiteSnowFilling, HTMLWhiteHoneydewFilling, HTMLWhiteMintCreamFilling, HTMLWhiteAzureFilling,
HTMLWhiteAliceBlueFilling, HTMLWhiteGhostWhiteFilling, HTMLWhiteWhiteSmokeFilling, HTMLWhiteSeashellFilling,
HTMLWhiteBeigeFilling, HTMLWhiteOldLaceFilling, HTMLWhiteFloralWhiteFilling, HTMLWhiteIvoryFilling,
HTMLWhiteAntiqueWhiteFilling, HTMLWhiteLinenFilling, HTMLWhiteLavenderBlushFilling, HTMLWhiteMistyRoseFilling,
HTMLGrayGainsboroFilling, HTMLGrayLightGrayFilling, HTMLGraySilverFilling, HTMLGrayDarkGrayFilling,
HTMLGrayGrayFilling, HTMLGrayDimGrayFilling, HTMLGrayLightSlateGrayFilling, HTMLGraySlateGrayFilling,
HTMLGrayDarkSlateGrayFilling, HTMLGrayBlackFilling, HorFilling, VerFilling,
BdiagFilling, FdiagFilling
}
enum Color {
BlackColor, WhiteColor, GreenColor, RedColor,
BlueColor, GrayColor, BrunColor, YellowColor,
CyanColor, MagentaColor, LightgrayColor, OrangeColor,
PurpleColor, HTMLPinkPinkColor, HTMLPinkLightPinkColor, HTMLPinkHotPinkColor,
HTMLPinkDeepPinkColor, HTMLPinkPaleVioletRedColor, HTMLPinkMediumVioletRedColor, HTMLRedLightSalmonColor,
HTMLRedSalmonColor, HTMLRedDarkSalmonColor, HTMLRedLightCoralColor, HTMLRedIndianRedColor,
HTMLRedCrimsonColor, HTMLRedFirebrickColor, HTMLRedDarkRedColor, HTMLRedRedColor,
HTMLOrangeOrangeRedColor, HTMLOrangeTomatoColor, HTMLOrangeCoralColor, HTMLOrangeDarkOrangeColor,
HTMLOrangeOrangeColor, HTMLYellowYellowColor, HTMLYellowLightYellowColor, HTMLYellowLemonChiffonColor,
HTMLYellowLightGoldenrodYellowColor, HTMLYellowPapayaWhipColor, HTMLYellowMoccasinColor, HTMLYellowPeachPuffColor,
HTMLYellowPaleGoldenrodColor, HTMLYellowKhakiColor, HTMLYellowDarkKhakiColor, HTMLYellowGoldColor,
HTMLBrownCornsilkColor, HTMLBrownBlanchedAlmondColor, HTMLBrownBisqueColor, HTMLBrownNavajoWhiteColor,
HTMLBrownWheatColor, HTMLBrownBurlywoodColor, HTMLBrownTanColor, HTMLBrownRosyBrownColor,
HTMLBrownSandyBrownColor, HTMLBrownGoldenrodColor, HTMLBrownDarkGoldenrodColor, HTMLBrownPeruColor,
HTMLBrownChocolateColor, HTMLBrownSaddleBrownColor, HTMLBrownSiennaColor, HTMLBrownBrownColor,
HTMLBrownMaroonColor, HTMLGreenDarkOliveGreenColor, HTMLGreenOliveColor, HTMLGreenOliveDrabColor,
HTMLGreenYellowGreenColor, HTMLGreenLimeGreenColor, HTMLGreenLimeColor, HTMLGreenLawnGreenColor,
HTMLGreenChartreuseColor, HTMLGreenGreenYellowColor, HTMLGreenSpringGreenColor, HTMLGreenMediumSpringGreenColor,
HTMLGreenLightGreenColor, HTMLGreenPaleGreenColor, HTMLGreenDarkSeaGreenColor, HTMLGreenMediumAquamarineColor,
HTMLGreenMediumSeaGreenColor, HTMLGreenSeaGreenColor, HTMLGreenForestGreenColor, HTMLGreenGreenColor,
HTMLGreenDarkGreenColor, HTMLCyanAquaColor, HTMLCyanCyanColor, HTMLCyanLightCyanColor,
HTMLCyanPaleTurquoiseColor, HTMLCyanAquamarineColor, HTMLCyanTurquoiseColor, HTMLCyanMediumTurquoiseColor,
HTMLCyanDarkTurquoiseColor, HTMLCyanLightSeaGreenColor, HTMLCyanCadetBlueColor, HTMLCyanDarkCyanColor,
HTMLCyanTealColor, HTMLBlueLightSteelBlueColor, HTMLBluePowderBlueColor, HTMLBlueLightBlueColor,
HTMLBlueSkyBlueColor, HTMLBlueLightSkyBlueColor, HTMLBlueDeepSkyBlueColor, HTMLBlueDodgerBlueColor,
HTMLBlueCornflowerBlueColor, HTMLBlueSteelBlueColor, HTMLBlueRoyalBlueColor, HTMLBlueBlueColor,
HTMLBlueMediumBlueColor, HTMLBlueDarkBlueColor, HTMLBlueNavyColor, HTMLBlueMidnightBlueColor,
HTMLPurpleLavenderColor, HTMLPurpleThistleColor, HTMLPurplePlumColor, HTMLPurpleVioletColor,
HTMLPurpleOrchidColor, HTMLPurpleFuchsiaColor, HTMLPurpleMagentaColor, HTMLPurpleMediumOrchidColor,
HTMLPurpleMediumPurpleColor, HTMLPurpleBlueVioletColor, HTMLPurpleDarkVioletColor, HTMLPurpleDarkOrchidColor,
HTMLPurpleDarkMagentaColor, HTMLPurplePurpleColor, HTMLPurpleIndigoColor, HTMLPurpleDarkSlateBlueColor,
HTMLPurpleSlateBlueColor, HTMLPurpleMediumSlateBlueColor, HTMLWhiteWhiteColor, HTMLWhiteSnowColor,
HTMLWhiteHoneydewColor, HTMLWhiteMintCreamColor, HTMLWhiteAzureColor, HTMLWhiteAliceBlueColor,
HTMLWhiteGhostWhiteColor, HTMLWhiteWhiteSmokeColor, HTMLWhiteSeashellColor, HTMLWhiteBeigeColor,
HTMLWhiteOldLaceColor, HTMLWhiteFloralWhiteColor, HTMLWhiteIvoryColor, HTMLWhiteAntiqueWhiteColor,
HTMLWhiteLinenColor, HTMLWhiteLavenderBlushColor, HTMLWhiteMistyRoseColor, HTMLGrayGainsboroColor,
HTMLGrayLightGrayColor, HTMLGraySilverColor, HTMLGrayDarkGrayColor, HTMLGrayGrayColor,
HTMLGrayDimGrayColor, HTMLGrayLightSlateGrayColor, HTMLGraySlateGrayColor, HTMLGrayDarkSlateGrayColor,
HTMLGrayBlackColor, NoneColor
}
Public Member Functions
CustomElementGraphicPart (QETElementEditor *editor, QGraphicsItem *parent=nullptr)
CustomElementGraphicPart::CustomElementGraphicPart Default constructor. By default, item is selectable, send geometry change (Qt > 4.6), accept mouse left button and accept hover event.
~CustomElementGraphicPart () override
CustomElementGraphicPart::~CustomElementGraphicPart Destructor.
LineStyle lineStyle () const
void setLineStyle (const LineStyle ls)
CustomElementGraphicPart::setLineStyle Set line style to ls.
LineWeight lineWeight () const
void setLineWeight (const LineWeight lw)
CustomElementGraphicPart::setLineWeight Set line weight to lw.
qreal penWeight () const
CustomElementGraphicPart::penWeight.
Filling filling () const
void setFilling (const Filling f)
CustomElementGraphicPart::setFilling Set filling to f.
Color color () const
void setColor (const Color c)
CustomElementGraphicPart::setColor Set color to c.
bool antialiased () const
void setAntialiased (const bool b)
CustomElementGraphicPart::setAntialiased Set antialias to b.
void setProperty (const char *name, const QVariant &value) override
QVariant property (const char *name) const override
virtual QPainterPath shadowShape () const =0
virtual void setHandlerColor (QPointF, const QColor &)
virtual void resetAllHandlerColor ()
Public Member Functions inherited from CustomElementPart
CustomElementPart (QETElementEditor *editor)
CustomElementPart Constructor.
virtual ~CustomElementPart ()
~CustomElementPart Destructor
virtual void fromXml (const QDomElement &)=0
virtual const QDomElement toXml (QDomDocument &) const =0
virtual bool isUseless () const =0
virtual QRectF sceneGeometricRect () const =0
virtual void startUserTransformation (const QRectF &)=0
virtual void handleUserTransformation (const QRectF &, const QRectF &)=0
virtual QETElementEditor * elementEditor () const
virtual void updateCurrentPartEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString name () const =0
virtual QString xmlName () const =0
virtual QGraphicsItem * toItem ()
virtual QET::ScalingMethod preferredScalingMethod () const
Static Public Member Functions
static void drawCross (const QPointF &center, QPainter *painter)
CustomElementGraphicPart::drawCross Draw a cross at pos center.
Protected Member Functions
void stylesToXml (QDomElement &) const
CustomElementGraphicPart::stylesToXml Write the curent style to xml element. The style are stored like this: name-of-style:value;name-of-style:value Each style separate by ; and name-style/value are separate by :
void stylesFromXml (const QDomElement &)
CustomElementGraphicPart::stylesFromXml Read the style used by this, from a xml element.
void resetStyles ()
CustomElementGraphicPart::resetStyles Reset the curent style to default, same style of default constructor.
void applyStylesToQPainter (QPainter &) const
CustomElementGraphicPart::applyStylesToQPainter Apply the current style to the QPainter.
void drawShadowShape (QPainter *painter)
CustomElementGraphicPart::drawShadowShape Draw a transparent blue shadow arround the shape of this item. The QPainterPathStroker used to draw shadows have a width of SHADOWS_HEIGHT Be carefull if penWeight of this item is to 0 the outline of strock is bigger of 0.5.
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
CustomElementGraphicPart::itemChange Reimplemented from QGraphicsObject. If the item position change call updateCurrentPartEditor() the change is always send to QGraphicsObject.
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
CustomElementGraphicPart::hoverEnterEvent Reimplemented from QGraphicsObject. Set m_hovered to true.
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
CustomElementGraphicPart::hoverLeaveEvent Reimplemented from QGraphicsObject. Set m_hovered to false.
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions inherited from CustomElementPart
QList< QPointF > mapPoints (const QRectF &, const QRectF &, const QList< QPointF > &)
Protected Attributes
bool m_hovered
Properties
LineStyle line_style
LineWeight line_weight
Filling filling
Color color
bool antialias
Private Attributes
LineStyle _linestyle
LineWeight _lineweight
Filling _filling
Color _color
bool _antialiased
QPointF m_origin_pos
Detailed Description
The CustomElementGraphicPart class This class is the base for all home-made primitive like line, rectangle, ellipse etc.... It provides methods and enums to manage style attributes available for primitive (color, pen style, etc...)
Definition at line 35 of file customelementgraphicpart.h.
Member Enumeration Documentation
Color
enum CustomElementGraphicPart::Color
Enumerator
BlackColor
WhiteColor
GreenColor
RedColor
BlueColor
GrayColor
BrunColor
YellowColor
CyanColor
MagentaColor
LightgrayColor
OrangeColor
PurpleColor
HTMLPinkPinkColor
HTMLPinkLightPinkColor
HTMLPinkHotPinkColor
HTMLPinkDeepPinkColor
HTMLPinkPaleVioletRedColor
HTMLPinkMediumVioletRedColor
HTMLRedLightSalmonColor
HTMLRedSalmonColor
HTMLRedDarkSalmonColor
HTMLRedLightCoralColor
HTMLRedIndianRedColor
HTMLRedCrimsonColor
HTMLRedFirebrickColor
HTMLRedDarkRedColor
HTMLRedRedColor
HTMLOrangeOrangeRedColor
HTMLOrangeTomatoColor
HTMLOrangeCoralColor
HTMLOrangeDarkOrangeColor
HTMLOrangeOrangeColor
HTMLYellowYellowColor
HTMLYellowLightYellowColor
HTMLYellowLemonChiffonColor
HTMLYellowLightGoldenrodYellowColor
HTMLYellowPapayaWhipColor
HTMLYellowMoccasinColor
HTMLYellowPeachPuffColor
HTMLYellowPaleGoldenrodColor
HTMLYellowKhakiColor
HTMLYellowDarkKhakiColor
HTMLYellowGoldColor
HTMLBrownCornsilkColor
HTMLBrownBlanchedAlmondColor
HTMLBrownBisqueColor
HTMLBrownNavajoWhiteColor
HTMLBrownWheatColor
HTMLBrownBurlywoodColor
HTMLBrownTanColor
HTMLBrownRosyBrownColor
HTMLBrownSandyBrownColor
HTMLBrownGoldenrodColor
HTMLBrownDarkGoldenrodColor
HTMLBrownPeruColor
HTMLBrownChocolateColor
HTMLBrownSaddleBrownColor
HTMLBrownSiennaColor
HTMLBrownBrownColor
HTMLBrownMaroonColor
HTMLGreenDarkOliveGreenColor
HTMLGreenOliveColor
HTMLGreenOliveDrabColor
HTMLGreenYellowGreenColor
HTMLGreenLimeGreenColor
HTMLGreenLimeColor
HTMLGreenLawnGreenColor
HTMLGreenChartreuseColor
HTMLGreenGreenYellowColor
HTMLGreenSpringGreenColor
HTMLGreenMediumSpringGreenColor
HTMLGreenLightGreenColor
HTMLGreenPaleGreenColor
HTMLGreenDarkSeaGreenColor
HTMLGreenMediumAquamarineColor
HTMLGreenMediumSeaGreenColor
HTMLGreenSeaGreenColor
HTMLGreenForestGreenColor
HTMLGreenGreenColor
HTMLGreenDarkGreenColor
HTMLCyanAquaColor
HTMLCyanCyanColor
HTMLCyanLightCyanColor
HTMLCyanPaleTurquoiseColor
HTMLCyanAquamarineColor
HTMLCyanTurquoiseColor
HTMLCyanMediumTurquoiseColor
HTMLCyanDarkTurquoiseColor
HTMLCyanLightSeaGreenColor
HTMLCyanCadetBlueColor
HTMLCyanDarkCyanColor
HTMLCyanTealColor
HTMLBlueLightSteelBlueColor
HTMLBluePowderBlueColor
HTMLBlueLightBlueColor
HTMLBlueSkyBlueColor
HTMLBlueLightSkyBlueColor
HTMLBlueDeepSkyBlueColor
HTMLBlueDodgerBlueColor
HTMLBlueCornflowerBlueColor
HTMLBlueSteelBlueColor
HTMLBlueRoyalBlueColor
HTMLBlueBlueColor
HTMLBlueMediumBlueColor
HTMLBlueDarkBlueColor
HTMLBlueNavyColor
HTMLBlueMidnightBlueColor
HTMLPurpleLavenderColor
HTMLPurpleThistleColor
HTMLPurplePlumColor
HTMLPurpleVioletColor
HTMLPurpleOrchidColor
HTMLPurpleFuchsiaColor
HTMLPurpleMagentaColor
HTMLPurpleMediumOrchidColor
HTMLPurpleMediumPurpleColor
HTMLPurpleBlueVioletColor
HTMLPurpleDarkVioletColor
HTMLPurpleDarkOrchidColor
HTMLPurpleDarkMagentaColor
HTMLPurplePurpleColor
HTMLPurpleIndigoColor
HTMLPurpleDarkSlateBlueColor
HTMLPurpleSlateBlueColor
HTMLPurpleMediumSlateBlueColor
HTMLWhiteWhiteColor
HTMLWhiteSnowColor
HTMLWhiteHoneydewColor
HTMLWhiteMintCreamColor
HTMLWhiteAzureColor
HTMLWhiteAliceBlueColor
HTMLWhiteGhostWhiteColor
HTMLWhiteWhiteSmokeColor
HTMLWhiteSeashellColor
HTMLWhiteBeigeColor
HTMLWhiteOldLaceColor
HTMLWhiteFloralWhiteColor
HTMLWhiteIvoryColor
HTMLWhiteAntiqueWhiteColor
HTMLWhiteLinenColor
HTMLWhiteLavenderBlushColor
HTMLWhiteMistyRoseColor
HTMLGrayGainsboroColor
HTMLGrayLightGrayColor
HTMLGraySilverColor
HTMLGrayDarkGrayColor
HTMLGrayGrayColor
HTMLGrayDimGrayColor
HTMLGrayLightSlateGrayColor
HTMLGraySlateGrayColor
HTMLGrayDarkSlateGrayColor
HTMLGrayBlackColor
NoneColor
Definition at line 184 of file customelementgraphicpart.h.
Filling
enum CustomElementGraphicPart::Filling
Enumerator
NoneFilling
BlackFilling
WhiteFilling
GreenFilling
RedFilling
BlueFilling
GrayFilling
BrunFilling
YellowFilling
CyanFilling
MagentaFilling
LightgrayFilling
OrangeFilling
PurpleFilling
HTMLPinkPinkFilling
HTMLPinkLightPinkFilling
HTMLPinkHotPinkFilling
HTMLPinkDeepPinkFilling
HTMLPinkPaleVioletRedFilling
HTMLPinkMediumVioletRedFilling
HTMLRedLightSalmonFilling
HTMLRedSalmonFilling
HTMLRedDarkSalmonFilling
HTMLRedLightCoralFilling
HTMLRedIndianRedFilling
HTMLRedCrimsonFilling
HTMLRedFirebrickFilling
HTMLRedDarkRedFilling
HTMLRedRedFilling
HTMLOrangeOrangeRedFilling
HTMLOrangeTomatoFilling
HTMLOrangeCoralFilling
HTMLOrangeDarkOrangeFilling
HTMLOrangeOrangeFilling
HTMLYellowYellowFilling
HTMLYellowLightYellowFilling
HTMLYellowLemonChiffonFilling
HTMLYellowLightGoldenrodYellowFilling
HTMLYellowPapayaWhipFilling
HTMLYellowMoccasinFilling
HTMLYellowPeachPuffFilling
HTMLYellowPaleGoldenrodFilling
HTMLYellowKhakiFilling
HTMLYellowDarkKhakiFilling
HTMLYellowGoldFilling
HTMLBrownCornsilkFilling
HTMLBrownBlanchedAlmondFilling
HTMLBrownBisqueFilling
HTMLBrownNavajoWhiteFilling
HTMLBrownWheatFilling
HTMLBrownBurlywoodFilling
HTMLBrownTanFilling
HTMLBrownRosyBrownFilling
HTMLBrownSandyBrownFilling
HTMLBrownGoldenrodFilling
HTMLBrownDarkGoldenrodFilling
HTMLBrownPeruFilling
HTMLBrownChocolateFilling
HTMLBrownSaddleBrownFilling
HTMLBrownSiennaFilling
HTMLBrownBrownFilling
HTMLBrownMaroonFilling
HTMLGreenDarkOliveGreenFilling
HTMLGreenOliveFilling
HTMLGreenOliveDrabFilling
HTMLGreenYellowGreenFilling
HTMLGreenLimeGreenFilling
HTMLGreenLimeFilling
HTMLGreenLawnGreenFilling
HTMLGreenChartreuseFilling
HTMLGreenGreenYellowFilling
HTMLGreenSpringGreenFilling
HTMLGreenMediumSpringGreenFilling
HTMLGreenLightGreenFilling
HTMLGreenPaleGreenFilling
HTMLGreenDarkSeaGreenFilling
HTMLGreenMediumAquamarineFilling
HTMLGreenMediumSeaGreenFilling
HTMLGreenSeaGreenFilling
HTMLGreenForestGreenFilling
HTMLGreenGreenFilling
HTMLGreenDarkGreenFilling
HTMLCyanAquaFilling
HTMLCyanCyanFilling
HTMLCyanLightCyanFilling
HTMLCyanPaleTurquoiseFilling
HTMLCyanAquamarineFilling
HTMLCyanTurquoiseFilling
HTMLCyanMediumTurquoiseFilling
HTMLCyanDarkTurquoiseFilling
HTMLCyanLightSeaGreenFilling
HTMLCyanCadetBlueFilling
HTMLCyanDarkCyanFilling
HTMLCyanTealFilling
HTMLBlueLightSteelBlueFilling
HTMLBluePowderBlueFilling
HTMLBlueLightBlueFilling
HTMLBlueSkyBlueFilling
HTMLBlueLightSkyBlueFilling
HTMLBlueDeepSkyBlueFilling
HTMLBlueDodgerBlueFilling
HTMLBlueCornflowerBlueFilling
HTMLBlueSteelBlueFilling
HTMLBlueRoyalBlueFilling
HTMLBlueBlueFilling
HTMLBlueMediumBlueFilling
HTMLBlueDarkBlueFilling
HTMLBlueNavyFilling
HTMLBlueMidnightBlueFilling
HTMLPurpleLavenderFilling
HTMLPurpleThistleFilling
HTMLPurplePlumFilling
HTMLPurpleVioletFilling
HTMLPurpleOrchidFilling
HTMLPurpleFuchsiaFilling
HTMLPurpleMagentaFilling
HTMLPurpleMediumOrchidFilling
HTMLPurpleMediumPurpleFilling
HTMLPurpleBlueVioletFilling
HTMLPurpleDarkVioletFilling
HTMLPurpleDarkOrchidFilling
HTMLPurpleDarkMagentaFilling
HTMLPurplePurpleFilling
HTMLPurpleIndigoFilling
HTMLPurpleDarkSlateBlueFilling
HTMLPurpleSlateBlueFilling
HTMLPurpleMediumSlateBlueFilling
HTMLWhiteWhiteFilling
HTMLWhiteSnowFilling
HTMLWhiteHoneydewFilling
HTMLWhiteMintCreamFilling
HTMLWhiteAzureFilling
HTMLWhiteAliceBlueFilling
HTMLWhiteGhostWhiteFilling
HTMLWhiteWhiteSmokeFilling
HTMLWhiteSeashellFilling
HTMLWhiteBeigeFilling
HTMLWhiteOldLaceFilling
HTMLWhiteFloralWhiteFilling
HTMLWhiteIvoryFilling
HTMLWhiteAntiqueWhiteFilling
HTMLWhiteLinenFilling
HTMLWhiteLavenderBlushFilling
HTMLWhiteMistyRoseFilling
HTMLGrayGainsboroFilling
HTMLGrayLightGrayFilling
HTMLGraySilverFilling
HTMLGrayDarkGrayFilling
HTMLGrayGrayFilling
HTMLGrayDimGrayFilling
HTMLGrayLightSlateGrayFilling
HTMLGraySlateGrayFilling
HTMLGrayDarkSlateGrayFilling
HTMLGrayBlackFilling
HorFilling
VerFilling
BdiagFilling
FdiagFilling
Definition at line 64 of file customelementgraphicpart.h.
LineStyle
enum CustomElementGraphicPart::LineStyle
Enumerator
NormalStyle
DashedStyle
DottedStyle
DashdottedStyle
Definition at line 49 of file customelementgraphicpart.h.
LineWeight
enum CustomElementGraphicPart::LineWeight
Enumerator
NoneWeight
ThinWeight
NormalWeight
UltraWeight
BigWeight
Definition at line 56 of file customelementgraphicpart.h.
Constructor & Destructor Documentation
CustomElementGraphicPart()
CustomElementGraphicPart::CustomElementGraphicPart (QETElementEditor * editor, QGraphicsItem * parent = nullptr)
CustomElementGraphicPart::CustomElementGraphicPart Default constructor. By default, item is selectable, send geometry change (Qt > 4.6), accept mouse left button and accept hover event.
Parameters
editor QETElement editor that belong this.
parent
Definition at line 30 of file customelementgraphicpart.cpp.
~CustomElementGraphicPart()
CustomElementGraphicPart::~CustomElementGraphicPart () override
CustomElementGraphicPart::~CustomElementGraphicPart Destructor.
Definition at line 51 of file customelementgraphicpart.cpp.
Member Function Documentation
antialiased()
bool CustomElementGraphicPart::antialiased () const inline
Definition at line 288 of file customelementgraphicpart.h.
References _antialiased.
applyStylesToQPainter()
void CustomElementGraphicPart::applyStylesToQPainter (QPainter & painter) const protected
CustomElementGraphicPart::applyStylesToQPainter Apply the current style to the QPainter.
Parameters
painter
Definition at line 885 of file customelementgraphicpart.cpp.
References _antialiased, _color, _filling, _linestyle, _lineweight, BdiagFilling, BigWeight, BlackColor, BlackFilling, BlueColor, BlueFilling, BrunColor, BrunFilling, CyanColor, CyanFilling, DashdottedStyle, DashedStyle, DottedStyle, FdiagFilling, GrayColor, GrayFilling, GreenColor, GreenFilling, HorFilling, HTMLBlueBlueColor, HTMLBlueBlueFilling, HTMLBlueCornflowerBlueColor, HTMLBlueCornflowerBlueFilling, HTMLBlueDarkBlueColor, HTMLBlueDarkBlueFilling, HTMLBlueDeepSkyBlueColor, HTMLBlueDeepSkyBlueFilling, HTMLBlueDodgerBlueColor, HTMLBlueDodgerBlueFilling, HTMLBlueLightBlueColor, HTMLBlueLightBlueFilling, HTMLBlueLightSkyBlueColor, HTMLBlueLightSkyBlueFilling, HTMLBlueLightSteelBlueColor, HTMLBlueLightSteelBlueFilling, HTMLBlueMediumBlueColor, HTMLBlueMediumBlueFilling, HTMLBlueMidnightBlueColor, HTMLBlueMidnightBlueFilling, HTMLBlueNavyColor, HTMLBlueNavyFilling, HTMLBluePowderBlueColor, HTMLBluePowderBlueFilling, HTMLBlueRoyalBlueColor, HTMLBlueRoyalBlueFilling, HTMLBlueSkyBlueColor, HTMLBlueSkyBlueFilling, HTMLBlueSteelBlueColor, HTMLBlueSteelBlueFilling, HTMLBrownBisqueColor, HTMLBrownBisqueFilling, HTMLBrownBlanchedAlmondColor, HTMLBrownBlanchedAlmondFilling, HTMLBrownBrownColor, HTMLBrownBrownFilling, HTMLBrownBurlywoodColor, HTMLBrownBurlywoodFilling, HTMLBrownChocolateColor, HTMLBrownChocolateFilling, HTMLBrownCornsilkColor, HTMLBrownCornsilkFilling, HTMLBrownDarkGoldenrodColor, HTMLBrownDarkGoldenrodFilling, HTMLBrownGoldenrodColor, HTMLBrownGoldenrodFilling, HTMLBrownMaroonColor, HTMLBrownMaroonFilling, HTMLBrownNavajoWhiteColor, HTMLBrownNavajoWhiteFilling, HTMLBrownPeruColor, HTMLBrownPeruFilling, HTMLBrownRosyBrownColor, HTMLBrownRosyBrownFilling, HTMLBrownSaddleBrownColor, HTMLBrownSaddleBrownFilling, HTMLBrownSandyBrownColor, HTMLBrownSandyBrownFilling, HTMLBrownSiennaColor, HTMLBrownSiennaFilling, HTMLBrownTanColor, HTMLBrownTanFilling, HTMLBrownWheatColor, HTMLBrownWheatFilling, HTMLCyanAquaColor, HTMLCyanAquaFilling, HTMLCyanAquamarineColor, HTMLCyanAquamarineFilling, HTMLCyanCadetBlueColor, HTMLCyanCadetBlueFilling, HTMLCyanCyanColor, HTMLCyanCyanFilling, HTMLCyanDarkCyanColor, HTMLCyanDarkCyanFilling, HTMLCyanDarkTurquoiseColor, HTMLCyanDarkTurquoiseFilling, HTMLCyanLightCyanColor, HTMLCyanLightCyanFilling, HTMLCyanLightSeaGreenColor, HTMLCyanLightSeaGreenFilling, HTMLCyanMediumTurquoiseColor, HTMLCyanMediumTurquoiseFilling, HTMLCyanPaleTurquoiseColor, HTMLCyanPaleTurquoiseFilling, HTMLCyanTealColor, HTMLCyanTealFilling, HTMLCyanTurquoiseColor, HTMLCyanTurquoiseFilling, HTMLGrayBlackColor, HTMLGrayBlackFilling, HTMLGrayDarkGrayColor, HTMLGrayDarkGrayFilling, HTMLGrayDarkSlateGrayColor, HTMLGrayDarkSlateGrayFilling, HTMLGrayDimGrayColor, HTMLGrayDimGrayFilling, HTMLGrayGainsboroColor, HTMLGrayGainsboroFilling, HTMLGrayGrayColor, HTMLGrayGrayFilling, HTMLGrayLightGrayColor, HTMLGrayLightGrayFilling, HTMLGrayLightSlateGrayColor, HTMLGrayLightSlateGrayFilling, HTMLGraySilverColor, HTMLGraySilverFilling, HTMLGraySlateGrayColor, HTMLGraySlateGrayFilling, HTMLGreenChartreuseColor, HTMLGreenChartreuseFilling, HTMLGreenDarkGreenColor, HTMLGreenDarkGreenFilling, HTMLGreenDarkOliveGreenColor, HTMLGreenDarkOliveGreenFilling, HTMLGreenDarkSeaGreenColor, HTMLGreenDarkSeaGreenFilling, HTMLGreenForestGreenColor, HTMLGreenForestGreenFilling, HTMLGreenGreenColor, HTMLGreenGreenFilling, HTMLGreenGreenYellowColor, HTMLGreenGreenYellowFilling, HTMLGreenLawnGreenColor, HTMLGreenLawnGreenFilling, HTMLGreenLightGreenColor, HTMLGreenLightGreenFilling, HTMLGreenLimeColor, HTMLGreenLimeFilling, HTMLGreenLimeGreenColor, HTMLGreenLimeGreenFilling, HTMLGreenMediumAquamarineColor, HTMLGreenMediumAquamarineFilling, HTMLGreenMediumSeaGreenColor, HTMLGreenMediumSeaGreenFilling, HTMLGreenMediumSpringGreenColor, HTMLGreenMediumSpringGreenFilling, HTMLGreenOliveColor, HTMLGreenOliveDrabColor, HTMLGreenOliveDrabFilling, HTMLGreenOliveFilling, HTMLGreenPaleGreenColor, HTMLGreenPaleGreenFilling, HTMLGreenSeaGreenColor, HTMLGreenSeaGreenFilling, HTMLGreenSpringGreenColor, HTMLGreenSpringGreenFilling, HTMLGreenYellowGreenColor, HTMLGreenYellowGreenFilling, HTMLOrangeCoralColor, HTMLOrangeCoralFilling, HTMLOrangeDarkOrangeColor, HTMLOrangeDarkOrangeFilling, HTMLOrangeOrangeColor, HTMLOrangeOrangeFilling, HTMLOrangeOrangeRedColor, HTMLOrangeOrangeRedFilling, HTMLOrangeTomatoColor, HTMLOrangeTomatoFilling, HTMLPinkDeepPinkColor, HTMLPinkDeepPinkFilling, HTMLPinkHotPinkColor, HTMLPinkHotPinkFilling, HTMLPinkLightPinkColor, HTMLPinkLightPinkFilling, HTMLPinkMediumVioletRedColor, HTMLPinkMediumVioletRedFilling, HTMLPinkPaleVioletRedColor, HTMLPinkPaleVioletRedFilling, HTMLPinkPinkColor, HTMLPinkPinkFilling, HTMLPurpleBlueVioletColor, HTMLPurpleBlueVioletFilling, HTMLPurpleDarkMagentaColor, HTMLPurpleDarkMagentaFilling, HTMLPurpleDarkOrchidColor, HTMLPurpleDarkOrchidFilling, HTMLPurpleDarkSlateBlueColor, HTMLPurpleDarkSlateBlueFilling, HTMLPurpleDarkVioletColor, HTMLPurpleDarkVioletFilling, HTMLPurpleFuchsiaColor, HTMLPurpleFuchsiaFilling, HTMLPurpleIndigoColor, HTMLPurpleIndigoFilling, HTMLPurpleLavenderColor, HTMLPurpleLavenderFilling, HTMLPurpleMagentaColor, HTMLPurpleMagentaFilling, HTMLPurpleMediumOrchidColor, HTMLPurpleMediumOrchidFilling, HTMLPurpleMediumPurpleColor, HTMLPurpleMediumPurpleFilling, HTMLPurpleMediumSlateBlueColor, HTMLPurpleMediumSlateBlueFilling, HTMLPurpleOrchidColor, HTMLPurpleOrchidFilling, HTMLPurplePlumColor, HTMLPurplePlumFilling, HTMLPurplePurpleColor, HTMLPurplePurpleFilling, HTMLPurpleSlateBlueColor, HTMLPurpleSlateBlueFilling, HTMLPurpleThistleColor, HTMLPurpleThistleFilling, HTMLPurpleVioletColor, HTMLPurpleVioletFilling, HTMLRedCrimsonColor, HTMLRedCrimsonFilling, HTMLRedDarkRedColor, HTMLRedDarkRedFilling, HTMLRedDarkSalmonColor, HTMLRedDarkSalmonFilling, HTMLRedFirebrickColor, HTMLRedFirebrickFilling, HTMLRedIndianRedColor, HTMLRedIndianRedFilling, HTMLRedLightCoralColor, HTMLRedLightCoralFilling, HTMLRedLightSalmonColor, HTMLRedLightSalmonFilling, HTMLRedRedColor, HTMLRedRedFilling, HTMLRedSalmonColor, HTMLRedSalmonFilling, HTMLWhiteAliceBlueColor, HTMLWhiteAliceBlueFilling, HTMLWhiteAntiqueWhiteColor, HTMLWhiteAntiqueWhiteFilling, HTMLWhiteAzureColor, HTMLWhiteAzureFilling, HTMLWhiteBeigeColor, HTMLWhiteBeigeFilling, HTMLWhiteFloralWhiteColor, HTMLWhiteFloralWhiteFilling, HTMLWhiteGhostWhiteColor, HTMLWhiteGhostWhiteFilling, HTMLWhiteHoneydewColor, HTMLWhiteHoneydewFilling, HTMLWhiteIvoryColor, HTMLWhiteIvoryFilling, HTMLWhiteLavenderBlushColor, HTMLWhiteLavenderBlushFilling, HTMLWhiteLinenColor, HTMLWhiteLinenFilling, HTMLWhiteMintCreamColor, HTMLWhiteMintCreamFilling, HTMLWhiteMistyRoseColor, HTMLWhiteMistyRoseFilling, HTMLWhiteOldLaceColor, HTMLWhiteOldLaceFilling, HTMLWhiteSeashellColor, HTMLWhiteSeashellFilling, HTMLWhiteSnowColor, HTMLWhiteSnowFilling, HTMLWhiteWhiteColor, HTMLWhiteWhiteFilling, HTMLWhiteWhiteSmokeColor, HTMLWhiteWhiteSmokeFilling, HTMLYellowDarkKhakiColor, HTMLYellowDarkKhakiFilling, HTMLYellowGoldColor, HTMLYellowGoldFilling, HTMLYellowKhakiColor, HTMLYellowKhakiFilling, HTMLYellowLemonChiffonColor, HTMLYellowLemonChiffonFilling, HTMLYellowLightGoldenrodYellowColor, HTMLYellowLightGoldenrodYellowFilling, HTMLYellowLightYellowColor, HTMLYellowLightYellowFilling, HTMLYellowMoccasinColor, HTMLYellowMoccasinFilling, HTMLYellowPaleGoldenrodColor, HTMLYellowPaleGoldenrodFilling, HTMLYellowPapayaWhipColor, HTMLYellowPapayaWhipFilling, HTMLYellowPeachPuffColor, HTMLYellowPeachPuffFilling, HTMLYellowYellowColor, HTMLYellowYellowFilling, LightgrayColor, LightgrayFilling, MagentaColor, MagentaFilling, NoneColor, NoneFilling, NoneWeight, NormalStyle, NormalWeight, OrangeColor, OrangeFilling, PurpleColor, PurpleFilling, RedColor, RedFilling, ThinWeight, UltraWeight, VerFilling, WhiteColor, WhiteFilling, YellowColor, and YellowFilling.
Referenced by PartArc::paint(), PartEllipse::paint(), PartRectangle::paint(), PartPolygon::paint(), and PartLine::paint().
color()
Color CustomElementGraphicPart::color () const inline
Definition at line 285 of file customelementgraphicpart.h.
References _color.
drawCross()
void CustomElementGraphicPart::drawCross (const QPointF & center, QPainter * painter) static
CustomElementGraphicPart::drawCross Draw a cross at pos center.
Parameters
center : center of cross
painter : painter to use for draw cross, the painter state is restored at end of this method.
Definition at line 60 of file customelementgraphicpart.cpp.
References color.
Referenced by PartArc::paint(), PartEllipse::paint(), and PartRectangle::paint().
drawShadowShape()
void CustomElementGraphicPart::drawShadowShape (QPainter * painter) protected
CustomElementGraphicPart::drawShadowShape Draw a transparent blue shadow arround the shape of this item. The QPainterPathStroker used to draw shadows have a width of SHADOWS_HEIGHT Be carefull if penWeight of this item is to 0 the outline of strock is bigger of 0.5.
Parameters
painter : painter to use for draw this shadows
Definition at line 1240 of file customelementgraphicpart.cpp.
References color, SHADOWS_HEIGHT, and shadowShape().
Referenced by PartArc::paint(), PartEllipse::paint(), PartTerminal::paint(), PartRectangle::paint(), PartPolygon::paint(), and PartLine::paint().
filling()
Filling CustomElementGraphicPart::filling () const inline
Definition at line 282 of file customelementgraphicpart.h.
References _filling.
hoverEnterEvent()
void CustomElementGraphicPart::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
CustomElementGraphicPart::hoverEnterEvent Reimplemented from QGraphicsObject. Set m_hovered to true.
Parameters
event
Definition at line 1281 of file customelementgraphicpart.cpp.
References m_hovered.
hoverLeaveEvent()
void CustomElementGraphicPart::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
CustomElementGraphicPart::hoverLeaveEvent Reimplemented from QGraphicsObject. Set m_hovered to false.
Parameters
event
Definition at line 1293 of file customelementgraphicpart.cpp.
References m_hovered.
itemChange()
QVariant CustomElementGraphicPart::itemChange (GraphicsItemChange change, const QVariant & value) override protected
CustomElementGraphicPart::itemChange Reimplemented from QGraphicsObject. If the item position change call updateCurrentPartEditor() the change is always send to QGraphicsObject.
Parameters
change
value
Returns
the returned value of QGraphicsObject::itemChange
Definition at line 1266 of file customelementgraphicpart.cpp.
References CustomElementPart::updateCurrentPartEditor().
lineStyle()
LineStyle CustomElementGraphicPart::lineStyle () const inline
Definition at line 275 of file customelementgraphicpart.h.
References _linestyle.
lineWeight()
LineWeight CustomElementGraphicPart::lineWeight () const inline
Definition at line 278 of file customelementgraphicpart.h.
References _lineweight.
mouseMoveEvent()
void CustomElementGraphicPart::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 1307 of file customelementgraphicpart.cpp.
References CustomElementPart::elementScene(), and m_origin_pos.
mousePressEvent()
void CustomElementGraphicPart::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 1299 of file customelementgraphicpart.cpp.
References m_origin_pos.
mouseReleaseEvent()
void CustomElementGraphicPart::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 1318 of file customelementgraphicpart.cpp.
References CustomElementPart::elementScene(), QPropertyUndoCommand::enableAnimation(), m_origin_pos, QET::Icons::tr, and ElementScene::undoStack().
Referenced by PartEllipse::mouseReleaseEvent(), PartArc::mouseReleaseEvent(), and PartRectangle::mouseReleaseEvent().
penWeight()
qreal CustomElementGraphicPart::penWeight () const
CustomElementGraphicPart::penWeight.
Returns
the weight of pen
Definition at line 109 of file customelementgraphicpart.cpp.
References _lineweight, BigWeight, NoneWeight, NormalWeight, ThinWeight, and UltraWeight.
Referenced by AbstractPartEllipse::boundingRect(), PartPolygon::boundingRect(), PartRectangle::boundingRect(), PartLine::boundingRect(), PartLine::path(), PartEllipse::shadowShape(), PartArc::shadowShape(), PartPolygon::shadowShape(), PartRectangle::shadowShape(), PartLine::shadowShape(), PartEllipse::shape(), PartArc::shape(), PartPolygon::shape(), PartRectangle::shape(), and PartLine::shape().
property()
QVariant CustomElementGraphicPart::property (const char * name) const inline override virtual
Get the current value of a specific primitive property
Implements CustomElementPart.
Definition at line 297 of file customelementgraphicpart.h.
References CustomElementPart::name().
Referenced by EllipseEditor::editingFinishedH(), EllipseEditor::editingFinishedV(), EllipseEditor::editingFinishedX(), EllipseEditor::editingFinishedY(), LineEditor::lineEditingFinishedX1(), LineEditor::lineEditingFinishedX2(), LineEditor::lineEditingFinishedY1(), LineEditor::lineEditingFinishedY2(), StyleEditor::makeUndo(), PolygonEditor::on_m_close_polygon_cb_stateChanged(), PolygonEditor::on_m_points_list_tree_itemChanged(), ArcEditor::updateArcA(), ArcEditor::updateArcRectH(), ArcEditor::updateArcRectV(), ArcEditor::updateArcRectX(), ArcEditor::updateArcRectY(), ArcEditor::updateArcS(), RectangleEditor::updateForm(), EllipseEditor::updateForm(), ArcEditor::updateForm(), TerminalEditor::updateForm(), LineEditor::updateLineEndLength1(), LineEditor::updateLineEndLength2(), LineEditor::updateLineEndType1(), LineEditor::updateLineEndType2(), TerminalEditor::updateTerminalO(), TerminalEditor::updateXPos(), and TerminalEditor::updateYPos().
resetAllHandlerColor()
virtual void CustomElementGraphicPart::resetAllHandlerColor () inline virtual
Reimplemented in PartPolygon.
Definition at line 303 of file customelementgraphicpart.h.
resetStyles()
void CustomElementGraphicPart::resetStyles () protected
CustomElementGraphicPart::resetStyles Reset the curent style to default, same style of default constructor.
Definition at line 871 of file customelementgraphicpart.cpp.
References _antialiased, _color, _filling, _linestyle, _lineweight, BlackColor, NoneFilling, NormalStyle, and NormalWeight.
Referenced by stylesFromXml().
setAntialiased()
void CustomElementGraphicPart::setAntialiased (const bool b)
CustomElementGraphicPart::setAntialiased Set antialias to b.
Parameters
b
Definition at line 147 of file customelementgraphicpart.cpp.
References _antialiased.
setColor()
void CustomElementGraphicPart::setColor (const Color c)
CustomElementGraphicPart::setColor Set color to c.
Parameters
c
Definition at line 135 of file customelementgraphicpart.cpp.
References _color.
setFilling()
void CustomElementGraphicPart::setFilling (const Filling f)
CustomElementGraphicPart::setFilling Set filling to f.
Parameters
f
Definition at line 123 of file customelementgraphicpart.cpp.
References _filling.
setHandlerColor()
virtual void CustomElementGraphicPart::setHandlerColor (QPointF , const QColor &) inline virtual
Reimplemented in PartPolygon.
Definition at line 301 of file customelementgraphicpart.h.
setLineStyle()
void CustomElementGraphicPart::setLineStyle (const LineStyle ls)
CustomElementGraphicPart::setLineStyle Set line style to ls.
Parameters
ls
Definition at line 86 of file customelementgraphicpart.cpp.
References _linestyle.
setLineWeight()
void CustomElementGraphicPart::setLineWeight (const LineWeight lw)
CustomElementGraphicPart::setLineWeight Set line weight to lw.
Parameters
lw
Definition at line 98 of file customelementgraphicpart.cpp.
References _lineweight.
setProperty()
void CustomElementGraphicPart::setProperty (const char * name, const QVariant & value) inline override virtual
Set a specific property of the primitive
Implements CustomElementPart.
Definition at line 294 of file customelementgraphicpart.h.
References CustomElementPart::name().
shadowShape()
virtual QPainterPath CustomElementGraphicPart::shadowShape () const pure virtual
Implemented in PartLine, PartRectangle, PartPolygon, PartTerminal, PartArc, and PartEllipse.
Referenced by drawShadowShape().
stylesFromXml()
void CustomElementGraphicPart::stylesFromXml (const QDomElement & qde) protected
CustomElementGraphicPart::stylesFromXml Read the style used by this, from a xml element.
Parameters
qde : QDomElement used to read the style
Definition at line 508 of file customelementgraphicpart.cpp.
References _antialiased, _color, _filling, _linestyle, _lineweight, BdiagFilling, BigWeight, BlackColor, BlackFilling, BlueColor, BlueFilling, BrunColor, BrunFilling, CyanColor, CyanFilling, DashdottedStyle, DashedStyle, DottedStyle, FdiagFilling, GrayColor, GrayFilling, GreenColor, GreenFilling, HorFilling, HTMLBlueBlueColor, HTMLBlueBlueFilling, HTMLBlueCornflowerBlueColor, HTMLBlueCornflowerBlueFilling, HTMLBlueDarkBlueColor, HTMLBlueDarkBlueFilling, HTMLBlueDeepSkyBlueColor, HTMLBlueDeepSkyBlueFilling, HTMLBlueDodgerBlueColor, HTMLBlueDodgerBlueFilling, HTMLBlueLightBlueColor, HTMLBlueLightBlueFilling, HTMLBlueLightSkyBlueColor, HTMLBlueLightSkyBlueFilling, HTMLBlueLightSteelBlueColor, HTMLBlueLightSteelBlueFilling, HTMLBlueMediumBlueColor, HTMLBlueMediumBlueFilling, HTMLBlueMidnightBlueColor, HTMLBlueMidnightBlueFilling, HTMLBlueNavyColor, HTMLBlueNavyFilling, HTMLBluePowderBlueColor, HTMLBluePowderBlueFilling, HTMLBlueRoyalBlueColor, HTMLBlueRoyalBlueFilling, HTMLBlueSkyBlueColor, HTMLBlueSkyBlueFilling, HTMLBlueSteelBlueColor, HTMLBlueSteelBlueFilling, HTMLBrownBisqueColor, HTMLBrownBisqueFilling, HTMLBrownBlanchedAlmondColor, HTMLBrownBlanchedAlmondFilling, HTMLBrownBrownColor, HTMLBrownBrownFilling, HTMLBrownBurlywoodColor, HTMLBrownBurlywoodFilling, HTMLBrownChocolateColor, HTMLBrownChocolateFilling, HTMLBrownCornsilkColor, HTMLBrownCornsilkFilling, HTMLBrownDarkGoldenrodColor, HTMLBrownDarkGoldenrodFilling, HTMLBrownGoldenrodColor, HTMLBrownGoldenrodFilling, HTMLBrownMaroonColor, HTMLBrownMaroonFilling, HTMLBrownNavajoWhiteColor, HTMLBrownNavajoWhiteFilling, HTMLBrownPeruColor, HTMLBrownPeruFilling, HTMLBrownRosyBrownColor, HTMLBrownRosyBrownFilling, HTMLBrownSaddleBrownColor, HTMLBrownSaddleBrownFilling, HTMLBrownSandyBrownColor, HTMLBrownSandyBrownFilling, HTMLBrownSiennaColor, HTMLBrownSiennaFilling, HTMLBrownTanColor, HTMLBrownTanFilling, HTMLBrownWheatColor, HTMLBrownWheatFilling, HTMLCyanAquaColor, HTMLCyanAquaFilling, HTMLCyanAquamarineColor, HTMLCyanAquamarineFilling, HTMLCyanCadetBlueColor, HTMLCyanCadetBlueFilling, HTMLCyanCyanColor, HTMLCyanCyanFilling, HTMLCyanDarkCyanColor, HTMLCyanDarkCyanFilling, HTMLCyanDarkTurquoiseColor, HTMLCyanDarkTurquoiseFilling, HTMLCyanLightCyanColor, HTMLCyanLightCyanFilling, HTMLCyanLightSeaGreenColor, HTMLCyanLightSeaGreenFilling, HTMLCyanMediumTurquoiseColor, HTMLCyanMediumTurquoiseFilling, HTMLCyanPaleTurquoiseColor, HTMLCyanPaleTurquoiseFilling, HTMLCyanTealColor, HTMLCyanTealFilling, HTMLCyanTurquoiseColor, HTMLCyanTurquoiseFilling, HTMLGrayBlackColor, HTMLGrayBlackFilling, HTMLGrayDarkGrayColor, HTMLGrayDarkGrayFilling, HTMLGrayDarkSlateGrayColor, HTMLGrayDarkSlateGrayFilling, HTMLGrayDimGrayColor, HTMLGrayDimGrayFilling, HTMLGrayGainsboroColor, HTMLGrayGainsboroFilling, HTMLGrayGrayColor, HTMLGrayGrayFilling, HTMLGrayLightGrayColor, HTMLGrayLightGrayFilling, HTMLGrayLightSlateGrayColor, HTMLGrayLightSlateGrayFilling, HTMLGraySilverColor, HTMLGraySilverFilling, HTMLGraySlateGrayColor, HTMLGraySlateGrayFilling, HTMLGreenChartreuseColor, HTMLGreenChartreuseFilling, HTMLGreenDarkGreenColor, HTMLGreenDarkGreenFilling, HTMLGreenDarkOliveGreenColor, HTMLGreenDarkOliveGreenFilling, HTMLGreenDarkSeaGreenColor, HTMLGreenDarkSeaGreenFilling, HTMLGreenForestGreenColor, HTMLGreenForestGreenFilling, HTMLGreenGreenColor, HTMLGreenGreenFilling, HTMLGreenGreenYellowColor, HTMLGreenGreenYellowFilling, HTMLGreenLawnGreenColor, HTMLGreenLawnGreenFilling, HTMLGreenLightGreenColor, HTMLGreenLightGreenFilling, HTMLGreenLimeColor, HTMLGreenLimeFilling, HTMLGreenLimeGreenColor, HTMLGreenLimeGreenFilling, HTMLGreenMediumAquamarineColor, HTMLGreenMediumAquamarineFilling, HTMLGreenMediumSeaGreenColor, HTMLGreenMediumSeaGreenFilling, HTMLGreenMediumSpringGreenColor, HTMLGreenMediumSpringGreenFilling, HTMLGreenOliveColor, HTMLGreenOliveDrabColor, HTMLGreenOliveDrabFilling, HTMLGreenOliveFilling, HTMLGreenPaleGreenColor, HTMLGreenPaleGreenFilling, HTMLGreenSeaGreenColor, HTMLGreenSeaGreenFilling, HTMLGreenSpringGreenColor, HTMLGreenSpringGreenFilling, HTMLGreenYellowGreenColor, HTMLGreenYellowGreenFilling, HTMLOrangeCoralColor, HTMLOrangeCoralFilling, HTMLOrangeDarkOrangeColor, HTMLOrangeDarkOrangeFilling, HTMLOrangeOrangeColor, HTMLOrangeOrangeFilling, HTMLOrangeOrangeRedColor, HTMLOrangeOrangeRedFilling, HTMLOrangeTomatoColor, HTMLOrangeTomatoFilling, HTMLPinkDeepPinkColor, HTMLPinkDeepPinkFilling, HTMLPinkHotPinkColor, HTMLPinkHotPinkFilling, HTMLPinkLightPinkColor, HTMLPinkLightPinkFilling, HTMLPinkMediumVioletRedColor, HTMLPinkMediumVioletRedFilling, HTMLPinkPaleVioletRedColor, HTMLPinkPaleVioletRedFilling, HTMLPinkPinkColor, HTMLPinkPinkFilling, HTMLPurpleBlueVioletColor, HTMLPurpleBlueVioletFilling, HTMLPurpleDarkMagentaColor, HTMLPurpleDarkMagentaFilling, HTMLPurpleDarkOrchidColor, HTMLPurpleDarkOrchidFilling, HTMLPurpleDarkSlateBlueColor, HTMLPurpleDarkSlateBlueFilling, HTMLPurpleDarkVioletColor, HTMLPurpleDarkVioletFilling, HTMLPurpleFuchsiaColor, HTMLPurpleFuchsiaFilling, HTMLPurpleIndigoColor, HTMLPurpleIndigoFilling, HTMLPurpleLavenderColor, HTMLPurpleLavenderFilling, HTMLPurpleMagentaColor, HTMLPurpleMagentaFilling, HTMLPurpleMediumOrchidColor, HTMLPurpleMediumOrchidFilling, HTMLPurpleMediumPurpleColor, HTMLPurpleMediumPurpleFilling, HTMLPurpleMediumSlateBlueColor, HTMLPurpleMediumSlateBlueFilling, HTMLPurpleOrchidColor, HTMLPurpleOrchidFilling, HTMLPurplePlumColor, HTMLPurplePlumFilling, HTMLPurplePurpleColor, HTMLPurplePurpleFilling, HTMLPurpleSlateBlueColor, HTMLPurpleSlateBlueFilling, HTMLPurpleThistleColor, HTMLPurpleThistleFilling, HTMLPurpleVioletColor, HTMLPurpleVioletFilling, HTMLRedCrimsonColor, HTMLRedCrimsonFilling, HTMLRedDarkRedColor, HTMLRedDarkRedFilling, HTMLRedDarkSalmonColor, HTMLRedDarkSalmonFilling, HTMLRedFirebrickColor, HTMLRedFirebrickFilling, HTMLRedIndianRedColor, HTMLRedIndianRedFilling, HTMLRedLightCoralColor, HTMLRedLightCoralFilling, HTMLRedLightSalmonColor, HTMLRedLightSalmonFilling, HTMLRedRedColor, HTMLRedRedFilling, HTMLRedSalmonColor, HTMLRedSalmonFilling, HTMLWhiteAliceBlueColor, HTMLWhiteAliceBlueFilling, HTMLWhiteAntiqueWhiteColor, HTMLWhiteAntiqueWhiteFilling, HTMLWhiteAzureColor, HTMLWhiteAzureFilling, HTMLWhiteBeigeColor, HTMLWhiteBeigeFilling, HTMLWhiteFloralWhiteColor, HTMLWhiteFloralWhiteFilling, HTMLWhiteGhostWhiteColor, HTMLWhiteGhostWhiteFilling, HTMLWhiteHoneydewColor, HTMLWhiteHoneydewFilling, HTMLWhiteIvoryColor, HTMLWhiteIvoryFilling, HTMLWhiteLavenderBlushColor, HTMLWhiteLavenderBlushFilling, HTMLWhiteLinenColor, HTMLWhiteLinenFilling, HTMLWhiteMintCreamColor, HTMLWhiteMintCreamFilling, HTMLWhiteMistyRoseColor, HTMLWhiteMistyRoseFilling, HTMLWhiteOldLaceColor, HTMLWhiteOldLaceFilling, HTMLWhiteSeashellColor, HTMLWhiteSeashellFilling, HTMLWhiteSnowColor, HTMLWhiteSnowFilling, HTMLWhiteWhiteColor, HTMLWhiteWhiteFilling, HTMLWhiteWhiteSmokeColor, HTMLWhiteWhiteSmokeFilling, HTMLYellowDarkKhakiColor, HTMLYellowDarkKhakiFilling, HTMLYellowGoldColor, HTMLYellowGoldFilling, HTMLYellowKhakiColor, HTMLYellowKhakiFilling, HTMLYellowLemonChiffonColor, HTMLYellowLemonChiffonFilling, HTMLYellowLightGoldenrodYellowColor, HTMLYellowLightGoldenrodYellowFilling, HTMLYellowLightYellowColor, HTMLYellowLightYellowFilling, HTMLYellowMoccasinColor, HTMLYellowMoccasinFilling, HTMLYellowPaleGoldenrodColor, HTMLYellowPaleGoldenrodFilling, HTMLYellowPapayaWhipColor, HTMLYellowPapayaWhipFilling, HTMLYellowPeachPuffColor, HTMLYellowPeachPuffFilling, HTMLYellowYellowColor, HTMLYellowYellowFilling, LightgrayColor, LightgrayFilling, MagentaColor, MagentaFilling, NoneColor, NoneFilling, NoneWeight, NormalStyle, NormalWeight, OrangeColor, OrangeFilling, PurpleColor, PurpleFilling, RedColor, RedFilling, resetStyles(), ThinWeight, UltraWeight, VerFilling, WhiteColor, WhiteFilling, YellowColor, and YellowFilling.
Referenced by PartArc::fromXml(), PartEllipse::fromXml(), PartPolygon::fromXml(), PartRectangle::fromXml(), and PartLine::fromXml().
stylesToXml()
void CustomElementGraphicPart::stylesToXml (QDomElement & qde) const protected
CustomElementGraphicPart::stylesToXml Write the curent style to xml element. The style are stored like this: name-of-style:value;name-of-style:value Each style separate by ; and name-style/value are separate by :
Parameters
qde : QDOmElement used to write the style.
Definition at line 162 of file customelementgraphicpart.cpp.
References _antialiased, _color, _filling, _linestyle, _lineweight, BdiagFilling, BigWeight, BlackColor, BlackFilling, BlueColor, BlueFilling, BrunColor, BrunFilling, CyanColor, CyanFilling, DashdottedStyle, DashedStyle, DottedStyle, FdiagFilling, GrayColor, GrayFilling, GreenColor, GreenFilling, HorFilling, HTMLBlueBlueColor, HTMLBlueBlueFilling, HTMLBlueCornflowerBlueColor, HTMLBlueCornflowerBlueFilling, HTMLBlueDarkBlueColor, HTMLBlueDarkBlueFilling, HTMLBlueDeepSkyBlueColor, HTMLBlueDeepSkyBlueFilling, HTMLBlueDodgerBlueColor, HTMLBlueDodgerBlueFilling, HTMLBlueLightBlueColor, HTMLBlueLightBlueFilling, HTMLBlueLightSkyBlueColor, HTMLBlueLightSkyBlueFilling, HTMLBlueLightSteelBlueColor, HTMLBlueLightSteelBlueFilling, HTMLBlueMediumBlueColor, HTMLBlueMediumBlueFilling, HTMLBlueMidnightBlueColor, HTMLBlueMidnightBlueFilling, HTMLBlueNavyColor, HTMLBlueNavyFilling, HTMLBluePowderBlueColor, HTMLBluePowderBlueFilling, HTMLBlueRoyalBlueColor, HTMLBlueRoyalBlueFilling, HTMLBlueSkyBlueColor, HTMLBlueSkyBlueFilling, HTMLBlueSteelBlueColor, HTMLBlueSteelBlueFilling, HTMLBrownBisqueColor, HTMLBrownBisqueFilling, HTMLBrownBlanchedAlmondColor, HTMLBrownBlanchedAlmondFilling, HTMLBrownBrownColor, HTMLBrownBrownFilling, HTMLBrownBurlywoodColor, HTMLBrownBurlywoodFilling, HTMLBrownChocolateColor, HTMLBrownChocolateFilling, HTMLBrownCornsilkColor, HTMLBrownCornsilkFilling, HTMLBrownDarkGoldenrodColor, HTMLBrownDarkGoldenrodFilling, HTMLBrownGoldenrodColor, HTMLBrownGoldenrodFilling, HTMLBrownMaroonColor, HTMLBrownMaroonFilling, HTMLBrownNavajoWhiteColor, HTMLBrownNavajoWhiteFilling, HTMLBrownPeruColor, HTMLBrownPeruFilling, HTMLBrownRosyBrownColor, HTMLBrownRosyBrownFilling, HTMLBrownSaddleBrownColor, HTMLBrownSaddleBrownFilling, HTMLBrownSandyBrownColor, HTMLBrownSandyBrownFilling, HTMLBrownSiennaColor, HTMLBrownSiennaFilling, HTMLBrownTanColor, HTMLBrownTanFilling, HTMLBrownWheatColor, HTMLBrownWheatFilling, HTMLCyanAquaColor, HTMLCyanAquaFilling, HTMLCyanAquamarineColor, HTMLCyanAquamarineFilling, HTMLCyanCadetBlueColor, HTMLCyanCadetBlueFilling, HTMLCyanCyanColor, HTMLCyanCyanFilling, HTMLCyanDarkCyanColor, HTMLCyanDarkCyanFilling, HTMLCyanDarkTurquoiseColor, HTMLCyanDarkTurquoiseFilling, HTMLCyanLightCyanColor, HTMLCyanLightCyanFilling, HTMLCyanLightSeaGreenColor, HTMLCyanLightSeaGreenFilling, HTMLCyanMediumTurquoiseColor, HTMLCyanMediumTurquoiseFilling, HTMLCyanPaleTurquoiseColor, HTMLCyanPaleTurquoiseFilling, HTMLCyanTealColor, HTMLCyanTealFilling, HTMLCyanTurquoiseColor, HTMLCyanTurquoiseFilling, HTMLGrayBlackColor, HTMLGrayBlackFilling, HTMLGrayDarkGrayColor, HTMLGrayDarkGrayFilling, HTMLGrayDarkSlateGrayColor, HTMLGrayDarkSlateGrayFilling, HTMLGrayDimGrayColor, HTMLGrayDimGrayFilling, HTMLGrayGainsboroColor, HTMLGrayGainsboroFilling, HTMLGrayGrayColor, HTMLGrayGrayFilling, HTMLGrayLightGrayColor, HTMLGrayLightGrayFilling, HTMLGrayLightSlateGrayColor, HTMLGrayLightSlateGrayFilling, HTMLGraySilverColor, HTMLGraySilverFilling, HTMLGraySlateGrayColor, HTMLGraySlateGrayFilling, HTMLGreenChartreuseColor, HTMLGreenChartreuseFilling, HTMLGreenDarkGreenColor, HTMLGreenDarkGreenFilling, HTMLGreenDarkOliveGreenColor, HTMLGreenDarkOliveGreenFilling, HTMLGreenDarkSeaGreenColor, HTMLGreenDarkSeaGreenFilling, HTMLGreenForestGreenColor, HTMLGreenForestGreenFilling, HTMLGreenGreenColor, HTMLGreenGreenFilling, HTMLGreenGreenYellowColor, HTMLGreenGreenYellowFilling, HTMLGreenLawnGreenColor, HTMLGreenLawnGreenFilling, HTMLGreenLightGreenColor, HTMLGreenLightGreenFilling, HTMLGreenLimeColor, HTMLGreenLimeFilling, HTMLGreenLimeGreenColor, HTMLGreenLimeGreenFilling, HTMLGreenMediumAquamarineColor, HTMLGreenMediumAquamarineFilling, HTMLGreenMediumSeaGreenColor, HTMLGreenMediumSeaGreenFilling, HTMLGreenMediumSpringGreenColor, HTMLGreenMediumSpringGreenFilling, HTMLGreenOliveColor, HTMLGreenOliveDrabColor, HTMLGreenOliveDrabFilling, HTMLGreenOliveFilling, HTMLGreenPaleGreenColor, HTMLGreenPaleGreenFilling, HTMLGreenSeaGreenColor, HTMLGreenSeaGreenFilling, HTMLGreenSpringGreenColor, HTMLGreenSpringGreenFilling, HTMLGreenYellowGreenColor, HTMLGreenYellowGreenFilling, HTMLOrangeCoralColor, HTMLOrangeCoralFilling, HTMLOrangeDarkOrangeColor, HTMLOrangeDarkOrangeFilling, HTMLOrangeOrangeColor, HTMLOrangeOrangeFilling, HTMLOrangeOrangeRedColor, HTMLOrangeOrangeRedFilling, HTMLOrangeTomatoColor, HTMLOrangeTomatoFilling, HTMLPinkDeepPinkColor, HTMLPinkDeepPinkFilling, HTMLPinkHotPinkColor, HTMLPinkHotPinkFilling, HTMLPinkLightPinkColor, HTMLPinkLightPinkFilling, HTMLPinkMediumVioletRedColor, HTMLPinkMediumVioletRedFilling, HTMLPinkPaleVioletRedColor, HTMLPinkPaleVioletRedFilling, HTMLPinkPinkColor, HTMLPinkPinkFilling, HTMLPurpleBlueVioletColor, HTMLPurpleBlueVioletFilling, HTMLPurpleDarkMagentaColor, HTMLPurpleDarkMagentaFilling, HTMLPurpleDarkOrchidColor, HTMLPurpleDarkOrchidFilling, HTMLPurpleDarkSlateBlueColor, HTMLPurpleDarkSlateBlueFilling, HTMLPurpleDarkVioletColor, HTMLPurpleDarkVioletFilling, HTMLPurpleFuchsiaColor, HTMLPurpleFuchsiaFilling, HTMLPurpleIndigoColor, HTMLPurpleIndigoFilling, HTMLPurpleLavenderColor, HTMLPurpleLavenderFilling, HTMLPurpleMagentaColor, HTMLPurpleMagentaFilling, HTMLPurpleMediumOrchidColor, HTMLPurpleMediumOrchidFilling, HTMLPurpleMediumPurpleColor, HTMLPurpleMediumPurpleFilling, HTMLPurpleMediumSlateBlueColor, HTMLPurpleMediumSlateBlueFilling, HTMLPurpleOrchidColor, HTMLPurpleOrchidFilling, HTMLPurplePlumColor, HTMLPurplePlumFilling, HTMLPurplePurpleColor, HTMLPurplePurpleFilling, HTMLPurpleSlateBlueColor, HTMLPurpleSlateBlueFilling, HTMLPurpleThistleColor, HTMLPurpleThistleFilling, HTMLPurpleVioletColor, HTMLPurpleVioletFilling, HTMLRedCrimsonColor, HTMLRedCrimsonFilling, HTMLRedDarkRedColor, HTMLRedDarkRedFilling, HTMLRedDarkSalmonColor, HTMLRedDarkSalmonFilling, HTMLRedFirebrickColor, HTMLRedFirebrickFilling, HTMLRedIndianRedColor, HTMLRedIndianRedFilling, HTMLRedLightCoralColor, HTMLRedLightCoralFilling, HTMLRedLightSalmonColor, HTMLRedLightSalmonFilling, HTMLRedRedColor, HTMLRedRedFilling, HTMLRedSalmonColor, HTMLRedSalmonFilling, HTMLWhiteAliceBlueColor, HTMLWhiteAliceBlueFilling, HTMLWhiteAntiqueWhiteColor, HTMLWhiteAntiqueWhiteFilling, HTMLWhiteAzureColor, HTMLWhiteAzureFilling, HTMLWhiteBeigeColor, HTMLWhiteBeigeFilling, HTMLWhiteFloralWhiteColor, HTMLWhiteFloralWhiteFilling, HTMLWhiteGhostWhiteColor, HTMLWhiteGhostWhiteFilling, HTMLWhiteHoneydewColor, HTMLWhiteHoneydewFilling, HTMLWhiteIvoryColor, HTMLWhiteIvoryFilling, HTMLWhiteLavenderBlushColor, HTMLWhiteLavenderBlushFilling, HTMLWhiteLinenColor, HTMLWhiteLinenFilling, HTMLWhiteMintCreamColor, HTMLWhiteMintCreamFilling, HTMLWhiteMistyRoseColor, HTMLWhiteMistyRoseFilling, HTMLWhiteOldLaceColor, HTMLWhiteOldLaceFilling, HTMLWhiteSeashellColor, HTMLWhiteSeashellFilling, HTMLWhiteSnowColor, HTMLWhiteSnowFilling, HTMLWhiteWhiteColor, HTMLWhiteWhiteFilling, HTMLWhiteWhiteSmokeColor, HTMLWhiteWhiteSmokeFilling, HTMLYellowDarkKhakiColor, HTMLYellowDarkKhakiFilling, HTMLYellowGoldColor, HTMLYellowGoldFilling, HTMLYellowKhakiColor, HTMLYellowKhakiFilling, HTMLYellowLemonChiffonColor, HTMLYellowLemonChiffonFilling, HTMLYellowLightGoldenrodYellowColor, HTMLYellowLightGoldenrodYellowFilling, HTMLYellowLightYellowColor, HTMLYellowLightYellowFilling, HTMLYellowMoccasinColor, HTMLYellowMoccasinFilling, HTMLYellowPaleGoldenrodColor, HTMLYellowPaleGoldenrodFilling, HTMLYellowPapayaWhipColor, HTMLYellowPapayaWhipFilling, HTMLYellowPeachPuffColor, HTMLYellowPeachPuffFilling, HTMLYellowYellowColor, HTMLYellowYellowFilling, LightgrayColor, LightgrayFilling, MagentaColor, MagentaFilling, NoneColor, NoneFilling, NoneWeight, NormalStyle, NormalWeight, OrangeColor, OrangeFilling, PurpleColor, PurpleFilling, RedColor, RedFilling, ThinWeight, UltraWeight, VerFilling, WhiteColor, WhiteFilling, YellowColor, and YellowFilling.
Referenced by PartArc::toXml(), PartEllipse::toXml(), PartRectangle::toXml(), PartPolygon::toXml(), and PartLine::toXml().
Member Data Documentation
_antialiased
bool CustomElementGraphicPart::_antialiased private
Definition at line 329 of file customelementgraphicpart.h.
Referenced by antialiased(), applyStylesToQPainter(), resetStyles(), setAntialiased(), stylesFromXml(), and stylesToXml().
_color
Color CustomElementGraphicPart::_color private
Definition at line 328 of file customelementgraphicpart.h.
Referenced by applyStylesToQPainter(), color(), resetStyles(), setColor(), stylesFromXml(), and stylesToXml().
_filling
Filling CustomElementGraphicPart::_filling private
Definition at line 327 of file customelementgraphicpart.h.
Referenced by applyStylesToQPainter(), filling(), resetStyles(), setFilling(), stylesFromXml(), and stylesToXml().
_linestyle
LineStyle CustomElementGraphicPart::_linestyle private
Definition at line 325 of file customelementgraphicpart.h.
Referenced by applyStylesToQPainter(), lineStyle(), resetStyles(), setLineStyle(), stylesFromXml(), and stylesToXml().
_lineweight
LineWeight CustomElementGraphicPart::_lineweight private
Definition at line 326 of file customelementgraphicpart.h.
Referenced by applyStylesToQPainter(), lineWeight(), penWeight(), resetStyles(), setLineWeight(), stylesFromXml(), and stylesToXml().
m_hovered
bool CustomElementGraphicPart::m_hovered protected
Definition at line 323 of file customelementgraphicpart.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), PartArc::paint(), PartEllipse::paint(), PartTerminal::paint(), PartRectangle::paint(), PartPolygon::paint(), PartLine::paint(), PartArc::shape(), PartEllipse::shape(), PartPolygon::shape(), PartRectangle::shape(), and PartLine::shape().
m_origin_pos
QPointF CustomElementGraphicPart::m_origin_pos private
Definition at line 330 of file customelementgraphicpart.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
Property Documentation
antialias
bool CustomElementGraphicPart::antialias read write
Definition at line 333 of file customelementgraphicpart.h.
color
Color CustomElementGraphicPart::color read write
Definition at line 333 of file customelementgraphicpart.h.
Referenced by PartEllipse::addHandler(), PartArc::addHandler(), PartRectangle::addHandler(), drawCross(), drawShadowShape(), and PartPolygon::setHandlerColor().
filling
Filling CustomElementGraphicPart::filling read write
Definition at line 333 of file customelementgraphicpart.h.
line_style
LineStyle CustomElementGraphicPart::line_style read write
Definition at line 333 of file customelementgraphicpart.h.
line_weight
LineWeight CustomElementGraphicPart::line_weight read write
Definition at line 333 of file customelementgraphicpart.h.
The documentation for this class was generated from the following files:
customelementgraphicpart.h
customelementgraphicpart.cpp