QElectroTech: DynamicTextFieldEditor Class Reference
DynamicTextFieldEditor Class Reference
The DynamicTextFieldEditor class This class provide a widget used to edit the property of a dynamic text field.
#include <dynamictextfieldeditor.h>
Public Member Functions
DynamicTextFieldEditor (QETElementEditor *editor, PartDynamicTextField *text_field=nullptr, QWidget *parent=nullptr)
~DynamicTextFieldEditor () override
bool setPart (CustomElementPart *part) override
DynamicTextFieldEditor::setPart Set part as current edited part of this widget.
bool setParts (QList< CustomElementPart * >) override
CustomElementPart * currentPart () const override
DynamicTextFieldEditor::currentPart.
QList< CustomElementPart * > currentParts () const override
void updateForm () override
Public Member Functions inherited from ElementItemEditor
ElementItemEditor (QETElementEditor *, QWidget *=nullptr)
~ElementItemEditor () override
virtual QETElementEditor * elementEditor () const
virtual ElementScene * elementScene () const
virtual QUndoStack & undoStack () const
virtual QString elementTypeName () const
virtual void setElementTypeName (const QString &)
virtual void detach ()
Private Slots
void on_m_x_sb_editingFinished ()
void on_m_y_sb_editingFinished ()
void on_m_rotation_sb_editingFinished ()
void on_m_user_text_le_editingFinished ()
void on_m_size_sb_editingFinished ()
void on_m_frame_cb_clicked ()
void on_m_width_sb_editingFinished ()
void on_m_elmt_info_cb_activated (const QString &arg1)
void on_m_text_from_cb_activated (int index)
void on_m_composite_text_pb_clicked ()
void on_m_alignment_pb_clicked ()
void on_m_font_pb_clicked ()
void on_m_color_kpb_changed (const QColor &newColor)
Private Member Functions
void fillInfoComboBox ()
DynamicTextFieldEditor::fillInfoComboBox Fill the combo box "element information".
void setUpConnections ()
void disconnectConnections ()
Private Attributes
Ui::DynamicTextFieldEditor * ui
QPointer< PartDynamicTextField > m_text_field
QList< PartDynamicTextField * > m_parts
QList< QMetaObject::Connection > m_connection_list
Detailed Description
The DynamicTextFieldEditor class This class provide a widget used to edit the property of a dynamic text field.
Definition at line 32 of file dynamictextfieldeditor.h.
Constructor & Destructor Documentation
DynamicTextFieldEditor()
DynamicTextFieldEditor::DynamicTextFieldEditor (QETElementEditor * editor, PartDynamicTextField * text_field = nullptr, QWidget * parent = nullptr) explicit
Definition at line 33 of file dynamictextfieldeditor.cpp.
References fillInfoComboBox(), setPart(), and ui.
~DynamicTextFieldEditor()
DynamicTextFieldEditor::~DynamicTextFieldEditor () override
Definition at line 46 of file dynamictextfieldeditor.cpp.
References m_connection_list, and ui.
Member Function Documentation
currentPart()
CustomElementPart * DynamicTextFieldEditor::currentPart () const override virtual
DynamicTextFieldEditor::currentPart.
Returns
The current edited part, note they can return nullptr if there is not a currently edited part.
Implements ElementItemEditor.
Definition at line 111 of file dynamictextfieldeditor.cpp.
References m_text_field.
currentParts()
QList< CustomElementPart * > DynamicTextFieldEditor::currentParts () const override virtual
Implements ElementItemEditor.
Definition at line 115 of file dynamictextfieldeditor.cpp.
References m_parts.
disconnectConnections()
void DynamicTextFieldEditor::disconnectConnections () private
Definition at line 180 of file dynamictextfieldeditor.cpp.
References m_connection_list.
Referenced by setPart(), and setParts().
fillInfoComboBox()
void DynamicTextFieldEditor::fillInfoComboBox () private
DynamicTextFieldEditor::fillInfoComboBox Fill the combo box "element information".
Definition at line 193 of file dynamictextfieldeditor.cpp.
References ElementItemEditor::elementEditor(), QETApp::elementInfoKeys(), ElementItemEditor::elementScene(), QETApp::elementTranslatedInfoKey(), and ui.
Referenced by DynamicTextFieldEditor().
on_m_alignment_pb_clicked
void DynamicTextFieldEditor::on_m_alignment_pb_clicked () private slot
Definition at line 352 of file dynamictextfieldeditor.cpp.
References AlignmentTextDialog::alignment(), m_parts, m_text_field, QET::Icons::tr, and ElementItemEditor::undoStack().
on_m_color_kpb_changed
void DynamicTextFieldEditor::on_m_color_kpb_changed (const QColor & newColor) private slot
Definition at line 382 of file dynamictextfieldeditor.cpp.
References m_parts, QET::Icons::tr, and ElementItemEditor::undoStack().
on_m_composite_text_pb_clicked
void DynamicTextFieldEditor::on_m_composite_text_pb_clicked () private slot
Definition at line 338 of file dynamictextfieldeditor.cpp.
References m_parts, m_text_field, CompositeTextEditDialog::plainText(), and ElementItemEditor::undoStack().
on_m_elmt_info_cb_activated
void DynamicTextFieldEditor::on_m_elmt_info_cb_activated (const QString & arg1) private slot
Definition at line 288 of file dynamictextfieldeditor.cpp.
References ElementItemEditor::elementEditor(), ElementItemEditor::elementScene(), m_parts, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_font_pb_clicked
void DynamicTextFieldEditor::on_m_font_pb_clicked () private slot
Definition at line 367 of file dynamictextfieldeditor.cpp.
References m_parts, m_text_field, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_frame_cb_clicked
void DynamicTextFieldEditor::on_m_frame_cb_clicked () private slot
Definition at line 264 of file dynamictextfieldeditor.cpp.
References m_parts, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_rotation_sb_editingFinished
void DynamicTextFieldEditor::on_m_rotation_sb_editingFinished () private slot
Definition at line 235 of file dynamictextfieldeditor.cpp.
References m_parts, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_size_sb_editingFinished
void DynamicTextFieldEditor::on_m_size_sb_editingFinished () private slot
Definition at line 254 of file dynamictextfieldeditor.cpp.
References m_parts, m_text_field, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_text_from_cb_activated
void DynamicTextFieldEditor::on_m_text_from_cb_activated (int index) private slot
Definition at line 303 of file dynamictextfieldeditor.cpp.
References DynamicElementTextItem::CompositeText, DynamicElementTextItem::ElementInfo, m_parts, QET::Icons::tr, ui, ElementItemEditor::undoStack(), and DynamicElementTextItem::UserText.
Referenced by updateForm().
on_m_user_text_le_editingFinished
void DynamicTextFieldEditor::on_m_user_text_le_editingFinished () private slot
Definition at line 245 of file dynamictextfieldeditor.cpp.
References m_parts, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_width_sb_editingFinished
void DynamicTextFieldEditor::on_m_width_sb_editingFinished () private slot
Definition at line 276 of file dynamictextfieldeditor.cpp.
References m_parts, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_x_sb_editingFinished
void DynamicTextFieldEditor::on_m_x_sb_editingFinished () private slot
Definition at line 215 of file dynamictextfieldeditor.cpp.
References m_parts, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
on_m_y_sb_editingFinished
void DynamicTextFieldEditor::on_m_y_sb_editingFinished () private slot
Definition at line 225 of file dynamictextfieldeditor.cpp.
References m_parts, QET::Icons::tr, ui, and ElementItemEditor::undoStack().
setPart()
bool DynamicTextFieldEditor::setPart (CustomElementPart * part) override virtual
DynamicTextFieldEditor::setPart Set part as current edited part of this widget.
Parameters
part
Returns
true if part can be edited by this widget
Implements ElementItemEditor.
Definition at line 61 of file dynamictextfieldeditor.cpp.
References disconnectConnections(), m_text_field, setUpConnections(), PartDynamicTextField::Type, and updateForm().
Referenced by DynamicTextFieldEditor().
setParts()
bool DynamicTextFieldEditor::setParts (QList< CustomElementPart * > parts) override virtual
Reimplemented from ElementItemEditor.
Definition at line 78 of file dynamictextfieldeditor.cpp.
References disconnectConnections(), m_parts, m_text_field, setUpConnections(), and updateForm().
setUpConnections()
void DynamicTextFieldEditor::setUpConnections () private
Definition at line 155 of file dynamictextfieldeditor.cpp.
References PartDynamicTextField::colorChanged(), PartDynamicTextField::compositeTextChanged(), PartDynamicTextField::fontChanged(), PartDynamicTextField::frameChanged(), PartDynamicTextField::infoNameChanged(), m_connection_list, m_text_field, PartDynamicTextField::taggChanged(), PartDynamicTextField::textChanged(), PartDynamicTextField::textFromChanged(), and PartDynamicTextField::textWidthChanged().
Referenced by setPart(), and setParts().
updateForm()
void DynamicTextFieldEditor::updateForm () override virtual
Implements ElementItemEditor.
Definition at line 123 of file dynamictextfieldeditor.cpp.
References DynamicElementTextItem::CompositeText, QET::correctAngle(), DynamicElementTextItem::ElementInfo, m_text_field, on_m_text_from_cb_activated(), ui, and DynamicElementTextItem::UserText.
Referenced by setPart(), and setParts().
Member Data Documentation
m_connection_list
QList<QMetaObject::Connection> DynamicTextFieldEditor::m_connection_list private
Definition at line 70 of file dynamictextfieldeditor.h.
Referenced by disconnectConnections(), setUpConnections(), and ~DynamicTextFieldEditor().
m_parts
QList<PartDynamicTextField*> DynamicTextFieldEditor::m_parts private
Definition at line 69 of file dynamictextfieldeditor.h.
Referenced by currentParts(), on_m_alignment_pb_clicked(), on_m_color_kpb_changed(), on_m_composite_text_pb_clicked(), on_m_elmt_info_cb_activated(), on_m_font_pb_clicked(), on_m_frame_cb_clicked(), on_m_rotation_sb_editingFinished(), on_m_size_sb_editingFinished(), on_m_text_from_cb_activated(), on_m_user_text_le_editingFinished(), on_m_width_sb_editingFinished(), on_m_x_sb_editingFinished(), on_m_y_sb_editingFinished(), and setParts().
m_text_field
QPointer<PartDynamicTextField> DynamicTextFieldEditor::m_text_field private
Definition at line 68 of file dynamictextfieldeditor.h.
Referenced by currentPart(), on_m_alignment_pb_clicked(), on_m_composite_text_pb_clicked(), on_m_font_pb_clicked(), on_m_size_sb_editingFinished(), setPart(), setParts(), setUpConnections(), and updateForm().
ui
Ui::DynamicTextFieldEditor* DynamicTextFieldEditor::ui private
Definition at line 67 of file dynamictextfieldeditor.h.
Referenced by DynamicTextFieldEditor(), fillInfoComboBox(), on_m_elmt_info_cb_activated(), on_m_font_pb_clicked(), on_m_frame_cb_clicked(), on_m_rotation_sb_editingFinished(), on_m_size_sb_editingFinished(), on_m_text_from_cb_activated(), on_m_user_text_le_editingFinished(), on_m_width_sb_editingFinished(), on_m_x_sb_editingFinished(), on_m_y_sb_editingFinished(), updateForm(), and ~DynamicTextFieldEditor().
The documentation for this class was generated from the following files:
dynamictextfieldeditor.h
dynamictextfieldeditor.cpp