QElectroTech: ElementFactory Class Reference
ElementFactory Class Reference
The ElementFactory class this class is a pattern factory and also a singleton factory. this class create new instance of herited class element like simple element or report element.
#include <elementfactory.h>
Public Member Functions
Element * createElement (const ElementsLocation &, QGraphicsItem *=nullptr, int *=nullptr)
ElementFactory::createElement.
Static Public Member Functions
static ElementFactory * Instance ()
static void dropInstance ()
Private Member Functions
ElementFactory ()
ElementFactory (const ElementFactory &)
ElementFactory operator= (const ElementFactory &)
~ElementFactory ()
Static Private Attributes
static ElementFactory * factory_ = nullptr
Detailed Description
The ElementFactory class this class is a pattern factory and also a singleton factory. this class create new instance of herited class element like simple element or report element.
Definition at line 33 of file elementfactory.h.
Constructor & Destructor Documentation
ElementFactory() [1/2]
ElementFactory::ElementFactory () inline private
Definition at line 65 of file elementfactory.h.
Referenced by Instance().
ElementFactory() [2/2]
ElementFactory::ElementFactory (const ElementFactory &) private
~ElementFactory()
ElementFactory::~ElementFactory () inline private
Definition at line 68 of file elementfactory.h.
Member Function Documentation
createElement()
Element * ElementFactory::createElement (const ElementsLocation & location, QGraphicsItem * qgi = nullptr, int * state = nullptr)
ElementFactory::createElement.
Parameters
location create element at this location
qgi parent item for this elemnt
state state of the creation
Returns
the element or 0
Definition at line 34 of file elementfactory.cpp.
References ElementsLocation::exist(), ElementsLocation::isElement(), and ElementsLocation::pugiXml().
Referenced by ElementsTreeView::startElementDrag().
dropInstance()
static void ElementFactory::dropInstance () inline static
Definition at line 49 of file elementfactory.h.
References factory_.
Referenced by QETApp::~QETApp().
Instance()
static ElementFactory* ElementFactory::Instance () inline static
Definition at line 38 of file elementfactory.h.
References ElementFactory(), and factory_.
Referenced by DiagramEventAddElement::addElement(), DiagramEventAddElement::buildElement(), ElementsCollectionCache::fetchData(), Diagram::fromXml(), and ElementsTreeView::startElementDrag().
operator=()
ElementFactory ElementFactory::operator= (const ElementFactory &) private
Member Data Documentation
factory_
ElementFactory * ElementFactory::factory_ = nullptr static private
Definition at line 61 of file elementfactory.h.
Referenced by dropInstance(), and Instance().
The documentation for this class was generated from the following files:
elementfactory.h
elementfactory.cpp