QElectroTech: QETUtils Namespace Reference
QETUtils Namespace Reference
Functions
QString marginsToString (const QMargins &margins)
QETUtils::marginsToString.
QMargins marginsFromString (const QString &string)
QETUtils::marginsFromString.
Detailed Description
Provide some small utils function
Function Documentation
marginsFromString()
QMargins QETUtils::marginsFromString (const QString & string)
QETUtils::marginsFromString.
Parameters
string
Returns
QMargins margins
Definition at line 46 of file qetutils.cpp.
Referenced by GraphicsTablePropertiesEditor::associatedUndo(), AddTableDialog::loadConfig(), QetGraphicsHeaderItem::paint(), QetGraphicsTableItem::paint(), QetGraphicsTableItem::setUpColumnAndRowMinimumSize(), QetGraphicsHeaderItem::setUpMinimumSectionsSize(), QetGraphicsHeaderItem::toXml(), and GraphicsTablePropertiesEditor::updateUi().
marginsToString()
QString QETUtils::marginsToString (const QMargins & margins)
QETUtils::marginsToString.
Parameters
margins
Returns
QString str "left;top;right;bottom"
Definition at line 27 of file qetutils.cpp.
Referenced by GraphicsTablePropertiesEditor::associatedUndo(), QetGraphicsHeaderItem::fromXml(), QetGraphicsTableFactory::newTable(), and AddTableDialog::saveConfig().