QElectroTech: MarginsEditDialog Class Reference
MarginsEditDialog Class Reference
The MarginsEditDialog class A simple dialog to edit QMargins.
#include <marginseditdialog.h>
Public Member Functions
MarginsEditDialog (QMargins margins=QMargins(), QWidget *parent=nullptr)
~MarginsEditDialog ()
QMargins margins () const
Static Public Member Functions
static QMargins getMargins (QMargins margins=QMargins(), bool *accepted=nullptr, QWidget *parent=nullptr)
MarginsEditDialog::getMargins.
Private Attributes
Ui::MarginsEditDialog * ui
Detailed Description
The MarginsEditDialog class A simple dialog to edit QMargins.
Definition at line 32 of file marginseditdialog.h.
Constructor & Destructor Documentation
MarginsEditDialog()
MarginsEditDialog::MarginsEditDialog (QMargins margins = QMargins(), QWidget * parent = nullptr) explicit
Definition at line 23 of file marginseditdialog.cpp.
References margins(), and ui.
Referenced by getMargins().
~MarginsEditDialog()
MarginsEditDialog::~MarginsEditDialog ()
Definition at line 34 of file marginseditdialog.cpp.
References ui.
Member Function Documentation
getMargins()
QMargins MarginsEditDialog::getMargins (QMargins margins = QMargins(), bool * accepted = nullptr, QWidget * parent = nullptr) static
MarginsEditDialog::getMargins.
Parameters
margins : margins to set by default
accepted : bool to know if dialog is accepted
parent : parent widget.
Returns
The a margins with the edited value if dialog is accepted or a default constructed QMargins() if dialog is rejected
Definition at line 54 of file marginseditdialog.cpp.
References margins(), and MarginsEditDialog().
Referenced by AddTableDialog::on_m_edit_header_margins_pb_clicked(), and AddTableDialog::on_m_table_margins_pb_clicked().
margins()
QMargins MarginsEditDialog::margins () const
Definition at line 39 of file marginseditdialog.cpp.
References ui.
Referenced by getMargins(), and MarginsEditDialog().
Member Data Documentation
ui
Ui::MarginsEditDialog* MarginsEditDialog::ui private
Definition at line 48 of file marginseditdialog.h.
Referenced by margins(), MarginsEditDialog(), and ~MarginsEditDialog().
The documentation for this class was generated from the following files:
marginseditdialog.h
marginseditdialog.cpp