QElectroTech: Machine_info::Pc::Built Struct Reference
Machine_info::Pc::Built Struct Reference
#include <machine_info.h>
Public Attributes
QString version
QString date =QString(__DATE__)
QString time =QString(__TIME__)
Detailed Description
Definition at line 56 of file machine_info.h.
Member Data Documentation
date
QString Machine_info::Pc::Built::date =QString(__DATE__)
Definition at line 67 of file machine_info.h.
Referenced by Machine_info::compilation_info(), and Machine_info::send_info_to_debug().
time
QString Machine_info::Pc::Built::time =QString(__TIME__)
Definition at line 68 of file machine_info.h.
Referenced by Machine_info::compilation_info(), and Machine_info::send_info_to_debug().
version
QString Machine_info::Pc::Built::version
Initial value:
=
            QString QT=QString(QT_VERSION_STR)
Definition at line 58 of file machine_info.h.
Referenced by Machine_info::compilation_info(), and Machine_info::send_info_to_debug().
The documentation for this struct was generated from the following file:
machine_info.h