QElectroTech: ElementsPanel Class Reference
ElementsPanel Class Reference
#include <elementspanel.h>
Public Slots
void slot_doubleClick (QTreeWidgetItem *, int)
void reload (bool=false)
ElementsPanel::reload Reload the elements tree.
void filter (const QString &, QET::Filtering=QET::RegularFilter)
void projectWasOpened (QETProject *)
void projectWasClosed (QETProject *)
void buildFilterList ()
void applyCurrentFilter (const QList< QTreeWidgetItem * > &)
void ensureHierarchyIsVisible (const QList< QTreeWidgetItem * > &)
Signals
void requestForProject (QETProject *)
void requestForDiagram (Diagram *)
void requestForTitleBlockTemplate (const TitleBlockTemplateLocation &)
Signals inherited from GenericPanel
bool firstActivated ()
void panelContentChanged ()
Public Member Functions
ElementsPanel (QWidget *=nullptr)
~ElementsPanel () override
QString dirPathForItem (QTreeWidgetItem *)
ElementsPanel::dirPathForItem.
QString filePathForItem (QTreeWidgetItem *)
ElementsPanel::filePathForItem.
Public Member Functions inherited from GenericPanel
GenericPanel (QWidget *=nullptr)
~GenericPanel () override
virtual int currentItemType ()
virtual QETProject * projectForItem (QTreeWidgetItem *) const
GenericPanel::projectForItem.
virtual Diagram * diagramForItem (QTreeWidgetItem *) const
GenericPanel::diagramForItem.
virtual TitleBlockTemplateLocation templateLocationForItem (QTreeWidgetItem *) const
GenericPanel::templateLocationForItem.
virtual QETProject * selectedProject () const
GenericPanel::selectedProject.
virtual Diagram * selectedDiagram () const
GenericPanel::selectedDiagram.
virtual TitleBlockTemplateLocation selectedTemplateLocation () const
GenericPanel::selectedTemplateLocation.
virtual QTreeWidgetItem * itemForProject (QETProject *)
virtual QTreeWidgetItem * addDiagram (Diagram *, QTreeWidgetItem *=nullptr, PanelOptions=AddAllChild)
GenericPanel::addDiagram.
virtual QTreeWidgetItem * addTemplatesCollection (TitleBlockTemplatesCollection *, QTreeWidgetItem *=nullptr, PanelOptions=AddAllChild)
GenericPanel::addTemplatesCollection.
virtual QTreeWidgetItem * itemForTemplatesCollection (TitleBlockTemplatesCollection *)
GenericPanel::itemForTemplatesCollection.
virtual QTreeWidgetItem * addTemplate (const TitleBlockTemplateLocation &, QTreeWidgetItem *=nullptr, PanelOptions=AddAllChild)
GenericPanel::addTemplate.
Protected Slots
void panelContentChange ()
Protected Slots inherited from GenericPanel
virtual void projectInformationsChanged (QETProject *)
GenericPanel::projectInformationsChanged.
virtual void diagramAdded (QETProject *, Diagram *)
GenericPanel::diagramAdded.
virtual void diagramRemoved (QETProject *, Diagram *)
GenericPanel::diagramRemoved.
virtual void projectDiagramsOrderChanged (QETProject *, int, int)
GenericPanel::projectDiagramsOrderChanged.
virtual void diagramTitleChanged (Diagram *, const QString &)
GenericPanel::diagramTitleChanged Inform this panel the diagram diagram has changed its title to title.
virtual void templatesCollectionChanged (TitleBlockTemplatesCollection *, const QString &)
GenericPanel::templatesCollectionChanged.
virtual void diagramUsedTemplate (TitleBlockTemplatesCollection *, const QString &)
GenericPanel::diagramUsedTemplate.
Protected Member Functions
void startDrag (Qt::DropActions) override
void startTitleBlockTemplateDrag (const TitleBlockTemplateLocation &)
bool matchesFilter (const QTreeWidgetItem *, const QString &) const
Protected Member Functions inherited from GenericPanel
virtual QTreeWidgetItem * getItemForProject (QETProject *, bool *=nullptr)
virtual QTreeWidgetItem * updateProjectItem (QTreeWidgetItem *, QETProject *, PanelOptions=AddAllChild, bool=false)
GenericPanel::updateProjectItem.
virtual QTreeWidgetItem * fillProjectItem (QTreeWidgetItem *, QETProject *, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillProjectItem.
virtual QTreeWidgetItem * getItemForDiagram (Diagram *, bool *=nullptr)
GenericPanel::getItemForDiagram.
virtual QTreeWidgetItem * updateDiagramItem (QTreeWidgetItem *, Diagram *, PanelOptions=AddAllChild, bool=false)
GenericPanel::updateDiagramItem.
virtual QTreeWidgetItem * fillDiagramItem (QTreeWidgetItem *, Diagram *, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillDiagramItem.
virtual QTreeWidgetItem * getItemForTemplatesCollection (TitleBlockTemplatesCollection *, bool *=nullptr)
GenericPanel::getItemForTemplatesCollection.
virtual QTreeWidgetItem * fillTemplatesCollectionItem (QTreeWidgetItem *, TitleBlockTemplatesCollection *, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillTemplatesCollectionItem.
virtual QTreeWidgetItem * getItemForTemplate (const TitleBlockTemplateLocation &, bool *=nullptr)
GenericPanel::getItemForTemplate.
virtual QTreeWidgetItem * fillTemplateItem (QTreeWidgetItem *, const TitleBlockTemplateLocation &, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillTemplateItem.
virtual QTreeWidgetItem * updateItem (QTreeWidgetItem *, PanelOptions=AddAllChild, bool=false)
GenericPanel::updateItem This generic method is called at the end of each update*Item method. Its only purpose is being reimplemented in a subclass. The default implementation does nothing.
virtual QTreeWidgetItem * fillItem (QTreeWidgetItem *, PanelOptions=AddAllChild, bool=false)
GenericPanel::fillItem This generic method is called at the end of each fill*Item method. Its only purpose is being reimplemented in a subclass. The default implementation does nothing.
virtual QString defaultText (QET::ItemType)
GenericPanel::defaultText.
virtual QIcon defaultIcon (QET::ItemType)
GenericPanel::defaultIcon.
virtual QTreeWidgetItem * makeItem (QET::ItemType, QTreeWidgetItem *=nullptr, const QString &=QString(), const QIcon &=QIcon())
GenericPanel::makeItem Create a QTreeWidgetItem.
virtual void deleteItem (QTreeWidgetItem *, bool=false)
GenericPanel::deleteItem Delete and item and its children.
virtual void markItemAsUnused (QTreeWidgetItem *)
GenericPanel::markItemAsUnused Mark the provided QTreeWidgetItem as unused in its parent project.
virtual void reparent (QTreeWidgetItem *, QTreeWidgetItem *)
GenericPanel::reparent.
QList< QTreeWidgetItem * > childItems (QTreeWidgetItem *, QET::ItemType, bool=false) const
GenericPanel::childItems.
template<typename T >
void removeObsoleteItems (const QList< T > &, QTreeWidgetItem *, QET::ItemType, bool)
template<typename T >
T valueForItem (QTreeWidgetItem *) const
void unregisterItem (QTreeWidgetItem *)
GenericPanel::unregisterItem.
bool event (QEvent *) override
GenericPanel::event Handle various events; reimplemented here to emit the signal firstActivated().
Private Member Functions
ElementsPanel (const ElementsPanel &)
QTreeWidgetItem * addProject (QETProject *, QTreeWidgetItem *=nullptr, PanelOptions=AddAllChild) override
ElementsPanel::addProject Methode permettant d'ajouter un projet au panel d'elements.
QTreeWidgetItem * updateTemplatesCollectionItem (QTreeWidgetItem *, TitleBlockTemplatesCollection *, PanelOptions=AddAllChild, bool=false) override
GenericPanel::updateTemplatesCollectionItem.
QTreeWidgetItem * updateTemplateItem (QTreeWidgetItem *, const TitleBlockTemplateLocation &, PanelOptions, bool=false) override
GenericPanel::updateTemplateItem.
Private Attributes
QSet< QETProject * > projects_to_display_
list of projects that have been added to this panel
QTreeWidgetItem * common_tbt_collection_item_
pointer to the item representing the common templates collection
QTreeWidgetItem * custom_tbt_collection_item_
pointer to the item representing the user templates collection
bool first_reload_
used to distinguish the first time this panel is reloaded
QString filter_
Currently applied filter.
QStringList filter_list_
Currently applied list of filter.
Additional Inherited Members
Public Types inherited from GenericPanel
enum PanelOption {
AddChildDiagrams = 1, AddChildTemplatesCollection = 2, AddChildTemplates = 4, AddAllChildTemplates = 6,
AddAllChild = 63, All = 127
}
enum MetaData { Item = Qt::UserRole + 1, AliasItem, Parent, PanelFlags }
Detailed Description
This class provides a tree widget listing known filesystem-based elements collections and opened project files along with their content (diagrams, embedded collections, ...). It enables users to perform various actions on the displayed content
Definition at line 34 of file elementspanel.h.
Constructor & Destructor Documentation
ElementsPanel() [1/2]
ElementsPanel::ElementsPanel (QWidget * parent = nullptr)
Constructeur
Parameters
parent Le QWidget parent du panel d'appareils
Definition at line 39 of file elementspanel.cpp.
References GenericPanel::firstActivated(), panelContentChange(), GenericPanel::panelContentChanged(), reload(), and slot_doubleClick().
~ElementsPanel()
ElementsPanel::~ElementsPanel () override
Destructeur
Definition at line 77 of file elementspanel.cpp.
ElementsPanel() [2/2]
ElementsPanel::ElementsPanel (const ElementsPanel &) private
Member Function Documentation
addProject()
QTreeWidgetItem * ElementsPanel::addProject (QETProject * project, QTreeWidgetItem * parent_item = nullptr, PanelOptions options = AddAllChild) override private virtual
ElementsPanel::addProject Methode permettant d'ajouter un projet au panel d'elements.
Parameters
project : project Projet a inserer dans le panel d'elements
parent_item : Q_UNUSED QTreeWidgetItem parent sous lequel sera insere le projet
options : Q_UNUSED
Returns
Le QTreeWidgetItem insere le plus haut
Reimplemented from GenericPanel.
Definition at line 131 of file elementspanel.cpp.
References GenericPanel::addProject(), GenericPanel::All, common_tbt_collection_item_, first_reload_, GenericPanel::itemForTemplatesCollection(), projects_to_display_, and QET::Icons::tr.
Referenced by projectWasOpened(), and reload().
applyCurrentFilter
void ElementsPanel::applyCurrentFilter (const QList< QTreeWidgetItem * > & items) slot
Apply the current filter to a given item.
Definition at line 392 of file elementspanel.cpp.
References buildFilterList(), ensureHierarchyIsVisible(), filter(), filter_, filter_list_, and matchesFilter().
Referenced by filter().
buildFilterList
void ElementsPanel::buildFilterList () slot
Build filter list for multiple filter
Definition at line 377 of file elementspanel.cpp.
References filter_, and filter_list_.
Referenced by applyCurrentFilter().
dirPathForItem()
QString ElementsPanel::dirPathForItem (QTreeWidgetItem * item)
ElementsPanel::dirPathForItem.
Parameters
item : a QTreeWidgetItem
Returns
the directory path of the object represented by item
Definition at line 276 of file elementspanel.cpp.
References filePathForItem().
ensureHierarchyIsVisible
void ElementsPanel::ensureHierarchyIsVisible (const QList< QTreeWidgetItem * > & items) slot
Parameters
items une liste de QTreeWidgetItem pour lesquels il faut s'assurer que eux et leurs parents sont visibles
Definition at line 416 of file elementspanel.cpp.
Referenced by applyCurrentFilter(), and filter().
filePathForItem()
QString ElementsPanel::filePathForItem (QTreeWidgetItem * item)
ElementsPanel::filePathForItem.
Parameters
item : a QTreeWidgetItem
Returns
the filepath of the object represented by item
Definition at line 295 of file elementspanel.cpp.
References TitleBlockTemplateLocation::parentCollection(), GenericPanel::projectForItem(), and GenericPanel::templateLocationForItem().
Referenced by dirPathForItem().
filter
void ElementsPanel::filter (const QString & m, QET::Filtering filtering = QET::RegularFilter) slot
Hide items that do not match the provided string, ensure others are visible along with their parent hierarchy. When ending the filtering, restore the tree as it was before the filtering (except the current item) and scroll to the currently selected item.
Parameters
m String to be matched
filtering whether to begin/apply/end the filtering
See also
QET::Filtering
Definition at line 321 of file elementspanel.cpp.
References applyCurrentFilter(), QET::BeginFilter, QET::EndFilter, ensureHierarchyIsVisible(), and filter_.
Referenced by applyCurrentFilter(), matchesFilter(), and panelContentChange().
matchesFilter()
bool ElementsPanel::matchesFilter (const QTreeWidgetItem * item, const QString & filter) const protected
Returns
true if item matches the filter, false otherwise
Definition at line 199 of file elementspanel.cpp.
References filter().
Referenced by applyCurrentFilter().
panelContentChange
void ElementsPanel::panelContentChange () protected slot
Ensure the filter is applied again after the panel content has changed.
Definition at line 114 of file elementspanel.cpp.
References filter(), and filter_.
Referenced by ElementsPanel().
projectWasClosed
void ElementsPanel::projectWasClosed (QETProject * project) slot
Enleve un projet du panel d'elements
Parameters
project Projet a enlever du panel
Definition at line 366 of file elementspanel.cpp.
References GenericPanel::deleteItem(), GenericPanel::itemForProject(), GenericPanel::panelContentChanged(), and projects_to_display_.
projectWasOpened
void ElementsPanel::projectWasOpened (QETProject * project) slot
Rajoute un projet au panel d'elements
Parameters
project Projet ouvert a rajouter au panel
Definition at line 356 of file elementspanel.cpp.
References addProject(), GenericPanel::panelContentChanged(), and projects_to_display_.
reload
void ElementsPanel::reload (bool reload_collections = false) slot
ElementsPanel::reload Reload the elements tree.
Parameters
reload_collections : true for read all collections since their sources (files, projects ...)
Definition at line 218 of file elementspanel.cpp.
References addProject(), GenericPanel::addTemplatesCollection(), common_tbt_collection_item_, QETApp::commonTitleBlockTemplatesCollection(), custom_tbt_collection_item_, QETApp::customTitleBlockTemplatesCollection(), first_reload_, projects_to_display_, and QET::Icons::tr.
Referenced by ElementsPanel().
requestForDiagram
void ElementsPanel::requestForDiagram (Diagram *) signal
Referenced by slot_doubleClick().
requestForProject
void ElementsPanel::requestForProject (QETProject *) signal
Referenced by slot_doubleClick().
requestForTitleBlockTemplate
void ElementsPanel::requestForTitleBlockTemplate (const TitleBlockTemplateLocation &) signal
Referenced by slot_doubleClick().
slot_doubleClick
void ElementsPanel::slot_doubleClick (QTreeWidgetItem * qtwi, int) slot
Gere le double-clic sur un element. Si un double-clic sur un projet est effectue, le signal requestForProject est emis. Si un double-clic sur un schema est effectue, le signal requestForDiagram est emis.
Parameters
qtwi
Definition at line 257 of file elementspanel.cpp.
References QET::Diagram, QET::Project, requestForDiagram(), requestForProject(), requestForTitleBlockTemplate(), and QET::TitleBlockTemplate.
Referenced by ElementsPanel().
startDrag()
void ElementsPanel::startDrag (Qt::DropActions supportedActions) override protected
Gere le debut des drag'n drop
Parameters
supportedActions Les actions supportees
Definition at line 84 of file elementspanel.cpp.
References TitleBlockTemplateLocation::isValid(), GenericPanel::selectedTemplateLocation(), and startTitleBlockTemplateDrag().
startTitleBlockTemplateDrag()
void ElementsPanel::startTitleBlockTemplateDrag (const TitleBlockTemplateLocation & location) protected
Handle the dragging of a title block template
Parameters
location Location of the dragged template.
Definition at line 98 of file elementspanel.cpp.
References QET::Icons::TitleBlock, and TitleBlockTemplateLocation::toString().
Referenced by startDrag().
updateTemplateItem()
QTreeWidgetItem * ElementsPanel::updateTemplateItem (QTreeWidgetItem * tb_template_qtwi, const TitleBlockTemplateLocation & tb_template, PanelOptions options, bool freshly_created = false) override private virtual
GenericPanel::updateTemplateItem.
Parameters
tb_template_qtwi
tb_template
options
freshly_created
Returns
updateItem(tb_template_qtwi, options, freshly_created)
Reimplemented from GenericPanel.
Definition at line 177 of file elementspanel.cpp.
References QET::Icons::tr, and GenericPanel::updateTemplateItem().
updateTemplatesCollectionItem()
QTreeWidgetItem * ElementsPanel::updateTemplatesCollectionItem (QTreeWidgetItem * tbt_collection_qtwi, TitleBlockTemplatesCollection * tbt_collection, PanelOptions options = AddAllChild, bool freshly_created = false) override private virtual
GenericPanel::updateTemplatesCollectionItem.
Parameters
tbt_collection_qtwi
tbt_collection
options
freshly_created
Returns
updateItem(tbt_collection_qtwi, options, freshly_created)
Reimplemented from GenericPanel.
Definition at line 160 of file elementspanel.cpp.
References QET::Icons::tr, and GenericPanel::updateTemplatesCollectionItem().
Member Data Documentation
common_tbt_collection_item_
QTreeWidgetItem* ElementsPanel::common_tbt_collection_item_ private
pointer to the item representing the common templates collection
Definition at line 84 of file elementspanel.h.
Referenced by addProject(), and reload().
custom_tbt_collection_item_
QTreeWidgetItem* ElementsPanel::custom_tbt_collection_item_ private
pointer to the item representing the user templates collection
Definition at line 85 of file elementspanel.h.
Referenced by reload().
filter_
QString ElementsPanel::filter_ private
Currently applied filter.
Definition at line 87 of file elementspanel.h.
Referenced by applyCurrentFilter(), buildFilterList(), filter(), and panelContentChange().
filter_list_
QStringList ElementsPanel::filter_list_ private
Currently applied list of filter.
Definition at line 88 of file elementspanel.h.
Referenced by applyCurrentFilter(), and buildFilterList().
first_reload_
bool ElementsPanel::first_reload_ private
used to distinguish the first time this panel is reloaded
Definition at line 86 of file elementspanel.h.
Referenced by addProject(), and reload().
projects_to_display_
QSet<QETProject *> ElementsPanel::projects_to_display_ private
list of projects that have been added to this panel
Definition at line 83 of file elementspanel.h.
Referenced by addProject(), projectWasClosed(), projectWasOpened(), and reload().
The documentation for this class was generated from the following files:
elementspanel.h
elementspanel.cpp