QElectroTech: PotentialSelectorDialog Class Reference
PotentialSelectorDialog Class Reference
The PotentialSelectorDialog class This dialog is used when user try to connect two existing potential together. The dialog ask to user to make a choice between the properties of the two existing potential, to apply it for the new potential.
#include <potentialselectordialog.h>
Public Member Functions
PotentialSelectorDialog (Conductor *conductor, QUndoCommand *parent_undo=nullptr, QWidget *parent=nullptr)
PotentialSelectorDialog::PotentialSelectorDialog Constructor when we link two potentiels together, with a conductor.
PotentialSelectorDialog (Element *report, QUndoCommand *parent_undo=nullptr, QWidget *parent=nullptr)
PotentialSelectorDialog::PotentialSelectorDialog Constructor when we link two potentiels together, with a folio report.
~PotentialSelectorDialog () override
Static Public Member Functions
static ConductorProperties chosenProperties (QList< ConductorProperties > list, QWidget *parent=nullptr)
Private Slots
void on_buttonBox_accepted ()
PotentialSelectorDialog::on_buttonBox_accepted Action when user click on OK button.
Private Member Functions
void buildWidget ()
PotentialSelectorDialog::buildWidget Build the dialog.
Private Attributes
Ui::PotentialSelectorDialog * ui
Conductor * m_conductor
Element * m_report
QUndoCommand * m_parent_undo
autonum::sequentialNumbers m_sequential_num
AbstractPotentialSelector * m_potential_selector
QList< ConductorProperties > m_properties_list
QList< Conductor * > m_conductors_to_change
int m_selected = 0
Detailed Description
The PotentialSelectorDialog class This dialog is used when user try to connect two existing potential together. The dialog ask to user to make a choice between the properties of the two existing potential, to apply it for the new potential.
Each constructor have a QUndoCommand parent_undo for parameter If parent_undo isn't null, when user click on OK button, the dialog will use the parent-undo as parent of the undo command that describe the changes. If parent_undo is null, the created undo-command is push to the undo stack of the parent diagram of a conductor in potential. else we apply the change without a QUndoCommand.
the static function chosenProperties, open a dialog who ask user to make a choice between the given properties
Definition at line 68 of file potentialselectordialog.h.
Constructor & Destructor Documentation
PotentialSelectorDialog() [1/2]
PotentialSelectorDialog::PotentialSelectorDialog (Conductor * conductor, QUndoCommand * parent_undo = nullptr, QWidget * parent = nullptr) explicit
PotentialSelectorDialog::PotentialSelectorDialog Constructor when we link two potentiels together, with a conductor.
Parameters
conductor : the new conductor who connect to existing potential
parent_undo : undo parent to use.
parent : parent widget.
Definition at line 242 of file potentialselectordialog.cpp.
References buildWidget(), m_potential_selector, and ui.
PotentialSelectorDialog() [2/2]
PotentialSelectorDialog::PotentialSelectorDialog (Element * report, QUndoCommand * parent_undo = nullptr, QWidget * parent = nullptr) explicit
PotentialSelectorDialog::PotentialSelectorDialog Constructor when we link two potentiels together, with a folio report.
Parameters
report : one of the report used to link the potentials (report must be linked to another report)
parent_undo : undo parent to use
parent : parent widget
Definition at line 264 of file potentialselectordialog.cpp.
References buildWidget(), m_potential_selector, and ui.
~PotentialSelectorDialog()
PotentialSelectorDialog::~PotentialSelectorDialog () override
Definition at line 278 of file potentialselectordialog.cpp.
References m_potential_selector, and ui.
Member Function Documentation
buildWidget()
void PotentialSelectorDialog::buildWidget () private
PotentialSelectorDialog::buildWidget Build the dialog.
Definition at line 288 of file potentialselectordialog.cpp.
References AbstractPotentialSelector::m_conductor_number_1, AbstractPotentialSelector::m_conductor_number_2, AbstractPotentialSelector::m_conductors_list_1, AbstractPotentialSelector::m_conductors_list_2, m_conductors_to_change, ConductorProperties::m_function, m_potential_selector, m_properties_list, AbstractPotentialSelector::m_properties_list_1, AbstractPotentialSelector::m_properties_list_2, AbstractPotentialSelector::m_seq_num_1, AbstractPotentialSelector::m_seq_num_2, m_sequential_num, ConductorProperties::m_tension_protocol, ConductorProperties::m_wire_color, ConductorProperties::m_wire_section, ConductorProperties::text, QET::Icons::tr, and ui.
Referenced by PotentialSelectorDialog().
chosenProperties()
ConductorProperties PotentialSelectorDialog::chosenProperties (QList< ConductorProperties > list, QWidget * parent = nullptr) static
Definition at line 187 of file potentialselectordialog.cpp.
References QET::Icons::tr.
Referenced by ConductorCreator::setUpPropertieToUse().
on_buttonBox_accepted
void PotentialSelectorDialog::on_buttonBox_accepted () private slot
PotentialSelectorDialog::on_buttonBox_accepted Action when user click on OK button.
Definition at line 386 of file potentialselectordialog.cpp.
References Element::AllReport, ConductorProperties::applyForEqualAttributes(), Element::conductors(), QetGraphicsItem::diagram(), Conductor::diagram(), FormulaAssistantDialog::formula(), Element::isFree(), AbstractPotentialSelector::isValid(), Element::linkType(), m_conductor, m_conductors_to_change, ConductorProperties::m_formula, m_parent_undo, m_potential_selector, m_properties_list, m_report, m_sequential_num, Conductor::properties, Conductor::relatedPotentialConductors(), Conductor::sequenceNum, FormulaAssistantDialog::setForbiddenVariables(), FormulaAssistantDialog::setFormula(), FormulaAssistantDialog::setText(), QET::Icons::tr, and Diagram::undoStack().
Member Data Documentation
m_conductor
Conductor* PotentialSelectorDialog::m_conductor private
Definition at line 97 of file potentialselectordialog.h.
Referenced by on_buttonBox_accepted().
m_conductors_to_change
QList<Conductor *> PotentialSelectorDialog::m_conductors_to_change private
Definition at line 103 of file potentialselectordialog.h.
Referenced by buildWidget(), and on_buttonBox_accepted().
m_parent_undo
QUndoCommand* PotentialSelectorDialog::m_parent_undo private
Definition at line 99 of file potentialselectordialog.h.
Referenced by on_buttonBox_accepted().
m_potential_selector
AbstractPotentialSelector* PotentialSelectorDialog::m_potential_selector private
Definition at line 101 of file potentialselectordialog.h.
Referenced by buildWidget(), on_buttonBox_accepted(), PotentialSelectorDialog(), and ~PotentialSelectorDialog().
m_properties_list
QList<ConductorProperties> PotentialSelectorDialog::m_properties_list private
Definition at line 102 of file potentialselectordialog.h.
Referenced by buildWidget(), and on_buttonBox_accepted().
m_report
Element* PotentialSelectorDialog::m_report private
Definition at line 98 of file potentialselectordialog.h.
Referenced by on_buttonBox_accepted().
m_selected
int PotentialSelectorDialog::m_selected = 0 private
Definition at line 104 of file potentialselectordialog.h.
m_sequential_num
autonum::sequentialNumbers PotentialSelectorDialog::m_sequential_num private
Definition at line 100 of file potentialselectordialog.h.
Referenced by buildWidget(), and on_buttonBox_accepted().
ui
Ui::PotentialSelectorDialog* PotentialSelectorDialog::ui private
Definition at line 96 of file potentialselectordialog.h.
Referenced by buildWidget(), PotentialSelectorDialog(), and ~PotentialSelectorDialog().
The documentation for this class was generated from the following files:
potentialselectordialog.h
potentialselectordialog.cpp