QElectroTech: NumStrategy Class Reference
NumStrategy Class Reference abstract
#include <numerotationcontextcommands.h>
Public Member Functions
NumStrategy (Diagram *=nullptr)
virtual ~NumStrategy ()
virtual QString toRepresentedString (const QString) const =0
virtual NumerotationContext next (const NumerotationContext &, const int) const =0
virtual NumerotationContext previous (const NumerotationContext &, const int) const =0
Protected Member Functions
NumerotationContext nextString (const NumerotationContext &, const int) const
NumStrategy::nextString.
NumerotationContext nextNumber (const NumerotationContext &, const int) const
NumStrategy::nextNumber.
NumerotationContext previousNumber (const NumerotationContext &, const int) const
NumStrategy::previousNumber.
Protected Attributes
Diagram * diagram_
Detailed Description
Definition at line 47 of file numerotationcontextcommands.h.
Constructor & Destructor Documentation
NumStrategy()
NumStrategy::NumStrategy (Diagram * d = nullptr)
Constructor
Definition at line 154 of file numerotationcontextcommands.cpp.
~NumStrategy()
NumStrategy::~NumStrategy () virtual
Definition at line 158 of file numerotationcontextcommands.cpp.
Member Function Documentation
next()
virtual NumerotationContext NumStrategy::next (const NumerotationContext & , const int) const pure virtual
Implemented in ElementPrefixNum, ElementColumnNum, ElementLineNum, LocmachNum, PlantNum, FolioNum, IdFolioNum, StringNum, HundredFNum, HundredNum, TenFNum, TenNum, UnitFNum, and UnitNum.
nextNumber()
NumerotationContext NumStrategy::nextNumber (const NumerotationContext & nc, const int i) const protected
NumStrategy::nextNumber.
Returns
the next value of nc at position i
Definition at line 176 of file numerotationcontextcommands.cpp.
References NumerotationContext::addValue(), and NumerotationContext::itemAt().
Referenced by UnitNum::next(), UnitFNum::next(), TenNum::next(), TenFNum::next(), HundredNum::next(), and HundredFNum::next().
nextString()
NumerotationContext NumStrategy::nextString (const NumerotationContext & nc, const int i) const protected
NumStrategy::nextString.
Returns
the next value of nc at position i
Definition at line 164 of file numerotationcontextcommands.cpp.
References NumerotationContext::addValue(), and NumerotationContext::itemAt().
Referenced by StringNum::next(), IdFolioNum::next(), FolioNum::next(), PlantNum::next(), LocmachNum::next(), ElementLineNum::next(), ElementColumnNum::next(), ElementPrefixNum::next(), StringNum::previous(), IdFolioNum::previous(), FolioNum::previous(), PlantNum::previous(), LocmachNum::previous(), ElementLineNum::previous(), ElementColumnNum::previous(), and ElementPrefixNum::previous().
previous()
virtual NumerotationContext NumStrategy::previous (const NumerotationContext & , const int) const pure virtual
Implemented in ElementPrefixNum, ElementColumnNum, ElementLineNum, LocmachNum, PlantNum, FolioNum, IdFolioNum, StringNum, HundredFNum, HundredNum, TenFNum, TenNum, UnitFNum, and UnitNum.
previousNumber()
NumerotationContext NumStrategy::previousNumber (const NumerotationContext & nc, const int i) const protected
NumStrategy::previousNumber.
Returns
the previous value of nc at position i
Definition at line 189 of file numerotationcontextcommands.cpp.
References NumerotationContext::addValue(), and NumerotationContext::itemAt().
Referenced by UnitNum::previous(), UnitFNum::previous(), TenNum::previous(), TenFNum::previous(), HundredNum::previous(), and HundredFNum::previous().
toRepresentedString()
virtual QString NumStrategy::toRepresentedString (const QString) const pure virtual
Implemented in ElementPrefixNum, ElementColumnNum, ElementLineNum, LocmachNum, PlantNum, FolioNum, IdFolioNum, StringNum, HundredFNum, HundredNum, TenFNum, TenNum, UnitFNum, and UnitNum.
Member Data Documentation
diagram_
Diagram* NumStrategy::diagram_ protected
Definition at line 61 of file numerotationcontextcommands.h.
The documentation for this class was generated from the following files:
numerotationcontextcommands.h
numerotationcontextcommands.cpp