QElectroTech: MultiPasteDialog Class Reference
MultiPasteDialog Class Reference
#include <multipastedialog.h>
Public Member Functions
MultiPasteDialog (Diagram *diagram, QWidget *parent=nullptr)
~MultiPasteDialog ()
void updatePreview ()
Private Slots
void on_m_button_box_accepted ()
Private Attributes
Ui::MultiPasteDialog * ui
Diagram * m_diagram = nullptr
DiagramContent m_pasted_content
QPointF m_origin
QDomDocument m_document
bool m_accept = false
QList< DiagramContent > m_pasted_content_list
Detailed Description
Definition at line 31 of file multipastedialog.h.
Constructor & Destructor Documentation
MultiPasteDialog()
MultiPasteDialog::MultiPasteDialog (Diagram * diagram, QWidget * parent = nullptr) explicit
Definition at line 26 of file multipastedialog.cpp.
References QET::Icons::br, m_diagram, m_document, m_origin, Diagram::toXml(), ui, and updatePreview().
~MultiPasteDialog()
MultiPasteDialog::~MultiPasteDialog ()
Definition at line 46 of file multipastedialog.cpp.
References DiagramContent::items(), m_accept, m_diagram, m_pasted_content, Diagram::removeItem(), and ui.
Member Function Documentation
on_m_button_box_accepted
void MultiPasteDialog::on_m_button_box_accepted () private slot
Definition at line 94 of file multipastedialog.cpp.
References Diagram::adjustSceneRect(), QET::Icons::Conductor, QETProject::conductorAutoNum(), DiagramContent::count(), QETProject::elementAutoNum(), Diagram::freezeNewConductors(), QETProject::isFreezeNewConductors(), m_accept, m_diagram, m_pasted_content, m_pasted_content_list, ConductorAutoNumerotation::numerate(), autonum::numerotationContextToFormula(), Diagram::project(), QETProject::setCurrentConductorAutoNum(), QETProject::setCurrrentElementAutonum(), Conductor::setFreezeLabel(), sort(), QET::Icons::tr, ui, and Diagram::undoStack().
updatePreview()
void MultiPasteDialog::updatePreview ()
Definition at line 63 of file multipastedialog.cpp.
References Diagram::adjustSceneRect(), DiagramContent::clear(), DiagramContent::count(), Diagram::fromXml(), DiagramContent::items(), m_diagram, m_document, m_origin, m_pasted_content, m_pasted_content_list, Diagram::removeItem(), and ui.
Referenced by MultiPasteDialog().
Member Data Documentation
m_accept
bool MultiPasteDialog::m_accept = false private
Definition at line 49 of file multipastedialog.h.
Referenced by on_m_button_box_accepted(), and ~MultiPasteDialog().
m_diagram
Diagram* MultiPasteDialog::m_diagram = nullptr private
Definition at line 45 of file multipastedialog.h.
Referenced by MultiPasteDialog(), on_m_button_box_accepted(), updatePreview(), and ~MultiPasteDialog().
m_document
QDomDocument MultiPasteDialog::m_document private
Definition at line 48 of file multipastedialog.h.
Referenced by MultiPasteDialog(), and updatePreview().
m_origin
QPointF MultiPasteDialog::m_origin private
Definition at line 47 of file multipastedialog.h.
Referenced by MultiPasteDialog(), and updatePreview().
m_pasted_content
DiagramContent MultiPasteDialog::m_pasted_content private
Definition at line 46 of file multipastedialog.h.
Referenced by on_m_button_box_accepted(), updatePreview(), and ~MultiPasteDialog().
m_pasted_content_list
QList<DiagramContent> MultiPasteDialog::m_pasted_content_list private
Definition at line 50 of file multipastedialog.h.
Referenced by on_m_button_box_accepted(), and updatePreview().
ui
Ui::MultiPasteDialog* MultiPasteDialog::ui private
Definition at line 44 of file multipastedialog.h.
Referenced by MultiPasteDialog(), on_m_button_box_accepted(), updatePreview(), and ~MultiPasteDialog().
The documentation for this class was generated from the following files:
multipastedialog.h
multipastedialog.cpp